export const server = {
    notifyTitle: {
        ru: 'Подпольное производство',
        ua: 'Підпільне виробництво',
        en: 'Underground production',
        de: 'Untergrundproduktion',
        pl: 'Podziemna produkcja',
    },
    interactions: {
        enter: {
            ru: 'войти в помещение',
            ua: 'увійти до приміщення',
            en: 'enter the premises',
            de: 'die Räumlichkeiten betreten',
            pl: 'wejść do lokalu',
        },
        exit: {
            ru: 'выйти на улицу',
            ua: 'вийти на вулицю',
            en: 'go outside',
            de: 'nach draußen gehen',
            pl: 'wyjść na zewnątrz',
        },
        panel: {
            ru: 'открыть управление производством',
            ua: 'відкрити керування виробництвом',
            en: 'open production controls',
            de: 'Produktionssteuerung öffnen',
            pl: 'otworzyc zarzadzanie produkcja',
        },
    },
    supply: {
        loaded: {
            ru: 'Загружено {{cycles}} циклов сырья. Запас: {{total}} (~{{hours}} ч работы)',
            ua: 'Завантажено {{cycles}} циклів сировини. Запас: {{total}} (~{{hours}} год роботи)',
            en: 'Loaded {{cycles}} cycles of materials. Stock: {{total}} (~{{hours}} h of work)',
            de: '{{cycles}} Zyklen Rohstoff geladen. Vorrat: {{total}} (~{{hours}} Std. Arbeit)',
            pl: 'Zaladowano {{cycles}} cykli surowca. Zapas: {{total}} (~{{hours}} h pracy)',
        },
        alreadyFull: {
            ru: 'Линия уже заправлена полностью',
            ua: 'Лінія вже заправлена повністю',
            en: 'The line is already fully loaded',
            de: 'Die Linie ist bereits voll beladen',
            pl: 'Linia jest juz w pelni zaladowana',
        },
        switched: {
            ru: 'Линия переведена на производство: {{item}}',
            ua: 'Лінію переведено на виробництво: {{item}}',
            en: 'The line has been switched to: {{item}}',
            de: 'Die Linie wurde umgestellt auf: {{item}}',
            pl: 'Linia zostala przestawiona na: {{item}}',
        },
        switchedRefund: {
            ru: 'Линия переведена на производство: {{item}}. На склад возвращено сырьё {{cycles}} циклов',
            ua: 'Лінію переведено на виробництво: {{item}}. На склад повернуто сировину {{cycles}} циклів',
            en: 'The line has been switched to: {{item}}. Materials for {{cycles}} cycles returned to the warehouse',
            de: 'Die Linie wurde umgestellt auf: {{item}}. Rohstoff für {{cycles}} Zyklen ging ins Lager zurück',
            pl: 'Linia zostala przestawiona na: {{item}}. Surowiec na {{cycles}} cykli wrocil do magazynu',
        },
    },
    errors: {
        noOrganization: {
            ru: 'Вы не состоите в организации',
            ua: 'Ви не перебуваєте в організації',
            en: 'You are not a member of an organization',
            de: 'Du bist in keiner Organisation',
            pl: 'Nie należysz do organizacji',
        },
        notCaptured: {
            ru: 'Территория этого бизнеса никем не захвачена',
            ua: 'Територія цього бізнесу ніким не захоплена',
            en: 'Nobody controls the territory of this business',
            de: 'Das Gebiet dieses Geschäfts gehört niemandem',
            pl: 'Terytorium tego biznesu nie jest przez nikogo przejęte',
        },
        otherOrg: {
            ru: 'Территорией этого бизнеса владеет организация {{org}}',
            ua: 'Територією цього бізнесу володіє організація {{org}}',
            en: 'The territory of this business belongs to {{org}}',
            de: 'Das Gebiet dieses Geschäfts gehört der Organisation {{org}}',
            pl: 'Terytorium tego biznesu należy do organizacji {{org}}',
        },
        noCell: {
            ru: 'Этот бизнес не привязан к территории',
            ua: 'Цей бізнес не прив’язаний до території',
            en: 'This business is not linked to a territory',
            de: 'Dieses Geschäft ist keinem Gebiet zugeordnet',
            pl: 'Ten biznes nie jest powiązany z terytorium',
        },
        refundNoSpace: {
            ru: 'На складе нет места под сырьё, которое вернётся с линии',
            ua: 'На складі немає місця під сировину, яка повернеться з лінії',
            en: 'The warehouse has no room for the materials coming back from the line',
            de: 'Im Lager ist kein Platz für den Rohstoff, der von der Linie zurückkommt',
            pl: 'W magazynie nie ma miejsca na surowiec wracajacy z linii',
        },
        noWarehouse: {
            ru: 'У вашей организации нет склада',
            ua: 'У вашої організації немає складу',
            en: 'Your organization has no warehouse',
            de: 'Deine Organisation hat kein Lager',
            pl: 'Twoja organizacja nie ma magazynu',
        },
        noMaterials: {
            ru: 'На складе организации нет полного набора сырья',
            ua: 'На складі організації немає повного набору сировини',
            en: 'The organization warehouse has no complete set of materials',
            de: 'Im Lager der Organisation fehlt ein vollständiger Rohstoffsatz',
            pl: 'W magazynie organizacji brakuje pelnego zestawu surowca',
        },
        lostControl: {
            ru: 'Ваша организация потеряла контроль над территорией этого бизнеса',
            ua: 'Ваша організація втратила контроль над територією цього бізнесу',
            en: 'Your organization has lost control of this business territory',
            de: 'Deine Organisation hat die Kontrolle über dieses Gebiet verloren',
            pl: 'Twoja organizacja straciła kontrolę nad terytorium tego biznesu',
        },
        weaponsBlocked: {
            ru: 'В помещении нельзя брать оружие в руки',
            ua: 'У приміщенні не можна брати зброю до рук',
            en: 'Weapons cannot be drawn inside the premises',
            de: 'In den Räumlichkeiten dürfen keine Waffen gezogen werden',
            pl: 'W lokalu nie można wyciągać broni',
        },
    },
};
