export const hairs = {
    male: {
        bald: {
            ru: 'Лысый',
            ua: 'Лисий',
            en: 'Bald',
            de: 'Glatze',
            pl: 'Łysy',
        },
        shortHair: {
            ru: 'Короткая стрижка',
            ua: 'Коротка стрижка',
            en: 'Short haircut',
            de: 'Kurzer Haarschnitt',
            pl: 'Krótkie cięcie',
        },
        fauxHawk: {
            ru: 'Фок-хок (ложный ирокез)',
            ua: 'Фоксхок (фальш-ірокез)',
            en: 'Faux hawk',
            de: 'Fauxhawk (falscher Irokesenschnitt)',
            pl: 'Faux hawk (fałszywy irokez)',
        },
        hipsterShaved: {
            ru: 'Хипстерская с выбритыми висками',
            ua: 'Хіпстерська з поголеними скронями',
            en: 'Hipster cut with shaved sides',
            de: 'Hipster mit rasierten Seiten',
            pl: 'Hipsterskie, wygolone boki',
        },
        sideSweptPompadour: {
            ru: 'Помпадур, зачесанный набок',
            ua: 'Помпадур, зачесаний набік',
            en: 'Side-swept pompadour',
            de: 'Seitlich gekämmter Pompadour',
            pl: 'Pompadour zaczesany na bok',
        },
        shorterHaircut: {
            ru: 'Более короткая стрижка',
            ua: 'Коротша стрижка',
            en: 'Shorter haircut',
            de: 'Kürzerer Haarschnitt',
            pl: 'Krótsza fryzura',
        },
        biker: {
            ru: 'Байкерская',
            ua: 'Байкерський стиль',
            en: 'Biker style',
            de: 'Biker-Style',
            pl: 'Styl biker',
        },
        ponytail: {
            ru: 'Конский хвост',
            ua: 'Кінський хвіст',
            en: 'Ponytail',
            de: 'Pferdeschwanz',
            pl: 'Kucyk',
        },
        afroBraids: {
            ru: 'Афрокосы',
            ua: 'Афрокоси',
            en: 'Afro braids',
            de: 'Afro-Zöpfe',
            pl: 'Warkoczyki afro',
        },
        slickedBack: {
            ru: 'Зализанные назад',
            ua: 'Зализане назад',
            en: 'Slicked back',
            de: 'Nach hinten gegelt',
            pl: 'Zalizane do tyłu',
        },
        shortSpike: {
            ru: 'Короткий ёжик',
            ua: 'Короткий їжачок',
            en: 'Short spiky',
            de: 'Kurze Spikes',
            pl: 'Krótki jeżyk',
        },
        spikyHair: {
            ru: 'Торчащие волосы',
            ua: 'Колюча укладка',
            en: 'Spiky hair',
            de: 'Stachelige Haare',
            pl: 'Kolczaste włosy',
        },
        caesar: {
            ru: 'Цезарь',
            ua: 'Цезар',
            en: 'Caesar',
            de: 'Caesar-Schnitt',
            pl: 'Fryzura Caesar',
        },
        parted: {
            ru: 'С пробором',
            ua: 'З проділом',
            en: 'Parted',
            de: 'Mit Scheitel',
            pl: 'Z przedziałkiem',
        },
        dreadlocks: {
            ru: 'Дреды',
            ua: 'Дреди',
            en: 'Dreadlocks',
            de: 'Dreadlocks',
            pl: 'Dredy',
        },
        longHair: {
            ru: 'Длинные волосы',
            ua: 'Довге волосся',
            en: 'Long hair',
            de: 'Lange Haare',
            pl: 'Długie włosy',
        },
        fluffyCurls: {
            ru: 'Пышные кудри',
            ua: 'Пухнасті кучері',
            en: 'Fluffy curls',
            de: 'Flauschige Locken',
            pl: 'Puszyste loki',
        },
        surferStyle: {
            ru: 'Сёрферский стиль',
            ua: 'Серферський стиль',
            en: 'Surfer style',
            de: 'Surfer-Style',
            pl: 'Styl surfer',
        },
        shortSidePart: {
            ru: 'Короткий боковой пробор',
            ua: 'Короткий бічний проділ',
            en: 'Short side part',
            de: 'Kurzer Seitenscheitel',
            pl: 'Krótki boczny przedziałek',
        },
        highShavedSides: {
            ru: 'Высоко выбритые бока',
            ua: 'Високо виголені боки',
            en: 'High shaved sides',
            de: 'Hoch ausrasierte Seiten',
            pl: 'Wysoko wygolone boki',
        },
        longShaved: {
            ru: 'Длинные волосы с выбритыми боками',
            ua: 'Довге волосся з виголеними боками',
            en: 'Long hair with shaved sides',
            de: 'Langhaar mit rasierten Seiten',
            pl: 'Długie włosy z wygolonymi bokami',
        },
        youngHipster: {
            ru: 'Молодёжный хипстер',
            ua: 'Молодіжний хіпстер',
            en: 'Young hipster',
            de: 'Junger Hipster',
            pl: 'Młody hipster',
        },
        toddler: {
            ru: 'Малютка',
            ua: 'Малюк',
            en: 'Toddler',
            de: 'Kleinkind',
            pl: 'Maluch',
        },
        classicAfroBraids: {
            ru: 'Классические афрокосы',
            ua: 'Класичні афрокоси',
            en: 'Classic afro braids',
            de: 'Klassische Afro-Zöpfe',
            pl: 'Klasyczne warkoczyki afro',
        },
        palmTreeAfroBraids: {
            ru: 'Афрокосы «пальма»',
            ua: 'Афрокоси «пальма»',
            en: 'Palm-tree afro braids',
            de: 'Palmen-Afro-Zöpfe',
            pl: 'Afro w stylu palma',
        },
        lightningAfroBraids: {
            ru: 'Афрокосы «молния»',
            ua: 'Афрокоси «блискавка»',
            en: 'Lightning afro braids',
            de: 'Blitz-Afro-Zöpfe',
            pl: 'Afro w stylu błyskawica',
        },
        whippedAfroBraids: {
            ru: 'Закрученные афрокосы',
            ua: 'Закручені афрокоси',
            en: 'Twisted afro braids',
            de: 'Gedrehte Afro-Zöpfe',
            pl: 'Skręcone warkoczyki afro',
        },
        zigzagAfroBraids: {
            ru: 'Афрокосы «зигзаг»',
            ua: 'Афрокоси «зигзаг»',
            en: 'Zigzag afro braids',
            de: 'Zickzack-Afro-Zöpfe',
            pl: 'Afro zygzak',
        },
        snailAfroBraids: {
            ru: 'Афрокосы «улитка»',
            ua: 'Афрокоси «равлик»',
            en: 'Snail afro braids',
            de: 'Schnecken-Afro-Zöpfe',
            pl: 'Afro ślimak',
        },
        hightop: {
            ru: 'Хайтоп',
            ua: 'Хай-топ',
            en: 'High top',
            de: 'High-Top',
            pl: 'High top',
        },
        casuallySweptBack: {
            ru: 'Небрежно зачесанные назад',
            ua: 'Недбало зачесане назад',
            en: 'Casually swept back',
            de: 'Locker nach hinten gekämmt',
            pl: 'Niedbale zaczesane do tyłu',
        },
        furryTrimmed: {
            ru: 'Пушистые, подстриженные',
            ua: 'Пухнаста, підстрижена',
            en: 'Fluffy, trimmed',
            de: 'Flauschig, getrimmt',
            pl: 'Puszyste, podcięte',
        },
        casuallySweptToSide: {
            ru: 'Небрежно зачесанные набок',
            ua: 'Недбало зачесане набік',
            en: 'Casually swept to the side',
            de: 'Locker zur Seite gekämmt',
            pl: 'Niedbale na bok',
        },
        spikyMohawk: {
            ru: 'Шипастый ирокез',
            ua: 'Шипастий ірокез',
            en: 'Spiky mohawk',
            de: 'Stacheliger Irokesenschnitt',
            pl: 'Kolczasty irokez',
        },
        trendy: {
            ru: 'Модный',
            ua: 'Модний',
            en: 'Trendy',
            de: 'Trendig',
            pl: 'Modny',
        },
        grunge: {
            ru: 'Гранж',
            ua: 'Гранж',
            en: 'Grunge',
            de: 'Grunge',
            pl: 'Grunge',
        },
        military_classic: {
            ru: 'Армейская классика',
            ua: 'Військова класика',
            en: 'Military classic',
            de: 'Militärklassiker',
            pl: 'Klasyka wojskowa',
        },
        rockabilly: {
            ru: 'Рокабилли',
            ua: 'Рокабілі',
            en: 'Rockabilly',
            de: 'Rockabilly',
            pl: 'Rockabilly',
        },
        flattop: {
            ru: 'Флэттоп',
            ua: 'Флеттоп',
            en: 'Flattop',
            de: 'Flattop',
            pl: 'Flattop',
        },
        sabotage: {
            ru: 'Саботаж',
            ua: 'Саботаж',
            en: 'Sabotage',
            de: 'Sabotage',
            pl: 'Sabotage',
        },
        wet_style: {
            ru: 'Мокрый стиль',
            ua: 'Вологий стиль',
            en: 'Wet style',
            de: 'Wet-Look',
            pl: 'Mokry look',
        },
        rocker: {
            ru: 'Рокер',
            ua: 'Рокер',
            en: 'Rocker',
            de: 'Rocker',
            pl: 'Rocker',
        },
        fade_curl: {
            ru: 'Фейд с кудрями',
            ua: 'Фейд із кучерями',
            en: 'Fade with curls',
            de: 'Fade mit Locken',
            pl: 'Fade z lokami',
        },
        curtains: {
            ru: '«Шторки»',
            ua: '«Шторки»',
            en: 'Curtains',
            de: 'Curtains-Frisur',
            pl: 'Fryzura „firanki”',
        },
        street_braids: {
            ru: 'Уличные косы',
            ua: 'Вуличні коси',
            en: 'Street braids',
            de: 'Street-Braids',
            pl: 'Uliczne warkocze',
        },
        wanderer_xxl: {
            ru: 'Бродяга XXL',
            ua: 'Мандрівник XXL',
            en: 'Wanderer XXL',
            de: 'Wanderer XXL',
            pl: 'Wędrowiec XXL',
        },
        philosopher: {
            ru: 'Философ',
            ua: 'Філософ',
            en: 'Philosopher',
            de: 'Philosoph',
            pl: 'Filozof',
        },
        sadMonk: {
            ru: 'Печальный монах',
            ua: 'Сумний монах',
            en: 'Sad monk',
            de: 'Trauriger Mönch',
            pl: 'Smutny mnich',
        },
        afroBall: {
            ru: 'Афро-шар',
            ua: 'Афро-куля',
            en: 'Afro ball',
            de: 'Afro-Ball',
            pl: 'Afro-kula',
        },
        backToBusiness: {
            ru: 'Назад к делу',
            ua: 'Назад до справ',
            en: 'Back to business',
            de: 'Zurück ins Business',
            pl: 'Back to business',
        },
        officePredator: {
            ru: 'Офисный хищник',
            ua: 'Офісний хижак',
            en: 'Office predator',
            de: 'Büro-Raubtier',
            pl: 'Drapieżnik biurowy',
        },
        samurai: {
            ru: 'Самурай',
            ua: 'Самурай',
            en: 'Samurai',
            de: 'Samurai (Topknot)',
            pl: 'Samuraj',
        },
        justWokeUp: {
            ru: 'Проснулся и пошёл',
            ua: 'Прокинувся й пішов',
            en: 'Just woke up',
            de: 'Gerade aufgewacht',
            pl: 'Wstałeś i wyszedłeś',
        },
        dreadFall: {
            ru: 'Падающие дреды',
            ua: 'Падіння дредів',
            en: 'Dreadfall',
            de: 'Dreadfall',
            pl: 'Dreadfall',
        },
        banditBand: {
            ru: 'Бандит с повязкой',
            ua: 'Бандит із пов’язкою',
            en: 'Bandit with headband',
            de: 'Bandit mit Stirnband',
            pl: 'Bandyta z opaską',
        },
        dreadCrown: {
            ru: 'Корона из дредов',
            ua: 'Корона з дредів',
            en: 'Dread crown',
            de: 'Dread-Krone',
            pl: 'Korona z dredów',
        },
        curlyUp: {
            ru: 'Кудри вверх',
            ua: 'Кучері вгору',
            en: 'Curls up',
            de: 'Locken nach oben',
            pl: 'Loki ku górze',
        },
        tinyCurls: {
            ru: 'Мелкие кудри',
            ua: 'Дрібні кучері',
            en: 'Tiny curls',
            de: 'Kleine Locken',
            pl: 'Drobne loczki',
        },
        sportClassic: {
            ru: 'Спортивная классика',
            ua: 'Спортивна класика',
            en: 'Sport classic',
            de: 'Sport-Klassik',
            pl: 'Klasyka sportowa',
        },
        highCube: {
            ru: 'Высокий бокс',
            ua: 'Високий бокс',
            en: 'High box',
            de: 'High Box',
            pl: 'Wysoki box',
        },
        dreadBun: {
            ru: 'Дред-пучок',
            ua: 'Пучок із дредів',
            en: 'Dread bun',
            de: 'Dread-Dutt',
            pl: 'Kok z dredów',
        },
        spikeDread: {
            ru: 'Ёж-дред',
            ua: 'Їжак-дред',
            en: 'Spiky dread',
            de: 'Stachel-Dread',
            pl: 'Dred-kolec',
        },
        giantDread: {
            ru: 'Дред-гигант',
            ua: 'Гігантський дред',
            en: 'Giant dread',
            de: 'Riesen-Dread',
            pl: 'Ogromny dred',
        },
        braidDread: {
            ru: 'Заплетённый дред',
            ua: 'Заплетений дред',
            en: 'Braided dread',
            de: 'Geflochtener Dread',
            pl: 'Zaplatany dred',
        },
        dreadTail: {
            ru: 'Дред-хвост',
            ua: 'Хвіст із дредів',
            en: 'Dread tail',
            de: 'Dread-Schwanz',
            pl: 'Ogonek z dredów',
        },
        twistUp: {
            ru: 'Твисты вверх',
            ua: 'Твісти вгору',
            en: 'Twist up',
            de: 'Twist nach oben',
            pl: 'Twisty do góry',
        },
        palmTree: {
            ru: 'Пальма',
            ua: 'Пальма',
            en: 'Palm tree',
            de: 'Palme',
            pl: 'Palma',
        },
        punkSpike: {
            ru: 'Панковский шип',
            ua: 'Панківський шип',
            en: 'Punk spike',
            de: 'Punk-Stachel',
            pl: 'Punkowy kolec',
        },
        urbanFade: {
            ru: 'Городской фейд',
            ua: 'Міський фейд',
            en: 'Urban fade',
            de: 'Urban Fade',
            pl: 'Miejski fade',
        },
        voluminousCurls: {
            ru: 'Пышные кудри',
            ua: 'Об’ємні кучері',
            en: 'Voluminous curls',
            de: 'Voluminöse Locken',
            pl: 'Bujne loki',
        },
        slickBack: {
            ru: 'Зализанные назад',
            ua: 'Зализане назад',
            en: 'Slick back',
            de: 'Nach hinten gegelt',
            pl: 'Zalizane do tyłu',
        },
        dreadTail2: {
            ru: 'Дред-хвост 2.0',
            ua: 'Хвіст із дредів 2.0',
            en: 'Dread tail 2.0',
            de: 'Dread-Schwanz 2.0',
            pl: 'Ogonek z dredów 2.0',
        },
        casualHome: {
            ru: 'Домашний стиль',
            ua: 'Домашній стиль',
            en: 'Casual home style',
            de: 'Home-Casual',
            pl: 'Domowy luz',
        },
        windyLook: {
            ru: 'Растрепанный ветром',
            ua: 'Злегка розтріпаний',
            en: 'Windblown',
            de: 'Verweht',
            pl: 'Potargany przez wiatr',
        },
        leafHead: {
            ru: 'Листья на голове',
            ua: 'Листя на голові',
            en: 'Leaves on head',
            de: 'Blätter auf dem Kopf',
            pl: 'Liście na głowie',
        },
        frostStroke: {
            ru: 'Ледяной штрих',
            ua: 'Крижаний штрих',
            en: 'Frost stroke',
            de: 'Frost-Strich',
            pl: 'Lodowy akcent',
        },
        freeDreads: {
            ru: 'Свободные дреды',
            ua: 'Вільні дреди',
            en: 'Free dreads',
            de: 'Freie Dreads',
            pl: 'Luźne dredy',
        },
        afroBraids2: {
            ru: 'Афрокосы',
            ua: 'Афрокоси',
            en: 'Afro braids',
            de: 'Afro-Zöpfe',
            pl: 'Warkoczyki afro',
        },
        mushroomCut: {
            ru: 'Грибок',
            ua: 'Грибок',
            en: 'Mushroom cut',
            de: 'Pilzschnitt',
            pl: 'Grzybek',
        },
        salonStyle: {
            ru: 'Салонный стиль',
            ua: 'Салонний стиль',
            en: 'Salon style',
            de: 'Salon-Style',
            pl: 'Styl salonowy',
        },
        samurai2: {
            ru: 'Самурай 2.0',
            ua: 'Самурай 2.0',
            en: 'Samurai 2.0',
            de: 'Samurai 2.0',
            pl: 'Samuraj 2.0',
        },
        machineCut: {
            ru: 'Под машинку',
            ua: 'Під машинку',
            en: 'Buzz cut',
            de: 'Maschinenschnitt',
            pl: 'Na maszynkę',
        },
        thickDreads: {
            ru: 'Толстые дреды',
            ua: 'Товсті дреди',
            en: 'Thick dreads',
            de: 'Dicke Dreads',
            pl: 'Grube dredy',
        },
        shortDreads: {
            ru: 'Короткие дреды',
            ua: 'Короткі дреди',
            en: 'Short dreads',
            de: 'Kurze Dreads',
            pl: 'Krótkie dredy',
        },
        longBob: {
            ru: 'Длинное каре',
            ua: 'Довге каре',
            en: 'Long bob',
            de: 'Langer Bob',
            pl: 'Długi bob',
        },
        messyMedium: {
            ru: 'Небрежная средняя длина',
            ua: 'Недбала середня довжина',
            en: 'Messy medium length',
            de: 'Mittellang, messy',
            pl: 'Średnia długość, messy',
        },
        undercutVolume: {
            ru: 'Андеркат с объёмом',
            ua: 'Андеркот з об’ємом',
            en: 'Undercut with volume',
            de: 'Undercut mit Volumen',
            pl: 'Undercut z objętością',
        },
        sideUndercut: {
            ru: 'Боковой андеркат',
            ua: 'Бічний андеркот',
            en: 'Side undercut',
            de: 'Seitlicher Undercut',
            pl: 'Boczny undercut',
        },
        classicVolume: {
            ru: 'Классика с объёмом',
            ua: 'Класика з об’ємом',
            en: 'Classic with volume',
            de: 'Klassik mit Volumen',
            pl: 'Klasyka z objętością',
        },
        trendyMess: {
            ru: 'Модный хаос',
            ua: 'Модний хаос',
            en: 'Trendy mess',
            de: 'Trendiges Chaos',
            pl: 'Modny nieład',
        },
        middlePart: {
            ru: 'Центральный пробор',
            ua: 'Середній проділ',
            en: 'Middle part',
            de: 'Mittelscheitel',
            pl: 'Przedziałek na środku',
        },
        straightBob: {
            ru: 'Прямое каре',
            ua: 'Пряме каре',
            en: 'Straight bob',
            de: 'Gerader Bob',
            pl: 'Prosty bob',
        },
        wavyFlow: {
            ru: 'Волнистая укладка',
            ua: 'Хвиляста укладка',
            en: 'Wavy styling',
            de: 'Welliges Styling',
            pl: 'Falowana stylizacja',
        },
        mushroomCut2: {
            ru: 'Грибок',
            ua: 'Грибок',
            en: 'Mushroom cut',
            de: 'Pilzschnitt',
            pl: 'Grzybek',
        },
        dreadBun2: {
            ru: 'Дреды в пучок',
            ua: 'Дреди в пучок',
            en: 'Dreads in a bun',
            de: 'Dreads zum Dutt',
            pl: 'Dredy w koku',
        },
        pineappleDreads: {
            ru: 'Ананас из дредов',
            ua: 'Дреди «ананас»',
            en: 'Pineapple dreads',
            de: 'Ananas-Dreads',
            pl: 'Dredy „ananas”',
        },
        slickBack2: {
            ru: 'Зализанные назад',
            ua: 'Зализане назад',
            en: 'Slicked back',
            de: 'Nach hinten gegelt',
            pl: 'Zalizane do tyłu',
        },
        lowBun: {
            ru: 'Низкий пучок',
            ua: 'Низький пучок',
            en: 'Low bun',
            de: 'Tiefer Dutt',
            pl: 'Niski kok',
        },
        longWavy: {
            ru: 'Длинные волнистые волосы',
            ua: 'Довге хвилясте волосся',
            en: 'Long wavy hair',
            de: 'Lange, wellige Haare',
            pl: 'Długie falowane włosy',
        },
        messyFringe: {
            ru: 'Небрежная чёлка',
            ua: 'Недбала чолка',
            en: 'Messy fringe',
            de: 'Messy-Pony',
            pl: 'Niedbana grzywka',
        },
    },
    female: {
        bald: {
            ua: 'Лиса',
            en: 'Bald',
            ru: 'Лысая',
            de: 'Glatze',
            pl: 'Łysy',
            zh: '秃头',
        },

        shortHaircut: {
            ua: 'Коротка стрижка',
            en: 'Short Haircut',
            ru: 'Короткая стрижка',
            de: 'Kurzhaarschnitt',
            pl: 'Krótka fryzura',
            zh: '短发',
        },

        layeredBob: {
            ua: 'Сходящийся боб',
            en: 'Layered Bob',
            ru: 'Ступенчатый боб',
            de: 'Stufiger Bob',
            pl: 'Warstwowy bob',
            zh: '分层发型',
        },

        braids: {
            ua: 'Косички',
            en: 'Braids',
            ru: 'Косички',
            de: 'Flechten',
            pl: 'Warkocze',
            zh: '麻花辫',
        },

        bun: {
            ua: 'Кок',
            en: 'Bun',
            ru: 'Пучок',
            de: 'Dutt',
            pl: 'Kok',
            zh: '圆发型',
        },

        slantingMohawk: {
            ua: 'Нахилений мохок',
            en: 'Slanting Mohawk',
            ru: 'Косой мохок',
            de: 'Schräger Irokesenschnitt',
            pl: 'Pochylony irokez',
            zh: '倾斜的莫霍克',
        },

        bob: {
            ua: 'Боб',
            en: 'Bob',
            ru: 'Боб',
            de: 'Bob',
            pl: 'Bob',
            zh: 'Bob',
        },

        pinnedBow: {
            ua: 'Приколотий бант',
            en: 'Pinned Bow',
            ru: 'Приколотый бант',
            de: 'Angesteckte Schleife',
            pl: 'Przypięty kokard',
            zh: '梳理发型',
        },

        longBob: {
            ua: 'Довгий боб',
            en: 'Long Bob',
            ru: 'Длинный боб',
            de: 'Langer Bob',
            pl: 'Długi bob',
            zh: '长发bob',
        },

        pixie: {
            ua: 'Піксі',
            en: 'Pixie',
            ru: 'Пикси',
            de: 'Pixie-Schnitt',
            pl: 'Pixie',
            zh: '精灵发型',
        },

        sidePartedHair: {
            ua: 'Волосся розділені на бік',
            en: 'Side Parted Hair',
            ru: 'Разделенные волосы на бок',
            de: 'Seitlich geteiltes Haar',
            pl: 'Włosy z przedziałkiem na bok',
            zh: '侧分头发',
        },

        wavyBob: {
            ua: 'Боб хвилястий',
            en: 'Wavy Bob',
            ru: 'Волновой боб',
            de: 'Gewellter Bob',
            pl: 'Falowany bob',
            zh: '波浪头',
        },

        pinUpHairdo: {
            ua: 'Зачіска в стилі Pin Up',
            en: 'Pin Up Hairdo',
            ru: 'Стрижка в стиле Pin Up',
            de: 'Pin Up Frisur',
            pl: 'Fryzura pin-up',
            zh: '别针式发型',
        },

        messyBun: {
            ua: 'Нерівний кок',
            en: 'Messy Bun',
            ru: 'Небрежный пучок',
            de: 'Unordentlicher Dutt',
            pl: 'Niezgrabny kok',
            zh: '凌乱丸子头',
        },

        tightBun: {
            ua: 'Тугий кок',
            en: 'Tight Bun',
            ru: 'Тугой пучок',
            de: 'Enger Dutt',
            pl: 'Ciasny kok',
            zh: '紧束发髻',
        },

        braidedBob: {
            ua: 'Заплетений боб',
            en: 'Braided Bob',
            ru: 'Заплетенный боб',
            de: 'Geflochtener Bob',
            pl: 'Zaplatany bob',
            zh: '编织发型',
        },

        bigBangs: {
            ua: 'Великі чубчики',
            en: 'Big Bangs',
            ru: 'Большие челки',
            de: 'Großer Pony',
            pl: 'Duże grzywki',
            zh: '爆炸头',
        },

        braidedBun: {
            ua: 'Заплетений кок',
            en: 'Braided Bun',
            ru: 'Заплетенный пучок',
            de: 'Geflochtener Dutt',
            pl: 'Zaplatany kok',
            zh: '凌乱辫子发簪',
        },

        baby: {
            ua: 'Дитинка',
            en: 'Baby',
            ru: 'Малютка',
            de: 'Baby',
            pl: 'Dziecko',
            zh: '婴儿发型',
        },

        wavyBraids: {
            ua: 'Волнисті косички',
            en: 'Wavy Braids',
            ru: 'Волновые косички',
            de: 'Gewellte Zöpfe',
            pl: 'Falowane warkocze',
            zh: '波浪的辫子',
        },

        spiralBraids: {
            ua: 'Спіральні косички',
            en: 'Spiral Braids',
            ru: 'Спиральные косички',
            de: 'Spiralzöpfe',
            pl: 'Spiralne warkocze',
            zh: '螺旋的辫子',
        },

        combedQuiff: {
            ua: 'Заправлений квифф',
            en: 'Combed Quiff',
            ru: 'Заправленный квифф',
            de: 'Gekämmter Quiff',
            pl: 'Czesany kufr',
            zh: '梳理发型',
        },

        wavyBangs: {
            ua: 'Волнисті чубчики',
            en: 'Wavy Bangs',
            ru: 'Волнистые челки',
            de: 'Gewellter Pony',
            pl: 'Falowane grzywki',
            zh: '波浪的刘海',
        },

        slickedBackHair: {
            ua: 'Прибрані волосся назад',
            en: 'Slicked Back Hair',
            ru: 'Отложенные волосы назад',
            de: 'Gekämmte zurückgestrichene Haare',
            pl: 'Wysmarowane do tyłu włosy',
            zh: '大背头',
        },

        shortBack: {
            ua: 'Коротка на спині',
            en: 'Short Back',
            ru: 'Короткая назад',
            de: 'Kurze Rückseite',
            pl: 'Krótki tył',
            zh: '短黑发',
        },

        shortSide: {
            ua: 'Коротка на бік',
            en: 'Short Side',
            ru: 'Короткая на бок',
            de: 'Kurze Seite',
            pl: 'Krótka strona',
            zh: '男士发型',
        },

        mohawk: {
            ua: 'Ірокез',
            en: 'Mohawk',
            ru: 'Ирокез',
            de: 'Irokesenschnitt',
            pl: 'Irokez',
            zh: '莫西干',
        },

        braidedHair: {
            ua: 'Косички',
            en: 'Braids',
            ru: 'Косички',
            de: 'Flechten',
            pl: 'Warkocze',
            zh: '辫子',
        },

        oneEye: {
            ua: 'Одне око',
            en: 'One Eye',
            ru: 'Один глаз',
            de: 'Ein Auge',
            pl: 'Jedno oko',
            zh: '独眼龙',
        },

        longSide: {
            ua: 'Довгі на бік',
            en: 'Long Side',
            ru: 'Длинные на бок',
            de: 'Lange Seite',
            pl: 'Długa strona',
            zh: '长发',
        },

        longOtherSide: {
            ua: 'Довгі на інший бік',
            en: 'Long Other Side',
            ru: 'Длинные на другой бок',
            de: 'Lange andere Seite',
            pl: 'Długa inna strona',
            zh: '长长的另一边',
        },

        bigBraid: {
            ua: 'Велика косичка',
            en: 'Big Braid',
            ru: 'Большая косичка',
            de: 'Große Flechte',
            pl: 'Duży warkocz',
            zh: '大辫子',
        },

        longHair: {
            ua: 'Довгі волосся',
            en: 'Long Hair',
            ru: 'Длинные',
            de: 'Langes Haar',
            pl: 'Długie włosy',
            zh: '长发',
        },

        dreadlocks: {
            ua: 'Дреди',
            en: 'Dreadlocks',
            ru: 'Дреды',
            de: 'Dreadlocks',
            pl: 'Dredy',
            zh: '长发绺',
        },

        messy: {
            ua: 'Хаотична',
            en: 'Messy',
            ru: 'Хаотичная',
            de: 'Unordentlich',
            pl: 'Zabałaganiona',
            zh: '脏辫',
        },

        mediumHair: {
            ua: 'Півдовгі волосся',
            en: 'Medium Hair',
            ru: 'Полу длинная',
            de: 'Mittellanges Haar',
            pl: 'Średnie włosy',
            zh: '中长发',
        },

        bigTail: {
            ua: 'Великий хвіст',
            en: 'Big Tail',
            ru: 'Большой хвост',
            de: 'Großer Pferdeschwanz',
            pl: 'Duży kucyk',
            zh: '大头发',
        },

        longStraight: {
            ua: 'Довгі прямі',
            en: 'Long Straight',
            ru: 'Длинные прямые',
            de: 'Lange Gerade',
            pl: 'Długie proste',
            zh: '长直发',
        },

        longOther: {
            ua: 'Довгі',
            en: 'Long Other',
            ru: 'Длинные',
            de: 'Lange andere',
            pl: 'Długie inne',
            zh: '长发',
        },

        esbuild: {
            ua: 'Есбілд',
            en: 'Esbuild',
            ru: 'Есбилд',
            de: 'Esbuild',
            pl: 'Esbuild',
            zh: '发型1',
        },

        shortOtherSide: {
            ua: 'Коротка на інший бік',
            en: 'Short Other Side',
            ru: 'Короткая на бок',
            de: 'Kurze andere Seite',
            pl: 'Krótka inna strona',
            zh: '一边短发型',
        },

        harleyQuinn: {
            ua: 'Харлі Квінн',
            en: 'Harley Quinn',
            ru: 'Харли Квинн',
            de: 'Harley Quinn',
            pl: 'Harley Quinn',
            zh: '哈莉奎因',
        },

        bombBack: {
            ua: 'Бомба назад',
            en: 'Bomb Back',
            ru: 'Бомба сзади',
            de: 'Bombe zurück',
            pl: 'Bombowy tył',
            zh: '爆炸头',
        },

        abobus: {
            ua: 'Абобусна',
            en: 'Abobus',
            ru: 'Абобусная',
            de: 'Abobus',
            pl: 'Abobus',
            zh: '发型',
        },
    },
};
