export default {
    green: {
        ua: 'Зелений',
        en: 'Green',
        ru: 'Зелёный',
        de: 'Grün',
        pl: 'Zielony',
        zh: '绿色',
    },
    emerald: {
        ua: 'Смарагдовий',
        en: 'Emerald',
        ru: 'Изумрудный',
        de: 'Smaragd',
        pl: 'Szmaragdowy',
        zh: '翡翠色',
    },
    blue: {
        ua: 'Блакитний',
        en: 'Blue',
        ru: 'Голубой',
        de: 'Blau',
        pl: 'Niebieski',
        zh: '蓝色',
    },
    dark_blue: {
        ua: 'Темно-синій',
        en: 'Dark Blue',
        ru: 'Синий',
        de: 'Dunkelblau',
        pl: 'Ciemnoniebieski',
        zh: '深蓝色',
    },
    light_brown: {
        ua: 'Світлий шатен',
        en: 'Light Brown',
        ru: 'Светлый шатен',
        de: 'Hellbraun',
        pl: 'Jasny brąz',
        zh: '浅棕色',
    },
    dark_brown: {
        ua: 'Темно-коричневий',
        en: 'Dark Brown',
        ru: 'Темно-коричневый',
        de: 'Dunkelbraun',
        pl: 'Ciemnobrązowy',
        zh: '深棕色',
    },
    hazel: {
        ua: 'Карий',
        en: 'Hazel',
        ru: 'Карий',
        de: 'Haselnuss',
        pl: 'Orzechowy',
        zh: '淡褐色',
    },
    dark_gray: {
        ua: 'Темно-сірий',
        en: 'Dark Gray',
        ru: 'Темно-серый',
        de: 'Dunkelgrau',
        pl: 'Ciemnoszary',
        zh: '深灰色',
    },
    light_gray: {
        ua: 'Світло-сірий',
        en: 'Light Gray',
        ru: 'Светло-серый',
        de: 'Hellgrau',
        pl: 'Jasnoszary',
        zh: '浅灰色',
    },
    pink: {
        ua: 'Рожевий',
        en: 'Pink',
        ru: 'Розовый',
        de: 'Rosa',
        pl: 'Różowy',
        zh: '粉色',
    },
    yellow: {
        ua: 'Жовтий',
        en: 'Yellow',
        ru: 'Желтый',
        de: 'Gelb',
        pl: 'Żółty',
        zh: '黄色',
    },
    violet: {
        ua: 'Фіолетовий',
        en: 'Violet',
        ru: 'Фиолетовый',
        de: 'Violett',
        pl: 'Fioletowy',
        zh: '紫色',
    },
    shade: {
        ua: 'Затемнення',
        en: 'Shade',
        ru: 'Затемнение',
        de: 'Schatten',
        pl: 'Cień',
        zh: '阴影',
    },
    gray_shades: {
        ua: 'Відтінки сірого',
        en: 'Gray Shades',
        ru: 'Оттенки серого',
        de: 'Graustufen',
        pl: 'Odcienie szarości',
        zh: '灰色阴影',
    },
    tequila_sunrise: {
        ua: 'Текіла-Санрайз',
        en: 'Tequila Sunrise',
        ru: 'Текила-санрайз',
        de: 'Tequila Sunrise',
        pl: 'Tequila Sunrise',
        zh: '日出鸡尾酒',
    },
    atomic: {
        ua: 'Атомік',
        en: 'Atomic',
        ru: 'Atomic',
        de: 'Atomar',
        pl: 'Atomowy',
        zh: '原子',
    },
    distortion: {
        ua: 'Спотворення',
        en: 'Distortion',
        ru: 'Искажение',
        de: 'Verzerrung',
        pl: 'Zniekształcenie',
        zh: '失真',
    },
    ecola: {
        ua: 'ECola',
        en: 'ECola',
        ru: 'ECola',
        de: 'ECola',
        pl: 'ECola',
        zh: 'ECola',
    },
    space_ranger: {
        ua: 'Космічний рейнджер',
        en: 'Space Ranger',
        ru: 'Космический рейнджер',
        de: 'Weltraum-Ranger',
        pl: 'Kosmiczny ranger',
        zh: '太空游侠',
    },
    yin_yang: {
        ua: 'Інь-янь',
        en: 'Yin Yang',
        ru: 'Инь-ян',
        de: 'Yin und Yang',
        pl: 'Yin Yang',
        zh: '阴阳',
    },
    target: {
        ua: 'Мішень',
        en: 'Target',
        ru: 'Мишень',
        de: 'Zielscheibe',
        pl: 'Cel',
        zh: '目标',
    },
    lizard: {
        ua: 'Ящірка',
        en: 'Lizard',
        ru: 'Ящерица',
        de: 'Eidechse',
        pl: 'Jaszczurka',
        zh: '蜥蜴',
    },
    dragon: {
        ua: 'Дракон',
        en: 'Dragon',
        ru: 'Дракон',
        de: 'Drache',
        pl: 'Smok',
        zh: '龙',
    },
    alien: {
        ua: 'Інопланетянин',
        en: 'Alien',
        ru: 'Инопланетянин',
        de: 'Außerirdischer',
        pl: 'Obcy',
        zh: '外星人',
    },
    goat: {
        ua: 'Козел',
        en: 'Goat',
        ru: 'Козел',
        de: 'Ziege',
        pl: 'Koza',
        zh: '山羊',
    },
    smiley: {
        ua: 'Смайлик',
        en: 'Smiley',
        ru: 'Смайлик',
        de: 'Smiley',
        pl: 'Uśmiech',
        zh: '笑脸',
    },
    possessed: {
        ua: 'Одержимий',
        en: 'Possessed',
        ru: 'Одержимый',
        de: 'Besessen',
        pl: 'Opętany',
        zh: '附身',
    },
    demon: {
        ua: 'Демон',
        en: 'Demon',
        ru: 'Демон',
        de: 'Dämon',
        pl: 'Demon',
        zh: '恶魔',
    },
    infected: {
        ua: 'Заражений',
        en: 'Infected',
        ru: 'Зараженный',
        de: 'Infiziert',
        pl: 'Zainfekowany',
        zh: '感染',
    },
    undead: {
        ua: 'Нежить',
        en: 'Undead',
        ru: 'Нежить',
        de: 'Untoter',
        pl: 'Nieumarły',
        zh: '亡灵',
    },
    zombie: {
        ua: 'Зомбі',
        en: 'Zombie',
        ru: 'Зомби',
        de: 'Zombie',
        pl: 'Zombie',
        zh: '僵尸',
    },
};
