export default {
    welcome: {
        ru: 'Добрый день! Чем могу помочь?',
        ua: 'Добрий день! Чим можу допомогти?',
        en: 'Good day! How can I help you?',
        de: 'Guten Tag! Wie kann ich Ihnen helfen?',
        pl: 'Dzień dobry! W czym mogę pomóc?',
    },
    leave: {
        ru: 'Ничего, спасибо',
        ua: 'Нічого, дякую',
        en: 'Nothing, thanks',
        de: 'Nichts, danke',
        pl: 'Nic, dziękuję',
    },
    customize: {
        ru: 'Кастомизировать помещение',
        ua: 'Кастомізувати приміщення',
        en: 'Customize the premises',
        de: 'Räumlichkeiten anpassen',
        pl: 'Dostosuj lokal',
    },
    joinTerritoryAttack: {
        ru: 'Отправиться на бой за {{cell}} ({{staged}}/{{slots}})',
        ua: 'Вирушити на бій за {{cell}} ({{staged}}/{{slots}})',
        en: 'Join the battle for {{cell}} ({{staged}}/{{slots}})',
        de: 'Zum Kampf um {{cell}} aufbrechen ({{staged}}/{{slots}})',
        pl: 'Wyrusz do walki o {{cell}} ({{staged}}/{{slots}})',
    },
    joinTerritoryDefense: {
        ru: 'Отправиться на защиту {{cell}} ({{staged}}/{{slots}})',
        ua: 'Вирушити на захист {{cell}} ({{staged}}/{{slots}})',
        en: 'Join the defense of {{cell}} ({{staged}}/{{slots}})',
        de: 'Zur Verteidigung von {{cell}} aufbrechen ({{staged}}/{{slots}})',
        pl: 'Wyrusz na obrone {{cell}} ({{staged}}/{{slots}})',
    },
    enterWarLobby: {
        ru: 'Перейти в лобби капта - {{cell}}',
        ua: 'Перейти в лобі бою - {{cell}}',
        en: 'Enter war lobby - {{cell}}',
        de: 'Kriegs-Lobby betreten - {{cell}}',
        pl: 'Wejdz do lobby wojny - {{cell}}',
    },
    awaitDefenderRoster: {
        ru: 'Состав защиты ещё не утверждён - {{cell}}',
        ua: 'Склад захисту ще не затверджено - {{cell}}',
        en: 'Defender roster not committed yet - {{cell}}',
        de: 'Verteidiger-Kader noch nicht bestaetigt - {{cell}}',
        pl: 'Sklad obrony jeszcze nie zatwierdzony - {{cell}}',
    },
    notInDefenderRoster: {
        ru: 'Вы не в составе защиты - {{cell}}',
        ua: 'Ви не у складі захисту - {{cell}}',
        en: 'You are not in the defender roster - {{cell}}',
        de: 'Du bist nicht im Verteidiger-Kader - {{cell}}',
        pl: 'Nie jestes w skladzie obrony - {{cell}}',
    },
};
