export const server = {
    notifyTitle: {
        ru: 'Офис',
        ua: 'Офіс',
        en: 'Office',
        de: 'Büro',
        pl: 'Biuro',
    },
    modal: {
        exit: {
            title: {
                ru: 'Выход',
                ua: 'Вихід',
                en: 'Exit',
                de: 'Ausgang',
                pl: 'Wyjście',
            },
            message: {
                ru: 'Куда вы хотите выйти?',
                ua: 'Куди ви хочете вийти?',
                en: 'Where do you want to go?',
                de: 'Wohin möchten Sie gehen?',
                pl: 'Dokąd chcesz wyjść?',
            },
            street: {
                ru: 'На улицу',
                ua: 'На вулицю',
                en: 'Street',
                de: 'Zur Straße',
                pl: 'Na ulicę',
            },
            garage: {
                ru: 'В гараж',
                ua: 'В гараж',
                en: 'Garage',
                de: 'In die Garage',
                pl: 'Do garażu',
            },
        },
        buy: {
            title: {
                ru: 'Покупка офиса',
                ua: 'Купівля офісу',
                en: 'Office Purchase',
                de: 'Bürokauf',
                pl: 'Zakup biura',
            },
            message: {
                ru: 'Вы уверены, что хотите купить офис #{{slotId}} в {{building}} за ${{price}}? Средства будут списаны с баланса организации.',
                ua: 'Ви впевнені, що хочете купити офіс #{{slotId}} в {{building}} за ${{price}}? Кошти будуть списані з балансу організації.',
                en: 'Are you sure you want to buy office #{{slotId}} in {{building}} for ${{price}}? Funds will be deducted from the organization balance.',
                de: 'Möchten Sie Büro #{{slotId}} in {{building}} für ${{price}} kaufen? Der Betrag wird vom Organisationskonto abgebucht.',
                pl: 'Czy na pewno chcesz kupić biuro #{{slotId}} w {{building}} za ${{price}}? Środki zostaną pobrane z konta organizacji.',
            },
            confirm: {
                ru: 'Купить',
                ua: 'Купити',
                en: 'Buy',
                de: 'Kaufen',
                pl: 'Kup',
            },
            cancel: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
        },
        sell: {
            title: {
                ru: 'Продажа офиса',
                ua: 'Продаж офісу',
                en: 'Sell office',
                de: 'Büro verkaufen',
                pl: 'Sprzedaż biura',
            },
            message: {
                ru: 'Продать офис #{{slotId}} в {{building}}? На баланс организации вернётся ${{refund}}.',
                ua: 'Продати офіс #{{slotId}} в {{building}}? На баланс організації повернеться ${{refund}}.',
                en: 'Sell office #{{slotId}} in {{building}}? The organization will receive ${{refund}}.',
                de: 'Büro #{{slotId}} in {{building}} verkaufen? Die Organisation erhält ${{refund}}.',
                pl: 'Sprzedać biuro #{{slotId}} w {{building}}? Organizacja otrzyma ${{refund}}.',
            },
            confirm: {
                ru: 'Продать',
                ua: 'Продати',
                en: 'Sell',
                de: 'Verkaufen',
                pl: 'Sprzedaj',
            },
            cancel: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
        },
    },
    errors: {
        invalidData: {
            ru: 'Некорректные данные.',
            ua: 'Некоректні дані.',
            en: 'Invalid data.',
            de: 'Ungültige Daten.',
            pl: 'Nieprawidłowe dane.',
        },
        notFound: {
            ru: 'Офис не найден.',
            ua: 'Офіс не знайдено.',
            en: 'Office not found.',
            de: 'Büro nicht gefunden.',
            pl: 'Biuro nie znalezione.',
        },
        noOrganization: {
            ru: 'Вы не состоите в организации.',
            ua: 'Ви не перебуваєте в організації.',
            en: 'You are not in an organization.',
            de: 'Sie sind nicht in einer Organisation.',
            pl: 'Nie jesteś w organizacji.',
        },
        notLeader: {
            ru: 'Только лидер организации может покупать офисы.',
            ua: 'Тільки лідер організації може купувати офіси.',
            en: 'Only the organization leader can buy offices.',
            de: 'Nur der Organisationsleiter kann Büros kaufen.',
            pl: 'Tylko lider organizacji może kupować biura.',
        },
        alreadyOwned: {
            ru: 'Этот офис уже куплен.',
            ua: 'Цей офіс вже куплено.',
            en: 'This office is already owned.',
            de: 'Dieses Büro ist bereits gekauft.',
            pl: 'To biuro jest już kupione.',
        },
        orgAlreadyHasOffice: {
            ru: 'Ваша организация уже владеет офисом.',
            ua: 'Ваша організація вже володіє офісом.',
            en: 'Your organization already owns an office.',
            de: 'Ihre Organisation besitzt bereits ein Büro.',
            pl: 'Twoja organizacja już posiada biuro.',
        },
        notEnoughMoney: {
            ru: 'Недостаточно средств на балансе организации. Необходимо: ${{price}}',
            ua: 'Недостатньо коштів на балансі організації. Потрібно: ${{price}}',
            en: 'Not enough funds in the organization balance. Required: ${{price}}',
            de: 'Nicht genügend Mittel auf dem Organisationskonto. Erforderlich: ${{price}}',
            pl: 'Niewystarczające środki na koncie organizacji. Wymagane: ${{price}}',
        },
        takeFailed: {
            ru: 'Не удалось списать средства с баланса организации.',
            ua: 'Не вдалося списати кошти з балансу організації.',
            en: 'Failed to deduct funds from the organization balance.',
            de: 'Konnte den Betrag nicht vom Organisationskonto abbuchen.',
            pl: 'Nie udało się pobrać środków z konta organizacji.',
        },
        purchaseFailed: {
            ru: 'Не удалось приобрести офис. Средства возвращены.',
            ua: 'Не вдалося придбати офіс. Кошти повернуто.',
            en: 'Failed to purchase the office. Funds have been refunded.',
            de: 'Bürokauf fehlgeschlagen. Betrag wurde erstattet.',
            pl: 'Nie udało się kupić biura. Środki zostały zwrócone.',
        },
        notPurchased: {
            ru: 'Этот офис не куплен.',
            ua: 'Цей офіс не куплено.',
            en: 'This office is not purchased.',
            de: 'Dieses Büro ist nicht gekauft.',
            pl: 'To biuro nie jest kupione.',
        },
        notYourOrg: {
            ru: 'Этот офис принадлежит другой организации.',
            ua: 'Цей офіс належить іншій організації.',
            en: 'This office belongs to another organization.',
            de: 'Dieses Büro gehört einer anderen Organisation.',
            pl: 'To biuro należy do innej organizacji.',
        },
        garageNotPurchased: {
            ru: 'Гараж не прокачан. Приобретите его в меню офиса.',
            ua: 'Гараж не прокачаний. Придбайте його в меню офісу.',
            en: 'Garage not upgraded. Purchase it in the office menu.',
            de: 'Garage nicht ausgebaut. Kaufen Sie sie im Büromenü.',
            pl: 'Garaż nie jest ulepszony. Kup go w menu biura.',
        },
        garageConfigMissing: {
            ru: 'Конфигурация гаража не найдена.',
            ua: 'Конфігурацію гаража не знайдено.',
            en: 'Garage configuration not found.',
            de: 'Garagenkonfiguration nicht gefunden.',
            pl: 'Konfiguracja garażu nie została znaleziona.',
        },
    },
    success: {
        purchased: {
            ru: 'Офис #{{slotId}} в {{building}} успешно приобретён за ${{price}}',
            ua: 'Офіс #{{slotId}} в {{building}} успішно придбано за ${{price}}',
            en: 'Office #{{slotId}} in {{building}} successfully purchased for ${{price}}',
            de: 'Büro #{{slotId}} in {{building}} erfolgreich gekauft für ${{price}}',
            pl: 'Biuro #{{slotId}} w {{building}} kupione za ${{price}}',
        },
        sold: {
            ru: 'Офис #{{slotId}} в {{building}} продан, возвращено ${{refund}}',
            ua: 'Офіс #{{slotId}} в {{building}} продано, повернуто ${{refund}}',
            en: 'Office #{{slotId}} in {{building}} sold, refunded ${{refund}}',
            de: 'Büro #{{slotId}} in {{building}} verkauft, ${{refund}} erstattet',
            pl: 'Biuro #{{slotId}} w {{building}} sprzedane, zwrócono ${{refund}}',
        },
    },
};
