import levels from './levels/index';

export default {
    title: {
        ru: 'Beak Break',
        ua: 'Beak Break',
        en: 'Beak Break',
        de: 'Beak Break',
        pl: 'Beak Break',
    },
    campaign: {
        ru: 'Семечковый поход',
        ua: 'Насіннєвий похід',
        en: 'The Seed Quest',
        de: 'Die Kernsuche',
        pl: 'Wyprawa po ziarno',
    },
    level: {
        ru: 'Уровень {{n}}',
        ua: 'Рівень {{n}}',
        en: 'Level {{n}}',
        de: 'Level {{n}}',
        pl: 'Poziom {{n}}',
    },
    levelMap: {
        ru: 'К уровням',
        ua: 'До рівнів',
        en: 'To levels',
        de: 'Zu den Levels',
        pl: 'Do poziomów',
    },
    toWorlds: {
        ru: 'К мирам',
        ua: 'До світів',
        en: 'To worlds',
        de: 'Zu den Welten',
        pl: 'Do światów',
    },
    pause: {
        ru: 'Пауза',
        ua: 'Пауза',
        en: 'Pause',
        de: 'Pause',
        pl: 'Pauza',
    },
    resume: {
        ru: 'Продолжить',
        ua: 'Продовжити',
        en: 'Resume',
        de: 'Weiter',
        pl: 'Wznów',
    },
    restart: {
        ru: 'Заново',
        ua: 'Заново',
        en: 'Restart',
        de: 'Neu starten',
        pl: 'Od nowa',
    },
    next: {
        ru: 'Следующий уровень',
        ua: 'Наступний рівень',
        en: 'Next level',
        de: 'Nächstes Level',
        pl: 'Następny poziom',
    },
    close: {
        ru: 'Закрыть',
        ua: 'Закрити',
        en: 'Close',
        de: 'Schließen',
        pl: 'Zamknij',
    },
    best: {
        ru: 'Рекорд',
        ua: 'Рекорд',
        en: 'Best',
        de: 'Rekord',
        pl: 'Rekord',
    },
    newRecord: {
        ru: 'Новый рекорд',
        ua: 'Новий рекорд',
        en: 'New record',
        de: 'Neuer Rekord',
        pl: 'Nowy rekord',
    },
    won: {
        ru: 'Уровень пройден',
        ua: 'Рівень пройдено',
        en: 'Level cleared',
        de: 'Level geschafft',
        pl: 'Poziom ukończony',
    },
    lost: {
        ru: 'Лисы устояли',
        ua: 'Лиси встояли',
        en: 'The foxes held out',
        de: 'Die Füchse haben gehalten',
        pl: 'Lisy się obroniły',
    },
    leaders: {
        ru: 'Лучшие игроки',
        ua: 'Найкращі гравці',
        en: 'Top players',
        de: 'Bestenliste',
        pl: 'Najlepsi gracze',
    },
    noLeaders: {
        ru: 'Пройдите уровень, чтобы попасть в таблицу',
        ua: 'Пройдіть рівень, щоб потрапити до таблиці',
        en: 'Clear a level to get on the board',
        de: 'Schaffe ein Level, um in die Liste zu kommen',
        pl: 'Ukończ poziom, aby trafić do tabeli',
    },
    loadError: {
        ru: 'Игра не загрузилась. Откройте приложение ещё раз',
        ua: 'Гра не завантажилася. Відкрийте застосунок ще раз',
        en: 'The game did not load. Open the app again',
        de: 'Das Spiel wurde nicht geladen. Öffne die App erneut',
        pl: 'Gra się nie wczytała. Otwórz aplikację ponownie',
    },
    comingSoon: {
        ru: 'Скоро',
        ua: 'Незабаром',
        en: 'Coming soon',
        de: 'Bald',
        pl: 'Wkrótce',
    },
    worldLocked: {
        ru: 'Победите Барона в прошлом мире',
        ua: 'Переможіть Барона в минулому світі',
        en: 'Beat the Baron in the world before',
        de: 'Besiege den Baron in der Welt davor',
        pl: 'Pokonaj Barona w poprzednim świecie',
    },
    secret: {
        ru: 'Секретный уровень',
        ua: 'Секретний рівень',
        en: 'Secret level',
        de: 'Geheimes Level',
        pl: 'Tajny poziom',
    },
    secretLocked: {
        ru: 'Найдите три золотых жёлудя этого мира',
        ua: 'Знайдіть три золоті жолуді цього світу',
        en: 'Find the three golden acorns of this world',
        de: 'Finde die drei goldenen Eicheln dieser Welt',
        pl: 'Znajdź trzy złote żołędzie tego świata',
    },
    acornFound: {
        ru: 'Золотой жёлудь',
        ua: 'Золотий жолудь',
        en: 'Golden acorn',
        de: 'Goldene Eichel',
        pl: 'Złoty żołądź',
    },
    hint: {
        ru: 'Подсказка',
        ua: 'Підказка',
        en: 'Hint',
        de: 'Tipp',
        pl: 'Podpowiedź',
    },
    settings: {
        ru: 'Настройки',
        ua: 'Налаштування',
        en: 'Settings',
        de: 'Einstellungen',
        pl: 'Ustawienia',
    },
    sound: {
        ru: 'Звуки',
        ua: 'Звуки',
        en: 'Sounds',
        de: 'Geräusche',
        pl: 'Dźwięki',
    },
    music: {
        ru: 'Музыка',
        ua: 'Музика',
        en: 'Music',
        de: 'Musik',
        pl: 'Muzyka',
    },
    on: {
        ru: 'Вкл',
        ua: 'Увімк',
        en: 'On',
        de: 'An',
        pl: 'Wł.',
    },
    off: {
        ru: 'Выкл',
        ua: 'Вимк',
        en: 'Off',
        de: 'Aus',
        pl: 'Wył.',
    },
    tapToContinue: {
        ru: 'Нажмите, чтобы продолжить',
        ua: 'Натисніть, щоб продовжити',
        en: 'Tap to continue',
        de: 'Tippen zum Fortfahren',
        pl: 'Dotknij, aby kontynuować',
    },
    worlds: {
        w1: {
            ru: 'Подсолнуховая роща',
            ua: 'Соняшниковий гай',
            en: 'Sunflower Grove',
            de: 'Sonnenblumenhain',
            pl: 'Słonecznikowy gaj',
        },
        w2: {
            ru: 'Мельничные холмы',
            ua: 'Млинові пагорби',
            en: 'Mill Hills',
            de: 'Mühlenhügel',
            pl: 'Młyńskie wzgórza',
        },
        w3: {
            ru: 'Ледяной перевал',
            ua: 'Крижаний перевал',
            en: 'Icy Pass',
            de: 'Eispass',
            pl: 'Lodowa przełęcz',
        },
        w4: {
            ru: 'Лисья цитадель',
            ua: 'Лисяча цитадель',
            en: 'Fox Citadel',
            de: 'Fuchszitadelle',
            pl: 'Lisia cytadela',
        },
    },
    // The heroes: the five birds and the fox who stole the seed.
    names: {
        sparrow: {
            ru: 'Чирик',
            ua: 'Чирик',
            en: 'Chirp',
            de: 'Tschilp',
            pl: 'Ćwirek',
        },
        woodpecker: {
            ru: 'Тук',
            ua: 'Тук',
            en: 'Knock',
            de: 'Klopf',
            pl: 'Stuk',
        },
        pelican: {
            ru: 'Пеля',
            ua: 'Пеля',
            en: 'Pela',
            de: 'Pela',
            pl: 'Pela',
        },
        hummingbird: {
            ru: 'Изи',
            ua: 'Ізі',
            en: 'Izzy',
            de: 'Izzy',
            pl: 'Izzy',
        },
        penguin: {
            ru: 'Тюк',
            ua: 'Тюк',
            en: 'Tuck',
            de: 'Tuck',
            pl: 'Tuk',
        },
        baron: {
            ru: 'Барон Рыжехвост',
            ua: 'Барон Рудохвіст',
            en: 'Baron Redtail',
            de: 'Baron Rotschwanz',
            pl: 'Baron Rudoogon',
        },
    },
    // Captions of the comics and the scenes between worlds (FunnyBirds/story).
    story: {
        prologue1: {
            ru: 'Раз в год Великий Подсолнух дарит роще одно Солнечное зерно. Из него весной прорастает вся роща.',
            ua: 'Раз на рік Великий Соняшник дарує гаю одну Сонячну зернину. З неї навесні проростає весь гай.',
            en: 'Once a year the Great Sunflower gives the grove one Sun Seed. In spring the whole grove grows from it.',
            de: 'Einmal im Jahr schenkt die Große Sonnenblume dem Hain einen Sonnenkern. Im Frühling wächst der ganze Hain daraus.',
            pl: 'Raz w roku Wielki Słonecznik daje gajowi jedno Słoneczne ziarno. Wiosną wyrasta z niego cały gaj.',
        },
        prologue2: {
            ru: 'Ночью Барон Рыжехвост и его лисы унесли мешок с зерном. Чирик и Тук бросаются в погоню!',
            ua: 'Уночі Барон Рудохвіст і його лиси винесли мішок із зерниною. Чирик і Тук кидаються навздогін!',
            en: 'At night Baron Redtail and his foxes carried off the sack with the seed. Chirp and Knock give chase!',
            de: 'In der Nacht haben Baron Rotschwanz und seine Füchse den Sack mit dem Kern geraubt. Tschilp und Klopf nehmen die Verfolgung auf!',
            pl: 'Nocą Baron Rudoogon i jego lisy porwali worek z ziarnem. Ćwirek i Stuk ruszają w pościg!',
        },
        escape1a: {
            ru: 'Барон удирает с мешком к Мельничным холмам.',
            ua: 'Барон тікає з мішком до Млинових пагорбів.',
            en: 'The Baron runs off with the sack to the Mill Hills.',
            de: 'Der Baron flieht mit dem Sack zu den Mühlenhügeln.',
            pl: 'Baron ucieka z workiem na Młyńskie wzgórza.',
        },
        escape1b: {
            ru: 'На помощь прилетает Пеля: её удар сверху не выдержит даже камень.',
            ua: 'На допомогу прилітає Пеля: її удар згори не витримає навіть камінь.',
            en: 'Pela flies in to help: not even stone can take her strike from above.',
            de: 'Pela kommt zu Hilfe: ihrem Schlag von oben hält nicht einmal Stein stand.',
            pl: 'Na pomoc przylatuje Pela: jej uderzenia z góry nie wytrzyma nawet kamień.',
        },
        escape2a: {
            ru: 'Мельница пала, но Барон уходит в горы, на Ледяной перевал.',
            ua: 'Млин упав, але Барон іде в гори, на Крижаний перевал.',
            en: 'The mill has fallen, but the Baron heads into the mountains, to the Icy Pass.',
            de: 'Die Mühle ist gefallen, doch der Baron flieht in die Berge, zum Eispass.',
            pl: 'Młyn padł, ale Baron ucieka w góry, na Lodową przełęcz.',
        },
        escape2b: {
            ru: 'В снегах к птицам присоединяется Тюк: по льду он скользит быстрее всех.',
            ua: 'У снігах до птахів приєднується Тюк: по льоду він ковзає найшвидше.',
            en: 'In the snow Tuck joins the birds: nobody slides on ice faster.',
            de: 'Im Schnee schließt sich Tuck den Vögeln an: niemand rutscht schneller übers Eis.',
            pl: 'W śniegach do ptaków dołącza Tuk: nikt nie ślizga się po lodzie szybciej.',
        },
        escape3a: {
            ru: 'Ледяная броня разбита. Барон бежит в свою цитадель.',
            ua: 'Крижану броню розбито. Барон тікає до своєї цитаделі.',
            en: 'The ice armour is shattered. The Baron flees to his citadel.',
            de: 'Die Eisrüstung ist zerschlagen. Der Baron flieht in seine Zitadelle.',
            pl: 'Lodowa zbroja rozbita. Baron ucieka do swojej cytadeli.',
        },
        escape3b: {
            ru: 'Птицы идут за ним в Лисью цитадель. Зерно уже близко.',
            ua: 'Птахи йдуть за ним до Лисячої цитаделі. Зернина вже близько.',
            en: 'The birds follow him into the Fox Citadel. The seed is close now.',
            de: 'Die Vögel folgen ihm in die Fuchszitadelle. Der Kern ist ganz nah.',
            pl: 'Ptaki ruszają za nim do Lisiej cytadeli. Ziarno jest już blisko.',
        },
        twist1: {
            ru: 'Когда-то машина Барона дарила лисам тепло и свет, но выпила всю жизнь из их леса.',
            ua: 'Колись машина Барона дарувала лисам тепло і світло, але випила все життя з їхнього лісу.',
            en: "Once the Baron's machine gave the foxes warmth and light, but it drained all life from their forest.",
            de: 'Einst schenkte die Maschine des Barons den Füchsen Wärme und Licht, doch sie hat ihrem Wald alles Leben ausgesaugt.',
            pl: 'Kiedyś maszyna Barona dawała lisom ciepło i światło, ale wyssała całe życie z ich lasu.',
        },
        twist2: {
            ru: 'Барон хочет, чтобы Солнечное зерно вернуло его лесу зелень. Даже если роща птиц останется без весны.',
            ua: 'Барон хоче, щоб Сонячна зернина повернула його лісу зелень. Навіть якщо гай птахів лишиться без весни.',
            en: "The Baron wants the Sun Seed to bring his forest back to green, even if the birds' grove is left without spring.",
            de: 'Der Baron will, dass der Sonnenkern seinen Wald wieder ergrünen lässt, selbst wenn der Hain der Vögel ohne Frühling bleibt.',
            pl: 'Baron chce, by Słoneczne ziarno przywróciło zieleń jego lasowi, nawet jeśli gaj ptaków zostanie bez wiosny.',
        },
        planting1: {
            ru: 'Машина сломана. Но птицы не уносят зерно домой: они сажают его в землю лис.',
            ua: 'Машину зламано. Але птахи не несуть зернину додому: вони садять її в землю лис.',
            en: "The machine is broken. But the birds do not take the seed home: they plant it in the foxes' land.",
            de: 'Die Maschine ist zerstört. Doch die Vögel bringen den Kern nicht heim: sie pflanzen ihn in die Erde der Füchse.',
            pl: 'Maszyna zniszczona. Ale ptaki nie zabierają ziarna do domu: sadzą je w ziemi lisów.',
        },
        planting2: {
            ru: 'Из мёртвой земли пробивается первый росток.',
            ua: 'З мертвої землі пробивається перший паросток.',
            en: 'The first sprout pushes up through the dead ground.',
            de: 'Aus der toten Erde bricht der erste Spross hervor.',
            pl: 'Z martwej ziemi przebija się pierwszy kiełek.',
        },
        finale1: {
            ru: 'Весной зацвели обе рощи.',
            ua: 'Навесні розквітли обидва гаї.',
            en: 'In spring both groves came into bloom.',
            de: 'Im Frühling erblühten beide Haine.',
            pl: 'Wiosną zakwitły oba gaje.',
        },
        finale2: {
            ru: 'А на лугу между ними птицы и лисы теперь делят семечки поровну.',
            ua: 'А на лузі між ними птахи й лиси тепер ділять насіння порівну.',
            en: 'And on the meadow between them, birds and foxes now share the seeds.',
            de: 'Und auf der Wiese dazwischen teilen Vögel und Füchse nun die Kerne.',
            pl: 'A na łące między nimi ptaki i lisy dzielą się teraz ziarnami.',
        },
    },
    levels,
};
