export default {
    name: {
        ru: 'Уличный музыкант',
        ua: 'Вуличний музикант',
        en: 'The street musician',
        de: 'Der Straßenmusiker',
        pl: 'Uliczny muzyk',
    },
    dialog: {
        offer: {
            ru: 'Играю тут с самого утра, а в чехле до сих пор пусто. Слушать - бесплатно, честное слово. Но если зацепит, ты знаешь, что делать.',
            ua: 'Граю тут із самого ранку, а в чохлі досі порожньо. Слухати - безкоштовно, чесне слово. Але якщо зачепить, ти знаєш, що робити.',
            en: 'I have been playing since morning and the case is still empty. Listening is free, honest. But if it gets to you, you know what to do.',
            de: 'Ich spiele hier seit dem Morgen, und der Koffer ist immer noch leer. Zuhören kostet nichts, ehrlich. Aber wenn es dich packt, weißt du ja, was zu tun ist.',
            pl: 'Gram tu od rana, a futerał wciąż pusty. Słuchanie jest za darmo, słowo daję. Ale jak cię chwyci, wiesz, co robić.',
        },
        busy: {
            ru: 'Ты уже сегодня выручил меня, друг. Просто постой и послушай, это тоже немало.',
            ua: 'Ти вже сьогодні мене виручив, друже. Просто постій і послухай, це теж чимало.',
            en: 'You already made my day, friend. Just stand and listen a while, that counts too.',
            de: 'Du hast meinen Tag schon gerettet, Freund. Bleib einfach stehen und hör zu, das zählt auch.',
            pl: 'Już mi dziś pomogłeś, przyjacielu. Po prostu stań i posłuchaj, to też się liczy.',
        },
        tipSmall: {
            ru: 'Бросить {{amount}}',
            ua: 'Кинути {{amount}}',
            en: 'Drop {{amount}}',
            de: '{{amount}} einwerfen',
            pl: 'Wrzucić {{amount}}',
        },
        tipMedium: {
            ru: 'Бросить {{amount}}',
            ua: 'Кинути {{amount}}',
            en: 'Drop {{amount}}',
            de: '{{amount}} einwerfen',
            pl: 'Wrzucić {{amount}}',
        },
        tipLarge: {
            ru: 'Бросить {{amount}}',
            ua: 'Кинути {{amount}}',
            en: 'Drop {{amount}}',
            de: '{{amount}} einwerfen',
            pl: 'Wrzucić {{amount}}',
        },
        thanksSmall: {
            ru: 'О, спасибо! Первые за день, если честно. Не сбиваюсь, слышишь? Куплет твой, до конца доиграю.',
            ua: 'О, дякую! Перші за день, якщо чесно. Не збиваюсь, чуєш? Куплет твій, до кінця дограю.',
            en: 'Oh, thank you! First of the day, if I am honest. Hear that? I did not miss a beat. This verse is yours, I will play it out.',
            de: 'Oh, danke dir! Die ersten heute, ehrlich gesagt. Hörst du? Kein Takt daneben. Die Strophe gehört dir, ich spiele sie zu Ende.',
            pl: 'O, dzięki! Pierwsze dzisiaj, szczerze mówiąc. Słyszysz? Ani jednej pomyłki. Ta zwrotka jest twoja, dogram ją do końca.',
        },
        thanksMedium: {
            ru: 'Ого. Слушай, это не "на кофе", это на струны и ещё на неделю здесь простоять. Держись, сейчас будет то, что я обычно приберегаю.',
            ua: 'Ого. Слухай, це не "на каву", це на струни і ще на тиждень тут простояти. Тримайся, зараз буде те, що я зазвичай приберігаю.',
            en: 'Whoa. Listen, that is not coffee money, that is strings and another week of standing here. Hold on, here comes the one I usually save.',
            de: 'Wow. Hör mal, das ist kein Kaffeegeld, das sind Saiten und noch eine Woche hier. Warte, jetzt kommt das Stück, das ich mir sonst aufhebe.',
            pl: 'Ojej. Słuchaj, to nie są pieniądze na kawę, to struny i jeszcze tydzień stania tutaj. Poczekaj, teraz zagram to, co zwykle zostawiam na koniec.',
        },
        thanksLarge: {
            ru: 'Ты... подожди. Ты хоть понимаешь, сколько это? Я за такое полгода тут стою.\n\nЗнаешь что. Забирай её. Нет, я серьёзно - забирай. Я себе ещё найду, я всегда нахожу. А ей руки нужны, а не чехол. Только играй на ней, ладно? Не вешай на стену.\n\nИ вот это возьми, из чехла. Само туда попало за все эти годы, а мне без надобности.',
            ua: 'Ти... зачекай. Ти хоч розумієш, скільки це? Я за таке пів року тут стою.\n\nЗнаєш що. Забирай її. Ні, я серйозно - забирай. Я собі ще знайду, я завжди знаходжу. А їй руки потрібні, а не чохол. Тільки грай на ній, добре? Не вішай на стіну.\n\nІ ось це візьми, з чохла. Само туди потрапило за всі ці роки, а мені ні до чого.',
            en: 'You... hold on. Do you even know how much that is? That is half a year of standing on this corner.\n\nYou know what. Take her. No, I mean it - take her. I will find myself another, I always do. She needs hands, not a case. Just play her, alright? Do not hang her on a wall.\n\nAnd take this too, out of the case. It found its way in there over the years and I have no use for it.',
            de: 'Du... warte mal. Weißt du überhaupt, wie viel das ist? Dafür stehe ich hier ein halbes Jahr.\n\nWeißt du was. Nimm sie. Nein, im Ernst - nimm sie. Ich finde mir eine neue, das tue ich immer. Sie braucht Hände, keinen Koffer. Spiel sie nur, ja? Häng sie nicht an die Wand.\n\nUnd das hier nimm auch, aus dem Koffer. Das hat sich über die Jahre da angesammelt, ich brauche es nicht.',
            pl: 'Ty... zaczekaj. Ty w ogóle wiesz, ile to jest? Za tyle stoję tu pół roku.\n\nWiesz co. Bierz ją. Nie, mówię poważnie - bierz. Znajdę sobie inną, zawsze znajduję. Ona potrzebuje rąk, a nie futerału. Tylko na niej graj, dobrze? Nie wieszaj jej na ścianie.\n\nI to jeszcze weź, z futerału. Samo się tam przez lata znalazło, a mnie niepotrzebne.',
        },
        decline: {
            ru: 'Просто послушаю',
            ua: 'Просто послухаю',
            en: 'I will just listen',
            de: 'Ich höre nur zu',
            pl: 'Po prostu posłucham',
        },
        bye: {
            ru: 'Удачи, Пол',
            ua: 'Щасти, Пол',
            en: 'Good luck, Paul',
            de: 'Viel Glück, Paul',
            pl: 'Powodzenia, Paul',
        },
    },
};
