export default {
    cef: {
        title: {
            ru: 'ОБМЕН ИМУЩЕСТВОМ',
            ua: 'ОБМІН МАЙНОМ',
            en: 'PROPERTY TRADE',
            de: 'EIGENTUMSTAUSCH',
            pl: 'WYMIANA MAJĄTKU',
            zh: '财产交换',
        },
        subtitle: {
            ru: 'Обмен будет осуществлён сразу после нажатия обоими участниками сделки кнопки "Подтвердить обмен"',
            ua: 'Обмін буде здійснено одразу після натискання обома учасниками угоди кнопки "Підтвердити обмін"',
            en: 'The trade will be executed once both participants press the "Confirm trade" button',
            de: 'Der Tausch wird durchgeführt, sobald beide Teilnehmer die Schaltfläche "Tausch bestätigen" drücken',
            pl: 'Wymiana zostanie przeprowadzona po naciśnięciu przez obu uczestników przycisku "Potwierdź wymianę"',
            zh: '双方点击“确认交换”按钮后，交换将立即执行',
        },
        cancel: {
            ru: 'Отменить обмен',
            ua: 'Скасувати обмін',
            en: 'Cancel trade',
            de: 'Tausch abbrechen',
            pl: 'Anuluj wymianę',
            zh: '取消交换',
        },
        addAssetHint: {
            ru: 'Добавьте имущество в обмен',
            ua: 'Додайте майно до обміну',
            en: 'Add property to the trade',
            de: 'Eigentum zum Tausch hinzufügen',
            pl: 'Dodaj majątek do wymiany',
            zh: '向交换添加财产',
        },
        offersHintSelf: {
            ru: 'Вы предлагаете имущество для обмена',
            ua: 'Ви пропонуєте майно для обміну',
            en: 'You are offering property for trade',
            de: 'Sie bieten Eigentum zum Tausch an',
            pl: 'Oferujesz majątek do wymiany',
            zh: '您正在提供财产用于交换',
        },
        offersHint: {
            ru: 'Предлагает имущество для обмена',
            ua: 'Пропонує майно для обміну',
            en: 'Offers property for trade',
            de: 'Bietet Eigentum zum Tausch an',
            pl: 'Oferuje majątek do wymiany',
            zh: '提供交换财产',
        },
        commission: {
            ru: 'Комиссия',
            ua: 'Комісія',
            en: 'Fee',
            de: 'Gebühr',
            pl: 'Prowizja',
            zh: '手续费',
        },
        categories: {
            items: {
                ru: 'Предметы',
                ua: 'Предмети',
                en: 'Items',
                de: 'Gegenstände',
                pl: 'Przedmioty',
                zh: '物品',
            },
            vehicles: {
                ru: 'Транспорт',
                ua: 'Транспорт',
                en: 'Vehicles',
                de: 'Fahrzeuge',
                pl: 'Pojazdy',
                zh: '车辆',
            },
            houses: {
                ru: 'Дома',
                ua: 'Будинки',
                en: 'Houses',
                de: 'Häuser',
                pl: 'Domy',
                zh: '房屋',
            },
            businesses: {
                ru: 'Бизнессы',
                ua: 'Бізнеси',
                en: 'Businesses',
                de: 'Geschäfte',
                pl: 'Biznesy',
                zh: '企业',
            },
        },
        surchargePlaceholder: {
            ru: 'Доплата',
            ua: 'Доплата',
            en: 'Surcharge',
            de: 'Aufpreis',
            pl: 'Dopłata',
            zh: '附加费',
        },
        add: {
            ru: 'Добавить',
            ua: 'Додати',
            en: 'Add',
            de: 'Hinzufügen',
            pl: 'Dodaj',
            zh: '添加',
        },
        back: {
            ru: 'Назад',
            ua: 'Назад',
            en: 'Back',
            de: 'Zurück',
            pl: 'Wstecz',
            zh: '返回',
        },
        confirm: {
            ru: 'Подтвердить обмен',
            ua: 'Підтвердити обмін',
            en: 'Confirm trade',
            de: 'Tausch bestätigen',
            pl: 'Potwierdź wymianę',
            zh: '确认交换',
        },
        confirmed: {
            ru: 'Готов к обмену',
            ua: 'Готовий до обміну',
            en: 'Ready to trade',
            de: 'Bereit zum Tausch',
            pl: 'Gotowy do wymiany',
            zh: '准备交换',
        },
        notConfirmed: {
            ru: 'Не подтвердил обмен',
            ua: 'Не підтвердив обмін',
            en: 'Has not confirmed the trade',
            de: 'Hat den Tausch nicht bestätigt',
            pl: 'Nie potwierdził wymiany',
            zh: '尚未确认交换',
        },
        otherConfirmed: {
            ru: 'Подтвердил обмен',
            ua: 'Підтвердив обмін',
            en: 'Confirmed the trade',
            de: 'Hat den Tausch bestätigt',
            pl: 'Potwierdził wymianę',
            zh: '已确认交换',
        },
        wait: {
            ru: 'Подождите',
            ua: 'Зачекайте',
            en: 'Wait',
            de: 'Warten',
            pl: 'Czekaj',
            zh: '请等待',
        },
        commissionPayer: {
            ru: 'Комиссию платит',
            ua: 'Комісію сплачує',
            en: 'Fee is paid by',
            de: 'Gebühr wird bezahlt von',
            pl: 'Prowizję płaci',
            zh: '手续费支付方',
        },
        side1: {
            ru: 'Сторона 1',
            ua: 'Сторона 1',
            en: 'Side 1',
            de: 'Seite 1',
            pl: 'Strona 1',
            zh: '第一方',
        },
        side2: {
            ru: 'Сторона 2',
            ua: 'Сторона 2',
            en: 'Side 2',
            de: 'Seite 2',
            pl: 'Strona 2',
            zh: '第二方',
        },
        half: {
            ru: '50/50',
            ua: '50/50',
            en: '50/50',
            de: '50/50',
            pl: '50/50',
            zh: '50/50',
        },
        hintFields: {
            name: {
                ru: 'Название',
                ua: 'Назва',
                en: 'Name',
                de: 'Name',
                pl: 'Nazwa',
                zh: '名称',
            },
            plate: {
                ru: 'Номер',
                ua: 'Номер',
                en: 'Plate',
                de: 'Kennzeichen',
                pl: 'Numer',
                zh: '车牌',
            },
            tuningCost: {
                ru: 'Стоимость тюнинга',
                ua: 'Вартість тюнінгу',
                en: 'Tuning cost',
                de: 'Tuningkosten',
                pl: 'Koszt tuningu',
                zh: '改装费用',
            },
            govPrice: {
                ru: 'Гос. стоимость',
                ua: 'Держ. вартість',
                en: 'Gov. price',
                de: 'Staatl. Preis',
                pl: 'Cena państwowa',
                zh: '政府估价',
            },
            district: {
                ru: 'Район',
                ua: 'Район',
                en: 'District',
                de: 'Bezirk',
                pl: 'Dzielnica',
                zh: '区',
            },
            street: {
                ru: 'Улица',
                ua: 'Вулиця',
                en: 'Street',
                de: 'Straße',
                pl: 'Ulica',
                zh: '街道',
            },
            repairCost: {
                ru: 'Стоимость ремонта',
                ua: 'Вартість ремонту',
                en: 'Repair cost',
                de: 'Reparaturkosten',
                pl: 'Koszt naprawy',
                zh: '维修费用',
            },
            amount: {
                ru: 'Сумма',
                ua: 'Сума',
                en: 'Amount',
                de: 'Betrag',
                pl: 'Kwota',
                zh: '金额',
            },
            house: {
                ru: 'Дом',
                ua: 'Будинок',
                en: 'House',
                de: 'Haus',
                pl: 'Dom',
                zh: '房屋',
            },
            money: {
                ru: 'Деньги',
                ua: 'Гроші',
                en: 'Money',
                de: 'Geld',
                pl: 'Pieniądze',
                zh: '金钱',
            },
        },
    },
};
