export default {
    cef: {
        title: {
            ru: 'ОБМЕН ИМУЩЕСТВОМ',
            ua: 'ОБМІН МАЙНОМ',
            en: 'PROPERTY TRADE',
            de: 'EIGENTUMSTAUSCH',
            pl: 'WYMIANA MAJĄTKU',
            zh: '财产交换',
        },
        subtitle: {
            ru: 'Обмен будет осуществлён сразу после нажатия обоими участниками сделки кнопки "Подтвердить обмен"',
            ua: 'Обмін буде здійснено одразу після натискання обома учасниками угоди кнопки "Підтвердити обмін"',
            en: 'The trade will be executed once both participants press the "Confirm trade" button',
            de: 'Der Tausch wird durchgeführt, sobald beide Teilnehmer die Schaltfläche "Tausch bestätigen" drücken',
            pl: 'Wymiana zostanie przeprowadzona po naciśnięciu przez obu uczestników przycisku "Potwierdź wymianę"',
            zh: '双方点击“确认交换”按钮后，交换将立即执行',
        },
        cancel: {
            ru: 'Отменить обмен',
            ua: 'Скасувати обмін',
            en: 'Cancel trade',
            de: 'Tausch abbrechen',
            pl: 'Anuluj wymianę',
            zh: '取消交换',
        },
        cancelHeader: {
            ru: 'Обмен имуществом',
            ua: 'Обмін майном',
            en: 'Property trade',
            de: 'Eigentumstausch',
            pl: 'Wymiana majątku',
            zh: '财产交换',
        },
        otherCancelled: {
            ru: 'Другой участник обмена отменил сделку',
            ua: 'Інший учасник обміну скасував угоду',
            en: 'The other participant cancelled the trade',
            de: 'Der andere Teilnehmer hat den Tausch abgebrochen',
            pl: 'Drugi uczestnik anulował wymianę',
            zh: '另一方取消了交换',
        },
        alreadyInTrade: {
            ru: 'Участник уже находится в обмене',
            ua: 'Учасник вже бере участь в обміні',
            en: 'Participant is already in a trade',
            de: 'Teilnehmer ist bereits in einem Tausch',
            pl: 'Uczestnik jest już w wymianie',
            zh: '该玩家已在交换中',
        },
        success: {
            ru: 'Обмен успешно завершён',
            ua: 'Обмін успішно завершено',
            en: 'Trade completed successfully',
            de: 'Tausch erfolgreich abgeschlossen',
            pl: 'Wymiana zakończona pomyślnie',
            zh: '交换已成功完成',
        },
        cancelReasons: {
            notEnoughCommissionCash: {
                    ru: 'Недостаточно денег для оплаты комиссии обмена',
                    ua: 'Недостатньо грошей для оплати комісії обміну',
                    en: 'Not enough cash to pay the trade fee',
                    de: 'Nicht genug Bargeld, um die Tauschgebühr zu bezahlen',
                    pl: 'Brak gotówki na pokrycie prowizji wymiany',
                    zh: '现金不足以支付交换手续费',
                },
                notEnoughInventorySpace: {
                    ru: 'Недостаточно места в инвентаре',
                    ua: 'Недостатньо місця в інвентарі',
                    en: 'Not enough inventory space',
                    de: 'Nicht genug Platz im Inventar',
                    pl: 'Brak miejsca w ekwipunku',
                    zh: '物品栏空间不足',
                },
                notEnoughVehicleSpace: {
                    ru: 'Недостаточно места для транспорта',
                    ua: 'Недостатньо місця для транспорту',
                    en: 'Not enough parking space for vehicles',
                    de: 'Nicht genug Parkplatz für Fahrzeuge',
                    pl: 'Brak miejsca parkingowego dla pojazdów',
                    zh: '车辆停车位不足',
                },
                notEnoughHouseSlots: {
                    ru: 'Превышен лимит домов',
                    ua: 'Перевищено ліміт будинків',
                    en: 'House limit exceeded',
                    de: 'Hauslimit überschritten',
                    pl: 'Przekroczono limit domów',
                    zh: '超过房屋数量上限',
                },
                notEnoughBusinessSlots: {
                    ru: 'Превышен лимит бизнесов',
                    ua: 'Перевищено ліміт бізнесів',
                    en: 'Business limit exceeded',
                    de: 'Geschäftslimit überschritten',
                    pl: 'Przekroczono limit biznesów',
                    zh: '超过企业数量上限',
                },
                assetUnavailable: {
                    ru: 'Имущество больше недоступно',
                    ua: 'Майно більше недоступне',
                    en: 'Asset is no longer available',
                    de: 'Gegenstand ist nicht mehr verfügbar',
                    pl: 'Przedmiot nie jest już dostępny',
                    zh: '资产已不可用',
                },
                executionFailed: {
                    ru: 'Ошибка при выполнении обмена',
                    ua: 'Помилка під час виконання обміну',
                    en: 'Trade execution failed',
                    de: 'Tauschausführung fehlgeschlagen',
                    pl: 'Wymiana nie powiodła się',
                    zh: '交换执行失败',
                },
        },
        addAssetHint: {
            ru: 'Добавьте имущество в обмен',
            ua: 'Додайте майно до обміну',
            en: 'Add property to the trade',
            de: 'Eigentum zum Tausch hinzufügen',
            pl: 'Dodaj majątek do wymiany',
            zh: '向交换添加财产',
        },
        offersHintSelf: {
            ru: 'Вы предлагаете имущество для обмена',
            ua: 'Ви пропонуєте майно для обміну',
            en: 'You are offering property for trade',
            de: 'Sie bieten Eigentum zum Tausch an',
            pl: 'Oferujesz majątek do wymiany',
            zh: '您正在提供财产用于交换',
        },
        offersHint: {
            ru: 'Предлагает имущество для обмена',
            ua: 'Пропонує майно для обміну',
            en: 'Offers property for trade',
            de: 'Bietet Eigentum zum Tausch an',
            pl: 'Oferuje majątek do wymiany',
            zh: '提供交换财产',
        },
        commission: {
            ru: 'Комиссия',
            ua: 'Комісія',
            en: 'Fee',
            de: 'Gebühr',
            pl: 'Prowizja',
            zh: '手续费',
        },
        categories: {
            items: {
                ru: 'Предметы',
                ua: 'Предмети',
                en: 'Items',
                de: 'Gegenstände',
                pl: 'Przedmioty',
                zh: '物品',
            },
            vehicles: {
                ru: 'Транспорт',
                ua: 'Транспорт',
                en: 'Vehicles',
                de: 'Fahrzeuge',
                pl: 'Pojazdy',
                zh: '车辆',
            },
            houses: {
                ru: 'Дома',
                ua: 'Будинки',
                en: 'Houses',
                de: 'Häuser',
                pl: 'Domy',
                zh: '房屋',
            },
            businesses: {
                ru: 'Бизнессы',
                ua: 'Бізнеси',
                en: 'Businesses',
                de: 'Geschäfte',
                pl: 'Biznesy',
                zh: '企业',
            },
        },
        surchargePlaceholder: {
            ru: 'Доплата',
            ua: 'Доплата',
            en: 'Surcharge',
            de: 'Aufpreis',
            pl: 'Dopłata',
            zh: '附加费',
        },
        add: {
            ru: 'Добавить',
            ua: 'Додати',
            en: 'Add',
            de: 'Hinzufügen',
            pl: 'Dodaj',
            zh: '添加',
        },
        back: {
            ru: 'Назад',
            ua: 'Назад',
            en: 'Back',
            de: 'Zurück',
            pl: 'Wstecz',
            zh: '返回',
        },
        confirm: {
            ru: 'Подтвердить обмен',
            ua: 'Підтвердити обмін',
            en: 'Confirm trade',
            de: 'Tausch bestätigen',
            pl: 'Potwierdź wymianę',
            zh: '确认交换',
        },
        confirmed: {
            ru: 'Вы подтвердили обмен',
            ua: 'Ви підтвердили обмін',
            en: 'You confirmed the trade',
            de: 'Sie haben den Tausch bestätigt',
            pl: 'Potwierdziłeś wymianę',
            zh: '您已确认交换',
        },
        notConfirmed: {
            ru: 'Не подтвердил обмен',
            ua: 'Не підтвердив обмін',
            en: 'Has not confirmed the trade',
            de: 'Hat den Tausch nicht bestätigt',
            pl: 'Nie potwierdził wymiany',
            zh: '尚未确认交换',
        },
        otherConfirmed: {
            ru: 'Подтвердил обмен',
            ua: 'Підтвердив обмін',
            en: 'Confirmed the trade',
            de: 'Hat den Tausch bestätigt',
            pl: 'Potwierdził wymianę',
            zh: '已确认交换',
        },
        wait: {
            ru: 'Подождите',
            ua: 'Зачекайте',
            en: 'Wait',
            de: 'Warten',
            pl: 'Czekaj',
            zh: '请等待',
        },
        commissionPayer: {
            ru: 'Комиссию платит',
            ua: 'Комісію сплачує',
            en: 'Fee is paid by',
            de: 'Gebühr wird bezahlt von',
            pl: 'Prowizję płaci',
            zh: '手续费支付方',
        },
        side1: {
            ru: 'Сторона 1',
            ua: 'Сторона 1',
            en: 'Side 1',
            de: 'Seite 1',
            pl: 'Strona 1',
            zh: '第一方',
        },
        side2: {
            ru: 'Сторона 2',
            ua: 'Сторона 2',
            en: 'Side 2',
            de: 'Seite 2',
            pl: 'Strona 2',
            zh: '第二方',
        },
        half: {
            ru: '50/50',
            ua: '50/50',
            en: '50/50',
            de: '50/50',
            pl: '50/50',
            zh: '50/50',
        },
        hintFields: {
            name: {
                ru: 'Название',
                ua: 'Назва',
                en: 'Name',
                de: 'Name',
                pl: 'Nazwa',
                zh: '名称',
            },
            plate: {
                ru: 'Номер',
                ua: 'Номер',
                en: 'Plate',
                de: 'Kennzeichen',
                pl: 'Numer',
                zh: '车牌',
            },
            tuningCost: {
                ru: 'Стоимость тюнинга',
                ua: 'Вартість тюнінгу',
                en: 'Tuning cost',
                de: 'Tuningkosten',
                pl: 'Koszt tuningu',
                zh: '改装费用',
            },
            govPrice: {
                ru: 'Гос. стоимость',
                ua: 'Держ. вартість',
                en: 'Gov. price',
                de: 'Staatl. Preis',
                pl: 'Cena państwowa',
                zh: '政府估价',
            },
            insurance: {
                ru: 'Страховка',
                ua: 'Страховка',
                en: 'Insurance',
                de: 'Versicherung',
                pl: 'Ubezpieczenie',
                zh: '保险',
            },
            insuranceActive: {
                ru: 'до {{date}}',
                ua: 'до {{date}}',
                en: 'until {{date}}',
                de: 'bis {{date}}',
                pl: 'do {{date}}',
                zh: '至 {{date}}',
            },
            insuranceNone: {
                ru: 'Нет',
                ua: 'Немає',
                en: 'None',
                de: 'Keine',
                pl: 'Brak',
                zh: '无',
            },
            district: {
                ru: 'Район',
                ua: 'Район',
                en: 'District',
                de: 'Bezirk',
                pl: 'Dzielnica',
                zh: '区',
            },
            street: {
                ru: 'Улица',
                ua: 'Вулиця',
                en: 'Street',
                de: 'Straße',
                pl: 'Ulica',
                zh: '街道',
            },
            repairCost: {
                ru: 'Стоимость ремонта',
                ua: 'Вартість ремонту',
                en: 'Repair cost',
                de: 'Reparaturkosten',
                pl: 'Koszt naprawy',
                zh: '维修费用',
            },
            amount: {
                ru: 'Сумма',
                ua: 'Сума',
                en: 'Amount',
                de: 'Betrag',
                pl: 'Kwota',
                zh: '金额',
            },
            house: {
                ru: 'Дом',
                ua: 'Будинок',
                en: 'House',
                de: 'Haus',
                pl: 'Dom',
                zh: '房屋',
            },
            class: {
                ru: 'Класс',
                ua: 'Клас',
                en: 'Class',
                de: 'Klasse',
                pl: 'Klasa',
                zh: '等级',
            },
            money: {
                ru: 'Деньги',
                ua: 'Гроші',
                en: 'Money',
                de: 'Geld',
                pl: 'Pieniądze',
                zh: '金钱',
            },
            weight: {
                ru: 'Вес',
                ua: 'Вага',
                en: 'Weight',
                de: 'Gewicht',
                pl: 'Waga',
                zh: '重量',
            },
            weightUnit: {
                ru: 'кг',
                ua: 'кг',
                en: 'kg',
                de: 'kg',
                pl: 'kg',
                zh: 'kg',
            },
        },
    },
};
