export default {
    pages: {
        home: {
            tabName: {
                ru: 'Главная',
                ua: 'Головна',
                en: 'Home',
                de: 'Hauptseite',
                pl: 'Główna',
            },
            title: {
                ru: 'Боевой пропуск',
                ua: 'Бойовий пропуск',
                en: 'Battle Pass',
                de: 'Battle Pass',
                pl: 'Karnet bojowy',
            },
            titleBattle: {
                ru: 'Боевой',
                ua: 'Бойовий',
                en: 'Battle',
                de: 'Battle',
                pl: 'Bojowy',
            },
            titlePass: {
                ru: 'Пропуск',
                ua: 'Пропуск',
                en: 'Pass',
                de: 'Pass',
                pl: 'Karnet',
            },
            description: {
                ru: 'Открывайте уникальные награды за прохождение уровней. Выполняйте задания и получайте опыт.',
                ua: 'Відкривайте унікальні нагороди за проходження рівнів. Виконуйте завдання та отримуйте досвід.',
                en: 'Unlock unique rewards as you level up. Complete tasks and gain experience.',
                de: 'Schalte einzigartige Belohnungen frei, indem du Level aufsteigst. Erfülle Aufgaben und sammle Erfahrung.',
                pl: 'Odblokowuj unikalne nagrody, awansując na kolejne poziomy. Wykonuj zadania i zdobywaj doświadczenie.',
            },
        },
        upgrade: {
            tabName: {
                ru: 'Улучшение пропуска',
                ua: 'Покращення пропуску',
                en: 'Pass upgrade',
                de: 'Pass-Upgrade',
                pl: 'Ulepszenie przepustki',
            },
            title: {
                ru: 'Улучшение пропуска',
                ua: 'Покращення пропуску',
                en: 'Pass upgrade',
                de: 'Pass-Upgrade',
                pl: 'Ulepszenie przepustki',
            },
            description: {
                ru: 'Получите больше наград и эксклюзивные призы, открыв премиум-уровень пропуска.',
                ua: 'Отримайте більше нагород та ексклюзивні призи, відкривши преміум-рівень пропуску.',
                en: 'Get more rewards and exclusive prizes by unlocking the premium pass tier.',
                de: 'Erhalte mehr Belohnungen und exklusive Preise, indem du die Premium-Stufe des Passes freischaltest.',
                pl: 'Zdobądź więcej nagród i ekskluzywne prezenty, odblokowując poziom premium przepustki.',
            },
            passWord: {
                ru: 'пропуск',
                ua: 'пропуск',
                en: 'pass',
                de: 'Pass',
                pl: 'przepustka',
            },
            starterDescription: {
                ru: 'Вам доступны награды только в верхней ленте. Улучшите пропуск чтобы получить более ценные награды.',
                ua: 'Вам доступні нагороди лише у верхній стрічці. Покращте пропуск, щоб отримати більш цінні нагороди.',
                en: 'You only get rewards from the top track. Upgrade the pass to unlock more valuable rewards.',
                de: 'Du erhältst nur Belohnungen aus der oberen Spur. Verbessere den Pass, um wertvollere Belohnungen freizuschalten.',
                pl: 'Otrzymujesz nagrody tylko z górnego toru. Ulepsz przepustkę, aby odblokować cenniejsze nagrody.',
            },
            unlockTo: {
                ru: 'Открывает доступ к',
                ua: 'Відкриває доступ до',
                en: 'Unlocks access to',
                de: 'Schaltet den Zugang frei zu',
                pl: 'Odblokowuje dostęp do',
            },
            unlockRange: {
                ru: '1-{{max}} Премиум уровням',
                ua: '1-{{max}} Преміум рівням',
                en: '1-{{max}} Premium levels',
                de: '1-{{max}} Premium-Level',
                pl: '1-{{max}} poziomów Premium',
            },
            refreshPrefix: {
                ru: 'Смена заданий раз в',
                ua: 'Зміна завдань раз на',
                en: 'Tasks refresh every',
                de: 'Aufgaben werden alle',
                pl: 'Zmiana zadań co',
            },
            refreshValue: {
                ru: '{{hours}} часов',
                ua: '{{hours}} годин',
                en: '{{hours}} hours',
                de: '{{hours}} Stunden',
                pl: '{{hours}} godzin',
            },
            startFree: {
                ru: 'Начать бесплатно',
                ua: 'Почати безкоштовно',
                en: 'Start for free',
                de: 'Kostenlos starten',
                pl: 'Zacznij za darmo',
            },
            buy: {
                ru: 'Купить',
                ua: 'Купити',
                en: 'Buy',
                de: 'Kaufen',
                pl: 'Kup',
            },
            active: {
                ru: 'Активно',
                ua: 'Активно',
                en: 'Active',
                de: 'Aktiv',
                pl: 'Aktywne',
            },
            level: {
                ru: 'Уровень {{level}}',
                ua: 'Рівень {{level}}',
                en: 'Level {{level}}',
                de: 'Level {{level}}',
                pl: 'Poziom {{level}}',
            },
            noShowcase: {
                ru: 'Скоро здесь появятся награды',
                ua: 'Скоро тут з’являться нагороди',
                en: 'Rewards coming soon',
                de: 'Bald gibt es hier Belohnungen',
                pl: 'Wkrótce pojawią się nagrody',
            },
        },
        buyXp: {
            tabName: {
                ru: 'Купить опыт',
                ua: 'Купити досвід',
                en: 'Buy XP',
                de: 'XP kaufen',
                pl: 'Kup XP',
            },
            title: {
                ru: 'Покупка опыта',
                ua: 'Купівля досвіду',
                en: 'Buy experience',
                de: 'Erfahrung kaufen',
                pl: 'Kupowanie doświadczenia',
            },
            description: {
                ru: 'Ускорьте прогресс пропуска, купив дополнительный опыт за внутриигровую валюту или донат.',
                ua: 'Прискорте прогрес пропуску, купивши додатковий досвід за внутрішньоігрову валюту або донат.',
                en: 'Speed up pass progression by buying extra experience for in-game currency or donate.',
                de: 'Beschleunige den Pass-Fortschritt, indem du zusätzliche Erfahrung für Spielwährung oder Spenden kaufst.',
                pl: 'Przyspiesz postęp przepustki, kupując dodatkowe doświadczenie za walutę w grze lub donat.',
            },
        },
        quests: {
            tabName: {
                ru: 'Задания',
                ua: 'Завдання',
                en: 'Quests',
                de: 'Aufträge',
                pl: 'Zadania',
            },
            title: {
                ru: 'Задания пропуска',
                ua: 'Завдання пропуску',
                en: 'Pass quests',
                de: 'Pass-Aufgaben',
                pl: 'Zadania przepustki',
            },
            description: {
                ru: 'Выполняйте ежедневные и сезонные задания, чтобы получить дополнительный опыт пропуска.',
                ua: 'Виконуйте щоденні та сезонні завдання, щоб отримати додатковий досвід пропуску.',
                en: 'Complete daily and seasonal quests to earn extra battle pass experience.',
                de: 'Erfülle tägliche und saisonale Aufgaben, um zusätzliche Pass-Erfahrung zu erhalten.',
                pl: 'Wykonuj codzienne i sezonowe zadania, aby zdobyć dodatkowe doświadczenie przepustki.',
            },
        },
        rating: {
            tabName: {
                ru: 'Рейтинг',
                ua: 'Рейтинг',
                en: 'Rating',
                de: 'Wertung',
                pl: 'Ranking',
            },
            title: {
                ru: 'Рейтинг сезона',
                ua: 'Рейтинг сезону',
                en: 'Season rating',
                de: 'Saisonwertung',
                pl: 'Ranking sezonu',
            },
            description: {
                ru: 'Соревнуйтесь с другими игроками за лучшие места в общем рейтинге пропуска сезона.',
                ua: 'Змагайтеся з іншими гравцями за найкращі місця у загальному рейтингу пропуску сезону.',
                en: 'Compete with other players for top spots in the overall season pass leaderboard.',
                de: 'Tritt gegen andere Spieler in der Gesamtrangliste des Saisonpasses an.',
                pl: 'Rywalizuj z innymi graczami o najwyższe miejsca w ogólnym rankingu przepustki sezonu.',
            },
        },
    },
    tiers: {
        none: {
            ru: 'Нет пропуска',
            ua: 'Немає пропуску',
            en: 'No pass',
            de: 'Kein Pass',
            pl: 'Brak przepustki',
        },
        free: {
            ru: 'Базовый',
            ua: 'Базовий',
            en: 'Free',
            de: 'Kostenlos',
            pl: 'Darmowy',
        },
        starter: {
            ru: 'Стартовый',
            ua: 'Стартовий',
            en: 'Starter',
            de: 'Starter',
            pl: 'Startowy',
        },
        bronze: {
            ru: 'Бронзовый',
            ua: 'Бронзовий',
            en: 'Bronze',
            de: 'Bronze',
            pl: 'Brązowy',
        },
        silver: {
            ru: 'Серебряный',
            ua: 'Срібний',
            en: 'Silver',
            de: 'Silber',
            pl: 'Srebrny',
        },
        gold: {
            ru: 'Золотой',
            ua: 'Золотий',
            en: 'Gold',
            de: 'Gold',
            pl: 'Złoty',
        },
    },
    sidebar: {
        upgrade: {
            ru: 'Улучшить',
            ua: 'Покращити',
            en: 'Upgrade',
            de: 'Verbessern',
            pl: 'Ulepsz',
        },
        xpToNext: {
            ru: 'Опыта для повышения уровня',
            ua: 'Досвіду для підвищення рівня',
            en: 'XP to next level',
            de: 'XP bis zum nächsten Level',
            pl: 'XP do następnego poziomu',
        },
        premiumLevels: {
            ru: 'Премиум уровни',
            ua: 'Преміум рівні',
            en: 'Premium levels',
            de: 'Premium-Level',
            pl: 'Poziomy premium',
        },
    },
    lines: {
        free: {
            ru: 'Обычный',
            ua: 'Звичайний',
            en: 'Regular',
            de: 'Normal',
            pl: 'Zwykły',
        },
        premium: {
            ru: 'Премиум',
            ua: 'Преміум',
            en: 'Premium',
            de: 'Premium',
            pl: 'Premium',
        },
    },
    controls: {
        myLevel: {
            ru: 'Мой уровень',
            ua: 'Мій рівень',
            en: 'My level',
            de: 'Mein Level',
            pl: 'Mój poziom',
        },
    },
    progressBar: {
        purchaseLevel: {
            ru: 'Купить {{level}} уровень',
            ua: 'Купити {{level}} рівень',
            en: 'Buy level {{level}}',
            de: 'Level {{level}} kaufen',
            pl: 'Kup poziom {{level}}',
        },
    },
    timer: {
        endsIn: {
            ru: 'Событие завершается через',
            ua: 'Подія завершується через',
            en: 'Event ends in',
            de: 'Event endet in',
            pl: 'Wydarzenie kończy się za',
        },
        daysWord: {
            ru: 'дней',
            ua: 'днів',
            en: 'days',
            de: 'Tage',
            pl: 'dni',
        },
    },
    freeXp: {
        title: {
            ru: '{{hours}} часов игры = {{xp}} опыта',
            ua: '{{hours}} годин гри = {{xp}} досвіду',
            en: '{{hours}} hours played = {{xp}} XP',
            de: '{{hours}} Stunden Spielzeit = {{xp}} XP',
            pl: '{{hours}} godzin gry = {{xp}} XP',
        },
        claim: {
            ru: 'Забрать',
            ua: 'Забрати',
            en: 'Claim',
            de: 'Abholen',
            pl: 'Odbierz',
        },
        claimableIn: {
            ru: 'Можно забрать через',
            ua: 'Можна забрати через',
            en: 'Available in',
            de: 'Verfügbar in',
            pl: 'Dostępne za',
        },
    },
    rewards: {
        claim: {
            ru: 'Забрать',
            ua: 'Забрати',
            en: 'Claim',
            de: 'Abholen',
            pl: 'Odbierz',
        },
        sell: {
            ru: 'Продать',
            ua: 'Продати',
            en: 'Sell',
            de: 'Verkaufen',
            pl: 'Sprzedaj',
        },
        warehouse: {
            ru: 'На склад',
            ua: 'На склад',
            en: 'To warehouse',
            de: 'Ins Lager',
            pl: 'Do magazynu',
        },
        qtyShort: {
            ru: 'шт.',
            ua: 'шт.',
            en: 'pcs',
            de: 'St.',
            pl: 'szt.',
        },
        days: {
            ru: 'д.',
            ua: 'д.',
            en: 'd',
            de: 'T.',
            pl: 'd.',
        },
        claimSelf: {
            ru: 'Забрать себе',
            ua: 'Забрати собі',
            en: 'Claim for yourself',
            de: 'Für sich nehmen',
            pl: 'Weź dla siebie',
        },
        breakdown: {
            ru: 'Разобрать на',
            ua: 'Розібрати на',
            en: 'Disassemble for',
            de: 'Zerlegen für',
            pl: 'Rozłóż na',
        },
        toDonateInventory: {
            ru: 'Отложить в донат инвентарь',
            ua: 'Відкласти в донат інвентар',
            en: 'Save to donate inventory',
            de: 'In Donate-Inventar legen',
            pl: 'Odłóż do inwentarza donate',
        },
        sellForXp: {
            ru: 'Продать за',
            ua: 'Продати за',
            en: 'Sell for',
            de: 'Verkaufen für',
            pl: 'Sprzedaj za',
        },
    },
    categories: {
        default: {
            ru: 'Награда',
            ua: 'Нагорода',
            en: 'Reward',
            de: 'Belohnung',
            pl: 'Nagroda',
        },
        currency: {
            ru: 'Деньги',
            ua: 'Гроші',
            en: 'Cash',
            de: 'Geld',
            pl: 'Pieniądze',
        },
        donate: {
            ru: 'Монеты',
            ua: 'Монети',
            en: 'Coins',
            de: 'Münzen',
            pl: 'Monety',
        },
        experience: {
            ru: 'Опыт',
            ua: 'Досвід',
            en: 'Experience',
            de: 'Erfahrung',
            pl: 'Doświadczenie',
        },
        cases: {
            ru: 'Кейс',
            ua: 'Кейс',
            en: 'Case',
            de: 'Kiste',
            pl: 'Skrzynka',
        },
        vehicles: {
            ru: 'Транспорт',
            ua: 'Транспорт',
            en: 'Vehicle',
            de: 'Fahrzeug',
            pl: 'Pojazd',
        },
        skins: {
            ru: 'Скин',
            ua: 'Скін',
            en: 'Skin',
            de: 'Skin',
            pl: 'Skórka',
        },
        statuses: {
            ru: 'Статус',
            ua: 'Статус',
            en: 'Status',
            de: 'Status',
            pl: 'Status',
        },
        animations: {
            ru: 'Анимация',
            ua: 'Анімація',
            en: 'Animation',
            de: 'Animation',
            pl: 'Animacja',
        },
        features: {
            ru: 'Особенность',
            ua: 'Особливість',
            en: 'Feature',
            de: 'Funktion',
            pl: 'Funkcja',
        },
        weapon: {
            ru: 'Оружие',
            ua: 'Зброя',
            en: 'Weapon',
            de: 'Waffe',
            pl: 'Broń',
        },
        ammo: {
            ru: 'Патроны',
            ua: 'Патрони',
            en: 'Ammo',
            de: 'Munition',
            pl: 'Amunicja',
        },
        clothes: {
            ru: 'Одежда',
            ua: 'Одяг',
            en: 'Clothing',
            de: 'Kleidung',
            pl: 'Odzież',
        },
        backpack: {
            ru: 'Одежда',
            ua: 'Одяг',
            en: 'Clothing',
            de: 'Kleidung',
            pl: 'Odzież',
        },
        blueprint: {
            ru: 'Чертёж',
            ua: 'Креслення',
            en: 'Blueprint',
            de: 'Bauplan',
            pl: 'Schemat',
        },
        item: {
            ru: 'Предмет',
            ua: 'Предмет',
            en: 'Item',
            de: 'Gegenstand',
            pl: 'Przedmiot',
        },
    },
    featured: {
        title: {
            ru: 'Главные призы',
            ua: 'Головні призи',
            en: 'Featured prizes',
            de: 'Hauptpreise',
            pl: 'Główne nagrody',
        },
    },
    seasons: {
        summer: {
            name: {
                ru: 'Боевой пропуск',
                ua: 'Бойовий пропуск',
                en: 'Battle Pass',
                de: 'Battle Pass',
                pl: 'Karnet bojowy',
            },
            description: {
                ru: 'Открывайте уникальные награды за прохождение уровней. Выполняйте задания и получайте опыт.',
                ua: 'Відкривайте унікальні нагороди за проходження рівнів. Виконуйте завдання та отримуйте досвід.',
                en: 'Unlock unique rewards as you level up. Complete tasks and gain experience.',
                de: 'Schalte einzigartige Belohnungen frei, indem du Level aufsteigst. Erfülle Aufgaben und sammle Erfahrung.',
                pl: 'Odblokowuj unikalne nagrody, awansując na kolejne poziomy. Wykonuj zadania i zdobywaj doświadczenie.',
            },
        },
    },
    rewardNames: {
        animation: {
            ru: 'Анимация',
            ua: 'Анімація',
            en: 'Animation',
            de: 'Animation',
            pl: 'Animacja',
        },
    },
    placeholder: {
        wip: {
            ru: 'В разработке',
            ua: 'В розробці',
            en: 'Work in progress',
            de: 'In Bearbeitung',
            pl: 'W trakcie prac',
        },
    },
};
