export default {
    pages: {
        home: {
            ru: 'Главная',
            ua: 'Головна',
            en: 'Home',
            de: 'Hauptseite',
            pl: 'Główna',
        },
        upgrade: {
            ru: 'Улучшение пропуска',
            ua: 'Покращення пропуску',
            en: 'Pass upgrade',
            de: 'Pass-Upgrade',
            pl: 'Ulepszenie przepustki',
        },
        buyXp: {
            ru: 'Купить опыт',
            ua: 'Купити досвід',
            en: 'Buy XP',
            de: 'XP kaufen',
            pl: 'Kup XP',
        },
        quests: {
            ru: 'Задания',
            ua: 'Завдання',
            en: 'Quests',
            de: 'Aufträge',
            pl: 'Zadania',
        },
        rating: {
            ru: 'Рейтинг',
            ua: 'Рейтинг',
            en: 'Rating',
            de: 'Wertung',
            pl: 'Ranking',
        },
    },
    tiers: {
        free: {
            ru: 'Базовый',
            ua: 'Базовий',
            en: 'Free',
            de: 'Kostenlos',
            pl: 'Darmowy',
        },
        silver: {
            ru: 'Серебряный',
            ua: 'Срібний',
            en: 'Silver',
            de: 'Silber',
            pl: 'Srebrny',
        },
        gold: {
            ru: 'Золотой',
            ua: 'Золотий',
            en: 'Gold',
            de: 'Gold',
            pl: 'Złoty',
        },
    },
    sidebar: {
        subscription: {
            ru: 'Подписка',
            ua: 'Підписка',
            en: 'Subscription',
            de: 'Abonnement',
            pl: 'Subskrypcja',
        },
        upgrade: {
            ru: 'Улучшить пропуск',
            ua: 'Покращити пропуск',
            en: 'Upgrade pass',
            de: 'Pass verbessern',
            pl: 'Ulepsz przepustkę',
        },
    },
    lines: {
        free: {
            ru: 'Обычный',
            ua: 'Звичайний',
            en: 'Regular',
            de: 'Normal',
            pl: 'Zwykły',
        },
        premium: {
            ru: 'Премиум',
            ua: 'Преміум',
            en: 'Premium',
            de: 'Premium',
            pl: 'Premium',
        },
    },
    controls: {
        myLevel: {
            ru: 'Мой уровень',
            ua: 'Мій рівень',
            en: 'My level',
            de: 'Mein Level',
            pl: 'Mój poziom',
        },
    },
    timer: {
        days: {
            ru: 'дней',
            ua: 'днів',
            en: 'days',
            de: 'Tage',
            pl: 'dni',
        },
        hours: {
            ru: 'часов',
            ua: 'годин',
            en: 'hours',
            de: 'Stunden',
            pl: 'godzin',
        },
        minutes: {
            ru: 'минут',
            ua: 'хвилин',
            en: 'minutes',
            de: 'Minuten',
            pl: 'minut',
        },
    },
    freeXp: {
        title: {
            ru: '5 часов игры = 500 опыта',
            ua: '5 годин гри = 500 досвіду',
            en: '5 hours played = 500 XP',
            de: '5 Stunden Spielzeit = 500 XP',
            pl: '5 godzin gry = 500 XP',
        },
        claim: {
            ru: 'Забрать',
            ua: 'Забрати',
            en: 'Claim',
            de: 'Abholen',
            pl: 'Odbierz',
        },
    },
    rewards: {
        claim: {
            ru: 'Забрать',
            ua: 'Забрати',
            en: 'Claim',
            de: 'Abholen',
            pl: 'Odbierz',
        },
        sell: {
            ru: 'Продать',
            ua: 'Продати',
            en: 'Sell',
            de: 'Verkaufen',
            pl: 'Sprzedaj',
        },
        warehouse: {
            ru: 'На склад',
            ua: 'На склад',
            en: 'To warehouse',
            de: 'Ins Lager',
            pl: 'Do magazynu',
        },
        qtyShort: {
            ru: 'шт.',
            ua: 'шт.',
            en: 'pcs',
            de: 'St.',
            pl: 'szt.',
        },
        days: {
            ru: 'д.',
            ua: 'д.',
            en: 'd',
            de: 'T.',
            pl: 'd.',
        },
    },
    featured: {
        title: {
            ru: 'Главные призы',
            ua: 'Головні призи',
            en: 'Featured prizes',
            de: 'Hauptpreise',
            pl: 'Główne nagrody',
        },
    },
    seasons: {
        summer: {
            name: {
                ru: 'Боевой пропуск',
                ua: 'Бойовий пропуск',
                en: 'Battle Pass',
                de: 'Battle Pass',
                pl: 'Karnet bojowy',
            },
            description: {
                ru: 'Открывайте уникальные награды за прохождение уровней. Выполняйте задания и получайте опыт.',
                ua: 'Відкривайте унікальні нагороди за проходження рівнів. Виконуйте завдання та отримуйте досвід.',
                en: 'Unlock unique rewards as you level up. Complete tasks and gain experience.',
                de: 'Schalte einzigartige Belohnungen frei, indem du Level aufsteigst. Erfülle Aufgaben und sammle Erfahrung.',
                pl: 'Odblokowuj unikalne nagrody, awansując na kolejne poziomy. Wykonuj zadania i zdobywaj doświadczenie.',
            },
        },
    },
    rewardNames: {
        animation: {
            ru: 'Анимация',
            ua: 'Анімація',
            en: 'Animation',
            de: 'Animation',
            pl: 'Animacja',
        },
    },
};
