export default {
    pages: {
        home: {
            tabName: {
                ru: 'Главная',
                ua: 'Головна',
                en: 'Home',
                de: 'Hauptseite',
                pl: 'Główna',
            },
            title: {
                ru: 'Боевой пропуск',
                ua: 'Бойовий пропуск',
                en: 'Battle Pass',
                de: 'Battle Pass',
                pl: 'Karnet bojowy',
            },
            titleBattle: {
                ru: 'Боевой',
                ua: 'Бойовий',
                en: 'Battle',
                de: 'Battle',
                pl: 'Bojowy',
            },
            titlePass: {
                ru: 'Пропуск',
                ua: 'Пропуск',
                en: 'Pass',
                de: 'Pass',
                pl: 'Karnet',
            },
            description: {
                ru: 'Встречайте наш первый боевой пропуск!\nВыполняйте задания и получайте уникальные награды.',
                ua: 'Зустрічайте наш перший бойовий пропуск!\nВиконуйте завдання та отримуйте унікальні нагороди.',
                en: 'Meet our very first battle pass!\nComplete quests and earn unique rewards.',
                de: 'Lernt unseren ersten Battle Pass kennen!\nErfüllt Aufgaben und erhaltet einzigartige Belohnungen.',
                pl: 'Poznajcie naszą pierwszą przepustkę bojową!\nWykonuj zadania i zdobywaj wyjątkowe nagrody.',
            },
        },
        upgrade: {
            tabName: {
                ru: 'Улучшение пропуска',
                ua: 'Покращення пропуску',
                en: 'Pass upgrade',
                de: 'Pass-Upgrade',
                pl: 'Ulepszenie przepustki',
            },
            title: {
                ru: 'Улучшение пропуска',
                ua: 'Покращення пропуску',
                en: 'Pass upgrade',
                de: 'Pass-Upgrade',
                pl: 'Ulepszenie przepustki',
            },
            description: {
                ru: 'Откройте полный потенциал пропуска!\nВыбирайте свой тир и забирайте эксклюзивные премиум-награды.',
                ua: 'Розкрийте повний потенціал пропуску!\nОбирайте свій тир і забирайте ексклюзивні преміум-нагороди.',
                en: 'Unlock the full potential of your pass!\nChoose your tier and claim exclusive premium rewards.',
                de: 'Entfaltet das volle Potenzial des Passes!\nWähle deine Stufe und sichere dir exklusive Premium-Belohnungen.',
                pl: 'Odkryj pełny potencjał przepustki!\nWybierz swój poziom i zgarnij ekskluzywne nagrody premium.',
            },
            passWord: {
                ru: 'пропуск',
                ua: 'пропуск',
                en: 'pass',
                de: 'Pass',
                pl: 'przepustka',
            },
            starterDescription: {
                ru: 'Вам доступны награды только в верхней ленте. Улучшите пропуск чтобы получить более ценные награды.',
                ua: 'Вам доступні нагороди лише у верхній стрічці. Покращте пропуск, щоб отримати більш цінні нагороди.',
                en: 'You only get rewards from the top track. Upgrade the pass to unlock more valuable rewards.',
                de: 'Du erhältst nur Belohnungen aus der oberen Spur. Verbessere den Pass, um wertvollere Belohnungen freizuschalten.',
                pl: 'Otrzymujesz nagrody tylko z górnego toru. Ulepsz przepustkę, aby odblokować cenniejsze nagrody.',
            },
            unlockTo: {
                ru: 'Открывает доступ к',
                ua: 'Відкриває доступ до',
                en: 'Unlocks access to',
                de: 'Schaltet den Zugang frei zu',
                pl: 'Odblokowuje dostęp do',
            },
            unlockRange: {
                ru: '1-{{max}} Премиум уровням',
                ua: '1-{{max}} Преміум рівням',
                en: '1-{{max}} Premium levels',
                de: '1-{{max}} Premium-Level',
                pl: '1-{{max}} poziomów Premium',
            },
            refreshPrefix: {
                ru: 'Смена заданий раз в',
                ua: 'Зміна завдань раз на',
                en: 'Tasks refresh every',
                de: 'Aufgaben werden alle',
                pl: 'Zmiana zadań co',
            },
            refreshValue: {
                ru: '{{hours}} часов',
                ua: '{{hours}} годин',
                en: '{{hours}} hours',
                de: '{{hours}} Stunden',
                pl: '{{hours}} godzin',
            },
            startFree: {
                ru: 'Начать бесплатно',
                ua: 'Почати безкоштовно',
                en: 'Start for free',
                de: 'Kostenlos starten',
                pl: 'Zacznij za darmo',
            },
            buy: {
                ru: 'Купить',
                ua: 'Купити',
                en: 'Buy',
                de: 'Kaufen',
                pl: 'Kup',
            },
            active: {
                ru: 'Активно',
                ua: 'Активно',
                en: 'Active',
                de: 'Aktiv',
                pl: 'Aktywne',
            },
            level: {
                ru: 'Уровень {{level}}',
                ua: 'Рівень {{level}}',
                en: 'Level {{level}}',
                de: 'Level {{level}}',
                pl: 'Poziom {{level}}',
            },
            noShowcase: {
                ru: 'Скоро здесь появятся награды',
                ua: 'Скоро тут з’являться нагороди',
                en: 'Rewards coming soon',
                de: 'Bald gibt es hier Belohnungen',
                pl: 'Wkrótce pojawią się nagrody',
            },
            confirmModalTitle: {
                ru: 'Подтверждение покупки пропуска',
                ua: 'Підтвердження купівлі пропуску',
                en: 'Confirm pass purchase',
                de: 'Pass-Kauf bestätigen',
                pl: 'Potwierdzenie zakupu przepustki',
            },
            confirmButton: {
                ru: 'Купить',
                ua: 'Купити',
                en: 'Buy',
                de: 'Kaufen',
                pl: 'Kup',
            },
            cancelButton: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
            modalBody: {
                buy: {
                    ru: 'Купить',
                    ua: 'Купити',
                    en: 'Buy',
                    de: 'Kaufen',
                    pl: 'Kup',
                },
                for: {
                    ru: 'за',
                    ua: 'за',
                    en: 'for',
                    de: 'für',
                    pl: 'za',
                },
            },
        },
        buyXp: {
            tabName: {
                ru: 'Купить опыт',
                ua: 'Купити досвід',
                en: 'Buy XP',
                de: 'XP kaufen',
                pl: 'Kup XP',
            },
            title: {
                ru: 'Покупка опыта',
                ua: 'Купівля досвіду',
                en: 'Buy experience',
                de: 'Erfahrung kaufen',
                pl: 'Kupowanie doświadczenia',
            },
            description: {
                ru: 'Не хватает времени, но хочется наград?\nКупите опыт пропуска и быстро доберитесь до нужных уровней.',
                ua: 'Не вистачає часу, але хочеться нагород?\nКупіть досвід пропуску й швидко дістаньтеся потрібних рівнів.',
                en: 'Short on time but want the rewards?\nBuy battle pass XP and quickly reach the levels you need.',
                de: 'Wenig Zeit, aber Lust auf Belohnungen?\nKaufe Pass-Erfahrung und erreiche schnell die gewünschten Level.',
                pl: 'Brakuje czasu, a chcesz nagród?\nKup doświadczenie przepustki i szybko dotrzyj do potrzebnych poziomów.',
            },
            maxLevelTitle: {
                ru: 'Купить до {{level}} уровня',
                ua: 'Купити до {{level}} рівня',
                en: 'Buy up to level {{level}}',
                de: 'Bis Level {{level}} kaufen',
                pl: 'Kup do poziomu {{level}}',
            },
            maxLevelDescription: {
                ru: 'Это самое простое и выгодное решение купить все недостающие уровни боевого пропуска',
                ua: 'Це найпростіше і найвигідніше рішення купити всі відсутні рівні бойового пропуску',
                en: 'The simplest and best value way to buy every missing battle pass level',
                de: 'Der einfachste und günstigste Weg, alle fehlenden Battle-Pass-Level zu kaufen',
                pl: 'Najprostszy i najbardziej opłacalny sposób na zakup wszystkich brakujących poziomów karnetu bojowego',
            },
            modalTitle: {
                ru: 'EXP для Боевого Пропуска {{year}}',
                ua: 'EXP для Бойового Пропуску {{year}}',
                en: 'EXP for Battle Pass {{year}}',
                de: 'EXP für Battle Pass {{year}}',
                pl: 'EXP do Karnetu Bojowego {{year}}',
            },
            modalBody: {
                buy: {
                    ru: 'Купить',
                    ua: 'Купити',
                    en: 'Buy',
                    de: 'Kaufen',
                    pl: 'Kup',
                },
                for: {
                    ru: 'за',
                    ua: 'за',
                    en: 'for',
                    de: 'für',
                    pl: 'za',
                },
            },
            confirmButton: {
                ru: 'Купить',
                ua: 'Купити',
                en: 'Buy',
                de: 'Kaufen',
                pl: 'Kup',
            },
            cancelButton: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
        },
        quests: {
            tabName: {
                ru: 'Задания',
                ua: 'Завдання',
                en: 'Quests',
                de: 'Aufträge',
                pl: 'Zadania',
            },
            title: {
                ru: 'Задания пропуска',
                ua: 'Завдання пропуску',
                en: 'Pass quests',
                de: 'Pass-Aufgaben',
                pl: 'Zadania przepustki',
            },
            description: {
                ru: 'Ваш список целей на сегодня.\nВыполняйте задания и зарабатывайте опыт пропуска.',
                ua: 'Ваш список цілей на сьогодні.\nВиконуйте завдання та заробляйте досвід пропуску.',
                en: 'Your goals for today.\nComplete quests and earn battle pass experience.',
                de: 'Deine Ziele für heute.\nErfülle Aufgaben und verdiene Pass-Erfahrung.',
                pl: 'Twoja lista celów na dziś.\nWykonuj zadania i zdobywaj doświadczenie przepustki.',
            },
            refreshIn: {
                ru: 'До обновления списка заданий',
                ua: 'До оновлення списку завдань',
                en: 'Until task list refresh',
                de: 'Bis zur Aktualisierung der Aufgabenliste',
                pl: 'Do odświeżenia listy zadań',
            },
            refreshNow: {
                ru: 'Обновить сейчас',
                ua: 'Оновити зараз',
                en: 'Refresh now',
                de: 'Jetzt aktualisieren',
                pl: 'Odśwież teraz',
            },
            reward: {
                ru: 'Награда',
                ua: 'Нагорода',
                en: 'Reward',
                de: 'Belohnung',
                pl: 'Nagroda',
            },
            replace: {
                ru: 'Заменить',
                ua: 'Замінити',
                en: 'Replace',
                de: 'Ersetzen',
                pl: 'Zamień',
            },
            track: {
                ru: 'Отслеживать',
                ua: 'Відстежувати',
                en: 'Track',
                de: 'Verfolgen',
                pl: 'Śledź',
            },
            untrack: {
                ru: 'Не отслеживать',
                ua: 'Не відстежувати',
                en: 'Untrack',
                de: 'Nicht verfolgen',
                pl: 'Nie śledź',
            },
            // Mock copy used while no real task data is wired up; remove once backend feeds tasks.
            demoTitle: {
                ru: 'Во все тяжкие',
                ua: 'У всі тяжкі',
                en: 'Breaking Bad',
                de: 'Breaking Bad',
                pl: 'Breaking Bad',
            },
            demoDescription: {
                ru: 'Отрастить бородку и побриться налысо, а потом идти варить мет прямо в пустыне.',
                ua: 'Відростити борідку і поголитись налисо, а потім іти варити мет прямо в пустелі.',
                en: 'Grow a goatee, shave your head, and head out to cook meth in the desert.',
                de: 'Lass dir einen Spitzbart wachsen, rasiere dir den Kopf und koche dann Meth in der Wüste.',
                pl: 'Zapuść kozią bródkę, ogol głowę na łyso i jedź gotować metę na pustynię.',
            },
            demoTitle2: {
                ru: 'Городской бегун',
                ua: 'Міський бігун',
                en: 'City Runner',
                de: 'Stadtläufer',
                pl: 'Miejski biegacz',
            },
            demoDescription2: {
                ru: 'Преодолейте 10 километров пешком, исследуя улицы Лос-Сантоса.',
                ua: 'Подолайте 10 кілометрів пішки, досліджуючи вулиці Лос-Сантоса.',
                en: 'Cover 10 kilometers on foot exploring the streets of Los Santos.',
                de: 'Lege 10 Kilometer zu Fuß zurück und erkunde die Straßen von Los Santos.',
                pl: 'Pokonaj 10 kilometrów pieszo, zwiedzając ulice Los Santos.',
            },
            demoTitle3: {
                ru: 'Нужен ствол',
                ua: 'Потрібен ствол',
                en: 'Need a Gun',
                de: 'Brauche eine Knarre',
                pl: 'Potrzebny gnat',
            },
            demoDescription3: {
                ru: 'Загляните в оружейный магазин и купите любой огнестрел.',
                ua: 'Завітайте до збройного магазину та купіть будь-яку вогнепальну зброю.',
                en: 'Drop by the gun store and purchase any firearm.',
                de: 'Schau im Waffenladen vorbei und kaufe eine beliebige Schusswaffe.',
                pl: 'Wpadnij do sklepu z bronią i kup dowolną broń palną.',
            },
            demoTitle4: {
                ru: 'Заядлый гонщик',
                ua: 'Завзятий гонщик',
                en: 'Avid Racer',
                de: 'Begeisterter Rennfahrer',
                pl: 'Zapalony kierowca',
            },
            demoDescription4: {
                ru: 'Пройдите 3 заезда на любой гоночной трассе и поднимитесь в топ-3.',
                ua: 'Пройдіть 3 заїзди на будь-якій гоночній трасі та потрапте в топ-3.',
                en: 'Complete 3 races on any track and finish in the top 3.',
                de: 'Absolviere 3 Rennen auf einer beliebigen Strecke und lande in den Top 3.',
                pl: 'Ukończ 3 wyścigi na dowolnym torze i znajdź się w pierwszej trójce.',
            },
            demoTitle5: {
                ru: 'Рыбный день',
                ua: 'Рибний день',
                en: 'Fish Day',
                de: 'Fischtag',
                pl: 'Dzień ryby',
            },
            demoDescription5: {
                ru: 'Поймайте 15 рыб любого вида в любом водоёме штата Сан-Андреас.',
                ua: 'Зловіть 15 риб будь-якого виду в будь-якій водоймі штату Сан-Андреас.',
                en: 'Catch 15 fish of any kind in any body of water in San Andreas.',
                de: 'Fange 15 beliebige Fische in einem beliebigen Gewässer in San Andreas.',
                pl: 'Złów 15 ryb dowolnego gatunku w dowolnym akwenie w San Andreas.',
            },
            demoTitle6: {
                ru: 'Ночной гость',
                ua: 'Нічний гість',
                en: 'Night Guest',
                de: 'Nachtgast',
                pl: 'Nocny gość',
            },
            demoDescription6: {
                ru: 'Загляните в один из ночных клубов города и проведите там не меньше часа.',
                ua: 'Завітайте до одного з нічних клубів міста та проведіть там щонайменше годину.',
                en: 'Visit one of the city nightclubs and spend at least an hour there.',
                de: 'Besuche einen der Nachtclubs der Stadt und verbringe dort mindestens eine Stunde.',
                pl: 'Odwiedź jeden z nocnych klubów w mieście i spędź tam co najmniej godzinę.',
            },
            demoTitle7: {
                ru: 'Помощь товарищу',
                ua: 'Допомога товаришу',
                en: 'Lend a Hand',
                de: 'Hand reichen',
                pl: 'Pomoc koledze',
            },
            demoDescription7: {
                ru: 'Передайте другому игроку любой предмет или сумму денег в качестве подарка.',
                ua: 'Передайте іншому гравцеві будь-який предмет або суму грошей як подарунок.',
                en: 'Give another player any item or amount of money as a gift.',
                de: 'Übergib einem anderen Spieler einen beliebigen Gegenstand oder Geldbetrag als Geschenk.',
                pl: 'Przekaż innemu graczowi dowolny przedmiot lub sumę pieniędzy w prezencie.',
            },
            demoTitle8: {
                ru: 'Колёсный мастер',
                ua: 'Майстер кермa',
                en: 'Wheel Master',
                de: 'Lenkrad-Meister',
                pl: 'Mistrz kierownicy',
            },
            demoDescription8: {
                ru: 'Проедьте 50 километров за рулём любого транспорта без столкновений.',
                ua: 'Проїдьте 50 кілометрів за кермом будь-якого транспорту без зіткнень.',
                en: 'Drive 50 kilometers in any vehicle without collisions.',
                de: 'Fahre 50 Kilometer mit einem beliebigen Fahrzeug ohne Kollisionen.',
                pl: 'Przejedź 50 kilometrów dowolnym pojazdem bez zderzeń.',
            },
        },
        rating: {
            tabName: {
                ru: 'Рейтинг',
                ua: 'Рейтинг',
                en: 'Rating',
                de: 'Wertung',
                pl: 'Ranking',
            },
            title: {
                ru: 'Рейтинг сезона',
                ua: 'Рейтинг сезону',
                en: 'Season rating',
                de: 'Saisonwertung',
                pl: 'Ranking sezonu',
            },
            description: {
                ru: 'Соревнуйтесь с другими игроками за лучшие места в общем рейтинге пропуска сезона.',
                ua: 'Змагайтеся з іншими гравцями за найкращі місця у загальному рейтингу пропуску сезону.',
                en: 'Compete with other players for top spots in the overall season pass leaderboard.',
                de: 'Tritt gegen andere Spieler in der Gesamtrangliste des Saisonpasses an.',
                pl: 'Rywalizuj z innymi graczami o najwyższe miejsca w ogólnym rankingu przepustki sezonu.',
            },
        },
    },
    tiers: {
        none: {
            ru: 'Нет пропуска',
            ua: 'Немає пропуску',
            en: 'No pass',
            de: 'Kein Pass',
            pl: 'Brak przepustki',
        },
        free: {
            ru: 'Базовый',
            ua: 'Базовий',
            en: 'Free',
            de: 'Kostenlos',
            pl: 'Darmowy',
        },
        starter: {
            ru: 'Стартовый',
            ua: 'Стартовий',
            en: 'Starter',
            de: 'Starter',
            pl: 'Startowy',
        },
        bronze: {
            ru: 'Бронзовый',
            ua: 'Бронзовий',
            en: 'Bronze',
            de: 'Bronze',
            pl: 'Brązowy',
        },
        silver: {
            ru: 'Серебряный',
            ua: 'Срібний',
            en: 'Silver',
            de: 'Silber',
            pl: 'Srebrny',
        },
        gold: {
            ru: 'Золотой',
            ua: 'Золотий',
            en: 'Gold',
            de: 'Gold',
            pl: 'Złoty',
        },
    },
    sidebar: {
        upgrade: {
            ru: 'Улучшить',
            ua: 'Покращити',
            en: 'Upgrade',
            de: 'Verbessern',
            pl: 'Ulepsz',
        },
        upgradePass: {
            ru: 'Улучшить пропуск',
            ua: 'Покращити пропуск',
            en: 'Upgrade pass',
            de: 'Pass verbessern',
            pl: 'Ulepsz przepustkę',
        },
        xpToNext: {
            ru: 'Опыта для повышения уровня',
            ua: 'Досвіду для підвищення рівня',
            en: 'XP to next level',
            de: 'XP bis zum nächsten Level',
            pl: 'XP do następnego poziomu',
        },
        premiumLevels: {
            ru: 'Премиум уровни',
            ua: 'Преміум рівні',
            en: 'Premium levels',
            de: 'Premium-Level',
            pl: 'Poziomy premium',
        },
    },
    lines: {
        free: {
            ru: 'Обычный',
            ua: 'Звичайний',
            en: 'Regular',
            de: 'Normal',
            pl: 'Zwykły',
        },
        premium: {
            ru: 'Премиум',
            ua: 'Преміум',
            en: 'Premium',
            de: 'Premium',
            pl: 'Premium',
        },
    },
    controls: {
        myLevel: {
            ru: 'Мой уровень',
            ua: 'Мій рівень',
            en: 'My level',
            de: 'Mein Level',
            pl: 'Mój poziom',
        },
    },
    progressBar: {
        purchaseLevel: {
            ru: 'Купить {{level}} уровень',
            ua: 'Купити {{level}} рівень',
            en: 'Buy level {{level}}',
            de: 'Level {{level}} kaufen',
            pl: 'Kup poziom {{level}}',
        },
    },
    timer: {
        endsIn: {
            ru: 'Событие завершается через',
            ua: 'Подія завершується через',
            en: 'Event ends in',
            de: 'Event endet in',
            pl: 'Wydarzenie kończy się za',
        },
        daysWord: {
            ru: 'дней',
            ua: 'днів',
            en: 'days',
            de: 'Tage',
            pl: 'dni',
        },
    },
    notify: {
        tierUpgradeTitle: {
            ru: 'Боевой пропуск',
            ua: 'Бойовий пропуск',
            en: 'Battle Pass',
            de: 'Battle Pass',
            pl: 'Karnet bojowy',
        },
        tierUpgradeBody: {
            ru: 'Активирован тир «{{tier}}»',
            ua: 'Активовано тир «{{tier}}»',
            en: 'Tier "{{tier}}" activated',
            de: 'Stufe „{{tier}}" aktiviert',
            pl: 'Aktywowano poziom „{{tier}}"',
        },
        tierUpgradeNoFunds: {
            ru: 'Недостаточно Olymp-Coin для покупки этого тира',
            ua: 'Недостатньо Olymp-Coin для покупки цього тиру',
            en: 'Not enough Olymp-Coin to buy this tier',
            de: 'Nicht genug Olymp-Coin für diese Stufe',
            pl: 'Za mało Olymp-Coin, aby kupić ten poziom',
        },
        freeXpClaimed: {
            ru: 'Получено {{xp}} опыта пропуска',
            ua: 'Отримано {{xp}} досвіду пропуску',
            en: 'Received {{xp}} pass XP',
            de: '{{xp}} Pass-XP erhalten',
            pl: 'Otrzymano {{xp}} XP przepustki',
        },
        buyXpDone: {
            ru: 'Куплено {{xp}} опыта за {{price}} Olymp-Coin',
            ua: 'Куплено {{xp}} досвіду за {{price}} Olymp-Coin',
            en: 'Bought {{xp}} XP for {{price}} Olymp-Coin',
            de: '{{xp}} XP für {{price}} Olymp-Coin gekauft',
            pl: 'Kupiono {{xp}} XP za {{price}} Olymp-Coin',
        },
        warehouseAdded: {
            ru: 'Награда отправлена в донат-инвентарь',
            ua: 'Нагороду надіслано в донат-інвентар',
            en: 'Reward sent to donate inventory',
            de: 'Belohnung ins Donate-Inventar gesendet',
            pl: 'Nagrodę wysłano do inwentarza donate',
        },
        sellDone: {
            ru: 'Награда продана за {{price}} Olymp-Coin',
            ua: 'Нагороду продано за {{price}} Olymp-Coin',
            en: 'Reward sold for {{price}} Olymp-Coin',
            de: 'Belohnung für {{price}} Olymp-Coin verkauft',
            pl: 'Nagroda sprzedana za {{price}} Olymp-Coin',
        },
        sellForXpDone: {
            ru: 'Награда обменяна на {{xp}} опыта пропуска',
            ua: 'Нагороду обміняно на {{xp}} досвіду пропуску',
            en: 'Reward exchanged for {{xp}} pass XP',
            de: 'Belohnung gegen {{xp}} Pass-XP getauscht',
            pl: 'Nagrodę wymieniono na {{xp}} XP przepustki',
        },
        seasonRewardsTransferred: {
            ru: 'Награды прошлого сезона перенесены в донат-инвентарь ({{count}} шт.)',
            ua: 'Нагороди минулого сезону перенесено в донат-інвентар ({{count}} шт.)',
            en: 'Last season rewards moved to donate inventory ({{count}} items)',
            de: 'Belohnungen der letzten Saison wurden ins Donate-Inventar verschoben ({{count}} Stk.)',
            pl: 'Nagrody z poprzedniego sezonu przeniesiono do inwentarza donate ({{count}} szt.)',
        },
        taskCompleted: {
            ru: 'Задание «{{title}}» выполнено',
            ua: 'Завдання «{{title}}» виконано',
            en: 'Task "{{title}}" completed',
            de: 'Aufgabe „{{title}}" abgeschlossen',
            pl: 'Zadanie „{{title}}" ukończone',
        },
        tasksRefreshDone: {
            ru: 'Список заданий обновлён',
            ua: 'Список завдань оновлено',
            en: 'Tasks list refreshed',
            de: 'Aufgabenliste aktualisiert',
            pl: 'Lista zadań odświeżona',
        },
        tasksRefreshNoFunds: {
            ru: 'Недостаточно Olymp-Coin для обновления заданий',
            ua: 'Недостатньо Olymp-Coin для оновлення завдань',
            en: 'Not enough Olymp-Coin to refresh tasks',
            de: 'Nicht genug Olymp-Coin zum Aktualisieren der Aufgaben',
            pl: 'Za mało Olymp-Coin, aby odświeżyć zadania',
        },
    },
    freeXp: {
        title: {
            ru: '{{hours}} часов игры = {{xp}} опыта',
            ua: '{{hours}} годин гри = {{xp}} досвіду',
            en: '{{hours}} hours played = {{xp}} XP',
            de: '{{hours}} Stunden Spielzeit = {{xp}} XP',
            pl: '{{hours}} godzin gry = {{xp}} XP',
        },
        claim: {
            ru: 'Забрать',
            ua: 'Забрати',
            en: 'Claim',
            de: 'Abholen',
            pl: 'Odbierz',
        },
        claimableIn: {
            ru: 'Можно забрать через',
            ua: 'Можна забрати через',
            en: 'Available in',
            de: 'Verfügbar in',
            pl: 'Dostępne za',
        },
    },
    rewards: {
        claim: {
            ru: 'Забрать',
            ua: 'Забрати',
            en: 'Claim',
            de: 'Abholen',
            pl: 'Odbierz',
        },
        sell: {
            ru: 'Продать',
            ua: 'Продати',
            en: 'Sell',
            de: 'Verkaufen',
            pl: 'Sprzedaj',
        },
        warehouse: {
            ru: 'На склад',
            ua: 'На склад',
            en: 'To warehouse',
            de: 'Ins Lager',
            pl: 'Do magazynu',
        },
        qtyShort: {
            ru: 'шт.',
            ua: 'шт.',
            en: 'pcs',
            de: 'St.',
            pl: 'szt.',
        },
        days: {
            ru: 'д.',
            ua: 'д.',
            en: 'd',
            de: 'T.',
            pl: 'd.',
        },
        claimSelf: {
            ru: 'Забрать себе',
            ua: 'Забрати собі',
            en: 'Claim for yourself',
            de: 'Für sich nehmen',
            pl: 'Weź dla siebie',
        },
        breakdown: {
            ru: 'Разобрать на',
            ua: 'Розібрати на',
            en: 'Disassemble for',
            de: 'Zerlegen für',
            pl: 'Rozłóż na',
        },
        toDonateInventory: {
            ru: 'Отложить в донат инвентарь',
            ua: 'Відкласти в донат інвентар',
            en: 'Save to donate inventory',
            de: 'In Donate-Inventar legen',
            pl: 'Odłóż do inwentarza donate',
        },
        sellForXp: {
            ru: 'Продать за',
            ua: 'Продати за',
            en: 'Sell for',
            de: 'Verkaufen für',
            pl: 'Sprzedaj za',
        },
    },
    categories: {
        default: {
            ru: 'Награда',
            ua: 'Нагорода',
            en: 'Reward',
            de: 'Belohnung',
            pl: 'Nagroda',
        },
        currency: {
            ru: 'Деньги',
            ua: 'Гроші',
            en: 'Cash',
            de: 'Geld',
            pl: 'Pieniądze',
        },
        donate: {
            ru: 'Монеты',
            ua: 'Монети',
            en: 'Coins',
            de: 'Münzen',
            pl: 'Monety',
        },
        experience: {
            ru: 'Опыт',
            ua: 'Досвід',
            en: 'Experience',
            de: 'Erfahrung',
            pl: 'Doświadczenie',
        },
        cases: {
            ru: 'Кейс',
            ua: 'Кейс',
            en: 'Case',
            de: 'Kiste',
            pl: 'Skrzynka',
        },
        vehicles: {
            ru: 'Транспорт',
            ua: 'Транспорт',
            en: 'Vehicle',
            de: 'Fahrzeug',
            pl: 'Pojazd',
        },
        skins: {
            ru: 'Скин',
            ua: 'Скін',
            en: 'Skin',
            de: 'Skin',
            pl: 'Skórka',
        },
        statuses: {
            ru: 'Статус',
            ua: 'Статус',
            en: 'Status',
            de: 'Status',
            pl: 'Status',
        },
        animations: {
            ru: 'Анимация',
            ua: 'Анімація',
            en: 'Animation',
            de: 'Animation',
            pl: 'Animacja',
        },
        features: {
            ru: 'Особенность',
            ua: 'Особливість',
            en: 'Feature',
            de: 'Funktion',
            pl: 'Funkcja',
        },
        weapon: {
            ru: 'Оружие',
            ua: 'Зброя',
            en: 'Weapon',
            de: 'Waffe',
            pl: 'Broń',
        },
        ammo: {
            ru: 'Патроны',
            ua: 'Патрони',
            en: 'Ammo',
            de: 'Munition',
            pl: 'Amunicja',
        },
        clothes: {
            ru: 'Одежда',
            ua: 'Одяг',
            en: 'Clothing',
            de: 'Kleidung',
            pl: 'Odzież',
        },
        backpack: {
            ru: 'Одежда',
            ua: 'Одяг',
            en: 'Clothing',
            de: 'Kleidung',
            pl: 'Odzież',
        },
        blueprint: {
            ru: 'Чертёж',
            ua: 'Креслення',
            en: 'Blueprint',
            de: 'Bauplan',
            pl: 'Schemat',
        },
        item: {
            ru: 'Предмет',
            ua: 'Предмет',
            en: 'Item',
            de: 'Gegenstand',
            pl: 'Przedmiot',
        },
    },
    featured: {
        title: {
            ru: 'Главные призы',
            ua: 'Головні призи',
            en: 'Featured prizes',
            de: 'Hauptpreise',
            pl: 'Główne nagrody',
        },
    },
    seasons: {
        summer: {
            name: {
                ru: 'Боевой пропуск',
                ua: 'Бойовий пропуск',
                en: 'Battle Pass',
                de: 'Battle Pass',
                pl: 'Karnet bojowy',
            },
            description: {
                ru: 'Открывайте уникальные награды за прохождение уровней. Выполняйте задания и получайте опыт.',
                ua: 'Відкривайте унікальні нагороди за проходження рівнів. Виконуйте завдання та отримуйте досвід.',
                en: 'Unlock unique rewards as you level up. Complete tasks and gain experience.',
                de: 'Schalte einzigartige Belohnungen frei, indem du Level aufsteigst. Erfülle Aufgaben und sammle Erfahrung.',
                pl: 'Odblokowuj unikalne nagrody, awansując na kolejne poziomy. Wykonuj zadania i zdobywaj doświadczenie.',
            },
        },
    },
    rewardNames: {
        animation: {
            ru: 'Анимация',
            ua: 'Анімація',
            en: 'Animation',
            de: 'Animation',
            pl: 'Animacja',
        },
    },
    placeholder: {
        wip: {
            ru: 'В разработке',
            ua: 'В розробці',
            en: 'Work in progress',
            de: 'In Bearbeitung',
            pl: 'W trakcie prac',
        },
    },
};
