export default {
    title: {
        ru: 'Прачечная',
        ua: 'Пральня',
        en: 'Laundromat',
        de: 'Waschsalon',
        pl: 'Pralnia',
    },
    desc: {
        ru: 'Снимите с ленты купюры, испорченные краской, затем соберите пачки по книге и найдите в ней строку, которая с ними сходится',
        ua: 'Зніміть зі стрічки купюри, зіпсовані фарбою, потім зберіть пачки за книгою та знайдіть у ній рядок, що з ними сходиться',
        en: 'Pull the dye-stained notes off the belt, then count the bundles the book asks for and find the line that matches them',
        de: 'Nimm die farbverschmierten Scheine vom Band, zähle dann die Bündel nach dem Buch ab und finde die Zeile, die zu ihnen passt',
        pl: 'Zdejmij z taśmy banknoty zniszczone farbą, potem ułóż pliki według księgi i znajdź w niej wiersz, który się z nimi zgadza',
    },
    phaseBelt: {
        ru: 'Барабан',
        ua: 'Барабан',
        en: 'Drum',
        de: 'Trommel',
        pl: 'Bęben',
    },
    phaseCount: {
        ru: 'Касса',
        ua: 'Каса',
        en: 'Till',
        de: 'Kasse',
        pl: 'Kasa',
    },
    hintBelt: {
        ru: 'Снимайте меченые купюры до конца ленты',
        ua: 'Знімайте мічені купюри до кінця стрічки',
        en: 'Pull the marked notes until the belt stops',
        de: 'Markierte Scheine abnehmen, bis das Band steht',
        pl: 'Zdejmuj oznaczone banknoty, aż taśma stanie',
    },
    hintPull: {
        ru: 'снять купюру с ленты',
        ua: 'зняти купюру зі стрічки',
        en: 'pull the note off the belt',
        de: 'Schein vom Band nehmen',
        pl: 'zdejmij banknot z taśmy',
    },
    hintBundles: {
        ru: 'добавить купюру в пачку',
        ua: 'додати купюру до пачки',
        en: 'add a note to the bundle',
        de: 'Schein zum Bündel legen',
        pl: 'dodaj banknot do pliku',
    },
    hintUndo: {
        ru: 'убрать последнюю',
        ua: 'прибрати останню',
        en: 'take the last one back',
        de: 'letzten zurücknehmen',
        pl: 'cofnij ostatni',
    },
    hintLedger: {
        ru: 'выбрать запись с суммой пачек',
        ua: 'вибрати запис із сумою пачок',
        en: 'pick the entry with the sum of the bundles',
        de: 'den Eintrag mit der Summe der Bündel wählen',
        pl: 'wskaż wpis z sumą plików',
    },
    bundle: {
        ru: 'Пачка',
        ua: 'Пачка',
        en: 'Bundle',
        de: 'Bündel',
        pl: 'Plik',
    },
    target: {
        ru: 'В пачке',
        ua: 'У пачці',
        en: 'Bundle of',
        de: 'Bündel zu',
        pl: 'Plik na',
    },
    remaining: {
        ru: 'Добрать ещё',
        ua: 'Добрати ще',
        en: 'Still to add',
        de: 'Fehlt noch',
        pl: 'Brakuje jeszcze',
    },
    over: {
        ru: 'Перебор на',
        ua: 'Перебір на',
        en: 'Over by',
        de: 'Zu viel um',
        pl: 'Za dużo o',
    },
    bundleOf: {
        ru: 'Пачка {{index}} из {{count}}',
        ua: 'Пачка {{index}} з {{count}}',
        en: 'Bundle {{index}} of {{count}}',
        de: 'Bündel {{index}} von {{count}}',
        pl: 'Plik {{index}} z {{count}}',
    },
    ledgerTitle: {
        ru: 'Какая запись в книге выручки равна сумме пачек?',
        ua: 'Який запис у книзі виторгу дорівнює сумі пачок?',
        en: 'Which entry in the takings book equals the sum of the bundles?',
        de: 'Welcher Eintrag im Kassenbuch entspricht der Summe der Bündel?',
        pl: 'Który wpis w księdze utargu równa się sumie plików?',
    },
    ledgerEntry: {
        ru: 'Запись',
        ua: 'Запис',
        en: 'Entry',
        de: 'Eintrag',
        pl: 'Wpis',
    },
    ledgerStatus: {
        ru: 'Сложите пачки и нажмите запись с их суммой. Неверная запись = брак',
        ua: 'Складіть пачки та натисніть запис з їхньою сумою. Хибний запис = брак',
        en: 'Add up the bundles and press the entry with their sum. A wrong entry scraps the batch',
        de: 'Bündel zusammenzählen und den Eintrag mit ihrer Summe drücken. Ein falscher Eintrag ist Ausschuss',
        pl: 'Zsumuj pliki i naciśnij wpis z ich sumą. Zły wpis = partia na straty',
    },
    hintExit: {
        ru: 'Выйти',
        ua: 'Вийти',
        en: 'Exit',
        de: 'Beenden',
        pl: 'Wyjdź',
    },
    pulled: {
        ru: 'Снято',
        ua: 'Знято',
        en: 'Pulled',
        de: 'Entnommen',
        pl: 'Zdjęte',
    },
    undo: {
        ru: 'Убрать',
        ua: 'Прибрати',
        en: 'Undo',
        de: 'Zurück',
        pl: 'Cofnij',
    },
    stampDone: {
        ru: 'Чисто',
        ua: 'Чисто',
        en: 'Clean',
        de: 'Sauber',
        pl: 'Czysto',
    },
    stampDoneSub: {
        ru: 'Партия сведена',
        ua: 'Партія зведена',
        en: 'The batch balances',
        de: 'Die Charge stimmt',
        pl: 'Partia się zgadza',
    },
    stampFail: {
        ru: 'Брак',
        ua: 'Брак',
        en: 'Scrapped',
        de: 'Ausschuss',
        pl: 'Wadliwe',
    },
    stampFailBelt: {
        ru: 'Меченые ушли в партию',
        ua: 'Мічені пішли в партію',
        en: 'Marked notes went through',
        de: 'Markierte Scheine sind durch',
        pl: 'Oznaczone poszły dalej',
    },
    stampFailCount: {
        ru: 'Смена кончилась, пачки не сведены',
        ua: 'Зміна скінчилася, пачки не зведені',
        en: 'The shift ran out before the bundles balanced',
        de: 'Die Schicht endete, bevor die Bündel stimmten',
        pl: 'Zmiana się skończyła, pliki się nie zgadzają',
    },
    stampFailLedger: {
        ru: 'Строка в книге не сошлась',
        ua: 'Рядок у книзі не зійшовся',
        en: 'The line in the book did not balance',
        de: 'Die Zeile im Buch stimmte nicht',
        pl: 'Wiersz w księdze się nie zgadza',
    },
    stampFailLeft: {
        ru: 'Партия брошена',
        ua: 'Партія покинута',
        en: 'The batch was left behind',
        de: 'Die Charge wurde stehen gelassen',
        pl: 'Partia porzucona',
    },
    // Server-side notification body when a batch is scrapped (`contracts/runner.ts`).
    batchFailSub: {
        ru: 'Партия ушла в брак',
        ua: 'Партія пішла в брак',
        en: 'The batch was scrapped',
        de: 'Die Charge ist Ausschuss',
        pl: 'Partia poszła na straty',
    },
};
