export default {
    name: {
        ru: 'Номерные знаки',
        ua: 'Номерні знаки',
        en: 'License plates',
        de: 'Kennzeichen',
        pl: 'Tablice rejestracyjne',
    },
    tokensRevoked: {
        ru: 'Аннулированы номера: {{numbers}}',
        ua: 'Анульовано номери: {{numbers}}',
        en: 'Plates revoked: {{numbers}}',
        de: 'Kennzeichen entzogen: {{numbers}}',
        pl: 'Unieważnione tablice: {{numbers}}',
    },
    removeBeforeTransfer: {
        ru: 'Снимите номерной знак в полицейском участке для перерегистрации транспорта',
        ua: 'Зніміть номерний знак у поліцейському відділку для перереєстрації транспорту',
        en: 'Remove the license plate at the police station to re-register the vehicle',
        de: 'Entfernen Sie das Kennzeichen auf der Polizeiwache, um das Fahrzeug umzumelden',
        pl: 'Zdejmij tablicę rejestracyjną na posterunku policji, aby przerejestrować pojazd',
    },

    // Remove / mount from the vehicle interaction menu (systems/numberPlates/remote).
    remote: {
        removeTitle: {
            ru: 'Снять номер',
            ua: 'Зняти номер',
            en: 'Remove plate',
            de: 'Kennzeichen abnehmen',
            pl: 'Zdejmij tablicę',
        },
        removeMessage: {
            ru: 'Снять номер {{number}}<br><br>Снять номер и переоформить его удалённо, это стоит дороже чем напрямую в полицейском участке.<br><br>Цена {{price}}',
            ua: 'Зняти номер {{number}}<br><br>Зняти номер і переоформити його віддалено, це коштує дорожче, ніж напряму в поліцейському відділку.<br><br>Ціна {{price}}',
            en: 'Remove plate {{number}}<br><br>Removing and re-registering the plate remotely costs more than doing it at the police station.<br><br>Price {{price}}',
            de: 'Kennzeichen {{number}} abnehmen<br><br>Das Kennzeichen aus der Ferne abzunehmen und umzumelden kostet mehr als direkt auf der Polizeiwache.<br><br>Preis {{price}}',
            pl: 'Zdejmij tablicę {{number}}<br><br>Zdjęcie i przerejestrowanie tablicy zdalnie kosztuje więcej niż bezpośrednio na posterunku policji.<br><br>Cena {{price}}',
        },
        selectTitle: {
            ru: 'Выберите номер',
            ua: 'Оберіть номер',
            en: 'Choose a plate',
            de: 'Kennzeichen wählen',
            pl: 'Wybierz tablicę',
        },
        installTitle: {
            ru: 'Установить номер',
            ua: 'Встановити номер',
            en: 'Mount plate',
            de: 'Kennzeichen montieren',
            pl: 'Zamontuj tablicę',
        },
        installMessage: {
            ru: 'Установить номер {{number}} на {{vehicle}}?<br><br>Установка удалённо стоит дороже, чем напрямую в полицейском участке.<br><br>Цена {{price}}',
            ua: 'Встановити номер {{number}} на {{vehicle}}?<br><br>Встановлення віддалено коштує дорожче, ніж напряму в поліцейському відділку.<br><br>Ціна {{price}}',
            en: 'Mount plate {{number}} on {{vehicle}}?<br><br>Mounting remotely costs more than doing it at the police station.<br><br>Price {{price}}',
            de: 'Kennzeichen {{number}} an {{vehicle}} montieren?<br><br>Die Montage aus der Ferne kostet mehr als direkt auf der Polizeiwache.<br><br>Preis {{price}}',
            pl: 'Zamontować tablicę {{number}} na {{vehicle}}?<br><br>Montaż zdalny kosztuje więcej niż bezpośrednio na posterunku policji.<br><br>Cena {{price}}',
        },
        confirmButton: {
            ru: 'Подтвердить',
            ua: 'Підтвердити',
            en: 'Confirm',
            de: 'Bestätigen',
            pl: 'Potwierdź',
        },
        cancelButton: {
            ru: 'Отменить',
            ua: 'Скасувати',
            en: 'Cancel',
            de: 'Abbrechen',
            pl: 'Anuluj',
        },
        noOwnedTokens: {
            ru: 'В инвентаре нет номеров, оформленных на вас',
            ua: 'В інвентарі немає номерів, оформлених на вас',
            en: 'There are no plates registered to you in your inventory',
            de: 'In deinem Inventar gibt es keine auf dich registrierten Kennzeichen',
            pl: 'W ekwipunku nie ma tablic zarejestrowanych na ciebie',
        },
        noPlateOnVehicle: {
            ru: 'На этом транспорте не установлен номер',
            ua: 'На цьому транспорті не встановлено номер',
            en: 'This vehicle has no plate',
            de: 'Dieses Fahrzeug hat kein Kennzeichen',
            pl: 'Ten pojazd nie ma tablicy',
        },
        vehicleHasPlate: {
            ru: 'На этом транспорте уже установлен номер',
            ua: 'На цьому транспорті вже встановлено номер',
            en: 'This vehicle already has a plate',
            de: 'Dieses Fahrzeug hat bereits ein Kennzeichen',
            pl: 'Ten pojazd ma już tablicę',
        },
        vehicleChanged: {
            ru: 'Транспорт больше недоступен для этой операции',
            ua: 'Транспорт більше недоступний для цієї операції',
            en: 'The vehicle is no longer available for this operation',
            de: 'Das Fahrzeug ist für diesen Vorgang nicht mehr verfügbar',
            pl: 'Pojazd nie jest już dostępny dla tej operacji',
        },
        plateInvalid: {
            ru: 'Номер аннулирован или уже установлен на другой транспорт',
            ua: 'Номер анульовано або вже встановлено на інший транспорт',
            en: 'The plate has been revoked or is already mounted on another vehicle',
            de: 'Das Kennzeichen wurde entzogen oder ist bereits an einem anderen Fahrzeug montiert',
            pl: 'Tablica została unieważniona lub jest już zamontowana na innym pojeździe',
        },
        plateForeign: {
            ru: 'Номер оформлен на {{ownerName}}, переоформите его в полицейском участке',
            ua: 'Номер оформлено на {{ownerName}}, переоформіть його в поліцейському відділку',
            en: 'The plate is registered to {{ownerName}}, re-register it at the police station',
            de: 'Das Kennzeichen ist auf {{ownerName}} registriert, melde es auf der Polizeiwache um',
            pl: 'Tablica jest zarejestrowana na {{ownerName}}, przerejestruj ją na posterunku policji',
        },
        removed: {
            ru: 'Номер {{number}} снят с {{vehicle}} и добавлен в инвентарь',
            ua: 'Номер {{number}} знято з {{vehicle}} та додано до інвентарю',
            en: 'Plate {{number}} removed from {{vehicle}} and added to your inventory',
            de: 'Kennzeichen {{number}} von {{vehicle}} abgenommen und dem Inventar hinzugefügt',
            pl: 'Tablica {{number}} zdjęta z {{vehicle}} i dodana do ekwipunku',
        },
        installed: {
            ru: 'Номер {{number}} установлен на {{vehicle}}',
            ua: 'Номер {{number}} встановлено на {{vehicle}}',
            en: 'Plate {{number}} mounted on {{vehicle}}',
            de: 'Kennzeichen {{number}} an {{vehicle}} montiert',
            pl: 'Tablica {{number}} zamontowana na {{vehicle}}',
        },
    },

    shop: {
        // The payment sheet's line (modules/payment) - the named number only; the random draw
        // is still a straight charge.
        payment: {
            description: {
                ru: 'Покупка именного номера {{number}}',
                ua: 'Купівля іменного номера {{number}}',
                en: 'Buying the custom plate {{number}}',
                de: 'Kauf des Wunschkennzeichens {{number}}',
                pl: 'Zakup tablicy na zamówienie {{number}}',
            },
        },
        notEnoughMoney: {
            ru: 'Недостаточно наличных',
            ua: 'Недостатньо готівки',
            en: 'Not enough cash',
            de: 'Nicht genug Bargeld',
            pl: 'Za mało gotówki',
        },
        noInventorySpace: {
            ru: 'В инвентаре нет места для номерного знака',
            ua: 'В інвентарі немає місця для номерного знака',
            en: 'No room in your inventory for the plate',
            de: 'Kein Platz im Inventar für das Kennzeichen',
            pl: 'Brak miejsca w ekwipunku na tablicę',
        },
        numberTaken: {
            ru: 'Номер {{number}} уже занят',
            ua: 'Номер {{number}} вже зайнятий',
            en: 'Plate {{number}} is already taken',
            de: 'Kennzeichen {{number}} ist bereits vergeben',
            pl: 'Tablica {{number}} jest już zajęta',
        },
        invalidNumber: {
            ru: 'Недопустимый номер: от 4 до 8 символов, латинские буквы и цифры',
            ua: 'Неприпустимий номер: від 4 до 8 символів, латинські літери та цифри',
            en: 'Invalid number: 4 to 8 characters, latin letters and digits',
            de: 'Ungültiges Kennzeichen: 4 bis 8 Zeichen, lateinische Buchstaben und Ziffern',
            pl: 'Nieprawidłowy numer: od 4 do 8 znaków, litery łacińskie i cyfry',
        },
        noFreeNumber: {
            ru: 'Не удалось подобрать свободный номер, попробуйте ещё раз',
            ua: 'Не вдалося підібрати вільний номер, спробуйте ще раз',
            en: 'Could not find a free number, try again',
            de: 'Es konnte kein freies Kennzeichen gefunden werden, versuchen Sie es erneut',
            pl: 'Nie udało się znaleźć wolnego numeru, spróbuj ponownie',
        },
    },

    cef: {
        title: {
            ru: 'Регистрация',
            ua: 'Реєстрація',
            en: 'Plate',
            de: 'Kennzeichen',
            pl: 'Rejestracja',
        },
        titleAccent: {
            ru: 'номера',
            ua: 'номера',
            en: 'registration',
            de: 'registrieren',
            pl: 'tablicy',
        },
        subtitle: {
            ru: 'Здесь вы можете попытать удачу выбить красивый номер либо же получить именной номер под заказ',
            ua: 'Тут ви можете спробувати вдачу вибити гарний номер або ж отримати іменний номер на замовлення',
            en: 'Try your luck at a good-looking number or order a custom plate of your own',
            de: 'Versuchen Sie Ihr Glück auf ein schönes Kennzeichen oder bestellen Sie ein Wunschkennzeichen',
            pl: 'Spróbuj szczęścia w losowaniu ładnego numeru albo zamów tablicę na życzenie',
        },
        tabs: {
            random: {
                ru: 'Случайные',
                ua: 'Випадкові',
                en: 'Random',
                de: 'Zufällig',
                pl: 'Losowe',
            },
            named: {
                ru: 'Именные',
                ua: 'Іменні',
                en: 'Custom',
                de: 'Wunsch',
                pl: 'Na życzenie',
            },
        },
        placeholder: {
            ru: 'OLYMP',
            ua: 'OLYMP',
            en: 'OLYMP',
            de: 'OLYMP',
            pl: 'OLYMP',
        },
        lengthLabel: {
            ru: 'Количество символов',
            ua: 'Кількість символів',
            en: 'Number of characters',
            de: 'Anzahl der Zeichen',
            pl: 'Liczba znaków',
        },
        generate: {
            ru: 'Сгенерировать номер',
            ua: 'Згенерувати номер',
            en: 'Generate a number',
            de: 'Kennzeichen generieren',
            pl: 'Wygeneruj numer',
        },
        take: {
            ru: 'Забрать номер в инвентарь',
            ua: 'Забрати номер в інвентар',
            en: 'Take the plate to inventory',
            de: 'Kennzeichen ins Inventar legen',
            pl: 'Odbierz tablicę do ekwipunku',
        },
        check: {
            ru: 'Проверить номер',
            ua: 'Перевірити номер',
            en: 'Check the number',
            de: 'Kennzeichen prüfen',
            pl: 'Sprawdź numer',
        },
        buy: {
            ru: 'Купить и получить номер',
            ua: 'Купити та отримати номер',
            en: 'Buy and receive the plate',
            de: 'Kennzeichen kaufen und erhalten',
            pl: 'Kup i odbierz tablicę',
        },
        patterns: {
            identical: {
                ru: 'Одинаковые символы',
                ua: 'Однакові символи',
                en: 'Identical characters',
                de: 'Gleiche Zeichen',
                pl: 'Identyczne znaki',
            },
            sequence: {
                ru: 'Символы подряд',
                ua: 'Символи поспіль',
                en: 'Running sequence',
                de: 'Fortlaufende Folge',
                pl: 'Kolejne znaki',
            },
            longRun: {
                ru: 'Четыре подряд',
                ua: 'Чотири поспіль',
                en: 'Four in a row',
                de: 'Vier am Stück',
                pl: 'Cztery pod rząd',
            },
            repeatedBlock: {
                ru: 'Повтор группы',
                ua: 'Повтор групи',
                en: 'Repeated group',
                de: 'Wiederholte Gruppe',
                pl: 'Powtórzona grupa',
            },
            palindrome: {
                ru: 'Читается в обе стороны',
                ua: 'Читається в обидва боки',
                en: 'Reads both ways',
                de: 'Beidseitig lesbar',
                pl: 'Czyta się w obie strony',
            },
            run: {
                ru: 'Три подряд',
                ua: 'Три поспіль',
                en: 'Three in a row',
                de: 'Drei am Stück',
                pl: 'Trzy pod rząd',
            },
            pairs: {
                ru: 'Символы парами',
                ua: 'Символи парами',
                en: 'Doubled characters',
                de: 'Doppelte Zeichen',
                pl: 'Znaki parami',
            },
            twoSymbols: {
                ru: 'Всего два символа',
                ua: 'Лише два символи',
                en: 'Only two characters',
                de: 'Nur zwei Zeichen',
                pl: 'Tylko dwa znaki',
            },
            pure: {
                ru: 'Без смешения букв и цифр',
                ua: 'Без змішування літер і цифр',
                en: 'Letters or digits only',
                de: 'Nur Buchstaben oder Ziffern',
                pl: 'Tylko litery lub cyfry',
            },
        },

        status: {
            empty: {
                title: {
                    ru: 'Номер не введён',
                    ua: 'Номер не введено',
                    en: 'No number entered',
                    de: 'Kein Kennzeichen eingegeben',
                    pl: 'Nie wpisano numeru',
                },
                desc: {
                    ru: 'Введите желаемый именной номер в поле выше прямо в номерную рамку',
                    ua: 'Введіть бажаний іменний номер у поле вище прямо в номерну рамку',
                    en: 'Type the number you want straight into the plate frame above',
                    de: 'Geben Sie das gewünschte Kennzeichen direkt in den Rahmen oben ein',
                    pl: 'Wpisz wybrany numer bezpośrednio w ramkę tablicy powyżej',
                },
            },
            invalid: {
                title: {
                    ru: 'Недопустимый номер',
                    ua: 'Неприпустимий номер',
                    en: 'Invalid number',
                    de: 'Ungültiges Kennzeichen',
                    pl: 'Nieprawidłowy numer',
                },
                desc: {
                    ru: 'Номер должен содержать от 4 до 8 символов: латинские буквы и цифры',
                    ua: 'Номер має містити від 4 до 8 символів: латинські літери та цифри',
                    en: 'A plate must be 4 to 8 characters long: latin letters and digits',
                    de: 'Ein Kennzeichen muss 4 bis 8 Zeichen lang sein: lateinische Buchstaben und Ziffern',
                    pl: 'Tablica musi mieć od 4 do 8 znaków: litery łacińskie i cyfry',
                },
            },
            unchecked: {
                title: {
                    ru: 'Номер ещё не проверен',
                    ua: 'Номер ще не перевірено',
                    en: 'Number not checked yet',
                    de: 'Kennzeichen noch nicht geprüft',
                    pl: 'Numer jeszcze nie sprawdzony',
                },
                desc: {
                    ru: 'Введённый номер пока не проверен, нажмите на кнопку "Проверить номер" ниже, чтобы узнать его статус',
                    ua: 'Введений номер поки не перевірено, натисніть кнопку "Перевірити номер" нижче, щоб дізнатися його статус',
                    en: 'The number has not been checked yet, press "Check the number" below to see its status',
                    de: 'Das Kennzeichen wurde noch nicht geprüft, klicken Sie unten auf "Kennzeichen prüfen", um seinen Status zu sehen',
                    pl: 'Numer nie został jeszcze sprawdzony, naciśnij "Sprawdź numer" poniżej, aby poznać jego status',
                },
            },
            available: {
                title: {
                    ru: 'Номер доступен',
                    ua: 'Номер доступний',
                    en: 'Number available',
                    de: 'Kennzeichen verfügbar',
                    pl: 'Numer dostępny',
                },
                desc: {
                    ru: 'Вы можете купить и получить этот номер прямо сейчас за определённую сумму',
                    ua: 'Ви можете купити та отримати цей номер прямо зараз за певну суму',
                    en: 'You can buy and receive this plate right now for the listed price',
                    de: 'Sie können dieses Kennzeichen jetzt zum angegebenen Preis kaufen und erhalten',
                    pl: 'Możesz kupić i odebrać tę tablicę od razu za podaną cenę',
                },
            },
            unavailable: {
                title: {
                    ru: 'Номер недоступен',
                    ua: 'Номер недоступний',
                    en: 'Number unavailable',
                    de: 'Kennzeichen nicht verfügbar',
                    pl: 'Numer niedostępny',
                },
                desc: {
                    ru: 'Этот номер уже кем-то куплен либо недоступен для покупки',
                    ua: 'Цей номер уже хтось купив або він недоступний для покупки',
                    en: 'This number is already owned by someone or cannot be purchased',
                    de: 'Dieses Kennzeichen gehört bereits jemandem oder kann nicht gekauft werden',
                    pl: 'Ten numer został już kupiony albo nie jest dostępny do zakupu',
                },
            },
        },
    },

    tooltip: {
        number: {
            ru: 'Номер',
            ua: 'Номер',
            en: 'Plate',
            de: 'Kennzeichen',
            pl: 'Numer',
        },
        registeredTo: {
            ru: 'Оформлен на',
            ua: 'Оформлено на',
            en: 'Registered to',
            de: 'Registriert auf',
            pl: 'Zarejestrowana na',
        },
        foreignWarning: {
            ru: 'Этот номер оформлен на {{name}}. Вы можете переоформить его в полицейском участке, чтобы сохранить право владения',
            ua: 'Цей номер оформлено на {{name}}. Ви можете переоформити його в поліцейському відділку, щоб зберегти право власності',
            en: 'This plate is registered to {{name}}. You can re-register it at the police station to keep the right to own it',
            de: 'Dieses Kennzeichen ist auf {{name}} registriert. Sie können es auf der Polizeiwache ummelden, um das Eigentumsrecht zu behalten',
            pl: 'Ta tablica jest zarejestrowana na {{name}}. Możesz ją przerejestrować na posterunku policji, aby zachować prawo własności',
        },
    },

    dialogs: {
        clerk: {
            messages: {
                platesMenu: {
                    ru: 'Что вас интересует по номерным знакам?',
                    ua: 'Що вас цікавить щодо номерних знаків?',
                    en: 'What would you like to do with license plates?',
                    de: 'Was möchten Sie mit Kennzeichen tun?',
                    pl: 'Co chcesz zrobić z tablicami rejestracyjnymi?',
                },
                myPlates: {
                    ru: 'Вот номера, которые числятся за вами или находятся при вас. Страница {{page}}/{{totalPages}}, всего номеров: {{count}}.',
                    ua: 'Ось номери, що числяться за вами або є при вас. Сторінка {{page}}/{{totalPages}}, усього номерів: {{count}}.',
                    en: 'These are the plates registered to you or in your possession. Page {{page}}/{{totalPages}}, total plates: {{count}}.',
                    de: 'Das sind die auf Sie registrierten oder bei Ihnen befindlichen Kennzeichen. Seite {{page}}/{{totalPages}}, Kennzeichen insgesamt: {{count}}.',
                    pl: 'Oto tablice zarejestrowane na ciebie lub będące przy tobie. Strona {{page}}/{{totalPages}}, łącznie tablic: {{count}}.',
                },
                myPlatesEmpty: {
                    ru: 'За вами не числится ни одного номера, и при себе у вас их нет.',
                    ua: 'За вами не числиться жодного номера, і при собі у вас їх немає.',
                    en: 'No plates are registered to you and you have none on you.',
                    de: 'Auf Sie ist kein Kennzeichen registriert und Sie haben keines dabei.',
                    pl: 'Nie masz zarejestrowanych tablic ani żadnej przy sobie.',
                },
                plateMounted: {
                    ru: 'Номер {{number}} установлен на {{vehicle}}. Снятие стоит {{price}}, знак будет выдан вам на руки.',
                    ua: 'Номер {{number}} встановлено на {{vehicle}}. Зняття коштує {{price}}, знак буде видано вам на руки.',
                    en: 'Plate {{number}} is mounted on {{vehicle}}. Removal costs {{price}}; the plate will be handed to you.',
                    de: 'Kennzeichen {{number}} ist an {{vehicle}} montiert. Die Demontage kostet {{price}}; das Kennzeichen wird Ihnen ausgehändigt.',
                    pl: 'Tablica {{number}} jest zamontowana na {{vehicle}}. Zdjęcie kosztuje {{price}}; tablica zostanie ci wydana.',
                },
                confirmRemove: {
                    ru: 'Снять номер {{number}} с {{vehicle}} за {{price}}?',
                    ua: 'Зняти номер {{number}} з {{vehicle}} за {{price}}?',
                    en: 'Remove plate {{number}} from {{vehicle}} for {{price}}?',
                    de: 'Kennzeichen {{number}} für {{price}} von {{vehicle}} abnehmen?',
                    pl: 'Zdjąć tablicę {{number}} z {{vehicle}} za {{price}}?',
                },
                plateOwned: {
                    ru: 'Номер {{number}} оформлен на вас. Установка на ваш транспорт стоит {{price}}.',
                    ua: 'Номер {{number}} оформлено на вас. Встановлення на ваш транспорт коштує {{price}}.',
                    en: 'Plate {{number}} is registered to you. Mounting it on your vehicle costs {{price}}.',
                    de: 'Kennzeichen {{number}} ist auf Sie registriert. Die Montage an Ihrem Fahrzeug kostet {{price}}.',
                    pl: 'Tablica {{number}} jest zarejestrowana na ciebie. Montaż na twoim pojeździe kosztuje {{price}}.',
                },
                noVehicles: {
                    ru: 'У вас нет транспорта без номера.',
                    ua: 'У вас немає транспорту без номера.',
                    en: 'You have no vehicle without a plate.',
                    de: 'Sie haben kein Fahrzeug ohne Kennzeichen.',
                    pl: 'Nie masz pojazdu bez tablicy.',
                },
                selectVehicle: {
                    ru: 'На какой транспорт установить номер {{number}}?',
                    ua: 'На який транспорт встановити номер {{number}}?',
                    en: 'Which vehicle should plate {{number}} go on?',
                    de: 'An welches Fahrzeug soll das Kennzeichen {{number}} montiert werden?',
                    pl: 'Na którym pojeździe zamontować tablicę {{number}}?',
                },
                confirmInstall: {
                    ru: 'Установить номер {{number}} на {{vehicle}} за {{price}}?',
                    ua: 'Встановити номер {{number}} на {{vehicle}} за {{price}}?',
                    en: 'Mount plate {{number}} on {{vehicle}} for {{price}}?',
                    de: 'Kennzeichen {{number}} für {{price}} an {{vehicle}} montieren?',
                    pl: 'Zamontować tablicę {{number}} na {{vehicle}} za {{price}}?',
                },
                plateForeign: {
                    ru: 'Этот номер оформлен на {{ownerName}}. Вы не можете установить его на свой транспорт без переоформления. Переоформление стоит {{reregisterPrice}}.',
                    ua: 'Цей номер оформлено на {{ownerName}}. Ви не можете встановити його на свій транспорт без переоформлення. Переоформлення коштує {{reregisterPrice}}.',
                    en: 'This plate is registered to {{ownerName}}. You cannot mount it on your vehicle without re-registration. Re-registration costs {{reregisterPrice}}.',
                    de: 'Dieses Kennzeichen ist auf {{ownerName}} registriert. Ohne Ummeldung können Sie es nicht an Ihrem Fahrzeug montieren. Die Ummeldung kostet {{reregisterPrice}}.',
                    pl: 'Ta tablica jest zarejestrowana na {{ownerName}}. Nie możesz jej zamontować na swoim pojeździe bez przerejestrowania. Przerejestrowanie kosztuje {{reregisterPrice}}.',
                },
                confirmReregister: {
                    ru: 'Переоформить номер {{number}} на себя за {{reregisterPrice}}?',
                    ua: 'Переоформити номер {{number}} на себе за {{reregisterPrice}}?',
                    en: 'Re-register plate {{number}} to yourself for {{reregisterPrice}}?',
                    de: 'Kennzeichen {{number}} für {{reregisterPrice}} auf sich ummelden?',
                    pl: 'Przerejestrować tablicę {{number}} na siebie za {{reregisterPrice}}?',
                },
                removed: {
                    ru: 'Готово. Номер {{number}} снят с {{vehicle}} и выдан вам на руки.',
                    ua: 'Готово. Номер {{number}} знято з {{vehicle}} та видано вам на руки.',
                    en: 'Done. Plate {{number}} has been removed from {{vehicle}} and handed to you.',
                    de: 'Erledigt. Kennzeichen {{number}} wurde von {{vehicle}} abgenommen und Ihnen ausgehändigt.',
                    pl: 'Gotowe. Tablica {{number}} została zdjęta z {{vehicle}} i wydana tobie.',
                },
                installed: {
                    ru: 'Готово. Номер {{number}} установлен на {{vehicle}}.',
                    ua: 'Готово. Номер {{number}} встановлено на {{vehicle}}.',
                    en: 'Done. Plate {{number}} is now mounted on {{vehicle}}.',
                    de: 'Erledigt. Kennzeichen {{number}} ist jetzt an {{vehicle}} montiert.',
                    pl: 'Gotowe. Tablica {{number}} została zamontowana na {{vehicle}}.',
                },
                reregistered: {
                    ru: 'Готово. Номер {{number}} теперь оформлен на вас.',
                    ua: 'Готово. Номер {{number}} тепер оформлено на вас.',
                    en: 'Done. Plate {{number}} is now registered to you.',
                    de: 'Erledigt. Kennzeichen {{number}} ist jetzt auf Sie registriert.',
                    pl: 'Gotowe. Tablica {{number}} jest teraz zarejestrowana na ciebie.',
                },
                notEnoughMoney: {
                    ru: 'У вас недостаточно наличных для оплаты услуги.',
                    ua: 'У вас недостатньо готівки для оплати послуги.',
                    en: 'You do not have enough cash for this service.',
                    de: 'Sie haben nicht genug Bargeld für diese Dienstleistung.',
                    pl: 'Nie masz wystarczająco gotówki na tę usługę.',
                },
                noInventorySpace: {
                    ru: 'В вашем инвентаре нет места для номерного знака.',
                    ua: 'У вашому інвентарі немає місця для номерного знака.',
                    en: 'There is no room in your inventory for the plate.',
                    de: 'In Ihrem Inventar ist kein Platz für das Kennzeichen.',
                    pl: 'W twoim ekwipunku nie ma miejsca na tablicę.',
                },
                plateInvalid: {
                    ru: 'Операция невозможна: номер аннулирован, уже установлен на другой транспорт или транспорт вам больше не принадлежит.',
                    ua: 'Операція неможлива: номер анульовано, вже встановлено на інший транспорт або транспорт вам більше не належить.',
                    en: 'This cannot be done: the plate has been revoked, is already mounted on another vehicle, or the vehicle is no longer yours.',
                    de: 'Nicht möglich: Das Kennzeichen wurde entzogen, ist bereits an einem anderen Fahrzeug montiert oder das Fahrzeug gehört Ihnen nicht mehr.',
                    pl: 'Operacja niemożliwa: tablica została unieważniona, jest już zamontowana na innym pojeździe lub pojazd nie należy już do ciebie.',
                },
                vehicleHasPlate: {
                    ru: 'На этом транспорте уже установлен номер.',
                    ua: 'На цьому транспорті вже встановлено номер.',
                    en: 'This vehicle already has a plate.',
                    de: 'Dieses Fahrzeug hat bereits ein Kennzeichen.',
                    pl: 'Ten pojazd ma już tablicę.',
                },
            },
            buttons: {
                myPlates: {
                    ru: 'Ваши номера',
                    ua: 'Ваші номери',
                    en: 'My plates',
                    de: 'Meine Kennzeichen',
                    pl: 'Moje tablice',
                },
                registerNew: {
                    ru: 'Регистрация нового номера',
                    ua: 'Реєстрація нового номера',
                    en: 'Register a new plate',
                    de: 'Neues Kennzeichen registrieren',
                    pl: 'Rejestracja nowej tablicy',
                },
                plateMounted: {
                    ru: '{{number}} ({{vehicle}})',
                    ua: '{{number}} ({{vehicle}})',
                    en: '{{number}} ({{vehicle}})',
                    de: '{{number}} ({{vehicle}})',
                    pl: '{{number}} ({{vehicle}})',
                },
                plateOwned: {
                    ru: '{{number}} (в инвентаре)',
                    ua: '{{number}} (в інвентарі)',
                    en: '{{number}} (in inventory)',
                    de: '{{number}} (im Inventar)',
                    pl: '{{number}} (w ekwipunku)',
                },
                plateForeign: {
                    ru: '{{number}} (оформлен на {{ownerName}})',
                    ua: '{{number}} (оформлено на {{ownerName}})',
                    en: '{{number}} (registered to {{ownerName}})',
                    de: '{{number}} (registriert auf {{ownerName}})',
                    pl: '{{number}} (zarejestrowana na {{ownerName}})',
                },
                vehicle: {
                    ru: '{{vehicle}}',
                    ua: '{{vehicle}}',
                    en: '{{vehicle}}',
                    de: '{{vehicle}}',
                    pl: '{{vehicle}}',
                },
                remove: {
                    ru: 'Снять номер ({{price}})',
                    ua: 'Зняти номер ({{price}})',
                    en: 'Remove plate ({{price}})',
                    de: 'Kennzeichen abnehmen ({{price}})',
                    pl: 'Zdejmij tablicę ({{price}})',
                },
                install: {
                    ru: 'Установить ({{price}})',
                    ua: 'Встановити ({{price}})',
                    en: 'Mount ({{price}})',
                    de: 'Montieren ({{price}})',
                    pl: 'Zamontuj ({{price}})',
                },
                reregister: {
                    ru: 'Переоформление номера ({{reregisterPrice}})',
                    ua: 'Переоформлення номера ({{reregisterPrice}})',
                    en: 'Re-register plate ({{reregisterPrice}})',
                    de: 'Kennzeichen ummelden ({{reregisterPrice}})',
                    pl: 'Przerejestruj tablicę ({{reregisterPrice}})',
                },
                confirm: {
                    ru: 'Подтвердить',
                    ua: 'Підтвердити',
                    en: 'Confirm',
                    de: 'Bestätigen',
                    pl: 'Potwierdź',
                },
                prev: {
                    ru: '<',
                    ua: '<',
                    en: '<',
                    de: '<',
                    pl: '<',
                },
                next: {
                    ru: '>',
                    ua: '>',
                    en: '>',
                    de: '>',
                    pl: '>',
                },
                back: {
                    ru: 'Назад',
                    ua: 'Назад',
                    en: 'Back',
                    de: 'Zurück',
                    pl: 'Wstecz',
                },
                toMyNumberPlates: {
                    ru: 'К списку номеров',
                    ua: 'До списку номерів',
                    en: 'Back to plates',
                    de: 'Zu den Kennzeichen',
                    pl: 'Do listy tablic',
                },
                goodbye: {
                    ru: 'Попрощаться',
                    ua: 'Попрощатися',
                    en: 'Goodbye',
                    de: 'Verabschieden',
                    pl: 'Do widzenia',
                },
            },
        },
    },
};
