export default {
    title: {
        ru: 'Швейный цех',
        ua: 'Швейний цех',
        en: 'Sewing floor',
        de: 'Näherei',
        pl: 'Szwalnia',
    },
    interaction: {
        ru: 'Чтобы начать строчку',
        ua: 'Щоб почати строчку',
        en: 'To start stitching',
        de: 'Um mit dem Nähen zu beginnen',
        pl: 'Aby rozpocząć szycie',
    },
    suit: {
        ru: 'Костюм',
        ua: 'Костюм',
        en: 'Suit',
        de: 'Anzug',
        pl: 'Garnitur',
    },
    defects: {
        ru: 'Брак',
        ua: 'Брак',
        en: 'Defects',
        de: 'Ausschuss',
        pl: 'Wady',
    },
    hintRun: {
        ru: 'Держите, чтобы шить',
        ua: 'Тримайте, щоб шити',
        en: 'Hold to run the machine',
        de: 'Halten, um die Maschine laufen zu lassen',
        pl: 'Przytrzymaj, aby szyć',
    },
    hintSteer: {
        ru: 'Ведите строчку',
        ua: 'Ведіть строчку',
        en: 'Guide the seam',
        de: 'Naht führen',
        pl: 'Prowadź ścieg',
    },
    hintExit: {
        ru: 'Выйти',
        ua: 'Вийти',
        en: 'Exit',
        de: 'Beenden',
        pl: 'Wyjdź',
    },
    stampDone: {
        ru: 'Готово',
        ua: 'Готово',
        en: 'Finished',
        de: 'Fertig',
        pl: 'Gotowe',
    },
    stampDoneSub: {
        ru: 'Точность {{acc}}%',
        ua: 'Точність {{acc}}%',
        en: 'Accuracy {{acc}}%',
        de: 'Genauigkeit {{acc}}%',
        pl: 'Dokładność {{acc}}%',
    },
    stampFail: {
        ru: 'Брак',
        ua: 'Брак',
        en: 'Defect',
        de: 'Ausschuss',
        pl: 'Wadliwe',
    },
    stampFailSub: {
        ru: 'Строчка ушла с линии',
        ua: 'Строчка зійшла з лінії',
        en: 'The seam left the line',
        de: 'Die Naht verließ die Linie',
        pl: 'Ścieg zszedł z linii',
    },
};
