export default {
    enter: {
        ru: 'Чтобы начать игру в теннис, нажмите',
        ua: 'Щоб почати гру в теніс, натисніть',
        en: 'To start a tennis match, press',
        de: 'Drücke, um ein Tennisspiel zu starten',
        pl: 'Aby rozpocząć grę w tenisa, naciśnij',
        zh: '按下开始打网球',
    },
    alreadyPlaying: {
        ru: 'Вы уже играете в теннис.',
        ua: 'Ви вже граєте в теніс.',
        en: 'You are already playing tennis.',
        de: 'Du spielst bereits Tennis.',
        pl: 'Już grasz w tenisa.',
        zh: '你已经在打网球了。',
    },
    positionOccupied: {
        ru: 'Это место уже занято.',
        ua: 'Це місце вже зайняте.',
        en: 'This position is already occupied.',
        de: 'Diese Position ist bereits besetzt.',
        pl: 'To miejsce jest już zajęte.',
        zh: '这个位置已被占用。',
    },
    waitingOpponent: {
        ru: 'Ожидание соперника',
        ua: 'Очікування суперника',
        en: 'Waiting for opponent',
        de: 'Warten auf Gegner',
        pl: 'Oczekiwanie na przeciwnika',
        zh: '等待对手',
    },
    practiceMachine: {
        ru: 'Тренажёр',
        ua: 'Тренажер',
        en: 'Ball machine',
        de: 'Ballmaschine',
        pl: 'Maszyna treningowa',
        zh: '发球机',
    },
    scoreOpponent: {
        ru: 'Соперник',
        ua: 'Суперник',
        en: 'Opponent',
        de: 'Gegner',
        pl: 'Przeciwnik',
        zh: '对手',
    },
    scoreYou: {
        ru: 'Вы',
        ua: 'Ви',
        en: 'You',
        de: 'Du',
        pl: 'Ty',
        zh: '你',
    },
    scoreboardTitle: {
        ru: 'Теннис',
        ua: 'Теніс',
        en: 'Tennis',
        de: 'Tennis',
        pl: 'Tenis',
        zh: '网球',
    },
    scoreboardColumn: {
        ru: 'Счёт',
        ua: 'Рахунок',
        en: 'Score',
        de: 'Punktestand',
        pl: 'Wynik',
        zh: '比分',
    },
    scoreboardGames: {
        ru: 'Геймы',
        ua: 'Гейми',
        en: 'Games',
        de: 'Spiele',
        pl: 'Gemy',
        zh: '局',
    },
    scoreboardSets: {
        ru: 'Сеты',
        ua: 'Сети',
        en: 'Sets',
        de: 'Sätze',
        pl: 'Sety',
        zh: '盘',
    },
    scoreboardPoints: {
        ru: 'Поинт',
        ua: 'Поінт',
        en: 'Points',
        de: 'Punkte',
        pl: 'Punkty',
        zh: '分',
    },
    scoreboardDeuceCourt: {
        ru: 'Ровная сторона',
        ua: 'Рівна сторона',
        en: 'Deuce court',
        de: 'Einstandseite',
        pl: 'Strona deuce',
        zh: '平分区',
    },
    scoreboardAdCourt: {
        ru: 'Сторона больше',
        ua: 'Сторона переваги',
        en: 'Ad court',
        de: 'Vorteilsseite',
        pl: 'Strona przewagi',
        zh: '占先区',
    },
    scoreboardSecondServe: {
        ru: 'Вторая подача',
        ua: 'Друга подача',
        en: 'Second serve',
        de: 'Zweiter Aufschlag',
        pl: 'Drugi serwis',
        zh: '二发',
    },
    serveAim: {
        ru: 'Подача: ЛКМ начать, A / D сместиться',
        ua: 'Подача: ЛКМ почати, A / D зміститися',
        en: 'Serve: LMB to start, A / D to move',
        de: 'Aufschlag: LMT starten, A / D bewegen',
        pl: 'Serwis: LPM rozpocznij, A / D przesuń się',
        zh: '发球：鼠标左键开始，A / D 调整位置',
    },
    serveSwing: {
        ru: 'Подача: ЛКМ зафиксировать силу удара',
        ua: 'Подача: ЛКМ зафіксувати силу удару',
        en: 'Serve: LMB to lock shot power',
        de: 'Aufschlag: LMT, um die Schlagkraft festzulegen',
        pl: 'Serwis: LPM, aby zablokować siłę uderzenia',
        zh: '发球：鼠标左键锁定击球力度',
    },
    rallyControls: {
        ru: 'Удар: ЛКМ обычный, ПКМ топспин, ПРОБЕЛ подрезка',
        ua: 'Удар: ЛКМ звичайний, ПКМ топспін, ПРОБІЛ підрізка',
        en: 'Shot: LMB normal, RMB topspin, SPACE slice',
        de: 'Schlag: LMT normal, RMT Topspin, LEERTASTE Slice',
        pl: 'Uderzenie: LPM zwykłe, PPM topspin, SPACJA slice',
        zh: '击球：左键普通，右键上旋，空格切削',
    },
    uiServeStart: {
        ru: 'Начать подачу',
        ua: 'Почати подачу',
        en: 'Start serve',
        de: 'Aufschlag starten',
        pl: 'Rozpocznij serwis',
        zh: '开始发球',
    },
    uiLockPower: {
        ru: 'Зафиксировать силу',
        ua: 'Зафіксувати силу',
        en: 'Lock power',
        de: 'Kraft festlegen',
        pl: 'Zablokuj siłę',
        zh: '锁定力度',
    },
    uiMoveLeft: {
        ru: 'Сместиться влево',
        ua: 'Зміститися вліво',
        en: 'Move left',
        de: 'Nach links',
        pl: 'Przesuń w lewo',
        zh: '向左移动',
    },
    uiMoveRight: {
        ru: 'Сместиться вправо',
        ua: 'Зміститися вправо',
        en: 'Move right',
        de: 'Nach rechts',
        pl: 'Przesuń w prawo',
        zh: '向右移动',
    },
    uiNormalShot: {
        ru: 'Обычный удар',
        ua: 'Звичайний удар',
        en: 'Normal shot',
        de: 'Normaler Schlag',
        pl: 'Zwykłe uderzenie',
        zh: '普通击球',
    },
    uiTopspinShot: {
        ru: 'Топспин',
        ua: 'Топспін',
        en: 'Topspin',
        de: 'Topspin',
        pl: 'Topspin',
        zh: '上旋',
    },
    uiLobShot: {
        ru: 'Свеча',
        ua: 'Свічка',
        en: 'Lob',
        de: 'Lob',
        pl: 'Lob',
        zh: '吊高球',
    },
    uiSliceShot: {
        ru: 'Подрезка',
        ua: 'Підрізка',
        en: 'Slice',
        de: 'Slice',
        pl: 'Slice',
        zh: '切削',
    },
    // Native instructional-button labels, mirroring the GXT strings the source uses
    // (CUC_BASE_SWING / CUC_TOPSPIN / CUC_BACKSPIN / CUC_LOB / CUC_CAM / CUC_QUIT /
    //  CUC_BEGIN_SERVE / CUC_STOP_METER / TEN_SB_PLAIN).
    controls: {
        baseSwing: {
            ru: 'Удар',
            ua: 'Удар',
            en: 'Swing',
            de: 'Schlag',
            pl: 'Uderzenie',
            zh: '击球',
        },
        topspin: {
            ru: 'Топспин',
            ua: 'Топспін',
            en: 'Topspin',
            de: 'Topspin',
            pl: 'Topspin',
            zh: '上旋',
        },
        backspin: {
            ru: 'Подрезка',
            ua: 'Підрізка',
            en: 'Slice',
            de: 'Slice',
            pl: 'Slice',
            zh: '切削',
        },
        lob: {
            ru: 'Свеча',
            ua: 'Свічка',
            en: 'Lob',
            de: 'Lob',
            pl: 'Lob',
            zh: '吊高球',
        },
        camera: {
            ru: 'Камера',
            ua: 'Камера',
            en: 'Camera',
            de: 'Kamera',
            pl: 'Kamera',
            zh: '镜头',
        },
        quit: {
            ru: 'Сдаться (удерживать)',
            ua: 'Здатися (утримувати)',
            en: 'Forfeit (hold)',
            de: 'Aufgeben (halten)',
            pl: 'Poddaj się (przytrzymaj)',
            zh: '弃赛（长按）',
        },
        scoreboard: {
            ru: 'Табло',
            ua: 'Табло',
            en: 'Scoreboard',
            de: 'Anzeigetafel',
            pl: 'Tablica wyników',
            zh: '记分牌',
        },
        beginServe: {
            ru: 'Начать подачу',
            ua: 'Почати подачу',
            en: 'Begin serve',
            de: 'Aufschlag beginnen',
            pl: 'Rozpocznij serwis',
            zh: '开始发球',
        },
        stopMeter: {
            ru: 'Зафиксировать силу',
            ua: 'Зафіксувати силу',
            en: 'Stop meter',
            de: 'Kraft festlegen',
            pl: 'Zatrzymaj miernik',
            zh: '锁定力度',
        },
    },
    shardYou: {
        ru: 'Вы',
        ua: 'Ви',
        en: 'You',
        de: 'Du',
        pl: 'Ty',
        zh: '你',
    },
    shardOpponent: {
        ru: 'Соперник',
        ua: 'Суперник',
        en: 'Opponent',
        de: 'Gegner',
        pl: 'Przeciwnik',
        zh: '对手',
    },
    shard_fault: {
        ru: 'Ошибка подачи',
        ua: 'Помилка подачі',
        en: 'Fault',
        de: 'Aufschlagfehler',
        pl: 'Błąd serwisu',
        zh: '发球失误',
    },
    shard_doubleFault: {
        ru: 'Двойная ошибка',
        ua: 'Подвійна помилка',
        en: 'Double fault',
        de: 'Doppelfehler',
        pl: 'Podwójny błąd',
        zh: '双误',
    },
    shard_secondServe: {
        ru: 'Вторая подача',
        ua: 'Друга подача',
        en: 'Second serve',
        de: 'Zweiter Aufschlag',
        pl: 'Drugi serwis',
        zh: '二发',
    },
    shard_ace: {
        ru: 'Эйс',
        ua: 'Ейс',
        en: 'Ace',
        de: 'Ass',
        pl: 'As',
        zh: '发球直接得分',
    },
    shard_let: {
        ru: 'Переигровка подачи',
        ua: 'Перегравання подачі',
        en: 'Let',
        de: 'Netzaufschlag',
        pl: 'Let',
        zh: '擦网重发',
    },
    shard_deuce: {
        ru: 'Ровно',
        ua: 'Рівно',
        en: 'Deuce',
        de: 'Einstand',
        pl: 'Równowaga',
        zh: '平分',
    },
    shard_advantage: {
        ru: 'Больше',
        ua: 'Перевага',
        en: 'Advantage',
        de: 'Vorteil',
        pl: 'Przewaga',
        zh: '占先',
    },
    shard_gamePoint: {
        ru: 'Геймбол',
        ua: 'Геймбол',
        en: 'Game point',
        de: 'Spielball',
        pl: 'Piłka gemowa',
        zh: '局点',
    },
    shard_breakPoint: {
        ru: 'Брейк-пойнт',
        ua: 'Брейк-пойнт',
        en: 'Break point',
        de: 'Breakball',
        pl: 'Break point',
        zh: '破发点',
    },
    shard_setPoint: {
        ru: 'Сетбол',
        ua: 'Сетбол',
        en: 'Set point',
        de: 'Satzball',
        pl: 'Piłka setowa',
        zh: '盘点',
    },
    shard_matchPoint: {
        ru: 'Матчбол',
        ua: 'Матчбол',
        en: 'Match point',
        de: 'Matchball',
        pl: 'Piłka meczowa',
        zh: '赛点',
    },
    shard_gameWon: {
        ru: 'Гейм',
        ua: 'Гейм',
        en: 'Game won',
        de: 'Spiel gewonnen',
        pl: 'Gem wygrany',
        zh: '赢下此局',
    },
    shard_setWon: {
        ru: 'Сет',
        ua: 'Сет',
        en: 'Set won',
        de: 'Satz gewonnen',
        pl: 'Set wygrany',
        zh: '赢下此盘',
    },
    shard_matchWon: {
        ru: 'Победа',
        ua: 'Перемога',
        en: 'Match won',
        de: 'Match gewonnen',
        pl: 'Mecz wygrany',
        zh: '赢下比赛',
    },
    shard_matchLost: {
        ru: 'Поражение',
        ua: 'Поразка',
        en: 'Match lost',
        de: 'Match verloren',
        pl: 'Mecz przegrany',
        zh: '输掉比赛',
    },
    shard_tiebreak: {
        ru: 'Тай-брейк',
        ua: 'Тай-брейк',
        en: 'Tiebreak',
        de: 'Tie-Break',
        pl: 'Tie-break',
        zh: '抢七',
    },
    blip: {
        ru: 'Теннисный корт',
        ua: 'Тенісний корт',
        en: 'Tennis court',
        de: 'Tennisplatz',
        pl: 'Kort tenisowy',
        zh: '网球场',
    },
    opponentUnavailable: {
        ru: 'Соперник недоступен.',
        ua: 'Суперник недоступний.',
        en: 'That opponent is unavailable.',
        de: 'Dieser Gegner ist nicht verfügbar.',
        pl: 'Ten przeciwnik jest niedostępny.',
        zh: '该对手当前无法应战。',
    },
    opponentBusy: {
        ru: 'Соперник уже в игре.',
        ua: 'Суперник уже в грі.',
        en: 'That opponent is already in a match.',
        de: 'Dieser Gegner ist bereits in einem Match.',
        pl: 'Ten przeciwnik jest już w meczu.',
        zh: '该对手已在比赛中。',
    },
    notEnoughMoney: {
        ru: 'Недостаточно наличных.',
        ua: 'Недостатньо готівки.',
        en: 'Not enough cash.',
        de: 'Nicht genug Bargeld.',
        pl: 'Za mało gotówki.',
        zh: '现金不足。',
    },
    opponentCannotAfford: {
        ru: 'Соперник не может оплатить участие.',
        ua: 'Суперник не може сплатити участь.',
        en: 'Your opponent cannot cover the entry fee.',
        de: 'Dein Gegner kann die Startgebühr nicht zahlen.',
        pl: 'Przeciwnik nie może opłacić wpisowego.',
        zh: '对手无法支付报名费。',
    },
    inviteSent: {
        ru: 'Приглашение отправлено.',
        ua: 'Запрошення надіслано.',
        en: 'Invite sent.',
        de: 'Einladung gesendet.',
        pl: 'Zaproszenie wysłane.',
        zh: '邀请已发送。',
    },
    inviteExpired: {
        ru: 'Приглашение истекло.',
        ua: 'Запрошення минуло.',
        en: 'The invite expired.',
        de: 'Die Einladung ist abgelaufen.',
        pl: 'Zaproszenie wygasło.',
        zh: '邀请已过期。',
    },
    inviteDeclined: {
        ru: 'Соперник отклонил приглашение.',
        ua: 'Суперник відхилив запрошення.',
        en: 'Your invite was declined.',
        de: 'Deine Einladung wurde abgelehnt.',
        pl: 'Zaproszenie zostało odrzucone.',
        zh: '对方拒绝了你的邀请。',
    },
    venues: {
        michaelHouse: {
            ru: 'Ротонда-Драйв',
            ua: 'Ротонда-Драйв',
            en: 'Rockford Hills',
            de: 'Rockford Hills',
            pl: 'Rockford Hills',
            zh: '罗克福德山',
        },
        countryClub: {
            ru: 'Загородный клуб',
            ua: 'Заміський клуб',
            en: 'Country club',
            de: 'Country Club',
            pl: 'Klub wiejski',
            zh: '乡村俱乐部',
        },
        vinewoodHotel: {
            ru: 'Отель Вайнвуд',
            ua: 'Готель Вайнвуд',
            en: 'Vinewood hotel',
            de: 'Vinewood-Hotel',
            pl: 'Hotel Vinewood',
            zh: '藤木酒店',
        },
        damVista: {
            ru: 'Плотина Ланд-Врата',
            ua: 'Гребля Ланд-Врата',
            en: 'Land Act Dam',
            de: 'Land-Act-Damm',
            pl: 'Zapora Land Act',
            zh: '土地法大坝',
        },
        richmanHotel: {
            ru: 'Отель Ричман',
            ua: 'Готель Річман',
            en: 'Richman hotel',
            de: 'Richman-Hotel',
            pl: 'Hotel Richman',
            zh: '里奇曼酒店',
        },
        lsuCourt: {
            ru: 'Университет Лос-Сантоса',
            ua: 'Університет Лос-Сантоса',
            en: 'Los Santos University',
            de: 'Universität Los Santos',
            pl: 'Uniwersytet Los Santos',
            zh: '洛圣都大学',
        },
        vespucciHotel: {
            ru: 'Отель Веспуччи',
            ua: 'Готель Веспуччі',
            en: 'Vespucci hotel',
            de: 'Vespucci-Hotel',
            pl: 'Hotel Vespucci',
            zh: '维斯普奇酒店',
        },
        weazelCourt: {
            ru: 'Плаза Уизел',
            ua: 'Плаза Візел',
            en: 'Weazel Plaza',
            de: 'Weazel Plaza',
            pl: 'Weazel Plaza',
            zh: '鼬鼠广场',
        },
        chumashHotel: {
            ru: 'Отель Чумаш',
            ua: 'Готель Чумаш',
            en: 'Chumash hotel',
            de: 'Chumash-Hotel',
            pl: 'Hotel Chumash',
            zh: '丘马什酒店',
        },
    },
    modes: {
        solo: {
            ru: 'Против ИИ',
            ua: 'Проти ШІ',
            en: 'Versus AI',
            de: 'Gegen KI',
            pl: 'Przeciw SI',
            zh: '对战 AI',
        },
        ballMachine: {
            ru: 'Тренажёр',
            ua: 'Тренажер',
            en: 'Ball machine',
            de: 'Ballmaschine',
            pl: 'Maszyna treningowa',
            zh: '发球机',
        },
        versus: {
            ru: 'Против игрока',
            ua: 'Проти гравця',
            en: 'Versus player',
            de: 'Gegen Spieler',
            pl: 'Przeciw graczowi',
            zh: '对战玩家',
        },
    },
    difficulties: {
        easy: {
            ru: 'Лёгкая',
            ua: 'Легка',
            en: 'Easy',
            de: 'Leicht',
            pl: 'Łatwy',
            zh: '简单',
        },
        normal: {
            ru: 'Средняя',
            ua: 'Середня',
            en: 'Normal',
            de: 'Normal',
            pl: 'Normalny',
            zh: '普通',
        },
        hard: {
            ru: 'Сложная',
            ua: 'Складна',
            en: 'Hard',
            de: 'Schwer',
            pl: 'Trudny',
            zh: '困难',
        },
    },
    rulesets: {
        0: {
            ru: 'Один гейм',
            ua: 'Один гейм',
            en: 'One game',
            de: 'Ein Spiel',
            pl: 'Jeden gem',
            zh: '一局',
        },
        1: {
            ru: 'До двух геймов',
            ua: 'До двох геймів',
            en: 'First to 2 games',
            de: 'Erster mit 2 Spielen',
            pl: 'Do 2 gemów',
            zh: '先赢两局',
        },
        2: {
            ru: 'До трёх геймов',
            ua: 'До трьох геймів',
            en: 'First to 3 games',
            de: 'Erster mit 3 Spielen',
            pl: 'Do 3 gemów',
            zh: '先赢三局',
        },
        3: {
            ru: 'Один сет',
            ua: 'Один сет',
            en: 'One set',
            de: 'Ein Satz',
            pl: 'Jeden set',
            zh: '一盘',
        },
        4: {
            ru: 'Три сета',
            ua: 'Три сети',
            en: 'Best of 3 sets',
            de: 'Best of 3 Sätze',
            pl: 'Do dwóch wygranych setów',
            zh: '三盘两胜',
        },
        5: {
            ru: 'Пять сетов',
            ua: 'П’ять сетів',
            en: 'Best of 5 sets',
            de: 'Best of 5 Sätze',
            pl: 'Do trzech wygranych setów',
            zh: '五盘三胜',
        },
    },
    cef: {
        title: {
            ru: 'Теннис',
            ua: 'Теніс',
            en: 'Tennis',
            de: 'Tennis',
            pl: 'Tenis',
            zh: '网球',
        },
        description: {
            ru: 'Выберите корт и формат матча',
            ua: 'Оберіть корт і формат матчу',
            en: 'Pick a court and a match format',
            de: 'Wähle einen Platz und ein Matchformat',
            pl: 'Wybierz kort i format meczu',
            zh: '选择球场与赛制',
        },
        match: {
            ru: 'Матч',
            ua: 'Матч',
            en: 'Match',
            de: 'Match',
            pl: 'Mecz',
            zh: '比赛',
        },
        mode: {
            ru: 'Режим',
            ua: 'Режим',
            en: 'Mode',
            de: 'Modus',
            pl: 'Tryb',
            zh: '模式',
        },
        venue: {
            ru: 'Корт',
            ua: 'Корт',
            en: 'Court',
            de: 'Platz',
            pl: 'Kort',
            zh: '球场',
        },
        ruleset: {
            ru: 'Формат',
            ua: 'Формат',
            en: 'Format',
            de: 'Format',
            pl: 'Format',
            zh: '赛制',
        },
        difficulty: {
            ru: 'Сложность',
            ua: 'Складність',
            en: 'Difficulty',
            de: 'Schwierigkeit',
            pl: 'Poziom trudności',
            zh: '难度',
        },
        opponent: {
            ru: 'Соперник',
            ua: 'Суперник',
            en: 'Opponent',
            de: 'Gegner',
            pl: 'Przeciwnik',
            zh: '对手',
        },
        noOpponents: {
            ru: 'Рядом нет свободных игроков',
            ua: 'Поруч немає вільних гравців',
            en: 'Nobody nearby is free to play',
            de: 'Niemand in der Nähe ist frei',
            pl: 'Nikt w pobliżu nie jest wolny',
            zh: '附近没有空闲的玩家',
        },
        entryFee: {
            ru: 'Взнос',
            ua: 'Внесок',
            en: 'Entry fee',
            de: 'Startgebühr',
            pl: 'Wpisowe',
            zh: '报名费',
        },
        start: {
            ru: 'Начать матч',
            ua: 'Почати матч',
            en: 'Start match',
            de: 'Match starten',
            pl: 'Rozpocznij mecz',
            zh: '开始比赛',
        },
        invitePlayer: {
            ru: 'Пригласить',
            ua: 'Запросити',
            en: 'Send invite',
            de: 'Einladen',
            pl: 'Zaproś',
            zh: '发送邀请',
        },
        topPlayers: {
            ru: 'Лучшие теннисисты',
            ua: 'Найкращі тенісисти',
            en: 'Top players',
            de: 'Top-Spieler',
            pl: 'Najlepsi gracze',
            zh: '排行榜',
        },
        record: {
            ru: 'Победы / поражения',
            ua: 'Перемоги / поразки',
            en: 'Wins / losses',
            de: 'Siege / Niederlagen',
            pl: 'Wygrane / przegrane',
            zh: '胜 / 负',
        },
        rating: {
            ru: 'Рейтинг',
            ua: 'Рейтинг',
            en: 'Rating',
            de: 'Wertung',
            pl: 'Ranking',
            zh: '积分',
        },
        you: {
            ru: 'Вы',
            ua: 'Ви',
            en: 'You',
            de: 'Du',
            pl: 'Ty',
            zh: '你',
        },
        inviteTitle: {
            ru: 'Приглашение в теннис',
            ua: 'Запрошення в теніс',
            en: 'Tennis invite',
            de: 'Tennis-Einladung',
            pl: 'Zaproszenie na tenis',
            zh: '网球邀请',
        },
        inviteBody: {
            ru: '{name} зовёт вас на матч',
            ua: '{name} кличе вас на матч',
            en: '{name} wants to play you',
            de: '{name} fordert dich heraus',
            pl: '{name} wyzywa cię na mecz',
            zh: '{name} 向你发起挑战',
        },
        accept: {
            ru: 'Принять',
            ua: 'Прийняти',
            en: 'Accept',
            de: 'Annehmen',
            pl: 'Akceptuj',
            zh: '接受',
        },
        decline: {
            ru: 'Отклонить',
            ua: 'Відхилити',
            en: 'Decline',
            de: 'Ablehnen',
            pl: 'Odrzuć',
            zh: '拒绝',
        },
    },
};
