export default {
    slots: {
        clip: {
            ru: 'Магазин',
            ua: 'Магазин',
            en: 'Magazine',
            de: 'Magazin',
            pl: 'Magazynek',
        },
        scope: {
            ru: 'Прицел',
            ua: 'Приціл',
            en: 'Scope',
            de: 'Zielfernrohr',
            pl: 'Celownik',
        },
        muzzle: {
            ru: 'Дуло',
            ua: 'Дуло',
            en: 'Muzzle',
            de: 'Mündung',
            pl: 'Wylot lufy',
        },
        flashlight: {
            ru: 'Фонарик',
            ua: 'Ліхтарик',
            en: 'Flashlight',
            de: 'Taschenlampe',
            pl: 'Latarka',
        },
        grip: {
            ru: 'Рукоятка',
            ua: "Руків'я",
            en: 'Grip',
            de: 'Griff',
            pl: 'Chwyt',
        },
        barrel: {
            ru: 'Ствол',
            ua: 'Ствол',
            en: 'Barrel',
            de: 'Lauf',
            pl: 'Lufa',
        },
    },

    // Description of a part item: which slot it goes into
    descs: {
        clip: {
            ru: 'Ставится в слот магазина.',
            ua: 'Встановлюється у слот магазина.',
            en: 'Goes into the magazine slot.',
            de: 'Wird in den Magazinsteckplatz eingesetzt.',
            pl: 'Montowany w gnieździe magazynka.',
        },
        scope: {
            ru: 'Ставится в слот прицела.',
            ua: 'Встановлюється у слот прицілу.',
            en: 'Goes into the scope slot.',
            de: 'Wird in den Zielfernrohr-Steckplatz eingesetzt.',
            pl: 'Montowany w gnieździe celownika.',
        },
        muzzle: {
            ru: 'Ставится на дуло.',
            ua: 'Встановлюється на дуло.',
            en: 'Goes onto the muzzle.',
            de: 'Wird an der Mündung montiert.',
            pl: 'Montowany na wylocie lufy.',
        },
        flashlight: {
            ru: 'Ставится на планку под стволом.',
            ua: 'Встановлюється на планку під стволом.',
            en: 'Goes onto the underbarrel rail.',
            de: 'Wird an der Unterlaufschiene montiert.',
            pl: 'Montowany na szynie pod lufą.',
        },
        grip: {
            ru: 'Ставится на планку под стволом.',
            ua: 'Встановлюється на планку під стволом.',
            en: 'Goes onto the underbarrel rail.',
            de: 'Wird an der Unterlaufschiene montiert.',
            pl: 'Montowany na szynie pod lufą.',
        },
        barrel: {
            ru: 'Заменяет ствол оружия.',
            ua: 'Замінює ствол зброї.',
            en: 'Replaces the weapon barrel.',
            de: 'Ersetzt den Waffenlauf.',
            pl: 'Zastępuje lufę broni.',
        },
    },

    // Weapon family a part fits, when it fits several weapons at once
    families: {
        pistol: {
            ru: 'для пистолетов',
            ua: 'для пістолетів',
            en: 'for pistols',
            de: 'für Pistolen',
            pl: 'do pistoletów',
        },
        rifle: {
            ru: 'для винтовок',
            ua: 'для гвинтівок',
            en: 'for rifles',
            de: 'für Gewehre',
            pl: 'do karabinów',
        },
        sniper: {
            ru: 'для снайперских винтовок',
            ua: 'для снайперських гвинтівок',
            en: 'for sniper rifles',
            de: 'für Scharfschützengewehre',
            pl: 'do karabinów wyborowych',
        },
    },

    // Model tag of a part - only where two parts of the same name could not be told apart otherwise
    variants: {
        ii: {
            ru: 'II',
            ua: 'II',
            en: 'II',
            de: 'II',
            pl: 'II',
        },
        iii: {
            ru: 'III',
            ua: 'III',
            en: 'III',
            de: 'III',
            pl: 'III',
        },
        mk2: {
            ru: 'Mk II',
            ua: 'Mk II',
            en: 'Mk II',
            de: 'Mk II',
            pl: 'Mk II',
        },
    },

    // MAGAZINES AND AMMUNITION
    clip1: {
        ru: 'Стандартный магазин',
        ua: 'Стандартний магазин',
        en: 'Default Clip',
        de: 'Standardmagazin',
        pl: 'Standardowy magazynek',
    },
    clip2: {
        ru: 'Увеличенный магазин',
        ua: 'Збільшений магазин',
        en: 'Extended Clip',
        de: 'Erweitertes Magazin',
        pl: 'Powiększony magazynek',
    },
    clipDrm: {
        ru: 'Барабанный магазин',
        ua: 'Барабанний магазин',
        en: 'Drum Magazine',
        de: 'Trommelmagazin',
        pl: 'Magazynek bębnowy',
    },
    clip1Rv: {
        ru: 'Стандартные патроны',
        ua: 'Стандартні патрони',
        en: 'Default Rounds',
        de: 'Standardmunition',
        pl: 'Standardowe naboje',
    },
    clipAp: {
        ru: 'Бронебойные патроны',
        ua: 'Бронебійні патрони',
        en: 'Armor Piercing Rounds',
        de: 'Panzerbrechende Munition',
        pl: 'Naboje przeciwpancerne',
    },
    clipFmj: {
        ru: 'Патроны в цельнометаллической оболочке',
        ua: 'Патрони в цільнометалевій оболонці',
        en: 'Full Metal Jacket Rounds',
        de: 'Vollmantelmunition',
        pl: 'Naboje pełnopłaszczowe',
    },
    clipHp: {
        ru: 'Экспансивные патроны',
        ua: 'Експансивні патрони',
        en: 'Hollow Point Rounds',
        de: 'Hohlspitzmunition',
        pl: 'Naboje z pociskiem wydrążonym',
    },
    clipTr: {
        ru: 'Трассирующие патроны',
        ua: 'Трасувальні патрони',
        en: 'Tracer Rounds',
        de: 'Leuchtspurmunition',
        pl: 'Naboje smugowe',
    },

    // SHOTGUN SHELLS
    shell: {
        ru: 'Стандартные заряды',
        ua: 'Стандартні заряди',
        en: 'Default Shells',
        de: 'Standardpatronen',
        pl: 'Standardowe naboje',
    },
    shellAp: {
        ru: 'Стальная картечь',
        ua: 'Сталевий шріт',
        en: 'Steel Buckshot Shells',
        de: 'Stahlschrot-Patronen',
        pl: 'Naboje ze stalowym śrutem',
    },
    shellHp: {
        ru: 'Стреловидные заряды',
        ua: 'Стрілоподібні заряди',
        en: 'Flechette Shells',
        de: 'Flechette-Patronen',
        pl: 'Naboje strzałkowe',
    },

    // SCOPES
    scopeMac: {
        ru: 'Прицел',
        ua: 'Приціл',
        en: 'Scope',
        de: 'Zielfernrohr',
        pl: 'Celownik optyczny',
    },
    scopeSml: {
        ru: 'Прицел',
        ua: 'Приціл',
        en: 'Scope',
        de: 'Zielfernrohr',
        pl: 'Celownik optyczny',
    },
    scopeMed: {
        ru: 'Прицел',
        ua: 'Приціл',
        en: 'Scope',
        de: 'Zielfernrohr',
        pl: 'Celownik optyczny',
    },
    scopeLrg: {
        ru: 'Прицел',
        ua: 'Приціл',
        en: 'Scope',
        de: 'Zielfernrohr',
        pl: 'Celownik optyczny',
    },
    scopeMac2: {
        ru: 'Малый прицел',
        ua: 'Малий приціл',
        en: 'Small Scope',
        de: 'Kleines Zielfernrohr',
        pl: 'Mały celownik',
    },
    scopeSml2: {
        ru: 'Средний прицел',
        ua: 'Середній приціл',
        en: 'Medium Scope',
        de: 'Mittleres Zielfernrohr',
        pl: 'Średni celownik',
    },
    scopeMed2: {
        ru: 'Большой прицел',
        ua: 'Великий приціл',
        en: 'Large Scope',
        de: 'Großes Zielfernrohr',
        pl: 'Duży celownik',
    },
    scopeLrg2: {
        ru: 'Прицел с увеличением',
        ua: 'Приціл зі збільшенням',
        en: 'Zoom Scope',
        de: 'Zoom-Zielfernrohr',
        pl: 'Celownik z powiększeniem',
    },
    scopeMax: {
        ru: 'Улучшенный прицел',
        ua: 'Покращений приціл',
        en: 'Advanced Scope',
        de: 'Fortschrittliches Zielfernrohr',
        pl: 'Zaawansowany celownik',
    },
    scopePi: {
        ru: 'Навесной прицел',
        ua: 'Навісний приціл',
        en: 'Mounted Scope',
        de: 'Aufgesetztes Zielfernrohr',
        pl: 'Celownik montowany',
    },
    scopeNv: {
        ru: 'Прицел ночного видения',
        ua: 'Приціл нічного бачення',
        en: 'Night Vision Scope',
        de: 'Nachtsichtzielfernrohr',
        pl: 'Celownik noktowizyjny',
    },
    scopeTh: {
        ru: 'Тепловизионный прицел',
        ua: 'Тепловізійний приціл',
        en: 'Thermal Scope',
        de: 'Wärmebildzielfernrohr',
        pl: 'Celownik termowizyjny',
    },
    holo: {
        ru: 'Голографический прицел',
        ua: 'Голографічний приціл',
        en: 'Holographic Sight',
        de: 'Holovisier',
        pl: 'Celownik holograficzny',
    },
    hvyrfleSig: {
        ru: 'Штатный прицел',
        ua: 'Штатний приціл',
        en: 'Default Sight',
        de: 'Standardvisier',
        pl: 'Celownik standardowy',
    },
    mrflSight: {
        ru: 'Штатный прицел',
        ua: 'Штатний приціл',
        en: 'Default Sight',
        de: 'Standardvisier',
        pl: 'Celownik standardowy',
    },

    // MUZZLE
    supp: {
        ru: 'Глушитель',
        ua: 'Глушник',
        en: 'Suppressor',
        de: 'Schalldämpfer',
        pl: 'Tłumik',
    },
    comp: {
        ru: 'Компенсатор',
        ua: 'Компенсатор',
        en: 'Compensator',
        de: 'Kompensator',
        pl: 'Kompensator',
    },
    muzz1: {
        ru: 'Плоский дульный тормоз',
        ua: 'Плоске дулове гальмо',
        en: 'Flat Muzzle Brake',
        de: 'Flache Mündungsbremse',
        pl: 'Płaski hamulec wylotowy',
    },
    muzz2: {
        ru: 'Тактический дульный тормоз',
        ua: 'Тактичне дулове гальмо',
        en: 'Tactical Muzzle Brake',
        de: 'Taktische Mündungsbremse',
        pl: 'Taktyczny hamulec wylotowy',
    },
    muzz3: {
        ru: 'Утолщенный дульный тормоз',
        ua: 'Потовщене дулове гальмо',
        en: 'Fat-End Muzzle Brake',
        de: 'Mündungsbremse mit dickem Ende',
        pl: 'Hamulec wylotowy z grubą końcówką',
    },
    muzz4: {
        ru: 'Точный дульный тормоз',
        ua: 'Точне дулове гальмо',
        en: 'Precision Muzzle Brake',
        de: 'Präzisions-Mündungsbremse',
        pl: 'Precyzyjny hamulec wylotowy',
    },
    muzz5: {
        ru: 'Усиленный дульный тормоз',
        ua: 'Посилене дулове гальмо',
        en: 'Heavy Duty Muzzle Brake',
        de: 'Hochleistungs-Mündungsbremse',
        pl: 'Wzmocniony hamulec wylotowy',
    },
    muzz6: {
        ru: 'Скошенный дульный тормоз',
        ua: 'Скошене дулове гальмо',
        en: 'Slanted Muzzle Brake',
        de: 'Schräge Mündungsbremse',
        pl: 'Skośny hamulec wylotowy',
    },
    muzz7: {
        ru: 'Раздвоенный дульный тормоз',
        ua: 'Роздвоєне дулове гальмо',
        en: 'Split-End Muzzle Brake',
        de: 'Gespaltene Mündungsbremse',
        pl: 'Rozdwojony hamulec wylotowy',
    },
    muzz8: {
        ru: 'Квадратный дульный тормоз',
        ua: 'Квадратне дулове гальмо',
        en: 'Squared Muzzle Brake',
        de: 'Eckige Mündungsbremse',
        pl: 'Kwadratowy hamulec wylotowy',
    },
    muzz9: {
        ru: 'Раструбный дульный тормоз',
        ua: 'Розтрубне дулове гальмо',
        en: 'Bell-End Muzzle Brake',
        de: 'Trichter-Mündungsbremse',
        pl: 'Hamulec wylotowy z rozszerzeniem',
    },

    // BARREL, GRIP, FLASHLIGHT
    barr: {
        ru: 'Стандартный ствол',
        ua: 'Стандартний ствол',
        en: 'Default Barrel',
        de: 'Standardlauf',
        pl: 'Standardowa lufa',
    },
    barr2: {
        ru: 'Усиленный ствол',
        ua: 'Посилений ствол',
        en: 'Heavy Barrel',
        de: 'Schwerer Lauf',
        pl: 'Ciężka lufa',
    },
    grip: {
        ru: 'Рукоятка',
        ua: "Руків'я",
        en: 'Grip',
        de: 'Griff',
        pl: 'Chwyt',
    },
    flash: {
        ru: 'Фонарик',
        ua: 'Ліхтарик',
        en: 'Flashlight',
        de: 'Taschenlampe',
        pl: 'Latarka',
    },

    // What a part actually does in play on this server. Damage and range are server-computed,
    // so a part whose only game effect is on those numbers says so. {{zoom}} is the factor from
    // shared/configs/weaponZoom.
    effects: {
        stock: {
            ru: 'Заводская деталь, без бонусов.',
            ua: 'Заводська деталь, без бонусів.',
            en: 'Factory part, no bonuses.',
            de: 'Werksteil, ohne Boni.',
            pl: 'Część fabryczna, bez bonusów.',
        },
        clip2: {
            ru: 'Вмещает больше патронов, перезаряжаться приходится реже. На точность и урон не влияет.',
            ua: 'Вміщує більше патронів, перезаряджатися доводиться рідше. На точність і шкоду не впливає.',
            en: 'Holds more rounds, so you reload less often. Does not affect accuracy or damage.',
            de: 'Fasst mehr Patronen, du musst seltener nachladen. Kein Einfluss auf Genauigkeit oder Schaden.',
            pl: 'Mieści więcej naboi, rzadziej trzeba przeładowywać. Nie wpływa na celność ani obrażenia.',
        },
        clipDrm: {
            ru: 'Барабанный магазин: самый большой запас патронов для этого оружия. На точность и урон не влияет.',
            ua: 'Барабанний магазин: найбільший запас патронів для цієї зброї. На точність і шкоду не впливає.',
            en: 'Drum magazine: the largest ammo capacity for this weapon. Does not affect accuracy or damage.',
            de: 'Trommelmagazin: die größte Munitionskapazität für diese Waffe. Kein Einfluss auf Genauigkeit oder Schaden.',
            pl: 'Magazynek bębnowy: największy zapas amunicji dla tej broni. Nie wpływa na celność ani obrażenia.',
        },
        clipTr: {
            ru: 'Часть пуль оставляет светящийся след, по нему видно, куда уходит очередь. Урон не меняется.',
            ua: 'Частина куль залишає світний слід, по ньому видно, куди йде черга. Шкода не змінюється.',
            en: 'Some rounds leave a glowing trail that shows where your fire is going. Damage is unchanged.',
            de: 'Ein Teil der Geschosse zieht eine Leuchtspur, an der man sieht, wohin die Salve geht. Der Schaden bleibt gleich.',
            pl: 'Część pocisków zostawia świecący ślad, po którym widać, dokąd leci seria. Obrażenia bez zmian.',
        },
        supp: {
            ru: 'Выстрел тише и почти без вспышки. Урон и дальность не меняются.',
            ua: 'Постріл тихіший і майже без спалаху. Шкода та дальність не змінюються.',
            en: 'Quieter shots with almost no muzzle flash. Damage and range are unchanged.',
            de: 'Leisere Schüsse fast ohne Mündungsfeuer. Schaden und Reichweite bleiben gleich.',
            pl: 'Cichsze strzały prawie bez błysku. Obrażenia i zasięg bez zmian.',
        },
        comp: {
            ru: 'Гасит подброс камеры при стрельбе на 50%.',
            ua: 'Гасить підкидання камери під час стрільби на 50%.',
            en: 'Cuts camera kick while firing by 50%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 50 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 50%.',
        },
        muzz1: {
            ru: 'Гасит подброс камеры при стрельбе на 35%.',
            ua: 'Гасить підкидання камери під час стрільби на 35%.',
            en: 'Cuts camera kick while firing by 35%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 35 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 35%.',
        },
        muzz2: {
            ru: 'Гасит подброс камеры при стрельбе на 35%.',
            ua: 'Гасить підкидання камери під час стрільби на 35%.',
            en: 'Cuts camera kick while firing by 35%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 35 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 35%.',
        },
        muzz3: {
            ru: 'Гасит подброс камеры при стрельбе на 35%.',
            ua: 'Гасить підкидання камери під час стрільби на 35%.',
            en: 'Cuts camera kick while firing by 35%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 35 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 35%.',
        },
        muzz4: {
            ru: 'Гасит подброс камеры при стрельбе на 35%.',
            ua: 'Гасить підкидання камери під час стрільби на 35%.',
            en: 'Cuts camera kick while firing by 35%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 35 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 35%.',
        },
        muzz5: {
            ru: 'Гасит подброс камеры при стрельбе на 35%.',
            ua: 'Гасить підкидання камери під час стрільби на 35%.',
            en: 'Cuts camera kick while firing by 35%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 35 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 35%.',
        },
        muzz6: {
            ru: 'Гасит подброс камеры при стрельбе на 35%.',
            ua: 'Гасить підкидання камери під час стрільби на 35%.',
            en: 'Cuts camera kick while firing by 35%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 35 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 35%.',
        },
        muzz7: {
            ru: 'Гасит подброс камеры при стрельбе на 35%.',
            ua: 'Гасить підкидання камери під час стрільби на 35%.',
            en: 'Cuts camera kick while firing by 35%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 35 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 35%.',
        },
        muzz8: {
            ru: 'Гасит подброс камеры при стрельбе на 25%.',
            ua: 'Гасить підкидання камери під час стрільби на 25%.',
            en: 'Cuts camera kick while firing by 25%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 25 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 25%.',
        },
        muzz9: {
            ru: 'Гасит подброс камеры при стрельбе на 25%.',
            ua: 'Гасить підкидання камери під час стрільби на 25%.',
            en: 'Cuts camera kick while firing by 25%.',
            de: 'Verringert das Hochschlagen der Kamera beim Schießen um 25 %.',
            pl: 'Zmniejsza podrzut kamery podczas strzelania o 25%.',
        },
        grip: {
            ru: 'Повышает точность: пули ложатся кучнее.',
            ua: 'Підвищує точність: кулі лягають купніше.',
            en: 'Improves accuracy: shots group tighter.',
            de: 'Erhöht die Genauigkeit: die Treffer liegen enger beieinander.',
            pl: 'Zwiększa celność: pociski układają się ciaśniej.',
        },
        flash: {
            ru: 'Подсвечивает цель при прицеливании в темноте.',
            ua: 'Підсвічує ціль під час прицілювання в темряві.',
            en: 'Lights up the target while aiming in the dark.',
            de: 'Leuchtet das Ziel beim Zielen im Dunkeln aus.',
            pl: 'Oświetla cel podczas celowania w ciemności.',
        },
        barr2: {
            ru: 'Меняет внешний вид ствола. Урон и дальность на сервере не меняются.',
            ua: 'Змінює зовнішній вигляд ствола. Шкода та дальність на сервері не змінюються.',
            en: 'Changes the look of the barrel. Damage and range on the server are unchanged.',
            de: 'Ändert das Aussehen des Laufs. Schaden und Reichweite bleiben auf dem Server gleich.',
            pl: 'Zmienia wygląd lufy. Obrażenia i zasięg na serwerze bez zmian.',
        },
        holo: {
            ru: 'Коллиматорная метка. Приближения не даёт.',
            ua: 'Коліматорна мітка. Наближення не дає.',
            en: 'Red dot sight. No magnification.',
            de: 'Rotpunktvisier. Keine Vergrößerung.',
            pl: 'Celownik kolimatorowy. Bez powiększenia.',
        },
        scopePi: {
            ru: 'Позволяет приближать камеру колёсиком мыши при прицеливании от третьего лица, до x{{zoom}}. В приближении пули ложатся кучнее.',
            ua: 'Дає наближати камеру колесом миші під час прицілювання від третьої особи, до x{{zoom}}. У наближенні кулі лягають купніше.',
            en: 'Lets you zoom the camera with the mouse wheel while aiming in third person, up to x{{zoom}}. Zoomed in, your shots group tighter.',
            de: 'Erlaubt beim Zielen aus der dritten Person, die Kamera mit dem Mausrad heranzuzoomen, bis x{{zoom}}. Herangezoomt liegen die Treffer enger beieinander.',
            pl: 'Pozwala przybliżać kamerę kółkiem myszy podczas celowania z trzeciej osoby, do x{{zoom}}. Po przybliżeniu pociski układają się ciaśniej.',
        },
        scopeMac2: {
            ru: 'Позволяет приближать камеру колёсиком мыши при прицеливании от третьего лица, до x{{zoom}}. В приближении пули ложатся кучнее.',
            ua: 'Дає наближати камеру колесом миші під час прицілювання від третьої особи, до x{{zoom}}. У наближенні кулі лягають купніше.',
            en: 'Lets you zoom the camera with the mouse wheel while aiming in third person, up to x{{zoom}}. Zoomed in, your shots group tighter.',
            de: 'Erlaubt beim Zielen aus der dritten Person, die Kamera mit dem Mausrad heranzuzoomen, bis x{{zoom}}. Herangezoomt liegen die Treffer enger beieinander.',
            pl: 'Pozwala przybliżać kamerę kółkiem myszy podczas celowania z trzeciej osoby, do x{{zoom}}. Po przybliżeniu pociski układają się ciaśniej.',
        },
        scopeSml2: {
            ru: 'Позволяет приближать камеру колёсиком мыши при прицеливании от третьего лица, до x{{zoom}}. В приближении пули ложатся кучнее.',
            ua: 'Дає наближати камеру колесом миші під час прицілювання від третьої особи, до x{{zoom}}. У наближенні кулі лягають купніше.',
            en: 'Lets you zoom the camera with the mouse wheel while aiming in third person, up to x{{zoom}}. Zoomed in, your shots group tighter.',
            de: 'Erlaubt beim Zielen aus der dritten Person, die Kamera mit dem Mausrad heranzuzoomen, bis x{{zoom}}. Herangezoomt liegen die Treffer enger beieinander.',
            pl: 'Pozwala przybliżać kamerę kółkiem myszy podczas celowania z trzeciej osoby, do x{{zoom}}. Po przybliżeniu pociski układają się ciaśniej.',
        },
        scopeMed2: {
            ru: 'Позволяет приближать камеру колёсиком мыши при прицеливании от третьего лица, до x{{zoom}}. В приближении пули ложатся кучнее.',
            ua: 'Дає наближати камеру колесом миші під час прицілювання від третьої особи, до x{{zoom}}. У наближенні кулі лягають купніше.',
            en: 'Lets you zoom the camera with the mouse wheel while aiming in third person, up to x{{zoom}}. Zoomed in, your shots group tighter.',
            de: 'Erlaubt beim Zielen aus der dritten Person, die Kamera mit dem Mausrad heranzuzoomen, bis x{{zoom}}. Herangezoomt liegen die Treffer enger beieinander.',
            pl: 'Pozwala przybliżać kamerę kółkiem myszy podczas celowania z trzeciej osoby, do x{{zoom}}. Po przybliżeniu pociski układają się ciaśniej.',
        },
        scopeLrg2: {
            ru: 'Снайперская оптика, приближение примерно до 4x.',
            ua: 'Снайперська оптика, наближення приблизно до 4x.',
            en: 'Sniper optics, zoom up to about 4x.',
            de: 'Scharfschützenoptik, Zoom bis etwa 4x.',
            pl: 'Optyka snajperska, przybliżenie do około 4x.',
        },
        scopeMax: {
            ru: 'Снайперская оптика, приближение примерно до 6x.',
            ua: 'Снайперська оптика, наближення приблизно до 6x.',
            en: 'Sniper optics, zoom up to about 6x.',
            de: 'Scharfschützenoptik, Zoom bis etwa 6x.',
            pl: 'Optyka snajperska, przybliżenie do około 6x.',
        },
        scopeNv: {
            ru: 'Снайперская оптика с ночным видением, приближение примерно до 4x.',
            ua: 'Снайперська оптика з нічним баченням, наближення приблизно до 4x.',
            en: 'Sniper optics with night vision, zoom up to about 4x.',
            de: 'Scharfschützenoptik mit Nachtsicht, Zoom bis etwa 4x.',
            pl: 'Optyka snajperska z noktowizją, przybliżenie do około 4x.',
        },
        scopeTh: {
            ru: 'Снайперская оптика с тепловизором, приближение примерно до 4x.',
            ua: 'Снайперська оптика з тепловізором, наближення приблизно до 4x.',
            en: 'Sniper optics with thermal vision, zoom up to about 4x.',
            de: 'Scharfschützenoptik mit Wärmebild, Zoom bis etwa 4x.',
            pl: 'Optyka snajperska z termowizją, przybliżenie do około 4x.',
        },
    },
};
