export const npc = {
    freddy: {
        ru: 'Фредди',
        ua: 'Фреддi',
        en: 'Freddy',
        de: 'Freddy',
        pl: 'Freddy',
        zh: '弗莱迪',
    },
    james: {
        ru: 'Джеймс',
        ua: 'Джеймс',
        en: 'James',
        de: 'James',
        pl: 'James',
        zh: '詹姆斯',
    },
    robert: {
        ru: 'Роберт',
        ua: 'Роберт',
        en: 'Robert',
        de: 'Robert',
        pl: 'Robert',
        zh: '罗伯特',
    },
    michael: {
        ru: 'Майкл',
        ua: 'Майкл',
        en: 'Michael',
        de: 'Michael',
        pl: 'Michael',
        zh: '迈克尔',
    },
    david: {
        ru: 'Дэвид',
        ua: 'Девід',
        en: 'David',
        de: 'David',
        pl: 'David',
        zh: '戴维',
    },
    william: {
        ru: 'Уильям',
        ua: 'Вільям',
        en: 'William',
        de: 'William',
        pl: 'William',
        zh: '威廉',
    },
    john: {
        ru: 'Джон',
        ua: 'Джон',
        en: 'John',
        de: 'John',
        pl: 'John',
        zh: '约翰',
    },
    brian: {
        ru: 'Брайан',
        ua: 'Брайан',
        en: 'Brian',
        de: 'Brian',
        pl: 'Brian',
        zh: '布莱恩',
    },
    matthew: {
        ru: 'Мэттью',
        ua: 'Меттью',
        en: 'Matthew',
        de: 'Matthew',
        pl: 'Mateusz',
        zh: '马修',
    },
    joseph: {
        ru: 'Джозеф',
        ua: 'Джозеф',
        en: 'Joseph',
        de: 'Joseph',
        pl: 'Józef',
        zh: '乔瑟夫',
    },
    richard: {
        ru: 'Ричард',
        ua: 'Річард',
        en: 'Richard',
        de: 'Richard',
        pl: 'Ryszard',
        zh: '理查德',
    },
    daniel: {
        ru: 'Дэниел',
        ua: 'Деніел',
        en: 'Daniel',
        de: 'Daniel',
        pl: 'Daniel',
        zh: '丹尼尔',
    },
    paul: {
        ru: 'Пол',
        ua: 'Пол',
        en: 'Paul',
        de: 'Paul',
        pl: 'Paweł',
        zh: '保罗',
    },
    mark: {
        ru: 'Марк',
        ua: 'Марк',
        en: 'Mark',
        de: 'Mark',
        pl: 'Marek',
        zh: '马克',
    },
    anthony: {
        ru: 'Энтони',
        ua: 'Ентоні',
        en: 'Anthony',
        de: 'Anton',
        pl: 'Antoni',
        zh: '安东尼',
    },
    'santa-claus': {
        ru: 'Санта-Клаус',
        ua: 'Санта-Клаус',
        en: 'Santa-Claus',
        de: 'Santa',
        pl: 'Santa-Claus',
        zh: '圣诞老人',
    },
    mary: {
        en: 'Mary',
        ru: 'Мэри',
        ua: 'Мерi',
        de: 'Maria',
        pl: 'Maria',
        zh: '玛丽',
    },
    emily: {
        en: 'Emily',
        ru: 'Эмили',
        ua: 'Емiлi',
        de: 'Emily',
        pl: 'Emilia',
        zh: '艾米莉',
    },
    rider: {
        ru: 'Райдер',
        ua: 'Райдер',
        en: 'Ryder',
        de: 'Reiter',
        pl: 'Jeździec',
        zh: '莱德',
    },
    joe: {
        ru: 'Джо',
        ua: 'Джо',
        en: 'Joe',
        de: 'Joe',
        pl: 'Joe',
        zh: '乔',
    },
    natalia: {
        ru: 'Наталья',
        ua: 'Наталiя',
        en: 'Natalia',
        de: 'Natalia',
        pl: 'Natalia',
        zh: '纳塔莉亚',
    },
    lisa: {
        ru: 'Лиза',
        ua: 'Лiза',
        en: 'Lisa',
        de: 'Lisa',
        pl: 'Lisa',
        zh: '莉莎',
    },
    slivnoyVitalya: {
        ru: 'Сливной Виталя',
        ua: 'Зливний Віталя',
        en: 'Drain Vitalya',
        de: 'Obdachloser Vitalya',
        pl: 'Odpływ Vitalya',
    },
    surgeon: {
        ru: 'Хирург',
        ua: 'Хірург',
        en: 'Surgeon',
        de: 'Chirurg',
        pl: 'Chirurg',
    },
    finn: {
        ru: 'Финн',
        ua: 'Фiнн',
        en: 'Finn',
        de: 'Finn',
        pl: 'Finn',
        zh: '芬恩',
    },
    diver: {
        ru: 'Главный Дайвер',
        ua: 'Головний Дайвер',
        en: 'Chief Diver',
        de: 'Taucher',
        pl: 'Główny Nurek',
    },
    melissa: {
        ru: 'Мелисса',
        ua: 'Мелісса',
        en: 'Melissa',
        de: 'Melissa',
        pl: 'Melissa',
    },
};
