export const server = {
    name: {
        ru: 'Автосалон',
        ua: 'Автосалон',
        en: 'Car dealership',
        de: 'Autohaus',
        pl: 'Salon samochodowy',
        zh: '汽车经销商',
    },
    low: {
        ru: 'Низкого класса',
        ua: 'Низького класу',
        en: 'Low-class',
        de: 'Niedrige Klasse',
        pl: 'Niska klasa',
        zh: '低级',
    },
    medium: {
        ru: 'Среднего класса',
        ua: 'Середнього класу',
        en: 'Medium-class',
        de: 'Mittelklasse',
        pl: 'Średnia klasa',
        zh: '中级',
    },
    luxury: {
        ru: 'Luxury',
        ua: 'Люкс',
        en: 'Luxury',
        de: 'Luxus',
        pl: 'Luksus',
        zh: '豪华',
    },
    moto: {
        ru: 'Мото',
        ua: 'Мото',
        en: 'Motorcycle',
        de: 'Motorrad',
        pl: 'Motocykl',
        zh: '摩托车',
    },
    boat: {
        ru: 'Водного транспорта',
        ua: 'Водного транспорту',
        en: 'Watercraft',
        de: 'Wasserfahrzeug',
        pl: 'Pojazd wodny',
        zh: '船只',
    },
    helicopter: {
        ru: 'Вертолётов',
        ua: 'Гелiкоптерiв',
        en: 'Helicopters',
        de: 'Hubschrauber',
        pl: 'Śmigłowców',
        zh: '直升机',
    },

    plane: {
        ru: 'Самолётов',
        ua: 'Лiтакiв',
        en: 'Planes',
        de: 'Flugzeuge',
        pl: 'Samolotów',
        zh: '飞机',
    },
    notEnoughtParkingSpaces: {
        ua: 'У вас недостатньо парковочних місць',
        en: 'You do not have enough parking spaces',
        ru: 'У вас недостаточно парковочных мест',
        de: 'Du hast nicht genügend Parkplätze',
        pl: 'Nie masz wystarczającej ilości miejsc parkingowych',
        zh: '你没有足够的停车位',
    },
    notEnoughtMoney: {
        ua: 'У вас недостатньо коштів для покупки цього автомобіля',
        en: 'You do not have enough money to buy this vehicle',
        ru: 'У вас недостаточно средств для покупки этой машины',
        de: 'Du hast nicht genügend Geld, um dieses Fahrzeug zu kaufen',
        pl: 'Nie masz wystarczająco dużo pieniędzy, aby kupić ten pojazd',
        zh: '你没有足够的钱买这辆车',
    },
    // The payment sheet's line (modules/payment).
    payment: {
        description: {
            ru: 'Покупка {{name}} в автосалоне',
            ua: 'Купівля {{name}} в автосалоні',
            en: 'Buying {{name}} at the dealership',
            de: 'Kauf von {{name}} im Autohaus',
            pl: 'Zakup {{name}} w salonie',
            zh: '在汽车经销店购买 {{name}}',
        },
    },
    buyedVehicle: {
        ua: 'Ви успішно придбали {{name}}',
        en: 'You have successfully purchased the {{name}}',
        ru: 'Вы успешно купили {{name}}',
        de: 'Du hast erfolgreich {{name}} gekauft',
        pl: 'Pomyślnie zakupiono {{name}}',
        zh: '您已成功购买{{name}}',
    },
    // Where the bought vehicle goes (systems/businesses/carshop/buyTargets).
    buyTarget: {
        noOrganizationPermission: {
            ru: 'Вы не можете покупать транспорт для организации',
            ua: 'Ви не можете купувати транспорт для організації',
            en: 'You cannot buy vehicles for the organization',
            de: 'Du darfst keine Fahrzeuge für die Organisation kaufen',
            pl: 'Nie możesz kupować pojazdów dla organizacji',
        },
        organizationNoSlots: {
            ru: 'В гаражах организации нет свободных мест',
            ua: 'У гаражах організації немає вільних місць',
            en: 'The organization garages have no free places',
            de: 'In den Garagen der Organisation sind keine Plätze frei',
            pl: 'W garażach organizacji nie ma wolnych miejsc',
        },
        houseNoSlots: {
            ru: 'В гараже этого дома нет свободных мест',
            ua: 'У гаражі цього будинку немає вільних місць',
            en: 'This house garage has no free places',
            de: 'In der Garage dieses Hauses sind keine Plätze frei',
            pl: 'W garażu tego domu nie ma wolnych miejsc',
        },
        boughtForOrganization: {
            ru: 'Вы купили {{name}} для организации {{organization}}. Машина стоит в её гараже',
            ua: 'Ви купили {{name}} для організації {{organization}}. Машина стоїть у її гаражі',
            en: 'You bought the {{name}} for {{organization}}. It is waiting in the organization garage',
            de: 'Du hast {{name}} für {{organization}} gekauft. Es steht in der Garage der Organisation',
            pl: 'Kupiono {{name}} dla organizacji {{organization}}. Pojazd stoi w jej garażu',
        },
    },
};
