export const server = {
    name: {
        ru: 'Автосалон',
        ua: 'Автосалон',
        en: 'Car dealership',
        de: 'Autohaus',
        pl: 'Salon samochodowy',
        zh:'汽车经销商',
    },
    low: {
        ru: 'Низкого класса',
        ua: 'Низького класу',
        en: 'Low-class',
        de: 'Niedrige Klasse',
        pl: 'Niska klasa',
       zh:'低级',
    },
    medium: {
        ru: 'Среднего класса',
        ua: 'Середнього класу',
        en: 'Medium-class',
        de: 'Mittelklasse',
        pl: 'Średnia klasa',
       zh:'中级',
    },
    luxury: {
        ru: 'Luxury',
        ua: 'Люкс',
        en: 'Luxury',
        de: 'Luxus',
        pl: 'Luksus',
       zh:'豪华',
    },
    moto: {
        ru: 'Мото',
        ua: 'Мото',
        en: 'Motorcycle',
        de: 'Motorrad',
        pl: 'Motocykl',
       zh:'摩托车',
    },
    boat: {
        ru: 'Водного транспорта',
        ua: 'Водного транспорту',
        en: 'Watercraft',
        de: 'Wasserfahrzeug',
        pl: 'Pojazd wodny',
       zh:'船只',
    },
    helicopter: {
        ru: 'Вертолётов',
        ua: 'Гелiкоптерiв',
        en: 'Helicopters',
        de: 'Hubschrauber',
        pl: 'Śmigłowców',
       zh:'直升机',
    },

    plane: {
        ru: 'Самолётов',
        ua: 'Лiтакiв',
        en: 'Planes',
        de: 'Flugzeuge',
        pl: 'Samolotów',
       zh:'飞机',
    },
    notEnoughtParkingSpaces: {
        ua: 'У вас недостатньо парковочних місць',
        en: 'You do not have enough parking spaces',
        ru: 'У вас недостаточно парковочных мест',
        de: 'Sie haben nicht genügend Parkplätze',
        pl: 'Nie masz wystarczającej ilości miejsc parkingowych',
       zh:'你没有足够的停车位',
    },
    notEnoughtMoney: {
        ua: 'У вас недостатньо коштів для покупки цього автомобіля',
        en: 'You do not have enough money to buy this vehicle',
        ru: 'У вас недостаточно средств для покупки этой машины',
        de: 'Sie haben nicht genügend Geld, um dieses Fahrzeug zu kaufen',
        pl: 'Nie masz wystarczająco dużo pieniędzy, aby kupić ten pojazd',
        zh:'你没有足够的钱买这辆车',
    },
    buyedVehicle: {
        ua: 'Ви успішно придбали {{name}}',
        en: 'You have successfully purchased the {{name}}',
        ru: 'Вы успешно купили {{name}}',
        de: 'Sie haben erfolgreich {{name}} gekauft',
        pl: 'Pomyślnie zakupiono {{name}}',
       zh:'您已成功购买{{name}}',
    },
};
