export const cargoList = {
    // ------------------------------------------------------------------- legal
    cargoWarehouse: {
        name: {
            ru: 'Товар со склада',
            ua: 'Товар зі складу',
            en: 'Warehouse Freight',
            de: 'Lagerfracht',
            pl: 'Towar z magazynu',
        },
        description: {
            ru: 'Склад в Сайпресс-Флэтс забит под потолок, а почта в Вайнвуде ждёт посылки со вчерашнего дня. Паллета в кузов, рейс до отделения, разгрузка - и так {{rolledGoal}} раз. Идите бригадой: на приёмке за одиночку никто не распишется.',
            ua: 'Склад у Сайпресс-Флетс забитий під стелю, а пошта у Вайнвуді чекає посилки з учора. Палета в кузов, рейс до відділення, розвантаження - і так {{rolledGoal}} разів. Ідіть бригадою: на прийманні за одинака ніхто не розпишеться.',
            en: 'The Cypress Flats warehouse is packed to the roof and the Vinewood post office has been waiting since yesterday. Pallet on the truck, run to the counter, unload - {{rolledGoal}} times over. Go as a crew: nobody signs for a man working alone.',
            de: 'Das Lagerhaus in Cypress Flats ist bis unters Dach voll und das Postamt in Vinewood wartet seit gestern. Palette auf den LKW, Fahrt zum Schalter, abladen - {{rolledGoal}} Mal. Fahrt als Crew: fuer einen Einzelnen unterschreibt an der Annahme keiner.',
            pl: 'Magazyn w Cypress Flats jest zapchany po sufit, a poczta w Vinewood czeka od wczoraj. Paleta na pake, kurs na poczte, rozladunek - i tak {{rolledGoal}} razy. Jedzcie ekipa: za samotnika nikt na odbiorze sie nie podpisze.',
        },
        objective: {
            ru: 'Перевезти {{rolledGoal}} паллет со склада на почту',
            ua: 'Перевезти {{rolledGoal}} палет зі складу на пошту',
            en: 'Haul {{rolledGoal}} pallets from the warehouse to the post office',
            de: '{{rolledGoal}} Paletten vom Lager zum Postamt fahren',
            pl: 'Przewiezc {{rolledGoal}} palet z magazynu na poczte',
        },
    },
    cargoTrain: {
        name: {
            ru: 'Товар с поезда',
            ua: 'Товар з поїзда',
            en: 'Rail Freight',
            de: 'Bahnfracht',
            pl: 'Towar z pociagu',
        },
        description: {
            ru: 'С поезда в Полето сгружают корм, а ферма в Грейпсиде без него встанет к вечеру. От тупика до фермы - {{rolledGoal}} рейсов, и мешки по дороге не терять. Путь неблизкий, держитесь колонной.',
            ua: 'З поїзда в Полето вивантажують корм, а ферма в Грейпсиді без нього стане до вечора. Від тупика до ферми - {{rolledGoal}} рейсів, і мішки дорогою не губити. Шлях неблизький, тримайтеся колоною.',
            en: 'They are unloading feed off the train at Paleto, and the Grapeseed farm stalls by evening without it. Siding to farm, {{rolledGoal}} runs, and no sacks left on the roadside. It is a long haul - stay in convoy.',
            de: 'In Paleto wird Futter vom Zug geladen, und ohne das steht die Farm in Grapeseed bis zum Abend still. Vom Rangiergleis zur Farm, {{rolledGoal}} Fahrten, und keine Saecke am Strassenrand. Weiter Weg - bleibt im Konvoi.',
            pl: 'W Paleto zrzucaja pasze z pociagu, a farma w Grapeseed bez niej stanie do wieczora. Z bocznicy na farme, {{rolledGoal}} kursow, i zadnego worka na poboczu. Trasa dluga - trzymajcie sie w kolumnie.',
        },
        objective: {
            ru: 'Отвезти {{rolledGoal}} паллет с кормом на ферму Грейпсид',
            ua: 'Відвезти {{rolledGoal}} палет з кормом на ферму Грейпсид',
            en: 'Run {{rolledGoal}} pallets of feed to the Grapeseed farm',
            de: '{{rolledGoal}} Paletten Futter zur Farm Grapeseed bringen',
            pl: 'Zawiezc {{rolledGoal}} palet paszy na farme Grapeseed',
        },
    },
    cargoShip: {
        name: {
            ru: 'Товар с корабля',
            ua: 'Товар з корабля',
            en: 'Ship Freight',
            de: 'Schiffsfracht',
            pl: 'Towar ze statku',
        },
        description: {
            ru: 'Судно с запчастями встало в терминале, а завод в пустыне Гранд-Сенора стоит без линии. Дорога через полкарты, {{rolledGoal}} рейсов - выезжайте колонной и не растягивайтесь. Capisci?',
            ua: 'Судно із запчастинами стало в терміналі, а завод у пустелі Гранд-Сенора стоїть без лінії. Дорога через півкарти, {{rolledGoal}} рейсів - виїжджайте колоною і не розтягуйтеся. Capisci?',
            en: 'The parts ship is sitting at the terminal and the Grand Senora factory has a dead line. Half the map of road, {{rolledGoal}} runs - roll out in convoy and do not string out. Capisci?',
            de: 'Das Ersatzteilschiff liegt am Terminal und in der Fabrik in Grand Senora steht die Linie still. Halbe Karte Fahrt, {{rolledGoal}} Touren - fahrt im Konvoi los und reisst nicht auseinander. Capisci?',
            pl: 'Statek z czesciami stoi w terminalu, a fabryka w Grand Senora ma martwa linie. Pol mapy drogi, {{rolledGoal}} kursow - ruszajcie kolumna i nie rozciagajcie sie. Capisci?',
        },
        objective: {
            ru: 'Доставить {{rolledGoal}} паллет с запчастями на завод',
            ua: 'Доставити {{rolledGoal}} палет із запчастинами на завод',
            en: 'Deliver {{rolledGoal}} pallets of parts to the factory',
            de: '{{rolledGoal}} Paletten Ersatzteile zur Fabrik liefern',
            pl: 'Dostarczyc {{rolledGoal}} palet czesci do fabryki',
        },
    },
    cargoPlane: {
        name: {
            ru: 'Товар с самолёта',
            ua: 'Товар з літака',
            en: 'Air Freight',
            de: 'Luftfracht',
            pl: 'Towar z samolotu',
        },
        description: {
            ru: 'Борт разгружают в грузовом терминале аэропорта, кейсы идут ко мне на склад в Сайпресс-Флэтс. {{rolledGoal}} рейсов, и ни один кейс не должен уехать не туда - за этот груз я отвечаю лично.',
            ua: 'Борт розвантажують у вантажному терміналі аеропорту, кейси йдуть до мене на склад у Сайпресс-Флетс. {{rolledGoal}} рейсів, і жоден кейс не повинен поїхати не туди - за цей вантаж я відповідаю особисто.',
            en: 'They are stripping the plane at the airport freight terminal and the cases come to my warehouse in Cypress Flats. {{rolledGoal}} runs, and not one case goes anywhere else - I answer for this load personally.',
            de: 'Die Maschine wird am Frachtterminal des Flughafens entladen, die Kisten gehen in mein Lager in Cypress Flats. {{rolledGoal}} Fahrten, und keine einzige Kiste faehrt woandershin - fuer diese Ladung hafte ich persoenlich.',
            pl: 'Samolot rozladowuja na terminalu cargo lotniska, a walizki jada do mojego magazynu w Cypress Flats. {{rolledGoal}} kursow i ani jedna walizka nie pojedzie gdzie indziej - za ten ladunek odpowiadam osobiscie.',
        },
        objective: {
            ru: 'Перевезти {{rolledGoal}} паллет с кейсами на склад',
            ua: 'Перевезти {{rolledGoal}} палет із кейсами на склад',
            en: 'Move {{rolledGoal}} pallets of cases to the warehouse',
            de: '{{rolledGoal}} Paletten Kisten ins Lager fahren',
            pl: 'Przewiezc {{rolledGoal}} palet walizek do magazynu',
        },
    },

    // ------------------------------------------------------------------- crime
    blackContainers: {
        name: {
            ru: 'Неизвестные контейнеры',
            ua: 'Невідомі контейнери',
            en: 'Unmarked Containers',
            de: 'Unbekannte Container',
            pl: 'Nieznane kontenery',
        },
        description: {
            ru: 'На Элизиан пришли контейнеры без единой бумажки - разбирайте по паллетам и везите в цех на Рокфорд-Хиллз. {{rolledGoal}} рейсов, все пятеро на разгрузке, и фарами у ворот не свети.',
            ua: 'На Елізіан прийшли контейнери без жодного папірця - розбирайте по палетах і везіть у цех на Рокфорд-Хіллз. {{rolledGoal}} рейсів, усі п\'ятеро на розвантаженні, і фарами біля воріт не світи.',
            en: 'Containers landed on Elysian without a single sheet of paper - break them onto pallets and run them to the shop in Rockford Hills. {{rolledGoal}} runs, all five of you at the unload, and keep your headlights off the gate.',
            de: 'Auf Elysian stehen Container ohne ein einziges Papier - auf Paletten aufteilen und ab in die Werkstatt in Rockford Hills. {{rolledGoal}} Fahrten, alle fuenf beim Abladen, und leuchtet nicht mit den Scheinwerfern aufs Tor.',
            pl: 'Na Elysian przyszly kontenery bez jednej kartki - rozbierzcie na palety i wieziecie do warsztatu na Rockford Hills. {{rolledGoal}} kursow, cala piatka przy rozladunku i nie swiec reflektorami na brame.',
        },
        objective: {
            ru: 'Вывезти {{rolledGoal}} паллет из контейнеров в цех',
            ua: 'Вивезти {{rolledGoal}} палет із контейнерів у цех',
            en: 'Move {{rolledGoal}} pallets from the containers to the shop',
            de: '{{rolledGoal}} Paletten aus den Containern in die Werkstatt bringen',
            pl: 'Wywiezc {{rolledGoal}} palet z kontenerow do warsztatu',
        },
    },
    blackSite: {
        name: {
            ru: 'Подставная стройка',
            ua: 'Підставне будівництво',
            en: 'Front Construction Site',
            de: 'Schein-Baustelle',
            pl: 'Podstawiona budowa',
        },
        description: {
            ru: 'Списанный кабель лежит у меня в Ранчо, а стройка у Форт-Занкудо ждёт его сегодня. {{rolledGoal}} рейсов мимо военной базы - скорость ровная, лишнего шума не надо, там вопросов не задают.',
            ua: 'Списаний кабель лежить у мене в Ранчо, а будівництво біля Форт-Занкудо чекає на нього сьогодні. {{rolledGoal}} рейсів повз військову базу - швидкість рівна, зайвого шуму не треба, там питань не ставлять.',
            en: 'The write-off cable is sitting in my yard in Rancho and the site by Fort Zancudo wants it today. {{rolledGoal}} runs past a military base - keep it steady and keep it quiet, nobody there asks questions first.',
            de: 'Das abgeschriebene Kabel liegt bei mir in Rancho, und die Baustelle bei Fort Zancudo will es heute. {{rolledGoal}} Fahrten an einem Militaerstuetzpunkt vorbei - ruhig fahren, leise bleiben, dort fragt keiner erst nach.',
            pl: 'Spisany kabel lezy u mnie w Rancho, a budowa przy Fort Zancudo chce go dzisiaj. {{rolledGoal}} kursow obok bazy wojskowej - rowno i cicho, tam nikt najpierw nie pyta.',
        },
        objective: {
            ru: 'Отвезти {{rolledGoal}} паллет кабеля на стройку',
            ua: 'Відвезти {{rolledGoal}} палет кабелю на будівництво',
            en: 'Run {{rolledGoal}} pallets of cable to the site',
            de: '{{rolledGoal}} Paletten Kabel zur Baustelle fahren',
            pl: 'Zawiezc {{rolledGoal}} palet kabla na budowe',
        },
    },
    blackChem: {
        name: {
            ru: 'Незаконное предприятие',
            ua: 'Незаконне підприємство',
            en: 'Illicit Enterprise',
            de: 'Illegaler Betrieb',
            pl: 'Nielegalne przedsiebiorstwo',
        },
        description: {
            ru: 'Химия для лабы идёт через подставное предприятие в Гранд-Сенора. {{rolledGoal}} рейсов: бочки не бить, крышки не открывать, в аварию не попадать. Одна течь - и везти будет уже некому.',
            ua: 'Хімія для лабораторії йде через підставне підприємство в Гранд-Сенора. {{rolledGoal}} рейсів: бочки не бити, кришки не відкривати, в аварію не потрапляти. Один витік - і везти вже буде нікому.',
            en: 'The lab precursor moves through the front company in Grand Senora. {{rolledGoal}} runs: do not dent the drums, do not crack the lids, do not crash. One leak and there is nobody left to drive.',
            de: 'Der Laborstoff laeuft ueber die Scheinfirma in Grand Senora. {{rolledGoal}} Fahrten: Faesser nicht verbeulen, Deckel nicht oeffnen, keinen Unfall bauen. Ein Leck und es faehrt keiner mehr.',
            pl: 'Chemia do labki idzie przez firme-przykrywke w Grand Senora. {{rolledGoal}} kursow: beczek nie obijac, wiek nie otwierac, nie rozwalic sie. Jeden wyciek i nie bedzie komu wiezc.',
        },
        objective: {
            ru: 'Доставить {{rolledGoal}} паллет химии на предприятие',
            ua: 'Доставити {{rolledGoal}} палет хімії на підприємство',
            en: 'Deliver {{rolledGoal}} pallets of chemicals to the enterprise',
            de: '{{rolledGoal}} Paletten Chemie zum Betrieb liefern',
            pl: 'Dostarczyc {{rolledGoal}} palet chemii do przedsiebiorstwa',
        },
    },
    blackShip: {
        name: {
            ru: 'Нелегальное судно',
            ua: 'Нелегальне судно',
            en: 'Contraband Vessel',
            de: 'Illegales Schiff',
            pl: 'Nielegalny statek',
        },
        description: {
            ru: 'С судна снимают взрывчатку, и она нужна на подземном заводе, а не в порту. {{rolledGoal}} рейсов, колонной, без резких торможений. Кто уронит ящик - хоронить будет нечего.',
            ua: 'Із судна знімають вибухівку, і вона потрібна на підземному заводі, а не в порту. {{rolledGoal}} рейсів, колоною, без різких гальмувань. Хто впустить ящик - ховати буде нічого.',
            en: 'They are pulling explosives off the hull, and they belong at the underground plant, not on the dock. {{rolledGoal}} runs, in convoy, no hard braking. Drop a crate and there will be nothing left to bury.',
            de: 'Vom Rumpf wird Sprengstoff geholt, und der gehoert in die unterirdische Fabrik, nicht auf den Kai. {{rolledGoal}} Fahrten, im Konvoi, kein hartes Bremsen. Wer eine Kiste fallen laesst, den muss keiner mehr begraben.',
            pl: 'Z kadluba sciagaja materialy wybuchowe i maja trafic do podziemnej fabryki, nie na nabrzeze. {{rolledGoal}} kursow, w kolumnie, bez ostrego hamowania. Kto upusci skrzynie, tego nie bedzie co chowac.',
        },
        objective: {
            ru: 'Довезти {{rolledGoal}} паллет со взрывчаткой на завод',
            ua: 'Довезти {{rolledGoal}} палет із вибухівкою на завод',
            en: 'Get {{rolledGoal}} pallets of explosives to the plant',
            de: '{{rolledGoal}} Paletten Sprengstoff zur Fabrik bringen',
            pl: 'Dowiezc {{rolledGoal}} palet materialow wybuchowych do fabryki',
        },
    },
};

// Every cargo point names the PLACE it is, not its role in the run - the runner already draws
// the contract name under the label, so "Loading point" twice would say nothing.
export const cargoBlips = {
    cargoCypressWarehouse: {
        ru: 'Склад в Сайпресс-Флэтс',
        ua: 'Склад у Сайпресс-Флетс',
        en: 'Cypress Flats warehouse',
        de: 'Lagerhaus Cypress Flats',
        pl: 'Magazyn Cypress Flats',
    },
    cargoVinewoodPost: {
        ru: 'Почтовое отделение Вайнвуда',
        ua: 'Поштове відділення Вайнвуда',
        en: 'Vinewood post office',
        de: 'Postamt Vinewood',
        pl: 'Poczta Vinewood',
    },
    cargoPaletoSiding: {
        ru: 'Железнодорожный тупик Полето',
        ua: 'Залізничний тупик Полето',
        en: 'Paleto rail siding',
        de: 'Rangiergleis Paleto',
        pl: 'Bocznica kolejowa Paleto',
    },
    cargoGrapeseedFarm: {
        ru: 'Ферма Грейпсид',
        ua: 'Ферма Грейпсид',
        en: 'Grapeseed farm',
        de: 'Farm Grapeseed',
        pl: 'Farma Grapeseed',
    },
    cargoContainerTerminal: {
        ru: 'Контейнерный терминал порта',
        ua: 'Контейнерний термінал порту',
        en: 'Port container terminal',
        de: 'Container-Terminal im Hafen',
        pl: 'Terminal kontenerowy w porcie',
    },
    cargoDesertFactory: {
        ru: 'Завод в пустыне Гранд-Сенора',
        ua: 'Завод у пустелі Гранд-Сенора',
        en: 'Grand Senora desert factory',
        de: 'Fabrik in der Grand-Senora-Wueste',
        pl: 'Fabryka na pustyni Grand Senora',
    },
    cargoAirportFreight: {
        ru: 'Грузовой терминал аэропорта',
        ua: 'Вантажний термінал аеропорту',
        en: 'Airport freight terminal',
        de: 'Frachtterminal des Flughafens',
        pl: 'Terminal cargo lotniska',
    },
    blackElysianContainers: {
        ru: 'Контейнеры на Элизиан-Айленд',
        ua: 'Контейнери на Елізіан-Айленд',
        en: 'Elysian Island containers',
        de: 'Container auf Elysian Island',
        pl: 'Kontenery na Elysian Island',
    },
    blackRockfordShop: {
        ru: 'Подпольный цех в Рокфорд-Хиллз',
        ua: 'Підпільний цех у Рокфорд-Хіллз',
        en: 'Rockford Hills underground shop',
        de: 'Untergrundwerkstatt Rockford Hills',
        pl: 'Podziemny warsztat Rockford Hills',
    },
    blackRanchoYard: {
        ru: 'Кабельный склад в Ранчо',
        ua: 'Кабельний склад у Ранчо',
        en: 'Rancho cable yard',
        de: 'Kabellager Rancho',
        pl: 'Skladowisko kabli Rancho',
    },
    blackZancudoSite: {
        ru: 'Стройка у Форт-Занкудо',
        ua: 'Будівництво біля Форт-Занкудо',
        en: 'Fort Zancudo construction site',
        de: 'Baustelle bei Fort Zancudo',
        pl: 'Budowa przy Fort Zancudo',
    },
    blackChemDepot: {
        ru: 'Химический склад Восточного Лос-Сантоса',
        ua: 'Хімічний склад Східного Лос-Сантоса',
        en: 'East Los Santos chemical depot',
        de: 'Chemielager Ost-Los-Santos',
        pl: 'Sklad chemiczny we wschodnim Los Santos',
    },
    blackFrontCompany: {
        ru: 'Подставное предприятие в Гранд-Сенора',
        ua: 'Підставне підприємство в Гранд-Сенора',
        en: 'Grand Senora front company',
        de: 'Scheinfirma in Grand Senora',
        pl: 'Firma-przykrywka w Grand Senora',
    },
    blackShipBerth: {
        ru: 'Причал нелегального судна',
        ua: 'Причал нелегального судна',
        en: 'Contraband vessel berth',
        de: 'Liegeplatz des Schmuggelschiffs',
        pl: 'Nabrzeze nielegalnego statku',
    },
    blackWeaponsPlant: {
        ru: 'Подземный оружейный завод',
        ua: 'Підземний збройовий завод',
        en: 'Underground weapons plant',
        de: 'Unterirdische Waffenfabrik',
        pl: 'Podziemna fabryka broni',
    },
};
