export const cargoList = {
    // ------------------------------------------------------------------- legal
    cargoWarehouse: {
        name: {
            ru: 'Товар со склада',
            ua: 'Товар зі складу',
            en: 'Warehouse Freight',
            de: 'Lagerfracht',
            pl: 'Towar z magazynu',
        },
        description: {
            ru: 'Склад в Сайпресс-Флэтс забит под потолок, а почта в Вайнвуде ждёт посылки со вчерашнего дня. {{rolledGoal}} коробок: каждую берёте на руки, кладёте в багажник и везёте на отделение. Идите бригадой - вдвоём вы это до ночи не растащите.',
            ua: 'Склад у Сайпрес-Флетс забитий під стелю, а пошта у Вайнвуді чекає посилки з учора. {{rolledGoal}} коробок: кожну берете на руки, кладете в багажник і везете до відділення. Ідіть бригадою - удвох ви це до ночі не перетягаєте.',
            en: 'The Cypress Flats warehouse is packed to the roof and the Vinewood post office has been waiting since yesterday. {{rolledGoal}} boxes: every one goes in your hands, into a boot, and out to the counter. Go as a crew - two men will not shift this before dark.',
            de: 'Das Lagerhaus in Cypress Flats ist bis unters Dach voll und das Postamt in Vinewood wartet seit gestern. {{rolledGoal}} Kisten: jede in die Hände, in den Kofferraum und raus zum Schalter. Fahrt als Crew - zu zweit schafft ihr das bis zum Abend nicht.',
            pl: 'Magazyn w Cypress Flats jest zapchany po sufit, a poczta w Vinewood czeka od wczoraj. {{rolledGoal}} kartonów: każdy bierzesz na ręce, wkładasz do bagażnika i wieziesz na pocztę. Jedźcie ekipą - we dwóch nie wyniesiecie tego do nocy.',
        },
        objective: {
            ru: 'Перевезти {{rolledGoal}} коробок со склада на почту',
            ua: 'Перевезти {{rolledGoal}} коробок зі складу на пошту',
            en: 'Haul {{rolledGoal}} boxes from the warehouse to the post office',
            de: '{{rolledGoal}} Kisten vom Lager zum Postamt fahren',
            pl: 'Przewieźć {{rolledGoal}} kartonów z magazynu na pocztę',
        },
    },
    cargoTrain: {
        name: {
            ru: 'Товар с поезда',
            ua: 'Товар з поїзда',
            en: 'Rail Freight',
            de: 'Bahnfracht',
            pl: 'Towar z pociągu',
        },
        description: {
            ru: 'Состав встаёт на платформе у карьера пятнадцать минут в час, и корм снимают только пока он там. {{rolledGoal}} мешков на руках до багажника, дальше на ферму в Грейпсид. Ушёл поезд - ждите следующего, так что бригадой и без раскачки.',
            ua: 'Поїзд стоїть на платформі біля кар\'єру по п\'ятнадцять хвилин щогодини, і корм знімають лише поки він там. {{rolledGoal}} мішків на руках до багажника, далі на ферму в Грейпсід. Пішов поїзд - чекайте наступного, тож бригадою і без зволікань.',
            en: 'The consist stands at the quarry platform fifteen minutes in the hour, and the feed comes off only while it is there. {{rolledGoal}} sacks carried to a boot, then out to the Grapeseed farm. Miss the window and you wait for the next one, so bring the crew and do not dawdle.',
            de: 'Der Zug steht fünfzehn Minuten pro Stunde an der Rampe am Steinbruch, und das Futter kommt nur in dieser Zeit herunter. {{rolledGoal}} Säcke von Hand in den Kofferraum, dann raus zur Farm in Grapeseed. Fenster verpasst, nächste Stunde gewartet - also mit der Crew und ohne Trödeln.',
            pl: 'Skład stoi na rampie przy kamieniołomie piętnaście minut na godzinę i pasze zdejmuje się tylko w tym czasie. {{rolledGoal}} worków na rękach do bagażnika, potem na farmę w Grapeseed. Przegapisz okno - czekasz na kolejne, więc ekipą i bez ociągania.',
        },
        objective: {
            ru: 'Снять с поезда {{rolledGoal}} мешков комбикорма и отвезти на ферму Грейпсид',
            ua: 'Зняти з поїзда {{rolledGoal}} мішків комбікорму і відвезти на ферму Грейпсід',
            en: 'Take {{rolledGoal}} sacks of feed off the train and run them to the Grapeseed farm',
            de: '{{rolledGoal}} Säcke Futter vom Zug holen und zur Farm Grapeseed bringen',
            pl: 'Zdjąć z pociągu {{rolledGoal}} worków paszy i zawieźć na farmę Grapeseed',
        },
    },
    cargoPlane: {
        name: {
            ru: 'Товар с самолёта',
            ua: 'Товар з літака',
            en: 'Air Freight',
            de: 'Luftfracht',
            pl: 'Towar z samolotu',
        },
        description: {
            ru: 'Борт разгружают на грузовом перроне аэропорта, кейсы идут ко мне на склад в Сайпресс-Флэтс. {{rolledGoal}} кейсов: с площадки на руки, в багажник и до склада. Ни один не должен уехать не туда - за этот груз я отвечаю лично.',
            ua: 'Борт розвантажують на вантажному пероні аеропорту, кейси йдуть до мене на склад у Сайпрес-Флетс. {{rolledGoal}} кейсів: з майданчика на руки, в багажник і до складу. Жоден не повинен поїхати не туди - за цей вантаж я відповідаю особисто.',
            en: 'They are stripping the plane on the airport freight apron and the cases come to my warehouse in Cypress Flats. {{rolledGoal}} cases: off the pad into your hands, into a boot, out to the warehouse. Not one goes anywhere else - I answer for this load personally.',
            de: 'Die Maschine wird auf dem Frachtvorfeld entladen, die Koffer gehen in mein Lager in Cypress Flats. {{rolledGoal}} Koffer: vom Feld in die Hände, in den Kofferraum und ab ins Lager. Keiner fährt woandershin - für diese Ladung hafte ich persönlich.',
            pl: 'Samolot rozładowują na płycie cargo lotniska, a walizki jadą do mojego magazynu w Cypress Flats. {{rolledGoal}} walizek: z płyty na ręce, do bagażnika i do magazynu. Ani jedna nie pojedzie gdzie indziej - za ten ładunek odpowiadam osobiście.',
        },
        objective: {
            ru: 'Перевезти {{rolledGoal}} кейсов с борта на склад',
            ua: 'Перевезти {{rolledGoal}} кейсів з борту на склад',
            en: 'Move {{rolledGoal}} cases from the plane to the warehouse',
            de: '{{rolledGoal}} Koffer vom Flieger ins Lager fahren',
            pl: 'Przewieźć {{rolledGoal}} walizek z samolotu do magazynu',
        },
    },

    // ------------------------------------------------------------------- crime
    blackContainers: {
        name: {
            ru: 'Неизвестные контейнеры',
            ua: 'Невідомі контейнери',
            en: 'Unmarked Containers',
            de: 'Unbekannte Container',
            pl: 'Nieznane kontenery',
        },
        description: {
            ru: 'На Элизиан пришли контейнеры без единой бумажки - разбирайте ящик за ящиком и везите в цех на Рокфорд-Хиллз. {{rolledGoal}} ящиков, все пятеро на погрузке, и фарами у ворот не свети.',
            ua: 'На Елізіан прийшли контейнери без жодного папірця - розбирайте ящик за ящиком і везіть у цех на Рокфорд-Хіллз. {{rolledGoal}} ящиків, усі п\'ятеро на завантаженні, і фарами біля воріт не світи.',
            en: 'Containers landed on Elysian without a single sheet of paper - take them out crate by crate and run them to the shop in Rockford Hills. {{rolledGoal}} crates, all five of you on the loading, and keep your headlights off the gate.',
            de: 'Auf Elysian stehen Container ohne ein einziges Papier - Kiste für Kiste ausräumen und ab in die Werkstatt in Rockford Hills. {{rolledGoal}} Kisten, alle fünf beim Beladen, und leuchtet nicht mit den Scheinwerfern aufs Tor.',
            pl: 'Na Elysian przyszły kontenery bez jednej kartki - wynoście skrzynię po skrzyni i wieźcie do warsztatu na Rockford Hills. {{rolledGoal}} skrzyń, cała piątka przy załadunku i nie świeć reflektorami na bramę.',
        },
        objective: {
            ru: 'Вывезти {{rolledGoal}} ящиков из контейнеров в цех',
            ua: 'Вивезти {{rolledGoal}} ящиків із контейнерів у цех',
            en: 'Move {{rolledGoal}} crates from the containers to the shop',
            de: '{{rolledGoal}} Kisten aus den Containern in die Werkstatt bringen',
            pl: 'Wywieźć {{rolledGoal}} skrzyń z kontenerów do warsztatu',
        },
    },
    blackChem: {
        name: {
            ru: 'Незаконное предприятие',
            ua: 'Незаконне підприємство',
            en: 'Illicit Enterprise',
            de: 'Illegaler Betrieb',
            pl: 'Nielegalne przedsiębiorstwo',
        },
        description: {
            ru: 'Химия для лабы идёт через подставное предприятие в Гранд-Сенора. {{rolledGoal}} ящиков: не бить, крышки не открывать, в аварию не попадать. Одна течь - и везти будет уже некому.',
            ua: 'Хімія для лабораторії йде через підставне підприємство в Гранд-Сенора. {{rolledGoal}} ящиків: не бити, кришки не відкривати, в аварію не потрапляти. Один витік - і везти вже буде нікому.',
            en: 'The lab precursor moves through the front company in Grand Senora. {{rolledGoal}} crates: do not knock them, do not crack the lids, do not crash. One leak and there is nobody left to drive.',
            de: 'Der Laborstoff läuft über die Scheinfirma in Grand Senora. {{rolledGoal}} Kisten: nicht stoßen, Deckel nicht öffnen, keinen Unfall bauen. Ein Leck und es fährt keiner mehr.',
            pl: 'Chemia do labki idzie przez firmę-przykrywkę w Grand Senora. {{rolledGoal}} skrzyń: nie obijać, nie otwierać wiek, nie rozwalić się. Jeden wyciek i nie będzie komu wieźć.',
        },
        objective: {
            ru: 'Доставить {{rolledGoal}} ящиков химии на предприятие',
            ua: 'Доставити {{rolledGoal}} ящиків хімії на підприємство',
            en: 'Deliver {{rolledGoal}} crates of chemicals to the enterprise',
            de: '{{rolledGoal}} Kisten Chemie zum Betrieb liefern',
            pl: 'Dostarczyć {{rolledGoal}} skrzyń chemii do przedsiębiorstwa',
        },
    },
    blackShip: {
        name: {
            ru: 'Нелегальное судно',
            ua: 'Нелегальне судно',
            en: 'Contraband Vessel',
            de: 'Illegales Schiff',
            pl: 'Nielegalny statek',
        },
        description: {
            ru: 'С судна снимают взрывчатку, и она нужна на подземном заводе, а не в порту. {{rolledGoal}} ящиков, колонной, без резких торможений. Кто уронит ящик - хоронить будет нечего.',
            ua: 'Із судна знімають вибухівку, і вона потрібна на підземному заводі, а не в порту. {{rolledGoal}} ящиків, колоною, без різких гальмувань. Хто впустить ящик - не буде чого ховати.',
            en: 'They are pulling explosives off the hull, and they belong at the underground plant, not on the dock. {{rolledGoal}} crates, in convoy, no hard braking. Drop a crate and there will be nothing left to bury.',
            de: 'Vom Rumpf wird Sprengstoff geholt, und der gehört in die unterirdische Fabrik, nicht auf den Kai. {{rolledGoal}} Kisten, im Konvoi, kein hartes Bremsen. Wer eine Kiste fallen lässt, den muss keiner mehr begraben.',
            pl: 'Z kadłuba ściągają materiały wybuchowe i mają trafić do podziemnej fabryki, nie na nabrzeże. {{rolledGoal}} skrzyń, w kolumnie, bez ostrego hamowania. Kto upuści skrzynię, nie będzie czego chować.',
        },
        objective: {
            ru: 'Довезти {{rolledGoal}} ящиков со взрывчаткой на завод',
            ua: 'Довезти {{rolledGoal}} ящиків із вибухівкою на завод',
            en: 'Get {{rolledGoal}} crates of explosives to the plant',
            de: '{{rolledGoal}} Kisten Sprengstoff zur Fabrik bringen',
            pl: 'Dowieźć {{rolledGoal}} skrzyń materiałów wybuchowych do fabryki',
        },
    },
};

export const cargoBlips = {
    cargoCypressWarehouse: {
        ru: 'Склад в Сайпресс-Флэтс',
        ua: 'Склад у Сайпрес-Флетс',
        en: 'Cypress Flats warehouse',
        de: 'Lagerhaus Cypress Flats',
        pl: 'Magazyn Cypress Flats',
    },
    cargoVinewoodPost: {
        ru: 'Почтовое отделение Вайнвуда',
        ua: 'Поштове відділення Вайнвуду',
        en: 'Vinewood post office',
        de: 'Postamt Vinewood',
        pl: 'Poczta Vinewood',
    },
    cargoQuarrySiding: {
        ru: 'Грузовая платформа у карьера',
        ua: 'Вантажна платформа біля кар\'єру',
        en: 'Quarry freight platform',
        de: 'Frachtrampe am Steinbruch',
        pl: 'Rampa towarowa przy kamieniołomie',
    },
    cargoGrapeseedFarm: {
        ru: 'Ферма Грейпсид',
        ua: 'Ферма Грейпсід',
        en: 'Grapeseed farm',
        de: 'Farm Grapeseed',
        pl: 'Farma Grapeseed',
    },
    cargoAirportFreight: {
        ru: 'Грузовой терминал аэропорта',
        ua: 'Вантажний термінал аеропорту',
        en: 'Airport freight terminal',
        de: 'Frachtterminal des Flughafens',
        pl: 'Terminal cargo lotniska',
    },
    blackElysianContainers: {
        ru: 'Контейнеры на Элизиан-Айленд',
        ua: 'Контейнери на Елізіан-Айленд',
        en: 'Elysian Island containers',
        de: 'Container auf Elysian Island',
        pl: 'Kontenery na Elysian Island',
    },
    blackRockfordShop: {
        ru: 'Подпольный цех в Рокфорд-Хиллз',
        ua: 'Підпільний цех у Рокфорд-Хіллз',
        en: 'Rockford Hills underground shop',
        de: 'Untergrundwerkstatt Rockford Hills',
        pl: 'Podziemny warsztat Rockford Hills',
    },
    blackChemDepot: {
        ru: 'Химический склад Восточного Лос-Сантоса',
        ua: 'Хімічний склад Східного Лос-Сантоса',
        en: 'East Los Santos chemical depot',
        de: 'Chemielager Ost-Los-Santos',
        pl: 'Skład chemiczny we wschodnim Los Santos',
    },
    blackFrontCompany: {
        ru: 'Подставное предприятие в Гранд-Сенора',
        ua: 'Підставне підприємство в Гранд-Сенора',
        en: 'Grand Senora front company',
        de: 'Scheinfirma in Grand Senora',
        pl: 'Firma-przykrywka w Grand Senora',
    },
    blackShipBerth: {
        ru: 'Причал нелегального судна',
        ua: 'Причал нелегального судна',
        en: 'Contraband vessel berth',
        de: 'Liegeplatz des Schmuggelschiffs',
        pl: 'Nabrzeże nielegalnego statku',
    },
    blackWeaponsPlant: {
        ru: 'Подземный оружейный завод',
        ua: 'Підземний збройовий завод',
        en: 'Underground weapons plant',
        de: 'Unterirdische Waffenfabrik',
        pl: 'Podziemna fabryka broni',
    },
};
