export default {
    header: {
        ru: 'Дартс',
        ua: 'Дартс',
        en: 'Darts',
        de: 'Darts',
        pl: 'Rzutki',
        zh: '飞镖',
    },
    blip: {
        ru: 'Дартс',
        ua: 'Дартс',
        en: 'Darts',
        de: 'Darts',
        pl: 'Rzutki',
        zh: '飞镖',
    },
    interaction: {
        ru: 'Сыграть в дартс',
        ua: 'Зіграти в дартс',
        en: 'Play darts',
        de: 'Darts spielen',
        pl: 'Zagraj w rzutki',
        zh: '玩飞镖',
    },
    boardBusy: {
        ru: 'На этой доске уже идёт партия',
        ua: 'На цій дошці вже йде партія',
        en: 'A match is already being played on this board',
        de: 'An dieser Scheibe läuft bereits ein Spiel',
        pl: 'Na tej tarczy trwa już mecz',
        zh: '这个飞镖盘上已经有比赛在进行',
    },
    pickOpponent: {
        ru: 'Дартс - с кем играть',
        ua: 'Дартс - з ким грати',
        en: 'Darts - who to play',
        de: 'Darts - gegen wen spielen',
        pl: 'Rzutki - z kim grać',
        zh: '飞镖 - 选择对局',
    },
    soloOption: {
        ru: 'Одиночная игра - ${{price}}',
        ua: 'Одиночна гра - ${{price}}',
        en: 'Solo game - ${{price}}',
        de: 'Solospiel - ${{price}}',
        pl: 'Gra solo - ${{price}}',
        zh: '单人游戏 - ${{price}}',
    },
    notEnoughMoneySolo: {
        ru: 'Одиночная игра стоит ${{price}} наличными',
        ua: 'Одиночна гра коштує ${{price}} готівкою',
        en: 'A solo game costs ${{price}} in cash',
        de: 'Ein Solospiel kostet ${{price}} in bar',
        pl: 'Gra solo kosztuje ${{price}} w gotówce',
        zh: '单人游戏需要${{price}}现金',
    },
    tooFarSolo: {
        ru: 'Подойдите к доске',
        ua: 'Підійдіть до дошки',
        en: 'Walk up to the board',
        de: 'Geh zur Scheibe',
        pl: 'Podejdź do tarczy',
        zh: '请走到飞镖盘旁',
    },
    opponentUnavailable: {
        ru: 'Соперник больше не может играть',
        ua: 'Суперник більше не може грати',
        en: 'That opponent can no longer play',
        de: 'Dieser Gegner kann nicht mehr spielen',
        pl: 'Ten przeciwnik nie może już grać',
        zh: '该对手已无法参与比赛',
    },
    betTitle: {
        ru: 'Дартс - ставка',
        ua: 'Дартс - ставка',
        en: 'Darts - bet',
        de: 'Darts - Einsatz',
        pl: 'Rzutki - zakład',
        zh: '飞镖 - 下注',
    },
    betPlaceholder: {
        ru: 'Сумма от ${{min}} до ${{max}}',
        ua: 'Сума від ${{min}} до ${{max}}',
        en: 'Amount from ${{min}} to ${{max}}',
        de: 'Betrag von ${{min}} bis ${{max}}',
        pl: 'Kwota od ${{min}} do ${{max}}',
        zh: '金额从${{min}}到${{max}}',
    },
    offer: {
        ru: 'Предложить',
        ua: 'Запропонувати',
        en: 'Offer',
        de: 'Anbieten',
        pl: 'Zaproponuj',
        zh: '提议',
    },
    cancel: {
        ru: 'Отмена',
        ua: 'Скасувати',
        en: 'Cancel',
        de: 'Abbrechen',
        pl: 'Anuluj',
        zh: '取消',
    },
    invalidBet: {
        ru: 'Некорректная ставка (от ${{min}} до ${{max}})',
        ua: 'Некоректна ставка (від ${{min}} до ${{max}})',
        en: 'Invalid bet (from ${{min}} to ${{max}})',
        de: 'Ungültiger Einsatz (von ${{min}} bis ${{max}})',
        pl: 'Nieprawidłowy zakład (od ${{min}} do ${{max}})',
        zh: '无效的赌注（从${{min}}到${{max}}）',
    },
    notEnoughMoney: {
        ru: 'Недостаточно наличных для ставки',
        ua: 'Недостатньо готівки для ставки',
        en: 'Not enough cash for the bet',
        de: 'Nicht genug Bargeld für den Einsatz',
        pl: 'Za mało gotówki na zakład',
        zh: '现金不足以下注',
    },
    opponentNoMoney: {
        ru: 'У соперника недостаточно наличных',
        ua: 'У суперника недостатньо готівки',
        en: 'Your opponent does not have enough cash',
        de: 'Dein Gegner hat nicht genug Bargeld',
        pl: 'Przeciwnik nie ma wystarczająco gotówki',
        zh: '对手现金不足',
    },
    opponentBusy: {
        ru: 'Игрок уже рассматривает другое предложение',
        ua: 'Гравець уже розглядає іншу пропозицію',
        en: 'That player is already looking at another offer',
        de: 'Dieser Spieler prüft bereits ein anderes Angebot',
        pl: 'Ten gracz rozpatruje już inną ofertę',
        zh: '该玩家正在处理另一个邀请',
    },
    offerText: {
        ru: 'предлагает сыграть в дартс до 301 на ${{bet}}',
        ua: 'пропонує зіграти в дартс до 301 на ${{bet}}',
        en: 'challenges you to a game of 301 darts for ${{bet}}',
        de: 'fordert dich zu einer Partie Darts 301 um ${{bet}} heraus',
        pl: 'wyzywa cię na mecz w rzutki 301 o ${{bet}}',
        zh: '邀请你以${{bet}}进行一局301飞镖',
    },
    offerSent: {
        ru: 'Предложение отправлено',
        ua: 'Пропозицію надіслано',
        en: 'Challenge sent',
        de: 'Herausforderung gesendet',
        pl: 'Wyzwanie wysłane',
        zh: '邀请已发送',
    },
    tooFar: {
        ru: 'Оба игрока должны стоять у доски',
        ua: 'Обидва гравці мають стояти біля дошки',
        en: 'Both players have to be at the board',
        de: 'Beide Spieler müssen an der Scheibe stehen',
        pl: 'Obaj gracze muszą stać przy tarczy',
        zh: '双方玩家都必须在飞镖盘旁',
    },
    won: {
        ru: 'Вы выиграли партию и ${{amount}}',
        ua: 'Ви виграли партію та ${{amount}}',
        en: 'You won the match and ${{amount}}',
        de: 'Du hast das Spiel und ${{amount}} gewonnen',
        pl: 'Wygrałeś mecz i ${{amount}}',
        zh: '你赢得了比赛和${{amount}}',
    },
    wonForfeit: {
        ru: 'Соперник сдался, вы забираете ${{amount}}',
        ua: 'Суперник здався, ви забираєте ${{amount}}',
        en: 'Your opponent forfeited, you take ${{amount}}',
        de: 'Dein Gegner hat aufgegeben, du bekommst ${{amount}}',
        pl: 'Przeciwnik się poddał, zabierasz ${{amount}}',
        zh: '对手认输，你获得${{amount}}',
    },
    lost: {
        ru: 'Вы проиграли ставку ${{amount}}',
        ua: 'Ви програли ставку ${{amount}}',
        en: 'You lost your ${{amount}} bet',
        de: 'Du hast deinen Einsatz von ${{amount}} verloren',
        pl: 'Przegrałeś zakład ${{amount}}',
        zh: '你输掉了${{amount}}的赌注',
    },
    cef: {
        you: {
            ru: 'Вы',
            ua: 'Ви',
            en: 'You',
            de: 'Du',
            pl: 'Ty',
            zh: '你',
        },
        opponentThrowing: {
            ru: 'Бросает {{name}}',
            ua: 'Кидає {{name}}',
            en: '{{name}} is throwing',
            de: '{{name}} wirft',
            pl: 'Rzuca {{name}}',
            zh: '{{name}}正在投掷',
        },
        yourThrow: {
            ru: 'Ваш бросок',
            ua: 'Ваш кидок',
            en: 'Your throw',
            de: 'Du wirfst',
            pl: 'Twój rzut',
            zh: '轮到你投掷',
        },
        dartOf: {
            ru: 'Дротик {{n}} из 3',
            ua: 'Дротик {{n}} з 3',
            en: 'Dart {{n}} of 3',
            de: 'Pfeil {{n}} von 3',
            pl: 'Rzutka {{n}} z 3',
            zh: '第{{n}}支飞镖，共3支',
        },
        throwOffDetail: {
            ru: 'Кто ближе к центру, тот начинает партию',
            ua: 'Хто ближче до центру, той починає партію',
            en: 'Closest to the bull starts the match',
            de: 'Wer näher am Bull ist, beginnt das Spiel',
            pl: 'Kto bliżej środka, ten zaczyna mecz',
            zh: '离靶心更近的一方先开始',
        },
        goal: {
            ru: 'Сбейте счёт ровно до нуля. Последний дротик должен попасть в удвоение или яблочко',
            ua: 'Зведіть рахунок рівно до нуля. Останній дротик має влучити в подвоєння або яблучко',
            en: 'Bring your score down to exactly zero. The last dart has to land in a double or the bull',
            de: 'Bring deinen Stand auf genau null. Der letzte Pfeil muss ein Double oder den Bull treffen',
            pl: 'Zbij wynik dokładnie do zera. Ostatnia rzutka musi trafić w podwójne pole lub środek',
            zh: '把分数正好减到零。最后一镖必须命中双倍区或靶心',
        },
        checkout: {
            ru: 'Для победы: {{target}}',
            ua: 'Для перемоги: {{target}}',
            en: 'To win: {{target}}',
            de: 'Zum Sieg: {{target}}',
            pl: 'Do wygranej: {{target}}',
            zh: '获胜所需：{{target}}',
        },
        hintAim: {
            ru: 'Прицел',
            ua: 'Приціл',
            en: 'Aim',
            de: 'Zielen',
            pl: 'Celowanie',
            zh: '瞄准',
        },
        hintThrow: {
            ru: 'Бросок',
            ua: 'Кидок',
            en: 'Throw',
            de: 'Werfen',
            pl: 'Rzut',
            zh: '投掷',
        },
        hintSteady: {
            ru: 'Сосредоточиться',
            ua: 'Зосередитися',
            en: 'Focus',
            de: 'Konzentrieren',
            pl: 'Skup się',
            zh: '集中',
        },
        hintFast: {
            ru: 'Быстрее',
            ua: 'Швидше',
            en: 'Faster',
            de: 'Schneller',
            pl: 'Szybciej',
            zh: '加速',
        },
        hintQuit: {
            ru: 'Удерживайте, чтобы выйти',
            ua: 'Утримуйте, щоб вийти',
            en: 'Hold to leave',
            de: 'Halten zum Verlassen',
            pl: 'Przytrzymaj, aby wyjść',
            zh: '长按离开',
        },
        bull: {
            ru: 'Яблочко',
            ua: 'Яблучко',
            en: 'Bull',
            de: 'Bull',
            pl: 'Środek',
            zh: '靶心',
        },
        miss: {
            ru: 'Мимо',
            ua: 'Мимо',
            en: 'Miss',
            de: 'Daneben',
            pl: 'Pudło',
            zh: '脱靶',
        },
        bust: {
            ru: 'Перебор',
            ua: 'Перебір',
            en: 'Bust',
            de: 'Bust',
            pl: 'Fura',
            zh: '爆分',
        },
    },
    msg: {
        throwOffYou: {
            ru: 'Бросок за право начать: кто ближе к центру, тот бросает первым',
            ua: 'Кидок за право почати: хто ближче до центру, той кидає першим',
            en: 'Throw for the start: closest to the bull throws first',
            de: 'Wurf um den Anwurf: wer näher am Bull ist, wirft zuerst',
            pl: 'Rzut o rozpoczęcie: kto bliżej środka, ten zaczyna',
            zh: '争先投掷：离靶心更近的一方先投',
        },
        throwOffOpponent: {
            ru: '{{name}} бросает за право начать',
            ua: '{{name}} кидає за право почати',
            en: '{{name}} throws for the start',
            de: '{{name}} wirft um den Anwurf',
            pl: '{{name}} rzuca o rozpoczęcie',
            zh: '{{name}}正在争先投掷',
        },
        throwOffWon: {
            ru: 'Вы ближе к центру и начинаете партию',
            ua: 'Ви ближче до центру і починаєте партію',
            en: 'You are closest to the bull and throw first',
            de: 'Du bist näher am Bull und wirfst zuerst',
            pl: 'Jesteś bliżej środka i zaczynasz',
            zh: '你离靶心更近，由你先投',
        },
        throwOffLost: {
            ru: '{{name}} ближе к центру и начинает партию',
            ua: '{{name}} ближче до центру і починає партію',
            en: '{{name}} is closest to the bull and throws first',
            de: '{{name}} ist näher am Bull und wirft zuerst',
            pl: '{{name}} jest bliżej środka i zaczyna',
            zh: '{{name}}离靶心更近，由其先投',
        },
        yourTurn: {
            ru: 'Ваш ход. Осталось {{score}}',
            ua: 'Ваш хід. Залишилось {{score}}',
            en: 'Your throw. {{score}} remaining',
            de: 'Du bist dran. Noch {{score}}',
            pl: 'Twój rzut. Zostało {{score}}',
            zh: '轮到你。剩余{{score}}',
        },
        opponentTurn: {
            ru: 'Бросает {{name}}. У него осталось {{score}}',
            ua: 'Кидає {{name}}. Залишилось {{score}}',
            en: '{{name}} is throwing. {{score}} remaining',
            de: '{{name}} wirft. Noch {{score}}',
            pl: 'Rzuca {{name}}. Zostało {{score}}',
            zh: '{{name}}正在投掷。剩余{{score}}',
        },
        remain: {
            ru: 'Набрано за ход: {{scored}}. Осталось {{remaining}}',
            ua: 'Набрано за хід: {{scored}}. Залишилось {{remaining}}',
            en: 'Scored this turn: {{scored}}. {{remaining}} remaining',
            de: 'In diesem Zug: {{scored}}. Noch {{remaining}}',
            pl: 'W tej turze: {{scored}}. Zostało {{remaining}}',
            zh: '本轮得分：{{scored}}。剩余{{remaining}}',
        },
        bustUnderZero: {
            ru: 'Перебор! {{scored}} очков - это больше, чем осталось',
            ua: 'Перебір! {{scored}} очок - це більше, ніж залишилось',
            en: 'Bust! {{scored}} is more than was left',
            de: 'Bust! {{scored}} ist mehr als übrig war',
            pl: 'Fura! {{scored}} to więcej, niż zostało',
            zh: '爆分！{{scored}}超过了剩余分数',
        },
        bustNotDouble: {
            ru: 'Перебор! Закончить можно только удвоением или яблочком, а не {{value}}',
            ua: 'Перебір! Закінчити можна лише подвоєнням або яблучком, а не {{value}}',
            en: 'Bust! You have to finish on a double or the bull, not {{value}}',
            de: 'Bust! Du musst mit einem Double oder dem Bull beenden, nicht mit {{value}}',
            pl: 'Fura! Kończy się podwójnym polem lub środkiem, a nie {{value}}',
            zh: '爆分！必须以双倍区或靶心结束，而不是{{value}}',
        },
        bustOnePoint: {
            ru: 'Перебор! Одно очко удвоением не закрыть',
            ua: 'Перебір! Одне очко подвоєнням не закрити',
            en: 'Bust! One point can not be finished on a double',
            de: 'Bust! Ein Punkt lässt sich nicht mit einem Double beenden',
            pl: 'Fura! Jednego punktu nie da się zamknąć podwójnym polem',
            zh: '爆分！剩余一分无法用双倍区结束',
        },
        switchToOpponent: {
            ru: 'Ход переходит к {{name}}. У вас осталось {{remaining}}',
            ua: 'Хід переходить до {{name}}. У вас залишилось {{remaining}}',
            en: "{{name}}'s throw. You have {{remaining}} left",
            de: '{{name}} ist dran. Dir bleiben {{remaining}}',
            pl: 'Rzuca {{name}}. Zostało ci {{remaining}}',
            zh: '轮到{{name}}。你剩余{{remaining}}',
        },
        switchToYou: {
            ru: 'Ваш ход. У {{name}} осталось {{remaining}}',
            ua: 'Ваш хід. У {{name}} залишилось {{remaining}}',
            en: 'Your throw. {{name}} has {{remaining}} left',
            de: 'Du bist dran. {{name}} bleiben {{remaining}}',
            pl: 'Twój rzut. {{name}} zostało {{remaining}}',
            zh: '轮到你。{{name}}剩余{{remaining}}',
        },
        youCheckedOut: {
            ru: 'Вы закрыли партию!',
            ua: 'Ви закрили партію!',
            en: 'You checked out!',
            de: 'Du hast ausgecheckt!',
            pl: 'Zamknąłeś mecz!',
            zh: '你完成了收镖！',
        },
        opponentCheckedOut: {
            ru: '{{name}} закрыл партию',
            ua: '{{name}} закрив партію',
            en: '{{name}} checked out',
            de: '{{name}} hat ausgecheckt',
            pl: '{{name}} zamknął mecz',
            zh: '{{name}}完成了收镖',
        },
    },
    shard: {
        won: {
            ru: 'ПОБЕДА',
            ua: 'ПЕРЕМОГА',
            en: 'WINNER',
            de: 'GEWONNEN',
            pl: 'WYGRANA',
            zh: '胜利',
        },
        lost: {
            ru: 'ПОРАЖЕНИЕ',
            ua: 'ПОРАЗКА',
            en: 'LOSER',
            de: 'VERLOREN',
            pl: 'PRZEGRANA',
            zh: '失败',
        },
        pot: {
            ru: 'Банк: ${{amount}}',
            ua: 'Банк: ${{amount}}',
            en: 'Pot: ${{amount}}',
            de: 'Pot: ${{amount}}',
            pl: 'Pula: ${{amount}}',
            zh: '奖池：${{amount}}',
        },
        soloDone: {
            ru: 'ПАРТИЯ ЗАКРЫТА',
            ua: 'ПАРТІЮ ЗАКРИТО',
            en: 'CHECKED OUT',
            de: 'AUSGECHECKT',
            pl: 'MECZ ZAMKNIĘTY',
            zh: '收镖完成',
        },
        forfeit: {
            ru: 'Партия окончена досрочно',
            ua: 'Партію завершено достроково',
            en: 'The match ended early',
            de: 'Das Spiel wurde vorzeitig beendet',
            pl: 'Mecz zakończył się przedwcześnie',
            zh: '比赛提前结束',
        },
        bullseye: {
            ru: 'ЯБЛОЧКО',
            ua: 'ЯБЛУЧКО',
            en: 'BULLSEYE',
            de: 'BULLSEYE',
            pl: 'ŚRODEK',
            zh: '靶心',
        },
        oneEighty: {
            ru: '180!',
            ua: '180!',
            en: '180!',
            de: '180!',
            pl: '180!',
            zh: '180!',
        },
    },
};
