export default {
    header: {
        ru: 'Тренажерный зал',
        ua: 'Тренажерний зал',
        en: 'Gym',
        de: 'Fitnessstudio',
        pl: 'Siłownia',
    },
    occupied: {
        ru: 'Этот тренажер сейчас занят.',
        ua: 'Цей тренажер зараз зайнятий.',
        en: 'This machine is currently in use.',
        de: 'Dieses Gerät ist derzeit belegt.',
        pl: 'To urządzenie jest obecnie zajęte.',
    },
    cooldown: {
        ru: 'Подождите {{time}} перед следующей тренировкой.',
        ua: 'Зачекайте {{time}} перед наступним тренуванням.',
        en: 'Wait {{time}} before the next workout.',
        de: 'Warte {{time}} vor dem nächsten Training.',
        pl: 'Poczekaj {{time}} przed kolejnym treningiem.',
    },
    strengthProgress: {
        ru: 'Сила {{prev}} -> {{gain}}',
        ua: 'Сила {{prev}} -> {{gain}}',
        en: 'Strength {{prev}} -> {{gain}}',
        de: 'Kraft {{prev}} -> {{gain}}',
        pl: 'Siła {{prev}} -> {{gain}}',
    },
    minigame: {
        subtitle: {
            ru: 'Нажми SPACE в зелёной зоне',
            ua: 'Натисни SPACE у зеленій зоні',
            en: 'Press SPACE in the green zone',
            de: 'Drücke LEERTASTE in der grünen Zone',
            pl: 'Naciśnij SPACJĘ w zielonej strefie',
        },
        hits: {
            ru: 'Попаданий',
            ua: 'Влучань',
            en: 'Hits',
            de: 'Treffer',
            pl: 'Trafienia',
        },
        perfect: {
            ru: 'Идеально',
            ua: 'Ідеально',
            en: 'Perfect',
            de: 'Perfekt',
            pl: 'Idealnie',
        },
        good: {
            ru: 'Хорошо',
            ua: 'Добре',
            en: 'Good',
            de: 'Gut',
            pl: 'Dobrze',
        },
        miss: {
            ru: 'Мимо',
            ua: 'Промах',
            en: 'Miss',
            de: 'Daneben',
            pl: 'Pudło',
        },
        hintHit: {
            ru: 'Нажать',
            ua: 'Натиснути',
            en: 'Press',
            de: 'Drücken',
            pl: 'Naciśnij',
        },
        hintExit: {
            ru: 'Выйти',
            ua: 'Вийти',
            en: 'Exit',
            de: 'Beenden',
            pl: 'Wyjdź',
        },
    },
};
