export default {
    captureZones: {
        ru: 'Захватите {{count}} территорий',
        ua: 'Захопіть {{count}} територій',
        en: 'Capture {{count}} zones',
        de: 'Erobere {{count}} Gebiete',
        pl: 'Przejmij {{count}} terytoriów',
    },
    pariticpateAirdrops: {
        ru: 'Поучавствуйте в {{count}} аирдропах',
        ua: 'Візьміть участь у {{count}} аірдропах',
        en: 'Participate in {{count}} airdrops',
        de: 'Nehme an {{count}} Airdrops teil',
        pl: 'Weź udział w {{count}} airdropach',
    },
    robShops: {
        ru: 'Ограбьте {{count}} бизнесов',
        ua: 'Пограбуйте {{count}} бізнесів',
        en: 'Rob {{count}} businesses',
        de: 'Überfalle {{count}} Geschäfte',
        pl: 'Okradnij {{count}} biznesów',
    },
    carjack: {
        ru: 'Сделайте {{count}} автоугонок',
        ua: 'Здійсніть {{count}} викрадень авто',
        en: 'Perform {{count}} carjackings',
        de: 'Begehe {{count}} Autodiebstähle',
        pl: 'Dokonaj {{count}} kradzieży samochodów',
    },
    deliverStashes: {
        ru: 'Развезти {{count}} закладок',
        ua: 'Розвезти {{count}} закладок',
        en: 'Deliver {{count}} stashes',
        de: '{{count}} Verstecke ausliefern',
        pl: 'Rozwieź {{count}} skrytek',
    },
    growGreen: {
        ru: 'Вырастить {{count}} кустов Green на ферме',
        ua: 'Виростити {{count}} кущів Green на фермі',
        en: 'Grow {{count}} Green bushes on the farm',
        de: '{{count}} Weed-Pflanzen auf der Farm anbauen',
        pl: 'Wyhoduj {{count}} krzaków Green na farmie',
    },

    // GOV!!
    arrestPeople: {
        'ru': 'Арестовать {{count}} людей',
        'ua': 'Арештувати {{count}} людей',
        'en': 'Arrest {{count}} people',
        'de': '{{count}} Personen verhaften',
        'pl': 'Aresztuj {{count}} osób',
    },
    friskPeople: {
        'ru': 'Обыскать {{count}} людей на наличие нелегальных предметов',
        'ua': 'Оглянути {{count}} людей на наявність нелегальних предметів',
        'en': 'Frisk {{count}} people for illegal items',
        'de': '{{count}} Personen auf illegale Gegenstände durchsuchen',
        'pl': 'Przeszukaj {{count}} osób pod kątem nielegalnych przedmiotów',
    },
    setSpeedRadar: {
        'ru': 'Установить {{count}} скоростных радаров',
        'ua': 'Встановити {{count}} радарів швидкості',
        'en': 'Set up {{count}} speed radars',
        'de': '{{count}} Radargeräte aufstellen',
        'pl': 'Ustaw {{count}} radarów prędkości',
    },
    imposeFine: {
        'ru': 'Выдать {{count}} штрафов за нарушения разным людям',
        'ua': 'Виписати {{count}} штрафів за порушення різним людям',
        'en': 'Give out {{count}} tickets for violations to different people',
        'de': '{{count}} Strafzettel an verschiedene Personen ausstellen',
        'pl': 'Wystaw {{count}} mandatów za wykroczenia różnym osobom',
    },
    giveEvacuationOrder: {
        'ru': 'Выдать {{count}} ордеров на эвакуацию авто',
        'ua': 'Виписати {{count}} ордерів на евакуацію авто',
        'en': 'Issue {{count}} vehicle evacuation orders',
        'de': '{{count}} Abschleppanweisungen erteilen',
        'pl': 'Wydaj {{count}} nakazów ewakuacji pojazdów',
    },
    //
    'reanimatePlayer': {
        'ru': 'Реанимировать {{count}} людей',
        'ua': 'Реанімувати {{count}} людей',
        'en': 'Revive {{count}} people',
        'de': '{{count}} Leute wiederbeleben',
        'pl': 'Reanimuj {{count}} osób',
    },
    'sellPills': {
        'ru': 'Продать {{count}} любых таблеток людям',
        'ua': 'Продати {{count}} будь-яких пігулок людям',
        'en': 'Sell {{count}} any pills to people',
        'de': '{{count}} beliebige Pillen an Leute verkaufen',
        'pl': 'Sprzedaj {{count}} dowolnych tabletek ludziom',
    },
    'takeBlood': {
        'ru': 'Взять кровь у {{count}} людей',
        'ua': 'Взяти кров у {{count}} людей',
        'en': 'Take blood from {{count}} people',
        'de': 'Blut von {{count}} Leuten abnehmen',
        'pl': 'Pobierz krew od {{count}} osób',
    },
    'checkPlayerHealth': {
        'ru': 'Проверить здоровье у {{count}} людей',
        'ua': 'Перевірити здоров\'я у {{count}} людей',
        'en': 'Check health of {{count}} people',
        'de': 'Gesundheit von {{count}} Leuten überprüfen',
        'pl': 'Sprawdź zdrowie u {{count}} osób',
    },
    healPlayerDiseases: {
        'ru': 'Вылечить болезни у {{count}} людей',
        'ua': 'Вилікувати хвороби у {{count}} людей',
        'en': 'Heal diseases in {{count}} people',
        'de': 'Heile Krankheiten bei {{count}} Personen',
        'pl': 'Wylecz choroby u {{count}} osób',
    },
    'sellLicense': {
        'ru': 'Продать любую лицензию {{count}} людям',
        'ua': 'Продати будь-яку ліцензію {{count}} людям',
        'en': 'Sell any license to {{count}} people',
        'de': 'Irgendeine Lizenz an {{count}} Leute verkaufen',
        'pl': 'Sprzedaj dowolną licencję {{count}} osobom',
    },
    acceptPrismDispatches: {
        'ru': 'Принять {{count}} вызовов в PRISM',
        'ua': 'Прийняти {{count}} викликів у PRISM',
        'en': 'Accept {{count}} dispatches in PRISM',
        'de': '{{count}} Einsätze in PRISM annehmen',
        'pl': 'Przyjmij {{count}} zgłoszeń w PRISM',
    },
    "publishAd": {
        "ru": "Смодерируйте и опубликуйте {{count}} реклам",
        "ua": "Змодеруйте та опублікуйте {{count}} реклам",
        "en": "Review and publish {{count}} ads",
        "de": "Moderiere und veröffentliche {{count}} Werbeanzeigen",
        "pl": "Zmoderuj i opublikuj {{count}} reklam"
    },
    "goLive": {
        "ru": "Выйдите в прямой эфир {{count}} раза за этот день",
        "ua": "Вийди в прямий ефір {{count}} разів за цей день",
        "en": "Go live {{count}} times today",
        "de": "Geh heute {{count}} Mal live",
        "pl": "Wejdź na żywo {{count}} razy dziś"
    },
};
