export default {
    notFaction: {
        ru: 'Этот дрон доступен только сотрудникам LSPD',
        ua: 'Цей дрон доступний лише співробітникам LSPD',
        en: 'This drone is available to LSPD officers only',
        de: 'Diese Drohne ist nur für LSPD-Beamte verfügbar',
        pl: 'Ten dron jest dostępny tylko dla funkcjonariuszy LSPD',
    },
    notOnDuty: {
        ru: 'Нужно быть на службе чтобы запустить этот дрон',
        ua: 'Потрібно бути на службі, щоб запустити цей дрон',
        en: 'You must be on duty to launch this drone',
        de: 'Du musst im Dienst sein, um diese Drohne zu starten',
        pl: 'Musisz być na służbie, aby uruchomić tego drona',
    },
    cooldown: {
        ru: 'Подожди немного перед следующим запуском',
        ua: 'Зачекай трохи перед наступним запуском',
        en: 'Wait a bit before launching again',
        de: 'Warte einen Moment vor dem nächsten Start',
        pl: 'Poczekaj chwilę przed kolejnym uruchomieniem',
    },
    batteryDead: {
        ru: 'Батарея дрона разряжена',
        ua: 'Батарея дрона розряджена',
        en: 'Drone battery is dead',
        de: 'Drohnenakku ist leer',
        pl: 'Bateria drona jest rozładowana',
    },
    cantDoWhileFlying: {
        ru: 'Нельзя делать это пока вы управляете дроном',
        ua: 'Не можна робити це, поки ви керуєте дроном',
        en: "You can't do this while piloting a drone",
        de: 'Das kannst du nicht tun, während du eine Drohne steuerst',
        pl: 'Nie możesz tego robić podczas sterowania dronem',
    },
    rthEngaged: {
        ru: 'Автовозврат активирован',
        ua: 'Автоповернення активовано',
        en: 'Auto-return engaged',
        de: 'Auto-Rückkehr aktiv',
        pl: 'Auto-powrót aktywny',
    },
    rthArrived: {
        ru: 'Дрон вернулся',
        ua: 'Дрон повернувся',
        en: 'Drone returned home',
        de: 'Drohne ist beim Piloten',
        pl: 'Dron wrócił',
    },
    rthDisengaged: {
        ru: 'Автовозврат отменён',
        ua: 'Автоповернення скасовано',
        en: 'Auto-return cancelled',
        de: 'Auto-Rückkehr abgebrochen',
        pl: 'Auto-powrót anulowany',
    },
    controlsHint: {
        ru: 'WASD - наклон, SPACE/CTRL - газ, мышь - камера, V - режим, BACKSPACE - посадка, N - тепловизор',
        ua: 'WASD - нахил, SPACE/CTRL - газ, миша - камера, V - режим, BACKSPACE - посадка, N - тепловізор',
        en: 'WASD - tilt, SPACE/CTRL - throttle, mouse - camera, V - mode, BACKSPACE - land, N - thermal',
        de: 'WASD - Neigung, SPACE/CTRL - Schub, Maus - Kamera, V - Modus, BACKSPACE - landen, N - Wärmebild',
        pl: 'WASD - przechył, SPACE/CTRL - ciąg, mysz - kamera, V - tryb, BACKSPACE - lądowanie, N - termowizja',
    },
    outOfRange: {
        ru: 'Сигнал потерян, дрон отключился',
        ua: 'Сигнал втрачено, дрон відключився',
        en: 'Signal lost, drone disconnected',
        de: 'Signal verloren, Drohne getrennt',
        pl: 'Sygnał utracony, dron rozłączony',
    },
    brokenByDamage: {
        ru: 'Дрон повреждён и вышел из строя',
        ua: 'Дрон пошкоджено, він вийшов з ладу',
        en: 'Drone is damaged and disabled',
        de: 'Drohne ist beschädigt und außer Betrieb',
        pl: 'Dron jest uszkodzony i wyłączony',
    },
    brokenByWater: {
        ru: 'Дрон промок и перестал работать',
        ua: 'Дрон промок і перестав працювати',
        en: 'Drone got wet and stopped working',
        de: 'Drohne ist nass geworden und funktioniert nicht mehr',
        pl: 'Dron zamókł i przestał działać',
    },
    view: {
        fpv: {
            ru: 'Камера: от первого лица',
            ua: 'Камера: від першої особи',
            en: 'Camera: first-person',
            de: 'Kamera: Egoperspektive',
            pl: 'Kamera: pierwsza osoba',
        },
        tps: {
            ru: 'Камера: от третьего лица',
            ua: 'Камера: від третьої особи',
            en: 'Camera: third-person',
            de: 'Kamera: Verfolger-Perspektive',
            pl: 'Kamera: trzecia osoba',
        },
    },
    vision: {
        normal: {
            ru: 'Зрение: обычное',
            ua: 'Зір: звичайний',
            en: 'Vision: normal',
            de: 'Sicht: normal',
            pl: 'Wzrok: zwykły',
        },
        nightVision: {
            ru: 'Зрение: ночное',
            ua: 'Зір: нічне',
            en: 'Vision: night',
            de: 'Sicht: Nachtsicht',
            pl: 'Wzrok: nocny',
        },
        thermal: {
            ru: 'Зрение: тепловизор',
            ua: 'Зір: тепловізор',
            en: 'Vision: thermal',
            de: 'Sicht: Wärmebild',
            pl: 'Wzrok: termiczny',
        },
    },
    hud: {
        units: {
            meters: {
                ru: 'м',
                ua: 'м',
                en: 'm',
                de: 'm',
                pl: 'm',
            },
            kmh: {
                ru: 'км/ч',
                ua: 'км/год',
                en: 'km/h',
                de: 'km/h',
                pl: 'km/h',
            },
            mps: {
                ru: 'м/с',
                ua: 'м/с',
                en: 'm/s',
                de: 'm/s',
                pl: 'm/s',
            },
        },
        controls: {
            movement: {
                ru: 'движение',
                ua: 'рух',
                en: 'movement',
                de: 'Bewegung',
                pl: 'ruch',
            },
            up: {
                ru: 'вверх',
                ua: 'вгору',
                en: 'up',
                de: 'hoch',
                pl: 'w górę',
            },
            down: {
                ru: 'вниз',
                ua: 'вниз',
                en: 'down',
                de: 'runter',
                pl: 'w dół',
            },
            boost: {
                ru: 'ускорение',
                ua: 'прискорення',
                en: 'boost',
                de: 'Boost',
                pl: 'przyspieszenie',
            },
            view: {
                ru: 'вид',
                ua: 'вид',
                en: 'view',
                de: 'Ansicht',
                pl: 'widok',
            },
            mode: {
                ru: 'режим',
                ua: 'режим',
                en: 'mode',
                de: 'Modus',
                pl: 'tryb',
            },
            vision: {
                ru: 'зрение',
                ua: 'зір',
                en: 'vision',
                de: 'Sicht',
                pl: 'wzrok',
            },
            tilt: {
                ru: 'наклон',
                ua: 'нахил',
                en: 'tilt',
                de: 'Neigung',
                pl: 'nachylenie',
            },
            roll: {
                ru: 'крен',
                ua: 'крен',
                en: 'roll',
                de: 'Rolle',
                pl: 'przechył',
            },
            tiltReset: {
                ru: 'выровнять',
                ua: 'вирівняти',
                en: 'level',
                de: 'ausrichten',
                pl: 'wypoziomuj',
            },
            returnHome: {
                ru: 'RTH',
                ua: 'RTH',
                en: 'RTH',
                de: 'RTH',
                pl: 'RTH',
            },
            disconnect: {
                ru: 'отключить',
                ua: 'відключити',
                en: 'disconnect',
                de: 'trennen',
                pl: 'rozłącz',
            },
        },
    },
    mode: {
        stable: {
            ru: 'Режим: стабильный',
            ua: 'Режим: стабільний',
            en: 'Mode: stable',
            de: 'Modus: stabil',
            pl: 'Tryb: stabilny',
        },
        sport: {
            ru: 'Режим: спортивный',
            ua: 'Режим: спортивний',
            en: 'Mode: sport',
            de: 'Modus: Sport',
            pl: 'Tryb: sportowy',
        },
        police: {
            ru: 'Режим: полицейский',
            ua: 'Режим: поліцейський',
            en: 'Mode: police',
            de: 'Modus: Polizei',
            pl: 'Tryb: policyjny',
        },
    },
};
