export const server = {
    notifyHeader: {
        ru: 'Грузоперевозчик',
        ua: 'Вантажоперевізник',
        en: 'Trucker',
        de: 'Frachtführer',
        pl: 'Przewoźnik towarowy',
    },
    labels: {
        loaded: {
            ru: 'Товара загружено',
            ua: 'Товара завантажено',
            en: 'Items loaded',
            de: 'Artikel geladen',
            pl: 'Załadowane przedmioty',
        },
        unloaded: {
            ru: 'Товара разгружено',
            ua: 'Товар розгружено',
            en: 'Items unloaded',
            de: 'Artikel entladen',
            pl: 'Rozładowane przedmioty',
        },
    },
    gotJob: {
        ru: 'Вы успешно устроились на работу, отправляйтесь на точку загрузки',
        ua: 'Ви успішно працевлаштувались, вирушайте на точку завантаження',
        en: 'You have successfully got a job, head to the loading point',
        de: 'Sie haben erfolgreich einen Job gefunden, begeben Sie sich zur Ladezone',
        pl: 'Pomyślnie znalazłeś pracę, udaj się do punktu załadunku',
    },
    leaveJob: {
        ru: 'Вы успешно уволились с работы',
        ua: 'Ви успішно звільнилися з роботи',
        en: 'You have successfully left the job',
        de: 'Sie haben erfolgreich den Job verlassen',
        pl: 'Pomyślnie zrezygnowałeś z pracy',
    },
    startLoading: {
        ru: 'Начинайте загружать товар в машину',
        ua: 'Починайте завантажувати товар у машину',
        en: 'Start loading the goods into the truck',
        de: 'Beginnen Sie mit dem Beladen der Waren in den LKW',
        pl: 'Zacznij załadunek towaru do ciężarówki',
    },
    startUnloading: {
        ru: 'Начинайте разгружать товар из машины',
        ua: 'Починайте розгружати товар з машини',
        en: 'Start unloading the goods from the truck',
        de: 'Beginnen Sie mit dem Entladen der Waren aus dem LKW',
        pl: 'Zacznij rozładunek towaru z ciężarówki',
    },
    firstTakeGoodsFromStorage: {
        ru: 'Сначала возьмите товар со склада',
        ua: 'Спочатку візьміть товар зі складу',
        en: 'First take the goods from the warehouse',
        de: 'Nehmen Sie zuerst die Waren aus dem Lager',
        pl: 'Najpierw weź towar ze składu',
    },
    youLoadedBoxAndEarned: {
        ru: 'Вы загрузили ящик и заработали {{salary}}$',
        ua: 'Ви завантажили ящик і заробили {{salary}}$',
        en: 'You loaded a box and earned {{salary}}$',
        de: 'Sie haben eine Kiste geladen und {{salary}}$ verdient',
        pl: 'Załadowałeś skrzynię i zarobiłeś {{salary}}$',
    },
    youSuccessfullyUnloadedGoods: {
        ru: 'Вы успешно разгрузили весь товар из машины и заработали {{salary}}. Отправляйтесь на следующую точку загрузки.',
        ua: 'Ви успішно розгрузили весь товар з машини і заробили {{salary}}. Вирушайте на наступну точку завантаження.',
        en: 'You have successfully unloaded all the goods from the truck and earned {{salary}}. Head to the next loading point.',
        de: 'Sie haben erfolgreich alle Waren aus dem LKW entladen und {{salary}} verdient. Begeben Sie sich zur nächsten Ladezone.',
        pl: 'Pomyślnie rozładowałeś cały towar z ciężarówki i zarobiłeś {{salary}}. Udaj się do następnego punktu załadunku.',
    },
    youUnloadedBoxAndEarned: {
        ru: 'Вы разгрузили ящик и заработали {{salary}}$',
        ua: 'Ви розгрузили ящик і заробили {{salary}}$',
        en: 'You unloaded a box and earned {{salary}}$',
        de: 'Sie haben eine Kiste entladen und {{salary}}$ verdient',
        pl: 'Rozładowałeś skrzynię i zarobiłeś {{salary}}$',
    },
    youSuccessfullyLoadedGoods: {
        ru: 'Вы успешно загрузили весь товар в машину. Отправляйтесь на точку разгрузки.',
        ua: 'Ви успішно завантажили весь товар у машину. Вирушайте на точку розгрузки.',
        en: 'You have successfully loaded all the goods into the truck. Head to the unloading point.',
        de: 'Sie haben erfolgreich alle Waren in den LKW geladen. Begeben Sie sich zur Entladezone.',
        pl: 'Pomyślnie załadowałeś cały towar do ciężarówki. Udaj się do punktu rozładowczego.',
    },
    yourVehicleDestroyed: {
        ru: 'Ваш рабочий транспорт уничтожен, вы уволены',
        ua: 'Ваш робочий транспорт знищено, вас звільнено',
        en: 'Your work vehicle has been destroyed, you have been fired',
        de: 'Ihr Arbeitsfahrzeug wurde zerstört, Sie wurden entlassen',
        pl: 'Twój pojazd służbowy został zniszczony, zostałeś zwolniony',
    },
    returnToLoadingPoint: {
        ru: 'Возвращайтесь на точку загрузки',
        ua: 'Повертайтеся на точку завантаження',
        en: 'Return to the loading point',
        de: 'Zurück zum Ladebereich',
        pl: 'Wróć do punktu załadunku',
    },
    returnToUnloadingPoint: {
        ru: 'Возвращайтесь на точку разгрузки',
        ua: 'Повертайтесь на точку розгрузки',
        en: 'Return to the unloading point',
        de: 'Zurück zum Entladebereich',
        pl: 'Wróć do punktu rozładunku',
    },
    youCantEnterVehicle: {
        ru: 'Это не ваш рабочий транспорт',
        ua: 'Це не ваш робочий транспорт',
        en: 'This is not your work vehicle',
        de: 'Dies ist nicht Ihr Arbeitsfahrzeug',
        pl: 'To nie jest twój pojazd służbowy',
    },
    youHaveReturnedToVehicle: {
        ru: 'Вы вернулись в рабочий транспорт',
        ua: 'Ви повернулися у робочий транспорт',
        en: 'You have returned to the work vehicle',
        de: 'Sie sind zum Arbeitsfahrzeug zurückgekehrt',
        pl: 'Wróciłeś do pojazdu służbowego',
    },
    youHaveMinuteToReturnToVehicle: {
        ru: 'У вас есть 1 минута чтобы вернуться в рабочий транспорт, иначе вы будете уволены',
        ua: 'У вас є 1 хвилина, щоб повернутися у робочий транспорт, інакше вас звільнять',
        en: 'You have 1 minute to return to the work vehicle, otherwise you will be fired',
        de: 'Sie haben 1 Minute, um zum Arbeitsfahrzeug zurückzukehren, andernfalls werden Sie entlassen',
        pl: 'Masz 1 minutę na powrót do pojazdu służbowego, w przeciwnym razie zostaniesz zwolniony',
    },
    youBeenFired: {
        ru: 'Вы уволены, так как покинули свой рабочий транспорт на продолжительное время',
        ua: 'Ви звільнені, оскільки покинули свій робочий транспорт на тривалий час',
        en: 'You have been fired for leaving your work vehicle unattended for an extended period',
        de: 'Sie wurden entlassen, weil Sie Ihr Arbeitsfahrzeug längere Zeit unbeaufsichtigt gelassen haben',
        pl: 'Zostałeś zwolniony za zostawienie pojazdu służbowego bez opieki przez dłuższy czas',
    },
    yourJobVehicle: {
        ru: 'Ваша рабочая машина',
        ua: 'Ваша робоча машина',
        en: 'Your job vehicle',
        de: 'Ihr Arbeitsfahrzeug',
        pl: 'Twój pojazd służbowy',
    },
    loadingPoint: {
        ru: 'Точка загрузки',
        ua: 'Точка завантаження',
        en: 'Loading point',
        de: 'Ladezone',
        pl: 'Punkt załadunku',
    },
    unloadingPoint: {
        ru: 'Точка разгрузки',
        ua: 'Точка розгрузки',
        en: 'Unloading point',
        de: 'Entladezone',
        pl: 'Punkt rozładunku',
    },
};
