export default {
    modal: {
        titleCayoPerico: {
            ru: 'Вы хотите отправиться на Кайо Перико?',
            ua: 'Ви хочете вирушити на Кайо Перико?',
            en: 'Do you want to go to Cayo Perico?',
            de: 'Möchten Sie nach Cayo Perico gehen?',
            pl: 'Czy chcesz pojechać na Cayo Perico?',
            zh:'你想去佩里科岛吗?',
        },
        titleLS: {
            ru: 'Вы хотите вернуться на Лос Сантос?',
            ua: 'Ви хочете повернутися до Лос-Сантоса?',
            en: 'Do you want to return to Los Santos?',
            de: 'Möchten Sie nach Los Santos zurückkehren?',
            pl: 'Czy chcesz wrócić do Los Santos?',
            zh:'你想回自由城吗?',
        },
        message: {
            ru: 'Цена отправки будет ${{price}}, вы готовы?',
            ua: 'Ціна відправлення буде ${{price}}, ви готові?',
            en: 'The cost of the trip will be ${{price}}, are you ready?',
            de: 'Die Kosten für die Reise betragen ${{price}}, sind Sie bereit?',
            pl: 'Koszt podróży wyniesie ${{price}}, jesteś gotowy?',
            zh:'这次旅行的费用是${{price}}，你准备好了吗?',
        },
        confirmButton: {
            ru: 'Да',
            ua: 'Так',
            en: 'Yes',
            de: 'Ja',
            pl: 'Tak',
            zh:'是的',
        },
        cancelButton: {
            ru: 'Нет',
            ua: 'Ні',
            en: 'No',
            de: 'Nein',
            pl: 'Nie',
            zh:'不',
        },
    },
    labelToCayoPerico: {
        ru: 'Отправка на Кайо Перико',
        ua: 'Відправлення на Кайо Перико',
        en: 'Trip to Cayo Perico',
        de: 'Reise nach Cayo Perico',
        pl: 'Podróż na Cayo Perico',
        zh:'前往佩里克岛',
    },
    labelToLS: {
        ru: 'Возвращение в Лос Сантос',
        ua: 'Повернення до Лос-Сантоса',
        en: 'Return to Los Santos',
        de: 'Rückkehr nach Los Santos',
        pl: 'Powrót do Los Santos',
        zh:'返回自由城',
    },
};
