export default {
    name: {
        ru: 'Подбросить попутчика',
        ua: 'Підвезти попутника',
        en: 'Give the hitchhiker a lift',
        de: 'Den Anhalter mitnehmen',
        pl: 'Podwieź autostopowicza',
    },
    dialog: {
        offer: {
            ru: 'Эй, притормози! Меня высадили посреди дороги, а мне ещё {{distance}} км пилить. Подбросишь? В долгу не останусь.',
            ua: 'Гей, пригальмуй! Мене висадили посеред дороги, а мені ще {{distance}} км їхати. Підвезеш? Я віддячу.',
            en: 'Hey, hold up! I got dropped off in the middle of nowhere and I still have {{distance}} km to go. Give me a lift? I will make it worth your while.',
            de: 'Hey, halt mal an! Man hat mich mitten auf der Strecke rausgelassen und ich habe noch {{distance}} km vor mir. Nimmst du mich mit? Es lohnt sich für dich.',
            pl: 'Hej, zatrzymaj się! Wysadzili mnie w polu, a mam jeszcze {{distance}} km do przejechania. Podwieziesz? Odwdzięczę się.',
        },
        detail: {
            ru: 'Да ничего особенного. Поспорил с водителем о музыке, и вот стою тут с большим пальцем. Дорогу знаю, покажу где сворачивать.',
            ua: 'Та нічого особливого. Посварився з водієм через музику, і ось стою тут з великим пальцем. Дорогу знаю, покажу де звертати.',
            en: 'Nothing dramatic. Argued with the driver about music and here I am with my thumb out. I know the road, I will tell you where to turn.',
            de: 'Nichts Dramatisches. Streit mit dem Fahrer wegen der Musik, und jetzt stehe ich hier mit ausgestrecktem Daumen. Ich kenne die Strecke und sage dir, wo es abgeht.',
            pl: 'Nic wielkiego. Pokłóciłem się z kierowcą o muzykę i stoję tu z kciukiem. Znam drogę, powiem gdzie skręcić.',
        },
        progress: {
            ru: 'Я никуда не денусь. Подгоняй тачку, место рядом с тобой сойдёт.',
            ua: 'Я нікуди не подінусь. Підганяй тачку, місце поруч з тобою підійде.',
            en: 'I am not going anywhere. Bring the car around, the seat next to you will do.',
            de: 'Ich bleibe hier. Fahr den Wagen vor, der Sitz neben dir reicht.',
            pl: 'Nigdzie się nie ruszam. Podjedź autem, miejsce obok ciebie wystarczy.',
        },
        noCar: {
            ru: 'Пешком мы с тобой далеко не уйдём. Подгони машину - и по рукам.',
            ua: 'Пішки ми з тобою далеко не зайдемо. Підганяй машину - і по руках.',
            en: 'On foot we are not getting far. Bring a car around and we have a deal.',
            de: 'Zu Fuß kommen wir beide nicht weit. Fahr einen Wagen vor, dann sind wir im Geschäft.',
            pl: 'Na piechotę daleko nie zajdziemy. Podjedź autem i mamy umowę.',
        },
        noSeat: {
            ru: 'Я бы рад, но у тебя все места заняты. Освободи одно - и поехали.',
            ua: 'Я б радий, але в тебе всі місця зайняті. Звільни одне - і поїхали.',
            en: 'I would love to, but every seat of yours is taken. Free one up and we go.',
            de: 'Gern, aber bei dir ist jeder Platz belegt. Mach einen frei, dann fahren wir.',
            pl: 'Chętnie, ale masz wszystkie miejsca zajęte. Zwolnij jedno i jedziemy.',
        },
        busy: {
            ru: 'Спасибо, меня уже подвозят. Удачи на дороге!',
            ua: 'Дякую, мене вже підвозять. Щасливої дороги!',
            en: 'Thanks, I already got a ride. Safe roads!',
            de: 'Danke, ich werde schon mitgenommen. Gute Fahrt!',
            pl: 'Dzięki, już mnie ktoś zabiera. Szerokiej drogi!',
        },
        accept: {
            ru: 'Садись, довезу',
            ua: 'Сідай, довезу',
            en: 'Get in, I will drive you',
            de: 'Steig ein, ich fahre dich',
            pl: 'Wsiadaj, podwiozę',
        },
        ask: {
            ru: 'А что случилось-то?',
            ua: 'А що взагалі сталося?',
            en: 'What happened to you?',
            de: 'Was ist dir denn passiert?',
            pl: 'Co ci się właściwie stało?',
        },
        decline: {
            ru: 'Не по пути, извини',
            ua: 'Не по дорозі, вибач',
            en: 'Not my direction, sorry',
            de: 'Nicht mein Weg, tut mir leid',
            pl: 'Nie po drodze, wybacz',
        },
        ok: {
            ru: 'Понял',
            ua: 'Зрозумів',
            en: 'Got it',
            de: 'Verstanden',
            pl: 'Jasne',
        },
    },
};
