export default {
    blip: {
        name: {
            ru: 'Агентство недвижимости',
            ua: 'Агентство нерухомості',
            en: 'Real Estate Agency',
            de: 'Immobilienagentur',
            pl: 'Agencja nieruchomości',
        },
    },
    dialogs: {
        main: {
            welcome: {
                ru: 'Добрый день. Я помогу подобрать свободный дом по всему штату. Что вас интересует?',
                ua: 'Добрий день. Я допоможу підібрати вільний будинок по всьому штату. Що вас цікавить?',
                en: 'Good day. I can help you find available houses across the state. What are you looking for?',
                de: 'Guten Tag. Ich helfe Ihnen, freie Häuser im ganzen Bundesstaat zu finden. Was interessiert Sie?',
                pl: 'Dzień dobry. Pomogę dobrać wolny dom w całym stanie. Czego szukasz?',
            },
            showOffers: {
                ru: 'Покажите доступные предложения',
                ua: 'Покажіть доступні пропозиції',
                en: 'Show me available offers',
                de: 'Zeigen Sie mir verfügbare Angebote',
                pl: 'Pokaż dostępne oferty',
            },
            howItWorks: {
                ru: 'Как проходит подбор дома?',
                ua: 'Як відбувається підбір будинку?',
                en: 'How does house selection work?',
                de: 'Wie funktioniert die Haussuche?',
                pl: 'Jak działa dobór domu?',
            },
            routeToReserved: {
                ru: 'Проложить маршрут к забронированному дому',
                ua: 'Прокласти маршрут до заброньованого будинку',
                en: 'Set route to reserved house',
                de: 'Route zum reservierten Haus setzen',
                pl: 'Wyznacz trasę do zarezerwowanego domu',
            },
            howItWorksReply: {
                ru: 'Агентство OLYMP ESTATE помогает вам с поиском подходящих домов и оформлением брони на выбранный объект. На карте отмечены свободные варианты: выберите дом и срок брони (1, 3 или 6 часов). Окончательное решение о покупке и само оформление покупки вы принимаете самостоятельно, на своё усмотрение.',
                ua: 'Агентство OLYMP ESTATE допомагає вам із пошуком відповідних будинків і оформленням броні на обраний обʼєкт. На мапі позначені вільні варіанти: оберіть будинок і строк броні (1, 3 або 6 годин). Остаточне рішення про покупку та саме оформлення покупки ви приймаєте самостійно, на власний розсуд.',
                en: 'OLYMP ESTATE helps you find suitable houses and place a reservation on the selected property. Available options are marked on the map: choose a house and reservation duration (1, 3, or 6 hours). The final purchase decision and the purchase process itself are entirely up to you.',
                de: 'Die Agentur OLYMP ESTATE unterstützt Sie bei der Suche nach passenden Häusern und bei der Reservierung des gewählten Objekts. Freie Optionen sind auf der Karte markiert: Wählen Sie ein Haus und die Reservierungsdauer (1, 3 oder 6 Stunden). Die endgültige Kaufentscheidung und der Kaufabschluss liegen vollständig bei Ihnen.',
                pl: 'Agencja OLYMP ESTATE pomaga w znalezieniu odpowiednich domów i zarezerwowaniu wybranego obiektu. Dostępne opcje są oznaczone na mapie: wybierz dom oraz czas rezerwacji (1, 3 lub 6 godzin). Ostateczna decyzja o zakupie i samo sfinalizowanie zakupu należą wyłącznie do Ciebie.',
            },
            goodbye: {
                ru: 'Понял, спасибо. Вернусь позже',
                ua: 'Зрозумів, дякую. Повернуся пізніше',
                en: "Got it, thanks. I'll come back later",
                de: 'Verstanden, danke. Ich komme später wieder',
                pl: 'Rozumiem, dzięki. Wrócę później',
            },
        },
    },
    server: {
        houseUnavailable: {
            ru: 'Дом уже недоступен',
            ua: 'Будинок уже недоступний',
            en: 'This house is no longer available',
            de: 'Dieses Haus ist nicht mehr verfügbar',
            pl: 'Ten dom jest już niedostępny',
        },
        noReservedHouses: {
            ru: 'У вас нет активных броней домов',
            ua: 'У вас немає активних бронювань будинків',
            en: 'You have no active house reservations',
            de: 'Sie haben keine aktiven Hausreservierungen',
            pl: 'Nie masz aktywnych rezerwacji domów',
        },
        routeToReservedSet: {
            ru: 'Маршрут проложен к дому #{{houseId}}',
            ua: 'Маршрут прокладено до будинку #{{houseId}}',
            en: 'Route set to house #{{houseId}}',
            de: 'Route zum Haus #{{houseId}} wurde gesetzt',
            pl: 'Trasa wyznaczona do domu #{{houseId}}',
        },
        reservedAndRouteSet: {
            ru: 'Вы забронировали дом #{{houseId}}. Маршрут к дому проложен.',
            ua: 'Ви забронювали будинок #{{houseId}}. Маршрут до будинку прокладено.',
            en: 'You reserved house #{{houseId}}. Route to the house has been set.',
            de: 'Sie haben Haus #{{houseId}} reserviert. Die Route zum Haus wurde gesetzt.',
            pl: 'Zarezerwowałeś dom #{{houseId}}. Trasa do domu została wyznaczona.',
        },
    },
    cef: {
        title: {
            ru: 'Каталог недвижимости',
            ua: 'Каталог нерухомості',
            en: 'Property Catalog',
            de: 'Immobilienkatalog',
            pl: 'Katalog nieruchomości',
        },
        subtitle: {
            ru: 'Выберите дом на карте и изучите карточку объекта',
            ua: "Оберіть будинок на мапі та перегляньте картку об'єкта",
            en: 'Select a house on the map and view its details',
            de: 'Wählen Sie ein Haus auf der Karte und sehen Sie die Objektkarte',
            pl: 'Wybierz dom na mapie i sprawdź kartę obiektu',
        },
        housesFound: {
            ru: 'Найдено домов',
            ua: 'Знайдено будинків',
            en: 'Houses found',
            de: 'Gefundene Häuser',
            pl: 'Znalezione domy',
        },
        empty: {
            ru: 'Свободные дома сейчас отсутствуют',
            ua: 'Вільні будинки зараз відсутні',
            en: 'No available houses right now',
            de: 'Derzeit keine freien Häuser',
            pl: 'Brak wolnych domów na tę chwilę',
        },
        reserve: {
            ru: 'Забронировать',
            ua: 'Забронювати',
            en: 'Reserve',
            de: 'Reservieren',
            pl: 'Zarezerwować',
        },
        reserveDescription: {
            ru: 'Выберите срок брони: 1, 3 или 6 часов. Пока активна бронь, этот дом недоступен для покупки другими игроками.',
            ua: 'Оберіть строк броні: 1, 3 або 6 годин. Поки бронь активна, цей будинок недоступний для купівлі іншими гравцями.',
            en: 'Choose reservation duration: 1, 3, or 6 hours. While active, other players cannot buy this house.',
            de: 'Wählen Sie eine Reservierungsdauer: 1, 3 oder 6 Stunden. Solange die Reservierung aktiv ist, können andere Spieler dieses Haus nicht kaufen.',
            pl: 'Wybierz czas rezerwacji: 1, 3 lub 6 godzin. Gdy rezerwacja jest aktywna, inni gracze nie mogą kupić tego domu.',
        },
        reservePriceLabel: {
            ru: 'Цена бронирования',
            ua: 'Ціна бронювання',
            en: 'Reservation price',
            de: 'Reservierungspreis',
            pl: 'Cena rezerwacji',
        },
        reserved: {
            ru: 'Уже забронирован',
            ua: 'Вже заброньовано',
            en: 'Already reserved',
            de: 'Bereits reserviert',
            pl: 'Już zarezerwowany',
        },
        extendReserve: {
            ru: 'Продлить бронь',
            ua: 'Подовжити бронь',
            en: 'Extend reserve',
            de: 'Reservierung verlängern',
            pl: 'Przedłuż rezerwację',
        },
        setWaypoint: {
            ru: 'Поставить метку в GPS',
            ua: 'Поставити мітку в GPS',
            en: 'Set GPS waypoint',
            de: 'GPS-Punkt setzen',
            pl: 'Ustaw punkt GPS',
        },
        hoursShort: {
            ru: 'ч',
            ua: 'г',
            en: 'h',
            de: 'Std',
            pl: 'h',
        },
        state: {
            ru: 'Государство',
            ua: 'Держава',
            en: 'State',
            de: 'Staat',
            pl: 'Państwo',
        },
        day: {
            ru: 'день',
            ua: 'день',
            en: 'day',
            de: 'Tag',
            pl: 'dzień',
        },
        status: {
            free: {
                ru: 'Свободен',
                ua: 'Вільний',
                en: 'Available',
                de: 'Verfügbar',
                pl: 'Wolny',
            },
        },
        fields: {
            id: {
                ru: 'ID',
                ua: 'ID',
                en: 'ID',
                de: 'ID',
                pl: 'ID',
            },
            price: {
                ru: 'Цена',
                ua: 'Ціна',
                en: 'Price',
                de: 'Preis',
                pl: 'Cena',
            },
            class: {
                ru: 'Класс',
                ua: 'Клас',
                en: 'Class',
                de: 'Klasse',
                pl: 'Klasa',
            },
            status: {
                ru: 'Статус',
                ua: 'Статус',
                en: 'Status',
                de: 'Status',
                pl: 'Status',
            },
            owner: {
                ru: 'Владелец',
                ua: 'Власник',
                en: 'Owner',
                de: 'Besitzer',
                pl: 'Właściciel',
            },
            rent: {
                ru: 'Квартплата',
                ua: 'Квартплата',
                en: 'Rent',
                de: 'Miete',
                pl: 'Czynsz',
            },
            garage: {
                ru: 'Мест в гараже',
                ua: 'Місць у гаражі',
                en: 'Garage spots',
                de: 'Garagenplätze',
                pl: 'Miejsca w garażu',
            },
        },
    },
};
