export default {
    noAccess: {
        ru: 'У тебя нет доступа к этому сейфу',
        ua: 'У тебе немає доступу до цього сейфу',
        en: 'You don’t have access to this safe',
        de: 'Du hast keinen Zugriff auf diesen Safe',
        pl: 'Nie masz dostępu do tego sejfu',
    },
    interact: {
        ru: 'Посмотреть в сейф',
        ua: 'Подивитися в сейф',
        en: 'Look into the safe',
        de: 'In den Safe schauen',
        pl: 'Zajrzeć do sejfu',
    },
    notEnoughMoney: {
        ru: 'В сейфе нет столько денег',
        ua: 'У сейфі немає стільки грошей',
        en: 'There isn’t that much money in the safe',
        de: 'Im Safe ist nicht so viel Geld',
        pl: 'W sejfie nie ma tyle pieniędzy',
    },
    safe: {
        ru: 'Сейф',
        ua: 'Сейф',
        en: 'Safe',
        de: 'Tresor',
        pl: 'Sejf',
    },
    balance: {
        ru: 'Баланс',
        ua: 'Баланс',
        en: 'Balance',
        de: 'Kontostand',
        pl: 'Saldo',
    },
    limit: {
        ru: 'Лимит',
        ua: 'Ліміт',
        en: 'Limit',
        de: 'Limit',
        pl: 'Limit',
    },
    take: {
        ru: 'Взять',
        ua: 'Взяти',
        en: 'Take',
        de: 'Nehmen',
        pl: 'Weź',
    },
    put: {
        ru: 'Положить',
        ua: 'Покласти',
        en: 'Put',
        de: 'Hineinlegen',
        pl: 'Włóż',
    },
    placeholder: {
        ru: 'Введите сумму',
        ua: 'Введи суму',
        en: 'Enter the amount',
        de: 'Gib den Betrag ein',
        pl: 'Wpisz kwotę',
    },
};
