export default {
    blip: {
        ru: 'Downtown Towing Co.',
        ua: 'Downtown Towing Co.',
        en: 'Downtown Towing Co.',
        de: 'Downtown Towing Co.',
        pl: 'Downtown Towing Co.',
    },
    jobStarted: {
        ru: 'Вы устроились оператором эвакуатора в Downtown Towing Co. Ваш эвакуатор ожидает вас.',
        ua: 'Ви влаштувалися оператором евакуатора в Downtown Towing Co. Ваш евакуатор чекає на вас.',
        en: 'You have been hired as a tow truck operator at Downtown Towing Co. Your tow truck is waiting for you.',
        de: 'Du wurdest als Abschleppfahrer bei Downtown Towing Co. eingestellt. Dein Abschleppwagen wartet auf dich.',
        pl: 'Zostałeś zatrudniony jako operator lawety w Downtown Towing Co. Twoja laweta czeka na ciebie.',
    },
    hintFor1level: {
        ru: 'Управление эвакуатором осуществляется через меню взаимодействия (G). Подойдите к эвакуатору или сядьте в него и нажмите G.',
        ua: 'Керування евакуатором здійснюється через меню взаємодії (G). Підійдіть до евакуатора або сядьте в нього та натисніть G.',
        en: 'Tow truck controls are accessed via the interaction menu (G). Walk up to or get inside the tow truck and press G.',
        de: 'Die Steuerung des Abschleppwagens erfolgt über das Interaktionsmenü (G). Gehe zum Abschleppwagen oder steige ein und drücke G.',
        pl: 'Sterowanie lawetą odbywa się przez menu interakcji (G). Podejdź do lawety lub wsiądź do niej i naciśnij G.',
    },
    jobStopped: {
        ru: 'Вы уволились с работы оператора эвакуатора.',
        ua: 'Ви звільнилися з роботи оператора евакуатора.',
        en: 'You have quit the tow truck operator job.',
        de: 'Du hast den Job als Abschleppfahrer gekündigt.',
        pl: 'Zrezygnowałeś z pracy operatora lawety.',
    },
    newOrderNpc: {
        ru: 'Новый заказ! Заберите брошенный автомобиль и доставьте на штрафстоянку.',
        ua: 'Нове замовлення! Заберіть покинутий автомобіль та доставте на штрафмайданчик.',
        en: 'New order! Pick up the abandoned vehicle and deliver it to the impound lot.',
        de: 'Neuer Auftrag! Hole das verlassene Fahrzeug ab und bringe es zum Abschleppplatz.',
        pl: 'Nowe zlecenie! Zabierz porzucony pojazd i dostarcz go na parking policyjny.',
    },
    newOrderReal: {
        ru: 'Срочный заказ от полиции! Заберите автомобиль с ордером на эвакуацию.',
        ua: 'Терміново замовлення від поліції! Заберіть автомобіль з ордером на евакуацію.',
        en: 'Urgent police order! Pick up the vehicle with an evacuation order.',
        de: 'Dringender Polizeiauftrag! Hole das Fahrzeug mit Abschleppbefehl ab.',
        pl: 'Pilne zlecenie policyjne! Zabierz pojazd z nakazem ewakuacji.',
    },
    vehiclePickedUp: {
        ru: 'Автомобиль загружен! Доставьте его на штрафстоянку.',
        ua: 'Автомобіль завантажений! Доставте його на штрафмайданчик.',
        en: 'Vehicle loaded! Deliver it to the impound lot.',
        de: 'Fahrzeug geladen! Bringe es zum Abschleppplatz.',
        pl: 'Pojazd załadowany! Dostarcz go na parking policyjny.',
    },
    orderCompleted: {
        ru: 'Заказ выполнен! Вы получили ${{salary}}. Ожидайте следующий заказ.',
        ua: 'Замовлення виконано! Ви отримали ${{salary}}. Чекайте на наступне замовлення.',
        en: 'Order completed! You received ${{salary}}. Wait for the next order.',
        de: 'Auftrag erledigt! Du hast ${{salary}} erhalten. Warte auf den nächsten Auftrag.',
        pl: 'Zlecenie wykonane! Otrzymałeś ${{salary}}. Czekaj na następne zlecenie.',
    },
    noFreePosition: {
        ru: 'Сейчас нет доступных заказов, подождите немного.',
        ua: 'Зараз немає доступних замовлень, зачекайте трохи.',
        en: 'No available orders right now, please wait.',
        de: 'Derzeit keine Aufträge verfügbar, bitte warten.',
        pl: 'Brak dostępnych zleceń, proszę czekać.',
    },
    vehicleDestroyed: {
        ru: 'Автомобиль, который вы должны были забрать, был уничтожен.',
        ua: 'Автомобіль, який ви повинні були забрати, був знищений.',
        en: 'The vehicle you were supposed to pick up was destroyed.',
        de: 'Das Fahrzeug, das du abholen solltest, wurde zerstört.',
        pl: 'Pojazd, który miałeś zabrać, został zniszczony.',
    },
    mustBeInFlatbed: {
        ru: 'Вы должны быть в эвакуаторе для выполнения заказов.',
        ua: 'Ви повинні бути в евакуаторі для виконання замовлень.',
        en: 'You must be in the tow truck to complete orders.',
        de: 'Du musst im Abschleppwagen sein, um Aufträge zu erfüllen.',
        pl: 'Musisz być w lawecie, aby realizować zlecenia.',
    },
    smsNewOrder: {
        ru: 'Новый заказ на эвакуацию. Координаты отмечены на карте. Заберите авто и доставьте на ближайшую штрафстоянку.',
        ua: 'Нове замовлення на евакуацію. Координати позначені на карті. Заберіть авто та доставте на найближчий штрафмайданчик.',
        en: 'New tow order. Coordinates are marked on the map. Pick up the vehicle and deliver it to the nearest impound lot.',
        de: 'Neuer Abschleppauftrag. Koordinaten sind auf der Karte markiert. Hole das Fahrzeug ab und bringe es zum nächsten Abschleppplatz.',
        pl: 'Nowe zlecenie holowania. Współrzędne zaznaczone na mapie. Zabierz pojazd i dostarcz go na najbliższy parking policyjny.',
    },
    smsOrderCompleted: {
        ru: 'Отличная работа! Оплата переведена. Ожидайте следующего заказа.',
        ua: 'Відмінна робота! Оплату переведено. Чекайте наступне замовлення.',
        en: 'Great job! Payment transferred. Wait for the next order.',
        de: 'Gute Arbeit! Zahlung überwiesen. Warte auf den nächsten Auftrag.',
        pl: 'Świetna robota! Płatność przelana. Czekaj na następne zlecenie.',
    },
    orderTimedOut: {
        ru: 'Время на выполнение заказа истекло. Заказ отменён.',
        ua: 'Час на виконання замовлення вичерпано. Замовлення скасовано.',
        en: 'Order time expired. Order cancelled.',
        de: 'Die Zeit für den Auftrag ist abgelaufen. Auftrag storniert.',
        pl: 'Czas na wykonanie zlecenia minął. Zlecenie anulowane.',
    },
    hud: {
        title: {
            ru: 'Эвакуатор',
            ua: 'Евакуатор',
            en: 'Tow Truck',
            de: 'Abschleppwagen',
            pl: 'Laweta',
        },
        waitingOrder: {
            ru: 'Ожидайте новый заказ...',
            ua: 'Очікуйте нове замовлення...',
            en: 'Waiting for a new order...',
            de: 'Warte auf neuen Auftrag...',
            pl: 'Oczekiwanie na nowe zlecenie...',
        },
        goToPickupReal: {
            ru: 'Заберите автомобиль по ордеру полиции',
            ua: 'Заберіть автомобіль за ордером поліції',
            en: 'Pick up the vehicle by police order',
            de: 'Hole das Fahrzeug laut Polizeianordnung ab',
            pl: 'Zabierz pojazd na polecenie policji',
        },
        goToPickupNpc: {
            ru: 'Заберите брошенный автомобиль',
            ua: 'Заберіть покинутий автомобіль',
            en: 'Pick up the abandoned vehicle',
            de: 'Hole das verlassene Fahrzeug ab',
            pl: 'Zabierz porzucony pojazd',
        },
        deliverToLot: {
            ru: 'Доставьте авто на штрафстоянку',
            ua: 'Доставте авто на штрафмайданчик',
            en: 'Deliver the vehicle to the impound lot',
            de: 'Liefere das Fahrzeug zum Abschleppplatz',
            pl: 'Dostarcz pojazd na parking policyjny',
        },
        completed: {
            ru: 'Выполнено',
            ua: 'Виконано',
            en: 'Completed',
            de: 'Abgeschlossen',
            pl: 'Ukończono',
        },
        earned: {
            ru: 'Заработано',
            ua: 'Зароблено',
            en: 'Earned',
            de: 'Verdient',
            pl: 'Zarobiono',
        },
        timerHeader: {
            ru: 'Эвакуатор',
            ua: 'Евакуатор',
            en: 'Tow Truck',
            de: 'Abschleppwagen',
            pl: 'Laweta',
        },
        timerText: {
            ru: 'Времени на заказ',
            ua: 'Часу на замовлення',
            en: 'Time for order',
            de: 'Zeit für Auftrag',
            pl: 'Czas na zlecenie',
        },
    },
    dialogs: {
        hire: {
            welcome: {
                ru: 'Привет! Я менеджер Downtown Towing Co. У нас есть вакансия оператора эвакуатора. Хочешь подзаработать?',
                ua: "Привіт! Я менеджер Downtown Towing Co. У нас є вакансія оператора евакуатора. Хочеш підзаробити?",
                en: "Hey! I'm the manager at Downtown Towing Co. We have an opening for a tow truck operator. Want to earn some cash?",
                de: 'Hey! Ich bin der Manager bei Downtown Towing Co. Wir haben eine Stelle als Abschleppfahrer frei. Willst du etwas Geld verdienen?',
                pl: 'Hej! Jestem menedżerem Downtown Towing Co. Mamy wolne stanowisko operatora lawety. Chcesz dorobić?',
            },
            moreInfo: {
                ru: 'Расскажи подробнее',
                ua: 'Розкажи детальніше',
                en: 'Tell me more',
                de: 'Erzähl mir mehr',
                pl: 'Powiedz mi więcej',
            },
            info: {
                ru: 'Мы занимаемся эвакуацией автомобилей. Ты садишься в эвакуатор, получаешь заказы и отвозишь машины на штрафстоянку. Если полиция выпишет ордер — ты забираешь реальные машины, а если заказов нет — возишь брошенные авто. Платим за каждую доставку.',
                ua: "Ми займаємося евакуацією автомобілів. Ти сідаєш в евакуатор, отримуєш замовлення і відвозиш машини на штрафмайданчик. Якщо поліція випише ордер — ти забираєш реальні машини, а якщо замовлень нема — возиш покинуті авто. Платимо за кожну доставку.",
                en: "We handle vehicle towing. You hop in the tow truck, get orders and deliver cars to impound lots. If police issue an evacuation order — you pick up real vehicles, otherwise you tow abandoned cars. We pay per delivery.",
                de: 'Wir kümmern uns um das Abschleppen von Fahrzeugen. Du steigst in den Abschleppwagen, bekommst Aufträge und lieferst Autos zum Abschleppplatz. Wenn die Polizei einen Befehl ausstellt — holst du echte Fahrzeuge ab, sonst schleppst du verlassene Autos ab. Bezahlung pro Lieferung.',
                pl: 'Zajmujemy się holowaniem pojazdów. Wsiadasz do lawety, dostajesz zlecenia i dostarczasz auta na parking policyjny. Jeśli policja wystawi nakaz — zabierasz prawdziwe pojazdy, a jeśli zleceń nie ma — wozisz porzucone auta. Płacimy za każdą dostawę.',
            },
            yes: {
                ru: 'Давай, устраиваюсь!',
                ua: 'Давай, влаштовуюся!',
                en: "Let's do it, I'm in!",
                de: "Los geht's, ich bin dabei!",
                pl: 'Dawaj, biorę robotę!',
            },
            no: {
                ru: 'Нет, спасибо',
                ua: 'Ні, дякую',
                en: 'No, thanks',
                de: 'Nein, danke',
                pl: 'Nie, dzięki',
            },
            great: {
                ru: 'Отлично! Твой эвакуатор уже ждёт тебя на стоянке. Удачи на дорогах!',
                ua: 'Чудово! Твій евакуатор вже чекає на стоянці. Удачі на дорогах!',
                en: 'Great! Your tow truck is already waiting at the lot. Good luck on the road!',
                de: 'Super! Dein Abschleppwagen wartet bereits auf dem Parkplatz. Viel Glück auf der Straße!',
                pl: 'Świetnie! Twoja laweta już czeka na parkingu. Powodzenia na drodze!',
            },
        },
        already: {
            busy: {
                ru: 'Ты уже работаешь, не отвлекайся!',
                ua: 'Ти вже працюєш, не відволікайся!',
                en: "You're already working, stay focused!",
                de: 'Du arbeitest bereits, lass dich nicht ablenken!',
                pl: 'Już pracujesz, nie rozpraszaj się!',
            },
            ok: {
                ru: 'Ладно',
                ua: 'Гаразд',
                en: 'Okay',
                de: 'Okay',
                pl: 'Okej',
            },
        },
        quit: {
            wantQuit: {
                ru: 'Хочешь уволиться? Ну, как знаешь. Машины сами себя не эвакуируют...',
                ua: 'Хочеш звільнитися? Ну, як знаєш. Машини самі себе не евакуюють...',
                en: "Want to quit? Well, your call. Cars don't tow themselves...",
                de: 'Willst du kündigen? Nun, deine Entscheidung. Autos schleppen sich nicht von selbst ab...',
                pl: 'Chcesz się zwolnić? No cóż, twoja decyzja. Auta same się nie holują...',
            },
            yesQuit: {
                ru: 'Да, увольняюсь',
                ua: 'Так, звільняюся',
                en: "Yes, I'm quitting",
                de: 'Ja, ich kündige',
                pl: 'Tak, rezygnuję',
            },
            noStay: {
                ru: 'Нет, продолжу работать',
                ua: 'Ні, продовжу працювати',
                en: "No, I'll keep working",
                de: 'Nein, ich mache weiter',
                pl: 'Nie, będę dalej pracować',
            },
        },
        lowLevel: {
            tooLow: {
                ru: 'Извини, дружище, но у нас нужен опыт. Приходи, когда достигнешь {{level}} уровня.',
                ua: 'Вибач, друже, але нам потрібен досвід. Приходь, коли досягнеш {{level}} рівня.',
                en: 'Sorry buddy, we need experience. Come back when you reach level {{level}}.',
                de: 'Tut mir leid, Kumpel, aber wir brauchen Erfahrung. Komm wieder, wenn du Level {{level}} erreicht hast.',
                pl: 'Przepraszam, stary, ale potrzebujemy doświadczenia. Wróć, gdy osiągniesz {{level}} poziom.',
            },
            ok: {
                ru: 'Понял',
                ua: 'Зрозумів',
                en: 'Got it',
                de: 'Verstanden',
                pl: 'Rozumiem',
            },
        },
    },
};
