export default {
    name: {
        ru: 'Blood Street Gang',
        ua: 'Blood Street Gang',
        en: 'Blood Street Gang',
        de: 'Blood Street Gang',
        pl: 'Blood Street Gang',
    },
    ranks: {
        settler: {
            ru: 'Settler',
            ua: 'Settler',
            en: 'Settler',
            de: 'Settler',
            pl: 'Settler',
        },
        younggangster: {
            ru: 'Young Gangster',
            ua: 'Young Gangster',
            en: 'Young Gangster',
            de: 'Young Gangster',
            pl: 'Young Gangster',
        },
        gangster: {
            ru: 'Gangster',
            ua: 'Gangster',
            en: 'Gangster',
            de: 'Gangster',
            pl: 'Gangster',
        },
        thuggangsta: {
            ru: 'Thug Gangsta',
            ua: 'Thug Gangsta',
            en: 'Thug Gangsta',
            de: 'Thug Gangsta',
            pl: 'Thug Gangsta',
        },
        ghettosoldier: {
            ru: 'Ghetto Soldier',
            ua: 'Ghetto Soldier',
            en: 'Ghetto Soldier',
            de: 'Ghetto Soldier',
            pl: 'Ghetto Soldier',
        },
        cutthroat: {
            ru: 'Cutthroat',
            ua: 'Cutthroat',
            en: 'Cutthroat',
            de: 'Cutthroat',
            pl: 'Cutthroat',
        },
        lockilla: {
            ru: 'Loc Killa',
            ua: 'Loc Killa',
            en: 'Loc Killa',
            de: 'Loc Killa',
            pl: 'Loc Killa',
        },
        bloodmentor: {
            ru: 'Blood Mentor',
            ua: 'Blood Mentor',
            en: 'Blood Mentor',
            de: 'Blood Mentor',
            pl: 'Blood Mentor',
        },
        advisor: {
            ru: 'Advisor',
            ua: 'Advisor',
            en: 'Advisor',
            de: 'Advisor',
            pl: 'Advisor',
        },
        eastsidepac: {
            ru: 'East Side Pac',
            ua: 'East Side Pac',
            en: 'East Side Pac',
            de: 'East Side Pac',
            pl: 'East Side Pac',
        },
    },
};
