export default {
    name: {
        ru: 'Blood Street Gang',
        ua: 'Blood Street Gang',
        en: 'Blood Street Gang',
        de: 'Blood Street Gang',
        pl: 'Blood Street Gang',
        zh:'血帮'.
    },
    ranks: {
        settler: {
            ru: 'Settler',
            ua: 'Settler',
            en: 'Settler',
            de: 'Settler',
            pl: 'Settler',
            zh:'定居者',
        },
        younggangster: {
            ru: 'Young Gangster',
            ua: 'Young Gangster',
            en: 'Young Gangster',
            de: 'Young Gangster',
            pl: 'Young Gangster',
           zh:'少年黑帮',
        },
        gangster: {
            ru: 'Gangster',
            ua: 'Gangster',
            en: 'Gangster',
            de: 'Gangster',
            pl: 'Gangster',
            zh:'黑帮',
        },
        thuggangsta: {
            ru: 'Thug Gangsta',
            ua: 'Thug Gangsta',
            en: 'Thug Gangsta',
            de: 'Thug Gangsta',
            pl: 'Thug Gangsta',
           zh:'暴徒',
        },
        ghettosoldier: {
            ru: 'Ghetto Soldier',
            ua: 'Ghetto Soldier',
            en: 'Ghetto Soldier',
            de: 'Ghetto Soldier',
            pl: 'Ghetto Soldier',
            zh:'贫民区士兵',
        },
        cutthroat: {
            ru: 'Cutthroat',
            ua: 'Cutthroat',
            en: 'Cutthroat',
            de: 'Cutthroat',
            pl: 'Cutthroat',
           zh:'Cutthroat',
        },
        lockilla: {
            ru: 'Loc Killa',
            ua: 'Loc Killa',
            en: 'Loc Killa',
            de: 'Loc Killa',
            pl: 'Loc Killa',
           zh:'基拉湖',
        },
        bloodmentor: {
            ru: 'Blood Mentor',
            ua: 'Blood Mentor',
            en: 'Blood Mentor',
            de: 'Blood Mentor',
            pl: 'Blood Mentor',
            zh:'血液导师',
        },
        advisor: {
            ru: 'Advisor',
            ua: 'Advisor',
            en: 'Advisor',
            de: 'Advisor',
            pl: 'Advisor',
           zh:'顾问',
        },
        eastsidepac: {
            ru: 'East Side Pac',
            ua: 'East Side Pac',
            en: 'East Side Pac',
            de: 'East Side Pac',
            pl: 'East Side Pac',
            zh:'东区Pac',
        },
    },
};
