export default {
    name: {
        ru: 'EMS',
        ua: 'EMS',
        en: 'EMS',
        de: 'EMS',
        pl: 'EMS',
        zh:'EMS',
    },
    ranks: {
        student: {
            ru: 'Студент',
            ua: 'Студент',
            en: 'Student',
            de: 'Student',
            pl: 'Student',
            zh:'学生',
        },
        intern: {
            ru: 'Интерн',
            ua: 'Інтерн',
            en: 'Intern',
            de: 'Praktikant',
            pl: 'Stażysta',
           zh:'互联网',
        },
        medicalWorker: {
            ru: 'Медицинский Работник',
            ua: 'Медичний Працівник',
            en: 'Medical Worker',
            de: 'Medizinischer Arbeiter',
            pl: 'Pracownik Medyczny',
           zh:'医务工作者',
        },
        doctor: {
            ru: 'Доктор',
            ua: 'Лікар',
            en: 'Doctor',
            de: 'Arzt',
            pl: 'Lekarz',
           zh:'医生',
        },
        therapist: {
            ru: 'Терапевт',
            ua: 'Терапевт',
            en: 'Therapist',
            de: 'Therapeut',
            pl: 'Terapeuta',
            zh:'治疗师',
        },
        narсologist: {
            ru: 'Нарколог',
            ua: 'Нарколог',
            en: 'Narcologist',
            de: 'Narkologe',
            pl: 'Narkolog',
           zh:'麻醉师',
        },
        surgeon: {
            ru: 'Хирург',
            ua: 'Хірург',
            en: 'Surgeon',
            de: 'Chirurg',
            pl: 'Chirurg',
            zh:'外科医生',
        },
        psychiatrist: {
            ru: 'Психиатр',
            ua: 'Психіатр',
            en: 'Psychiatrist',
            de: 'Psychiater',
            pl: 'Psychiatra',
            zh:'精神科医生',
        },
        inspector: {
            ru: 'Инспектор',
            ua: 'Інспектор',
            en: 'Inspector',
            de: 'Inspektor',
            pl: 'Inspektor',
            zh:'检查员',
        },
        specialist: {
            ru: 'Специалист',
            ua: 'Спеціаліст',
            en: 'Specialist',
            de: 'Spezialist',
            pl: 'Specjalista',
            zh:'专家',
        },
        seniorInspector: {
            ru: 'Старший инспектор',
            ua: 'Старший інспектор',
            en: 'Senior Inspector',
            de: 'Oberinspektor',
            pl: 'Starszy Inspektor',
            zh:'高级督察',
        },
        chiefOfEMSInspection: {
            ru: 'Начальник инспекции EMS',
            ua: 'Начальник інспекції EMS',
            en: 'Chief of EMS Inspection',
            de: 'Leiter der EMS-Inspektion',
            pl: 'Szef Inspekcji EMS',
            zh:'EMS检查主管',
        },
        deputyChiefPhysician: {
            ru: 'Заместитель Глав Врача',
            ua: 'Заступник Головного Лікаря',
            en: 'Deputy Chief Physician',
            de: 'Stellvertretender Chefarzt',
            pl: 'Zastępca Głównego Lekarza',
            zh:'副主任医师',
        },
        chiefPhysician: {
            ru: 'Глав Врач',
            ua: 'Головний Лікар',
            en: 'Chief Physician',
            de: 'Chefarzt',
            pl: 'Główny Lekarz',
            zh:'主任医师',
        },
    },
};
