export default {
    name: {
        ru: 'The Families',
        ua: 'The Families',
        en: 'The Families',
        de: 'The Families',
        pl: 'The Families',
    },
    ranks: {
        youngsta: {
            ru: 'Youngsta',
            ua: 'Youngsta',
            en: 'Youngsta',
            de: 'Youngsta',
            pl: 'Youngsta',
        },
        beginner: {
            ru: 'Beginner',
            ua: 'Beginner',
            en: 'Beginner',
            de: 'Beginner',
            pl: 'Beginner',
        },
        checkedup: {
            ru: 'Checked Up',
            ua: 'Checked Up',
            en: 'Checked Up',
            de: 'Checked Up',
            pl: 'Checked Up',
        },
        hustler: {
            ru: 'Hustler',
            ua: 'Hustler',
            en: 'Hustler',
            de: 'Hustler',
            pl: 'Hustler',
        },
        hoodlum: {
            ru: 'Hoodlum',
            ua: 'Hoodlum',
            en: 'Hoodlum',
            de: 'Hoodlum',
            pl: 'Hoodlum',
        },
        blackflawless: {
            ru: 'Black Flawless',
            ua: 'Black Flawless',
            en: 'Black Flawless',
            de: 'Black Flawless',
            pl: 'Black Flawless',
        },
        outlaw: {
            ru: 'Outlaw',
            ua: 'Outlaw',
            en: 'Outlaw',
            de: 'Outlaw',
            pl: 'Outlaw',
        },
        authority: {
            ru: 'Authority',
            ua: 'Authority',
            en: 'Authority',
            de: 'Authority',
            pl: 'Authority',
        },
        deputypac: {
            ru: 'Deputy Pac',
            ua: 'Deputy Pac',
            en: 'Deputy Pac',
            de: 'Deputy Pac',
            pl: 'Deputy Pac',
        },
        strawberrypac: {
            ru: 'Strawberry Pac',
            ua: 'Strawberry Pac',
            en: 'Strawberry Pac',
            de: 'Strawberry Pac',
            pl: 'Strawberry Pac',
        },
    },
};
