export default {
    name: {
        ru: 'The Families',
        ua: 'The Families',
        en: 'The Families',
        de: 'The Families',
        pl: 'The Families',
        zh: '家庭',
    },
    ranks: {
        youngsta: {
            ru: 'Youngsta',
            ua: 'Youngsta',
            en: 'Youngsta',
            de: 'Youngsta',
            pl: 'Youngsta',
            zh: 'Youngsta',
        },
        beginner: {
            ru: 'Beginner',
            ua: 'Beginner',
            en: 'Beginner',
            de: 'Beginner',
            pl: 'Beginner',
            zh: '初学者',
        },
        checkedup: {
            ru: 'Checked Up',
            ua: 'Checked Up',
            en: 'Checked Up',
            de: 'Checked Up',
            pl: 'Checked Up',
            zh: '检查过了',
        },
        hustler: {
            ru: 'Hustler',
            ua: 'Hustler',
            en: 'Hustler',
            de: 'Hustler',
            pl: 'Hustler',
            zh: '骗子',
        },
        hoodlum: {
            ru: 'Hoodlum',
            ua: 'Hoodlum',
            en: 'Hoodlum',
            de: 'Hoodlum',
            pl: 'Hoodlum',
            zh: 'Hoodlum',
        },
        blackflawless: {
            ru: 'Black Flawless',
            ua: 'Black Flawless',
            en: 'Black Flawless',
            de: 'Black Flawless',
            pl: 'Black Flawless',
            zh: '黑色无瑕',
        },
        outlaw: {
            ru: 'Outlaw',
            ua: 'Outlaw',
            en: 'Outlaw',
            de: 'Outlaw',
            pl: 'Outlaw',
            zh: '违法',
        },
        authority: {
            ru: 'Authority',
            ua: 'Authority',
            en: 'Authority',
            de: 'Authority',
            pl: 'Authority',
            zh: '权威',
        },
        deputypac: {
            ru: 'Deputy Pac',
            ua: 'Deputy Pac',
            en: 'Deputy Pac',
            de: 'Deputy Pac',
            pl: 'Deputy Pac',
            zh: '副警长',
        },
        strawberrypac: {
            ru: 'Strawberry Pac',
            ua: 'Strawberry Pac',
            en: 'Strawberry Pac',
            de: 'Strawberry Pac',
            pl: 'Strawberry Pac',
            zh: '草莓派',
        },
    },
};
