export default {
    name: {
        ru: 'LSPD',
        ua: 'LSPD',
        en: 'LSPD',
        de: 'LSPD',
        pl: 'LSPD',
    },
    ranks: {
        cadet: {
            ru: 'Кадет',
            ua: 'Кадет',
            en: 'Cadet',
            de: 'Kadett',
            pl: 'Kadet',
        },
        senior_cadet: {
            ru: 'Старший кадет',
            ua: 'Старший кадет',
            en: 'Senior Cadet',
            de: 'Senior Kadett',
            pl: 'Starszy kadet',
        },
        trainee_officer: {
            ru: 'Офицер стажер',
            ua: 'Офіцер-стажер',
            en: 'Trainee Officer',
            de: 'Auszubildender Offizier',
            pl: 'Stażysta oficer',
        },
        corporal: {
            ru: 'Капрал',
            ua: 'Капрал',
            en: 'Corporal',
            de: 'Gefreiter',
            pl: 'Kapral',
        },
        sergeant: {
            ru: 'Сержант',
            ua: 'Сержант',
            en: 'Sergeant',
            de: 'Sergeant',
            pl: 'Sierżant',
        },
        staff_sergeant: {
            ru: 'Штаб-Сержант',
            ua: 'Штаб-сержант',
            en: 'Staff Sergeant',
            de: 'Stabsfeldwebel',
            pl: 'Starszy sierżant',
        },
        lieutenant: {
            ru: 'Лейтенант',
            ua: 'Лейтенант',
            en: 'Lieutenant',
            de: 'Leutnant',
            pl: 'Porucznik',
        },
        captain: {
            ru: 'Капитан',
            ua: 'Капітан',
            en: 'Captain',
            de: 'Kapitän',
            pl: 'Kapitan',
        },
        department_inspector: {
            ru: 'Инспектор отдела',
            ua: 'Інспектор відділу',
            en: 'Department Inspector',
            de: 'Abteilungsinspektor',
            pl: 'Inspektor działu',
        },
        department_head: {
            ru: 'Начальник отдела',
            ua: 'Начальник відділу',
            en: 'Department Head',
            de: 'Abteilungsleiter',
            pl: 'Kierownik działu',
        },
        deputy_chief: {
            ru: 'Заместитель Шефа',
            ua: 'Заступник Шефа',
            en: 'Deputy Chief',
            de: 'Stellvertretender Chef',
            pl: 'Zastępca szefa',
        },
        chief: {
            ru: 'Шеф',
            ua: 'Шеф',
            en: 'Chief',
            de: 'Chef',
            pl: 'Szef',
        },
    },
};
