export default {
    name: {
        ru: 'Marabunta Grande',
        ua: 'Marabunta Grande',
        en: 'Marabunta Grande',
        de: 'Marabunta Grande',
        pl: 'Marabunta Grande',
        zh:'大马拉邦塔',
    },
    ranks: {
        forastero: {
            ru: 'Forastero',
            ua: 'Forastero',
            en: 'Forastero',
            de: 'Forastero',
            pl: 'Forastero',
            zh:'福拉斯特罗',
        },
        jovenes: {
            ru: 'Jovenes',
            ua: 'Jovenes',
            en: 'Jovenes',
            de: 'Jovenes',
            pl: 'Jovenes',
            zh:'年轻人',
        },
        formado: {
            ru: 'Formado',
            ua: 'Formado',
            en: 'Formado',
            de: 'Formado',
            pl: 'Formado',
            zh:'格式',
        },
        bandido: {
            ru: 'Bandido',
            ua: 'Bandido',
            en: 'Bandido',
            de: 'Bandido',
            pl: 'Bandido',
            zh:'土匪',
        },
        verificado: {
            ru: 'Verificado',
            ua: 'Verificado',
            en: 'Verificado',
            de: 'Verificado',
            pl: 'Verificado',
            zh:'已验证',
        },
        matador: {
            ru: 'Matador',
            ua: 'Matador',
            en: 'Matador',
            de: 'Matador',
            pl: 'Matador',
            zh:'杀手',
        },
        elegante: {
            ru: 'Elegante',
            ua: 'Elegante',
            en: 'Elegante',
            de: 'Elegante',
            pl: 'Elegante',
            zh:'优雅',
        },
        suplente: {
            ru: 'Suplente',
            ua: 'Suplente',
            en: 'Suplente',
            de: 'Suplente',
            pl: 'Suplente',
            zh:'至高无上',
        },
        adjunto: {
            ru: 'Adjunto',
            ua: 'Adjunto',
            en: 'Adjunto',
            de: 'Adjunto',
            pl: 'Adjunto',
            zh:'在一起',
        },
        padre: { ru: 'Padre', ua: 'Padre', en: 'Padre', de: 'Padre', pl: 'Padre' },
    },
};
