export default {
    name: {
        ru: 'LS Vagos',
        ua: 'LS Vagos',
        en: 'LS Vagos',
        de: 'LS Vagos',
        pl: 'LS Vagos',
    },
    ranks: {
        novato: {
            ru: 'Novato',
            ua: 'Novato',
            en: 'Novato',
            de: 'Novato',
            pl: 'Novato',
        },
        ordinario: {
            ru: 'Ordinario',
            ua: 'Ordinario',
            en: 'Ordinario',
            de: 'Ordinario',
            pl: 'Ordinario',
        },
        local: { ru: 'Local', ua: 'Local', en: 'Local', de: 'Local', pl: 'Local' },
        buscando: {
            ru: 'Buscando',
            ua: 'Buscando',
            en: 'Buscando',
            de: 'Buscando',
            pl: 'Buscando',
        },
        hermano: {
            ru: 'Hermano',
            ua: 'Hermano',
            en: 'Hermano',
            de: 'Hermano',
            pl: 'Hermano',
        },
        soldado: {
            ru: 'Soldado',
            ua: 'Soldado',
            en: 'Soldado',
            de: 'Soldado',
            pl: 'Soldado',
        },
        elgangsterviejo: {
            ru: 'El gangster viejo',
            ua: 'El gangster viejo',
            en: 'El gangster viejo',
            de: 'El gangster viejo',
            pl: 'El gangster viejo',
        },
        autoridad: {
            ru: 'Autoridad',
            ua: 'Autoridad',
            en: 'Autoridad',
            de: 'Autoridad',
            pl: 'Autoridad',
        },
        asesor: {
            ru: 'Asesor',
            ua: 'Asesor',
            en: 'Asesor',
            de: 'Asesor',
            pl: 'Asesor',
        },
        elpadre: {
            ru: 'El Padre',
            ua: 'El Padre',
            en: 'El Padre',
            de: 'El Padre',
            pl: 'El Padre',
        },
    },
};
