export default {
    name: {
        ru: 'ВЗЛОМ КОДОВОЙ ПАНЕЛИ',
        ua: 'ЗЛАМ КОДОВОЇ ПАНЕЛІ',
        en: 'BREACH THE CODE PANEL',
        de: 'CODEFELD AUFBRECHEN',
        pl: 'ZLAM PANEL KODOWY',
    },
    desc: {
        ru: 'Соберите коды в нужном порядке. Подсветка идёт по строке, затем по столбцу выбранного кода.',
        ua: 'Зберіть коди в потрібному порядку. Підсвітка йде по рядку, потім по стовпцю обраного коду.',
        en: 'Collect the codes in order. The highlight runs along a row, then along the column of the code you took.',
        de: 'Sammle die Codes in der richtigen Reihenfolge. Die Hervorhebung laeuft ueber eine Zeile, dann ueber die Spalte des gewaehlten Codes.',
        pl: 'Zbieraj kody we wlasciwej kolejnosci. Podswietlenie idzie po wierszu, a potem po kolumnie wybranego kodu.',
    },
    labelGrid: {
        ru: 'СЕТКА КОДОВ',
        ua: 'СІТКА КОДІВ',
        en: 'CODE GRID',
        de: 'CODERASTER',
        pl: 'SIATKA KODOW',
    },
    labelSequence: {
        ru: 'ПОСЛЕДОВАТЕЛЬНОСТЬ',
        ua: 'ПОСЛІДОВНІСТЬ',
        en: 'SEQUENCE',
        de: 'SEQUENZ',
        pl: 'SEKWENCJA',
    },
    labelBuffer: {
        ru: 'БУФЕР',
        ua: 'БУФЕР',
        en: 'BUFFER',
        de: 'PUFFER',
        pl: 'BUFOR',
    },
    statusInjecting: {
        ru: 'Подбор кода',
        ua: 'Підбір коду',
        en: 'Injecting',
        de: 'Einspeisung',
        pl: 'Wstrzykiwanie',
    },
    statusBreached: {
        ru: 'Взломано',
        ua: 'Зламано',
        en: 'Breached',
        de: 'Geknackt',
        pl: 'Zlamane',
    },
    statusLockout: {
        ru: 'Блокировка',
        ua: 'Блокування',
        en: 'Lockout',
        de: 'Sperre',
        pl: 'Blokada',
    },
    hintPick: {
        ru: 'Выбрать код',
        ua: 'Обрати код',
        en: 'Take a code',
        de: 'Code nehmen',
        pl: 'Wybierz kod',
    },
    hintExit: {
        ru: 'Выйти из игры',
        ua: 'Вийти з гри',
        en: 'Exit game',
        de: 'Spiel verlassen',
        pl: 'Wyjdź z gry',
    },
    msgRow: {
        ru: 'Возьмите код из подсвеченной строки.',
        ua: 'Візьміть код із підсвіченого рядка.',
        en: 'Take a code from the highlighted row.',
        de: 'Nimm einen Code aus der hervorgehobenen Zeile.',
        pl: 'Wez kod z podswietlonego wiersza.',
    },
    msgColumn: {
        ru: 'Возьмите код из подсвеченного столбца.',
        ua: 'Візьміть код із підсвіченого стовпця.',
        en: 'Take a code from the highlighted column.',
        de: 'Nimm einen Code aus der hervorgehobenen Spalte.',
        pl: 'Wez kod z podswietlonej kolumny.',
    },
    msgBreached: {
        ru: 'Код принят. Панель отключена.',
        ua: 'Код прийнято. Панель вимкнено.',
        en: 'Code accepted. The panel is down.',
        de: 'Code angenommen. Das Feld ist tot.',
        pl: 'Kod przyjety. Panel wylaczony.',
    },
    msgOverrun: {
        ru: 'Буфер переполнен. Панель ушла в блокировку.',
        ua: 'Буфер переповнено. Панель пішла в блокування.',
        en: 'Buffer overrun. The panel went into lockout.',
        de: 'Puffer uebergelaufen. Das Feld ist in die Sperre gegangen.',
        pl: 'Przepelnienie bufora. Panel przeszedl w blokade.',
    },
    msgTimeout: {
        ru: 'Время вышло. Панель ушла в блокировку.',
        ua: 'Час вийшов. Панель пішла в блокування.',
        en: 'Out of time. The panel went into lockout.',
        de: 'Zeit abgelaufen. Das Feld ist in die Sperre gegangen.',
        pl: 'Koniec czasu. Panel przeszedl w blokade.',
    },
};
