export default {
    name: {
        ru: 'ПРОВЕРКА НАВЫКА',
        ua: 'ПЕРЕВІРКА НАВИЧКИ',
        en: 'SKILL CHECK',
        de: 'FERTIGKEITSPRUEFUNG',
        pl: 'TEST UMIEJETNOSCI',
    },
    desc: {
        ru: 'Нажимайте, когда метка идёт по подсвеченному сектору. Промах или конец времени завершают попытку.',
        ua: 'Натискайте, коли мітка йде по підсвіченому сектору. Промах або кінець часу завершують спробу.',
        en: 'Hit the key while the marker is inside the highlighted sector. One miss or the clock ends the attempt.',
        de: 'Druecke, waehrend die Marke im hervorgehobenen Sektor laeuft. Ein Fehlschlag oder die Uhr beendet den Versuch.',
        pl: 'Nacisnij, gdy znacznik jest w podswietlonym sektorze. Pudlo albo koniec czasu konczy probe.',
    },
    labelRounds: {
        ru: 'ПОПАДАНИЯ',
        ua: 'ВЛУЧАННЯ',
        en: 'HITS',
        de: 'TREFFER',
        pl: 'TRAFIENIA',
    },
    statusTracking: {
        ru: 'Подбор момента',
        ua: 'Підбір моменту',
        en: 'Tracking',
        de: 'Verfolgung',
        pl: 'Sledzenie',
    },
    statusPassed: {
        ru: 'Пройдено',
        ua: 'Пройдено',
        en: 'Passed',
        de: 'Bestanden',
        pl: 'Zaliczone',
    },
    statusFailed: {
        ru: 'Провалено',
        ua: 'Провалено',
        en: 'Failed',
        de: 'Gescheitert',
        pl: 'Nieudane',
    },
    hintAttempt: {
        ru: 'Попытка',
        ua: 'Спроба',
        en: 'Attempt',
        de: 'Versuch',
        pl: 'Proba',
    },
    hintClick: {
        ru: 'То же мышью',
        ua: 'Те саме мишею',
        en: 'Same with the mouse',
        de: 'Dasselbe mit der Maus',
        pl: 'To samo mysza',
    },
    hintExit: {
        ru: 'Выйти из игры',
        ua: 'Вийти з гри',
        en: 'Exit game',
        de: 'Spiel verlassen',
        pl: 'Wyjdź z gry',
    },
    msgStart: {
        ru: 'Ждите, пока метка дойдёт до сектора.',
        ua: 'Чекайте, поки мітка дійде до сектора.',
        en: 'Wait until the marker reaches the sector.',
        de: 'Warte, bis die Marke den Sektor erreicht.',
        pl: 'Poczekaj, az znacznik dojdzie do sektora.',
    },
    msgHit: {
        ru: 'Есть. Осталось попаданий: {{left}}.',
        ua: 'Є. Залишилось влучань: {{left}}.',
        en: 'Caught it. Hits left: {{left}}.',
        de: 'Sitzt. Verbleibende Treffer: {{left}}.',
        pl: 'Trafione. Pozostalo trafien: {{left}}.',
    },
    msgPassed: {
        ru: 'Все попадания собраны.',
        ua: 'Усі влучання зібрано.',
        en: 'Every hit landed.',
        de: 'Alle Treffer sitzen.',
        pl: 'Wszystkie trafienia zebrane.',
    },
    msgMissed: {
        ru: 'Мимо сектора. Попытка провалена.',
        ua: 'Повз сектор. Спробу провалено.',
        en: 'Outside the sector. The attempt failed.',
        de: 'Ausserhalb des Sektors. Der Versuch ist gescheitert.',
        pl: 'Poza sektorem. Proba nieudana.',
    },
    msgTimeout: {
        ru: 'Время вышло. Попытка провалена.',
        ua: 'Час вийшов. Спробу провалено.',
        en: 'Out of time. The attempt failed.',
        de: 'Zeit abgelaufen. Der Versuch ist gescheitert.',
        pl: 'Koniec czasu. Proba nieudana.',
    },
};
