export default {
    name: {
        ru: 'ВСКРОЙТЕ СЕЙФ',
        ua: 'ЗЛАМАЙТЕ СЕЙФ',
        en: 'CRACK THE SAFE',
        de: 'KNACK DEN TRESOR',
        pl: 'OTWÓRZ SEJF',
    },
    desc: {
        ru: 'Найдите числа на слух, после каждого меняйте направление вращения.',
        ua: 'Знайдіть числа на слух, після кожного змінюйте напрямок обертання.',
        en: 'Find the numbers by ear and reverse the direction after every one.',
        de: 'Finde die Zahlen nach Gehör und wechsle nach jeder die Drehrichtung.',
        pl: 'Znajdz liczby ze sluchu i po kazdej zmieniaj kierunek obrotu.',
    },
    hintSpin: {
        ru: 'Вращать диск',
        ua: 'Обертати диск',
        en: 'Spin the dial',
        de: 'Scheibe drehen',
        pl: 'Kręć tarczą',
    },
    hintWheel: {
        ru: 'Точная подкрутка',
        ua: 'Точне підкручування',
        en: 'Fine adjustment',
        de: 'Feinjustierung',
        pl: 'Precyzyjna regulacja',
    },
    hintExit: {
        ru: 'Выйти из игры',
        ua: 'Вийти з гри',
        en: 'Exit game',
        de: 'Spiel verlassen',
        pl: 'Wyjdź z gry',
    },
    msgStart: {
        ru: 'Вращайте диск по часовой стрелке и слушайте. Глухой двойной щелчок - нужное число.',
        ua: 'Обертайте диск за годинниковою стрілкою і слухайте. Глухий подвійний щиглик - потрібне число.',
        en: 'Spin the dial clockwise and listen. A dull double click means the right number.',
        de: 'Dreh die Scheibe im Uhrzeigersinn und hör zu. Ein dumpfes Doppelklicken ist die richtige Zahl.',
        pl: 'Kręć tarczą zgodnie z ruchem wskazówek zegara i słuchaj. Głuche podwójne kliknięcie to właściwa liczba.',
    },
    msgLocked: {
        ru: 'Число {{index}} зафиксировано. Теперь вращайте {{dir}}.',
        ua: 'Число {{index}} зафіксовано. Тепер обертайте {{dir}}.',
        en: 'Number {{index}} locked in. Now spin {{dir}}.',
        de: 'Zahl {{index}} sitzt. Jetzt {{dir}} drehen.',
        pl: 'Liczba {{index}} zablokowana. Teraz kręć {{dir}}.',
    },
    msgCracked: {
        ru: 'Сейф вскрыт.',
        ua: 'Сейф зламано.',
        en: 'Safe cracked.',
        de: 'Tresor geknackt.',
        pl: 'Sejf otwarty.',
    },
    dirCw: {
        ru: 'по часовой стрелке',
        ua: 'за годинниковою стрілкою',
        en: 'clockwise',
        de: 'im Uhrzeigersinn',
        pl: 'zgodnie z ruchem wskazówek zegara',
    },
    dirCcw: {
        ru: 'против часовой стрелки',
        ua: 'проти годинникової стрілки',
        en: 'counter-clockwise',
        de: 'gegen den Uhrzeigersinn',
        pl: 'przeciwnie do ruchu wskazówek zegara',
    },
};
