export default {
    name: {
        ru: 'РЕЗКА ГОРЕЛКОЙ',
        ua: 'РІЗАННЯ ПАЛЬНИКОМ',
        en: 'TORCH CUT',
        de: 'BRENNSCHNEIDEN',
        pl: 'CIECIE PALNIKIEM',
    },
    desc: {
        ru: 'Зажгите горелку у метки и ведите её по пунктиру, держась на кончике реза. Сход со шва, обгон реза и остановки греют сталь; перегрев или конец времени завершают попытку.',
        ua: 'Запаліть пальник біля мітки й ведіть його по пунктиру, тримаючись на кінчику різу. Схід зі шва, обгін різу та зупинки гріють сталь; перегрів або кінець часу завершують спробу.',
        en: 'Light the torch at the mark and run it along the dotted line, staying on the tip of the cut. Leaving the seam, running ahead of the cut or stopping heats the steel; overheating or the clock ends the attempt.',
        de: 'Zuende den Brenner an der Marke und fuehre ihn an der gestrichelten Linie entlang, immer an der Spitze des Schnitts. Abweichen von der Naht, Vorauseilen oder Anhalten erhitzt den Stahl; Ueberhitzung oder die Uhr beendet den Versuch.',
        pl: 'Zapal palnik przy znaczniku i prowadz go wzdluz przerywanej linii, trzymajac sie konca ciecia. Zejscie ze szwu, wyprzedzanie ciecia lub zatrzymanie nagrzewa stal; przegrzanie albo koniec czasu konczy probe.',
    },
    labelHeat: {
        ru: 'НАГРЕВ',
        ua: 'НАГРІВ',
        en: 'HEAT',
        de: 'HITZE',
        pl: 'NAGRZANIE',
    },
    labelCut: {
        ru: 'РЕЗ',
        ua: 'РІЗ',
        en: 'CUT',
        de: 'SCHNITT',
        pl: 'CIECIE',
    },
    statusIdle: {
        ru: 'Горелка погашена',
        ua: 'Пальник погашено',
        en: 'Torch off',
        de: 'Brenner aus',
        pl: 'Palnik zgaszony',
    },
    statusCutting: {
        ru: 'Резка',
        ua: 'Різання',
        en: 'Cutting',
        de: 'Schneiden',
        pl: 'Ciecie',
    },
    statusPassed: {
        ru: 'Пройдено',
        ua: 'Пройдено',
        en: 'Passed',
        de: 'Bestanden',
        pl: 'Zaliczone',
    },
    statusFailed: {
        ru: 'Провалено',
        ua: 'Провалено',
        en: 'Failed',
        de: 'Gescheitert',
        pl: 'Nieudane',
    },
    hintTorch: {
        ru: 'Держать - горелка горит',
        ua: 'Тримати - пальник горить',
        en: 'Hold - torch lit',
        de: 'Halten - Brenner an',
        pl: 'Trzymaj - palnik pali sie',
    },
    hintMove: {
        ru: 'Вести вдоль шва',
        ua: 'Вести вздовж шва',
        en: 'Run along the seam',
        de: 'An der Naht entlangfuehren',
        pl: 'Prowadz wzdluz szwu',
    },
    hintExit: {
        ru: 'Выйти из игры',
        ua: 'Вийти з гри',
        en: 'Exit game',
        de: 'Spiel verlassen',
        pl: 'Wyjdz z gry',
    },
    msgStart: {
        ru: 'Зажмите кнопку у метки в начале шва.',
        ua: 'Затисніть кнопку біля мітки на початку шва.',
        en: 'Hold the button at the mark where the seam starts.',
        de: 'Halte die Taste an der Marke am Anfang der Naht.',
        pl: 'Przytrzymaj przycisk przy znaczniku na poczatku szwu.',
    },
    msgCut: {
        ru: 'Ровный ход, держите горелку на кончике реза.',
        ua: 'Рівний хід, тримайте пальник на кінчику різу.',
        en: 'Steady pace, keep the torch on the tip of the cut.',
        de: 'Gleichmaessig weiter, den Brenner an der Spitze des Schnitts halten.',
        pl: 'Rowne tempo, trzymaj palnik na koncu ciecia.',
    },
    msgHot: {
        ru: 'Перегрев. Отпустите горелку и дайте стали остыть.',
        ua: 'Перегрів. Відпустіть пальник і дайте сталі охолонути.',
        en: 'Overheating. Let go of the torch and let the steel cool.',
        de: 'Ueberhitzung. Brenner loslassen und den Stahl abkuehlen lassen.',
        pl: 'Przegrzanie. Pusc palnik i daj stali ostygnac.',
    },
    msgPassed: {
        ru: 'Шов прорезан.',
        ua: 'Шов прорізано.',
        en: 'The seam is through.',
        de: 'Die Naht ist durch.',
        pl: 'Szew przeciety.',
    },
    msgOverheat: {
        ru: 'Сталь перегрета. Попытка провалена.',
        ua: 'Сталь перегріта. Спробу провалено.',
        en: 'The steel overheated. The attempt failed.',
        de: 'Der Stahl ist ueberhitzt. Der Versuch ist gescheitert.',
        pl: 'Stal przegrzana. Proba nieudana.',
    },
    msgTimeout: {
        ru: 'Время вышло. Попытка провалена.',
        ua: 'Час вийшов. Спробу провалено.',
        en: 'Out of time. The attempt failed.',
        de: 'Zeit abgelaufen. Der Versuch ist gescheitert.',
        pl: 'Koniec czasu. Proba nieudana.',
    },
};
