export default {
    difficultyLevels: {
        EASY: {
            ru: 'ПРОСТО',
            ua: 'ПРОСТО',
            en: 'EASY',
            de: 'EINFACH',
            pl: 'ŁATWY',
        },
        MEDIUM: {
            ru: 'СРЕДНЕ',
            ua: 'СЕРЕДНЬО',
            en: 'MEDIUM',
            de: 'MITTEL',
            pl: 'ŚREDNI',
        },
        HARD: {
            ru: 'СЛОЖНО',
            ua: 'СКЛАДНО',
            en: 'HARD',
            de: 'SCHWER',
            pl: 'TRUDNY',
        },
        EXPERT: {
            ru: 'ЭКСПЕРТ',
            ua: 'ЕКСПЕРТ',
            en: 'EXPERT',
            de: 'EXPERTE',
            pl: 'EKSPERT',
        },
    },
    hitZones: {
        PERFECT: {
            ru: 'СОВЕРШЕННО',
            ua: 'ДОСКОНАЛО',
            en: 'PERFECT',
            de: 'PERFEKT',
            pl: 'PERFEKCYJNIE',
        },
        GOOD: {
            ru: 'ХОРОШО',
            ua: 'ДОБРЕ',
            en: 'GOOD',
            de: 'GUT',
            pl: 'DOBRZE',
        },
        HIT: {
            ru: 'ПОПАДАНИЕ',
            ua: 'ВЛУЧАННЯ',
            en: 'NORMAL',
            de: 'TREFFER',
            pl: 'TRAFIENIE',
        },
        POOR: {
            ru: 'СЛАБО',
            ua: 'СЛАБО',
            en: 'POOR',
            de: 'SCHLECHT',
            pl: 'SŁABO',
        },
        MISS: {
            ru: 'ПРОМАХ',
            ua: 'ПРОМАХ',
            en: 'MISS',
            de: 'VERFEHLT',
            pl: 'CHYBIENIE',
        },
    },
    cef: {
        shooting_range: {
            ru: 'Стрельбище',
            ua: 'Тир',
            en: 'Shooting Range',
            de: 'Schießstand',
            pl: 'Strzelnica',
        },
        description: {
            ru: 'Тут вы можете по практиковаться в стрельбе',
            ua: 'Тут ви можете потренуватися у стрільбі',
            en: 'Here you can practice shooting',
            de: 'Hier können Sie das Schießen üben',
            pl: 'Tutaj możesz poćwiczyć strzelanie',
        },
        session: {
            ru: 'Сеанс',
            ua: 'Сеанс',
            en: 'Session',
            de: 'Sitzung',
            pl: 'Sesja',
        },
        weapon: {
            ru: 'Оружие',
            ua: 'Зброя',
            en: 'Weapon',
            de: 'Waffe',
            pl: 'Broń',
        },
        targets_amount: {
            ru: 'Кол-во целей',
            ua: 'Кількість цілей',
            en: 'Number of targets',
            de: 'Anzahl der Ziele',
            pl: 'Liczba celów',
        },
        time: {
            ru: 'Время',
            ua: 'Час',
            en: 'Time',
            de: 'Zeit',
            pl: 'Czas',
        },
        difficulty: {
            ru: 'Сложность',
            ua: 'Складність',
            en: 'Difficulty',
            de: 'Schwierigkeit',
            pl: 'Trudność',
        },
        total_price: {
            ru: 'Итоговая цена за сеанс',
            ua: 'Підсумкова ціна за сеанс',
            en: 'Total session price',
            de: 'Gesamtpreis der Sitzung',
            pl: 'Łączna cena za sesję',
        },
        start: {
            ru: 'Начать',
            ua: 'Почати',
            en: 'Start',
            de: 'Starten',
            pl: 'Start',
        },
        top_shooters: {
            ru: 'Лучшие стрелки',
            ua: 'Кращі стрілки',
            en: 'Top Shooters',
            de: 'Beste Schützen',
            pl: 'Najlepsi strzelcy',
        },
        you: {
            ru: 'Вы',
            ua: 'Ви',
            en: 'You',
            de: 'Sie',
            pl: 'Ty',
        },
        timeOptions: {
            time_1_minute: {
                ru: '1 минута',
                ua: '1 хвилина',
                en: '1 minute',
                de: '1 Minute',
                pl: '1 minuta',
            },
            time_2_minutes: {
                ru: '2 минуты',
                ua: '2 хвилини',
                en: '2 minutes',
                de: '2 Minuten',
                pl: '2 minuty',
            },
            time_5_minutes: {
                ru: '5 минут',
                ua: '5 хвилин',
                en: '5 minutes',
                de: '5 Minuten',
                pl: '5 minut',
            },
            time_7_minutes: {
                ru: '7 минут',
                ua: '7 хвилин',
                en: '7 minutes',
                de: '7 Minuten',
                pl: '7 minut',
            },
        },
    },
    finishedWithRating: {
        ru: 'Вы закончили сессию на {{name}}',
        ua: 'Ви завершили сесію на {{name}}',
        en: 'You have finished the session on {{name}}',
        de: 'Sie haben die Sitzung auf {{name}} beendet',
        pl: 'Zakończyłeś sesję na {{name}}',
    },

    sessionStats: {
        ru: 'Статистика сессии: Точность {{accuracy}}% | Попаданий: {{hits}} | Промахов: {{missed}}',
        ua: 'Статистика сесії: Точність {{accuracy}}% | Влучань: {{hits}} | Промахів: {{missed}}',
        en: 'Session stats: Accuracy {{accuracy}}% | Hits: {{hits}} | Missed: {{missed}}',
        de: 'Sitzungsstatistik: Genauigkeit {{accuracy}}% | Treffer: {{hits}} | Verfehlt: {{missed}}',
        pl: 'Statystyki sesji: Celność {{accuracy}}% | Trafienia: {{hits}} | Chybienia: {{missed}}',
    },
    reactionStats: {
        ru: 'Средняя реакция: {{avgReaction}} мс | Лучшая реакция: {{bestReaction}}',
        ua: 'Середня реакція: {{avgReaction}} мс | Найкраща реакція: {{bestReaction}}',
        en: 'Average reaction: {{avgReaction}} ms | Best reaction: {{bestReaction}}',
        de: 'Durchschnittliche Reaktion: {{avgReaction}} ms | Beste Reaktion: {{bestReaction}}',
        pl: 'Średnia reakcja: {{avgReaction}} ms | Najlepsza reakcja: {{bestReaction}}',
    },
    notAvailable: {
        ru: 'Н/Д',
        ua: 'Н/Д',
        en: 'N/A',
        de: 'N/V',
        pl: 'N/D',
    },
    ms: {
        ru: 'мс',
        ua: 'мс',
        en: 'ms',
        de: 'ms',
        pl: 'ms',
    },
    yourLastRecord: {
        ru: 'Вы побили рекорд рейтинга, ваш прошлый рейтинг: {{old}} и новый: {{newRecord}}',
        ua: 'Ви побили рекорд рейтингу, ваш попередній рейтинг: {{old}}, а новий: {{newRecord}}',
        en: 'You broke the rating record, your previous rating was {{old}} and the new one is {{newRecord}}',
        de: 'Sie haben den Bewertungsrekord gebrochen, Ihre vorherige Bewertung war {{old}} und die neue ist {{newRecord}}',
        pl: 'Pobito rekord oceny, Twój poprzedni wynik to {{old}}, a nowy to {{newRecord}}',
    },
    blip: {
        ru: 'Стрельбище',
        ua: 'Стрiлецький тир',
        en: 'Shooting range',
        de: 'Schießstand',
        pl: 'Strzelnica',
    },
};
