export default {
    blip: {
        ru: 'Стрельбище',
        ua: 'Стрiлецький тир',
        en: 'Shooting range',
        de: 'Schießstand',
        pl: 'Strzelnica',
    },
    categories: {
        pistol: {
            ru: 'Пистолет',
            ua: 'Пістолет',
            en: 'Pistol',
            de: 'Pistole',
            pl: 'Pistolet',
        },
        smg: {
            ru: 'Пистолет-пулемёт',
            ua: 'Пістолет-кулемет',
            en: 'SMG',
            de: 'MP',
            pl: 'Pistolet maszynowy',
        },
        shotgun: {
            ru: 'Дробовик',
            ua: 'Дробовик',
            en: 'Shotgun',
            de: 'Schrotflinte',
            pl: 'Strzelba',
        },
        ar: {
            ru: 'Штурмовая винтовка',
            ua: 'Штурмова гвинтівка',
            en: 'Assault rifle',
            de: 'Sturmgewehr',
            pl: 'Karabin szturmowy',
        },
        lmg: {
            ru: 'Пулемёт',
            ua: 'Кулемет',
            en: 'LMG',
            de: 'MG',
            pl: 'Karabin maszynowy',
        },
        minigun: {
            ru: 'Миниган',
            ua: 'Мініган',
            en: 'Minigun',
            de: 'Minigun',
            pl: 'Minigun',
        },
    },
    medals: {
        none: {
            ru: 'без медали',
            ua: 'без медалі',
            en: 'no medal',
            de: 'keine Medaille',
            pl: 'bez medalu',
        },
        bronze: {
            ru: 'бронза',
            ua: 'бронза',
            en: 'bronze',
            de: 'Bronze',
            pl: 'brąz',
        },
        silver: {
            ru: 'серебро',
            ua: 'срібло',
            en: 'silver',
            de: 'Silber',
            pl: 'srebro',
        },
        gold: {
            ru: 'золото',
            ua: 'золото',
            en: 'gold',
            de: 'Gold',
            pl: 'złoto',
        },
    },
    hud: {
        multiplier: {
            ru: 'МНОЖИТЕЛЬ',
            ua: 'МНОЖНИК',
            en: 'MULTIPLIER',
            de: 'MULTIPLIKATOR',
            pl: 'MNOŻNIK',
        },
        targets: {
            ru: 'МИШЕНИ',
            ua: 'МІШЕНІ',
            en: 'TARGETS',
            de: 'ZIELE',
            pl: 'CELE',
        },
        best: {
            ru: 'РЕКОРД',
            ua: 'РЕКОРД',
            en: 'BEST SCORE',
            de: 'BESTWERT',
            pl: 'REKORD',
        },
        score: {
            ru: 'ОЧКИ',
            ua: 'ОЧКИ',
            en: 'SCORE',
            de: 'PUNKTE',
            pl: 'WYNIK',
        },
        timer: {
            ru: 'ВРЕМЯ',
            ua: 'ЧАС',
            en: 'TIME',
            de: 'ZEIT',
            pl: 'CZAS',
        },
        timeBonus: {
            ru: 'БОНУС ЗА ВРЕМЯ',
            ua: 'БОНУС ЗА ЧАС',
            en: 'TIME BONUS',
            de: 'ZEITBONUS',
            pl: 'BONUS CZASOWY',
        },
        goalBronze: {
            ru: 'ЦЕЛЬ: БРОНЗА',
            ua: 'МЕТА: БРОНЗА',
            en: 'TARGET: BRONZE',
            de: 'ZIEL: BRONZE',
            pl: 'CEL: BRĄZ',
        },
        goalSilver: {
            ru: 'ЦЕЛЬ: СЕРЕБРО',
            ua: 'МЕТА: СРІБЛО',
            en: 'TARGET: SILVER',
            de: 'ZIEL: SILBER',
            pl: 'CEL: SREBRO',
        },
        goalGold: {
            ru: 'ЦЕЛЬ: ЗОЛОТО',
            ua: 'МЕТА: ЗОЛОТО',
            en: 'TARGET: GOLD',
            de: 'ZIEL: GOLD',
            pl: 'CEL: ZŁOTO',
        },
        passed: {
            ru: 'ЗАЧЁТ',
            ua: 'ЗАРАХОВАНО',
            en: 'PASSED',
            de: 'BESTANDEN',
            pl: 'ZALICZONE',
        },
        failed: {
            ru: 'НЕЗАЧЁТ',
            ua: 'НЕ ЗАРАХОВАНО',
            en: 'FAILED',
            de: 'GESCHEITERT',
            pl: 'NIEZALICZONE',
        },
        outOfAmmo: {
            ru: 'ПАТРОНЫ КОНЧИЛИСЬ',
            ua: 'ПАТРОНИ ЗАКІНЧИЛИСЬ',
            en: 'OUT OF AMMO',
            de: 'KEINE MUNITION',
            pl: 'BRAK AMUNICJI',
        },
        medalUnlocked: {
            ru: 'МЕДАЛЬ ПОЛУЧЕНА',
            ua: 'МЕДАЛЬ ОТРИМАНА',
            en: 'MEDAL UNLOCKED',
            de: 'MEDAILLE FREIGESCHALTET',
            pl: 'MEDAL ZDOBYTY',
        },
    },
    help: {
        // SH_MULT_HG / SH_MULT_AUTO / SH_MULT_HEAVY, shown once per weapon class.
        multiplierSingle: {
            ru: 'Попадания подряд поднимают ~y~множитель~s~. Один промах сбрасывает его сразу.',
            ua: 'Влучання поспіль піднімають ~y~множник~s~. Один промах скидає його одразу.',
            en: 'Consecutive hits raise your ~y~multiplier~s~. A single miss resets it immediately.',
            de: 'Treffer in Folge erhöhen den ~y~Multiplikator~s~. Ein Fehlschuss setzt ihn sofort zurück.',
            pl: 'Trafienia z rzędu podnoszą ~y~mnożnik~s~. Jedno pudło natychmiast go zeruje.',
        },
        multiplierAuto: {
            ru: 'Попадания подряд поднимают ~y~множитель~s~. Автоматическому оружию прощается один промах.',
            ua: 'Влучання поспіль піднімають ~y~множник~s~. Автоматичній зброї пробачається один промах.',
            en: 'Consecutive hits raise your ~y~multiplier~s~. Automatic weapons are forgiven one miss.',
            de: 'Treffer in Folge erhöhen den ~y~Multiplikator~s~. Automatikwaffen wird ein Fehlschuss verziehen.',
            pl: 'Trafienia z rzędu podnoszą ~y~mnożnik~s~. Broni automatycznej wybacza się jedno pudło.',
        },
        multiplierHeavy: {
            ru: 'Держите огонь на мишенях, чтобы поднять ~y~множитель~s~. Пауза сбрасывает его.',
            ua: 'Тримайте вогонь на мішенях, щоб підняти ~y~множник~s~. Пауза скидає його.',
            en: 'Keep fire on the targets to raise your ~y~multiplier~s~. A pause resets it.',
            de: 'Halte das Feuer auf den Zielen, um den ~y~Multiplikator~s~ zu steigern. Eine Pause setzt ihn zurück.',
            pl: 'Utrzymuj ogień na celach, aby podnieść ~y~mnożnik~s~. Przerwa go zeruje.',
        },
        // SHR_EXIT_HELP.
        //
        // The button token LEADS the sentence on purpose. The help box needs <font face> markup to
        // render і/ї (see withFontFace in client/modules/fonts.ts), and the engine appears to place
        // the ~INPUT_*~ sprite from an offset measured on the marked-up string while laying the text
        // out from the parsed one - so every markup character in front of the token pushes the
        // button along the line, away from the gap reserved for it. At index 0 there is nothing in
        // front of it to shift it.
        exit: {
            ru: '~INPUT_CONTEXT~ — зажмите, чтобы прервать испытание. Результат не будет засчитан.',
            ua: '~INPUT_CONTEXT~ — затисніть, щоб перервати випробування. Результат не зарахується.',
            en: '~INPUT_CONTEXT~ — hold to leave the challenge. Your score will not count.',
            de: '~INPUT_CONTEXT~ — halten, um die Herausforderung zu verlassen. Dein Ergebnis zählt nicht.',
            pl: '~INPUT_CONTEXT~ — przytrzymaj, aby przerwać wyzwanie. Wynik nie zostanie zaliczony.',
        },
    },
    notify: {
        header: {
            ru: 'Стрельбище',
            ua: 'Тир',
            en: 'Shooting Range',
            de: 'Schießstand',
            pl: 'Strzelnica',
        },
        noMoney: {
            ru: 'Не хватает наличных: нужно ${{price}}',
            ua: 'Не вистачає готівки: потрібно ${{price}}',
            en: 'Not enough cash: ${{price}} required',
            de: 'Nicht genug Bargeld: ${{price}} nötig',
            pl: 'Za mało gotówki: potrzeba ${{price}}',
        },
    },
    chat: {
        result: {
            ru: '{{challenge}}: {{score}} очков, медаль — {{medal}}',
            ua: '{{challenge}}: {{score}} очок, медаль — {{medal}}',
            en: '{{challenge}}: {{score}} points, medal: {{medal}}',
            de: '{{challenge}}: {{score}} Punkte, Medaille: {{medal}}',
            pl: '{{challenge}}: {{score}} punktów, medal: {{medal}}',
        },
        stats: {
            ru: 'Точность {{accuracy}}% — попаданий {{hits}} из {{shots}}',
            ua: 'Точність {{accuracy}}% — влучань {{hits}} з {{shots}}',
            en: 'Accuracy {{accuracy}}% - {{hits}} hits out of {{shots}}',
            de: 'Genauigkeit {{accuracy}}% - {{hits}} Treffer von {{shots}}',
            pl: 'Celność {{accuracy}}% - {{hits}} trafień z {{shots}}',
        },
        rating: {
            ru: 'Ваш рейтинг стрельбища: {{rating}}',
            ua: 'Ваш рейтинг тиру: {{rating}}',
            en: 'Your shooting range rating: {{rating}}',
            de: 'Deine Schießstand-Wertung: {{rating}}',
            pl: 'Twój ranking strzelnicy: {{rating}}',
        },
    },
    cef: {
        shooting_range: {
            ru: 'Стрельбище',
            ua: 'Тир',
            en: 'Shooting Range',
            de: 'Schießstand',
            pl: 'Strzelnica',
        },
        description: {
            ru: 'Выберите испытание и попробуйте побить свой рекорд',
            ua: 'Оберіть випробування та спробуйте побити свій рекорд',
            en: 'Pick a challenge and try to beat your best score',
            de: 'Wähle eine Herausforderung und schlage deinen Bestwert',
            pl: 'Wybierz wyzwanie i pobij swój rekord',
        },
        challenges: {
            ru: 'Испытания',
            ua: 'Випробування',
            en: 'Challenges',
            de: 'Herausforderungen',
            pl: 'Wyzwania',
        },
        challenge: {
            ru: 'Испытание {{number}}',
            ua: 'Випробування {{number}}',
            en: 'Challenge {{number}}',
            de: 'Herausforderung {{number}}',
            pl: 'Wyzwanie {{number}}',
        },
        best_score: {
            ru: 'Рекорд',
            ua: 'Рекорд',
            en: 'Best',
            de: 'Bestwert',
            pl: 'Rekord',
        },
        accuracy: {
            ru: 'Точность',
            ua: 'Точність',
            en: 'Accuracy',
            de: 'Genauigkeit',
            pl: 'Celność',
        },
        targets: {
            ru: 'Мишени',
            ua: 'Мішені',
            en: 'Targets',
            de: 'Ziele',
            pl: 'Cele',
        },
        time_limit: {
            ru: 'Время',
            ua: 'Час',
            en: 'Time',
            de: 'Zeit',
            pl: 'Czas',
        },
        requirements: {
            ru: 'Пороги медалей',
            ua: 'Пороги медалей',
            en: 'Medal thresholds',
            de: 'Medaillen-Schwellen',
            pl: 'Progi medali',
        },
        price: {
            ru: 'Стоимость',
            ua: 'Вартість',
            en: 'Entry fee',
            de: 'Startgebühr',
            pl: 'Opłata',
        },
        start: {
            ru: 'Начать',
            ua: 'Почати',
            en: 'Start',
            de: 'Starten',
            pl: 'Start',
        },
        not_enough: {
            ru: 'Недостаточно наличных',
            ua: 'Недостатньо готівки',
            en: 'Not enough cash',
            de: 'Nicht genug Bargeld',
            pl: 'Za mało gotówki',
        },
        top_shooters: {
            ru: 'Лучшие стрелки',
            ua: 'Кращі стрілки',
            en: 'Top Shooters',
            de: 'Beste Schützen',
            pl: 'Najlepsi strzelcy',
        },
        you: {
            ru: 'Вы',
            ua: 'Ви',
            en: 'You',
            de: 'Du',
            pl: 'Ty',
        },
        no_record: {
            ru: 'Нет результата',
            ua: 'Немає результату',
            en: 'No score yet',
            de: 'Noch kein Ergebnis',
            pl: 'Brak wyniku',
        },
        seconds: {
            ru: '{{value}} с',
            ua: '{{value}} с',
            en: '{{value}}s',
            de: '{{value}} s',
            pl: '{{value}} s',
        },
        rating: {
            ru: 'Рейтинг',
            ua: 'Рейтинг',
            en: 'Rating',
            de: 'Wertung',
            pl: 'Ranking',
        },
        unranked: {
            ru: 'Без места',
            ua: 'Без місця',
            en: 'Unranked',
            de: 'Ohne Platz',
            pl: 'Bez miejsca',
        },
        no_players: {
            ru: 'Пока никто не проходил испытания',
            ua: 'Поки ніхто не проходив випробування',
            en: 'Nobody has run a challenge yet',
            de: 'Noch hat niemand eine Herausforderung gespielt',
            pl: 'Nikt jeszcze nie ukończył wyzwania',
        },
        bronze: {
            ru: 'Бронза',
            ua: 'Бронза',
            en: 'Bronze',
            de: 'Bronze',
            pl: 'Brąz',
        },
        silver: {
            ru: 'Серебро',
            ua: 'Срібло',
            en: 'Silver',
            de: 'Silber',
            pl: 'Srebro',
        },
        gold: {
            ru: 'Золото',
            ua: 'Золото',
            en: 'Gold',
            de: 'Gold',
            pl: 'Złoto',
        },
    },
};
