export default {
    takeKnifeToHands: {
        ru: 'Возьмите нож в руки',
        ua: 'Візьміть ніж у руки',
        en: 'Take the knife in your hands',
        de: 'Nehmen Sie das Messer in die Hand',
        pl: 'Weź nóż do rąk',
        zh: '把刀拿在手里',
    },
    interaction: {
        ru: 'Разделать животное',
        ua: 'Обробити тварину',
        en: 'Field dress the animal',
        de: 'Das Tier ausweiden',
        pl: 'Oskórować zwierzę',
        zh: '野外处理动物',
    },
    animalArea: {
        ru: 'Зона охоты',
        ua: 'Зона полювання',
        en: 'Hunting Zone',
        de: 'Jagdzonen',
        pl: 'Strefa polowań',
        zh: '狩猎区',
    },
    inventoryFull: {
        ru: 'Недостаточно места в инвентаре',
        ua: 'Недостатньо місця в інвентарі',
        en: 'Not enough space in the inventory',
        de: 'Nicht genug Platz im Inventar',
        pl: 'Niewystarczająca ilość miejsca w ekwipunku',
        zh: '背包空间不足',
    },
    killedByVehicle: {
        ru: 'Эта тушка была повреждена машиной, поэтому не может быть обработана',
        ua: 'Ця туша була пошкоджена машиною, тому не може бути оброблена',
        en: 'This carcass was damaged by a vehicle and cannot be processed',
        de: 'Dieses Tier wurde von einem Fahrzeug beschädigt und kann nicht verarbeitet werden',
        pl: 'Ta tusza została uszkodzona przez pojazd i nie może zostać przetworzona',
        zh: '这具动物尸体被车辆损坏，无法处理',
    },
    someoneAnotherPickUp: {
        ru: 'Кто-то другой обрабатывает это животное',
        ua: 'Хтось інший обробляє цю тварину',
        en: 'Someone else is handling this animal',
        de: 'Jemand anderes kümmert sich um dieses Tier',
        pl: 'Ktoś inny zajmuje się tym zwierzęciem',
        zh: '有人在处理这个动物',
    },
};
