export default {
    deliveryJobDailyQuest: {
        name: {
            ru: 'Пора доставить пиццу',
            ua: 'Час доставити піцу',
            en: 'Time to Deliver Pizza',
            de: 'Zeit, Pizza zu liefern',
            pl: 'Czas dostarczyć pizzę',
            zh: '是时候送披萨了',
        },
        desc: {
            ru: 'Почему бы сегодня тебе не доставить {{amount}} пицц голодным заказчикам, чем побыстрее! Ещё и получить за это награду сверху, как по мне отличная идея',
            ua: 'Чому б тобі сьогодні не доставити {{amount}} піц голодним замовникам, якомога швидше! Ще й отримати за це нагороду зверху, як на мене чудова ідея',
            en: 'Why not deliver {{amount}} pizzas to hungry customers today, as fast as possible! And get a reward on top of that, sounds like a great idea to me',
            de: 'Warum lieferst du heute nicht {{amount}} Pizzen an hungrige Kunden? Und dafür auch noch eine Belohnung bekommen, klingt für mich nach einer großartigen Idee',
            pl: 'Dlaczego nie dostarczyć dziś {{amount}} pizz głodnym klientom, jak najszybciej! A do tego jeszcze dostać nagrodę, dla mnie to świetny pomysł',
            zh: '为什么不今天就把{{amount}}披萨送到饥饿的顾客手中，越快越好!除此之外还能得到奖励，我觉得这主意不错',
        },
    },
    farmJobDailyQuest: {
        name: {
            ru: 'Яблочная страда',
            ua: 'Яблучний врожай',
            en: 'Apple Harvest Hustle',
            de: 'Apfelernte-Rummel',
            pl: 'Zbiór Jabłek',
            zh: '收苹果',
        },
        desc: {
            ru: 'Время яблочного урожая! Собери {{amount}} корзин с яблоками, чтобы приготовить яблочный пирог для всей деревни. Стань героем сезона и получи заслуженную награду!',
            ua: 'Час яблучного врожаю! Збери {{amount}} кошиків з яблуками, щоб приготувати яблучний пиріг для всього села. Стань героєм сезону та отримай заслужену нагороду!',
            en: "It's apple harvest time! Gather {{amount}} baskets of apples to bake a pie for the whole village. Become the hero of the season and earn a well-deserved reward!",
            de: 'Zeit Äpfel zu ernten! Sammle {{amount}} Körbe voll mit Äpfeln, um einen Kuchen für das ganze Dorf zu backen. Werde zum Helden der Saison und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Czas na zbiór jabłek! Zbierz {{amount}} koszy jabłek, aby upiec ciasto dla całej wioski. Zostań bohaterem sezonu i zdobądź zasłużoną nagrodę!',
            zh: '苹果收获季节到了!收集{{amount}}篮苹果，为全村烤一个馅饼。成为本赛季的英雄，并获得当之无愧的奖励',
        },
    },
    meetDailyQuest: {
        name: {
            ru: 'Новые знакомства',
            ua: 'Нові знайомства',
            en: 'New Encounters',
            de: 'Neue Bekanntschaften',
            pl: 'Nowe Spotkania',
            zh: '新接触',
        },
        desc: {
            ru: 'Познакомься с {{amount}} новыми игроками и узнай больше о них. Возможно, они поделятся с тобой полезной информацией или предложат совместные приключения. Заводи новые знакомства и расширяй свой круг общения!',
            ua: 'Познайомся з {{amount}} новими гравцями та дізнайся більше про них. Можливо, вони поділяться з тобою корисною інформацією або запропонують спільні пригоди. Заводь нові знайомства та розширюй свій круг спілкування!',
            en: 'Get to know {{amount}} new players and learn more about them. They might share useful information or suggest joint adventures. Make new friends and expand your social circle!',
            de: 'Lerne {{amount}} neue Spieler kennen und erfahre mehr über sie. Vielleicht teilen sie nützliche Informationen mit dir oder schlagen gemeinsame Abenteuer vor.',
            pl: 'Poznaj {{amount}} nowych graczy i dowiedz się o nich więcej. Mogą podzielić się z tobą przydatnymi informacjami lub zaproponować wspólne przygody. Zawieraj nowe znajomości i poszerzaj swoje kręgi towarzyskie!',
            zh: '了解{{amount}}新玩家并了解更多关于他们的信息。他们可能会分享有用的信息或建议共同冒险。结交新朋友，扩大你的社交圈',
        },
    },
    truckerJobDailyQuest: {
        name: {
            ru: 'Большая доставка',
            ua: 'Велика доставка',
            en: 'Big Haul',
            de: 'Große Lieferung',
            pl: 'Duży transport',
            zh: '一大网鱼',
        },
        desc: {
            ru: 'Сегодня твоя цель - заработать ${{goal}}, работая грузоперевозчиком. Доставляй грузы в целости и сохранности, и пусть твоя фура всегда будет на ходу. Заработай заслуженную награду за свои труды!',
            ua: 'Сьогодні твоя мета - заробити ${{goal}}, працюючи вантажоперевізником. Доставляй вантажі в цілості й схоронності, і нехай твоя фура завжди буде на ходу. Зароби заслужену нагороду за свої труди!',
            en: 'Your goal today is to earn ${{goal}} working as a trucker. Deliver your loads safely and keep your truck running smoothly. Earn your well-deserved reward for your hard work!',
            de: 'Dein Ziel heute ist es, ${{goal}} zu verdienen, indem du als Lkw-Fahrer arbeitest. Liefere deine Ladungen sicher ab und halte deinen Lkw reibungslos am Laufen. Verdiene dir deine wohlverdiente Belohnung für deine harte Arbeit!',
            pl: 'Twoim celem na dziś jest zarobienie ${{goal}}, pracując jako kierowca ciężarówki. Dostarczaj ładunki bezpiecznie i utrzymuj swoją ciężarówkę w dobrym stanie. Zarób zasłużoną nagrodę za swoją ciężką pracę!',
            zh: '你今天的目标是赚${{目标}}作为一名卡车司机。安全运送货物，保持卡车平稳运行。为你的辛勤工作赢得应得的回报!',
        },
    },
    trucker2JobDailyQuest: {
        name: {
            ru: 'Магистральный рейд',
            ua: 'Магістральний рейд',
            en: 'Highway Hustle',
            de: 'Autobahn-Tour',
            pl: 'Autostradowy rajd',
            zh: '高速公路拥挤',
        },
        desc: {
            ru: 'Твоя задача - заработать ${{goal}}, работая дальнобойщиком. Проедь сотни километров, доставляя грузы в целости и сохранности. Покажи свой профессионализм и получи заслуженную награду!',
            ua: 'Твоє завдання - заробити ${{goal}}, працюючи далекобійником. Проїдь сотні кілометрів, доставляючи вантажі в цілості й схоронності. Покажи свій професіоналізм і отримай заслужену нагороду!',
            en: 'Your goal is to earn ${{goal}} working as a trucker. Drive hundreds of miles, delivering loads safely. Show your professionalism and earn your well-deserved reward!',
            de: 'Dein Ziel ist es, ${{goal}} zu verdienen, indem du als Fernfahrer arbeitest. Fahre Hunderte von Kilometern und liefere die Ladungen sicher ab. Zeige dein Können und verdiene dir deine wohlverdiente Belohnung!',
            pl: 'Twoim celem jest zarobienie ${{goal}}, pracując jako kierowca ciężarówki na długich trasach. Przejedź setki kilometrów, dostarczając ładunki bezpiecznie. Pokaż swój profesjonalizm i zdobądź zasłużoną nagrodę!',
            zh: '你的目标是挣${{目标}},作为一个卡车司机。行驶数百英里，安全地运送货物。展现你的专业精神，赢得你应得的奖励',
        },
    },
    spinLuckyWheelDailyQuest: {
        name: {
            ru: 'Испытай удачу',
            ua: 'Випробуй удачу',
            en: 'Try Your Luck',
            de: 'Versuch dein Glück',
            pl: 'Spróbuj szczęścia',
            zh: '试试运气',
        },
        desc: {
            ru: 'Почему бы тебе не испытать удачу и не покрутить колесо фортуны сегодня? У тебя есть шанс выиграть удивительные призы. Пусть фортуна будет на твоей стороне!',
            ua: 'Чому б тобі не випробувати удачу і не покрутити колесо фортуни сьогодні? У тебе є шанс виграти дивовижні призи. Нехай фортуна буде на твоєму боці!',
            en: 'Why not try your luck and spin the lucky wheel today? You have a chance to win amazing prizes. May fortune be on your side!',
            de: 'Warum versuchst du nicht dein Glück und drehst heute am Glücksrad? Du hast die Chance, tolle Preise zu gewinnen. Möge das Glück auf deiner Seite sein!',
            pl: 'Dlaczego by nie spróbować szczęścia i zakręcić kołem fortuny dzisiaj? Masz szansę wygrać niesamowite nagrody. Niech szczęście będzie po twojej stronie!',
            zh: '今天何不试试运气，转一下幸运轮呢?你有机会赢得惊人的奖品。愿好运在你身边',
        },
    },
    playRouletteDailyQuest: {
        name: {
            ru: 'Рулетка удачи',
            ua: 'Рулетка удачі',
            en: 'Roulette Luck',
            de: 'Roulette-Glück',
            pl: 'Ruletka szczęścia',
            zh: '轮盘赌运气',
        },
        desc: {
            ru: 'Почему бы тебе не испытать удачу и не сыграть в рулетку на сумму {{amount}} фишек? У тебя есть шанс выиграть крупные призы и насладиться азартом игры. Пусть удача будет на твоей стороне!',
            ua: 'Чому б тобі не випробувати удачу і не зіграти в рулетку на суму {{amount}} фішок? У тебе є шанс виграти великі призи і насолодитися азартом гри. Нехай удача буде на твоєму боці!',
            en: 'Why not try your luck and play roulette for {{amount}} chips? You have a chance to win big prizes and enjoy the thrill of the game. May luck be on your side!',
            de: 'Warum versuchst du nicht dein Glück und spielst Roulette mit {{amount}} Chips? Du hast die Chance, große Preise zu gewinnen und den Nervenkitzel des Spiels zu genießen. Möge das Glück auf deiner Seite sein!',
            pl: 'Dlaczego by nie spróbować szczęścia i zagrać w ruletkę za {{amount}} żetonów? Masz szansę wygrać wielkie nagrody i cieszyć się dreszczykiem emocji. Niech szczęście będzie po twojej stronie!',
            zh: '为什么不试试你的运气和玩轮盘赌{{amount}}筹码?你有机会赢得大奖，享受游戏的刺激。愿好运站在你这边',
        },
    },
    transferMoneyDailyQuest: {
        name: {
            ru: 'Щедрый даритель',
            ua: 'Щедрий дарувальник',
            en: 'Generous Giver',
            de: 'Großzügiger Geber',
            pl: 'Hojny dawca',
            zh: '慷慨的给予者',
        },
        desc: {
            ru: 'Почему бы тебе не передать наличные {{count}} людям на сумму ${{amount}}? Помоги другим и получи заслуженную награду!',
            ua: 'Чому б тобі не передати готівку {{count}} людям на суму ${{amount}}? Допоможи іншим і отримай заслужену нагороду!',
            en: 'Why not hand over cash to {{count}} people totaling ${{amount}}? Help others and earn a well-deserved reward!',
            de: 'Warum übergibst du nicht {{count}} Menschen Bargeld in Höhe von ${{amount}}? Hilf anderen und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Dlaczego by nie przekazać gotówki {{count}} ludziom na sumę ${{amount}}? Pomóż innym i zdobądź zasłużoną nagrodę!',
            zh: '为什么不把现金交给{{count}}人总计${{amount}}?帮助他人，获得应得的回报',
        },
    },
    busmanJobDailyQuest: {
        name: {
            ru: 'Автобусный магнат',
            ua: 'Автобусний магнат',
            en: 'Bus Baron',
            de: 'Bus-Fahrer',
            pl: 'Autobusowy Magnat',
            zh: '公交大亨',
        },
        desc: {
            ru: 'Почему бы тебе не попробовать заработать ${{goal}}, работая водителем автобуса? Перевози пассажиров, следуй маршрутам и покажи свои навыки за рулём. Получи заслуженную награду за свою работу!',
            ua: 'Чому б тобі не спробувати заробити ${{goal}}, працюючи водієм автобуса? Перевозь пасажирів, слідуй маршрутам і покажи свої навички за кермом. Отримай заслужену нагороду за свою роботу!',
            en: 'Why not try to earn ${{goal}} working as a bus driver? Transport passengers, follow routes, and showcase your driving skills. Earn a well-deserved reward for your efforts!',
            de: 'Warum versuchst du nicht, ${{goal}} zu verdienen, indem du als Busfahrer arbeitest? Transportiere Passagiere, folge den Routen und zeige deine Fahrkünste. Verdiene dir eine wohlverdiente Belohnung für deine Mühe!',
            pl: 'Dlaczego by nie spróbować zarobić ${{goal}}, pracując jako kierowca autobusu? Przewoź pasażerów, przestrzegaj tras i pokaż swoje umiejętności jazdy. Zdobądź zasłużoną nagrodę za swoje wysiłki!',
            zh: '为什么不尝试挣${{目标}}作为一个公共汽车司机?运送乘客，跟随路线，并展示您的驾驶技能。为你的努力获得当之无愧的回报',
        },
    },
    playSlotsDailyQuest: {
        name: {
            ru: 'Играй в слоты',
            ua: 'Грай в слоти',
            en: 'Slot Machine Fun',
            de: 'Spielautomaten-Spaß',
            pl: 'Gra na automatach',
            zh: '老虎机',
        },
        desc: {
            ru: 'Почему бы тебе не испытать удачу и не сыграть в слоты на сумму ${{amount}} фишек? У тебя есть шанс выиграть большие призы и насладиться азартом игры. Пусть удача будет на твоей стороне!',
            ua: 'Чому б тобі не випробувати удачу і не зіграти в слоти на суму ${{amount}} фішок? У тебе є шанс виграти великі призи і насолодитися азартом гри. Нехай удача буде на твоєму боці!',
            en: 'Why not try your luck and play the slots for ${{amount}} chips? You have a chance to win big prizes and enjoy the thrill of the game. May luck be on your side!',
            de: 'Warum versuchst du nicht dein Glück und spielst ${{amount}} Chips an den Spielautomaten? Du hast die Chance, große Preise zu gewinnen und den Nervenkitzel des Spiels zu genießen. Möge das Glück auf deiner Seite sein!',
            pl: 'Dlaczego by nie spróbować szczęścia i zagrać na automatach za ${{amount}} żetonów? Masz szansę wygrać wielkie nagrody i cieszyć się dreszczykiem emocji. Niech szczęście będzie po twojej stronie!',
            zh: '为什么不试试你的运气和玩老虎机${{amount}}筹码?你有机会赢得大奖，享受游戏的刺激。愿好运站在你这边',
        },
    },
    playSlotsDailyQuest: {
        name: {
            ru: 'Играй в слоты',
            ua: 'Грай в слоти',
            en: 'Slot Machine Fun',
            de: 'Spielautomaten-Spaß',
            pl: 'Gra na automatach',
            zh: '老虎机',
        },
        desc: {
            ru: 'Почему бы тебе не испытать удачу и не сыграть в слоты на сумму {{amount}} фишек? У тебя есть шанс выиграть большие призы и насладиться азартом игры. Пусть удача будет на твоей стороне!',
            ua: 'Чому б тобі не випробувати удачу і не зіграти в слоти на суму {{amount}} фішок? У тебе є шанс виграти великі призи і насолодитися азартом гри. Нехай удача буде на твоєму боці!',
            en: 'Why not try your luck and play the slots for {{amount}} chips? You have a chance to win big prizes and enjoy the thrill of the game. May luck be on your side!',
            de: 'Warum versuchst du nicht dein Glück und spielst {{amount}} Chips an den Spielautomaten? Du hast die Chance, große Preise zu gewinnen und den Nervenkitzel des Spiels zu genießen. Möge das Glück auf deiner Seite sein!',
            pl: 'Dlaczego by nie spróbować szczęścia i zagrać na automatach za {{amount}} żetonów? Masz szansę wygrać wielkie nagrody i cieszyć się dreszczykiem emocji. Niech szczęście będzie po twojej stronie!',
            zh: '为什么不试试你的运气，玩{{amount}}筹码的老虎机呢?你有机会赢得大奖，享受游戏的刺激。愿好运站在你这边',
        },
    },
    shoppingClothesDailyQuest: {
        name: {
            ru: 'Модный шопинг',
            ua: 'Модний шопінг',
            en: 'Fashion Shopping',
            de: 'Mode-Shopping',
            pl: 'Zakupy modowe',
            zh: '风尚购物',
        },
        desc: {
            ru: 'Почему бы тебе не отправиться на шопинг и не потратить ${{goal}} на новую одежду? Обнови свой гардероб и получи за это заслуженную награду!',
            ua: 'Чому б тобі не вирушити на шопінг і не витратити ${{goal}} на новий одяг? Онови свій гардероб і отримай за це заслужену нагороду!',
            en: 'Why not go shopping and spend ${{goal}} on new clothes? Update your wardrobe and earn a well-deserved reward!',
            de: 'Warum gehst du nicht shoppen und gibst ${{goal}} für neue Kleidung aus? Aktualisiere deine Garderobe und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Dlaczego by nie wybrać się na zakupy i wydać ${{goal}} na nowe ubrania? Odśwież swoją garderobę i zdobądź zasłużoną nagrodę!',
            zh: '为什么不去购物，花{{goal}}美元买新衣服呢?更新你的衣橱，获得当之无愧的奖励',
        },
    },
    shoppingGunStoreDailyQuest: {
        name: {
            ru: 'Оружейный шопинг',
            ua: 'Зброєвий шопінг',
            en: 'Gun Store Shopping',
            de: 'Waffenladen-Einkauf',
            pl: 'Zakupy w sklepie z bronią',
            zh: '武装国度购物',
        },
        desc: {
            ru: 'Почему бы тебе не потратить ${{goal}} на покупку чего угодно в оружейном магазине? Пройдись по магазинам, выбери необходимое снаряжение и пополни свой арсенал. Получи заслуженную награду за свои покупки!',
            ua: 'Чому б тобі не витратити ${{goal}} на покупку чого завгодно у зброярні? Пройдися по магазинах, вибери необхідне спорядження та поповни свій арсенал. Отримай заслужену нагороду за свої покупки!',
            en: 'Why not spend ${{goal}} on anything at the gun store? Browse the shops, pick up the necessary gear, and expand your arsenal. Earn a well-deserved reward for your purchases!',
            de: 'Warum gibst du nicht ${{goal}} im Waffenladen aus? Durchstöbere die Läden, kaufe die notwendige Ausrüstung und erweitere dein Arsenal. Verdiene dir eine wohlverdiente Belohnung für deine Einkäufe!',
            pl: 'Dlaczego by nie wydać ${{goal}} na cokolwiek w sklepie z bronią? Przejrzyj sklepy, wybierz niezbędny sprzęt i rozbuduj swój arsenał. Zdobądź zasłużoną nagrodę za swoje zakupy!',
            zh: '为什么不花${{goal}}在枪支店买东西呢?浏览商店，挑选必要的装备，并扩大你的武器库。为您的购买获得当之无愧的奖励!',
        },
    },
    buyInCasinoBarDailyQuest: {
        name: {
            ru: 'Коктейль в казино',
            ua: 'Коктейль у казино',
            en: 'Casino Cocktail',
            de: 'Casino-Cocktail',
            pl: 'Koktajl w kasynie',
            zh: '赌场酒吧',
        },
        desc: {
            ru: 'Зайди в бар казино и купи что-нибудь вкусное. Напиток или закуска помогут тебе расслабиться и насладиться атмосферой. Получи награду за свои покупки!',
            ua: 'Зайди в бар казино і купи щось смачне. Напій чи закуска допоможуть тобі розслабитися та насолодитися атмосферою. Отримай нагороду за свої покупки!',
            en: 'Visit the casino bar and buy something tasty. A drink or a snack will help you relax and enjoy the atmosphere. Earn a reward for your purchases!',
            de: 'Besuche die Casino-Bar und kaufe etwas Leckeres. Ein Getränk oder ein Snack helfen dir, zu entspannen und die Atmosphäre zu genießen. Verdiene eine Belohnung für deine Einkäufe!',
            pl: 'Odwiedź bar w kasynie i kup coś smacznego. Napój lub przekąska pomogą ci się zrelaksować i cieszyć atmosferą. Zdobywaj nagrody za swoje zakupy!',
            zh: '去赌场酒吧买些好吃的。一杯饮料或零食会帮助你放松，享受气氛。为你的购买获得奖励',
        },
    },
    drinkVodkaDailyQuest: {
        name: {
            ru: 'Водочный марафон',
            ua: 'Горілчаний марафон',
            en: 'Vodka Marathon',
            de: 'Wodka-Marathon',
            pl: 'Wódka-maraton',
            zh: '伏特加马拉松',
        },
        desc: {
            ru: 'Смело выпей {{amount}} порций водки и покажи свою стойкость. Докажи, что можешь выдержать настоящий водочный марафон и получи за это заслуженную награду!',
            ua: 'Сміливо випий {{amount}} порцій горілки та покажи свою витримку. Доведи, що можеш витримати справжній горілчаний марафон та отримай за це заслужену нагороду!',
            en: 'Bravely drink {{amount}} servings of vodka and show your resilience. Prove you can handle a real vodka marathon and earn a well-deserved reward!',
            de: 'Trinke mutig {{amount}} Portionen Wodka und zeige deine Ausdauer. Beweise, dass du einen echten Wodka-Marathon durchstehen kannst und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Śmiało wypij {{amount}} porcje wódki i pokaż swoją wytrzymałość. Udowodnij, że potrafisz przetrwać prawdziwy wódka-maraton i zdobądź zasłużoną nagrodę!',
            zh: '勇敢地喝下{{amount}}份伏特加，展现你的韧性。证明你可以驾驭真正的伏特加马拉松，并获得当之无愧的奖励!',
        },
    },
    fishingAtDawnDailyQuest: {
        name: {
            ru: 'Рыбалка на рассвете',
            ua: 'Рибалка на світанку',
            en: 'Fishing at Dawn',
            de: 'Angeln im Morgengrauen',
            pl: 'Wędkowanie o świcie',
            zh: '捕鱼',
        },
        desc: {
            ru: 'Начни свой день с рыбалки на рассвете! Поймай {{amount}} рыб, наслаждаясь красотой природы и тишиной утренних вод. Получи заслуженную награду за свой ранний подъем!',
            ua: 'Розпочни свій день рибалкою на світанку! Злови {{amount}} риб, насолоджуючись красою природи та тишею ранкових вод. Отримай заслужену нагороду за свій ранній підйом!',
            en: 'Start your day with fishing at dawn! Catch {{amount}} fish while enjoying the beauty of nature and the tranquility of the morning waters. Earn a well-deserved reward for your early rise!',
            de: 'Beginne deinen Tag mit Angeln im Morgengrauen! Fange {{amount}} Fische und genieße die Schönheit der Natur und die Ruhe der morgendlichen Gewässer. Verdiene eine wohlverdiente Belohnung für dein frühes Aufstehen!',
            pl: 'Rozpocznij dzień od wędkowania o świcie! Złap {{amount}} ryb, ciesząc się pięknem natury i spokojem porannych wód. Zdobądź zasłużoną nagrodę za wczesne wstawanie!',
            zh: '在黎明钓鱼开始你的一天!在享受大自然的美丽和早晨水域的宁静的同时，捕捉{{数量}}条鱼。为你的早起得到了应得的奖励!',
        },
    },
    fishingChallengeDailyQuest: {
        name: {
            ru: 'Рыбный вызов',
            ua: 'Рибний виклик',
            en: 'Fishing Challenge',
            de: 'Angeln-Herausforderung',
            pl: 'Wyzwanie wędkarskie',
            zh: '钓鱼挑战',
        },
        desc: {
            ru: 'Готов к рыбацкому вызову? Поймай {{amount}} раз рыбу определенного вида и докажи, что ты настоящий мастер рыбалки! Вперед к берегу за приключениями и заслуженной наградой!',
            ua: 'Готовий до рибальського виклику? Злови {{amount}} разів рибу певного виду і доведи, що ти справжній майстер риболовлі! Вперед до берега за пригодами та заслуженою нагородою!',
            en: "Ready for a fishing challenge? Catch {{amount}} times a specific type of fish and prove you're a true fishing master! Head to the shore for adventure and a well-deserved reward!",
            de: 'Bereit für eine Angelherausforderung? Fange {{amount}} Mal einen bestimmten Fisch und beweise, dass du ein wahrer Angelmeister bist! Auf zum Ufer für Abenteuer und eine wohlverdiente Belohnung!',
            pl: 'Gotowy na wyzwanie wędkarskie? Złap {{amount}} razy rybę określonego gatunku i udowodnij, że jesteś prawdziwym mistrzem wędkowania! Ruszaj na brzeg po przygodę i zasłużoną nagrodę!',
            zh: '准备好挑战钓鱼了吗?捕获{{数量}}倍的特定类型的鱼，并证明你是一个真正的钓鱼大师!前往海岸探险和当之无愧的奖励',
        },
    },
    dailyAnimalHuntQuest: {
        name: {
            ru: 'Дикая охота',
            ua: 'Дике полювання',
            en: 'Wild Hunt',
            de: 'Wilde Jagd',
            pl: 'Dzika polowanie',
            zh: '疯狂打猎',
        },
        desc: {
            ru: 'Сегодня тебе предстоит стать настоящим охотником! Поймай {{amount}} животных и докажи, что дикая природа тебе по плечу. Стань легендой лесов и получи заслуженную награду!',
            ua: 'Сьогодні ти маєш стати справжнім мисливцем! Злови {{amount}} тварин і доведи, що дика природа тобі під силу. Стань легендою лісів та отримай заслужену нагороду!',
            en: 'Today, you must become a true hunter! Catch {{amount}} animals and prove that the wild is your domain. Become a legend of the forests and earn a well-deserved reward!',
            de: 'Heute musst du ein wahrer Jäger werden! Fange {{amount}} Tiere und beweise, dass die Wildnis dein Revier ist. Werde zur Legende der Wälder und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Dziś musisz zostać prawdziwym myśliwym! Złap {{amount}} zwierząt i udowodnij, że dzika przyroda to twoje terytorium. Zostań legendą lasów i zdobądź zasłużoną nagrodę!',
            zh: '今天，你必须成为一个真正的猎人!捕捉{{amount}}动物，证明野生是你的领地。成为森林传奇，并获得应得的奖励!',
        },
    },
    plantFarmDailyQuest: {
        name: {
            ru: 'Грядка в деле',
            ua: 'Грядка в ділі',
            en: 'Plot in Action',
            de: 'Beet im Einsatz',
            pl: 'Grządka w akcji',
            zh: '田地行动',
        },
        desc: {
            ru: 'Твой огород ждёт действий! Посади, вырасти и собери урожай {{count}} раз на ферме, чтобы доказать, что ты настоящий фермер. За усердие тебя ждёт заслуженная награда!',
            ua: 'Твій город чекає на дії! Посади, вирости та збері врожай {{count}} разів на фермі, щоб довести, що ти справжній фермер. За старанність на тебе чекає заслужена нагорода!',
            en: 'Your plot is ready for action! Plant, grow, and harvest {{count}} times on the farm to prove you’re a true farmer. A well-deserved reward awaits you for your hard work!',
            de: 'Dein Beet ist bereit für den Einsatz! Pflanze, pflege und ernte {{count}} Mal auf dem Bauernhof, um zu beweisen, dass du ein wahrer Bauer bist. Für deine Mühe wartet eine wohlverdiente Belohnung auf dich!',
            pl: 'Twoja grządka czeka na akcję! Posadź, wyhoduj i zbierz plony {{count}} razy na farmie, aby udowodnić, że jesteś prawdziwym rolnikiem. Zasłużona nagroda czeka na ciebie za ciężką pracę!',
            zh: '你的田地准备行动了！种植、培育并收获{{count}}次，以证明你是一个真正的农夫。你的辛勤劳动将获得应得的奖励！',
        },
    },
    waterPlantsDailyQuest: {
        name: {
            ru: 'Лейка в бой',
            ua: 'Лійка в бій',
            en: 'Watering Duty',
            de: 'Gießkanne im Einsatz',
            pl: 'Podlej i ruszaj',
            zh: '浇水行动',
        },
        desc: {
            ru: 'Твои растения жаждут внимания! Полей {{count}} раз любые растения на ферме и убедись, что урожай будет сочным. За заботу тебя ждёт заслуженная награда!',
            ua: 'Твої рослини потребують уваги! Полий {{count}} разів будь-які рослини на фермі та переконайся, що врожай буде соковитим. За турботу на тебе чекає заслужена нагорода!',
            en: 'Your plants are thirsty for attention! Water any plants on the farm {{count}} times and ensure your harvest will be plentiful. A well-deserved reward awaits you for your care!',
            de: 'Deine Pflanzen dürsten nach Aufmerksamkeit! Gieße {{count}} Mal beliebige Pflanzen auf dem Bauernhof und sorge dafür, dass deine Ernte saftig wird. Für deine Fürsorge wartet eine wohlverdiente Belohnung auf dich!',
            pl: 'Twoje rośliny potrzebują uwagi! Podlej {{count}} razy dowolne rośliny na farmie i upewnij się, że plony będą obfite. Zasłużona nagroda czeka na ciebie za opiekę!',
            zh: '你的植物渴望关注！在农场浇水{{count}}次，确保你的收成丰富。你的细心照料将得到应得的回报！',
        },
    },
};
