export default {
    deliveryJobDailyQuest: {
        name: {
            ru: 'Время доставки еды',
            ua: 'Час доставки їжі',
            en: 'Food Delivery Time',
            de: 'Zeit für Essenslieferungen',
            pl: 'Czas na dostawę jedzenia',
            zh: '是时候送餐了',
        },
        desc: {
            ru: 'Почему бы сегодня тебе не доставить {{amount}} заказов еды голодным клиентам, да побыстрее? Ещё и получить за это награду сверху, как по мне отличная идея.',
            ua: 'Чому б тобі сьогодні не доставити {{amount}} замовлень їжі голодним клієнтам, та ще й якнайшвидше? Ще й отримати за це нагороду зверху, як на мене чудова ідея.',
            en: 'Why not deliver {{amount}} food orders to hungry customers today, as fast as possible? And get an extra reward on top of that. Sounds like a great idea to me.',
            de: 'Warum lieferst du heute nicht {{amount}} Essensbestellungen an hungrige Kunden, und zwar so schnell wie möglich? Obendrauf gibt es noch eine Belohnung. Klingt nach einer großartigen Idee.',
            pl: 'Dlaczego nie dostarczyć dziś {{amount}} zamówień jedzenia głodnym klientom, i to jak najszybciej? Do tego jeszcze zgarniesz dodatkową nagrodę. Brzmi jak świetny pomysł.',
            zh: '不如今天尽快把{{amount}}份餐食订单送到饥饿的顾客手中？而且还能额外获得奖励。我觉得这主意不错。',
        },
    },
    farmJobDailyQuest: {
        name: {
            ru: 'Яблочная страда',
            ua: 'Яблучний врожай',
            en: 'Apple Harvest Hustle',
            de: 'Apfelernte-Rummel',
            pl: 'Zbiór Jabłek',
            zh: '收苹果',
        },
        desc: {
            ru: 'Время яблочного урожая! Собери {{amount}} корзин с яблоками, чтобы приготовить яблочный пирог для всей деревни. Стань героем сезона и получи заслуженную награду!',
            ua: 'Час яблучного врожаю! Збери {{amount}} кошиків з яблуками, щоб приготувати яблучний пиріг для всього села. Стань героєм сезону та отримай заслужену нагороду!',
            en: "It's apple harvest time! Gather {{amount}} baskets of apples to bake a pie for the whole village. Become the hero of the season and earn a well-deserved reward!",
            de: 'Zeit Äpfel zu ernten! Sammle {{amount}} Körbe voll mit Äpfeln, um einen Kuchen für das ganze Dorf zu backen. Werde zum Helden der Saison und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Czas na zbiór jabłek! Zbierz {{amount}} koszy jabłek, aby upiec ciasto dla całej wioski. Zostań bohaterem sezonu i zdobądź zasłużoną nagrodę!',
            zh: '苹果收获季节到了!收集{{amount}}篮苹果，为全村烤一个馅饼。成为本赛季的英雄，并获得当之无愧的奖励',
        },
    },
    meetDailyQuest: {
        name: {
            ru: 'Новые знакомства',
            ua: 'Нові знайомства',
            en: 'New Encounters',
            de: 'Neue Bekanntschaften',
            pl: 'Nowe Spotkania',
            zh: '新接触',
        },
        desc: {
            ru: 'Познакомься с {{amount}} новыми игроками и узнай больше о них. Возможно, они поделятся с тобой полезной информацией или предложат совместные приключения. Заводи новые знакомства и расширяй свой круг общения!',
            ua: 'Познайомся з {{amount}} новими гравцями та дізнайся більше про них. Можливо, вони поділяться з тобою корисною інформацією або запропонують спільні пригоди. Заводь нові знайомства та розширюй свій круг спілкування!',
            en: 'Get to know {{amount}} new players and learn more about them. They might share useful information or suggest joint adventures. Make new friends and expand your social circle!',
            de: 'Lerne {{amount}} neue Spieler kennen und erfahre mehr über sie. Vielleicht teilen sie nützliche Informationen mit dir oder schlagen gemeinsame Abenteuer vor.',
            pl: 'Poznaj {{amount}} nowych graczy i dowiedz się o nich więcej. Mogą podzielić się z tobą przydatnymi informacjami lub zaproponować wspólne przygody. Zawieraj nowe znajomości i poszerzaj swoje kręgi towarzyskie!',
            zh: '了解{{amount}}新玩家并了解更多关于他们的信息。他们可能会分享有用的信息或建议共同冒险。结交新朋友，扩大你的社交圈',
        },
    },
    truckerJobDailyQuest: {
        name: {
            ru: 'Большая доставка',
            ua: 'Велика доставка',
            en: 'Big Haul',
            de: 'Große Lieferung',
            pl: 'Duży transport',
            zh: '一大网鱼',
        },
        desc: {
            ru: 'Сегодня твоя цель - заработать ${{goal}}, работая грузоперевозчиком. Доставляй грузы в целости и сохранности, и пусть твоя фура всегда будет на ходу. Заработай заслуженную награду за свои труды!',
            ua: 'Сьогодні твоя мета - заробити ${{goal}}, працюючи вантажоперевізником. Доставляй вантажі в цілості й схоронності, і нехай твоя фура завжди буде на ходу. Зароби заслужену нагороду за свої труди!',
            en: 'Your goal today is to earn ${{goal}} working as a trucker. Deliver your loads safely and keep your truck running smoothly. Earn your well-deserved reward for your hard work!',
            de: 'Dein Ziel heute ist es, ${{goal}} zu verdienen, indem du als Lkw-Fahrer arbeitest. Liefere deine Ladungen sicher ab und halte deinen Lkw reibungslos am Laufen. Verdiene dir deine wohlverdiente Belohnung für deine harte Arbeit!',
            pl: 'Twoim celem na dziś jest zarobienie ${{goal}}, pracując jako kierowca ciężarówki. Dostarczaj ładunki bezpiecznie i utrzymuj swoją ciężarówkę w dobrym stanie. Zarób zasłużoną nagrodę za swoją ciężką pracę!',
            zh: '你今天的目标是赚${{目标}}作为一名卡车司机。安全运送货物，保持卡车平稳运行。为你的辛勤工作赢得应得的回报!',
        },
    },
    trucker2JobDailyQuest: {
        name: {
            ru: 'Магистральный рейд',
            ua: 'Магістральний рейд',
            en: 'Highway Hustle',
            de: 'Autobahn-Tour',
            pl: 'Autostradowy rajd',
            zh: '高速公路拥挤',
        },
        desc: {
            ru: 'Твоя задача - заработать ${{goal}}, работая дальнобойщиком. Проедь сотни километров, доставляя грузы в целости и сохранности. Покажи свой профессионализм и получи заслуженную награду!',
            ua: 'Твоє завдання - заробити ${{goal}}, працюючи далекобійником. Проїдь сотні кілометрів, доставляючи вантажі в цілості й схоронності. Покажи свій професіоналізм і отримай заслужену нагороду!',
            en: 'Your goal is to earn ${{goal}} working as a trucker. Drive hundreds of miles, delivering loads safely. Show your professionalism and earn your well-deserved reward!',
            de: 'Dein Ziel ist es, ${{goal}} zu verdienen, indem du als Fernfahrer arbeitest. Fahre Hunderte von Kilometern und liefere die Ladungen sicher ab. Zeige dein Können und verdiene dir deine wohlverdiente Belohnung!',
            pl: 'Twoim celem jest zarobienie ${{goal}}, pracując jako kierowca ciężarówki na długich trasach. Przejedź setki kilometrów, dostarczając ładunki bezpiecznie. Pokaż swój profesjonalizm i zdobądź zasłużoną nagrodę!',
            zh: '你的目标是挣${{目标}},作为一个卡车司机。行驶数百英里，安全地运送货物。展现你的专业精神，赢得你应得的奖励',
        },
    },
    taxiJobDailyQuest: {
        name: {
            ru: 'Такси на линии',
            ua: 'Таксі на лінії',
            en: 'Taxi Shift',
            de: 'Taxi-Schicht',
            pl: 'Zmiana taksówkarza',
        },
        desc: {
            ru: 'Пора выйти на смену и заработать ${{goal}}, выполняя заказы в такси. Быстро подбирай клиентов, довози до точки и забирай награду!',
            ua: 'Час виходити на зміну й заробити ${{goal}}, виконуючи замовлення в таксі. Швидко підбирай клієнтів, довозь до точки та забирай нагороду!',
            en: 'Time to hit your shift and earn ${{goal}} by completing taxi orders. Pick up clients quickly, deliver them safely, and claim your reward!',
            de: 'Zeit für deine Schicht: Verdiene ${{goal}}, indem du Taxiaufträge abschließt. Nimm Kunden schnell auf, bring sie sicher ans Ziel und hol dir deine Belohnung!',
            pl: 'Czas na zmianę: zarób ${{goal}}, realizując kursy taxi. Szybko odbieraj klientów, dowoź ich na miejsce i zgarnij nagrodę!',
        },
    },
    garbageJobDailyQuest: {
        name: {
            ru: 'Чистый район',
            ua: 'Чистий район',
            en: 'Clean District',
            de: 'Sauberer Bezirk',
            pl: 'Czysta dzielnica',
        },
        desc: {
            ru: 'Садись в мусоровоз и заработай ${{goal}}, вывозя мусор по маршруту. Чем чище город - тем ближе награда!',
            ua: 'Сідай у сміттєвоз і зароби ${{goal}}, вивозячи сміття за маршрутом. Чим чистіше місто - тим ближча нагорода!',
            en: 'Hop into the garbage truck and earn ${{goal}} by hauling trash along the route. The cleaner the city, the closer the reward!',
            de: 'Steig in den Müllwagen und verdiene ${{goal}}, indem du Müll auf der Route sammelst. Je sauberer die Stadt, desto näher die Belohnung!',
            pl: 'Wskakuj do śmieciarki i zarób ${{goal}}, wywożąc odpady po trasie. Im czystsze miasto, tym bliżej nagroda!',
        },
    },
    divingCollectDailyQuest: {
        name: {
            ru: 'Подводный сбор',
            ua: 'Підводний збір',
            en: 'Underwater Collect',
            de: 'Unterwasser-Sammlung',
            pl: 'Podwodny zbiór',
        },
        desc: {
            ru: 'Ныряй глубже и подними {{amount}} подводных находок. Чем больше трофеев достанешь со дна - тем ближе награда!',
            ua: 'Пірнай глибше та підніми {{amount}} підводних знахідок. Чим більше трофеїв дістанеш із дна - тим ближча нагорода!',
            en: 'Dive deeper and collect {{amount}} underwater finds. The more treasures you lift from the seabed, the closer your reward!',
            de: 'Tauche tiefer und sammle {{amount}} Unterwasserfunde. Je mehr Schätze du vom Meeresboden holst, desto näher ist deine Belohnung!',
            pl: 'Nurkuj głębiej i zbierz {{amount}} podwodnych znalezisk. Im więcej skarbów wyciągniesz z dna, tym bliżej nagroda!',
        },
    },
    mushroomsJobDailyQuest: {
        name: {
            ru: 'Грибная тропа',
            ua: 'Грибна стежка',
            en: 'Mushroom Trail',
            de: 'Pilzpfad',
            pl: 'Grzybowa ścieżka',
        },
        desc: {
            ru: 'Собери {{amount}} грибных точек, работая грибником. Проверь удачные места и забери награду за продуктивный сбор!',
            ua: 'Збери {{amount}} грибних точок, працюючи грибником. Перевір вдалi місця та забери нагороду за продуктивний збір!',
            en: 'Collect {{amount}} mushroom spots while working as a mushroom picker. Check the best places and claim your reward for a productive run!',
            de: 'Sammle {{amount}} Pilzstellen als Pilzsammler. Such die besten Orte ab und hol dir deine Belohnung für eine produktive Tour!',
            pl: 'Zbierz {{amount}} punktów grzybów, pracując jako grzybiarz. Sprawdź najlepsze miejscówki i odbierz nagrodę za udany zbiór!',
        },
    },
    treasureHunterJobDailyQuest: {
        name: {
            ru: 'Охотник за кладами',
            ua: 'Мисливець за скарбами',
            en: 'Treasure Seeker',
            de: 'Schatzjäger',
            pl: 'Łowca skarbów',
        },
        desc: {
            ru: 'Найди {{amount}} кладов, используя карты сокровищ. Копай точнее, забирай лут и получай награду!',
            ua: 'Знайди {{amount}} скарбів, використовуючи карти скарбів. Копай точніше, забирай лут і отримуй нагороду!',
            en: 'Find {{amount}} treasures using treasure maps. Dig precisely, grab the loot, and earn your reward!',
            de: 'Finde {{amount}} Schätze mit Schatzkarten. Grabe präzise, nimm die Beute mit und sichere dir deine Belohnung!',
            pl: 'Znajdź {{amount}} skarbów, używając map skarbów. Kop dokładnie, zgarnij łup i odbierz nagrodę!',
        },
    },
    spinLuckyWheelDailyQuest: {
        name: {
            ru: 'Испытай удачу',
            ua: 'Випробуй удачу',
            en: 'Try Your Luck',
            de: 'Versuch dein Glück',
            pl: 'Spróbuj szczęścia',
            zh: '试试运气',
        },
        desc: {
            ru: 'Почему бы тебе не испытать удачу и не покрутить колесо фортуны сегодня? У тебя есть шанс выиграть удивительные призы. Пусть фортуна будет на твоей стороне!',
            ua: 'Чому б тобі не випробувати удачу і не покрутити колесо фортуни сьогодні? У тебе є шанс виграти дивовижні призи. Нехай фортуна буде на твоєму боці!',
            en: 'Why not try your luck and spin the lucky wheel today? You have a chance to win amazing prizes. May fortune be on your side!',
            de: 'Warum versuchst du nicht dein Glück und drehst heute am Glücksrad? Du hast die Chance, tolle Preise zu gewinnen. Möge das Glück auf deiner Seite sein!',
            pl: 'Dlaczego by nie spróbować szczęścia i zakręcić kołem fortuny dzisiaj? Masz szansę wygrać niesamowite nagrody. Niech szczęście będzie po twojej stronie!',
            zh: '今天何不试试运气，转一下幸运轮呢?你有机会赢得惊人的奖品。愿好运在你身边',
        },
    },
    playRouletteDailyQuest: {
        name: {
            ru: 'Рулетка удачи',
            ua: 'Рулетка удачі',
            en: 'Roulette Luck',
            de: 'Roulette-Glück',
            pl: 'Ruletka szczęścia',
            zh: '轮盘赌运气',
        },
        desc: {
            ru: 'Почему бы тебе не испытать удачу и не сыграть в рулетку на сумму {{amount}} фишек? У тебя есть шанс выиграть крупные призы и насладиться азартом игры. Пусть удача будет на твоей стороне!',
            ua: 'Чому б тобі не випробувати удачу і не зіграти в рулетку на суму {{amount}} фішок? У тебе є шанс виграти великі призи і насолодитися азартом гри. Нехай удача буде на твоєму боці!',
            en: 'Why not try your luck and play roulette for {{amount}} chips? You have a chance to win big prizes and enjoy the thrill of the game. May luck be on your side!',
            de: 'Warum versuchst du nicht dein Glück und spielst Roulette mit {{amount}} Chips? Du hast die Chance, große Preise zu gewinnen und den Nervenkitzel des Spiels zu genießen. Möge das Glück auf deiner Seite sein!',
            pl: 'Dlaczego by nie spróbować szczęścia i zagrać w ruletkę za {{amount}} żetonów? Masz szansę wygrać wielkie nagrody i cieszyć się dreszczykiem emocji. Niech szczęście będzie po twojej stronie!',
            zh: '为什么不试试你的运气和玩轮盘赌{{amount}}筹码?你有机会赢得大奖，享受游戏的刺激。愿好运站在你这边',
        },
    },
    transferMoneyDailyQuest: {
        name: {
            ru: 'Щедрый даритель',
            ua: 'Щедрий дарувальник',
            en: 'Generous Giver',
            de: 'Großzügiger Geber',
            pl: 'Hojny dawca',
            zh: '慷慨的给予者',
        },
        desc: {
            ru: 'Почему бы тебе не передать наличные {{count}} людям на сумму ${{amount}}? Помоги другим и получи заслуженную награду!',
            ua: 'Чому б тобі не передати готівку {{count}} людям на суму ${{amount}}? Допоможи іншим і отримай заслужену нагороду!',
            en: 'Why not hand over cash to {{count}} people totaling ${{amount}}? Help others and earn a well-deserved reward!',
            de: 'Warum übergibst du nicht {{count}} Menschen Bargeld in Höhe von ${{amount}}? Hilf anderen und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Dlaczego by nie przekazać gotówki {{count}} ludziom na sumę ${{amount}}? Pomóż innym i zdobądź zasłużoną nagrodę!',
            zh: '为什么不把现金交给{{count}}人总计${{amount}}?帮助他人，获得应得的回报',
        },
    },
    busmanJobDailyQuest: {
        name: {
            ru: 'Автобусный магнат',
            ua: 'Автобусний магнат',
            en: 'Bus Baron',
            de: 'Bus-Fahrer',
            pl: 'Autobusowy Magnat',
            zh: '公交大亨',
        },
        desc: {
            ru: 'Почему бы тебе не попробовать заработать ${{goal}}, работая водителем автобуса? Перевози пассажиров, следуй маршрутам и покажи свои навыки за рулём. Получи заслуженную награду за свою работу!',
            ua: 'Чому б тобі не спробувати заробити ${{goal}}, працюючи водієм автобуса? Перевозь пасажирів, слідуй маршрутам і покажи свої навички за кермом. Отримай заслужену нагороду за свою роботу!',
            en: 'Why not try to earn ${{goal}} working as a bus driver? Transport passengers, follow routes, and showcase your driving skills. Earn a well-deserved reward for your efforts!',
            de: 'Warum versuchst du nicht, ${{goal}} zu verdienen, indem du als Busfahrer arbeitest? Transportiere Passagiere, folge den Routen und zeige deine Fahrkünste. Verdiene dir eine wohlverdiente Belohnung für deine Mühe!',
            pl: 'Dlaczego by nie spróbować zarobić ${{goal}}, pracując jako kierowca autobusu? Przewoź pasażerów, przestrzegaj tras i pokaż swoje umiejętności jazdy. Zdobądź zasłużoną nagrodę za swoje wysiłki!',
            zh: '为什么不尝试挣${{目标}}作为一个公共汽车司机?运送乘客，跟随路线，并展示您的驾驶技能。为你的努力获得当之无愧的回报',
        },
    },
    playSlotsDailyQuest: {
        name: {
            ru: 'Играй в слоты',
            ua: 'Грай в слоти',
            en: 'Slot Machine Fun',
            de: 'Spielautomaten-Spaß',
            pl: 'Gra na automatach',
            zh: '老虎机',
        },
        desc: {
            ru: 'Почему бы тебе не испытать удачу и не сыграть в слоты на сумму ${{amount}} фишек? У тебя есть шанс выиграть большие призы и насладиться азартом игры. Пусть удача будет на твоей стороне!',
            ua: 'Чому б тобі не випробувати удачу і не зіграти в слоти на суму ${{amount}} фішок? У тебе є шанс виграти великі призи і насолодитися азартом гри. Нехай удача буде на твоєму боці!',
            en: 'Why not try your luck and play the slots for ${{amount}} chips? You have a chance to win big prizes and enjoy the thrill of the game. May luck be on your side!',
            de: 'Warum versuchst du nicht dein Glück und spielst ${{amount}} Chips an den Spielautomaten? Du hast die Chance, große Preise zu gewinnen und den Nervenkitzel des Spiels zu genießen. Möge das Glück auf deiner Seite sein!',
            pl: 'Dlaczego by nie spróbować szczęścia i zagrać na automatach za ${{amount}} żetonów? Masz szansę wygrać wielkie nagrody i cieszyć się dreszczykiem emocji. Niech szczęście będzie po twojej stronie!',
            zh: '为什么不试试你的运气和玩老虎机${{amount}}筹码?你有机会赢得大奖，享受游戏的刺激。愿好运站在你这边',
        },
    },
    shoppingClothesDailyQuest: {
        name: {
            ru: 'Модный шопинг',
            ua: 'Модний шопінг',
            en: 'Fashion Shopping',
            de: 'Mode-Shopping',
            pl: 'Zakupy modowe',
            zh: '风尚购物',
        },
        desc: {
            ru: 'Почему бы тебе не отправиться на шопинг и не потратить ${{goal}} на новую одежду? Обнови свой гардероб и получи за это заслуженную награду!',
            ua: 'Чому б тобі не вирушити на шопінг і не витратити ${{goal}} на новий одяг? Онови свій гардероб і отримай за це заслужену нагороду!',
            en: 'Why not go shopping and spend ${{goal}} on new clothes? Update your wardrobe and earn a well-deserved reward!',
            de: 'Warum gehst du nicht shoppen und gibst ${{goal}} für neue Kleidung aus? Aktualisiere deine Garderobe und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Dlaczego by nie wybrać się na zakupy i wydać ${{goal}} na nowe ubrania? Odśwież swoją garderobę i zdobądź zasłużoną nagrodę!',
            zh: '为什么不去购物，花{{goal}}美元买新衣服呢?更新你的衣橱，获得当之无愧的奖励',
        },
    },
    shoppingGunStoreDailyQuest: {
        name: {
            ru: 'Оружейный шопинг',
            ua: 'Зброєвий шопінг',
            en: 'Gun Store Shopping',
            de: 'Waffenladen-Einkauf',
            pl: 'Zakupy w sklepie z bronią',
            zh: '武装国度购物',
        },
        desc: {
            ru: 'Почему бы тебе не потратить ${{goal}} на покупку чего угодно в оружейном магазине? Пройдись по магазинам, выбери необходимое снаряжение и пополни свой арсенал. Получи заслуженную награду за свои покупки!',
            ua: 'Чому б тобі не витратити ${{goal}} на покупку чого завгодно у зброярні? Пройдися по магазинах, вибери необхідне спорядження та поповни свій арсенал. Отримай заслужену нагороду за свої покупки!',
            en: 'Why not spend ${{goal}} on anything at the gun store? Browse the shops, pick up the necessary gear, and expand your arsenal. Earn a well-deserved reward for your purchases!',
            de: 'Warum gibst du nicht ${{goal}} im Waffenladen aus? Durchstöbere die Läden, kaufe die notwendige Ausrüstung und erweitere dein Arsenal. Verdiene dir eine wohlverdiente Belohnung für deine Einkäufe!',
            pl: 'Dlaczego by nie wydać ${{goal}} na cokolwiek w sklepie z bronią? Przejrzyj sklepy, wybierz niezbędny sprzęt i rozbuduj swój arsenał. Zdobądź zasłużoną nagrodę za swoje zakupy!',
            zh: '为什么不花${{goal}}在枪支店买东西呢?浏览商店，挑选必要的装备，并扩大你的武器库。为您的购买获得当之无愧的奖励!',
        },
    },
    buyInCasinoBarDailyQuest: {
        name: {
            ru: 'Коктейль в казино',
            ua: 'Коктейль у казино',
            en: 'Casino Cocktail',
            de: 'Casino-Cocktail',
            pl: 'Koktajl w kasynie',
            zh: '赌场酒吧',
        },
        desc: {
            ru: 'Зайди в бар казино и купи что-нибудь вкусное. Напиток или закуска помогут тебе расслабиться и насладиться атмосферой. Получи награду за свои покупки!',
            ua: 'Зайди в бар казино і купи щось смачне. Напій чи закуска допоможуть тобі розслабитися та насолодитися атмосферою. Отримай нагороду за свої покупки!',
            en: 'Visit the casino bar and buy something tasty. A drink or a snack will help you relax and enjoy the atmosphere. Earn a reward for your purchases!',
            de: 'Besuche die Casino-Bar und kaufe etwas Leckeres. Ein Getränk oder ein Snack helfen dir, zu entspannen und die Atmosphäre zu genießen. Verdiene eine Belohnung für deine Einkäufe!',
            pl: 'Odwiedź bar w kasynie i kup coś smacznego. Napój lub przekąska pomogą ci się zrelaksować i cieszyć atmosferą. Zdobywaj nagrody za swoje zakupy!',
            zh: '去赌场酒吧买些好吃的。一杯饮料或零食会帮助你放松，享受气氛。为你的购买获得奖励',
        },
    },
    drinkVodkaDailyQuest: {
        name: {
            ru: 'Водочный марафон',
            ua: 'Горілчаний марафон',
            en: 'Vodka Marathon',
            de: 'Wodka-Marathon',
            pl: 'Wódka-maraton',
            zh: '伏特加马拉松',
        },
        desc: {
            ru: 'Смело выпей {{amount}} порций водки и покажи свою стойкость. Докажи, что можешь выдержать настоящий водочный марафон и получи за это заслуженную награду!',
            ua: 'Сміливо випий {{amount}} порцій горілки та покажи свою витримку. Доведи, що можеш витримати справжній горілчаний марафон та отримай за це заслужену нагороду!',
            en: 'Bravely drink {{amount}} servings of vodka and show your resilience. Prove you can handle a real vodka marathon and earn a well-deserved reward!',
            de: 'Trinke mutig {{amount}} Portionen Wodka und zeige deine Ausdauer. Beweise, dass du einen echten Wodka-Marathon durchstehen kannst und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Śmiało wypij {{amount}} porcje wódki i pokaż swoją wytrzymałość. Udowodnij, że potrafisz przetrwać prawdziwy wódka-maraton i zdobądź zasłużoną nagrodę!',
            zh: '勇敢地喝下{{amount}}份伏特加，展现你的韧性。证明你可以驾驭真正的伏特加马拉松，并获得当之无愧的奖励!',
        },
    },
    fishingAtDawnDailyQuest: {
        name: {
            ru: 'Рыбалка на рассвете',
            ua: 'Рибалка на світанку',
            en: 'Fishing at Dawn',
            de: 'Angeln im Morgengrauen',
            pl: 'Wędkowanie o świcie',
            zh: '捕鱼',
        },
        desc: {
            ru: 'Начни свой день с рыбалки на рассвете! Поймай {{amount}} рыб, наслаждаясь красотой природы и тишиной утренних вод. Получи заслуженную награду за свой ранний подъем!',
            ua: 'Розпочни свій день рибалкою на світанку! Злови {{amount}} риб, насолоджуючись красою природи та тишею ранкових вод. Отримай заслужену нагороду за свій ранній підйом!',
            en: 'Start your day with fishing at dawn! Catch {{amount}} fish while enjoying the beauty of nature and the tranquility of the morning waters. Earn a well-deserved reward for your early rise!',
            de: 'Beginne deinen Tag mit Angeln im Morgengrauen! Fange {{amount}} Fische und genieße die Schönheit der Natur und die Ruhe der morgendlichen Gewässer. Verdiene eine wohlverdiente Belohnung für dein frühes Aufstehen!',
            pl: 'Rozpocznij dzień od wędkowania o świcie! Złap {{amount}} ryb, ciesząc się pięknem natury i spokojem porannych wód. Zdobądź zasłużoną nagrodę za wczesne wstawanie!',
            zh: '在黎明钓鱼开始你的一天!在享受大自然的美丽和早晨水域的宁静的同时，捕捉{{数量}}条鱼。为你的早起得到了应得的奖励!',
        },
    },
    fishingChallengeDailyQuest: {
        name: {
            ru: 'Рыбный вызов',
            ua: 'Рибний виклик',
            en: 'Fishing Challenge',
            de: 'Angeln-Herausforderung',
            pl: 'Wyzwanie wędkarskie',
            zh: '钓鱼挑战',
        },
        desc: {
            ru: 'Готов к рыбацкому вызову? Поймай {{amount}} раз рыбу определенного вида и докажи, что ты настоящий мастер рыбалки! Вперед к берегу за приключениями и заслуженной наградой!',
            ua: 'Готовий до рибальського виклику? Злови {{amount}} разів рибу певного виду і доведи, що ти справжній майстер риболовлі! Вперед до берега за пригодами та заслуженою нагородою!',
            en: "Ready for a fishing challenge? Catch {{amount}} times a specific type of fish and prove you're a true fishing master! Head to the shore for adventure and a well-deserved reward!",
            de: 'Bereit für eine Angelherausforderung? Fange {{amount}} Mal einen bestimmten Fisch und beweise, dass du ein wahrer Angelmeister bist! Auf zum Ufer für Abenteuer und eine wohlverdiente Belohnung!',
            pl: 'Gotowy na wyzwanie wędkarskie? Złap {{amount}} razy rybę określonego gatunku i udowodnij, że jesteś prawdziwym mistrzem wędkowania! Ruszaj na brzeg po przygodę i zasłużoną nagrodę!',
            zh: '准备好挑战钓鱼了吗?捕获{{数量}}倍的特定类型的鱼，并证明你是一个真正的钓鱼大师!前往海岸探险和当之无愧的奖励',
        },
    },
    dailyAnimalHuntQuest: {
        name: {
            ru: 'Дикая охота',
            ua: 'Дике полювання',
            en: 'Wild Hunt',
            de: 'Wilde Jagd',
            pl: 'Dzika polowanie',
            zh: '疯狂打猎',
        },
        desc: {
            ru: 'Сегодня тебе предстоит стать настоящим охотником! Поймай {{amount}} животных и докажи, что дикая природа тебе по плечу. Стань легендой лесов и получи заслуженную награду!',
            ua: 'Сьогодні ти маєш стати справжнім мисливцем! Злови {{amount}} тварин і доведи, що дика природа тобі під силу. Стань легендою лісів та отримай заслужену нагороду!',
            en: 'Today, you must become a true hunter! Catch {{amount}} animals and prove that the wild is your domain. Become a legend of the forests and earn a well-deserved reward!',
            de: 'Heute musst du ein wahrer Jäger werden! Fange {{amount}} Tiere und beweise, dass die Wildnis dein Revier ist. Werde zur Legende der Wälder und verdiene dir eine wohlverdiente Belohnung!',
            pl: 'Dziś musisz zostać prawdziwym myśliwym! Złap {{amount}} zwierząt i udowodnij, że dzika przyroda to twoje terytorium. Zostań legendą lasów i zdobądź zasłużoną nagrodę!',
            zh: '今天，你必须成为一个真正的猎人!捕捉{{amount}}动物，证明野生是你的领地。成为森林传奇，并获得应得的奖励!',
        },
    },
    plantFarmDailyQuest: {
        name: {
            ru: 'Грядка в деле',
            ua: 'Грядка в ділі',
            en: 'Plot in Action',
            de: 'Beet im Einsatz',
            pl: 'Grządka w akcji',
            zh: '田地行动',
        },
        desc: {
            ru: 'Твой огород ждёт действий! Посади, вырасти и собери урожай {{count}} раз на ферме, чтобы доказать, что ты настоящий фермер. За усердие тебя ждёт заслуженная награда!',
            ua: 'Твій город чекає на дії! Посади, вирости та збері врожай {{count}} разів на фермі, щоб довести, що ти справжній фермер. За старанність на тебе чекає заслужена нагорода!',
            en: 'Your plot is ready for action! Plant, grow, and harvest {{count}} times on the farm to prove you’re a true farmer. A well-deserved reward awaits you for your hard work!',
            de: 'Dein Beet ist bereit für den Einsatz! Pflanze, pflege und ernte {{count}} Mal auf dem Bauernhof, um zu beweisen, dass du ein wahrer Bauer bist. Für deine Mühe wartet eine wohlverdiente Belohnung auf dich!',
            pl: 'Twoja grządka czeka na akcję! Posadź, wyhoduj i zbierz plony {{count}} razy na farmie, aby udowodnić, że jesteś prawdziwym rolnikiem. Zasłużona nagroda czeka na ciebie za ciężką pracę!',
            zh: '你的田地准备行动了！种植、培育并收获{{count}}次，以证明你是一个真正的农夫。你的辛勤劳动将获得应得的奖励！',
        },
    },
    waterPlantsDailyQuest: {
        name: {
            ru: 'Лейка в бой',
            ua: 'Лійка в бій',
            en: 'Watering Duty',
            de: 'Gießkanne im Einsatz',
            pl: 'Podlej i ruszaj',
            zh: '浇水行动',
        },
        desc: {
            ru: 'Твои растения жаждут внимания! Полей {{count}} раз любые растения на ферме и убедись, что урожай будет сочным. За заботу тебя ждёт заслуженная награда!',
            ua: 'Твої рослини потребують уваги! Полий {{count}} разів будь-які рослини на фермі та переконайся, що врожай буде соковитим. За турботу на тебе чекає заслужена нагорода!',
            en: 'Your plants are thirsty for attention! Water any plants on the farm {{count}} times and ensure your harvest will be plentiful. A well-deserved reward awaits you for your care!',
            de: 'Deine Pflanzen dürsten nach Aufmerksamkeit! Gieße {{count}} Mal beliebige Pflanzen auf dem Bauernhof und sorge dafür, dass deine Ernte saftig wird. Für deine Fürsorge wartet eine wohlverdiente Belohnung auf dich!',
            pl: 'Twoje rośliny potrzebują uwagi! Podlej {{count}} razy dowolne rośliny na farmie i upewnij się, że plony będą obfite. Zasłużona nagroda czeka na ciebie za opiekę!',
            zh: '你的植物渴望关注！在农场浇水{{count}}次，确保你的收成丰富。你的细心照料将得到应得的回报！',
        },
    },

    // Новые квесты с 03/08/2025 august
    jobQuarryMinerCollectDailyQuest: {
        name: {
            ru: 'Шахтёрский улов',
            ua: 'Шахтарський улов',
            en: 'Miner’s Catch',
            de: 'Bergarbeiter-Beute',
            pl: 'Wydobywcza zdobycz',
        },
        desc: {
            ru: 'Сегодня твоя задача - добыть {{amount}} руды на шахте. Возьми кирку покрепче, отправляйся в забой и покажи, кто тут настоящий добытчик! Чем больше руды - тем выше твоя награда!',
            ua: 'Сьогодні твоє завдання - добути {{amount}} руди на шахті. Бери міцніше кайло, вирушай у забій і покажи, хто тут справжній добувач! Чим більше руди - тим вища твоя нагорода!',
            en: 'Today your task is to mine {{amount}} ore in the quarry. Grab your strongest pickaxe, head into the pit, and show who the real miner is! The more ore you get, the bigger your reward!',
            de: 'Deine Aufgabe heute: Baue {{amount}} Erz im Steinbruch ab. Nimm deine stärkste Spitzhacke, geh in den Stollen und zeig, wer hier der wahre Schürfer ist! Je mehr Erz, desto größer die Belohnung!',
            pl: 'Twoje dzisiejsze zadanie to wydobycie {{amount}} rudy w kopalni. Chwyć najmocniejszy kilof, ruszaj w dół i pokaż, kto tu rządzi! Im więcej rudy, tym większa nagroda!',
        },
    },
    earnQuarryDumperDailyQuest: {
        name: {
            ru: 'Король самосвала',
            ua: 'Король самоскида',
            en: 'Dump Truck King',
            de: 'König des Kippers',
            pl: 'Król wywrotki',
        },
        desc: {
            ru: 'Садись за руль здоровенного дампера и заработай {{goal}}$, перевозя руду. Покажи класс, не забудь пристегнуться и не тормози - только вперёд к награде!',
            ua: 'Сідай за кермо здоровенного самоскида і зароби {{goal}}$, перевозячи руду. Покажи клас, не забудь пристебнутись і не гальмуй - тільки вперед до нагороди!',
            en: 'Get behind the wheel of a massive dumper and earn {{goal}}$ by hauling ore. Show your skills, buckle up, and don’t slow down - just full speed ahead to the reward!',
            de: 'Setz dich ans Steuer eines riesigen Kippers und verdiene {{goal}}$, indem du Erz transportierst. Zeig, was du drauf hast, schnall dich an und gib Gas - volle Fahrt voraus zur Belohnung!',
            pl: 'Wsiadaj za kierownicę wielkiej wywrotki i zarób {{goal}}$, przewożąc rudę. Pokaż klasę, zapnij pasy i nie zwalniaj - tylko naprzód po nagrodę!',
        },
    },
    earnQuarryBulldozerDailyQuest: {
        name: {
            ru: 'Бульдозер-босс',
            ua: 'Бульдозер-бос',
            en: 'Bulldozer Boss',
            de: 'Bulldozer-Boss',
            pl: 'Szef buldożera',
        },
        desc: {
            ru: 'Врубай двигатель и заработай {{goal}}$, работая на бульдозере в карьере. Разгребай завалы, расчищай путь и собирай заслуженную награду!',
            ua: "Заводь двигун і зароби {{goal}}$, працюючи на бульдозері в кар'єрі. Розгрібай завали, розчищай шлях і забирай заслужену нагороду!",
            en: 'Start the engine and earn {{goal}}$ while working with the bulldozer in the quarry. Clear debris, open the way, and collect your well-earned reward!',
            de: 'Starte den Motor und verdiene {{goal}}$, während du mit dem Bulldozer im Steinbruch arbeitest. Räume Geröll weg, mach den Weg frei und hol dir deine verdiente Belohnung!',
            pl: 'Odpal silnik i zarób {{goal}}$, pracując buldożerem w kamieniołomie. Usuń gruz, oczyść drogę i zgarnij zasłużoną nagrodę!',
        },
    },
    sellAnythingToBuyerDailyQuest: {
        name: {
            ru: 'Сделка со скупщиком',
            ua: 'Угода зі скупником',
            en: 'Deal with the Fence',
            de: 'Deal mit dem Hehler',
            pl: 'Transakcja z paserem',
        },
        desc: {
            ru: 'Зайди к скупщику {{buyerName}} и продай что угодно на сумму {{goal}} $. Не стесняйся - избавляйся от хлама, получай кэш и двигайся к награде!',
            ua: 'Зайди до скупника {{buyerName}} і продай що завгодно на суму {{goal}} $. Не соромся - позбувайся мотлоху, отримуй кеш і рухайся до нагороди!',
            en: 'Visit the fence {{buyerName}} and sell anything worth {{goal}} $. Don’t hold back - ditch the junk, get the cash, and move toward your reward!',
            de: 'Geh zum Hehler {{buyerName}} und verkauf irgendwas im Wert von {{goal}} $. Keine Zurückhaltung - werde den Krempel los, kassiere das Geld und hol dir deine Belohnung!',
            pl: 'Odwiedź pasera {{buyerName}} i sprzedaj cokolwiek za {{goal}} $. Nie krępuj się - pozbądź się gratów, zgarnij kasę i rusz po nagrodę!',
        },
    },
    sellDivingLootToBuyerDailyQuest: {
        name: {
            ru: 'Морской барыга',
            ua: 'Морський барига',
            en: 'Sea Hustler',
            de: 'Meeres-Schieber',
            pl: 'Morski handlarz',
        },
        desc: {
            ru: 'Продай скупщику {{buyerName}} всё, что нарыбачил под водой, на сумму {{goal}} $. Ныряй глубже, тащи больше - и не забудь забрать свою награду!',
            ua: 'Продай скупнику {{buyerName}} все, що наловив під водою, на суму {{goal}} $. Пірнай глибше, тягни більше - і не забудь забрати свою нагороду!',
            en: 'Sell everything you fished up underwater to the fence {{buyerName}} for {{goal}} $. Dive deeper, bring more - and don’t forget your reward!',
            de: 'Verkauf dem Hehler {{buyerName}} alles, was du unter Wasser gefischt hast, für {{goal}} $. Tauch tiefer, bring mehr - und vergiss deine Belohnung nicht!',
            pl: 'Sprzedaj paserowi {{buyerName}} wszystko, co wyłowiłeś pod wodą, za {{goal}} $. Nurkuj głębiej, przynoś więcej - i nie zapomnij o nagrodzie!',
        },
    },
    sellMinerLootToBuyerDailyQuest: {
        name: {
            ru: 'Сбыт руды',
            ua: 'Збут руди',
            en: 'Ore Dealing',
            de: 'Erzhandel',
            pl: 'Zbyt rudy',
        },
        desc: {
            ru: 'Продай скупщику {{buyerName}} руду, которую добыл на шахте, на сумму {{goal}} $. Не держи богатство при себе - обменивай на кэш и получай награду!',
            ua: 'Продай скупнику {{buyerName}} руду, яку добув у шахті, на суму {{goal}} $. Не тримай багатство при собі - міняй на кеш і отримуй нагороду!',
            en: 'Sell the ore you mined to the fence {{buyerName}} for {{goal}} $. Don’t hoard your riches - trade for cash and claim your reward!',
            de: 'Verkauf das Erz, das du in der Mine abgebaut hast, dem Hehler {{buyerName}} für {{goal}} $. Behalte den Reichtum nicht für dich - tausch ihn gegen Geld und hol dir die Belohnung!',
            pl: 'Sprzedaj paserowi {{buyerName}} rudę, którą wydobyłeś w kopalni, za {{goal}} $. Nie trzymaj bogactwa przy sobie - wymień na kasę i zgarnij nagrodę!',
        },
    },
    sellFishingLootToBuyerDailyQuest: {
        name: {
            ru: 'Рыбный барыга',
            ua: 'Рибний барига',
            en: 'Fish Hustler',
            de: 'Fisch-Schieber',
            pl: 'Rybny handlarz',
        },
        desc: {
            ru: 'Сдавай весь свой улов скупщику {{buyerName}} на сумму {{goal}} $. Чем крупнее улов - тем ближе награда. Не сиди на берегу - лови и продавай всё подряд!',
            ua: 'Здавай весь свій улов скупнику {{buyerName}} на суму {{goal}} $. Чим більший улов - тим ближче нагорода. Не сиди на березі - лови й продавай усе підряд!',
            en: 'Sell your entire catch to the fence {{buyerName}} for {{goal}} $. The bigger the haul, the closer the reward. Don’t sit on the shore - catch and sell it all!',
            de: 'Verkauf deinen gesamten Fang dem Hehler {{buyerName}} für {{goal}} $. Je größer der Fang - desto näher die Belohnung. Sitz nicht am Ufer - fang was und verkauf alles!',
            pl: 'Sprzedaj cały swój połów paserowi {{buyerName}} za {{goal}} $. Im większy połów - tym bliżej nagroda. Nie siedź na brzegu - łów i sprzedawaj wszystko jak leci!',
        },
    },
    sellHuntingLootToBuyerDailyQuest: {
        name: {
            ru: 'Сбыт добычи',
            ua: 'Збут здобичі',
            en: 'Trophy Trade',
            de: 'Beutehandel',
            pl: 'Zbyt zdobyczy',
        },
        desc: {
            ru: 'Снеси скупщику {{buyerName}} всю охотничью добычу на сумму {{goal}} $. Не оставляй трофеи пылиться - меняй их на деньги и забирай награду!',
            ua: 'Занеси скупнику {{buyerName}} всю мисливську здобич на суму {{goal}} $. Не залишай трофеї припадати пилом - міняй їх на гроші й забирай нагороду!',
            en: 'Bring all your hunting loot to the fence {{buyerName}} for {{goal}} $. Don’t let your trophies gather dust - trade them for cash and grab your reward!',
            de: 'Bring dem Hehler {{buyerName}} deine gesamte Jagdbeute im Wert von {{goal}} $. Lass deine Trophäen nicht verstauben - tausch sie gegen Geld und hol dir deine Belohnung!',
            pl: 'Zanieś paserowi {{buyerName}} całą swoją myśliwską zdobycz za {{goal}} $. Nie pozwól trofeom się kurzyć - wymień je na gotówkę i odbierz nagrodę!',
        },
    },
    flappyBirdScoreInOneGameDailyQuest: {
        name: {
            ru: 'Чистый полёт',
            ua: 'Чистий політ',
            en: 'Clean Flight',
            de: 'Sauberer Flug',
            pl: 'Czysty lot',
        },
        desc: {
            ru: 'Пролети {{goal}} труб за одну игру во Flappy Bird. Одна попытка, никаких склеек - только ты и труба за трубой!',
            ua: 'Пролети {{goal}} труб за одну гру у Flappy Bird. Одна спроба, ніяких склейок - тільки ти і труба за трубою!',
            en: 'Clear {{goal}} pipes in a single Flappy Bird run. One attempt, nothing stitched together - just you and pipe after pipe!',
            de: 'Passiere {{goal}} Rohre in einem einzigen Flappy Bird Lauf. Ein Versuch, nichts zusammengestückelt - nur du und Rohr für Rohr!',
            pl: 'Przeleć obok {{goal}} rur w jednej grze Flappy Bird. Jedna próba, nic zszywanego - tylko ty i rura za rurą!',
        },
    },
    sumFlappyBirdScoreDailyQuest: {
        name: {
            ru: 'Налетать за день',
            ua: 'Налітати за день',
            en: 'A Day of Flying',
            de: 'Ein Tag im Flug',
            pl: 'Dzień w powietrzu',
        },
        desc: {
            ru: 'Набери {{goal}} очков во Flappy Bird за сколько угодно попыток. Разбилась птица - запускай снова, всё идёт в копилку!',
            ua: 'Набери {{goal}} очок у Flappy Bird за скільки завгодно спроб. Розбилася пташка - запускай знову, усе йде в скарбничку!',
            en: 'Score {{goal}} points in Flappy Bird across as many attempts as you like. Crashed the bird? Start again, it all adds up!',
            de: 'Erziele {{goal}} Punkte in Flappy Bird in beliebig vielen Versuchen. Vogel abgestürzt? Starte neu, alles zählt zusammen!',
            pl: 'Zdobądź {{goal}} punktów we Flappy Bird w dowolnej liczbie prób. Ptak się rozbił? Zaczynaj od nowa, wszystko się sumuje!',
        },
    },
    winGrandmasterMatchesDailyQuest: {
        name: {
            ru: 'Партия за телефоном',
            ua: 'Партія за телефоном',
            en: 'A Match on the Phone',
            de: 'Eine Partie am Handy',
            pl: 'Partia przy telefonie',
        },
        desc: {
            ru: 'Выиграй {{count}} партии в шахматы в приложении Grandmaster. Бот тоже считается, но живой соперник интереснее!',
            ua: 'Виграй {{count}} партії в шахи в застосунку Grandmaster. Бот теж вважається, але живий суперник цікавіший!',
            en: 'Win {{count}} chess matches in the Grandmaster app. The bot counts too, but a live opponent is far more fun!',
            de: 'Gewinne {{count}} Schachpartien in der Grandmaster-App. Der Bot zählt auch, aber ein echter Gegner ist spannender!',
            pl: 'Wygraj {{count}} partii szachów w aplikacji Grandmaster. Bot też się liczy, ale żywy przeciwnik jest ciekawszy!',
        },
    },
    sendPhoneSmsDailyQuest: {
        name: {
            ru: 'Смс-общение',
            ua: 'СМС-спілкування',
            en: 'SMS Socializing',
            de: 'SMS-Kommunikation',
            pl: 'SMS-komunikacja',
        },
        desc: {
            ru: 'Разошли смс на {{count}} разных номеров. Больше общения - больше движухи, а заодно и награда в кармане!',
            ua: 'Надішли смс на {{count}} різних номерів. Більше спілкування - більше двіжу, а ще й нагорода в кишені!',
            en: 'Send SMS messages to {{count}} different numbers. The more you connect - the more action, and a reward in your pocket!',
            de: 'Verschicke SMS an {{count}} verschiedene Nummern. Mehr Kommunikation - mehr Action und obendrauf eine Belohnung in der Tasche!',
            pl: 'Wyślij SMS-y na {{count}} różnych numerów. Więcej kontaktu - więcej akcji, a nagroda sama wpadnie do kieszeni!',
        },
    },
    drinkWiskeyDailyQuest: {
        name: {
            ru: 'Глоток крепкого',
            ua: 'Ковток міцного',
            en: 'A Sip of the Strong Stuff',
            de: 'Ein Schluck Starkes',
            pl: 'Łyk mocnego',
        },
        desc: {
            ru: 'Залей в себя виски и почувствуй вкус жизни. Иногда нужно просто расслабиться и поднять бокал за успех - а награда найдёт тебя сама!',
            ua: 'Залий у себе віскі й відчуй смак життя. Іноді треба просто розслабитися й підняти келих за успіх - а нагорода знайде тебе сама!',
            en: 'Pour yourself some whiskey and taste life. Sometimes you just need to relax and raise a glass to success - and the reward will come to you!',
            de: 'Gieß dir einen Whiskey ein und schmeck das Leben. Manchmal muss man sich einfach entspannen und das Glas auf den Erfolg heben - und die Belohnung kommt von selbst!',
            pl: 'Wlej w siebie whisky i poczuj smak życia. Czasem trzeba się po prostu zrelaksować i wznieść toast za sukces - a nagroda sama cię znajdzie!',
        },
    },
    eatBurgersDailyQuest: {
        name: {
            ru: 'Бургер-обжора',
            ua: 'Бургер-обжора',
            en: 'Burger Glutton',
            de: 'Burger-Fresser',
            pl: 'Burgerowy Obżartuch',
        },
        desc: {
            ru: 'Уплети {{amount}} бургеров за день. Покажи всем, кто тут главный по фастфуду, и заодно забери свою награду!',
            ua: "З'їж {{amount}} бургерів за день. Покажи всім, хто тут головний по фастфуду, і забери свою нагороду!",
            en: "Devour {{amount}} burgers in a day. Show everyone who's the fast food boss and grab your reward!",
            de: 'Verschling {{amount}} Burger an einem Tag. Zeig allen, wer hier der Fast-Food-Boss ist, und hol dir deine Belohnung!',
            pl: 'Wciągnij {{amount}} burgerów w jeden dzień. Pokaż wszystkim, kto tu rządzi fast foodem, i zgarnij nagrodę!',
        },
    },
    callTimeDailyQuest: {
        name: {
            ru: 'Болтун на проводе',
            ua: "Базікало на зв'язку",
            en: 'Chatterbox on the Line',
            de: 'Plappermaul am Draht',
            pl: 'Gaduła na linii',
        },
        desc: {
            ru: 'Проведи в звонках не меньше {{minutes}} минут. Общайся, решай вопросы, базарь ни о чём - главное не молчи! За разговорчивость - награда.',
            ua: 'Проведи в дзвінках не менше {{minutes}} хвилин. Спілкуйся, вирішуй питання, теревенькай про все - головне не мовчи! За балакучість - нагорода.',
            en: 'Spend at least {{minutes}} minutes on calls. Chat, solve stuff, ramble about nothing - just don’t stay silent! Chattiness gets you a reward.',
            de: 'Verbringe mindestens {{minutes}} Minuten in Anrufen. Quatsch, löse Probleme, laber über alles Mögliche - Hauptsache, du schweigst nicht! Für Redseligkeit gibt’s eine Belohnung.',
            pl: 'Spędź co najmniej {{minutes}} minut na rozmowach. Gadaj, rozwiązuj sprawy, trajkocz o byle czym - byle nie milcz! Za gadatliwość czeka nagroda.',
        },
    },
    repairVehiclesDailyQuest: {
        name: {
            ru: 'Механик дня',
            ua: 'Механік дня',
            en: 'Mechanic of the Day',
            de: 'Mechaniker des Tages',
            pl: 'Mechanik Dnia',
        },
        desc: {
            ru: 'Почини {{count}} любых машин с помощью ремкомплекта. Взял ключ, подкрутил - и награда уже в твоих руках!',
            ua: 'Полагодь {{count}} будь-яких машин за допомогою ремкомплекту. Взяв ключ, підкрутив - і нагорода вже в твоїх руках!',
            en: 'Repair {{count}} any vehicles using a repair kit. Grab a wrench, tighten a few bolts - and the reward is yours!',
            de: 'Repariere {{count}} beliebige Fahrzeuge mit einem Reparaturset. Schnapp dir den Schraubenschlüssel, zieh nach - und die Belohnung gehört dir!',
            pl: 'Napraw {{count}} dowolnych pojazdów za pomocą zestawu naprawczego. Chwyć klucz, dokręć parę śrub - i nagroda jest twoja!',
        },
    },
    medicalCheckupDailyQuest: {
        name: {
            ru: 'Медосмотр',
            ua: 'Медогляд',
            en: 'Medical Checkup',
            de: 'Gesundheitscheck',
            pl: 'Badania lekarskie',
        },
        desc: {
            ru: 'Загляни в больницу и пройди медосмотр - проверься на наличие болезней. Здоровье превыше всего, а за заботу о себе - заслуженная награда!',
            ua: "Зазирни до лікарні та пройди медогляд - перевірся на наявність хвороб. Здоров'я - перш за все, а за турботу про себе - заслужена нагорода!",
            en: "Drop by the hospital and get a checkup - make sure you're disease-free. Health comes first, and self-care earns you a well-deserved reward!",
            de: 'Schau im Krankenhaus vorbei und mach einen Gesundheitscheck - lass dich auf Krankheiten untersuchen. Gesundheit geht vor, und für Selbstfürsorge gibt’s eine wohlverdiente Belohnung!',
            pl: 'Wpadnij do szpitala na badania - sprawdź, czy nie masz żadnych chorób. Zdrowie przede wszystkim, a za dbanie o siebie zasłużona nagroda!',
        },
    },
    takeBloodMedicalDailyQuest: {
        name: {
            ru: 'Донор дня',
            ua: 'Донор дня',
            en: 'Donor of the Day',
            de: 'Spender des Tages',
            pl: 'Dawca Dnia',
        },
        desc: {
            ru: 'Сдай кровь в больнице и помоги тем, кому она нужна. Хорошее дело не останется без награды!',
            ua: 'Здай кров у лікарні та допоможи тим, хто її потребує. Добра справа не залишиться без нагороди!',
            en: 'Donate blood at the hospital and help those in need. A good deed won’t go unrewarded!',
            de: 'Spende Blut im Krankenhaus und hilf denen, die es brauchen. Eine gute Tat bleibt nicht unbelohnt!',
            pl: 'Oddaj krew w szpitalu i pomóż tym, którzy jej potrzebują. Dobre uczynki nie pozostają bez nagrody!',
        },
    },
    sellFarmLootToBuyerDailyQuest: {
        name: {
            ru: 'Собрал - продал',
            ua: 'Зібрав - продав',
            en: 'Harvest and Sell',
            de: 'Geerntet und verkauft',
            pl: 'Zebrane - sprzedane',
        },
        desc: {
            ru: 'Всё, что вырастил на ферме, неси скупщику {{buyerName}} и продай минимум на {{goal}} $. Не скупись - награда тебя не подведёт!',
            ua: 'Усе, що виростив на фермі, неси скупнику {{buyerName}} і продай щонайменше на {{goal}} $. Не шкодуй - нагорода не підведе!',
            en: 'Take everything you grew on the farm to buyer {{buyerName}} and sell it for at least {{goal}} $. Don’t hold back - the reward won’t disappoint!',
            de: 'Bring alles, was du auf dem Bauernhof angebaut hast, zu {{buyerName}} und verkaufe es für mindestens {{goal}} $. Sei nicht geizig - die Belohnung lohnt sich!',
            pl: 'Zanieś wszystko, co wyhodowałeś na farmie, do kupca {{buyerName}} i sprzedaj za co najmniej {{goal}} $. Nie żałuj - nagroda cię nie zawiedzie!',
        },
    },
    tuneCarDailyQuest: {
        name: {
            ru: 'Прокачай корыто',
            ua: 'Прокачай корито',
            en: 'Pimp Your Ride',
            de: 'Tuning für die Karre',
            pl: 'Podrasuj brykę',
        },
        desc: {
            ru: 'Ввали {{amount}} $ в тюнинг своей машины. Пусть все офигеют от прокачки, а ты получи заслуженную награду!',
            ua: 'Ввали {{amount}} $ у тюнінг своєї машини. Нехай усі офігєють від прокачки, а ти отримай заслужену нагороду!',
            en: 'Throw {{amount}} $ into tuning your car. Let everyone be blown away by the upgrades - and you get the reward you deserve!',
            de: 'Ballere {{amount}} $ ins Tuning deiner Karre. Lass alle staunen über dein Setup - und hol dir deine wohlverdiente Belohnung!',
            pl: 'Pakuj {{amount}} $ w tuning swojej bryki. Niech wszyscy zbierają szczęki z podłogi - a ty zgarnij zasłużoną nagrodę!',
        },
    },
    airCargoCratesDailyQuest: {
        name: {
            ru: 'Борт не ждёт',
            ua: 'Борт не чекає',
            en: 'The Plane Waits for No One',
            de: 'Der Flieger wartet nicht',
            pl: 'Samolot nie czeka',
        },
        desc: {
            ru: 'Выгрузи {{amount}} ящиков из трюма. Самолёт улетит по расписанию, успеешь ты или нет - так что не тяни с погрузчиком!',
            ua: 'Вивантаж {{amount}} ящиків із трюму. Літак полетить за розкладом, встигнеш ти чи ні - тож не тягни з навантажувачем!',
            en: 'Unload {{amount}} crates from the hold. The plane leaves on schedule whether you made it or not - so keep that forklift moving!',
            de: 'Entlade {{amount}} Kisten aus dem Frachtraum. Der Flieger startet nach Plan, ob du fertig bist oder nicht - also ran an den Gabelstapler!',
            pl: 'Rozładuj {{amount}} skrzyń z ładowni. Samolot odleci o czasie, zdążysz czy nie - więc nie ociągaj się z wózkiem!',
        },
    },
    airCargoEarnDailyQuest: {
        name: {
            ru: 'Смена на перроне',
            ua: 'Зміна на пероні',
            en: 'A Shift on the Apron',
            de: 'Schicht auf dem Vorfeld',
            pl: 'Zmiana na płycie',
        },
        desc: {
            ru: 'Заработай {{goal}} $ на разгрузке грузовых бортов. Отстоял смену честно - получи своё сверху!',
            ua: 'Зароби {{goal}} $ на розвантаженні вантажних бортів. Відстояв зміну чесно - отримай своє зверху!',
            en: 'Earn {{goal}} $ unloading cargo planes. Put in an honest shift and take your cut on top!',
            de: 'Verdiene {{goal}} $ beim Entladen von Frachtmaschinen. Steh die Schicht ehrlich durch und hol dir was obendrauf!',
            pl: 'Zarób {{goal}} $ na rozładunku samolotów towarowych. Odstój uczciwą zmianę i zgarnij coś ekstra!',
        },
    },
    crackContrabandCratesDailyQuest: {
        name: {
            ru: 'Чужой груз',
            ua: 'Чужий вантаж',
            en: 'Cargo That Is Not Yours',
            de: 'Fremde Fracht',
            pl: 'Cudzy ładunek',
        },
        desc: {
            ru: 'Вскрой {{count}} ящиков контрабанды. Ящик достаётся тому, кто добрался первым, так что не зевай - и не лови пулю на вскрытии!',
            ua: 'Розкрий {{count}} ящиків контрабанди. Ящик дістається тому, хто дістався першим, тож не позіхай - і не злови кулю на розкритті!',
            en: 'Crack {{count}} contraband crates. A crate goes to whoever got there first, so do not dawdle - and do not catch a bullet mid-crack!',
            de: 'Knacke {{count}} Schmuggelkisten. Eine Kiste gehört dem, der zuerst da war - also trödel nicht und fang dir keine Kugel beim Aufbrechen!',
            pl: 'Otwórz {{count}} skrzyń z kontrabandą. Skrzynia należy do tego, kto dotarł pierwszy, więc nie ociągaj się - i nie oberwij kulką przy otwieraniu!',
        },
    },
    cashCollectorAtmsDailyQuest: {
        name: {
            ru: 'Броневик по маршруту',
            ua: 'Броньовик за маршрутом',
            en: 'The Van on the Route',
            de: 'Der Panzerwagen auf Tour',
            pl: 'Furgon na trasie',
        },
        desc: {
            ru: 'Загрузи броневик в кассовом центре и обслужи {{amount}} банкоматов. Город без наличных долго не живёт - а гангстеры уже слышат, как ты подъезжаешь.',
            ua: 'Завантаж броньовик у касовому центрі й обслужи {{amount}} банкоматів. Місто без готівки довго не живе - а гангстери вже чують, як ти під\'їжджаєш.',
            en: 'Load the van at the cash centre and service {{amount}} ATMs. A city does not last long without cash - and the gangs can already hear you pulling up.',
            de: 'Belade den Panzerwagen im Geldzentrum und befülle {{amount}} Geldautomaten. Ohne Bargeld hält die Stadt nicht lange durch - und die Gangs hören dich schon vorfahren.',
            pl: 'Załaduj furgon w centrum gotówkowym i obsłuż {{amount}} bankomatów. Miasto bez gotówki długo nie pociągnie - a gangi już słyszą, jak podjeżdżasz.',
        },
    },
    burglaryRunsDailyQuest: {
        name: {
            ru: 'Тихий вечер',
            ua: 'Тихий вечір',
            en: 'A Quiet Evening',
            de: 'Ein ruhiger Abend',
            pl: 'Cichy wieczór',
        },
        desc: {
            ru: 'Проведи {{amount}} заходов по домам и уйди от полиции с товаром. Взяли на выезде - заход не считается!',
            ua: 'Проведи {{amount}} заходів по будинках і піди від поліції з товаром. Взяли на виїзді - захід не рахується!',
            en: 'Pull off {{amount}} house jobs and lose the police with the goods still on you. Get busted and the run does not count!',
            de: 'Zieh {{amount}} Hauseinbrüche durch und häng die Polizei mit der Ware ab. Wirst du geschnappt, zählt der Zug nicht!',
            pl: 'Zrób {{amount}} skoków na domy i zgub policję z łupem. Dasz się złapać - kurs się nie liczy!',
        },
    },
    towTruckOrdersDailyQuest: {
        name: {
            ru: 'Крюк и трос',
            ua: 'Гак і трос',
            en: 'Hook and Cable',
            de: 'Haken und Seil',
            pl: 'Hak i lina',
        },
        desc: {
            ru: 'Прими {{count}} заказов на эвакуаторе и вывези чужие машины со стоянок. Аккуратнее на лебёдке - помятый кузов тебе никто не оплатит.',
            ua: 'Прийми {{count}} замовлень на евакуаторі та вивези чужі машини зі стоянок. Обережніше з лебідкою - подряпаний кузов тобі ніхто не оплатить.',
            en: 'Take {{count}} tow truck orders and haul other people cars off the streets. Go easy on the winch - nobody pays you for a dented body.',
            de: 'Nimm {{count}} Abschleppaufträge an und schaff fremde Autos von der Straße. Sei vorsichtig mit der Winde - eine verbeulte Karosserie zahlt dir keiner.',
            pl: 'Przyjmij {{count}} zleceń lawetą i zabierz cudze auta z ulic. Ostrożnie z wciągarką - za pogięte blachy nikt ci nie zapłaci.',
        },
    },
    carjackerDeliverDailyQuest: {
        name: {
            ru: 'Чужие ключи',
            ua: 'Чужі ключі',
            en: 'Someone Else Keys',
            de: 'Fremde Schlüssel',
            pl: 'Cudze kluczyki',
        },
        desc: {
            ru: 'Пригони заказчику {{count}} машин. Стекло лучше не бить, копов лучше не собирать, а деньги забрать на точке.',
            ua: 'Пригони замовнику {{count}} машин. Скло краще не бити, копів краще не збирати, а гроші забрати на точці.',
            en: 'Bring the buyer {{count}} cars. Better not smash the glass, better not collect cops, and pick your cash up at the drop.',
            de: 'Bring dem Auftraggeber {{count}} Autos. Schlag besser keine Scheibe ein, sammle keine Cops ein und hol dein Geld am Übergabepunkt ab.',
            pl: 'Dostarcz zleceniodawcy {{count}} aut. Lepiej nie wybijaj szyby, nie zbieraj radiowozów, a kasę odbierz na miejscu.',
        },
    },
    collectOrangesDailyQuest: {
        name: {
            ru: 'Апельсиновый сезон',
            ua: 'Апельсиновий сезон',
            en: 'Orange Season',
            de: 'Orangensaison',
            pl: 'Sezon na pomarańcze',
        },
        desc: {
            ru: 'Обойди сады и обери {{count}} деревьев. Солнце печёт, лестница шатается, зато ящики полные.',
            ua: 'Обійди сади та обери {{count}} дерев. Сонце пече, драбина хитається, зате ящики повні.',
            en: 'Walk the orchards and strip {{count}} trees. The sun beats down, the ladder wobbles, but the crates come back full.',
            de: 'Geh durch die Obstgärten und pflücke {{count}} Bäume leer. Die Sonne brennt, die Leiter wackelt, dafür sind die Kisten voll.',
            pl: 'Obejdź sady i ogołoć {{count}} drzew. Słońce praży, drabina się chwieje, ale skrzynki wracają pełne.',
        },
    },
    washVehiclesDailyQuest: {
        name: {
            ru: 'Пена и блеск',
            ua: 'Піна і блиск',
            en: 'Foam and Shine',
            de: 'Schaum und Glanz',
            pl: 'Piana i połysk',
        },
        desc: {
            ru: 'Загони на мойку {{count}} машин и смой с них всю дорогу. Чистая тачка ездит не быстрее, но смотрится совсем иначе.',
            ua: 'Зажени на мийку {{count}} машин і змий з них усю дорогу. Чиста тачка їздить не швидше, але має зовсім інший вигляд.',
            en: 'Run {{count}} cars through the wash and rinse the road off them. A clean ride is no faster, but it looks like a different car.',
            de: 'Fahr {{count}} Autos durch die Waschanlage und spül die Straße runter. Sauber fährt nicht schneller, sieht aber ganz anders aus.',
            pl: 'Przepuść {{count}} aut przez myjnię i zmyj z nich całą trasę. Czysta bryka nie jedzie szybciej, ale wygląda zupełnie inaczej.',
        },
    },
    gymWorkoutDailyQuest: {
        name: {
            ru: 'Железо не ждёт',
            ua: 'Залізо не чекає',
            en: 'The Iron Is Waiting',
            de: 'Das Eisen wartet',
            pl: 'Żelazo czeka',
        },
        desc: {
            ru: 'Загляни в зал и отработай {{count}} подходов. Тело скажет спасибо, а награда лежит рядом со штангой.',
            ua: 'Загляни до залу та відпрацюй {{count}} підходів. Тіло скаже дякую, а нагорода лежить поруч зі штангою.',
            en: 'Drop by the gym and put in {{count}} sets. Your body will thank you, and the reward is sitting right next to the bar.',
            de: 'Schau im Fitnessstudio vorbei und zieh {{count}} Sätze durch. Dein Körper dankt es dir, und die Belohnung liegt gleich neben der Hantel.',
            pl: 'Wpadnij na siłownię i zrób {{count}} serii. Ciało podziękuje, a nagroda leży zaraz obok sztangi.',
        },
    },
    shootingRangeDailyQuest: {
        name: {
            ru: 'Пристрелка',
            ua: 'Пристрілка',
            en: 'Zeroing In',
            de: 'Einschießen',
            pl: 'Przystrzelanie',
        },
        desc: {
            ru: 'Зайди в тир и отстреляй {{count}} упражнений. Патроны за твой счёт, зато рука перестанет дрожать.',
            ua: 'Зайди до тиру та відстріляй {{count}} вправ. Патрони твоїм коштом, зате рука перестане тремтіти.',
            en: 'Head to the range and shoot {{count}} rounds of the course. The ammo is on you, but your hand will stop shaking.',
            de: 'Geh auf den Schießstand und absolviere {{count}} Durchgänge. Die Munition zahlst du selbst, dafür zittert die Hand nicht mehr.',
            pl: 'Wpadnij na strzelnicę i zalicz {{count}} rund. Amunicja na twój koszt, za to ręka przestanie drżeć.',
        },
    },
    refuelLitersDailyQuest: {
        name: {
            ru: 'Полный бак',
            ua: 'Повний бак',
            en: 'Full Tank',
            de: 'Voller Tank',
            pl: 'Pełny bak',
        },
        desc: {
            ru: 'Залей на заправках {{liters}} литров топлива. Пистолет в бак, чек в карман - и дальше по трассе.',
            ua: 'Залий на заправках {{liters}} літрів пального. Пістолет у бак, чек до кишені - і далі трасою.',
            en: 'Pump {{liters}} litres of fuel at the stations. Nozzle in the tank, receipt in the pocket, back on the road.',
            de: 'Tanke an den Tankstellen {{liters}} Liter Kraftstoff. Zapfpistole rein, Beleg in die Tasche und weiter auf die Straße.',
            pl: 'Zatankuj na stacjach {{liters}} litrów paliwa. Pistolet do baku, paragon do kieszeni i w trasę.',
        },
    },
    canteenMealDailyQuest: {
        name: {
            ru: 'Обед по расписанию',
            ua: 'Обід за розкладом',
            en: 'Lunch on Schedule',
            de: 'Mittagessen nach Plan',
            pl: 'Obiad o czasie',
        },
        desc: {
            ru: 'Зайди в столовую и возьми себе поесть. Работа работой, а обед никто не отменял.',
            ua: 'Зайди до їдальні та візьми собі попоїсти. Робота роботою, а обід ніхто не скасовував.',
            en: 'Stop by the canteen and grab something to eat. Work is work, but nobody cancelled lunch.',
            de: 'Schau in der Kantine vorbei und hol dir etwas zu essen. Arbeit ist Arbeit, aber Mittagessen bleibt Mittagessen.',
            pl: 'Wpadnij do stołówki i weź coś do jedzenia. Praca pracą, ale obiadu nikt nie odwołał.',
        },
    },
    petStreetAnimalsDailyQuest: {
        name: {
            ru: 'Уличные хвосты',
            ua: 'Вуличні хвости',
            en: 'Strays of the City',
            de: 'Streuner der Stadt',
            pl: 'Uliczne ogony',
        },
        desc: {
            ru: 'Найди на улицах {{count}} кошек или собак и погладь каждую. Одного и того же зверя дважды не засчитают, так что придётся прогуляться.',
            ua: 'Знайди на вулицях {{count}} котів або собак і погладь кожного. Одну й ту саму тварину двічі не зарахують, тож доведеться прогулятися.',
            en: 'Find {{count}} cats or dogs out on the streets and pet each one. The same animal will not count twice, so you are in for a walk.',
            de: 'Finde {{count}} Katzen oder Hunde auf der Straße und streichle jedes Tier. Dasselbe Tier zählt kein zweites Mal, also mach dich auf einen Spaziergang gefasst.',
            pl: 'Znajdź na ulicach {{count}} kotów lub psów i pogłaszcz każde. To samo zwierzę nie policzy się dwa razy, więc czeka cię spacer.',
        },
    },
    winTennisMatchDailyQuest: {
        name: {
            ru: 'Подача принята',
            ua: 'Подача прийнята',
            en: 'Serve Returned',
            de: 'Aufschlag angenommen',
            pl: 'Serw przyjęty',
        },
        desc: {
            ru: 'Выйди на корт и выиграй партию в теннис. Соперник может быть живым или машиной - победа засчитывается любая.',
            ua: 'Вийди на корт і виграй партію в теніс. Суперник може бути живим або машиною - перемога зараховується будь-яка.',
            en: 'Get out on the court and win a tennis match. Live opponent or machine, a win is a win.',
            de: 'Geh auf den Platz und gewinne ein Tennismatch. Ob echter Gegner oder Maschine, ein Sieg zählt.',
            pl: 'Wyjdź na kort i wygraj mecz tenisa. Żywy przeciwnik czy maszyna - liczy się każda wygrana.',
        },
    },
    sellFenceLootToBuyerDailyQuest: {
        name: {
            ru: 'Сбыт краденого',
            ua: 'Збут краденого',
            en: 'Moving the Goods',
            de: 'Ware absetzen',
            pl: 'Zbyt kradzionego',
        },
        desc: {
            ru: 'Сдай скупщику {{buyerName}} добычу на {{goal}} $. Он сидит в пустыне и берёт всё, что вынесли из чужих домов - вопросов не задаёт.',
            ua: 'Здай скупнику {{buyerName}} здобич на {{goal}} $. Він сидить у пустелі й бере все, що винесли з чужих будинків - питань не ставить.',
            en: 'Move {{goal}} $ worth of loot through the fence {{buyerName}}. He sits out in the desert and takes anything carried out of a house that is not yours - no questions.',
            de: 'Setz Beute für {{goal}} $ beim Hehler {{buyerName}} ab. Er sitzt draußen in der Wüste und nimmt alles, was aus fremden Häusern getragen wurde - ohne Fragen.',
            pl: 'Opchnij paserowi {{buyerName}} łup za {{goal}} $. Siedzi na pustyni i bierze wszystko, co wyniesiono z cudzych domów - bez pytań.',
        },
    },
};
