export const server = {
    church: {
        ru: 'Церковь',
        ua: 'Церква',
        en: 'Church',
        de: 'Kirche',
        pl: 'Kościół',
    },
    automarket: {
        ua: 'Авторинок',
        en: 'Automarket',
        ru: 'Авторынок',
        de: 'Automarkt',
        pl: 'Automarket',
        zh: '汽车市场',
    },
    productShop: {
        ua: 'Магазин 24/7',
        en: 'Shop 24/7',
        ru: 'Магазин 24/7',
        de: 'Supermarkt',
        pl: 'Sklep convenience',
        zh: '24/7便利店',
    },
    clothesShop: {
        ua: 'Магазин одягу',
        en: 'Clothing Store',
        ru: 'Магазин одежды',
        de: 'Bekleidungsgeschäft',
        pl: 'Sklep z odzieżą',
        zh: '服装店',
    },
    gunShop: {
        ua: 'Збройний магазин',
        en: 'Gun Shop',
        ru: 'Магазин оружия',
        de: 'Waffenladen',
        pl: 'Sklep z bronią',
        zh: '武装国度',
    },
    barberShop: {
        ua: 'Перукарня',
        en: 'Barber Shop',
        ru: 'Барбершоп',
        de: 'Barbershop',
        pl: 'Barber Shop',
        zh: '理发店',
    },
    trucker: {
        ru: 'Грузоперевозчик',
        ua: 'Вантажоперевiзник',
        en: 'Trucker',
        de: 'Lkwjob',
        pl: 'Przewoźnik towarowy',
        zh: '卡车司机',
    },
    trucker2: {
        ru: 'Дальнобойщик',
        en: 'Trucker',
        de: 'Trucker',
        pl: 'Kierowca ciężarówki',
        ua: 'Далекобiйник',
        zh: '卡车司机2',
    },
    delivery: {
        ua: 'Курьер',
        en: 'Delivery',
        ru: 'Курьер',
        de: 'Lieferung',
        pl: 'Dostawa',
        zh: '递送',
    },
    bus: {
        ru: 'Автобусник',
        ua: 'Автобусник',
        en: 'Bus Driver',
        de: 'Busfahrer',
        pl: 'Autobusnik',
        zh: '公共汽车司机',
    },
    farm: {
        ru: 'Ферма',
        ua: 'Ферма',
        en: 'Farm',
        de: 'Bauernhof',
        pl: 'Farma',
        zh: '农场',
    },
    quarry: {
        ru: 'Карьер',
        ua: "Кар'ер",
        en: 'Quarry',
        de: 'Steinbruch',
        pl: 'Kamieniołom',
    },
    rent: {
        ua: 'Оренда Т/З',
        en: 'Car Rental',
        ru: 'Аренда Т/С',
        de: 'Autovermietung',
        pl: 'Wynajem samochodów',
        zh: '汽车租赁',
    },
    hospital: {
        ua: 'Лiкарня',
        en: 'Hospital',
        ru: 'Больница',
        de: 'Krankenhaus',
        pl: 'Szpital',
        zh: '医院',
    },
    bank: {
        ru: 'Отделение банка',
        en: 'Bank Branch',
        ua: 'Вiддiлення банку',
        de: 'Bank',
        pl: 'Oddział banku',
        zh: '银行分行',
    },
    atm: {
        ru: 'Банкомат',
        en: 'ATM',
        ua: 'Банкомат',
        de: 'ATM',
        pl: 'Bankomat',
        zh: 'ATM',
    },
    quest: {
        ru: 'Квестовое задание',
        ua: 'Квестове завдання',
        en: 'Quest',
        de: 'Quest',
        pl: 'Zadanie questowe',
        zh: '任务',
    },
    strangersAndOthers: {
        ru: 'Чудаки и прочие незнакомцы',
        ua: 'Диваки та інші незнайомці',
        en: 'Oddballs and other strangers',
        de: 'Sonderlinge und andere Fremde',
        pl: 'Dziwacy i inni nieznajomi',
        zh: '怪人和其他陌生人',
    },
    santa: {
        ru: 'Санта-Клаус',
        ua: 'Санта-Клаус',
        en: 'Santa Claus',
        de: 'Santa Claus',
        pl: 'Święty Mikołaj',
        zh: '圣诞老人',
    },
    cityhall: {
        ru: 'Мэрия',
        ua: 'Мерiя',
        en: 'City Hall',
        de: 'Rathaus',
        pl: 'Ratusz',
        zh: '市政厅',
    },
    gunClub: {
        ru: 'Тир',
        ua: 'Тир',
        en: 'Shooting range',
        de: 'Schießstand',
        pl: 'Strzelnica',
        zh: '射击场',
    },
    airdrop: {
        ru: 'Air drop',
        ua: 'Air drop',
        en: 'Air drop',
        pl: 'Air drop',
        de: 'Airdrop',
        zh: '空投',
    },
    fishing: {
        ru: 'Зона для рыбалки',
        ua: 'Зона для риболовлi',
        en: 'Fishing area',
        de: 'Angelgebiet',
        pl: 'Strefa wędkowania',
        zh: '渔区',
    },
    tattooSalon: {
        ru: 'Тату-Салон',
        ua: 'Тату-Салон',
        en: 'Tattoo Shop',
        de: 'Tattoo-Studio',
        pl: 'Studio Tatuażu',
    },
    carPartyParking: {
        ru: 'Паркинг автолюбителей',
        ua: 'Паркінг автолюбителів',
        en: "Car Enthusiasts' Parking",
        de: 'Parkplatz für Autoliebhaber',
        pl: 'Parking dla miłośników samochodów',
    },
    carPartyParkingExit: {
        ru: 'Выезд из паркинга',
        ua: 'Виїзд з паркінгу',
        en: 'Parking exit',
        de: 'Parkausfahrt',
        pl: 'Wyjazd z parkingu',
    },
    burgerShot: {
        ru: 'Burger Shot',
        ua: 'Burger Shot',
        en: 'Burger Shot',
        de: 'Burger Shot',
        pl: 'Burger Shot',
    },
    carWash: {
        ru: 'Автомойка',
        ua: 'Автомийка',
        en: 'Car Wash',
        de: 'Autowäsche',
        pl: 'Myjnia samochodowa',
    },
    gym: {
        ru: 'Тренажерный зал',
        ua: 'Тренажерний зал',
        en: 'Gym',
        de: 'Fitnessstudio',
        pl: 'Siłownia',
    },
    factions: {
        sang: {
            ru: 'Армия',
            ua: 'Армія',
            en: 'SANG',
            de: 'SANG',
            pl: 'SANG',
        },
        LSPD: {
            ru: 'Полиция',
            ua: 'Поліція',
            en: 'LSPD',
            de: 'LSPD',
            pl: 'LSPD',
        },
        sheriff: {
            ru: 'Шериф',
            ua: 'Шериф',
            en: 'Sheriff Department',
            de: 'Sheriff-Abteilung',
            pl: 'Departament Szeryfa',
        },
        fib: {
            ru: 'ФБР',
            ua: 'ФБР',
            en: 'FIB',
            de: 'FIB',
            pl: 'FIB',
        },
        ems: {
            ru: 'Скорая помощь',
            ua: 'Швидка допомога',
            en: 'EMS',
            de: 'Rettungsdienst',
            pl: 'Pogotowie',
        },
        weazelNews: {
            ru: 'Weazel News',
            ua: 'Weazel News',
            en: 'Weazel News',
            de: 'Weazel News',
            pl: 'Weazel News',
        },
        families: {
            ru: 'The Families',
            ua: 'The Families',
            en: 'The Families',
            de: 'The Families',
            pl: 'The Families',
        },
        ballas: {
            ru: 'Ballas',
            ua: 'Ballas',
            en: 'Ballas',
            de: 'Ballas',
            pl: 'Ballas',
        },
        vagos: {
            ru: 'LS Vagos',
            ua: 'LS Vagos',
            en: 'LS Vagos',
            de: 'LS Vagos',
            pl: 'LS Vagos',
        },
        bloods: {
            ru: 'Blood Street Gang',
            ua: 'Blood Street Gang',
            en: 'Blood Street Gang',
            de: 'Blood Street Gang',
            pl: 'Blood Street Gang',
        },
        marabunta: {
            ru: 'Marabunta Grande',
            ua: 'Marabunta Grande',
            en: 'Marabunta Grande',
            de: 'Marabunta Grande',
            pl: 'Marabunta Grande',
        },
    },
};
