export const server = {
    automarket: {
        ua: 'Авторинок',
        en: 'Automarket',
        ru: 'Авторынок',
        de: 'Automarkt',
        pl: 'Automarket',
    },
    productShop: {
        ua: 'Магазин 24/7',
        en: 'Shop 24/7',
        ru: 'Магазин 24/7',
        de: 'Supermarkt',
        pl: 'Sklep convenience',
    },
    clothesShop: {
        ua: 'Магазин одягу',
        en: 'Clothing Store',
        ru: 'Магазин одежды',
        de: 'Bekleidungsgeschäft',
        pl: 'Sklep z odzieżą',
    },
    gunShop: {
        ua: 'Збройний магазин',
        en: 'Gun Shop',
        ru: 'Магазин оружия',
        de: 'Waffengeschäft',
        pl: 'Sklep z bronią',
    },
    barberShop: {
        ua: 'Перукарня',
        en: 'Barber Shop',
        ru: 'Барбершоп',
        de: 'Barbershop',
        pl: 'Barber Shop',
    },
    tattooShop: {
        ua: 'Тату салон',
        en: 'Tattoo Shop',
        ru: 'Тату салон',
        de: 'Tattoo-Studio',
        pl: 'Studio tatuażu',
    },
    trucker: {
        ru: 'Грузоперевозчик',
        ua: 'Вантажоперевiзник',
        en: 'Trucker',
        de: 'Frachtführer',
        pl: 'Przewoźnik towarowy',
    },
    trucker2: {
        ru: 'Дальнобойщик',
        en: 'Trucker',
        de: 'Trucker',
        pl: 'Kierowca ciężarówki',
        ua: 'Далекобійник',
    },
    delivery: {
        ua: 'Курьер',
        en: 'Delivery',
        ru: 'Курьер',
        de: 'Lieferung',
        pl: 'Dostawa',
    },
    bus: {
        ru: 'Автобусник',
        ua: 'Автобусник',
        en: 'Bus Driver',
        de: 'Busleiter',
        pl: 'Autobusnik',
    },
    farm: {
        ru: 'Ферма',
        ua: 'Ферма',
        en: 'Farm',
        de: 'Bauernhof',
        pl: 'Farma',
    },
    rent: {
        ua: 'Оренда Т/З',
        en: 'Car Rental',
        ru: 'Аренда Т/С',
        de: 'Autovermietung',
        pl: 'Wynajem samochodów',
    },
    hospital: {
        ua: 'Лiкарня',
        en: 'Hospital',
        ru: 'Больница',
        de: 'Krankenhaus',
        pl: 'Szpital',
    },
    bank: {
        ru: 'Отделение банка',
        en: 'Bank Branch',
        ua: 'Вiддiлення банку',
        de: 'Bankfiliale',
        pl: 'Oddział banku',
    },
    atm: {
        ru: 'Банкомат',
        en: 'ATM',
        ua: 'Банкомат',
        de: 'ATM',
        pl: 'Bankomat',
    },
    quest: {
        ru: 'Квестовое задание',
        ua: 'Квестове завдання',
        en: 'Quest',
        de: 'Quest',
        pl: 'Zadanie questowe',
    },
    strangersAndOthers: {
        ru: 'Чудаки и прочие незнакомцы',
        ua: 'Диваки та інші незнайомці',
        en: 'Oddballs and other strangers',
        de: 'Sonderlinge und andere Fremde',
        pl: 'Dziwacy i inni nieznajomi',
    },
    santa: {
        ru: 'Санта-Клаус',
        ua: 'Санта-Клаус',
        en: 'Santa Claus',
        de: 'Santa Claus',
        pl: 'Święty Mikołaj',
    },
    cityhall: {
        ru: 'Мэрия',
        ua: 'Мерiя',
        en: 'City Hall',
        de: 'Rathaus',
        pl: 'Ratusz',
    },
    gunClub: {
        ru: 'Тир',
        ua: 'Тир',
        en: 'Shooting range',
        de: 'Schießstand',
        pl: 'Strzelnica',
    },
    airdrop: {
        ru: 'Air drop',
        ua: 'Air drop',
        en: 'Air drop',
        pl: 'Air drop',
        de: 'Air drop',
    },
    fishing: {
        ru: 'Зона для рыбалки',
        ua: 'Зона для риболовлi',
        en: 'Fishing area',
        de: 'Angelgebiet',
        pl: 'Strefa wędkowania',
    },
};
