export const notify = {
    header: {
        ru: 'Склад',
        ua: 'Склад',
        en: 'Warehouse',
        de: 'Lager',
        pl: 'Magazyn',
    },
};

export const errors = {
    notPurchased: {
        ru: 'Этот склад не куплен.',
        ua: 'Цей склад не куплено.',
        en: 'This warehouse is not purchased.',
        de: 'Dieses Lager ist nicht gekauft.',
        pl: 'Ten magazyn nie jest kupiony.',
    },
    notYourOrg: {
        ru: 'Этот склад принадлежит другой организации.',
        ua: 'Цей склад належить іншій організації.',
        en: 'This warehouse belongs to another organization.',
        de: 'Dieses Lager gehört einer anderen Organisation.',
        pl: 'Ten magazyn należy do innej organizacji.',
    },
    notYours: {
        ru: 'У вас нет склада в этом здании.',
        ua: 'У вас немає складу в цій будівлі.',
        en: 'You do not hold a premise in this building.',
        de: 'Sie besitzen in diesem Gebäude kein Lager.',
        pl: 'Nie masz lokalu w tym budynku.',
    },
    noChests: {
        ru: 'На складе нет ни одного сундука. Создайте его внутри помещения.',
        ua: 'На складі немає жодної скрині. Створіть її всередині приміщення.',
        en: 'The warehouse has no chests. Create one inside the premise.',
        de: 'Das Lager hat keine Truhen. Legen Sie drinnen eine an.',
        pl: 'Magazyn nie ma żadnej skrzyni. Utwórz ją wewnątrz lokalu.',
    },
    chestGone: {
        ru: 'Этого сундука больше нет.',
        ua: 'Цієї скрині більше немає.',
        en: 'That chest no longer exists.',
        de: 'Diese Truhe existiert nicht mehr.',
        pl: 'Ta skrzynia już nie istnieje.',
    },
    chestLimit: {
        ru: 'Достигнут предел сундуков для этого склада: {{limit}}.',
        ua: 'Досягнуто межі скринь для цього складу: {{limit}}.',
        en: 'This warehouse is at its chest limit: {{limit}}.',
        de: 'Dieses Lager hat sein Truhenlimit erreicht: {{limit}}.',
        pl: 'Ten magazyn osiągnął limit skrzyń: {{limit}}.',
    },
    chestDuplicate: {
        ru: 'Сундук с таким названием уже есть.',
        ua: 'Скриня з такою назвою вже є.',
        en: 'A chest with that name already exists.',
        de: 'Eine Truhe mit diesem Namen existiert bereits.',
        pl: 'Skrzynia o tej nazwie już istnieje.',
    },
    chestName: {
        ru: 'Название сундука: от 1 до {{max}} символов, только буквы, цифры и знаки препинания.',
        ua: 'Назва скрині: від 1 до {{max}} символів, лише літери, цифри та розділові знаки.',
        en: 'Chest name must be 1 to {{max}} characters: letters, digits and punctuation only.',
        de: 'Der Truhenname muss 1 bis {{max}} Zeichen lang sein: nur Buchstaben, Ziffern und Satzzeichen.',
        pl: 'Nazwa skrzyni musi mieć od 1 do {{max}} znaków: tylko litery, cyfry i znaki interpunkcyjne.',
    },
    noAccess: {
        ru: 'У вас нет прав на доступ к складу.',
        ua: 'У вас немає прав доступу до складу.',
        en: 'You do not have access to the warehouse.',
        de: 'Sie haben keinen Zugriff auf das Lager.',
        pl: 'Nie masz dostępu do magazynu.',
    },
    depositOnly: {
        ru: 'У вас право только на пополнение склада, забирать предметы запрещено.',
        ua: 'У вас право лише на поповнення складу, забирати предмети заборонено.',
        en: 'Your permission allows depositing only - taking items is forbidden.',
        de: 'Ihre Berechtigung erlaubt nur das Einlagern - das Entnehmen ist verboten.',
        pl: 'Masz prawo tylko do deponowania - zabieranie przedmiotów jest zabronione.',
    },
    loadingNotInVehicle: {
        ru: 'Сядьте в транспорт с грузом, чтобы воспользоваться зоной погрузки.',
        ua: 'Сядьте у транспорт з вантажем, щоб скористатися зоною завантаження.',
        en: 'Get into a cargo vehicle to use the loading zone.',
        de: 'Steigen Sie in ein Frachtfahrzeug, um die Ladezone zu nutzen.',
        pl: 'Wsiądź do pojazdu z ładunkiem, aby skorzystać ze strefy załadunku.',
    },
    loadingNotDriver: {
        ru: 'Только водитель может пользоваться зоной погрузки.',
        ua: 'Тільки водій може користуватися зоною завантаження.',
        en: 'Only the driver can use the loading zone.',
        de: 'Nur der Fahrer kann die Ladezone benutzen.',
        pl: 'Tylko kierowca może korzystać ze strefy załadunku.',
    },
    loadingNoTrunk: {
        ru: 'У этого транспорта нет багажника для груза.',
        ua: 'У цього транспорту немає багажника для вантажу.',
        en: 'This vehicle has no cargo hold.',
        de: 'Dieses Fahrzeug hat keinen Laderaum.',
        pl: 'Ten pojazd nie ma przestrzeni ładunkowej.',
    },
    noOrganization: {
        ru: 'Вы не состоите в организации.',
        ua: 'Ви не перебуваєте в організації.',
        en: 'You are not in an organization.',
        de: 'Sie sind in keiner Organisation.',
        pl: 'Nie jesteś w organizacji.',
    },
    returnNotAllowed: {
        ru: 'Вернуть склад владельцу может только лидер организации.',
        ua: 'Повернути склад власнику може лише лідер організації.',
        en: 'Only the organization leader can hand the warehouse back.',
        de: 'Nur der Organisationsleiter kann das Lager zurückgeben.',
        pl: 'Tylko lider organizacji może zwrócić magazyn.',
    },
    returnNoOwner: {
        ru: 'Этот склад организация купила сама — возвращать его некому.',
        ua: 'Цей склад організація купила сама — повертати його нема кому.',
        en: 'The organization bought this warehouse itself - there is nobody to hand it back to.',
        de: 'Die Organisation hat dieses Lager selbst gekauft - es gibt niemanden, dem es zurückgegeben werden könnte.',
        pl: 'Organizacja sama kupiła ten magazyn - nie ma go komu zwrócić.',
    },
    returnOwnerHasWarehouse: {
        ru: 'У прежнего владельца уже есть личный склад — вернуть этот нельзя.',
        ua: 'У колишнього власника вже є особистий склад — повернути цей не можна.',
        en: 'The former owner already has a personal warehouse - this one cannot go back.',
        de: 'Der frühere Eigentümer hat bereits ein persönliches Lager - dieses kann nicht zurück.',
        pl: 'Poprzedni właściciel ma już osobisty magazyn - tego nie można zwrócić.',
    },
    returnFailed: {
        ru: 'Не удалось вернуть склад владельцу.',
        ua: 'Не вдалося повернути склад власнику.',
        en: 'Failed to hand the warehouse back.',
        de: 'Das Lager konnte nicht zurückgegeben werden.',
        pl: 'Nie udało się zwrócić magazynu.',
    },
};

export const taxCycle = {
    confiscation: {
        leaderRefund: {
            ru: 'Склад {{orgName}} конфискован. Вам возвращено ${{amount}}.',
            ua: 'Склад {{orgName}} конфісковано. Вам повернуто ${{amount}}.',
            en: 'Warehouse of {{orgName}} confiscated. You received ${{amount}}.',
            de: 'Lager von {{orgName}} beschlagnahmt. Sie erhielten ${{amount}}.',
            pl: 'Magazyn {{orgName}} skonfiskowany. Otrzymałeś ${{amount}}.',
        },
        sms: {
            ru: 'Склад {{orgName}} конфискован за неуплату. Возврат: {{percent}}% стоимости.',
            ua: 'Склад {{orgName}} конфісковано за несплату. Повернення: {{percent}}% вартості.',
            en: 'Warehouse {{orgName}} confiscated for non-payment. Refund: {{percent}}% of value.',
            de: 'Lager {{orgName}} wegen Nichtzahlung beschlagnahmt. Erstattung: {{percent}}% des Wertes.',
            pl: 'Magazyn {{orgName}} skonfiskowany za niepłacenie. Zwrot: {{percent}}% wartości.',
        },
        notifyMembers: {
            ru: 'Склад {{orgName}} конфискован за неуплату налога.',
            ua: 'Склад {{orgName}} конфісковано за несплату податку.',
            en: 'Warehouse of {{orgName}} confiscated for unpaid tax.',
            de: 'Lager von {{orgName}} wegen unbezahlter Steuern beschlagnahmt.',
            pl: 'Magazyn {{orgName}} skonfiskowany z powodu niezapłaconego podatku.',
        },
    },
    debt: {
        started: {
            ru: 'Не хватило средств на налог за склад {{orgName}} (${{rent}}). У вас 72 часа на погашение долга.',
            ua: 'Не вистачило коштів на податок за склад {{orgName}} (${{rent}}). У вас 72 години на погашення боргу.',
            en: 'Not enough funds for warehouse tax {{orgName}} (${{rent}}). You have 72 hours to repay the debt.',
            de: 'Nicht genügend Mittel für die Lagersteuer {{orgName}} (${{rent}}). Sie haben 72 Stunden zur Tilgung.',
            pl: 'Brak środków na podatek od magazynu {{orgName}} (${{rent}}). Masz 72 godziny na spłatę długu.',
        },
        reminder: {
            ru: 'Склад {{orgName}}: долг по налогу. До конфискации осталось {{hoursLeft}}ч (налог ${{rent}}).',
            ua: 'Склад {{orgName}}: борг по податку. До конфіскації залишилось {{hoursLeft}}год (податок ${{rent}}).',
            en: 'Warehouse {{orgName}}: tax debt. {{hoursLeft}}h until confiscation (tax ${{rent}}).',
            de: 'Lager {{orgName}}: Steuerschuld. {{hoursLeft}}h bis zur Beschlagnahmung (Steuer ${{rent}}).',
            pl: 'Magazyn {{orgName}}: dług podatkowy. Do konfiskaty zostało {{hoursLeft}}h (podatek ${{rent}}).',
        },
        cleared: {
            ru: 'Долг по налогу склада {{orgName}} погашен.',
            ua: 'Борг по податку складу {{orgName}} погашений.',
            en: 'Warehouse tax debt cleared for {{orgName}}.',
            de: 'Steuerschuld des Lagers {{orgName}} beglichen.',
            pl: 'Dług podatkowy magazynu {{orgName}} spłacony.',
        },
    },
    personal: {
        debtStarted: {
            ru: 'Не хватило средств на налоговом счёте за склад #{{slotId}} в {{building}} (${{rent}}). У вас 72 часа на погашение долга.',
            ua: 'Не вистачило коштів на податковому рахунку за склад #{{slotId}} в {{building}} (${{rent}}). У вас 72 години на погашення боргу.',
            en: 'Not enough funds on the tax account for warehouse #{{slotId}} in {{building}} (${{rent}}). You have 72 hours to repay the debt.',
            de: 'Nicht genügend Mittel auf dem Steuerkonto für Lager #{{slotId}} in {{building}} (${{rent}}). Sie haben 72 Stunden zur Tilgung.',
            pl: 'Brak środków na koncie podatkowym za magazyn #{{slotId}} w {{building}} (${{rent}}). Masz 72 godziny na spłatę długu.',
        },
        debtReminder: {
            ru: 'Склад #{{slotId}} в {{building}}: долг по налогу. До конфискации осталось {{hoursLeft}}ч (налог ${{rent}}).',
            ua: 'Склад #{{slotId}} в {{building}}: борг по податку. До конфіскації залишилось {{hoursLeft}}год (податок ${{rent}}).',
            en: 'Warehouse #{{slotId}} in {{building}}: tax debt. {{hoursLeft}}h until confiscation (tax ${{rent}}).',
            de: 'Lager #{{slotId}} in {{building}}: Steuerschuld. {{hoursLeft}}h bis zur Beschlagnahmung (Steuer ${{rent}}).',
            pl: 'Magazyn #{{slotId}} w {{building}}: dług podatkowy. Do konfiskaty zostało {{hoursLeft}}h (podatek ${{rent}}).',
        },
        debtCleared: {
            ru: 'Долг по налогу за склад #{{slotId}} в {{building}} погашен.',
            ua: 'Борг по податку за склад #{{slotId}} в {{building}} погашений.',
            en: 'Tax debt cleared for warehouse #{{slotId}} in {{building}}.',
            de: 'Steuerschuld für Lager #{{slotId}} in {{building}} beglichen.',
            pl: 'Dług podatkowy za magazyn #{{slotId}} w {{building}} spłacony.',
        },
        confiscated: {
            ru: 'Склад #{{slotId}} в {{building}} конфискован за неуплату налога. Вам возвращено ${{amount}}.',
            ua: 'Склад #{{slotId}} в {{building}} конфісковано за несплату податку. Вам повернуто ${{amount}}.',
            en: 'Warehouse #{{slotId}} in {{building}} confiscated for unpaid tax. You received ${{amount}}.',
            de: 'Lager #{{slotId}} in {{building}} wegen unbezahlter Steuern beschlagnahmt. Sie erhielten ${{amount}}.',
            pl: 'Magazyn #{{slotId}} w {{building}} skonfiskowany za niezapłacony podatek. Otrzymałeś ${{amount}}.',
        },
        sms: {
            ru: 'Склад #{{slotId}} в {{building}} конфискован за неуплату. Возврат: {{percent}}% стоимости.',
            ua: 'Склад #{{slotId}} в {{building}} конфісковано за несплату. Повернення: {{percent}}% вартості.',
            en: 'Warehouse #{{slotId}} in {{building}} confiscated for non-payment. Refund: {{percent}}% of value.',
            de: 'Lager #{{slotId}} in {{building}} wegen Nichtzahlung beschlagnahmt. Erstattung: {{percent}}% des Wertes.',
            pl: 'Magazyn #{{slotId}} w {{building}} skonfiskowany za niepłacenie. Zwrot: {{percent}}% wartości.',
        },
    },
};
