export const server = {
    notifyTitle: {
        ru: 'Склад',
        ua: 'Склад',
        en: 'Warehouse',
        de: 'Lager',
        pl: 'Magazyn',
    },
    modal: {
        buy: {
            title: {
                ru: 'Покупка склада',
                ua: 'Купівля складу',
                en: 'Warehouse Purchase',
                de: 'Lagerkauf',
                pl: 'Zakup magazynu',
            },
            message: {
                ru: 'Вы уверены, что хотите купить склад #{{slotId}} в {{building}} за ${{price}}? Средства будут списаны с баланса организации.',
                ua: 'Ви впевнені, що хочете купити склад #{{slotId}} в {{building}} за ${{price}}? Кошти будуть списані з балансу організації.',
                en: 'Are you sure you want to buy warehouse #{{slotId}} in {{building}} for ${{price}}? Funds will be deducted from the organization balance.',
                de: 'Möchten Sie Lager #{{slotId}} in {{building}} für ${{price}} kaufen? Der Betrag wird vom Organisationskonto abgebucht.',
                pl: 'Czy na pewno chcesz kupić magazyn #{{slotId}} w {{building}} za ${{price}}? Środki zostaną pobrane z konta organizacji.',
            },
            confirm: {
                ru: 'Купить',
                ua: 'Купити',
                en: 'Buy',
                de: 'Kaufen',
                pl: 'Kup',
            },
            cancel: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
        },
    },
    errors: {
        notReady: {
            ru: 'Этот склад ещё не доделан администрацией.',
            ua: 'Цей склад ще не доопрацьовано адміністрацією.',
            en: 'This warehouse is not configured yet.',
            de: 'Dieses Lager ist noch nicht eingerichtet.',
            pl: 'Ten magazyn nie jest jeszcze skonfigurowany.',
        },
        noOrganization: {
            ru: 'Вы не состоите в организации.',
            ua: 'Ви не перебуваєте в організації.',
            en: 'You are not in an organization.',
            de: 'Sie sind nicht in einer Organisation.',
            pl: 'Nie jesteś w organizacji.',
        },
        notLeader: {
            ru: 'Только лидер организации может покупать склады.',
            ua: 'Тільки лідер організації може купувати склади.',
            en: 'Only the organization leader can buy warehouses.',
            de: 'Nur der Organisationsleiter kann Lager kaufen.',
            pl: 'Tylko lider organizacji może kupować magazyny.',
        },
        alreadyOwned: {
            ru: 'Этот склад уже куплен.',
            ua: 'Цей склад вже куплено.',
            en: 'This warehouse is already owned.',
            de: 'Dieses Lager ist bereits gekauft.',
            pl: 'Ten magazyn jest już kupiony.',
        },
        orgAlreadyHasWarehouse: {
            ru: 'Ваша организация уже владеет складом.',
            ua: 'Ваша організація вже володіє складом.',
            en: 'Your organization already owns a warehouse.',
            de: 'Ihre Organisation besitzt bereits ein Lager.',
            pl: 'Twoja organizacja już posiada magazyn.',
        },
        notEnoughMoney: {
            ru: 'Недостаточно средств на балансе организации. Необходимо: ${{price}}',
            ua: 'Недостатньо коштів на балансі організації. Потрібно: ${{price}}',
            en: 'Not enough funds in the organization balance. Required: ${{price}}',
            de: 'Nicht genügend Mittel auf dem Organisationskonto. Erforderlich: ${{price}}',
            pl: 'Niewystarczające środki na koncie organizacji. Wymagane: ${{price}}',
        },
        takeFailed: {
            ru: 'Не удалось списать средства с баланса организации.',
            ua: 'Не вдалося списати кошти з балансу організації.',
            en: 'Failed to deduct funds from the organization balance.',
            de: 'Konnte den Betrag nicht vom Organisationskonto abbuchen.',
            pl: 'Nie udało się pobrać środków z konta organizacji.',
        },
        purchaseFailed: {
            ru: 'Не удалось приобрести склад. Средства возвращены.',
            ua: 'Не вдалося придбати склад. Кошти повернуто.',
            en: 'Failed to purchase the warehouse. Funds have been refunded.',
            de: 'Lagerkauf fehlgeschlagen. Betrag wurde erstattet.',
            pl: 'Nie udało się kupić magazynu. Środki zostały zwrócone.',
        },
        notPurchased: {
            ru: 'Этот склад не куплен.',
            ua: 'Цей склад не куплено.',
            en: 'This warehouse is not purchased.',
            de: 'Dieses Lager ist nicht gekauft.',
            pl: 'Ten magazyn nie jest kupiony.',
        },
        notYourOrg: {
            ru: 'Этот склад принадлежит другой организации.',
            ua: 'Цей склад належить іншій організації.',
            en: 'This warehouse belongs to another organization.',
            de: 'Dieses Lager gehört einer anderen Organisation.',
            pl: 'Ten magazyn należy do innej organizacji.',
        },
        noAccess: {
            ru: 'У вас нет прав на работу со складом.',
            ua: 'У вас немає прав на роботу зі складом.',
            en: 'You do not have access to this warehouse.',
            de: 'Sie haben keinen Zugriff auf dieses Lager.',
            pl: 'Nie masz dostępu do tego magazynu.',
        },
        loadingNotInVehicle: {
            ru: 'Чтобы воспользоваться загрузочной зоной, нужно сидеть в машине.',
            ua: 'Щоб скористатися завантажувальною зоною, потрібно сидіти в машині.',
            en: 'You must be in a vehicle to use the loading zone.',
            de: 'Sie müssen sich in einem Fahrzeug befinden, um die Ladezone zu nutzen.',
            pl: 'Aby skorzystać ze strefy załadunku, musisz siedzieć w pojeździe.',
        },
        loadingNotDriver: {
            ru: 'Только водитель может работать с загрузочной зоной.',
            ua: 'Тільки водій може працювати із завантажувальною зоною.',
            en: 'Only the driver can use the loading zone.',
            de: 'Nur der Fahrer kann die Ladezone nutzen.',
            pl: 'Tylko kierowca może korzystać ze strefy załadunku.',
        },
        loadingNoTrunk: {
            ru: 'У этой машины нет багажника, доступного для загрузки.',
            ua: 'У цієї машини немає багажника, доступного для завантаження.',
            en: 'This vehicle has no trunk available for loading.',
            de: 'Dieses Fahrzeug hat keinen Kofferraum zum Beladen.',
            pl: 'Ten pojazd nie ma bagażnika dostępnego do załadunku.',
        },
    },
    success: {
        purchased: {
            ru: 'Склад #{{slotId}} в {{building}} успешно приобретён за ${{price}}',
            ua: 'Склад #{{slotId}} в {{building}} успішно придбано за ${{price}}',
            en: 'Warehouse #{{slotId}} in {{building}} successfully purchased for ${{price}}',
            de: 'Lager #{{slotId}} in {{building}} erfolgreich gekauft für ${{price}}',
            pl: 'Magazyn #{{slotId}} w {{building}} kupiony za ${{price}}',
        },
    },
};
