export const cashier = {
    header: {
        ru: "КАССА <span style='color:var(--golden-sunshine)'>КАЗИНО</span>",
        ua: "КАСА <span style='color:var(--golden-sunshine)'>КАЗИНО</span>",
        en: "CASINO <span style='color:var(--golden-sunshine)'>CASHIER</span>",
        de: "KASSE <span style='color:var(--golden-sunshine)'>KASINO</span>",
        pl: "KASA <span style='color:var(--golden-sunshine)'>KASINO</span>",
    },
    buyChipsName: {
        ru: "Покупка фишек",
        ua: "Купівля фішок",
        en: "Buy chips",
        de: "Chips kaufen",
        pl: "Kupić żetony",
    },
    buyChipsDesc: {
        ru: "Вы можете намного выгодней купить фишки в виде карточек",
        ua: "Ви можете набагато вигідноше купити фішки у вигляді карток",
        en: "You can buy chips in card packs for a much better price",
        de: "Sie können Chips in Kartenpaketen zu einem viel besseren Preis kaufen",
        pl: "Możesz kupić żetony w pakietach kart w o wiele lepszej cenie",
    },
    buySellChipsName: {
        ru: "Купить / продать фишки",
        ua: "Купити / продати фішки",
        en: "Buy / sell chips",
        de: "Chips kaufen / verkaufen",
        pl: "Kup / sprzedaj żetony",
    },
    buySellChipsDesc: {
        ru: "Тут вы можете купить или продать определённое кол-во фишек.",
        ua: "Тут ви можете купити або продати певну кількість фішок.",
        en: "Here you can buy or sell a certain number of chips.",
        de: "Hier kannst du eine bestimmte Anzahl von Chips kaufen oder verkaufen.",
        pl: "Tutaj możesz kupić lub sprzedać określoną liczbę żetonów.",
    },
    buy: {
        ru: "Покупка",
        ua: "Купівля",
        en: "Buy",
        de: "Kaufen",
        pl: "Kupić",
    },
    sell: {
        ru: "Продажа",
        ua: "Продаж",
        en: "Sell",
        de: "Verkaufen",
        pl: "Sprzedać",
    },
    buyChips: {
        ru: "Купить фишки",
        ua: "Купити фішки",
        en: "Buy chips",
        de: "Chips kaufen",
        pl: "Kupić żetony",
    },
    sellChips: {
        ru: "Продать фишки",
        ua: "Продати фішки",
        en: "Sell chips",
        de: "Chips verkaufen",
        pl: "Sprzedać żetony",
    },
    inputQuantity: {
        ru: "Введите кол-во фишек",
        ua: "Введіть кількість фішок",
        en: "Enter the quantity of chips",
        de: "Geben Sie die Anzahl der Chips ein",
        pl: "Wprowadź ilość żetonów"
    },

    cashier: {
        ru: 'Касса',
        ua: 'Каса',
        en: 'Cashier',
        de: 'Kasse',
        pl: 'Kasa',
    },
    successBuy: {
        ru: 'Вы купили {{chips}} фишек за ${{money}}. Удачной игры!',
        ua: 'Ви купили {{chips}} фішок за ${{money}}. Удачі в грі!',
        en: 'You bought {{chips}} chips for ${{money}}. Good luck!',
        de: 'Du hast {{chips}} Chips für ${{money}} gekauft. Viel Glück!',
        pl: 'Kupiłeś {{chips}} żetonów za ${{money}}. Powodzenia!',
    },
    successSell: {
        ru: 'Вы продали {{chips}} фишек за ${{money}}.',
        ua: 'Ви продали {{chips}} фішок за ${{money}}.',
        en: 'You sold {{chips}} chips for ${{money}}.',
        de: 'Du hast {{chips}} Chips für ${{money}} verkauft.',
        pl: 'Sprzedałeś {{chips}} żetonów za ${{money}}.',
    },
    discord: {
        ru: 'Покупает фишки',
        ua: 'Купує фішки',
        en: 'Buying chips',
        de: 'Kauft Chips',
        pl: 'Kupuje żetony',
    },
}