export const server = {
    productShop: {
        ru: 'Магазин 24/7',
        ua: 'Магазин 24/7',
        en: '24/7 Store',
        de: '24/7 Laden',
        pl: 'Sklep 24/7',
        zh: '24小时便利店',
    },
    weaponShop: {
        ru: 'Магазин оружия',
        ua: 'Магазин зброї',
        en: 'Weapon Shop',
        de: 'Waffengeschäft',
        pl: 'Sklep z bronią',
        zh: '武器店',
    },
    clothesShop: {
        ru: 'Магазин одежды',
        ua: 'Магазин одягу',
        en: 'Clothes Shop',
        de: 'Kleidungsgeschäft',
        pl: 'Sklep odzieżowy',
        zh: '服装店',
    },
    thanksForBuy: {
        ru: 'Спасибо за покупку',
        ua: 'Дякуємо за покупку',
        en: 'Thanks for the purchase',
        de: 'Vielen Dank für den Kauf',
        pl: 'Dziękujemy za zakup',
        zh: '感谢您的购买',
    },
    youAlreadyHaveThisClothes: {
        ru: 'У вас уже есть эта одежда',
        ua: 'У вас вже є ця одяг',
        en: 'You already have this clothing',
        de: 'Du hast diese Kleidung bereits',
        pl: 'Masz już tę odzież',
        zh: '您已经拥有这件服装',
    },
    notEnoughSpace: {
        ru: 'Недостаточно места в инвентаре',
        ua: 'Недостатньо місця в інвентарі',
        en: 'Not enough space in the inventory',
        de: 'Nicht genügend Platz im Inventar',
        pl: 'Brak miejsca w inwentarzu',
        zh: '您的背包空间不足',
    },

    //
    noWeaponLicense: {
        ru: 'Нет лицензии оружия',
        ua: 'Немає ліцензії зброї',
        en: 'No weapon license',
        de: 'Keine Waffenlizenz',
        pl: 'Brak licencji broni',
        zh: '没有武器许可证',
    },
};