export const server = {
    productShop: {
        ru: 'Магазин 24/7',
        ua: 'Магазин 24/7',
        en: '24/7 Store',
        de: '24/7 Laden',
        pl: 'Sklep 24/7',
        zh: '24小时便利店',
    },
    weaponShop: {
        ru: 'Магазин оружия',
        ua: 'Магазин зброї',
        en: 'Weapon Shop',
        de: 'Waffengeschäft',
        pl: 'Sklep z bronią',
        zh: '武器店',
    },
    clothesShop: {
        ru: 'Магазин одежды',
        ua: 'Магазин одягу',
        en: 'Clothes Shop',
        de: 'Kleidungsgeschäft',
        pl: 'Sklep odzieżowy',
        zh: '服装店',
    },
    barberShop: {
        ru: 'Барбершоп',
        ua: 'Барбершоп',
        en: 'Barbershop',
        de: 'Friseur',
        pl: 'Barbershop',
    },
    tattooSalon: {
        ru: 'Тату-салон',
        ua: 'Тату-салон',
        en: 'Tattoo salon',
        de: 'Tattoo-Studio',
        pl: 'Salon tatuażu',
    },
    thanksForBuy: {
        ru: 'Спасибо за покупку',
        ua: 'Дякуємо за покупку',
        en: 'Thanks for the purchase',
        de: 'Vielen Dank für den Kauf',
        pl: 'Dziękujemy za zakup',
        zh: '感谢您的购买',
    },
    youRemovedTattoo: {
        ru: 'Вы успешно свели это тату',
        ua: 'Ви успішно вивели це тату',
        en: 'You successfully removed this tattoo',
        de: 'Du hast dieses Tattoo erfolgreich entfernt',
        pl: 'Udało ci się usunąć ten tatuaż',
    },
    youAlreadyHaveThisClothes: {
        ru: 'У вас уже есть эта одежда',
        ua: 'У вас вже є ця одяг',
        en: 'You already have this clothing',
        de: 'Du trägst diese Kleidung bereits',
        pl: 'Masz już tę odzież',
        zh: '您已经拥有这件服装',
    },
    chairAlreadyTaken: {
        ru: 'Кресло уже занято',
        ua: 'Крісло вже зайняте',
        en: 'The chair is already taken',
        de: 'Der Stuhl ist bereits besetzt',
        pl: 'Krzesło jest już zajęte',
    },
    notEnoughSpace: {
        ru: 'Недостаточно места в инвентаре',
        ua: 'Недостатньо місця в інвентарі',
        en: 'Not enough space in the inventory',
        de: 'Nicht genügend Platz im Inventar',
        pl: 'Brak miejsca w inwentarzu',
        zh: '您的背包空间不足',
    },

    youAlreadyHaveThisAppearance: {
        ru: 'У вас уже есть это',
        ua: 'У вас вже є це',
        en: 'You already have this',
        de: 'Du hast das bereits',
        pl: 'Już to masz',
    },
    youAlreadyHaveThisTattoo: {
        ru: 'У вас уже есть этот тату',
        ua: 'У вас вже є це тату',
        en: 'You already have this tattoo',
        de: 'Du hast dieses Tattoo bereits',
        pl: 'Masz już ten tatuaż',
    },
    //
    noWeaponLicense: {
        ru: 'Нет лицензии оружия',
        ua: 'Немає ліцензії зброї',
        en: 'No weapon license',
        de: 'Keine Waffenlizenz',
        pl: 'Brak licencji broni',
        zh: '没有武器许可证',
    },
    noFreeChairs: {
        ru: 'Нет свободных кресел',
        ua: 'Немає вільних крісел',
        en: 'No free chairs',
        de: 'Keine freien Stühle',
        pl: 'Brak wolnych krzeseł',
    },

    //
    closed: {
        ru: 'Магазин сейчас не работает',
        ua: 'Магазин зараз не працює',
        en: 'The store is currently closed',
        de: 'Der Laden ist derzeit geschlossen',
        pl: 'Sklep jest obecnie zamknięty',
    },
};
