export default {
    first: {
        welcomeToFarm: {
            ru: 'Приветствую на нашей ферме! Кем хочешь поработать?',
            ua: 'Вітаємо на нашій фермі! Ким хочеш працювати?',
            en: 'Welcome to our farm! What job would you like to do?',
            de: 'Willkommen auf unserem Bauernhof! Welche Arbeit möchtest du machen?',
            pl: 'Witamy na naszej farmie! Jaką pracę chcesz wykonywać?',
            ge: 'მოგესალმებით ჩვენს ფერმაში! რომელი საქმე გსურს გააკეთო?',
        },
        orange: {
            ru: 'Собирать апельсины',
            ua: 'Збирати апельсини',
            en: 'Pick oranges',
            de: 'Orangen pflücken',
            pl: 'Zbierać pomarańcze',
            ge: 'ფორთოხლების კრეფა',
        },
        growth: {
            ru: 'Сажать растения',
            ua: 'Садити рослини',
            en: 'Plant crops',
            de: 'Pflanzen anbauen',
            pl: 'Sadzenie roślin',
            ge: 'მცენარეების დარგვა',
        },
        tractor: {
            ru: 'Трактористом',
            ua: 'Трактористом',
            en: 'Tractor driver',
            de: 'Traktorfahrer',
            pl: 'Kierowca traktora',
            ge: 'ტრაქტორისტი',
        },

        letsGo: {
            ru: 'Поехали',
            ua: 'Поїхали',
            en: "Let's go",
            de: "Los geht's",
            pl: 'Jedziemy',
            ge: 'წადი',
        },
        later: {
            ru: 'Позже',
            ua: 'Пізніше',
            en: 'Later',
            de: 'Später',
            pl: 'Później',
            ge: 'მოგვიანებით',
        },
        orangeInfo: {
            ru: 'С сбором апельснов всё очень просто, подходишь к деревьям собираешь апельсины и потом относишь на склад и так пока не надоест, зарплата ${{salary}} за корзину, готов?',
            ua: 'Збирання апельсинів дуже просте: підходиш до дерев, збираєш апельсини і потім несеш на склад, і так доти, поки не набридне. Зарплата ${{salary}} за кошик. Готовий?',
            en: 'Picking oranges is very simple: you go to the trees, pick the oranges, and then take them to the warehouse. You do this until you get bored. The pay is ${{salary}} per basket. Ready?',
            de: 'Das Sammeln von Orangen ist sehr einfach: Du gehst zu den Bäumen, pflückst die Orangen und bringst sie dann zum Lager. Du machst das, bis du genug hast. Der Lohn beträgt ${{salary}} pro Korb. Bereit?',
            pl: 'Zbieranie pomarańczy jest bardzo proste: podchodzisz do drzew, zbierasz pomarańcze i potem zanoszisz je do magazynu. Robisz to, aż ci się znudzi. Płaca wynosi ${{salary}} za kosz. Gotowy?',
            ge: 'ფორთოხლების კრეფა ძალიან მარტივია: მიდიხარ ხეებთან, კრეფ ფორთოხლებს და მერე მიიტან საწყობში. ასე გააგრძელებ, სანამ არ მოგბეზრდება. ხელფასი ${{salary}} კალათაზე. მზად ხარ?',
        },
        growthInfo: {
            ru: 'Для этой работы тебе нужно иметь семена растений, их можно купить в магазине, также надо лейку, для каждой культуры своё поле по ходу дела разберешся, готов?',
            ua: 'Для цієї роботи тобі потрібне насіння рослин, яке можна купити в магазині. Також потрібна лійка. Для кожної культури своє поле, розберешся в процесі. Готовий?',
            en: "For this job, you need plant seeds, which can be bought in the store. You also need a watering can. Each crop has its own field; you'll figure it out as you go. Ready?",
            de: 'Für diese Arbeit brauchst du Pflanzensamen, die du im Laden kaufen kannst. Du brauchst auch eine Gießkanne. Jede Pflanze hat ihr eigenes Feld; du wirst es im Laufe der Zeit herausfinden. Bereit?',
            pl: 'Do tej pracy potrzebujesz nasion roślin, które można kupić w sklepie. Potrzebna jest także konewka. Każda roślina ma swoje pole, zorientujesz się w trakcie pracy. Gotowy?',
            ge: 'ამ საქმეში საჭიროა მცენარეების თესლი, რომელიც მაღაზიაში შეგიძლიათ შეიძინოთ. ასევე საჭიროა სარწყავი ჭურჭელი. თითოეული კულტურისთვის თავისი ველია; პროცესში გაგერკვევი. მზად ხარ?',
        },
        tractorInfo: {
            ru: 'Тракторист важнейшая часть фермы, без культивации полей нельзя садить на полях, зарплата в среднем около ${{salary}} за поле, готов?',
            ua: 'Тракторист - найважливіша частина ферми. Без культивації полів не можна садити на полях. Зарплата в середньому ${{salary}} за поле. Готовий?',
            en: "The tractor driver is the most important part of the farm. Without field cultivation, crops can't be planted. The average pay is ${{salary}} per field. Ready?",
            de: 'Der Traktorfahrer ist der wichtigste Teil des Bauernhofs. Ohne Feldbearbeitung können keine Pflanzen angebaut werden. Der Durchschnittslohn beträgt ${{salary}} pro Feld. Bereit?',
            pl: 'Traktorzysta jest najważniejszą częścią farmy. Bez uprawy pola nie można sadzić roślin. Średnia płaca wynosi ${{salary}} za pole. Gotowy?',
            ge: 'ტრაქტორისტი ფერმის უმნიშვნელოვანესი ნაწილია. ველების დამუშავების გარეშე არ შეიძლება დარგვა. ხელფასი საშუალოდ ${{salary}} ველზე. მზად ხარ?',
        },
    },
    second: {
        youWantToQuitAlready: {
            ru: 'Похоже ты хочешь уволиться, это так?',
            ua: 'Схоже, ти хочеш звільнитися, це так?',
            en: 'It looks like you want to quit, is that right?',
            de: 'Es sieht so aus, als ob du kündigen möchtest, stimmt das?',
            pl: 'Wygląda na to, że chcesz zrezygnować, czy to prawda?',
        },
        yes: {
            ru: 'Да',
            ua: 'Так',
            en: 'Yes',
            de: 'Ja',
            pl: 'Tak',
        },
        no: {
            ru: 'Я передумал',
            ua: 'Я передумав',
            en: "I've changed my mind",
            de: 'Ich habe es mir anders überlegt',
            pl: 'Zmieniłem zdanie',
        },
    },
};
