export default {
    first: {
        welcomeToFarm: {
            ru: 'Здравствуй. Я Марк, управляющий фермой. Хочешь поработать?',
            ua: 'Привіт. Я Марк, керівник ферми. Хочеш попрацювати?',
            en: "Hey there. I'm Mark, the farm manager. Want to work?",
            de: 'Hey. Ich bin Mark, der Farmleiter. Willst du arbeiten?',
            pl: 'Cześć. Jestem Mark, zarządzający farmą. Chcesz popracować?',
        },
        yesTellMeMore: {
            ru: 'Расскажите подробнее про ферму',
            ua: 'Розкажи докладніше про ферму',
            en: 'Tell me more about the farm',
            de: 'Erzähl mir mehr über die Farm',
            pl: 'Opowiedz mi więcej o farmie',
        },
        yesStartNow: {
            ru: 'Хочу устроиться',
            ua: 'Хочу влаштуватися',
            en: 'I want to start working',
            de: 'Ich will anfangen zu arbeiten',
            pl: 'Chcę zacząć pracę',
        },
        noExit: {
            ru: 'Сейчас нет',
            ua: 'Зараз ні',
            en: 'Not now',
            de: 'Jetzt nicht',
            pl: 'Nie teraz',
        },
        whatDoYouWantToKnow: {
            ru: 'Спрашивай. Что именно тебя интересует?',
            ua: 'Питай. Що саме тебе цікавить?',
            en: 'Ask away. What exactly are you curious about?',
            de: 'Frag ruhig. Was interessiert dich genau?',
            pl: 'Pytaj śmiało. Co dokładnie cię interesuje?',
        },
        aboutPlanting: {
            ru: 'Посадка культур и уровни',
            ua: 'Посадка культур і рівні',
            en: 'Planting crops and levels',
            de: 'Pflanzen und Level',
            pl: 'Sadzenie upraw i poziomy',
        },
        aboutTractor: {
            ru: 'Работа на тракторе',
            ua: 'Робота на тракторі',
            en: 'Tractor work',
            de: 'Arbeit mit dem Traktor',
            pl: 'Praca na traktorze',
        },
        aboutOranges: {
            ru: 'Сбор апельсинов',
            ua: 'Збір апельсинів',
            en: 'Orange picking',
            de: 'Orangen pflücken',
            pl: 'Zbieranie pomarańczy',
        },
        imReadyToWork: {
            ru: 'Всё ясно, я готов приступить',
            ua: 'Все зрозуміло, я готовий приступити',
            en: "Got it, I'm ready to start",
            de: 'Alles klar, ich bin bereit loszulegen',
            pl: 'Wszystko jasne, jestem gotów zaczynać',
        },
        laterWork: {
            ru: 'Я пока не буду работать',
            ua: 'Я поки не буду працювати',
            en: "I won't work for now",
            de: 'Ich werde vorerst nicht arbeiten',
            pl: 'Na razie nie będę pracować',
        },
        plantingDetails: {
            ru: 'Посадка культур - это основа нашей фермы. Она доступна со второго уровня. Лейку и семена ты сможешь приобрести в любом магазине 24/7.\n\nОбрати внимание: каждое поле предназначено для своего типа культуры, и на нём всегда указано, что именно там нужно сажать и сколько уже посажено. Начнёшь ты с картофеля, а с ростом опыта тебе откроются новые культуры:\n\n• Уровень 2: Картофель\n• Уровень 3: Лук\n• Уровень 4: Огурцы, Томаты\n• Уровень 5: Капуста, Тыква\n• Уровень 6: Морковь, Подсолнух\n• Уровень 7: Ананас, Арбуз\n\nСобранный урожай необходимо продать у скупщика. Цены у него меняются раз в некоторое время, так что тебе нужно постоянно мониторить их и выбирать момент для продажи грамотно.',
            ua: 'Посадка культур - це основа нашої ферми. Вона доступна з другого рівня. Лійку та насіння ти зможеш придбати в будь-якому магазині 24/7.\n\nЗверни увагу: кожне поле призначене для свого типу культури, і на ньому завжди вказано, що саме потрібно садити та скільки вже посаджено. Почнеш із картоплі, а з досвідом тобі відкриються нові культури:\n\n• Рівень 2: Картопля\n• Рівень 3: Цибуля\n• Рівень 4: Огірки, Помідори\n• Рівень 5: Капуста, Гарбуз\n• Рівень 6: Морква, Соняшник\n• Рівень 7: Ананас, Кавун\n\nЗібраний урожай потрібно продати скупникові. Ціни змінюються час від часу, тому потрібно стежити за ними й продавати в слушний момент.',
            en: "Planting crops is the foundation of our farm. It's available from level 2. You can buy a watering can and seeds in any store 24/7.\n\nNote: each field is meant for a specific crop type, and it always shows what should be planted there and how much is already planted. You’ll start with potatoes, and as you gain experience, new crops will unlock:\n\n• Level 2: Potatoes\n• Level 3: Onions\n• Level 4: Cucumbers, Tomatoes\n• Level 5: Cabbage, Pumpkin\n• Level 6: Carrots, Sunflowers\n• Level 7: Pineapples, Watermelons\n\nThe harvested crops must be sold to the buyer. Prices change from time to time, so you’ll need to monitor them and choose the best moment to sell.",
            de: 'Das Pflanzen von Kulturen ist die Grundlage unserer Farm. Es ist ab Level 2 verfügbar. Du kannst eine Gießkanne und Samen in jedem Laden 24/7 kaufen.\n\nBeachte: Jedes Feld ist für eine bestimmte Kultur vorgesehen, und dort steht immer, was gepflanzt werden soll und wie viel bereits gepflanzt ist. Du beginnst mit Kartoffeln, und mit wachsender Erfahrung schaltest du neue Kulturen frei:\n\n• Level 2: Kartoffeln\n• Level 3: Zwiebeln\n• Level 4: Gurken, Tomaten\n• Level 5: Kohl, Kürbis\n• Level 6: Karotten, Sonnenblumen\n• Level 7: Ananas, Wassermelonen\n\nDie geernteten Pflanzen musst du beim Käufer verkaufen. Die Preise ändern sich von Zeit zu Zeit, also beobachte sie und verkaufe im richtigen Moment.',
            pl: 'Sadzenie upraw to podstawa naszej farmy. Dostępne od poziomu 2. Konewkę i nasiona możesz kupić w dowolnym sklepie 24/7.\n\nZwróć uwagę: każde pole jest przeznaczone dla określonego rodzaju uprawy i zawsze pokazuje, co należy tam posadzić i ile już posadzono. Zaczniesz od ziemniaków, a wraz z doświadczeniem odblokujesz nowe uprawy:\n\n• Poziom 2: Ziemniaki\n• Poziom 3: Cebula\n• Poziom 4: Ogórki, Pomidory\n• Poziom 5: Kapusta, Dynia\n• Poziom 6: Marchew, Słonecznik\n• Poziom 7: Ananas, Arbuz\n\nZebrane plony musisz sprzedać skupującemu. Ceny zmieniają się co jakiś czas, więc obserwuj je i wybieraj odpowiedni moment na sprzedaż.',
        },
        tractorDetails: {
            ru: 'Работа на тракторе - это возможность дополнительно заработать, пока ждёшь урожай. Она открывается со второго уровня. Но есть условие: ты можешь работать только на тех полях, которые полностью засажены и требуют культивации. Как только поле обработано (культивировано), на нём снова можно будет сажать новую партию.',
            ua: 'Робота на тракторі - це можливість додатково заробити, поки чекаєш урожай. Вона відкривається з другого рівня. Але є умова: ти можеш працювати лише на тих полях, які повністю засаджені та потребують культивації. Як тільки поле оброблене, на ньому можна знову садити нову партію.',
            en: 'Tractor work is a way to earn extra money while waiting for your crops to grow. It unlocks at level 2. But there’s a condition: you can only work on fields that are fully planted and need cultivation. Once a field is cultivated, you can plant a new batch there again.',
            de: 'Die Arbeit mit dem Traktor ist eine Möglichkeit, zusätzlich Geld zu verdienen, während du auf deine Ernte wartest. Sie wird ab Level 2 freigeschaltet. Es gibt aber eine Bedingung: Du kannst nur auf Feldern arbeiten, die vollständig bepflanzt sind und Kultivierung benötigen. Sobald ein Feld bearbeitet ist, kannst du dort wieder neu pflanzen.',
            pl: 'Praca na traktorze to sposób na dodatkowy zarobek, gdy czekasz na plony. Dostępna od poziomu 2. Jest jednak warunek: możesz pracować tylko na polach, które są w pełni obsiane i wymagają uprawy. Gdy pole zostanie uprawione, można znowu sadzić nową partię.',
        },
        orangesDetails: {
            ru: 'Это твоя стартовая задача. На первом уровне ты можешь только собирать апельсины в трёх садах. Это несложно, но даёт ценный опыт, который откроет тебе доступ к полевым работам и посадке. Собранные апельсины, как и весь остальной урожай, нужно продать у скупщика.',
            ua: 'Це твоє стартове завдання. На першому рівні ти можеш лише збирати апельсини в трьох садах. Це нескладно, але дає цінний досвід, який відкриє тобі доступ до польових робіт і посадки. Зібрані апельсини, як і весь інший урожай, потрібно продати скупникові.',
            en: 'This is your starting task. At level one, you can only pick oranges in three orchards. It’s simple, but it gives you valuable experience that unlocks fieldwork and planting. The collected oranges, like all other crops, must be sold to the buyer.',
            de: 'Das ist deine Startaufgabe. Auf Level 1 kannst du nur Orangen in drei Obstgärten pflücken. Es ist einfach, aber es bringt wertvolle Erfahrung, die dir Zugang zu Feldarbeit und Pflanzen gibt. Die gesammelten Orangen müssen wie alle anderen Ernten beim Käufer verkauft werden.',
            pl: 'To twoje początkowe zadanie. Na pierwszym poziomie możesz jedynie zbierać pomarańcze w trzech sadach. To proste, ale daje cenne doświadczenie, które odblokuje prace polowe i sadzenie. Zebrane pomarańcze, podobnie jak inne plony, musisz sprzedać skupującemu.',
        },
        anotherQuestion: {
            ru: 'У меня есть другой вопрос.',
            ua: 'У мене є інше запитання.',
            en: 'I have another question.',
            de: 'Ich habe noch eine andere Frage.',
            pl: 'Mam inne pytanie.',
        },
        thanksStartJob: {
            ru: 'Спасибо, я готов начать.',
            ua: 'Дякую, я готовий почати.',
            en: 'Thanks, I’m ready to start.',
            de: 'Danke, ich bin bereit anzufangen.',
            pl: 'Dzięki, jestem gotów zacząć.',
        },
    },
    second: {
        youWantToQuitAlready: {
            ru: 'Похоже ты хочешь уволиться, это так?',
            ua: 'Схоже, ти хочеш звільнитися, це так?',
            en: 'It looks like you want to quit, is that right?',
            de: 'Es sieht so aus, als ob du kündigen möchtest, stimmt das?',
            pl: 'Wygląda na to, że chcesz zrezygnować, czy to prawda?',
            zh: '看起来你想要辞职，是吗？',
        },
        yes: {
            ru: 'Да',
            ua: 'Так',
            en: 'Yes',
            de: 'Ja',
            pl: 'Tak',
            zh: '是的',
        },
        no: {
            ru: 'Я передумал',
            ua: 'Я передумав',
            en: "I've changed my mind",
            de: 'Ich habe es mir anders überlegt',
            pl: 'Zmieniłem zdanie',
            zh: '我改变主意了',
        },
    },
};
