export const server = {
    farm: {
        ru: 'Работа фермера',
        ua: 'Робота фермера',
        en: 'Farm work',
        de: 'Arbeiten auf dem Bauernhof',
        pl: 'Praca na farmie',
    },
    farmChat: {
        ru: '[Ферма]: ',
        ua: '[Ферма]: ',
        en: '[Farm]: ',
        de: '[Bauernhof]: ',
        pl: '[Farma]: ',
        ge: '[ფერმა]: ',
    },
    plantation: {
        ru: 'Поле',
        ua: 'Поле',
        en: 'Plantation',
        de: 'Plantage',
        pl: 'Plantacja',
    },
    garden: {
        ru: 'Сад апельсинов',
        ua: 'Сад апельсинів',
        en: 'Orange Garden',
        de: 'Orangengarten',
        pl: 'Ogród pomarańczowy',
        ge: 'ფორთოხლის ბაღი',
    },
    fieldMinLevel: {
        ru: 'Минимальный уровень для этого поля: {{level}}',
        ua: 'Мінімальний рівень для цього поля: {{level}}',
        en: 'Minimum level for this field: {{level}}',
        de: 'Mindestlevel für dieses Feld: {{level}}',
        pl: 'Minimalny poziom dla tego pola: {{level}}',
        ge: 'მინიმალური დონე ამ ველისთვის: {{level}}',
    },
    youCantPlantThere: {
        ru: 'Вы не можете садить здесь',
        ua: 'Ви не можете садити тут',
        en: "You can't plant there",
        de: 'Sie können dort nicht pflanzen',
        pl: 'Nie możesz tam sadzić',
    },
    thatSeedsNot: {
        ru: 'На этом поле можно садить только: {{seeds}}',
        ua: 'На цьому полі можна садити тільки: {{seeds}}',
        en: 'Only the following can be planted in this field: {{seeds}}',
        de: 'Auf diesem Feld können nur die folgenden Pflanzen gesät werden: {{seeds}}',
        pl: 'Na tym polu można sadzić tylko: {{seeds}}',
        ge: 'ამ ველში მხოლოდ შემდეგის დათესვაა შესაძლებელი: {{seeds}}',
    },
    waterTowerShapeEnter: {
        ru: 'Используйте лейку чтобы набрать в неё воду',
        ua: 'Використайте лійку, щоб набрати в неї воду',
        en: 'Use the watering can to fill it with water',
        de: 'Benutzen Sie die Gießkanne, um sie mit Wasser zu füllen',
        pl: 'Użyj konewki, aby napełnić ją wodą',
    },
    filledWateringCan: {
        ru: 'Вы наполнили лейку водой',
        ua: 'Ви наповнили лійку водою',
        en: 'You filled the watering can with water',
        de: 'Sie haben die Gießkanne mit Wasser gefüllt',
        pl: 'Napełniłeś konewkę wodą',
    },
    wateringCanIsFull: {
        ru: 'Лейка заполнена',
        ua: 'Лійка заповнена',
        en: 'The watering can is full',
        de: 'Die Gießkanne ist voll',
        pl: 'Konewka jest pełna',
    },
    youWatered: {
        ru: 'Вы полили растение водой, в лейке осталось {{water}}% воды',
        ua: 'Ви полили рослину водою, в лійці залишилося {{water}}% води',
        en: 'You watered the plant, there is {{water}}% water left in the watering can',
        de: 'Sie haben die Pflanze gegossen, es sind noch {{water}}% Wasser in der Gießkanne',
        pl: 'Podlałeś roślinę, w konewce zostało {{water}}% wody',
    },
    interaction: {
        ru: 'Собрать урожай',
        ua: 'Зібрати врожай',
        en: 'Harvest',
        de: 'Ernten',
        pl: 'Zbierać plony',
    },
    notOwner: {
        ru: 'Это не ваш урожай',
        ua: 'Це не ваш врожай',
        en: 'This is not your crop',
        de: 'Das ist nicht deine Ernte',
        pl: 'To nie są twoje plony',
    },
    inventoryFull: {
        ru: 'У вас нет места в инвентаре для этого растения',
        ua: 'У вас немає місця в інвентарі для цієї рослини',
        en: 'You have no space in your inventory for this plant',
        de: 'Du hast keinen Platz in deinem Inventar für diese Pflanze',
        pl: 'Nie masz miejsca w ekwipunku na tę roślinę',
    },
    wateringCanIsEmpty: {
        ru: 'Лейка пуста',
        ua: 'Лійка пуста',
        en: 'The watering can is empty',
        de: 'Die Gießkanne ist leer',
        pl: 'Konewka jest pusta',
    },
    noWaterNeed: {
        ru: 'Растение и так полито',
        ua: 'Рослину вже полито',
        en: 'The plant is already watered',
        de: 'Die Pflanze ist bereits gegossen',
        pl: 'Roślina jest już podlana',
        ge: 'მცენარე უკვე მორწყულია',
    },
    fieldIsNotCultivated: {
        ru: 'Чтобы садить на этом поле его нужно культивировать',
        ua: 'Щоб садити на цьому полі, його потрібно культивувати',
        en: 'To plant on this field, it needs to be cultivated',
        de: 'Um auf diesem Feld zu pflanzen, muss es kultiviert werden',
        pl: 'Aby sadzić na tym polu, należy je uprawiać',
        ge: 'ამ ველზე დარგვისთვის საჭიროა მისი კულტივაცია',
    },
    stages: {
        dead: {
            ru: 'Погибло',
            ua: 'Загинуло',
            en: 'Dead',
            de: 'Gestorben',
            pl: 'Zmarło',
        },
        almostWithered: {
            ru: 'Почти засохло',
            ua: 'Майже засохло',
            en: 'Almost Withered',
            de: 'Fast verdorrt',
            pl: 'Prawie uschło',
        },
        withers: {
            ru: 'Начинает засохать',
            ua: 'Починає засихати',
            en: 'Withers',
            de: 'Verdorrt',
            pl: 'Usycha',
        },
        grew: {
            ru: 'Готово к сбору',
            ua: 'Готово до збору',
            en: 'Grew',
            de: 'Gewachsen',
            pl: 'Urosło',
        },
        grow: {
            ru: 'Растёт',
            ua: 'Росте',
            en: 'Grow',
            de: 'Wächst',
            pl: 'Rośnie',
        },
    },

    // Tractors stuff
    deployedToTractorJob: {
        ru: 'Найдите свободный трактор и следуйте указаниям',
        ua: 'Знайдіть вільний трактор і дотримуйтесь вказівок',
        en: 'Find a free tractor and follow the instructions',
        de: 'Finde einen freien Traktor und folge den Anweisungen',
        pl: 'Znajdź wolny traktor i postępuj zgodnie z instrukcjami',
        ge: 'იპოვეთ თავისუფალი ტრაქტორი და მიჰყევით ინსტრუქციებს',
    },
    seatToTractorAndStart: {
        ru: 'Найдите свободный культиватор и прицепите его к трактору',
        ua: 'Знайдіть вільний культиватор і причепіть його до трактора',
        en: 'Find a free cultivator and attach it to the tractor',
        de: 'Finden Sie einen freien Kultivator und befestigen Sie ihn am Traktor',
        pl: 'Znajdź wolny kultywator i przyczep go do traktora',
        ge: 'იპოვეთ თავისუფალი კულტივატორი და მიამაგრეთ იგი ტრაქტორზე',
    },
    attachedCultivator: {
        ru: 'Ищите свободное поле и начинайте его культивировать',
        ua: 'Шукайте вільне поле і починайте його культивувати',
        en: 'Look for a free field and start cultivating it',
        de: 'Suchen Sie ein freies Feld und beginnen Sie es zu kultivieren',
        pl: 'Szukaj wolnego pola i zacznij je uprawiać',
        ge: 'მოიძიეთ თავისუფალი მინდორი და დაიწყეთ მისი კულტივირება',
    },
    yourLevelTooLow: {
        ru: 'Ваш уровень слишком низкий для работы трактористом',
        ua: 'Ваш рівень занадто низький для роботи трактористом',
        en: 'Your level is too low to work as a tractor driver',
        de: 'Ihr Level ist zu niedrig, um als Traktorfahrer zu arbeiten',
        pl: 'Twój poziom jest zbyt niski, aby pracować jako traktorzysta',
        ge: 'თქვენი დონე ძალიან დაბალია ტრაქტორისტად სამუშაოდ',
    },
    youAreCantSeatTractor: {
        ru: 'У вас нет доступа к этому трактору',
        ua: 'У вас немає доступу до цього трактора',
        en: 'You do not have access to this tractor',
        de: 'Sie haben keinen Zugang zu diesem Traktor',
        pl: 'Nie masz dostępu do tego traktora',
        ge: 'თქვენ არ გაქვთ წვდომა ამ ტრაქტორზე',
    },
    finishedCultivation: {
        ru: 'Вы закончили культивировать это поле, теперь это поле пригодно для посадки растений. Вы заработали: ${{salary}}',
        ua: 'Ви закінчили культивацію цього поля, тепер це поле придатне для посадки рослин. Ви заробили: ${{salary}}',
        en: 'You have finished cultivating this field, it is now suitable for planting crops. You earned: ${{salary}}',
        de: 'Du hast die Bearbeitung dieses Feldes abgeschlossen, es ist jetzt für den Anbau von Pflanzen geeignet. Du hast verdient: ${{salary}}',
        pl: 'Zakończyłeś uprawę tego pola, teraz jest ono odpowiednie do sadzenia roślin. Zarobiłeś: ${{salary}}',
        ge: 'თქვენ დაასრულეთ ამ ველის დამუშავება, ახლა ის მზადაა მცენარეების დასარგავად. თქვენ გამოიმუშავეთ: ${{salary}}',
    },
    // returnToTractor: {
    //     ru: 'Вернитесь к трактору иначе '
    // }

    // Orange
    deployedToOrangesJob: {
        ru: 'Отправляйтесь в сад собирать апельсины',
        ua: 'Вирушайте в сад збирати апельсини',
        en: 'Go to the orchard to pick oranges',
        de: 'Gehen Sie in den Obstgarten, um Orangen zu pflücken',
        pl: 'Idź do sadu zbierać pomarańcze',
        ge: 'წადით ბაღში ფორთოხლების მოსაკრეფად',
    },
    youAreNotDeployedToOranges: {
        ru: 'Чтобы собирать апельсины нужно устроится на работу',
        ua: 'Щоб збирати апельсини, потрібно влаштуватися на роботу',
        en: 'To pick oranges, you need to get a job',
        de: 'Um Orangen zu pflücken, müssen Sie einen Job bekommen',
        pl: 'Aby zbierać pomarańcze, musisz znaleźć pracę',
        ge: 'ფორთოხლების მოსაკრეფად უნდა დასაქმდეთ',
    },
    treeCooldown: {
        ru: 'Плоды на этом дереве ещё растут...',
        ua: 'Плоди на цьому дереві ще ростуть...',
        en: 'The fruits on this tree are still growing...',
        de: 'Die Früchte an diesem Baum wachsen noch...',
        pl: 'Owoce na tym drzewie wciąż rosną...',
        ge: 'ხილები ამ ხეზე ჯერ კიდევ იზრდება...',
    },
    treeBusy: {
        ru: 'Кто то уже собирает плоды на этом дереве',
        ua: 'Хтось вже збирає плоди на цьому дереві',
        en: 'Someone is already picking fruits from this tree',
        de: 'Jemand pflückt bereits Früchte von diesem Baum',
        pl: 'Ktoś już zbiera owoce z tego drzewa',
        ge: 'ვინმე უკვე კრეფს ხილს ამ ხიდან',
    },

    notEnoughtLevelForTractor: {
        ru: 'Для работы на тракторе нужен {{level}} уровень фермера',
        ua: 'Для роботи на тракторі потрібен {{level}} рівень фермера',
        en: 'You need a farmer level of {{level}} to operate a tractor',
        de: 'Für die Arbeit mit dem Traktor wird ein Bauernlevel von {{level}} benötigt',
        pl: 'Do pracy na traktorze potrzebny jest poziom rolnika {{level}}',
    },
    noFreeFiels: {
        ru: 'Сейчас нет свободных полей для культивации',
        ua: 'Зараз немає вільних полів для культивації',
        en: 'There are currently no free fields for cultivation',
        de: 'Zurzeit gibt es keine freien Felder für die Kultivierung',
        pl: 'Obecnie nie ma wolnych pól do uprawy',
    },

    returnToTractor: {
        ru: 'Вернитесь к трактору иначе прогресс будет потерян',
        ua: 'Поверніться до трактора, інакше прогрес буде втрачено',
        en: 'Return to the tractor or progress will be lost',
        de: 'Kehren Sie zum Traktor zurück, sonst geht der Fortschritt verloren',
        pl: 'Wróć do traktora, inaczej postęp zostanie utracony',
    },

    //
    vehiclesRespawned: {
        ru: 'Незанятые тракторы и культиваторы были зареспавнены!',
        ua: 'Незайняті трактори та культиватори були респавнені!',
        en: 'Unoccupied tractors and cultivators have respawned!',
        de: 'Unbesetzte Traktoren und Kultivatoren wurden respawnt!',
        pl: 'Nieobsadzone traktory i kultywatory zostały zrespawnowane!',
        ge: 'დაუკავებელი ტრაქტორები და კულტივატორები რესპავნდნენ!',
    },

    //
    label: {
        field: {
            ru: 'Поле',
            ua: 'Поле',
            en: 'Field',
            de: 'Feld',
            pl: 'Pole',
            ge: 'ველი',
        },
        lvl: {
            ru: 'Нужный уровень',
            ua: 'Необхідний рівень',
            en: 'Required level',
            de: 'Erforderliches Niveau',
            pl: 'Wymagany poziom',
            ge: 'საჭირო დონე',
        },
        crop: {
            ru: 'Культура',
            ua: 'Культура',
            en: 'Crop',
            de: 'Kultur',
            pl: 'Uprawa',
            ge: 'მოსავალი',
        },
        planted: {
            ru: 'Посажено',
            ua: 'Посаджено',
            en: 'Planted',
            de: 'Gepflanzt',
            pl: 'Zasadzono',
            ge: 'დარგული',
        },
    },
};
