export const server = {
    farm: {
        ru: 'Работа фермера',
        ua: 'Робота фермера',
        en: 'Farm work',
        de: 'Arbeiten auf dem Bauernhof',
        pl: 'Praca na farmie',
    },
    plantation: {
        ru: 'Поле',
        ua: 'Поле',
        en: 'Plantation',
        de: 'Plantage',
        pl: 'Plantacja',
    },
    youCantPlantThere: {
        ru: 'Вы не можете садить здесь',
        ua: 'Ви не можете садити тут',
        en: "You can't plant there",
        de: 'Sie können dort nicht pflanzen',
        pl: 'Nie możesz tam sadzić',
    },
    thatSeedsNot: {
        ru: 'Эти семена не подходят на этом поле',
        ua: 'Ці насіння не підходять на цьому полі',
        en: 'These seeds are not suitable for this field',
        de: 'Diese Samen sind für dieses Feld nicht geeignet',
        pl: 'Te nasiona nie nadają się na to pole',
    },
    waterTowerShapeEnter: {
        ru: 'Используйте лейку чтобы набрать в неё воду',
        ua: 'Використайте лійку, щоб набрати в неї воду',
        en: 'Use the watering can to fill it with water',
        de: 'Benutzen Sie die Gießkanne, um sie mit Wasser zu füllen',
        pl: 'Użyj konewki, aby napełnić ją wodą',
    },
    filledWateringCan: {
        ru: 'Вы наполнили лейку водой',
        ua: 'Ви наповнили лійку водою',
        en: 'You filled the watering can with water',
        de: 'Sie haben die Gießkanne mit Wasser gefüllt',
        pl: 'Napełniłeś konewkę wodą',
    },
    wateringCanIsFull: {
        ru: 'Лейка заполнена',
        ua: 'Лійка заповнена',
        en: 'The watering can is full',
        de: 'Die Gießkanne ist voll',
        pl: 'Konewka jest pełna',
    },
    youWatered: {
        ru: 'Вы полили растение водой, в лейке осталось {{water}}% воды',
        ua: 'Ви полили рослину водою, в лійці залишилося {{water}}% води',
        en: 'You watered the plant, there is {{water}}% water left in the watering can',
        de: 'Sie haben die Pflanze gegossen, es sind noch {{water}}% Wasser in der Gießkanne',
        pl: 'Podlałeś roślinę, w konewce zostało {{water}}% wody',
    },
    interaction: {
        ru: 'Собрать урожай',
        ua: 'Зібрати врожай',
        en: 'Harvest',
        de: 'Ernten',
        pl: 'Zbierać plony',
    },
    notOwner: {
        ru: 'Это не ваш урожай',
        ua: 'Це не ваш врожай',
        en: 'This is not your crop',
        de: 'Das ist nicht deine Ernte',
        pl: 'To nie są twoje plony',
    },
    inventoryFull: {
        ru: 'У вас нет места в инвентаре для этого растения',
        ua: 'У вас немає місця в інвентарі для цієї рослини',
        en: 'You have no space in your inventory for this plant',
        de: 'Du hast keinen Platz in deinem Inventar für diese Pflanze',
        pl: 'Nie masz miejsca w ekwipunku na tę roślinę',
    },
    wateringCanIsEmpty: {
        ru: 'Лейка пуста',
        ua: 'Лійка пуста',
        en: 'The watering can is empty',
        de: 'Die Gießkanne ist leer',
        pl: 'Konewka jest pusta',
    },
    stages: {
        dead: {
            ru: 'Погибло',
            ua: 'Загинуло',
            en: 'Dead',
            de: 'Gestorben',
            pl: 'Zmarło',
        },
        almostWithered: {
            ru: 'Почти засохло',
            ua: 'Майже засохло',
            en: 'Almost Withered',
            de: 'Fast verdorrt',
            pl: 'Prawie uschło',
        },
        withers: {
            ru: 'Начинает засохать',
            ua: 'Починає засихати',
            en: 'Withers',
            de: 'Verdorrt',
            pl: 'Usycha',
        },
        grew: {
            ru: 'Готово к сбору',
            ua: 'Готово до збору',
            en: 'Grew',
            de: 'Gewachsen',
            pl: 'Urosło',
        },
        grow: {
            ru: 'Растёт',
            ua: 'Росте',
            en: 'Grow',
            de: 'Wächst',
            pl: 'Rośnie',
        },
    },
};
