export default {
    name: {
        ru: 'Необъятный океан',
        ua: 'Неосяжна блакить',
        en: 'Grand Blue',
        de: 'Grand Blue',
        pl: 'Grand Blue',
    },
    desc: {
        ru: 'Встреться с Иори, легендарным дайвером. Возьми у него задание и попробуй себя в роли дайвера — исследуй глубины у дамбы Land Act.',
        ua: 'Зустрінься з Іорі, легендарним дайвером. Візьми у нього завдання і спробуй себе в ролі дайвера — досліди глибини біля дамби Land Act.',
        en: 'Meet Iori, the legendary diver. Get a job from him and try being a diver — explore the depths near the Land Act Dam.',
        de: 'Triff dich mit Iori, dem legendären Taucher. Hol dir einen Auftrag von ihm und versuch dich als Taucher – erkunde die Tiefen am Land Act-Damm.',
        pl: 'Spotkaj się z Iorim, legendarnym nurkiem. Weź od niego zadanie i spróbuj swoich sił jako nurek — zbadaj głębiny przy tamie Land Act.',
    },
    smsFromDiana: {
        ru: 'Приветик! Короче, мой знакомый дайвер Иори просил, чтобы ты зашёл к нему на дамбу в Лос-Сантосе. Говорит, для тебя есть какое-то дело. Главное — не увлекайся его фирменным «чаем»!',
        ua: 'Привіт! Коротше, мій знайомий дайвер Іорі просив, щоб ти зайшов до нього на дамбу в Лос-Сантосі. Каже, для тебе є якась справа. Головне — не захоплюйся його фірмовим «чаєм»!',
        en: "Hey! So, my friend Iori the diver asked if you could drop by the dam in Los Santos. He says he's got something for you. Just don’t get too into his special 'tea'!",
        de: 'Hey! Also, mein Kumpel Iori, der Taucher, wollte, dass du ihn beim Damm in Los Santos besuchst. Er meint, er hat was für dich. Aber übertreib es nicht mit seinem berühmten „Tee“!',
        pl: 'Hejka! Słuchaj, mój znajomy nurek Iori prosił, żebyś wpadł do niego na tamę w Los Santos. Mówi, że ma coś dla ciebie. Tylko nie przesadź z jego słynną „herbatką”!',
    },
    dialog1: {
        firstMeet: {
            ru: 'Эй, ты новенький? Ха, не переживай — плавать научим, а вот похмеляться тут у каждого свой стиль! Меня Иори зовут. Если по делу — есть работёнка для такого как ты. Только сперва… попробуй вот этот чай. Ну, для храбрости!',
            ua: 'Гей, ти новенький? Ха, не хвилюйся — плавати навчимо, а ось похмелятися тут у кожного свій стиль! Я Іорі. Якщо по справі — є робота для такого, як ти. Але спочатку… спробуй ось цей чай. Для хоробрості!',
            en: 'Hey, you’re new here? Ha, don’t worry — we’ll teach you how to swim, but when it comes to hangovers, everyone’s got their own style! Name’s Iori. If you’re looking for work — I’ve got a job for someone like you. But first… try this tea. For courage!',
            de: 'Hey, du bist neu hier? Ha, keine Sorge — schwimmen bringen wir dir bei, aber was den Kater angeht, hat hier jeder seinen eigenen Stil! Ich heiße Iori. Wenn du was suchst — ich hab ’nen Job für jemanden wie dich. Aber zuerst… probier diesen Tee. Für den Mut!',
            pl: 'Hej, jesteś nowy? Ha, nie przejmuj się — nauczymy cię pływać, ale każdy ma tu swój sposób na kaca! Nazywam się Iori. Jeśli chcesz coś robić — mam robotę dla kogoś takiego jak ty. Ale najpierw… spróbuj tej herbaty. Na odwagę!',
        },
        okay: {
            ru: 'Окей щас выпью',
            ua: 'Окей, зараз вип’ю',
            en: 'Okay, I’ll drink it now',
            de: 'Okay, ich trink’s jetzt',
            pl: 'Okej, zaraz wypiję',
        },
        later: {
            ru: 'Я чуть позже подойду',
            ua: 'Я трохи пізніше підійду',
            en: 'I’ll come back a bit later',
            de: 'Ich komm später nochmal vorbei',
            pl: 'Podejdę trochę później',
        },
    },
    dialog2: {
        afterTea: {
            ru: 'Ну что, как тебе чаёк? Крепковат, да? Привыкай — без этого тут не выжить! Когда голова пройдёт, дуй к местному дайверу, он выдаст тебе снарягу. А дальше — твой путь под воду, ищи сокровища, только не утопи печень!',
            ua: 'Ну що, як тобі чайок? Крепкуватий, га? Звикай — без цього тут не вижити! Як голова відпустить, біжи до місцевого дайвера, він дасть тобі спорягу. А далі — твій шлях під воду, шукай скарби, тільки печінку не втопи!',
            en: 'So, how’s the tea? Bit strong, huh? Get used to it — you won’t survive here without it! Once your head clears up, go see the local diver, he’ll give you some gear. After that — it’s your dive down, hunt for treasure, just don’t drown your liver!',
            de: 'Na, wie war der Tee? Ganz schön stark, was? Gewöhn dich dran — ohne das überlebst du hier nicht! Wenn der Schädel wieder klar ist, geh zum Taucher hier, der gibt dir Ausrüstung. Und dann — ab unter Wasser, such die Schätze, aber ersäuf dir nicht die Leber!',
            pl: 'No i jak herbatka? Mocna, co? Przyzwyczajaj się — bez niej tutaj nie przeżyjesz! Jak już głowa przestanie dudnić, idź do miejscowego nurka, da ci sprzęt. A potem — twój czas na zejście pod wodę, szukaj skarbów, tylko nie utop wątroby!',
        },
        okay: {
            ru: 'Ок-ккей!',
            ua: 'Ок-ккей!',
            en: 'O-o-okay!',
            de: 'O-okay!',
            pl: 'O-o-okej!',
        },
        afterDive: {
            "ru": "А, да… Как соберёшь весь лут — возвращайся ко мне. Только не потеряйся там под водой, ага?",
            "ua": "А, так… Як збереш весь лут — повертайся до мене. Тільки не загубись там під водою, гаразд?",
            "en": "Oh, right… Once you’ve grabbed all the loot, come back to me. Just don’t get lost down there, okay?",
            "de": "Ach ja… Wenn du den ganzen Loot eingesammelt hast, komm zurück zu mir. Aber verirr dich nicht da unten im Wasser, ja?",
            "pl": "A, racja… Jak już zbierzesz cały loot, wróć do mnie. Tylko się tam nie zgub pod wodą, dobra?",
        },
        getIt: {
            ru: 'П-понял!',
            ua: 'З-зрозумів!',
            en: 'G-got it!',
            de: 'V-verstanden!',
            pl: 'Z-załapałem!',
        },
    },
    dialog3: {
        afterLoot: {
            "ru": "Красавчик! Ну что, задание моё сделал — теперь топай к скупщику, сдай всё барахло и забери награду. Я потом подкину бонус за проделанную работу. Кстати, скупщики шастают по разным местам, так что глянь в телефоне навигатор и проложи к нему актуальный маршрут.",
            "ua": "Красунчик! Ну що, завдання моє зробив — тепер рушай до скупника, здай усе барахло та забери нагороду. Я потім підкину бонус за виконану роботу. До речі, скупники шастають по різних місцях, тож глянь у телефоні навігатор і проклади до нього актуальний маршрут.",
            "en": "Nice one! So, you did my job — now head to the fence, sell all the junk and grab your reward. I’ll throw in a bonus later for the work you’ve done. By the way, fences roam around different spots, so check the navigator on your phone and set the current route to them.",
            "de": "Gut gemacht! Also, meinen Auftrag hast du erledigt — jetzt geh zum Hehler, verkauf den ganzen Kram und hol dir deine Belohnung. Später leg ich noch einen Bonus für die erledigte Arbeit drauf. Übrigens, Hehler treiben sich an verschiedenen Orten herum, also schau im Handy in den Navigator und leg dir die aktuelle Route zu ihm fest.",
            "pl": "Brawo! No więc, wykonałeś moje zadanie — teraz idź do pasera, oddaj cały ten grat i odbierz nagrodę. Potem dorzucę bonus za wykonaną robotę. A tak przy okazji, paserzy kręcą się po różnych miejscach, więc sprawdź w telefonie nawigację i ustaw do niego aktualną trasę.",
        },
        okay: {
            "ru": "Окей",
            "ua": "Окей",
            "en": "Okay",
            "de": "Okay",
            "pl": "Okej",
        },
        nextTime: {
            "ru": "Ещё увидимся, я прям чую. Мир тесный, а океан — тем более… так что не расслабляйся, приключения только начинаются.",
            "ua": "Ще побачимось, я прямо відчуваю. Світ тісний, а океан — тим більше… тож не розслабляйся, пригоди тільки починаються.",
            "en": "We’ll meet again, I can feel it. The world’s small, and the ocean’s even smaller… so don’t relax, the adventures are just beginning.",
            "de": "Wir sehen uns wieder, das spür ich. Die Welt ist klein, und der Ozean noch kleiner… also entspann dich nicht zu sehr, die Abenteuer fangen gerade erst an.",
            "pl": "Jeszcze się spotkamy, czuję to. Świat jest mały, a ocean jeszcze mniejszy… więc nie rozluźniaj się, przygody dopiero się zaczynają.",
        },
        bye: {
            "ru": "До встречи!",
            "ua": "До зустрічі!",
            "en": "See you!",
            "de": "Bis später!",
            "pl": "Do zobaczenia!",
        },
    },
};
