export default {
    white: { ru: 'Белый', ua: 'Білий', en: 'White', de: 'Weiß', pl: 'Biały',zh:'白色' },
    black: { ru: 'Чёрный', ua: 'Чорний', en: 'Black', de: 'Schwarz', pl: 'Czarny' ,zh:'黑色'},
    red: { ru: 'Красный', ua: 'Червоний', en: 'Red', de: 'Rot', pl: 'Czerwony' ,zh:'红色'},
    green: { ru: 'Зелёный', ua: 'Зелений', en: 'Green', de: 'Grün', pl: 'Zielony' ,zh:'绿色'},
    blue: { ru: 'Синий', ua: 'Синій', en: 'Blue', de: 'Blau', pl: 'Niebieski',zh:'蓝色' },
    yellow: { ru: 'Жёлтый', ua: 'Жовтий', en: 'Yellow', de: 'Gelb', pl: 'Żółty',zh:'黄色' },
    cyan: { ru: 'Циан', ua: 'Ціан', en: 'Cyan', de: 'Cyan', pl: 'Cyjan',zh:'青色' },
    magenta: { ru: 'Маджента', ua: 'Маджента', en: 'Magenta', de: 'Magenta', pl: 'Magenta',zh:'品红色' },
    gray: { ru: 'Серый', ua: 'Сірий', en: 'Gray', de: 'Grau', pl: 'Szary',zh:'灰色' },
    orange: { ru: 'Оранжевый', ua: 'Помаранчевий', en: 'Orange', de: 'Orange', pl: 'Pomarańczowy',zh:'橙色' },
    purple: { ru: 'Фиолетовый', ua: 'Фіолетовий', en: 'Purple', de: 'Lila', pl: 'Fioletowy',zh:'紫色' },
    pink: { ru: 'Розовый', ua: 'Рожевий', en: 'Pink', de: 'Rosa', pl: 'Różowy',zh:'粉色' },
    brown: { ru: 'Коричневый', ua: 'Коричневий', en: 'Brown', de: 'Braun', pl: 'Brązowy',zh:'棕色' },
};
