export const burglarItems = {
    crtTv: {
        name: {
            ru: 'Ламповый телевизор',
            ua: 'Ламповий телевізор',
            en: 'Valve television set',
            de: 'Röhrenfernseher',
            pl: 'Telewizor lampowy',
        },
        desc: {
            ru: 'Деревянный корпус, две ручки и вес чугунной гири. Показывать давно перестал, но за такое до сих пор дают деньги.',
            ua: "Дерев'яний корпус, дві ручки і вага чавунної гирі. Показувати давно перестав, але за таке досі дають гроші.",
            en: 'A wooden case, two dials and the weight of a cast-iron kettlebell. It stopped showing anything years ago, but people still pay for these.',
            de: 'Holzgehäuse, zwei Drehknöpfe und das Gewicht einer gusseisernen Kugelhantel. Zeigt schon lange nichts mehr, doch dafür wird immer noch gezahlt.',
            pl: 'Drewniana obudowa, dwa pokrętła i waga żeliwnego odważnika. Dawno przestał cokolwiek pokazywać, ale wciąż da się go opchnąć.',
        },
    },
    antennaTv: {
        name: {
            ru: 'Телевизор с антенной',
            ua: 'Телевізор з антеною',
            en: 'Television with rabbit ears',
            de: 'Fernseher mit Zimmerantenne',
            pl: 'Telewizor z anteną pokojową',
        },
        desc: {
            ru: 'Кинескоп ещё тёплый, антенна согнута под единственный угол, при котором ловил хоть один канал. Хозяин точно расстроится.',
            ua: 'Кінескоп ще теплий, антена зігнута під єдиним кутом, за якого ловив хоч один канал. Господар точно засмутиться.',
            en: 'The tube is still warm and the aerial is bent at the one angle that ever caught a channel. The owner is going to miss this one.',
            de: 'Die Bildröhre ist noch warm, die Antenne genau in dem Winkel verbogen, in dem je ein Sender ankam. Der Besitzer wird das vermissen.',
            pl: 'Kineskop jeszcze ciepły, antena wygięta pod jedynym kątem, przy którym łapała choć jeden kanał. Właściciel będzie tęsknił.',
        },
    },
    crtMonitor: {
        name: {
            ru: 'Монитор с кинескопом',
            ua: 'Монітор з кінескопом',
            en: 'CRT monitor',
            de: 'Röhrenmonitor',
            pl: 'Monitor kineskopowy',
        },
        desc: {
            ru: 'Пожелтевший от времени пластик и глубина в половину стола. Экран так и остался включённым.',
            ua: 'Пожовклий від часу пластик і глибина в половину столу. Екран так і залишився увімкненим.',
            en: 'Plastic yellowed with age and half a desk deep. Nobody bothered to switch the screen off.',
            de: 'Vergilbter Kunststoff und halb so tief wie der Schreibtisch. Den Bildschirm hat niemand ausgeschaltet.',
            pl: 'Zżółkły ze starości plastik i głębokość pół biurka. Ekranu nikt nie wyłączył.',
        },
    },
    desktopPc: {
        name: {
            ru: 'Системный блок',
            ua: 'Системний блок',
            en: 'Desktop tower',
            de: 'Desktop-Rechner',
            pl: 'Jednostka centralna',
        },
        desc: {
            ru: 'Дисковод, привод и слой пыли в палец толщиной. Что внутри - разберутся уже покупатели.',
            ua: 'Дисковод, привід і шар пилу в палець завтовшки. Що всередині - розберуться вже покупці.',
            en: 'A floppy drive, an optical drive and a finger of dust. Whatever is inside is the buyer to work out.',
            de: 'Diskettenlaufwerk, optisches Laufwerk und fingerdick Staub. Was drin steckt, klärt der Käufer.',
            pl: 'Stacja dyskietek, napęd optyczny i palec kurzu. Co jest w środku, ustali już kupiec.',
        },
    },
    oldLaptop: {
        name: {
            ru: 'Потёртый ноутбук',
            ua: 'Потертий ноутбук',
            en: 'Battered laptop',
            de: 'Abgenutzter Laptop',
            pl: 'Wysłużony laptop',
        },
        desc: {
            ru: 'Чёрный, тяжёлый, с вытертыми до блеска клавишами. Заряда нет, но за корпус и начинку возьмут не глядя.',
            ua: 'Чорний, важкий, з витертими до блиску клавішами. Заряду немає, але за корпус і начинку візьмуть не дивлячись.',
            en: 'Black, heavy, the keys worn shiny. The battery is flat, but the case and the parts sell without a second look.',
            de: 'Schwarz, schwer, die Tasten blank gewetzt. Der Akku ist leer, doch Gehäuse und Innenleben gehen ungesehen weg.',
            pl: 'Czarny, ciężki, klawisze wytarte do połysku. Bateria padła, ale obudowę i podzespoły biorą bez oglądania.',
        },
    },
    openLaptop: {
        name: {
            ru: 'Незалоченный ноутбук',
            ua: 'Незаблокований ноутбук',
            en: 'Unlocked laptop',
            de: 'Entsperrter Laptop',
            pl: 'Niezablokowany laptop',
        },
        desc: {
            ru: 'Хозяин ушёл, не закрыв крышку: на экране до сих пор открыта чужая страница в Lifeinvader. Самое дорогое здесь - не железо.',
            ua: 'Господар пішов, не закривши кришку: на екрані досі відкрита чужа сторінка в Lifeinvader. Найдорожче тут - не залізо.',
            en: 'The owner walked away without closing the lid - their Lifeinvader page is still open. The hardware is the cheap part.',
            de: 'Der Besitzer ging, ohne den Deckel zu schließen - seine Lifeinvader-Seite ist noch offen. Die Hardware ist hier das Billigste.',
            pl: 'Właściciel odszedł, nie zamykając klapy - jego strona na Lifeinvader wciąż otwarta. Sprzęt jest tu najtańszy.',
        },
    },
    bigBoombox: {
        name: {
            ru: 'Двухкассетная магнитола',
            ua: 'Двокасетна магнітола',
            en: 'Twin-deck boombox',
            de: 'Doppelkassetten-Ghettoblaster',
            pl: 'Dwukasetowy boombox',
        },
        desc: {
            ru: 'Метр чёрного пластика, эквалайзер на десять полос и ручка сверху, за которую это чудо носили на плече. Ровно так его и понесут снова.',
            ua: 'Метр чорного пластику, еквалайзер на десять смуг і ручка згори, за яку це диво носили на плечі. Рівно так його й понесуть знову.',
            en: 'A metre of black plastic, a ten-band equaliser and a handle on top it used to be carried by. It is about to be carried that way again.',
            de: 'Ein Meter schwarzer Kunststoff, ein Zehnband-Equalizer und oben der Griff, an dem man ihn trug. Genau so wird er gleich wieder getragen.',
            pl: 'Metr czarnego plastiku, dziesięciopasmowy korektor i rączka na górze, za którą się go nosiło. Właśnie tak zostanie zniesiony znowu.',
        },
    },
    boombox: {
        name: {
            ru: 'Бумбокс',
            ua: 'Бумбокс',
            en: 'Boombox',
            de: 'Ghettoblaster',
            pl: 'Boombox',
        },
        desc: {
            ru: 'Два динамика в хромированных кольцах и кассетная дека посередине. Классика, которую до сих пор охотно берут.',
            ua: 'Два динаміки в хромованих кільцях і касетна дека посередині. Класика, яку досі охоче беруть.',
            en: 'Two speakers in chrome rings with a cassette deck between them. A classic that still moves easily.',
            de: 'Zwei Lautsprecher in Chromringen, dazwischen ein Kassettendeck. Ein Klassiker, der immer noch gut weggeht.',
            pl: 'Dwa głośniki w chromowanych ringach i magnetofon pośrodku. Klasyk, który wciąż dobrze schodzi.',
        },
    },
    vcr: {
        name: {
            ru: 'Видеомагнитофон',
            ua: 'Відеомагнітофон',
            en: 'VCR',
            de: 'Videorekorder',
            pl: 'Magnetowid',
        },
        desc: {
            ru: 'Часы на передней панели так и мигают нулями - их никто ни разу не выставил. Кассета внутри осталась.',
            ua: 'Годинник на передній панелі так і блимає нулями - його ніхто жодного разу не виставив. Касета всередині залишилася.',
            en: 'The clock on the front is still blinking zeroes - nobody ever set it. There is a tape left inside.',
            de: 'Die Uhr auf der Front blinkt noch immer Nullen - eingestellt hat sie nie jemand. Eine Kassette steckt noch drin.',
            pl: 'Zegar na froncie wciąż mruga zerami - nikt go nigdy nie ustawił. W środku została kaseta.',
        },
    },
    printer: {
        name: {
            ru: 'Лазерный принтер',
            ua: 'Лазерний принтер',
            en: 'Laser printer',
            de: 'Laserdrucker',
            pl: 'Drukarka laserowa',
        },
        desc: {
            ru: 'Тяжёлый, угловатый и почти ничего не стоит. Берут такое обычно от жадности.',
            ua: 'Важкий, кутастий і майже нічого не вартий. Беруть таке зазвичай від жадібності.',
            en: 'Heavy, boxy and worth almost nothing. This one gets taken out of pure greed.',
            de: 'Schwer, kantig und fast nichts wert. So etwas nimmt man aus reiner Gier mit.',
            pl: 'Ciężka, kanciasta i prawie nic niewarta. Takie rzeczy bierze się z czystej chciwości.',
        },
    },
    fan: {
        name: {
            ru: 'Напольный вентилятор',
            ua: 'Підлоговий вентилятор',
            en: 'Pedestal fan',
            de: 'Standventilator',
            pl: 'Wentylator stojący',
        },
        desc: {
            ru: 'Гнутая стойка, крестовина в пыли и одна работающая скорость из трёх. Стоит копейки, но занимает целые руки.',
            ua: 'Гнута стійка, хрестовина в пилюці й одна робоча швидкість із трьох. Коштує копійки, але займає цілі руки.',
            en: 'A bent stand, a dusty cross-base and one working speed out of three. Worth pennies and takes both hands.',
            de: 'Verbogene Stange, staubiges Kreuzfußgestell und eine funktionierende Stufe von dreien. Kaum etwas wert, aber beide Hände voll.',
            pl: 'Wygięty statyw, zakurzona krzyżakowa podstawa i jeden działający bieg z trzech. Warty grosze, a zajmuje obie ręce.',
        },
    },
    djCase: {
        name: {
            ru: 'Кейс диджея',
            ua: 'Кейс діджея',
            en: 'DJ flight case',
            de: 'DJ-Flightcase',
            pl: 'Case didżejski',
        },
        desc: {
            ru: 'Две вертушки и микшер в ударопрочном кофре. Самая дорогая вещь в квартире и самая неудобная для выноса.',
            ua: 'Дві вертушки і мікшер в ударостійкому кофрі. Найдорожча річ у квартирі й найнезручніша для виносу.',
            en: 'Two turntables and a mixer in a road case. The most valuable thing in the flat, and the most awkward to walk out with.',
            de: 'Zwei Plattenspieler und ein Mixer im Flightcase. Das Wertvollste in der Wohnung und das Sperrigste zum Rausschaffen.',
            pl: 'Dwa gramofony i mikser w skrzyni transportowej. Najcenniejsza rzecz w mieszkaniu i najbardziej niewygodna do wyniesienia.',
        },
    },
    electricGuitar: {
        name: {
            ru: 'Электрогитара',
            ua: 'Електрогітара',
            en: 'Electric guitar',
            de: 'E-Gitarre',
            pl: 'Gitara elektryczna',
        },
        desc: {
            ru: 'Белый корпус клином, языки пламени по деке и золочёная фурнитура. Такую покупали, чтобы вешать на стену, а не играть.',
            ua: 'Білий корпус клином, язики полум\'я по деці й позолочена фурнітура. Таку купували, щоб вішати на стіну, а не грати.',
            en: 'A white V-shaped body, flames down the front and gold hardware. Bought to hang on a wall, not to play.',
            de: 'Weißer V-Korpus, Flammen auf der Decke und vergoldete Hardware. Gekauft für die Wand, nicht zum Spielen.',
            pl: 'Biały korpus w kształcie V, płomienie na pudle i złocone okucia. Kupiona na ścianę, nie do grania.',
        },
    },
    acousticGuitar: {
        name: {
            ru: 'Акустическая гитара',
            ua: 'Акустична гітара',
            en: 'Acoustic guitar',
            de: 'Akustikgitarre',
            pl: 'Gitara akustyczna',
        },
        desc: {
            ru: 'Светлая дека, тёмные обечайки, вокруг розетки протёрто до дерева. На ней действительно играли.',
            ua: 'Світла дека, темні обичайки, навколо розетки протерто до дерева. На ній справді грали.',
            en: 'A pale top, dark sides, the wood worn bare around the sound hole. This one actually got played.',
            de: 'Helle Decke, dunkle Zargen, ums Schallloch bis aufs Holz abgewetzt. Auf der wurde wirklich gespielt.',
            pl: 'Jasny wierzch, ciemne boki, wokół otworu rezonansowego przetarte do drewna. Na tej naprawdę grano.',
        },
    },
    magazines: {
        name: {
            ru: 'Стопка журналов',
            ua: 'Стос журналів',
            en: 'Stack of magazines',
            de: 'Stapel Zeitschriften',
            pl: 'Stos czasopism',
        },
        desc: {
            ru: 'Выцветшие обложки, слипшиеся от сырости страницы. Стоит почти ничего, но пустыми руками из дома не уходят.',
            ua: 'Вицвілі обкладинки, злиплі від вологи сторінки. Коштує майже нічого, але з порожніми руками з дому не йдуть.',
            en: 'Faded covers and pages stuck together with damp. Worth next to nothing, but nobody leaves a house empty-handed.',
            de: 'Verblasste Titel, von Feuchtigkeit verklebte Seiten. So gut wie wertlos, doch mit leeren Händen geht keiner.',
            pl: 'Wyblakłe okładki, sklejone od wilgoci strony. Warte tyle co nic, ale z pustymi rękami się nie wychodzi.',
        },
    },
    books: {
        name: {
            ru: 'Стопка книг',
            ua: 'Стос книг',
            en: 'Stack of books',
            de: 'Bücherstapel',
            pl: 'Stos książek',
        },
        desc: {
            ru: 'Пять томов в твёрдых переплётах, ни один не открывали. Букинист даст немного, зато возьмёт не спрашивая.',
            ua: "П'ять томів у твердих палітурках, жодного не відкривали. Букініст дасть небагато, зате візьме не питаючи.",
            en: 'Five hardbacks, not one of them ever opened. A second-hand dealer pays little but asks nothing.',
            de: 'Fünf gebundene Bände, keiner je aufgeschlagen. Der Antiquar zahlt wenig, fragt dafür nichts.',
            pl: 'Pięć tomów w twardej oprawie, żadnego nie otwarto. Antykwariusz da niewiele, za to o nic nie zapyta.',
        },
    },
    microwave: {
        name: {
            ru: 'Микроволновка',
            ua: 'Мікрохвильовка',
            en: 'Microwave oven',
            de: 'Mikrowelle',
            pl: 'Kuchenka mikrofalowa',
        },
        desc: {
            ru: 'Снята прямо с кухонной тумбы, вилка так и болтается сзади. Внутри чья-то вчерашняя тарелка.',
            ua: 'Знята просто з кухонної тумби, вилка так і теліпається позаду. Усередині чиясь учорашня тарілка.',
            en: "Lifted straight off the counter with the plug still swinging behind it. Somebody's dinner is still inside.",
            de: 'Direkt von der Arbeitsplatte gehoben, der Stecker baumelt noch hinterher. Drinnen steht noch jemandes Abendessen.',
            pl: 'Zdjęta wprost z blatu, wtyczka wciąż dynda z tyłu. W środku czyjaś wczorajsza kolacja.',
        },
    },
    toolBox: {
        name: {
            ru: 'Ящик с инструментами',
            ua: 'Ящик з інструментами',
            en: 'Toolbox',
            de: 'Werkzeugkasten',
            pl: 'Skrzynka z narzędziami',
        },
        desc: {
            ru: 'Тяжёлый и гремит на каждом шаге. Хозяин собирал его годами, скупщик оценит за пять секунд.',
            ua: "Важкий і гримить на кожному кроці. Господар збирав його роками, скупник оцінить за п'ять секунд.",
            en: 'Heavy, and it rattles at every step. The owner spent years filling it; the fence values it in five seconds.',
            de: 'Schwer, und bei jedem Schritt klappert es. Der Besitzer hat ihn jahrelang gefüllt, der Hehler schätzt ihn in fünf Sekunden.',
            pl: 'Ciężka i grzechocze przy każdym kroku. Właściciel kompletował ją latami, paser wyceni w pięć sekund.',
        },
    },
    coolerBox: {
        name: {
            ru: 'Термобокс',
            ua: 'Термобокс',
            en: 'Cool box',
            de: 'Kühlbox',
            pl: 'Lodówka turystyczna',
        },
        desc: {
            ru: 'Пластиковый ящик с плотной крышкой, внутри ещё холодно. Что в нём лежало, лучше не выяснять.',
            ua: "Пластикова скриня зі щільною кришкою, всередині ще холодно. Що в ній лежало, краще не з'ясовувати.",
            en: 'A plastic box with a tight lid, still cold inside. Better not to work out what it was keeping cold.',
            de: 'Eine Plastikbox mit dichtem Deckel, innen noch kalt. Was darin lag, erfragt man besser nicht.',
            pl: 'Plastikowa skrzynia ze szczelną pokrywą, w środku wciąż zimno. Lepiej nie dociekać, co w niej trzymano.',
        },
    },
    paperBox: {
        name: {
            ru: 'Коробка бумаги',
            ua: 'Коробка паперу',
            en: 'Box of copy paper',
            de: 'Karton Kopierpapier',
            pl: 'Karton papieru',
        },
        desc: {
            ru: 'Нераспечатанная пачка офисной бумаги. Тащат такое только от безысходности, зато никто не хватится.',
            ua: 'Нерозпечатана пачка офісного паперу. Тягнуть таке лише з безвиході, зате ніхто не схопиться.',
            en: 'An unopened case of copy paper. You only carry this out when nothing better is left, but nobody ever reports it missing.',
            de: 'Ein ungeöffneter Karton Kopierpapier. Das nimmt man nur mit, wenn nichts Besseres bleibt, dafür vermisst es niemand.',
            pl: 'Nieotwarta ryza papieru do drukarki. Bierze się to z bezradności, za to nikt tego nie zgłosi.',
        },
    },
    woodenCrate: {
        name: {
            ru: 'Заколоченный ящик',
            ua: 'Забитий ящик',
            en: 'Nailed-down crate',
            de: 'Zugenagelte Kiste',
            pl: 'Zabita skrzynia',
        },
        desc: {
            ru: 'Сколочен на совесть, штамп на боку затёрт. Внутри что-то есть, но вскрывать некогда.',
            ua: 'Збитий на совість, штамп збоку затертий. Усередині щось є, але розкривати ніколи.',
            en: 'Nailed shut properly, the stencil on the side worn off. Something is in there, but there is no time to find out what.',
            de: 'Ordentlich zugenagelt, die Schablone an der Seite abgerieben. Da ist etwas drin, aber keine Zeit nachzusehen.',
            pl: 'Solidnie zabita gwoździami, szablon z boku starty. Coś w niej jest, ale nie ma kiedy sprawdzać.',
        },
    },
    clothesCrate: {
        name: {
            ru: 'Ящик с одеждой',
            ua: 'Ящик з одягом',
            en: 'Crate of clothes',
            de: 'Kiste mit Kleidung',
            pl: 'Skrzynia z ubraniami',
        },
        desc: {
            ru: 'Пластиковый контейнер, из-под крышки торчит рукав. Тряпьё как тряпьё, но на вес берут и такое.',
            ua: "Пластиковий контейнер, з-під кришки стирчить рукав. Ганчір'я як ганчір'я, але на вагу беруть і таке.",
            en: 'A plastic crate with a sleeve poking out from under the lid. Rags are rags, but they get bought by weight.',
            de: 'Eine Plastikkiste, unter dem Deckel schaut ein Ärmel hervor. Lumpen bleiben Lumpen, doch auch die gehen nach Gewicht weg.',
            pl: 'Plastikowa skrzynia, spod pokrywy wystaje rękaw. Szmaty jak szmaty, ale i takie idą na wagę.',
        },
    },
    suitcase: {
        name: {
            ru: 'Чемодан',
            ua: 'Валіза',
            en: 'Suitcase',
            de: 'Koffer',
            pl: 'Walizka',
        },
        desc: {
            ru: 'Мягкий чемодан с биркой аэропорта, так и не снятой. Судя по весу, разбирать его после отпуска не стали.',
            ua: 'М\'яка валіза з биркою аеропорту, так і не знятою. Судячи з ваги, розбирати її після відпустки не стали.',
            en: 'A soft suitcase with the airport tag still on it. By the weight, nobody unpacked it after the holiday.',
            de: 'Ein weicher Koffer, der Flughafenanhänger hängt noch dran. Dem Gewicht nach hat ihn nach dem Urlaub niemand ausgepackt.',
            pl: 'Miękka walizka z wciąż przyczepioną przywieszką z lotniska. Sądząc po wadze, nikt jej po urlopie nie rozpakował.',
        },
    },
    sportsBag: {
        name: {
            ru: 'Спортивная сумка',
            ua: 'Спортивна сумка',
            en: 'Sports holdall',
            de: 'Sporttasche',
            pl: 'Torba sportowa',
        },
        desc: {
            ru: 'Красная сумка из-под кровати. Внутри форма, кроссовки и что-то тяжёлое на самом дне.',
            ua: 'Червона сумка з-під ліжка. Усередині форма, кросівки і щось важке на самому дні.',
            en: 'A red holdall from under the bed. Kit, trainers, and something heavy right at the bottom.',
            de: 'Eine rote Sporttasche unter dem Bett hervor. Trikot, Turnschuhe und ganz unten etwas Schweres.',
            pl: 'Czerwona torba spod łóżka. W środku strój, buty i coś ciężkiego na samym dnie.',
        },
    },
    vinylBag: {
        name: {
            ru: 'Сумка с винилом',
            ua: 'Сумка з вінілом',
            en: 'Bag of records',
            de: 'Plattentasche',
            pl: 'Torba z winylami',
        },
        desc: {
            ru: 'Сумка диджея, набитая пластинками. Половина тиража давно не переиздавалась, и на этом можно поднять.',
            ua: 'Сумка діджея, напхана платівками. Половина накладу давно не перевидавалася, і на цьому можна підняти.',
            en: 'A DJ bag packed with records. Half the pressings have never been reissued, and that is where the money is.',
            de: 'Eine DJ-Tasche voller Platten. Die Hälfte der Pressungen wurde nie neu aufgelegt, und genau daran verdient man.',
            pl: 'Torba didżeja wypchana płytami. Połowa tłoczeń nigdy nie doczekała się wznowienia i właśnie na tym się zarabia.',
        },
    },
    golfBag: {
        name: {
            ru: 'Сумка для гольфа',
            ua: 'Сумка для гольфу',
            en: 'Golf bag',
            de: 'Golfbag',
            pl: 'Torba golfowa',
        },
        desc: {
            ru: 'Полный набор клюшек в розовом чехле. Смотрится в этой квартире так же неуместно, как и на плече у вора.',
            ua: 'Повний набір ключок у рожевому чохлі. Виглядає в цій квартирі так само недоречно, як і на плечі у злодія.',
            en: "A full set of clubs in a pink bag. It looks as out of place in this flat as it does on a burglar's shoulder.",
            de: 'Ein kompletter Satz Schläger in einem rosa Bag. In dieser Wohnung wirkt er so fehl am Platz wie auf der Schulter eines Einbrechers.',
            pl: 'Pełny zestaw kijów w różowym pokrowcu. W tym mieszkaniu wygląda równie nie na miejscu, co na ramieniu włamywacza.',
        },
    },
    weaponsBag: {
        name: {
            ru: 'Сумка с оружием',
            ua: 'Сумка зі зброєю',
            en: 'Bag of guns',
            de: 'Waffentasche',
            pl: 'Torba z bronią',
        },
        desc: {
            ru: 'Из приоткрытой молнии торчит ствол. Хозяин такой пропажи в полицию не пойдёт, но искать будет сам.',
            ua: 'З привідкритої блискавки стирчить ствол. Господар такої пропажі в поліцію не піде, але шукати буде сам.',
            en: 'A barrel sticking out of the half-open zip. The owner will not be calling the police about this one, but he will come looking himself.',
            de: 'Aus dem halb offenen Reißverschluss ragt ein Lauf. Wegen so etwas ruft der Besitzer nicht die Polizei, er sucht selbst.',
            pl: 'Z na wpół rozsuniętego zamka wystaje lufa. Właściciel z taką stratą na policję nie pójdzie, ale sam zacznie szukać.',
        },
    },
    organCooler: {
        name: {
            ru: 'Контейнер для органов',
            ua: 'Контейнер для органів',
            en: 'Organ transport cooler',
            de: 'Organtransportbox',
            pl: 'Pojemnik transportowy na organy',
        },
        desc: {
            ru: 'Медицинский термоконтейнер с надписью "human organ for transport". Что он делает в жилой квартире, лучше не спрашивать, а скупщик и не спросит.',
            ua: 'Медичний термоконтейнер з написом "human organ for transport". Що він робить у житловій квартирі, краще не питати, а скупник і не спитає.',
            en: 'A medical cooler stencilled "human organ for transport". What it is doing in somebody\'s flat is not a question to ask, and the fence will not ask it either.',
            de: 'Eine medizinische Kühlbox mit dem Aufdruck "human organ for transport". Was sie in einer Wohnung zu suchen hat, fragt man besser nicht, und der Hehler fragt es auch nicht.',
            pl: 'Medyczny pojemnik chłodzący z napisem "human organ for transport". Co robi w czyimś mieszkaniu, lepiej nie pytać, a paser i tak nie zapyta.',
        },
    },
};

export default burglarItems;
