export const food = {
    burger: {
        name: {
            ua: 'Бургер',
            en: 'Burger',
            ru: 'Бургер',
            de: 'Burger',
            pl: 'Burger',
        },
        desc: {
            ua: 'Дуже смачний та ситний бургер',
            en: 'Very tasty and hearty burger',
            ru: 'Очень вкусный насыщенный бургер',
            de: 'Sehr leckerer und herzhafter Burger',
            pl: 'Bardzo smaczny i sycący burger',
        },
    },
    donut: {
        name: {
            ua: 'Пончик',
            en: 'Donut',
            ru: 'Пончик',
            de: 'Donut',
            pl: 'Pączek',
        },
        desc: {
            ua: 'Солодкий пончик',
            en: 'Sweet donut',
            ru: 'Сладкий пончик',
            de: 'Süßer Donut',
            pl: 'Słodki pączek',
        },
    },
    chocolate: {
        name: {
            ua: 'Шоколадка',
            en: 'Chocolate',
            ru: 'Шоколадка',
            de: 'Schokolade',
            pl: 'Czekolada',
        },
        desc: {
            ua: 'Молочний шоколад',
            en: 'Milk chocolate',
            ru: 'Молочный шоколад',
            de: 'Milchschokolade',
            pl: 'Czekolada mleczna',
        },
    },
    cola: {
        name: {
            ua: 'Газировка',
            en: 'Cola',
            ru: 'Газировка',
            de: 'Cola',
            pl: 'Cola',
        },
        desc: {
            ua: 'Газована кола',
            en: 'Carbonated cola',
            ru: 'Газированная кола',
            de: 'Kohlensäurehaltige Cola',
            pl: 'Gazowany napój cola',
        },
    },
    water: {
        name: {
            ua: 'Вода',
            en: 'Water',
            ru: 'Вода',
            de: 'Wasser',
            pl: 'Woda',
        },
        desc: {
            ua: 'Чиста вода',
            en: 'Clean water',
            ru: 'Чистая вода',
            de: 'Reines Wasser',
            pl: 'Czysta woda',
        },
    },
    beer: {
        name: {
            ua: 'Пиво',
            en: 'Beer',
            ru: 'Пиво',
            de: 'Bier',
            pl: 'Piwo',
        },
        desc: {
            ua: 'Світле пиво',
            en: 'Light beer',
            ru: 'Светлое пиво',
            de: 'Helles Bier',
            pl: 'Jasne piwo',
        },
    },
    wine: {
        name: {
            ua: 'Вино',
            en: 'Wine',
            ru: 'Вино',
            de: 'Wein',
            pl: 'Wino',
        },
        desc: {
            ua: 'Червоне вино',
            en: 'Red wine',
            ru: 'Красное вино',
            de: 'Roter Wein',
            pl: 'Czerwone wino',
        },
    },
    vodka: {
        name: {
            ua: 'Горілка',
            en: 'Vodka',
            ru: 'Водка',
            de: 'Wodka',
            pl: 'Wódka',
        },
        desc: {
            ua: 'Українська горілка',
            en: 'Ukrainian vodka',
            ru: 'Украинская горілка',
            de: 'Ukrainischer Wodka',
            pl: 'Ukraińska wódka',
        },
    },
    whiskey: {
        name: {
            ua: 'Віскі',
            en: 'Whiskey',
            ru: 'Виски',
            de: 'Whiskey',
            pl: 'Whisky',
        },
        desc: {
            ua: 'Шотландський віскі',
            en: 'Scottish whiskey',
            ru: 'Шотландский виски',
            de: 'Schottischer Whiskey',
            pl: 'Szkocka whisky',
        },
    },
    apple: {
        name: {
            ua: 'Яблуко',
            en: 'Apple',
            ru: 'Яблоко',
            de: 'Apfel',
            pl: 'Jabłko',
        },
        desc: {
            ua: 'Соковите та освіжаюче яблуко',
            en: 'Juicy and refreshing apple',
            ru: 'Сочное и освежающее яблоко',
            de: 'Saftiger und erfrischender Apfel',
            pl: 'Soczyste i orzeźwiające jabłko',
        },
    },
    candy: {
        name: {
            ua: 'Цукерки',
            ru: 'Конфеты',
            en: 'Candies',
            de: 'Süßigkeiten',
            pl: 'Cukierki',
        },
        desc: {
            ua: 'Ви можете обміняти їх на подарунок у Санта-клауса',
            ru: 'Вы можете обменять их на подарок у Санта-Клауса',
            en: 'You can exchange them for a gift from Santa Claus',
            de: 'Sie können sie gegen ein Geschenk von Santa Claus eintauschen',
            pl: 'Możesz wymienić je na prezent od Świętego Mikołaja',
        },
    },
    orange: {
        name: {
            ru: 'Апельсин',
            ua: 'Апельсин',
            en: 'Orange',
            de: 'Orange',
            pl: 'Pomarańcza',
            ge: 'ფორთოხალი',
        },
        desc: {
            ru: 'Сочный апельсин, можно продать скупщику или съесть',
            ua: "Соковитий апельсин, можна продати скупщику або з'їсти",
            en: 'Juicy orange, can be sold to a buyer or eaten',
            de: 'Saftige Orange, kann an einen Käufer verkauft oder gegessen werden',
            pl: 'Soczysta pomarańcza, można sprzedać kupcowi lub zjeść',
            ge: 'წვენიანი ფორთოხალი, შეიძლება გაიყიდოს მყიდველზე ან შეჭამონ',
        },
    },
};
