export const food = {
    burger: {
        name: {
            ua: 'Бургер',
            en: 'Burger',
            ru: 'Бургер',
            de: 'Burger',
            pl: 'Burger',
            zh: '汉堡',
        },
        desc: {
            ua: 'Дуже смачний та ситний бургер',
            en: 'Very tasty and hearty burger',
            ru: 'Очень вкусный насыщенный бургер',
            de: 'Sehr leckerer und herzhafter Burger',
            pl: 'Bardzo smaczny i sycący burger',
            zh: '非常美味丰盛的汉堡',
        },
    },
    donut: {
        name: {
            ua: 'Пончик',
            en: 'Donut',
            ru: 'Пончик',
            de: 'Donut',
            pl: 'Pączek',
            zh: '甜甜圈',
        },
        desc: {
            ua: 'Солодкий пончик',
            en: 'Sweet donut',
            ru: 'Сладкий пончик',
            de: 'Süßer Donut',
            pl: 'Słodki pączek',
            zh: '甜甜圈',
        },
    },
    chocolate: {
        name: {
            ua: 'Шоколадка',
            en: 'Chocolate',
            ru: 'Шоколадка',
            de: 'Schokolade',
            pl: 'Czekolada',
            zh: '巧克力',
        },
        desc: {
            ua: 'Молочний шоколад',
            en: 'Milk chocolate',
            ru: 'Молочный шоколад',
            de: 'Milchschokolade',
            pl: 'Czekolada mleczna',
            zh: '牛奶巧克力',
        },
    },
    cola: {
        name: {
            ua: 'Газировка',
            en: 'Cola',
            ru: 'Газировка',
            de: 'Cola',
            pl: 'Cola',
            zh: '可乐',
        },
        desc: {
            ua: 'Газована кола',
            en: 'Carbonated cola',
            ru: 'Газированная кола',
            de: 'Kohlensäurehaltige Cola',
            pl: 'Gazowany napój cola',
            zh: '碳酸可乐',
        },
    },
    water: {
        name: {
            ua: 'Вода',
            en: 'Water',
            ru: 'Вода',
            de: 'Wasser',
            pl: 'Woda',
            zh: '水',
        },
        desc: {
            ua: 'Чиста вода',
            en: 'Clean water',
            ru: 'Чистая вода',
            de: 'Reines Wasser',
            pl: 'Czysta woda',
            zh: '清洁的水',
        },
    },
    beer: {
        name: {
            ua: 'Пиво',
            en: 'Beer',
            ru: 'Пиво',
            de: 'Bier',
            pl: 'Piwo',
            zh: '啤酒',
        },
        desc: {
            ua: 'Світле пиво',
            en: 'Light beer',
            ru: 'Светлое пиво',
            de: 'Helles Bier',
            pl: 'Jasne piwo',
            zh: '淡啤酒',
        },
    },
    wine: {
        name: {
            ua: 'Вино',
            en: 'Wine',
            ru: 'Вино',
            de: 'Wein',
            pl: 'Wino',
            zh: '葡萄酒',
        },
        desc: {
            ua: 'Червоне вино',
            en: 'Red wine',
            ru: 'Красное вино',
            de: 'Roter Wein',
            pl: 'Czerwone wino',
            zh: '红酒',
        },
    },
    vodka: {
        name: {
            ua: 'Горілка',
            en: 'Vodka',
            ru: 'Водка',
            de: 'Wodka',
            pl: 'Wódka',
            zh: '伏特加',
        },
        desc: {
            ua: 'Українська горілка',
            en: 'Ukrainian vodka',
            ru: 'Украинская горілка',
            de: 'Ukrainischer Wodka',
            pl: 'Ukraińska wódka',
            zh: '乌克兰伏特加',
        },
    },
    whiskey: {
        name: {
            ua: 'Віскі',
            en: 'Whiskey',
            ru: 'Виски',
            de: 'Whiskey',
            pl: 'Whisky',
            zh: '威士忌',
        },
        desc: {
            ua: 'Шотландський віскі',
            en: 'Scottish whiskey',
            ru: 'Шотландский виски',
            de: 'Schottischer Whiskey',
            pl: 'Szkocka whisky',
            zh: '苏格兰威士忌',
        },
    },
    apple: {
        name: {
            ua: 'Яблуко',
            en: 'Apple',
            ru: 'Яблоко',
            de: 'Apfel',
            pl: 'Jabłko',
            zh: '苹果',
        },
        desc: {
            ua: 'Соковите та освіжаюче яблуко',
            en: 'Juicy and refreshing apple',
            ru: 'Сочное и освежающее яблоко',
            de: 'Saftiger und erfrischender Apfel',
            pl: 'Soczyste i orzeźwiające jabłko',
            zh: '柔软新鲜的苹果',
        },
    },
    candy: {
        name: {
            ua: 'Цукерки',
            ru: 'Конфеты',
            en: 'Candies',
            de: 'Süßigkeiten',
            pl: 'Cukierki',
            zh: '糖果',
        },
        desc: {
            ru: 'Можно обменять у Санта Клауса на кейсы с которых ты можешь выбить новогоднюю одежду и другие подарки!',
            ua: 'Можна обміняти у Санта-Клауса на кейси, з яких ти можеш отримати новорічний одяг та інші подарунки!',
            en: 'Can be exchanged with Santa Claus for cases from which you can get Christmas clothes and other gifts!',
            de: 'Kann beim Weihnachtsmann gegen Kisten eingetauscht werden, aus denen du Weihnachtskleidung und andere Geschenke erhalten kannst!',
            pl: 'Można wymienić u Świętego Mikołaja na skrzynki, z których można zdobyć świąteczne ubrania i inne prezenty!',
        },
    },
    orange: {
        name: {
            ru: 'Апельсин',
            ua: 'Апельсин',
            en: 'Orange',
            de: 'Orange',
            pl: 'Pomarańcza',
            ge: 'ფორთოხალი',
            zh: '橙色',
        },
        desc: {
            ru: 'Сочный апельсин, можно продать скупщику или съесть',
            ua: "Соковитий апельсин, можна продати скупщику або з'їсти",
            en: 'Juicy orange, can be sold to a buyer or eaten',
            de: 'Saftige Orange, kann an einen Käufer verkauft oder gegessen werden',
            pl: 'Soczysta pomarańcza, można sprzedać kupcowi lub zjeść',
            ge: 'წვენიანი ფორთოხალი, შეიძლება გაიყიდოს მყიდველზე ან შეჭამონ',
            zh: '糖橙，可以卖也可以吃',
        },
    },
    melon_juice: {
        name: {
            ru: 'Арбузный коктейль',
            ua: 'Кавуновий коктейль',
            en: 'Watermelon Cocktail',
            de: 'Wassermelonen-Cocktail',
            pl: 'Koktajl arbuzowy',
            zh: '西瓜鸡尾酒',
        },
        desc: {
            ru: 'Летний коктейль из свежего арбуза. Можно продать скупщику или выпить для освежения',
            ua: 'Літній коктейль зі свіжого кавуна. Можна продати скупнику або випити для освіження',
            en: 'Summer cocktail made from fresh watermelon. Can be sold to a trader or enjoyed for refreshment',
            de: 'Sommercocktail aus frischer Wassermelone. Kann an einen Händler verkauft oder zur Erfrischung getrunken werden',
            pl: 'Letni koktajl z świeżego arbuza. Może być sprzedany handlarzowi lub wypity dla orzeźwienia',
            zh: '用新鲜草调制的夏季鸡尾酒。你可以卖给商人，或者把它当点心喝',
        },
    },

    // New since 08/24/2024
    pretzels: {
        name: {
            ua: 'Прецелі',
            en: 'Pretzels',
            ru: 'Пряцели',
            de: 'Brezeln',
            pl: 'Precle',
            zh: '椒盐脆饼',
        },
        desc: {
            ua: 'Солоні прецелі, чудово підходять як закуска',
            en: 'Salty pretzels, perfect as a snack',
            ru: 'Соленые пряцели, идеально подходят в качестве закуски',
            de: 'Salzige Brezeln, perfekt als Snack',
            pl: 'Słone precle, idealne jako przekąska',
            zh: '咸味椒盐脆饼，作为零食的完美选择”中',
        },
    },
    peanuts: {
        name: {
            ua: 'Арахіс',
            en: 'Peanuts',
            ru: 'Арахис',
            de: 'Erdnüsse',
            pl: 'Orzeszki ziemne',
            zh: '花生',
        },
        desc: {
            ua: 'Смачний та корисний арахіс',
            en: 'Tasty and nutritious peanuts',
            ru: 'Вкусный и питательный арахис',
            de: 'Leckere und nahrhafte Erdnüsse',
            pl: 'Smaczne i odżywcze orzeszki ziemne',
            zh: '美味营养的土豆',
        },
    },
    olymp_energy: {
        name: {
            ua: 'Olymp Energy',
            en: 'Olymp Energy',
            ru: 'Olymp Energy',
            de: 'Olymp Energy',
            pl: 'Olymp Energy',
            zh: '奥林普能源',
        },
        desc: {
            ua: 'Енергетичний напій для підвищення енергії',
            en: 'Energy drink to boost your energy',
            ru: 'Энергетический напиток для повышения энергии',
            de: 'Energydrink zur Steigerung der Energie',
            pl: 'Napój energetyczny na zwiększenie energii',
            zh: '能量饮料可以增加能量',
        },
    },
    pepsi_can: {
        name: {
            ua: 'Pepsi',
            en: 'Pepsi',
            ru: 'Pepsi',
            de: 'Pepsi',
            pl: 'Pepsi',
            zh: '百事可乐',
        },
        desc: {
            ua: 'Класична Pepsi у банці',
            en: 'Classic Pepsi in a can',
            ru: 'Классическая Pepsi в банке',
            de: 'Klassische Pepsi in der Dose',
            pl: 'Klasyczna Pepsi w puszce',
            zh: '沙漠中的经典百事可乐',
        },
    },
    pepsi_can_black: {
        name: {
            ua: 'Pepsi Black',
            en: 'Pepsi Black',
            ru: 'Pepsi Black',
            de: 'Pepsi Black',
            pl: 'Pepsi Black',
            zh: '百事黑',
        },
        desc: {
            ua: 'Pepsi без цукру у банці',
            en: 'Sugar-free Pepsi in a can',
            ru: 'Pepsi без сахара в банке',
            de: 'Zuckerfreie Pepsi in der Dose',
            pl: 'Pepsi bez cukru w puszce',
            zh: '没有糖的百事可乐',
        },
    },
    croissant: {
        name: {
            ua: 'Круасан',
            en: 'Croissant',
            ru: 'Круассан',
            de: 'Croissant',
            pl: 'Rogal',
            zh: '罗加尔',
        },
        desc: {
            ua: 'Ніжний круасан з маслом',
            en: 'Delicate butter croissant',
            ru: 'Нежный круассан с маслом',
            de: 'Zartes Buttercroissant',
            pl: 'Delikatny rogalik z masłem',
            zh: '黄油牛角面包',
        },
    },
    donut_white: {
        name: {
            ua: `Пончик з білою глазур'ю`,
            en: 'Donut with white glaze',
            ru: 'Пончик с белой глазурью',
            de: 'Donut mit weißer Glasur',
            pl: 'Pączek z białą polewą',
            zh: '白釉甜甜圈',
        },
        desc: {
            ua: `Солодкий пончик з білою глазур'ю`,
            en: 'Sweet donut with white glaze',
            ru: 'Сладкий пончик с белой глазурью',
            de: 'Süßer Donut mit weißer Glasur',
            pl: 'Słodki pączek z białą polewą',
            zh: '甜白色粉末',
        },
    },
    donut_black: {
        name: {
            ua: 'Пончик з чорним шоколадом',
            en: 'Donut with black chocolate',
            ru: 'Пончик с черным шоколадом',
            de: 'Donut mit schwarzer Schokolade',
            pl: 'Pączek z czarną czekoladą',
            zh: '黑巧克力甜甜圈',
        },
        desc: {
            ua: 'Солодкий пончик з чорним шоколадом',
            en: 'Sweet donut with black chocolate',
            ru: 'Сладкий пончик с черным шоколадом',
            de: 'Süßer Donut mit schwarzer Schokolade',
            pl: 'Słodki pączek z czarną czekoladą',
            zh: '甜圈配黑巧克力',
        },
    },
    oolong_tea: {
        name: {
            ru: 'Улун-ча «Grand Blue»',
            ua: 'Улун-ча «Grand Blue»',
            en: 'Grand Blue Oolong Tea',
            de: 'Grand Blue Oolong-Tee',
            pl: 'Herbata oolong „Grand Blue”',
        },
        desc: {
            ru: 'С виду обычный улун, но внутри фирменный коктейль дайверов-алкоголиков. Лайфхак: подожги — если вспыхнуло, «чай» правильный.',
            ua: 'На вигляд звичайний улун, але всередині фірмовий коктейль дайверів-алкоголіків. Лайфхак: підпали — як спалахне, «чай» справжній.',
            en: 'Looks like plain oolong, but the bottle hides the divers’ signature booze blend. Pro tip: set it on fire — if it burns, it’s the “real” tea.',
            de: 'Sieht aus wie gewöhnlicher Oolong, aber innen steckt der legendäre Alkohol-Mix der Taucher. Tipp: Zünde es an – wenn’s brennt, ist es der echte „Tee“.',
            pl: 'Wygląda jak zwykły oolong, ale w środku jest firmowy koktajl alkoholików-nurków. Pro tip: podpal — jeśli zapłonie, to „prawdziwa” herbata.',
        },
    },
    cheeseburger: {
        name: {
            ru: 'Чизбургер',
            ua: 'Чізбургер',
            en: 'Cheeseburger',
            de: 'Cheeseburger',
            pl: 'Cheeseburger',
        },
        desc: {
            ru: 'Классика — сочная котлета, расплавленный сыр и свежая булочка.',
            ua: 'Класика — соковита котлета, розплавлений сир і свіжа булочка.',
            en: 'A classic — juicy patty, melted cheese, and a fresh bun.',
            de: 'Klassiker – saftiges Patty, geschmolzener Käse und frisches Brötchen.',
            pl: 'Klasyk — soczysty kotlet, roztopiony ser i świeża bułka.',
        },
    },

    double_burger: {
        name: {
            ru: 'Двойной бургер',
            ua: 'Подвійний бургер',
            en: 'Double Burger',
            de: 'Doppelburger',
            pl: 'Podwójny burger',
        },
        desc: {
            ru: 'Две котлеты, дважды вкуснее. Для настоящих прожор.',
            ua: 'Дві котлети, вдвічі смачніше. Для справжніх ненажер.',
            en: 'Two patties, twice the flavor. For real food lovers.',
            de: 'Zwei Patties, doppelt so lecker. Für echte Vielfraße.',
            pl: 'Dwa kotlety, dwa razy smaczniej. Dla prawdziwych żarłoków.',
        },
    },

    chicken_burger: {
        name: {
            ru: 'Чикенбургер',
            ua: 'Чікенбургер',
            en: 'Chicken Burger',
            de: 'Chicken Burger',
            pl: 'Chicken Burger',
        },
        desc: {
            ru: 'Куриное мясо, салат и соус в мягкой булочке. Легко и вкусно.',
            ua: 'Куряче м’ясо, салат і соус у м’якій булочці. Легко й смачно.',
            en: 'Chicken, lettuce, and sauce in a soft bun. Light and tasty.',
            de: 'Hähnchenfleisch, Salat und Soße im weichen Brötchen. Leicht und lecker.',
            pl: 'Kurczak, sałata i sos w miękkiej bułce. Lekko i smacznie.',
        },
    },

    fries: {
        name: {
            ru: 'Картошка фри',
            ua: 'Картопля фрі',
            en: 'French Fries',
            de: 'Pommes Frites',
            pl: 'Frytki',
        },
        desc: {
            ru: 'Хрустящая, золотистая и всегда в тему.',
            ua: 'Хрустка, золотиста і завжди доречна.',
            en: 'Crispy, golden, and always on point.',
            de: 'Knusprig, goldbraun und immer passend.',
            pl: 'Chrupiące, złociste i zawsze na czasie.',
        },
    },

    onion_rings: {
        name: {
            ru: 'Луковые кольца',
            ua: 'Цибулеві кільця',
            en: 'Onion Rings',
            de: 'Zwiebelringe',
            pl: 'Krążki cebulowe',
        },
        desc: {
            ru: 'Золотистые кольца лука в панировке. Идеальны к бургеру.',
            ua: 'Золотисті кільця цибулі в паніровці. Ідеальні до бургера.',
            en: 'Golden onion rings in crispy breading. Perfect with a burger.',
            de: 'Goldene Zwiebelringe in knuspriger Panade. Perfekt zum Burger.',
            pl: 'Złociste krążki cebuli w panierce. Idealne do burgera.',
        },
    },

    nuggets: {
        name: {
            ru: 'Наггетсы',
            ua: 'Нагетси',
            en: 'Nuggets',
            de: 'Nuggets',
            pl: 'Nuggetsy',
        },
        desc: {
            ru: 'Маленькие кусочки счастья из сочной курочки.',
            ua: 'Маленькі шматочки щастя з соковитої курочки.',
            en: 'Little bites of happiness made from juicy chicken.',
            de: 'Kleine Stücke Glück aus saftigem Hähnchen.',
            pl: 'Małe kawałki szczęścia z soczystego kurczaka.',
        },
    },

    hotdog: {
        name: {
            ru: 'Хот-дог',
            ua: 'Хот-дог',
            en: 'Hot Dog',
            de: 'Hotdog',
            pl: 'Hot-dog',
        },
        desc: {
            ru: 'Быстро, просто и вкусно. Уличная классика.',
            ua: 'Швидко, просто і смачно. Вулична класика.',
            en: 'Fast, simple, and tasty. Street food classic.',
            de: 'Schnell, einfach und lecker. Straßenklassiker.',
            pl: 'Szybko, prosto i smacznie. Klasyka street foodu.',
        },
    },

    milkshake: {
        name: {
            ru: 'Молочный коктейль',
            ua: 'Молочний коктейль',
            en: 'Milkshake',
            de: 'Milchshake',
            pl: 'Shake mleczny',
        },
        desc: {
            ru: 'Сладкий, холодный и бодрящий. Вернись в детство.',
            ua: 'Солодкий, холодний і бадьорий. Повертайся в дитинство.',
            en: 'Sweet, cold, and refreshing. Go back to your childhood.',
            de: 'Süß, kalt und erfrischend. Geh zurück in deine Kindheit.',
            pl: 'Słodki, zimny i orzeźwiający. Wróć do dzieciństwa.',
        },
    },

    coffee: {
        name: {
            ru: 'Кофе',
            ua: 'Кава',
            en: 'Coffee',
            de: 'Kaffee',
            pl: 'Kawa',
        },
        desc: {
            ru: 'Ароматный кофе для тех, кто ещё не проснулся.',
            ua: 'Ароматна кава для тих, хто ще не прокинувся.',
            en: 'Aromatic coffee for those who haven’t woken up yet.',
            de: 'Aromatischer Kaffee für alle, die noch nicht wach sind.',
            pl: 'Aromatyczna kawa dla tych, którzy jeszcze się nie obudzili.',
        },
    },

    ice_cream: {
        name: {
            ru: 'Мороженое',
            ua: 'Морозиво',
            en: 'Ice Cream',
            de: 'Eiscreme',
            pl: 'Lody',
        },
        desc: {
            ru: 'Пломбир, который растопит твоё сердце.',
            ua: 'Пломбір, що розтопить твоє серце.',
            en: 'Ice cream that will melt your heart.',
            de: 'Eis, das dein Herz schmelzen lässt.',
            pl: 'Lody, które roztopią twoje serce.',
        },
    },
};
