export const food = {
    burger: {
        name: {
            ua: 'Бургер',
            en: 'Burger',
            ru: 'Бургер',
            de: 'Burger',
            pl: 'Burger',
        },
        desc: {
            ua: 'Дуже смачний та ситний бургер',
            en: 'Very tasty and hearty burger',
            ru: 'Очень вкусный насыщенный бургер',
            de: 'Sehr leckerer und herzhafter Burger',
            pl: 'Bardzo smaczny i sycący burger',
        },
    },
    donut: {
        name: {
            ua: 'Пончик',
            en: 'Donut',
            ru: 'Пончик',
            de: 'Donut',
            pl: 'Pączek',
        },
        desc: {
            ua: 'Солодкий пончик',
            en: 'Sweet donut',
            ru: 'Сладкий пончик',
            de: 'Süßer Donut',
            pl: 'Słodki pączek',
        },
    },
    chocolate: {
        name: {
            ua: 'Шоколадка',
            en: 'Chocolate',
            ru: 'Шоколадка',
            de: 'Schokolade',
            pl: 'Czekolada',
        },
        desc: {
            ua: 'Молочний шоколад',
            en: 'Milk chocolate',
            ru: 'Молочный шоколад',
            de: 'Milchschokolade',
            pl: 'Czekolada mleczna',
        },
    },
    cola: {
        name: {
            ua: 'Газировка',
            en: 'Cola',
            ru: 'Газировка',
            de: 'Cola',
            pl: 'Cola',
        },
        desc: {
            ua: 'Газована кола',
            en: 'Carbonated cola',
            ru: 'Газированная кола',
            de: 'Kohlensäurehaltige Cola',
            pl: 'Gazowany napój cola',
        },
    },
    water: {
        name: {
            ua: 'Вода',
            en: 'Water',
            ru: 'Вода',
            de: 'Wasser',
            pl: 'Woda',
        },
        desc: {
            ua: 'Чиста вода',
            en: 'Clean water',
            ru: 'Чистая вода',
            de: 'Reines Wasser',
            pl: 'Czysta woda',
        },
    },
    beer: {
        name: {
            ua: 'Пиво',
            en: 'Beer',
            ru: 'Пиво',
            de: 'Bier',
            pl: 'Piwo',
        },
        desc: {
            ua: 'Світле пиво',
            en: 'Light beer',
            ru: 'Светлое пиво',
            de: 'Helles Bier',
            pl: 'Jasne piwo',
        },
    },
    wine: {
        name: {
            ua: 'Вино',
            en: 'Wine',
            ru: 'Вино',
            de: 'Wein',
            pl: 'Wino',
        },
        desc: {
            ua: 'Червоне вино',
            en: 'Red wine',
            ru: 'Красное вино',
            de: 'Roter Wein',
            pl: 'Czerwone wino',
        },
    },
    vodka: {
        name: {
            ua: 'Горілка',
            en: 'Vodka',
            ru: 'Водка',
            de: 'Wodka',
            pl: 'Wódka',
        },
        desc: {
            ua: 'Українська горілка',
            en: 'Ukrainian vodka',
            ru: 'Украинская горілка',
            de: 'Ukrainischer Wodka',
            pl: 'Ukraińska wódka',
        },
    },
    whiskey: {
        name: {
            ua: 'Віскі',
            en: 'Whiskey',
            ru: 'Виски',
            de: 'Whiskey',
            pl: 'Whisky',
        },
        desc: {
            ua: 'Шотландський віскі',
            en: 'Scottish whiskey',
            ru: 'Шотландский виски',
            de: 'Schottischer Whiskey',
            pl: 'Szkocka whisky',
        },
    },
    apple: {
        name: {
            ua: 'Яблуко',
            en: 'Apple',
            ru: 'Яблоко',
            de: 'Apfel',
            pl: 'Jabłko',
        },
        desc: {
            ua: 'Соковите та освіжаюче яблуко',
            en: 'Juicy and refreshing apple',
            ru: 'Сочное и освежающее яблоко',
            de: 'Saftiger und erfrischender Apfel',
            pl: 'Soczyste i orzeźwiające jabłko',
        },
    },
    candy: {
        name: {
            ua: 'Цукерки',
            ru: 'Конфеты',
            en: 'Candies',
            de: 'Süßigkeiten',
            pl: 'Cukierki',
        },
        desc: {
            ua: 'Ви можете обміняти їх на подарунок у Санта-клауса',
            ru: 'Вы можете обменять их на подарок у Санта-Клауса',
            en: 'You can exchange them for a gift from Santa Claus',
            de: 'Sie können sie gegen ein Geschenk von Santa Claus eintauschen',
            pl: 'Możesz wymienić je na prezent od Świętego Mikołaja',
        },
    },
    orange: {
        name: {
            ru: 'Апельсин',
            ua: 'Апельсин',
            en: 'Orange',
            de: 'Orange',
            pl: 'Pomarańcza',
            ge: 'ფორთოხალი',
        },
        desc: {
            ru: 'Сочный апельсин, можно продать скупщику или съесть',
            ua: "Соковитий апельсин, можна продати скупщику або з'їсти",
            en: 'Juicy orange, can be sold to a buyer or eaten',
            de: 'Saftige Orange, kann an einen Käufer verkauft oder gegessen werden',
            pl: 'Soczysta pomarańcza, można sprzedać kupcowi lub zjeść',
            ge: 'წვენიანი ფორთოხალი, შეიძლება გაიყიდოს მყიდველზე ან შეჭამონ',
        },
    },
    melon_juice: {
        name: {
            ru: 'Арбузный коктейль',
            ua: 'Кавуновий коктейль',
            en: 'Watermelon Cocktail',
            de: 'Wassermelonen-Cocktail',
            pl: 'Koktajl arbuzowy',
        },
        desc: {
            ru: 'Летний коктейль из свежего арбуза. Можно продать скупщику или выпить для освежения',
            ua: 'Літній коктейль зі свіжого кавуна. Можна продати скупнику або випити для освіження',
            en: 'Summer cocktail made from fresh watermelon. Can be sold to a trader or enjoyed for refreshment',
            de: 'Sommercocktail aus frischer Wassermelone. Kann an einen Händler verkauft oder zur Erfrischung getrunken werden',
            pl: 'Letni koktajl z świeżego arbuza. Może być sprzedany handlarzowi lub wypity dla orzeźwienia',
        },
    },

    // New since 08/24/2024
    pretzels: {
        name: {
            ua: 'Прецелі',
            en: 'Pretzels',
            ru: 'Пряцели',
            de: 'Brezeln',
            pl: 'Precle',
        },
        desc: {
            ua: 'Солоні прецелі, чудово підходять як закуска',
            en: 'Salty pretzels, perfect as a snack',
            ru: 'Соленые пряцели, идеально подходят в качестве закуски',
            de: 'Salzige Brezeln, perfekt als Snack',
            pl: 'Słone precle, idealne jako przekąska',
        },
    },
    peanuts: {
        name: {
            ua: 'Арахіс',
            en: 'Peanuts',
            ru: 'Арахис',
            de: 'Erdnüsse',
            pl: 'Orzeszki ziemne',
        },
        desc: {
            ua: 'Смачний та корисний арахіс',
            en: 'Tasty and nutritious peanuts',
            ru: 'Вкусный и питательный арахис',
            de: 'Leckere und nahrhafte Erdnüsse',
            pl: 'Smaczne i odżywcze orzeszki ziemne',
        },
    },
    olymp_energy: {
        name: {
            ua: 'Olymp Energy',
            en: 'Olymp Energy',
            ru: 'Olymp Energy',
            de: 'Olymp Energy',
            pl: 'Olymp Energy',
        },
        desc: {
            ua: 'Енергетичний напій для підвищення енергії',
            en: 'Energy drink to boost your energy',
            ru: 'Энергетический напиток для повышения энергии',
            de: 'Energydrink zur Steigerung der Energie',
            pl: 'Napój energetyczny na zwiększenie energii',
        },
    },
    pepsi_can: {
        name: {
            ua: 'Pepsi',
            en: 'Pepsi',
            ru: 'Pepsi',
            de: 'Pepsi',
            pl: 'Pepsi',
        },
        desc: {
            ua: 'Класична Pepsi у банці',
            en: 'Classic Pepsi in a can',
            ru: 'Классическая Pepsi в банке',
            de: 'Klassische Pepsi in der Dose',
            pl: 'Klasyczna Pepsi w puszce',
        },
    },
    pepsi_can_black: {
        name: {
            ua: 'Pepsi Black',
            en: 'Pepsi Black',
            ru: 'Pepsi Black',
            de: 'Pepsi Black',
            pl: 'Pepsi Black',
        },
        desc: {
            ua: 'Pepsi без цукру у банці',
            en: 'Sugar-free Pepsi in a can',
            ru: 'Pepsi без сахара в банке',
            de: 'Zuckerfreie Pepsi in der Dose',
            pl: 'Pepsi bez cukru w puszce',
        },
    },
    croissant: {
        name: {
            ua: 'Круасан',
            en: 'Croissant',
            ru: 'Круассан',
            de: 'Croissant',
            pl: 'Rogal',
        },
        desc: {
            ua: 'Ніжний круасан з маслом',
            en: 'Delicate butter croissant',
            ru: 'Нежный круассан с маслом',
            de: 'Zartes Buttercroissant',
            pl: 'Delikatny rogalik z masłem',
        },
    },
    donut_white: {
        name: {
            ua: `Пончик з білою глазур'ю`,
            en: 'Donut with white glaze',
            ru: 'Пончик с белой глазурью',
            de: 'Donut mit weißer Glasur',
            pl: 'Pączek z białą polewą',
        },
        desc: {
            ua: `Солодкий пончик з білою глазур'ю`,
            en: 'Sweet donut with white glaze',
            ru: 'Сладкий пончик с белой глазурью',
            de: 'Süßer Donut mit weißer Glasur',
            pl: 'Słodki pączek z białą polewą',
        },
    },
    donut_black: {
        name: {
            ua: 'Пончик з чорним шоколадом',
            en: 'Donut with black chocolate',
            ru: 'Пончик с черным шоколадом',
            de: 'Donut mit schwarzer Schokolade',
            pl: 'Pączek z czarną czekoladą',
        },
        desc: {
            ua: 'Солодкий пончик з чорним шоколадом',
            en: 'Sweet donut with black chocolate',
            ru: 'Сладкий пончик с черным шоколадом',
            de: 'Süßer Donut mit schwarzer Schokolade',
            pl: 'Słodki pączek z czarną czekoladą',
        },
    },
};
