export default {
    pumpkin_seeds: {
        name: {
            ru: 'Семена тыквы',
            ua: 'Насіння гарбуза',
            en: 'Pumpkin Seeds',
            de: 'Kürbiskerne',
            pl: 'Nasiona dyni',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания тыквы или использованы в кулинарии',
            ua: 'Можуть бути посаджені для вирощування гарбуза або використані в кулінарії',
            en: 'Can be planted to grow pumpkins or used in cooking',
            de: 'Können gepflanzt werden, um Kürbisse anzubauen oder in der Küche verwendet werden',
            pl: 'Mogą być sadzone w celu uprawy dyni lub używane w kuchni',
        },
    },
    pumpkin: {
        name: {
            ru: 'Тыква',
            ua: 'Гарбуз',
            en: 'Pumpkin',
            de: 'Kürbis',
            pl: 'Dynia',
        },
        desc: {
            ru: 'Может быть использована для приготовления блюд или продана',
            ua: 'Може бути використана для приготування страв або продана',
            en: 'Can be used for cooking dishes or sold',
            de: 'Kann zum Kochen von Gerichten verwendet oder verkauft werden',
            pl: 'Może być używana do gotowania potraw lub sprzedawana',
        },
    },
    watering_can: {
        name: {
            ru: 'Лейка',
            ua: 'Лійка',
            en: 'Watering Can',
            de: 'Gießkanne',
            pl: 'Konewka',
        },
        desc: {
            ru: 'Можно использовать для полива растений на ферме',
            ua: 'Можна використовувати для поливу рослин на фермі',
            en: 'Can be used for watering plants on the farm',
            de: 'Kann zum Bewässern von Pflanzen auf dem Bauernhof verwendet werden',
            pl: 'Można używać do podlewania roślin na farmie',
        },
    },
    potato: {
        name: {
            ru: 'Картофель',
            ua: 'Картопля',
            en: 'Potato',
            de: 'Kartoffel',
            pl: 'Ziemniak',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
        },
    },
    tomato: {
        name: {
            ru: 'Помидор',
            ua: 'Помідор',
            en: 'Tomato',
            de: 'Tomate',
            pl: 'Pomidor',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
        },
    },
    cabbage: {
        name: {
            ru: 'Капуста',
            ua: 'Капуста',
            en: 'Cabbage',
            de: 'Kohl',
            pl: 'Kapusta',
        },
        desc: {
            ru: 'Может быть использована для приготовления блюд или продана скупщику',
            ua: 'Може бути використана для приготування страв або продана скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używana do gotowania potraw lub sprzedana handlarzowi',
        },
    },
    onion: {
        name: {
            ru: 'Лук',
            ua: 'Цибуля',
            en: 'Onion',
            de: 'Zwiebel',
            pl: 'Cebula',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
        },
    },
    cucumber: {
        name: {
            ru: 'Огурец',
            ua: 'Огірок',
            en: 'Cucumber',
            de: 'Gurke',
            pl: 'Ogórek',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
        },
    },
    tomato_seeds: {
        name: {
            ru: 'Семена помидор',
            ua: 'Насіння помідорів',
            en: 'Tomato Seeds',
            de: 'Tomatensamen',
            pl: 'Nasiona pomidorów',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания помидор на ферме',
            ua: 'Можуть бути посаджені для вирощування помідорів на фермі',
            en: 'Can be planted to grow tomatoes on the farm',
            de: 'Können gepflanzt werden, um Tomaten auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy pomidorów na farmie',
        },
    },
    cabbage_seeds: {
        name: {
            ru: 'Семена капусты',
            ua: 'Насіння капусти',
            en: 'Cabbage Seeds',
            de: 'Kohlsamen',
            pl: 'Nasiona kapusty',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания капусты на ферме',
            ua: 'Можуть бути посаджені для вирощування капусти на фермі',
            en: 'Can be planted to grow cabbage on the farm',
            de: 'Können gepflanzt werden, um Kohl auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy kapusty na farmie',
        },
    },
    onion_seeds: {
        name: {
            ru: 'Семена лука',
            ua: 'Насіння цибулі',
            en: 'Onion Seeds',
            de: 'Zwiebelsamen',
            pl: 'Nasiona cebuli',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания лука на ферме',
            ua: 'Можуть бути посаджені для вирощування цибулі на фермі',
            en: 'Can be planted to grow onions on the farm',
            de: 'Können gepflanzt werden, um Zwiebeln auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy cebuli na farmie',
        },
    },
    cucumber_seeds: {
        name: {
            ru: 'Семена огурцов',
            ua: 'Насіння огірків',
            en: 'Cucumber Seeds',
            de: 'Gurkensamen',
            pl: 'Nasiona ogórków',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания огурцов на ферме',
            ua: 'Можуть бути посаджені для вирощування огірків на фермі',
            en: 'Can be planted to grow cucumbers on the farm',
            de: 'Können gepflanzt werden, um Gurken auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy ogórków na farmie',
        },
    },
    potato_seeds: {
        name: {
            ru: 'Семена картофеля',
            ua: 'Насіння картоплі',
            en: 'Potato Seeds',
            de: 'Kartoffelsamen',
            pl: 'Nasiona ziemniaków',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания картофеля на ферме',
            ua: 'Можуть бути посаджені для вирощування картоплі на фермі',
            en: 'Can be planted to grow potatoes on the farm',
            de: 'Können gepflanzt werden, um Kartoffeln auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy ziemniaków na farmie',
        },
    },
    sunflower_seeds: {
        name: {
            ru: 'Семена подсолнуха',
            ua: 'Насіння соняшника',
            en: 'Sunflower Seeds',
            de: 'Sonnenblumensamen',
            pl: 'Nasiona słonecznika',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания подсолнуха на ферме',
            ua: 'Можуть бути посаджені для вирощування соняшника на фермі',
            en: 'Can be planted to grow sunflowers on the farm',
            de: 'Können gepflanzt werden, um Sonnenblumen auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy słonecznika na farmie',
        },
    },
    sunflower: {
        name: {
            ru: 'Подсолнух',
            ua: 'Соняшник',
            en: 'Sunflower',
            de: 'Sonnenblume',
            pl: 'Słonecznik',
        },
        desc: {
            ru: 'Может быть продан скупщику или использован для создания масла',
            ua: 'Може бути проданий скупнику або використаний для створення олії',
            en: 'Can be sold to a trader or used for making oil',
            de: 'Kann an einen Händler verkauft oder zur Herstellung von Öl verwendet werden',
            pl: 'Może być sprzedany handlarzowi lub użyty do produkcji oleju',
        },
    },
};
