export default {
    pumpkin_seeds: {
        name: {
            ru: 'Семена тыквы',
            ua: 'Насіння гарбуза',
            en: 'Pumpkin Seeds',
            de: 'Kürbiskerne',
            pl: 'Nasiona dyni',
            zh:'南瓜籽',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания тыквы или использованы в кулинарии',
            ua: 'Можуть бути посаджені для вирощування гарбуза або використані в кулінарії',
            en: 'Can be planted to grow pumpkins or used in cooking',
            de: 'Können gepflanzt werden, um Kürbisse anzubauen oder in der Küche verwendet werden',
            pl: 'Mogą być sadzone w celu uprawy dyni lub używane w kuchni',
           zh:'可以种植南瓜或用于烹饪',
        },
    },
    pumpkin: {
        name: {
            ru: 'Тыква',
            ua: 'Гарбуз',
            en: 'Pumpkin',
            de: 'Kürbis',
            pl: 'Dynia',
           zh:'南瓜',
        },
        desc: {
            ru: 'Может быть использована для приготовления блюд или продана',
            ua: 'Може бути використана для приготування страв або продана',
            en: 'Can be used for cooking dishes or sold',
            de: 'Kann zum Kochen von Gerichten verwendet oder verkauft werden',
            pl: 'Może być używana do gotowania potraw lub sprzedawana',
            zh:'可用于烹饪菜肴或出售'',
        },
    },
    watering_can: {
        name: {
            ru: 'Лейка',
            ua: 'Лійка',
            en: 'Watering Can',
            de: 'Gießkanne',
            pl: 'Konewka',
            zh:'浇水罐',
        },
        desc: {
            ru: 'Можно использовать для полива растений на ферме',
            ua: 'Можна використовувати для поливу рослин на фермі',
            en: 'Can be used for watering plants on the farm',
            de: 'Kann zum Bewässern von Pflanzen auf dem Bauernhof verwendet werden',
            pl: 'Można używać do podlewania roślin na farmie',
            zh:'可用于浇灌农场的植物',
        },
    },
    potato: {
        name: {
            ru: 'Картофель',
            ua: 'Картопля',
            en: 'Potato',
            de: 'Kartoffel',
            pl: 'Ziemniak',
            zh:'土豆',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
           zh:'可以用来做饭或卖给商人',
        },
    },
    tomato: {
        name: {
            ru: 'Помидор',
            ua: 'Помідор',
            en: 'Tomato',
            de: 'Tomate',
            pl: 'Pomidor',
           zh:'番茄',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
           zh:'可以用来做饭或卖给商人',
        },
    },
    cabbage: {
        name: {
            ru: 'Капуста',
            ua: 'Капуста',
            en: 'Cabbage',
            de: 'Kohl',
            pl: 'Kapusta',
           zh:'卷心菜',
        },
        desc: {
            ru: 'Может быть использована для приготовления блюд или продана скупщику',
            ua: 'Може бути використана для приготування страв або продана скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używana do gotowania potraw lub sprzedana handlarzowi',
           zh:'可用于烹饪菜肴或出售给商人',
        },
    },
    onion: {
        name: {
            ru: 'Лук',
            ua: 'Цибуля',
            en: 'Onion',
            de: 'Zwiebel',
            pl: 'Cebula',
            zh:'洋葱',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
           zh:'可用于烹饪菜肴或出售给商人',
        },
    },
    cucumber: {
        name: {
            ru: 'Огурец',
            ua: 'Огірок',
            en: 'Cucumber',
            de: 'Gurke',
            pl: 'Ogórek',
           zh:'黄瓜',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
            zh:'可用于烹饪菜肴或出售给商人',
        },
    },
    tomato_seeds: {
        name: {
            ru: 'Семена помидор',
            ua: 'Насіння помідорів',
            en: 'Tomato Seeds',
            de: 'Tomatensamen',
            pl: 'Nasiona pomidorów',
            zh:'番茄籽',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания помидор на ферме',
            ua: 'Можуть бути посаджені для вирощування помідорів на фермі',
            en: 'Can be planted to grow tomatoes on the farm',
            de: 'Können gepflanzt werden, um Tomaten auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy pomidorów na farmie',
            zh:'可以在农场种植西红柿
        },
    },
    cabbage_seeds: {
        name: {
            ru: 'Семена капусты',
            ua: 'Насіння капусти',
            en: 'Cabbage Seeds',
            de: 'Kohlsamen',
            pl: 'Nasiona kapusty',
          zh:'卷心菜',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания капусты на ферме',
            ua: 'Можуть бути посаджені для вирощування капусти на фермі',
            en: 'Can be planted to grow cabbage on the farm',
            de: 'Können gepflanzt werden, um Kohl auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy kapusty na farmie',
            zh:'可以在农场种植卷心菜',
        },
    },
    onion_seeds: {
        name: {
            ru: 'Семена лука',
            ua: 'Насіння цибулі',
            en: 'Onion Seeds',
            de: 'Zwiebelsamen',
            pl: 'Nasiona cebuli',
           zh:'洋葱种子',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания лука на ферме',
            ua: 'Можуть бути посаджені для вирощування цибулі на фермі',
            en: 'Can be planted to grow onions on the farm',
            de: 'Können gepflanzt werden, um Zwiebeln auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy cebuli na farmie',
           zh:'它们可以在农场种植洋葱',
        },
    },
    cucumber_seeds: {
        name: {
            ru: 'Семена огурцов',
            ua: 'Насіння огірків',
            en: 'Cucumber Seeds',
            de: 'Gurkensamen',
            pl: 'Nasiona ogórków',
           zh:'谷物种子',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания огурцов на ферме',
            ua: 'Можуть бути посаджені для вирощування огірків на фермі',
            en: 'Can be planted to grow cucumbers on the farm',
            de: 'Können gepflanzt werden, um Gurken auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy ogórków na farmie',
            zh:'它们可以在农场种植花生',
        },
    },
    potato_seeds: {
        name: {
            ru: 'Семена картофеля',
            ua: 'Насіння картоплі',
            en: 'Potato Seeds',
            de: 'Kartoffelsamen',
            pl: 'Nasiona ziemniaków',
           zh:'马铃薯种子',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания картофеля на ферме',
            ua: 'Можуть бути посаджені для вирощування картоплі на фермі',
            en: 'Can be planted to grow potatoes on the farm',
            de: 'Können gepflanzt werden, um Kartoffeln auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy ziemniaków na farmie',
            zh:'可以在农场种植土豆',
        },
    },
    sunflower_seeds: {
        name: {
            ru: 'Семена подсолнуха',
            ua: 'Насіння соняшника',
            en: 'Sunflower Seeds',
            de: 'Sonnenblumensamen',
            pl: 'Nasiona słonecznika',
            zh:'葵花籽',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания подсолнуха на ферме',
            ua: 'Можуть бути посаджені для вирощування соняшника на фермі',
            en: 'Can be planted to grow sunflowers on the farm',
            de: 'Können gepflanzt werden, um Sonnenblumen auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy słonecznika na farmie',
           zh:'可以在农场种植向日葵',
        },
    },
    sunflower: {
        name: {
            ru: 'Подсолнух',
            ua: 'Соняшник',
            en: 'Sunflower',
            de: 'Sonnenblume',
            pl: 'Słonecznik',
           zh:'向日葵',
        },
        desc: {
            ru: 'Может быть продан скупщику или использован для создания масла',
            ua: 'Може бути проданий скупнику або використаний для створення олії',
            en: 'Can be sold to a trader or used for making oil',
            de: 'Kann an einen Händler verkauft oder zur Herstellung von Öl verwendet werden',
            pl: 'Może być sprzedany handlarzowi lub użyty do produkcji oleju',
           zh:',可以卖给贸易商或用于制造石油
        },
    },
    watermelon_seeds: {
        name: {
            ru: 'Семена арбуза',
            ua: 'Насіння кавуна',
            en: 'Watermelon Seeds',
            de: 'Wassermelonensamen',
            pl: 'Nasiona arbuza',
           zh:'西瓜籽',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания арбуза на ферме',
            ua: 'Можуть бути посаджені для вирощування кавуна на фермі',
            en: 'Can be planted to grow watermelons on the farm',
            de: 'Können gepflanzt werden, um Wassermelonen auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy arbuzów na farmie',
           zh:'可以在农场种植西瓜',
        },
    },
    pineapple_seeds: {
        name: {
            ru: 'Семена ананаса',
            ua: 'Насіння ананаса',
            en: 'Pineapple Seeds',
            de: 'Ananassamen',
            pl: 'Nasiona ananasa',
           zh:'菠萝籽',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания ананаса на ферме',
            ua: 'Можуть бути посаджені для вирощування ананаса на фермі',
            en: 'Can be planted to grow pineapples on the farm',
            de: 'Können gepflanzt werden, um Ananas auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy ananasów na farmie',
           zh:'“可以在农场种植菠萝',
        },
    },
    carrot_seeds: {
        name: {
            ru: 'Семена моркови',
            ua: 'Насіння моркви',
            en: 'Carrot Seeds',
            de: 'Möhrensamen',
            pl: 'Nasiona marchwi',
           zh:'胡萝卜的种子',
        },
        desc: {
            ru: 'Могут быть посажены для выращивания моркови на ферме',
            ua: 'Можуть бути посаджені для вирощування моркви на фермі',
            en: 'Can be planted to grow carrots on the farm',
            de: 'Können gepflanzt werden, um Möhren auf der Farm anzubauen',
            pl: 'Mogą być zasadzone do uprawy marchwi na farmie',
           zh:'可以在农场种植胡萝卜',
        },
    },
    carrot: {
        name: {
            ru: 'Морковь',
            ua: 'Морква',
            en: 'Carrot',
            de: 'Möhre',
            pl: 'Marchew',
            zh:'胡萝卜',
        },
        desc: {
            ru: 'Может быть использована для приготовления блюд или продана скупщику',
            ua: 'Може бути використана для приготування страв або продана скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używana do gotowania potraw lub sprzedana handlarzowi',
            zh:'可以用来做饭或卖给杂货商',
        },
    },
    pineapple: {
        name: {
            ru: 'Ананас',
            ua: 'Ананас',
            en: 'Pineapple',
            de: 'Ananas',
            pl: 'Ananas',
           zh:'菠萝',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
            zh:'“可以用来做饭或卖杂货店”',
        },
    },
    watermelon: {
        name: {
            ru: 'Арбуз',
            ua: 'Кавун',
            en: 'Watermelon',
            de: 'Wassermelone',
            pl: 'Arbuz',
            zh:'西瓜',
        },
        desc: {
            ru: 'Может быть использован для приготовления блюд или продан скупщику',
            ua: 'Може бути використаний для приготування страв або проданий скупнику',
            en: 'Can be used for cooking dishes or sold to a trader',
            de: 'Kann zum Kochen von Gerichten verwendet oder an einen Händler verkauft werden',
            pl: 'Może być używany do gotowania potraw lub sprzedany handlarzowi',
            zh:'可用于烹饪菜肴或出售给商人',
        },
    },
    melon: {
        name: {
            ru: 'Долька арбуза',
            ua: 'Скибка кавуна',
            en: 'Slice of watermelon',
            de: 'Wassermelonenstück',
            pl: 'Kawałek arbuza',
            ge: 'საზამთროს ნაჭერი',
           zh:'甜瓜',
        },
        desc: {
            ru: 'Сочнейшая долька арбуза вырощеного на полях фермы Олимпа',
            ua: 'Соковита скибка кавуна, вирощеного на полях ферми Олімпу',
            en: 'The juiciest slice of watermelon grown on the fields of Olympus farm',
            de: 'Das saftigste Stück Wassermelone, angebaut auf den Feldern der Olympfarm',
            pl: 'Soczysty kawałek arbuza uprawiany na polach farmy Olimpu',
            ge: 'საზამთროს ყველაზე წვნიანი ნაჭერი, რომელიც ოლიმპის ფერმის ველებზე მოყვანილია',
            zh:'奥林巴斯农场田地里最多汁的西瓜片',
        },
    },
};
