export const items = {
    heal: {
        name: {
            ua: 'Аптечка',
            ru: 'Аптечка',
            en: 'First Aid Kit',
            de: 'Erste-Hilfe-Kasten',
            pl: 'Apteczka',
            zh: '急救箱',
        },
        desc: {
            ru: 'Восстанавливает 75 процентов здоровья, при условии что здоровье ниже 25 процентов, также можно использовать для одноразовой реанимации людей',
            ua: "Відновлює 75 відсотків здоров'я за умови, що здоров'я нижче 25 відсотків, також можна використовувати для одноразової реанімації людей",
            en: 'Restores 75 percent health if health is below 25 percent, can also be used for one-time revival of people',
            de: 'Stellt 75 Prozent der Gesundheit wieder her, wenn die Gesundheit unter 25 Prozent liegt, kann auch für einmalige Wiederbelebung von Personen verwendet werden',
            pl: 'Przywraca 75 procent zdrowia, jeśli zdrowie jest poniżej 25 procent, może być również używany do jednorazowej reanimacji ludzi',
            zh: '它可以恢复75%的健康，前提是只有不到25%的健康也可以用于同时进行人体复苏',
        },
    },
    repairkit: {
        name: {
            ua: 'Ремонтний комплект',
            en: 'Repair Kit',
            ru: 'Рем. комплект',
            de: 'Reparaturset',
            pl: 'Zestaw naprawczy',
            zh: '维修工具包',
        },
        desc: {
            ua: 'Комплект для ремонту',
            en: 'A kit for repairs',
            ru: 'Комплект для ремонта',
            de: 'Ein Set für Reparaturen',
            pl: 'Zestaw naprawczy',
            zh: '一套维修',
        },
    },
    passport: {
        name: {
            ua: 'Паспорт',
            en: 'Passport',
            ru: 'Пасспорт',
            de: 'Reisepass',
            pl: 'Paszport',
            zh: '护照',
        },
        desc: {
            ua: 'Документ для засвiдчення особи',
            en: 'Document for identification',
            ru: 'Документ для удостоверения личности',
            de: 'Dokument zur Identifikation',
            pl: 'Dokument tożsamości',
            zh: '身份证明文件',
        },
    },
    petrolcan: {
        name: {
            ru: 'Канистра бензина 20л.',
            ua: 'Каністра бензину 20л.',
            en: '20L Petrol Can',
            de: '20L Benzinkanister',
            pl: 'Kanister benzyny 20l.',
            zh: '汽油容器20升',
        },
        desc: {
            ru: 'Заправляет любой бензиновый автомобиль на 20л.',
            ua: 'Заправляє будь-який бензиновий автомобіль на 20л.',
            en: 'Refuels any petrol car with 20L.',
            de: 'Betankt jedes benzinbetriebene Auto mit 20L.',
            pl: 'Tankuje każdy samochód benzynowy na 20l.',
            zh: '任何20升的汽油车加油',
        },
    },
    powerStation: {
        name: {
            ru: 'Зарядная станция 20kW.',
            ua: 'Зарядна станція 20kW.',
            en: '20kW Charging Station',
            de: '20kW Ladestation',
            pl: 'Stacja ładowania 20kW',
            zh: '20kW充电站',
        },
        desc: {
            ru: 'Заряжает любой электро-мобиль на 20kW.',
            ua: 'Заряджає будь-який електро-мобіль на 20kW.',
            en: 'Charges any electric car with 20kW.',
            de: 'Lädt jedes Elektroauto mit 20kW.',
            pl: 'Ładuje każdy samochód elektryczny na 20kW.',
            zh: '为任何20kW的电动汽车充电',
        },
    },

    backpack1: {
        name: {
            ua: 'Рюкзак',
            en: 'Backpack',
            ru: 'Рюкзак',
            de: 'Rucksack',
            pl: 'Plecak',
            zh: '背包',
        },
        desc: {
            ua: 'Сумка для перенесення речей',
            en: 'Bag for carrying items',
            ru: 'Сумка для переноски вещей',
            de: 'Tasche zum Tragen von Gegenständen',
            pl: 'Torebka do przenoszenia przedmiotów',
            zh: '携带物品的袋子',
        },
    },
    simCard: {
        name: {
            ua: 'Сім карта',
            en: 'SIM Card',
            ru: 'Сим карта',
            de: 'SIM-Karte',
            pl: 'Karta SIM',
            zh: 'SIM卡',
        },
        desc: {
            ua: `Карта для мобільного зв'язку`,
            en: 'Card for mobile communication',
            ru: 'Карта для мобильной связи',
            de: 'Karte für mobile Kommunikation',
            pl: 'Karta do komunikacji mobilnej',
            zh: '手机卡',
        },
    },
    cigarettes: {
        name: {
            ua: 'Сигарети',
            en: 'Cigarettes',
            ru: 'Сигареты',
            de: 'Zigaretten',
            pl: 'Papierosy',
            zh: '香烟',
        },
        desc: {
            ua: 'Тютюнові вироби для куріння',
            en: 'Tobacco products for smoking',
            ru: 'Табачные изделия для курения',
            de: 'Tabakprodukte zum Rauchen',
            pl: 'Produkty tytoniowe do palenia',
            zh: '吸烟烟草制品',
        },
    },
    //
    reliefix: {
        name: {
            ua: 'Таблетки "RelieFix"',
            ru: 'Таблетки "RelieFix"',
            en: '"RelieFix" Pills',
            de: '"RelieFix" Tabletten',
            pl: 'Tabletki "RelieFix"',
            zh: 'RelieFix片剂',
        },
        desc: {
            ru: 'Восстанавливают 75 процентов здоровья, невзависимости от текущего здоровья',
            ua: "Відновлюють 75 відсотків здоров'я, незалежно від поточного здоров'я",
            en: 'Restores 75 percent of health, regardless of current health',
            de: 'Stellt 75 Prozent der Gesundheit wieder her, unabhängig von der aktuellen Gesundheit',
            pl: 'Przywraca 75 procent zdrowia, niezależnie od obecnego stanu zdrowia',
            zh: '无论他们目前的健康状况如何，他们都能恢复75%的健康',
        },
    },
    painaway_advanced: {
        name: {
            ru: 'Таблетки "PainAway Advanced"',
            ua: 'Таблетки "PainAway Advanced"',
            en: '"PainAway Advanced" Pills',
            de: '"PainAway Advanced" Tabletten',
            pl: 'Tabletki "PainAway Advanced"',
            zh: 'PainAway高级片剂',
        },
        desc: {
            ru: 'Восстанавливают здоровье полностью.',
            ua: "Повністю відновлюють здоров'я.",
            en: 'Fully restores health.',
            de: 'Stellt die Gesundheit vollständig wieder her.',
            pl: 'Całkowicie przywraca zdrowie.',
            zh: '完全恢复',
        },
    },

    defibrocharge: {
        name: {
            ua: 'Дефібрилятор "DefibroCharge"',
            en: 'Defibrillator "DefibroCharge"',
            ru: 'Дефибриллятор "DefibroCharge"',
            de: 'Defibrillator "DefibroCharge"',
            pl: 'Defibrylator "DefibroCharge"',
            zh: '除颤监护仪',
        },
        desc: {
            ua: 'Життєво необхідний прилад для невідкладної реанімації, що повертає на межі життя та смерті',
            en: 'A vital resuscitation device that snatches lives back from the brink of death',
            ru: 'Жизненно необходимое устройство для экстренной реанимации, возвращающее на грань жизни и смерти',
            de: 'Ein lebenswichtiges Reanimationsgerät, das Leben an der Schwelle zum Tod zurückholt',
            pl: 'Niezbędne urządzenie resuscytacyjne, które odzyskuje życie z granicy śmierci',
            zh: '一种从死亡边缘夺走生命的重要复苏装置”',
        },
    },
    materials: {
        name: {
            ru: 'Материалы',
            ua: 'Матеріали',
            en: 'Materials',
            de: 'Materialien',
            pl: 'Materiały',
            zh: '材料',
        },
        desc: {
            ru: 'Используются для создания различных предметов в том числе оружия',
            ua: 'Використовуються для створення різних предметів, в тому числі зброї',
            en: 'Used to create various items including weapons',
            de: 'Wird zur Herstellung verschiedener Gegenstände einschließlich Waffen verwendet',
            pl: 'Używane do tworzenia różnych przedmiotów, w tym broni',
            zh: '用于制造各种物品，包括武器',
        },
    },
    medicalMaterials: {
        name: {
            ru: 'Медицинские материалы',
            ua: 'Медичні матеріали',
            en: 'Medical materials',
            de: 'Medizinische Materialien',
            pl: 'Materiały medyczne',
            zh: '医用材料',
        },
        desc: {
            ru: 'Используются для создания аптечек, и лекарств',
            ua: 'Використовуються для створення аптечок і ліків',
            en: 'Used to create first aid kits and medicines',
            de: 'Wird zur Herstellung von Erste-Hilfe-Kästen und Medikamenten verwendet',
            pl: 'Używane do tworzenia apteczek i leków',
            zh: '用于制作急救箱和药品',
        },
    },
    bloodBag: {
        name: {
            ru: 'Мешочек с кровью',
            ua: "Мішечок з кров'ю",
            en: 'Blood bag',
            de: 'Blutbeutel',
            pl: 'Torba z krwią',
            zh: '血袋',
        },
        desc: {
            ru: 'Отнеси к NPC в лабаратории для получения награды',
            ua: 'Принеси до NPC в лабораторії для отримання нагороди',
            en: 'Take it to the NPC in the laboratory to get a reward',
            de: 'Bringen Sie es zum NPC im Labor, um eine Belohnung zu erhalten',
            pl: 'Zanieś to do NPC w laboratorium, aby otrzymać nagrodę',
            zh: '把它拿到实验室的NPC那里去拿奖励',
        },
    },
    scotch_tape: {
        name: {
            ru: 'Скотч',
            ua: 'Скотч',
            en: 'Scotch tape',
            de: 'Klebeband',
            pl: 'Taśma klejąca',
            zh: '苏格兰威士忌',
        },
        desc: {
            ru: 'Можно заклеить что угодно',
            ua: 'Можна заклеїти що завгодно',
            en: 'Can be used to tape anything',
            de: 'Kann zum Verkleben von allem verwendet werden',
            pl: 'Można go użyć do zaklejenia wszystkiego',
            zh: '你可以赌任何东西',
        },
    },

    polyethylene_film: {
        name: {
            ru: 'Полиэтиленовая пленка',
            ua: 'Поліетиленова плівка',
            en: 'Polyethylene film',
            de: 'Polyethylenfolie',
            pl: 'Folia polietylenowa',
            zh: '聚乙烯薄膜',
        },
        desc: {
            ru: 'Можно замотать что угодно',
            ua: 'Можна загорнути що завгодно',
            en: 'Can be used to wrap anything',
            de: 'Kann zum Einwickeln von allem verwendet werden',
            pl: 'Można go użyć do owinięcia wszystkiego',
            zh: '可以用来包装任何东西',
        },
    },
    handcuffs: {
        name: {
            ru: 'Наручники',
            ua: 'Наручники',
            en: 'Handcuffs',
            de: 'Handschellen',
            pl: 'Kajdanki',
            zh: '手铐',
        },
        desc: {
            ru: 'Используются гос. структурами для задержания преступников',
            ua: 'Використовуються державними структурами для затримання злочинців',
            en: 'Used by law enforcement to restrain criminals.',
            de: 'Verwendet von Strafverfolgungsbehörden, um Kriminelle festzuhalten.',
            pl: 'Używane przez organy ścigania do obezwładniania przestępców.',
            zh: '执法部门用来逮捕罪犯',
        },
    },
    C4: {
        name: {
            ru: 'C4',
            ua: 'C4',
            en: 'C4',
            de: 'C4',
            pl: 'C4',
        },
        desc: {
            ru: 'C4 — это компактная пластичная взрывчатка, идеально подходящая для подрыва укреплённых целей, например, ящиков аирдропа. Она легко устанавливается на поверхность, активируется с дистанции или по таймеру, и с высокой эффективностью разрушает препятствия, обеспечивая доступ к содержимому.',
            ua: 'C4 — це компактна пластична вибухівка, ідеально підходяща для підриву укріплених цілей, наприклад, ящиків аірдропу. Вона легко встановлюється на поверхню, активується дистанційно або за таймером, і з високою ефективністю руйнує перешкоди, забезпечуючи доступ до вмісту.',
            en: 'C4 is a compact plastic explosive, ideal for demolishing fortified targets, such as airdrop crates. It easily attaches to surfaces, can be activated remotely or by timer, and efficiently destroys obstacles, granting access to the contents.',
            de: 'C4 ist ein kompakter plastischer Sprengstoff, der sich ideal zum Zerstören befestigter Ziele eignet, wie z.B. Airdrop-Kisten. Es lässt sich leicht an Oberflächen anbringen, wird aus der Ferne oder per Timer aktiviert und zerstört effizient Hindernisse, um Zugang zum Inhalt zu gewähren.',
            pl: 'C4 to kompaktowy materiał wybuchowy, idealny do niszczenia umocnionych celów, takich jak skrzynie zrzutu. Łatwo przylega do powierzchni, może być aktywowany zdalnie lub za pomocą timera i skutecznie niszczy przeszkody, zapewniając dostęp do zawartości.',
        },
    },
    cloth: {
        name: {
            ru: 'Ткань',
            ua: 'Тканина',
            en: 'Cloth',
            de: 'Stoff',
            pl: 'Tkanina',
        },
        desc: {
            ru: 'универсальный материал, необходимый для крафта различных предметов.',
            ua: 'універсальний матеріал, необхідний для створення різних предметів.',
            en: 'a versatile material necessary for crafting various items.',
            de: 'ein vielseitiges Material, das für das Herstellen verschiedener Gegenstände benötigt wird.',
            pl: 'uniwersalny materiał potrzebny do tworzenia różnych przedmiotów.',
        },
    },
    chipset: {
        name: {
            ru: 'Набор микросхем',
            ua: 'Набір мікросхем',
            en: 'Chipset',
            de: 'Chipsatz',
            pl: 'Zestaw mikroprocesorów',
        },
        desc: {
            ru: 'Редкие электронные компоненты, применяемые для крафта продвинутого оборудования и взрывчатки.',
            ua: 'Рідкісні електронні компоненти, що застосовуються для створення передового обладнання та вибухівки.',
            en: 'Rare electronic components used for crafting advanced equipment and explosives.',
            de: 'Seltene elektronische Komponenten, die für die Herstellung fortschrittlicher Ausrüstung und Sprengstoffe verwendet werden.',
            pl: 'Rzadkie komponenty elektroniczne wykorzystywane do tworzenia zaawansowanego sprzętu i materiałów wybuchowych.',
        },
    },
    explosives: {
        name: {
            ru: 'Взрывчатка',
            ua: 'Вибухівка',
            en: 'Explosives',
            de: 'Sprengstoff',
            pl: 'Materiały wybuchowe',
        },
        desc: {
            ru: 'Мощное вещество, необходимое для создания различных взрывных устройств, таких как С4.',
            ua: 'Потужна речовина, необхідна для створення різних вибухових пристроїв, таких як C4.',
            en: 'A powerful substance necessary for creating various explosive devices, such as C4.',
            de: 'Eine kraftvolle Substanz, die zur Herstellung verschiedener Sprengvorrichtungen, wie z.B. C4, benötigt wird.',
            pl: 'Potężna substancja potrzebna do tworzenia różnych urządzeń wybuchowych, takich jak C4.',
        },
    },
    dirty_money: {
        name: {
            ru: 'Грязные деньги',
            ua: 'Брудні гроші',
            en: 'Dirty Money',
            de: 'Schmutziges Geld',
            pl: 'Brudne pieniądze',
        },
        desc: {
            ru: 'Деньги которые нельзя использовать пока не отмоешь их, обычно получают нелегальным путем',
            ua: 'Гроші, які не можна використовувати, поки їх не відмиєш, зазвичай отримують незаконним шляхом',
            en: 'Money that cannot be used until laundered, usually obtained illegally',
            de: 'Geld, das nicht verwendet werden kann, bis es gewaschen wird, wird normalerweise illegal erworben',
            pl: 'Pieniądze, których nie można używać, dopóki nie zostaną wyprane, zwykle zdobyte nielegalnie',
        },
    },

    boombox: {
        name: {
            en: 'Boombox',
        },

        desc: {
            ru: 'Громкий качественный бумбокс, хорошо подходит для тусовок в кругу друзей',
            ua: 'Гучний якісний бумбокс, добре підходить для тусовок у колі друзів',
            en: 'A loud, high-quality boombox, perfect for parties with friends',
            de: 'Ein lauter, hochwertiger Boombox, ideal für Partys mit Freunden',
            pl: 'Głośny, wysokiej jakości boombox, idealny na imprezy w gronie przyjaciół',
        },
    },
    rolling_paper: {
        name: {
            ru: 'Бумага для самокруток',
            ua: 'Папір для самокруток',
            en: 'Rolling paper',
            de: 'Drehpapier',
            pl: 'Bibułka do skrętów',
        },
        desc: {
            ru: 'Позволяет сделать сигарету',
            ua: 'Дозволяє зробити сигарету',
            en: 'Allows you to make a cigarette',
            de: 'Ermöglicht das Drehen einer Zigarette',
            pl: 'Pozwala zrobić papierosa',
        },
    },
    ephedrine_pills: {
        name: {
            ru: 'Эфедриновые таблетки',
            ua: 'Ефедринові таблетки',
            en: 'Ephedrine tablets',
            de: 'Ephedrin-Tabletten',
            pl: 'Tabletki efedrynowe',
        },
        desc: {
            ru: 'Могут пригодиться для крафта чего-то нелегального...',
            ua: 'Можуть стати в пригоді для крафту чогось нелегального...',
            en: 'Might be useful for crafting something illegal...',
            de: 'Könnten nützlich sein, um etwas Illegales herzustellen...',
            pl: 'Mogą przydać się do tworzenia czegoś nielegalnego...',
        },
    },
    pickaxe: {
        name: {
            ru: 'Кирка',
            ua: 'Кирка',
            en: 'Pickaxe',
            de: 'Spitzhacke',
            pl: 'Kilof',
        },
        desc: {
            ru: 'Мощная и надёжная кирка для работы в карьере. Тяжёлый металлический наконечник с лёгкостью разбивает камень, а прочная рукоять выдерживает любые нагрузки. Идеальный инструмент для добычи ресурсов.',
            ua: "Потужна та надійна кирка для роботи в кар'єрі. Важкий металевий наконечник з легкістю розбиває камінь, а міцна рукоятка витримує будь-які навантаження. Ідеальний інструмент для видобутку ресурсів.",
            en: 'A powerful and reliable pickaxe for quarry work. The heavy metal tip easily breaks stone, and the sturdy handle can withstand any load. The perfect tool for resource extraction.',
            de: 'Eine leistungsstarke und zuverlässige Spitzhacke für Steinbrucharbeiten. Die schwere Metallspitze bricht mühelos Stein, und der robuste Griff hält jeder Belastung stand. Das perfekte Werkzeug für die Rohstoffgewinnung.',
            pl: 'Potężny i niezawodny kilof do pracy w kamieniołomie. Ciężki metalowy grot z łatwością rozbija kamień, a solidny uchwyt wytrzymuje każde obciążenie. Idealne narzędzie do wydobywania zasobów.',
        },
    },
    lockpick: {
        name: {
            ru: 'Отмычка',
            ua: 'Відмичка',
            en: 'Lockpick',
            de: 'Dietrich',
            pl: 'Wytrych',
        },
        desc: {
            ru: 'Используется для взлома замка машин и других замков, может сломаться при неудачном взломе будьте внимательны!',
            ua: 'Використовується для злому замків автомобілів та інших замків, може зламатися при невдалому зломі — будьте уважні!',
            en: 'Used to pick car locks and other locks, may break if the attempt fails – be careful!',
            de: 'Wird verwendet, um Autoschlösser und andere Schlösser zu knacken, kann bei einem Fehlversuch brechen – seien Sie vorsichtig!',
            pl: 'Służy do otwierania zamków samochodów i innych zamków, może się złamać przy nieudanej próbie – bądź ostrożny!',
        },
    },
    speedradar: {
        name: {
            ru: 'Скоростной радар',
            ua: 'Швидкісний радар',
            en: 'Speed radar',
            de: 'Geschwindigkeitsradar',
            pl: 'Radar prędkości',
        },
        desc: {
            ru: 'Инструкция по использованию: Встаньте на место которое хотите поставить радар, обернитесь в сторону куда он должен смотреть и используйте предмет, выберете минимальную скорость.',
            ua: 'Інструкція з використання: Станьте на місце, де хочете встановити радар, оберніться в бік, куди він повинен дивитися, і використайте предмет, виберіть мінімальну швидкість.',
            en: 'Usage instructions: Stand in the place where you want to place the radar, turn towards the direction it should be facing, and use the item. Choose the minimum speed.',
            de: 'Gebrauchsanweisung: Stellen Sie sich an die Stelle, an der Sie das Radar aufstellen möchten, drehen Sie sich in die Richtung, in die es zeigen soll, und benutzen Sie den Gegenstand. Wählen Sie die Mindestgeschwindigkeit.',
            pl: 'Instrukcja użytkowania: Stań w miejscu, w którym chcesz umieścić radar, obróć się w kierunku, w którym ma być skierowany, i użyj przedmiotu. Wybierz minimalną prędkość.',
        },
    },
    bodycamera: {
        name: {
            ru: 'Нагрудная камера',
            ua: 'Нагрудна камера',
            en: 'Body camera',
            de: 'Körperkamera',
            pl: 'Kamera nasobna',
        },
        desc: {
            ru: 'Устройство для записи происходящего от первого лица персонажа, используется для документирования событий в RP-сценах. Часто применяется сотрудниками госструктур, например, полицией. Запись может быть использована как доказательство в суде или других RP-ситуациях.',
            ua: 'Пристрій для запису подій від першої особи персонажа, використовується для документування подій у RP-сценах. Часто використовується працівниками держструктур, наприклад, поліцією. Запис може бути використаний як доказ у суді або в інших RP-ситуаціях.',
            en: "A device for recording events from the character's first-person view, used to document situations in RP scenes. Often used by government employees, such as the police. The recording can be used as evidence in court or other RP scenarios.",
            de: 'Ein Gerät zur Aufzeichnung von Ereignissen aus der Ich-Perspektive des Charakters, das zur Dokumentation von Situationen in RP-Szenen verwendet wird. Wird häufig von Staatsbediensteten wie der Polizei verwendet. Die Aufzeichnung kann als Beweis vor Gericht oder in anderen RP-Situationen dienen.',
            pl: 'Urządzenie do nagrywania wydarzeń z perspektywy pierwszej osoby postaci, używane do dokumentowania sytuacji w scenach RP. Często wykorzystywane przez pracowników instytucji państwowych, np. policję. Nagranie może posłużyć jako dowód w sądzie lub innych sytuacjach RP.',
        },
    },
    walkieTalkie: {
        name: {
            ru: 'Рация',
            ua: 'Рація',
            en: 'Radio',
            de: 'Funkgerät',
            pl: 'Radio',
        },
        desc: {
            ru: 'Портативное устройство для голосовой связи. Позволяет подключаться к заданной радиочастоте и общаться с другими игроками на той же волне. Необходима для координации действий в группах.',
            ua: "Портативний пристрій для голосового зв'язку. Дозволяє підключатися до заданої радіочастоти та спілкуватися з іншими гравцями на тій самій хвилі. Необхідний для координації дій у групах.",
            en: 'A portable device for voice communication. Allows connecting to a specified radio frequency and talking with other players on the same channel. Essential for coordinating actions in groups.',
            de: 'Tragbares Gerät zur Sprachkommunikation. Ermöglicht die Verbindung mit einer bestimmten Funkfrequenz und die Kommunikation mit anderen Spielern auf dem gleichen Kanal. Unverzichtbar für die Koordination in Gruppen.',
            pl: 'Przenośne urządzenie do komunikacji głosowej. Umożliwia łączenie się z określoną częstotliwością radiową i rozmowę z innymi graczami na tym samym kanale. Niezbędne do koordynacji działań w grupach.',
        },
    },
    sprayPaintCan: {
        name: {
            ru: 'Баллончик с краской',
            ua: 'Балончик з фарбою',
            en: 'Spray Paint Can',
            de: 'Spraydose',
            pl: 'Puszka z farbą w sprayu',
        },
        desc: {
            ru: 'Аэрозольный баллончик, используемый для рисования граффити. Оставляет яркие следы на любой поверхности.',
            ua: 'Аерозольний балончик, що використовується для створення графіті. Залишає яскраві сліди на будь-якій поверхні.',
            en: 'An aerosol can used for graffiti. Leaves vivid marks on any surface.',
            de: 'Eine Sprühdose, die für Graffiti verwendet wird. Hinterlässt leuchtende Spuren auf jeder Oberfläche.',
            pl: 'Aerozolowa puszka używana do malowania graffiti. Pozostawia wyraźne ślady na każdej powierzchni.',
        },
    },
};
