export default {
    types: {
        illegalSeller: {
            ru: 'Нелегальный торговец',
            ua: 'Нелегальний торговець',
            en: 'Illegal Trader',
            de: 'Illegaler Händler',
            pl: 'Nielegalny handlarz',
        },
        localSeller: {
            ru: 'Местный торговец',
            ua: 'Місцевий торговець',
            en: 'Local seller',
            de: 'Lokaler Händler',
            pl: 'Lokalny sprzedawca',
        },
    },
    categories: {
        misc: {
            ru: 'Разное',
            ua: 'Різне',
            en: 'Misc',
            de: 'Verschiedenes',
            pl: 'Inne',
        },
        drugs: {
            ru: 'Наркотики',
            ua: 'Наркотики',
            en: 'Drugs',
            de: 'Drogen',
            pl: 'Narkotyki',
        },
    },
    waitSms: {
        ru: 'Ожидай смс об локации посылки',
        ua: 'Очікуй смс про локацію посилки',
        en: 'Wait for an SMS with the package location',
        de: 'Warte auf eine SMS mit dem Standort des Pakets',
        pl: 'Czekaj na SMS z lokalizacją paczki',
    },
    stashSms: {
        ru: 'Отправил тебе локацию твоей посылки, можешь увидеть в точности на карте. Знай другие игроки недалеко от неё могут попробовать её украсть',
        ua: 'Відправив тобі локацію твоєї посилки, можеш побачити точно на карті. Знай, інші гравці неподалік можуть спробувати її вкрасти',
        en: 'Sent you the location of your package, you can see it precisely on the map. Note that other players nearby may try to steal it',
        de: 'Ich habe dir den Standort deines Pakets geschickt. Beachte, dass Spieler in der Nähe des Pakets versuchen könnten, es zu stehlen',
        pl: 'Wysłałem ci lokalizację twojej paczki, możesz zobaczyć ją dokładnie na mapie. Pamiętaj, że inni gracze w pobliżu mogą spróbować ją ukraść',
    },
    smsToGangs: {
        ru: 'Держи секретную информацию, недалеко от тебя отправили посылку которую ты можешь перехватить, на карте отображено примерное местоположение!',
        ua: 'Тримай секретну інформацію, неподалік від тебе відправили посилку, яку ти можеш перехопити, на карті позначено приблизне місцезнаходження!',
        en: "Here's some secret information: a package was sent near you that you can intercept, its approximate location is marked on the map!",
        de: 'Hier sind geheime Informationen: In deiner Nähe wurde ein Paket verschickt, das du abfangen kannst, sein ungefährer Standort ist auf der Karte markiert!',
        pl: 'Oto tajna informacja: w twojej okolicy wysłano paczkę, którą możesz przechwycić, jej przybliżona lokalizacja jest zaznaczona na mapie!',
    },
    youTakedStash: {
        ru: 'Вы забрали посылку',
        ua: 'Ви забрали посилку',
        en: 'You took the package',
        de: 'Du hast das Paket abgeholt',
        pl: 'Zabrałeś paczkę',
    },
    stashBlip: {
        ru: 'Ваша посылка',
        ua: 'Ваша посилка',
        en: 'Your package',
        de: 'Dein Paket',
        pl: 'Twoja paczka',
    },
    stashBlipForOthers: {
        ru: 'Потенциальная закладка',
        ua: 'Потенцiйна закладка',
        en: 'Potential stash',
        de: 'Potentielles Versteck',
        pl: 'Potencjalna skrytka',
    },
    looksLikeSomeoneStolenYourStash: {
        ru: 'Похоже кто-то нашёл вашу посылку раньше вас, анлак...',
        ua: 'Схоже, хтось знайшов вашу посилку раніше за вас, анлак...',
        en: 'Looks like someone found your package before you, unlucky...',
        de: 'Jemand dein Paket vor dir abgeholt, Pech gehabt...',
        pl: 'Wygląda na to, że ktoś znalazł twoją paczkę przed tobą, pech...',
    },
    alreadyHaveIllegalOrder: {
        ru: 'У вас есть активная посылка, чем скорее заберите её',
        ua: 'У вас є активна посилка, якнайшвидше заберіть її',
        en: 'You have an active package, pick it up as soon as possible',
        de: 'Du hast ein aktives Paket, hole es so schnell wie möglich ab',
        pl: 'Masz aktywną paczkę, odbierz ją jak najszybciej',
    },

    productIsOutOfStock: {
        ru: 'Товар "{{name}}" закончился или недостаточно в наличии.',
        ua: 'Товар "{{name}}" закінчився або недостатньо в наявності.',
        en: 'The item "{{name}}" is out of stock or not available in sufficient quantity.',
        de: 'Der Artikel "{{name}}" ist ausverkauft oder nicht in ausreichender Menge verfügbar.',
        pl: 'Produkt "{{name}}" jest wyprzedany lub nie jest dostępny w wystarczającej ilości.',
    },
    noPositionsRightNow: {
        ru: 'Сейчас не получится доставить посылку, попробуй чуть позже...',
        ua: 'Зараз не вдасться доставити посилку, спробуй трохи пізніше...',
        en: 'The package cannot be delivered right now, try again a bit later...',
        de: 'Das Paket kann derzeit nicht zugestellt werden, versuche es später noch einmal...',
        pl: 'Nie można teraz dostarczyć paczki, spróbuj ponownie trochę później...',
    },
};
