export default {
    date: {
        ru: 'Дата выдачи',
        ua: 'Дата видачі',
        en: 'Date of issue',
        de: 'Ausstellungsdatum',
        pl: 'Data wydania',
        zh:'签发日期',
    },
    name: {
        ru: 'Имя фамилия',
        ua: "Ім'я прізвище",
        en: 'First name last name',
        de: 'Vorname Nachname',
        pl: 'Imię nazwisko',
        zh:'姓名',
    },
    age: {
        ru: 'Возраст',
        ua: 'Вік',
        en: 'Age',
        de: 'Alter',
        pl: 'Wiek',
        zh:'年龄',
    },
    gender: {
        ru: 'Пол',
        ua: 'Стать',
        en: 'Gender',
        de: 'Geschlecht',
        pl: 'Płeć',
        zh:'性别',
    },
    male: {
        ru: 'М',
        ua: 'М',
        en: 'M',
        de: 'M',
        pl: 'M',
        zh:'M',
    },
    female: {
        ru: 'Ж',
        ua: 'Ж',
        en: 'F',
        de: 'W',
        pl: 'K',
        zh:'F',
    },
    // сообщение что вы успешно получили пасспорт
    successGetPassport: {
        ru: 'Вы успешно получили пасспорт!',
        ua: 'Ви успішно отримали паспорт!',
        en: 'You have successfully obtained a passport!',
        de: 'Sie haben erfolgreich einen Pass erhalten!',
        pl: 'Pomyślnie otrzymałeś paszport!',
        zh:'你已成功取得护照!',
    },

    youHaveNoPassport: {
        ru: 'У вас нет пасспорта',
        ua: 'У вас немає паспорта',
        en: "You don't have a passport",
        de: 'Sie haben keinen Pass',
        pl: 'Nie masz paszportu',
        zh:'你没有护照',
    },
    targetHasNoPassport: {
        ru: 'У игрока нет пасспорта',
        ua: 'У гравця немає паспорту',
        en: 'The player does not have a passport',
        de: 'Der Spieler hat keinen Pass',
        pl: 'Gracz nie ma pasza',
        zh:'该市民没有护照',
    },
};
