export default {
    loginRecovery: {
        ru: 'Восстановление логина',
        ua: 'Відновлення логіну',
        en: 'Login Recovery',
        de: 'Login-Wiederherstellung',
        pl: 'Odzyskiwanie loginu',
        zh: '找回账号',
    },
    instruction: {
        ru: 'Мы получили запрос на напоминание логина для вашей учётной записи. Ниже указан логин, привязанный к этому email.',
        ua: "Ми отримали запит на нагадування логіну для вашого облікового запису. Нижче вказаний логін, прив'язаний до цього email.",
        en: 'We received a request to remind you of the login for your account. Below is the login associated with this email.',
        de: 'Wir haben eine Anfrage zur Erinnerung an den Login für dein Konto erhalten. Unten ist der mit dieser E-Mail verknüpfte Login.',
        pl: 'Otrzymaliśmy żądanie przypomnienia loginu dla twojego konta. Poniżej znajduje się login powiązany z tym adresem e-mail.',
        zh: '已发送账号找回邮件，下方为绑定该邮箱的账号',
    },
    yourLogin: {
        ru: 'Ваш логин',
        ua: 'Ваш логін',
        en: 'Your login',
        de: 'Dein Login',
        pl: 'Twój login',
        zh: '你的账号',
    },
    disclaimer: {
        ru: 'Если вы не запрашивали восстановление логина, пожалуйста, проигнорируйте это письмо.',
        ua: 'Якщо ви не запитували відновлення логіну, будь ласка, проігноруйте цей лист.',
        en: 'If you did not request a login recovery, please ignore this email.',
        de: 'Wenn du keine Login-Wiederherstellung angefordert hast, ignoriere bitte diese E-Mail.',
        pl: 'Jeśli nie żądałeś odzyskania loginu, proszę zignoruj tę wiadomość.',
        zh: '如果你没有找回账号，请忽略邮件',
    },
    site: {
        ru: 'Сайт',
        ua: 'Сайт',
        en: 'Website',
        de: 'Webseite',
        pl: 'Strona internetowa',
        zh: '网站',
    },
    mail: {
        ru: 'Почта',
        ua: 'Пошта',
        en: 'Mail',
        de: 'Mail',
        pl: 'Poczta',
        zh: '邮箱',
    },
};
