export default {
    passwordRecovery: {
        ru: 'Восстановление пароля для',
        ua: 'Відновлення паролю для',
        en: 'Password recovery for',
        de: 'Passwortwiederherstellung für',
        pl: 'Odzyskiwanie hasła dla',
       zh:'找回密码',
    },
    instruction: {
        ru: 'Мы получили запрос на восстановление пароля для вашей учетной записи. Пожалуйста, используйте следующий код для сброса пароля. Этот код действителен в течение 30 минут.',
        ua: 'Ми отримали запит на відновлення пароля для вашого облікового запису. Будь ласка, використовуйте наступний код для скидання пароля. Цей код дійсний протягом 30 хвилин.',
        en: 'We have received a request to reset the password for your account. Please use the following code to reset your password. This code is valid for 30 minutes.',
        de: 'Wir haben eine Anfrage zum Zurücksetzen des Passworts für Ihr Konto erhalten. Bitte verwende den folgenden Code, um dein Passwort zurückzusetzen. Dieser Code ist 30 Minuten lang gültig.',
        pl: 'Otrzymaliśmy żądanie zresetowania hasła do twojego konta. Proszę użyj poniższego kodu, aby zresetować hasło. Kod ten jest ważny przez 30 minut.',
       zh:'已发送验证码，有效期为30分钟',
    },
    disclaimer: {
        ru: 'Если вы не запрашивали восстановление пароля, пожалуйста, проигнорируйте это письмо.',
        ua: 'Якщо ви не запитували відновлення пароля, будь ласка, проігноруйте цей лист.',
        en: 'If you did not request a password recovery, please ignore this email.',
        de: 'Wenn du keine Passwortwiederherstellung angefordert hast, ignoriere bitte diese E-Mail.',
        pl: 'Jeśli nie żądałeś odzyskania hasła, proszę zignoruj tę wiadomość.',
       zh:'如果你没有找回密码，请忽略邮件',
    },
    site: {
        ru: 'Сайт',
        ua: 'Сайт',
        en: 'Website',
        de: 'Webseite',
        pl: 'Strona internetowa',
       zh:'网站',
    },
    mail: {
        ru: 'Почта',
        ua: 'Пошта',
        en: 'Mail',
        de: 'Mail',
        pl: 'Poczta',
       zh:'邮箱',
    },
};
