import recovery from './recovery';

export const server = {
    loginNotFound: {
        ua: 'Аккаунт не знайдено!',
        en: 'Account not found!',
        ru: 'Аккаунт не найден!',
        de: 'Konto nicht gefunden!',
        pl: 'Nie znaleziono konta!',
        zh: '未找到账户！',
    },
    accountAlreadyLogged: {
        ua: 'Під вашим акаунтом хтось авторизований',
        en: 'Someone is already logged in to your account',
        ru: 'Под вашим аккаунтом кто-то авторизован',
        de: 'Jemand ist bereits in deinem Konto angemeldet',
        pl: 'Ktoś jest już zalogowany na twoim koncie',
        zh: '账号已在别处登录',
    },
    invalidCredentials: {
        ua: 'Неправильні дані',
        en: 'Invalid credentials',
        ru: 'Неправильные данные',
        de: 'Ungültige Anmeldedaten',
        pl: 'Nieprawidłowe dane',
        zh: '身份信息不匹配',
    },
    waitSpam: {
        ua: 'Зачекайте трохи',
        en: 'Wait a little',
        ru: 'Подождите немного',
        de: 'Bitte warte einen Moment',
        pl: 'Poczekaj chwilę',
        zh: '请稍等',
    },
    registrationSuccess: {
        ua: 'Ви успішно створили аккаунт',
        en: 'You have successfully created an account',
        ru: 'Вы успешно создали аккаунт',
        de: 'Du hast erfolgreich ein Konto erstellt',
        pl: 'Pomyślnie utworzono konto',
        zh: '账户创建成功',
    },
    accountCreationError: {
        ua: 'Сталася помилка, спробуйте ще раз',
        en: 'An error occurred, please try again',
        ru: 'Произошла ошибка, повторите попытку',
        de: 'Es ist ein Fehler aufgetreten, bitte versuche es erneut',
        pl: 'Wystąpił błąd, spróbuj ponownie',
        zh: '错误，请重试',
    },
    accountAlreadyExists: {
        ua: 'Ви можете мати тільки один аккаунт',
        en: 'You can have only one account',
        ru: 'Вы можете иметь только один аккаунт',
        de: 'Du kannst nur ein Konto haben',
        pl: 'Możesz mieć tylko jedno konto',
        zh: '一人最多只能拥有一个账户',
    },
    loginEmailInUse: {
        ua: 'Логін або E-Mail вже використовуються. Спробуйте інші дані',
        en: 'Login or E-Mail is already in use. Try different data',
        ru: 'Логин или E-Mail уже используются. Попробуйте другие данные',
        de: 'Login oder E-Mail wird bereits verwendet. Versuche es mit anderen Daten',
        pl: 'Login lub E-Mail jest już używane. Spróbuj innych danych',
        zh: '该邮箱已被占用',
    },
    invalidRegistrationData: {
        ua: 'Неправильні дані при реєстрації',
        en: 'Invalid registration data',
        ru: 'Неправильные данные при регистрации',
        de: 'Ungültige Registrierungsdaten',
        pl: 'Nieprawidłowe dane rejestracji',
        zh: '注册数据无效',
    },
    banned: {
        ru: 'Вы заблокированы на {{days}} дней по причине {{reason}}',
        en: 'You are banned for {{days}} days for {{reason}}',
        ua: 'Ви заблоковані на {{days}} днів по причині {{reason}}',
        de: 'Du wurdest für {{days}} Tage gesperrt. Grund: {{reason}}',
        pl: 'Zostałeś zablokowany z powodu {{reason}}',
        zh: '您已被封禁{{days}}封禁原因{{reason}}',
    },
    invalidCode: {
        ru: 'Код восстановления не найден',
        ua: 'Код відновлення не знайдено',
        en: 'Recovery code not found',
        de: 'Wiederherstellungscode nicht gefunden',
        pl: 'Kod odzyskiwania nie znaleziony',
        zh: '未找到恢复代码',
    },
    codeExpired: {
        ru: 'Время действия кода истекло',
        ua: 'Час дії коду закінчився',
        en: 'Code has expired',
        de: 'Code ist abgelaufen',
        pl: 'Kod wygasł',
        zh: '代码已过期',
    },
    passwordChanged: {
        ru: 'Вы успешно изменили пароль',
        ua: 'Ви успішно змінили пароль',
        en: 'You have successfully changed your password',
        de: 'Du hast Ihr Passwort erfolgreich geändert',
        pl: 'Pomyślnie zmieniłeś hasło',
        zh: '密码修改成功',
    },
    resetData: {
        ru: 'Сохраненные данные были сброшены в целях безопасности',
        ua: 'Збережені дані були скинуті з міркувань безпеки',
        en: 'Saved data has been reset for security reasons',
        de: 'Gespeicherte Daten wurden aus Sicherheitsgründen zurückgesetzt',
        pl: 'Zapisane dane zostały zresetowane ze względów bezpieczeństwa',
    },
    html: {
        recovery,
    },
};
