export const blackjack = {
    name: {
        ru: 'Блекджек',
        ua: 'Блекджек',
        en: 'Blackjack',
        de: 'Blackjack',
        pl: 'Blackjack',
        zh: '二十一点',
    },

    play: {
        ru: 'Сесть за стол блекджека',
        ua: 'Сісти за стіл блекджеку',
        en: 'Sit at the blackjack table',
        de: 'Am Blackjack-Tisch Platz nehmen',
        pl: 'Usiądź przy stole do blackjacka',
        zh: '坐到二十一点桌前',
    },

    maxChips: {
        ru: 'Вы уже поставили максимум фишек',
        ua: 'Ви вже поставили максимум фішок',
        en: 'You have already placed the maximum number of chips',
        de: 'Du hast bereits die maximale Anzahl an Chips gesetzt',
        pl: 'Postawiłeś już maksymalną liczbę żetonów',
        zh: '你已经下了最多的筹码',
    },

    occupied: {
        ru: 'Это место уже занято',
        ua: 'Це місце вже зайняте',
        en: 'This seat is taken',
        de: 'Dieser Platz ist besetzt',
        pl: 'To miejsce jest zajęte',
        zh: '这个座位已被占用',
    },

    table: {
        ru: 'Стол {{n}}',
        ua: 'Стіл {{n}}',
        en: 'Table {{n}}',
        de: 'Tisch {{n}}',
        pl: 'Stół {{n}}',
        zh: '{{n}}号桌',
    },

    phases: {
        idle: {
            ru: 'Ждём игроков',
            ua: 'Чекаємо гравців',
            en: 'Waiting for players',
            de: 'Warten auf Spieler',
            pl: 'Czekamy na graczy',
            zh: '等待玩家',
        },
        betting: {
            ru: 'Делайте ставки',
            ua: 'Робіть ставки',
            en: 'Place your bets',
            de: 'Bitte setzen',
            pl: 'Obstawiajcie',
            zh: '请下注',
        },
        dealing: {
            ru: 'Раздача',
            ua: 'Роздача',
            en: 'Dealing',
            de: 'Karten werden ausgeteilt',
            pl: 'Rozdanie',
            zh: '发牌中',
        },
        yourTurn: {
            ru: 'Ваш ход',
            ua: 'Ваш хід',
            en: 'Your turn',
            de: 'Du bist dran',
            pl: 'Twój ruch',
            zh: '轮到你了',
        },
        seatTurn: {
            ru: 'Ходит место {{n}}',
            ua: 'Ходить місце {{n}}',
            en: 'Seat {{n}} to play',
            de: 'Platz {{n}} ist dran',
            pl: 'Ruch miejsca {{n}}',
            zh: '{{n}}号位行动中',
        },
        dealer: {
            ru: 'Дилер добирает',
            ua: 'Дилер добирає',
            en: 'Dealer draws',
            de: 'Der Dealer zieht',
            pl: 'Krupier dobiera',
            zh: '庄家补牌',
        },
        results: {
            ru: 'Итоги раунда',
            ua: 'Підсумки раунду',
            en: 'Round results',
            de: 'Rundenergebnis',
            pl: 'Wyniki rundy',
            zh: '本局结果',
        },
        nextRound: {
            ru: 'Ставка в следующем раунде',
            ua: 'Ставка в наступному раунді',
            en: 'You bet in the next round',
            de: 'Einsatz in der nächsten Runde',
            pl: 'Zakład w następnej rundzie',
            zh: '下一局下注',
        },
    },

    dealer: {
        ru: 'Дилер',
        ua: 'Дилер',
        en: 'Dealer',
        de: 'Dealer',
        pl: 'Krupier',
        zh: '庄家',
    },

    you: {
        ru: 'Вы',
        ua: 'Ви',
        en: 'You',
        de: 'Du',
        pl: 'Ty',
        zh: '你',
    },

    others: {
        ru: 'Другие игроки',
        ua: 'Інші гравці',
        en: 'Other players',
        de: 'Andere Spieler',
        pl: 'Inni gracze',
        zh: '其他玩家',
    },

    seat: {
        ru: 'Место {{n}}',
        ua: 'Місце {{n}}',
        en: 'Seat {{n}}',
        de: 'Platz {{n}}',
        pl: 'Miejsce {{n}}',
        zh: '{{n}}号位',
    },

    // Key hints of the bottom bar.
    hints: {
        placeBet: {
            ru: 'Поставить',
            ua: 'Поставити',
            en: 'Place bet',
            de: 'Setzen',
            pl: 'Postaw',
            zh: '下注',
        },
        hit: {
            ru: 'Ещё карту',
            ua: 'Ще карту',
            en: 'Hit',
            de: 'Karte',
            pl: 'Dobierz',
            zh: '要牌',
        },
        stand: {
            ru: 'Хватит',
            ua: 'Досить',
            en: 'Stand',
            de: 'Stehen',
            pl: 'Pas',
            zh: '停牌',
        },
        double: {
            ru: 'Удвоить',
            ua: 'Подвоїти',
            en: 'Double',
            de: 'Verdoppeln',
            pl: 'Podwój',
            zh: '加倍',
        },
        split: {
            ru: 'Разделить',
            ua: 'Розділити',
            en: 'Split',
            de: 'Teilen',
            pl: 'Rozdziel',
            zh: '分牌',
        },
        hideTable: {
            ru: 'Скрыть стол',
            ua: 'Сховати стіл',
            en: 'Hide table',
            de: 'Tisch ausblenden',
            pl: 'Ukryj stół',
            zh: '隐藏牌桌',
        },
        rules: {
            ru: 'Правила',
            ua: 'Правила',
            en: 'Rules',
            de: 'Regeln',
            pl: 'Zasady',
            zh: '规则',
        },
        showTable: {
            ru: 'Показать стол',
            ua: 'Показати стіл',
            en: 'Show table',
            de: 'Tisch anzeigen',
            pl: 'Pokaż stół',
            zh: '显示牌桌',
        },
    },

    // The rules panel (I).
    rules: {
        title: {
            ru: 'Информация и правила игры в Блекджек',
            ua: 'Інформація та правила гри в Блекджек',
            en: 'Blackjack info and rules',
            de: 'Blackjack: Infos und Regeln',
            pl: 'Blackjack: informacje i zasady',
            zh: '二十一点信息与规则',
        },
        goalTitle: {
            ru: 'Цель',
            ua: 'Мета',
            en: 'Goal',
            de: 'Ziel',
            pl: 'Cel',
            zh: '目标',
        },
        goal: {
            ru: 'Наберите больше, чем у дилера, но не больше 21.',
            ua: 'Наберіть більше, ніж у дилера, але не більше 21.',
            en: "Beat the dealer's total without going over 21.",
            de: 'Mehr als der Dealer, aber nicht über 21.',
            pl: 'Zdobądź więcej niż krupier, ale nie więcej niż 21.',
            zh: '点数比庄家大, 且不超过 21。',
        },
        valuesTitle: {
            ru: 'Стоимость карт',
            ua: 'Вартість карт',
            en: 'Card values',
            de: 'Kartenwerte',
            pl: 'Wartości kart',
            zh: '牌面点数',
        },
        valueNumber: {
            ru: 'по номиналу',
            ua: 'за номіналом',
            en: 'face value',
            de: 'Nennwert',
            pl: 'według nominału',
            zh: '按牌面',
        },
        valueAce: {
            ru: '1 или 11',
            ua: '1 або 11',
            en: '1 or 11',
            de: '1 oder 11',
            pl: '1 lub 11',
            zh: '1 或 11',
        },
        roundTitle: {
            ru: 'Ход раунда',
            ua: 'Хід раунду',
            en: 'The round',
            de: 'Rundenablauf',
            pl: 'Przebieg rundy',
            zh: '回合流程',
        },
        stepBets: {
            ru: 'Ставки принимаются {{s}} секунд, можно поставить до {{n}} фишек',
            ua: 'Ставки приймаються {{s}} секунд, можна поставити до {{n}} фішок',
            en: 'Bets are open for {{s}} seconds, up to {{n}} chips',
            de: 'Einsätze sind {{s}} Sekunden lang offen, bis zu {{n}} Chips',
            pl: 'Zakłady przyjmowane są przez {{s}} sekund, maksymalnie {{n}} żetonów',
            zh: '下注时间 {{s}} 秒, 最多 {{n}} 枚筹码',
        },
        stepDeal: {
            ru: 'Все получают по 2 карты, одна карта дилера лежит закрытой. Если у дилера открыт туз или десятка, он сразу проверяет блекджек',
            ua: 'Усі отримують по 2 карти, одна карта дилера лежить закритою. Якщо в дилера відкритий туз або десятка, він одразу перевіряє блекджек',
            en: "Everyone gets two cards, one of the dealer's lies face down. With an ace or a ten showing, the dealer checks for blackjack right away",
            de: 'Alle bekommen zwei Karten, eine Dealerkarte liegt verdeckt. Zeigt er ein Ass oder eine Zehn, prüft er sofort auf Blackjack',
            pl: 'Każdy dostaje 2 karty, jedna karta krupiera leży zakryta. Gdy krupier ma odkrytego asa lub dziesiątkę, od razu sprawdza blackjacka',
            zh: '每人发两张牌, 庄家一张牌扣着。庄家明牌为 A 或 10 时会立即检查是否为二十一点',
        },
        stepTurn: {
            ru: 'На каждое решение есть {{s}} секунд, потом рука останавливается',
            ua: 'На кожне рішення є {{s}} секунд, потім рука зупиняється',
            en: 'You have {{s}} seconds for each decision, then the hand stands',
            de: 'Für jede Entscheidung hast du {{s}} Sekunden, danach bleibt die Hand stehen',
            pl: 'Na każdą decyzję masz {{s}} sekund, potem ręka pasuje',
            zh: '每次决定有 {{s}} 秒, 超时自动停牌',
        },
        stepDealer: {
            ru: 'Дилер открывает карту и добирает до 17. На 17 с тузом, который считается за 11, он тоже берёт',
            ua: 'Дилер відкриває карту й добирає до 17. На 17 з тузом, що рахується за 11, він теж бере',
            en: 'The dealer turns the card over and draws to 17, and also draws on a 17 that counts an ace as 11',
            de: 'Der Dealer deckt auf und zieht bis 17, auch bei einer 17 mit einem Ass als 11',
            pl: 'Krupier odkrywa kartę i dobiera do 17, także przy 17 z asem liczonym jako 11',
            zh: '庄家翻开暗牌补牌至 17, 若 17 点中 A 计为 11 则继续补牌',
        },
        actionsTitle: {
            ru: 'Действия',
            ua: 'Дії',
            en: 'Actions',
            de: 'Aktionen',
            pl: 'Akcje',
            zh: '操作',
        },
        actionDouble: {
            ru: 'Удвоить ставку и получить ровно одну карту',
            ua: 'Подвоїти ставку й отримати рівно одну карту',
            en: 'Double the bet and take exactly one more card',
            de: 'Einsatz verdoppeln und genau eine Karte nehmen',
            pl: 'Podwój stawkę i weź dokładnie jedną kartę',
            zh: '下注翻倍, 只再拿一张牌',
        },
        actionSplit: {
            ru: 'Разделить пару на две руки с такой же второй ставкой, один раз за раунд',
            ua: 'Розділити пару на дві руки з такою ж другою ставкою, один раз за раунд',
            en: 'Split a pair into two hands with an equal second bet, once a round',
            de: 'Ein Paar in zwei Hände teilen, mit gleichem zweitem Einsatz, einmal pro Runde',
            pl: 'Rozdziel parę na dwie ręce z taką samą drugą stawką, raz na rundę',
            zh: '将对子分成两手, 第二手下注相同, 每回合一次',
        },
        payoutsTitle: {
            ru: 'Выплаты',
            ua: 'Виплати',
            en: 'Payouts',
            de: 'Auszahlungen',
            pl: 'Wypłaty',
            zh: '赔付',
        },
        payBlackjack: {
            ru: 'Блекджек, первые две карты туз и десятка',
            ua: 'Блекджек, перші дві карти туз і десятка',
            en: 'Blackjack, an ace and a ten as the first two cards',
            de: 'Blackjack, Ass und Zehn als erste zwei Karten',
            pl: 'Blackjack, as i dziesiątka jako pierwsze dwie karty',
            zh: '二十一点, 前两张为 A 和 10',
        },
        payWin: {
            ru: 'Победа',
            ua: 'Перемога',
            en: 'Win',
            de: 'Sieg',
            pl: 'Wygrana',
            zh: '获胜',
        },
        payCharlie: {
            ru: '7 карт без перебора',
            ua: '7 карт без перебору',
            en: '7 cards without busting',
            de: '7 Karten ohne Überkaufen',
            pl: '7 kart bez fury',
            zh: '七张不爆',
        },
        paySplit21: {
            ru: '21 после разделения',
            ua: '21 після розділення',
            en: '21 after a split',
            de: '21 nach dem Teilen',
            pl: '21 po rozdzieleniu',
            zh: '分牌后的 21',
        },
        payPush: {
            ru: 'Ничья',
            ua: 'Нічия',
            en: 'Push',
            de: 'Unentschieden',
            pl: 'Remis',
            zh: '平局',
        },
        payPushValue: {
            ru: 'ставка возвращается',
            ua: 'ставка повертається',
            en: 'bet returned',
            de: 'Einsatz zurück',
            pl: 'stawka wraca',
            zh: '退还下注',
        },
        specialTitle: {
            ru: 'Особые правила',
            ua: 'Особливі правила',
            en: 'Special rules',
            de: 'Sonderregeln',
            pl: 'Zasady specjalne',
            zh: '特殊规则',
        },
        dealer22: {
            ru: 'Если у дилера 22, это ничья для всех, кроме блекджека и 7 карт',
            ua: 'Якщо в дилера 22, це нічия для всіх, крім блекджеку та 7 карт',
            en: 'A dealer 22 is a push for everyone except a blackjack or 7 cards',
            de: 'Hat der Dealer 22, ist es ein Unentschieden für alle außer Blackjack und 7 Karten',
            pl: 'Gdy krupier ma 22, jest remis dla wszystkich poza blackjackiem i 7 kartami',
            zh: '庄家 22 点时, 除二十一点和七张牌外均为平局',
        },
        dealerBlackjack: {
            ru: 'Если у дилера блекджек, проигрывают все, а у кого тоже блекджек, получают ничью',
            ua: 'Якщо в дилера блекджек, програють усі, а в кого теж блекджек, отримують нічию',
            en: 'If the dealer has blackjack, everyone loses except a blackjack, which pushes',
            de: 'Hat der Dealer Blackjack, verlieren alle, nur ein Blackjack spielt unentschieden',
            pl: 'Gdy krupier ma blackjacka, wszyscy przegrywają, a blackjack daje remis',
            zh: '庄家为二十一点时全部输, 玩家同为二十一点则平局',
        },
        limits: {
            ru: 'Ставка от {{min}} до {{max}} фишек',
            ua: 'Ставка від {{min}} до {{max}} фішок',
            en: 'Bet {{min}} to {{max}} chips',
            de: 'Einsatz {{min}} bis {{max}} Chips',
            pl: 'Stawka od {{min}} do {{max}} żetonów',
            zh: '下注 {{min}} 至 {{max}} 筹码',
        },
    },

    bust: {
        ru: 'Перебор',
        ua: 'Перебір',
        en: 'Bust',
        de: 'Überkauft',
        pl: 'Fura',
        zh: '爆牌',
    },
};
