export const jackpot = {
    name: {
        ru: 'Джекпот',
        ua: 'Джекпот',
        en: 'Jackpot',
        de: 'Jackpot',
        pl: 'Jackpot',
        zh: '奖池',
    },

    // Said in more than one place of the wall.
    chance: {
        ru: 'Шанс',
        ua: 'Шанс',
        en: 'Chance',
        de: 'Chance',
        pl: 'Szansa',
        zh: '概率',
    },
    closed: {
        ru: 'Ставки закрыты',
        ua: 'Ставки закриті',
        en: 'Stakes are closed',
        de: 'Einsätze geschlossen',
        pl: 'Stawki zamknięte',
        zh: '停止下注',
    },

    // The chairs in front of the wall.
    play: {
        ru: 'Играть в джекпот',
        ua: 'Грати в джекпот',
        en: 'Play the jackpot',
        de: 'Jackpot spielen',
        pl: 'Graj w jackpot',
        zh: '玩奖池',
    },
    occupied: {
        ru: 'Это кресло уже занято',
        ua: 'Це крісло вже зайняте',
        en: 'This chair is taken',
        de: 'Dieser Sessel ist besetzt',
        pl: 'Ten fotel jest zajęty',
        zh: '这个座位已被占用',
    },

    // The list of players on the left of the wall.
    board: {
        players: {
            ru: 'Участники',
            ua: 'Учасники',
            en: 'Players',
            de: 'Spieler',
            pl: 'Gracze',
            zh: '玩家',
        },
        bet: {
            ru: 'Ставка',
            ua: 'Ставка',
            en: 'Stake',
            de: 'Einsatz',
            pl: 'Stawka',
            zh: '下注',
        },
        others: {
            ru: 'Другие',
            ua: 'Інші',
            en: 'Others',
            de: 'Andere',
            pl: 'Inni',
            zh: '其他',
        },
        empty: {
            ru: 'Ставок пока нет',
            ua: 'Ставок поки немає',
            en: 'No stakes yet',
            de: 'Noch keine Einsätze',
            pl: 'Nie ma jeszcze stawek',
            zh: '暂无下注',
        },
        emptyHint: {
            ru: 'Первая ставка открывает банк',
            ua: 'Перша ставка відкриває банк',
            en: 'The first stake opens the pot',
            de: 'Der erste Einsatz eröffnet den Pot',
            pl: 'Pierwsza stawka otwiera pulę',
            zh: '第一笔下注开启奖池',
        },
    },

    // The middle of the wheel.
    hub: {
        first: {
            ru: 'Сделайте первую ставку',
            ua: 'Зробіть першу ставку',
            en: 'Place the first stake',
            de: 'Setze den ersten Einsatz',
            pl: 'Postaw pierwszą stawkę',
            zh: '下第一注',
        },
        needOne: {
            ru: 'Нужен ещё один игрок',
            ua: 'Потрібен ще один гравець',
            en: 'One more player needed',
            de: 'Ein weiterer Spieler fehlt',
            pl: 'Potrzebny jeszcze jeden gracz',
            zh: '还需要一名玩家',
        },
        pot: {
            ru: 'Банк',
            ua: 'Банк',
            en: 'Pot',
            de: 'Pot',
            pl: 'Pula',
            zh: '奖池',
        },
        wins: {
            ru: 'Победитель',
            ua: 'Переможець',
            en: 'Winner',
            de: 'Gewinner',
            pl: 'Zwycięzca',
            zh: '赢家',
        },
        next: {
            ru: 'Новый раунд',
            ua: 'Новий раунд',
            en: 'Next round',
            de: 'Neue Runde',
            pl: 'Nowa runda',
            zh: '下一轮',
        },
    },

    // The player's own panel on the right of the wall.
    panel: {
        title: {
            ru: 'Ваша ставка',
            ua: 'Ваша ставка',
            en: 'Your stake',
            de: 'Dein Einsatz',
            pl: 'Twoja stawka',
            zh: '你的下注',
        },
        balance: {
            ru: 'Баланс',
            ua: 'Баланс',
            en: 'Balance',
            de: 'Guthaben',
            pl: 'Bilans',
            zh: '余额',
        },
        max: {
            ru: 'Макс',
            ua: 'Макс',
            en: 'Max',
            de: 'Max',
            pl: 'Maks',
            zh: '最大',
        },
        join: {
            ru: 'Войти в джекпот',
            ua: 'Увійти в джекпот',
            en: 'Join the jackpot',
            de: 'Am Jackpot teilnehmen',
            pl: 'Dołącz do jackpota',
            zh: '加入奖池',
        },
        add: {
            ru: 'Добавить к ставке',
            ua: 'Додати до ставки',
            en: 'Add to the stake',
            de: 'Einsatz erhöhen',
            pl: 'Dodaj do stawki',
            zh: '追加下注',
        },
        noChips: {
            ru: 'Недостаточно фишек',
            ua: 'Недостатньо фішок',
            en: 'Not enough chips',
            de: 'Nicht genug Chips',
            pl: 'Za mało żetonów',
            zh: '筹码不足',
        },
        limit: {
            ru: 'Лимит ставки исчерпан',
            ua: 'Ліміт ставки вичерпано',
            en: 'Stake limit reached',
            de: 'Einsatzlimit erreicht',
            pl: 'Limit stawki wyczerpany',
            zh: '已达下注上限',
        },
        staked: {
            ru: 'В банке',
            ua: 'У банку',
            en: 'In the pot',
            de: 'Im Pot',
            pl: 'W puli',
            zh: '已投入',
        },
        yourChance: {
            ru: 'Ваш шанс',
            ua: 'Ваш шанс',
            en: 'Your chance',
            de: 'Deine Chance',
            pl: 'Twoja szansa',
            zh: '你的概率',
        },
        withdraw: {
            ru: 'Забрать ставку',
            ua: 'Забрати ставку',
            en: 'Take the stake back',
            de: 'Einsatz zurücknehmen',
            pl: 'Odbierz stawkę',
            zh: '取回下注',
        },
    },

    // The right of the wall for a player who is not seated.
    rules: {
        title: {
            ru: 'Как играть',
            ua: 'Як грати',
            en: 'How to play',
            de: 'So wird gespielt',
            pl: 'Jak grać',
            zh: '玩法',
        },
        pot: {
            ru: 'Победитель получает весь джекпот\u00a0- банк всех участников ставок',
            ua: 'Переможець отримує весь джекпот\u00a0- банк усіх учасників ставок',
            en: 'The winner takes the whole jackpot\u00a0- the pot of every stake made',
            de: 'Der Gewinner bekommt den ganzen Jackpot\u00a0- den Pot aller Einsätze',
            pl: 'Zwycięzca zabiera cały jackpot\u00a0- pulę wszystkich stawek',
            zh: '赢家赢得整个奖池\u00a0- 所有参与者的下注总和',
        },
        range: {
            ru: 'ставка за раунд',
            ua: 'ставка за раунд',
            en: 'stake per round',
            de: 'Einsatz pro Runde',
            pl: 'stawka na rundę',
            zh: '每轮下注',
        },
        share: {
            ru: 'Шанс равен вашей доле в банке',
            ua: 'Шанс дорівнює вашій частці в банку',
            en: 'Your chance is your share of the pot',
            de: 'Deine Chance ist dein Anteil am Pot',
            pl: 'Szansa równa się twojemu udziałowi w puli',
            zh: '概率等于你在奖池中的份额',
        },
        fee: {
            ru: 'комиссия казино с банка',
            ua: 'комісія казино з банку',
            en: 'casino commission on the pot',
            de: 'Casino-Gebühr auf den Pot',
            pl: 'prowizja kasyna od puli',
            zh: '赌场从奖池抽成',
        },
        seat: {
            ru: 'Сядьте в кресло, чтобы сделать ставку',
            ua: 'Сядьте в крісло, щоб зробити ставку',
            en: 'Take a seat to place a stake',
            de: 'Nimm Platz, um zu setzen',
            pl: 'Usiądź w fotelu, aby postawić stawkę',
            zh: '入座后即可下注',
        },
    },
};
