export const poker = {
    name: {
        ru: 'Покер',
        ua: 'Покер',
        en: 'Three Card Poker',
        de: 'Three Card Poker',
        pl: 'Poker trzykartowy',
        zh: '三张牌扑克',
    },

    play: {
        ru: 'Сесть за стол покера',
        ua: 'Сісти за стіл покеру',
        en: 'Sit at the poker table',
        de: 'Am Pokertisch Platz nehmen',
        pl: 'Usiądź przy stole do pokera',
        zh: '坐到扑克桌前',
    },

    occupied: {
        ru: 'Это место уже занято',
        ua: 'Це місце вже зайняте',
        en: 'This seat is taken',
        de: 'Dieser Platz ist besetzt',
        pl: 'To miejsce jest zajęte',
        zh: '这个座位已被占用',
    },

    maxChips: {
        ru: 'На эту ставку уже поставлен максимум фишек',
        ua: 'На цю ставку вже поставлено максимум фішок',
        en: 'This bet already holds the maximum number of chips',
        de: 'Auf diesem Einsatz liegt bereits die maximale Anzahl an Chips',
        pl: 'Na tym zakładzie jest już maksymalna liczba żetonów',
        zh: '这个下注已达到筹码上限',
    },

    maxPairPlus: {
        ru: 'Ставка Пара плюс не может быть больше {{max}} фишек',
        ua: 'Ставка Пара плюс не може бути більшою за {{max}} фішок',
        en: 'The Pair Plus bet cannot exceed {{max}} chips',
        de: 'Der Pair-Plus-Einsatz darf {{max}} Chips nicht übersteigen',
        pl: 'Zakład Pair Plus nie może przekroczyć {{max}} żetonów',
        zh: '对子加注不能超过 {{max}} 筹码',
    },

    keepPlay: {
        ru: 'Оставьте фишки на ставку Игра, она равна Анте',
        ua: 'Залиште фішки на ставку Гра, вона дорівнює Анте',
        en: 'Keep chips for the Play bet, it equals the Ante',
        de: 'Behalte Chips für den Play-Einsatz, er entspricht dem Ante',
        pl: 'Zostaw żetony na zakład Gra, jest równy ante',
        zh: '请为跟注留出筹码, 跟注等于底注',
    },

    table: {
        ru: 'Стол {{n}}',
        ua: 'Стіл {{n}}',
        en: 'Table {{n}}',
        de: 'Tisch {{n}}',
        pl: 'Stół {{n}}',
        zh: '{{n}}号桌',
    },

    phases: {
        idle: {
            ru: 'Ждём игроков',
            ua: 'Чекаємо гравців',
            en: 'Waiting for players',
            de: 'Warten auf Spieler',
            pl: 'Czekamy na graczy',
            zh: '等待玩家',
        },
        betting: {
            ru: 'Делайте ставки',
            ua: 'Робіть ставки',
            en: 'Place your bets',
            de: 'Bitte setzen',
            pl: 'Obstawiajcie',
            zh: '请下注',
        },
        dealing: {
            ru: 'Раздача',
            ua: 'Роздача',
            en: 'Dealing',
            de: 'Karten werden ausgeteilt',
            pl: 'Rozdanie',
            zh: '发牌中',
        },
        decide: {
            ru: 'Играть или сбросить?',
            ua: 'Грати чи скинути?',
            en: 'Play or fold?',
            de: 'Spielen oder aussteigen?',
            pl: 'Grasz czy pasujesz?',
            zh: '跟注还是弃牌?',
        },
        deciding: {
            ru: 'Игроки решают',
            ua: 'Гравці вирішують',
            en: 'Players are deciding',
            de: 'Die Spieler entscheiden',
            pl: 'Gracze decydują',
            zh: '玩家决定中',
        },
        revealing: {
            ru: 'Вскрытие карт',
            ua: 'Відкриття карт',
            en: 'Showdown',
            de: 'Aufdecken',
            pl: 'Odkrywanie kart',
            zh: '亮牌',
        },
        results: {
            ru: 'Итоги раунда',
            ua: 'Підсумки раунду',
            en: 'Round results',
            de: 'Rundenergebnis',
            pl: 'Wyniki rundy',
            zh: '本局结果',
        },
        nextRound: {
            ru: 'Ставка в следующем раунде',
            ua: 'Ставка в наступному раунді',
            en: 'You bet in the next round',
            de: 'Einsatz in der nächsten Runde',
            pl: 'Zakład w następnej rundzie',
            zh: '下一局下注',
        },
    },

    dealer: {
        ru: 'Дилер',
        ua: 'Дилер',
        en: 'Dealer',
        de: 'Dealer',
        pl: 'Krupier',
        zh: '庄家',
    },

    you: {
        ru: 'Вы',
        ua: 'Ви',
        en: 'You',
        de: 'Du',
        pl: 'Ty',
        zh: '你',
    },

    others: {
        ru: 'Другие игроки',
        ua: 'Інші гравці',
        en: 'Other players',
        de: 'Andere Spieler',
        pl: 'Inni gracze',
        zh: '其他玩家',
    },

    spots: {
        ante: {
            ru: 'Анте',
            ua: 'Анте',
            en: 'Ante',
            de: 'Ante',
            pl: 'Ante',
            zh: '底注',
        },
        pairPlus: {
            ru: 'Пара плюс',
            ua: 'Пара плюс',
            en: 'Pair Plus',
            de: 'Pair Plus',
            pl: 'Pair Plus',
            zh: '对子加注',
        },
        play: {
            ru: 'Игра',
            ua: 'Гра',
            en: 'Play',
            de: 'Play',
            pl: 'Gra',
            zh: '跟注',
        },
    },

    folded: {
        ru: 'Сброс',
        ua: 'Скинуто',
        en: 'Folded',
        de: 'Ausgestiegen',
        pl: 'Pas',
        zh: '已弃牌',
    },

    noQualify: {
        ru: 'Не играет',
        ua: 'Не грає',
        en: 'Does not play',
        de: 'Spielt nicht',
        pl: 'Nie gra',
        zh: '庄家不跟',
    },

    hands: {
        straightFlush: {
            ru: 'Стрит-флеш',
            ua: 'Стріт-флеш',
            en: 'Straight flush',
            de: 'Straight Flush',
            pl: 'Poker',
            zh: '同花顺',
        },
        trips: {
            ru: 'Тройка',
            ua: 'Трійка',
            en: 'Three of a kind',
            de: 'Drilling',
            pl: 'Trójka',
            zh: '三条',
        },
        straight: {
            ru: 'Стрит',
            ua: 'Стріт',
            en: 'Straight',
            de: 'Straße',
            pl: 'Strit',
            zh: '顺子',
        },
        flush: {
            ru: 'Флеш',
            ua: 'Флеш',
            en: 'Flush',
            de: 'Flush',
            pl: 'Kolor',
            zh: '同花',
        },
        pair: {
            ru: 'Пара {{rank}}',
            ua: 'Пара {{rank}}',
            en: 'Pair of {{rank}}',
            de: 'Paar {{rank}}',
            pl: 'Para {{rank}}',
            zh: '对{{rank}}',
        },
        high: {
            ru: 'Старшая {{rank}}',
            ua: 'Старша {{rank}}',
            en: '{{rank}} high',
            de: '{{rank}} hoch',
            pl: 'Wysoka {{rank}}',
            zh: '{{rank}}高牌',
        },
    },

    hints: {
        ante: {
            ru: 'Анте',
            ua: 'Анте',
            en: 'Ante',
            de: 'Ante',
            pl: 'Ante',
            zh: '底注',
        },
        pairPlus: {
            ru: 'Пара плюс',
            ua: 'Пара плюс',
            en: 'Pair Plus',
            de: 'Pair Plus',
            pl: 'Pair Plus',
            zh: '对子加注',
        },
        play: {
            ru: 'Играть',
            ua: 'Грати',
            en: 'Play',
            de: 'Spielen',
            pl: 'Graj',
            zh: '跟注',
        },
        fold: {
            ru: 'Сбросить',
            ua: 'Скинути',
            en: 'Fold',
            de: 'Aussteigen',
            pl: 'Pasuj',
            zh: '弃牌',
        },
        showTable: {
            ru: 'Показать стол',
            ua: 'Показати стіл',
            en: 'Show table',
            de: 'Tisch zeigen',
            pl: 'Pokaż stół',
            zh: '显示牌桌',
        },
        hideTable: {
            ru: 'Скрыть стол',
            ua: 'Сховати стіл',
            en: 'Hide table',
            de: 'Tisch ausblenden',
            pl: 'Ukryj stół',
            zh: '隐藏牌桌',
        },
        rules: {
            ru: 'Правила',
            ua: 'Правила',
            en: 'Rules',
            de: 'Regeln',
            pl: 'Zasady',
            zh: '规则',
        },
    },

    // The rules panel (I).
    rules: {
        title: {
            ru: 'Информация и правила игры в Покер',
            ua: 'Інформація та правила гри в Покер',
            en: 'Three Card Poker info and rules',
            de: 'Three Card Poker: Infos und Regeln',
            pl: 'Poker trzykartowy: informacje i zasady',
            zh: '三张牌扑克信息与规则',
        },
        goalTitle: {
            ru: 'Цель',
            ua: 'Мета',
            en: 'Goal',
            de: 'Ziel',
            pl: 'Cel',
            zh: '目标',
        },
        goal: {
            ru: 'У вас и у дилера по три карты. Выигрывает старшая комбинация.',
            ua: 'У вас і в дилера по три карти. Виграє старша комбінація.',
            en: 'You and the dealer get three cards each. The higher hand wins.',
            de: 'Du und der Dealer bekommen je drei Karten. Die höhere Hand gewinnt.',
            pl: 'Ty i krupier dostajecie po trzy karty. Wygrywa starszy układ.',
            zh: '你和庄家各拿三张牌, 牌型大者获胜。',
        },
        handsTitle: {
            ru: 'Комбинации от старшей и выплаты Пары плюс',
            ua: 'Комбінації від старшої та виплати Пари плюс',
            en: 'Hands, highest first, and Pair Plus pays',
            de: 'Hände, die höchste zuerst, und Pair-Plus-Auszahlungen',
            pl: 'Układy od najstarszego i wypłaty Pair Plus',
            zh: '牌型从大到小及对子加注赔率',
        },
        // Hand names without a rank, for the ranking.
        hands: {
            straightFlush: {
                ru: 'Стрит-флеш',
                ua: 'Стріт-флеш',
                en: 'Straight flush',
                de: 'Straight Flush',
                pl: 'Poker',
                zh: '同花顺',
            },
            trips: {
                ru: 'Тройка',
                ua: 'Трійка',
                en: 'Three of a kind',
                de: 'Drilling',
                pl: 'Trójka',
                zh: '三条',
            },
            straight: {
                ru: 'Стрит',
                ua: 'Стріт',
                en: 'Straight',
                de: 'Straße',
                pl: 'Strit',
                zh: '顺子',
            },
            flush: {
                ru: 'Флеш',
                ua: 'Флеш',
                en: 'Flush',
                de: 'Flush',
                pl: 'Kolor',
                zh: '同花',
            },
            pair: {
                ru: 'Пара',
                ua: 'Пара',
                en: 'Pair',
                de: 'Paar',
                pl: 'Para',
                zh: '对子',
            },
            high: {
                ru: 'Старшая карта',
                ua: 'Старша карта',
                en: 'High card',
                de: 'Höchste Karte',
                pl: 'Wysoka karta',
                zh: '高牌',
            },
        },
        handsNote: {
            ru: 'Из трёх карт стрит собрать труднее, чем флеш, поэтому он старше. Туз может закрывать стрит сверху (Q-K-A) и начинать его снизу (A-2-3).',
            ua: 'З трьох карт стріт зібрати важче, ніж флеш, тому він старший. Туз може закривати стріт згори (Q-K-A) і починати його знизу (A-2-3).',
            en: 'With three cards a straight is harder to make than a flush, so it ranks higher. An ace can end a straight (Q-K-A) or start one (A-2-3).',
            de: 'Mit drei Karten ist eine Straße schwerer als ein Flush und daher höher. Ein Ass kann eine Straße oben (Q-K-A) oder unten (A-2-3) abschließen.',
            pl: 'Z trzech kart strita ułożyć trudniej niż kolor, dlatego jest starszy. As może kończyć strita (Q-K-A) albo go zaczynać (A-2-3).',
            zh: '三张牌时顺子比同花更难凑成, 所以更大。A 可作顺子的最大牌 (Q-K-A) 或最小牌 (A-2-3)。',
        },
        pairPlusNote: {
            ru: 'Пара плюс платит по этой таблице за вашу комбинацию, что бы ни было у дилера, даже если вы сбросили карты.',
            ua: 'Пара плюс платить за цією таблицею за вашу комбінацію, хай що в дилера, навіть якщо ви скинули карти.',
            en: 'Pair Plus pays your hand by this table, whatever the dealer holds, even if you fold.',
            de: 'Pair Plus zahlt deine Hand nach dieser Tabelle, egal was der Dealer hat, auch wenn du aussteigst.',
            pl: 'Pair Plus płaci za twój układ według tej tabeli, bez względu na krupiera, nawet gdy spasujesz.',
            zh: '对子加注按此表只看你的牌型支付, 与庄家无关, 弃牌后也照付。',
        },
        roundTitle: {
            ru: 'Ход раунда',
            ua: 'Хід раунду',
            en: 'The round',
            de: 'Rundenablauf',
            pl: 'Przebieg rundy',
            zh: '回合流程',
        },
        stepBets: {
            ru: 'Поставьте на Анте, на Пару плюс или на обе. Приём ставок закрывается через {{s}} секунд после первой ставки за столом',
            ua: 'Поставте на Анте, на Пару плюс або на обидві. Прийом ставок закривається через {{s}} секунд після першої ставки за столом',
            en: 'Bet on the Ante, on Pair Plus or on both. Bets close {{s}} seconds after the first bet at the table',
            de: 'Setze auf Ante, auf Pair Plus oder auf beides. Die Einsätze schließen {{s}} Sekunden nach dem ersten Einsatz am Tisch',
            pl: 'Postaw na ante, na Pair Plus albo na oba. Zakłady zamykają się {{s}} sekund po pierwszym zakładzie przy stole',
            zh: '可以下底注、对子加注或两者都下。桌上第一注后 {{s}} 秒停止下注',
        },
        stepDeal: {
            ru: 'Все получают по три карты. Свои вы видите сразу, карты дилера закрыты',
            ua: 'Усі отримують по три карти. Свої ви бачите одразу, карти дилера закриті',
            en: "Everyone gets three cards. You see yours at once, the dealer's stay face down",
            de: 'Alle bekommen drei Karten. Deine siehst du sofort, die des Dealers bleiben verdeckt',
            pl: 'Każdy dostaje trzy karty. Swoje widzisz od razu, karty krupiera są zakryte',
            zh: '每人发三张牌。你立即能看到自己的牌, 庄家的牌扣着',
        },
        stepDecide: {
            ru: 'Кто поставил на Анте, за {{s}} секунд решает: играть, поставив ещё столько же, сколько на Анте, или сбросить. Кто не успел, сбрасывает карты',
            ua: 'Хто поставив на Анте, за {{s}} секунд вирішує: грати, поставивши ще стільки ж, скільки на Анте, або скинути. Хто не встиг, скидає карти',
            en: 'With an Ante you have {{s}} seconds to play, betting as much again as the Ante, or to fold. No choice in time folds the hand',
            de: 'Wer auf Ante gesetzt hat, entscheidet in {{s}} Sekunden: spielen und noch einmal so viel wie das Ante setzen, oder aussteigen. Ohne Entscheidung wird ausgestiegen',
            pl: 'Kto postawił ante, ma {{s}} sekund: grać, stawiając drugi raz tyle co ante, albo spasować. Kto nie zdąży, pasuje',
            zh: '下了底注的玩家有 {{s}} 秒决定: 跟注 (再下与底注相同的金额) 或弃牌。超时自动弃牌',
        },
        stepReveal: {
            ru: 'Дилер открывает карты. Он играет, только если у него дама или старше',
            ua: 'Дилер відкриває карти. Він грає, лише якщо в нього дама або старше',
            en: 'The dealer shows the cards and plays only with a queen high or better',
            de: 'Der Dealer deckt auf und spielt nur ab einer Dame hoch',
            pl: 'Krupier odkrywa karty i gra tylko z damą lub wyżej',
            zh: '庄家亮牌, 只有 Q 高或更大时才跟注',
        },
        actionsTitle: {
            ru: 'Управление',
            ua: 'Керування',
            en: 'Controls',
            de: 'Steuerung',
            pl: 'Sterowanie',
            zh: '操作',
        },
        actionMain: {
            ru: 'Ставка на Анте, а после раздачи играть',
            ua: 'Ставка на Анте, а після роздачі грати',
            en: 'Bet on the Ante, then play after the deal',
            de: 'Einsatz aufs Ante, nach dem Austeilen spielen',
            pl: 'Zakład na ante, po rozdaniu graj',
            zh: '下底注, 发牌后跟注',
        },
        actionPairPlus: {
            ru: 'Ставка на Пару плюс',
            ua: 'Ставка на Пару плюс',
            en: 'Bet on Pair Plus',
            de: 'Einsatz auf Pair Plus',
            pl: 'Zakład na Pair Plus',
            zh: '下对子加注',
        },
        actionFold: {
            ru: 'Сбросить карты, Анте проигрывается',
            ua: 'Скинути карти, Анте програється',
            en: 'Fold, the Ante is lost',
            de: 'Aussteigen, das Ante ist verloren',
            pl: 'Spasuj, ante przepada',
            zh: '弃牌, 底注输掉',
        },
        payoutsTitle: {
            ru: 'Анте и Игра',
            ua: 'Анте і Гра',
            en: 'Ante and Play',
            de: 'Ante und Play',
            pl: 'Ante i Gra',
            zh: '底注与跟注',
        },
        payNoQualify: {
            ru: 'Дилер не играет',
            ua: 'Дилер не грає',
            en: 'The dealer does not play',
            de: 'Der Dealer spielt nicht',
            pl: 'Krupier nie gra',
            zh: '庄家不跟',
        },
        payNoQualifyValue: {
            ru: 'Анте 1:1, Игра возвращается',
            ua: 'Анте 1:1, Гра повертається',
            en: 'Ante 1:1, Play returned',
            de: 'Ante 1:1, Play zurück',
            pl: 'Ante 1:1, Gra wraca',
            zh: '底注 1:1, 跟注退还',
        },
        payWin: {
            ru: 'Ваша комбинация старше',
            ua: 'Ваша комбінація старша',
            en: 'Your hand is higher',
            de: 'Deine Hand ist höher',
            pl: 'Twój układ jest starszy',
            zh: '你的牌更大',
        },
        payWinValue: {
            ru: 'Анте и Игра 1:1',
            ua: 'Анте і Гра 1:1',
            en: 'Ante and Play 1:1',
            de: 'Ante und Play 1:1',
            pl: 'Ante i Gra 1:1',
            zh: '底注和跟注 1:1',
        },
        payLose: {
            ru: 'Комбинация дилера старше',
            ua: 'Комбінація дилера старша',
            en: "The dealer's hand is higher",
            de: 'Die Hand des Dealers ist höher',
            pl: 'Układ krupiera jest starszy',
            zh: '庄家的牌更大',
        },
        payLoseValue: {
            ru: 'Анте и Игра проигрывают',
            ua: 'Анте і Гра програють',
            en: 'Ante and Play lose',
            de: 'Ante und Play verlieren',
            pl: 'Ante i Gra przegrywają',
            zh: '底注和跟注输掉',
        },
        payPush: {
            ru: 'Комбинации равны',
            ua: 'Комбінації рівні',
            en: 'Equal hands',
            de: 'Gleiche Hände',
            pl: 'Równe układy',
            zh: '牌型相同',
        },
        payPushValue: {
            ru: 'Ставки возвращаются',
            ua: 'Ставки повертаються',
            en: 'Bets returned',
            de: 'Einsätze zurück',
            pl: 'Zakłady wracają',
            zh: '退还下注',
        },
        bonusTitle: {
            ru: 'Бонус к Анте',
            ua: 'Бонус до Анте',
            en: 'Ante Bonus',
            de: 'Ante-Bonus',
            pl: 'Bonus do ante',
            zh: '底注奖励',
        },
        bonus: {
            ru: 'за стрит и старше, если вы играли, даже при проигрыше',
            ua: 'за стріт і старше, якщо ви грали, навіть у разі програшу',
            en: 'for a straight or better if you played, even when you lose',
            de: 'für eine Straße oder besser, wenn du spielst, auch bei Verlust',
            pl: 'za strita i wyżej, jeśli grasz, nawet przy przegranej',
            zh: '顺子或更大且已跟注, 输了也照付',
        },
        limits: {
            ru: 'Анте от {{min}} до {{max}} фишек, Пара плюс от {{min}} до {{pairPlus}}',
            ua: 'Анте від {{min}} до {{max}} фішок, Пара плюс від {{min}} до {{pairPlus}}',
            en: 'Ante {{min}} to {{max}} chips, Pair Plus {{min}} to {{pairPlus}}',
            de: 'Ante {{min}} bis {{max}} Chips, Pair Plus {{min}} bis {{pairPlus}}',
            pl: 'Ante od {{min}} do {{max}} żetonów, Pair Plus od {{min}} do {{pairPlus}}',
            zh: '底注 {{min}} 至 {{max}} 筹码, 对子加注 {{min}} 至 {{pairPlus}}',
        },
        keepPlay: {
            ru: 'Игра равна Анте, поэтому после ставок у вас должно оставаться столько же фишек, сколько на Анте',
            ua: 'Гра дорівнює Анте, тому після ставок у вас має лишатися стільки ж фішок, скільки на Анте',
            en: 'Play equals the Ante, so after your bets you need as many chips left as your Ante',
            de: 'Play entspricht dem Ante, daher müssen dir nach den Einsätzen so viele Chips bleiben wie dein Ante',
            pl: 'Gra równa się ante, więc po zakładach musi ci zostać tyle żetonów, ile postawiłeś na ante',
            zh: '跟注等于底注, 所以下注后你剩下的筹码至少要等于底注',
        },
    },
};
