import cef from './cef';

export default {
    cef,
    error: {
        ru: 'Произошла ошибка при продаже авто',
        ua: 'Сталася помилка при продажу авто',
        en: 'An error occurred while selling the car',
        de: 'Beim Verkauf des Autos ist ein Fehler aufgetreten',
        pl: 'Wystąpił błąd podczas sprzedaży samochodu',
    },
    youSuccessfullySold: {
        ru: 'Вы продали {{vehicle}} за ${{price}} гражданину {{buyer}}',
        ua: 'Ви продали {{vehicle}} за ${{price}} громадянину {{buyer}}',
        en: 'You sold {{vehicle}} for ${{price}} to {{buyer}}',
        de: 'Sie haben {{vehicle}} für ${{price}} an {{buyer}} verkauft',
        pl: 'Sprzedałeś {{vehicle}} za ${{price}} obywatelowi {{buyer}}',
    },
    youSuccessfullyBought: {
        ru: 'Вы купили {{vehicle}} за ${{price}} у {{seller}}',
        ua: 'Ви купили {{vehicle}} за ${{price}} у {{seller}}',
        en: 'You bought {{vehicle}} for ${{price}} from {{seller}}',
        de: 'Sie haben {{vehicle}} für ${{price}} von {{seller}} gekauft',
        pl: 'Kupiłeś {{vehicle}} za ${{price}} od {{seller}}',
    },
    declineNotify: {
        ru: '{{buyer}} отказался от вашего предложения',
        ua: '{{buyer}} відмовився від вашої пропозиції',
        en: '{{buyer}} declined your offer',
        de: '{{buyer}} hat Ihr Angebot abgelehnt',
        pl: '{{buyer}} odrzucił twoją ofertę',
    },
    offerVehicle: {
        ru: 'Предлагает вам сделку по продаже Т/С',
        ua: 'Пропонує вам угоду з продажу Т/З',
        en: 'Offers you a deal to sell the vehicle',
        de: 'Bietet Ihnen ein Geschäft zum Verkauf des Fahrzeugs an',
        pl: 'Oferuje ci umowę na sprzedaż pojazdu',
    },
    waitForSeller: {
        ru: 'Ожидайте ответа продавца',
        ua: 'Очікуйте відповіді продавця',
        en: "Wait for the seller's response",
        de: 'Warten Sie auf die Antwort des Verkäufers',
        pl: 'Czekaj na odpowiedź sprzedawcy',
    },
    waitResponseFromBuyer: {
        ru: 'Ожидайте ответа покупателя',
        ua: 'Очікуйте відповіді покупця',
        en: 'Wait for a response from the buyer',
        de: 'Warten Sie auf eine Antwort des Käufers',
        pl: 'Czekaj na odpowiedź od kupującego',
    },
    timeIsOutForBuyer: {
        ru: 'Время ожидания ответа от покупателя истекло',
        ua: 'Час очікування відповіді від покупця минув',
        en: "The time for the buyer's response has expired",
        de: 'Die Wartezeit auf die Antwort des Käufers ist abgelaufen',
        pl: 'Czas oczekiwania na odpowiedź od kupującego minął',
    },
    buyerDisconnect: {
        ru: 'Покупатель неожиданно исчез, сделка отменена',
        ua: 'Покупець несподівано зник, угоду скасовано',
        en: 'The buyer unexpectedly disappeared, the deal is canceled',
        de: 'Der Käufer ist unerwartet verschwunden, das Geschäft ist storniert',
        pl: 'Kupujący niespodziewanie zniknął, transakcja została anulowana',
    },
    sellerDisconnect: {
        ru: 'Продавец неожиданно исчез, сделка отменена',
        ua: 'Продавець несподівано зник, угоду скасовано',
        en: 'The seller unexpectedly disappeared, the deal is canceled',
        de: 'Der Verkäufer ist unerwartet verschwunden, das Geschäft ist storniert',
        pl: 'Sprzedawca niespodziewanie zniknął, transakcja została anulowana',
    },
    notEnoughMoney: {
        ru: 'Недостаточно средств, сделка отменена',
        ua: 'Недостатньо коштів, угоду скасовано',
        en: 'Not enough funds, the deal is canceled',
        de: 'Nicht genügend Mittel, das Geschäft ist storniert',
        pl: 'Niewystarczające środki, transakcja została anulowana',
    },
    notEnoughMoneyTarget: {
        ru: 'У покупателя недостаточно средств, сделка отменена',
        ua: 'У покупця недостатньо коштів, угоду скасовано',
        en: 'The buyer does not have enough funds, the deal is canceled',
        de: 'Der Käufer hat nicht genügend Mittel, das Geschäft ist storniert',
        pl: 'Kupujący nie ma wystarczających środków, transakcja została anulowana',
    },
    alreadyOffer: {
        ru: 'Сейчас вы не можете ничего предложить',
        ua: 'Зараз ви не можете нічого запропонувати',
        en: "You can't offer anything right now",
        de: 'Du kannst momentan nichts anbieten',
        pl: 'Nie możesz teraz nic zaoferować',
    },
};
