export default {
    carriage: {
        ru: 'Грузовой вагон',
        ua: 'Вантажний вагон',
        en: 'Freight carriage',
        de: 'Güterwagen',
        pl: 'Wagon towarowy',
    },
    openContainer: {
        ru: 'Обыскать контейнер',
        ua: 'Обшукати контейнер',
        en: 'Search the container',
        de: 'Container durchsuchen',
        pl: 'Przeszukaj kontener',
    },
    header: {
        ru: 'Товарный поезд',
        ua: 'Товарний потяг',
        en: 'Freight train',
        de: 'Güterzug',
        pl: 'Pociąg towarowy',
    },
    cutContainer: {
        ru: 'Вскрыть контейнер',
        ua: 'Розкрити контейнер',
        en: 'Cut the container open',
        de: 'Container aufschneiden',
        pl: 'Rozciąć kontener',
    },
    cutBusy: {
        ru: 'Этот контейнер уже вскрывают.',
        ua: 'Цей контейнер уже розкривають.',
        en: 'Somebody is already cutting this container open.',
        de: 'Jemand schneidet diesen Container bereits auf.',
        pl: 'Ktoś już rozcina ten kontener.',
    },
    raidIncoming: {
        ru: '~y~[Товарный поезд] ~w~Встанет через ~y~{{minutes}} мин~w~. Отметка на карте.',
        ua: '~y~[Товарний потяг] ~w~Зупиниться через ~y~{{minutes}} хв~w~. Позначка на карті.',
        en: '~y~[Freight train] ~w~Stops in ~y~{{minutes}} min~w~. It is marked on your map.',
        de: '~y~[Güterzug] ~w~Hält in ~y~{{minutes}} Min~w~. Er ist auf deiner Karte markiert.',
        pl: '~y~[Pociąg towarowy] ~w~Zatrzyma się za ~y~{{minutes}} min~w~. Oznaczenie jest na mapie.',
    },
    noTorch: {
        ru: 'Нужен газовый резак.',
        ua: 'Потрібен газовий різак.',
        en: 'You need a cutting torch.',
        de: 'Du brauchst einen Schneidbrenner.',
        pl: 'Potrzebujesz palnika do cięcia.',
    },
    cutInterrupted: {
        ru: 'Резка прервана.',
        ua: 'Різання перервано.',
        en: 'The cut was interrupted.',
        de: 'Der Schnitt wurde unterbrochen.',
        pl: 'Cięcie zostało przerwane.',
    },
};
