export default {
    carriage: {
        ru: 'Грузовой вагон',
        ua: 'Вантажний вагон',
        en: 'Freight carriage',
        de: 'Güterwagen',
        pl: 'Wagon towarowy',
    },
    openContainer: {
        ru: 'Обыскать контейнер',
        ua: 'Обшукати контейнер',
        en: 'Search the container',
        de: 'Container durchsuchen',
        pl: 'Przeszukaj kontener',
    },
    header: {
        ru: 'Товарный поезд',
        ua: 'Товарний потяг',
        en: 'Freight train',
        de: 'Güterzug',
        pl: 'Pociąg towarowy',
    },
    cutContainer: {
        ru: 'Вскрыть контейнер',
        ua: 'Розкрити контейнер',
        en: 'Cut the container open',
        de: 'Container aufschneiden',
        pl: 'Rozciąć kontener',
    },
    cutBusy: {
        ru: 'Этот контейнер уже вскрывают.',
        ua: 'Цей контейнер уже розкривають.',
        en: 'Somebody is already cutting this container open.',
        de: 'Jemand schneidet diesen Container bereits auf.',
        pl: 'Ktoś już rozcina ten kontener.',
    },
    raidIncoming: {
        ru: 'Товарный поезд встанет через {{minutes}} мин. Отметка на карте.',
        ua: 'Вантажний потяг зупиниться через {{minutes}} хв. Позначка на карті.',
        en: 'The freight train stops in {{minutes}} min. It is marked on your map.',
        de: 'Der Güterzug hält in {{minutes}} Min. Er ist auf deiner Karte markiert.',
        pl: 'Pociąg towarowy zatrzyma się za {{minutes}} min. Oznaczenie jest na mapie.',
    },
    cutInterrupted: {
        ru: 'Резка прервана.',
        ua: 'Різання перервано.',
        en: 'The cut was interrupted.',
        de: 'Der Schnitt wurde unterbrochen.',
        pl: 'Cięcie zostało przerwane.',
    },
};
