export default {
    startMessage: {
        ru: '~r~ВНИМАНИЕ! Запущено мероприятие под названием {{name}}. Чтобы участвовать в нём введите /gomp',
        ua: '~r~УВАГА! Запущено захід під назвою {{name}}. Щоб взяти участь у ньому, введіть /gomp',
        en: '~r~ATTENTION! An event called {{name}} has started. To participate, enter /gomp',
        de: '~r~ACHTUNG! Eine Veranstaltung namens {{name}} wurde gestartet. Um teilzunehmen, gib /gomp ein',
        pl: '~r~UWAGA! Rozpoczęto wydarzenie o nazwie {{name}}. Aby wziąć udział, wpisz /gomp',
       zh:'~r~注意！活动{{name}}已开启,输入 /gomp 加入',
    },
    playerJoinMessage: {
        ru: 'Вы присоединились к мероприятию под названием {{name}}, ожидайте указаний администрации. Чтобы покинуть /leavemp',
        ua: 'Ви приєдналися до заходу під назвою {{name}}, очікуйте вказівок адміністрації. Щоб покинути /leavemp',
        en: 'You have joined the event called {{name}}, await further instructions from the administration. To leave, enter /leavemp',
        de: 'Du hast dich der Veranstaltung namens {{name}} angeschlossen. Warte auf Anweisungen der Administration. Um zu verlassen, gib /leavemp ein',
        pl: 'Dołączyłeś do wydarzenia o nazwie {{name}}, czekaj na instrukcje administracji. Aby opuścić, wpisz /leavemp',
       zh:'您已加入{{name}}活动,请管理部门的进一步指示.推出请输入/leavemp',
    },
    noActiveEvent: {
        ru: 'Нет активного мероприятия',
        ua: 'Немає активного заходу',
        en: 'No active event',
        de: 'Kein aktives Ereignis',
        pl: 'Brak aktywnego wydarzenia',
       zh:'暂无活动',
    },
    endMessage: {
        ru: '~r~Мероприятие {{name}} окончено. Спасибо всем за участие!',
        ua: '~r~Захід {{name}} завершено. Дякуємо всім за участь!',
        en: '~r~The event {{name}} has ended. Thank you all for participating!',
        de: '~r~Die Veranstaltung {{name}} ist beendet. Vielen Dank an alle Teilnehmer!',
        pl: '~r~Wydarzenie {{name}} zakończone. Dziękujemy wszystkim za udział!',
       zh:'~R~活动{{name}}已结束.谢谢参与!',
    },
    youStartedMp: {
        ru: 'Вы запустили мероприятие под названием {{name}}. Чтобы закончить его /endmp',
        ua: 'Ви запустили захід під назвою {{name}}. Щоб завершити його /endmp',
        en: 'You have started an event called {{name}}. To end it, enter /endmp',
        de: 'Du hast eine Veranstaltung namens {{name}} gestartet. Um sie zu beenden, gib /endmp ein',
        pl: 'Rozpocząłeś wydarzenie o nazwie {{name}}. Aby je zakończyć, wpisz /endmp',
       zh:'已开启{{name}}活动,输入 /endmp 结束活动',
    },
    activeJob: {
        ru: 'Вы не можете войти на мероприятие, находясь в работе',
        ua: 'Ви не можете увійти на захід, перебуваючи на роботі',
        en: 'You cannot join the event while on a job',
        de: 'Du kannst nicht an der Veranstaltung teilnehmen, während du arbeitest',
        pl: 'Nie możesz dołączyć do wydarzenia, będąc w pracy',
       zh:'你不能在工作期间加入活动',
    },
    youJustCant: {
        ru: 'Абобус совсем?',
        ua: 'Абобус зовсім?',
        en: 'Are you completely Abobus?',
        de: 'Bist du völlig Abobus?',
        pl: 'Jesteś całkiem Abobus?',
       zh:'你完全是阿波斯人吗?',
    },
    youDead: {
        ru: 'Вы умерли на мероприятии, и попадаете в обычный мир',
        ua: 'Ви померли на заході і повертаєтеся у звичайний світ',
        en: 'You died during the event and are returning to the normal world',
        de: 'Du bist während der Veranstaltung gestorben und kehrst in die normale Welt zurück',
        pl: 'Zginąłeś podczas wydarzenia i wracasz do normalnego świata',
       zh:'你在活动中死亡,你已被送回自由城',
    },
    youCant: {
        ru: 'Вы уже не можете участвовать в мероприятии',
        ua: 'Ви більше не можете брати участь у заході',
        en: 'You can no longer participate in the event',
        de: 'Du kannst nicht mehr an der Veranstaltung teilnehmen',
        pl: 'Nie możesz już brać udziału w wydarzeniu',
       zh:'你无法再参与活动',
    },
};
