export default {
    startMessage: {
        ru: '~r~ВНИМАНИЕ! Запущено мероприятие под названием {{name}}. Чтобы участвовать в нём введите /gomp (доступно для входа {{minutes}} мин.)',
        ua: '~r~УВАГА! Запущено захід під назвою {{name}}. Щоб взяти участь, введіть /gomp (доступно для входу {{minutes}} хв.)',
        en: '~r~ATTENTION! An event called {{name}} has started. To participate, enter /gomp (joining open for {{minutes}} min.)',
        de: '~r~ACHTUNG! Ein Event namens {{name}} hat begonnen. Um teilzunehmen, gib /gomp ein (Beitritt offen für {{minutes}} Min.)',
        pl: '~r~UWAGA! Rozpoczęto wydarzenie o nazwie {{name}}. Aby wziąć udział, wpisz /gomp (dołączanie otwarte przez {{minutes}} min.)',
       zh:'~r~注意！活动{{name}}已开启,输入 /gomp 加入(开放加入{{minutes}}分钟)',
    },
    playerJoinMessage: {
        ru: 'Вы присоединились к мероприятию под названием {{name}}, ожидайте указаний администрации. Чтобы покинуть /leavemp',
        ua: 'Ви приєдналися до заходу під назвою {{name}}, очікуйте вказівок адміністрації. Щоб покинути /leavemp',
        en: 'You have joined the event called {{name}}, await further instructions from the administration. To leave, enter /leavemp',
        de: 'Du hast am Event {{name}} teilgenommen. Warte auf weitere Anweisungen der Administration. Um das Event zu verlassen, gib /leavemp ein',
        pl: 'Dołączyłeś do wydarzenia o nazwie {{name}}, czekaj na instrukcje administracji. Aby opuścić, wpisz /leavemp',
       zh:'您已加入{{name}}活动,请管理部门的进一步指示.推出请输入/leavemp',
    },
    noActiveEvent: {
        ru: 'Нет активного мероприятия',
        ua: 'Немає активного заходу',
        en: 'No active event',
        de: 'Kein aktives Event vorhanden',
        pl: 'Brak aktywnego wydarzenia',
       zh:'暂无活动',
    },
    endMessage: {
        ru: '~r~Мероприятие {{name}} окончено. Спасибо всем за участие!',
        ua: '~r~Захід {{name}} завершено. Дякуємо всім за участь!',
        en: '~r~The event {{name}} has ended. Thank you all for participating!',
        de: '~r~Das Event {{name}} ist beendet. Vielen Dank an alle für die Teilnahme!',
        pl: '~r~Wydarzenie {{name}} zakończone. Dziękujemy wszystkim za udział!',
       zh:'~R~活动{{name}}已结束.谢谢参与!',
    },
    youStartedMp: {
        ru: 'Вы запустили мероприятие под названием {{name}}. Чтобы закончить его /endmp',
        ua: 'Ви запустили захід під назвою {{name}}. Щоб завершити його /endmp',
        en: 'You have started an event called {{name}}. To end it, enter /endmp',
        de: 'Du hast ein Event namens {{name}} gestartet. Um es zu beenden, gib /endmp ein',
        pl: 'Rozpocząłeś wydarzenie o nazwie {{name}}. Aby je zakończyć, wpisz /endmp',
       zh:'已开启{{name}}活动,输入 /endmp 结束活动',
    },
    activeJob: {
        ru: 'Вы не можете войти на мероприятие, находясь в работе',
        ua: 'Ви не можете увійти на захід, перебуваючи на роботі',
        en: 'You cannot join the event while on a job',
        de: 'Du kannst dem Event nicht beitreten, solange du arbeitest',
        pl: 'Nie możesz dołączyć do wydarzenia, będąc w pracy',
       zh:'你不能在工作期间加入活动',
    },
    youJustCant: {
        ru: 'Абобус совсем?',
        ua: 'Абобус зовсім?',
        en: 'Are you completely Abobus?',
        de: 'Bist du komplett abobus?',
        pl: 'Jesteś całkiem Abobus?',
       zh:'你完全是阿波斯人吗?',
    },
    youDead: {
        ru: 'Вы умерли на мероприятии, и попадаете в обычный мир',
        ua: 'Ви померли на заході і повертаєтеся у звичайний світ',
        en: 'You died during the event and are returning to the normal world',
        de: 'Du bist während des Events gestorben und kehrst nun in die normale Welt zurück',
        pl: 'Zginąłeś podczas wydarzenia i wracasz do normalnego świata',
       zh:'你在活动中死亡,你已被送回自由城',
    },
    youCant: {
        ru: 'Вы уже не можете участвовать в мероприятии',
        ua: 'Ви більше не можете брати участь у заході',
        en: 'You can no longer participate in the event',
        de: 'Du kannst nicht mehr am Event teilnehmen',
        pl: 'Nie możesz już brać udziału w wydarzeniu',
       zh:'你无法再参与活动',
    },
    targetNotInMp: {
        ru: 'Игрок не находится на мероприятии',
        ua: 'Гравець не перебуває на заході',
        en: 'Player is not on the event',
        de: 'Der Spieler nimmt nicht am Event teil',
        pl: 'Gracz nie znajduje się na wydarzeniu',
       zh:'该玩家不在活动中',
    },
    resetDone: {
        ru: 'Состояние мероприятия для {{name}} сброшено',
        ua: 'Стан заходу для {{name}} скинуто',
        en: 'Event state for {{name}} has been reset',
        de: 'Der Event-Status für {{name}} wurde zurückgesetzt',
        pl: 'Stan wydarzenia dla {{name}} został zresetowany',
       zh:'已重置{{name}}的活动状态',
    },
    mpCreated: {
        ru: 'Мероприятие {{name}} создано. Используйте /startmp чтобы открыть его для игроков, /endmp - чтобы закрыть',
        ua: 'Захід {{name}} створено. Використовуйте /startmp, щоб відкрити його для гравців, /endmp - щоб закрити',
        en: 'Event {{name}} created. Use /startmp to open it for players, /endmp to close',
        de: 'Event {{name}} wurde erstellt. Nutze /startmp, um es für Spieler zu öffnen, /endmp zum Beenden',
        pl: 'Wydarzenie {{name}} utworzone. Użyj /startmp, aby otworzyć je dla graczy, /endmp - aby zakończyć',
       zh:'活动{{name}}已创建.使用 /startmp 向玩家开放,/endmp 结束',
    },
    alreadyStarted: {
        ru: 'Мероприятие уже запущено',
        ua: 'Захід вже запущено',
        en: 'Event is already running',
        de: 'Das Event läuft bereits',
        pl: 'Wydarzenie już zostało uruchomione',
       zh:'活动已经开始',
    },
    notStartedYet: {
        ru: 'Мероприятие ещё не открыто для участников',
        ua: 'Захід ще не відкрито для учасників',
        en: 'Event is not yet open for participants',
        de: 'Das Event ist noch nicht für Teilnehmer geöffnet',
        pl: 'Wydarzenie nie jest jeszcze otwarte dla uczestników',
       zh:'活动尚未对参与者开放',
    },
    joinWindowClosed: {
        ru: 'Время на вход в мероприятие истекло',
        ua: 'Час на вхід у захід вичерпано',
        en: 'The window to join the event has closed',
        de: 'Das Zeitfenster zum Beitritt ist abgelaufen',
        pl: 'Czas na dołączenie do wydarzenia minął',
       zh:'加入活动的时间已结束',
    },
};
