export default {
    startMessage: {
        ru: '~r~ВНИМАНИЕ! Запущено мероприятие под названием {{name}}. Чтобы участвовать в нём введите /gomp',
        ua: '~r~УВАГА! Запущено захід під назвою {{name}}. Щоб взяти участь у ньому, введіть /gomp',
        en: '~r~ATTENTION! An event called {{name}} has started. To participate, enter /gomp',
        de: '~r~ACHTUNG! Eine Veranstaltung namens {{name}} wurde gestartet. Um teilzunehmen, geben Sie /gomp ein',
        pl: '~r~UWAGA! Rozpoczęto wydarzenie o nazwie {{name}}. Aby wziąć udział, wpisz /gomp',
    },
    playerJoinMessage: {
        ru: 'Вы присоединились к мероприятию под названием {{name}}, ожидайте указаний администрации. Чтобы покинуть /leavemp',
        ua: 'Ви приєдналися до заходу під назвою {{name}}, очікуйте вказівок адміністрації. Щоб покинути /leavemp',
        en: 'You have joined the event called {{name}}, await further instructions from the administration. To leave, enter /leavemp',
        de: 'Sie haben sich der Veranstaltung namens {{name}} angeschlossen, warten Sie auf Anweisungen der Verwaltung. Um zu verlassen, geben Sie /leavemp ein',
        pl: 'Dołączyłeś do wydarzenia o nazwie {{name}}, czekaj na instrukcje administracji. Aby opuścić, wpisz /leavemp',
    },
    noActiveEvent: {
        ru: 'Нет активного мероприятия',
        ua: 'Немає активного заходу',
        en: 'No active event',
        de: 'Kein aktives Ereignis',
        pl: 'Brak aktywnego wydarzenia',
    },
    endMessage: {
        ru: '~r~Мероприятие {{name}} окончено. Спасибо всем за участие!',
        ua: '~r~Захід {{name}} завершено. Дякуємо всім за участь!',
        en: '~r~The event {{name}} has ended. Thank you all for participating!',
        de: '~r~Die Veranstaltung {{name}} ist beendet. Vielen Dank an alle Teilnehmer!',
        pl: '~r~Wydarzenie {{name}} zakończone. Dziękujemy wszystkim za udział!',
    },
    youStartedMp: {
        ru: 'Вы запустили мероприятие под названием {{name}}. Чтобы закончить его /endmp',
        ua: 'Ви запустили захід під назвою {{name}}. Щоб завершити його /endmp',
        en: 'You have started an event called {{name}}. To end it, enter /endmp',
        de: 'Sie haben eine Veranstaltung namens {{name}} gestartet. Um sie zu beenden, geben Sie /endmp ein',
        pl: 'Rozpocząłeś wydarzenie o nazwie {{name}}. Aby je zakończyć, wpisz /endmp',
    },
    activeJob: {
        ru: 'Вы не можете войти на мероприятие, находясь в работе',
        ua: 'Ви не можете увійти на захід, перебуваючи на роботі',
        en: 'You cannot join the event while on a job',
        de: 'Sie können nicht an der Veranstaltung teilnehmen, während Sie arbeiten',
        pl: 'Nie możesz dołączyć do wydarzenia, będąc w pracy',
    },
    youJustCant: {
        ru: 'Абобус совсем?',
        ua: 'Абобус зовсім?',
        en: 'Are you completely Abobus?',
        de: 'Bist du völlig Abobus?',
        pl: 'Jesteś całkiem Abobus?',
    },
    youDead: {
        ru: 'Вы умерли на мероприятии, и попадаете в обычный мир',
        ua: 'Ви померли на заході і повертаєтеся у звичайний світ',
        en: 'You died during the event and are returning to the normal world',
        de: 'Sie sind während der Veranstaltung gestorben und kehren in die normale Welt zurück',
        pl: 'Zginąłeś podczas wydarzenia i wracasz do normalnego świata',
    },
    youCant: {
        ru: 'Вы уже не можете участвовать в мероприятии',
        ua: 'Ви більше не можете брати участь у заході',
        en: 'You can no longer participate in the event',
        de: 'Sie können nicht mehr an der Veranstaltung teilnehmen',
        pl: 'Nie możesz już brać udziału w wydarzeniu',
    },
};
