export default {
    arrivedMedic: {
        ru: 'Медик прибыл по вашему вызову',
        ua: 'Медик прибув за вашим викликом',
        en: 'The medic has arrived at your call',
        de: 'Der Sanitäter ist bei deinem Standort angekommen',
        pl: 'Medyk przybył na twoje wezwanie',
        zh: '医生接听了你的急救电话',
    },
    acceptedDispatch: {
        ru: '{{name}} принял ваш вызов. Ожидайте.',
        ua: '{{name}} прийняв ваш виклик. Очікуйте.',
        en: '{{name}} accepted your call. Wait.',
        de: '{{name}} hat deinen Anruf angenommen. Warte auf Hilfe.',
        pl: '{{name}} przyjął twoje wezwanie. Czekaj.',
        zh: '医生正在来的路上',
    },
    newDispatch: {
        ru: 'Поступил новый вызов',
        ua: 'Надійшов новий виклик',
        en: 'A new dispatch has arrived',
        de: 'Ein neuer Einsatz ist eingetroffen',
        pl: 'Nadeszło nowe wezwanie',
        zh: '新的报警电话',
    },
    goDispatch: {
        ru: 'Вы приняли вызов. Скорее отправляйтесь на точку',
        ua: 'Ви прийняли виклик. Швидше вирушайте до точки',
        en: 'You accepted the call. Hurry to the point',
        de: 'Du hast den Anruf angenommen. Beeile dich',
        pl: 'Przyjąłeś wezwanie. Śpiesz się do punktu',
        zh: '电话接通了',
    },
    playerDeath: {
        ru: 'Человек по вашему вызову скончался, вызов отменён.',
        ua: 'Людина за вашим викликом померла, виклик скасовано.',
        en: 'The person on your call has died, the call is canceled.',
        de: 'Die Person aus deinem Anruf ist gestorben, der Anruf wird abgebrochen.',
        pl: 'Osoba, do której dzwoniłeś, nie żyje, rozmowa jest anulowana.',
        zh: '通讯故障电话自动取消',
    },
    playerRevived: {
        ru: 'Человек по вашему вызову неожидано воскрес... Случаются же чудеса',
        ua: 'Людина за вашим викликом несподівано воскресла... Чудеса трапляються',
        en: 'The person you called has unexpectedly resurrected... Miracles do happen',
        de: 'Die Person, die du angerufen hast, ist unerwartet wieder auferstanden... Wunder geschehen',
        pl: 'Osoba, którą wezwałeś, niespodziewanie zmartwychwstała... Cuda się zdarzają',
        zh: '一个接到你电话的人意外复活了，真是个奇迹',
    },
    canceled: {
        ru: 'Вызов отменён',
        ua: 'Виклик скасовано',
        en: 'Call canceled',
        de: 'Anruf abgebrochen',
        pl: 'Połączenie anulowane',
        zh: '通话取消',
    },
    medicQuit: {
        ru: 'Медик который отправлялся к вам пропал безвести, к вам будет направленно другого медика.',
        ua: 'Медик, який вирушав до вас, зник безвісти, до вас буде направлено іншого медика.',
        en: 'The medic who was going to you has disappeared, another medic will be sent to you.',
        de: 'Der Sanitäter, der zu dir unterwegs war, ist spurlos verschwunden, ein anderer Sanitäter wird zu dir geschickt.',
        pl: 'Lekarz, który jechał do ciebie, zniknął, do ciebie zostanie wysłany inny lekarz.',
        zh: '医生取消了你的急救电话，将为您重新派遣',
    },
    playerReanimated: {
        ru: 'Человек по вашему вызову был реанимирован, вызов отменён.',
        ua: 'Людина за вашим викликом була реанімована, виклик скасовано.',
        en: 'The person on your call was reanimated, the call is canceled.',
        de: 'Die Person auf deinem Anruf wurde reanimiert, der Anruf wird abgebrochen.',
        pl: 'Osoba, do której dzwoniłeś, została reanimowana, rozmowa jest anulowana.',
        zh: '和你打电话的人改名了，通话自动挂断',
    },

    youReanimated: {
        ru: 'Вы реанимировали человека по вызову, ваша награда ${{reward}}',
        ua: 'Ви реанімували людину за викликом, ваша нагорода ${{reward}}',
        en: 'You reanimated a person on the call, your reward is ${{reward}}',
        de: 'Du hast eine Person auf dem Anruf reanimiert, Ihre Belohnung beträgt ${{reward}}',
        pl: 'Ożywiłeś osobę na połączeniu, twoja nagroda to ${{reward}}',
        zh: '你复活了一个人，你的奖励是',
    },
    leaveColshape: {
        ru: 'Человек по вызову покинул зону вызова и вызов был отменён.',
        ua: 'Людина за викликом покинула зону виклику, і виклик було скасовано.',
        en: 'The person from the call left the call zone, and the call was canceled.',
        de: 'Die Person vom Einsatz hat die Einsatzzone verlassen, der Einsatz wurde abgebrochen.',
        pl: 'Osoba wezwana opuściła strefę wezwania, wezwanie zostało anulowane.',
    },

    //
    policeQuit: {
        ru: 'Полицейский, который отправлялся к вам, пропал без вести, к вам будет направлен другой полицейский.',
        ua: 'Поліцейський, який прямував до вас, зник безвісти, до вас буде направлений інший поліцейський.',
        en: 'The police officer who was heading to you has gone missing; another officer will be dispatched to you.',
        de: 'Der Polizist, der zu dir unterwegs war, ist verschwunden. Ein anderer Polizist wird zu dir geschickt.',
        pl: 'Policjant, który zmierzał do ciebie, zaginął. Zostanie wysłany inny policjant.',
    },
    playerDeathPolice: {
        ru: 'Человек по вашему вызову погиб, вызов отменён.',
        ua: 'Людина за вашим викликом загинула, виклик скасовано.',
        en: 'The person from your call has died, the call has been canceled.',
        de: 'Die Person, die du gemeldet hast, ist verstorben. Der Einsatz wurde abgebrochen.',
        pl: 'Osoba wezwana przez ciebie zmarła, wezwanie zostało anulowane.',
    },
    arrivedPolice: {
        ru: 'Полицейский прибыл по вашему вызову',
        ua: 'Поліцейський прибув за вашим викликом',
        en: 'The police officer has arrived at your call',
        de: 'Der Polizist ist an deinem Militärpass eingetroffen',
        pl: 'Policjant przybył na twoje wezwanie',
    },
};
