export const server = {
    notifyHeader: {
        ru: 'Автобусник',
        ua: 'Водій автобуса',
        en: 'Bus Driver',
        de: 'Busfahrer',
        pl: 'Kierowca autobusu',
    },
    youSuccessfulyDeployed: {
        ru: 'Вы успешно устроились',
        ua: 'Ви успішно працевлаштувались',
        en: 'You have successfully been employed',
        de: 'Sie wurden erfolgreich eingestellt',
        pl: 'Pomyślnie zatrudniłeś się',
    },
    youSuccessfullyDismissed: {
        ru: 'Вы успешно уволились',
        ua: 'Ви успішно звільнились',
        en: 'You have successfully resigned',
        de: 'Sie haben erfolgreich gekündigt',
        pl: 'Pomyślnie zrezygnowałeś',
    },
    youGotSalary: {
        ru: 'Вы получили зарплату: ${{salary}}',
        ua: 'Ви отримали зарплату: ${{salary}}',
        en: 'You received a salary: ${{salary}}',
        de: 'Sie haben ein Gehalt erhalten: ${{salary}}',
        pl: 'Otrzymałeś wynagrodzenie: ${{salary}}',
    },
    returnToVehicle: {
        ru: 'Если вы не вернётесь в автобус за 1 минуту вы будете уволены',
        ua: 'Якщо ви не повернетесь до автобуса за 1 хвилину, вас звільнять',
        en: 'If you do not return to the bus within 1 minute, you will be fired',
        de: 'Wenn Sie nicht innerhalb von 1 Minute zum Bus zurückkehren, werden Sie entlassen',
        pl: 'Jeśli nie wrócisz do autobusu w ciągu 1 minuty, zostaniesz zwolniony',
    },
    youBeenDismissed: {
        ru: 'Вы были уволены за прогул',
        ua: 'Вас звільнено за прогул',
        en: 'You have been dismissed for skipping work',
        de: 'Sie wurden entlassen, weil Sie nicht zur Arbeit erschienen sind',
        pl: 'Zostałeś zwolniony za nieobecność w pracy',
    },
    youReturnedToBus: {
        ru: 'Вы вернулись в автобус',
        ua: 'Ви повернулися до автобуса',
        en: 'You returned to the bus',
        de: 'Sie sind zum Bus zurückgekehrt',
        pl: 'Wróciłeś do autobusu',
    },
    youPaidTheFare: {
        ru: 'Вы заплатили ${{rideFare}} за проезд.',
        ua: 'Ви заплатили ${{rideFare}} за проїзд.',
        en: 'You paid ${{rideFare}} for the fare.',
        de: 'Sie haben ${{rideFare}} für die Fahrkarte bezahlt.',
        pl: 'Zapłaciłeś ${{rideFare}} za przejazd.',
    },
    youGotFare: {
        ru: 'Вам заплатили ${{rideFare}} за проезд.',
        ua: 'Вам заплатили ${{rideFare}} за проїзд.',
        en: 'You received ${{rideFare}} for the fare.',
        de: 'Sie haben ${{rideFare}} für die Fahrkarte erhalten.',
        pl: 'Otrzymałeś ${{rideFare}} za przejazd.',
    },
    notEnoughCash: {
        ru: 'У вас недостаточно денег для оплаты проезда.',
        ua: 'У вас недостатньо грошей для оплати проїзду.',
        en: 'You do not have enough money to pay for the fare.',
        de: 'Sie haben nicht genug Geld, um die Fahrkarte zu bezahlen.',
        pl: 'Nie masz wystarczająco pieniędzy, żeby zapłacić za przejazd.',
    },
    youCantSeatToThisBus: {
        ru: 'Вы не можете сесть в этот автобус',
        ua: 'Ви не можете сісти в цей автобус',
        en: 'You cannot board this bus.',
        de: 'Sie können nicht in diesen Bus einsteigen.',
        pl: 'Nie możesz wsiąść do tego autobusu.',
    },
    // client
    wait: {
        ru: 'Подождите {{time}} секунд',
        ua: 'Зачекайте {{time}} секунд',
        en: 'Please wait {{time}} seconds',
        de: 'Bitte warten Sie {{time}} Sekunden',
        pl: 'Proszę czekać {{time}} sekundy',
    },
    returnToBusStop: {
        ru: 'Вернитесь на автобусную остановку',
        ua: 'Поверніться на автобусну зупинку',
        en: 'Return to the bus stop',
        de: 'Zurück zur Bushaltestelle',
        pl: 'Powrót na przystanek autobusowy',
    },
    discordStatus: {
        ru: 'Работает автобусником',
        ua: 'Працює автобусником',
        en: 'Working as a bus driver',
        de: 'Arbeitet als Busfahrer',
        pl: 'Pracuje jako kierowca autobusu',
    },
};
