export default {
    youSuccessfullyBannedCharacter: {
        ru: 'Вы успешно забанили игрока под айди {{id}}',
        ua: 'Ви успішно заблокували гравця з айді {{id}}',
        en: 'You successfully banned the player with ID {{id}}',
        de: 'Du hast den Spieler mit der ID {{id}} erfolgreich gebannt',
        pl: 'Pomyślnie zbanowałeś gracza z ID {{id}}',
    },
    youSuccessfullyUnbannedCharacter: {
        ru: 'Вы успешно разбанили игрока под айди {{id}}',
        ua: 'Ви успішно розблокували гравця з айді {{id}}',
        en: 'You successfully unbanned the player with ID {{id}}',
        de: 'Du hast den Spieler mit der ID {{id}} erfolgreich entbannt',
        pl: 'Pomyślnie odbanowałeś gracza z ID {{id}}',
    },
    accountNotFound: {
        ru: 'Аккаунт не найден',
        ua: 'Акаунт не знайдено',
        en: 'Account not found',
        de: 'Konto nicht gefunden',
        pl: 'Konto nie znaleziono',
    },
    alreadyBanned: {
        ru: 'Этот игрок уже забанен',
        ua: 'Цей гравець вже забанений',
        en: 'This player is already banned',
        de: 'Dieser Spieler ist bereits gebannt',
        pl: 'Ten gracz jest już zbanowany',
    },
    notBanned: {
        ru: 'Этот игрок не забанен',
        ua: 'Цей гравець не забанений',
        en: 'This player is not banned',
        de: 'Dieser Spieler ist nicht gebannt',
        pl: 'Ten gracz nie jest zbanowany',
    },
    typeCorrectPlayerId: {
        ru: 'Укажите корректный ID игрока',
        ua: 'Вкажіть правильний ID гравця',
        en: 'Enter the correct player ID',
        de: 'Gebe die richtige Spieler-ID ein',
        pl: 'Podaj poprawne ID gracza',
    },
    typeCorrectDays: {
        ru: 'Укажите корректное количество дней бана',
        ua: 'Вкажіть правильну кількість днів бана',
        en: 'Enter the correct number of ban days',
        de: 'Gebe die korrekte Anzahl der Bann-Tage ein',
        pl: 'Podaj poprawną liczbę dni bana',
    },
    typeCorrectReason: {
        ru: 'Укажите корректную причину бана',
        ua: 'Вкажіть правильну причину бана',
        en: 'Enter the correct ban reason',
        de: 'Gebe den richtigen Bann-Grund ein',
        pl: 'Podaj poprawny powód bana',
    },
    playersWithThisIdNotFound: {
        ru: 'Игрок с таким ID не найден',
        ua: 'Гравця з таким ID не знайдено',
        en: 'Player with this ID not found',
        de: 'Spieler mit dieser ID nicht gefunden',
        pl: 'Nie znaleziono gracza z tym ID',
    },
    youCantBanYourself: {
        ru: 'С ума тронулся?',
        ua: 'З розуму зійшов?',
        en: 'Have you lost your mind?',
        de: 'Bist du verrückt geworden?',
        pl: 'Postradałeś zmysły?',
    },
    youCantBanAdmin: {
        ru: 'Вы не можете забанить админа уровня повыше',
        ua: 'Ви не можете забанити адміна вищого рівня',
        en: 'You cannot ban a higher-level admin',
        de: 'Du kannst keinen höherstufigen Admin bannen',
        pl: 'Nie możesz zbanować administratora wyższego poziomu',
    },
    justTriedToBanYou: {
        ru: '~r~[ВНИМАНИЕ] Администратор {{admin}} только что попытался тебя забанить!',
        ua: '~r~[УВАГА] Адміністратор {{admin}} щойно спробував тебе забанити!',
        en: '~r~[WARNING] Administrator {{admin}} just tried to ban you!',
        de: '~r~[ACHTUNG] Administrator {{admin}} hat gerade versucht, dich zu bannen!',
        pl: '~r~[UWAGA] Administrator {{admin}} właśnie próbował cię zbanować!',
    },
};
