export default {
    notFound: {
        ru: 'Музыкальный плеер с таким ID не найден',
        ua: 'Музичний плеєр з таким ID не знайдено',
        en: 'No music player with this ID',
        de: 'Kein Musikplayer mit dieser ID gefunden',
        pl: 'Nie znaleziono odtwarzacza muzyki o tym ID',
    },
    noneNearby: {
        ru: 'Рядом нет музыкальных плееров, укажи ID',
        ua: 'Поруч немає музичних плеєрів, вкажи ID',
        en: 'No music player nearby, pass an ID',
        de: 'Kein Musikplayer in der Nähe, gib eine ID an',
        pl: 'W pobliżu nie ma odtwarzacza muzyki, podaj ID',
    },
    noPosition: {
        ru: 'У этого плеера нет позиции в мире',
        ua: 'У цього плеєра немає позиції у світі',
        en: 'This player has no position in the world',
        de: 'Dieser Player hat keine Position in der Welt',
        pl: 'Ten odtwarzacz nie ma pozycji w świecie',
    },
    listEmpty: {
        ru: 'Активных музыкальных плееров нет',
        ua: 'Активних музичних плеєрів немає',
        en: 'There are no active music players',
        de: 'Es gibt keine aktiven Musikplayer',
        pl: 'Nie ma aktywnych odtwarzaczy muzyki',
    },
    alreadyStopped: {
        ru: 'Плеер {{id}} уже остановлен',
        ua: 'Плеєр {{id}} вже зупинено',
        en: 'Player {{id}} is already stopped',
        de: 'Player {{id}} ist bereits gestoppt',
        pl: 'Odtwarzacz {{id}} jest już zatrzymany',
    },
    stopped: {
        ru: 'Плеер {{id}} остановлен',
        ua: 'Плеєр {{id}} зупинено',
        en: 'Player {{id}} stopped',
        de: 'Player {{id}} gestoppt',
        pl: 'Odtwarzacz {{id}} zatrzymany',
    },
    removed: {
        ru: 'Плеер {{id}} удалён',
        ua: 'Плеєр {{id}} видалено',
        en: 'Player {{id}} removed',
        de: 'Player {{id}} entfernt',
        pl: 'Odtwarzacz {{id}} usunięty',
    },
    volumeSet: {
        ru: 'Громкость плеера {{id}} выставлена на {{volume}}%',
        ua: 'Гучність плеєра {{id}} виставлена на {{volume}}%',
        en: 'Player {{id}} volume set to {{volume}}%',
        de: 'Lautstärke von Player {{id}} auf {{volume}}% gesetzt',
        pl: 'Głośność odtwarzacza {{id}} ustawiona na {{volume}}%',
    },
    logsDisabled: {
        ru: 'База логов недоступна',
        ua: 'База логів недоступна',
        en: 'The log database is unavailable',
        de: 'Die Log-Datenbank ist nicht verfügbar',
        pl: 'Baza logów jest niedostępna',
    },
    logsEmpty: {
        ru: 'Записей о включённых треках нет',
        ua: 'Записів про увімкнені треки немає',
        en: 'No played track records found',
        de: 'Keine Einträge über abgespielte Tracks gefunden',
        pl: 'Brak wpisów o odtworzonych utworach',
    },
};
