export default {
    wrongMinutes: {
        'ru': 'Укажите правильное количество минут мута',
        'ua': 'Вкажіть правильну кількість хвилин мута',
        'en': 'Specify the correct number of mute minutes',
        'de': 'Gib die richtige Anzahl der Stummschaltminuten an',
        'pl': 'Podaj prawidłową liczbę minut wyciszenia',
    },
    wrongReason: {
        'ru': 'Укажите корректную причину мута',
        'ua': 'Вкажіть коректну причину мута',
        'en': 'Specify a valid reason for the mute',
        'de': 'Gib einen gültigen Grund für die Stummschaltung an',
        'pl': 'Podaj prawidłowy powód wyciszenia',
    },
    youCantMuteHigherAdmin: {
        'ru': 'Вы не можете дать мут администратору более высокого уровня, чем вы',
        'ua': 'Ви не можете замутити адміністратора вищого рівня, ніж ви',
        'en': 'You cannot mute an admin of a higher level than you',
        'de': 'Du kannst keinen Admin mit einem höheren Level als du stummschalten',
        'pl': 'Nie możesz wyciszyć administratora, który ma wyższy poziom niż ty',
    },
    youCantUnmuteHigherAdmin: {
        'ru': 'Вы не можете снять мут с администратора более высокого уровня, чем вы',
        'ua': 'Ви не можете зняти мут з адміністратора вищого рівня, ніж ви',
        'en': 'You cannot unmute an admin of a higher level than you',
        'de': 'Du kannst die Stummschaltung eines Admins mit einem höheren Level als du nicht aufheben',
        'pl': 'Nie możesz zdjąć wyciszenia z administratora, który ma wyższy poziom niż ty',
    },
    mutedOnlineNotify: {
        'ru': 'Вы замутили игрока {{name}} на {{minutes}} по причине {{reason}}',
        'ua': 'Ви замутили гравця {{name}} на {{minutes}} хвилин через {{reason}}',
        'en': 'You have muted player {{name}} for {{minutes}} minutes for {{reason}}',
        'de': 'Du hast den Spieler {{name}} für {{minutes}} Minuten aus folgendem Grund stummgeschaltet: {{reason}}',
        'pl': 'Uciszyłeś gracza {{name}} na {{minutes}} minut z powodu {{reason}}',
    },
    mutedOfflineNotify: {
        'ru': 'Вы замутили игрока оффлайн {{name}} на {{minutes}} по причине {{reason}}',
        'ua': 'Ви замутили гравця офлайн {{name}} на {{minutes}} хвилин через {{reason}}',
        'en': 'You have muted player {{name}} offline for {{minutes}} minutes for {{reason}}',
        'de': 'Du hast den Spieler {{name}} offline für {{minutes}} Minuten aus folgendem Grund stummgeschaltet: {{reason}}',
        'pl': 'Uciszyłeś gracza {{name}} offline na {{minutes}} minut z powodu {{reason}}',
    },
    voiceMutedOnlineNotify: {
        'ru': 'Вы замутили голос игрока {{name}} на {{minutes}} по причине {{reason}}',
        'ua': 'Ви замутили голос гравця {{name}} на {{minutes}} хвилин через {{reason}}',
        'en': 'You have voice-muted player {{name}} for {{minutes}} minutes for {{reason}}',
        'de': 'Du hast die Stimme des Spielers {{name}} für {{minutes}} Minuten aus folgendem Grund stummgeschaltet: {{reason}}',
        'pl': 'Wyciszyłeś głos gracza {{name}} na {{minutes}} minut z powodu {{reason}}',
    },
    voiceMutedOfflineNotify: {
        'ru': 'Вы замутили голос игрока оффлайн {{name}} на {{minutes}} по причине {{reason}}',
        'ua': 'Ви замутили голос гравця офлайн {{name}} на {{minutes}} хвилин через {{reason}}',
        'en': 'You have voice-muted player {{name}} offline for {{minutes}} minutes for {{reason}}',
        'de': 'Du hast die Stimme des Spielers {{name}} offline für {{minutes}} Minuten aus folgendem Grund stummgeschaltet: {{reason}}',
        'pl': 'Wyciszyłeś głos gracza {{name}} offline na {{minutes}} minut z powodu {{reason}}',
    },
    successUnmuteOnline: {
        'ru': 'Вы размутили игрока {{name}}',
        'ua': 'Ви розмутіли гравця {{name}}',
        'en': 'You have unmuted player {{name}}',
        'de': 'Du hast die Stummschaltung des Spielers {{name}} aufgehoben',
        'pl': 'Odmutowałeś gracza {{name}}',
    },
    successUnmuteOffline: {
        'ru': 'Вы размутили игрока в оффлайне {{name}}',
        'ua': 'Ви розмутіли гравця {{name}} в оффлайні',
        'en': 'You have unmuted player {{name}} offline',
        'de': 'Du hast die Stummschaltung des Spielers {{name}} offline aufgehoben',
        'pl': 'Odmutowałeś gracza {{name}} będącego offline',
    },
    successVoiceUnmuteOnline: {
        'ru': 'Вы сняли голосовой мут с игрока {{name}}',
        'ua': 'Ви зняли голосовий мут з гравця {{name}}',
        'en': 'You have removed the voice mute from player {{name}}',
        'de': 'Du hast den Sprach-Mute des Spielers {{name}} aufgehoben',
        'pl': 'Zdjąłeś mute głosowy z gracza {{name}}',
    },
    successVoiceUnmuteOffline: {
        'ru': 'Вы сняли голосовой мут с игрока оффлайн {{name}}',
        'ua': 'Ви зняли голосовий мут з гравця офлайн {{name}}',
        'en': 'You have removed the voice mute from offline player {{name}}',
        'de': 'Du hast den Sprach-Mute des offline Spielers {{name}} aufgehoben',
        'pl': 'Zdjąłeś mute głosowy z gracza offline {{name}}',
    },
    broadcastMute: {
        'ru': '~r~Администратор {{admin}} замутил чат игроку {{target}} на {{minutes}} минут по причине {{reason}}',
        'ua': '~r~Адміністратор {{admin}} вимкнув чат гравцю {{target}} на {{minutes}} хвилин з причини {{reason}}',
        'en': '~r~Administrator {{admin}} muted player {{target}}\'s chat for {{minutes}} minutes due to {{reason}}',
        'de': '~r~Administrator {{admin}} hat den Chat von Spieler {{target}} für {{minutes}} Minuten wegen {{reason}} stummgeschaltet',
        'pl': '~r~Administrator {{admin}} wyciszył czat gracza {{target}} na {{minutes}} minut z powodu {{reason}}',
    },
};
