export default {
    wrongMinutes: {
        'ru': 'Укажите правильное количество минут мута',
        'ua': 'Вкажіть правильну кількість хвилин мута',
        'en': 'Specify the correct number of mute minutes',
        'de': 'Gib die richtige Anzahl der Stummschaltminuten an',
        'pl': 'Podaj prawidłową liczbę minut wyciszenia',
    },
    wrongReason: {
        'ru': 'Укажите корректную причину мута',
        'ua': 'Вкажіть коректну причину мута',
        'en': 'Specify a valid reason for the mute',
        'de': 'Gib einen gültigen Grund für die Stummschaltung an',
        'pl': 'Podaj prawidłowy powód wyciszenia',
    },
    youCantMuteHigherAdmin: {
        'ru': 'Вы не можете дать мут администратору более высокого уровня, чем вы',
        'ua': 'Ви не можете замутити адміністратора вищого рівня, ніж ви',
        'en': 'You cannot mute an admin of a higher level than you',
        'de': 'Du kannst keinen Admin mit einem höheren Level als dir stummschalten',
        'pl': 'Nie możesz wyciszyć administratora, który ma wyższy poziom niż ty',
    },
    mutedOnlineNotify: {
        'ru': 'Вы замутили игрока {{name}} на {{minutes}} по причине {{reason}}',
        'ua': 'Ви замутили гравця {{name}} на {{minutes}} хвилин через {{reason}}',
        'en': 'You have muted player {{name}} for {{minutes}} minutes for {{reason}}',
        'de': 'Du hast den Spieler {{name}} für {{minutes}} Minuten stummgeschaltet. Grund: {{reason}}',
        'pl': 'Uciszyłeś gracza {{name}} na {{minutes}} minut z powodu {{reason}}',
    },
    successUnmuteOnline: {
        'ru': 'Вы размутили игрока {{name}}',
        'ua': 'Ви розмутіли гравця {{name}}',
        'en': 'You have unmuted player {{name}}',
        'de': 'Du hast die Stummschaltung des Spielers {{name}} aufgehoben',
        'pl': 'Odmutowałeś gracza {{name}}',
    },
    successUnmuteOffline: {
        'ru': 'Вы размутили игрока в оффлайне {{name}}',
        'ua': 'Ви розмутіли гравця {{name}} в оффлайні',
        'en': 'You have unmuted player {{name}} offline',
        'de': 'Du hast die Stummschaltung des Spielers {{name}} im Offline-Modus aufgehoben',
        'pl': 'Odmutowałeś gracza {{name}} będącego offline',
    },
    broadcastMute: {
        'ru': '~r~Администратор {{admin}} замутил чат игроку {{target}} на {{minutes}} минут по причине {{reason}}',
        'ua': '~r~Адміністратор {{admin}} вимкнув чат гравцю {{target}} на {{minutes}} хвилин з причини {{reason}}',
        'en': '~r~Administrator {{admin}} muted player {{target}}\'s chat for {{minutes}} minutes due to {{reason}}',
        'de': '~r~Administrator {{admin}} hat den Chat von Spieler {{target}} für {{minutes}} Minuten stummgeschaltet. Grund: {{reason}}',
        'pl': '~r~Administrator {{admin}} wyciszył czat gracza {{target}} na {{minutes}} minut z powodu {{reason}}',
    },
};