export const server = {
    chat: {
        speaks: {
            ua: 'говорить',
            en: 'speaks',
            ru: 'говорит',
            de: 'spricht',
            pl: 'mówi',
            zh:'说话',
        },
        info: {
            ua: '[Інформація]',
            en: '[Information]',
            ru: '[Информация]',
            de: '[Information]',
            pl: '[Informacja]',
           zh:'[信息]',
        },
        success: {
            ru: 'Удачно',
            ua: 'Успішно',
            en: 'Successful',
            de: 'Erfolgreich',
            pl: 'Z powodzeniem',
            zh:'成功',
        },
        fail: {
            ru: 'Неудачно',
            ua: 'Невдало',
            en: 'Unsuccessful',
            de: 'Fehlgeschlagen',
            pl: 'Nieudany',
           zh:'失败',
        },
        chat: {
            ru: 'Чат',
            ua: 'Чат',
            en: 'Chat',
            de: 'Chat',
            pl: 'Czat',
            zh:'聊天',
        },
        youreMuted: {
            ru: 'Вы замучены',
            ua: 'Вас замовчано',
            en: 'You are muted',
            de: 'Du bist stummgeschaltet',
            pl: 'Jesteś wyciszony',
            zh:'您已静音',
        },
    },
};
