export default {
    dialog1: {
        helloMan: {
            "ru": "Привет! Хочешь поработать дайвером? Можно найти кучу крутых находок, а потом продать их скупщику",
            "ua": "Привіт! Хочеш попрацювати дайвером? Можна знайти купу класних знахідок, а потім продати їх скупнику",
            "en": "Hey! Want to work as a diver? You can find tons of cool stuff and sell it to the dealer later",
            "de": "Hey! Willst du als Taucher arbeiten? Du kannst viele coole Funde machen und sie dann dem Händler verkaufen",
            "pl": "Cześć! Chcesz popracować jako nurek? Możesz znaleźć mnóstwo fajnych rzeczy i sprzedać je handlarzowi",
        },
        go: {
            ru: 'Давай',
            ua: 'Давай',
            en: "Let's go",
            de: 'Los geht’s',
            pl: 'Jasne',
        },
        moreInfo: {
            ru: 'Раскажи больше',
            ua: 'Розкажи більше',
            en: 'Tell me more',
            de: 'Erzähl mir mehr',
            pl: 'Opowiedz więcej',
        },
        no: {
            ru: 'Нет',
            ua: 'Ні',
            en: 'No',
            de: 'Nein',
            pl: 'Nie',
        },
        //
        niceSoStartWork: {
            ru: 'Отлично! Сейчас мы дадим тебе нужное снаряжение и можешь идти в плавание',
            ua: 'Чудово! Зараз ми дамо тобі необхідне спорядження, і можеш вирушати в плавання',
            en: "Great! We'll give you the necessary gear and you can head out to sea",
            de: 'Super! Wir geben dir die nötige Ausrüstung, dann kannst du losschwimmen',
            pl: 'Świetnie! Damy ci potrzebny sprzęt i możesz wypływać',
        },
        ok: {
            ru: 'Хорошо',
            ua: 'Гаразд',
            en: 'Okay',
            de: 'Okay',
            pl: 'Dobrze',
        },
        nevermind: {
            ru: 'Я передумал',
            ua: 'Я передумав',
            en: 'I changed my mind',
            de: 'Ich habe es mir anders überlegt',
            pl: 'Zmieniłem zdanie',
        },
        bye: {
            ru: 'Ну как передумаешь буду ждать тебя здесь, всегда найдется работа для тебя!',
            ua: 'Як передумаєш — я чекатиму тебе тут, для тебе завжди знайдеться робота!',
            en: "If you change your mind, I'll be here — there's always a job for you!",
            de: 'Wenn du es dir anders überlegst, ich warte hier – es gibt immer Arbeit für dich!',
            pl: 'Jak zmienisz zdanie, będę tu czekać — zawsze znajdzie się dla ciebie praca!',
        },
        okayBye: {
            ru: 'Хорошо, пока',
            ua: 'Гаразд, бувай',
            en: 'Okay, bye',
            de: 'Okay, tschüss',
            pl: 'Dobrze, pa',
        },

        //
        info: {
            "ru": "После устройства мы выдаём тебе снаряжение для дайвинга. Ты идёшь плавать на дно морское и искать разные сокровища. Сколько найдёшь — столько и унесёшь с собой. Продать найденное ты можешь у скупщика",
            "ua": "Після влаштування ми видаємо тобі спорядження для дайвінгу. Ти пірнаєш на морське дно та шукаєш різні скарби. Скільки знайдеш — стільки й забереш із собою. Продати знайдене можна у скупника",
            "en": "Once you're hired, we’ll give you diving gear. You'll swim down to the sea floor and search for various treasures. Whatever you find, you can take with you. You can sell what you find to the dealer",
            "de": "Nach der Einstellung geben wir dir Tauchausrüstung. Du tauchst zum Meeresgrund und suchst nach verschiedenen Schätzen. Was du findest, kannst du mitnehmen. Verkaufen kannst du die Funde beim Händler",
            "pl": "Po zatrudnieniu dostaniesz od nas sprzęt do nurkowania. Schodzisz na dno morskie i szukasz różnych skarbów. Ile znajdziesz — tyle zabierzesz ze sobą. Znalezione rzeczy możesz sprzedać handlarzowi",
        },
        getIt: {
            ru: 'Понял',
            ua: 'Зрозуміло',
            en: 'Got it',
            de: 'Verstanden',
            pl: 'Zrozumiałem',
        },

        //
        alreadyJob: {
            ru: 'К сожалению ты уже где-то работаешь, сначала уволься там',
            ua: 'На жаль, ти вже десь працюєш — спершу звільнись там',
            en: "Unfortunately, you're already working somewhere else — quit that job first",
            de: 'Du arbeitest leider schon irgendwo – kündige dort zuerst',
            pl: 'Niestety, już gdzieś pracujesz — najpierw się tam zwolnij',
        },
    },
    dialogLeave: {
        soBye: {
            "ru": "Что, уже наплавался? Ну, в общем, ты собрал {{collected}} предметов. Можешь отнести их к скупщику и продать. Заканчиваешь работу?",
            "ua": "Що, вже наплавався? Ну, загалом, ти зібрав {{collected}} предметів. Можеш віднести їх до скупника й продати. Закінчуєш роботу?",
            "en": "Done swimming already? Well, you’ve collected {{collected}} items. You can take them to the dealer and sell them. Wrapping up?",
            "de": "Schon genug geschwommen? Also, du hast {{collected}} Gegenstände gesammelt. Du kannst sie dem Händler bringen und verkaufen. Hörst du auf?",
            "pl": "Już się napływałeś? No cóż, zebrałeś {{collected}} przedmiotów. Możesz zanieść je do handlarza i sprzedać. Kończysz pracę?",
        },
        soByeNoItems: {
            "ru": "Вроде поплавал, а толку — ничего не нашёл. Ну ладно, бывает. Будешь заканчивать работу?",
            "ua": "Наче поплавав, а толку — нічого не знайшов. Ну нічого, буває. Будеш закінчувати роботу?",
            "en": "Swam around, but didn’t find anything. Oh well, it happens. Ready to wrap up?",
            "de": "Bist zwar geschwommen, aber nichts gefunden. Naja, kommt vor. Willst du aufhören?",
            "pl": "Niby popływałeś, ale nic nie znalazłeś. No cóż, bywa. Kończysz pracę?",
        },
        yes: {
            ru: 'Да',
            ua: 'Так',
            en: 'Yes',
            de: 'Ja',
            pl: 'Tak',
        },
        no: {
            ru: 'Передумал',
            ua: 'Передумав',
            en: 'Changed my mind',
            de: 'Ich habe es mir anders überlegt',
            pl: 'Zmieniłem zdanie',
        },
        okayBye: {
            ru: 'Хорошо, ждем тебя снова',
            ua: 'Гаразд, чекаємо тебе знову',
            en: "Alright, we'll be waiting for you again",
            de: 'Okay, wir warten wieder auf dich',
            pl: 'Dobrze, będziemy na ciebie czekać',
        },
        bye: {
            ru: 'Пока',
            ua: 'Бувай',
            en: 'Bye',
            de: 'Tschüss',
            pl: 'Pa',
        },
    },
    dialogCantBecauseLevel: {
        helloAndBye: {
            ru: 'Привет, извини но работа дайвером доступна только с {{level}} уровня, возвращайся как получишь его!',
            ua: 'Привіт, вибач, але робота дайвером доступна тільки з {{level}} рівня. Повертайся, як отримаєш його!',
            en: 'Hey, sorry but the diver job is only available from level {{level}}. Come back once you reach it!',
            de: 'Hey, sorry, aber der Job als Taucher ist erst ab Stufe {{level}} verfügbar. Komm zurück, wenn du sie erreicht hast!',
            pl: 'Cześć, przepraszam, ale praca nurka dostępna jest dopiero od poziomu {{level}}. Wróć, gdy go osiągniesz!',
        },
        ok: {
            ru: 'Хорошо',
            ua: 'Гаразд',
            en: 'Okay',
            de: 'Okay',
            pl: 'Dobrze',
        },
    },
    dialogCantBecauseJobLevel: {
        helloFindOtherPoint: {
            ru: 'Извини но эта точка только для водолазов {{level}} уровня, поищи другую себе по уровню',
            ua: 'Вибач, але ця точка тільки для водолазів {{level}} рівня, пошукай іншу за своїм рівнем',
            en: 'Sorry, but this spot is only for divers of level {{level}}, try to find another one that matches your level',
            de: 'Entschuldige, aber dieser Punkt ist nur für Taucher der Stufe {{level}}, suche dir bitte einen anderen passenden Punkt',
            pl: 'Przepraszam, ale to miejsce jest tylko dla nurków poziomu {{level}}, poszukaj innego odpowiedniego dla siebie',
        },
        okay: {
            ru: 'Хорошо',
            ua: 'Гаразд',
            en: 'Okay',
            de: 'Okay',
            pl: 'Dobrze',
        },
    },
    //
    blip: {
        ru: 'Работа водолаза',
        ua: 'Робота водолаза',
        en: "Diver's Job",
        de: 'Taucherarbeit',
        pl: 'Praca nurka',
    },
    hud: {
        title: {
            ru: 'Работа водолаза',
            ua: 'Робота водолаза',
            en: "Diver's job",
            de: 'Taucherarbeit',
            pl: 'Praca nurka',
        },
        mainTask: {
            ru: 'Отправляйтесь на поиски предметов на дне океана',
            ua: 'Вирушайте на пошуки предметів на дні океану',
            en: 'Embark on a quest for items at the bottom of the ocean',
            de: 'Begeben Sie sich auf die Suche nach Gegenständen auf dem Meeresgrund',
            pl: 'Wyrusz na poszukiwanie przedmiotów na dnie oceanu',
        },
        earned: {
            ru: 'Заработано',
            ua: 'Зароблено',
            en: 'Earned',
            de: 'Verdient',
            pl: 'Zarobione',
        },
        oxygen: {
            ru: 'Запас воздуха',
            ua: 'Запас повiтря',
            en: 'Oxygen supply',
            de: 'Sauerstoffvorrat',
            pl: 'Zapas tlenu',
        },
        items: {
            ru: 'Собрано',
            ua: 'Зiбрано',
            en: 'Collected',
            de: 'Gesammelt',
            pl: 'Zebrano',
        },
    },
    startJobNotify: {
        ru: 'Вы начали работу дайвера. Ныряйте в воду и ищите предметы!',
        ua: 'Ви почали роботу дайвера. Пірнайте у воду та шукайте предмети!',
        en: 'You started the diver job. Dive into the water and look for items!',
        de: 'Du hast den Taucherjob begonnen. Tauche ins Wasser und suche nach Gegenständen!',
        pl: 'Rozpocząłeś pracę nurka. Zanurkuj w wodzie i szukaj przedmiotów!',
    },
    youRecoveredOxygen: {
        ru: 'Вы заправили баллоны воздухом на 100%',
        ua: 'Ви заправили балони повітрям на 100%',
        en: 'You refilled the tanks with air to 100%',
        de: 'Du hast die Flaschen zu 100 % mit Luft aufgefüllt',
        pl: 'Napełniłeś butle powietrzem w 100%',
    },
    youHaveEnoughOxygen: {
        ru: 'У вас и так в балонах полно воздуха',
        ua: 'У вас і так повно повітря в балонах',
        en: 'Your tanks are already full of air',
        de: 'Deine Flaschen sind bereits voll mit Luft',
        pl: 'Twoje butle są już pełne powietrza',
    },
    adminDistanceWarning: {
        ru: "~r~[ADMIN] {{name}} на работе дайвера смог вызвать 'diving.collect' с расстояния {{distance}} м.",
        ua: "~r~[ADMIN] {{name}} на роботі дайвера зміг викликати 'diving.collect' з відстані {{distance}} м.",
        en: "~r~[ADMIN] {{name}} as a diver was able to call 'diving.collect' from a distance of {{distance}} m.",
        de: "~r~[ADMIN] {{name}} konnte als Taucher 'diving.collect' aus einer Entfernung von {{distance}} m aufrufen.",
        pl: "~r~[ADMIN] {{name}} jako nurek był w stanie wywołać 'diving.collect' z odległości {{distance}} m.",
    },
    noJob: {
        ru: 'Вы не работаете водолазом',
        ua: 'Ви не працюєте водолазом',
        en: 'You are not working as a diver',
        de: 'Du arbeitest nicht als Taucher',
        pl: 'Nie pracujesz jako nurek',
    },
    "notEnoughSpaceInInventory": {
        "ru": "Недостаточно места в инвентаре чтобы подобрать это",
        "ua": "Недостатньо місця в інвентарі, щоб підібрати це",
        "en": "Not enough space in inventory to pick this up",
        "de": "Nicht genug Platz im Inventar, um dies aufzuheben",
        "pl": "Za mało miejsca w ekwipunku, aby to podnieść"
    },
    "hintFor1level": {
        "ru": "Подсказка: Тебе нужно плавать по всей поверхности и следить за радаром, на радаре будет отображаться лут, когда ты будешь рядом с ним. Также следи за воздухом в баллонах",
        "ua": "Підказка: Тобі потрібно плавати по всій поверхні й стежити за радаром — на радарі буде відображатися лут, коли ти будеш поруч із ним. Також слідкуй за повітрям у балонах",
        "en": "Hint: You need to swim across the whole surface and keep an eye on the radar — loot will appear on it when you're near. Also, watch the air in your tanks",
        "de": "Tipp: Du musst über die gesamte Oberfläche schwimmen und das Radar im Blick behalten — der Loot wird angezeigt, wenn du in der Nähe bist. Achte auch auf die Luft in deinen Flaschen",
        "pl": "Podpowiedź: Musisz pływać po całej powierzchni i obserwować radar — loot pojawi się, gdy będziesz blisko. Zwracaj też uwagę na powietrze w butlach",
    },
    "hintLowOxygen": {
        "ru": "Воздуха кот наплакал. Хочешь сдохнуть на дне — продолжай, а если нет — быстро заправь баллоны!",
        "ua": "Повітря майже не залишилось. Хочеш здохнути на дні — продовжуй, а якщо ні — швидко заправ балони!",
        "en": "There’s barely any air left. Wanna die at the bottom? Keep going. If not — go refill your tanks, fast!",
        "de": "Kaum noch Luft da. Willst du am Grund verrecken? Dann mach weiter. Wenn nicht – füll schnell die Flaschen auf!",
        "pl": "Prawie nie ma powietrza. Chcesz zdechnąć na dnie? To kontynuuj. Jeśli nie — szybko napełnij butle!",
    },
};
