export default {
    hello: {
        ru: 'Здравствуйте, если вам нужно в больницу пожалуйста поднимитесь по лифту или войдите с другой стороны',
        ua: 'Здравствуйте, якщо вам потрібно до лікарні, будь ласка, підніміться ліфтом або зайдіть з іншого боку',
        en: 'Hello, if you need to get to the hospital, please take the elevator or enter from the other side',
        de: 'Hallo, wenn du ins Krankenhaus musst, nehme den Aufzug oder gehe von der anderen Seite hinein',
        pl: 'Witaj, jeśli potrzebujesz dostać się do szpitala, skorzystaj z windy lub wejdź z drugiej strony',
    },
    ok: {
        ru: 'Спасибо',
        ua: 'Дякую',
        en: 'Thank you',
        de: 'Danke',
        pl: 'Dziękuję',
    },

    selledBloodBags: {
        ru: 'Вы продали {{amount}} мешочков крови за ${{price}}',
    },

    firstDialog: {
        welcomeToEms: {
            ru: 'Приветствую вас в нашем отделении EMS, чем я могу помочь?',
            en: 'Welcome to our EMS department, how can I help?',
            ua: 'Ласкаво просимо до нашого відділення EMS, як я можу допомогти?',
            de: 'Willkommen in unserer EMS-Abteilung, wie kann ich helfen?',
            pl: 'Witamy w naszym dziale EMS, jak mogę pomóc?',
            zh: '欢迎来到我们的EMS部门，有什么我能帮忙的吗？',
        },
        howToJoinToFaction: {
            ru: 'Как я могу присоединиться к вашей фракции?',
            en: 'How can I join your faction?',
            ua: 'Як я можу приєднатися до вашої фракції?',
            de: 'Wie kann ich dem EMS beitreten?',
            pl: 'Jak mogę dołączyć do twojej frakcji?',
            zh: '我怎样才能加入你的阵营',
        },
        aboutLicense: {
            ru: 'О лицензии',
            en: 'About license',
            ua: 'Про ліцензію',
            de: 'Über die Lizenz',
            pl: 'O licencji',
            zh: '许可证',
        },
        callStaff: {
            ru: 'Позвать работника',
            ua: 'Покликати працівника',
            en: 'Call staff',
            de: 'Mitarbeiter rufen',
            pl: 'Wezwać pracownika',
        },
        bye: {
            ru: 'Досвидания',
            en: 'Goodbye',
            ua: 'До побачення',
            de: 'Auf Wiedersehen',
            pl: 'Do widzenia',
            zh: '再见',
        },
        joinToFaction: {
            ru: 'Всё просто, лидер EMS часто проводит набор в персонал фракции EMS, внимательно следите за чатом, и приходите на собеседование',
            en: "It's simple, the EMS leader often recruits for the EMS faction staff, carefully follow the chat, and come for an interview",
            ua: 'Все просто, лідер EMS часто проводить набір до персоналу фракції EMS, уважно слідкуйте за чатом і приходьте на співбесіду',
            de: 'Es ist einfach, der EMS-Leiter rekrutiert oft Personal für die EMS-Fraktion, folge dem Chat genau und kommen Sie zum Vorstellungsgespräch',
            pl: 'To proste, lider EMS często rekrutuje do personelu frakcji EMS, uważnie obserwuj czat i przyjdź na rozmowę kwalifikacyjną',
            zh: '很简单，EMS负责人经常管理一个EMS人员团队，仔细关注聊天内容，然后来参加会议',
        },
        okay: {
            ru: 'Хорошо',
            en: 'Good',
            ua: 'Добре',
            de: 'Gut',
            pl: 'Dobrze',
            zh: '好的',
        },

        //
        licenseInfo: {
            ru: 'Лицензию можно получить у доктора, поищите вокруг себя докторов и спросите у них могут ли они выдавать вам лицензию.',
            en: 'You can get a license from a doctor, look around for doctors and ask them if they can issue you a license.',
            ua: 'Ліцензію можна отримати у лікаря, пошукайте навколо себе лікарів і запитайте у них, чи можуть вони видає вам ліцензію.',
            de: 'Du kannst eine Lizenz von einem Arzt erhalten, suchen Sie nach Ärzten und fragen Sie sie, ob sie Ihnen eine Lizenz ausstellen können.',
            pl: 'Licencję można uzyskać od lekarza, poszukaj lekarzy wokół siebie i zapytaj ich, czy mogą wydać ci licencję.',
            zh: '你可以从医生那里拿到执照，四处看看医生，问他们是否可以给你执照',
        },
        howItGoingBe: {
            ru: 'Как это будет происходить?',
            ua: 'Як це буде відбуватися?',
            en: 'How is it going to happen?',
            de: 'Wie wird das passieren?',
            pl: 'Jak to będzie się działo?',
            zh: '这将如何发生',
        },
        forWhatIt: {
            ru: 'Для чего это?',
            ua: 'Для чого це?',
            en: 'What is it for?',
            de: 'Wofür ist das?',
            pl: 'Do czego to jest?',
            zh: '这是干什么用的？',
        },
        howItGoingBeAnswer: {
            ru: 'Как только вы найдете доктора и скажите ему про получение медецинской лицензии, он осмотрит вас и возьмёт кровь на анализ, после этого вам придётся заплатить ${{money}} для получение этой лицензии',
            ua: 'Як тільки ви знайдете лікаря і скажете йому про отримання медичної ліцензії, він огляне вас і візьме кров на аналіз, після цього вам доведеться заплатити ${{money}} для отримання цієї ліцензії',
            en: 'As soon as you find a doctor and tell him about getting a medical license, he will examine you and take a blood test, after that you will have to pay ${{money}} to get this license',
            de: 'Sobald Sie einen Arzt finden und ihm von der Erlangung einer medizinischen Lizenz erzählen, wird er Sie untersuchen und einen Bluttest durchführen, danach müssen Sie ${{money}} bezahlen, um diese Lizenz zu erhalten',
            pl: 'Gdy tylko znajdziesz lekarza i powiesz mu o uzyskaniu licencji medycznej, przeprowadzi badanie i pobierze krew do analizy, po czym będziesz musiał zapłacić ${{money}} za uzyskanie tej licencji',
        },
        getIt: {
            ru: 'Понял',
            ua: 'Зрозумів',
            en: 'Got it',
            de: 'Verstanden',
            pl: 'Rozumiem',
        },
        forWhatItAnswer: {
            ru: 'Медицинская лицензия нужна во многих местах, и один из примеров - это вступление в нашу фракцию EMS или в полицию',
            ua: 'Медична ліцензія потрібна в багатьох місцях, і один з прикладів - це вступ до нашої фракції EMS або в поліцію',
            en: 'A medical license is needed in many places, and one of the examples is joining our EMS faction or the police',
            de: 'Eine medizinische Lizenz wird an vielen Orten benötigt, und ein Beispiel ist der Beitritt zu unserer EMS-Fraktion oder zur Polizei',
            pl: 'Licencja medyczna jest potrzebna w wielu miejscach, a jednym z przykładów jest dołączenie do naszej frakcji EMS lub policji',
        },
    },

    // Диалог в лаборатории
    labaratoryDialog: {
        helloMessage: {
            ru: 'Привет! Вижу у тебя есть мешочки с кровью, сдай мне их на анализ взамен на награду',
            ua: "Привіт! Бачу у тебе є мішечки з кров'ю, здай мені їх на аналіз в обмін на нагороду",
            en: 'Hello! I see you have blood bags, give them to me for analysis in exchange for a reward',
            de: 'Hallo! Ich sehe, du hast Blutbeutel, gib sie mir zur Analyse im Austausch gegen eine Belohnung',
            pl: 'Cześć! Widzę, że masz woreczki z krwią, oddaj mi je na analizę w zamian za nagrodę',
        },
        okay: {
            ru: 'Хорошо',
            ua: 'Добре',
            en: 'Okay',
            de: 'Okay',
            pl: 'Dobrze',
        },
        later: {
            ru: 'В другой раз',
            ua: 'В інший раз',
            en: 'Another time',
            de: 'Ein anderes Mal',
            pl: 'Innym razem',
        },
        soYouHave: {
            ru: 'Что-ж, у тебя есть {{count}} мешочков с кровью, и твоя награда будет ${{money}}, хорошо?',
            ua: "Що ж, у тебе є {{count}} мішечків з кров'ю, і твоя нагорода буде ${{money}}, добре?",
            en: 'Well, you have {{count}} blood bags, and your reward will be ${{money}}, okay?',
            de: 'Nun, du hast {{count}} Blutbeutel, und deine Belohnung wird ${{money}} sein, okay?',
            pl: 'Cóż, masz {{count}} woreczki z krwią, a twoja nagroda wyniesie ${{money}}, dobrze?',
        },
        great: {
            ru: 'Отлично',
            ua: 'Чудово',
            en: 'Great',
            de: 'Großartig',
            pl: 'Świetnie',
        },
        good: {
            ru: 'Хорошо',
            ua: 'Добре',
            en: 'Good',
            de: 'Gut',
            pl: 'Dobrze',
        },
        anotherTime: {
            ru: 'В другой раз',
            ua: 'В інший раз',
            en: 'Another time',
            de: 'Ein anderes Mal',
            pl: 'Innym razem',
        },
    },
    labaratoryDialog2: {
        helloMessage: {
            ru: 'Привет! у меня ты можешь сдать мешочки с кровью взамен на награду, сейчас у тебя их нет, получить ты и можешь у людей которые готовы сдать кровь',
            ua: "Привіт! у мене ти можеш здати мішечки з кров'ю в обмін на нагороду, зараз у тебе їх немає, отримати іх ти можеш у людей, які готові здати кров",
            en: "Hello! Here you can donate blood bags in exchange for a reward, you don't have any now, you can get them from people who are ready to donate blood",
            de: 'Hallo! Bei mir kannst du Blutbeutel gegen eine Belohnung abgeben, momentan hast du keine, du kannst sie von Leuten bekommen, die bereit sind, Blut zu spenden',
            pl: 'Cześć! U mnie możesz oddać woreczki z krwią w zamian za nagrodę, teraz nie masz żadnych, możesz je zdobyć od ludzi, którzy są gotowi oddać krew',
        },
        okay: {
            ru: 'Хорошо',
            ua: 'Добре',
            en: 'Okay',
            de: 'Okay',
            pl: 'Dobrze',
        },
    },
    labaratoryDialog3: {
        helloMessage: {
            ru: 'Похоже ты не работаешь в EMS, тебе тут не место, это лабаратория',
            ua: 'Схоже, ти не працюєш в EMS, тобі тут не місце, це лабораторія',
            en: "It seems you don't work at EMS, you don't belong here, this is a laboratory",
            de: 'Es scheint, du arbeitest nicht bei EMS, du gehörst hier nicht hin, das ist ein Labor',
            pl: 'Wygląda na to, że nie pracujesz w EMS, nie należysz tutaj, to jest laboratorium',
        },
        okay: {
            ru: 'Хорошо',
            ua: 'Добре',
            en: 'Okay',
            de: 'Okay',
            pl: 'Dobrze',
        },
    },

    // Диалог в хирурга
    surgeonDialog: {
        helloMessage: {
            ru: 'Здравствуйте, вы хотите изменить внешность? Это будет стоить ${{price}}',
            ua: 'Здравствуйте, ви хочете змінити зовнішність? Це коштуватиме ${{price}}',
            en: 'Hello, do you want to change your appearance? It will cost ${{price}}',
            de: 'Hallo, möchten Sie Ihr Aussehen ändern? Das kostet ${{price}}',
            pl: 'Witaj, chcesz zmienić swój wygląd? To będzie kosztować ${{price}}',
        },
        yes: {
            ru: 'Да',
            ua: 'Так',
            en: 'Yes',
            de: 'Ja',
            pl: 'Tak',
        },
        no: {
            ru: 'Нет',
            ua: 'Ні',
            en: 'No',
            de: 'Nein',
            pl: 'Nie',
        },
    },
};
