export default {
    default: {
        yoWorkInterest: {
            ru: 'Йоу, чё как? Интересует работёнка или есть какие то вопросы?',
            ua: 'Йо, як справи? Цікавить робота чи є якісь питання?',
            en: "Yo, what's up? Interested in some work or got any questions?",
            de: "Yo, wie läuft's? Interessiert an einem Job oder hast du Fragen?",
            pl: 'Yo, jak tam? Zainteresowany robotą czy masz jakieś pytania?',
        },
        yeahJob: {
            ru: 'Да, ищу работёнку',
            ua: 'Так, шукаю роботу',
            en: "Yeah, I'm looking for work",
            de: 'Ja, ich suche einen Job',
            pl: 'Tak, szukam roboty',
        },
        questions: {
            ru: 'Можно задать вопрос?',
            ua: 'Можна поставити запитання?',
            en: 'Can I ask a question?',
            de: 'Kann ich eine Frage stellen?',
            pl: 'Czy mogę zadać pytanie?',
        },
        takeFactionVehicle: {
            ru: 'Взять машину',
            ua: 'Взяти машину',
            en: 'Take a vehicle',
            de: 'Fahrzeug nehmen',
            pl: 'Weź pojazd',
        },
        moneyLaundering: {
            ru: 'Отмыв денег',
            ua: 'Відмивання грошей',
            en: 'Money laundering',
            de: 'Geldwäsche',
            pl: 'Pranie pieniędzy',
        },
        noWorkInterest: {
            ru: 'Неа',
            ua: 'Ні',
            en: 'Nope',
            de: 'Nee',
            pl: 'Nie',
        },
        carTheftOrGreen: {
            ru: 'Что-ж, есть задание на автоугон, есть адресок на хату, и также вижу у тебя есть блоки STANK так что можешь поработать курьером, что выберешь?',
            ua: "Отже, є завдання на викрадення авто, є адреса на хату, і також бачу, у тебе є блоки STANK, тож можеш попрацювати кур'єром. Що обереш?",
            en: "Well, there's a car theft task, there's an address worth knocking on, and I see you have STANK blocks, so you can work as a courier. What will you choose?",
            de: 'Also, es gibt einen Autodiebstahlauftrag, eine Adresse für einen Einbruch, und ich sehe, du hast STANK-Blöcke, also kannst du als Kurier arbeiten. Was wählst du?',
            pl: 'Cóż, jest zadanie kradzieży auta, jest adres na chatę, a widzę, że masz bloki STANK, więc możesz pracować jako kurier. Co wybierasz?',
        },
        carTheftInterest: {
            ru: 'Что-ж, могу предложить автоугон или адресок на хату, интересует?',
            ua: 'Отже, можу запропонувати викрадення авто або адресу на хату, цікавить?',
            en: 'Well, I can offer you a car theft or an address worth knocking on. Interested?',
            de: 'Also, ich kann dir einen Autodiebstahl oder eine Adresse für einen Einbruch anbieten. Interessiert?',
            pl: 'Cóż, mogę zaproponować kradzież auta albo adres na chatę. Zainteresowany?',
        },
        yesGo: {
            ru: 'Да, давай',
            ua: 'Так, давай',
            en: "Yes, let's go",
            de: 'Ja, lass uns gehen',
            pl: 'Tak, chodźmy',
        },
        maybeLater: {
            ru: 'Потом как нибудь',
            ua: 'Потім якось',
            en: 'Maybe later',
            de: 'Vielleicht später',
            pl: 'Może później',
        },
        carTheft: {
            ru: 'Автоугон',
            ua: 'Автокрадіжка',
            en: 'Car Theft',
            de: 'Autodiebstahl',
            pl: 'Kradzież samochodu',
        },
        burglary: {
            ru: 'Домушник',
            ua: 'Домушник',
            en: 'Burglary',
            de: 'Einbruch',
            pl: 'Włamanie',
        },
        courierGreen: {
            ru: 'Курьер',
            ua: "Кур'єр",
            en: 'Courier',
            de: 'Kurier',
            pl: 'Kurier',
        },
        youDontHaveGreenBlocks: {
            ru: 'Бро, чтобы работать тебе нужно скрафтить блоки STANK понимаешь?',
            ua: 'Брате, щоб працювати тобі потрібно скрафтити блоки STANK, розумієш?',
            en: 'Dude, you need to craft STANK blocks to work, you know?',
            de: 'Bro, du musst STANK-Blöcke herstellen, um zu arbeiten, verstehst du?',
            pl: 'Gościu, musisz wytworzyć bloki STANK, żeby pracować, rozumiesz?',
        },

        youHaveNotEnoughGreenBlocks: {
            ru: 'Бро, чтобы работать у тебя должно минимум {{quantity}} блоков STANK, смекаешь?',
            ua: 'Брате, щоб працювати у тебе повинно бути мінімум {{quantity}} блоків STANK, розумієш?',
            en: 'Dude, you need at least {{quantity}} STANK blocks to work, get it?',
            de: 'Bro, du brauchst mindestens {{quantity}} STANK-Blöcke, um zu arbeiten, klar?',
            pl: 'Gościu, potrzebujesz co najmniej {{quantity}} bloków STANK, żeby pracować, kapujesz?',
        },
        howToCraft: {
            ru: 'А как скрафтить',
            ua: 'А як скрафтити',
            en: 'How to craft',
            de: 'Wie craftet man',
            pl: 'Jak się craftuje',
            zh: '它是如何工作的',
        },

        asIKnowToCraft: {
            ru: 'Для начала тебе нужно посадить семена STANK, сорвать их, пойти в магазин купить скотч и плёнку, и в меню крафта скрафтить блок STANK',
            ua: 'Для початку тобі потрібно посадити насіння STANK, зірвати їх, піти в магазин купити скотч і плівку, і в меню крафта скрафтити блок STANK',
            en: 'First you need to plant STANK seeds, harvest them, go to the store to buy scotch tape and film, and craft a STANK block in the crafting menu',
            de: 'Zuerst musst du STANK-Samen pflanzen, sie ernten, in den Laden gehen, Klebeband und Folie kaufen und im Crafting-Menü einen STANK-Block craften',
            pl: 'Najpierw musisz zasadzić nasiona STANK, zebrać je, pójść do sklepu kupić taśmę klejącą i folię, a następnie stworzyć blok STANK w menu craftingu',
        },

        stealCarRulesReady: {
            ru: 'Так-с, вообщем тебе нужно угнать машину из локации которую тебе скинет один человечек, дальше нужно угнать либо по тихому либо выбив окно, выбив окно потеряешь половину прибыли. Также за повреждение авто будет штраф учти это. Готов?',
            ua: 'Так-с, загалом тобі потрібно викрасти машину з локації, яку тобі скине один чоловік, далі потрібно викрасти або тихо, або вибивши вікно. Вибивши вікно, втратиш половину прибутку. Також за пошкодження авто буде штраф, врахуй це. Готовий?',
            en: 'Alright, so you need to steal a car from a location that one person will send to you. Then, you have to steal it either quietly or by breaking the window. Breaking the window will cost you half the profit. Also, there will be a penalty for car damage, keep that in mind. Ready?',
            de: 'Also, du musst ein Auto von einem Standort stehlen, den dir jemand schicken wird. Dann musst du es entweder leise oder durch Einschlagen des Fensters stehlen. Beim Einschlagen des Fensters verlierst du die Hälfte des Gewinns. Auch für Schäden am Auto gibt es eine Strafe, beachte das. Bereit?',
            pl: 'Więc, musisz ukraść samochód z lokalizacji, którą poda ci pewna osoba. Następnie musisz go ukraść albo po cichu, albo wybijając szybę. Wybijając szybę, stracisz połowę zysku. Za uszkodzenie auta będzie też kara, weź to pod uwagę. Gotowy?',
        },
        letsGo: {
            ru: 'Погнали',
            ua: 'Погнали',
            en: "Let's go",
            de: "Los geht's",
            pl: 'Ruszajmy',
        },

        deliverGreenReady: {
            ru: 'Что-ж, вижу у тебя есть {{quantity}} блоков STANK можешь поразвозить их по точкам которые тебе скинут и заработать не мало баблишка, готов?',
            ua: 'Що ж, бачу у тебе є {{quantity}} блоків STANK, можеш розвезти їх по точках, які тобі скинуть, і заробити непогані гроші. Готовий?',
            en: 'Well, I see you have {{quantity}} STANK blocks. You can deliver them to the locations sent to you and make some decent cash. Ready?',
            de: 'Nun, ich sehe, du hast {{quantity}} STANK-Blöcke. Du kannst sie an die Orte liefern, die dir geschickt werden, und ordentlich Geld verdienen. Bereit?',
            pl: 'Widzę, że masz {{quantity}} bloków STANK. Możesz je rozwieźć po punktach, które ci podadzą, i zarobić niezłą kasę. Gotowy?',
        },
        ready: {
            ru: 'Готов.',
            ua: 'Готовий.',
            en: 'Ready.',
            de: 'Bereit.',
            pl: 'Gotowy.',
        },

        //
        sureAskQuestions: {
            ru: 'Конечно можешь, какие вопросы тебе интересуют?',
            ua: 'Звичайно можеш, які питання тебе цікавлять?',
            en: 'Of course you can, what questions do you have?',
            de: 'Natürlich kannst du, welche Fragen interessieren dich?',
            pl: 'Oczywiście, możesz, jakie pytania cię interesują?',
        },
        aboutGreenBlocks: {
            ru: 'Расскажи где брать блоки STANK',
            ua: 'Розкажи, де брати блоки STANK',
            en: 'Tell me where to get STANK blocks',
            de: 'Erzähl mir, wo man STANK-Blöcke bekommt',
            pl: 'Powiedz mi, gdzie zdobyć bloki STANK',
        },
        forgetIt: {
            ru: 'Уже никакие, забудь',
            ua: 'Вже ніякі, забудь',
            en: 'Never mind, forget it',
            de: 'Schon gut, vergiss es',
            pl: 'Już żadne, zapomnij',
        },
        craftGreenBlockSteps: {
            ru: 'Для начала тебе нужно посадить семена STANK на ферме, сорвать их, пойти в магазин купить скотч и плёнку, и в меню крафта скрафтить блок STANK',
            ua: 'Для початку тобі потрібно посадити насіння STANK на фермі, зірвати їх, піти в магазин купити скотч і плівку, і в меню крафту скрафтити блок STANK',
            en: 'First, you need to plant STANK seeds on a farm, harvest them, go to the store to buy tape and film, and then craft a STANK block in the crafting menu',
            de: 'Zuerst musst du STANK-Samen auf einer Farm pflanzen, sie ernten, zum Laden gehen, Klebeband und Folie kaufen und dann im Crafting-Menü einen STANK-Block herstellen',
            pl: 'Najpierw musisz zasadzić nasiona STANK na farmie, zebrać je, pójść do sklepu, kupić taśmę i folię, a następnie stworzyć blok STANK w menu craftingu',
        },
        gotIt: {
            ru: 'Понял',
            ua: 'Зрозумів',
            en: 'Got it',
            de: 'Verstanden',
            pl: 'Zrozumiałem',
        },

        alreadyHaveVehicle: {
            ru: 'Бро, за тобой уже числится тачка, хочешь вернуть её и взять другую?',
            ua: 'Бро, за тобою вже числиться тачка, хочеш повернути її і взяти іншу?',
            en: 'Bro, you already have a car checked out, wanna return it and take another one?',
            de: 'Bro, du hast schon ein Auto draußen, willst du es zurückgeben und ein anderes nehmen?',
            pl: 'Bro, masz już wypisany samochód, chcesz go zwrócić i wziąć inny?',
        },
        despawnVehicle: {
            ru: 'Да, верни её',
            ua: 'Так, поверни її',
            en: 'Yeah, return it',
            de: 'Ja, nimm es zurück',
            pl: 'Tak, zwróć go',
        },

        // Атмыв деньги
        noMoneyForLaundry: {
            ru: 'У тебя нет денег для отмыва, как будут возвращайся, буду рад с тобой сотрудничать',
            ua: "У тебе немає грошей для відмивання, як з'являться - повертайся, буду радий співпраці",
            en: "You don't have money for laundering, come back when you do, I'll be happy to work with you",
            de: 'Du hast kein Geld für die Wäsche, komm zurück, wenn du welches hast, ich freue mich auf die Zusammenarbeit',
            pl: 'Nie masz pieniędzy na pranie, wróć, gdy będziesz miał, z przyjemnością będę z tobą współpracować',
        },
        dirtyMoneyOffer: {
            ru: 'У тебя есть ${{quantity}} грязных денег, после отмыва их ты получишь ${{sum}}, устраивает?',
            ua: 'У тебе є ${{quantity}} брудних грошей, після їх відмивання ти отримаєш ${{sum}}, влаштовує?',
            en: "You have ${{quantity}} dirty money, after laundering it you'll get ${{sum}}, does that work for you?",
            de: 'Du hast ${{quantity}} schmutziges Geld, nach dem Waschen erhältst du ${{sum}}, passt das?',
            pl: 'Masz ${{quantity}} brudnych pieniędzy, po ich wypraniu otrzymasz ${{sum}}, pasuje ci to?',
        },
        agreed: {
            ru: 'Устраивает',
            ua: 'Влаштовує',
            en: 'Agreed',
            de: 'Einverstanden',
            pl: 'Zgoda',
        },

        // Война за территорию. Регистр сводки: связной отчитывается и отправляет,
        // а не уговаривает — никаких обращений и шуток.
        goToWar: {
            ru: 'Война за территорию #{{zone}}',
            ua: 'Війна за територію #{{zone}}',
            en: 'Territory war #{{zone}}',
            de: 'Gebietskrieg #{{zone}}',
            pl: 'Wojna o terytorium #{{zone}}',
        },
        warBriefing: {
            ru: 'Территория #{{zone}}. {{attacker}} против {{defender}}. Наших на месте: {{staged}} из {{slots}}. У них: {{enemyStaged}}.',
            ua: 'Територія #{{zone}}. {{attacker}} проти {{defender}}. Наших на місці: {{staged}} з {{slots}}. У них: {{enemyStaged}}.',
            en: 'Territory #{{zone}}. {{attacker}} against {{defender}}. Ours in position: {{staged}} of {{slots}}. Theirs: {{enemyStaged}}.',
            de: 'Gebiet #{{zone}}. {{attacker}} gegen {{defender}}. Unsere in Stellung: {{staged}} von {{slots}}. Ihre: {{enemyStaged}}.',
            pl: 'Terytorium #{{zone}}. {{attacker}} przeciw {{defender}}. Naszych na miejscu: {{staged}} z {{slots}}. Ich: {{enemyStaged}}.',
        },
        warGo: {
            ru: 'Участвовать',
            ua: 'Взяти участь',
            en: 'Take part',
            de: 'Teilnehmen',
            pl: 'Weź udział',
        },
        warLater: {
            ru: 'Не сейчас',
            ua: 'Не зараз',
            en: 'Not now',
            de: 'Nicht jetzt',
            pl: 'Nie teraz',
        },
        warNotInRoster: {
            ru: 'Тебя в состав не взяли. Иди к своим, пусть впишут.',
            ua: 'Тебе до складу не взяли. Іди до своїх, хай впишуть.',
            en: "You're not on the roster. Talk to your people about it.",
            de: 'Du stehst nicht in der Aufstellung. Rede mit deinen Leuten.',
            pl: 'Nie ma cię w składzie. Pogadaj ze swoimi.',
        },
        warNoRoster: {
            ru: 'Состав на бой ещё не выбран. Если у тебя есть право - выбери его в меню фракции, в разделе «Карта».',
            ua: 'Склад на бій ще не обрано. Якщо в тебе є право - обери його в меню фракції, у розділі «Карта».',
            en: "The roster for the battle hasn't been picked yet. If you have the right to, pick it in the faction menu, Map section.",
            de: 'Die Aufstellung für den Kampf steht noch nicht. Wenn du das Recht dazu hast, wähle sie im Fraktionsmenü im Bereich „Karte“.',
            pl: 'Skład na bitwę nie został jeszcze wybrany. Jeśli masz uprawnienia - wybierz go w menu frakcji, w sekcji „Mapa”.',
        },
        warSlotsFull: {
            ru: 'Состав набран. Все {{slots}} уже там.',
            ua: 'Склад набрано. Усі {{slots}} уже там.',
            en: 'Roster is full. All {{slots}} are already in position.',
            de: 'Aufstellung ist voll. Alle {{slots}} sind schon vor Ort.',
            pl: 'Skład zebrany. Wszystkie {{slots}} już na miejscu.',
        },
    },
    noFaction: {
        getLostNow: {
            ru: 'Ты чё вообще здесь забыл, а ну пиздуй отсюда нахуй пока тебя не отпиздили нахуй',
            ua: 'Ти що взагалі тут забув, а ну йди звідси нахуй, поки тебе не відпиздили нахуй',
            en: 'What the hell are you even doing here? Get the fuck out of here before you get your ass kicked!',
            de: 'Was zum Teufel machst du überhaupt hier? Verpiss dich sofort, bevor du aufs Maul bekommst!',
            pl: 'Co ty w ogóle tu robisz? Spierdalaj stąd, zanim cię ktoś wpierdoli!',
        },
        fuckYou: {
            ru: 'Иди нахуй',
            ua: 'Іди нахуй',
            en: 'Fuck you',
            de: 'Fick dich',
            pl: 'Pierdol się',
        },
        okay: {
            ru: 'Ладно ладно',
            ua: 'Гаразд гаразд',
            en: 'Alright, alright',
            de: 'Schon gut, schon gut',
            pl: 'Dobra, dobra',
        },
    },
    alreadyJob: {
        comeBackLater: {
            ru: 'Не могу тебе сейчас что то предложить, прийди позже',
            ua: 'Не можу зараз тобі щось запропонувати, приходь пізніше',
            en: "I can't offer you anything right now, come back later",
            de: 'Ich kann dir gerade nichts anbieten, komm später wieder',
            pl: 'Nie mogę ci teraz nic zaproponować, przyjdź później',
        },
        okay: {
            ru: 'Хорошо',
            ua: 'Добре',
            en: 'Alright',
            de: 'In Ordnung',
            pl: 'Dobrze',
        },
    },
};
