export default {
    default: {
        yoWorkInterest: {
            ru: 'Йоу, чё как? Интересует работёнка или есть какие то вопросы?',
            ua: 'Йо, як справи? Цікавить робота чи є якісь питання?',
            en: "Yo, what's up? Interested in some work or got any questions?",
            de: "Yo, wie läuft's? Interessiert an einem Job oder hast du Fragen?",
            pl: 'Yo, jak tam? Zainteresowany robotą czy masz jakieś pytania?',
        },
        yeahJob: {
            ru: 'Да, ищу работёнку',
            ua: 'Так, шукаю роботу',
            en: "Yeah, I'm looking for work",
            de: 'Ja, ich suche einen Job',
            pl: 'Tak, szukam roboty',
        },
        questions: {
            ru: 'Можно задать вопрос?',
            ua: 'Можна поставити запитання?',
            en: 'Can I ask a question?',
            de: 'Kann ich eine Frage stellen?',
            pl: 'Czy mogę zadać pytanie?',
        },
        moneyLaundering: {
            ru: 'Отмыв денег',
            ua: 'Відмивання грошей',
            en: 'Money laundering',
            de: 'Geldwäsche',
            pl: 'Pranie pieniędzy',
        },
        noWorkInterest: {
            ru: 'Неа',
            ua: 'Ні',
            en: 'Nope',
            de: 'Nee',
            pl: 'Nie',
        },
        carTheftOrGreen: {
            ru: 'Что-ж, есть задание на автоугон и также вижу у тебя есть блоки Green так что можешь поработать курьером, что выберешь?',
            ua: "Отже, є завдання на викрадення авто, і також бачу, у тебе є блоки Green, тож можеш попрацювати кур'єром. Що обереш?",
            en: "Well, there's a car theft task, and I see you have Green blocks, so you can work as a courier. What will you choose?",
            de: 'Also, es gibt einen Autodiebstahlauftrag, und ich sehe, du hast Green-Blöcke, also kannst du als Kurier arbeiten. Was wählst du?',
            pl: 'Cóż, jest zadanie kradzieży auta, a widzę, że masz bloki Green, więc możesz pracować jako kurier. Co wybierasz?',
        },
        carTheftInterest: {
            ru: 'Что-ж, могу тебе предложить только автоугон, интересует?',
            ua: 'Отже, можу запропонувати тобі лише викрадення авто, цікавить?',
            en: 'Well, I can only offer you a car theft. Interested?',
            de: 'Also, ich kann dir nur einen Autodiebstahl anbieten. Interessiert?',
            pl: 'Cóż, mogę ci zaproponować tylko kradzież auta. Zainteresowany?',
        },
        yesGo: {
            ru: 'Да, давай',
            ua: 'Так, давай',
            en: "Yes, let's go",
            de: 'Ja, lass uns gehen',
            pl: 'Tak, chodźmy',
        },
        maybeLater: {
            ru: 'Потом как нибудь',
            ua: 'Потім якось',
            en: 'Maybe later',
            de: 'Vielleicht später',
            pl: 'Może później',
        },
        carTheft: {
            ru: 'Автоугон',
            ua: 'Автокрадіжка',
            en: 'Car Theft',
            de: 'Autodiebstahl',
            pl: 'Kradzież samochodu',
        },
        courierGreen: {
            ru: 'Курьер',
            ua: "Кур'єр",
            en: 'Courier',
            de: 'Kurier',
            pl: 'Kurier',
        },
        youDontHaveGreenBlocks: {
            ru: 'Бро, чтобы работать тебе нужно скрафтить зелёные блоки понимаешь?',
            ua: 'Брате, щоб працювати тобі потрібно скрафтити зелені блоки, розумієш?',
            en: 'Dude, you need to craft green blocks to work, you know?',
            de: 'Bro, du musst grüne Blöcke herstellen, um zu arbeiten, verstehst du?',
            pl: 'Gościu, musisz wytworzyć zielone bloki, żeby pracować, rozumiesz?',
            zh: '老兄，你需要制作绿色积木才能工作，你知道吗？',
        },

        youHaveNotEnoughGreenBlocks: {
            ru: 'Бро, чтобы работать у тебя должно минимум {{quantity}} блоков Green, смекаешь?',
            ua: 'Брате, щоб працювати у тебе повинно бути мінімум {{quantity}} блоків Green, розумієш?',
            en: 'Dude, you need at least {{quantity}} green blocks to work, get it?',
            de: 'Bro, du brauchst mindestens {{quantity}} grüne Blöcke, um zu arbeiten, klar?',
            pl: 'Gościu, potrzebujesz co najmniej {{quantity}} zielonych bloków, żeby pracować, kapujesz?',
            zh: '兄弟，要在你这里工作，至少要有绿块，你知道吗？',
        },
        howToCraft: {
            ru: 'А как скрафтить',
            ua: 'А як скрафтити',
            en: 'How to craft',
            de: 'Wie craftet man',
            pl: 'Jak się craftuje',
            zh: '它是如何工作的',
        },

        asIKnowToCraft: {
            ru: 'Для начала тебе нужно посадить семена Green, сорвать их, пойти в магазин купить скотч и плёнку, и в меню крафта скрафтить блок Green',
            ua: 'Для початку тобі потрібно посадити насіння Green, зірвати їх, піти в магазин купити скотч і плівку, і в меню крафта скрафтити блок Green',
            en: 'First you need to plant Green seeds, harvest them, go to the store to buy scotch tape and film, and craft a Green block in the crafting menu',
            de: 'Zuerst musst du Green-Samen pflanzen, sie ernten, in den Laden gehen, Klebeband und Folie kaufen und im Crafting-Menü einen Green-Block craften',
            pl: 'Najpierw musisz zasadzić nasiona Green, zebrać je, pójść do sklepu kupić taśmę klejącą i folię, a następnie stworzyć blok Green w menu craftingu',
            zh: '首先，你必须种下绿色的种子，把它们撕碎，去商店买一杯苏格兰威士忌和一块瓷砖，然后嫁接在菜单上画出绿色的方块',
        },

        stealCarRulesReady: {
            ru: 'Так-с, вообщем тебе нужно угнать машину из локации которую тебе скинет один человечек, дальше нужно угнать либо по тихому либо выбив окно, выбив окно потеряешь половину прибыли. Также за повреждение авто будет штраф учти это. Готов?',
            ua: 'Так-с, загалом тобі потрібно викрасти машину з локації, яку тобі скине один чоловік, далі потрібно викрасти або тихо, або вибивши вікно. Вибивши вікно, втратиш половину прибутку. Також за пошкодження авто буде штраф, врахуй це. Готовий?',
            en: 'Alright, so you need to steal a car from a location that one person will send to you. Then, you have to steal it either quietly or by breaking the window. Breaking the window will cost you half the profit. Also, there will be a penalty for car damage, keep that in mind. Ready?',
            de: 'Also, du musst ein Auto von einem Standort stehlen, den dir jemand schicken wird. Dann musst du es entweder leise oder durch Einschlagen des Fensters stehlen. Beim Einschlagen des Fensters verlierst du die Hälfte des Gewinns. Auch für Schäden am Auto gibt es eine Strafe, beachte das. Bereit?',
            pl: 'Więc, musisz ukraść samochód z lokalizacji, którą poda ci pewna osoba. Następnie musisz go ukraść albo po cichu, albo wybijając szybę. Wybijając szybę, stracisz połowę zysku. Za uszkodzenie auta będzie też kara, weź to pod uwagę. Gotowy?',
        },
        letsGo: {
            ru: 'Погнали',
            ua: 'Погнали',
            en: "Let's go",
            de: "Los geht's",
            pl: 'Ruszajmy',
        },

        deliverGreenReady: {
            ru: 'Что-ж, вижу у тебя есть {{quantity}} блоков Green можешь поразвозить их по точкам которые тебе скинут и заработать не мало баблишка, готов?',
            ua: 'Що ж, бачу у тебе є {{quantity}} блоків Green, можеш розвезти їх по точках, які тобі скинуть, і заробити непогані гроші. Готовий?',
            en: 'Well, I see you have {{quantity}} Green blocks. You can deliver them to the locations sent to you and make some decent cash. Ready?',
            de: 'Nun, ich sehe, du hast {{quantity}} Green-Blöcke. Du kannst sie an die Orte liefern, die dir geschickt werden, und ordentlich Geld verdienen. Bereit?',
            pl: 'Widzę, że masz {{quantity}} bloków Green. Możesz je rozwieźć po punktach, które ci podadzą, i zarobić niezłą kasę. Gotowy?',
        },
        ready: {
            ru: 'Готов.',
            ua: 'Готовий.',
            en: 'Ready.',
            de: 'Bereit.',
            pl: 'Gotowy.',
        },

        //
        sureAskQuestions: {
            ru: 'Конечно можешь, какие вопросы тебе интересуют?',
            ua: 'Звичайно можеш, які питання тебе цікавлять?',
            en: 'Of course you can, what questions do you have?',
            de: 'Natürlich kannst du, welche Fragen interessieren dich?',
            pl: 'Oczywiście, możesz, jakie pytania cię interesują?',
        },
        aboutGreenBlocks: {
            ru: 'Расскажи где брать блоки Green',
            ua: 'Розкажи, де брати блоки Green',
            en: 'Tell me where to get Green blocks',
            de: 'Erzähl mir, wo man Green-Blöcke bekommt',
            pl: 'Powiedz mi, gdzie zdobyć bloki Green',
        },
        forgetIt: {
            ru: 'Уже никакие, забудь',
            ua: 'Вже ніякі, забудь',
            en: 'Never mind, forget it',
            de: 'Schon gut, vergiss es',
            pl: 'Już żadne, zapomnij',
        },
        craftGreenBlockSteps: {
            ru: 'Для начала тебе нужно посадить семена Green на ферме, сорвать их, пойти в магазин купить скотч и плёнку, и в меню крафта скрафтить блок Green',
            ua: 'Для початку тобі потрібно посадити насіння Green на фермі, зірвати їх, піти в магазин купити скотч і плівку, і в меню крафту скрафтити блок Green',
            en: 'First, you need to plant Green seeds on a farm, harvest them, go to the store to buy tape and film, and then craft a Green block in the crafting menu',
            de: 'Zuerst musst du Green-Samen auf einer Farm pflanzen, sie ernten, zum Laden gehen, Klebeband und Folie kaufen und dann im Crafting-Menü einen Green-Block herstellen',
            pl: 'Najpierw musisz zasadzić nasiona Green na farmie, zebrać je, pójść do sklepu, kupić taśmę i folię, a następnie stworzyć blok Green w menu craftingu',
        },
        gotIt: {
            ru: 'Понял',
            ua: 'Зрозумів',
            en: 'Got it',
            de: 'Verstanden',
            pl: 'Zrozumiałem',
        },

        // Атмыв деньги
        noMoneyForLaundry: {
            ru: 'У тебя нет денег для отмыва, как будут возвращайся, буду рад с тобой сотрудничать',
            ua: "У тебе немає грошей для відмивання, як з'являться — повертайся, буду радий співпраці",
            en: "You don't have money for laundering, come back when you do, I'll be happy to work with you",
            de: 'Du hast kein Geld für die Wäsche, komm zurück, wenn du welches hast, ich freue mich auf die Zusammenarbeit',
            pl: 'Nie masz pieniędzy na pranie, wróć, gdy będziesz miał, z przyjemnością będę z tobą współpracować',
        },
        dirtyMoneyOffer: {
            ru: 'У тебя есть ${{quantity}} грязных денег, после отмыва их ты получишь ${{sum}}, устраивает?',
            ua: 'У тебе є ${{quantity}} брудних грошей, після їх відмивання ти отримаєш ${{sum}}, влаштовує?',
            en: "You have ${{quantity}} dirty money, after laundering it you'll get ${{sum}}, does that work for you?",
            de: 'Du hast ${{quantity}} schmutziges Geld, nach dem Waschen erhältst du ${{sum}}, passt das?',
            pl: 'Masz ${{quantity}} brudnych pieniędzy, po ich wypraniu otrzymasz ${{sum}}, pasuje ci to?',
        },
        agreed: {
            ru: 'Устраивает',
            ua: 'Влаштовує',
            en: 'Agreed',
            de: 'Einverstanden',
            pl: 'Zgoda',
        },
    },
    noFaction: {
        getLostNow: {
            ru: 'Ты чё вообще здесь забыл, а ну пиздуй отсюда нахуй пока тебя не отпиздили нахуй',
            ua: 'Ти що взагалі тут забув, а ну йди звідси нахуй, поки тебе не відпиздили нахуй',
            en: 'What the hell are you even doing here? Get the fuck out of here before you get your ass kicked!',
            de: 'Was zum Teufel machst du überhaupt hier? Verpiss dich sofort, bevor du aufs Maul bekommst!',
            pl: 'Co ty w ogóle tu robisz? Spierdalaj stąd, zanim cię ktoś wpierdoli!',
        },
        fuckYou: {
            ru: 'Иди нахуй',
            ua: 'Іди нахуй',
            en: 'Fuck you',
            de: 'Fick dich',
            pl: 'Pierdol się',
        },
        okay: {
            ru: 'Ладно ладно',
            ua: 'Гаразд гаразд',
            en: 'Alright, alright',
            de: 'Schon gut, schon gut',
            pl: 'Dobra, dobra',
        },
    },
    alreadyJob: {
        comeBackLater: {
            ru: 'Не могу тебе сейчас что то предложить, прийди позже',
            ua: 'Не можу зараз тобі щось запропонувати, приходь пізніше',
            en: "I can't offer you anything right now, come back later",
            de: 'Ich kann dir gerade nichts anbieten, komm später wieder',
            pl: 'Nie mogę ci teraz nic zaproponować, przyjdź później',
        },
        okay: {
            ru: 'Хорошо',
            ua: 'Добре',
            en: 'Alright',
            de: 'In Ordnung',
            pl: 'Dobrze',
        },
    },
};
