export const creator = {
    header: {
        ua: 'Створеня персонажу',
        en: 'Character Creation',
        ru: 'Создание персонажа',
        de: 'Charaktererstellung',
        pl: 'Tworzenie postaci',
        zh:'角色创建',
    },

    notify: {
        ua: 'Ви ввели некоректні дані',
        en: 'You have entered incorrect data',
        ru: 'Вы ввели некоректные данные',
        de: 'Sie haben ungültige Daten eingegeben',
        pl: 'Wprowadziłeś nieprawidłowe dane',
        zh:'输入的数据不正确',
    },
    pages: {
        info: {
            ua: 'Інформація про персонажа',
            en: 'Character Information',
            ru: 'Информация о персонаже',
            de: 'Charakterinformationen',
            pl: 'Informacje o postaci',
           zh:'字符信息',
        },
        parents: {
            ua: 'Вибір батьків',
            en: 'Parents Selection',
            ru: 'Выбор родителей',
            de: 'Elternauswahl',
            pl: 'Wybór rodziców',
           zh:'选择父母',
        },
        face: {
            ua: 'Зовнішність',
            en: 'Face',
            ru: 'Внешность',
            de: 'Gesicht',
            pl: 'Twarz',
            zh:'脸',
        },
        appearance: {
            ua: 'Зовнішній вигляд',
            en: 'Appearance',
            ru: 'Внешний вид',
            de: 'Aussehen',
            pl: 'Wygląd',
            zh:'外观',
        },
        clothes: {
            ua: 'Одяг',
            en: 'Clothes',
            ru: 'Одежда',
            de: 'Kleidung',
            pl: 'Ubrania',
            zh:'衣服',
        },
        next: {
            ua: 'Далі',
            en: 'Next',
            ru: 'Дальше',
            de: 'Weiter',
            pl: 'Następny',
            zh:'下一个',
        },
    },
    info: {
        genders: {
            male: {
                ua: 'Чоловік',
                en: 'Male',
                ru: 'Мужской',
                de: 'Männlich',
                pl: 'Mężczyzna',
                zh:'男人',
            },
            female: {
                ua: 'Жінка',
                en: 'Female',
                ru: 'Женский',
                de: 'Weiblich',
                pl: 'Kobieta',
               zh:'女性',
            },
        },
        inputs: {
            namePlaceholder: {
                ua: "Введіть ім'я",
                en: 'Enter name',
                ru: 'Введите имя',
                de: 'Geben Sie einen Namen ein',
                pl: 'Wprowadź imię',
                zh:'进入游戏',
            },
            surnamePlaceholder: {
                ua: 'Введіть прізвище',
                en: 'Enter surname',
                ru: 'Введите фамилию',
                de: 'Geben Sie einen Nachnamen ein',
                pl: 'Wprowadź nazwisko',
                zh:'输入姓',
            },
            agePlaceholder: {
                ua: 'Введіть вік (від 18 до 90)',
                en: 'Enter age (18 to 90)',
                ru: 'Введите возраст (от 18 до 90)',
                de: 'Geben Sie das Alter ein (18 bis 90)',
                pl: 'Wprowadź wiek (od 18 do 90)',
                zh:'输入年龄(18至90岁)',
            },
            genderSelection: {
                ua: 'Вибір статі',
                en: 'Gender selection',
                ru: 'Выбор пола',
                de: 'Geschlechtsauswahl',
                pl: 'Wybór płci',
                zh:'性别选择',
            },
        },
    },
    parents: {
        similarityGenesLabel: {
            ua: 'Схожість генів',
            en: 'Gene similarity',
            ru: 'Сходство генов',
            de: 'Genähnlichkeit',
            pl: 'Podobieństwo genetyczne',
            zh:'基因相似度',
        },
        skinColorLabel: {
            ua: 'Колір шкіри',
            en: 'Skin color',
            ru: 'Цвет кожи',
            de: 'Hautfarbe',
            pl: 'Kolor skóry',
            zh:'皮肤颜色',
        },
    },
    face: {
        faceFeauture: {
            widthOfNose: {
                ua: 'Ширина носа',
                en: 'Width of the nose',
                ru: 'Ширина носа',
                de: 'Breite der Nase',
                pl: 'Szerokość nosa',
                zh:'鼻子宽度',
            },
            heightOfNose: {
                ua: 'Висота носа',
                en: 'Height of the nose',
                ru: 'Высота носа',
                de: 'Höhe der Nase',
                pl: 'Wysokość nosa',
                zh:'鼻子高度',
            },
            lengthOfNose: {
                ua: 'Довжина носа',
                en: 'Length of the nose',
                ru: 'Длина носа',
                de: 'Länge der Nase',
                pl: 'Długość nosa',
                zh:'鼻子长度',
            },
            bridgeOfNose: {
                ua: 'Місток носа',
                en: 'Bridge of the nose',
                ru: 'Мостик носа',
                de: 'Nasenrücken',
                pl: 'Grzbiet nosa',
                zh:'鼻梁',
            },
            nasalTip: {
                ua: 'Носовий кінчик',
                en: 'Nasal tip',
                ru: 'Носовой кончик',
                de: 'Nasenspitze',
                pl: 'Czoło nosa',
                zh:'鼻尖',
            },
            nasalBridge: {
                ua: 'Ребро носа',
                en: 'Nasal bridge',
                ru: 'Ребро носа',
                de: 'Nasenbrücke',
                pl: 'Mostek nosa',
                zh:'鼻梁',
            },
            eyebrowHeight: {
                ua: 'Высота брів',
                en: 'Eyebrow height',
                ru: 'Высота бровей',
                de: 'Augenbrauenhöhe',
                pl: 'Wysokość brwi',
                zh:'眉高',
            },
            eyebrowWidth: {
                ua: 'Ширина брів',
                en: 'Eyebrow width',
                ru: 'Ширина бровей',
                de: 'Augenbrauenbreite',
                pl: 'Szerokość brwi',
                zh:'眉宽度',
            },
            cheekboneHeight: {
                ua: 'Висота скул',
                en: 'Cheekbone height',
                ru: 'Высота скул',
                de: 'Wangenbeinhöhe',
                pl: 'Wysokość kości policzkowych',
                zh:'颧骨高',
            },
            cheekboneWidth: {
                ua: 'Ширина скул',
                en: 'Cheekbone width',
                ru: 'Ширина скул',
                de: 'Wangenbeinbreite',
                pl: 'Szerokość kości policzkowych',
               zh:'颧骨宽度',
            },
            cheekWidth: {
                ua: 'Ширина щік',
                en: 'Cheek width',
                ru: 'Ширина щек',
                de: 'Wangenbreite',
                pl: 'Szerokość policzków',
               zh:'脸颊宽度',
            },
            eyelids: {
                ua: 'Повіки',
                en: 'Eyelids',
                ru: 'Веки',
                de: 'Augenlider',
                pl: 'Powieki',
                zh:'眼皮',
            },
            lips: {
                ua: 'Губи',
                en: 'Lips',
                ru: 'Губы',
                de: 'Lippen',
                pl: 'Usta',
                zh:'嘴唇',
            },
            jawWidth: {
                ua: 'Ширина щелепи',
                en: 'Jaw width',
                ru: 'Ширина челюсти',
                de: 'Kieferbreite',
                pl: 'Szerokość szczęki',
               zh:'颚宽',
            },
            jawHeight: {
                ua: 'Высота щелепи',
                en: 'Jaw height',
                ru: 'Высота челюсти',
                de: 'Kieferhöhe',
                pl: 'Wysokość szczęki',
                zh:'下巴高度',
            },
            chinLength: {
                ua: 'Довжина підборіддя',
                en: 'Chin length',
                ru: 'Длина подбородка',
                de: 'Kinnlänge',
                pl: 'Długość brody',
                zh:'下巴长',
            },
            chinPosition: {
                ua: 'Положення підборіддя',
                en: 'Chin position',
                ru: 'Положение подбородка',
                de: 'Kinnposition',
                pl: 'Położenie brody',
                zh:'下巴位置',
            },
            chinWidth: {
                ua: 'Ширина підборіддя',
                en: 'Chin width',
                ru: 'Ширина подбородка',
                de: 'Kinnbreite',
                pl: 'Szerokość brody',
                zh:'下巴宽度',
            },
            chinShape: {
                ua: 'Форма підборіддя',
                en: 'Chin shape',
                ru: 'Форма подбородка',
                de: 'Kinnform',
                pl: 'Kształt brody',
                zh:'下巴形状',
            },
            neckWidth: {
                ua: 'Ширина шиї',
                en: 'Neck width',
                ru: 'Ширина шеи',
                de: 'Halsbreite',
                pl: 'Szerokość szyi',
                zh:'颈宽',
            },
        },
    },
    appearance: {
        eyesColor: {
            ua: 'Виберіть колір очей',
            en: 'Choose eye color',
            ru: 'Выберите цвет глаз',
            de: 'Wählen Sie die Augenfarbe',
            pl: 'Wybierz kolor oczu',
            zh:'选择眼睛颜色',
        },
        hairIndex: {
            ua: 'Виберіть зачіску',
            en: 'Choose hairstyle',
            ru: 'Выберите прическу',
            de: 'Wählen Sie eine Frisur',
            pl: 'Wybierz fryzurę',
            zh:'选择合适的发型',
        },
        hairColor: {
            ua: 'Виберіть колір волосся',
            en: 'Choose hair color',
            ru: 'Выберите цвет волос',
            de: 'Wählen Sie die Haarfarbe',
            pl: 'Wybierz kolor włosów',
            zh:'选择发色',
        },
        browsIndex: {
            ua: 'Виберіть брови',
            en: 'Choose eyebrows',
            ru: 'Выберите брови',
            de: 'Wählen Sie Augenbrauen',
            pl: 'Wybierz brwi',
           zh:'选择眉毛',
        },
        browsColor: {
            ua: 'Виберіть колір брів',
            en: 'Choose eyebrow color',
            ru: 'Выберите цвет бровей',
            de: 'Wählen Sie die Augenbrauenfarbe',
            pl: 'Wybierz kolor brwi',
            zh:'选择眉色',
        },
        beardIndex: {
            ua: 'Виберіть бороду',
            en: 'Choose beard',
            ru: 'Выберите бороду',
            de: 'Wählen Sie einen Bart',
            pl: 'Wybierz brodę',
            zh:'选择胡子',
        },
        beardColor: {
            ua: 'Виберіть колір бороди',
            en: 'Choose beard color',
            ru: 'Выберите цвет бороды',
            de: 'Wählen Sie die Bartfarbe',
            pl: 'Wybierz kolor brody',
            zh:'选择胡须颜色',
        },
        blemishesIndex: {
            ua: 'Пятна на лице',
            en: 'Blemishes',
            ru: 'Пятна на лице',
            de: 'Hautunreinheiten',
            pl: 'Znamiona i piegi',
           zh:'面部瑕疵',
        },
        ageingIndex: {
            ua: 'Старение',
            en: 'Ageing',
            ru: 'Старение',
            de: 'Alterung',
            pl: 'Starzenie się',
           zh:'衰老',
        },
        sunDamageIndex: {
            ua: 'Урон от солнца',
            en: 'Sun damage',
            ru: 'Урон от солнца',
            de: 'Sonnenschäden',
            pl: 'Uszkodzenia spowodowane słońcem',
            zh:'晒伤',
        },
        molesIndex: {
            ua: 'Родинки и веснушки',
            en: 'Moles and freckles',
            ru: 'Родинки и веснушки',
            de: 'Muttermale und Sommersprossen',
            pl: 'Pieprzyki i piegi',
            zh:'痣和雀斑',
        },
    },
    clothes: {
        tops: {
            ua: 'Верхній одяг',
            en: 'Tops',
            ru: 'Верхняя одежда',
            de: 'Oberteile',
            pl: 'Górne części',
            zh:'上装',
        },
        tshirt: {
            ua: 'Футболка',
            en: 'T-shirt',
            ru: 'Футболка',
            de: 'T-Shirt',
            pl: 'Koszulka',
            zh:'T恤',
        },
        legs: {
            ua: 'Штани',
            en: 'Pants',
            ru: 'Штаны',
            de: 'Hosen',
            pl: 'Spodnie',
            zh:'长裤',
        },
        shoes: {
            ua: 'Взуття',
            en: 'Shoes',
            ru: 'Обувь',
            de: 'Schuhe',
            pl: 'Buty',
            zh:'鞋子',
        },
    },
    buttons: {
        back: {
            ua: 'Назад',
            en: 'Back',
            ru: 'Назад',
            de: 'Zurück',
            pl: 'Wstecz',
            zh:'后面',
        },
        next: {
            ua: 'Далі',
            en: 'Next',
            ru: 'Далее',
            de: 'Weiter',
            pl: 'Dalej',
            zh:'下一个',
        },
    },
};
