export const creator = {
    header: {
        ua: 'Створеня персонажу',
        en: 'Character Creation',
        ru: 'Создание персонажа',
        de: 'Charaktererstellung',
        pl: 'Tworzenie postaci',
        zh: '角色创建',
    },

    notify: {
        ua: 'Ви ввели некоректні дані',
        en: 'You have entered incorrect data',
        ru: 'Вы ввели некоректные данные',
        de: 'Du hast ungültige Daten eingegeben',
        pl: 'Wprowadziłeś nieprawidłowe dane',
        zh: '输入的数据不正确',
    },

    talkToMike: {
        ru: 'Поговори с Майком, он поможет освоиться в игре!',
        ua: 'Поговори з Майком, він допоможе освоїтися в грі!',
        en: 'Talk to Mike, he’ll help you get used to the game!',
        de: 'Sprich mit Mike, er hilft dir, dich im Spiel zurechtzufinden!',
        pl: 'Porozmawiaj z Mike’iem, pomoże ci odnaleźć się w grze!',
    },
    pages: {
        info: {
            ua: 'Інформація про персонажа',
            en: 'Character Information',
            ru: 'Информация о персонаже',
            de: 'Charakterinformationen',
            pl: 'Informacje o postaci',
            zh: '字符信息',
        },
        genetics: {
            ua: 'Генетика',
            en: 'Genetics',
            ru: 'Генетика',
            de: 'Genetik',
            pl: 'Genetyka',
            zh: '遗传',
        },
        face: {
            ua: 'Зовнішність',
            en: 'Face',
            ru: 'Внешность',
            de: 'Gesicht',
            pl: 'Twarz',
            zh: '脸',
        },
        appearance: {
            ua: 'Зовнішній вигляд',
            en: 'Appearance',
            ru: 'Внешний вид',
            de: 'Aussehen',
            pl: 'Wygląd',
            zh: '外观',
        },
        clothes: {
            ua: 'Одяг',
            en: 'Clothes',
            ru: 'Одежда',
            de: 'Kleidung',
            pl: 'Ubrania',
            zh: '衣服',
        },
        next: {
            ua: 'Далі',
            en: 'Next',
            ru: 'Дальше',
            de: 'Weiter',
            pl: 'Następny',
            zh: '下一个',
        },
    },
    info: {
        genders: {
            male: {
                ua: 'Чоловік',
                en: 'Male',
                ru: 'Мужской',
                de: 'Männlich',
                pl: 'Mężczyzna',
                zh: '男人',
            },
            female: {
                ua: 'Жінка',
                en: 'Female',
                ru: 'Женский',
                de: 'Weiblich',
                pl: 'Kobieta',
                zh: '女性',
            },
        },
        inputs: {
            namePlaceholder: {
                ua: "Введіть ім'я",
                en: 'Enter name',
                ru: 'Введите имя',
                de: 'Gib einen Vornamen ein',
                pl: 'Wprowadź imię',
                zh: '进入游戏',
            },
            surnamePlaceholder: {
                ua: 'Введіть прізвище',
                en: 'Enter surname',
                ru: 'Введите фамилию',
                de: 'Gib einen Nachnamen ein',
                pl: 'Wprowadź nazwisko',
                zh: '输入姓',
            },
            agePlaceholder: {
                ua: 'Введіть вік (від 18 до 90)',
                en: 'Enter age (18 to 90)',
                ru: 'Введите возраст (от 18 до 90)',
                de: 'Gib das Alter ein (18 bis 90)',
                pl: 'Wprowadź wiek (od 18 do 90)',
                zh: '输入年龄(18至90岁)',
            },
            genderSelection: {
                ua: 'Вибір статі',
                en: 'Gender selection',
                ru: 'Выбор пола',
                de: 'Geschlechtsauswahl',
                pl: 'Wybór płci',
                zh: '性别选择',
            },
        },
    },
    parents: {
        similarityGenesLabel: {
            ua: 'Схожість генів',
            en: 'Gene similarity',
            ru: 'Сходство генов',
            de: 'Ähnlichkeit',
            pl: 'Podobieństwo genetyczne',
            zh: '基因相似度',
        },
        skinColorLabel: {
            ua: 'Колір шкіри',
            en: 'Skin color',
            ru: 'Цвет кожи',
            de: 'Hautfarbe',
            pl: 'Kolor skóry',
            zh: '皮肤颜色',
        },
    },
    face: {
        groups: {
            brow: {
                name: {
                    ua: 'Лоб',
                    en: 'Brow',
                    ru: 'Лоб',
                    de: 'Stirn',
                    pl: 'Czoło',
                    zh: '眉骨',
                },
                top: {
                    ua: 'Плоский',
                    en: 'Flat',
                    ru: 'Плоский',
                    de: 'Flach',
                    pl: 'Płaskie',
                    zh: '平坦',
                },
                bottom: {
                    ua: 'Опуклий',
                    en: 'Convex',
                    ru: 'Выпуклый',
                    de: 'Konvex',
                    pl: 'Wypukłe',
                    zh: '凸起',
                },
                left: {
                    ua: 'Високий',
                    en: 'High',
                    ru: 'Высокий',
                    de: 'Hoch',
                    pl: 'Wysokie',
                    zh: '高',
                },
                right: {
                    ua: 'Низький',
                    en: 'Low',
                    ru: 'Низкий',
                    de: 'Niedrig',
                    pl: 'Niskie',
                    zh: '低',
                },
            },
            eyes: {
                name: {
                    ua: 'Очі',
                    en: 'Eyes',
                    ru: 'Глаза',
                    de: 'Augen',
                    pl: 'Oczy',
                    zh: '眼睛',
                },
                left: {
                    ua: 'Широкі',
                    en: 'Wide',
                    ru: 'Широкие',
                    de: 'Breit',
                    pl: 'Szerokie',
                    zh: '宽',
                },
                right: {
                    ua: 'Вузькі',
                    en: 'Narrow',
                    ru: 'Узкие',
                    de: 'Schmal',
                    pl: 'Wąskie',
                    zh: '窄',
                },
            },
            nose: {
                name: {
                    ua: 'Ніс',
                    en: 'Nose',
                    ru: 'Нос',
                    de: 'Nase',
                    pl: 'Nos',
                    zh: '鼻子',
                },
                top: {
                    ua: 'Догори',
                    en: 'Up',
                    ru: 'Кверху',
                    de: 'Hoch',
                    pl: 'W górę',
                    zh: '向上',
                },
                bottom: {
                    ua: 'Донизу',
                    en: 'Down',
                    ru: 'Книзу',
                    de: 'Runter',
                    pl: 'W dół',
                    zh: '向下',
                },
                left: {
                    ua: 'Вузький',
                    en: 'Narrow',
                    ru: 'Узкий',
                    de: 'Schmal',
                    pl: 'Wąski',
                    zh: '窄',
                },
                right: {
                    ua: 'Широкий',
                    en: 'Wide',
                    ru: 'Широкий',
                    de: 'Breit',
                    pl: 'Szeroki',
                    zh: '宽',
                },
            },
            noseProfile: {
                name: {
                    ua: 'Профіль носа',
                    en: 'Nose profile',
                    ru: 'Профиль носа',
                    de: 'Nasenprofil',
                    pl: 'Profil nosa',
                    zh: '鼻子轮廓',
                },
                top: {
                    ua: 'З горбинкою',
                    en: 'Humped',
                    ru: 'С горбинкой',
                    de: 'Höckernase',
                    pl: 'Z garbem',
                    zh: '鹰钩',
                },
                bottom: {
                    ua: 'Вигнутий',
                    en: 'Arched',
                    ru: 'Выгнутый',
                    de: 'Gewölbt',
                    pl: 'Wygięty',
                    zh: '弧形',
                },
                left: {
                    ua: 'Малий',
                    en: 'Small',
                    ru: 'Малый',
                    de: 'Klein',
                    pl: 'Mały',
                    zh: '小',
                },
                right: {
                    ua: 'Великий',
                    en: 'Big',
                    ru: 'Большой',
                    de: 'Groß',
                    pl: 'Duży',
                    zh: '大',
                },
            },
            noseTip: {
                name: {
                    ua: 'Кінчик носа',
                    en: 'Nose tip',
                    ru: 'Кончик носа',
                    de: 'Nasenspitze',
                    pl: 'Czubek nosa',
                    zh: '鼻尖',
                },
                top: {
                    ua: 'Скіс вліво',
                    en: 'Bevel left',
                    ru: 'Скос влево',
                    de: 'Nach links',
                    pl: 'Skos w lewo',
                    zh: '左偏',
                },
                bottom: {
                    ua: 'Скіс вправо',
                    en: 'Bevel right',
                    ru: 'Скос вправо',
                    de: 'Nach rechts',
                    pl: 'Skos w prawo',
                    zh: '右偏',
                },
                left: {
                    ua: 'Кінчик вгору',
                    en: 'Tip up',
                    ru: 'Кончик вверх',
                    de: 'Spitze hoch',
                    pl: 'Czubek w górę',
                    zh: '鼻尖上翘',
                },
                right: {
                    ua: 'Кінчик вниз',
                    en: 'Tip down',
                    ru: 'Кончик вниз',
                    de: 'Spitze runter',
                    pl: 'Czubek w dół',
                    zh: '鼻尖下垂',
                },
            },
            cheekbones: {
                name: {
                    ua: 'Вилиці',
                    en: 'Cheekbones',
                    ru: 'Скулы',
                    de: 'Wangenknochen',
                    pl: 'Kości policzkowe',
                    zh: '颧骨',
                },
                top: {
                    ua: 'Худі',
                    en: 'Skinny',
                    ru: 'Худые',
                    de: 'Schmal',
                    pl: 'Szczupłe',
                    zh: '瘦削',
                },
                bottom: {
                    ua: 'Надуті',
                    en: 'Inflated',
                    ru: 'Надутые',
                    de: 'Aufgeblasen',
                    pl: 'Nadęte',
                    zh: '饱满',
                },
                left: {
                    ua: 'Високі',
                    en: 'High',
                    ru: 'Высокие',
                    de: 'Hoch',
                    pl: 'Wysokie',
                    zh: '高',
                },
                right: {
                    ua: 'Низькі',
                    en: 'Low',
                    ru: 'Низкие',
                    de: 'Niedrig',
                    pl: 'Niskie',
                    zh: '低',
                },
            },
            cheeks: {
                name: {
                    ua: 'Щоки',
                    en: 'Cheeks',
                    ru: 'Щёки',
                    de: 'Wangen',
                    pl: 'Policzki',
                    zh: '脸颊',
                },
                left: {
                    ua: 'Надуті',
                    en: 'Inflated',
                    ru: 'Надутые',
                    de: 'Aufgeblasen',
                    pl: 'Nadęte',
                    zh: '饱满',
                },
                right: {
                    ua: 'Худі',
                    en: 'Skinny',
                    ru: 'Худые',
                    de: 'Schmal',
                    pl: 'Szczupłe',
                    zh: '瘦削',
                },
            },
            lips: {
                name: {
                    ua: 'Губи',
                    en: 'Lips',
                    ru: 'Губы',
                    de: 'Lippen',
                    pl: 'Usta',
                    zh: '嘴唇',
                },
                left: {
                    ua: 'Товсті',
                    en: 'Thick',
                    ru: 'Толстые',
                    de: 'Dick',
                    pl: 'Grube',
                    zh: '厚',
                },
                right: {
                    ua: 'Тонкі',
                    en: 'Thin',
                    ru: 'Тонкие',
                    de: 'Dünn',
                    pl: 'Cienkie',
                    zh: '薄',
                },
            },
            jaw: {
                name: {
                    ua: 'Щелепа',
                    en: 'Jaw',
                    ru: 'Челюсть',
                    de: 'Kiefer',
                    pl: 'Szczęka',
                    zh: '下颌',
                },
                top: {
                    ua: 'Кругла',
                    en: 'Round',
                    ru: 'Круглая',
                    de: 'Rund',
                    pl: 'Okrągła',
                    zh: '圆润',
                },
                bottom: {
                    ua: 'Квадратна',
                    en: 'Square',
                    ru: 'Квадратная',
                    de: 'Eckig',
                    pl: 'Kwadratowa',
                    zh: '方正',
                },
                left: {
                    ua: 'Вузька',
                    en: 'Narrow',
                    ru: 'Узкая',
                    de: 'Schmal',
                    pl: 'Wąska',
                    zh: '窄',
                },
                right: {
                    ua: 'Широка',
                    en: 'Wide',
                    ru: 'Широкая',
                    de: 'Breit',
                    pl: 'Szeroka',
                    zh: '宽',
                },
            },
            chinProfile: {
                name: {
                    ua: 'Профіль підборіддя',
                    en: 'Chin profile',
                    ru: 'Профиль подбородка',
                    de: 'Kinnprofil',
                    pl: 'Profil brody',
                    zh: '下巴轮廓',
                },
                top: {
                    ua: 'Короткий',
                    en: 'Short',
                    ru: 'Короткий',
                    de: 'Kurz',
                    pl: 'Krótki',
                    zh: '短',
                },
                bottom: {
                    ua: 'Довгий',
                    en: 'Long',
                    ru: 'Длинный',
                    de: 'Lang',
                    pl: 'Długi',
                    zh: '长',
                },
                left: {
                    ua: 'Низький',
                    en: 'Low',
                    ru: 'Низкий',
                    de: 'Niedrig',
                    pl: 'Niski',
                    zh: '低',
                },
                right: {
                    ua: 'Високий',
                    en: 'High',
                    ru: 'Высокий',
                    de: 'Hoch',
                    pl: 'Wysoki',
                    zh: '高',
                },
            },
            chinShape: {
                name: {
                    ua: 'Форма підборіддя',
                    en: 'Chin shape',
                    ru: 'Форма подбородка',
                    de: 'Kinnform',
                    pl: 'Kształt brody',
                    zh: '下巴形状',
                },
                top: {
                    ua: 'Округла',
                    en: 'Rounded',
                    ru: 'Округлая',
                    de: 'Gerundet',
                    pl: 'Zaokrąglony',
                    zh: '圆形',
                },
                bottom: {
                    ua: 'З ямочкою',
                    en: 'Dimpled',
                    ru: 'С ямочкой',
                    de: 'Grübchen',
                    pl: 'Z dołkiem',
                    zh: '有凹陷',
                },
                left: {
                    ua: 'Загострена',
                    en: 'Pointed',
                    ru: 'Заострённая',
                    de: 'Spitz',
                    pl: 'Spiczasty',
                    zh: '尖',
                },
                right: {
                    ua: 'Квадратна',
                    en: 'Square',
                    ru: 'Квадратная',
                    de: 'Eckig',
                    pl: 'Kwadratowy',
                    zh: '方',
                },
            },
            neck: {
                name: {
                    ua: 'Шия',
                    en: 'Neck',
                    ru: 'Шея',
                    de: 'Hals',
                    pl: 'Szyja',
                    zh: '脖子',
                },
                left: {
                    ua: 'Вужча',
                    en: 'Narrow',
                    ru: 'Уже',
                    de: 'Schmal',
                    pl: 'Węższa',
                    zh: '细',
                },
                right: {
                    ua: 'Ширша',
                    en: 'Wide',
                    ru: 'Шире',
                    de: 'Breit',
                    pl: 'Szersza',
                    zh: '粗',
                },
            },
        },
    },
    appearance: {
        eyesColor: {
            ua: 'Оберіть колір очей',
            en: 'Choose eye color',
            ru: 'Выберите цвет глаз',
            de: 'Wähle die Augenfarbe',
            pl: 'Wybierz kolor oczu',
            zh: '选择眼睛颜色',
        },
        hairIndex: {
            ua: 'Оберіть зачіску',
            en: 'Choose hairstyle',
            ru: 'Выберите прическу',
            de: 'Wähle eine Frisur',
            pl: 'Wybierz fryzurę',
            zh: '选择合适的发型',
        },
        hairColor: {
            ua: 'Оберіть колір волосся',
            en: 'Choose hair color',
            ru: 'Выберите цвет волос',
            de: 'Wähle die Haarfarbe',
            pl: 'Wybierz kolor włosów',
            zh: '选择发色',
        },
        browsIndex: {
            ua: 'Оберіть брови',
            en: 'Choose eyebrows',
            ru: 'Выберите брови',
            de: 'Wähle die Augenbrauen',
            pl: 'Wybierz brwi',
            zh: '选择眉毛',
        },
        browsColor: {
            ua: 'Оберіть колір брів',
            en: 'Choose eyebrow color',
            ru: 'Выберите цвет бровей',
            de: 'Wähle die Augenbrauenfarbe',
            pl: 'Wybierz kolor brwi',
            zh: '选择眉色',
        },
        beardIndex: {
            ua: 'Оберіть бороду',
            en: 'Choose beard',
            ru: 'Выберите бороду',
            de: 'Wähle einen Bart',
            pl: 'Wybierz brodę',
            zh: '选择胡子',
        },
        beardColor: {
            ua: 'Оберіть колір бороди',
            en: 'Choose beard color',
            ru: 'Выберите цвет бороды',
            de: 'Wähle die Bartfarbe',
            pl: 'Wybierz kolor brody',
            zh: '选择胡须颜色',
        },
        blemishesIndex: {
            ua: 'Плями на обличчі',
            en: 'Blemishes',
            ru: 'Пятна на лице',
            de: 'Hautunreinheiten',
            pl: 'Znamiona i piegi',
            zh: '面部瑕疵',
        },
        ageingIndex: {
            ua: 'Старіння',
            en: 'Ageing',
            ru: 'Старение',
            de: 'Alterung',
            pl: 'Starzenie się',
            zh: '衰老',
        },
        sunDamageIndex: {
            ua: 'Пошкодження від сонця',
            en: 'Sun damage',
            ru: 'Урон от солнца',
            de: 'Sonnenschäden',
            pl: 'Uszkodzenia spowodowane słońcem',
            zh: '晒伤',
        },
        molesIndex: {
            ua: 'Родимки та веснянки',
            en: 'Moles and freckles',
            ru: 'Родинки и веснушки',
            de: 'Muttermale und Sommersprossen',
            pl: 'Pieprzyki i piegi',
            zh: '痣和雀斑',
        },
    },
    clothes: {
        tops: {
            ua: 'Верхній одяг',
            en: 'Tops',
            ru: 'Верхняя одежда',
            de: 'Oberteile',
            pl: 'Górne części',
            zh: '上装',
        },
        tshirt: {
            ua: 'Футболка',
            en: 'T-shirt',
            ru: 'Футболка',
            de: 'T-Shirt',
            pl: 'Koszulka',
            zh: 'T恤',
        },
        legs: {
            ua: 'Штани',
            en: 'Pants',
            ru: 'Штаны',
            de: 'Hosen',
            pl: 'Spodnie',
            zh: '长裤',
        },
        shoes: {
            ua: 'Взуття',
            en: 'Shoes',
            ru: 'Обувь',
            de: 'Schuhe',
            pl: 'Buty',
            zh: '鞋子',
        },
    },
    buttons: {
        create: {
            ua: 'Створити персонажа',
            en: 'Create character',
            ru: 'Создать персонажа',
            de: 'Charakter erstellen',
            pl: 'Stwórz postać',
            zh: '创建角色',
        },
        back: {
            ua: 'Назад',
            en: 'Back',
            ru: 'Назад',
            de: 'Zurück',
            pl: 'Wstecz',
            zh: '后面',
        },
        next: {
            ua: 'Далі',
            en: 'Next',
            ru: 'Далее',
            de: 'Weiter',
            pl: 'Dalej',
            zh: '下一个',
        },
    },
};
