export const selector = {
    createCharacter: {
        ua: 'Створити персонажа',
        en: 'Create Character',
        ru: 'Создать персонажа',
        de: 'Charakter erstellen',
        pl: 'Stwórz postać',
        zh: '创建角色',
    },
    delete: {
        ua: 'Видалити',
        en: 'Delete',
        ru: 'Удалить',
        de: 'Löschen',
        pl: 'Usuń',
        zh: '删除',
    },
    playCharacter: {
        ua: 'Вибрати персонажа',
        en: 'Select Character',
        ru: 'Выбрать персонажа',
        de: 'Charakter auswählen',
        pl: 'Wybierz postać',
        zh: '选择角色',
    },
    played: {
        ua: 'Відіграно:',
        en: 'Played:',
        ru: 'Отыграно:',
        de: 'Gespielt:',
        pl: 'Odtwarzane:',
        zh: '开演',
    },
    cash: {
        ua: 'Готівка:',
        en: 'Cash:',
        ru: 'Наличные:',
        de: 'Bargeld:',
        pl: 'Gotówka:',
        zh: '付款:',
    },
    bank: {
        ua: 'Гроші в банку:',
        en: 'Bank:',
        ru: 'Деньги в банке:',
        de: 'Bank:',
        pl: 'Bank:',
        zh: '银行:',
    },
    faction: {
        ua: 'Фракція',
        en: 'Faction',
        ru: 'Фракция',
        de: 'Fraktion',
        pl: 'Frakcja',
        zh: '帮派',
    },
    notMember: {
        ua: 'Не входить',
        en: 'Not a Member',
        ru: 'Не входит',
        de: 'Kein Mitglied',
        pl: 'Nie jest członkiem',
        zh: '非会员',
    },
    avatarReminder: {
        ru: 'Подсказка: аватарку можно установить в настройках меню.',
        ua: 'Підказка: аватарку можна встановити в налаштуваннях меню.',
        en: 'Tip: you can set your avatar in menu settings.',
        de: 'Tipp: Du kannst deinen Avatar in den Menüeinstellungen festlegen.',
        pl: 'Wskazówka: możesz ustawić awatar w ustawieniach menu.',
        zh: '提示：你可以在菜单设置中设置头像。',
    },
    modal: {
        title: {
            ua: 'Видалити персонажа {{name}}',
            en: 'Delete character {{name}}',
            ru: 'Удалить персонажа {{name}}',
            de: 'Charakter {{name}} löschen',
            pl: 'Usuń postać {{name}}',
            zh: '删除角色{{name}}',
        },
        message: {
            ru: 'Вы уверены? Ваш персонаж будет навсегда удалён!<br> Для подтверждения введите пароль от аккаунта.',
            ua: 'Ви впевнені? Ваш персонаж буде назавжди видалений!<br> Для підтвердження введіть пароль від аккаунту.',
            en: 'Are you sure? Your character will be permanently deleted!<br> To confirm, enter your account password.',
            de: 'Bist du sicher? Dein Charakter wird dauerhaft gelöscht!<br> Gebe zur Bestätigung dein Kontopasswort ein.',
            pl: 'Czy na pewno? Twoja postać zostanie trwale usunięta!<br> Aby potwierdzić, wprowadź hasło do konta.',
        },
        password: {
            ru: 'Пароль от аккаунта',
            ua: 'Пароль від аккаунту',
            en: 'Account password',
            de: 'Passwort für das Konto',
            pl: 'Hasło do konta',
        },
        confirmButton: {
            ua: 'Видалити',
            en: 'Delete',
            ru: 'Удалить',
            de: 'Löschen',
            pl: 'Usuń',
            zh: '删除',
        },
        cancelButton: {
            ua: 'Скасувати',
            en: 'Cancel',
            ru: 'Отмена',
            de: 'Abbrechen',
            pl: 'Anuluj',
            zh: '取消',
        },
    },
    youHaveDailyQuests: {
        ru: 'Похоже у вас есть {{count}} не выполненых ежедневных квестов, скорее пройди их!',
        ua: 'Схоже, у вас є {{count}} невиконаних щоденних квестів, скоріше проходьте їх!',
        en: 'It looks like you have {{count}} unfinished daily quests, hurry up and complete them!',
        de: 'Es sieht so aus, als hättest du {{count}} unerledigte tägliche Quests, beeilen dich und erledige sie!',
        pl: 'Wygląda na to, że masz {{count}} niewykonanych codziennych zadań, pospiesz się i ukończ je!',
        zh: '看起来你有{{count}}未完成的日常任务，快点完成它们',
    },
    failedActivateReferralCode: {
        ru: 'Реферальный код {{code}} не найден, поэтому не был активирован. Вы можете в любой момент ввести другой код в меню.',
        ua: 'Реферальний код {{code}} не знайдено, тому він не був активований. Ви можете в будь-який момент ввести інший код у меню.',
        en: 'Referral code {{code}} not found, so it was not activated. You can enter another code in the menu at any time.',
        de: 'Empfehlungscode {{code}} wurde nicht gefunden und daher nicht aktiviert. Du kannst jederzeit einen anderen Code im Menü eingeben.',
        pl: 'Kod polecający {{code}} nie został znaleziony, więc nie został aktywowany. W każdej chwili możesz wprowadzić inny kod w menu.',
    },
};
