export const selector = {
    createCharacter: {
        ua: 'Створити персонажа',
        en: 'Create Character',
        ru: 'Создать персонажа',
        de: 'Charakter erstellen',
        pl: 'Stwórz postać',
        zh: '创建角色',
    },
    delete: {
        ua: 'Видалити',
        en: 'Delete',
        ru: 'Удалить',
        de: 'Löschen',
        pl: 'Usuń',
        zh: '删除',
    },
    playCharacter: {
        ua: 'Вибрати персонажа',
        en: 'Select Character',
        ru: 'Выбрать персонажа',
        de: 'Charakter auswählen',
        pl: 'Wybierz postać',
        zh: '选择角色',
    },
    played: {
        ua: 'Відіграно:',
        en: 'Played:',
        ru: 'Отыграно:',
        de: 'Gespielt:',
        pl: 'Odtwarzane:',
        zh: '开演',
    },
    cash: {
        ua: 'Готівка:',
        en: 'Cash:',
        ru: 'Наличные:',
        de: 'Bargeld:',
        pl: 'Gotówka:',
        zh: '付款:',
    },
    bank: {
        ua: 'Гроші в банку:',
        en: 'Bank:',
        ru: 'Деньги в банке:',
        de: 'Bank:',
        pl: 'Bank:',
        zh: '银行:',
    },
    faction: {
        ua: 'Фракція',
        en: 'Faction',
        ru: 'Фракция',
        de: 'Fraktion',
        pl: 'Frakcja',
        zh: '帮派',
    },
    notMember: {
        ua: 'Не входить',
        en: 'Not a Member',
        ru: 'Не входит',
        de: 'Kein Mitglied',
        pl: 'Nie jest członkiem',
        zh: '非会员',
    },
    avatarReminder: {
        ru: 'Подсказка: аватарку можно установить в настройках меню.',
        ua: 'Підказка: аватарку можна встановити в налаштуваннях меню.',
        en: 'Tip: you can set your avatar in menu settings.',
        de: 'Tipp: Du kannst deinen Avatar in den Menüeinstellungen festlegen.',
        pl: 'Wskazówka: możesz ustawić awatar w ustawieniach menu.',
        zh: '提示：你可以在菜单设置中设置头像。',
    },
    slots: {
        buy: {
            ua: 'Відкрити слот №{{number}}',
            en: 'Unlock slot #{{number}}',
            ru: 'Открыть слот №{{number}}',
            de: 'Slot #{{number}} freischalten',
            pl: 'Odblokuj slot #{{number}}',
            zh: '解锁第{{number}}个槽位',
        },
        header: {
            ua: 'Слот персонажа',
            en: 'Character slot',
            ru: 'Слот персонажа',
            de: 'Charakter-Slot',
            pl: 'Slot postaci',
            zh: '角色槽位',
        },
        success: {
            ua: 'Слот відкрито. Тепер можна створити ще одного персонажа.',
            en: 'Slot unlocked. You can create one more character now.',
            ru: 'Слот открыт. Теперь можно создать ещё одного персонажа.',
            de: 'Slot freigeschaltet. Du kannst jetzt einen weiteren Charakter erstellen.',
            pl: 'Slot odblokowany. Możesz teraz stworzyć kolejną postać.',
            zh: '槽位已解锁，现在可以再创建一个角色。',
        },
        notEnough: {
            ua: 'Не вистачає Olymp-Coin: слот коштує {{price}}.',
            en: 'Not enough Olymp-Coin: the slot costs {{price}}.',
            ru: 'Не хватает Olymp-Coin: слот стоит {{price}}.',
            de: 'Nicht genug Olymp-Coin: Der Slot kostet {{price}}.',
            pl: 'Za mało Olymp-Coin: slot kosztuje {{price}}.',
            zh: 'Olymp-Coin 不足：该槽位需要 {{price}}。',
        },
        alreadyBought: {
            ua: 'Слот вже відкритий.',
            en: 'The slot is already unlocked.',
            ru: 'Слот уже открыт.',
            de: 'Der Slot ist bereits freigeschaltet.',
            pl: 'Slot jest już odblokowany.',
            zh: '该槽位已解锁。',
        },
        limit: {
            ua: 'Усі слоти персонажів зайняті.',
            en: 'All character slots are taken.',
            ru: 'Все слоты персонажей заняты.',
            de: 'Alle Charakter-Slots sind belegt.',
            pl: 'Wszystkie sloty postaci są zajęte.',
            zh: '所有角色槽位都已占满。',
        },
        modal: {
            title: {
                ua: 'Відкрити слот персонажа',
                en: 'Unlock character slot',
                ru: 'Открыть слот персонажа',
                de: 'Charakter-Slot freischalten',
                pl: 'Odblokuj slot postaci',
                zh: '解锁角色槽位',
            },
            message: {
                ua: 'Слот відкривається назавжди за {{price}} Olymp-Coin і залишається на цьому акаунті.',
                en: 'The slot costs {{price}} Olymp-Coin and stays on this account permanently.',
                ru: 'Слот открывается навсегда за {{price}} Olymp-Coin и остаётся на этом аккаунте.',
                de: 'Der Slot kostet einmalig {{price}} Olymp-Coin und bleibt dauerhaft auf diesem Konto.',
                pl: 'Slot kosztuje {{price}} Olymp-Coin i zostaje na tym koncie na stałe.',
                zh: '该槽位需要 {{price}} Olymp-Coin，永久保留在此账号上。',
            },
            confirmButton: {
                ua: 'Відкрити',
                en: 'Unlock',
                ru: 'Открыть',
                de: 'Freischalten',
                pl: 'Odblokuj',
                zh: '解锁',
            },
            cancelButton: {
                ua: 'Скасувати',
                en: 'Cancel',
                ru: 'Отмена',
                de: 'Abbrechen',
                pl: 'Anuluj',
                zh: '取消',
            },
        },
    },
    modal: {
        title: {
            ua: 'Видалити персонажа {{name}}',
            en: 'Delete character {{name}}',
            ru: 'Удалить персонажа {{name}}',
            de: 'Charakter {{name}} löschen',
            pl: 'Usuń postać {{name}}',
            zh: '删除角色{{name}}',
        },
        message: {
            ru: 'Вы уверены? Ваш персонаж будет навсегда удалён!<br> Для подтверждения введите пароль от аккаунта.',
            ua: 'Ви впевнені? Ваш персонаж буде назавжди видалений!<br> Для підтвердження введіть пароль від аккаунту.',
            en: 'Are you sure? Your character will be permanently deleted!<br> To confirm, enter your account password.',
            de: 'Bist du sicher? Dein Charakter wird dauerhaft gelöscht!<br> Gib zur Bestätigung dein Kontopasswort ein.',
            pl: 'Czy na pewno? Twoja postać zostanie trwale usunięta!<br> Aby potwierdzić, wprowadź hasło do konta.',
        },
        password: {
            ru: 'Пароль от аккаунта',
            ua: 'Пароль від аккаунту',
            en: 'Account password',
            de: 'Passwort für das Konto',
            pl: 'Hasło do konta',
        },
        confirmButton: {
            ua: 'Видалити',
            en: 'Delete',
            ru: 'Удалить',
            de: 'Löschen',
            pl: 'Usuń',
            zh: '删除',
        },
        cancelButton: {
            ua: 'Скасувати',
            en: 'Cancel',
            ru: 'Отмена',
            de: 'Abbrechen',
            pl: 'Anuluj',
            zh: '取消',
        },
    },
    youHaveDailyQuests: {
        ru: 'Похоже у вас есть {{count}} не выполненых ежедневных квестов, скорее пройди их!',
        ua: 'Схоже, у вас є {{count}} невиконаних щоденних квестів, скоріше проходьте їх!',
        en: 'It looks like you have {{count}} unfinished daily quests, hurry up and complete them!',
        de: 'Es sieht so aus, als hättest du {{count}} unerledigte tägliche Quests, beeilen dich und erledige sie!',
        pl: 'Wygląda na to, że masz {{count}} niewykonanych codziennych zadań, pospiesz się i ukończ je!',
        zh: '看起来你有{{count}}未完成的日常任务，快点完成它们',
    },
    failedActivateReferralCode: {
        ru: 'Реферальный код {{code}} не найден, поэтому не был активирован. Вы можете в любой момент ввести другой код в меню.',
        ua: 'Реферальний код {{code}} не знайдено, тому він не був активований. Ви можете в будь-який момент ввести інший код у меню.',
        en: 'Referral code {{code}} not found, so it was not activated. You can enter another code in the menu at any time.',
        de: 'Empfehlungscode {{code}} wurde nicht gefunden und daher nicht aktiviert. Du kannst jederzeit einen anderen Code im Menü eingeben.',
        pl: 'Kod polecający {{code}} nie został znaleziony, więc nie został aktywowany. W każdej chwili możesz wprowadzić inny kod w menu.',
    },
};
