export const server = {
    select: {
        ban: {
            ua: 'Ви заблоковані за',
            en: 'You are banned due to',
            ru: 'Вы забанены по причине',
            de: 'Du wurdest gesperrt wegen',
            pl: 'Zostałeś zablokowany z powodu',
            zh: '你被禁止是因为',
        },
        notify: {
            ua: 'Ласкаво просимо {{name}}!',
            en: 'Welcome {{name}}!',
            ru: 'Добро пожаловать {{name}}!',
            de: 'Willkommen {{name}}!',
            pl: 'Witaj {{name}}!',
            zh: '欢迎{{name}}!',
        },
        messages: {
            one: {
                ua: 'На даний момент сервер знаходиться в розробці!',
                en: 'The server is currently under development!',
                ru: 'На данный момент сервер находится в разработке!',
                de: 'Der Server befindet sich derzeit in der Entwicklung!',
                pl: 'Serwer jest obecnie w trakcie tworzenia!',
                zh: '该服务器目前正在开发中',
            },
            two: {
                ua: 'Наш Discord сервер ~b~discord.gg/XKvU9PY2UD',
                en: 'Join our Discord server~b~ discord.gg/XKvU9PY2UD',
                ru: 'Наш Discord сервер ~b~discord.gg/XKvU9PY2UD',
                de: 'Tritt unserem Discord-Server ~b~discord.gg/XKvU9PY2UD bei',
                pl: 'Dołącz do naszego serwera Discord ~b~discord.gg/XKvU9PY2UD',
                zh: '加入我们的不和服务器~b~ discord.gg / XKvU9PY2UD',
            },
            three: {
                ua: `Для зв'язку з адміністрацією ~b~/support`,
                en: 'To contact the administration, use ~b~/support',
                ru: 'Для связи с администрацией ~b~/support',
                de: 'Um die Administration zu kontaktieren, nutze ~b~/support',
                pl: 'Aby skontaktować się z administracją, użyj ~b~/support',
                zh: '要联系管理员,请使用~b~/support',
            },
        },
        delete: {
            ua: 'Видалення персонажа',
            en: 'Delete Character',
            ru: 'Удаление персонажа',
            de: 'Charakter löschen',
            pl: 'Usuń postać',
            zh: '删除角色',
        },
        wrongPassword: {
            ru: 'Пароль введен неверно',
            ua: 'Пароль введено невірно',
            en: 'Incorrect password',
            de: 'Falsches Passwort',
            pl: 'Nieprawidłowe hasło',
        },
    },
};
