export default {
    available: {
        ru: 'Доступно',
        ua: 'Доступно',
        en: 'Available',
        de: 'Verfügbar',
        pl: 'Dostępne',
    },
    mainAccount: {
        ru: 'Основной счёт',
        ua: 'Основний рахунок',
        en: 'Main account',
        de: 'Hauptkonto',
        pl: 'Konto główne',
    },
    accounts: {
        ru: 'Счета',
        ua: 'Рахунки',
        en: 'Accounts',
        de: 'Konten',
        pl: 'Konta',
    },
    recent: {
        ru: 'Последние операции',
        ua: 'Останні операції',
        en: 'Recent activity',
        de: 'Letzte Umsätze',
        pl: 'Ostatnie operacje',
    },
    showAll: {
        ru: 'Все',
        ua: 'Усі',
        en: 'All',
        de: 'Alle',
        pl: 'Wszystkie',
    },
    max: {
        ru: 'Всё',
        ua: 'Усе',
        en: 'Max',
        de: 'Max',
        pl: 'Max',
    },
    noAccount: {
        ru: 'Счёт ещё не открыт. Откройте его в отделении банка.',
        ua: 'Рахунок ще не відкрито. Відкрийте його у відділенні банку.',
        en: 'No account yet. Open one at a bank branch.',
        de: 'Noch kein Konto. Eröffne eines in einer Bankfiliale.',
        pl: 'Nie masz jeszcze konta. Otwórz je w oddziale banku.',
    },
    notEnough: {
        ru: 'Недостаточно средств',
        ua: 'Недостатньо коштів',
        en: 'Not enough money',
        de: 'Nicht genug Geld',
        pl: 'Za mało środków',
    },
    busy: {
        ru: 'Предыдущая операция ещё выполняется. Подождите пару секунд.',
        ua: 'Попередня операція ще виконується. Зачекайте пару секунд.',
        en: 'The previous operation is still running. Give it a couple of seconds.',
        de: 'Der vorherige Vorgang läuft noch. Warte ein paar Sekunden.',
        pl: 'Poprzednia operacja jeszcze trwa. Odczekaj kilka sekund.',
    },

    failed: {
        operation: {
            ru: 'Операция не выполнена',
            ua: 'Операцію не виконано',
            en: 'Operation failed',
            de: 'Vorgang fehlgeschlagen',
            pl: 'Operacja nie powiodła się',
        },
        transfer: {
            ru: 'Перевод не выполнен',
            ua: 'Переказ не виконано',
            en: 'Transfer failed',
            de: 'Überweisung fehlgeschlagen',
            pl: 'Przelew nie powiódł się',
        },
        payment: {
            ru: 'Платёж не прошёл',
            ua: 'Платіж не пройшов',
            en: 'Payment failed',
            de: 'Zahlung fehlgeschlagen',
            pl: 'Płatność nie powiodła się',
        },
        savings: {
            ru: 'Операция по вкладу не выполнена',
            ua: 'Операцію за вкладом не виконано',
            en: 'Savings operation failed',
            de: 'Sparvorgang fehlgeschlagen',
            pl: 'Operacja na lokacie nie powiodła się',
        },
    },

    actions: {
        transfer: {
            ru: 'Перевод',
            ua: 'Переказ',
            en: 'Transfer',
            de: 'Überweisen',
            pl: 'Przelew',
        },
        payments: {
            ru: 'Платежи',
            ua: 'Платежі',
            en: 'Payments',
            de: 'Zahlungen',
            pl: 'Płatności',
        },
        savings: {
            ru: 'Вклад',
            ua: 'Вклад',
            en: 'Savings',
            de: 'Sparen',
            pl: 'Lokata',
        },
        history: {
            ru: 'История',
            ua: 'Історія',
            en: 'History',
            de: 'Verlauf',
            pl: 'Historia',
        },
    },

    accountNames: {
        savings: {
            ru: 'Вклад',
            ua: 'Вклад',
            en: 'Savings',
            de: 'Sparkonto',
            pl: 'Lokata',
        },
        tax: {
            ru: 'Налоговый счёт',
            ua: 'Податковий рахунок',
            en: 'Tax account',
            de: 'Steuerkonto',
            pl: 'Konto podatkowe',
        },
        commercial: {
            ru: 'Коммерческий счёт',
            ua: 'Комерційний рахунок',
            en: 'Business account',
            de: 'Geschäftskonto',
            pl: 'Konto firmowe',
        },
        sim: {
            ru: 'Телефон',
            ua: 'Телефон',
            en: 'Phone',
            de: 'Telefon',
            pl: 'Telefon',
        },
    },

    accountMeta: {
        savings: {
            ru: '{{rate}}% в сутки',
            ua: '{{rate}}% на добу',
            en: '{{rate}}% per day',
            de: '{{rate}}% pro Tag',
            pl: '{{rate}}% dziennie',
        },
        limit: {
            ru: 'Лимит {{sum}}',
            ua: 'Ліміт {{sum}}',
            en: 'Limit {{sum}}',
            de: 'Limit {{sum}}',
            pl: 'Limit {{sum}}',
        },
        sim: {
            ru: 'Номер {{number}}',
            ua: 'Номер {{number}}',
            en: 'Number {{number}}',
            de: 'Nummer {{number}}',
            pl: 'Numer {{number}}',
        },
    },

    sources: {
        bank: {
            ru: 'Банк',
            ua: 'Банк',
            en: 'Bank',
            de: 'Bank',
            pl: 'Bank',
        },
        atm: {
            ru: 'Банкомат',
            ua: 'Банкомат',
            en: 'ATM',
            de: 'Geldautomat',
            pl: 'Bankomat',
        },
        system: {
            ru: 'Система',
            ua: 'Система',
            en: 'System',
            de: 'System',
            pl: 'System',
        },
        commercial: {
            ru: 'Коммерческий счёт',
            ua: 'Комерційний рахунок',
            en: 'Business account',
            de: 'Geschäftskonto',
            pl: 'Konto firmowe',
        },
        rent: {
            ru: 'Аренда',
            ua: 'Оренда',
            en: 'Rent',
            de: 'Miete',
            pl: 'Wynajem',
        },
        house: {
            ru: 'Дом',
            ua: 'Будинок',
            en: 'House',
            de: 'Haus',
            pl: 'Dom',
        },
        salary: {
            ru: 'Зарплата',
            ua: 'Зарплата',
            en: 'Salary',
            de: 'Gehalt',
            pl: 'Wypłata',
        },
        shop: {
            ru: 'Покупка',
            ua: 'Покупка',
            en: 'Purchase',
            de: 'Einkauf',
            pl: 'Zakup',
        },
        transfer: {
            ru: 'Перевод',
            ua: 'Переказ',
            en: 'Transfer',
            de: 'Überweisung',
            pl: 'Przelew',
        },
        gasStation: {
            ru: 'Заправка',
            ua: 'Заправка',
            en: 'Fuel',
            de: 'Tankstelle',
            pl: 'Stacja paliw',
        },
        fine: {
            ru: 'Штраф',
            ua: 'Штраф',
            en: 'Fine',
            de: 'Bußgeld',
            pl: 'Mandat',
        },
        job: {
            ru: 'Работа',
            ua: 'Робота',
            en: 'Job',
            de: 'Arbeit',
            pl: 'Praca',
        },
        tax: {
            ru: 'Налоги',
            ua: 'Податки',
            en: 'Taxes',
            de: 'Steuern',
            pl: 'Podatki',
        },
        deposit: {
            ru: 'Начисление по вкладу',
            ua: 'Нарахування за вкладом',
            en: 'Savings payout',
            de: 'Zinsgutschrift',
            pl: 'Odsetki z lokaty',
        },
        phone: {
            ru: 'Связь',
            ua: "Зв'язок",
            en: 'Mobile',
            de: 'Mobilfunk',
            pl: 'Telefonia',
        },
        business: {
            ru: 'Бизнес',
            ua: 'Бізнес',
            en: 'Business',
            de: 'Geschäft',
            pl: 'Biznes',
        },
    },

    transfer: {
        title: {
            ru: 'Перевод',
            ua: 'Переказ',
            en: 'Transfer',
            de: 'Überweisung',
            pl: 'Przelew',
        },
        recipient: {
            ru: 'Получатель',
            ua: 'Одержувач',
            en: 'Recipient',
            de: 'Empfänger',
            pl: 'Odbiorca',
        },
        recipientPlaceholder: {
            ru: 'Номер счёта или имя',
            ua: "Номер рахунку або ім'я",
            en: 'Account number or name',
            de: 'Kontonummer oder Name',
            pl: 'Numer konta lub imię',
        },
        amount: {
            ru: 'Сумма',
            ua: 'Сума',
            en: 'Amount',
            de: 'Betrag',
            pl: 'Kwota',
        },
        availableHint: {
            ru: 'На счету {{sum}}',
            ua: 'На рахунку {{sum}}',
            en: '{{sum}} on the account',
            de: '{{sum}} auf dem Konto',
            pl: 'Na koncie {{sum}}',
        },
        commentPlaceholder: {
            ru: 'Комментарий',
            ua: 'Коментар',
            en: 'Comment',
            de: 'Kommentar',
            pl: 'Komentarz',
        },
        commission: {
            ru: 'Комиссия {{percent}}%',
            ua: 'Комісія {{percent}}%',
            en: 'Fee {{percent}}%',
            de: 'Gebühr {{percent}}%',
            pl: 'Prowizja {{percent}}%',
        },
        total: {
            ru: 'Спишется',
            ua: 'Спишеться',
            en: 'Total charge',
            de: 'Gesamtbetrag',
            pl: 'Do zapłaty',
        },
        submit: {
            ru: 'Перевести',
            ua: 'Переказати',
            en: 'Send',
            de: 'Senden',
            pl: 'Wyślij',
        },
        sent: {
            ru: '{{sum}} отправлено: {{name}}',
            ua: '{{sum}} надіслано: {{name}}',
            en: '{{sum}} sent to {{name}}',
            de: '{{sum}} an {{name}} gesendet',
            pl: 'Wysłano {{sum}} do {{name}}',
        },
        noRecipients: {
            ru: 'Введите номер счёта получателя',
            ua: 'Введіть номер рахунку одержувача',
            en: "Enter the recipient's account number",
            de: 'Kontonummer des Empfängers eingeben',
            pl: 'Wpisz numer konta odbiorcy',
        },
        commentInvalid: {
            ru: 'В комментарии есть недопустимые символы',
            ua: 'У коментарі є неприпустимі символи',
            en: 'The comment contains characters that are not allowed',
            de: 'Der Kommentar enthält unzulässige Zeichen',
            pl: 'Komentarz zawiera niedozwolone znaki',
        },
        done: {
            ru: 'Перевод выполнен',
            ua: 'Переказ виконано',
            en: 'Transfer sent',
            de: 'Überweisung gesendet',
            pl: 'Przelew wysłany',
        },
        doneTo: {
            ru: 'Деньги уже на счету получателя',
            ua: 'Гроші вже на рахунку одержувача',
            en: 'The money is already on the recipient account',
            de: 'Das Geld ist bereits auf dem Empfängerkonto',
            pl: 'Pieniądze są już na koncie odbiorcy',
        },
        charged: {
            ru: 'Списано со счёта',
            ua: 'Списано з рахунку',
            en: 'Charged to the account',
            de: 'Vom Konto abgebucht',
            pl: 'Pobrano z konta',
        },
        again: {
            ru: 'Ещё перевод',
            ua: 'Ще переказ',
            en: 'Send again',
            de: 'Noch eine Überweisung',
            pl: 'Kolejny przelew',
        },
        finish: {
            ru: 'Готово',
            ua: 'Готово',
            en: 'Done',
            de: 'Fertig',
            pl: 'Gotowe',
        },
    },

    payments: {
        title: {
            ru: 'Платежи',
            ua: 'Платежі',
            en: 'Payments',
            de: 'Zahlungen',
            pl: 'Płatności',
        },
        subtitle: {
            ru: 'Пополнение счетов и связи',
            ua: "Поповнення рахунків та зв'язку",
            en: 'Top up your accounts and phone',
            de: 'Konten und Mobilfunk aufladen',
            pl: 'Doładowanie kont i telefonu',
        },
        limit: {
            ru: 'Лимит {{sum}}',
            ua: 'Ліміт {{sum}}',
            en: 'Limit {{sum}}',
            de: 'Limit {{sum}}',
            pl: 'Limit {{sum}}',
        },
        note: {
            ru: 'Платежи проходят с основного счёта и зачисляются сразу.',
            ua: 'Платежі проходять з основного рахунку та зараховуються одразу.',
            en: 'Payments are made from the main account and post instantly.',
            de: 'Zahlungen erfolgen vom Hauptkonto und werden sofort gebucht.',
            pl: 'Płatności są realizowane z konta głównego i księgowane od razu.',
        },
    },

    payment: {
        current: {
            ru: 'Сейчас на счету',
            ua: 'Зараз на рахунку',
            en: 'Current balance',
            de: 'Aktueller Stand',
            pl: 'Obecne saldo',
        },
        of: {
            ru: 'из {{sum}}',
            ua: 'з {{sum}}',
            en: 'of {{sum}}',
            de: 'von {{sum}}',
            pl: 'z {{sum}}',
        },
        amount: {
            ru: 'Сумма пополнения',
            ua: 'Сума поповнення',
            en: 'Top up amount',
            de: 'Aufladebetrag',
            pl: 'Kwota doładowania',
        },
        maxHint: {
            ru: 'Можно внести до {{sum}}',
            ua: 'Можна внести до {{sum}}',
            en: 'Up to {{sum}}',
            de: 'Bis zu {{sum}}',
            pl: 'Do {{sum}}',
        },
        submit: {
            ru: 'Оплатить',
            ua: 'Сплатити',
            en: 'Pay',
            de: 'Bezahlen',
            pl: 'Zapłać',
        },
        paid: {
            ru: '{{account}} пополнен на {{sum}}',
            ua: '{{account}} поповнено на {{sum}}',
            en: '{{account}} topped up by {{sum}}',
            de: '{{account}} um {{sum}} aufgeladen',
            pl: '{{account}} doładowane o {{sum}}',
        },
        overLimit: {
            ru: 'Столько на этот счёт не поместится',
            ua: 'Стільки на цей рахунок не поміститься',
            en: 'That is more than this account can hold',
            de: 'So viel passt nicht auf dieses Konto',
            pl: 'Tyle nie zmieści się na tym koncie',
        },
    },

    savings: {
        title: {
            ru: 'Вклад',
            ua: 'Вклад',
            en: 'Savings',
            de: 'Sparkonto',
            pl: 'Lokata',
        },
        onDeposit: {
            ru: 'На вкладе',
            ua: 'На вкладі',
            en: 'On deposit',
            de: 'Angelegt',
            pl: 'Na lokacie',
        },
        rate: {
            ru: '{{rate}}% в сутки',
            ua: '{{rate}}% на добу',
            en: '{{rate}}% per day',
            de: '{{rate}}% pro Tag',
            pl: '{{rate}}% dziennie',
        },
        nextPayout: {
            ru: 'До начисления {{time}}',
            ua: 'До нарахування {{time}}',
            en: 'Next payout in {{time}}',
            de: 'Nächste Gutschrift in {{time}}',
            pl: 'Do wypłaty odsetek {{time}}',
        },
        deposit: {
            ru: 'Пополнить',
            ua: 'Поповнити',
            en: 'Add money',
            de: 'Einzahlen',
            pl: 'Wpłać',
        },
        withdraw: {
            ru: 'Снять',
            ua: 'Зняти',
            en: 'Withdraw',
            de: 'Abheben',
            pl: 'Wypłać',
        },
        maxHint: {
            ru: 'Доступно {{sum}}',
            ua: 'Доступно {{sum}}',
            en: 'Available {{sum}}',
            de: 'Verfügbar {{sum}}',
            pl: 'Dostępne {{sum}}',
        },
        deposited: {
            ru: '{{sum}} на вкладе',
            ua: '{{sum}} на вкладі',
            en: '{{sum}} added to the deposit',
            de: '{{sum}} angelegt',
            pl: '{{sum}} na lokacie',
        },
        withdrawn: {
            ru: '{{sum}} снято со вклада',
            ua: '{{sum}} знято з вкладу',
            en: '{{sum}} withdrawn from the deposit',
            de: '{{sum}} vom Sparkonto abgehoben',
            pl: 'Wypłacono {{sum}} z lokaty',
        },
        overCap: {
            ru: 'Превышен максимум вклада',
            ua: 'Перевищено максимум вкладу',
            en: 'Over the deposit maximum',
            de: 'Über dem Anlagemaximum',
            pl: 'Przekroczono maksimum lokaty',
        },
        overDeposit: {
            ru: 'На вкладе меньше',
            ua: 'На вкладі менше',
            en: 'The deposit holds less than that',
            de: 'So viel ist nicht angelegt',
            pl: 'Na lokacie jest mniej',
        },
        fee: {
            ru: 'Комиссия за снятие {{percent}}%',
            ua: 'Комісія за зняття {{percent}}%',
            en: 'Withdrawal fee {{percent}}%',
            de: 'Abhebegebühr {{percent}}%',
            pl: 'Prowizja za wypłatę {{percent}}%',
        },
        youGet: {
            ru: 'На основной счёт придёт',
            ua: 'На основний рахунок надійде',
            en: 'The main account receives',
            de: 'Auf dem Hauptkonto landen',
            pl: 'Na konto główne trafi',
        },
        info: {
            first: {
                ru: 'Начисление приходит раз в сутки на основной счёт.',
                ua: 'Нарахування приходить раз на добу на основний рахунок.',
                en: 'Interest lands on the main account once a day.',
                de: 'Die Zinsen werden einmal täglich auf das Hauptkonto gebucht.',
                pl: 'Odsetki trafiają na konto główne raz na dobę.',
            },
            second: {
                ru: 'Ставка {{rate}}% считается от суммы на вкладе.',
                ua: 'Ставка {{rate}}% рахується від суми на вкладі.',
                en: 'The {{rate}}% rate applies to the deposited amount.',
                de: 'Der Satz von {{rate}}% gilt für den angelegten Betrag.',
                pl: 'Stawka {{rate}}% liczona jest od kwoty lokaty.',
            },
            third: {
                ru: 'Максимальная сумма вклада: {{sum}}.',
                ua: 'Максимальна сума вкладу: {{sum}}.',
                en: 'Maximum deposit: {{sum}}.',
                de: 'Maximale Anlage: {{sum}}.',
                pl: 'Maksymalna kwota lokaty: {{sum}}.',
            },
        },
    },

    history: {
        title: {
            ru: 'История',
            ua: 'Історія',
            en: 'History',
            de: 'Verlauf',
            pl: 'Historia',
        },
        filter: {
            all: {
                ru: 'Все',
                ua: 'Усі',
                en: 'All',
                de: 'Alle',
                pl: 'Wszystkie',
            },
            income: {
                ru: 'Поступления',
                ua: 'Надходження',
                en: 'Income',
                de: 'Eingänge',
                pl: 'Wpływy',
            },
            expense: {
                ru: 'Списания',
                ua: 'Списання',
                en: 'Spending',
                de: 'Ausgaben',
                pl: 'Wydatki',
            },
        },
        today: {
            ru: 'Сегодня',
            ua: 'Сьогодні',
            en: 'Today',
            de: 'Heute',
            pl: 'Dzisiaj',
        },
        yesterday: {
            ru: 'Вчера',
            ua: 'Вчора',
            en: 'Yesterday',
            de: 'Gestern',
            pl: 'Wczoraj',
        },
        empty: {
            ru: 'Операций пока нет',
            ua: 'Операцій поки немає',
            en: 'No transactions yet',
            de: 'Noch keine Umsätze',
            pl: 'Brak operacji',
        },
        income: {
            ru: 'Поступление',
            ua: 'Надходження',
            en: 'Incoming',
            de: 'Eingang',
            pl: 'Wpływ',
        },
        expense: {
            ru: 'Списание',
            ua: 'Списання',
            en: 'Outgoing',
            de: 'Abbuchung',
            pl: 'Wypływ',
        },
        counterparty: {
            ru: 'Контрагент',
            ua: 'Контрагент',
            en: 'Counterparty',
            de: 'Gegenpartei',
            pl: 'Kontrahent',
        },
        account: {
            ru: 'Номер счёта',
            ua: 'Номер рахунку',
            en: 'Account number',
            de: 'Kontonummer',
            pl: 'Numer konta',
        },
        source: {
            ru: 'Источник',
            ua: 'Джерело',
            en: 'Source',
            de: 'Quelle',
            pl: 'Źródło',
        },
        date: {
            ru: 'Дата и время',
            ua: 'Дата та час',
            en: 'Date and time',
            de: 'Datum und Uhrzeit',
            pl: 'Data i godzina',
        },
        comment: {
            ru: 'Комментарий',
            ua: 'Коментар',
            en: 'Comment',
            de: 'Kommentar',
            pl: 'Komentarz',
        },
        repeat: {
            ru: 'Повторить перевод',
            ua: 'Повторити переказ',
            en: 'Repeat transfer',
            de: 'Überweisung wiederholen',
            pl: 'Powtórz przelew',
        },
        reply: {
            ru: 'Перевести в ответ',
            ua: 'Переказати у відповідь',
            en: 'Send money back',
            de: 'Geld zurücksenden',
            pl: 'Odeślij pieniądze',
        },
        emptyIncome: {
            ru: 'Поступлений пока нет',
            ua: 'Надходжень поки немає',
            en: 'No incoming transactions yet',
            de: 'Noch keine Eingänge',
            pl: 'Brak wpływów',
        },
        emptyExpense: {
            ru: 'Списаний пока нет',
            ua: 'Списань поки немає',
            en: 'No spending yet',
            de: 'Noch keine Ausgaben',
            pl: 'Brak wydatków',
        },
        emptyHint: {
            ru: 'Здесь появятся все операции по основному счёту',
            ua: "Тут з'являться всі операції за основним рахунком",
            en: 'Every operation on the main account will show up here',
            de: 'Hier erscheinen alle Umsätze des Hauptkontos',
            pl: 'Tu pojawią się wszystkie operacje na koncie głównym',
        },
        end: {
            ru: 'Это все операции',
            ua: 'Це всі операції',
            en: 'That is everything',
            de: 'Das sind alle Umsätze',
            pl: 'To wszystkie operacje',
        },
    },

    card: {
        title: {
            ru: 'Карта',
            ua: 'Картка',
            en: 'Card',
            de: 'Karte',
            pl: 'Karta',
        },
        owner: {
            ru: 'Владелец',
            ua: 'Власник',
            en: 'Owner',
            de: 'Inhaber',
            pl: 'Właściciel',
        },
        account: {
            ru: 'Номер счёта',
            ua: 'Номер рахунку',
            en: 'Account number',
            de: 'Kontonummer',
            pl: 'Numer konta',
        },
        opened: {
            ru: 'Открыт',
            ua: 'Відкрито',
            en: 'Opened',
            de: 'Eröffnet',
            pl: 'Otwarte',
        },
        status: {
            ru: 'Статус',
            ua: 'Статус',
            en: 'Status',
            de: 'Status',
            pl: 'Status',
        },
        statusActive: {
            ru: 'Активна',
            ua: 'Активна',
            en: 'Active',
            de: 'Aktiv',
            pl: 'Aktywna',
        },
        copy: {
            ru: 'Скопировать номер счёта',
            ua: 'Скопіювати номер рахунку',
            en: 'Copy account number',
            de: 'Kontonummer kopieren',
            pl: 'Kopiuj numer konta',
        },
        copied: {
            ru: 'Номер счёта скопирован',
            ua: 'Номер рахунку скопійовано',
            en: 'Account number copied',
            de: 'Kontonummer kopiert',
            pl: 'Numer konta skopiowany',
        },
    },
};
