export default {
    callerActiveCall: {
        ru: 'Для начала завершите текущий вызов',
        ua: 'Для початку завершіть поточний виклик',
        en: 'Please end the current call first',
        de: 'Bitte beenden Sie zuerst den aktuellen Anruf',
        pl: 'Najpierw zakończ bieżące połączenie',
    },
    theSameNumber: {
        ru: 'Ты захотел поговорить с... Собой?',
        ua: 'Ти захотів поговорити з... Собою?',
        en: 'You wanted to talk to... Yourself?',
        de: 'Du wolltest mit... Dir selbst reden?',
        pl: 'Chcesz porozmawiać z... Sobą?',
    },
    targetBusy: {
        ru: 'Абонент сейчас занят, пожалуйста, позвоните позже',
        ua: 'Абонент зараз зайнятий, будь ласка, зателефонуйте пізніше',
        en: 'The subscriber is currently busy, please call again later',
        de: 'Der Teilnehmer ist zurzeit besetzt, bitte rufen Sie später noch einmal an',
        pl: 'Abonent jest teraz zajęty, proszę zadzwonić później',
    },
    noActive: {
        ru: 'Для этого пополните баланс вашей SIM-карты',
        ua: 'Для цього поповніть баланс вашої SIM-картки',
        en: 'To do this, top up your SIM card balance',
        de: 'Dazu müssen Sie Ihr SIM-Karten-Guthaben aufladen',
        pl: 'Aby to zrobić, doładuj saldo karty SIM',
    },
    notFound: {
        ru: 'Абонент не в штате либо номера не существует',
        ua: 'Абонент не в штаті або номера не існує',
        en: 'The subscriber is not in the state or the number does not exist',
        de: 'Der Teilnehmer ist nicht im Dienst oder die Nummer existiert nicht',
        pl: 'Abonent jest poza zasięgiem lub numer nie istnieje',
    },
    abonentDisconnect: {
        ru: 'Абонент вышел из штата',
        ua: 'Абонент вийшов зі штату',
        en: 'Player disconnected from the state',
        de: 'Spieler hat den Staat verlassen',
        pl: 'Gracz opuścił stan',
    },

    doNotDisturb: {
        ru: 'У абонента включен режим "Не беспокоить"',
        ua: 'У абонента ввімкнено режим "Не турбувати"',
        en: 'The subscriber has "Do Not Disturb" mode enabled',
        de: 'Der Teilnehmer hat den "Nicht stören"-Modus aktiviert',
        pl: 'Abonent ma włączony tryb "Nie przeszkadzać"',
    },

    statuses: {
        active: {
            ru: 'Активный звонок',
            ua: 'Активний дзвінок',
            en: 'Active call',
            de: 'Aktiver Anruf',
            pl: 'Aktywne połączenie',
        },
        incoming: {
            ru: 'Входящий звонок',
            ua: 'Вхідний дзвінок',
            en: 'Incoming call',
            de: 'Eingehender Anruf',
            pl: 'Połączenie przychodzące',
        },
        outgoing: {
            ru: 'Исходящий звонок',
            ua: 'Вихідний дзвінок',
            en: 'Outgoing call',
            de: 'Ausgehender Anruf',
            pl: 'Połączenie wychodzące',
        },
    },

    emergencyCall: {
        title: {
            ru: 'Вызов экстренной службы',
            ua: 'Виклик екстреної служби',
            en: 'Emergency Service Call',
            de: 'Notrufdienst anrufen',
            pl: 'Wezwanie służb ratunkowych',
        },
        chooseToCall: {
            ru: 'Выберите службу которую хотите вызвать',
            ua: 'Виберіть службу, яку хочете викликати',
            en: 'Choose the service you want to call',
            de: 'Wählen Sie den Dienst, den Sie anrufen möchten',
            pl: 'Wybierz służbę, którą chcesz wezwać',
        },
        calling: {
            ru: 'Вызов {{name}}',
            ua: 'Виклик {{name}}',
            en: 'Calling {{name}}',
            de: 'Rufe {{name}} an',
            pl: 'Wzywanie {{name}}',
        },
        youCallingTo: {
            ru: 'Вы собираетесь вызвать {{name}}',
            ua: 'Ви збираєтеся викликати {{name}}',
            en: 'You are about to call {{name}}',
            de: 'Sie sind dabei, {{name}} anzurufen',
            pl: 'Zamierzasz wezwać {{name}}',
        },
        reason: {
            ru: 'Причина вызова',
            ua: 'Причина виклику',
            en: 'Reason for the call',
            de: 'Grund des Anrufs',
            pl: 'Powód wezwania',
        },
        comment: {
            ru: 'Комментарий',
            ua: 'Коментар',
            en: 'Comment',
            de: 'Kommentar',
            pl: 'Komentarz',
        },
        danger: {
            ru: 'За ложный вызов вам могут дать штраф',
            ua: 'За хибний виклик вам можуть дати штраф',
            en: 'You may be fined for a false call',
            de: 'Für einen Fehlalarm droht eine Geldstrafe',
            pl: 'Za fałszywe wezwanie grozi kara grzywny',
        },
        back: {
            ru: '← Назад',
            ua: '← Назад',
            en: '← Back',
            de: '← Zurück',
            pl: '← Wstecz',
        },
        call: {
            ru: 'Вызвать',
            ua: 'Викликати',
            en: 'Call',
            de: 'Anrufen',
            pl: 'Wezwij',
        },
        enterComment: {
            ru: 'Введите комментарий',
            ua: 'Введіть коментар',
            en: 'Enter a comment',
            de: 'Kommentar eingeben',
            pl: 'Wprowadź komentarz',
        },
        chooseReason: {
            ru: 'Выберите причину',
            ua: 'Виберіть причину',
            en: 'Choose a reason',
            de: 'Wählen Sie einen Grund',
            pl: 'Wybierz powód',
        },
        notifySend: {
            ru: 'Ожидайте пока ваш запрос примут',
            ua: 'Очікуйте, поки ваш запит приймуть',
            en: 'Please wait while your request is being accepted',
            de: 'Bitte warten Sie, bis Ihre Anfrage angenommen wird',
            pl: 'Proszę czekać, aż twoje zgłoszenie zostanie zaakceptowane',
        },
        cooldown: {
            ru: 'Вы не давно уже вызывали экстренную службу, подождите немного',
            ua: 'Ви нещодавно вже викликали екстрену службу, зачекайте трохи',
            en: 'You have recently called the emergency service, please wait a moment',
            de: 'Sie haben vor kurzem bereits den Notdienst gerufen, bitte warten Sie einen Moment',
            pl: 'Niedawno wzywałeś już służby ratunkowe, poczekaj chwilę',
        },
        reasons: {
            murder: {
                ru: 'Убийство',
                ua: 'Вбивство',
                en: 'Murder',
                de: 'Mord',
                pl: 'Morderstwo',
            },
            robbery: {
                ru: 'Ограбление',
                ua: 'Пограбування',
                en: 'Robbery',
                de: 'Raubüberfall',
                pl: 'Rabunek',
            },
            theft: {
                ru: 'Кража',
                ua: 'Крадіжка',
                en: 'Theft',
                de: 'Diebstahl',
                pl: 'Kradzież',
            },
            fight: {
                ru: 'Драка',
                ua: 'Бійка',
                en: 'Fight',
                de: 'Schlägerei',
                pl: 'Bójka',
            },
            trafficViolation: {
                ru: 'Нарушение ПДД',
                ua: 'Порушення ПДР',
                en: 'Traffic violation',
                de: 'Verkehrsverstoß',
                pl: 'Wykroczenie drogowe',
            },
            vandalism: {
                ru: 'Вандализм',
                ua: 'Вандалізм',
                en: 'Vandalism',
                de: 'Vandalismus',
                pl: 'Wandalizm',
            },
            accident: {
                ru: 'Авария',
                ua: 'Аварія',
                en: 'Accident',
                de: 'Unfall',
                pl: 'Wypadek',
            },
            unconscious: {
                ru: 'Потеря сознания',
                ua: 'Втрата свідомості',
                en: 'Unconsciousness',
                de: 'Bewusstlosigkeit',
                pl: 'Utrata przytomności',
            },
            injury: {
                ru: 'Травма',
                ua: 'Травма',
                en: 'Injury',
                de: 'Verletzung',
                pl: 'Uraz',
            },
            overdose: {
                ru: 'Передозировка',
                ua: 'Передозування',
                en: 'Overdose',
                de: 'Überdosis',
                pl: 'Przedawkowanie',
            },
            heartAttack: {
                ru: 'Сердечный приступ',
                ua: 'Серцевий напад',
                en: 'Heart attack',
                de: 'Herzinfarkt',
                pl: 'Zawał serca',
            },
            other: {
                ru: 'Другое',
                ua: 'Інше',
                en: 'Other',
                de: 'Sonstiges',
                pl: 'Inne',
            },
        },
    },
};
