export default {
    callerActiveCall: {
        ru: 'Для начала завершите текущий вызов',
        ua: 'Для початку завершіть поточний виклик',
        en: 'Please end the current call first',
        de: 'Bitte beende zuerst den aktuellen Anruf',
        pl: 'Najpierw zakończ bieżące połączenie',
    },
    theSameNumber: {
        ru: 'Ты захотел поговорить с... Собой?',
        ua: 'Ти захотів поговорити з... Собою?',
        en: 'You wanted to talk to... Yourself?',
        de: 'Du wolltest mit... Dir selbst reden?',
        pl: 'Chcesz porozmawiać z... Sobą?',
    },
    targetBusy: {
        ru: 'Абонент сейчас занят, пожалуйста, позвоните позже',
        ua: 'Абонент зараз зайнятий, будь ласка, зателефонуйте пізніше',
        en: 'The subscriber is currently busy, please call again later',
        de: 'Der Teilnehmer ist zurzeit besetzt, bitte rufe später noch einmal an',
        pl: 'Abonent jest teraz zajęty, proszę zadzwonić później',
    },
    noActive: {
        ru: 'Для этого пополните баланс вашей SIM-карты',
        ua: 'Для цього поповніть баланс вашої SIM-картки',
        en: 'To do this, top up your SIM card balance',
        de: 'Dazu müssst du dein SIM-Karten-Guthaben aufladen',
        pl: 'Aby to zrobić, doładuj saldo karty SIM',
    },
    notFound: {
        ru: 'Абонент не в штате либо номера не существует',
        ua: 'Абонент не в штаті або номера не існує',
        en: 'The subscriber is not in the state or the number does not exist',
        de: 'Der Teilnehmer ist nicht im Dienst oder die Nummer existiert nicht',
        pl: 'Abonent jest poza zasięgiem lub numer nie istnieje',
    },
    abonentDisconnect: {
        ru: 'Абонент вышел из штата',
        ua: 'Абонент вийшов зі штату',
        en: 'Player disconnected from the state',
        de: 'Bürger hat den Staat verlassen',
        pl: 'Gracz opuścił stan',
    },

    doNotDisturb: {
        ru: 'У абонента включен режим "Не беспокоить"',
        ua: 'У абонента ввімкнено режим "Не турбувати"',
        en: 'The subscriber has "Do Not Disturb" mode enabled',
        de: 'Der Teilnehmer hat den "Nicht stören"-Modus aktiviert',
        pl: 'Abonent ma włączony tryb "Nie przeszkadzać"',
    },

    attorney: {
        noWanted: {
            ru: 'Соул: за тобой ничего не висит, приятель. Позвони, когда будет.',
            ua: 'Сол: за тобою нічого не висить, друже. Подзвони, коли буде.',
            en: 'Saul: nothing on you right now, buddy. Call me when there is.',
            de: 'Saul: gegen dich liegt nichts vor, Kumpel. Ruf an, wenn es so weit ist.',
            pl: 'Saul: nic na ciebie nie ma, kolego. Zadzwoń, gdy będzie.',
        },
        imprisoned: {
            ru: 'Соул: из камеры такие дела не решаются. Отсидишь и позвонишь.',
            ua: 'Сол: з камери такі справи не вирішуються. Відсидиш і подзвониш.',
            en: 'Saul: these things do not get fixed from a cell. Serve it and call me.',
            de: 'Saul: aus der Zelle regelt man das nicht. Sitz es ab und ruf mich an.',
            pl: 'Saul: z celi tego się nie załatwia. Odsiedź i zadzwoń.',
        },
        restrained: {
            ru: 'Соул: ты сейчас в наручниках, тут я бессилен.',
            ua: 'Сол: ти зараз у наручниках, тут я безсилий.',
            en: 'Saul: you are in cuffs right now, nothing I can do.',
            de: 'Saul: du bist in Handschellen, da kann ich nichts machen.',
            pl: 'Saul: jesteś w kajdankach, tu nic nie zrobię.',
        },
        cooldown: {
            ru: 'Соул: я уже вел твое дело, следующее возьму через {{time}}.',
            ua: 'Сол: я вже вів твою справу, наступну візьму через {{time}}.',
            en: 'Saul: I already handled a case of yours, the next one in {{time}}.',
            de: 'Saul: ich hatte schon einen Fall von dir, den nächsten in {{time}}.',
            pl: 'Saul: już prowadziłem twoją sprawę, następną wezmę za {{time}}.',
        },
        tooFresh: {
            ru: 'Соул: дело слишком свежее, ему всего {{age}}. Приходи через {{time}}.',
            ua: 'Сол: справа надто свіжа, їй лише {{age}}. Приходь через {{time}}.',
            en: 'Saul: the case is too fresh, it is only {{age}} old. Come back in {{time}}.',
            de: 'Saul: der Fall ist zu frisch, er ist erst {{age}} alt. Komm in {{time}} wieder.',
            pl: 'Saul: sprawa jest za świeża, ma dopiero {{age}}. Wróć za {{time}}.',
        },
        notEnoughCash: {
            ru: 'Соул: мой гонорар {{sum}} наличными. Приходи с деньгами.',
            ua: 'Сол: мій гонорар {{sum}} готівкою. Приходь з грошима.',
            en: 'Saul: my retainer is {{sum}} in cash. Come back with the money.',
            de: 'Saul: mein Honorar sind {{sum}} in bar. Komm mit dem Geld wieder.',
            pl: 'Saul: moje honorarium to {{sum}} w gotówce. Wróć z pieniędzmi.',
        },
        reduced: {
            ru: 'Соул: часть обвинений снял, розыск теперь {{to}} вместо {{from}}. Гонорар {{sum}}.',
            ua: 'Сол: частину обвинувачень зняв, розшук тепер {{to}} замість {{from}}. Гонорар {{sum}}.',
            en: 'Saul: got some charges dropped, your wanted level is {{to}} instead of {{from}}. Fee {{sum}}.',
            de: 'Saul: ein Teil der Anklagen ist weg, deine Fahndung steht jetzt auf {{to}} statt {{from}}. Honorar {{sum}}.',
            pl: 'Saul: część zarzutów zdjęta, twój poziom poszukiwania to teraz {{to}} zamiast {{from}}. Honorarium {{sum}}.',
        },
        cleared: {
            ru: 'Соул: все обвинения сняты, ты чист. Гонорар {{sum}}.',
            ua: 'Сол: усі обвинувачення зняті, ти чистий. Гонорар {{sum}}.',
            en: 'Saul: all charges dropped, you are clean. Fee {{sum}}.',
            de: 'Saul: alle Anklagen fallen gelassen, du bist sauber. Honorar {{sum}}.',
            pl: 'Saul: wszystkie zarzuty zdjęte, jesteś czysty. Honorarium {{sum}}.',
        },
    },

    statuses: {
        active: {
            ru: 'Активный звонок',
            ua: 'Активний дзвінок',
            en: 'Active call',
            de: 'Aktiver Anruf',
            pl: 'Aktywne połączenie',
        },
        incoming: {
            ru: 'Входящий звонок',
            ua: 'Вхідний дзвінок',
            en: 'Incoming call',
            de: 'Eingehender Anruf',
            pl: 'Połączenie przychodzące',
        },
        outgoing: {
            ru: 'Исходящий звонок',
            ua: 'Вихідний дзвінок',
            en: 'Outgoing call',
            de: 'Ausgehender Anruf',
            pl: 'Połączenie wychodzące',
        },
    },

    emergencyCall: {
        title: {
            ru: 'Вызов экстренной службы',
            ua: 'Виклик екстреної служби',
            en: 'Emergency Service Call',
            de: 'Notrufdienst anrufen',
            pl: 'Wezwanie służb ratunkowych',
        },
        chooseToCall: {
            ru: 'Выберите службу которую хотите вызвать',
            ua: 'Виберіть службу, яку хочете викликати',
            en: 'Choose the service you want to call',
            de: 'Wähle den Dienst, den du anrufen möchten',
            pl: 'Wybierz służbę, którą chcesz wezwać',
        },
        calling: {
            ru: 'Вызов {{name}}',
            ua: 'Виклик {{name}}',
            en: 'Calling {{name}}',
            de: 'Rufe {{name}} an',
            pl: 'Wzywanie {{name}}',
        },
        youCallingTo: {
            ru: 'Вы собираетесь вызвать {{name}}',
            ua: 'Ви збираєтеся викликати {{name}}',
            en: 'You are about to call {{name}}',
            de: 'Du bist dabei, {{name}} anzurufen',
            pl: 'Zamierzasz wezwać {{name}}',
        },
        reason: {
            ru: 'Причина вызова',
            ua: 'Причина виклику',
            en: 'Reason for the call',
            de: 'Grund des Anrufs',
            pl: 'Powód wezwania',
        },
        comment: {
            ru: 'Комментарий',
            ua: 'Коментар',
            en: 'Comment',
            de: 'Kommentar',
            pl: 'Komentarz',
        },
        danger: {
            ru: 'За ложный вызов вам могут дать штраф',
            ua: 'За хибний виклик вам можуть дати штраф',
            en: 'You may be fined for a false call',
            de: 'Für einen Fehlalarm droht eine Geldstrafe',
            pl: 'Za fałszywe wezwanie grozi kara grzywny',
        },
        back: {
            ru: '← Назад',
            ua: '← Назад',
            en: '← Back',
            de: '← Zurück',
            pl: '← Wstecz',
        },
        call: {
            ru: 'Вызвать',
            ua: 'Викликати',
            en: 'Call',
            de: 'Anrufen',
            pl: 'Wezwij',
        },
        enterComment: {
            ru: 'Введите комментарий',
            ua: 'Введіть коментар',
            en: 'Enter a comment',
            de: 'Kommentar eingeben',
            pl: 'Wprowadź komentarz',
        },
        chooseReason: {
            ru: 'Выберите причину',
            ua: 'Виберіть причину',
            en: 'Choose a reason',
            de: 'Wähle einen Grund',
            pl: 'Wybierz powód',
        },
        notifySend: {
            ru: 'Ожидайте пока ваш запрос примут',
            ua: 'Очікуйте, поки ваш запит приймуть',
            en: 'Please wait while your request is being accepted',
            de: 'Bitte warte bis deine Anfrage angenommen wird',
            pl: 'Proszę czekać, aż twoje zgłoszenie zostanie zaakceptowane',
        },
        cooldown: {
            ru: 'Вы не давно уже вызывали экстренную службу, подождите немного',
            ua: 'Ви нещодавно вже викликали екстрену службу, зачекайте трохи',
            en: 'You have recently called the emergency service, please wait a moment',
            de: 'Du hast vor kurzem bereits den Notdienst gerufen, bitte warte einen Moment',
            pl: 'Niedawno wzywałeś już służby ratunkowe, poczekaj chwilę',
        },
        sameFaction: {
            ru: 'Ты не можешь вызвать эту фракцию',
            ua: 'Ти не можеш викликати цю фракцію',
            en: "You can't summon this faction",
            de: 'Du kannst diese Fraktion nicht herbeirufen',
            pl: 'Nie możesz przywołać tej frakcji',
        },
        callFirst: {
            ru: 'Позвоните в 911 ещё раз, чтобы отправить вызов',
            ua: 'Зателефонуйте в 911 ще раз, щоб надіслати виклик',
            en: 'Call 911 again to send the request',
            de: 'Ruf erneut 911 an, um die Anfrage zu senden',
            pl: 'Zadzwoń ponownie pod 911, aby wysłać zgłoszenie',
        },
        invalidComment: {
            ru: 'Комментарий содержит недопустимые символы',
            ua: 'Коментар містить неприпустимі символи',
            en: 'The comment contains invalid characters',
            de: 'Der Kommentar enthält ungültige Zeichen',
            pl: 'Komentarz zawiera niedozwolone znaki',
        },
        reasons: {
            evacuation: {
                ru: 'Эвакуация ТС',
                ua: 'Евакуація ТЗ',
                en: 'Car tow',
                de: 'Autoabschleppung',
                pl: 'Holowanie auta',
            },
            murder: {
                ru: 'Убийство',
                ua: 'Вбивство',
                en: 'Murder',
                de: 'Mord',
                pl: 'Morderstwo',
            },
            robbery: {
                ru: 'Ограбление',
                ua: 'Пограбування',
                en: 'Robbery',
                de: 'Raubüberfall',
                pl: 'Rabunek',
            },
            theft: {
                ru: 'Кража',
                ua: 'Крадіжка',
                en: 'Theft',
                de: 'Diebstahl',
                pl: 'Kradzież',
            },
            fight: {
                ru: 'Драка',
                ua: 'Бійка',
                en: 'Fight',
                de: 'Schlägerei',
                pl: 'Bójka',
            },
            trafficViolation: {
                ru: 'Нарушение ПДД',
                ua: 'Порушення ПДР',
                en: 'Traffic violation',
                de: 'Verkehrsverstoß',
                pl: 'Wykroczenie drogowe',
            },
            vandalism: {
                ru: 'Вандализм',
                ua: 'Вандалізм',
                en: 'Vandalism',
                de: 'Vandalismus',
                pl: 'Wandalizm',
            },
            accident: {
                ru: 'Авария',
                ua: 'Аварія',
                en: 'Accident',
                de: 'Unfall',
                pl: 'Wypadek',
            },
            unconscious: {
                ru: 'Потеря сознания',
                ua: 'Втрата свідомості',
                en: 'Unconsciousness',
                de: 'Bewusstlosigkeit',
                pl: 'Utrata przytomności',
            },
            injury: {
                ru: 'Травма',
                ua: 'Травма',
                en: 'Injury',
                de: 'Verletzung',
                pl: 'Uraz',
            },
            overdose: {
                ru: 'Передозировка',
                ua: 'Передозування',
                en: 'Overdose',
                de: 'Überdosis',
                pl: 'Przedawkowanie',
            },
            heartAttack: {
                ru: 'Сердечный приступ',
                ua: 'Серцевий напад',
                en: 'Heart attack',
                de: 'Herzinfarkt',
                pl: 'Zawał serca',
            },
            kidnapping: {
                ru: 'Похищение',
                ua: 'Викрадення',
                en: 'Kidnapping',
                de: 'Entführung',
                pl: 'Porwanie',
            },
            terrorism: {
                ru: 'Терроризм',
                ua: 'Тероризм',
                en: 'Terrorism',
                de: 'Terrorismus',
                pl: 'Terroryzm',
            },
            organizedCrime: {
                ru: 'Организованная преступность',
                ua: 'Організована злочинність',
                en: 'Organized crime',
                de: 'Organisierte Kriminalität',
                pl: 'Przestępczość zorganizowana',
            },
            bankRobbery: {
                ru: 'Ограбление банка',
                ua: 'Пограбування банку',
                en: 'Bank robbery',
                de: 'Bankraub',
                pl: 'Napad na bank',
            },
            corruption: {
                ru: 'Коррупция',
                ua: 'Корупція',
                en: 'Corruption',
                de: 'Korruption',
                pl: 'Korupcja',
            },
            other: {
                ru: 'Другое',
                ua: 'Інше',
                en: 'Other',
                de: 'Sonstiges',
                pl: 'Inne',
            },
        },
    },
};
