export default {
    modes: {
        rear: {
            ru: 'Основная',
            ua: 'Основна',
            en: 'Rear',
            de: 'Hauptkamera',
            pl: 'Tylny',
        },
        front: {
            ru: 'Фронтальная',
            ua: 'Фронтальна',
            en: 'Front',
            de: 'Frontkamera',
            pl: 'Przedni',
        },
    },
    filters: {
        none: {
            ru: 'Без фильтра',
            ua: 'Без фільтра',
            en: 'No filter',
            de: 'Ohne Filter',
            pl: 'Bez filtra',
        },
        vintage: {
            ru: 'Винтаж',
            ua: 'Вінтаж',
            en: 'Vintage',
            de: 'Vintage',
            pl: 'Vintage',
        },
        noir: {
            ru: 'Нуар',
            ua: 'Нуар',
            en: 'Noir',
            de: 'Noir',
            pl: 'Noir',
        },
        sepia: {
            ru: 'Сепия',
            ua: 'Сепія',
            en: 'Sepia',
            de: 'Sepia',
            pl: 'Sepia',
        },
        toxic: {
            ru: 'Токсик',
            ua: 'Токсик',
            en: 'Toxic',
            de: 'Toxic',
            pl: 'Toksyczny',
        },
        dusk: {
            ru: 'Сумерки',
            ua: 'Сутінки',
            en: 'Dusk',
            de: 'Dämmerung',
            pl: 'Zmierzch',
        },
        frost: {
            ru: 'Холод',
            ua: 'Холод',
            en: 'Frost',
            de: 'Frost',
            pl: 'Chłód',
        },
        glamour: {
            ru: 'Гламур',
            ua: 'Гламур',
            en: 'Glamour',
            de: 'Glamour',
            pl: 'Glamour',
        },
        sunset: {
            ru: 'Закат',
            ua: 'Захід',
            en: 'Sunset',
            de: 'Sonnenuntergang',
            pl: 'Zachód',
        },
        amber: {
            ru: 'Янтарь',
            ua: 'Бурштин',
            en: 'Amber',
            de: 'Bernstein',
            pl: 'Bursztyn',
        },
        haze: {
            ru: 'Марево',
            ua: 'Марево',
            en: 'Haze',
            de: 'Flimmern',
            pl: 'Marzenie',
        },
        wave: {
            ru: 'Волна',
            ua: 'Хвиля',
            en: 'Wave',
            de: 'Welle',
            pl: 'Fala',
        },
    },
    hints: {
        shoot: {
            ru: 'Снять',
            ua: 'Зняти',
            en: 'Take photo',
            de: 'Foto machen',
            pl: 'Zrób zdjęcie',
        },
        flip: {
            ru: 'Объектив',
            ua: 'Об’єктив',
            en: 'Lens',
            de: 'Objektiv',
            pl: 'Obiektyw',
        },
        filter: {
            ru: 'Фильтр',
            ua: 'Фільтр',
            en: 'Filter',
            de: 'Filter',
            pl: 'Filtr',
        },
        zoom: {
            ru: 'Зум',
            ua: 'Зум',
            en: 'Zoom',
            de: 'Zoom',
            pl: 'Zoom',
        },
        exit: {
            ru: 'Выйти',
            ua: 'Вийти',
            en: 'Close',
            de: 'Schließen',
            pl: 'Zamknij',
        },
    },
    saved: {
        ru: 'Снимок в галерее',
        ua: 'Знімок у галереї',
        en: 'Photo saved to the gallery',
        de: 'Foto in der Galerie gespeichert',
        pl: 'Zdjęcie zapisane w galerii',
    },
    saveFailed: {
        ru: 'Не удалось сохранить снимок',
        ua: 'Не вдалося зберегти знімок',
        en: 'The photo could not be saved',
        de: 'Das Foto konnte nicht gespeichert werden',
        pl: 'Nie udało się zapisać zdjęcia',
    },
    galleryFull: {
        ru: 'Галерея заполнена - удалите старые снимки',
        ua: 'Галерея заповнена - видаліть старі знімки',
        en: 'The gallery is full - delete some photos',
        de: 'Die Galerie ist voll - lösche einige Fotos',
        pl: 'Galeria jest pełna - usuń stare zdjęcia',
    },
    errors: {
        inVehicle: {
            ru: 'Из машины не поснимаешь - выйди наружу',
            ua: 'З машини не познімаєш - вийди назовні',
            en: 'You cannot shoot from a car - step outside',
            de: 'Aus dem Auto lässt sich nicht fotografieren - steig aus',
            pl: 'Z samochodu nie zrobisz zdjęcia - wysiądź',
        },
        unavailable: {
            ru: 'Сейчас камеру не открыть',
            ua: 'Зараз камеру не відкрити',
            en: 'The camera cannot open right now',
            de: 'Die Kamera lässt sich gerade nicht öffnen',
            pl: 'Nie można teraz otworzyć aparatu',
        },
    },
};
