export default {
    desc: {
        ru: 'Все нужные локации в удобном приложении всегда под рукой.',
        ua: 'Всі потрібні локації у зручному додатку завжди під рукою.',
        en: 'All the necessary locations in a convenient application are always at your fingertips.',
        de: 'Alle notwendigen Standorte in einer praktischen App immer griffbereit.',
        pl: 'Wszystkie potrzebne lokalizacje w wygodnej aplikacji zawsze pod ręką.',
    },
    characters: {
        ru: 'Сюжетные персонажи',
        ua: 'Сюжетні персонажі',
        en: 'Story characters',
        de: 'Handlungscharaktere',
        pl: 'Postacie fabularne',
    },
    main: {
        name: 'Основные места',
        ua: 'Основні місця',
        en: 'Main places',
        de: 'Hauptorte',
        pl: 'Główne miejsca',
    },
    nearest: {
        name: 'Ближайшие места',
        ua: 'Найближчі місця',
        en: 'Nearest places',
        de: 'Nächste Orte',
        pl: 'Najbliższe miejsca',
    },
    jobs: {
        name: 'Работы',
        ua: 'Роботи',
        en: 'Jobs',
        de: 'Arbeiten',
        pl: 'Prace',
    },
    hobby: {
        name: 'Хобби',
        ua: 'Хобі',
        en: 'Hobbies',
        de: 'Hobbys',
        pl: 'Hobby',
    },
    faction: {
        name: 'Фракции',
        ua: 'Фракції',
        en: 'Factions',
        de: 'Fraktionen',
        pl: 'Frakcje',
    },
    property: {
        name: 'Ваше имущество',
        ua: 'Ваше майно',
        en: 'Your property',
        de: 'Dein Eigentum',
        pl: 'Twoja własność',
    },

    selectNotify: {
        ru: 'Метка к {{name}} установлена. Расстояние: {{distance}}',
        ua: 'Мітка до {{name}} встановлена. Відстань: {{distance}}',
        en: 'Label to {{name}} set. Distance: {{distance}}',
        de: 'Markierung zu {{name}} gesetzt. Entfernung: {{distance}}',
        pl: 'Etykieta do {{name}} ustawiona. Odległość: {{distance}}',
    },

    buyers: {
        ru: 'Скупщики',
        ua: 'Скупники',
        en: 'Buyers',
        de: 'Käufer',
        pl: 'Kupujący',
    },

    sellers: {
        ru: 'Продавцы',
        ua: 'Продавці',
        en: 'Sellers',
        de: 'Verkäufer',
        pl: 'Sprzedawcy',
    },

    clothesShops: {
        ru: 'Магазины одежды',
        ua: 'Магазини одягу',
        en: 'Clothes Shops',
        de: 'Bekleidungsgeschäfte',
        pl: 'Sklepy odzieżowe',
    },
    gasStations: {
        ru: 'Заправки',
        ua: 'Заправки',
        en: 'Gas Stations',
        de: 'Tankstellen',
        pl: 'Stacje benzynowe',
    },
    shop: {
        ru: 'Магазины 24/7',
        ua: 'Магазини 24/7',
        en: '24/7 Shops',
        de: '24/7 Geschäfte',
        pl: 'Sklepy 24/7',
    },
    rent: {
        ru: 'Аренда транспорта',
        ua: 'Оренда транспорту',
        en: 'Vehicle Rental',
        de: 'Fahrzeugvermietung',
        pl: 'Wypożyczalnie pojazdów',
    },
    barberShop: {
        ru: 'Барбершопы',
        ua: 'Барбершопи',
        en: 'Barber Shops',
        de: 'Friseursalons',
        pl: 'Barber shopy',
    },
    tattoo: {
        ru: 'Тату-салоны',
        ua: 'Тату-салони',
        en: 'Tattoo Parlors',
        de: 'Tattoo-Studios',
        pl: 'Salony tatuażu',
    },
    gunShop: {
        ru: 'Магазины оружия',
        ua: 'Магазини зброї',
        en: 'Gun Shops',
        de: 'Waffengeschäfte',
        pl: 'Sklepy z bronią',
    },
    bank: {
        ru: 'Банки',
        ua: 'Банки',
        en: 'Banks',
        de: 'Banken',
        pl: 'Banki',
    },
    atm: {
        ru: 'Банкоматы',
        ua: 'Банкомати',
        en: 'ATMs',
        de: 'Geldautomaten',
        pl: 'Bankomaty',
    },
    entertainments: {
        ru: 'Развлечения',
        ua: 'Розваги',
        en: 'Entertainments',
        de: 'Unterhaltung',
        pl: 'Rozrywka',
    },
    showroom: {
        ru: 'Дилерские центры',
        ua: 'Дилерські центри',
        en: 'Showrooms',
        de: 'Autohäuser',
        pl: 'Salony samochodowe',
    },
    tuning: {
        ru: 'Тюнинг',
        ua: 'Тюнінг',
        en: 'Tuning',
        de: 'Tuning',
        pl: 'Tuning',
    },
    fastFood: {
        ru: 'Фастфуд',
        ua: 'Фастфуд',
        en: 'Fast food',
        de: 'Fastfood',
        pl: 'Fast food',
    },
};
