export default {
    title: {
        ru: 'Группа',
        ua: 'Група',
        en: 'Group',
        de: 'Gruppe',
        pl: 'Grupa',
    },
    subtitleEmpty: {
        ru: 'Вы не состоите в группе',
        ua: 'Ви не перебуваєте в групі',
        en: 'You are not in a group',
        de: 'Du bist in keiner Gruppe',
        pl: 'Nie jesteś w grupie',
    },
    subtitle: {
        ru: '{{count}} из {{max}} участников',
        ua: '{{count}} з {{max}} учасників',
        en: '{{count}} of {{max}} members',
        de: '{{count}} von {{max}} Mitgliedern',
        pl: '{{count}} z {{max}} członków',
    },
    loading: {
        ru: 'Загружаем группу...',
        ua: 'Завантажуємо групу...',
        en: 'Loading the group...',
        de: 'Gruppe wird geladen...',
        pl: 'Wczytywanie grupy...',
    },
    emptyTitle: {
        ru: 'Играйте вместе',
        ua: 'Грайте разом',
        en: 'Play together',
        de: 'Gemeinsam spielen',
        pl: 'Grajcie razem',
    },
    intro: {
        ru: 'Общий чат, метки друг друга на карте и совместная работа с теми, кто рядом.',
        ua: 'Спільний чат, мітки одне одного на мапі та спільна робота з тими, хто поруч.',
        en: "A shared chat, each other's markers on the map, and work together with whoever is next to you.",
        de: 'Gemeinsamer Chat, eure Markierungen auf der Karte und gemeinsame Arbeit mit allen in deiner Nähe.',
        pl: 'Wspólny czat, wzajemne znaczniki na mapie i wspólna praca z tymi, którzy są obok.',
    },
    create: {
        ru: 'Создать группу',
        ua: 'Створити групу',
        en: 'Create group',
        de: 'Gruppe erstellen',
        pl: 'Utwórz grupę',
    },
    joinTitle: {
        ru: 'Вступить по коду',
        ua: 'Вступити за кодом',
        en: 'Join with a code',
        de: 'Mit Code beitreten',
        pl: 'Dołącz kodem',
    },
    join: {
        ru: 'Вступить',
        ua: 'Вступити',
        en: 'Join',
        de: 'Beitreten',
        pl: 'Dołącz',
    },
    joinHint: {
        ru: 'Попросите код у того, кто приглашает вас в группу.',
        ua: 'Попросіть код у того, хто запрошує вас до групи.',
        en: 'Ask whoever is inviting you for the group code.',
        de: 'Frag die Person, die dich einlädt, nach dem Gruppencode.',
        pl: 'Poproś o kod osobę, która zaprasza cię do grupy.',
    },
    inviteTitle: {
        ru: 'Пригласить в группу',
        ua: 'Запросити до групи',
        en: 'Invite to the group',
        de: 'In die Gruppe einladen',
        pl: 'Zaproś do grupy',
    },
    copy: {
        ru: 'Скопировать код',
        ua: 'Скопіювати код',
        en: 'Copy code',
        de: 'Code kopieren',
        pl: 'Skopiuj kod',
    },
    copied: {
        ru: 'Скопировано',
        ua: 'Скопійовано',
        en: 'Copied',
        de: 'Kopiert',
        pl: 'Skopiowano',
    },
    newCode: {
        ru: 'Новый код',
        ua: 'Новий код',
        en: 'New code',
        de: 'Neuer Code',
        pl: 'Nowy kod',
    },
    regenerateConfirm: {
        ru: 'Создать новый код? Старый сразу перестанет работать.',
        ua: 'Створити новий код? Старий одразу перестане працювати.',
        en: 'Make a new code? The old one stops working right away.',
        de: 'Neuen Code erstellen? Der alte funktioniert sofort nicht mehr.',
        pl: 'Utworzyć nowy kod? Stary od razu przestanie działać.',
    },
    regenerated: {
        ru: 'Код обновлён',
        ua: 'Код оновлено',
        en: 'Code updated',
        de: 'Code aktualisiert',
        pl: 'Kod zaktualizowany',
    },
    codeHint: {
        ru: 'Передайте код тому, кого хотите позвать: он введёт его в этом приложении.',
        ua: 'Передайте код тому, кого хочете покликати: він введе його в цьому застосунку.',
        en: 'Give the code to whoever you want to bring in: they enter it in this app.',
        de: 'Gib den Code weiter: Wer beitreten will, gibt ihn in dieser App ein.',
        pl: 'Przekaż kod osobie, którą chcesz zaprosić: wpisze go w tej aplikacji.',
    },
    membersSection: {
        ru: 'Участники',
        ua: 'Учасники',
        en: 'Members',
        de: 'Mitglieder',
        pl: 'Członkowie',
    },
    hudToggle: {
        ru: 'Показывать в HUD',
        ua: 'Показувати в HUD',
        en: 'Show on HUD',
        de: 'Im HUD anzeigen',
        pl: 'Pokazuj w HUD',
    },
    roles: {
        leader: {
            ru: 'Лидер',
            ua: 'Лідер',
            en: 'Leader',
            de: 'Leiter',
            pl: 'Lider',
        },
        deputy: {
            ru: 'Заместитель',
            ua: 'Заступник',
            en: 'Deputy',
            de: 'Vertreter',
            pl: 'Zastępca',
        },
        helper: {
            ru: 'Помощник',
            ua: 'Помічник',
            en: 'Helper',
            de: 'Helfer',
            pl: 'Pomocnik',
        },
        member: {
            ru: 'Участник',
            ua: 'Учасник',
            en: 'Member',
            de: 'Mitglied',
            pl: 'Członek',
        },
    },
    youRole: {
        ru: '{{role}}, это вы',
        ua: '{{role}}, це ви',
        en: '{{role}} (you)',
        de: '{{role}} (du)',
        pl: '{{role}} (ty)',
    },
    memberMeta: {
        ru: '{{role}}, ID {{id}}',
        ua: '{{role}}, ID {{id}}',
        en: '{{role}}, ID {{id}}',
        de: '{{role}}, ID {{id}}',
        pl: '{{role}}, ID {{id}}',
    },
    offline: {
        ru: 'Не в сети',
        ua: 'Не в мережі',
        en: 'Offline',
        de: 'Offline',
        pl: 'Offline',
    },
    voice: {
        ru: 'Голосовой чат',
        ua: 'Голосовий чат',
        en: 'Voice chat',
        de: 'Sprachchat',
        pl: 'Czat głosowy',
    },
    voiceOn: {
        ru: 'Включён',
        ua: 'Увімкнено',
        en: 'On',
        de: 'An',
        pl: 'Włączony',
    },
    voiceOff: {
        ru: 'Выключен',
        ua: 'Вимкнено',
        en: 'Off',
        de: 'Aus',
        pl: 'Wyłączony',
    },
    indicators: {
        ru: 'Индикаторы',
        ua: 'Індикатори',
        en: 'Markers',
        de: 'Markierungen',
        pl: 'Znaczniki',
    },
    indicatorsOn: {
        ru: 'Показаны',
        ua: 'Показано',
        en: 'Shown',
        de: 'Sichtbar',
        pl: 'Widoczne',
    },
    indicatorsOff: {
        ru: 'Скрыты',
        ua: 'Приховано',
        en: 'Hidden',
        de: 'Ausgeblendet',
        pl: 'Ukryte',
    },
    coopTitle: {
        ru: 'Совместная работа',
        ua: 'Спільна робота',
        en: 'Working together',
        de: 'Zusammenarbeit',
        pl: 'Wspólna praca',
    },
    coopNearby: {
        ru: 'Рядом с вами: {{count}}',
        ua: 'Поруч із вами: {{count}}',
        en: 'Next to you: {{count}}',
        de: 'In deiner Nähe: {{count}}',
        pl: 'Obok ciebie: {{count}}',
    },
    coopScope: {
        ru: 'До +{{percent}}% на {{count}} работах',
        ua: 'До +{{percent}}% на {{count}} роботах',
        en: 'Up to +{{percent}}% on {{count}} jobs',
        de: 'Bis +{{percent}}% bei {{count}} Jobs',
        pl: 'Do +{{percent}}% w {{count}} pracach',
    },
    coopAlone: {
        ru: 'Рядом нет участников группы',
        ua: 'Поруч немає учасників групи',
        en: 'No group members next to you',
        de: 'Keine Gruppenmitglieder in deiner Nähe',
        pl: 'Brak członków grupy w pobliżu',
    },
    coopExplain: {
        ru: 'Работайте на одной из этих работ вместе с участниками группы рядом, и каждый получит бонус к заработку.',
        ua: 'Працюйте на одній з цих робіт разом з учасниками групи поруч, і кожен отримає бонус до заробітку.',
        en: 'Work one of these jobs together with group members next to you, and each of you gets a bonus to your pay.',
        de: 'Arbeite in einem dieser Jobs zusammen mit Gruppenmitgliedern in deiner Nähe, und jeder bekommt einen Lohnbonus.',
        pl: 'Pracuj w jednej z tych prac razem z członkami grupy obok, a każdy dostanie bonus do zarobku.',
    },
    coopJobsTitle: {
        ru: 'Работы',
        ua: 'Роботи',
        en: 'Jobs',
        de: 'Jobs',
        pl: 'Prace',
    },
    coopTiersTitle: {
        ru: 'Бонус',
        ua: 'Бонус',
        en: 'Bonus',
        de: 'Bonus',
        pl: 'Bonus',
    },
    // Crew size, by Intl plural category (CoopSheet picks the form).
    coopCrew: {
        one: {
            ru: '{{count}} игрок',
            ua: '{{count}} гравець',
            en: '{{count}} player',
            de: '{{count}} Spieler',
            pl: '{{count}} gracz',
        },
        few: {
            ru: '{{count}} игрока',
            ua: '{{count}} гравці',
            en: '{{count}} players',
            de: '{{count}} Spieler',
            pl: '{{count}} gracze',
        },
        many: {
            ru: '{{count}} игроков',
            ua: '{{count}} гравців',
            en: '{{count}} players',
            de: '{{count}} Spieler',
            pl: '{{count}} graczy',
        },
        other: {
            ru: '{{count}} игрока',
            ua: '{{count}} гравця',
            en: '{{count}} players',
            de: '{{count}} Spieler',
            pl: '{{count}} gracza',
        },
    },
    gotIt: {
        ru: 'Понятно',
        ua: 'Зрозуміло',
        en: 'Got it',
        de: 'Verstanden',
        pl: 'Rozumiem',
    },
    coopBonus: {
        ru: 'до +{{percent}}%',
        ua: 'до +{{percent}}%',
        en: 'up to +{{percent}}%',
        de: 'bis +{{percent}}%',
        pl: 'do +{{percent}}%',
    },
    roleTitle: {
        ru: 'Роль',
        ua: 'Роль',
        en: 'Role',
        de: 'Rolle',
        pl: 'Rola',
    },
    colorTitle: {
        ru: 'Цвет на карте',
        ua: 'Колір на мапі',
        en: 'Colour on the map',
        de: 'Farbe auf der Karte',
        pl: 'Kolor na mapie',
    },
    leave: {
        ru: 'Покинуть группу',
        ua: 'Покинути групу',
        en: 'Leave group',
        de: 'Gruppe verlassen',
        pl: 'Opuść grupę',
    },
    leaveConfirm: {
        ru: 'Покинуть группу?',
        ua: 'Покинути групу?',
        en: 'Leave the group?',
        de: 'Die Gruppe verlassen?',
        pl: 'Opuścić grupę?',
    },
    leaveLeaderConfirm: {
        ru: 'Покинуть группу? Лидером станет другой участник.',
        ua: 'Покинути групу? Лідером стане інший учасник.',
        en: 'Leave the group? Another member becomes the leader.',
        de: 'Die Gruppe verlassen? Ein anderes Mitglied wird Leiter.',
        pl: 'Opuścić grupę? Liderem zostanie inny członek.',
    },
    disband: {
        ru: 'Распустить группу',
        ua: 'Розпустити групу',
        en: 'Disband group',
        de: 'Gruppe auflösen',
        pl: 'Rozwiąż grupę',
    },
    disbandConfirm: {
        ru: 'Распустить группу? Все участники выйдут из неё.',
        ua: 'Розпустити групу? Усі учасники вийдуть з неї.',
        en: 'Disband the group? Everyone will be removed from it.',
        de: 'Gruppe auflösen? Alle Mitglieder werden entfernt.',
        pl: 'Rozwiązać grupę? Wszyscy członkowie zostaną z niej usunięci.',
    },
    promote: {
        ru: 'Сделать лидером',
        ua: 'Зробити лідером',
        en: 'Make leader',
        de: 'Zum Leiter machen',
        pl: 'Uczyń liderem',
    },
    promoteConfirm: {
        ru: 'Передать лидерство {{name}}?',
        ua: 'Передати лідерство {{name}}?',
        en: 'Hand the lead to {{name}}?',
        de: 'Die Leitung an {{name}} übergeben?',
        pl: 'Przekazać przywództwo {{name}}?',
    },
    kick: {
        ru: 'Исключить из группы',
        ua: 'Виключити з групи',
        en: 'Remove from group',
        de: 'Aus der Gruppe entfernen',
        pl: 'Usuń z grupy',
    },
    kickConfirm: {
        ru: 'Исключить {{name}} из группы?',
        ua: 'Виключити {{name}} з групи?',
        en: 'Remove {{name}} from the group?',
        de: '{{name}} aus der Gruppe entfernen?',
        pl: 'Usunąć {{name}} z grupy?',
    },
    cancel: {
        ru: 'Отмена',
        ua: 'Скасувати',
        en: 'Cancel',
        de: 'Abbrechen',
        pl: 'Anuluj',
    },
};
