export default {
    yourVehicles: {
        ua: 'Ваш транспорт',
        en: 'Your Vehicles',
        ru: 'Ваш транспорт',
        de: 'Deine Fahrzeuge',
        pl: 'Twoje pojazdy',
        zh: '你的汽车',
    },
    findInput: {
        ua: 'Пошук автомобілів за назвою',
        en: 'Search for vehicles by name',
        ru: 'Поиск машин по названию',
        de: 'Suche nach Fahrzeugen nach Namen',
        pl: 'Wyszukaj pojazdy po nazwie',
        zh: '按名称搜索车辆',
    },
    familyBadge: {
        ru: 'Семья',
        ua: 'Сім\'я',
        en: 'Family',
        de: 'Familie',
        pl: 'Rodzina',
    },
    takenBadge: {
        ru: 'Занята',
        ua: 'Зайнята',
        en: 'Taken',
        de: 'Belegt',
        pl: 'Zajęte',
    },
    control: {
        km: {
            ru: 'км.',
            ua: 'км.',
            en: 'km',
            de: 'km',
            pl: 'km',
        },
        familyBadge: {
            ru: 'Семья',
            ua: 'Сім\'я',
            en: 'Family',
            de: 'Familie',
            pl: 'Rodzina',
        },
        familyMinRank: {
            ru: 'Мин. ранг: {{rank}}',
            ua: 'Мін. ранг: {{rank}}',
            en: 'Min rank: {{rank}}',
            de: 'Mind. Rang: {{rank}}',
            pl: 'Min. ranga: {{rank}}',
        },
        familyTakenBy: {
            ru: 'Машину уже взял {{name}}',
            ua: 'Машину вже взяв {{name}}',
            en: 'Vehicle is currently taken by {{name}}',
            de: 'Fahrzeug ist derzeit bei {{name}}',
            pl: 'Pojazd jest obecnie u {{name}}',
        },
        // Someone else's vehicle held on a key (server modules/vehicles/keys).
        keyAccessBadge: {
            ru: 'Доступ ключом',
            ua: 'Доступ за ключем',
            en: 'Key access',
            de: 'Zugang per Schlüssel',
            pl: 'Dostęp kluczem',
        },
        engines: {
            electric: {
                ru: 'Электрический',
                ua: 'Електричний',
                en: 'Electric',
                de: 'Elektrisch',
                pl: 'Elektryczny',
            },
            gasoline: {
                ru: 'Бензиновый',
                ua: 'Бензиновий',
                en: 'Gasoline',
                de: 'Benzin',
                pl: 'Benzynowy',
            },
        },
        info: {
            price: {
                ua: 'Ціна',
                en: 'Price',
                ru: 'Цена',
                de: 'Preis',
                pl: 'Cena',
                zh: '价格',
            },
            plate: {
                ua: 'Номери',
                en: 'Plate',
                ru: 'Номера',
                de: 'Kennzeichen',
                pl: 'Tablica rejestracyjna',
                zh: '盘子',
            },
            fuel: {
                ua: 'Паливо',
                en: 'Fuel',
                ru: 'Топливо',
                de: 'Kraftstoff',
                pl: 'Paliwo',
                zh: '燃料',
            },
            trunk: {
                ru: 'Багажник',
                ua: 'Багажник',
                en: 'Trunk',
                de: 'Kofferraum',
                pl: 'Bagażnik',
                zh: '树干',
            },
            class: {
                ua: 'Клас',
                en: 'Class',
                ru: 'Класс',
                de: 'Klasse',
                pl: 'Klasa',
                zh: '班级',
            },
            engine: {
                ru: 'Тип двигателя',
                ua: 'Тип двигуна',
                en: 'Engine type',
                de: 'Motortyp',
                pl: 'Typ silnika',
            },
            health: {
                ru: 'Состояние',
                ua: 'Стан',
                en: 'Condition',
                de: 'Zustand',
                pl: 'Stan',
            },
            mileage: {
                ua: 'Пробіг',
                en: 'Mileage',
                ru: 'Пробег',
                de: 'Kilometerstand',
                pl: 'Przebieg',
                zh: '里程数',
            },
            speed: {
                ua: 'Швидкість',
                en: 'Speed',
                ru: 'Скорость',
                de: 'Geschwindigkeit',
                pl: 'Prędkość',
                zh: '速度',
            },
            pessangers: {
                ua: 'Вмістимість',
                en: 'Passenger capacity',
                ru: 'Вместительность',
                de: 'Passagierkapazität',
                pl: 'Pojemność pasażerów',
                zh: '核载人数',
            },
        },
        buttons: {
            spawn: {
                despawn: {
                    ua: 'Прибрати',
                    en: 'Remove',
                    ru: 'Убрать',
                    de: 'Entfernen',
                    pl: 'Usuń',
                    zh: '移除',
                },
                spawn: {
                    ua: 'Спавнити',
                    en: 'Spawn',
                    ru: 'Заспавнить',
                    de: 'Spawnen',
                    pl: 'Spawnuj',
                    zh: '重生',
                },
            },
            blip: {
                remove: {
                    ua: 'Прибрати мітку',
                    en: 'Remove Marker',
                    ru: 'Убрать метку',
                    de: 'Markierung entfernen',
                    pl: 'Usuń znacznik',
                    zh: '取消标记',
                },
                show: {
                    ua: 'Мітка',
                    en: 'Marker',
                    ru: 'Метка',
                    de: 'Markierung',
                    pl: 'Znacznik',
                    zh: '标记',
                },
            },
            evacuateToGarage: {
                ua: 'Евакуювати',
                en: 'Tow',
                ru: 'Эвакуировать',
                de: 'Abschleppen',
                pl: 'Odholuj',
                zh: '拖车',
            },
            evacuated: {
                label: {
                    ua: 'Евакуювати',
                    en: 'Evacuate',
                    ru: 'Эвакуировать',
                    de: 'Evakuieren',
                    pl: 'Ewakuuj',
                    zh: '撤离',
                },
                additionalText: {
                    ua: '(${{price}})',
                    en: '(${{price}})',
                    ru: '(${{price}})',
                    de: '(${{price}})',
                    pl: '(${{price}})',
                    zh: '(${{price}})',
                },
            },
            remote: {
                ru: 'Управление',
                ua: 'Керування',
                en: 'Remote',
                de: 'Steuerung',
                pl: 'Sterowanie',
                zh: '遥控',
            },
            kickAll: {
                label: {
                    ua: 'Вигнати всіх',
                    en: 'Kick All',
                    ru: 'Выгнать всех',
                    de: 'Alle rausschmeißen',
                    pl: 'Wyrzuć wszystkich',
                    zh: '踢掉所有',
                },
            },
            delivery: {
                cancel: {
                    ua: 'Скасувати доставку',
                    en: 'Cancel Delivery',
                    ru: 'Отменить доставку',
                    de: 'Lieferung abbrechen',
                    pl: 'Anuluj dostawę',
                    zh: '取消运送',
                },
                delivery: {
                    ua: 'Доставити до себе',
                    en: 'Deliver to Me',
                    ru: 'Доставить к себе',
                    de: 'Zu mir liefern',
                    pl: 'Dostarcz do mnie',
                    zh: '交给我',
                },
                additionalText: {
                    ua: '(${{price}})',
                    en: '(${{price}})',
                    ru: '(${{price}})',
                    de: '(${{price}})',
                    pl: '(${{price}})',
                    zh: '(${{price}})',
                },
                free: {
                    ua: '(Безкоштовно)',
                    en: '(Free)',
                    ru: '(Бесплатно)',
                    de: '(Kostenlos)',
                    pl: '(Bezpłatnie)',
                    zh: '(Free)',
                },
            },
            restore: {
                restore: {
                    ru: 'Восстановить',
                    ua: 'Відновити',
                    en: 'Restore',
                    de: 'Wiederherstellen',
                    pl: 'Przywrócić',
                },
                free: {
                    ru: '(Бесплатно)',
                    ua: '(Безкоштовно)',
                    en: '(Free)',
                    de: '(Kostenlos)',
                    pl: '(Bezpłatnie)',
                    zh: '(Free)',
                },
            },
            inGarage: {
                ru: 'Доставить с гаража',
                ua: 'Доставити з гаража',
                en: 'Deliver from garage',
                de: 'Aus der Garage liefern',
                pl: 'Dostarcz z garażu',
            },
            familyDeliver: {
                ru: 'Доставить к себе',
                ua: 'Доставити до себе',
                en: 'Deliver to me',
                de: 'Zu mir liefern',
                pl: 'Dostarcz do mnie',
            },
            familyReturn: {
                ru: 'В гараж',
                ua: 'В гараж',
                en: 'To garage',
                de: 'In die Garage',
                pl: 'Do garażu',
            },
            impounded: {
                ru: 'Т/С находится на штрафстоянке #{{lotId}}',
                ua: 'ТЗ знаходиться на штрафмайданчику #{{lotId}}',
                en: 'The vehicle is impounded at lot #{{lotId}}',
                de: 'Das Fahrzeug steht auf dem Abschleppplatz #{{lotId}}',
                pl: 'Pojazd znajduje się na parkingu policyjnym #{{lotId}}',
            },
        },
        remote: {
            title: {
                ru: 'Удалённое управление',
                ua: 'Дистанційне керування',
                en: 'Remote control',
                de: 'Fernsteuerung',
                pl: 'Zdalne sterowanie',
                zh: '远程控制',
            },
            back: {
                ru: 'Назад',
                ua: 'Назад',
                en: 'Back',
                de: 'Zurück',
                pl: 'Wstecz',
                zh: '返回',
            },
            engineOn: {
                ru: 'Запустить двигатель',
                ua: 'Запустити двигун',
                en: 'Start the engine',
                de: 'Motor starten',
                pl: 'Uruchom silnik',
                zh: '启动发动机',
            },
            engineOff: {
                ru: 'Заглушить двигатель',
                ua: 'Заглушити двигун',
                en: 'Stop the engine',
                de: 'Motor abstellen',
                pl: 'Wyłącz silnik',
                zh: '关闭发动机',
            },
            trunkOpen: {
                ru: 'Открыть багажник',
                ua: 'Відкрити багажник',
                en: 'Open the trunk',
                de: 'Kofferraum öffnen',
                pl: 'Otwórz bagażnik',
                zh: '打开后备箱',
            },
            trunkClose: {
                ru: 'Закрыть багажник',
                ua: 'Закрити багажник',
                en: 'Close the trunk',
                de: 'Kofferraum schließen',
                pl: 'Zamknij bagażnik',
                zh: '关闭后备箱',
            },
            lightsOn: {
                ru: 'Включить фары',
                ua: 'Увімкнути фари',
                en: 'Turn the lights on',
                de: 'Licht einschalten',
                pl: 'Włącz światła',
                zh: '打开车灯',
            },
            lightsOff: {
                ru: 'Выключить фары',
                ua: 'Вимкнути фари',
                en: 'Turn the lights off',
                de: 'Licht ausschalten',
                pl: 'Wyłącz światła',
                zh: '关闭车灯',
            },
            neonOn: {
                ru: 'Включить неон',
                ua: 'Увімкнути неон',
                en: 'Turn the neon on',
                de: 'Neon einschalten',
                pl: 'Włącz neon',
                zh: '打开霓虹灯',
            },
            neonOff: {
                ru: 'Выключить неон',
                ua: 'Вимкнути неон',
                en: 'Turn the neon off',
                de: 'Neon ausschalten',
                pl: 'Wyłącz neon',
                zh: '关闭霓虹灯',
            },
            lock: {
                ru: 'Закрыть двери',
                ua: 'Закрити двері',
                en: 'Lock the doors',
                de: 'Türen verriegeln',
                pl: 'Zamknij drzwi',
                zh: '锁上车门',
            },
            unlock: {
                ru: 'Открыть двери',
                ua: 'Відкрити двері',
                en: 'Unlock the doors',
                de: 'Türen entriegeln',
                pl: 'Otwórz drzwi',
                zh: '打开车门',
            },
            horn: {
                ru: 'Посигналить',
                ua: 'Посигналити',
                en: 'Sound the horn',
                de: 'Hupen',
                pl: 'Zatrąb',
                zh: '鸣笛',
            },
            kickAll: {
                ru: 'Выгнать всех',
                ua: 'Вигнати всіх',
                en: 'Kick everyone out',
                de: 'Alle rausschmeißen',
                pl: 'Wyrzuć wszystkich',
                zh: '踢出所有人',
            },
            headlightColor: {
                ru: 'Цвет фар',
                ua: 'Колір фар',
                en: 'Headlight color',
                de: 'Scheinwerferfarbe',
                pl: 'Kolor reflektorów',
                zh: '大灯颜色',
            },
            neonColor: {
                ru: 'Цвет неона',
                ua: 'Колір неона',
                en: 'Neon color',
                de: 'Neonfarbe',
                pl: 'Kolor neonu',
                zh: '霓虹灯颜色',
            },
            dashboardColor: {
                ru: 'Цвет подсветки салона',
                ua: 'Колір підсвітки салону',
                en: 'Interior lighting color',
                de: 'Farbe der Innenbeleuchtung',
                pl: 'Kolor podświetlenia wnętrza',
                zh: '车内灯光颜色',
            },
            suspension: {
                ru: 'Пневмоподвеска',
                ua: 'Пневмопідвіска',
                en: 'Air suspension',
                de: 'Luftfederung',
                pl: 'Zawieszenie pneumatyczne',
                zh: '空气悬挂',
            },
            suspensionUnit: {
                ru: 'см',
                ua: 'см',
                en: 'cm',
                de: 'cm',
                pl: 'cm',
                zh: '厘米',
            },
            suspensionUp: {
                ru: 'Верхнее положение',
                ua: 'Верхнє положення',
                en: 'Upper position',
                de: 'Obere Position',
                pl: 'Pozycja górna',
                zh: '最高位置',
            },
            suspensionDown: {
                ru: 'Нижнее положение',
                ua: 'Нижнє положення',
                en: 'Lower position',
                de: 'Untere Position',
                pl: 'Pozycja dolna',
                zh: '最低位置',
            },
        },
        deliveryInProcess: {
            ua: 'Доставка триває',
            en: 'Delivery in progress',
            ru: 'Доставка идёт',
            de: 'Lieferung läuft',
            pl: 'Trwa dostawa',
            zh: '正在交货',
        },
        delivery: {
            ua: 'Доставити до себе',
            en: 'Deliver to Me',
            ru: 'Доставить к себе',
            de: 'Zu mir liefern',
            pl: 'Dostarcz do mnie',
            zh: '交给我',
        },
        unavailable: {
            ua: 'Недоступно',
            en: 'Unavailable',
            ru: 'Недоступно',
            de: 'Nicht verfügbar',
            pl: 'Niedostępne',
            zh: '不可用',
        },
        vehicleClasses: {
            compact: {
                ua: 'Компактні',
                en: 'Compact',
                ru: 'Компактные',
                de: 'Kompakt',
                pl: 'Kompaktowe',
                zh: '紧凑型',
            },
            sedan: {
                ua: 'Седани',
                en: 'Sedans',
                ru: 'Седаны',
                de: 'Limousinen',
                pl: 'Sedany',
                zh: '车型',
            },
            suv: {
                ua: 'Позашляховики',
                en: 'SUVs',
                ru: 'Внедорожники',
                de: 'SUVs',
                pl: 'SUV-y',
                zh: 'SUVs',
            },
            coupe: {
                ua: 'Купе',
                en: 'Coupes',
                ru: 'Купе',
                de: 'Coupés',
                pl: 'Coupé',
                zh: '轿车',
            },
            muscle: {
                ua: `М'юскл-кари`,
                en: 'Muscle Cars',
                ru: 'Мускул-кары',
                de: 'Muscle Cars',
                pl: 'Muscle Cars',
                zh: '肌肉车',
            },
            classicSport: {
                ua: 'Класичні спорткари',
                en: 'Classic Sports Cars',
                ru: 'Классические спорткары',
                de: 'Klassische Sportwagen',
                pl: 'Klasyczne samochody sportowe',
                zh: '经典跑车',
            },
            sports: {
                ua: 'Спортивні автомобілі',
                en: 'Sports Cars',
                ru: 'Спортивные автомобили',
                de: 'Sportwagen',
                pl: 'Samochody sportowe',
                zh: '越野车',
            },
            super: {
                ua: 'Суперкари',
                en: 'Supercars',
                ru: 'Суперкары',
                de: 'Supersportwagen',
                pl: 'Supersamochody',
                zh: '超级跑车',
            },
            motorcycles: {
                ua: 'Мотоцикли',
                en: 'Motorcycles',
                ru: 'Мотоциклы',
                de: 'Motorräder',
                pl: 'Motocykle',
                zh: '摩托车',
            },
            industrial: {
                ua: 'Промислові',
                en: 'Industrial',
                ru: 'Промышленные',
                de: 'Industriell',
                pl: 'Przemysłowe',
                zh: '工业车辆',
            },
            utility: {
                ua: 'Утилітарні',
                en: 'Utility',
                ru: 'Утилитарные',
                de: 'Nutzfahrzeuge',
                pl: 'Użytkowe',
                zh: '公共服务',
            },
            vans: {
                ua: 'Фургони',
                en: 'Vans',
                ru: 'Фургоны',
                de: 'Lieferwagen',
                pl: 'Vany',
                zh: '大蓬货车',
            },
            bicycles: {
                ua: 'Велосипеди',
                en: 'Bicycles',
                ru: 'Велосипеды',
                de: 'Fahrräder',
                pl: 'Rowery',
                zh: '自行车',
            },
            boats: {
                ua: 'Човни',
                en: 'Boats',
                ru: 'Лодки',
                de: 'Boote',
                pl: 'Łodzie',
                zh: '船',
            },
            helicopters: {
                ua: 'Вертольоти',
                en: 'Helicopters',
                ru: 'Вертолеты',
                de: 'Helikopter',
                pl: 'Śmigłowce',
                zh: '直升机',
            },
            planes: {
                ua: 'Літаки',
                en: 'Planes',
                ru: 'Самолеты',
                de: 'Flugzeuge',
                pl: 'Samoloty',
                zh: '飞机',
            },
            service: {
                ua: 'Службові',
                en: 'Service',
                ru: 'Служебные',
                de: 'Dienstwagen',
                pl: 'Służbowe',
                zh: '服务',
            },
            emergency: {
                ua: 'Екстрені',
                en: 'Emergency',
                ru: 'Экстренные',
                de: 'Notfall',
                pl: 'Pojazdy ratunkowe',
                zh: '紧急情况',
            },
            military: {
                ua: 'Військові',
                en: 'Military',
                ru: 'Военные',
                de: 'Militär',
                pl: 'Wojskowe',
                zh: '军事',
            },
            commercial: {
                ua: 'Комерційні',
                en: 'Commercial',
                ru: 'Коммерческие',
                de: 'Gewerblich',
                pl: 'Komercyjne',
                zh: '商业广告',
            },
            trains: {
                ua: 'Поїзди',
                en: 'Trains',
                ru: 'Поезда',
                de: 'Züge',
                pl: 'Pociągi',
                zh: '火车',
            },
            convertibles: {
                ua: 'Кабріолети',
                en: 'Convertibles',
                ru: 'Открытые автомобили',
                de: 'Cabrios',
                pl: 'Kabriolety',
                zh: '敞篷车',
            },
        },
    },
};
