export const server = {
    action: {
        ru: 'Для взаимодействия нажмите',
        ua: 'Для взаємодії натисніть',
        en: 'Press to interact',
        de: 'Drücken Sie, um zu interagieren',
        pl: 'Naciśnij, aby interakcji',
    },
    productShop: {
        ru: 'Чтобы открыть магазин 24/7',
        ua: 'Щоб відкрити магазин 24/7',
        en: 'To open the 24/7 store',
        de: 'Um den 24/7 Laden zu öffnen',
        pl: 'Aby otworzyć sklep 24/7',
    },
    weaponShop: {
        ru: 'Чтобы открыть каталог магазина оружия',
        ua: 'Щоб відкрити каталог магазину зброї',
        en: 'To open the weapon shop catalog',
        de: 'Um den Waffenladenkatalog zu öffnen',
        pl: 'Aby otworzyć katalog sklepu z bronią',
    },
    clothesShop: {
        ru: 'Чтобы открыть каталог магазина одежды',
        ua: 'Щоб відкрити каталог магазину одягу',
        en: 'To open the clothing store catalog',
        de: 'Um den Kleidungsladenkatalog zu öffnen',
        pl: 'Aby otworzyć katalog sklepu odzieżowego',
    },
    pickupItem: {
        ru: 'Чтобы подобрать предмет, нажмите',
        ua: 'Щоб підібрати предмет, натисніть',
        en: 'To pick up the item, press',
        de: 'Um den Gegenstand aufzuheben, drücken Sie',
        pl: 'Aby podnieść przedmiot, naciśnij',
    },
    truckerMenu: {
        ru: 'Чтобы открыть меню дальнобойщика',
        ua: 'Щоб відкрити меню дальнобойщика',
        en: 'To open the trucker menu',
        de: 'Um das Trucker-Menü zu öffnen',
        pl: 'Aby otworzyć menu truckera',
    },
    deliveryMenu: {
        ru: 'Чтобы открыть меню доставки еды',
        ua: 'Щоб відкрити меню доставки їжі',
        en: 'To open the food delivery menu',
        de: 'Um das Menü für die Lieferung von Essen zu öffnen',
        pl: 'Aby otworzyć menu dostawy jedzenia',
    },
    job: {
        ru: 'Чтобы открыть меню устройства на работу нажмите',
        ua: 'Щоб відкрити меню пристрою на роботу, натисніть',
        en: 'To open the job device menu, press',
        de: 'Um das Arbeitsgerätemenü zu öffnen, drücken Sie',
        pl: 'Aby otworzyć menu urządzenia na pracę, naciśnij',
    },
    rent: {
        ua: 'Щоб відкрити меню оренди',
        en: 'To open the rental menu',
        ru: 'Чтобы открыть меню аренды',
        de: 'Um das Mietmenü zu öffnen',
        pl: 'Aby otworzyć menu wynajmu',
    },
    carshop: {
        ua: 'Щоб відкрити меню автосалону',
        en: 'To open the car shop menu',
        ru: 'Чтобы открыть меню автосалона',
        de: 'Um das Menü des Autohauses zu öffnen',
        pl: 'Aby otworzyć menu salonu samochodowego',
    },
    lsc: {
        ua: 'Щоб відкрити меню тюнінг-ательє',
        en: 'To open the tuning workshop menu',
        ru: 'Чтобы открыть меню тюнинг-ателье',
        de: 'Um das Menü der Tuning-Werkstatt zu öffnen',
        pl: 'Aby otworzyć menu warsztatu tuningowego',
    },
    atm: {
        ua: 'Щоб відкрити меню банкомату',
        en: 'To open the ATM menu',
        ru: 'Чтобы открыть меню банкомата',
        de: 'Um das ATM-Menü zu öffnen',
        pl: 'Aby otworzyć menu bankomatu',
    },
    bank: {
        ua: 'Щоб відкрити меню банка',
        en: 'To open the bank menu',
        ru: 'Чтобы открыть меню банка',
        de: 'Um das Bank-Menü zu öffnen',
        pl: 'Aby otworzyć menu banku',
    },
    arrest: {
        ru: 'Оформление',
        ua: 'Оформлення',
        en: 'Processing',
        de: 'Bearbeitung',
        pl: 'Przetwarzanie',
    },
    toTalk: {
        ru: 'Чтобы поговорить нажмите',
        ua: 'Щоб поговорити натисніть',
        en: 'To talk, click',
        de: 'Um zu sprechen, klicken Sie auf',
        pl: 'Aby porozmawiać, kliknij',
    },
    houseInventory: {
        ru: 'Чтобы открыть инвентарь дома нажмите',
        ua: 'Щоб відкрити інвентар дома, натисніть',
        en: 'To open the house inventory, press',
        de: 'Um das Hausinventar zu öffnen, drücken Sie',
        pl: 'Aby otworzyc magazyn domu, naciśnij',
    },
};
