export default {
    interaction: {
        ru: 'Взаимодействие',
        ua: 'Взаємодія',
        en: 'Interaction',
        de: 'Interaktion',
        pl: 'Interakcja',
    },
    'interaction.self': {
        ru: 'Взаимодействие с собой',
        ua: 'Взаємодія з собою',
        en: 'Interaction with yourself',
        de: 'Interaktion mit sich selbst',
        pl: 'Interakcja ze sobą',
    },
    'interaction.others': {
        ru: 'Взаимодействие с окружающими',
        ua: 'Взаємодія з оточенням',
        en: 'Interaction with surroundings',
        de: 'Interaktion mit der Umgebung',
        pl: 'Interakcja z otoczeniem',
    },
    'interaction.quick.lock': {
        ru: 'Закрыть/открыть транспорт',
        ua: 'Зачинити/відчинити транспорт',
        en: 'Lock/unlock vehicle',
        de: 'Fahrzeug ab-/aufschließen',
        pl: 'Zamknij/otwórz pojazd',
    },
    'interaction.quick.trunk': {
        ru: 'Открыть/закрыть багажник для других игроков',
        ua: 'Відчинити/зачинити багажник для інших гравців',
        en: 'Open/close trunk for other players',
        de: 'Kofferraum für andere Spieler öffnen/schließen',
        pl: 'Otwórz/zamknij bagażnik dla innych graczy',
    },
    'interaction.quick.trunkInventory': {
        ru: 'Открыть багажник',
        ua: 'Відкрити багажник',
        en: 'Open trunk contents',
        de: 'Kofferrauminhalt öffnen',
        pl: 'Otwórz zawartość bagażnika',
    },
    'interaction.quick.musicPlayer': {
        ru: 'Плеер',
        ua: 'Плеєр',
        en: 'Music player',
        de: 'Musikplayer',
        pl: 'Odtwarzacz',
    },
    'interaction.quick.passport': {
        ru: 'Показать паспорт',
        ua: 'Показати паспорт',
        en: 'Show passport',
        de: 'Reisepass zeigen',
        pl: 'Pokaż paszport',
    },
    'interaction.quick.drivingLicenses': {
        ru: 'Показать водительское удостоверение',
        ua: 'Показати посвідчення водія',
        en: 'Show driving license',
        de: 'Führerschein zeigen',
        pl: 'Pokaż prawo jazdy',
    },
    'interaction.quick.licenses': {
        ru: 'Показать лицензии',
        ua: 'Показати ліцензії',
        en: 'Show licenses',
        de: 'Lizenzen zeigen',
        pl: 'Pokaż licencje',
    },
    inventory: {
        ru: 'Инвентарь',
        ua: 'Інвентар',
        en: 'Inventory',
        de: 'Inventar',
        pl: 'Ekwipunek',
    },
    exit: {
        ru: 'Закрыть',
        ua: 'Закрити',
        en: 'Close',
        de: 'Schließen',
        pl: 'Zamknij',
    },
    click: {
        ru: 'Действие (клик)',
        ua: 'Дія (клік)',
        en: 'Action (click)',
        de: 'Aktion (Klick)',
        pl: 'Akcja (klik)',
    },
    voice: {
        ru: 'Голосовой чат',
        ua: 'Голосовий чат',
        en: 'Voice chat',
        de: 'Sprachchat',
        pl: 'Czat głosowy',
    },
    'party.voice': {
        ru: 'Голосовой чат группы',
        ua: 'Голосовий чат групи',
        en: 'Group voice chat',
        de: 'Gruppen-Sprachchat',
        pl: 'Czat głosowy grupy',
    },
    seatBelt: {
        ru: 'Ремень безопасности',
        ua: 'Пас безпеки',
        en: 'Seat belt',
        de: 'Sicherheitsgurt',
        pl: 'Pasy bezpieczeństwa',
    },
    testDriveExit: {
        ru: 'Выйти из тест-драйва',
        ua: 'Вийти з тест-драйву',
        en: 'Exit test drive',
        de: 'Probefahrt beenden',
        pl: 'Zakończ jazdę próbną',
    },
    fingerPointing: {
        ru: 'Указать пальцем',
        ua: 'Вказати пальцем',
        en: 'Point with finger',
        de: 'Mit dem Finger zeigen',
        pl: 'Wskazać palcem',
    },
    cruiseControl: {
        ru: 'Круиз-контроль',
        ua: 'Круїз-контроль',
        en: 'Cruise control',
        de: 'Tempomat',
        pl: 'Tempomat',
    },
    accept: {
        ru: 'Принять',
        ua: 'Прийняти',
        en: 'Accept',
        de: 'Annehmen',
        pl: 'Przyjąć',
    },
    refuse: {
        ru: 'Отказать',
        ua: 'Відмовити',
        en: 'Refuse',
        de: 'Ablehnen',
        pl: 'Odmówić',
    },
    animations: {
        ru: 'Меню анимаций',
        ua: 'Меню анімацій',
        en: 'Animations menu',
        de: 'Animationsmenü',
        pl: 'Menu animacji',
    },
    toggleHud: {
        ru: 'Показать/скрыть HUD',
        ua: 'Показати/сховати HUD',
        en: 'Show/hide HUD',
        de: 'HUD ein-/ausblenden',
        pl: 'Pokaż/ukryj HUD',
    },
    chat: {
        ru: 'Открыть чат',
        ua: 'Відкрити чат',
        en: 'Open chat',
        de: 'Chat öffnen',
        pl: 'Otwórz czat',
    },
    engine: {
        ru: 'Двигатель',
        ua: 'Двигун',
        en: 'Engine',
        de: 'Motor',
        pl: 'Silnik',
    },
    menu: {
        ru: 'Меню',
        ua: 'Меню',
        en: 'Menu',
        de: 'Menü',
        pl: 'Menu',
    },
    phone: {
        ru: 'Телефон',
        ua: 'Телефон',
        en: 'Phone',
        de: 'Telefon',
        pl: 'Telefon',
    },
    raiseDrop: {
        ru: 'Подобрать предмет',
        ua: 'Підібрати предмет',
        en: 'Pick up item',
        de: 'Gegenstand aufheben',
        pl: 'Podnieś przedmiot',
    },
    stopAnimation: {
        ru: 'Остановить анимацию',
        ua: 'Зупинити анімацію',
        en: 'Stop animation',
        de: 'Animation stoppen',
        pl: 'Zatrzymaj animację',
    },
    console: {
        ru: 'Консоль',
        ua: 'Консоль',
        en: 'Console',
        de: 'Konsole',
        pl: 'Konsola',
    },
    animationsWheel: {
        ru: 'Колесо анимаций',
        ua: 'Колесо анімацій',
        en: 'Animations wheel',
        de: 'Animationsrad',
        pl: 'Koło animacji',
    },
    tpWaypoint: {
        ru: 'Телепорт к метке',
        ua: 'Телепорт до точки',
        en: 'Teleport to waypoint',
        de: 'Teleport zum Wegpunkt',
        pl: 'Teleport do punktu',
    },
    cursor: {
        ru: 'Курсор',
        ua: 'Курсор',
        en: 'Cursor',
        de: 'Cursor',
        pl: 'Kursor',
    },
    ping: {
        ru: 'Метка (пинг)',
        ua: 'Мітка (пінг)',
        en: 'Ping marker',
        de: 'Markierung (Ping)',
        pl: 'Znacznik (ping)',
    },
    'trucker.dropBox': {
        ru: 'Выкинуть груз',
        ua: 'Викинути вантаж',
        en: 'Drop cargo',
        de: 'Ladung abwerfen',
        pl: 'Wyrzuć ładunek',
    },
    'garbage.dropBag': {
        ru: 'Выкинуть мусор',
        ua: 'Викинути сміття',
        en: 'Drop garbage bag',
        de: 'Mülltüte wegwerfen',
        pl: 'Wyrzuć worek ze śmieciami',
    },
    'airCargo.forkUp': {
        ru: 'Поднять вилы погрузчика',
        ua: 'Підняти вила навантажувача',
        en: 'Raise forklift forks',
        de: 'Gabelstaplergabeln heben',
        pl: 'Podnieś widły wózka',
    },
    'airCargo.forkDown': {
        ru: 'Опустить вилы погрузчика',
        ua: 'Опустити вила навантажувача',
        en: 'Lower forklift forks',
        de: 'Gabelstaplergabeln senken',
        pl: 'Opuść widły wózka',
    },
    'burglar.dropItem': {
        ru: 'Поставить краденое',
        ua: 'Поставити крадене',
        en: 'Put down stolen item',
        de: 'Diebesgut abstellen',
        pl: 'Odłóż skradziony przedmiot',
    },
    'organizations.contracts.dropCrate': {
        ru: 'Выбросить ящик контракта',
        ua: 'Викинути ящик контракту',
        en: 'Drop the contract crate',
        de: 'Vertragskiste wegwerfen',
        pl: 'Wyrzuć skrzynię kontraktu',
    },
    'weapon-heavy': {
        ru: 'Тяжёлое оружие',
        ua: 'Важка зброя',
        en: 'Heavy weapon',
        de: 'Schwere Waffe',
        pl: 'Ciężka broń',
    },
    'weapon-pistol': {
        ru: 'Пистолет',
        ua: 'Пістолет',
        en: 'Pistol',
        de: 'Pistole',
        pl: 'Pistolet',
    },
    'weapon-near': {
        ru: 'Оружие ближнего боя',
        ua: 'Зброя ближнього бою',
        en: 'Melee weapon',
        de: 'Nahkampfwaffe',
        pl: 'Broń biała',
    },
    shoulderSwap: {
        ru: 'Сменить плечо при прицеливании',
        ua: 'Змінити плече під час прицілювання',
        en: 'Swap aiming shoulder',
        de: 'Zielschulter wechseln',
        pl: 'Zmień ramię przy celowaniu',
    },
    'arena.loadout': {
        ru: 'Арена: сменить оружие',
        ua: 'Арена: змінити зброю',
        en: 'Arena: change weapons',
        de: 'Arena: Waffen wechseln',
        pl: 'Arena: zmień broń',
    },
    'casino.slots.spinButton': {
        ru: 'Слоты - крутить кнопкой',
        ua: 'Слоти - крутити кнопкою',
        en: 'Slots - spin with button',
        de: 'Slots - per Knopf drehen',
        pl: 'Sloty - kręć przyciskiem',
    },
    'casino.slots.spinLever': {
        ru: 'Слоты - крутить рычагом',
        ua: 'Слоти - крутити важелем',
        en: 'Slots - spin with lever',
        de: 'Slots - mit Hebel drehen',
        pl: 'Sloty - kręć dźwignią',
    },
    'casino.blackjack.hit': {
        ru: 'Блекджек - взять карту / сделать ставку',
        ua: 'Блекджек - взяти карту / зробити ставку',
        en: 'Blackjack - hit / place the bet',
        de: 'Blackjack - Karte ziehen / Einsatz setzen',
        pl: 'Blackjack - dobierz kartę / postaw zakład',
    },
    'casino.blackjack.stand': {
        ru: 'Блекджек - хватит',
        ua: 'Блекджек - досить',
        en: 'Blackjack - stand',
        de: 'Blackjack - stehen bleiben',
        pl: 'Blackjack - pas',
    },
    'casino.blackjack.double': {
        ru: 'Блекджек - удвоить',
        ua: 'Блекджек - подвоїти',
        en: 'Blackjack - double down',
        de: 'Blackjack - verdoppeln',
        pl: 'Blackjack - podwój',
    },
    'casino.blackjack.split': {
        ru: 'Блекджек - разделить',
        ua: 'Блекджек - розділити',
        en: 'Blackjack - split',
        de: 'Blackjack - teilen',
        pl: 'Blackjack - rozdziel',
    },
    'casino.poker.play': {
        ru: 'Покер - играть / ставка анте',
        ua: 'Покер - грати / ставка анте',
        en: 'Poker - play / Ante bet',
        de: 'Poker - spielen / Ante setzen',
        pl: 'Poker - graj / zakład ante',
    },
    'casino.poker.pairPlus': {
        ru: 'Покер - ставка пара плюс',
        ua: 'Покер - ставка пара плюс',
        en: 'Poker - Pair Plus bet',
        de: 'Poker - Pair Plus setzen',
        pl: 'Poker - zakład pair plus',
    },
    'casino.poker.fold': {
        ru: 'Покер - сбросить карты',
        ua: 'Покер - скинути карти',
        en: 'Poker - fold',
        de: 'Poker - aussteigen',
        pl: 'Poker - pasuj',
    },
    'casino.roulette.double': {
        ru: 'Рулетка - удвоить ставки',
        ua: 'Рулетка - подвоїти ставки',
        en: 'Roulette - double the bets',
        de: 'Roulette - Einsätze verdoppeln',
        pl: 'Ruletka - podwój zakłady',
    },
    'casino.roulette.cancel': {
        ru: 'Рулетка - отменить ставку',
        ua: 'Рулетка - скасувати ставку',
        en: 'Roulette - cancel the bet',
        de: 'Roulette - Einsatz zurücknehmen',
        pl: 'Ruletka - anuluj zakład',
    },
    'casino.camera': {
        ru: 'Казино - вид сбоку / от первого лица',
        ua: 'Казино - вигляд збоку / від першої особи',
        en: 'Casino - side / first person view',
        de: 'Casino - Seiten- / Egoperspektive',
        pl: 'Kasyno - widok z boku / z pierwszej osoby',
    },
    'casino.info': {
        ru: 'Казино - скрыть / показать информацию',
        ua: 'Казино - сховати / показати інформацію',
        en: 'Casino - hide / show info',
        de: 'Casino - Infos aus- / einblenden',
        pl: 'Kasyno - ukryj / pokaż informacje',
    },
    'casino.chipPrev': {
        ru: 'Казино - предыдущая фишка',
        ua: 'Казино - попередня фішка',
        en: 'Casino - previous chip',
        de: 'Casino - vorheriger Chip',
        pl: 'Kasyno - poprzedni żeton',
    },
    'casino.rules': {
        ru: 'Казино - информация и правила игры',
        ua: 'Казино - інформація та правила гри',
        en: 'Casino - game info and rules',
        de: 'Casino - Spielinfos und Regeln',
        pl: 'Kasyno - informacje i zasady gry',
    },
    'casino.chipNext': {
        ru: 'Казино - следующая фишка',
        ua: 'Казино - наступна фішка',
        en: 'Casino - next chip',
        de: 'Casino - nächster Chip',
        pl: 'Kasyno - następny żeton',
    },
    'indicator.left': {
        ru: 'Левый поворотник',
        ua: 'Лівий поворотник',
        en: 'Left indicator',
        de: 'Linker Blinker',
        pl: 'Lewy kierunkowskaz',
    },
    'indicator.right': {
        ru: 'Правый поворотник',
        ua: 'Правий поворотник',
        en: 'Right indicator',
        de: 'Rechter Blinker',
        pl: 'Prawy kierunkowskaz',
    },
    'indicator.emergency': {
        ru: 'Аварийная сигнализация',
        ua: 'Аварійна сигналізація',
        en: 'Hazard lights',
        de: 'Warnblinkanlage',
        pl: 'Światła awaryjne',
    },
    'vehicle.lights': {
        ru: 'Фары',
        ua: 'Фари',
        en: 'Lights',
        de: 'Lichter',
        pl: 'Światła',
    },
    'vehicle.driftMode': {
        ru: 'Дрифт-режим',
        ua: 'Дрифт-режим',
        en: 'Drift mode',
        de: 'Driftmodus',
        pl: 'Tryb driftu',
    },
    'tank.sniper': {
        ru: 'Танк: снайперский режим',
        ua: 'Танк: снайперський режим',
        en: 'Tank: sniper view',
        de: 'Panzer: Scharfschützenansicht',
        pl: 'Czołg: widok snajperski',
    },
    'tank.shell1': {
        ru: 'Танк: основной снаряд',
        ua: 'Танк: основний снаряд',
        en: 'Tank: standard shell',
        de: 'Panzer: Standardgranate',
        pl: 'Czołg: pocisk podstawowy',
    },
    'tank.shell2': {
        ru: 'Танк: особый снаряд',
        ua: 'Танк: особливий снаряд',
        en: 'Tank: special shell',
        de: 'Panzer: Spezialgranate',
        pl: 'Czołg: pocisk specjalny',
    },
    'tank.shell3': {
        ru: 'Танк: фугасный снаряд',
        ua: 'Танк: фугасний снаряд',
        en: 'Tank: HE shell',
        de: 'Panzer: Sprenggranate',
        pl: 'Czołg: pocisk odłamkowo-burzący',
    },
    'tank.consumable1': {
        ru: 'Танк: ремкомплект',
        ua: 'Танк: ремкомплект',
        en: 'Tank: repair kit',
        de: 'Panzer: Reparaturset',
        pl: 'Czołg: zestaw naprawczy',
    },
    'tank.consumable2': {
        ru: 'Танк: огнетушитель',
        ua: 'Танк: вогнегасник',
        en: 'Tank: fire extinguisher',
        de: 'Panzer: Feuerlöscher',
        pl: 'Czołg: gaśnica',
    },
    'tank.consumable3': {
        ru: 'Танк: аптечка',
        ua: 'Танк: аптечка',
        en: 'Tank: first aid kit',
        de: 'Panzer: Erste-Hilfe-Set',
        pl: 'Czołg: apteczka',
    },
    'tank.shellsSet': {
        ru: 'Танк: комплект снарядов и снаряжения',
        ua: 'Танк: комплект снарядів і спорядження',
        en: 'Tank: shells and consumables set',
        de: 'Panzer: Satz Munition und Verbrauchsgüter',
        pl: 'Czołg: zestaw amunicji i wyposażenia eksploatacyjnego',
    },
    'tank.devicesSet': {
        ru: 'Танк: комплект оборудования',
        ua: 'Танк: комплект обладнання',
        en: 'Tank: equipment set',
        de: 'Panzer: Satz Ausrüstung',
        pl: 'Czołg: zestaw wyposażenia',
    },
    'tank.minimapBigger': {
        ru: 'Танк: увеличить миникарту',
        ua: 'Танк: збільшити мінікарту',
        en: 'Tank: enlarge minimap',
        de: 'Panzer: Minikarte vergrößern',
        pl: 'Czołg: powiększ minimapę',
    },
    'tank.minimapSmaller': {
        ru: 'Танк: уменьшить миникарту',
        ua: 'Танк: зменшити мінікарту',
        en: 'Tank: shrink minimap',
        de: 'Panzer: Minikarte verkleinern',
        pl: 'Czołg: pomniejsz minimapę',
    },
    'vehicle.chip.cycle': {
        ru: 'Чипы: следующий',
        ua: 'Чіпи: наступний',
        en: 'Chips: next one',
        de: 'Chips: nächster',
        pl: 'Chipy: następny',
    },
    'vehicle.chip.stage1': {
        ru: 'Чип: Stage 1',
        ua: 'Чіп: Stage 1',
        en: 'Chip: Stage 1',
        de: 'Chip: Stage 1',
        pl: 'Chip: Stage 1',
    },
    'vehicle.chip.stage2': {
        ru: 'Чип: Stage 2',
        ua: 'Чіп: Stage 2',
        en: 'Chip: Stage 2',
        de: 'Chip: Stage 2',
        pl: 'Chip: Stage 2',
    },
    'vehicle.chip.stage3': {
        ru: 'Чип: Stage 3',
        ua: 'Чіп: Stage 3',
        en: 'Chip: Stage 3',
        de: 'Chip: Stage 3',
        pl: 'Chip: Stage 3',
    },
    'vehicle.chip.drift': {
        ru: 'Чип: Drift',
        ua: 'Чіп: Drift',
        en: 'Chip: Drift',
        de: 'Chip: Drift',
        pl: 'Chip: Drift',
    },
    'vehicle.chip.awd': {
        ru: 'Чип: All-wheel drive',
        ua: 'Чіп: All-wheel drive',
        en: 'Chip: All-wheel drive',
        de: 'Chip: All-wheel drive',
        pl: 'Chip: All-wheel drive',
    },
    'vehicle.chip.rwd': {
        ru: 'Чип: Rear-wheel drive',
        ua: 'Чіп: Rear-wheel drive',
        en: 'Chip: Rear-wheel drive',
        de: 'Chip: Rear-wheel drive',
        pl: 'Chip: Rear-wheel drive',
    },
    'vehicle.passengerSeat': {
        ru: 'Сесть на пассажирское место',
        ua: 'Сісти на пасажирське місце',
        en: 'Enter passenger seat',
        de: 'Auf den Beifahrersitz setzen',
        pl: 'Usiądź na miejscu pasażera',
    },
    'vehicle.passengerWaypoint': {
        ru: 'Отправить метку водителю',
        ua: 'Надіслати мітку водію',
        en: 'Send waypoint to driver',
        de: 'Wegpunkt an Fahrer senden',
        pl: 'Wyślij punkt trasy kierowcy',
    },
    megaphone: {
        ru: 'Мегафон',
        ua: 'Мегафон',
        en: 'Megaphone',
        de: 'Megafon',
        pl: 'Megafon',
    },
    walkieTalkie: {
        ru: 'Рация',
        ua: 'Рація',
        en: 'Walkie-talkie',
        de: 'Funkgerät',
        pl: 'Krótkofalówka',
    },
    crawl: {
        ru: 'Ползти',
        ua: 'Повзти',
        en: 'Crawl',
        de: 'Kriechen',
        pl: 'Czołgać się',
    },
    skinningAnimal: {
        ru: 'Разделать животное',
        ua: 'Розділати тварину',
        en: 'Skin an animal',
        de: 'Ein Tier häuten',
        pl: 'Oskórować zwierzę',
    },
    sit: {
        ru: 'Сесть',
        ua: 'Сісти',
        en: 'Sit down',
        de: 'Hinsetzen',
        pl: 'Usiądź',
    },
    rockstarEditorRecord: {
        ru: 'Запись Rockstar Editor',
        ua: 'Запис Rockstar Editor',
        en: 'Rockstar Editor recording',
        de: 'Rockstar Editor Aufnahme',
        pl: 'Nagrywanie w Rockstar Editor',
    },
    crouch: {
        ru: 'Приседать',
        ua: 'Присідати',
        en: 'Crouch',
        de: 'Ducken',
        pl: 'Kucać',
    },
    bigmap: {
        ru: 'Переключить размер радара',
        ua: 'Перемкнути розмір радара',
        en: 'Toggle radar size',
        de: 'Radargröße umschalten',
        pl: 'Przełączyć rozmiar radaru',
    },
    'arena.matchMenu': {
        ru: 'Арена: меню матча',
        ua: 'Арена: меню матчу',
        en: 'Arena: match menu',
        de: 'Arena: Match-Menü',
        pl: 'Arena: menu meczu',
    },
    'photo.shoot': {
        ru: 'Камера: сделать снимок',
        ua: 'Камера: зробити знімок',
        en: 'Camera: take the shot',
        de: 'Kamera: Aufnahme machen',
        pl: 'Aparat: zrób zdjęcie',
    },
    'photo.exit': {
        ru: 'Камера: убрать фотоаппарат',
        ua: 'Камера: прибрати фотоапарат',
        en: 'Camera: put it away',
        de: 'Kamera: weglegen',
        pl: 'Aparat: schowaj',
    },
    'photo.zoomIn': {
        ru: 'Камера: приблизить',
        ua: 'Камера: наблизити',
        en: 'Camera: zoom in',
        de: 'Kamera: heranzoomen',
        pl: 'Aparat: przybliż',
    },
    'photo.zoomOut': {
        ru: 'Камера: отдалить',
        ua: 'Камера: віддалити',
        en: 'Camera: zoom out',
        de: 'Kamera: herauszoomen',
        pl: 'Aparat: oddal',
    },
    'photo.flip': {
        ru: 'Камера телефона: сменить объектив',
        ua: 'Камера телефона: змінити об’єктив',
        en: 'Phone camera: switch lens',
        de: 'Handykamera: Objektiv wechseln',
        pl: 'Aparat w telefonie: zmień obiektyw',
    },
    'photo.filterPrev': {
        ru: 'Камера телефона: предыдущий фильтр',
        ua: 'Камера телефона: попередній фільтр',
        en: 'Phone camera: previous filter',
        de: 'Handykamera: vorheriger Filter',
        pl: 'Aparat w telefonie: poprzedni filtr',
    },
    'photo.filterNext': {
        ru: 'Камера телефона: следующий фильтр',
        ua: 'Камера телефона: наступний фільтр',
        en: 'Phone camera: next filter',
        de: 'Handykamera: nächster Filter',
        pl: 'Aparat w telefonie: następny filtr',
    },
    'drone.cycleMode': {
        ru: 'Дрон: переключить режим полёта',
        ua: 'Дрон: перемкнути режим польоту',
        en: 'Drone: toggle flight mode',
        de: 'Drohne: Flugmodus wechseln',
        pl: 'Dron: przełącz tryb lotu',
    },
    'drone.toggleView': {
        ru: 'Дрон: переключить вид камеры',
        ua: 'Дрон: перемкнути вид камери',
        en: 'Drone: toggle camera view',
        de: 'Drohne: Kameraansicht wechseln',
        pl: 'Dron: przełącz widok kamery',
    },
    'drone.cycleVision': {
        ru: 'Дрон: переключить режим зрения',
        ua: 'Дрон: перемкнути режим зору',
        en: 'Drone: cycle vision modes',
        de: 'Drohne: Sichtmodus wechseln',
        pl: 'Dron: zmień tryb widzenia',
    },
    'drone.disconnect': {
        ru: 'Дрон: отключить',
        ua: 'Дрон: відключити',
        en: 'Drone: disconnect',
        de: 'Drohne: trennen',
        pl: 'Dron: rozłącz',
    },
    'drone.tiltReset': {
        ru: 'Дрон: выровнять корпус',
        ua: 'Дрон: вирівняти корпус',
        en: 'Drone: level body',
        de: 'Drohne: Lage ausrichten',
        pl: 'Dron: wypoziomuj kadłub',
    },
    'drone.returnHome': {
        ru: 'Дрон: автоматический возврат (RTH)',
        ua: 'Дрон: автоматичне повернення (RTH)',
        en: 'Drone: return to home (RTH)',
        de: 'Drohne: automatische Rückkehr (RTH)',
        pl: 'Dron: automatyczny powrót (RTH)',
    },
    'drone.tiltForward': {
        ru: 'Дрон: наклон вперёд',
        ua: 'Дрон: нахил вперед',
        en: 'Drone: pitch forward',
        de: 'Drohne: Nase nach vorn',
        pl: 'Dron: pochyl do przodu',
    },
    'drone.tiltBack': {
        ru: 'Дрон: наклон назад',
        ua: 'Дрон: нахил назад',
        en: 'Drone: pitch back',
        de: 'Drohne: Nase nach hinten',
        pl: 'Dron: pochyl do tyłu',
    },
    'drone.rollLeft': {
        ru: 'Дрон: крен влево',
        ua: 'Дрон: крен вліво',
        en: 'Drone: roll left',
        de: 'Drohne: Rolle links',
        pl: 'Dron: przechył w lewo',
    },
    'drone.rollRight': {
        ru: 'Дрон: крен вправо',
        ua: 'Дрон: крен вправо',
        en: 'Drone: roll right',
        de: 'Drohne: Rolle rechts',
        pl: 'Dron: przechył w prawo',
    },
    'furnitureEditor.W': {
        ru: 'Вперёд',
        ua: 'Вперед',
        en: 'Forward',
        de: 'Vorwärts',
        pl: 'Do przodu',
    },
    'furnitureEditor.A': {
        ru: 'Влево',
        ua: 'Вліво',
        en: 'Left',
        de: 'Links',
        pl: 'W lewo',
    },
    'furnitureEditor.S': {
        ru: 'Назад',
        ua: 'Назад',
        en: 'Backward',
        de: 'Rückwärts',
        pl: 'Do tyłu',
    },
    'furnitureEditor.D': {
        ru: 'Вправо',
        ua: 'Вправо',
        en: 'Right',
        de: 'Rechts',
        pl: 'W prawo',
    },
    'furnitureEditor.mouseCamera': {
        ru: 'Крутить камерой',
        ua: 'Крутити камерою',
        en: 'Rotate the camera',
        de: 'Die Kamera drehen',
        pl: 'Obracaj kamerą',
    },
    'furnitureEditor.selectObject': {
        ru: 'Выбрать объект',
        ua: "Вибрати об'єкт",
        en: 'Select an object',
        de: 'Ein Objekt auswählen',
        pl: 'Wybierz obiekt',
    },
    'furnitureEditor.deselect': {
        ru: 'Снять выделение',
        ua: 'Зняти виділення',
        en: 'Deselect object',
        de: 'Auswahl aufheben',
        pl: 'Odznacz obiekt',
    },
    'furnitureEditor.focusObject': {
        ru: 'Фокус на выбранном объекте',
        ua: "Фокус на вибраному об'єкті",
        en: 'Focus on selected object',
        de: 'Fokus auf ausgewähltes Objekt',
        pl: 'Skup się na wybranym obiekcie',
    },
    'furnitureEditor.focusHome': {
        ru: 'Камера к старту',
        ua: 'Камера до старту',
        en: 'Camera to start',
        de: 'Kamera zum Start',
        pl: 'Kamera na start',
    },
    'furnitureEditor.slowCamera': {
        ru: 'Медленная камера',
        ua: 'Повільна камера',
        en: 'Slow camera',
        de: 'Langsame Kamera',
        pl: 'Powolna kamera',
    },
    'furnitureEditor.speedCamera': {
        ru: 'Быстрая камера',
        ua: 'Швидка камера',
        en: 'Fast camera',
        de: 'Schnelle Kamera',
        pl: 'Szybka kamera',
    },
    'furnitureEditor.moveUp': {
        ru: 'Камера вверх',
        ua: 'Камера вгору',
        en: 'Camera up',
        de: 'Kamera hoch',
        pl: 'Kamera w górę',
    },
    'furnitureEditor.moveDown': {
        ru: 'Камера вниз',
        ua: 'Камера вниз',
        en: 'Camera down',
        de: 'Kamera runter',
        pl: 'Kamera w dół',
    },
    'furnitureEditor.rotateMode': {
        ru: 'Режим поворота объекта',
        ua: "Режим повороту об'єкта",
        en: 'Object rotation mode',
        de: 'Objektdrehmodus',
        pl: 'Tryb obracania obiektu',
    },
    'furnitureEditor.translateMode': {
        ru: 'Режим перемещения объекта',
        ua: "Режим переміщення об'єкта",
        en: 'Object movement mode',
        de: 'Objektverschiebungsmodus',
        pl: 'Tryb przesuwania obiektu',
    },
    'furnitureEditor.axisSpace': {
        ru: 'Оси: локальные / мировые',
        ua: 'Осі: локальні / світові',
        en: 'Axes: local / world',
        de: 'Achsen: lokal / global',
        pl: 'Osie: lokalne / globalne',
    },
    'furnitureEditor.hideHints': {
        ru: 'Скрыть подсказки',
        ua: 'Сховати підказки',
        en: 'Hide hints',
        de: 'Hinweise ausblenden',
        pl: 'Ukryj podpowiedzi',
    },
    'furnitureEditor.delete': {
        ru: 'Удалить объект',
        ua: "Видалити об'єкт",
        en: 'Delete object',
        de: 'Objekt löschen',
        pl: 'Usuń obiekt',
    },
    'furnitureEditor.duplicate': {
        ru: 'Дублировать объект',
        ua: "Дублювати об'єкт",
        en: 'Duplicate object',
        de: 'Objekt duplizieren',
        pl: 'Duplikuj obiekt',
    },
    'furnitureEditor.undo': {
        ru: 'Отменить действие',
        ua: 'Скасувати дію',
        en: 'Undo action',
        de: 'Aktion rückgängig machen',
        pl: 'Cofnij akcję',
    },
    'furnitureEditor.redo': {
        ru: 'Повторить действие',
        ua: 'Повторити дію',
        en: 'Redo action',
        de: 'Aktion wiederholen',
        pl: 'Ponów akcję',
    },

    // Описания биндов для правой панели настроек. Ключ совпадает с действием;
    // бинды без записи здесь просто показывают пустое описание.
    desc: {
        'interaction.self': {
            ru: 'Открывает меню действий над своим персонажем: документы, дом, фракция и группа. Если клавиша совпадает с взаимодействием с окружающими, меню открывается по цели под прицелом',
            ua: 'Відкриває меню дій над своїм персонажем: документи, дім, фракція та група. Якщо клавіша збігається з взаємодією з оточенням, меню відкривається по цілі під прицілом',
            en: 'Opens the action menu for your own character: documents, house, faction and party. If this key matches interaction with surroundings, the menu opens for the entity you are aiming at',
            de: 'Öffnet das Aktionsmenü für deinen eigenen Charakter: Dokumente, Haus, Fraktion und Gruppe. Wenn diese Taste mit der Interaktion mit der Umgebung übereinstimmt, öffnet sich das Menü für das anvisierte Ziel',
            pl: 'Otwiera menu akcji dla twojej postaci: dokumenty, dom, frakcja i grupa. Jeśli klawisz pokrywa się z interakcją z otoczeniem, menu otworzy się dla celu, na który patrzysz',
        },
        'interaction.others': {
            ru: 'Открывает меню действий над игроком, транспортом или предметом, на который вы смотрите. Подсказка с этой клавишей показывается над целью',
            ua: 'Відкриває меню дій над гравцем, транспортом або предметом, на який ви дивитесь. Підказка з цією клавішею показується над ціллю',
            en: 'Opens the action menu for the player, vehicle or object you are looking at. The key hint above the target follows this bind',
            de: 'Öffnet das Aktionsmenü für den Spieler, das Fahrzeug oder das Objekt, das du ansiehst. Der Tastenhinweis über dem Ziel richtet sich nach dieser Belegung',
            pl: 'Otwiera menu akcji dla gracza, pojazdu lub przedmiotu, na który patrzysz. Podpowiedź nad celem pokazuje ten klawisz',
        },
        'interaction.quick.lock': {
            ru: 'Закрывает или открывает замки транспорта без открытия меню: машины, в которой вы сидите, или той, на которую смотрите',
            ua: 'Зачиняє або відчиняє замки транспорту без відкриття меню: машини, в якій ви сидите, або тієї, на яку дивитесь',
            en: 'Locks or unlocks a vehicle without opening the menu: the one you are sitting in, or the one you are looking at',
            de: 'Ver- oder entriegelt ein Fahrzeug ohne das Menü: das, in dem du sitzt, oder das, das du ansiehst',
            pl: 'Zamyka lub otwiera zamki pojazdu bez otwierania menu: tego, w którym siedzisz, lub tego, na który patrzysz',
        },
        'interaction.quick.trunk': {
            ru: 'Открывает или закрывает крышку багажника: пока она открыта, доступ к содержимому получают все игроки рядом. Требует прав владельца или доступа фракции',
            ua: 'Відчиняє або зачиняє кришку багажника: поки вона відкрита, доступ до вмісту отримують усі гравці поруч. Потребує прав власника або доступу фракції',
            en: 'Opens or closes the trunk lid: while it is open, any nearby player can reach the contents. Requires vehicle ownership or faction access',
            de: 'Öffnet oder schließt die Kofferraumklappe: solange sie offen ist, kommt jeder Spieler in der Nähe an den Inhalt. Erfordert Fahrzeugbesitz oder Fraktionszugriff',
            pl: 'Otwiera lub zamyka klapę bagażnika: gdy jest otwarta, każdy gracz w pobliżu ma dostęp do zawartości. Wymaga własności pojazdu lub dostępu frakcji',
        },
        'interaction.quick.trunkInventory': {
            ru: 'Открывает содержимое багажника вам: владельцу и фракции всегда, остальным только пока крышка багажника открыта',
            ua: 'Відкриває вміст багажника вам: власнику та фракції завжди, іншим лише поки кришка багажника відчинена',
            en: 'Opens the trunk contents for you: always for the owner and faction, for everyone else only while the trunk lid is open',
            de: 'Öffnet den Kofferrauminhalt für dich: für Besitzer und Fraktion immer, für alle anderen nur bei offener Klappe',
            pl: 'Otwiera zawartość bagażnika dla ciebie: właścicielowi i frakcji zawsze, pozostałym tylko przy otwartej klapie',
        },
        'interaction.quick.musicPlayer': {
            ru: 'Открывает музыкальный плеер машины, в которой вы сидите. Вне транспорта не работает',
            ua: 'Відкриває музичний плеєр машини, в якій ви сидите. Поза транспортом не працює',
            en: 'Opens the music player of the vehicle you are sitting in. Does nothing outside a vehicle',
            de: 'Öffnet den Musikplayer des Fahrzeugs, in dem du sitzt. Außerhalb eines Fahrzeugs ohne Wirkung',
            pl: 'Otwiera odtwarzacz muzyki pojazdu, w którym siedzisz. Poza pojazdem nie działa',
        },
        'interaction.quick.passport': {
            ru: 'Показывает ваш паспорт игроку под прицелом по его согласию или открывает его вам, если цели нет',
            ua: 'Показує ваш паспорт гравцю під прицілом за його згодою або відкриває його вам, якщо цілі немає',
            en: 'Shows your passport to the player you are aiming at once they accept, or opens it for yourself with no target',
            de: 'Zeigt deinen Reisepass dem anvisierten Spieler nach dessen Zustimmung oder öffnet ihn für dich, wenn kein Ziel da ist',
            pl: 'Pokazuje twój paszport graczowi na celowniku po jego zgodzie lub otwiera go tobie, gdy nie ma celu',
        },
        'interaction.quick.drivingLicenses': {
            ru: 'Показывает ваше водительское удостоверение игроку под прицелом по его согласию или открывает его вам, если цели нет',
            ua: 'Показує ваше посвідчення водія гравцю під прицілом за його згодою або відкриває його вам, якщо цілі немає',
            en: 'Shows your driving license to the player you are aiming at once they accept, or opens it for yourself with no target',
            de: 'Zeigt deinen Führerschein dem anvisierten Spieler nach dessen Zustimmung oder öffnet ihn für dich, wenn kein Ziel da ist',
            pl: 'Pokazuje twoje prawo jazdy graczowi na celowniku po jego zgodzie lub otwiera je tobie, gdy nie ma celu',
        },
        'interaction.quick.licenses': {
            ru: 'Показывает ваши лицензии игроку под прицелом по его согласию или открывает их вам, если цели нет',
            ua: 'Показує ваші ліцензії гравцю під прицілом за його згодою або відкриває їх вам, якщо цілі немає',
            en: 'Shows your licenses to the player you are aiming at once they accept, or opens them for yourself with no target',
            de: 'Zeigt deine Lizenzen dem anvisierten Spieler nach dessen Zustimmung oder öffnet sie für dich, wenn kein Ziel da ist',
            pl: 'Pokazuje twoje licencje graczowi na celowniku po jego zgodzie lub otwiera je tobie, gdy nie ma celu',
        },
        shoulderSwap: {
            ru: 'Перекидывает камеру прицеливания от третьего лица с правого плеча на левое и обратно. Выбранная сторона сохраняется до следующего нажатия. В транспорте не работает',
            ua: 'Перекидає камеру прицілювання від третьої особи з правого плеча на ліве й назад. Обрана сторона зберігається до наступного натискання. У транспорті не працює',
            en: 'Moves the third-person aiming camera from the right shoulder to the left and back. The chosen side stays until the next press. Does nothing in a vehicle',
            de: 'Wechselt die Zielkamera in der Third-Person-Ansicht von der rechten auf die linke Schulter und zurück. Die gewählte Seite bleibt bis zum nächsten Drücken. Im Fahrzeug ohne Wirkung',
            pl: 'Przenosi kamerę celowania z trzeciej osoby z prawego ramienia na lewe i z powrotem. Wybrana strona zostaje do następnego naciśnięcia. W pojeździe nie działa',
        },
        'arena.loadout': {
            ru: 'В стрелковом матче арены открывает выбор оружия из того, что разрешило лобби. Новый набор выдадут при следующем появлении',
            ua: 'У стрілецькому матчі арени відкриває вибір зброї з того, що дозволило лобі. Новий набір видадуть під час наступної появи',
            en: 'In an arena shooting match, opens the weapon pick out of what the lobby allows. The new loadout is handed out at your next spawn',
            de: 'Öffnet in einem Arena-Schießmatch die Waffenwahl aus dem, was die Lobby erlaubt. Die neue Ausrüstung gibt es beim nächsten Spawn',
            pl: 'W meczu strzeleckim areny otwiera wybór broni spośród tej, na którą pozwala lobby. Nowy zestaw otrzymasz przy następnym odrodzeniu',
        },
        'arena.matchMenu': {
            ru: 'В любом матче арены открывает меню матча, из которого можно покинуть матч',
            ua: 'У будь-якому матчі арени відкриває меню матчу, з якого можна покинути матч',
            en: 'In any arena match, opens the match menu, where you can leave the match',
            de: 'Öffnet in jedem Arena-Match das Match-Menü, über das du das Match verlassen kannst',
            pl: 'W każdym meczu areny otwiera menu meczu, z którego możesz opuścić mecz',
        },
        'tank.sniper': {
            ru: 'В танке переключает вид из-за корпуса и прицел у орудия. Колесо мыши тоже приближает вид и переходит в прицел',
            ua: 'У танку перемикає вид з-за корпусу та приціл біля гармати. Колесо миші теж наближає вид і переходить у приціл',
            en: 'In a tank, switches between the view behind the hull and the sight at the gun. The mouse wheel also zooms in and into the sight',
            de: 'Wechselt im Panzer zwischen der Ansicht hinter der Wanne und dem Visier an der Kanone. Das Mausrad zoomt ebenfalls heran und ins Visier',
            pl: 'W czołgu przełącza widok zza kadłuba i celownik przy dziale. Kółko myszy też przybliża widok i przechodzi do celownika',
        },
        'tank.shell1': {
            ru: 'В танке: следующая перезарядка возьмёт основной снаряд. Заряженный снаряд остаётся в стволе, а смена во время перезарядки начинает её заново',
            ua: 'У танку: наступне перезаряджання візьме основний снаряд. Заряджений снаряд лишається в стволі, а зміна під час перезаряджання починає його заново',
            en: 'In a tank: the next reload takes the standard shell. A loaded shell stays in the breech, and a change during a reload starts it over',
            de: 'Im Panzer: Das nächste Nachladen nimmt die Standardgranate. Eine geladene Granate bleibt im Rohr, ein Wechsel während des Nachladens beginnt es neu',
            pl: 'W czołgu: następne przeładowanie weźmie pocisk podstawowy. Załadowany pocisk zostaje w lufie, a zmiana w trakcie przeładowania zaczyna je od nowa',
        },
        'tank.shell2': {
            ru: 'В танке: следующая перезарядка возьмёт особый снаряд - подкалиберный или кумулятивный, у каждого орудия свой',
            ua: 'У танку: наступне перезаряджання візьме особливий снаряд - підкаліберний або кумулятивний, у кожної гармати свій',
            en: 'In a tank: the next reload takes the special shell - APCR or HEAT, depending on the gun',
            de: 'Im Panzer: Das nächste Nachladen nimmt die Spezialgranate - APCR oder HEAT, je nach Kanone',
            pl: 'W czołgu: następne przeładowanie weźmie pocisk specjalny - APCR lub HEAT, zależnie od działa',
        },
        'tank.shell3': {
            ru: 'В танке: следующая перезарядка возьмёт фугасный снаряд - слабая пробиваемость, но урон и без пробития',
            ua: 'У танку: наступне перезаряджання візьме фугасний снаряд - слабке пробиття, але шкода і без пробиття',
            en: 'In a tank: the next reload takes the HE shell - weak penetration, but it deals damage without penetrating too',
            de: 'Im Panzer: Das nächste Nachladen nimmt die Sprenggranate - schwache Durchschlagskraft, aber Schaden auch ohne Durchschlag',
            pl: 'W czołgu: następne przeładowanie weźmie pocisk odłamkowo-burzący - słaba penetracja, ale zadaje obrażenia także bez przebicia',
        },
        'tank.consumable1': {
            ru: 'В танке чинит все повреждённые и уничтоженные модули. Сколько раз его можно применить и сколько ждать до следующего, видно на панели снизу',
            ua: 'У танку лагодить усі пошкоджені та знищені модулі. Скільки разів його можна застосувати і скільки чекати до наступного, видно на панелі знизу',
            en: 'In a tank, repairs every damaged and destroyed module. The panel at the bottom shows how many uses are left and when the next one is ready',
            de: 'Repariert im Panzer alle beschädigten und zerstörten Module. Die Leiste unten zeigt, wie oft es noch geht und wann es wieder bereit ist',
            pl: 'W czołgu naprawia wszystkie uszkodzone i zniszczone moduły. Panel na dole pokazuje, ile użyć zostało i kiedy następne będzie gotowe',
        },
        'tank.consumable2': {
            ru: 'В танке тушит пожар',
            ua: 'У танку гасить пожежу',
            en: 'In a tank, puts out a fire',
            de: 'Löscht im Panzer einen Brand',
            pl: 'W czołgu gasi pożar',
        },
        'tank.consumable3': {
            ru: 'В танке возвращает в строй контуженный экипаж',
            ua: 'У танку повертає до строю контужений екіпаж',
            en: 'In a tank, brings the stunned crew back to duty',
            de: 'Bringt im Panzer die betäubte Besatzung wieder zum Einsatz',
            pl: 'W czołgu przywraca do służby ogłuszoną załogę',
        },
        'tank.shellsSet': {
            ru: 'В отсчёте перед боем меняет комплект снарядов и снаряжения на второй, если в улучшениях танка он открыт',
            ua: 'У відліку перед боєм змінює комплект снарядів і спорядження на другий, якщо в покращеннях танка його відкрито',
            en: 'In the pre-battle countdown, switches to the other shells and consumables set, once the tank has it in its upgrades',
            de: 'Wechselt im Countdown vor dem Gefecht zum anderen Satz Munition und Verbrauchsgüter, sobald der Panzer ihn in seinen Verbesserungen hat',
            pl: 'W odliczaniu przed bitwą przełącza na drugi zestaw amunicji i wyposażenia eksploatacyjnego, jeśli czołg ma go w ulepszeniach',
        },
        'tank.devicesSet': {
            ru: 'В отсчёте перед боем меняет комплект оборудования на второй, если в улучшениях танка он открыт',
            ua: 'У відліку перед боєм змінює комплект обладнання на другий, якщо в покращеннях танка його відкрито',
            en: 'In the pre-battle countdown, switches to the other equipment set, once the tank has it in its upgrades',
            de: 'Wechselt im Countdown vor dem Gefecht zum anderen Satz Ausrüstung, sobald der Panzer ihn in seinen Verbesserungen hat',
            pl: 'W odliczaniu przed bitwą przełącza na drugi zestaw wyposażenia, jeśli czołg ma go w ulepszeniach',
        },
        'tank.minimapBigger': {
            ru: 'В бою делает квадратную миникарту на шаг больше. Размер запоминается между боями',
            ua: "У бою робить квадратну мінікарту на крок більшою. Розмір запам'ятовується між боями",
            en: 'In battle, makes the square minimap a step bigger. The size is kept between battles',
            de: 'Macht die quadratische Minikarte im Gefecht eine Stufe größer. Die Größe bleibt zwischen Gefechten erhalten',
            pl: 'W bitwie powiększa kwadratową minimapę o jeden stopień. Rozmiar jest zapamiętywany między bitwami',
        },
        'tank.minimapSmaller': {
            ru: 'В бою делает квадратную миникарту на шаг меньше. Размер запоминается между боями',
            ua: "У бою робить квадратну мінікарту на крок меншою. Розмір запам'ятовується між боями",
            en: 'In battle, makes the square minimap a step smaller. The size is kept between battles',
            de: 'Macht die quadratische Minikarte im Gefecht eine Stufe kleiner. Die Größe bleibt zwischen Gefechten erhalten',
            pl: 'W bitwie pomniejsza kwadratową minimapę o jeden stopień. Rozmiar jest zapamiętywany między bitwami',
        },
    },
};
