export default {
    interaction: {
        ru: 'Взаимодействие',
        ua: 'Взаємодія',
        en: 'Interaction',
        de: 'Interaktion',
        pl: 'Interakcja',
    },
    interaction2: {
        ru: 'Взаимодействие с игроком',
        ua: 'Взаємодія з гравцем',
        en: 'Interaction with a player',
        de: 'Interaktion mit einem Spieler',
        pl: 'Interakcja z graczem',
    },
    inventory: {
        ru: 'Инвентарь',
        ua: 'Інвентар',
        en: 'Inventory',
        de: 'Inventar',
        pl: 'Ekwipunek',
    },
    exit: {
        ru: 'Закрыть',
        ua: 'Закрити',
        en: 'Close',
        de: 'Schließen',
        pl: 'Zamknij',
    },
    click: {
        ru: 'Действие (клик)',
        ua: 'Дія (клік)',
        en: 'Action (click)',
        de: 'Aktion (Klick)',
        pl: 'Akcja (klik)',
    },
    voice: {
        ru: 'Голосовой чат',
        ua: 'Голосовий чат',
        en: 'Voice chat',
        de: 'Sprachchat',
        pl: 'Czat głosowy',
    },
    reloadVoice: {
        ru: 'Перезагрузка голосового чата',
        ua: 'Перезавантаження голосового чату',
        en: 'Reload voice chat',
        de: 'Neustart des Sprachchats',
        pl: 'Przeładowanie czatu głosowego',
    },
    seatBelt: {
        ru: 'Ремень безопасности',
        ua: 'Пас безпеки',
        en: 'Seat belt',
        de: 'Sicherheitsgurt',
        pl: 'Pasy bezpieczeństwa',
    },
    testDriveExit: {
        ru: 'Выйти из тест-драйва',
        ua: 'Вийти з тест-драйву',
        en: 'Exit test drive',
        de: 'Probefahrt beenden',
        pl: 'Zakończ jazdę próbną',
    },
    fingerPointing: {
        ru: 'Указать пальцем',
        ua: 'Вказати пальцем',
        en: 'Point with finger',
        de: 'Mit dem Finger zeigen',
        pl: 'Wskazać palcem',
    },
    cruiseControl: {
        ru: 'Круиз-контроль',
        ua: 'Круїз-контроль',
        en: 'Cruise control',
        de: 'Tempomat',
        pl: 'Tempomat',
    },
    accept: {
        ru: 'Принять',
        ua: 'Прийняти',
        en: 'Accept',
        de: 'Annehmen',
        pl: 'Przyjąć',
    },
    refuse: {
        ru: 'Отказать',
        ua: 'Відмовити',
        en: 'Refuse',
        de: 'Ablehnen',
        pl: 'Odmówić',
    },
    animations: {
        ru: 'Меню анимаций',
        ua: 'Меню анімацій',
        en: 'Animations menu',
        de: 'Animationsmenü',
        pl: 'Menu animacji',
    },
    toggleHud: {
        ru: 'Показать/скрыть HUD',
        ua: 'Показати/сховати HUD',
        en: 'Show/hide HUD',
        de: 'HUD ein-/ausblenden',
        pl: 'Pokaż/ukryj HUD',
    },
    chat: {
        ru: 'Открыть чат',
        ua: 'Відкрити чат',
        en: 'Open chat',
        de: 'Chat öffnen',
        pl: 'Otwórz czat',
    },
    engine: {
        ru: 'Двигатель',
        ua: 'Двигун',
        en: 'Engine',
        de: 'Motor',
        pl: 'Silnik',
    },
    menu: {
        ru: 'Меню',
        ua: 'Меню',
        en: 'Menu',
        de: 'Menü',
        pl: 'Menu',
    },
    phone: {
        ru: 'Телефон',
        ua: 'Телефон',
        en: 'Phone',
        de: 'Telefon',
        pl: 'Telefon',
    },
    raiseDrop: {
        ru: 'Подобрать предмет',
        ua: 'Підібрати предмет',
        en: 'Pick up item',
        de: 'Gegenstand aufheben',
        pl: 'Podnieś przedmiot',
    },
    stopAnimation: {
        ru: 'Остановить анимацию',
        ua: 'Зупинити анімацію',
        en: 'Stop animation',
        de: 'Animation stoppen',
        pl: 'Zatrzymaj animację',
    },
    console: {
        ru: 'Консоль',
        ua: 'Консоль',
        en: 'Console',
        de: 'Konsole',
        pl: 'Konsola',
    },
    animationsWheel: {
        ru: 'Колесо анимаций',
        ua: 'Колесо анімацій',
        en: 'Animations wheel',
        de: 'Animationsrad',
        pl: 'Koło animacji',
    },
    tpWaypoint: {
        ru: 'Телепорт к метке',
        ua: 'Телепорт до точки',
        en: 'Teleport to waypoint',
        de: 'Teleport zum Wegpunkt',
        pl: 'Teleport do punktu',
    },
    cursor: {
        ru: 'Курсор',
        ua: 'Курсор',
        en: 'Cursor',
        de: 'Cursor',
        pl: 'Kursor',
    },
    'trucker.dropBox': {
        ru: 'Выкинуть груз',
        ua: 'Викинути вантаж',
        en: 'Drop cargo',
        de: 'Ladung abwerfen',
        pl: 'Wyrzuć ładunek',
    },
    'weapon-heavy': {
        ru: 'Тяжёлое оружие',
        ua: 'Важка зброя',
        en: 'Heavy weapon',
        de: 'Schwere Waffe',
        pl: 'Ciężka broń',
    },
    'weapon-pistol': {
        ru: 'Пистолет',
        ua: 'Пістолет',
        en: 'Pistol',
        de: 'Pistole',
        pl: 'Pistolet',
    },
    'weapon-near': {
        ru: 'Оружие ближнего боя',
        ua: 'Зброя ближнього бою',
        en: 'Melee weapon',
        de: 'Nahkampfwaffe',
        pl: 'Broń biała',
    },
    'casino.slots.spinButton': {
        ru: 'Слоты - крутить кнопкой',
        ua: 'Слоти - крутити кнопкою',
        en: 'Slots - spin with button',
        de: 'Slots - per Knopf drehen',
        pl: 'Sloty - kręć przyciskiem',
    },
    'casino.slots.spinLever': {
        ru: 'Слоты - крутить рычагом',
        ua: 'Слоти - крутити важелем',
        en: 'Slots - spin with lever',
        de: 'Slots - mit Hebel drehen',
        pl: 'Sloty - kręć dźwignią',
    },
    'indicator.left': {
        ru: 'Левый поворотник',
        ua: 'Лівий поворотник',
        en: 'Left indicator',
        de: 'Linker Blinker',
        pl: 'Lewy kierunkowskaz',
    },
    'indicator.right': {
        ru: 'Правый поворотник',
        ua: 'Правий поворотник',
        en: 'Right indicator',
        de: 'Rechter Blinker',
        pl: 'Prawy kierunkowskaz',
    },
    'vehicle.lights': {
        ru: 'Фары',
        ua: 'Фари',
        en: 'Lights',
        de: 'Lichter',
        pl: 'Światła',
    },
    megaphone: {
        ru: 'Мегафон',
        ua: 'Мегафон',
        en: 'Megaphone',
        de: 'Megafon',
        pl: 'Megafon',
    },
    walkieTalkie: {
        ru: 'Рация',
        ua: 'Рація',
        en: 'Walkie-talkie',
        de: 'Funkgerät',
        pl: 'Krótkofalówka',
    },
    crawl: {
        ru: 'Ползти',
        ua: 'Повзти',
        en: 'Crawl',
        de: 'Kriechen',
        pl: 'Czołgać się',
    },
    skinningAnimal: {
        ru: 'Разделать животное',
        ua: 'Розділати тварину',
        en: 'Skin an animal',
        de: 'Ein Tier häuten',
        pl: 'Oskórować zwierzę',
    },
    rockstarEditorRecord: {
        ru: 'Запись Rockstar Editor',
        ua: 'Запис Rockstar Editor',
        en: 'Rockstar Editor recording',
        de: 'Rockstar Editor Aufnahme',
        pl: 'Nagrywanie w Rockstar Editor',
    },
    crouch: {
        ru: 'Приседать',
        ua: 'Присідати',
        en: 'Crouch',
        de: 'Ducken',
        pl: 'Kucać',
    },
    bigmap: {
        ru: 'Переключить размер радара',
        ua: 'Перемкнути розмір радара',
        en: 'Toggle radar size',
        de: 'Radargröße umschalten',
        pl: 'Przełączyć rozmiar radaru',
    },
    'furnitureEditor.W': {
        ru: 'Вперёд',
        ua: 'Вперед',
        en: 'Forward',
        de: 'Vorwärts',
        pl: 'Do przodu',
    },
    'furnitureEditor.A': {
        ru: 'Влево',
        ua: 'Вліво',
        en: 'Left',
        de: 'Links',
        pl: 'W lewo',
    },
    'furnitureEditor.S': {
        ru: 'Назад',
        ua: 'Назад',
        en: 'Backward',
        de: 'Rückwärts',
        pl: 'Do tyłu',
    },
    'furnitureEditor.D': {
        ru: 'Вправо',
        ua: 'Вправо',
        en: 'Right',
        de: 'Rechts',
        pl: 'W prawo',
    },
    'furnitureEditor.mouseCamera': {
        ru: 'Крутить камерой',
        ua: 'Крутити камерою',
        en: 'Rotate the camera',
        de: 'Die Kamera drehen',
        pl: 'Obracaj kamerą',
    },
    'furnitureEditor.selectObject': {
        ru: 'Выбрать объект',
        ua: 'Вибрати об’єкт',
        en: 'Select an object',
        de: 'Ein Objekt auswählen',
        pl: 'Wybierz obiekt',
    },
    'furnitureEditor.focusObject': {
        ru: 'Фокус на выбранном объекте',
        ua: 'Фокус на вибраному об’єкті',
        en: 'Focus on selected object',
        de: 'Fokus auf ausgewähltes Objekt',
        pl: 'Skup się na wybranym obiekcie',
    },
    'furnitureEditor.focusHome': {
        ru: 'Камера к старту',
        ua: 'Камера до старту',
        en: 'Camera to start',
        de: 'Kamera zum Start',
        pl: 'Kamera na start',
    },
    'furnitureEditor.slowCamera': {
        ru: 'Медленная камера',
        ua: 'Повільна камера',
        en: 'Slow camera',
        de: 'Langsame Kamera',
        pl: 'Powolna kamera',
    },
    'furnitureEditor.speedCamera': {
        ru: 'Быстрая камера',
        ua: 'Швидка камера',
        en: 'Fast camera',
        de: 'Schnelle Kamera',
        pl: 'Szybka kamera',
    },
    'furnitureEditor.moveUp': {
        ru: 'Камера вверх',
        ua: 'Камера вгору',
        en: 'Camera up',
        de: 'Kamera hoch',
        pl: 'Kamera w górę',
    },
    'furnitureEditor.moveDown': {
        ru: 'Камера вниз',
        ua: 'Камера вниз',
        en: 'Camera down',
        de: 'Kamera runter',
        pl: 'Kamera w dół',
    },
    'furnitureEditor.rotateMode': {
        ru: 'Режим поворота объекта',
        ua: 'Режим повороту об’єкта',
        en: 'Object rotation mode',
        de: 'Objektdrehmodus',
        pl: 'Tryb obracania obiektu',
    },
    'furnitureEditor.translateMode': {
        ru: 'Режим перемещения объекта',
        ua: 'Режим переміщення об’єкта',
        en: 'Object movement mode',
        de: 'Objektverschiebungsmodus',
        pl: 'Tryb przesuwania obiektu',
    },
    'furnitureEditor.hideHints': {
        ru: 'Скрыть подсказки',
        ua: 'Сховати підказки',
        en: 'Hide hints',
        de: 'Hinweise ausblenden',
        pl: 'Ukryj podpowiedzi',
    },
    'furnitureEditor.delete': {
        ru: 'Удалить объект',
        ua: 'Видалити обʼєкт',
        en: 'Delete object',
        de: 'Objekt löschen',
        pl: 'Usuń obiekt',
    },
    'furnitureEditor.duplicate': {
        ru: 'Дублировать объект',
        ua: 'Дублювати обʼєкт',
        en: 'Duplicate object',
        de: 'Objekt duplizieren',
        pl: 'Duplikuj obiekt',
    },
    'furnitureEditor.undo': {
        ru: 'Отменить действие',
        ua: 'Скасувати дію',
        en: 'Undo action',
        de: 'Aktion rückgängig machen',
        pl: 'Cofnij akcję',
    },
    'furnitureEditor.redo': {
        ru: 'Повторить действие',
        ua: 'Повторити дію',
        en: 'Redo action',
        de: 'Aktion wiederholen',
        pl: 'Ponów akcję',
    },
};
