export default {
    alert: {
        header: {
            ru: 'Ограбление банка',
            ua: 'Пограбування банку',
            en: 'Bank robbery',
            de: 'Bankraub',
            pl: 'Napad na bank',
        },
        text: {
            ru: 'Сработала сигнализация: {{bank}}',
            ua: 'Спрацювала сигналізація: {{bank}}',
            en: 'Alarm triggered: {{bank}}',
            de: 'Alarm ausgeloest: {{bank}}',
            pl: 'Uruchomiono alarm: {{bank}}',
        },
        target: {
            ru: 'Банк: {{bank}}',
            ua: 'Банк: {{bank}}',
            en: 'Bank: {{bank}}',
            de: 'Bank: {{bank}}',
            pl: 'Bank: {{bank}}',
        },
    },
    prompt: {
        unlock: {
            ru: 'Вскрыть хранилище (карта + взломщик)',
            ua: 'Зламати сховище (картка + зламувач)',
            en: 'Crack the vault (card + device)',
            de: 'Tresor knacken (Karte + Geraet)',
            pl: 'Otworzyc skarbiec (karta + urzadzenie)',
        },
        drill: {
            ru: 'Сверлить ячейку',
            ua: 'Свердлити комірку',
            en: 'Drill the deposit box',
            de: 'Das Schliessfach anbohren',
            pl: 'Wiercic skrytke',
        },
        thermite: {
            ru: 'Заложить термит',
            ua: 'Закласти терміт',
            en: 'Place the thermal charge',
            de: 'Thermitladung anbringen',
            pl: 'Podlozyc ladunek termitowy',
        },
        loot: {
            ru: 'Забрать деньги',
            ua: 'Забрати гроші',
            en: 'Take the money',
            de: 'Das Geld nehmen',
            pl: 'Zabrac pieniadze',
        },
    },
    success: {
        stepDone: {
            ru: 'Преграда вскрыта. Дальше следующая дверь.',
            ua: 'Перешкоду зламано. Далі наступні двері.',
            en: 'The gate is through. The next door is up.',
            de: 'Das Gitter ist offen. Die naechste Tuer wartet.',
            pl: 'Krata otwarta. Czas na kolejne drzwi.',
        },
        vaultOpen: {
            ru: 'Хранилище открыто. Забирайте деньги, пока есть время.',
            ua: 'Сховище відкрито. Забирайте гроші, поки є час.',
            en: 'The vault is open. Take the money while you still can.',
            de: 'Der Tresor ist offen. Nehmt das Geld, solange ihr koennt.',
            pl: 'Skarbiec jest otwarty. Bierzcie pieniadze, poki mozecie.',
        },
    },
    error: {
        dead: {
            ru: 'В таком состоянии не поработаешь.',
            ua: 'У такому стані не попрацюєш.',
            en: 'Not in this state.',
            de: 'In diesem Zustand geht das nicht.',
            pl: 'Nie w tym stanie.',
        },
        playerCooldown: {
            ru: 'Вы уже брали банк недавно. Осталось {{time}}.',
            ua: 'Ви вже брали банк нещодавно. Залишилось {{time}}.',
            en: 'You have already worked a bank recently. {{time}} left.',
            de: 'Du warst vor Kurzem schon an einer Bank. Noch {{time}}.',
            pl: 'Juz niedawno robiles bank. Zostalo {{time}}.',
        },
        bankCooldown: {
            ru: 'Этот банк уже грабили. Осталось {{time}}.',
            ua: 'Цей банк уже грабували. Залишилось {{time}}.',
            en: 'This bank has already been hit. {{time}} left.',
            de: 'Diese Bank wurde bereits ausgeraubt. Noch {{time}}.',
            pl: 'Ten bank juz obrobiono. Zostalo {{time}}.',
        },
        notEnoughCops: {
            ru: 'Слишком мало полиции в городе. Нужно минимум {{count}}.',
            ua: 'Замало поліції в місті. Потрібно щонайменше {{count}}.',
            en: 'Too few officers in the city. At least {{count}} are needed.',
            de: 'Zu wenige Beamte in der Stadt. Mindestens {{count}} noetig.',
            pl: 'Za malo policji w miescie. Potrzeba co najmniej {{count}}.',
        },
        notEnoughCrew: {
            ru: 'Мало людей в банке: {{current}} из {{count}}.',
            ua: 'Мало людей у банку: {{current}} з {{count}}.',
            en: 'Not enough people inside the bank: {{current}} of {{count}}.',
            de: 'Zu wenige Leute in der Bank: {{current}} von {{count}}.',
            pl: 'Za malo ludzi w banku: {{current}} z {{count}}.',
        },
        stepBusy: {
            ru: 'С этой дверью уже работают.',
            ua: 'З цими дверима вже працюють.',
            en: 'Someone is already working that door.',
            de: 'An dieser Tuer arbeitet schon jemand.',
            pl: 'Ktos juz pracuje przy tych drzwiach.',
        },
        pointBusy: {
            ru: 'Эту ячейку уже опустошают.',
            ua: 'Цю комірку вже спустошують.',
            en: 'Someone is already emptying that one.',
            de: 'Dieses Fach wird gerade schon geleert.',
            pl: 'Ktos juz oproznia ta skrytke.',
        },
        noEntryKit: {
            ru: 'Нужны карта допуска Fleeca и взломщик хранилища.',
            ua: 'Потрібні картка допуску Fleeca та зламувач сховища.',
            en: 'A Fleeca access card and a vault hacking device are needed.',
            de: 'Eine Fleeca-Zugangskarte und ein Tresor-Hacking-Geraet werden gebraucht.',
            pl: 'Potrzebna jest karta dostepu Fleeca i urzadzenie hakujace do skarbca.',
        },
    },
};
