export default {
    supplyBlip: {
        ru: 'Поставка',
        ua: 'Поставка',
        en: 'Supply',
        de: 'Lieferung',
        pl: 'Dostawa',
    },
    engineOffToStartLoad: {
        ru: 'Заглушите двигатель для начала погрузки',
        ua: 'Заглушіть двигун для початку завантаження',
        en: 'Turn off the engine to start loading',
        de: 'Motor ausschalten, um mit dem Laden zu beginnen',
        pl: 'Zgaś silnik, aby rozpocząć załadunek',
    },
    loadingComplete: {
        ru: 'Погрузка завершена',
        ua: 'Завантаження завершено',
        en: 'Loading complete',
        de: 'Ladevorgang abgeschlossen',
        pl: 'Załadunek zakończony',
    },
    loadingText: {
        ru: 'Идёт погрузка',
        ua: 'Йде завантаження',
        en: 'Loading',
        de: 'Wird geladen',
        pl: 'Trwa ładowanie',
    },
    invalidVehicleForSupply: {
        ru: 'Этот транспорт не подходит для погрузки',
        ua: 'Цей транспорт не підходить для завантаження',
        en: 'This vehicle is not suitable for loading',
        de: 'Dieses Fahrzeug ist nicht zum Beladen geeignet',
        pl: 'Ten pojazd nie nadaje się do załadunku',
    },
    alreadyLoaded: {
        ru: 'Этот транспорт уже заполнен',
        ua: 'Цей транспорт вже заповнений',
        en: 'This vehicle is already loaded',
        de: 'Dieses Fahrzeug ist bereits beladen',
        pl: 'Ten pojazd jest już załadowany',
    },
    materialsFinished: {
        ru: 'Все заказаные материалы были загружены, теперь вы должны довезти их до пункта назначения',
        ua: 'Усі замовлені матеріали завантажено, тепер ви повинні доставити їх до пункту призначення',
        en: 'All ordered materials have been loaded, now you must deliver them to the destination',
        de: 'Alle bestellten Materialien wurden geladen, jetzt müssen Sie sie zum Zielort bringen',
        pl: 'Wszystkie zamówione materiały zostały załadowane, teraz musisz je dostarczyć do miejsca docelowego',
    },
    goToUnloadingPoint: {
        ru: 'Отправляйтесь на разгрузку',
        ua: 'Вирушайте на розвантаження',
        en: 'Go to the unloading point',
        de: 'Fahren Sie zum Entladepunkt',
        pl: 'Udaj się do punktu rozładunku',
    },
    unloadingText: {
        ru: 'Идёт разгрузка',
        ua: 'Йде розвантаження',
        en: 'Unloading in progress',
        de: 'Entladung läuft',
        pl: 'Trwa rozładunek',
    },
    unloadingComplete: {
        ru: 'Успешно разгружено',
        ua: 'Успішно розвантажено',
        en: 'Successfully unloaded',
        de: 'Erfolgreich entladen',
        pl: 'Pomyślnie rozładowano',
    },
    wrongVehicleCapacity: {
        ru: 'Недостаточно материалов для разгрузки',
        ua: 'Недостатньо матеріалів для розвантаження',
        en: 'Not enough materials to unload',
        de: 'Nicht genügend Materialien zum Entladen',
        pl: 'Niewystarczająca ilość materiałów do rozładunku',
    },
    youStoleSupplyVehicle: {
        ru: 'Отвезите этот транспорт на вашу базу',
        ua: 'Відвезіть цей транспорт на вашу базу',
        en: 'Drive this vehicle to your base',
        de: 'Bringen Sie dieses Fahrzeug zu Ihrer Basis',
        pl: 'Zawieź ten pojazd do swojej bazy',
    },
    trackingBlip: {
        ru: 'Матовозка',
        ua: 'Матовозка',
        en: 'Mat Truck',
        de: 'Matten-LKW',
        pl: 'Ciężarówka z matami',
    },
};
