export default {
    supplyBlip: {
        ru: 'Поставка',
        ua: 'Поставка',
        en: 'Supply',
        de: 'Lieferung',
        pl: 'Dostawa',
    },
    engineOffToStartLoad: {
        ru: 'Заглушите двигатель для начала погрузки',
        ua: 'Заглушіть двигун для початку завантаження',
        en: 'Turn off the engine to start loading',
        de: 'Motor ausschalten, um mit dem Laden zu beginnen',
        pl: 'Zgaś silnik, aby rozpocząć załadunek',
    },
    loadingComplete: {
        ru: 'Погрузка завершена',
        ua: 'Завантаження завершено',
        en: 'Loading complete',
        de: 'Ladevorgang abgeschlossen',
        pl: 'Załadunek zakończony',
    },
    loadingText: {
        ru: 'Идёт погрузка',
        ua: 'Йде завантаження',
        en: 'Loading',
        de: 'Wird geladen',
        pl: 'Trwa ładowanie',
    },
    invalidVehicleForSupply: {
        ru: 'Этот транспорт не подходит для погрузки',
        ua: 'Цей транспорт не підходить для завантаження',
        en: 'This vehicle is not suitable for loading',
        de: 'Dieses Fahrzeug ist nicht zum Beladen geeignet',
        pl: 'Ten pojazd nie nadaje się do załadunku',
    },
    alreadyLoaded: {
        ru: 'Этот транспорт уже заполнен',
        ua: 'Цей транспорт вже заповнений',
        en: 'This vehicle is already loaded',
        de: 'Dieses Fahrzeug ist bereits beladen',
        pl: 'Ten pojazd jest już załadowany',
    },
    materialsFinished: {
        ru: 'Все заказаные материалы были загружены, теперь вы должны довезти их до пункта назначения',
        ua: 'Усі замовлені матеріали завантажено, тепер ви повинні доставити їх до пункту призначення',
        en: 'All ordered materials have been loaded, now you must deliver them to the destination',
        de: 'Alle bestellten Materialien wurden geladen, jetzt musst du sie zum Zielort bringen',
        pl: 'Wszystkie zamówione materiały zostały załadowane, teraz musisz je dostarczyć do miejsca docelowego',
    },
    supplyFinished: {
        ru: 'Поставка завершена',
        ua: 'Поставку завершено',
        en: 'Supply completed',
        de: 'Lieferung abgeschlossen',
        pl: 'Dostawa zakończona',
    },
    supplyCanceledByAdmin: {
        ru: 'Администратор {{admin}} отменил текущую поставку',
        ua: 'Адміністратор {{admin}} скасував поточне постачання',
        en: 'Administrator {{admin}} canceled the current supply',
        de: 'Administrator {{admin}} hat die aktuelle Lieferung abgebrochen',
        pl: 'Administrator {{admin}} anulował bieżącą dostawę',
    },
    goToUnloadingPoint: {
        ru: 'Отправляйтесь на разгрузку',
        ua: 'Вирушайте на розвантаження',
        en: 'Go to the unloading point',
        de: 'Fahre zum Entladepunkt',
        pl: 'Udaj się do punktu rozładunku',
    },
    unloadingText: {
        ru: 'Идёт разгрузка',
        ua: 'Йде розвантаження',
        en: 'Unloading in progress',
        de: 'Entladung läuft',
        pl: 'Trwa rozładunek',
    },
    unloadingComplete: {
        ru: 'Успешно разгружено',
        ua: 'Успішно розвантажено',
        en: 'Successfully unloaded',
        de: 'Erfolgreich entladen',
        pl: 'Pomyślnie rozładowano',
    },
    wrongVehicleCapacity: {
        ru: 'Недостаточно материалов для разгрузки',
        ua: 'Недостатньо матеріалів для розвантаження',
        en: 'Not enough materials to unload',
        de: 'Nicht genügend Materialien zum Entladen',
        pl: 'Niewystarczająca ilość materiałów do rozładunku',
    },
    youStoleSupplyVehicle: {
        ru: 'Отвезите этот транспорт на вашу базу',
        ua: 'Відвезіть цей транспорт на вашу базу',
        en: 'Drive this vehicle to your base',
        de: 'Bringe dieses Fahrzeug zu Ihrer Basis',
        pl: 'Zawieź ten pojazd do swojej bazy',
    },
    trackingBlip: {
        ru: 'Матовозка',
        ua: 'Матовозка',
        en: 'Mat Truck',
        de: 'Matten-LKW',
        pl: 'Ciężarówka z matami',
    },
    acceptedSupplyGoverment: {
        ru: 'Вы успешно подтвердили эту поставку, соотвествующая фракция выполнит её',
        ua: 'Ви успішно підтвердили цю поставку, відповідна фракція виконає її',
        en: 'You have successfully confirmed this supply, the corresponding faction will fulfill it',
        de: 'Du hast diese Lieferung erfolgreich bestätigt, die entsprechende Fraktion wird sie ausführen',
        pl: 'Pomyślnie potwierdziłeś tę dostawę, odpowiednia frakcja ją zrealizuje',
    },
    executorHasLowOnline: {
        ru: 'Текущая фракция исполнителя имеет недостаточный онлайн чтобы выполнить эту поставку',
        ua: 'Поточна фракція виконавця має недостатній онлайн, щоб виконати цю поставку',
        en: "The executor's current faction has insufficient online presence to complete this delivery",
        de: 'Die aktuelle Fraktion des Ausführers hat nicht genügend Online-Präsenz, um diese Lieferung abzuschließen',
        pl: 'Obecna frakcja wykonawcy ma niewystarczającą liczbę graczy online, aby zrealizować tę dostawę',
    },
    supplyAlreadyActive: {
        ru: 'Эта поставка уже активна',
        ua: 'Ця поставка вже активна',
        en: 'This supply is already active',
        de: 'Diese Lieferung ist bereits aktiv',
        pl: 'Ta dostawa jest już aktywna',
    },
    startSupplyExecutorMessage: {
        ru: 'Начинается поставка, скорее готовьте машины и отправляйтесь на неё!',
        ua: 'Починається поставка, скоріше готуйте машини та вирушайте на неї!',
        en: 'A supply run is starting, quickly prepare your vehicles and head out!',
        de: 'Eine Lieferung beginnt, bereitet schnell eure Fahrzeuge vor und macht euch auf den Weg!',
        pl: 'Rozpoczyna się dostawa, szybko przygotujcie pojazdy i ruszajcie w drogę!',
    },
    startClientSupplyMessage: {
        ru: 'Вашу заявку на поставку одобрили в правительстве, скоро вам привезут материалы',
        ua: 'Вашу заявку на постачання схвалили в уряді, скоро вам привезуть матеріали',
        en: 'Your supply request has been approved by the government, materials will be delivered to you soon',
        de: 'Ihr Lieferantrag wurde von der Regierung genehmigt, die Materialien werden Ihnen bald zugestellt',
        pl: 'Twój wniosek o dostawę został zatwierdzony przez rząd, wkrótce materiały zostaną ci dostarczone',
    },
    govermentMessage: {
        ru: 'Пришла новая заявка на поставку материалов',
        ua: 'Надійшла нова заявка на поставку матеріалів',
        en: 'A new request for the supply of materials has arrived',
        de: 'Eine neue Anfrage zur Lieferung von Materialien ist eingegangen',
        pl: 'Nadeszło nowe zgłoszenie na dostawę materiałów',
    },
};
