export default {
    refferalSystem: {
        ru: 'Реферальная система',
        ua: 'Реферальна система',
        en: 'Referral System',
        de: 'Empfehlungssystem',
        pl: 'System poleceń',
        zh:'转诊制度',
    },
    desc: {
        ru: 'Зови друзей, чтобы играть, ведь вместе не только веселее, но и выгоднее!',
        ua: 'Клич друзів, щоб грати, адже разом не тільки веселіше, а й вигідніше!',
        en: "Invite friends to play, because together it's not only more fun but also more profitable!",
        de: 'Lade Freunde zum Spielen ein, denn zusammen macht es nicht nur mehr Spaß, sondern ist auch profitabler!',
        pl: 'Zapraszaj przyjaciół do gry, bo razem jest nie tylko weselej, ale i bardziej opłacalnie!',
        zh:'邀请你的朋友！',
    },
    enterRefferalCode: {
        ru: 'Ввести реферальный код',
        ua: 'Введіть реферальний код',
        en: 'Enter Referral Code',
        de: 'Empfehlungscode eingeben',
        pl: 'Wprowadź kod polecający',
        zh:'输入转介代码', 
    },
    youAreReferralOf: {
        ru: 'Вы являетесь рефералом',
        ua: 'Ви є рефералом',
        en: 'You are a referral of',
        de: 'Sie sind ein Empfehlungsgeber von',
        pl: 'Jesteś poleconym przez',
        zh:'你是推荐人',
    },
    myRefferalCode: {
        ru: 'Мой реферальный код',
        ua: 'Мій реферальний код',
        en: 'My Referral Code',
        de: 'Mein Empfehlungscode',
        pl: 'Mój kod polecający',
        zh:'我的推荐代码',
    },
    refferals: {
        ru: 'Рефералов',
        ua: 'Рефералів',
        en: 'Referrals',
        de: 'Empfehlungen',
        pl: 'Polecenia',
        zh:'推荐',
    },
    earned: {
        ru: 'Заработано',
        ua: 'Зароблено',
        en: 'Earned',
        de: 'Verdient',
        pl: 'Zarobiono',
        zh:'已赚得',
    },
    achieveRefferalLevel: {
        ru: 'При достижении рефералом 5 лвл - ваш реферал получает 250 а вы 50 ',
        ua: 'При досягненні рефералом 5 рівня - ваш реферал отримує 250 а ви 50 ',
        en: 'Upon reaching level 5 by your referral, they get 250 and you get 50 ',
        de: 'Bei Erreichen von Level 5 durch Ihren Empfehlungsgeber erhalten sie 250 und Sie erhalten 50 ',
        pl: 'Po osiągnięciu poziomu 5 przez poleconego, otrzymuje on 250 a Ty 50 ',
        zh:'当你的推荐达到5级时，他们得到250，你得到50', 
    },
    donateRefferalBonus: {
        ru: 'При донате реферала вы получаете 1% от суммы его доната в ',
        ua: 'При донаті реферала ви отримуєте 1% від суми його донату в ',
        en: 'When your referral donates, you get 1% of their donation amount in ',
        de: 'Wenn Ihr Empfehlungsgeber spendet, erhalten Sie 1% des Spendenbetrags in ',
        pl: 'Kiedy Twój polecony przekazuje darowiznę, otrzymujesz 1% od jej kwoty w ',
        zh:'',
    },
    forExampleInput: {
        ru: 'Например: olymp',
        ua: 'Наприклад: olymp',
        en: 'For example: olymp',
        de: 'Zum Beispiel: olymp',
        pl: 'Na przykład: olymp',
        zh:'例如:olymp',
    },
    stats: {
        ru: 'Статистика',
        ua: 'Статистика',
        en: 'Stats',
        de: 'Statistiken',
        pl: 'Statystyki',
        zh:'统计', 
    },
    myReferrals: {
        ru: 'Мои рефералы',
        ua: 'Мої реферали',
        en: 'My Referrals',
        de: 'Meine Empfehlungen',
        pl: 'Moje polecenia',
        zh:'我的下线情况',
    },
    level: {
        ru: 'Уровень',
        ua: 'Рівень',
        en: 'Level',
        de: 'Stufe',
        pl: 'Poziom',
        zh:'级别',
    },
    date: {
        ru: 'Дата регистрации',
        ua: 'Дата реєстрації',
        en: 'Registration date',
        de: 'Registrierungsdatum',
        pl: 'Data rejestracji',
        zh:'注册时间',
    },

    //
    codeNotFound: {
        ru: 'Реферальный код не найден',
        ua: 'Реферальний код не знайдено',
        en: 'Referral code not found',
        de: 'Empfehlungscode nicht gefunden',
        pl: 'Kod polecający nie znaleziony',
        zh:'找不到转介代码',
    },
    youAlreadyActivatedCode: {
        ru: 'Вы уже активировали реферальный код: {{code}}',
        ua: 'Ви вже активували реферальний код: {{code}}',
        en: 'You have already activated the referral code: {{code}}',
        de: 'Sie haben den Empfehlungscode bereits aktiviert: {{code}}',
        pl: 'Już aktywowałeś kod polecający: {{code}}',
        zh:'您已经激活了推荐码:{{code}}',
    },
    youActivatedCode: {
        ru: 'Вы активировали реферальный код: {{code}} и получили {{award}} Olymp-Coins',
        ua: 'Ви активували реферальний код: {{code}} і отримали {{award}} Olymp-Coins',
        en: 'You activated the referral code: {{code}} and received {{award}} Olymp-Coins',
        de: 'Sie haben den Empfehlungscode: {{code}} aktiviert und {{award}} Olymp-Coins erhalten',
        pl: 'Aktywowałeś kod referencyjny: {{code}} i otrzymałeś {{award}} Olymp-Coins',
        zh:'您激活了推荐代码:{{code}}，并收到{{award}}奥林匹克币',
    },
    youGotAwardForLevel: {
        ru: 'Вы получили {{award}} Olymp-Coins и ${{moneyAward}} за достижение {{level}} уровня',
        ua: 'Ви отримали {{award}} Olymp-Coins і ${{moneyAward}} за досягнення {{level}} рівня',
        en: 'You got {{award}} Olymp-Coins and ${{moneyAward}} for reaching level {{level}}',
        de: 'Sie haben {{award}} Olymp-Coins und ${{moneyAward}} für das Erreichen von Level {{level}} erhalten',
        pl: 'Otrzymałeś {{award}} Olymp-Coins i ${{moneyAward}} za osiągnięcie poziomu {{level}}',
        zh:'达到级别{{level}}，你将获得{{award}}赞助币和${{moneyAward}}',
    },
    youCantActivateYourself: {
        ru: 'Вы не можете активировать свой собственный реферальный код',
        ua: 'Ви не можете активувати свій власний реферальний код',
        en: 'You cannot activate your own referral code',
        de: 'Sie können Ihren eigenen Empfehlungscode nicht aktivieren',
        pl: 'Nie możesz aktywować własnego kodu polecającego',
        zh:'您不能激活您自己的推荐代码',
    },

    hint0: {
        ru: '1. При вводе игроком вашего реферального кода, он становится вашим рефералом и сразу же получает <span style="color: var(--primary)">{{referralAward}} Olymp-Coins и {{referralAwardCash}} </span> для комфортного начала игры',
        ua: '1. При введенні гравцем вашого реферального коду, він стає вашим рефералом і відразу ж отримує <span style="color: var(--primary)">{{referralAward}} Olymp-Coins та {{referralAwardCash}} </span> для комфортного початку гри',
        en: '1. When a player enters your referral code, they become your referral and immediately receive <span style="color: var(--primary)">{{referralAward}} Olymp-Coins and {{referralAwardCash}} </span> for a comfortable start in the game',
        de: '1. Wenn ein Spieler Ihren Empfehlungscode eingibt, wird er Ihr Empfehlungsnehmer und erhält sofort <span style="color: var(--primary)">{{referralAward}} Olymp-Coins und {{referralAwardCash}} </span> für einen komfortablen Start ins Spiel',
        pl: '1. Po wprowadzeniu przez gracza twojego kodu polecającego, staje się twoim poleconym i natychmiast otrzymuje <span style="color: var(--primary)">{{referralAward}} Olymp-Coins i {{referralAwardCash}} </span> na komfortowy początek gry',
        zh:'当玩家输入你的推荐代码时，他们就会成为你的推荐代码，并立即收到<span style="color: var(- primary)">{{referralAward}}赞助币和{{referralAwardCash}} </span>在游戏中一个舒适的开始',
    },
    hint1: {
        ru: '2. При достижении рефералом <span style="color: var(--primary)">{{level}} уровня</span> - ваш реферал получает ещё <span style="color: var(--primary)">{{referralAward}} Olymp-Coins </span>а вы <span style="color: var(--primary)">{{yourAward}} Olymp-Coins</span>',
        ua: '2. При досягненні рефералом <span style="color: var(--primary)">{{level}} рівня</span> - ваш реферал отримує ще <span style="color: var(--primary)">{{referralAward}} Olymp-Coins </span>, а ви <span style="color: var(--primary)">{{yourAward}} Olymp-Coins</span>',
        en: '2. When your referral reaches <span style="color: var(--primary)">{{level}} level</span> - your referral receives another <span style="color: var(--primary)">{{referralAward}} Olymp-Coins </span> and you get <span style="color: var(--primary)">{{yourAward}} Olymp-Coins</span>',
        de: '2. Wenn Ihr Empfehlungsnehmer <span style="color: var(--primary)">{{level}} Level</span> erreicht - erhält Ihr Empfehlungsnehmer weitere <span style="color: var(--primary)">{{referralAward}} Olymp-Coins </span> und Sie erhalten <span style="color: var(--primary)">{{yourAward}} Olymp-Coins</span>',
        pl: '2. Po osiągnięciu przez twojego poleconego <span style="color: var(--primary)">{{level}} poziomu</span> - twój polecony otrzymuje kolejne <span style="color: var(--primary)">{{referralAward}} Olymp-Coins </span>, a ty otrzymujesz <span style="color: var(--primary)">{{yourAward}} Olymp-Coins</span>',
       zh:'当你的推荐达到<span style="color: var(——primary)">{{level}} level</span> -您的推荐人收到另一个<span style="color: var(——primary)">{{referralAward}} 赞助币 </span>得到<span style="color: var(——primary)"> {{yourAward}} 赞助币跨度< / >',
    },
    hint2: {
        ru: '3. При донате реферала вы получаете <span style="color: var(--primary)">{{percent}}%</span> от суммы его доната',
        ua: '3. При донаті реферала ви отримуєте <span style="color: var(--primary)">{{percent}}%</span> від суми його доната',
        en: '3. When your referral donates, you receive <span style="color: var(--primary)">{{percent}}%</span> of their donation amount',
        de: '3. Wenn Ihr Empfehlungsgeber spendet, erhalten Sie <span style="color: var(--primary)">{{percent}}%</span> des Spendenbetrags',
        pl: '3. Kiedy Twój polecony dokonuje darowizny, otrzymujesz <span style="color: var(--primary)">{{percent}}%</span> od kwoty jego darowizny',
        zh:'',
    },

    //
    days: {
        PN: {
            ru: 'Пн',
            ua: 'Пн',
            en: 'Mon',
            de: 'Mo',
            pl: 'Pn',
            zh:'星期一',
        },
        VT: {
            ru: 'Вт',
            ua: 'Вт',
            en: 'Tue',
            de: 'Di',
            pl: 'Wt',
            zh:'星期二',
        },
        SR: {
            ru: 'Ср',
            ua: 'Ср',
            en: 'Wed',
            de: 'Mi',
            pl: 'Śr',
            zh:'星期三',
        },
        CH: {
            ru: 'Чт',
            ua: 'Чт',
            en: 'Thu',
            de: 'Do',
            pl: 'Czw',
            zh:'星期四',
        },
        PT: {
            ru: 'Пт',
            ua: 'Пт',
            en: 'Fri',
            de: 'Fr',
            pl: 'Pt',
            zh:'星期五',
        },
        SB: {
            ru: 'Сб',
            ua: 'Сб',
            en: 'Sat',
            de: 'Sa',
            pl: 'Sb',
            zh:'星期六',
        },
        VS: {
            ru: 'Вс',
            ua: 'Нд',
            en: 'Sun',
            de: 'So',
            pl: 'Nd',
            zh:'星期日',
        },
    },
};
