export default {
    offerInvite: {
        ru: 'Предлагает вам вступить в группу к нему',
        ua: 'Пропонує вам приєднатися до його групи',
        en: 'Invites you to join their group',
        de: 'Lädt dich ein, seiner Gruppe beizutreten',
        pl: 'Zaproponował ci dołączenie do swojej grupy',
    },
    youCreatedParty: {
        ru: 'Вы создали группу. Код для вступления - в приложении "Группа" на телефоне.',
        ua: 'Ви створили групу. Код для вступу - у застосунку "Група" на телефоні.',
        en: 'You created a group. The join code is in the "Group" app on your phone.',
        de: 'Du hast eine Gruppe erstellt. Den Beitrittscode findest du in der App "Gruppe" auf dem Handy.',
        pl: 'Utworzyłeś grupę. Kod dołączenia znajdziesz w aplikacji "Grupa" w telefonie.',
    },
    playerJoinedParty: {
        ru: '{{name}} вступил в вашу группу',
        ua: '{{name}} вступив до вашої групи',
        en: '{{name}} joined your group',
        de: '{{name}} ist deiner Gruppe beigetreten',
        pl: '{{name}} dołączył do twojej grupy',
    },
    errors: {
        alreadyInParty: {
            ru: 'Вы уже состоите в группе',
            ua: 'Ви вже перебуваєте в групі',
            en: 'You are already in a group',
            de: 'Du bist bereits in einer Gruppe',
            pl: 'Jesteś już w grupie',
        },
        notInParty: {
            ru: 'Вы не состоите в группе',
            ua: 'Ви не перебуваєте в групі',
            en: 'You are not in a group',
            de: 'Du bist in keiner Gruppe',
            pl: 'Nie jesteś w grupie',
        },
        codeNotFound: {
            ru: 'Группы с таким кодом нет',
            ua: 'Групи з таким кодом немає',
            en: 'No group has this code',
            de: 'Keine Gruppe hat diesen Code',
            pl: 'Żadna grupa nie ma takiego kodu',
        },
        partyFull: {
            ru: 'В группе уже {{max}} участников',
            ua: 'У групі вже {{max}} учасників',
            en: 'The group already has {{max}} members',
            de: 'Die Gruppe hat bereits {{max}} Mitglieder',
            pl: 'Grupa ma już {{max}} członków',
        },
        notLeader: {
            ru: 'Это может только лидер группы',
            ua: 'Це може лише лідер групи',
            en: 'Only the group leader can do this',
            de: 'Das kann nur der Gruppenleiter',
            pl: 'Tylko lider grupy może to zrobić',
        },
        memberNotFound: {
            ru: 'Этого игрока уже нет в группе',
            ua: 'Цього гравця вже немає в групі',
            en: 'That player is no longer in the group',
            de: 'Dieser Spieler ist nicht mehr in der Gruppe',
            pl: 'Tego gracza nie ma już w grupie',
        },
        hudLimit: {
            ru: 'В HUD можно вывести не больше {{max}} участников',
            ua: 'У HUD можна вивести не більше {{max}} учасників',
            en: 'Up to {{max}} members fit on the HUD',
            de: 'Im HUD haben höchstens {{max}} Mitglieder Platz',
            pl: 'W HUD zmieści się najwyżej {{max}} członków',
        },
        targetInParty: {
            ru: 'Этот игрок уже состоит в группе',
            ua: 'Цей гравець уже перебуває в групі',
            en: 'That player is already in a group',
            de: 'Dieser Spieler ist bereits in einer Gruppe',
            pl: 'Ten gracz jest już w grupie',
        },
        inviteSelf: {
            ru: 'Нельзя пригласить самого себя',
            ua: 'Не можна запросити самого себе',
            en: "You can't invite yourself",
            de: 'Du kannst dich nicht selbst einladen',
            pl: 'Nie możesz zaprosić samego siebie',
        },
        noPermission: {
            ru: 'Ваша роль в группе этого не позволяет',
            ua: 'Ваша роль у групі цього не дозволяє',
            en: 'Your role in the group does not allow this',
            de: 'Deine Rolle in der Gruppe erlaubt das nicht',
            pl: 'Twoja rola w grupie na to nie pozwala',
        },
        targetBusy: {
            ru: 'Игрок ещё не ответил на другое предложение, попробуйте позже',
            ua: 'Гравець ще не відповів на іншу пропозицію, спробуйте пізніше',
            en: 'That player has not answered another offer yet, try again later',
            de: 'Dieser Spieler hat noch nicht auf ein anderes Angebot geantwortet, versuche es später',
            pl: 'Ten gracz nie odpowiedział jeszcze na inną propozycję, spróbuj później',
        },
        memberOffline: {
            ru: 'Лидерство можно передать только участнику в сети',
            ua: 'Лідерство можна передати лише учаснику в мережі',
            en: 'The lead can only go to a member who is online',
            de: 'Die Leitung kann nur an ein Mitglied gehen, das online ist',
            pl: 'Przywództwo można przekazać tylko członkowi, który jest online',
        },
    },
    youKickedFromParty: {
        ru: 'Вы были исключены из группы',
        ua: 'Вас було виключено з групи',
        en: 'You have been kicked from the group',
        de: 'Du wurdest aus der Gruppe entfernt',
        pl: 'Zostałeś wyrzucony z grupy',
    },
    youKickedPlayer: {
        ru: 'Вы исключили {{name}} из группы',
        ua: 'Ви виключили {{name}} з групи',
        en: 'You kicked {{name}} from the group',
        de: 'Du hast {{name}} aus der Gruppe entfernt',
        pl: 'Wyrzuciłeś {{name}} z grupy',
    },
    disband: {
        ru: 'Вы распустили группу',
        ua: 'Ви розпустили групу',
        en: 'You disbanded the group',
        de: 'Du hast die Gruppe aufgelöst',
        pl: 'Rozwiązałeś grupę',
    },
    disbandForPlayers: {
        ru: 'Группа в котором вы состояли было распущено',
        ua: 'Групу, в якій ви перебували, було розпущено',
        en: 'The group you were in has been disbanded',
        de: 'Die Gruppe, in der du warst, wurde aufgelöst',
        pl: 'Grupa, do której należałeś, została rozwiązana',
    },
    youJoinedParty: {
        ru: 'Вы присоединились к группе',
        ua: 'Ви приєдналися до групи',
        en: 'You joined the group',
        de: 'Du bist der Gruppe beigetreten',
        pl: 'Dołączyłeś do grupy',
    },
    maxMembers: {
        ru: 'Максимальное количество участников в группе достигнуто',
        ua: 'Досягнуто максимальну кількість учасників у групі',
        en: 'Maximum number of group members reached',
        de: 'Maximale Anzahl an Gruppenmitgliedern erreicht',
        pl: 'Osiągnięto maksymalną liczbę członków grupy',
    },

    partyTitle: {
        ru: 'Группа',
        ua: 'Група',
        en: 'Group',
        de: 'Gruppe',
        pl: 'Grupa',
    },
    speakerId: {
        ru: 'ID {{id}}',
        ua: 'ID {{id}}',
        en: 'ID {{id}}',
        de: 'ID {{id}}',
        pl: 'ID {{id}}',
    },

    kickTitle: {
        ru: 'Выберете игрока которого хотите исключить',
        ua: 'Виберіть гравця, якого хочете виключити',
        en: 'Select the player you want to kick',
        de: 'Wähle den Spieler aus, den du entfernen möchtest',
        pl: 'Wybierz gracza, którego chcesz wyrzucić',
    },
    youLeftParty: {
        "ru": "Вы покинули группу",
        "ua": "Ти покинув групу",
        "en": "You left the party",
        "de": "Du hast die Gruppe verlassen",
        "pl": "Opuściłeś grupę",
    },
    playerLeftParty: {
        "ru": "{{name}} покинул вашу группу",
        "ua": "{{name}} покинув твою групу",
        "en": "{{name}} left your party",
        "de": "{{name}} hat deine Gruppe verlassen",
        "pl": "{{name}} opuścił twoją grupę",
    },
    newLeader: {
        ru: 'Новым лидером группы стал {{name}}',
        ua: 'Новим лідером групи став {{name}}',
        en: '{{name}} is now the group leader',
        de: '{{name}} ist jetzt der Gruppenleiter',
        pl: '{{name}} jest teraz liderem grupy',
    },
    youAreNewLeader: {
        ru: 'Вы стали лидером группы',
        ua: 'Ви стали лідером групи',
        en: 'You are now the group leader',
        de: 'Du bist jetzt der Gruppenleiter',
        pl: 'Jesteś teraz liderem grupy',
    },
    chatMessage: {
        ru: '~t~[Группа] {{playerName}}: {{message}}',
        ua: '~t~[Група] {{playerName}}: {{message}}',
        en: '~t~[Party] {{playerName}}: {{message}}',
        de: '~t~[Gruppe] {{playerName}}: {{message}}',
        pl: '~t~[Grupa] {{playerName}}: {{message}}',
    },
    chatMessageOoc: {
        ru: '~t~[Группа] {{playerName}}: (( {{message}} ))',
        ua: '~t~[Група] {{playerName}}: (( {{message}} ))',
        en: '~t~[Party] {{playerName}}: (( {{message}} ))',
        de: '~t~[Gruppe] {{playerName}}: (( {{message}} ))',
        pl: '~t~[Grupa] {{playerName}}: (( {{message}} ))',
    },
};
