export default {
    desc: {
        ru: 'Динамичная игра с риском и выигрышем: взять небольшой <br />выигрыш пораньше или сорвать большой банк.',
        en: 'A dynamic game with risk and reward: take a small <br />win early or break the bank for a big payout.',
        ua: 'Динамічна гра з ризиком та виграшем: взяти <br />невеликий виграш раніше або взяти великий банк.',
        de: 'Ein dynamisches Spiel mit Risiko und Belohnung: Holen Sie sich einen kleinen Gewinn frühzeitig oder brechen Sie die Bank für einen großen Gewinn.',
        pl: 'Dynamiczna gra z ryzykiem i nagrodą: zdobądź małą wygraną wcześnie lub zdobądź duży bank.',
    },
    sumBet: {
        ru: 'Сумма ставки',
        en: 'Bet amount',
        ua: 'Сума ставки',
        de: 'Wetteinsatz',
        pl: 'Kwota zakładu',
    },
    autoOut: {
        ru: 'Авто-вывод',
        en: 'Auto-withdraw',
        ua: 'Авто-вивід',
        de: 'Automatischer Auszahlung',
        pl: 'Automatyczne wycofywanie',
    },
    bet: {
        ru: 'Сделать ставку',
        en: 'Place a bet',
        ua: 'Зробити ставку',
        de: 'Eine Wette platzieren',
        pl: 'Postaw zakład',
    },
    take: {
        ru: 'Забрать',
        en: 'Take',
        ua: 'Забрати',
        de: 'Nehmen',
        pl: 'Zabierz',
    },
    unavailable: {
        ru: 'Недоступно',
        en: 'Unavailable',
        ua: 'Недоступно',
        de: 'Nicht verfügbar',
        pl: 'Niedostępne',
    },
    playersBets: {
        ru: 'Ставки игроков',
        en: "Players' bets",
        ua: 'Ставки гравців',
        de: 'Spielerwetten',
        pl: 'Zakłady graczy',
    },
    noBets: {
        ru: 'Ставок нет',
        en: 'No bets',
        ua: 'Ставок немає',
        de: 'Keine Wetten',
        pl: 'Brak zakładów',
    },
    toStart: {
        ru: 'До начала',
        en: 'To start',
        ua: 'До початку',
        de: 'Bis zum Start',
        pl: 'Do rozpoczęcia',
    },
    inGame: {
        ru: 'В ИГРЕ',
        en: 'IN GAME',
        ua: 'У ГРІ',
        de: 'IM SPIEL',
        pl: 'W GRZE',
    },
};
