export default {
    messageForFaction: {
        ru: '~r~[Внимание] Где то в штате сброшен Air Drop, на карте появится примерная его позиция, отправляйтесь на поиски!',
        ua: "~r~[Увага] Десь у штаті скинуто Air Drop, на карті з'явиться приблизна його позиція, вирушайте на пошуки!",
        en: '~r~[Attention] Somewhere in the state an Air Drop has been dropped, an approximate position will appear on the map, go searching!',
        de: '~r~[Achtung] Irgendwo im Staat wurde ein Air Drop abgeworfen, eine ungefähre Position wird auf der Karte erscheinen, gehen Sie auf die Suche!',
        pl: '~r~[Uwaga] Gdzieś w stanie zrzucono Air Drop, na mapie pojawi się przybliżona jego pozycja, ruszajcie na poszukiwania!',
        zh: '在该州的某个地方空投了空投，地图上显示了它的大致位置，去看看！',
    },
    messageForAdmins: {
        ru: '~r~[ADMIN] Начался Air Drop, следите чтобы никто не нарушал правила на нём!',
        ua: '~r~[ADMIN] Почався Air Drop, слідкуйте, щоб ніхто не порушував правила на ньому!',
        en: '~r~[ADMIN] Air Drop has started, make sure no one is breaking the rules!',
        de: '~r~[ADMIN] Air Drop hat begonnen, stellen Sie sicher, dass niemand die Regeln bricht!',
        pl: '~r~[ADMIN] Rozpoczął się Air Drop, upewnij się, że nikt nie łamie zasad!',
        zh: '~r~[ADMN]空投已经开始，确保没有人违反规则！',
    },
    failedToDrop: {
        ru: '~r~[ADMIN] Аирдроп не сброшен так как недостаточно игроков в крайме',
        ua: '~r~[ADMIN] Аірдроп не скинуто, тому що недостатньо гравців у краймі',
        en: '~r~[ADMIN] Air Drop not dropped as there are not enough players in the crime',
        de: '~r~[ADMIN] Air Drop wurde nicht abgeworfen, da nicht genügend Spieler im Kriminalbereich sind',
        pl: '~r~[ADMIN] Air Drop nie został zrzucony, ponieważ nie ma wystarczającej liczby graczy w przestępstwie',
        zh: '~r~[ADMN]空投未投放，因为犯罪中没有足够的玩家',
    },

    // Cayo perico
    messageForFactionCayoPerico: {
        ru: '~r~[Внимание] На острове Cayo Perico был сброшен Air Drop, на карте появится примерная его позиция, отправляйтесь на поиски!',
        ua: "~r~[Увага] На острові Cayo Perico був скинутий Air Drop, на карті з'явиться його приблизна позиція, вирушайте на пошуки!",
        en: '~r~[Attention] An Air Drop has been dropped on Cayo Perico island, its approximate position will appear on the map, go search for it!',
        de: '~r~[Achtung] Ein Air Drop wurde auf der Insel Cayo Perico abgeworfen, seine ungefähre Position wird auf der Karte erscheinen, machen Sie sich auf die Suche!',
        pl: '~r~[Uwaga] Na wyspie Cayo Perico zrzucono Air Drop, jego przybliżona pozycja pojawi się na mapie, wyruszcie na poszukiwania!',
        ge: '~r~[ყურადღება] კაიო პერიკოს კუნძულზე ჩამოვარდა საჰაერო ჩამოტვირთვა, მისი სავარაუდო პოზიცია გამოჩნდება რუკაზე, მოძებნეთ!',
        zh: '“~r~[注意]在佩里科岛空投了飞机，地图上显示了它的大致位置，去搜索吧！',
    },
    messageForAdminsCayoPerico: {
        ru: '~r~[ADMIN] Начался Air Drop на Cayo Perico, следите чтобы никто не нарушал правила на нём!',
        ua: '~r~[ADMIN] Почався Air Drop на Cayo Perico, стежте щоб ніхто не порушував правила на ньому!',
        en: '~r~[ADMIN] An Air Drop has started on Cayo Perico, make sure no one breaks the rules during it!',
        de: '~r~[ADMIN] Ein Air Drop hat auf Cayo Perico begonnen, achten Sie darauf, dass niemand die Regeln verletzt!',
        pl: '~r~[ADMIN] Rozpoczął się Air Drop na Cayo Perico, upewnij się, że nikt nie łamie zasad podczas niego!',
        ge: '~r~[ADMIN] კაიო პერიკოზე დაიწყო საჰაერო ჩამოტვირთვა, დარწმუნდით, რომ არავინ არღვევს წესებს!',
        zh: '~r~[ADMN]佩里科岛已经开始空投，确保在空投过程中没有人违反规定！',
    },
    //
    plantInteraction: {
        ru: 'Заложить взрывчатку',
        ua: 'Закласти вибухівку',
        en: 'Plant the explosive',
        de: 'Sprengsatz platzieren',
        pl: 'Podłożyć ładunek wybuchowy',
    },
    openInteraction: {
        ru: 'Осмотреть ящик',
        ua: 'Оглянути ящик',
        en: 'Inspect the box',
        de: 'Kiste inspizieren',
        pl: 'Sprawdzić skrzynkę',
    },
    youPlantedBomb: {
        ru: 'Вы заложили взрывчатку, ожидайте взрыва',
        ua: 'Ви заклали вибухівку, чекайте вибуху',
        en: 'You planted the explosive, wait for the detonation',
        de: 'Sie haben den Sprengsatz platziert, warten Sie auf die Explosion',
        pl: 'Podłożyłeś ładunek wybuchowy, czekaj na detonację',
    },
    youHaveNoBomb: {
        ru: 'У вас нет C4',
        ua: 'У вас немає C4',
        en: "You don't have any C4",
        de: 'Sie haben kein C4',
        pl: 'Nie masz C4',
    },
};
