export default {
    database: {
        ru: 'База данных',
        ua: 'База даних',
        en: 'Database',
        de: 'Datenbank',
        pl: 'Baza danych',
    },
    citizens: {
        ru: 'Граждане',
        ua: 'Громадяни',
        en: 'Citizens',
        de: 'Bürger',
        pl: 'Obywatele',
    },
    stolenVehicles: {
        ru: 'Угонные автомобили',
        ua: 'Викрадені автомобілі',
        en: 'Stolen Vehicles',
        de: 'Gestohlene Fahrzeuge',
        pl: 'Skradzione pojazdy',
    },
    transport: {
        ru: 'Транспорт',
        ua: 'Транспорт',
        en: 'Transport',
        de: 'Transport',
        pl: 'Transport',
    },
    arrests: {
        ru: 'Аресты',
        ua: 'Арешти',
        en: 'Arrests',
        de: 'Verhaftungen',
        pl: 'Aresztowania',
    },
    id: {
        ru: 'ID',
        ua: 'ID',
        en: 'ID',
        de: 'ID',
        pl: 'ID',
    },
    organization: {
        ru: 'Организация',
        ua: 'Організація',
        en: 'Organization',
        de: 'Organisation',
        pl: 'Organizacja',
    },
    searchInput: {
        ru: 'Введите значение',
        ua: 'Введіть значення',
        en: 'Enter a value',
        de: 'Geben Sie einen Wert ein',
        pl: 'Wprowadź wartość',
    },
    name: {
        ru: 'Полное имя',
        ua: "Повне ім'я",
        en: 'Full name',
        de: 'Vollständiger Name',
        pl: 'Pełne imię i nazwisko',
    },
    wanted: {
        ru: 'Розыск',
        ua: 'Розшук',
        en: 'Wanted',
        de: 'Gesucht',
        pl: 'Poszukiwany',
    },
    arrestCount: {
        ru: 'Аресты',
        ua: 'Арешти',
        en: 'Arrests',
        de: 'Verhaftungen',
        pl: 'Aresztowania',
    },
    status: {
        ru: 'Статус',
        ua: 'Статус',
        en: 'Status',
        de: 'Status',
        pl: 'Status',
    },
    offline: {
        ru: 'Оффлайн',
        ua: 'Офлайн',
        en: 'Offline',
        de: 'Offline',
        pl: 'Offline',
    },
    online: {
        ru: 'Онлайн',
        ua: 'Онлайн',
        en: 'Online',
        de: 'Online',
        pl: 'Online',
    },

    // Страница пользователя
    caseArchive: {
        ru: 'Архив дел',
        ua: 'Архів справ',
        en: 'Case archive',
        de: 'Fallarchiv',
        pl: 'Archiwum spraw',
    },
    org: {
        ru: 'Орг.',
        ua: 'Орг.',
        en: 'Org.',
        de: 'Org.',
        pl: 'Org.',
    },
    employee: {
        ru: 'Сотрудник',
        ua: 'Співробітник',
        en: 'Employee',
        de: 'Mitarbeiter',
        pl: 'Pracownik',
    },
    type: {
        ru: 'Тип',
        ua: 'Тип',
        en: 'Type',
        de: 'Typ',
        pl: 'Typ',
    },
    reason: {
        ru: 'Причина',
        ua: 'Причина',
        en: 'Reason',
        de: 'Grund',
        pl: 'Powód',
    },
    date: {
        ru: 'Дата',
        ua: 'Дата',
        en: 'Date',
        de: 'Datum',
        pl: 'Data',
    },
    phoneNumber: {
        ru: 'Тел. номер',
        ua: 'Тел. номер',
        en: 'Phone number',
        de: 'Telefonnummer',
        pl: 'Numer telefonu',
    },
    none: {
        ru: 'Нет',
        ua: 'Немає',
        en: 'None',
        de: 'Keiner',
        pl: 'Brak',
    },
    back: {
        ru: 'Назад',
        ua: 'Назад',
        en: 'Back',
        de: 'Zurück',
        pl: 'Powrót',
    },
    issueSearch: {
        ru: 'Выдать розыск',
        ua: 'Оголосити розшук',
        en: 'Issue search',
        de: 'Fahndung ausstellen',
        pl: 'Wystaw poszukiwanie',
    },
    // Модальное окно
    issueWanted: {
        ru: 'Выдать розыск',
        ua: 'Оголосити розшук',
        en: 'Issue wanted',
        de: 'Fahndung ausstellen',
        pl: 'Wystaw poszukiwanie',
    },
    selectWantedLevel: {
        ru: 'Выберите уровень розыска',
        ua: 'Оберіть рівень розшуку',
        en: 'Select wanted level',
        de: 'Wählen Sie die Fahndungsstufe',
        pl: 'Wybierz poziom poszukiwania',
    },
    wantedLevel0: {
        ru: 'Нет розыска',
        ua: 'Немає розшуку',
        en: 'No wanted',
        de: 'Keine Fahndung',
        pl: 'Brak poszukiwania',
    },
    wantedLevel1: {
        ru: '1 звезда',
        ua: '1 зірка',
        en: '1 star',
        de: '1 Stern',
        pl: '1 gwiazdka',
    },
    wantedLevel2: {
        ru: '2 звезды',
        ua: '2 зірки',
        en: '2 stars',
        de: '2 Sterne',
        pl: '2 gwiazdki',
    },
    wantedLevel3: {
        ru: '3 звезды',
        ua: '3 зірки',
        en: '3 stars',
        de: '3 Sterne',
        pl: '3 gwiazdki',
    },
    wantedLevel4: {
        ru: '4 звезды',
        ua: '4 зірки',
        en: '4 stars',
        de: '4 Sterne',
        pl: '4 gwiazdki',
    },
    wantedLevel5: {
        ru: '5 звезд',
        ua: '5 зірок',
        en: '5 stars',
        de: '5 Sterne',
        pl: '5 gwiazdek',
    },
    reasonForWanted: {
        ru: 'Причина розыска',
        ua: 'Причина розшуку',
        en: 'Reason for wanted',
        de: 'Grund für Fahndung',
        pl: 'Powód poszukiwania',
    },
    leaveComment: {
        ru: 'Оставьте комментарий...',
        ua: 'Залиште коментар...',
        en: 'Leave a comment...',
        de: 'Hinterlassen Sie einen Kommentar...',
        pl: 'Zostaw komentarz...',
    },
    save: {
        ru: 'Сохранить',
        ua: 'Зберегти',
        en: 'Save',
        de: 'Speichern',
        pl: 'Zapisz',
    },
    cancel: {
        ru: 'Отмена',
        ua: 'Скасувати',
        en: 'Cancel',
        de: 'Abbrechen',
        pl: 'Anuluj',
    },

    //
    vehicleName: {
        ru: 'Модель',
        ua: 'Модель',
        en: 'Model',
        de: 'Modell',
        pl: 'Model',
    },
    vehicleOwner: {
        ru: 'Владелец',
        ua: 'Власник',
        en: 'Owner',
        de: 'Eigentümer',
        pl: 'Właściciel',
    },
    vehiclePlate: {
        ru: 'Гос. номер',
        ua: 'Держ. номер',
        en: 'License plate',
        de: 'Kennzeichen',
        pl: 'Tablica rejestracyjna',
    },

    //
    caseTypes: {
        wanted: {
            ru: 'Розыск',
            ua: 'Розшук',
            en: 'Wanted',
            de: 'Gesucht',
            pl: 'Poszukiwany',
        },
        arrest: {
            ru: 'Арест',
            ua: 'Арешт',
            en: 'Arrest',
            de: 'Verhaftung',
            pl: 'Aresztowanie',
        },
    },
    //
    noResults: {
        ru: 'Пусто',
        ua: 'Порожньо',
        en: 'Empty',
        de: 'Leer',
        pl: 'Pusto',
    },

    //
    youHaveNoRights: {
        ru: 'У вас нет доступа к базе данных',
        ua: 'У вас немає доступу до бази даних',
        en: 'You have no access to the database',
        de: 'Sie haben keinen Zugriff auf die Datenbank',
        pl: 'Nie masz dostępu do bazy danych',
    },

    //
    allLoaded: {
        ru: 'Больше ничего',
        ua: 'Більше нічого',
        en: 'Nothing more',
        de: 'Nichts weiter',
        pl: 'Nic więcej',
    },
    noResults: {
        ru: 'Ничего не найдено',
        ua: 'Нічого не знайдено',
        en: 'No results found',
        de: 'Keine Ergebnisse gefunden',
        pl: 'Nie znaleziono wyników',
    },
};
