export default {
    name: {
        ru: 'Война за территорию',
        ua: 'Війна за територію',
        en: 'Territory war',
        de: 'Gebietskrieg',
        pl: 'Wojna o terytorium',
        zh: '领土战争',
    },
    players: {
        ru: 'Участников',
        ua: 'Учасникiв',
        en: 'Participants',
        de: 'Teilnehmer',
        pl: 'Uczestników',
        zh: '参与者',
    },
    scoreboardPlayer: {
        ru: 'Игрок',
        ua: 'Гравець',
        en: 'Player',
        de: 'Spieler',
        pl: 'Gracz',
        zh: '玩家',
    },
    blip: {
        ru: 'Война за территорию',
        ua: 'Війна за територію',
        en: 'Territory war',
        de: 'Gebietskrieg',
        pl: 'Wojna o terytorium',
    },
    youSuccessDeclareWar: {
        ru: 'Вы успешно объявили войну за территорию',
        ua: 'Ви успішно оголосили війну за територію',
        en: 'You have successfully declared war for the territory',
        de: 'Du hast erfolgreich Krieg um das Territorium erklärt',
        pl: 'Pomyślnie ogłosiłeś wojnę o terytorium',
        zh: '你已经成功地向该领土宣战了',
    },
    youHasCooldown: {
        ru: 'Вы сейчас не можете объявить войну так как недавно воевали',
        ua: 'Ви зараз не можете оголосити війну так як недавно воювали',
        en: 'You are currently on a cooldown from declaring war',
        de: 'Du hast derzeit eine Abklingzeit für Kriegserklärungen',
        pl: 'Obecnie obowiązuje okres odnowienia po wypowiedzeniu wojny',
        zh: '你不能宣战，因为你最近一直在打仗',
    },
    targetHasCooldown: {
        ru: 'Банда которой вы объявляете войну недавно воевала',
        ua: 'Банда, якій ви оголошуєте війну, недавно воювала',
        en: 'The gang you are declaring war on is currently on a cooldown from being attacked',
        de: 'Die Bande, der du den Krieg erklärst, hat derzeit eine Abklingzeit für Angriffe',
        pl: 'Gang, której wypowiadasz wojnę, jest obecnie w stanie odnowienia po atakach',
        zh: '你宣战的帮派目前正处于被攻击的冷静期',
    },
    youDeclareWar: {
        ru: '~r~Объявлена война за территорию #{{zone}}. Начало через {{time}}. Состав: до {{maxPlayers}} с каждой стороны',
        ua: '~r~Оголошено війну за територію #{{zone}}. Початок через {{time}}. Ростер: до {{maxPlayers}} з кожної сторони',
        en: '~r~War declared for territory #{{zone}}. Starts in {{time}}. Roster: up to {{maxPlayers}} per side',
        de: '~r~Krieg um Gebiet #{{zone}} erklärt. Beginn in {{time}}. Aufstellung: bis zu {{maxPlayers}} pro Seite',
        pl: '~r~Wypowiedziano wojnę o terytorium #{{zone}}. Początek za {{time}}. Skład: do {{maxPlayers}} na stronę',
    },
    declaredWarToYou: {
        ru: '~r~Вам объявлена война за территорию #{{zone}}. Начало через {{time}}. Состав: до {{maxPlayers}} с каждой стороны',
        ua: '~r~Вам оголошено війну за територію #{{zone}}. Початок через {{time}}. Ростер: до {{maxPlayers}} з кожної сторони',
        en: '~r~War declared against you for territory #{{zone}}. Starts in {{time}}. Roster: up to {{maxPlayers}} per side',
        de: '~r~Gegen dich wurde Krieg um Gebiet #{{zone}} erklärt. Beginn in {{time}}. Aufstellung: bis zu {{maxPlayers}} pro Seite',
        pl: '~r~Wypowiedziano ci wojnę o terytorium #{{zone}}. Początek za {{time}}. Skład: do {{maxPlayers}} na stronę',
    },
    toLessMembersToStartWar: {
        ru: 'Для объявления войны необходимо минимум {{count}} человек',
        ua: 'Для оголошення війни необхідно мінімум {{count}} осіб',
        en: 'To declare war, you need a minimum of {{count}} people',
        de: 'Um Krieg zu erklären, benötigst du mindestens {{count}} Personen',
        pl: 'Aby ogłosić wojnę, potrzebujesz co najmniej {{count}} osób',
        zh: '要宣战，你需要至少{{count}}人',
    },
    tooLessMembersInEnemyTeam: {
        ru: 'Для объявления войны у врага должно быть онлайн минимум {{count}} человек',
        ua: 'Для оголошення війни у ворога повинно бути онлайн мінімум {{count}} осіб',
        en: 'To declare war, the enemy must have a minimum of {{count}} online players',
        de: 'Um Krieg zu erklären, muss der Feind mindestens {{count}} Online-Spieler haben',
        pl: 'Aby ogłosić wojnę, wróg musi mieć co najmniej {{count}} graczy online',
        zh: '要宣战，敌人必须至少有{{count}}名在线玩家',
    },
    failedBattle: {
        ru: '~r~Война за территорию не удалась из-за недостаточного кол-ва игроков из одной из сторон',
        ua: '~r~Війна за територію не вдалася через недостатню кількість гравців з одного з боків',
        en: '~r~The battle for the territory failed due to insufficient number of players on one of the sides',
        de: '~r~Der Kampf um das Gebiet ist aufgrund unzureichender Spielerzahl auf einer der Seiten gescheitert',
        pl: '~r~Bitwa o terytorium nie powiodła się z powodu niewystarczającej liczby graczy po jednej ze stron',
        zh: '~r~由于一方玩家数量不足，争夺领土的战斗失败了',
    },
    youAreInRoster: {
        ru: '~y~Вы в составе на битву за территорию #{{zone}}. Отправиться на бой можно у NPC на базе.',
        ua: '~y~Ви у ростері на битву за територію #{{zone}}. Вирушити на бій можна у NPC на базі.',
        en: '~y~You are on the roster for the battle for territory #{{zone}}. Head out at the NPC in your base.',
        de: '~y~Du stehst in der Aufstellung für den Kampf um Gebiet #{{zone}}. Losziehen kannst du beim NPC in deiner Basis.',
        pl: '~y~Jesteś w składzie na bitwę o terytorium #{{zone}}. Wyruszysz na walkę u NPC w swojej bazie.',
    },
    youJoinedWar: {
        ru: 'Вы отправлены в зону #{{zone}}. Ожидайте начала',
        ua: 'Вас відправлено в зону #{{zone}}. Очікуйте початку',
        en: 'Sent to zone #{{zone}}. Wait for the start',
        de: 'In Zone #{{zone}} geschickt. Warte auf den Beginn',
        pl: 'Wysłano do strefy #{{zone}}. Czekaj na początek',
    },
    warAlreadyDeclared: {
        ru: 'Война за территорию уже идёт',
        ua: 'Війна за територію вже йде',
        en: 'A territory war is already in progress',
        de: 'Ein Gebietskrieg läuft bereits',
        pl: 'Wojna o terytorium już trwa',
    },
    cantDeclareWar: {
        ru: 'Объявить войну за эту территорию нельзя',
        ua: 'Оголосити війну за цю територію не можна',
        en: 'War cannot be declared for this territory',
        de: 'Für dieses Gebiet kann kein Krieg erklärt werden',
        pl: 'Nie można wypowiedzieć wojny o to terytorium',
    },
    noActiveWar: {
        ru: 'Сбор на войну не идёт',
        ua: 'Збір на війну не йде',
        en: 'No war muster is open',
        de: 'Es läuft keine Sammlung für einen Krieg',
        pl: 'Zbiórka na wojnę nie trwa',
    },
    rosterNotPicked: {
        ru: 'Ваша сторона ещё не выбрала состав на бой',
        ua: 'Ваша сторона ще не обрала ростер на бій',
        en: 'Your side has not picked a roster for the battle yet',
        de: 'Deine Seite hat noch keine Aufstellung für den Kampf gewählt',
        pl: 'Twoja strona nie wybrała jeszcze składu na bitwę',
    },
    badWarTime: {
        ru: 'Такое время начала недоступно',
        ua: 'Такий час початку недоступний',
        en: 'That start time is not available',
        de: 'Diese Startzeit ist nicht verfuegbar',
        pl: 'Ta godzina rozpoczecia jest niedostepna',
    },
    notInRoster: {
        ru: 'Вас не включили в состав на этот капт',
        ua: 'Вас не включили до ростера на цей капт',
        en: 'You were not picked for this capture roster',
        de: 'Du wurdest nicht für diese Einnahme ausgewählt',
        pl: 'Nie zostałeś wybrany do składu na to przejęcie',
    },
    eliminatedOnStaging: {
        ru: 'Вы покинули зону боя и выбыли из этой войны',
        ua: 'Ви покинули зону бою та вибули з цієї війни',
        en: 'You left the battle zone and are out of this war',
        de: 'Du hast die Kampfzone verlassen und bist aus diesem Krieg raus',
        pl: 'Opuściłeś strefę walki i odpadłeś z tej wojny',
    },
    badLoadout: {
        ru: 'Выберите хотя бы одно оружие ближнего боя и один пистолет',
        ua: 'Оберіть хоча б одну зброю ближнього бою та один пістолет',
        en: 'Pick at least one melee weapon and one pistol',
        de: 'Wähle mindestens eine Nahkampfwaffe und eine Pistole',
        pl: 'Wybierz co najmniej jedną broń białą i jeden pistolet',
    },
    emptyRoster: {
        ru: 'Нужно выбрать хотя бы одного участника с правом на войну',
        ua: 'Потрібно обрати хоча б одного учасника з правом на війну',
        en: 'Pick at least one member cleared for the war',
        de: 'Wähle mindestens ein Mitglied mit Kriegsfreigabe aus',
        pl: 'Wybierz co najmniej jednego członka z dostępem do wojny',
    },
    cantPickRoster: {
        ru: 'У вас нет права отбирать состав на войну',
        ua: 'У вас немає права відбирати ростер на війну',
        en: 'You are not allowed to pick the war roster',
        de: 'Du darfst die Kriegsaufstellung nicht wählen',
        pl: 'Nie masz prawa wybierać składu na wojnę',
    },
    rosterBusy: {
        ru: 'Состав сейчас отбирает {{name}}',
        ua: 'Ростер зараз відбирає {{name}}',
        en: '{{name}} is picking the roster right now',
        de: '{{name}} wählt gerade die Aufstellung',
        pl: 'Skład wybiera teraz {{name}}',
    },
    rosterAlreadyPicked: {
        ru: 'Состав на эту войну уже отобран',
        ua: 'Ростер на цю війну вже відібрано',
        en: 'The roster for this war is already picked',
        de: 'Die Aufstellung für diesen Krieg steht bereits',
        pl: 'Skład na tę wojnę został już wybrany',
    },
    rosterSaved: {
        ru: 'Состав на войну сохранён: {{count}} чел.',
        ua: 'Ростер на війну збережено: {{count}} осіб',
        en: 'War roster saved: {{count}} players',
        de: 'Kriegsaufstellung gespeichert: {{count}} Spieler',
        pl: 'Skład na wojnę zapisany: {{count}} graczy',
    },
    warSlotsFull: {
        ru: 'Состав уже набран',
        ua: 'Ростер уже набрано',
        en: 'The roster is already full',
        de: 'Die Aufstellung ist bereits voll',
        pl: 'Skład jest już zebrany',
    },
    failedJoinWar: {
        ru: 'Отправить в зону не удалось. Повторите',
        ua: 'Відправити в зону не вдалося. Повторіть',
        en: 'Transport to the zone failed. Try again',
        de: 'Der Transport in die Zone ist fehlgeschlagen. Versuche es erneut',
        pl: 'Transport do strefy nie udał się. Powtórz',
    },
    underAttack: {
        ru: 'Вам объявили войну',
        ua: 'Вам оголосили війну',
        en: 'War declared on you',
        de: 'Dir wurde der Krieg erklärt',
        pl: 'Wypowiedziano ci wojnę',
    },
    slotsOverDefender: {
        ru: 'У защитников столько людей нет: максимум {{count}} с каждой стороны',
        ua: 'У захисників стільки людей немає: максимум {{count}} з кожного боку',
        en: 'The defenders do not have that many members: {{count}} per side at most',
        de: 'So viele Mitglieder haben die Verteidiger nicht: hoechstens {{count}} pro Seite',
        pl: 'Obroncy nie maja tylu ludzi: maksymalnie {{count}} na strone',
    },
    declaredOnZone: {
        ru: 'объявили войну за зону #{{zone}}',
        ua: 'оголосили війну за зону #{{zone}}',
        en: 'declared war for zone #{{zone}}',
        de: 'haben Krieg um Zone #{{zone}} erklaert',
        pl: 'wypowiedzieli wojne o strefe #{{zone}}',
    },
    weaponsCaption: {
        ru: 'Оружие',
        ua: 'Зброя',
        en: 'Weapons',
        de: 'Waffen',
        pl: 'Bron',
    },
    rosterTerm: {
        ru: 'до {{max}} с каждой стороны · отобрано {{count}}',
        ua: 'до {{max}} з кожного боку · відібрано {{count}}',
        en: 'up to {{max}} per side · {{count}} picked',
        de: 'bis zu {{max}} pro Seite · {{count}} gewaehlt',
        pl: 'do {{max}} na strone · wybrano {{count}}',
    },
    toStartShort: {
        ru: 'До начала',
        ua: 'До початку',
        en: 'To start',
        de: 'Bis zum Start',
        pl: 'Do rozpoczecia',
    },
    slotsCaption: {
        ru: 'Мест на бой',
        ua: 'Місць на бій',
        en: 'Slots',
        de: 'Plaetze',
        pl: 'Miejsc',
    },
    rosterCaption: {
        ru: 'Отобрано',
        ua: 'Відібрано',
        en: 'Picked',
        de: 'Gewaehlt',
        pl: 'Wybrano',
    },
    rosterPickedByLeaders: {
        ru: 'Состав отбирает тот, у кого есть право на это',
        ua: 'Ростер відбирає той, у кого є право на це',
        en: 'The roster is picked by whoever holds the right to do it',
        de: 'Die Aufstellung wählt, wer das Recht dazu hat',
        pl: 'Skład wybiera ten, kto ma do tego prawo',
    },
    underAttackWarning: {
        ru: 'Неявка на бой засчитывается как поражение: зона переходит атакующим',
        ua: 'Неявка на бій зараховується як поразка: зона переходить атакувальникам',
        en: 'A no-show counts as a defeat: the zone goes to the attackers',
        de: 'Nichterscheinen gilt als Niederlage: die Zone geht an die Angreifer',
        pl: 'Niestawienie sie liczy sie jako porazka: strefa przechodzi do atakujacych',
    },
    pickRoster: {
        ru: 'Собрать состав',
        ua: 'Зібрати ростер',
        en: 'Pick the roster',
        de: 'Aufstellung wählen',
        pl: 'Wybierz skład',
    },
    rosterLocked: {
        ru: 'Состав отобран и больше не меняется',
        ua: 'Ростер відібрано і більше не змінюється',
        en: 'The roster is picked and cannot be changed',
        de: 'Die Aufstellung steht fest und ist nicht mehr änderbar',
        pl: 'Skład został wybrany i nie podlega zmianie',
    },
    toStart: {
        ru: 'До начала:',
        ua: 'До початку:',
        en: 'To start:',
        de: 'Bis zum Start:',
        pl: 'Do rozpoczecia:',
        zh: '直到开始',
    },
    endingTitle: {
        ua: 'ВИ ПЕРЕМОГЛИ',
        ru: 'ВЫ ПОБЕДИЛИ',
        en: 'YOU WON',
        de: 'SIE HABEN GEWONNEN',
        pl: 'WYGRAŁEŚ',
        zh: '你赢了',
    },
    youLoseTitle: {
        ua: 'ВИ ПРОГРАЛИ',
        ru: 'ВЫ ПРОИГРАЛИ',
        en: 'YOU LOST',
        de: 'SIE HABEN VERLOREN',
        pl: 'PRZEGRAŁEŚ',
        zh: '你进步了',
    },
    youGotZone: {
        ua: 'Ви захопили територію #{{zone}}',
        ru: 'Вы захватили территорию #{{zone}}',
        en: 'You captured territory #{{zone}}',
        de: 'Du hast das Gebiet #{{zone}} erobert',
        pl: 'Zdobyłeś terytorium #{{zone}}',
        zh: '你已经占领了领土#{{zone}}',
    },
    youLoseZone: {
        ua: 'Ви втратили територію #{{zone}}',
        ru: 'Вы потеряли территорию #{{zone}}',
        en: 'You lost territory #{{zone}}',
        de: 'Du hast das Gebiet #{{zone}} verloren',
        pl: 'Straciłeś terytorium #{{zone}}',
        zh: '你失去了领土#{{zone}}',
    },
    youFailedToCapture: {
        ru: 'Вы не смогли захватить территорию #{{zone}}',
        ua: 'Ви не змогли захопити територію #{{zone}}',
        en: 'You failed to capture territory #{{zone}}',
        de: 'Du konntest das Gebiet #{{zone}} nicht erobern',
        pl: 'Nie udało ci się zdobyć terytorium #{{zone}}',
        zh: '你没能占领领土',
    },
    enemyFailedToCapture: {
        ru: 'Враг не смог захватить территорию #{{zone}}',
        ua: 'Ворог не зміг захопити територію #{{zone}}',
        en: 'The enemy failed to capture territory #{{zone}}',
        de: 'Der Feind konnte das Gebiet #{{zone}} nicht erobern',
        pl: 'Wrogi nie zdołał zdobyć terytorium #{{zone}}',
        zh: '敌人未能占领领土#{{zone}',
    },

    cooldown: {
        ru: 'Перезарядка',
        ua: 'Перезарядка',
        en: 'Cooldown',
        de: 'Abklingzeit',
        pl: 'Czas odnowienia',
        zh: '重新加载',
    },

    activeWar: {
        ru: 'Активная война',
        ua: 'Активна війна',
        en: 'Active War',
        de: 'Aktiver Krieg',
        pl: 'Wojna aktywna',
        zh: '积极战争',
    },

    income: {
        ru: 'Выручка',
        ua: 'Виручка',
        en: 'Income',
        de: 'Einnahmen',
        pl: 'Przychód',
        zh: '收入',
    },

    perHour: {
        ru: 'в час',
        ua: 'в годину',
        en: 'per hour',
        de: 'pro Stunde',
        pl: 'na godzine',
        zh: '以“每小时”为单位',
    },

    zone: {
        ru: 'Зона',
        ua: 'Зона',
        en: 'Zone',
        de: 'Zone',
        pl: 'Strefa',
        zh: '区域',
    },

    control: {
        ru: 'Контроль:',
        ua: 'Контроль:',
        en: 'Control:',
        de: 'Kontrolle:',
        pl: 'Kontrola:',
        zh: '控制',
    },
    maxPlayers: {
        ru: 'Макс. кол-во игроков:',
        ua: 'Макс. кількість гравців:',
        en: 'Max number of players:',
        de: 'Maximale Anzahl an Spielern:',
        pl: 'Maksymalna liczba graczy:',
        zh: '最大。玩家数量',
    },

    noPlayersInCapture: {
        ru: '~r~На захват территории никто не пришёл, поэтому война не состоялась',
        ua: '~r~На захоп території ніхто не прийшов, тому війна не відбулася',
        en: '~r~No one came to capture the territory, so the war didn’t happen',
        de: '~r~Niemand ist zur Gebietseroberung gekommen, also hat der Krieg nicht stattgefunden',
        pl: '~r~Nikt nie przyszedł na przejęcie terytorium, więc wojna się nie odbyła',
    },

    leaveFromZone: {
        ru: 'Вы покинули зону капта чем нарушили правила поэтому вы были убиты',
        ua: 'Ви покинули зону капта, чим порушили правила, тому вас було вбито',
        en: 'You left the capture zone, violating the rules, therefore you were killed',
        de: 'Du hast die Eroberungszone verlassen und damit gegen die Regeln verstoßen, daher wurdest du getötet',
        pl: 'Opuszczono strefę przejęcia, naruszając zasady, dlatego zostałeś zabity',
        zh: '你离开了抓捕区，违反了规定，因此被杀',
    },

    deathDialog: {
        title: {
            ru: 'Пал в бою',
            ua: 'Поліг у бою',
            en: 'Fell in battle',
            de: 'Im Kampf gefallen',
            pl: 'Poległ w walce',
        },
        message: {
            ru: 'Ты погиб на захвате. Хочешь уйти с поля боя или остаться мёртвым до конца?',
            ua: 'Ти загинув під час захоплення. Хочеш піти з поля бою чи залишитися мертвим до кінця?',
            en: 'You died during the capture. Do you want to leave the battlefield or stay dead until the end?',
            de: 'Du bist bei der Eroberung gestorben. Willst du das Schlachtfeld verlassen oder bis zum Ende tot bleiben?',
            pl: 'Zginąłeś podczas przejęcia. Chcesz opuścić pole bitwy czy pozostać martwy do końca?',
        },
        confirmButton: {
            ru: 'Покинуть',
            ua: 'Покинути',
            en: 'Leave',
            de: 'Verlassen',
            pl: 'Opuścić',
        },
        cancelButton: {
            ru: 'Остаться',
            ua: 'Залишитися',
            en: 'Stay',
            de: 'Bleiben',
            pl: 'Zostać',
        },
    },
    // LOST
    evenMyGrandmaShootsBetterThanYou: {
        ru: 'Даже моя бабушка стреляет лучше, чем вы!',
        ua: 'Навіть моя бабуся стріляє краще, ніж ви!',
        en: 'Even my grandma shoots better than you!',
        de: 'Selbst meine Oma schießt besser als du!',
        pl: 'Nawet moja babcia strzela lepiej niż ty!',
        zh: '连我祖母的投篮都比你好！',
    },
    lostBattleNotWar: {
        ru: 'Вы проиграли битву, а не войну',
        ua: 'Ви програли битву, а не війну',
        en: 'You lost the battle, not the war',
        de: 'Du hast die Schlacht verloren, nicht den Krieg',
        pl: 'Przegrałeś bitwę, nie wojnę',
        zh: '你输掉了一场战斗，而不是一场战争',
    },
    betterLuckNextTime: {
        ru: 'Повезет в следующий раз!',
        ua: 'Пощастить наступного разу!',
        en: 'Better luck next time!',
        de: 'Beim nächsten Mal mehr Glück!',
        pl: 'Powodzenia następnym razem!',
        zh: '祝你下次好运！',
    },
    defeatMakesStronger: {
        ru: 'Поражение лишь закаляет. С каждым разом мы только сильнее.',
        ua: 'Поразка тільки гартує. З кожним разом ми лише сильніші.',
        en: 'Defeat only hardens you. Each time, we come back stronger.',
        de: 'Niederlagen härten ab. Jedes Mal werden wir stärker.',
        pl: 'Porażka tylko hartuje. Z każdym razem jesteśmy silniejsi.',
    },
    almostSetARecord: {
        ru: 'Поставили рекорд по неудачам. Уже прогресс!',
        ua: 'Поставили рекорд із невдач. Уже прогрес!',
        en: 'Set a failure record - that’s progress already!',
        de: 'Rekord an Misserfolgen aufgestellt - das ist schon Fortschritt!',
        pl: 'Ustanowiliśmy rekord porażek. To już postęp!',
    },
    loseButBeautiful: {
        ru: 'Проиграли, зато как красиво! Почти как победили.',
        ua: 'Програли, зате як красиво! Майже як перемога.',
        en: 'We lost - but oh, how beautifully! Almost felt like a win.',
        de: 'Verloren - aber wie schön! Fast wie ein Sieg.',
        pl: 'Przegraliśmy, ale jak pięknie! Prawie jak zwycięstwo.',
    },
    fellButRise: {
        ru: 'Упали? Значит, скоро поднимемся ещё выше.',
        ua: 'Впали? Значить, скоро піднімемося ще вище.',
        en: 'Fell down? That means we’re about to rise even higher.',
        de: 'Gefallen? Dann stehen wir bald noch höher auf.',
        pl: 'Upadliśmy? To znaczy, że wkrótce wstaniemy jeszcze wyżej.',
    },

    // WIN
    nowTimeForSomeFood: {
        ru: 'Ну, а теперь можно и покушать...',
        ua: 'Ну, а тепер можна і поїсти...',
        en: "Now it's time for some food...",
        de: 'Jetzt ist Zeit für etwas zu essen...',
        pl: 'Teraz czas na jedzenie...',
        zh: '现在该吃点东西了',
    },
    evenGodsProudYou: {
        ru: 'Даже боги Олимпа верили в вас',
        ua: 'Навіть боги Олімпу вірили в вас',
        en: 'Even the gods of Olympus believed in you',
        de: 'Selbst die Götter des Olymp glaubten an dich',
        pl: 'Nawet bogowie Olimpu wierzyli w ciebie',
        zh: '就连奥林匹斯山的众神也相信你',
    },
    olympPeakToday: {
        ru: 'Сегодня вы взошли на вершину Олимпа, надолго ли это?',
        ua: 'Сьогодні ти піднявся на вершину Олімпу, надовго це?',
        en: 'Today you’ve reached the peak of Olympus - but how long will it last?',
        de: 'Heute bist du auf den Olymp gestiegen - aber wie lange bleibt das so?',
        pl: 'Dziś wspiąłeś się na szczyt Olimpu - ale na jak długo?',
    },
    easierToDethrone: {
        ru: 'Свергнуть соперников проще, чем удержаться на троне - не забывайте об этом.',
        ua: 'Скинути суперників легше, ніж утриматися на троні - не забувай про це.',
        en: 'Dethroning rivals is easier than staying on the throne - don’t forget that.',
        de: 'Gegner zu stürzen ist einfacher, als den Thron zu halten - vergiss das nicht.',
        pl: 'Obalić rywali jest łatwiej niż utrzymać się na tronie - nie zapominaj o tym.',
    },
    victoryIsJustBeginning: {
        ru: 'Победа - лишь начало. Сможете ли вы остаться наверху?',
        ua: 'Перемога - лише початок. Чи зможеш ти залишитися нагорі?',
        en: 'Victory is just the beginning. Can you stay on top?',
        de: 'Der Sieg ist nur der Anfang. Kannst du dich an der Spitze halten?',
        pl: 'Zwycięstwo to dopiero początek. Czy zdołasz pozostać na szczycie?',
    },
    everyWinIsYourStrength: {
        ru: 'С каждой победой вы становитесь только сильнее.',
        ua: 'З кожною перемогою ти стаєш тільки сильнішим.',
        en: 'With every win, you only grow stronger.',
        de: 'Mit jedem Sieg wirst du nur stärker.',
        pl: 'Z każdym zwycięstwem stajesz się silniejszy.',
    },
    stepTowardsGlory: {
        ru: 'Каждая победа - это шаг к настоящей славе. Так держать!',
        ua: 'Кожна перемога - це крок до справжньої слави. Так тримати!',
        en: 'Every win is a step toward true glory. Keep it up!',
        de: 'Jeder Sieg ist ein Schritt zu echtem Ruhm. Weiter so!',
        pl: 'Każde zwycięstwo to krok ku prawdziwej chwale. Tak trzymaj!',
    },

    // DRAW
    stalemate: {
        ru: 'Ничья',
        ua: 'Нічия',
        en: 'Stalemate',
        de: 'Unentschieden',
        pl: 'Remis',
    },
};
