export default {
    categories: {
        all: {
            ru: 'Все',
            ua: 'Всі',
            en: 'All',
            de: 'Alle',
            pl: 'Wszystko',
            zh: '每个人',
        },
        money: {
            ru: 'Денежные операции',
            ua: 'Грошові операції',
            en: 'Money operations',
            de: 'Geldoperationen',
            pl: 'Operacje pieniężne',
            zh: '货币操作',
        },
        inventory: {
            ru: 'Инвентарь',
            ua: 'Інвентар',
            en: 'Inventory',
            de: 'Inventar',
            pl: 'Inwentarz',
            zh: '发明人',
        },
        pills: {
            ru: 'Таблетки',
            ua: 'Таблетки',
            en: 'Pills',
            de: 'Pillen',
            pl: 'Pigułki',
            zh: '平板电脑',
        },
        actions: {
            ru: 'Действия',
            ua: 'Дії',
            en: 'Actions',
            de: 'Aktionen',
            pl: 'Działania',
            zh: '行动',
        },
        members: {
            ru: 'Участники',
            ua: 'Учасники',
            en: 'Members',
            de: 'Mitglieder',
            pl: 'Członkowie',
            zh: '参与者',
        },
        fines: {
            ru: 'Штрафы',
            ua: 'Штрафи',
            en: 'Fines',
            de: 'Bußgelder',
            pl: 'Grzywny',
            zh: '罚款',
        },
        zones: {
            ru: 'Територии',
            ua: 'Території',
            en: 'Territories',
            de: 'Gebiete',
            pl: 'Terytoria',
            zh: '领土',
        },
        ranks: {
            ru: 'Ранги',
            ua: 'Ранги',
            en: 'Ranks',
            de: 'Ränge',
            pl: 'Rangi',
        },
        tickets: {
            ru: 'Военные билеты',
            ua: 'Військові квитки',
            en: 'Military tickets',
            de: 'Militärtickets',
            pl: 'Bilety wojskowe',
        },
        licenses: {
            'ru': 'Лицензии',
            'ua': 'Ліцензії',
            'en': 'Licenses',
            'de': 'Lizenzen',
            'pl': 'Licencje',
        },
    },

    //
    moneyOperations: {
        add: {
            'pointCaptureWin': {
                'ru': 'Ваша банда победила в захвате точки и получила ${{money}}',
                'ua': 'Ваша банда перемогла у захопленні точки й отримала ${{money}}',
                'en': 'Your gang won the point capture and received ${{money}}',
                'de': 'Deine Gang hat den Punkt eingenommen und ${{money}} erhalten',
                'pl': 'Twoja banda wygrała przejęcie punktu i otrzymała ${{money}}',
            },
            'acceptedSupplyGoverment': {
                'ru': 'Одобрение поставки для {{factionName}}, получено: ${{money}}',
                'ua': 'Постачання для {{factionName}} схвалено, отримано: ${{money}}',
                'en': 'Supply for {{factionName}} approved, received: ${{money}}',
                'de': 'Lieferung für {{factionName}} genehmigt, erhalten: ${{money}}',
                'pl': 'Dostawa dla {{factionName}} zatwierdzona, otrzymano: ${{money}}',
            },
            'boughtSurgeonOperation': {
                'ru': '{{name}} купил операцию по смене внешности у хирурга. Получено: ${{money}}',
                'ua': '{{name}} придбав операцію зі зміни зовнішності у хірурга. Отримано: ${{money}}',
                'en': '{{name}} bought a cosmetic surgery from the surgeon. Received: ${{money}}',
                'de': '{{name}} hat eine Schönheitsoperation beim Chirurgen gekauft. Erhalten: ${{money}}',
                'pl': '{{name}} kupił operację zmiany wyglądu u chirurga. Otrzymano: ${{money}}',
            },
            'takedVehicleFromImpound': {
                'ru': '{{name}} забрал свою машину с штрафстоянки. Получено: ${{money}}',
                'ua': '{{name}} забрав свою машину зі штрафмайданчика. Отримано: ${{money}}',
                'en': '{{name}} took their car from the impound lot. Received: ${{money}}',
                'de': '{{name}} hat sein Auto vom Abschlepphof geholt. Erhalten: ${{money}}',
                'pl': '{{name}} odebrał swój samochód z parkingu policyjnego. Otrzymano: ${{money}}',
            },
            'boughtAd': {
                'ru': '{{name}} подал заявку на рекламу. Получено ${{name}}',
                'ua': '{{name}} подав заявку на рекламу. Отримано ${{name}}',
                'en': '{{name}} submitted an ad request. Received ${{name}}',
                'de': '{{name}} hat eine Werbeanfrage gestellt. Erhalten ${{name}}',
                'pl': '{{name}} złożył wniosek o reklamę. Otrzymano ${{name}}',
            },
        },
        take: {
            'upgradePayday': {
                'ru': 'Плата за улучшения {{upgrade}}. -${{money}}',
                'ua': 'Оплата за покращення {{upgrade}}. -${{money}}',
                'en': 'Upgrade fee for {{upgrade}}. -${{money}}',
                'de': 'Upgrade-Gebühr für {{upgrade}}. -${{money}}',
                'pl': 'Opłata za ulepszenie {{upgrade}}. -${{money}}',
            },
            'vehicleImpoundSalary': {
                'ru': '{{name}} выплата зарплаты эвакуаторищка. -${{money}}',
                'ua': '{{name}} виплата зарплати евакуаторнику. -${{money}}',
                'en': '{{name}} tow truck driver salary payout. -${{money}}',
                'de': '{{name}} Gehaltszahlung für Abschleppfahrer. -${{money}}',
                'pl': '{{name}} wypłata dla lawetnika. -${{money}}',
            },
            'boughtUpgrade': {
                'ru': 'Покупка улучшения {{upgrade}} -${{money}}',
                'ua': 'Покупка покращення {{upgrade}} -${{money}}',
                'en': 'Purchased upgrade {{upgrade}} -${{money}}',
                'de': 'Upgrade {{upgrade}} gekauft -${{money}}',
                'pl': 'Zakup ulepszenia {{upgrade}} -${{money}}',
            },
            'orderSupply': {
                'ru': 'Заказ поставки материалов. -${{money}}',
                'ua': 'Замовлення постачання матеріалів. -${{money}}',
                'en': 'Ordered material supply. -${{money}}',
                'de': 'Materiallieferung bestellt. -${{money}}',
                'pl': 'Zamówienie dostawy materiałów. -${{money}}',
            },
        },
    },
    //
    invitedPlayer: {
        ru: 'Пригласил игрока {{player}}',
        ua: 'Запросив гравця {{player}}',
        en: 'Invited player {{player}}',
        de: 'Eingeladener Spieler {{player}}',
        pl: 'Zaprosił gracza {{player}}',
        zh: '受邀玩家{{player}}',
    },
    kickedPlayer: {
        ru: 'Выгнал игрока {{player}}',
        ua: 'Вигнав гравця {{player}}',
        en: 'Kicked out player {{player}}',
        de: 'Spieler {{player}} rausgeworfen',
        pl: 'Wyrzucił gracza {{player}}',
        zh: '玩家{{Player}}被踢出',
    },
    deposited: {
        ru: 'Пополнил бюджет на ${{money}}',
        ua: 'Поповнив бюджет на ${{money}}',
        en: 'Deposited to the budget ${{money}}',
        de: 'Budget auf ${{money}} aufgefüllt',
        pl: 'Doładowałem budżet o ${{money}}',
        zh: '存入预算${货币}',
    },
    withdraw: {
        ru: 'Взял с бюджета ${{money}}',
        ua: 'Взяв з бюджету ${{money}}',
        en: 'Withdrew from the budget ${{money}}',
        de: 'Vom Budget ${{money}} abgehoben',
        pl: 'Wypłaciłem z budżetu ${{money}}',
        zh: '从预算中提取${货币}',
    },
    test: {
        ru: 'Абоба №{{num}}',
        ua: 'Абоба №{{num}}',
        en: 'Aboba No. {{num}}',
        de: 'Aboba Nr. {{num}}',
        pl: 'Aboba nr {{num}}',
        zh: '阿巴号',
    },
    sellPills: {
        ru: 'Продал таблетки {{type}} на ${{sum}}',
        ua: 'Продав таблетки {{type}} за ${{sum}}',
        en: 'Sold {{type}} pills for ${{sum}}',
        de: '{{type}} Pillen für ${{sum}} verkauft',
        pl: 'Sprzedano tabletki {{type}} za ${{sum}}',
        zh: '“以{{type}}美元的价格出售平板电脑',
    },
    takedBlood: {
        ru: 'Взял кровь у {{name}}',
        ua: 'Взяв кров у {{name}}',
        en: 'Took blood from {{name}}',
        de: 'Hat Blut von {{name}} genommen',
        pl: 'Pobrał krew od {{name}}',
        zh: '从{{name}}身上取了血',
    },
    sellBloodBag: {
        ru: 'Сдал кровь в лабаратории на сумму ${{sum}}',
        ua: 'Здав кров в лабораторії на суму ${{sum}}',
        en: 'Donated blood in the laboratory for the amount of ${{sum}}',
        de: 'Hat Blut im Labor für den Betrag von ${{sum}} gespendet',
        pl: 'Oddał krew w laboratorium za kwotę ${{sum}}',
        zh: '以{{sum}美元的价格向实验室献血',
    },
    giveMedicalLicense: {
        ru: 'Выдал медицинскую лицензию {{player}}',
        ua: 'Видав медичну ліцензію {{player}}',
        en: 'Issued a medical license to {{player}}',
        de: 'Hat eine medizinische Lizenz an {{player}} ausgestellt',
        pl: 'Wydano licencję medyczną dla {{player}}',
        zh: '已颁发医疗执照{{player}}',
    },
    renewMedicalLicense: {
        ru: 'Возобновил медицинскую лицензию {{player}}',
        ua: 'Оновив медичну ліцензію {{player}}',
        en: 'Renewed the medical license of {{player}}',
        de: 'Hat die medizinische Lizenz von {{player}} erneuert',
        pl: 'Odnowiono licencję medyczną dla {{player}}',
        zh: '更新{{player}}的医疗执照',
    },

    //
    putItemToInventory: {
        ru: 'Положил {{item}} ({{quantity}}x) на склад',
        ua: 'Поклав {{item}} ({{quantity}}x) на склад',
        en: 'Put {{item}} ({{quantity}}x) in inventory',
        de: 'Lege {{item}} ({{quantity}}x) ins Inventar',
        pl: 'Umieścił {{item}} ({{quantity}}x) w ekwipunku',
        zh: '已将{{item}}（{{quantity}}x）放入存储中',
    },

    takeItemFromInventory: {
        ru: 'Взял {{item}} ({{quantity}}x) с склада',
        ua: 'Взяв {{item}} ({{quantity}}x) зі складу',
        en: 'Took {{item}} ({{quantity}}x) from inventory',
        de: 'Nahm {{item}} ({{quantity}}x) aus dem Inventar',
        pl: 'Zabrał {{item}} ({{quantity}}x) z ekwipunku',
        zh: '从存储中获取{{item}}（{{quantity}}x）',
    },

    //
    ticketed: {
        ru: 'Выписал штраф {{name}} на сумму ${{value}} по причине {{reason}}. Коментарий: {{comment}}',
        ua: 'Виписав штраф {{name}} на суму ${{value}} з причини {{reason}}. Коментар: {{comment}}',
        en: 'Issued a fine to {{name}} in the amount of ${{value}} for the reason: {{reason}}. Comment: {{comment}}',
        de: 'Hat {{name}} ein Bußgeld in Höhe von ${{value}} aus folgendem Grund verhängt: {{reason}}. Kommentar: {{comment}}',
        pl: 'Wystawił grzywnę {{name}} w wysokości ${{value}} z następującego powodu: {{reason}}. Komentarz: {{comment}}',
        zh: '对{{name}}处以金额为${value}}的罚款，原因为：{{reason}}。评论：｛｛Comment｝｝',
    },

    //
    zoneIncome: {
        ru: 'Выручка от территорий ${{amount}}',
        ua: 'Виручка від територій ${{amount}}',
        en: 'Revenue from territories ${{amount}}',
        de: 'Einnahmen aus Gebieten ${{amount}}',
        pl: 'Przychody z terytoriów ${{amount}}',
        zh: '来自领土的收入${金额}',
    },

    failedZoneIncome: {
        ru: 'Из-за недостаточного кол-ва игроков выручка от территорий не получена!',
        ua: 'Через недостатню кількість гравців дохід від територій не отримано!',
        en: 'Due to an insufficient number of players, no income was received from the territories!',
        de: 'Aufgrund einer unzureichenden Anzahl von Spielern wurde kein Einkommen aus den Gebieten erzielt!',
        pl: 'Z powodu niewystarczającej liczby graczy dochód z terytoriów nie został uzyskany!',
        ge: 'მოთამაშეთა არასაკმარისი რაოდენობის გამო, ტერიტორიის შემოსავალი ვერ მიიღეს!',
        zh: '由于玩家数量不足，没有从领土获得任何收入！',
    },

    declaredWar: {
        ru: 'Объявил войну за территорию #{{zone}}.',
        ua: 'Оголосив війну за територію #{{zone}}.',
        en: 'Declared war for territory #{{zone}}.',
        de: 'Krieg um Gebiet #{{zone}} erklärt. ',
        pl: 'Wypowiedziano wojnę o terytorium #{{zone}}',
        zh: '对领土宣战',
    },
    startedWar: {
        ru: 'Началась война за территорию #{{zone}}.',
        ua: 'Розпочалася війна за територію #{{zone}}.',
        en: 'War started for territory #{{zone}}.',
        de: 'Krieg um Gebiet #{{zone}} hat begonnen.',
        pl: 'Rozpoczęła się wojna o terytorium #{{zone}}.',
        zh: '战争是为了领土而开始的',
    },
    youWinZone: {
        ru: 'Вы выиграли войну за территорию #{{zone}}.',
        ua: 'Ви виграли війну за територію #{{zone}}.',
        en: 'You won the war for territory #{{zone}}.',
        de: 'Du hast den Krieg um Gebiet #{{zone}} gewonnen.',
        pl: 'Wygrałeś wojnę o terytorium #{{zone}}.',
        zh: '你赢得了领土上的战争',
    },
    youLoseZone: {
        ru: 'Вы проиграли войну за территорию #{{zone}}.',
        ua: 'Ви програли війну за територію #{{zone}}.',
        en: 'You lost the war for territory #{{zone}}.',
        de: 'Du hast den Krieg um Gebiet #{{zone}} verloren.',
        pl: 'Przegrałeś wojnę o terytorium #{{zone}}.',
        zh: '你在争夺领土的战争中失败了',
    },
    failedToStartWar: {
        ru: 'Не удалось начать войну за территорию #{{zone}}.',
        ua: 'Не вдалося розпочати війну за територію #{{zone}}.',
        en: 'Failed to start the war for territory #{{zone}}.',
        de: 'Krieg um Gebiet #{{zone}} konnte nicht begonnen werden.',
        pl: 'Nie udało się rozpocząć wojny o terytorium #{{zone}}.',
        zh: '无法开始对#{zone}}领土的战争。',
    },

    //
    createdRank: {
        ru: 'Создал новый ранг {{rank}}',
        ua: 'Створив новий ранг {{rank}}',
        en: 'Created a new rank {{rank}}',
        de: 'Neuen Rang erstellt {{rank}}',
        pl: 'Utworzono nową rangę {{rank}}',
    },
    deletedRank: {
        ru: 'Удалил ранг {{rank}}',
        ua: 'Видалив ранг {{rank}}',
        en: 'Deleted rank {{rank}}',
        de: 'Rang gelöscht {{rank}}',
        pl: 'Usunięto rangę {{rank}}',
    },
    updatedRank: {
        ru: 'Обновил ранг {{rank}}',
        ua: 'Оновив ранг {{rank}}',
        en: 'Updated rank {{rank}}',
        de: 'Rang aktualisiert {{rank}}',
        pl: 'Zaktualizowano rangę {{rank}}',
    },
    updatedMemberRank: {
        ru: 'Обновил ранг участника {{member}} на {{rank}}',
        ua: 'Оновив ранг учасника {{member}} на {{rank}}',
        en: 'Updated member {{member}}\'s rank to {{rank}}',
        de: 'Rang von Mitglied {{member}} auf {{rank}} aktualisiert',
        pl: 'Zaktualizowano rangę członka {{member}} na {{rank}}',
    },
    giveWarn: {
        ru: 'Выдал предупреждение {{member}}. (({{warns}}/3))',
        ua: 'Видав догану {{member}}. (({{warns}}/3))',
        en: 'Issued a warning to {{member}}. (({{warns}}/3))',
        de: 'Hat eine Verwarnung an {{member}} erteilt. (({{warns}}/3))',
        pl: 'Wystawił ostrzeżenie dla {{member}}. (({{warns}}/3))',
    },

    //
    giveMiltaryTicket: {
        ru: 'Выдал военный билет {{name}}',
        ua: 'Видав військовий квиток {{name}}',
        en: 'Issued military ticket to {{name}}',
        de: 'Militärausweis an {{name}} ausgegeben',
        pl: 'Wydał bilet wojskowy {{name}}',
    },

    // sellLicense
    sellLicense: {
        'ru': 'Продал лицензию {{name}} за {{price}}$',
        'ua': 'Продав ліцензію {{name}} за {{price}}$',
        'en': 'Sold license {{name}} for {{price}}$',
        'de': 'Lizenz {{name}} für {{price}}$ verkauft',
        'pl': 'Sprzedano licencję {{name}} za {{price}}$',
    },
};
