export default {
    warehouse: {
        ru: 'Доступ к складу',
        ua: 'Доступ до складу',
        en: 'Warehouse Access',
        de: 'Zugang zum Lager',
        pl: 'Dostęp do magazynu',
        zh: '仓库访问',
    },
    inventory: {
        ru: 'Доступ к складу',
        ua: 'Доступ до складу',
        en: 'Access to inventory',
        de: 'Zugang zum Lager',
        pl: 'Dostęp do magazynu',
        zh: '访问存储',
    },
    garage: {
        ru: 'Доступ к гаражу',
        ua: 'Доступ до гаражу',
        en: 'Garage Access',
        de: 'Zugang zur Garage',
        pl: 'Dostęp do garażu',
        zh: '进入车库',
    },
    workshop: {
        ru: 'Доступ к крафтам',
        ua: 'Доступ до майстерні',
        en: 'Workshop Access',
        de: 'Zugang zur Werkstatt',
        pl: 'Dostęp do warsztatu',
        zh: '进入大楼',
    },
    wanted: {
        ru: 'Доступ к розыскам',
        ua: 'Доступ до розшуків',
        en: 'Wanted Access',
        de: 'Zugang zur Fahndung',
        pl: 'Dostęp do listy gończej',
        zh: '想要访问',
    },
    members: {
        ru: 'Доступ к управлению членами',
        ua: 'Доступ до управління членами',
        en: 'Members Management Access',
        de: 'Zugang zur Mitgliederverwaltung',
        pl: 'Dostęp do zarządzania członkami',
        zh: '访问成员管理',
    },
    acceptCalls: {
        ru: 'Принимать вызовы на скорую помощь',
        ua: 'Приймати виклики швидкої допомоги',
        en: 'Accept emergency calls',
        de: 'Notrufe annehmen',
        pl: 'Przyjmować połączenia alarmowe',
        zh: '接听紧急电话',
    },
    license: {
        ru: 'Выдавать лицензию',
        ua: 'Видавати ліцензію',
        en: 'Issue a license',
        de: 'Eine Lizenz ausstellen',
        pl: 'Wydawać licencję',
        zh: '许可证已颁发',
    },
    blood: {
        ru: 'Возможность брать кровь',
        ua: 'Можливість брати кров',
        en: 'Ability to take blood',
        de: 'Möglichkeit, Blut zu nehmen',
        pl: 'Możliwość pobierania krwi',
        zh: '采血的能力',
    },
    factionUpgrades: {
        ru: 'Управление улучшениями',
        ua: 'Управління покращеннями',
        en: 'Upgrade Management',
        de: 'Verbesserungsverwaltung',
        pl: 'Zarządzanie ulepszeniami',
        zh: '升级管理',
    },
    ranks: {
        ru: 'Управлять рангами, и рангами игроков',
        ua: 'Управляти рангами та рангами гравців',
        en: 'Manage ranks and player ranks',
        de: 'Ränge und Spieler-Ränge verwalten',
        pl: 'Zarządzać rangami i rangami graczy',
        zh: '管理排名和玩家排名',
    },
    controlInventory: {
        ru: 'Закрывать/Открывать склад',
        ua: 'Закривати/Відкривати склад',
        en: 'Close/Open inventory',
        de: 'Lager schließen/öffnen',
        pl: 'Zamykać/Otwierać magazyn',
        zh: '关闭/打开仓库',
    },
    money: {
        ru: 'Доступ к бюджету',
        ua: 'Доступ до бюджету',
        en: 'Access to Budget',
        de: 'Zugriff auf Budget',
        pl: 'Dostęp do budżetu',
        zh: '预算访问',
    },
    startSuply: {
        ru: 'Начинать поставки',
        ua: 'Починати поставки',
        en: 'Start Supplies',
        de: 'Lieferung starten',
        pl: 'Rozpocząć dostawy',
        zh: '开始供应',
    },
    startCaptureWar: {
        ru: 'Начинать войну за территорию',
        ua: 'Розпочинати війну за територію',
        en: 'Start a territory war',
        de: 'Territoriumskrieg beginnen',
        pl: 'Rozpocząć wojnę o terytorium',
        zh: '在领土上发动战争',
    },
    goToCaptureWar: {
        ru: 'Участвовать в войне за территорию',
        ua: 'Брати участь у війні за територію',
        en: 'Participate in the territory war',
        de: 'Am Territoriumskrieg teilnehmen',
        pl: 'Uczestniczyć w wojnie o terytorium',
        zh: '在“参与领土战争”中',
    },
    takeLicense: {
        ru: 'Забирать лицензии',
        ua: 'Забирати ліцензії',
        en: 'Take licenses',
        de: 'Lizenzen nehmen',
        pl: 'Zabierać licencje',
        zh: '获取许可证',
    },
    respawnVehicles: {
        ru: 'Респавнить авто',
        ua: 'Респавнити авто',
        en: 'Respawn vehicles',
        de: 'Fahrzeuge respawnen',
        pl: 'Respawnować pojazdy',
        zh: '修复车辆',
    },
    frisk: {
        ru: 'Обыск',
        ua: 'Обшук',
        en: 'Frisk',
        de: 'Durchsuchung',
        pl: 'Przeszukanie',
    },
    database: {
        ru: 'Доступ к базе данных',
        ua: 'Доступ до бази даних',
        en: 'Access to the database',
        de: 'Zugriff auf die Datenbank',
        pl: 'Dostęp do bazy danych',
    },
};
