export default {
    warehouse: {
        ru: 'Доступ к складу',
        ua: 'Доступ до складу',
        en: 'Warehouse Access',
        de: 'Zugang zum Lager',
        pl: 'Dostęp do magazynu',
    },
    inventory: {
        ru: 'Доступ к складу',
        ua: 'Доступ до складу',
        en: 'Access to inventory',
        de: 'Zugang zum Lager',
        pl: 'Dostęp do magazynu',
    },
    garage: {
        ru: 'Доступ к гаражу',
        ua: 'Доступ до гаражу',
        en: 'Garage Access',
        de: 'Zugang zur Garage',
        pl: 'Dostęp do garażu',
    },
    workshop: {
        ru: 'Доступ к крафтам',
        ua: 'Доступ до майстерні',
        en: 'Workshop Access',
        de: 'Zugang zur Werkstatt',
        pl: 'Dostęp do warsztatu',
    },
    wanted: {
        ru: 'Доступ к розыскам',
        ua: 'Доступ до розшуків',
        en: 'Wanted Access',
        de: 'Zugang zur Fahndung',
        pl: 'Dostęp do listy gończej',
    },
    members: {
        ru: 'Доступ к управлению членами',
        ua: 'Доступ до управління членами',
        en: 'Members Management Access',
        de: 'Zugang zur Mitgliederverwaltung',
        pl: 'Dostęp do zarządzania członkami',
    },
    acceptCalls: {
        ru: 'Принимать вызовы на скорую помощь',
        ua: 'Приймати виклики швидкої допомоги',
        en: 'Accept emergency calls',
        de: 'Notrufe annehmen',
        pl: 'Przyjmować połączenia alarmowe',
    },
    license: {
        ru: 'Выдавать лицензию',
        ua: 'Видавати ліцензію',
        en: 'Issue a license',
        de: 'Eine Lizenz ausstellen',
        pl: 'Wydawać licencję',
    },
    blood: {
        ru: 'Возможность брать кровь',
        ua: 'Можливість брати кров',
        en: 'Ability to take blood',
        de: 'Möglichkeit, Blut zu nehmen',
        pl: 'Możliwość pobierania krwi',
    },
    factionUpgrades: {
        ru: 'Управление улучшениями',
        ua: 'Управління покращеннями',
        en: 'Upgrade Management',
        de: 'Verbesserungsverwaltung',
        pl: 'Zarządzanie ulepszeniami',
    },
    ranks: {
        ru: 'Управлять рангами, и рангами игроков',
        ua: 'Управляти рангами та рангами гравців',
        en: 'Manage ranks and player ranks',
        de: 'Ränge und Spieler-Ränge verwalten',
        pl: 'Zarządzać rangami i rangami graczy',
    },
    controlInventory: {
        ru: 'Закрывать/Открывать склад',
        ua: 'Закривати/Відкривати склад',
        en: 'Close/Open inventory',
        de: 'Lager schließen/öffnen',
        pl: 'Zamykać/Otwierać magazyn',
    },
    money: {
        ru: 'Доступ к бюджету',
        ua: 'Доступ до бюджету',
        en: 'Access to Budget',
        de: 'Zugriff auf Budget',
        pl: 'Dostęp do budżetu',
    },
    startSuply: {
        ru: 'Начинать поставки',
        ua: 'Починати поставки',
        en: 'Start Supplies',
        de: 'Lieferung starten',
        pl: 'Rozpocząć dostawy',
    },
    startCaptureWar: {
        ru: 'Начинать войну за территорию',
        ua: 'Розпочинати війну за територію',
        en: 'Start a territory war',
        de: 'Territoriumskrieg beginnen',
        pl: 'Rozpocząć wojnę o terytorium',
    },
    goToCaptureWar: {
        ru: 'Участвовать в войне за территорию',
        ua: 'Брати участь у війні за територію',
        en: 'Participate in the territory war',
        de: 'Am Territoriumskrieg teilnehmen',
        pl: 'Uczestniczyć w wojnie o terytorium',
    },
    takeLicense: {
        ru: 'Забирать лицензии',
        ua: 'Забирати ліцензії',
        en: 'Take licenses',
        de: 'Lizenzen nehmen',
        pl: 'Zabierać licencje',
    },
    respawnVehicles: {
        ru: 'Респавнить авто',
        ua: 'Респавнити авто',
        en: 'Respawn vehicles',
        de: 'Fahrzeuge respawnen',
        pl: 'Respawnować pojazdy',
    },
};
