export default {
    notAvailable: {
        ru: 'Этот бизнес сейчас недоступен для ограбления.',
        ua: 'Цей бізнес зараз недоступний для пограбування.',
        en: 'This business is currently not available for robbery.',
        de: 'Dieses Geschäft ist derzeit nicht für einen Überfall verfügbar.',
        pl: 'Ten biznes jest obecnie niedostępny do napadu.',
    },
    shopRecentlyRobbed: {
        ru: 'Этот бизнес недавно был ограблен. Подождите немного.',
        ua: 'Цей бізнес нещодавно був пограбований. Зачекайте трохи.',
        en: 'This business was recently robbed. Wait a bit.',
        de: 'Dieses Geschäft wurde kürzlich überfallen. Bitte warten Sie ein wenig.',
        pl: 'Ten biznes został niedawno okradziony. Proszę chwilę poczekać.',
    },
    inGroupNeeded: {
        ru: 'Для ограбления вы должны быть в группе!',
        ua: 'Для пограбування ви повинні бути у групі!',
        en: 'You must be in a group to perform a robbery!',
        de: 'Für einen Überfall müssen Sie in einer Gruppe sein!',
        pl: 'Aby dokonać napadu, musisz być w grupie!',
    },
    minParty: {
        ru: 'В группе должно быть минимум {{minCount}} игрока!',
        ua: 'У групі має бути щонайменше {{minCount}} гравця!',
        en: 'There must be at least {{minCount}} players in the group!',
        de: 'In der Gruppe müssen mindestens {{minCount}} Spieler sein!',
        pl: 'W grupie musi być co najmniej {{minCount}} graczy!',
    },
    groupInvalid: {
        ru: 'Ваша группа не соответствует требованиям для начала ограбления.',
        ua: 'Ваша група не відповідає вимогам для початку пограбування.',
        en: 'Your group does not meet the requirements to start a robbery.',
        de: 'Ihre Gruppe erfüllt nicht die Anforderungen, um einen Überfall zu beginnen.',
        pl: 'Twoja grupa nie spełnia wymagań do rozpoczęcia napadu.',
    },
    alreadyInProgress: {
        ru: 'Этот бизнес уже ограбляют.',
        ua: 'Цей бізнес вже пограбовується.',
        en: 'This business is already being robbed.',
        de: 'Dieses Geschäft wird bereits überfallen.',
        pl: 'Ten biznes jest już rabowany.',
    },
    successShare: {
        ru: 'Ограбление успешно завершено! Ваша доля ${{share}}',
        ua: 'Пограбування успішно завершено! Ваша частка ${{share}}',
        en: 'The robbery has been successfully completed! Your share is ${{share}}',
        de: 'Der Überfall wurde erfolgreich abgeschlossen! Ihr Anteil beträgt ${{share}}',
        pl: 'Napad zakończony sukcesem! Twój udział to ${{share}}',
    },
    allDead: {
        ru: 'Все участники группы мертвы, ограбление провалено!',
        ua: 'Усі учасники групи мертві, пограбування провалено!',
        en: 'All group members are dead, the robbery has failed!',
        de: 'Alle Gruppenmitglieder sind tot, der Überfall ist gescheitert!',
        pl: 'Wszyscy członkowie grupy nie żyją, napad się nie powiódł!',
    },
    pedKilled: {
        ru: 'Продавец был убит, ограбление провалено!',
        ua: 'Продавця було вбито, пограбування провалено!',
        en: 'The seller was killed, the robbery has failed!',
        de: 'Der Verkäufer wurde getötet, der Überfall ist gescheitert!',
        pl: 'Sprzedawca został zabity, napad się nie powiódł!',
    },
    revolt: {
        ru: 'Продавец взбунтовался, ограбление провалено!',
        ua: 'Продавець збунтувався, пограбування провалено!',
        en: 'The seller rebelled, the robbery has failed!',
        de: 'Der Verkäufer hat sich aufgelehnt, der Überfall ist gescheitert!',
        pl: 'Sprzedawca zbuntował się, napad się nie powiódł!',
    },
    timer: {
        header: {
            ru: 'Ограбление бизнеса',
            ua: 'Пограбування бізнесу',
            en: 'Business Robbery',
            de: 'Geschäftsraub',
            pl: 'Napad na biznes',
        },
        text: {
            ru: 'Держите прицел на продавце и не отпускайте',
            ua: 'Тримайте приціл на продавцеві і не відпускайте',
            en: "Keep your aim on the seller and don't let go",
            de: 'Halten Sie den Verkäufer im Visier und lassen Sie nicht los',
            pl: 'Trzymaj celownik na sprzedawcy i nie puszczaj',
        },
    },
    lspdMessage: {
        ru: 'Внимание! Началось ограбление магазина, он обозначен на карте!',
        ua: 'Увага! Почалося пограбування магазину, він позначений на карті!',
        en: 'Attention! A store robbery has started, it is marked on the map!',
        de: 'Achtung! Ein Ladenüberfall hat begonnen, er ist auf der Karte markiert!',
        pl: 'Uwaga! Rozpoczęło się napad na sklep, jest zaznaczony na mapie!',
    },
    notAllowedFaction: {
        ru: 'Участники группы состоят в корректной фракции',
        ua: 'Учасники групи перебувають у правильній фракції',
        en: 'Group members belong to the correct faction',
        de: 'Gruppenmitglieder gehören der richtigen Fraktion an',
        pl: 'Członkowie grupy należą do właściwej frakcji',
    },
};
