export default {
    blip: {
        ru: 'Штрафстоянка',
        ua: 'Штрафмайданчик',
        en: 'Impound Lot',
        de: 'Abschleppplatz',
        pl: 'Parking policyjny',
    },
    youCantAttachThisVehicle: {
        ru: 'У этой машины нет ордера на эвакуацию!',
        ua: 'У цього автомобіля немає ордера на евакуацію!',
        en: 'This vehicle has no tow order!',
        de: 'Dieses Fahrzeug hat keinen Abschleppbefehl!',
        pl: 'Ten pojazd nie ma zlecenia na odholowanie!',
    },
    attachedNotify: {
        ru: 'Отвезите это транспортное средство на штрафстоянку',
        ua: 'Відвезіть цей транспортний засіб на штрафмайданчик',
        en: 'Take this vehicle to the impound lot',
        de: 'Bringe dieses Fahrzeug zum Abschleppplatz',
        pl: 'Zawieź ten pojazd na parking policyjny',
    },
    youDropOffVehicleSuccess: {
        ru: 'Вы сдали транспортное средство на штарфстоянку и получили ${{salary}}',
        ua: 'Ви здали транспортний засіб на штрафмайданчик і отримали ${{salary}}',
        en: 'You dropped off the vehicle at the impound lot and received ${{salary}}',
        de: 'Du hast das Fahrzeug beim Abschleppplatz abgeliefert und ${{salary}} erhalten',
        pl: 'Oddałeś pojazd na parking policyjny i otrzymałeś ${{salary}}',
    },
    targetVehicleDestroyed: {
        ru: 'Эвакуируемая машина была уничтожена',
        ua: 'Евакуйований автомобіль було знищено',
        en: 'The towed vehicle was destroyed',
        de: 'Das abzuschleppende Fahrzeug wurde zerstört',
        pl: 'Holowany pojazd został zniszczony',
    },
    noVehiclesToTake: {
        ru: 'У вас нет авто на штрафстоянке',
        ua: 'У тебе немає авто на штрафмайданчику',
        en: "You don't have any vehicles in the impound lot",
        de: 'Du hast keine Fahrzeuge auf dem Abschleppplatz',
        pl: 'Nie masz żadnych pojazdów na parkingu policyjnym',
    },
    youTakedVehicle: {
        ru: 'Вы забрали ваш транспорт с штрафстоянки',
        ua: 'Ти забрав свій транспорт зі штрафмайданчика',
        en: 'You retrieved your vehicle from the impound lot',
        de: 'Du hast dein Fahrzeug vom Abschleppplatz abgeholt',
        pl: 'Odebrałeś swój pojazd z parkingu policyjnego',
    },
    evacuationLabel: {
        ru: 'Т/С будет эвакуировано через',
        ua: 'Т/З буде евакуйовано через',
        en: 'The vehicle will be towed in',
        de: 'Das Fahrzeug wird abgeschleppt in',
        pl: 'Pojazd zostanie odholowany za',
    },
    seconds: {
        ru: 'секунд',
        ua: 'секунд',
        en: 'seconds',
        de: 'Sekunden',
        pl: 'sekund',
    },
    dialogs: {
        first: {
            helloMessage: {
                ru: 'Здравствуйте! Я работник этой штрафстоянки, чем могу помочь?',
                ua: 'Вітаю! Я працівник цього штрафмайданчика, чим можу допомогти?',
                en: 'Hi there! I work at this impound lot. How can I help you?',
                de: 'Hallo! Ich arbeite auf diesem Abschlepphof. Wie kann ich dir helfen?',
                pl: 'Cześć! Pracuję na tym parkingu policyjnym. Jak mogę ci pomóc?',
            },
            takeVehicles: {
                ru: 'Забрать авто',
                ua: 'Забрати авто',
                en: 'Pick up the car',
                de: 'Auto abholen',
                pl: 'Odebrać auto',
            },
            noVehiclesInImpound: {
                ru: 'Похоже, вашего транспорта нет на этой штрафстоянке, так что ничем не могу помочь',
                ua: 'Схоже, твого транспорту немає на цій штрафстоянці, тож я нічим не можу допомогти',
                en: "Looks like your vehicle isn't at this impound lot, so I can't help you",
                de: 'Sieht so aus, als wäre dein Fahrzeug nicht auf diesem Abschleppplatz, also kann ich dir nicht helfen',
                pl: 'Wygląda na to, że twojego pojazdu nie ma na tym parkingu policyjnym, więc nie mogę ci pomóc',
            },
            bye: {
                ru: 'Прощайте',
                ua: 'Прощавайте',
                en: 'Goodbye',
                de: 'Leb wohl',
                pl: 'Żegnaj',
            },
        },
    },
    modalSelect: {
        title: {
            ru: 'Вы можете забрать эти авто',
            ua: 'Ти можеш забрати ці авто',
            en: 'You can retrieve these cars',
            de: 'Du kannst diese Autos abholen',
            pl: 'Możesz odebrać te auta',
        },
    },
    modal: {
        title: {
            ru: 'Забрать транспорт со штрафстоянки',
            ua: 'Забрати транспорт зі штрафмайданчика',
            en: 'Retrieve vehicle from impound lot',
            de: 'Fahrzeug vom Abschleppplatz abholen',
            pl: 'Odbierz pojazd z parkingu policyjnego',
        },
        desc: {
            ru: 'Ваша машина была эвакуирована. <br/>Для возврата оплатите все сборы <br/> К оплате: <span style="color: #3c8025">${{price}}</span>',
            ua: 'Твоє авто було евакуйовано. <br/>Щоб його повернути, оплати всі збори <br/> До сплати: <span style="color: #3c8025">${{price}}</span>',
            en: 'Your car was towed. <br/>To get it back, pay all the fees <br/> Amount due: <span style="color: #3c8025">${{price}}</span>',
            de: 'Dein Auto wurde abgeschleppt. <br/>Um es zurückzubekommen, bezahle alle Gebühren <br/> Zu zahlen: <span style="color: #3c8025">${{price}}</span>',
            pl: 'Twoje auto zostało odholowane. <br/>Aby je odzyskać, zapłać wszystkie opłaty <br/> Do zapłaty: <span style="color: #3c8025">${{price}}</span>',
        },
        confirmButton: {
            ru: 'Забрать',
            ua: 'Забрати',
            en: 'Retrieve',
            de: 'Abholen',
            pl: 'Odbierz',
        },
        cancelButton: {
            ru: 'Отмена',
            ua: 'Скасувати',
            en: 'Cancel',
            de: 'Abbrechen',
            pl: 'Anuluj',
        },
    },
    orderModal: {
        title: {
            ru: 'Выписывание ордера на эвакуацию',
            ua: 'Виписування ордера на евакуацію',
            en: 'Issuing an evacuation order',
            de: 'Ausstellung eines Abschleppbefehls',
            pl: 'Wystawienie nakazu ewakuacji',
        },
        message: {
            ru: 'Вы действительно хотите выписать ордер на эвакуацию этого транспортного средства?',
            ua: 'Ти дійсно хочеш виписати ордер на евакуацію цього транспортного засобу?',
            en: 'Do you really want to issue an evacuation order for this vehicle?',
            de: 'Willst du wirklich einen Abschleppbefehl für dieses Fahrzeug ausstellen?',
            pl: 'Czy naprawdę chcesz wystawić nakaz ewakuacji tego pojazdu?',
        },
        placeholder: {
            ru: 'Укажите причину эвакуации',
            ua: 'Вкажи причину евакуації',
            en: 'Specify the reason for evacuation',
            de: 'Gib den Grund für die Abschleppung an',
            pl: 'Podaj powód ewakuacji',
        },
        confirmButton: {
            ru: 'Вызвать эвакуатор',
            ua: 'Викликати евакуатор',
            en: 'Call a tow truck',
            de: 'Abschleppwagen rufen',
            pl: 'Wezwij lawetę',
        },
        cancelButton: {
            ru: 'Отмена',
            ua: 'Скасувати',
            en: 'Cancel',
            de: 'Abbrechen',
            pl: 'Anuluj',
        },
    },
    successOrderNotify: {
        ru: 'Ты успешно выписал ордер на эвакуацию',
        ua: 'Ти успішно виписав ордер на евакуацію',
        en: 'You successfully issued an evacuation order',
        de: 'Du hast erfolgreich einen Evakuierungsbefehl ausgestellt',
        pl: 'Pomyślnie wystawiłeś rozkaz ewakuacji',
    },
    targetIsMoving: {
        ru: 'Машина должна стоять на месте для выписывания ордера',
        ua: 'Машина повинна стояти на місці, щоб виписати ордер',
        en: 'The vehicle must be stationary to issue the order',
        de: 'Das Fahrzeug muss stillstehen, um den Befehl auszustellen',
        pl: 'Pojazd musi stać w miejscu, aby wystawić rozkaz',
    },
    invalidInput: {
        ru: 'Указан некорректный комментарий',
        ua: 'Вказано некоректний коментар',
        en: 'Invalid comment provided',
        de: 'Ungültiger Kommentar angegeben',
        pl: 'Podano nieprawidłowy komentarz',
    },
    alreadyEvacuationOrder: {
        ru: 'На это авто уже выписан ордер на эвакуацию',
        ua: 'На це авто вже виписано ордер на евакуацію',
        en: 'This car already has an evacuation order issued',
        de: 'Für dieses Auto wurde bereits ein Abschleppbefehl ausgestellt',
        pl: 'Na ten samochód został już wystawiony nakaz odholowania',
    },
    noEvacuationOrder: {
        ru: 'На это Т/С нет ордера на эвакуацию',
        ua: 'На цей ТЗ немає ордера на евакуацію',
        en: 'There’s no evacuation order for this vehicle',
        de: 'Für dieses Fahrzeug liegt kein Evakuierungsbefehl vor',
        pl: 'Dla tego pojazdu nie ma rozkazu ewakuacji',
    },
    removedOrderNotify: {
        ru: 'Вы отозвали ордер на эвакуацию транспорта',
        ua: 'Ти відкликав ордер на евакуацію транспорту',
        en: 'You canceled the vehicle evacuation order',
        de: 'Du hast den Evakuierungsbefehl für das Fahrzeug widerrufen',
        pl: 'Cofnąłeś rozkaz ewakuacji pojazdu',
    },
    youCantWorkEvacuatorWork: {
        ru: 'У вас нет прав на работу эвакуаторщиком',
        ua: 'У тебе немає прав на роботу евакуаторником',
        en: "You don't have permission to work as a tow truck driver",
        de: 'Du hast keine Erlaubnis, als Abschleppfahrer zu arbeiten',
        pl: 'Nie masz uprawnień do pracy jako operator lawety',
    },
    cancelCompensation: {
        ru: 'Владелец машины вышел, поэтому машина, которую ты эвакуировал, была удалена. Ты получил зарплату в качестве компенсации: ${{salary}}',
        ua: 'Власник машини вийшов, тому машину, яку ти евакуював, було видалено. Ти отримав зарплату як компенсацію: ${{salary}}',
        en: 'The car owner left, so the car you towed was removed. You received a salary as compensation: ${{salary}}',
        de: 'Der Fahrzeugbesitzer ist gegangen, also wurde das Auto, das du abgeschleppt hast, entfernt. Du hast als Entschädigung dein Gehalt bekommen: ${{salary}}',
        pl: 'Właściciel samochodu wyszedł, więc samochód, który odholowałeś, został usunięty. Otrzymałeś wynagrodzenie jako rekompensatę: ${{salary}}',
    },
    cancelNoCompensation: {
        ru: 'Владелец машины вышел, поэтому машина, которую ты эвакуировал, была удалена.',
        ua: 'Власник машини вийшов, тому машину, яку ти евакуював, було видалено.',
        en: 'The car owner left, so the car you towed was removed.',
        de: 'Der Fahrzeugbesitzer ist gegangen, also wurde das Auto, das du abgeschleppt hast, entfernt.',
        pl: 'Właściciel samochodu wyszedł, więc samochód, który odholowałeś, został usunięty.',
    },
    notEnoughMoneyInFaction: {
        ru: 'В вашей организации недостаточно денег, чтобы выдать тебе зарплату',
        ua: 'У вашій організації недостатньо грошей, щоб видати тобі зарплату',
        en: "Your organization doesn't have enough money to pay your salary",
        de: 'Deine Organisation hat nicht genug Geld, um dir dein Gehalt zu zahlen',
        pl: 'Twoja organizacja nie ma wystarczająco pieniędzy, żeby wypłacić ci pensję',
    },
};
