export default {
    title: {
        ru: 'История каптов',
        ua: 'Історія каптів',
        en: 'Capture history',
        de: 'Einnahmeverlauf',
        pl: 'Historia przejęć',
    },
    open: {
        ru: 'История',
        ua: 'Історія',
        en: 'History',
        de: 'Verlauf',
        pl: 'Historia',
    },
    close: {
        ru: 'Закрыть',
        ua: 'Закрити',
        en: 'Close',
        de: 'Schliessen',
        pl: 'Zamknij',
    },
    back: {
        ru: 'Назад',
        ua: 'Назад',
        en: 'Back',
        de: 'Zurueck',
        pl: 'Wstecz',
    },
    loading: {
        ru: 'Загрузка',
        ua: 'Завантаження',
        en: 'Loading',
        de: 'Laedt',
        pl: 'Wczytywanie',
    },
    empty: {
        ru: 'Каптов ещё не было',
        ua: 'Каптів ще не було',
        en: 'No captures yet',
        de: 'Noch keine Einnahmen',
        pl: 'Nie było jeszcze przejęć',
    },
    zone: {
        ru: 'Зона {{index}}',
        ua: 'Зона {{index}}',
        en: 'Zone {{index}}',
        de: 'Zone {{index}}',
        pl: 'Strefa {{index}}',
    },
    vs: {
        ru: 'против',
        ua: 'проти',
        en: 'vs',
        de: 'gegen',
        pl: 'kontra',
    },
    player: {
        ru: 'Игрок',
        ua: 'Гравець',
        en: 'Player',
        de: 'Spieler',
        pl: 'Gracz',
    },
    meta: {
        date: {
            ru: 'Дата',
            ua: 'Дата',
            en: 'Date',
            de: 'Datum',
            pl: 'Data',
        },
        kind: {
            ru: 'Тип',
            ua: 'Тип',
            en: 'Type',
            de: 'Typ',
            pl: 'Typ',
        },
        duration: {
            ru: 'Длительность',
            ua: 'Тривалість',
            en: 'Duration',
            de: 'Dauer',
            pl: 'Czas trwania',
        },
    },
    attackers: {
        ru: 'Атакующие',
        ua: 'Атакуючі',
        en: 'Attackers',
        de: 'Angreifer',
        pl: 'Atakujacy',
    },
    defenders: {
        ru: 'Защитники',
        ua: 'Захисники',
        en: 'Defenders',
        de: 'Verteidiger',
        pl: 'Obroncy',
    },
    unknownFaction: {
        ru: 'Неизвестная фракция',
        ua: 'Невідома фракція',
        en: 'Unknown faction',
        de: 'Unbekannte Fraktion',
        pl: 'Nieznana frakcja',
    },
    noShow: {
        ru: 'Без боя',
        ua: 'Без бою',
        en: 'No-show',
        de: 'Nicht angetreten',
        pl: 'Bez walki',
    },
    noShowNote: {
        ru: 'Капт закончился неявкой - боя не было',
        ua: 'Капт закінчився неявкою - бою не було',
        en: 'The capture ended in a no-show, so no fight took place',
        de: 'Die Einnahme endete ohne Antreten, es gab keinen Kampf',
        pl: 'Przejęcie zakończyło się brakiem stawienia się, walki nie było',
    },
    participantsEmpty: {
        ru: 'Состав не записан',
        ua: 'Склад не записано',
        en: 'No roster recorded',
        de: 'Keine Aufstellung erfasst',
        pl: 'Brak zapisanego skladu',
    },
    justNow: {
        ru: 'только что',
        ua: 'щойно',
        en: 'just now',
        de: 'gerade eben',
        pl: 'przed chwila',
    },
    minutesAgo: {
        ru: '{{count}} мин назад',
        ua: '{{count}} хв тому',
        en: '{{count}} min ago',
        de: 'vor {{count}} Min',
        pl: '{{count}} min temu',
    },
    hoursAgo: {
        ru: '{{count}} ч назад',
        ua: '{{count}} год тому',
        en: '{{count}} h ago',
        de: 'vor {{count}} Std',
        pl: '{{count}} godz temu',
    },
    daysAgo: {
        ru: '{{count}} д назад',
        ua: '{{count}} д тому',
        en: '{{count}} d ago',
        de: 'vor {{count}} T',
        pl: '{{count}} dni temu',
    },
    filter: {
        all: {
            ru: 'Все',
            ua: 'Всі',
            en: 'All',
            de: 'Alle',
            pl: 'Wszystkie',
        },
        attack: {
            ru: 'Атаки',
            ua: 'Атаки',
            en: 'Attacks',
            de: 'Angriffe',
            pl: 'Ataki',
        },
        defense: {
            ru: 'Защиты',
            ua: 'Захисти',
            en: 'Defenses',
            de: 'Verteidigungen',
            pl: 'Obrony',
        },
    },
    kind: {
        attack: {
            ru: 'атака',
            ua: 'атака',
            en: 'attack',
            de: 'Angriff',
            pl: 'atak',
        },
        defense: {
            ru: 'защита',
            ua: 'захист',
            en: 'defense',
            de: 'Verteidigung',
            pl: 'obrona',
        },
    },
    result: {
        victory: {
            ru: 'Победа',
            ua: 'Перемога',
            en: 'Victory',
            de: 'Sieg',
            pl: 'Zwyciestwo',
        },
        defeat: {
            ru: 'Поражение',
            ua: 'Поразка',
            en: 'Defeat',
            de: 'Niederlage',
            pl: 'Porazka',
        },
        draw: {
            ru: 'Ничья',
            ua: 'Нічия',
            en: 'Draw',
            de: 'Unentschieden',
            pl: 'Remis',
        },
    },
    summary: {
        victories: {
            ru: 'побед',
            ua: 'перемог',
            en: 'wins',
            de: 'Siege',
            pl: 'wygranych',
        },
        defeats: {
            ru: 'поражений',
            ua: 'поразок',
            en: 'losses',
            de: 'Niederlagen',
            pl: 'przegranych',
        },
    },
};
