export default {
    adMessage: {
        ru: '!{#DA8815}[РЕКЛАМА] {{message}} | {{fromName}} Телефон: {{phoneNumber}}',
        ua: '!{#DA8815}[РЕКЛАМА] {{message}} | {{fromName}} Телефон: {{phoneNumber}}',
        en: '!{#DA8815}[AD] {{message}} | {{fromName}} Phone: {{phoneNumber}}',
        de: '!{#DA8815}[WERBUNG] {{message}} | {{fromName}} Telefon: {{phoneNumber}}',
        pl: '!{#DA8815}[REKLAMA] {{message}} | {{fromName}} Telefon: {{phoneNumber}}',
    },
    adMessage2: {
        ru: '!{#A06A18}Отредактировал сотрудник Weazel News {{name}}.',
        ua: '!{#A06A18}Відредагував співробітник Weazel News {{name}}.',
        en: '!{#A06A18}Edited by Weazel News staff member {{name}}.',
        de: '!{#A06A18}Bearbeitet von Weazel News Mitarbeiter {{name}}.',
        pl: '!{#A06A18}Edytowane przez pracownika Weazel News {{name}}.',
    },
    editingAlreadySomeone: {
        ru: 'Это объявление уже кто то редактирует',
        ua: 'Це оголошення вже хтось редагує',
        en: 'This listing is already being edited by someone',
        de: 'Diese Anzeige wird bereits von jemandem bearbeitet',
        pl: 'To ogłoszenie jest już edytowane przez kogoś',
    },
    publishedBySomeone: {
        ru: 'Это объявление уже кто то опубликовал',
        ua: 'Це оголошення вже хтось опублікував',
        en: 'This listing has already been published by someone',
        de: 'Diese Anzeige wurde bereits von jemandem veröffentlicht',
        pl: 'To ogłoszenie zostało już przez kogoś opublikowane',
    },
    declinedSomeone: {
        ru: 'Это объявление уже отклонено',
        ua: 'Це оголошення вже відхилено',
        en: 'This listing has already been declined',
        de: 'Diese Anzeige wurde bereits abgelehnt',
        pl: 'To ogłoszenie zostało już odrzucone',
    },
    youPublishedSuccess: {
        ru: 'Вы успешно опубликовали объявление и заработали ${{money}}',
        ua: 'Ви успішно опублікували оголошення та заробили ${{money}}',
        en: 'You have successfully published the ad and earned ${{money}}',
        de: 'Sie haben die Anzeige erfolgreich veröffentlicht und ${{money}} verdient',
        pl: 'Pomyślnie opublikowałeś ogłoszenie i zarobiłeś ${{money}}',
    },
    youDeclinedSuccess: {
        ru: 'Вы отклонили объявление гражданина {{name}}',
        ua: 'Ви відхилили оголошення громадянина {{name}}',
        en: 'You have declined the listing of citizen {{name}}',
        de: 'Sie haben die Anzeige von Bürger {{name}} abgelehnt',
        pl: 'Odrzuciłeś ogłoszenie obywatela {{name}}',
    },

    invalidMessage: {
        ru: 'Текст некорректный',
        ua: 'Текст некоректний',
        en: 'The text is incorrect',
        de: 'Der Text ist fehlerhaft',
        pl: 'Tekst jest nieprawidłowy',
    },
    notEnoughMoney: {
        ru: 'На вашем банковском счету недостаточно денег',
        ua: 'На вашому банківському рахунку недостатньо коштів',
        en: 'There is not enough money in your bank account',
        de: 'Ihr Bankkonto enthält nicht genügend Geld',
        pl: 'Na Twoim koncie bankowym brakuje środków',
    },
    cef: {
        titleBase: {
            ru: 'ОБЪЯВЛЕНИЯ',
            ua: 'ОГОЛОШЕННЯ',
            en: 'ANNOUNCEMENTS',
            de: 'ANKÜNDIGUNGEN',
            pl: 'OGŁOSZENIA',
        },
        titleEdit: {
            ru: 'РЕДАКТИРОВАНИЕ',
            ua: 'РЕДАГУВАННЯ',
            en: 'EDITING',
            de: 'BEARBEITUNG',
            pl: 'EDYCJA',
        },
        editTextByRules: {
            ru: 'Отредактируйте текст по всем правилам',
            ua: 'Відредагуйте текст за всіма правилами',
            en: 'Edit the text according to all the rules',
            de: 'Bearbeiten Sie den Text nach allen Regeln',
            pl: 'Edytuj tekst zgodnie ze wszystkimi zasadami',
        },
        acceptButton: {
            ru: 'Отправить',
            ua: 'Надіслати',
            en: 'Submit',
            de: 'Senden',
            pl: 'Wyślij',
        },
        declineButton: {
            ru: 'Отклонить',
            ua: 'Відхилити',
            en: 'Decline',
            de: 'Ablehnen',
            pl: 'Odrzuć',
        },
        startEdit: {
            ru: 'Начать проверку',
            ua: 'Почати перевірку',
            en: 'Start review',
            de: 'Überprüfung starten',
            pl: 'Rozpocznij sprawdzanie',
        },
        from: {
            ru: 'От',
            ua: 'Від',
            en: 'From',
            de: 'Von',
            pl: 'Od',
        },
        statuses: {
            editing: {
                ru: 'Редактируется {{name}}',
                ua: 'Редагується {{name}}',
                en: 'Editing {{name}}',
                de: '{{name}} wird bearbeitet',
                pl: 'Edytowanie {{name}}',
            },
            declined: {
                ru: 'Отклонено {{name}}',
                ua: 'Відхилено {{name}}',
                en: 'Declined {{name}}',
                de: 'Abgelehnt {{name}}',
                pl: 'Odrzucono {{name}}',
            },
            published: {
                ru: 'Опубликовано {{name}}',
                ua: 'Опубліковано {{name}}',
                en: 'Published {{name}}',
                de: 'Veröffentlicht {{name}}',
                pl: 'Opublikowano {{name}}',
            },
        },
    },

    liveStream: {
        live: {
            ru: '<font color="b51d1d">LIVE</font>',
            ua: '<font color="b51d1d">НАЖИВО</font>',
            en: '<font color="b51d1d">LIVE</font>',
            de: '<font color="b51d1d">LIVE</font>',
            pl: '<font color="b51d1d">NA ŻYWO</font>',
        },
        notLive: {
            ru: 'Прямой эфир отключен',
            ua: 'Прямий ефір вимкнено',
            en: 'Live stream is off',
            de: 'Live-Übertragung ist deaktiviert',
            pl: 'Transmisja na żywo wyłączona',
        },
        peopleInStream: {
            ru: 'Людей в эфире:',
            ua: 'Людей в ефірі:',
            en: 'People in stream:',
            de: 'Personen im Stream:',
            pl: 'Ludzi na transmisji:',
        },

        modal: {
            title: {
                ru: 'Управление прямым эфиром',
                ua: 'Керування прямим ефіром',
                en: 'Live Stream Control',
                de: 'Live-Stream-Steuerung',
                pl: 'Zarządzanie transmisją na żywo',
            },
            startButton: {
                ru: 'Начать прямой эфир',
                ua: 'Почати прямий ефір',
                en: 'Start Live Stream',
                de: 'Live-Stream starten',
                pl: 'Rozpocznij transmisję na żywo',
            },
            stopButton: {
                ru: 'Остановить прямой эфир',
                ua: 'Зупинити прямий ефір',
                en: 'Stop Live Stream',
                de: 'Live-Stream beenden',
                pl: 'Zatrzymaj transmisję na żywo',
            },
        },
    },
};
