export default {
    adMessage: {
        ru: '!{#DA8815}[РЕКЛАМА] {{message}} | {{fromName}} Телефон: {{phoneNumber}}',
        ua: '!{#DA8815}[РЕКЛАМА] {{message}} | {{fromName}} Телефон: {{phoneNumber}}',
        en: '!{#DA8815}[AD] {{message}} | {{fromName}} Phone: {{phoneNumber}}',
        de: '!{#DA8815}[WERBUNG] {{message}} | {{fromName}} Telefon: {{phoneNumber}}',
        pl: '!{#DA8815}[REKLAMA] {{message}} | {{fromName}} Telefon: {{phoneNumber}}',
    },
    adMessage2: {
        ru: '!{#A06A18}Отредактировал сотрудник Weazel News {{name}}.',
        ua: '!{#A06A18}Відредагував співробітник Weazel News {{name}}.',
        en: '!{#A06A18}Edited by Weazel News staff member {{name}}.',
        de: '!{#A06A18}Bearbeitet von Weazel News Mitarbeiter {{name}}.',
        pl: '!{#A06A18}Edytowane przez pracownika Weazel News {{name}}.',
    },
    editingAlreadySomeone: {
        ru: 'Это объявление уже кто то редактирует',
        ua: 'Це оголошення вже хтось редагує',
        en: 'This listing is already being edited by someone',
        de: 'Diese Anzeige wird bereits von jemandem bearbeitet',
        pl: 'To ogłoszenie jest już edytowane przez kogoś',
    },
    publishedBySomeone: {
        ru: 'Это объявление уже кто то опубликовал',
        ua: 'Це оголошення вже хтось опублікував',
        en: 'This listing has already been published by someone',
        de: 'Diese Anzeige wurde bereits von jemandem veröffentlicht',
        pl: 'To ogłoszenie zostało już przez kogoś opublikowane',
    },
    declinedSomeone: {
        ru: 'Это объявление уже отклонено',
        ua: 'Це оголошення вже відхилено',
        en: 'This listing has already been declined',
        de: 'Diese Anzeige wurde bereits abgelehnt',
        pl: 'To ogłoszenie zostało już odrzucone',
    },
    youPublishedSuccess: {
        ru: 'Вы успешно опубликовали объявление и заработали ${{money}}',
        ua: 'Ви успішно опублікували оголошення та заробили ${{money}}',
        en: 'You have successfully published the ad and earned ${{money}}',
        de: 'Du hast die Anzeige erfolgreich veröffentlicht und ${{money}} verdient',
        pl: 'Pomyślnie opublikowałeś ogłoszenie i zarobiłeś ${{money}}',
    },
    youDeclinedSuccess: {
        ru: 'Вы отклонили объявление гражданина {{name}}',
        ua: 'Ви відхилили оголошення громадянина {{name}}',
        en: 'You have declined the listing of citizen {{name}}',
        de: 'Du hast die Anzeige von Bürger {{name}} abgelehnt',
        pl: 'Odrzuciłeś ogłoszenie obywatela {{name}}',
    },

    phoneMessage: {
        ru: 'Ожидайте одобрение заявки',
        ua: 'Очікуйте на схвалення заявки',
        en: 'Awaiting application approval',
        de: 'Warten auf Antragsgenehmigung',
        pl: 'Oczekiwanie na zatwierdzenie wniosku',
    },
    invalidMessage: {
        ru: 'Текст некорректный',
        ua: 'Текст некоректний',
        en: 'The text is incorrect',
        de: 'Der Text ist fehlerhaft',
        pl: 'Tekst jest nieprawidłowy',
    },
    notEnoughMoney: {
        ru: 'На вашем банковском счету недостаточно денег',
        ua: 'На вашому банківському рахунку недостатньо коштів',
        en: 'There is not enough money in your bank account',
        de: 'Dein Bankkonto enthält nicht genügend Geld',
        pl: 'Na Twoim koncie bankowym brakuje środków',
    },
    cooldown: {
        ru: 'Вы недавно уже отправляли объявление, подождите немного',
        ua: 'Ви нещодавно вже надсилали оголошення, зачекайте трохи',
        en: 'You have recently sent an announcement, please wait a bit',
        de: 'Du hast kürzlich bereits eine Anzeige gesendet, bitte warte etwas',
        pl: 'Niedawno już wysłałeś ogłoszenie, poczekaj chwilę',
    },
    cef: {
        titleBase: {
            ru: 'ОБЪЯВЛЕНИЯ',
            ua: 'ОГОЛОШЕННЯ',
            en: 'ANNOUNCEMENTS',
            de: 'ANKÜNDIGUNGEN',
            pl: 'OGŁOSZENIA',
        },
        titleEdit: {
            ru: 'РЕДАКТИРОВАНИЕ',
            ua: 'РЕДАГУВАННЯ',
            en: 'EDITING',
            de: 'BEARBEITUNG',
            pl: 'EDYCJA',
        },
        editTextByRules: {
            ru: 'Отредактируйте текст по всем правилам',
            ua: 'Відредагуйте текст за всіма правилами',
            en: 'Edit the text according to all the rules',
            de: 'Bearbeite den Text nach allen Regeln',
            pl: 'Edytuj tekst zgodnie ze wszystkimi zasadami',
        },
        acceptButton: {
            ru: 'Отправить',
            ua: 'Надіслати',
            en: 'Submit',
            de: 'Senden',
            pl: 'Wyślij',
        },
        declineButton: {
            ru: 'Отклонить',
            ua: 'Відхилити',
            en: 'Decline',
            de: 'Ablehnen',
            pl: 'Odrzuć',
        },
        startEdit: {
            ru: 'Начать проверку',
            ua: 'Почати перевірку',
            en: 'Start review',
            de: 'Überprüfung starten',
            pl: 'Rozpocznij sprawdzanie',
        },
        from: {
            ru: 'От',
            ua: 'Від',
            en: 'From',
            de: 'Von',
            pl: 'Od',
        },
        statuses: {
            editing: {
                ru: 'Редактируется {{name}}',
                ua: 'Редагується {{name}}',
                en: 'Editing {{name}}',
                de: '{{name}} wird bearbeitet',
                pl: 'Edytowanie {{name}}',
            },
            declined: {
                ru: 'Отклонено {{name}}',
                ua: 'Відхилено {{name}}',
                en: 'Declined {{name}}',
                de: 'Abgelehnt {{name}}',
                pl: 'Odrzucono {{name}}',
            },
            published: {
                ru: 'Опубликовано {{name}}',
                ua: 'Опубліковано {{name}}',
                en: 'Published {{name}}',
                de: 'Veröffentlicht {{name}}',
                pl: 'Opublikowano {{name}}',
            },
        },
    },

    liveStream: {
        live: {
            ru: '<font color="b51d1d">LIVE</font>',
            ua: '<font color="b51d1d">НАЖИВО</font>',
            en: '<font color="b51d1d">LIVE</font>',
            de: '<font color="b51d1d">LIVE</font>',
            pl: '<font color="b51d1d">NA ŻYWO</font>',
        },
        notLive: {
            ru: 'Прямой эфир отключен',
            ua: 'Прямий ефір вимкнено',
            en: 'Live stream is off',
            de: 'Live-Übertragung ist deaktiviert',
            pl: 'Transmisja na żywo wyłączona',
        },
        peopleInStream: {
            ru: 'Людей в эфире:',
            ua: 'Людей в ефірі:',
            en: 'People in stream:',
            de: 'Personen im Stream:',
            pl: 'Ludzi na transmisji:',
        },

        modal: {
            title: {
                ru: 'Управление прямым эфиром',
                ua: 'Керування прямим ефіром',
                en: 'Live Stream Control',
                de: 'Live-Stream-Steuerung',
                pl: 'Zarządzanie transmisją na żywo',
            },
            startButton: {
                ru: 'Начать прямой эфир',
                ua: 'Почати прямий ефір',
                en: 'Start Live Stream',
                de: 'Live-Stream starten',
                pl: 'Rozpocznij transmisję na żywo',
            },
            stopButton: {
                ru: 'Остановить прямой эфир',
                ua: 'Зупинити прямий ефір',
                en: 'Stop Live Stream',
                de: 'Live-Stream beenden',
                pl: 'Zatrzymaj transmisję na żywo',
            },
        },
    },

    npc: {
        dialog_01: {
            welcome: {
                ru: 'Добро пожаловать в офис Weazel News. Здесь работает редакция, ведущие и наши корреспонденты. Чем могу помочь?',
                ua: 'Ласкаво просимо до офісу Weazel News. Тут працює редакція, ведучі та наші кореспонденти. Чим можу допомогти?',
                en: 'Welcome to the Weazel News office. This is where our editors, anchors and correspondents work. How can I help you?',
                de: 'Willkommen im Büro von Weazel News. Hier arbeiten unsere Redaktion, Moderatoren und Korrespondenten. Wie kann ich dir helfen?',
                pl: 'Witamy w biurze Weazel News. Tu pracują nasi redaktorzy, prezenterzy i korespondenci. W czym mogę pomóc?',
            },
            howToJoin: {
                ru: 'Как вступить во фракцию?',
                ua: 'Як вступити до фракції?',
                en: 'How do I join the faction?',
                de: 'Wie trete ich der Fraktion bei?',
                pl: 'Jak dołączyć do frakcji?',
            },
            howToBuyAd: {
                ru: 'Где купить рекламу?',
                ua: 'Де купити рекламу?',
                en: 'Where can I buy advertising?',
                de: 'Wo kann ich Werbung kaufen?',
                pl: 'Gdzie kupić reklamę?',
            },
            howToJoinAnswer: {
                ru: 'Набор в штат проводит руководство фракции. Следите за анонсами в чате и сообществах, затем приходите к нам на собеседование.',
                ua: 'Набір до штату проводить керівництво фракції. Слідкуйте за анонсами в чаті та спільнотах, а потім приходьте до нас на співбесіду.',
                en: 'Staff recruitment is handled by the faction leadership. Follow the announcements in chat and community channels, then come to us for an interview.',
                de: 'Die Einstellung übernimmt die Fraktionsleitung. Verfolge die Ankündigungen im Chat und in den Community-Kanälen und komm dann zu uns zum Vorstellungsgespräch.',
                pl: 'Rekrutacją zajmuje się kierownictwo frakcji. Śledź ogłoszenia na czacie i w społecznościach, a następnie przyjdź do nas na rozmowę.',
            },
            howToBuyAdAnswer: {
                ru: 'Подать объявление можно прямо с телефона: откройте приложение Weazel News, перейдите во вкладку "Опубликовать", составьте текст и оплатите публикацию. После проверки наш сотрудник опубликует объявление.',
                ua: 'Подати оголошення можна прямо з телефону: відкрийте застосунок Weazel News, перейдіть у вкладку "Опублікувати", складіть текст і оплатіть публікацію. Після перевірки наш співробітник опублікує оголошення.',
                en: 'You can submit an ad right from your phone: open the Weazel News app, go to the "Publish" tab, write your text and pay for the publication. After review, one of our staff will post it.',
                de: 'Du kannst eine Anzeige direkt über dein Handy aufgeben: Öffne die Weazel-News-App, gehe zum Reiter "Veröffentlichen", verfasse den Text und bezahle die Veröffentlichung. Nach der Prüfung stellt einer unserer Mitarbeiter sie online.',
                pl: 'Ogłoszenie możesz wysłać prosto z telefonu: otwórz aplikację Weazel News, przejdź do zakładki "Opublikuj", napisz treść i opłać publikację. Po weryfikacji nasz pracownik opublikuje ogłoszenie.',
            },
            okay: {
                ru: 'Понятно',
                ua: 'Зрозуміло',
                en: 'Got it',
                de: 'Verstanden',
                pl: 'Rozumiem',
            },
            bye: {
                ru: 'До свидания',
                ua: 'До побачення',
                en: 'Goodbye',
                de: 'Auf Wiedersehen',
                pl: 'Do widzenia',
            },
        },
    },

    discordAdMessage: {
        title: {
            ru: '📢 Weazel News - Новое объявление',
            ua: '📢 Weazel News - Нове оголошення',
            en: '📢 Weazel News - New Advertisement',
            de: '📢 Weazel News - Neue Anzeige',
            pl: '📢 Weazel News - Nowe ogłoszenie',
        },
        contact: {
            ru: '📱 Контакт',
            ua: '📱 Контакт',
            en: '📱 Contact',
            de: '📱 Kontakt',
            pl: '📱 Kontakt',
        },
        published: {
            ru: '🕐 Опубликовано',
            ua: '🕐 Опубліковано',
            en: '🕐 Published',
            de: '🕐 Veröffentlicht',
            pl: '🕐 Opublikowano',
        },
        discord: {
            ru: '👤 Discord',
            ua: '👤 Discord',
            en: '👤 Discord',
            de: '👤 Discord',
            pl: '👤 Discord',
        },
        editedBy: {
            ru: '👀 Отредактировал',
            ua: '👀 Відредагував',
            en: '👀 Edited By',
            de: '👀 Bearbeitet von',
            pl: '👀 Edytował',
        },
        notSpecified: {
            ru: 'Не указано',
            ua: 'Не вказано',
            en: 'Not specified',
            de: 'Nicht angegeben',
            pl: 'Nie podano',
        },
        unknown: {
            ru: 'Неизвестно',
            ua: 'Невідомо',
            en: 'Unknown',
            de: 'Unbekannt',
            pl: 'Nieznany',
        },
    },
};
