export default {
    adMessage: {
        ru: '~g~Объявление: {{message}}. Прислал: {{fromName}}. Тел: {{phoneNumber}}',
        ua: '~g~Оголошення: {{message}}. Надіслав: {{fromName}}. Тел: {{phoneNumber}}',
        en: '~g~Announcement: {{message}}. Sent by: {{fromName}}. Phone: {{phoneNumber}}',
        de: '~g~Anzeige: {{message}}. Eingesandt von: {{fromName}}. Tel: {{phoneNumber}}',
        pl: '~g~Ogłoszenie: {{message}}. Nadesłał: {{fromName}}. Tel: {{phoneNumber}}',
    },
    // The editorial byline sits under the ad itself and carries the ad color. The leading
    // bullet marks it as a continuation of the line above.
    adMessage2: {
        ru: '~g~• Редакция Weazel News. Отредактировал: {{name}}',
        ua: '~g~• Редакція Weazel News. Відредагував: {{name}}',
        en: '~g~• Weazel News editorial. Edited by: {{name}}',
        de: '~g~• Redaktion Weazel News. Bearbeitet von: {{name}}',
        pl: '~g~• Redakcja Weazel News. Edytował: {{name}}',
    },
    adDeclined: {
        ru: '~y~[Weazel News] ~w~Ваше объявление отклонено сотрудником {{name}}.',
        ua: '~y~[Weazel News] ~w~Ваше оголошення відхилено співробітником {{name}}.',
        en: '~y~[Weazel News] ~w~Your ad was declined by staff member {{name}}.',
        de: '~y~[Weazel News] ~w~Deine Anzeige wurde von Mitarbeiter {{name}} abgelehnt.',
        pl: '~y~[Weazel News] ~w~Twoje ogłoszenie zostało odrzucone przez pracownika {{name}}.',
    },
    adDeclinedReason: {
        ru: '~m~Причина: ~r~{{reason}}',
        ua: '~m~Причина: ~r~{{reason}}',
        en: '~m~Reason: ~r~{{reason}}',
        de: '~m~Grund: ~r~{{reason}}',
        pl: '~m~Powód: ~r~{{reason}}',
    },
    adDeclinedText: {
        ru: '~m~Текст объявления: ~w~{{message}}',
        ua: '~m~Текст оголошення: ~w~{{message}}',
        en: '~m~Ad text: ~w~{{message}}',
        de: '~m~Anzeigentext: ~w~{{message}}',
        pl: '~m~Treść ogłoszenia: ~w~{{message}}',
    },
    newAdOnModeration: {
        ru: '~y~[Weazel News] ~w~Новое объявление от {{name}} ожидает модерации.',
        ua: '~y~[Weazel News] ~w~Нове оголошення від {{name}} очікує модерації.',
        en: '~y~[Weazel News] ~w~A new ad from {{name}} is awaiting moderation.',
        de: '~y~[Weazel News] ~w~Eine neue Anzeige von {{name}} wartet auf Moderation.',
        pl: '~y~[Weazel News] ~w~Nowe ogłoszenie od {{name}} oczekuje na moderację.',
    },
    invalidDeclineReason: {
        ru: 'Укажите причину отклонения от 3 до 100 символов',
        ua: 'Вкажіть причину відхилення від 3 до 100 символів',
        en: 'Enter a decline reason between 3 and 100 characters',
        de: 'Gib einen Ablehnungsgrund mit 3 bis 100 Zeichen an',
        pl: 'Podaj powód odrzucenia o długości od 3 do 100 znaków',
    },
    editingAlreadySomeone: {
        ru: 'Это объявление уже кто то редактирует',
        ua: 'Це оголошення вже хтось редагує',
        en: 'This listing is already being edited by someone',
        de: 'Diese Anzeige wird bereits von jemandem bearbeitet',
        pl: 'To ogłoszenie jest już edytowane przez kogoś',
    },
    publishedBySomeone: {
        ru: 'Это объявление уже кто то опубликовал',
        ua: 'Це оголошення вже хтось опублікував',
        en: 'This listing has already been published by someone',
        de: 'Diese Anzeige wurde bereits von jemandem veröffentlicht',
        pl: 'To ogłoszenie zostało już przez kogoś opublikowane',
    },
    declinedSomeone: {
        ru: 'Это объявление уже отклонено',
        ua: 'Це оголошення вже відхилено',
        en: 'This listing has already been declined',
        de: 'Diese Anzeige wurde bereits abgelehnt',
        pl: 'To ogłoszenie zostało już odrzucone',
    },
    youPublishedSuccess: {
        ru: 'Вы успешно опубликовали объявление и заработали ${{money}}',
        ua: 'Ви успішно опублікували оголошення та заробили ${{money}}',
        en: 'You have successfully published the ad and earned ${{money}}',
        de: 'Du hast die Anzeige erfolgreich veröffentlicht und ${{money}} verdient',
        pl: 'Pomyślnie opublikowałeś ogłoszenie i zarobiłeś ${{money}}',
    },
    youDeclinedSuccess: {
        ru: 'Вы отклонили объявление гражданина {{name}}',
        ua: 'Ви відхилили оголошення громадянина {{name}}',
        en: 'You have declined the listing of citizen {{name}}',
        de: 'Du hast die Anzeige von Bürger {{name}} abgelehnt',
        pl: 'Odrzuciłeś ogłoszenie obywatela {{name}}',
    },

    phoneMessage: {
        ru: 'Ожидайте одобрение заявки',
        ua: 'Очікуйте на схвалення заявки',
        en: 'Awaiting application approval',
        de: 'Warten auf Antragsgenehmigung',
        pl: 'Oczekiwanie na zatwierdzenie wniosku',
    },
    notOnDuty: {
        ru: 'Сначала заступите на смену',
        ua: 'Спочатку заступіть на зміну',
        en: 'Start your shift first',
        de: 'Beginne zuerst deine Schicht',
        pl: 'Najpierw rozpocznij zmianę',
    },
    invalidMessage: {
        ru: 'Текст некорректный',
        ua: 'Текст некоректний',
        en: 'The text is incorrect',
        de: 'Der Text ist fehlerhaft',
        pl: 'Tekst jest nieprawidłowy',
    },
    notEnoughMoney: {
        ru: 'На вашем банковском счету недостаточно денег',
        ua: 'На вашому банківському рахунку недостатньо коштів',
        en: 'There is not enough money in your bank account',
        de: 'Dein Bankkonto enthält nicht genügend Geld',
        pl: 'Na Twoim koncie bankowym brakuje środków',
    },
    cooldown: {
        ru: 'Вы недавно уже отправляли объявление, подождите немного',
        ua: 'Ви нещодавно вже надсилали оголошення, зачекайте трохи',
        en: 'You have recently sent an announcement, please wait a bit',
        de: 'Du hast kürzlich bereits eine Anzeige gesendet, bitte warte etwas',
        pl: 'Niedawno już wysłałeś ogłoszenie, poczekaj chwilę',
    },

    liveStream: {
        live: {
            ru: '~r~LIVE',
            ua: '~r~НАЖИВО',
            en: '~r~LIVE',
            de: '~r~LIVE',
            pl: '~r~NA ŻYWO',
        },
        notLive: {
            ru: 'Прямой эфир отключен',
            ua: 'Прямий ефір вимкнено',
            en: 'Live stream is off',
            de: 'Live-Übertragung ist deaktiviert',
            pl: 'Transmisja na żywo wyłączona',
        },
        peopleInStream: {
            ru: 'Людей в эфире:',
            ua: 'Людей в ефірі:',
            en: 'People in stream:',
            de: 'Personen im Stream:',
            pl: 'Ludzi na transmisji:',
        },

        modal: {
            title: {
                ru: 'Управление прямым эфиром',
                ua: 'Керування прямим ефіром',
                en: 'Live Stream Control',
                de: 'Live-Stream-Steuerung',
                pl: 'Zarządzanie transmisją na żywo',
            },
            startButton: {
                ru: 'Начать прямой эфир',
                ua: 'Почати прямий ефір',
                en: 'Start Live Stream',
                de: 'Live-Stream starten',
                pl: 'Rozpocznij transmisję na żywo',
            },
            stopButton: {
                ru: 'Остановить прямой эфир',
                ua: 'Зупинити прямий ефір',
                en: 'Stop Live Stream',
                de: 'Live-Stream beenden',
                pl: 'Zatrzymaj transmisję na żywo',
            },
        },
    },

    npc: {
        dialog_01: {
            welcome: {
                ru: 'Добро пожаловать в офис Weazel News. Здесь работает редакция, ведущие и наши корреспонденты. Чем могу помочь?',
                ua: 'Ласкаво просимо до офісу Weazel News. Тут працює редакція, ведучі та наші кореспонденти. Чим можу допомогти?',
                en: 'Welcome to the Weazel News office. This is where our editors, anchors and correspondents work. How can I help you?',
                de: 'Willkommen im Büro von Weazel News. Hier arbeiten unsere Redaktion, Moderatoren und Korrespondenten. Wie kann ich dir helfen?',
                pl: 'Witamy w biurze Weazel News. Tu pracują nasi redaktorzy, prezenterzy i korespondenci. W czym mogę pomóc?',
            },
            howToJoin: {
                ru: 'Как вступить во фракцию?',
                ua: 'Як вступити до фракції?',
                en: 'How do I join the faction?',
                de: 'Wie trete ich der Fraktion bei?',
                pl: 'Jak dołączyć do frakcji?',
            },
            howToBuyAd: {
                ru: 'Где купить рекламу?',
                ua: 'Де купити рекламу?',
                en: 'Where can I buy advertising?',
                de: 'Wo kann ich Werbung kaufen?',
                pl: 'Gdzie kupić reklamę?',
            },
            howToJoinAnswer: {
                ru: 'Набор в штат проводит руководство фракции. Следите за анонсами в чате и сообществах, затем приходите к нам на собеседование.',
                ua: 'Набір до штату проводить керівництво фракції. Слідкуйте за анонсами в чаті та спільнотах, а потім приходьте до нас на співбесіду.',
                en: 'Staff recruitment is handled by the faction leadership. Follow the announcements in chat and community channels, then come to us for an interview.',
                de: 'Die Einstellung übernimmt die Fraktionsleitung. Verfolge die Ankündigungen im Chat und in den Community-Kanälen und komm dann zu uns zum Vorstellungsgespräch.',
                pl: 'Rekrutacją zajmuje się kierownictwo frakcji. Śledź ogłoszenia na czacie i w społecznościach, a następnie przyjdź do nas na rozmowę.',
            },
            howToBuyAdAnswer: {
                ru: 'Подать объявление можно прямо с телефона: откройте приложение Weazel News, перейдите во вкладку "Опубликовать", составьте текст и оплатите публикацию. После проверки наш сотрудник опубликует объявление.',
                ua: 'Подати оголошення можна прямо з телефону: відкрийте застосунок Weazel News, перейдіть у вкладку "Опублікувати", складіть текст і оплатіть публікацію. Після перевірки наш співробітник опублікує оголошення.',
                en: 'You can submit an ad right from your phone: open the Weazel News app, go to the "Publish" tab, write your text and pay for the publication. After review, one of our staff will post it.',
                de: 'Du kannst eine Anzeige direkt über dein Handy aufgeben: Öffne die Weazel-News-App, gehe zum Reiter "Veröffentlichen", verfasse den Text und bezahle die Veröffentlichung. Nach der Prüfung stellt einer unserer Mitarbeiter sie online.',
                pl: 'Ogłoszenie możesz wysłać prosto z telefonu: otwórz aplikację Weazel News, przejdź do zakładki "Opublikuj", napisz treść i opłać publikację. Po weryfikacji nasz pracownik opublikuje ogłoszenie.',
            },
            okay: {
                ru: 'Понятно',
                ua: 'Зрозуміло',
                en: 'Got it',
                de: 'Verstanden',
                pl: 'Rozumiem',
            },
            bye: {
                ru: 'До свидания',
                ua: 'До побачення',
                en: 'Goodbye',
                de: 'Auf Wiedersehen',
                pl: 'Do widzenia',
            },
        },
    },

    discordAdMessage: {
        title: {
            ru: '📢 Weazel News - Новое объявление',
            ua: '📢 Weazel News - Нове оголошення',
            en: '📢 Weazel News - New Advertisement',
            de: '📢 Weazel News - Neue Anzeige',
            pl: '📢 Weazel News - Nowe ogłoszenie',
        },
        contact: {
            ru: '📱 Контакт',
            ua: '📱 Контакт',
            en: '📱 Contact',
            de: '📱 Kontakt',
            pl: '📱 Kontakt',
        },
        published: {
            ru: '🕐 Опубликовано',
            ua: '🕐 Опубліковано',
            en: '🕐 Published',
            de: '🕐 Veröffentlicht',
            pl: '🕐 Opublikowano',
        },
        discord: {
            ru: '👤 Discord',
            ua: '👤 Discord',
            en: '👤 Discord',
            de: '👤 Discord',
            pl: '👤 Discord',
        },
        editedBy: {
            ru: '👀 Отредактировал',
            ua: '👀 Відредагував',
            en: '👀 Edited By',
            de: '👀 Bearbeitet von',
            pl: '👀 Edytował',
        },
        notSpecified: {
            ru: 'Не указано',
            ua: 'Не вказано',
            en: 'Not specified',
            de: 'Nicht angegeben',
            pl: 'Nie podano',
        },
        unknown: {
            ru: 'Неизвестно',
            ua: 'Невідомо',
            en: 'Unknown',
            de: 'Unbekannt',
            pl: 'Nieznany',
        },
    },
};
