export default {
    header: {
        ru: 'Армрестлинг',
        ua: 'Армрестлінг',
        en: 'Arm wrestling',
        de: 'Armdrücken',
        pl: 'Siłowanie na rękę',
    },
    prompt: {
        start: {
            ru: 'Сесть за стол для армрестлинга',
            ua: 'Сісти за стіл для армрестлінгу',
            en: 'Take a seat at the arm wrestling table',
            de: 'Am Armdrück-Tisch Platz nehmen',
            pl: 'Usiądź przy stole do siłowania',
        },
        join: {
            ru: 'Принять вызов',
            ua: 'Прийняти виклик',
            en: 'Accept the challenge',
            de: 'Herausforderung annehmen',
            pl: 'Przyjmij wyzwanie',
        },
        cancel: {
            ru: 'Встать из-за стола',
            ua: 'Встати з-за столу',
            en: 'Leave the table',
            de: 'Den Tisch verlassen',
            pl: 'Odejdź od stołu',
        },
        busy: {
            ru: 'Стол занят',
            ua: 'Стіл зайнятий',
            en: 'The table is taken',
            de: 'Der Tisch ist besetzt',
            pl: 'Stół jest zajęty',
        },
    },
    bet: {
        title: {
            ru: 'Армрестлинг - ставка',
            ua: 'Армрестлінг - ставка',
            en: 'Arm wrestling - bet',
            de: 'Armdrücken - Einsatz',
            pl: 'Siłowanie na rękę - zakład',
        },
        message: {
            ru: 'Соперник поставит столько же, победитель забирает всё. 0 - дружеский поединок. Максимум ${{max}}.',
            ua: 'Суперник поставить стільки ж, переможець забирає все. 0 - дружній поєдинок. Максимум ${{max}}.',
            en: 'Your opponent matches the stake and the winner takes it all. 0 is a friendly bout. Up to ${{max}}.',
            de: 'Der Gegner setzt dasselbe, der Sieger nimmt alles. 0 ist ein freundschaftliches Duell. Höchstens ${{max}}.',
            pl: 'Przeciwnik stawia tyle samo, zwycięzca bierze wszystko. 0 to pojedynek towarzyski. Maksymalnie ${{max}}.',
        },
        placeholder: {
            ru: 'Сумма ставки',
            ua: 'Сума ставки',
            en: 'Bet amount',
            de: 'Einsatzbetrag',
            pl: 'Kwota zakładu',
        },
        confirm: {
            ru: 'Ждать соперника',
            ua: 'Чекати суперника',
            en: 'Wait for an opponent',
            de: 'Auf einen Gegner warten',
            pl: 'Czekaj na przeciwnika',
        },
        cancel: {
            ru: 'Отмена',
            ua: 'Скасувати',
            en: 'Cancel',
            de: 'Abbrechen',
            pl: 'Anuluj',
        },
        invalid: {
            ru: 'Ставка должна быть от $0 до ${{max}}',
            ua: 'Ставка має бути від $0 до ${{max}}',
            en: 'The bet must be from $0 to ${{max}}',
            de: 'Der Einsatz muss zwischen $0 und ${{max}} liegen',
            pl: 'Zakład musi wynosić od $0 do ${{max}}',
        },
    },
    join: {
        title: {
            ru: 'Армрестлинг',
            ua: 'Армрестлінг',
            en: 'Arm wrestling',
            de: 'Armdrücken',
            pl: 'Siłowanie na rękę',
        },
        message: {
            ru: '{{name}} ждёт соперника. Дружеский поединок без ставки.',
            ua: '{{name}} чекає суперника. Дружній поєдинок без ставки.',
            en: '{{name}} is waiting for an opponent. A friendly bout, no bet.',
            de: '{{name}} wartet auf einen Gegner. Ein freundschaftliches Duell ohne Einsatz.',
            pl: '{{name}} czeka na przeciwnika. Pojedynek towarzyski bez zakładu.',
        },
        messageBet: {
            ru: '{{name}} ждёт соперника. Ставка ${{bet}} с каждого, победитель забирает всё.',
            ua: '{{name}} чекає суперника. Ставка ${{bet}} з кожного, переможець забирає все.',
            en: '{{name}} is waiting for an opponent. ${{bet}} from each of you, the winner takes it all.',
            de: '{{name}} wartet auf einen Gegner. ${{bet}} von jedem, der Sieger nimmt alles.',
            pl: '{{name}} czeka na przeciwnika. ${{bet}} od każdego, zwycięzca bierze wszystko.',
        },
        confirm: {
            ru: 'Бороться',
            ua: 'Боротися',
            en: 'Wrestle',
            de: 'Antreten',
            pl: 'Walcz',
        },
    },
    tableBusy: {
        ru: 'Этот стол уже занят',
        ua: 'Цей стіл уже зайнятий',
        en: 'This table is already taken',
        de: 'Dieser Tisch ist bereits besetzt',
        pl: 'Ten stół jest już zajęty',
    },
    cantNow: {
        ru: 'Сейчас не получится',
        ua: 'Зараз не вийде',
        en: 'You cannot do that right now',
        de: 'Das geht gerade nicht',
        pl: 'Teraz się nie da',
    },
    tooFar: {
        ru: 'Нужно стоять у стола',
        ua: 'Потрібно стояти біля столу',
        en: 'You have to stand at the table',
        de: 'Du musst am Tisch stehen',
        pl: 'Musisz stać przy stole',
    },
    notEnoughMoney: {
        ru: 'Недостаточно наличных для ставки',
        ua: 'Недостатньо готівки для ставки',
        en: 'Not enough cash for the bet',
        de: 'Nicht genug Bargeld für den Einsatz',
        pl: 'Za mało gotówki na zakład',
    },
    waiting: {
        ru: 'Вы ждёте соперника за столом',
        ua: 'Ви чекаєте суперника за столом',
        en: 'You are waiting for an opponent at the table',
        de: 'Du wartest am Tisch auf einen Gegner',
        pl: 'Czekasz przy stole na przeciwnika',
    },
    waitingBet: {
        ru: 'Вы ждёте соперника за столом, ставка ${{bet}}',
        ua: 'Ви чекаєте суперника за столом, ставка ${{bet}}',
        en: 'You are waiting for an opponent at the table, bet ${{bet}}',
        de: 'Du wartest am Tisch auf einen Gegner, Einsatz ${{bet}}',
        pl: 'Czekasz przy stole na przeciwnika, zakład ${{bet}}',
    },
    cancelled: {
        ru: 'Вы встали из-за стола',
        ua: 'Ви встали з-за столу',
        en: 'You left the table',
        de: 'Du hast den Tisch verlassen',
        pl: 'Odszedłeś od stołu',
    },
    leftTable: {
        ru: 'Вы отошли от стола',
        ua: 'Ви відійшли від столу',
        en: 'You walked away from the table',
        de: 'Du hast dich vom Tisch entfernt',
        pl: 'Oddaliłeś się od stołu',
    },
    hostTimeout: {
        ru: 'Соперник так и не нашёлся',
        ua: 'Суперник так і не знайшовся',
        en: 'Nobody took up the challenge',
        de: 'Niemand hat die Herausforderung angenommen',
        pl: 'Nikt nie podjął wyzwania',
    },
    won: {
        ru: 'Победа! Выигрыш ${{amount}}',
        ua: 'Перемога! Виграш ${{amount}}',
        en: 'Victory! You won ${{amount}}',
        de: 'Sieg! Du gewinnst ${{amount}}',
        pl: 'Zwycięstwo! Wygrana ${{amount}}',
    },
    wonForfeit: {
        ru: 'Соперник сдался. Выигрыш ${{amount}}',
        ua: 'Суперник здався. Виграш ${{amount}}',
        en: 'Your opponent gave up. You won ${{amount}}',
        de: 'Dein Gegner hat aufgegeben. Du gewinnst ${{amount}}',
        pl: 'Przeciwnik się poddał. Wygrana ${{amount}}',
    },
    lost: {
        ru: 'Поражение. Ставка ${{amount}} проиграна',
        ua: 'Поразка. Ставку ${{amount}} програно',
        en: 'Defeat. You lost your ${{amount}} bet',
        de: 'Niederlage. Dein Einsatz von ${{amount}} ist verloren',
        pl: 'Porażka. Zakład ${{amount}} przegrany',
    },
    wonFriendly: {
        ru: 'Победа!',
        ua: 'Перемога!',
        en: 'Victory!',
        de: 'Sieg!',
        pl: 'Zwycięstwo!',
    },
    wonForfeitFriendly: {
        ru: 'Соперник сдался. Победа!',
        ua: 'Суперник здався. Перемога!',
        en: 'Your opponent gave up. Victory!',
        de: 'Dein Gegner hat aufgegeben. Sieg!',
        pl: 'Przeciwnik się poddał. Zwycięstwo!',
    },
    lostFriendly: {
        ru: 'Поражение',
        ua: 'Поразка',
        en: 'Defeat',
        de: 'Niederlage',
        pl: 'Porażka',
    },
    hostNoMoney: {
        ru: 'У соперника больше нет денег на ставку',
        ua: 'У суперника більше немає грошей на ставку',
        en: 'Your opponent no longer has the cash for the bet',
        de: 'Dein Gegner hat das Geld für den Einsatz nicht mehr',
        pl: 'Przeciwnik nie ma już gotówki na zakład',
    },
    shard: {
        win: {
            ru: 'Победа',
            ua: 'Перемога',
            en: 'Winner',
            de: 'Sieg',
            pl: 'Zwycięstwo',
        },
        lose: {
            ru: 'Поражение',
            ua: 'Поразка',
            en: 'Loser',
            de: 'Niederlage',
            pl: 'Porażka',
        },
    },
    blip: {
        ru: 'Армрестлинг',
        ua: 'Армрестлінг',
        en: 'Arm wrestling',
        de: 'Armdrücken',
        pl: 'Siłowanie na rękę',
    },
    cef: {
        you: {
            ru: 'Вы',
            ua: 'Ви',
            en: 'You',
            de: 'Du',
            pl: 'Ty',
        },
        quitHold: {
            ru: 'Удерживайте, чтобы сдаться',
            ua: 'Утримуйте, щоб здатися',
            en: 'Hold to give up',
            de: 'Halten zum Aufgeben',
            pl: 'Przytrzymaj, aby się poddać',
        },
        bet: {
            ru: 'Банк',
            ua: 'Банк',
            en: 'Pot',
            de: 'Pott',
            pl: 'Pula',
        },
        friendly: {
            ru: 'Без ставки',
            ua: 'Без ставки',
            en: 'No bet',
            de: 'Ohne Einsatz',
            pl: 'Bez zakładu',
        },
        stage: {
            grip: {
                ru: 'Захват',
                ua: 'Захват',
                en: 'Grip',
                de: 'Griff',
                pl: 'Chwyt',
            },
            push: {
                ru: 'Натиск',
                ua: 'Натиск',
                en: 'Pressure',
                de: 'Druck',
                pl: 'Nacisk',
            },
            final: {
                ru: 'Решающий рывок',
                ua: 'Вирішальний ривок',
                en: 'Final push',
                de: 'Letzter Kraftakt',
                pl: 'Decydujący zryw',
            },
        },
    },
};
