export default {
    tabTitle: {
        ru: 'ARGUS · Федеральная информационная сеть',
        ua: 'ARGUS · Федеральна інформаційна мережа',
        en: 'ARGUS · Federal Intelligence Network',
        de: 'ARGUS · Föderales Nachrichtennetzwerk',
        pl: 'ARGUS · Federalna sieć wywiadowcza',
        zh: 'ARGUS · 联邦情报网络',
    },
    searchTitle: {
        ru: 'ARGUS - Федеральная информационная сеть',
        ua: 'ARGUS - Федеральна інформаційна мережа',
        en: 'ARGUS - Federal Intelligence Network',
        de: 'ARGUS - Föderales Nachrichtennetzwerk',
        pl: 'ARGUS - Federalna sieć wywiadowcza',
        zh: 'ARGUS - 联邦情报网络',
    },
    searchSnippet: {
        ru: 'Официальная база данных LSPD, FIB, Sheriff и Правительства. Записи граждан, реестр транспорта, архив дел.',
        ua: 'Офіційна база даних LSPD, FIB, Sheriff та Уряду. Записи громадян, реєстр транспорту, архів справ.',
        en: 'Official federal database for LSPD, FIB, Sheriff and Government. Citizen records, vehicle registry, case archive.',
        de: 'Offizielle Bundesdatenbank für LSPD, FIB, Sheriff und Regierung. Bürgerverzeichnis, Fahrzeugregister, Fallarchiv.',
        pl: 'Oficjalna federalna baza danych LSPD, FIB, Sheriff i Rządu. Rejestr obywateli, pojazdów, archiwum spraw.',
        zh: 'LSPD、FIB、Sheriff 和政府的官方联邦数据库。公民档案、车辆登记和案件存档。',
    },
    checking: {
        ru: 'Проверка доступа',
        ua: 'Перевірка доступу',
        en: 'Verifying clearance',
        de: 'Berechtigung wird geprüft',
        pl: 'Weryfikacja dostępu',
        zh: '验证权限',
    },
    deniedTag: {
        ru: 'ДОСТУП ЗАПРЕЩЁН',
        ua: 'ДОСТУП ЗАБОРОНЕНО',
        en: 'ACCESS DENIED',
        de: 'ZUGRIFF VERWEIGERT',
        pl: 'DOSTĘP ZABRONIONY',
        zh: '拒绝访问',
    },
    deniedTitle: {
        ru: 'Эта система предназначена только для уполномоченных сотрудников.',
        ua: 'Ця система призначена лише для уповноважених співробітників.',
        en: 'This system is restricted to authorized federal personnel.',
        de: 'Dieses System ist nur für autorisiertes Bundespersonal zugänglich.',
        pl: 'System dostępny wyłącznie dla upoważnionych pracowników federalnych.',
        zh: '本系统仅限授权联邦人员访问。',
    },
    reasonNotInGame: {
        ru: 'Сессия не подтверждена.',
        ua: 'Сесію не підтверджено.',
        en: 'Session not verified.',
        de: 'Sitzung nicht verifiziert.',
        pl: 'Sesja niezweryfikowana.',
        zh: '会话未验证。',
    },
    reasonNoFaction: {
        ru: 'Доступ имеют только сотрудники LSPD, FIB, Sheriff и Правительства.',
        ua: 'Доступ мають лише співробітники LSPD, FIB, Sheriff та Уряду.',
        en: 'Access limited to LSPD, FIB, Sheriff and Government personnel.',
        de: 'Zugriff nur für LSPD-, FIB-, Sheriff- und Regierungspersonal.',
        pl: 'Dostęp tylko dla pracowników LSPD, FIB, Sheriff i Rządu.',
        zh: '仅限 LSPD、FIB、Sheriff 和政府人员访问。',
    },
    reasonNoPermission: {
        ru: 'У вас нет разрешения на работу с базой данных.',
        ua: 'У вас немає дозволу на роботу з базою даних.',
        en: 'You do not have database permission within your faction.',
        de: 'Du hast keine Datenbank-Berechtigung in deiner Fraktion.',
        pl: 'Nie masz uprawnień do bazy danych w swojej frakcji.',
        zh: '您在所属派系中没有数据库权限。',
    },
    reasonOffDuty: {
        ru: 'Доступ возможен только на службе.',
        ua: 'Доступ можливий лише на службі.',
        en: 'Database access is available on duty only.',
        de: 'Datenbankzugriff nur im Dienst möglich.',
        pl: 'Dostęp do bazy tylko na służbie.',
        zh: '仅在执勤时可访问数据库。',
    },
    deniedFooter: {
        ru: 'Все попытки доступа фиксируются.',
        ua: 'Усі спроби доступу фіксуються.',
        en: 'All access attempts are logged.',
        de: 'Alle Zugriffsversuche werden protokolliert.',
        pl: 'Wszystkie próby dostępu są rejestrowane.',
        zh: '所有访问尝试都将被记录。',
    },
};
