export default {
    tabTitle: {
        ru: 'FreeDonate · Бесплатные Olymp Coins',
        ua: 'FreeDonate · Безкоштовні Olymp Coins',
        en: 'FreeDonate · Free Olymp Coins',
        de: 'FreeDonate · Kostenlose Olymp Coins',
        pl: 'FreeDonate · Darmowe Olymp Coins',
        zh: 'FreeDonate · 免费 Olymp Coins',
    },
    searchTitle: {
        ru: 'FreeDonate — получи БЕСПЛАТНЫЕ Olymp Coins прямо сейчас!',
        ua: 'FreeDonate — отримай БЕЗКОШТОВНІ Olymp Coins просто зараз!',
        en: 'FreeDonate — Get FREE Olymp Coins instantly!',
        de: 'FreeDonate — Hol dir KOSTENLOSE Olymp Coins sofort!',
        pl: 'FreeDonate — Odbierz DARMOWE Olymp Coins od razu!',
        zh: 'FreeDonate — 立即获取免费 Olymp Coins！',
    },
    searchSnippet: {
        ru: 'Забери 5 000 OC прямо сейчас. Без проверок и заданий — просто кликни и получи. Ограниченное предложение!',
        ua: 'Забери 5 000 OC прямо зараз. Без перевірок і завдань — просто клікни і отримай. Обмежена пропозиція!',
        en: 'Claim your 5,000 OC bonus right now. No verification, no tasks — just click and receive. Limited time offer!',
        de: 'Hol dir jetzt deinen 5 000 OC Bonus. Keine Verifizierung, keine Aufgaben — einfach klicken und erhalten. Zeitlich begrenztes Angebot!',
        pl: 'Odbierz teraz bonus 5 000 OC. Bez weryfikacji, bez zadań — wystarczy kliknąć. Oferta limitowana!',
        zh: '立即领取 5,000 OC 奖励。无需验证、无需任务，点击即可获得。限时优惠！',
    },
    stamp: {
        ru: '100%<br>ЛЕГИТ',
        ua: '100%<br>ЛЕГІТ',
        en: '100%<br>LEGIT',
        de: '100%<br>ECHT',
        pl: '100%<br>LEGIT',
        zh: '100%<br>真实',
    },
    titlePrefix: {
        ru: 'бесплатно',
        ua: 'безкоштовно',
        en: 'free',
        de: 'kostenlos',
        pl: 'darmowe',
        zh: '免费',
    },
    titleAmount: {
        ru: '1 000 OC',
        ua: '1 000 OC',
        en: '1,000 OC',
        de: '1.000 OC',
        pl: '1 000 OC',
        zh: '1,000 OC',
    },
    sub: {
        ru: 'нажми кнопку чтобы получить',
        ua: 'натисни кнопку щоб отримати',
        en: 'click the button below to receive',
        de: 'klicke auf den Button um zu erhalten',
        pl: 'kliknij przycisk poniżej, aby otrzymać',
        zh: '点击下方按钮领取',
    },
    button: {
        ru: 'забрать ✓',
        ua: 'забрати ✓',
        en: 'click to receive ✓',
        de: 'jetzt erhalten ✓',
        pl: 'odbierz ✓',
        zh: '立即领取 ✓',
    },
    checkNoScam: {
        ru: '✓ не скам',
        ua: '✓ не скам',
        en: '✓ no scam',
        de: '✓ kein Scam',
        pl: '✓ nie scam',
        zh: '✓ 非骗局',
    },
    checkInstant: {
        ru: '✓ мгновенно',
        ua: '✓ миттєво',
        en: '✓ instant',
        de: '✓ sofort',
        pl: '✓ natychmiast',
        zh: '✓ 即时到账',
    },
    checkSafe: {
        ru: '✓ безопасно',
        ua: '✓ безпечно',
        en: '✓ safe',
        de: '✓ sicher',
        pl: '✓ bezpiecznie',
        zh: '✓ 安全',
    },
    foot: {
        ru: 'официальный партнёр olymp coin · проверено google™',
        ua: 'офіційний партнер olymp coin · перевірено google™',
        en: 'official olymp coin partner · verified by google™',
        de: 'offizieller olymp coin partner · von google™ verifiziert',
        pl: 'oficjalny partner olymp coin · zweryfikowane przez google™',
        zh: '官方 olymp coin 合作伙伴 · 由 google™ 认证',
    },
    loading: {
        ru: 'отправляем монеты...',
        ua: 'надсилаємо монети...',
        en: 'sending coins...',
        de: 'münzen werden gesendet...',
        pl: 'wysyłanie monet...',
        zh: '正在发送硬币……',
    },
};
