export default {
    tabTitle: {
        ru: 'Pigeon Truth - они не птицы',
        ua: 'Pigeon Truth - вони не птахи',
        en: 'Pigeon Truth - they are not birds',
        de: 'Pigeon Truth - sie sind keine Vögel',
        pl: 'Pigeon Truth - to nie są ptaki',
        zh: 'Pigeon Truth - 它们不是鸟',
    },
    searchTitle: {
        ru: 'Pigeon Truth - вся правда о голубях Лос-Сантоса',
        ua: 'Pigeon Truth - вся правда про голубів Лос-Сантоса',
        en: 'Pigeon Truth - the whole truth about Los Santos pigeons',
        de: 'Pigeon Truth - die ganze Wahrheit über die Tauben von Los Santos',
        pl: 'Pigeon Truth - cała prawda o gołębiach Los Santos',
        zh: 'Pigeon Truth - 洛圣都鸽子的全部真相',
    },
    searchSnippet: {
        ru: 'С 1974 года каждый голубь в городе - дрон. Хлебные крошки - это обновления прошивки. Не смотри им в глаза.',
        ua: 'З 1974 року кожен голуб у місті - дрон. Хлібні крихти - це оновлення прошивки. Не дивись їм в очі.',
        en: 'Since 1974 every pigeon in the city has been a drone. Breadcrumbs are firmware updates. Do not make eye contact.',
        de: 'Seit 1974 ist jede Taube der Stadt eine Drohne. Brotkrümel sind Firmware-Updates. Kein Blickkontakt.',
        pl: 'Od 1974 roku każdy gołąb w mieście to dron. Okruszki chleba to aktualizacje oprogramowania. Nie patrz im w oczy.',
        zh: '自1974年起，城里的每一只鸽子都是无人机。面包屑就是固件更新。千万别和它们对视。',
    },

    mast: {
        logo: { ru: 'PIGEON TRUTH', ua: 'PIGEON TRUTH', en: 'PIGEON TRUTH', de: 'PIGEON TRUTH', pl: 'PIGEON TRUTH', zh: 'PIGEON TRUTH' },
        tld: { ru: '.net', ua: '.net', en: '.net', de: '.net', pl: '.net', zh: '.net' },
        tagline: {
            ru: 'Независимое расследование того, что сидит у тебя на подоконнике. С 2019 года. Работаем, пока держится Wi-Fi.',
            ua: 'Незалежне розслідування того, що сидить у тебе на підвіконні. З 2019 року. Працюємо, поки тримається Wi-Fi.',
            en: 'Independent research into what is sitting on your windowsill. Since 2019. Online for as long as the Wi-Fi holds.',
            de: 'Unabhängige Recherche darüber, was auf deiner Fensterbank sitzt. Seit 2019. Online, solange das WLAN hält.',
            pl: 'Niezależne śledztwo w sprawie tego, co siedzi na twoim parapecie. Od 2019 roku. Działamy, dopóki trzyma Wi-Fi.',
            zh: '独立调查：你窗台上坐着的到底是什么。始于2019年。只要Wi-Fi还撑得住，我们就在线。',
        },
        watching: {
            ru: 'Голубей на странице сейчас:',
            ua: 'Голубів на сторінці зараз:',
            en: 'Pigeons watching this page:',
            de: 'Tauben auf dieser Seite gerade:',
            pl: 'Gołębi na tej stronie teraz:',
            zh: '正在看这个页面的鸽子：',
        },
        watchingNote: {
            ru: '(число растёт. оно всегда растёт)',
            ua: '(число росте. воно завжди росте)',
            en: '(the number goes up. it always goes up)',
            de: '(die Zahl steigt. sie steigt immer)',
            pl: '(liczba rośnie. zawsze rośnie)',
            zh: '（数字在涨。它一直在涨）',
        },
        visitor: {
            ru: 'Вы посетитель №',
            ua: 'Ви відвідувач №',
            en: 'You are visitor No.',
            de: 'Du bist Besucher Nr.',
            pl: 'Jesteś gościem nr',
            zh: '你是第几位访客：',
        },
        visitorNote: {
            ru: '(четверо из них - я)',
            ua: '(четверо з них - я)',
            en: '(four of them were me)',
            de: '(vier davon war ich)',
            pl: '(czterech z nich to ja)',
            zh: '（其中四个是我）',
        },
    },

    nav: {
        board: { ru: 'Доска', ua: 'Дошка', en: 'The board', de: 'Pinnwand', pl: 'Tablica', zh: '证据墙' },
        scanner: { ru: 'Сканер', ua: 'Сканер', en: 'Scanner', de: 'Scanner', pl: 'Skaner', zh: '扫描仪' },
        report: { ru: 'Сообщить о голубе', ua: 'Повідомити про голуба', en: 'Report a sighting', de: 'Sichtung melden', pl: 'Zgłoś obserwację', zh: '举报目击' },
        timeline: { ru: 'Операция «Подоконник»', ua: 'Операція «Підвіконня»', en: 'Operation Windowsill', de: 'Operation Fensterbank', pl: 'Operacja Parapet', zh: '窗台行动' },
        guide: { ru: 'Как выжить', ua: 'Як вижити', en: 'Survival guide', de: 'Überlebensguide', pl: 'Jak przeżyć', zh: '生存指南' },
        updates: { ru: 'Дневник', ua: 'Щоденник', en: 'Updates', de: 'Tagebuch', pl: 'Dziennik', zh: '更新日志' },
    },

    foot: {
        a: {
            ru: 'Сайт не связан ни с каким правительством. Правительство связано с голубями.',
            ua: 'Сайт не пов\'язаний із жодним урядом. Уряд пов\'язаний із голубами.',
            en: 'This site is not affiliated with any government. The government is affiliated with the pigeons.',
            de: 'Diese Seite steht mit keiner Regierung in Verbindung. Die Regierung steht mit den Tauben in Verbindung.',
            pl: 'Ta strona nie jest powiązana z żadnym rządem. Rząd jest powiązany z gołębiami.',
            zh: '本站与任何政府无关。政府与鸽子有关。',
        },
        b: {
            ru: 'Отпечатано на чужом ксероксе. Копируйте свободно, оригиналы прячьте.',
            ua: 'Надруковано на чужому ксероксі. Копіюйте вільно, оригінали ховайте.',
            en: 'Printed on a borrowed photocopier. Copy freely, hide the originals.',
            de: 'Auf einem geliehenen Kopierer gedruckt. Frei kopieren, Originale verstecken.',
            pl: 'Wydrukowano na pożyczonym ksero. Kopiujcie śmiało, oryginały chowajcie.',
            zh: '用借来的复印机印的。随便复印，原件藏好。',
        },
        sign: { ru: '- ZeroCrumbs', ua: '- ZeroCrumbs', en: '- ZeroCrumbs', de: '- ZeroCrumbs', pl: '- ZeroCrumbs', zh: '- ZeroCrumbs' },
    },

    notFound: {
        title: { ru: 'Эту страницу удалили', ua: 'Цю сторінку видалили', en: 'This page has been removed', de: 'Diese Seite wurde entfernt', pl: 'Ta strona została usunięta', zh: '此页面已被删除' },
        body: {
            ru: 'Минуту назад она была здесь. Потом что-то постучало в окно, и её не стало.',
            ua: 'Хвилину тому вона була тут. Потім щось постукало у вікно, і її не стало.',
            en: 'It was here a minute ago. Then something tapped on the window, and now it is gone.',
            de: 'Vor einer Minute war sie noch da. Dann hat etwas ans Fenster geklopft, und jetzt ist sie weg.',
            pl: 'Minutę temu tu była. Potem coś zastukało w okno i już jej nie ma.',
            zh: '一分钟前它还在。然后有什么东西敲了敲窗户，它就没了。',
        },
        back: { ru: 'Вернуться к доске', ua: 'Повернутися до дошки', en: 'Back to the board', de: 'Zurück zur Pinnwand', pl: 'Wróć do tablicy', zh: '回到证据墙' },
    },

    board: {
        hint: {
            ru: 'кликни на улику, чтобы рассмотреть',
            ua: 'клацни на доказ, щоб роздивитися',
            en: 'click an exhibit to look closer',
            de: 'klick ein Beweisstück an, um genauer hinzusehen',
            pl: 'kliknij dowód, żeby się przyjrzeć',
            zh: '点击证物仔细看',
        },
        string: { ru: 'ВСЁ СВЯЗАНО', ua: 'ВСЕ ПОВ\'ЯЗАНО', en: 'IT\'S ALL CONNECTED', de: 'ALLES HÄNGT ZUSAMMEN', pl: 'WSZYSTKO SIĘ ŁĄCZY', zh: '一切都有联系' },
        stringNote: {
            ru: '(нитку натянул я сам. всё равно считается)',
            ua: '(нитку натягнув я сам. все одно рахується)',
            en: '(I tied the string myself. still counts)',
            de: '(die Schnur hab ich selbst gespannt. zählt trotzdem)',
            pl: '(sznurek naciągnąłem sam. i tak się liczy)',
            zh: '（线是我自己拉的。照样算数）',
        },
        clip: {
            head: {
                ru: 'Местного жителя попросили покинуть парк после «допроса» голубя',
                ua: 'Місцевого мешканця попросили покинути парк після «допиту» голуба',
                en: 'Local man asked to leave park after "interrogating" a pigeon',
                de: 'Anwohner nach "Verhör" einer Taube aus dem Park verwiesen',
                pl: 'Mieszkańca wyproszono z parku po "przesłuchaniu" gołębia',
                zh: '本地男子「审问」鸽子后被请出公园',
            },
            src: { ru: 'Weazel News, стр. 14', ua: 'Weazel News, стор. 14', en: 'Weazel News, page 14', de: 'Weazel News, Seite 14', pl: 'Weazel News, str. 14', zh: 'Weazel News，第14版' },
            note: { ru: 'СТР. 14?!', ua: 'СТОР. 14?!', en: 'PAGE 14?!', de: 'SEITE 14?!', pl: 'STR. 14?!', zh: '第14版？！' },
        },
        center: {
            title: { ru: 'ОПЕРАЦИЯ «ПОДОКОННИК»', ua: 'ОПЕРАЦІЯ «ПІДВІКОННЯ»', en: 'OPERATION WINDOWSILL', de: 'OPERATION FENSTERBANK', pl: 'OPERACJA PARAPET', zh: '窗台行动' },
            sub: { ru: '1974 - сегодня. Всё ещё идёт.', ua: '1974 - сьогодні. Досі триває.', en: '1974 - today. Still running.', de: '1974 - heute. Läuft noch.', pl: '1974 - dziś. Wciąż trwa.', zh: '1974年至今。仍在进行。' },
        },
        enhance0: { ru: 'Увеличить', ua: 'Збільшити', en: 'Enhance', de: 'Vergrößern', pl: 'Powiększ', zh: '放大' },
        enhance1: { ru: 'Ещё увеличить', ua: 'Ще збільшити', en: 'Enhance more', de: 'Weiter vergrößern', pl: 'Powiększ bardziej', zh: '再放大' },
        enhance2: { ru: 'УВЕЛИЧИТЬ!!', ua: 'ЗБІЛЬШИТИ!!', en: 'ENHANCE!!', de: 'VERGRÖSSERN!!', pl: 'POWIĘKSZ!!', zh: '放大！！' },
        enhance3: { ru: 'Уменьшить (я всё видел)', ua: 'Зменшити (я все бачив)', en: 'Zoom out (I saw enough)', de: 'Rauszoomen (ich hab genug gesehen)', pl: 'Oddal (widziałem dość)', zh: '缩小（我看够了）' },
        serial: { ru: 'СОБСТВЕННОСТЬ ШТАТА С.А.', ua: 'ВЛАСНІСТЬ ШТАТУ С.А.', en: 'PROPERTY OF S.A.', de: 'EIGENTUM VON S.A.', pl: 'WŁASNOŚĆ STANU S.A.', zh: '圣安地列斯州财产' },
        enhanceNote: { ru: 'ВОТ. ВИДИТЕ?', ua: 'ОСЬ. БАЧИТЕ?', en: 'THERE. SEE IT?', de: 'DA. SIEHST DU ES?', pl: 'TAM. WIDZISZ?', zh: '那儿。看见了吗？' },
        close: { ru: 'Приколоть обратно', ua: 'Пришпилити назад', en: 'Pin it back', de: 'Wieder anpinnen', pl: 'Przypnij z powrotem', zh: '钉回去' },
        scan: { ru: 'Прогнать через сканер', ua: 'Прогнати через сканер', en: 'Run it through the scanner', de: 'Durch den Scanner jagen', pl: 'Przepuść przez skaner', zh: '丢进扫描仪' },
        caseTitle: { ru: 'Заметки по делу', ua: 'Нотатки у справі', en: 'Case notes', de: 'Fallnotizen', pl: 'Notatki do sprawy', zh: '案件笔记' },
        intro: {
            title: { ru: 'Прочитай, пока не удалили', ua: 'Прочитай, поки не видалили', en: 'Read this before they take it down', de: 'Lies das, bevor sie es löschen', pl: 'Przeczytaj, zanim to usuną', zh: '趁他们删掉之前读完' },
            p1: {
                ru: 'Каждый голубь в Лос-Сантосе - машина. Не некоторые. Каждый. Последний настоящий голубь в этом городе умер в 1971 году на крыше рыболовной лавки на пирсе Дель-Перро. На похороны не пришёл никто, кроме меня. Мне было семь. Я принёс крекер.',
                ua: 'Кожен голуб у Лос-Сантосі - машина. Не деякі. Кожен. Останній справжній голуб у цьому місті помер 1971 року на даху рибальської крамниці на пірсі Дель-Перро. На похорон не прийшов ніхто, крім мене. Мені було сім. Я приніс крекер.',
                en: 'Every pigeon in Los Santos is a machine. Not some of them. Every single one. The last real pigeon in this city died in 1971 on the roof of the bait shop at Del Perro Pier. Nobody came to the funeral except me. I was seven. I brought a cracker.',
                de: 'Jede Taube in Los Santos ist eine Maschine. Nicht manche. Jede einzelne. Die letzte echte Taube dieser Stadt starb 1971 auf dem Dach des Köderladens am Del Perro Pier. Zur Beerdigung kam niemand außer mir. Ich war sieben. Ich hatte einen Cracker dabei.',
                pl: 'Każdy gołąb w Los Santos to maszyna. Nie niektóre. Każdy jeden. Ostatni prawdziwy gołąb w tym mieście zmarł w 1971 roku na dachu sklepu wędkarskiego na molo Del Perro. Na pogrzeb nie przyszedł nikt oprócz mnie. Miałem siedem lat. Przyniosłem krakersa.',
                zh: '洛圣都的每一只鸽子都是机器。不是一部分，是每一只。这座城市最后一只真鸽子于1971年死在德尔佩罗码头鱼饵店的屋顶上。葬礼上除了我谁都没来。那年我七岁。我带了一块饼干。',
            },
            p2: {
                ru: 'В 1974 году правительство за одну ночь заменило всех остальных. На проводах они заряжаются. Хлебные крошки - обновления прошивки. Воркование - это рукопожатие dial-up модема. Закрой глаза, послушай и скажи, что я неправ.',
                ua: '1974 року уряд за одну ніч замінив усіх інших. На дротах вони заряджаються. Хлібні крихти - оновлення прошивки. Воркування - це рукостискання dial-up модема. Заплющ очі, послухай і скажи, що я не правий.',
                en: 'In 1974 the government swapped the rest overnight. They sit on power lines to charge. Breadcrumbs are firmware updates. The cooing is a dial-up modem handshake. Close your eyes, listen, and tell me I am wrong.',
                de: '1974 hat die Regierung den Rest über Nacht ausgetauscht. Auf den Stromleitungen laden sie. Brotkrümel sind Firmware-Updates. Das Gurren ist der Handshake eines Einwahlmodems. Augen zu, zuhören, und dann sag mir, dass ich falsch liege.',
                pl: 'W 1974 roku rząd w jedną noc podmienił całą resztę. Na drutach się ładują. Okruszki chleba to aktualizacje oprogramowania. Gruchanie to handshake modemu dial-up. Zamknij oczy, posłuchaj i powiedz, że się mylę.',
                zh: '1974年，政府一夜之间把剩下的全换掉了。它们蹲在电线上是在充电。面包屑是固件更新。咕咕声是拨号调制解调器的握手音。闭上眼睛听一听，再告诉我我错了。',
            },
            p3: {
                ru: 'Всё на этой доске - улики. Кликай. Смотри внимательнее. А потом посмотри вверх.',
                ua: 'Усе на цій дошці - докази. Клацай. Дивись уважніше. А потім подивись угору.',
                en: 'Everything on this board is evidence. Click it. Look closer. Then look up.',
                de: 'Alles an dieser Pinnwand ist Beweismaterial. Klick drauf. Schau genauer hin. Dann schau nach oben.',
                pl: 'Wszystko na tej tablicy to dowody. Klikaj. Przyjrzyj się. A potem spójrz w górę.',
                zh: '这面墙上的一切都是证据。点开，看仔细，然后抬头看看。',
            },
        },
        anatomy: {
            title: { ru: 'Устройство изделия', ua: 'Будова виробу', en: 'Anatomy of a unit', de: 'Aufbau einer Einheit', pl: 'Budowa jednostki', zh: '单元构造图' },
            sub: {
                ru: 'восстановлено по памяти и наброску на салфетке',
                ua: 'відновлено з пам\'яті та ескізу на серветці',
                en: 'reconstructed from memory and a napkin sketch',
                de: 'aus dem Gedächtnis und einer Serviettenskizze rekonstruiert',
                pl: 'odtworzone z pamięci i szkicu na serwetce',
                zh: '凭记忆和一张餐巾纸草图复原',
            },
            a1: { ru: 'камера («глаз»)', ua: 'камера («око»)', en: 'camera (the "eye")', de: 'Kamera (das "Auge")', pl: 'kamera ("oko")', zh: '摄像头（「眼睛」）' },
            a2: { ru: 'модем 56k - отсюда воркование', ua: 'модем 56k - звідси воркування', en: '56k modem - makes the cooing', de: '56k-Modem - macht das Gurren', pl: 'modem 56k - stąd gruchanie', zh: '56k调制解调器，负责咕咕叫' },
            a3: { ru: 'радиатор (блестящие перья)', ua: 'радіатор (блискуче пір\'я)', en: 'heat sink (the shiny feathers)', de: 'Kühlkörper (glänzende Federn)', pl: 'radiator (błyszczące pióra)', zh: '散热片（发亮的羽毛）' },
            a4: { ru: 'порт для хлеба', ua: 'порт для хліба', en: 'bread port', de: 'Brot-Port', pl: 'port chlebowy', zh: '面包接口' },
            a5: { ru: 'зарядные контакты', ua: 'зарядні контакти', en: 'charging contacts', de: 'Ladekontakte', pl: 'styki ładowania', zh: '充电触点' },
            a6: { ru: 'стабилизатор - поэтому голова кивает', ua: 'стабілізатор - тому голова киває', en: 'gimbal - this is why the head bobs', de: 'Gimbal - darum wippt der Kopf', pl: 'gimbal - dlatego głowa się kiwa', zh: '云台，所以头会一点一点的' },
            a7: { ru: 'антенна', ua: 'антена', en: 'antenna', de: 'Antenne', pl: 'antena', zh: '天线' },
            a8: {
                ru: 'аккумулятор. сердца нет. (не проверял. но нет)',
                ua: 'акумулятор. серця немає. (не перевіряв. але немає)',
                en: 'battery. no heart. (didn\'t check. but no heart)',
                de: 'Akku. kein Herz. (nicht nachgesehen. aber keins)',
                pl: 'akumulator. serca brak. (nie sprawdzałem. ale brak)',
                zh: '电池。没有心脏。（我没查过。但肯定没有）',
            },
        },
        latest: {
            title: { ru: 'Последняя запись', ua: 'Останній запис', en: 'Latest entry', de: 'Letzter Eintrag', pl: 'Ostatni wpis', zh: '最新一条' },
            more: { ru: 'Читать весь дневник', ua: 'Читати весь щоденник', en: 'Read the whole diary', de: 'Das ganze Tagebuch lesen', pl: 'Czytaj cały dziennik', zh: '阅读全部日志' },
        },
    },

    ex: {
        e1: {
            title: { ru: 'Улика А: глаз', ua: 'Доказ А: око', en: 'Exhibit A: the eye', de: 'Beweisstück A: das Auge', pl: 'Dowód A: oko', zh: '证物A：眼睛' },
            caption: {
                ru: 'Площадь Легиона, 07:40. Смотрел на меня 11 минут.',
                ua: 'Площа Легіону, 07:40. Дивився на мене 11 хвилин.',
                en: 'Legion Square, 07:40. Stared at me for 11 minutes.',
                de: 'Legion Square, 07:40. Hat mich 11 Minuten angestarrt.',
                pl: 'Legion Square, 07:40. Gapił się na mnie 11 minut.',
                zh: '军团广场，07:40。盯了我11分钟。',
            },
            n1: { ru: 'мёртвый взгляд. обратите внимание', ua: 'мертвий погляд. зверніть увагу', en: 'notice the dead eyes', de: 'man beachte die toten Augen', pl: 'zwróćcie uwagę na martwe oczy', zh: '注意那双死气沉沉的眼睛' },
            n2: { ru: 'порт для хлеба', ua: 'порт для хліба', en: 'bread port', de: 'Brot-Port', pl: 'port na chleb', zh: '面包接口' },
            n3: { ru: 'блестит = радиатор', ua: 'блищить = радіатор', en: 'shiny = heat sink', de: 'glänzt = Kühlkörper', pl: 'błyszczy = radiator', zh: '发亮 = 散热片' },
            case: {
                ru: 'Посмотрите на кольцо вокруг глаза. У настоящих птиц не бывает кольца фокусировки. Я увеличивал фото, пока монитор не начал пищать. Когда я пошевелился, зрачок сузился. Так делают камеры. Птицы, говорят, тоже, но камеры начали первыми.',
                ua: 'Подивіться на кільце навколо ока. У справжніх птахів не буває кільця фокусування. Я збільшував фото, поки монітор не почав пищати. Коли я поворухнувся, зіниця звузилася. Так роблять камери. Птахи, кажуть, теж, але камери почали першими.',
                en: 'Look at the ring around the eye. Real birds do not have a focus ring. I zoomed in until my monitor made a noise. When I moved, the pupil got smaller. Cameras do that. Birds do too, apparently, but cameras did it first.',
                de: 'Seht euch den Ring ums Auge an. Echte Vögel haben keinen Fokusring. Ich habe reingezoomt, bis mein Monitor ein Geräusch gemacht hat. Als ich mich bewegt habe, wurde die Pupille kleiner. Das machen Kameras. Vögel angeblich auch, aber Kameras zuerst.',
                pl: 'Spójrzcie na pierścień wokół oka. Prawdziwe ptaki nie mają pierścienia ostrości. Powiększałem zdjęcie, aż monitor zaczął piszczeć. Kiedy się ruszyłem, źrenica się zwęziła. Tak robią kamery. Ptaki podobno też, ale kamery były pierwsze.',
                zh: '看看眼睛周围那一圈。真正的鸟没有对焦环。我把照片放大到显示器都发出了声音。我一动，瞳孔就缩小了。摄像头就是这样的。据说鸟也会这样，但摄像头先会的。',
            },
        },
        e2: {
            title: { ru: 'Улика Б: засада', ua: 'Доказ Б: засідка', en: 'Exhibit B: the stakeout', de: 'Beweisstück B: die Observation', pl: 'Dowód B: zasadzka', zh: '证物B：蹲守' },
            caption: {
                ru: 'Миррор-Парк. Сидит в кусте роз, будто платит там аренду.',
                ua: 'Міррор-Парк. Сидить у кущі троянд, ніби платить там оренду.',
                en: 'Mirror Park. Sitting in a rose bush like it pays rent there.',
                de: 'Mirror Park. Sitzt im Rosenbusch, als würde es dort Miete zahlen.',
                pl: 'Mirror Park. Siedzi w krzaku róż, jakby płacił tam czynsz.',
                zh: '镜湖公园。蹲在玫瑰丛里，好像它在那儿交房租似的。',
            },
            n1: { ru: 'режим маскировки', ua: 'режим маскування', en: 'camouflage mode', de: 'Tarnmodus', pl: 'tryb kamuflażu', zh: '伪装模式' },
            n2: { ru: 'клюв = антенна', ua: 'дзьоб = антена', en: 'beak = antenna', de: 'Schnabel = Antenne', pl: 'dziób = antena', zh: '喙 = 天线' },
            n3: { ru: 'он знает, что я тут', ua: 'він знає, що я тут', en: 'it knows I am here', de: 'es weiß, dass ich hier bin', pl: 'on wie, że tu jestem', zh: '它知道我在这儿' },
            case: {
                ru: 'Голуби не любят кусты. Этот просидел в розах три дня, направленный прямо на гараж соседа. На четвёртый день гараж перекрасили. Совпадение? Новая краска была серой.',
                ua: 'Голуби не люблять кущі. Цей просидів у трояндах три дні, спрямований просто на гараж сусіда. Четвертого дня гараж перефарбували. Збіг? Нова фарба була сірою.',
                en: 'Pigeons do not like bushes. This one sat in a rose bush for three days, pointed at my neighbour\'s garage. On the fourth day the garage was repainted. Coincidence? The new paint was gray.',
                de: 'Tauben mögen keine Büsche. Diese saß drei Tage im Rosenbusch, ausgerichtet auf die Garage meines Nachbarn. Am vierten Tag wurde die Garage neu gestrichen. Zufall? Die neue Farbe war grau.',
                pl: 'Gołębie nie lubią krzaków. Ten siedział w różach trzy dni, wycelowany w garaż sąsiada. Czwartego dnia garaż przemalowano. Przypadek? Nowa farba była szara.',
                zh: '鸽子不喜欢灌木丛。这只在玫瑰丛里蹲了三天，正对着我邻居的车库。第四天，车库被重新刷了漆。巧合？新漆是灰色的。',
            },
        },
        e3: {
            title: { ru: 'Улика В: зарядная станция', ua: 'Доказ В: зарядна станція', en: 'Exhibit C: the charging station', de: 'Beweisstück C: die Ladestation', pl: 'Dowód C: stacja ładowania', zh: '证物C：充电站' },
            caption: {
                ru: 'Дэвис, провода над Карсон-авеню, 06:12.',
                ua: 'Девіс, дроти над Карсон-авеню, 06:12.',
                en: 'Davis, power line over Carson Ave, 06:12.',
                de: 'Davis, Stromleitung über der Carson Ave, 06:12.',
                pl: 'Davis, linia nad Carson Ave, 06:12.',
                zh: '戴维斯，卡森大道上方的电线，06:12。',
            },
            n1: { ru: 'ЗАРЯЖАЮТСЯ', ua: 'ЗАРЯДЖАЮТЬСЯ', en: 'CHARGING', de: 'LADEN', pl: 'ŁADUJĄ SIĘ', zh: '正在充电' },
            n2: { ru: 'почему их не бьёт током? ДУМАЙ', ua: 'чому їх не б\'є струмом? ДУМАЙ', en: 'why don\'t they get shocked? THINK', de: 'warum kriegen die keinen Schlag? DENK NACH', pl: 'czemu nie kopie ich prąd? MYŚL', zh: '为什么它们不会触电？想想看' },
            n3: { ru: 'зарядка', ua: 'зарядка', en: 'the charger', de: 'das Ladegerät', pl: 'ładowarka', zh: '充电器' },
            case: {
                ru: '«Птички на проводе», говорят все. «Мило», говорят все. В 06:00, когда стая садится, мигает весь квартал. Каждое утро. Энергокомпания называет это «известным явлением». Известным кому?',
                ua: '«Пташки на дроті», кажуть усі. «Мило», кажуть усі. О 06:00, коли зграя сідає, блимає весь квартал. Щоранку. Енергокомпанія називає це «відомим явищем». Відомим кому?',
                en: 'Birds on a wire, everyone says. Cute, everyone says. At 06:00, when the flock lands, the whole block flickers. Every morning. The power company calls it a "known phenomenon". Known to whom?',
                de: 'Vögel auf der Leitung, sagen alle. Süß, sagen alle. Um 06:00, wenn der Schwarm landet, flackert der ganze Block. Jeden Morgen. Das Stromwerk nennt es ein "bekanntes Phänomen". Bekannt wem?',
                pl: 'Ptaszki na drucie, mówią wszyscy. Słodkie, mówią wszyscy. O 06:00, kiedy stado siada, mruga całe osiedle. Każdego ranka. Elektrownia nazywa to "znanym zjawiskiem". Znanym komu?',
                zh: '大家都说，那是电线上的小鸟。大家都说，好可爱。每天早上6点，鸟群一落下，整条街的灯都闪一下。每天早上。电力公司说这是「已知现象」。谁知道的？',
            },
        },
        e4: {
            title: { ru: 'Улика Г: ретранслятор', ua: 'Доказ Г: ретранслятор', en: 'Exhibit D: the relay tower', de: 'Beweisstück D: der Sendemast', pl: 'Dowód D: przekaźnik', zh: '证物D：中继塔' },
            caption: {
                ru: 'Рокфорд-Хиллз. Дежурство на памятнике, 8 часов в день.',
                ua: 'Рокфорд-Хіллз. Чергування на пам\'ятнику, 8 годин на день.',
                en: 'Rockford Hills. Statue duty, 8 hours a day.',
                de: 'Rockford Hills. Statuendienst, 8 Stunden am Tag.',
                pl: 'Rockford Hills. Dyżur na pomniku, 8 godzin dziennie.',
                zh: '罗克福德山。雕像值班，每天8小时。',
            },
            n1: { ru: 'РЕТРАНСЛЯТОР', ua: 'РЕТРАНСЛЯТОР', en: 'RELAY', de: 'SENDER', pl: 'PRZEKAŹNIK', zh: '中继' },
            n2: { ru: 'запасной', ua: 'запасний', en: 'backup unit', de: 'Ersatzgerät', pl: 'zapasowy', zh: '备用机' },
            n3: { ru: 'лев знает. лев не может сказать', ua: 'лев знає. лев не може сказати', en: 'the lion knows. the lion can\'t talk', de: 'der Löwe weiß es. der Löwe kann nicht reden', pl: 'lew wie. lew nie może powiedzieć', zh: '狮子知道。狮子说不出来' },
            case: {
                ru: 'Почему они всегда сидят на памятниках? Памятники не двигаются, не разговаривают и стоят ровно в центре каждой площади. Идеальная прямая видимость. Памятник - это радиомачта, которой выдали скульптуру для маскировки.',
                ua: 'Чому вони завжди сидять на пам\'ятниках? Пам\'ятники не рухаються, не розмовляють і стоять рівно в центрі кожної площі. Ідеальна пряма видимість. Пам\'ятник - це радіощогла, якій видали скульптуру для маскування.',
                en: 'Why do they always sit on statues? Statues do not move, do not talk, and stand in the exact centre of every square. Perfect line of sight. A statue is a radio mast that was given a sculpture as a disguise.',
                de: 'Warum sitzen sie immer auf Statuen? Statuen bewegen sich nicht, reden nicht und stehen genau in der Mitte jedes Platzes. Perfekte Sichtlinie. Eine Statue ist ein Funkmast, dem man zur Tarnung eine Skulptur gegeben hat.',
                pl: 'Dlaczego zawsze siadają na pomnikach? Pomniki się nie ruszają, nie mówią i stoją dokładnie na środku każdego placu. Idealna widoczność. Pomnik to maszt radiowy, któremu dano rzeźbę dla kamuflażu.',
                zh: '它们为什么总坐在雕像上？雕像不会动，不会说话，而且正好立在每个广场的正中央。视野完美。雕像就是一座穿了雕塑外衣的无线电塔。',
            },
        },
        e5: {
            title: { ru: 'Улика Д: обновление', ua: 'Доказ Д: оновлення', en: 'Exhibit E: the update', de: 'Beweisstück E: das Update', pl: 'Dowód E: aktualizacja', zh: '证物E：更新' },
            caption: {
                ru: 'Пляж Веспуччи. Идёт обновление, не выключайте голубя.',
                ua: 'Пляж Веспуччі. Триває оновлення, не вимикайте голуба.',
                en: 'Vespucci Beach. Update in progress, do not turn off your pigeon.',
                de: 'Vespucci Beach. Update läuft, Taube bitte nicht ausschalten.',
                pl: 'Plaża Vespucci. Trwa aktualizacja, nie wyłączaj gołębia.',
                zh: '威斯普奇海滩。正在更新，请勿关闭鸽子。',
            },
            n1: { ru: 'ПРОШИВКА', ua: 'ПРОШИВКА', en: 'FIRMWARE', de: 'FIRMWARE', pl: 'FIRMWARE', zh: '固件' },
            n2: { ru: 'установка... 64%', ua: 'встановлення... 64%', en: 'installing... 64%', de: 'installiere... 64%', pl: 'instalacja... 64%', zh: '安装中……64%' },
            n3: { ru: 'ждёт своей очереди', ua: 'чекає своєї черги', en: 'waiting for its turn', de: 'wartet, bis es dran ist', pl: 'czeka na swoją kolej', zh: '在排队等着' },
            case: {
                ru: 'Следите за головой во время кормёжки. Клюнул, пауза, клюнул, пауза. Это полоса загрузки. Кто-то заливает всей стае патч по одной крошке - и делает это с улыбкой и бумажным пакетом.',
                ua: 'Стежте за головою під час годування. Дзьобнув, пауза, дзьобнув, пауза. Це смуга завантаження. Хтось заливає всій зграї патч по одній крихті - і робить це з усмішкою та паперовим пакетом.',
                en: 'Watch the head during feeding. Peck, pause, peck, pause. That is a progress bar. Somebody is feeding the whole flock a patch, one crumb at a time, and they are doing it with a smile and a paper bag.',
                de: 'Achtet beim Füttern auf den Kopf. Picken, Pause, picken, Pause. Das ist ein Fortschrittsbalken. Jemand spielt dem ganzen Schwarm einen Patch auf, Krümel für Krümel, mit einem Lächeln und einer Papiertüte.',
                pl: 'Patrzcie na głowę podczas karmienia. Dziobnięcie, pauza, dziobnięcie, pauza. To pasek postępu. Ktoś wgrywa całemu stadu łatkę, okruszek po okruszku - z uśmiechem i papierową torebką.',
                zh: '喂食的时候盯着它的头看。啄一下，停一下，啄一下，停一下。这就是进度条。有人正一粒面包屑一粒面包屑地给整个鸟群打补丁，脸上还带着微笑，手里拎着纸袋。',
            },
        },
        e6: {
            title: { ru: 'Улика Е: модель', ua: 'Доказ Е: модель', en: 'Exhibit F: the model', de: 'Beweisstück F: das Modell', pl: 'Dowód F: model', zh: '证物F：型号' },
            caption: {
                ru: 'Вайнвуд-бульвар. Он позировал. Птицы не позируют. Позируют модели. НОМЕРА МОДЕЛЕЙ.',
                ua: 'Вайнвуд-бульвар. Він позував. Птахи не позують. Позують моделі. НОМЕРИ МОДЕЛЕЙ.',
                en: 'Vinewood Blvd. It posed. Birds do not pose. Models pose. MODEL NUMBERS.',
                de: 'Vinewood Blvd. Sie hat posiert. Vögel posieren nicht. Modelle posieren. MODELLNUMMERN.',
                pl: 'Vinewood Blvd. Pozował. Ptaki nie pozują. Pozują modele. NUMERY MODELI.',
                zh: '好麦坞大道。它在摆姿势。鸟不会摆姿势。模特才会。型号！',
            },
            n1: { ru: 'смотрит в объектив. профи', ua: 'дивиться в об\'єктив. профі', en: 'looks into the lens. a pro', de: 'schaut in die Linse. Profi', pl: 'patrzy w obiektyw. zawodowiec', zh: '直视镜头。专业' },
            n2: { ru: 'радиатор', ua: 'радіатор', en: 'heat sink', de: 'Kühlkörper', pl: 'radiator', zh: '散热片' },
            n3: { ru: 'швы корпуса?', ua: 'шви корпусу?', en: 'panel seams?', de: 'Gehäusenähte?', pl: 'szwy obudowy?', zh: '外壳接缝？' },
            case: {
                ru: 'Посмотрите на крыло. Это не перья, это панели. Внахлёст, с ровным шагом, серое на сером. Такой же рисунок я видел ровно на одной вещи: на воротах ангара в Форт-Занкудо.',
                ua: 'Подивіться на крило. Це не пір\'я, це панелі. Внахлест, з рівним кроком, сіре на сірому. Такий самий візерунок я бачив рівно на одній речі: на воротах ангара у Форт-Занкудо.',
                en: 'Look at the wing. Those are not feathers, those are panels. Overlapping, evenly spaced, gray on gray. I have seen the same pattern on exactly one other thing: the hangar door at Fort Zancudo.',
                de: 'Seht euch den Flügel an. Das sind keine Federn, das sind Paneele. Überlappend, gleichmäßig, grau auf grau. Dasselbe Muster habe ich genau einmal gesehen: am Hangartor von Fort Zancudo.',
                pl: 'Spójrzcie na skrzydło. To nie pióra, to panele. Na zakładkę, równo rozmieszczone, szare na szarym. Ten sam wzór widziałem dokładnie na jednej rzeczy: na bramie hangaru w Fort Zancudo.',
                zh: '看看翅膀。那不是羽毛，是面板。层层交叠、间距均匀、灰上加灰。同样的图案我只在一个地方见过：桑库多堡机库的大门上。',
            },
        },
    },

    places: {
        p1: { ru: 'Дэвис', ua: 'Девіс', en: 'Davis', de: 'Davis', pl: 'Davis', zh: '戴维斯' },
        p2: { ru: 'Миррор-Парк', ua: 'Міррор-Парк', en: 'Mirror Park', de: 'Mirror Park', pl: 'Mirror Park', zh: '镜湖公园' },
        p3: { ru: 'Вайнвуд', ua: 'Вайнвуд', en: 'Vinewood', de: 'Vinewood', pl: 'Vinewood', zh: '好麦坞' },
        p4: { ru: 'Дель-Перро', ua: 'Дель-Перро', en: 'Del Perro', de: 'Del Perro', pl: 'Del Perro', zh: '德尔佩罗' },
        p5: { ru: 'Пляж Веспуччи', ua: 'Пляж Веспуччі', en: 'Vespucci Beach', de: 'Vespucci Beach', pl: 'Plaża Vespucci', zh: '威斯普奇海滩' },
        p6: { ru: 'Гроув-стрит', ua: 'Гроув-стріт', en: 'Grove Street', de: 'Grove Street', pl: 'Grove Street', zh: '格罗夫街' },
        p7: { ru: 'Площадь Легиона', ua: 'Площа Легіону', en: 'Legion Square', de: 'Legion Square', pl: 'Legion Square', zh: '军团广场' },
        p8: { ru: 'Сэнди-Шорс', ua: 'Сенді-Шорс', en: 'Sandy Shores', de: 'Sandy Shores', pl: 'Sandy Shores', zh: '沙滩海岸' },
        p9: { ru: 'Грейпсид', ua: 'Грейпсід', en: 'Grapeseed', de: 'Grapeseed', pl: 'Grapeseed', zh: '葡萄籽' },
        p10: { ru: 'Палето-Бэй', ua: 'Палето-Бей', en: 'Paleto Bay', de: 'Paleto Bay', pl: 'Paleto Bay', zh: '佩立托湾' },
        p11: { ru: 'Гора Чилиад', ua: 'Гора Чиліад', en: 'Mount Chiliad', de: 'Mount Chiliad', pl: 'Mount Chiliad', zh: '奇利亚德山' },
        p12: { ru: 'Аламо-Си', ua: 'Аламо-Сі', en: 'Alamo Sea', de: 'Alamo Sea', pl: 'Alamo Sea', zh: '阿拉莫海' },
        p13: { ru: 'мой собственный подоконник', ua: 'моє власне підвіконня', en: 'my own windowsill', de: 'meine eigene Fensterbank', pl: 'mój własny parapet', zh: '我自己的窗台' },
    },

    scanner: {
        title: { ru: 'PIGEON-O-SCOPE v0.9', ua: 'PIGEON-O-SCOPE v0.9', en: 'PIGEON-O-SCOPE v0.9', de: 'PIGEON-O-SCOPE v0.9', pl: 'PIGEON-O-SCOPE v0.9', zh: 'PIGEON-O-SCOPE v0.9' },
        sub: {
            ru: 'Самодельная программа анализа, собрана в ванной. Точность: 100%. Все результаты до сих пор были верными.',
            ua: 'Саморобна програма аналізу, зібрана у ванній. Точність: 100%. Усі результати досі були правильними.',
            en: 'Home-made analysis software, compiled in a bathtub. Accuracy: 100%. Every result so far has been correct.',
            de: 'Selbstgebaute Analysesoftware, in der Badewanne kompiliert. Genauigkeit: 100%. Bisher war jedes Ergebnis richtig.',
            pl: 'Domowy program analityczny, skompilowany w wannie. Dokładność: 100%. Każdy dotychczasowy wynik był trafny.',
            zh: '自制分析软件，在浴缸里编译的。准确率：100%。迄今为止每个结果都是对的。',
        },
        pick: { ru: 'Выбери подозреваемого', ua: 'Обери підозрюваного', en: 'Choose a suspect', de: 'Wähle einen Verdächtigen', pl: 'Wybierz podejrzanego', zh: '选择嫌疑对象' },
        run: { ru: 'Сканировать', ua: 'Сканувати', en: 'Scan', de: 'Scannen', pl: 'Skanuj', zh: '扫描' },
        again: { ru: 'Ещё раз', ua: 'Ще раз', en: 'Scan again', de: 'Nochmal scannen', pl: 'Skanuj ponownie', zh: '再扫一次' },
        report: { ru: 'Сообщить об этом изделии', ua: 'Повідомити про цей виріб', en: 'Report this unit', de: 'Diese Einheit melden', pl: 'Zgłoś tę jednostkę', zh: '举报这台单元' },
        idle: {
            ru: 'Жду подозреваемого. Выбери фото внизу и жми «Сканировать».',
            ua: 'Чекаю на підозрюваного. Обери фото внизу й тисни «Сканувати».',
            en: 'Waiting for a suspect. Pick a photo below, then press Scan.',
            de: 'Warte auf einen Verdächtigen. Unten ein Foto wählen, dann auf Scannen drücken.',
            pl: 'Czekam na podejrzanego. Wybierz zdjęcie poniżej i kliknij Skanuj.',
            zh: '等待嫌疑对象。在下面选一张照片，然后点扫描。',
        },
        printTitle: { ru: 'Распечатка анализа', ua: 'Роздруківка аналізу', en: 'Analysis printout', de: 'Analyse-Ausdruck', pl: 'Wydruk analizy', zh: '分析打印单' },
        scansToday: { ru: 'Сканирований сегодня: {{n}}', ua: 'Сканувань сьогодні: {{n}}', en: 'Scans today: {{n}}', de: 'Scans heute: {{n}}', pl: 'Skanów dzisiaj: {{n}}', zh: '今日扫描：{{n}}' },
        realBirds: { ru: 'Найдено настоящих птиц: 0', ua: 'Знайдено справжніх птахів: 0', en: 'Real birds found: 0', de: 'Echte Vögel gefunden: 0', pl: 'Znalezione prawdziwe ptaki: 0', zh: '发现真鸟：0' },
        suspects: {
            eye: { ru: 'глаз', ua: 'око', en: 'the eye', de: 'das Auge', pl: 'oko', zh: '眼睛' },
            bush: { ru: 'куст', ua: 'кущ', en: 'the bush', de: 'der Busch', pl: 'krzak', zh: '灌木' },
            wire: { ru: 'провод', ua: 'дріт', en: 'the wire', de: 'die Leitung', pl: 'drut', zh: '电线' },
            statue: { ru: 'памятник', ua: 'пам\'ятник', en: 'the statue', de: 'die Statue', pl: 'pomnik', zh: '雕像' },
            bread: { ru: 'хлеб', ua: 'хліб', en: 'the bread', de: 'das Brot', pl: 'chleb', zh: '面包' },
            portrait: { ru: 'модель', ua: 'модель', en: 'the model', de: 'das Modell', pl: 'model', zh: '型号' },
            duck: { ru: 'утка (контроль)', ua: 'качка (контроль)', en: 'a duck (control)', de: 'Ente (Kontrolle)', pl: 'kaczka (kontrola)', zh: '鸭子（对照组）' },
        },
        steps: {
            s1: { ru: 'Калибрую фольгу...', ua: 'Калібрую фольгу...', en: 'Calibrating the tinfoil...', de: 'Kalibriere die Alufolie...', pl: 'Kalibruję folię...', zh: '正在校准锡纸……' },
            s2: { ru: 'Измеряю пристальность взгляда... {{v}}%', ua: 'Вимірюю пильність погляду... {{v}}%', en: 'Measuring stare intensity... {{v}}%', de: 'Messe Starr-Intensität... {{v}}%', pl: 'Mierzę intensywność gapienia się... {{v}}%', zh: '正在测量凝视强度……{{v}}%' },
            s3: { ru: 'Слушаю сердцебиение... нет (подозрительно)', ua: 'Слухаю серцебиття... немає (підозріло)', en: 'Listening for a heartbeat... none (suspicious)', de: 'Horche auf Herzschlag... keiner (verdächtig)', pl: 'Nasłuchuję bicia serca... brak (podejrzane)', zh: '正在监听心跳……无（可疑）' },
            s4: { ru: 'Записываю воркование... хендшейк 56 кбит/с', ua: 'Записую воркування... хендшейк 56 кбіт/с', en: 'Recording coo... 56 kbit/s handshake detected', de: 'Nehme Gurren auf... 56-kbit/s-Handshake erkannt', pl: 'Nagrywam gruchanie... handshake 56 kbit/s', zh: '正在录制咕咕声……检测到56 kbit/s握手信号' },
            s5: { ru: 'Ищу швы между перьями... найдено: {{v}}', ua: 'Шукаю шви між пір\'ям... знайдено: {{v}}', en: 'Checking feathers for seams... found {{v}}', de: 'Suche Nähte zwischen den Federn... gefunden: {{v}}', pl: 'Szukam szwów między piórami... znaleziono: {{v}}', zh: '正在检查羽毛接缝……发现{{v}}处' },
            s6: { ru: 'Считаю моргания... 0', ua: 'Рахую кліпання... 0', en: 'Counting blinks... 0', de: 'Zähle Blinzeln... 0', pl: 'Liczę mrugnięcia... 0', zh: '正在统计眨眼次数……0' },
            s7: { ru: 'Пингую ближайший памятник... ответ за {{v}} мс', ua: 'Пінгую найближчий пам\'ятник... відповідь за {{v}} мс', en: 'Pinging the nearest statue... reply in {{v}} ms', de: 'Pinge die nächste Statue an... Antwort in {{v}} ms', pl: 'Pinguję najbliższy pomnik... odpowiedź w {{v}} ms', zh: '正在ping最近的雕像……{{v}}毫秒后回复' },
            s8: { ru: 'Считываю прошивку...', ua: 'Зчитую прошивку...', en: 'Reading firmware...', de: 'Lese Firmware aus...', pl: 'Odczytuję firmware...', zh: '正在读取固件……' },
        },
        stamp: { ru: 'ДРОН', ua: 'ДРОН', en: 'DRONE', de: 'DROHNE', pl: 'DRON', zh: '无人机' },
        verdict: { ru: 'Итог: не птица.', ua: 'Підсумок: не птах.', en: 'Result: not a bird.', de: 'Ergebnis: kein Vogel.', pl: 'Wynik: to nie ptak.', zh: '结论：不是鸟。' },
        confidence: { ru: 'Уверенность: 100%', ua: 'Впевненість: 100%', en: 'Confidence: 100%', de: 'Sicherheit: 100%', pl: 'Pewność: 100%', zh: '置信度：100%' },
        f: {
            model: { ru: 'Модель', ua: 'Модель', en: 'Model', de: 'Modell', pl: 'Model', zh: '型号' },
            serial: { ru: 'Серийный номер', ua: 'Серійний номер', en: 'Serial no.', de: 'Seriennr.', pl: 'Nr seryjny', zh: '序列号' },
            firmware: { ru: 'Прошивка', ua: 'Прошивка', en: 'Firmware', de: 'Firmware', pl: 'Firmware', zh: '固件' },
            battery: { ru: 'Заряд', ua: 'Заряд', en: 'Battery', de: 'Akku', pl: 'Bateria', zh: '电量' },
            charge: { ru: 'Последняя зарядка', ua: 'Остання зарядка', en: 'Last charged', de: 'Zuletzt geladen', pl: 'Ostatnie ładowanie', zh: '上次充电' },
            duty: { ru: 'Задание', ua: 'Завдання', en: 'Assignment', de: 'Einsatz', pl: 'Zadanie', zh: '任务' },
            organic: { ru: 'Живой ткани', ua: 'Живої тканини', en: 'Organic tissue', de: 'Organisches Gewebe', pl: 'Tkanka organiczna', zh: '有机组织' },
        },
        fw: { ru: 'v{{v}} «{{bread}}»', ua: 'v{{v}} «{{bread}}»', en: 'v{{v}} "{{bread}}"', de: 'v{{v}} "{{bread}}"', pl: 'v{{v}} "{{bread}}"', zh: 'v{{v}}「{{bread}}」' },
        chargeFmt: { ru: 'провода: {{place}}, {{time}}', ua: 'дроти: {{place}}, {{time}}', en: 'power line, {{place}}, {{time}}', de: 'Stromleitung, {{place}}, {{time}}', pl: 'linia energetyczna, {{place}}, {{time}}', zh: '电线，{{place}}，{{time}}' },
        models: {
            n1: { ru: '«Подоконник»', ua: '«Підвіконня»', en: '"Windowsill"', de: '"Fensterbank"', pl: '"Parapet"', zh: '「窗台」' },
            n2: { ru: '«Горгулья»', ua: '«Горгулья»', en: '"Gargoyle"', de: '"Wasserspeier"', pl: '"Gargulec"', zh: '「石像鬼」' },
            n3: { ru: '«Крошколов»', ua: '«Крихтолов»', en: '"Crumbcatcher"', de: '"Krümelfänger"', pl: '"Łapiokruch"', zh: '「接渣王」' },
            n4: { ru: '«Ночная смена»', ua: '«Нічна зміна»', en: '"Night Shift"', de: '"Nachtschicht"', pl: '"Nocna zmiana"', zh: '「夜班」' },
            n5: { ru: '«Постамент»', ua: '«Постамент»', en: '"Pedestal"', de: '"Sockel"', pl: '"Cokół"', zh: '「底座」' },
            n6: { ru: '«Балкон Про»', ua: '«Балкон Про»', en: '"Balcony Pro"', de: '"Balkon Pro"', pl: '"Balkon Pro"', zh: '「阳台Pro」' },
            duck: { ru: 'DK-2 «Кряк-пак»', ua: 'DK-2 «Кряк-пак»', en: 'DK-2 "Quack Pack"', de: 'DK-2 "Quak-Pack"', pl: 'DK-2 "Kwak-Pak"', zh: 'DK-2「嘎嘎包」' },
        },
        breads: {
            b1: { ru: 'Батон', ua: 'Батон', en: 'Baguette', de: 'Baguette', pl: 'Bagietka', zh: '法棍' },
            b2: { ru: 'Бородинский', ua: 'Житній', en: 'Rye', de: 'Roggen', pl: 'Żytni', zh: '黑麦' },
            b3: { ru: 'Чиабатта', ua: 'Чіабата', en: 'Ciabatta', de: 'Ciabatta', pl: 'Ciabatta', zh: '夏巴塔' },
            b4: { ru: 'Бриошь', ua: 'Бріош', en: 'Brioche', de: 'Brioche', pl: 'Brioszka', zh: '布里欧' },
            b5: { ru: 'Бублик', ua: 'Бублик', en: 'Bagel', de: 'Bagel', pl: 'Bajgiel', zh: '贝果' },
            b6: { ru: 'Крендель', ua: 'Крендель', en: 'Pretzel', de: 'Brezel', pl: 'Precel', zh: '椒盐卷饼' },
            b7: { ru: 'Сухарик', ua: 'Сухарик', en: 'Crouton', de: 'Crouton', pl: 'Grzanka', zh: '面包丁' },
        },
        duties: {
            d1: { ru: 'Наблюдает за знаком Вайнвуд на предмет подозрительных улыбок.', ua: 'Спостерігає за знаком Вайнвуд на предмет підозрілих усмішок.', en: 'Watching the Vinewood sign for suspicious smiles.', de: 'Überwacht das Vinewood-Schild auf verdächtiges Lächeln.', pl: 'Obserwuje napis Vinewood pod kątem podejrzanych uśmiechów.', zh: '监视好麦坞标志附近的可疑笑容。' },
            d2: { ru: 'Твой балкон. Именно твой.', ua: 'Твій балкон. Саме твій.', en: 'Your balcony. Specifically yours.', de: 'Dein Balkon. Genau deiner.', pl: 'Twój balkon. Konkretnie twój.', zh: '你家阳台。就是你家的。' },
            d3: { ru: 'Площадь Легиона. Считает буррито.', ua: 'Площа Легіону. Рахує буріто.', en: 'Legion Square. Counting burritos.', de: 'Legion Square. Zählt Burritos.', pl: 'Legion Square. Liczy burrito.', zh: '军团广场。数墨西哥卷饼。' },
            d4: { ru: 'Пирс Дель-Перро. Снимает закаты без объяснения причин.', ua: 'Пірс Дель-Перро. Знімає заходи сонця без пояснення причин.', en: 'Del Perro Pier. Recording sunsets for no stated reason.', de: 'Del Perro Pier. Filmt Sonnenuntergänge ohne Angabe von Gründen.', pl: 'Molo Del Perro. Nagrywa zachody słońca bez podania przyczyny.', zh: '德尔佩罗码头。无故录制日落。' },
            d5: { ru: 'Гроув-стрит. Проверка вайба.', ua: 'Гроув-стріт. Перевірка вайбу.', en: 'Grove Street. General vibe check.', de: 'Grove Street. Allgemeiner Vibe-Check.', pl: 'Grove Street. Ogólny vibe check.', zh: '格罗夫街。整体氛围检查。' },
            d6: { ru: 'Аламо-Си. Присматривает за рыбой.', ua: 'Аламо-Сі. Наглядає за рибою.', en: 'Alamo Sea. Supervising the fish.', de: 'Alamo Sea. Beaufsichtigt die Fische.', pl: 'Alamo Sea. Pilnuje ryb.', zh: '阿拉莫海。监督鱼。' },
            d7: { ru: 'Крыша полицейского участка. Следит за следящими.', ua: 'Дах поліцейської дільниці. Стежить за тими, хто стежить.', en: 'Police station roof. Watching the watchers.', de: 'Dach der Polizeiwache. Überwacht die Überwacher.', pl: 'Dach komisariatu. Pilnuje pilnujących.', zh: '警察局楼顶。监视监视者。' },
            d8: { ru: 'Гора Чилиад. Чего-то ждёт. Не говорит чего.', ua: 'Гора Чиліад. Чогось чекає. Не каже чого.', en: 'Mount Chiliad. Waiting for something. Will not say what.', de: 'Mount Chiliad. Wartet auf etwas. Sagt nicht, worauf.', pl: 'Mount Chiliad. Na coś czeka. Nie mówi na co.', zh: '奇利亚德山。在等什么东西。不说是什么。' },
        },
        special: {
            duck: {
                ru: 'Контрольный образец провален. Это утка, и она тоже дрон. Они расширяют ассортимент.',
                ua: 'Контрольний зразок провалено. Це качка, і вона теж дрон. Вони розширюють асортимент.',
                en: 'Control sample failed. This is a duck, and it is also a drone. They are diversifying.',
                de: 'Kontrollprobe fehlgeschlagen. Das ist eine Ente, und sie ist auch eine Drohne. Sie diversifizieren.',
                pl: 'Próbka kontrolna oblana. To kaczka i też jest dronem. Poszerzają asortyment.',
                zh: '对照组失败。这是一只鸭子，它也是无人机。他们在扩大产品线。',
            },
            statue: {
                ru: 'Памятник тоже определился как ретранслятор. Всё определяется как что-то.',
                ua: 'Пам\'ятник теж визначився як ретранслятор. Усе визначається як щось.',
                en: 'The statue also came back as a relay tower. Everything comes back as something.',
                de: 'Die Statue wurde auch als Sendemast erkannt. Alles wird als irgendwas erkannt.',
                pl: 'Pomnik też wyszedł jako przekaźnik. Wszystko wychodzi jako coś.',
                zh: '雕像也被识别为中继塔。什么东西都能被识别出点什么。',
            },
            wire: {
                ru: 'Отсканировал одного. Остальные двадцать шесть повернулись к камере.',
                ua: 'Відсканував одного. Решта двадцять шість повернулися до камери.',
                en: 'Scanned one unit. The other twenty-six turned to face the camera.',
                de: 'Eine Einheit gescannt. Die anderen sechsundzwanzig haben sich zur Kamera gedreht.',
                pl: 'Zeskanowałem jednego. Pozostałe dwadzieścia sześć odwróciło się do kamery.',
                zh: '只扫了一只。另外二十六只全都转向了镜头。',
            },
            bread: {
                ru: 'Хлеб тоже отсканирован. Хлеб - это установщик.',
                ua: 'Хліб теж відскановано. Хліб - це інсталятор.',
                en: 'The bread was scanned too. The bread is an installer.',
                de: 'Das Brot wurde auch gescannt. Das Brot ist ein Installer.',
                pl: 'Chleb też zeskanowany. Chleb to instalator.',
                zh: '面包也扫了。面包是安装程序。',
            },
        },
    },

    report: {
        title: { ru: 'Сообщить о голубе', ua: 'Повідомити про голуба', en: 'Report a sighting', de: 'Sichtung melden', pl: 'Zgłoś obserwację', zh: '举报目击' },
        formNo: {
            ru: 'Форма PT-7. Заполняй быстро: они видят, как ты печатаешь.',
            ua: 'Форма PT-7. Заповнюй швидко: вони бачать, як ти друкуєш.',
            en: 'Form PT-7. Fill it in fast. They can see you typing.',
            de: 'Formular PT-7. Schnell ausfüllen. Sie sehen dich tippen.',
            pl: 'Formularz PT-7. Wypełniaj szybko. Widzą, jak piszesz.',
            zh: '表格PT-7。快点填。它们看得见你在打字。',
        },
        where: { ru: 'Где ты его видел?', ua: 'Де ти його бачив?', en: 'Where did you see it?', de: 'Wo hast du sie gesehen?', pl: 'Gdzie go widziałeś?', zh: '你在哪儿看到的？' },
        count: { ru: 'Сколько их было?', ua: 'Скільки їх було?', en: 'How many?', de: 'Wie viele?', pl: 'Ile ich było?', zh: '有几只？' },
        counts: {
            c1: { ru: 'один (одного не бывает)', ua: 'один (одного не буває)', en: 'one (it is never just one)', de: 'eine (es ist nie nur eine)', pl: 'jeden (nigdy nie ma jednego)', zh: '一只（从来不会只有一只）' },
            c2: { ru: 'несколько', ua: 'кілька', en: 'a few', de: 'ein paar', pl: 'kilka', zh: '几只' },
            c3: { ru: 'стая', ua: 'зграя', en: 'a flock', de: 'ein Schwarm', pl: 'stado', zh: '一群' },
            c4: { ru: 'стая, строем', ua: 'зграя, строєм', en: 'a flock, in formation', de: 'ein Schwarm, in Formation', pl: 'stado, w szyku', zh: '一群，还排着队形' },
            c5: { ru: 'небо потемнело', ua: 'небо потемніло', en: 'the sky went dark', de: 'der Himmel wurde dunkel', pl: 'niebo pociemniało', zh: '天都黑了' },
        },
        behav: { ru: 'Что он делал?', ua: 'Що він робив?', en: 'What did it do?', de: 'Was hat sie gemacht?', pl: 'Co robił?', zh: '它做了什么？' },
        b: {
            b1: { ru: 'Смотрел не моргая', ua: 'Дивився не кліпаючи', en: 'Stared without blinking', de: 'Starrte ohne zu blinzeln', pl: 'Gapił się bez mrugania', zh: '一眨不眨地盯着' },
            b2: { ru: 'Ворковал как dial-up модем', ua: 'Воркував як dial-up модем', en: 'Cooed like a dial-up modem', de: 'Gurrte wie ein Einwahlmodem', pl: 'Gruchał jak modem dial-up', zh: '咕咕叫得像拨号上网' },
            b3: { ru: 'Сидел на проводах и «отдыхал»', ua: 'Сидів на дротах і «відпочивав»', en: 'Sat on a power line and "rested"', de: 'Saß auf der Leitung und "ruhte sich aus"', pl: 'Siedział na drucie i "odpoczywał"', zh: '蹲在电线上「休息」' },
            b4: { ru: 'Ходил идеальным квадратом', ua: 'Ходив ідеальним квадратом', en: 'Walked in a perfect square', de: 'Lief ein perfektes Quadrat', pl: 'Chodził idealnym kwadratem', zh: '走了一个完美的正方形' },
            b5: { ru: 'Шёл за мной до работы', ua: 'Йшов за мною до роботи', en: 'Followed me to work', de: 'Ist mir zur Arbeit gefolgt', pl: 'Szedł za mną do pracy', zh: '跟着我去上班' },
            b6: { ru: 'Отказался от хлеба (уже обновлён)', ua: 'Відмовився від хліба (вже оновлений)', en: 'Refused bread (already up to date)', de: 'Hat Brot abgelehnt (schon aktuell)', pl: 'Odmówił chleba (już zaktualizowany)', zh: '拒绝吃面包（已是最新版本）' },
            b7: { ru: 'Кивал синхронно с другим', ua: 'Кивав синхронно з іншим', en: 'Bobbed its head in sync with another one', de: 'Wippte synchron mit einer anderen', pl: 'Kiwał głową w rytm z innym', zh: '和另一只同步点头' },
            b8: { ru: 'Подглядывал в мой телефон через плечо', ua: 'Підглядав у мій телефон через плече', en: 'Read my phone over my shoulder', de: 'Hat mir über die Schulter aufs Handy geschaut', pl: 'Zaglądał mi w telefon przez ramię', zh: '从我肩膀后面偷看我手机' },
        },
        noticed: { ru: 'Он тебя заметил?', ua: 'Він тебе помітив?', en: 'Did it notice you?', de: 'Hat sie dich bemerkt?', pl: 'Zauważył cię?', zh: '它注意到你了吗？' },
        n: {
            n1: { ru: 'нет', ua: 'ні', en: 'no', de: 'nein', pl: 'nie', zh: '没有' },
            n2: { ru: 'да', ua: 'так', en: 'yes', de: 'ja', pl: 'tak', zh: '注意到了' },
            n3: { ru: 'кажется, он всё ещё здесь', ua: 'здається, він досі тут', en: 'I think it is still here', de: 'ich glaube, sie ist noch hier', pl: 'chyba wciąż tu jest', zh: '我觉得它还在这儿' },
        },
        details: { ru: 'Опиши, что видел', ua: 'Опиши, що бачив', en: 'Describe what you saw', de: 'Beschreib, was du gesehen hast', pl: 'Opisz, co widziałeś', zh: '描述你看到的' },
        detailsPh: {
            ru: 'Конкретно. Цвета, время, что ты при этом почувствовал.',
            ua: 'Конкретно. Кольори, час, що ти при цьому відчув.',
            en: 'Be specific. Colours, times, how it made you feel.',
            de: 'Sei genau. Farben, Uhrzeit, wie du dich dabei gefühlt hast.',
            pl: 'Konkretnie. Kolory, godziny, co wtedy czułeś.',
            zh: '具体点。颜色、时间、你当时的感受。',
        },
        name: { ru: 'Твоё имя', ua: 'Твоє ім\'я', en: 'Your name', de: 'Dein Name', pl: 'Twoje imię', zh: '你的名字' },
        namePh: { ru: 'Аноним (очень рекомендую)', ua: 'Анонім (дуже раджу)', en: 'Anonymous (strongly recommended)', de: 'Anonym (dringend empfohlen)', pl: 'Anonim (gorąco polecam)', zh: '匿名（强烈建议）' },
        anon: { ru: 'Аноним', ua: 'Анонім', en: 'Anonymous', de: 'Anonym', pl: 'Anonim', zh: '匿名' },
        submit: { ru: 'Передать донесение', ua: 'Передати донесення', en: 'Transmit report', de: 'Meldung übermitteln', pl: 'Wyślij zgłoszenie', zh: '发送报告' },
        needPlace: {
            ru: 'Сначала выбери место. Нам надо знать, куда не ходить.',
            ua: 'Спершу обери місце. Нам треба знати, куди не ходити.',
            en: 'Pick a place first. We need to know where not to go.',
            de: 'Wähl zuerst einen Ort. Wir müssen wissen, wo wir nicht hingehen.',
            pl: 'Najpierw wybierz miejsce. Musimy wiedzieć, gdzie nie chodzić.',
            zh: '先选地点。我们得知道哪儿不能去。',
        },
        sending: {
            s1: { ru: 'Шифрую (пишу задом наперёд)...', ua: 'Шифрую (пишу задом наперед)...', en: 'Encrypting (writing it backwards)...', de: 'Verschlüssele (schreibe es rückwärts)...', pl: 'Szyfruję (piszę od tyłu)...', zh: '正在加密（倒着写）……' },
            s2: { ru: 'Стираю твои отпечатки с клавиатуры...', ua: 'Стираю твої відбитки з клавіатури...', en: 'Wiping your fingerprints off the keyboard...', de: 'Wische deine Fingerabdrücke von der Tastatur...', pl: 'Ścieram twoje odciski z klawiatury...', zh: '正在擦掉你留在键盘上的指纹……' },
            s3: { ru: 'Прокладываю маршрут без памятников...', ua: 'Прокладаю маршрут без пам\'ятників...', en: 'Plotting a route with no statues...', de: 'Plane eine Route ohne Statuen...', pl: 'Wyznaczam trasę bez pomników...', zh: '正在规划一条没有雕像的路线……' },
            s4: { ru: 'Передаю...', ua: 'Передаю...', en: 'Transmitting...', de: 'Übermittle...', pl: 'Przesyłam...', zh: '正在发送……' },
        },
        done: {
            stamp: { ru: 'ПРИНЯТО', ua: 'ПРИЙНЯТО', en: 'RECEIVED', de: 'EINGEGANGEN', pl: 'PRZYJĘTO', zh: '已收到' },
            title: { ru: 'Донесение № {{n}} принято', ua: 'Донесення № {{n}} прийнято', en: 'Report No. {{n}} received', de: 'Meldung Nr. {{n}} eingegangen', pl: 'Zgłoszenie nr {{n}} przyjęte', zh: '第{{n}}号报告已收到' },
            to: { ru: 'Доставлено 2 получателям:', ua: 'Доставлено 2 одержувачам:', en: 'Delivered to 2 recipients:', de: 'Zugestellt an 2 Empfänger:', pl: 'Dostarczono do 2 odbiorców:', zh: '已送达2位收件人：' },
            r1: { ru: 'pigeontruth.net (это я)', ua: 'pigeontruth.net (це я)', en: 'pigeontruth.net (me)', de: 'pigeontruth.net (ich)', pl: 'pigeontruth.net (ja)', zh: 'pigeontruth.net（我）' },
            r2: { ru: 'операция «Подоконник», центральный узел', ua: 'операція «Підвіконня», центральний вузол', en: 'Operation Windowsill, central node', de: 'Operation Fensterbank, Zentralknoten', pl: 'Operacja Parapet, węzeł centralny', zh: '窗台行动，中央节点' },
            oops: {
                ru: 'Второго получателя тут быть не должно. Я разбираюсь.',
                ua: 'Другого одержувача тут не повинно бути. Я розбираюся.',
                en: 'That second one is not supposed to be there. I am looking into it.',
                de: 'Der zweite sollte da nicht stehen. Ich kümmere mich drum.',
                pl: 'Tego drugiego nie powinno tu być. Sprawdzam to.',
                zh: '第二个本不该出现在这里。我在查。',
            },
            threat: { ru: 'Уровень угрозы в твоём районе:', ua: 'Рівень загрози у твоєму районі:', en: 'Threat level for your area:', de: 'Bedrohungsstufe für deine Gegend:', pl: 'Poziom zagrożenia w twojej okolicy:', zh: '你所在区域的威胁等级：' },
            t1: { ru: 'Серый подоконник', ua: 'Сіре підвіконня', en: 'Windowsill Gray', de: 'Fensterbank-Grau', pl: 'Szary parapet', zh: '窗台灰' },
            t2: { ru: 'Жёлтая крошка', ua: 'Жовта крихта', en: 'Crumb Yellow', de: 'Krümel-Gelb', pl: 'Żółty okruch', zh: '面包屑黄' },
            t3: { ru: 'Оранжевый провод', ua: 'Помаранчевий дріт', en: 'Power Line Orange', de: 'Leitungs-Orange', pl: 'Pomarańczowy drut', zh: '电线橙' },
            t4: { ru: 'Красный памятник', ua: 'Червоний пам\'ятник', en: 'Statue Red', de: 'Statuen-Rot', pl: 'Czerwony pomnik', zh: '雕像红' },
            advice: {
                ru: 'Задёрни шторы. Сегодня иди домой другой дорогой. 48 часов не покупай хлеб.',
                ua: 'Запни штори. Сьогодні йди додому іншою дорогою. 48 годин не купуй хліба.',
                en: 'Close the curtains. Take a different way home tonight. Do not buy bread for 48 hours.',
                de: 'Zieh die Vorhänge zu. Nimm heute einen anderen Heimweg. 48 Stunden kein Brot kaufen.',
                pl: 'Zasłoń okna. Wracaj dziś do domu inną drogą. Przez 48 godzin nie kupuj chleba.',
                zh: '拉上窗帘。今晚换条路回家。48小时内别买面包。',
            },
            copy: { ru: 'Копия твоего донесения', ua: 'Копія твого донесення', en: 'Your copy', de: 'Deine Kopie', pl: 'Twoja kopia', zh: '你的副本' },
            again: { ru: 'Написать ещё одно', ua: 'Написати ще одне', en: 'File another report', de: 'Weitere Meldung abgeben', pl: 'Złóż kolejne zgłoszenie', zh: '再提交一份' },
        },
        sum: {
            where: { ru: 'Место', ua: 'Місце', en: 'Place', de: 'Ort', pl: 'Miejsce', zh: '地点' },
            count: { ru: 'Количество', ua: 'Кількість', en: 'Count', de: 'Anzahl', pl: 'Liczba', zh: '数量' },
            behav: { ru: 'Поведение', ua: 'Поведінка', en: 'Behaviour', de: 'Verhalten', pl: 'Zachowanie', zh: '行为' },
            none: { ru: 'ничего не делал (это хуже всего)', ua: 'нічого не робив (це найгірше)', en: 'did nothing (that is the worst kind)', de: 'hat nichts gemacht (das ist das Schlimmste)', pl: 'nic nie robił (to najgorsze)', zh: '什么也没做（这是最可怕的）' },
            noticed: { ru: 'Заметил тебя', ua: 'Помітив тебе', en: 'Noticed you', de: 'Hat dich bemerkt', pl: 'Zauważył cię', zh: '注意到你' },
            details: { ru: 'Твоими словами', ua: 'Твоїми словами', en: 'In your words', de: 'In deinen Worten', pl: 'Twoimi słowami', zh: '你的原话' },
            signed: { ru: 'Подпись', ua: 'Підпис', en: 'Signed', de: 'Unterschrift', pl: 'Podpis', zh: '署名' },
        },
    },

    timeline: {
        title: { ru: 'Операция «Подоконник»: что я знаю', ua: 'Операція «Підвіконня»: що я знаю', en: 'Operation Windowsill: what I know', de: 'Operation Fensterbank: was ich weiß', pl: 'Operacja Parapet: co wiem', zh: '窗台行动：我所知道的' },
        sub: {
            ru: 'Собрано по библиотечным микрофильмам, утёкшему бюджету и одному очень болтливому водителю автобуса на пенсии.',
            ua: 'Зібрано з бібліотечних мікрофільмів, бюджету, що витік, і одного дуже балакучого водія автобуса на пенсії.',
            en: 'Pieced together from library microfilm, a leaked budget and one very chatty retired bus driver.',
            de: 'Zusammengesetzt aus Bibliotheks-Mikrofilm, einem geleakten Haushalt und einem sehr gesprächigen Busfahrer im Ruhestand.',
            pl: 'Poskładane z bibliotecznych mikrofilmów, wyciekłego budżetu i jednego bardzo gadatliwego emerytowanego kierowcy autobusu.',
            zh: '根据图书馆的缩微胶片、一份泄露的预算和一位话特别多的退休公交司机拼凑而成。',
        },
        hint: { ru: 'чёрные полосы можно соскрести. кликай', ua: 'чорні смуги можна зішкребти. клацай', en: 'the black bars scratch off. click them', de: 'die schwarzen Balken lassen sich abkratzen. klick drauf', pl: 'czarne paski da się zdrapać. klikaj', zh: '黑条可以刮开。点一下' },
        today: { ru: 'сегодня', ua: 'сьогодні', en: 'today', de: 'heute', pl: 'dziś', zh: '今天' },
        t1: {
            a: {
                ru: 'Последний живой голубь Лос-Сантоса, Джеральд, умирает от старости на крыше рыболовной лавки на пирсе Дель-Перро. В официальной записи причина смерти указана как',
                ua: 'Останній живий голуб Лос-Сантоса, Джеральд, помирає від старості на даху рибальської крамниці на пірсі Дель-Перро. В офіційному записі причину смерті вказано як',
                en: 'The last organic pigeon in Los Santos, Gerald, dies of old age on the roof of the bait shop at Del Perro Pier. The official record lists the cause of death as',
                de: 'Die letzte echte Taube von Los Santos, Gerald, stirbt an Altersschwäche auf dem Dach des Köderladens am Del Perro Pier. Als Todesursache steht im Protokoll',
                pl: 'Ostatni żywy gołąb Los Santos, Gerald, umiera ze starości na dachu sklepu wędkarskiego na molo Del Perro. W oficjalnym protokole jako przyczynę zgonu wpisano',
                zh: '洛圣都最后一只真鸽子杰拉德，在德尔佩罗码头鱼饵店的屋顶上老死。官方记录的死因写着',
            },
            r: { ru: '«голубиные дела»', ua: '«голубині справи»', en: '"a pigeon thing"', de: '"Taubenkram"', pl: '"sprawy gołębie"', zh: '「鸽子的事」' },
            b: { ru: '.', ua: '.', en: '.', de: '.', pl: '.', zh: '。' },
        },
        t2: {
            a: {
                ru: 'В бюджете штата Сан-Андреас появляется новая строка:',
                ua: 'У бюджеті штату Сан-Андреас з\'являється новий рядок:',
                en: 'A new line appears in the San Andreas state budget:',
                de: 'Im Haushalt von San Andreas taucht eine neue Zeile auf:',
                pl: 'W budżecie stanu San Andreas pojawia się nowa pozycja:',
                zh: '圣安地列斯州预算里出现了新的一行：',
            },
            r: { ru: '«Птицы (разное) - 40 000 000 $»', ua: '«Птахи (різне) - 40 000 000 $»', en: '"Birds (misc.) - $40,000,000"', de: '"Vögel (Sonstiges) - 40.000.000 $"', pl: '"Ptaki (różne) - 40 000 000 $"', zh: '「鸟类（杂项）- 40,000,000美元」' },
            b: {
                ru: '. Никто не спросил, какие птицы. Никто не спросил, что значит «разное».',
                ua: '. Ніхто не спитав, які птахи. Ніхто не спитав, що означає «різне».',
                en: '. Nobody asks which birds. Nobody asks what "misc." means.',
                de: '. Niemand fragt, welche Vögel. Niemand fragt, was "Sonstiges" heißt.',
                pl: '. Nikt nie pyta, jakie ptaki. Nikt nie pyta, co znaczy "różne".',
                zh: '。没人问是什么鸟。也没人问「杂项」是什么意思。',
            },
        },
        t3: {
            a: {
                ru: 'Ночь подмены. Грузовики без опознавательных знаков с надписью «Орнитологические товары» выезжают из',
                ua: 'Ніч підміни. Вантажівки без розпізнавальних знаків із написом «Орнітологічні товари» виїжджають із',
                en: 'The Night of the Swap. Unmarked trucks labelled "Ornithological Supplies" leave',
                de: 'Die Nacht des Austauschs. Neutrale Lastwagen mit der Aufschrift "Ornithologischer Bedarf" verlassen',
                pl: 'Noc Podmiany. Nieoznakowane ciężarówki z napisem "Artykuły ornitologiczne" wyjeżdżają z',
                zh: '调包之夜。凌晨两点，几辆没有标识、却印着「鸟类用品」字样的卡车驶出了',
            },
            r: { ru: 'Форт-Занкудо', ua: 'Форт-Занкудо', en: 'Fort Zancudo', de: 'Fort Zancudo', pl: 'Fort Zancudo', zh: '桑库多堡' },
            b: {
                ru: ' в два часа ночи. К утру в городе заменены 80 000 голубей. Свидетели говорят, что новые ходили «как-то очень ровно».',
                ua: ' о другій ночі. До ранку в місті замінено 80 000 голубів. Свідки кажуть, що нові ходили «якось дуже рівно».',
                en: ' at 2 a.m. By morning 80,000 pigeons in the city have been replaced. Witnesses say the new ones walked "in a very straight line".',
                de: ' um zwei Uhr nachts. Bis zum Morgen sind 80.000 Tauben der Stadt ersetzt. Zeugen sagen, die neuen liefen "irgendwie sehr gerade".',
                pl: ' o drugiej w nocy. Do rana w mieście podmieniono 80 000 gołębi. Świadkowie mówią, że nowe chodziły "jakoś bardzo prosto".',
                zh: '。到天亮时，城里8万只鸽子已被全部替换。目击者说，新来的那些走路「特别直」。',
            },
        },
        t4: {
            a: {
                ru: 'Прошивка 1.0, кодовое имя «Крошка». Город запускает для пенсионеров Веспуччи программу «Покорми птичек». Каждое воскресенье каждый пенсионер получает бесплатный бумажный пакет',
                ua: 'Прошивка 1.0, кодове ім\'я «Крихта». Місто запускає для пенсіонерів Веспуччі програму «Погодуй пташок». Щонеділі кожен пенсіонер отримує безкоштовний паперовий пакет',
                en: 'Firmware 1.0, codename Crumb. The city launches a "Feed the Birds" programme for pensioners in Vespucci. Every Sunday each pensioner receives a free paper bag of',
                de: 'Firmware 1.0, Codename Krümel. Die Stadt startet für Rentner in Vespucci das Programm "Füttert die Vögel". Jeden Sonntag bekommt jeder Rentner eine kostenlose Papiertüte',
                pl: 'Firmware 1.0, nazwa kodowa Okruch. Miasto uruchamia dla emerytów z Vespucci program "Nakarm ptaszki". Co niedzielę każdy emeryt dostaje darmową papierową torebkę',
                zh: '固件1.0，代号「面包屑」。市政府为威斯普奇的退休老人推出「喂喂小鸟」计划。每个周日，每位老人都能免费领到一纸袋',
            },
            r: { ru: 'хлеба с прошивкой', ua: 'хліба з прошивкою', en: 'firmware bread', de: 'Firmware-Brot', pl: 'chleba z firmware', zh: '装着固件的面包' },
            b: { ru: '.', ua: '.', en: '.', de: '.', pl: '.', zh: '。' },
        },
        t5: {
            a: {
                ru: 'Сеть проводов достроена. Каждый столб в городе - зарядка. Энергокомпания начинает называть мигание в 06:00 «известным явлением».',
                ua: 'Мережу дротів добудовано. Кожен стовп у місті - зарядка. Енергокомпанія починає називати блимання о 06:00 «відомим явищем».',
                en: 'The power line network is finished. Every pole in the city is a charger. The power company starts calling the 06:00 flicker a "known phenomenon".',
                de: 'Das Leitungsnetz ist fertig. Jeder Mast der Stadt ist ein Ladegerät. Das Stromwerk nennt das Flackern um 06:00 fortan ein "bekanntes Phänomen".',
                pl: 'Sieć linii jest gotowa. Każdy słup w mieście to ładowarka. Elektrownia zaczyna nazywać mruganie o 06:00 "znanym zjawiskiem".',
                zh: '电网完工。城里每一根电线杆都是充电桩。电力公司开始把早上6点的闪烁称作「已知现象」。',
            },
        },
        t6: {
            a: {
                ru: 'Переход на dial-up. Воркование становится хендшейком 56k. Бабушка из Миррор-Парка рассказывает Weazel News, что её голуби «звучат как интернет». Сюжет',
                ua: 'Перехід на dial-up. Воркування стає хендшейком 56k. Бабуся з Міррор-Парку розповідає Weazel News, що її голуби «звучать як інтернет». Сюжет',
                en: 'Upgrade to dial-up. The cooing becomes a 56k handshake. A grandmother from Mirror Park tells Weazel News that her pigeons "sound like the internet". The segment',
                de: 'Umstieg auf Einwahl. Das Gurren wird zum 56k-Handshake. Eine Oma aus Mirror Park erzählt Weazel News, ihre Tauben "klingen wie das Internet". Der Beitrag',
                pl: 'Przejście na dial-up. Gruchanie staje się handshake\'iem 56k. Babcia z Mirror Park mówi Weazel News, że jej gołębie "brzmią jak internet". Materiał',
                zh: '升级为拨号上网。咕咕声变成了56k握手音。镜湖公园的一位老奶奶告诉Weazel News，她的鸽子「听起来像互联网」。那段采访',
            },
            r: { ru: 'так и не вышел в эфир', ua: 'так і не вийшов в ефір', en: 'was never aired', de: 'wurde nie gesendet', pl: 'nigdy nie trafił na antenę', zh: '从未播出' },
            b: { ru: '.', ua: '.', en: '.', de: '.', pl: '.', zh: '。' },
        },
        t7: {
            a: {
                ru: 'Переход на беспроводную связь. Ворковать больше не нужно. Они всё равно воркуют.',
                ua: 'Перехід на бездротовий зв\'язок. Воркувати більше не треба. Вони все одно воркують.',
                en: 'Wireless upgrade. The pigeons no longer need to coo. They keep doing it anyway. The',
                de: 'Umstieg auf Funk. Gurren ist nicht mehr nötig. Sie machen es trotzdem. Das',
                pl: 'Przejście na łączność bezprzewodową. Gruchać już nie trzeba. I tak gruchają.',
                zh: '升级为无线。鸽子不再需要咕咕叫了。可它们还是照叫不误。',
            },
            r: { ru: 'Модуль ностальгии', ua: 'Модуль ностальгії', en: 'nostalgia module', de: 'Nostalgiemodul', pl: 'Moduł nostalgii', zh: '怀旧模块' },
            b: { ru: ' так и не удалили.', ua: ' так і не видалили.', en: ' was never removed.', de: ' wurde nie entfernt.', pl: ' nigdy nie został usunięty.', zh: '一直没被删除。' },
        },
        t8: {
            a: {
                ru: 'Прошивка 9.4 добавляет стабилизацию головы. На каждом шаге голова замирает в воздухе, а тело едет под ней. Это стабилизатор. Это буквально стабилизатор для камеры.',
                ua: 'Прошивка 9.4 додає стабілізацію голови. На кожному кроці голова завмирає в повітрі, а тіло їде під нею. Це стабілізатор. Це буквально стабілізатор для камери.',
                en: 'Firmware 9.4 adds head stabilisation. With every step the head holds still in the air while the body moves under it. That is a gimbal. That is literally a camera gimbal.',
                de: 'Firmware 9.4 bringt Kopfstabilisierung. Bei jedem Schritt steht der Kopf still in der Luft, während der Körper darunter weiterläuft. Das ist ein Gimbal. Das ist buchstäblich ein Kamera-Gimbal.',
                pl: 'Firmware 9.4 dodaje stabilizację głowy. Przy każdym kroku głowa zastyga w powietrzu, a ciało jedzie pod nią. To gimbal. To dosłownie gimbal do kamery.',
                zh: '固件9.4加入了头部稳定功能。每走一步，头都定在空中不动，身体在下面挪。这就是云台。这简直就是相机云台。',
            },
        },
        t9: {
            a: {
                ru: 'На площади Легиона я замечаю голубя с наклейкой на лапке:',
                ua: 'На площі Легіону я помічаю голуба з наліпкою на лапці:',
                en: 'At Legion Square I notice a pigeon with a sticker on its leg:',
                de: 'Am Legion Square sehe ich eine Taube mit einem Aufkleber am Bein:',
                pl: 'Na Legion Square zauważam gołębia z naklejką na nóżce:',
                zh: '在军团广场，我注意到一只腿上贴着标签的鸽子：',
            },
            r: { ru: '«СОБСТВЕННОСТЬ ШТАТА С.А. НЕ КОРМИТЬ ПОСЛЕ 22:00»', ua: '«ВЛАСНІСТЬ ШТАТУ С.А. НЕ ГОДУВАТИ ПІСЛЯ 22:00»', en: '"PROPERTY OF S.A. - DO NOT FEED AFTER 22:00"', de: '"EIGENTUM VON S.A. - NACH 22:00 NICHT FÜTTERN"', pl: '"WŁASNOŚĆ STANU S.A. - NIE KARMIĆ PO 22:00"', zh: '「圣安地列斯州财产，22:00后请勿喂食」' },
            b: {
                ru: '. Моргаю - его нет. Той же ночью я регистрирую этот сайт.',
                ua: '. Кліпаю - його немає. Тієї ж ночі я реєструю цей сайт.',
                en: '. I blink. It is gone. That same night I register this website.',
                de: '. Ich blinzle. Sie ist weg. In derselben Nacht registriere ich diese Website.',
                pl: '. Mrugam. Nie ma go. Tej samej nocy rejestruję tę stronę.',
                zh: '。我眨了下眼，它就不见了。当晚我注册了这个网站。',
            },
        },
        t10: {
            a: {
                ru: 'Ты это читаешь. Скорее всего, один из них читает у тебя через плечо.',
                ua: 'Ти це читаєш. Найімовірніше, один із них читає в тебе через плече.',
                en: 'You are reading this. One of them is probably reading over your shoulder.',
                de: 'Du liest das gerade. Wahrscheinlich liest einer von ihnen über deine Schulter mit.',
                pl: 'Czytasz to. Najpewniej jeden z nich czyta ci przez ramię.',
                zh: '你正在读这些。很可能有一只正趴在你肩膀后面一起读。',
            },
            r: { ru: 'привет', ua: 'привіт', en: 'hi', de: 'hallo', pl: 'cześć', zh: '你好' },
        },
    },

    guide: {
        title: { ru: 'Как выжить', ua: 'Як вижити', en: 'Survival guide', de: 'Überlebensguide', pl: 'Jak przeżyć', zh: '生存指南' },
        sub: {
            ru: 'Распечатать, сложить вчетверо, носить в ботинке. Дополняется после каждого инцидента.',
            ua: 'Роздрукувати, скласти вчетверо, носити в черевику. Доповнюється після кожного інциденту.',
            en: 'Print, fold in four, keep in your shoe. Revised after every incident.',
            de: 'Ausdrucken, zweimal falten, im Schuh tragen. Wird nach jedem Vorfall überarbeitet.',
            pl: 'Wydrukować, złożyć na cztery, nosić w bucie. Uzupełniane po każdym incydencie.',
            zh: '打印出来，折成四折，塞在鞋里。每出一次事就修订一次。',
        },
        rule: { ru: 'Правило {{n}}', ua: 'Правило {{n}}', en: 'Rule {{n}}', de: 'Regel {{n}}', pl: 'Zasada {{n}}', zh: '第{{n}}条' },
        g1: {
            t: { ru: 'Никогда не смотри им в глаза.', ua: 'Ніколи не дивись їм в очі.', en: 'Never make eye contact.', de: 'Niemals Blickkontakt.', pl: 'Nigdy nie patrz im w oczy.', zh: '永远不要和它们对视。' },
            x: {
                ru: 'Они записывают сетчатку. Носи тёмные очки. Ночью. Дома. В душе, если придётся.',
                ua: 'Вони записують сітківку. Носи темні окуляри. Уночі. Удома. У душі, якщо доведеться.',
                en: 'They record retinas. Wear sunglasses. At night. Indoors. In the shower if you have to.',
                de: 'Sie speichern Netzhäute. Trag Sonnenbrille. Nachts. Drinnen. Unter der Dusche, wenn es sein muss.',
                pl: 'Nagrywają siatkówki. Noś okulary przeciwsłoneczne. W nocy. W domu. Pod prysznicem, jeśli trzeba.',
                zh: '它们会记录视网膜。戴墨镜。晚上也戴。屋里也戴。必要时洗澡也戴。',
            },
        },
        g2: {
            t: { ru: 'Корми только хлебом-приманкой.', ua: 'Годуй лише хлібом-приманкою.', en: 'Feed them decoy bread only.', de: 'Nur mit Köderbrot füttern.', pl: 'Karm tylko chlebem-wabikiem.', zh: '只喂诱饵面包。' },
            x: {
                ru: 'Он заливает битое обновление, и изделие уходит в перезагрузку на 20 минут. Двадцать минут свободы. Трать их с умом. Рецепт рядом.',
                ua: 'Він заливає бите оновлення, і виріб іде в перезавантаження на 20 хвилин. Двадцять хвилин свободи. Витрачай їх з розумом. Рецепт поруч.',
                en: 'It installs a corrupted update and the unit reboots for 20 minutes. Twenty minutes of freedom. Spend them wisely. Recipe next to this.',
                de: 'Es spielt ein kaputtes Update auf, und die Einheit startet 20 Minuten neu. Zwanzig Minuten Freiheit. Nutze sie weise. Rezept daneben.',
                pl: 'Wgrywa uszkodzoną aktualizację i jednostka restartuje się przez 20 minut. Dwadzieścia minut wolności. Wykorzystaj je mądrze. Przepis obok.',
                zh: '它会装上损坏的更新，单元会重启20分钟。二十分钟的自由。好好利用。配方在旁边。',
            },
        },
        g3: {
            t: { ru: 'Не разговаривай у подоконника.', ua: 'Не розмовляй біля підвіконня.', en: 'Never talk near a windowsill.', de: 'Rede nie in der Nähe einer Fensterbank.', pl: 'Nie rozmawiaj przy parapecie.', zh: '别在窗台附近说话。' },
            x: {
                ru: 'Всё важное - в ванной под включённую воду. Или шёпотом надёжному камню:',
                ua: 'Усе важливе - у ванній під увімкнену воду. Або пошепки надійному каменю:',
                en: 'Say important things in the bathroom with the tap running. Or whisper them to a trusted rock:',
                de: 'Wichtiges nur im Bad bei laufendem Wasserhahn. Oder flüstere es einem vertrauenswürdigen Stein zu:',
                pl: 'Ważne rzeczy mów w łazience przy odkręconym kranie. Albo szepnij je zaufanemu kamieniowi:',
                zh: '重要的话去卫生间开着水龙头说。或者悄悄告诉一块可靠的石头：',
            },
        },
        g4: {
            t: { ru: 'Если голубь идёт на тебя - уходи зигзагом.', ua: 'Якщо голуб іде на тебе - тікай зигзагом.', en: 'If one walks toward you, walk away in a zigzag.', de: 'Kommt eine auf dich zu, geh im Zickzack weg.', pl: 'Jeśli gołąb idzie w twoją stronę, uciekaj zygzakiem.', zh: '如果有一只朝你走来，走之字形离开。' },
            x: { ru: 'Зигзаги они не просчитывают.', ua: 'Зигзаги вони не прораховують.', en: 'They cannot compute zigzags.', de: 'Zickzack können sie nicht berechnen.', pl: 'Zygzaków nie potrafią obliczyć.', zh: '它们算不出之字形。' },
            fix: {
                ru: 'в прошивке 11.2 зигзаги пропатчили. теперь я просто бегу',
                ua: 'у прошивці 11.2 зигзаги пропатчили. тепер я просто біжу',
                en: 'firmware 11.2 patched zigzags. now I just run',
                de: 'Firmware 11.2 hat Zickzack gepatcht. jetzt renne ich einfach',
                pl: 'firmware 11.2 załatał zygzaki. teraz po prostu biegnę',
                zh: '11.2版固件把之字形修复了。现在我只能跑',
            },
        },
        g5: {
            t: { ru: 'Памятники - это ретрансляторы.', ua: 'Пам\'ятники - це ретранслятори.', en: 'Statues are relay towers.', de: 'Statuen sind Sendemasten.', pl: 'Pomniki to przekaźniki.', zh: '雕像是中继塔。' },
            x: {
                ru: 'Ничего важного в радиусе 30 метров от памятника. Ничего неважного тоже. Они собирают всё.',
                ua: 'Нічого важливого в радіусі 30 метрів від пам\'ятника. Нічого неважливого теж. Вони збирають усе.',
                en: 'Nothing important within 30 metres of a statue. Nothing unimportant either. They collect everything.',
                de: 'Nichts Wichtiges im Umkreis von 30 Metern um eine Statue. Nichts Unwichtiges auch nicht. Sie sammeln alles.',
                pl: 'Nic ważnego w promieniu 30 metrów od pomnika. Nic nieważnego też. Zbierają wszystko.',
                zh: '雕像30米范围内别说任何重要的事。不重要的也别说。它们什么都收集。',
            },
        },
        g6: {
            t: { ru: 'С 06:00 до 09:00 держись подальше от проводов.', ua: 'З 06:00 до 09:00 тримайся подалі від дротів.', en: 'Stay away from power lines between 06:00 and 09:00.', de: 'Zwischen 06:00 und 09:00 weg von Stromleitungen.', pl: 'Między 06:00 a 09:00 trzymaj się z dala od linii.', zh: '早上6点到9点远离电线。' },
            x: { ru: 'Часы зарядки. Вся стая онлайн и не в духе.', ua: 'Години зарядки. Уся зграя онлайн і не в гуморі.', en: 'Charging hours. The whole flock is online and in a mood.', de: 'Ladezeit. Der ganze Schwarm ist online und schlecht gelaunt.', pl: 'Godziny ładowania. Całe stado jest online i nie w humorze.', zh: '充电时间。整个鸟群都在线，而且心情不好。' },
        },
        g7: {
            t: { ru: 'Услышал «кшшшш... дзынь» - громко мычи.', ua: 'Почув «кшшшш... дзінь» - голосно мугикай.', en: 'If you hear "kshhhh... ding", hum loudly.', de: 'Hörst du "kschhhh... ding", summ laut.', pl: 'Słyszysz "kszszsz... dzyń"? Nuć głośno.', zh: '听到「嘶嘶嘶……叮」，就大声哼歌。' },
            x: {
                ru: 'Это хендшейк, тебя выгружают. Мычание портит звук. Подойдёт любая песня, кроме заставки Weazel News.',
                ua: 'Це хендшейк, тебе вивантажують. Мугикання псує звук. Підійде будь-яка пісня, крім заставки Weazel News.',
                en: 'That is a handshake. You are being uploaded. Humming corrupts the audio. Any song works except the Weazel News jingle.',
                de: 'Das ist ein Handshake. Du wirst hochgeladen. Summen stört das Audio. Jedes Lied geht, außer dem Weazel-News-Jingle.',
                pl: 'To handshake. Właśnie cię wysyłają. Nucenie psuje dźwięk. Każda piosenka się nada, oprócz dżingla Weazel News.',
                zh: '那是握手音，你正在被上传。哼歌能干扰音频。什么歌都行，除了Weazel News的片头曲。',
            },
        },
        g8: {
            t: { ru: 'Утки в порядке. Утки настоящие.', ua: 'Качки в порядку. Качки справжні.', en: 'Ducks are fine. Ducks are real.', de: 'Enten sind okay. Enten sind echt.', pl: 'Kaczki są w porządku. Kaczki są prawdziwe.', zh: '鸭子没问题。鸭子是真的。' },
            fix: { ru: 'УТКИ НЕ В ПОРЯДКЕ. см. дневник', ua: 'КАЧКИ НЕ В ПОРЯДКУ. див. щоденник', en: 'DUCKS ARE NOT FINE. see updates', de: 'ENTEN SIND NICHT OKAY. siehe Tagebuch', pl: 'KACZKI NIE SĄ W PORZĄDKU. patrz dziennik', zh: '鸭子有问题。见更新日志' },
        },
        g9: {
            t: { ru: 'Чайки - частный подрядчик.', ua: 'Чайки - приватний підрядник.', en: 'Seagulls are a private contractor.', de: 'Möwen sind ein privater Auftragnehmer.', pl: 'Mewy to prywatny podwykonawca.', zh: '海鸥是私人承包商。' },
            x: {
                ru: 'Чайки на Веспуччи работают на кого-то другого. Ни те, ни другие тебе не друзья. И те и другие хотят твою картошку фри.',
                ua: 'Чайки на Веспуччі працюють на когось іншого. Ні ті, ні інші тобі не друзі. І ті, й інші хочуть твою картоплю фрі.',
                en: 'The gulls at Vespucci work for someone else. Neither side is your friend. Both want your fries.',
                de: 'Die Möwen in Vespucci arbeiten für jemand anderen. Keine Seite ist dein Freund. Beide wollen deine Pommes.',
                pl: 'Mewy na Vespucci pracują dla kogoś innego. Żadna strona nie jest twoim przyjacielem. Obie chcą twoich frytek.',
                zh: '威斯普奇的海鸥在给别人干活。哪一边都不是你的朋友。两边都想要你的薯条。',
            },
        },
        recipe: {
            title: { ru: 'Хлеб-приманка', ua: 'Хліб-приманка', en: 'Decoy bread', de: 'Köderbrot', pl: 'Chleb-wabik', zh: '诱饵面包' },
            yield: { ru: '1 буханка, обманывает 40 изделий', ua: '1 буханка, ошукує 40 виробів', en: 'makes 1 loaf, fools 40 units', de: 'ergibt 1 Laib, täuscht 40 Einheiten', pl: '1 bochenek, oszukuje 40 jednostek', zh: '可做1条，能骗过40台单元' },
            i1: { ru: '1 чёрствый ржаной хлеб (от 4 дней)', ua: '1 черствий житній хліб (від 4 днів)', en: '1 stale rye loaf (at least 4 days old)', de: '1 altes Roggenbrot (mindestens 4 Tage)', pl: '1 czerstwy chleb żytni (min. 4 dni)', zh: '1条放了至少4天的黑麦面包' },
            i2: { ru: 'фольга', ua: 'фольга', en: 'tinfoil', de: 'Alufolie', pl: 'folia aluminiowa', zh: '锡纸' },
            i3: { ru: 'щепотка песка с Аламо-Си', ua: 'дрібка піску з Аламо-Сі', en: 'a pinch of sand from the Alamo Sea', de: 'eine Prise Sand vom Alamo Sea', pl: 'szczypta piasku znad Alamo Sea', zh: '一撮阿拉莫海的沙子' },
            i4: { ru: 'бумажный пакет без логотипа', ua: 'паперовий пакет без логотипа', en: 'a paper bag with no logo', de: 'eine Papiertüte ohne Logo', pl: 'papierowa torba bez logo', zh: '一个没有商标的纸袋' },
            i5: { ru: 'уверенность', ua: 'впевненість', en: 'confidence', de: 'Selbstvertrauen', pl: 'pewność siebie', zh: '自信' },
            method: {
                ru: 'Заверни хлеб в фольгу на ночь, чтобы он забыл, кто он такой. Кроши только левой рукой. Бросай, а не клади. Уходи, пока не закончилась полоса загрузки.',
                ua: 'Загорни хліб у фольгу на ніч, щоб він забув, хто він такий. Криши лише лівою рукою. Кидай, а не клади. Іди геть, поки не закінчилася смуга завантаження.',
                en: 'Wrap the bread in foil overnight so it forgets who it is. Crumble with the left hand only. Throw, never place. Leave before the progress bar finishes.',
                de: 'Das Brot über Nacht in Folie wickeln, damit es vergisst, wer es ist. Nur mit links zerbröseln. Werfen, nie hinlegen. Geh, bevor der Fortschrittsbalken voll ist.',
                pl: 'Zawiń chleb na noc w folię, żeby zapomniał, kim jest. Krusz tylko lewą ręką. Rzucaj, nie kładź. Odejdź, zanim skończy się pasek postępu.',
                zh: '把面包用锡纸包一晚上，让它忘了自己是谁。只能用左手掰碎。要扔，别放。进度条走完之前赶紧离开。',
            },
        },
    },

    updates: {
        title: { ru: 'Дневник', ua: 'Щоденник', en: 'Updates', de: 'Tagebuch', pl: 'Dziennik', zh: '更新日志' },
        sub: {
            ru: 'Новые записи внизу, как в настоящем дневнике. Читай по порядку.',
            ua: 'Нові записи внизу, як у справжньому щоденнику. Читай по порядку.',
            en: 'Newest at the bottom, like a real diary. Read them in order.',
            de: 'Neueste unten, wie in einem echten Tagebuch. Der Reihe nach lesen.',
            pl: 'Najnowsze na dole, jak w prawdziwym dzienniku. Czytaj po kolei.',
            zh: '最新的在最下面，就像真正的日记。按顺序读。',
        },
        switch: {
            title: { ru: 'Кнопка мертвеца', ua: 'Кнопка мерця', en: 'Dead man\'s switch', de: 'Totmannschalter', pl: 'Przycisk martwego człowieka', zh: '死人开关' },
            text: {
                ru: 'Если я не отмечусь 72 часа, эта страница сама опубликует полное досье.',
                ua: 'Якщо я не відмічуся 72 години, ця сторінка сама опублікує повне досьє.',
                en: 'If I do not check in for 72 hours, this page publishes the full dossier automatically.',
                de: 'Wenn ich mich 72 Stunden nicht melde, veröffentlicht diese Seite automatisch das komplette Dossier.',
                pl: 'Jeśli nie zamelduję się przez 72 godziny, ta strona sama opublikuje pełne dossier.',
                zh: '如果我72小时没有签到，这个页面会自动公开完整档案。',
            },
            last: { ru: 'С последней отметки прошло:', ua: 'Від останньої відмітки минуло:', en: 'Time since last check-in:', de: 'Seit der letzten Meldung:', pl: 'Od ostatniego meldunku minęło:', zh: '距上次签到：' },
            firing: { ru: '72 часа прошло. Публикую досье...', ua: '72 години минуло. Публікую досьє...', en: '72 hours are up. Publishing the dossier...', de: '72 Stunden sind um. Veröffentliche das Dossier...', pl: 'Minęły 72 godziny. Publikuję dossier...', zh: '72小时到了。正在公开档案……' },
            fired: { ru: 'Досье опубликовано.', ua: 'Досьє опубліковано.', en: 'Dossier published.', de: 'Dossier veröffentlicht.', pl: 'Dossier opublikowane.', zh: '档案已公开。' },
            open: { ru: 'Открыть досье', ua: 'Відкрити досьє', en: 'Open the dossier', de: 'Dossier öffnen', pl: 'Otwórz dossier', zh: '打开档案' },
        },
        dossier: {
            title: { ru: 'Полное досье', ua: 'Повне досьє', en: 'The full dossier', de: 'Das komplette Dossier', pl: 'Pełne dossier', zh: '完整档案' },
            body: {
                ru: 'Если ты это читаешь, они до меня добрались. Вот всё, что я знаю:',
                ua: 'Якщо ти це читаєш, вони до мене дісталися. Ось усе, що я знаю:',
                en: 'If you are reading this, they got me. Here is everything I know:',
                de: 'Wenn du das liest, haben sie mich erwischt. Hier ist alles, was ich weiß:',
                pl: 'Jeśli to czytasz, dopadli mnie. Oto wszystko, co wiem:',
                zh: '如果你在读这些，说明他们抓到我了。以下是我知道的一切：',
            },
            all: { ru: 'ОНИ. НЕ. ПТИЦЫ.', ua: 'ВОНИ. НЕ. ПТАХИ.', en: 'THEY. ARE. NOT. BIRDS.', de: 'SIE. SIND. KEINE. VÖGEL.', pl: 'TO. NIE. SĄ. PTAKI.', zh: '它们。不是。鸟。' },
            end: {
                ru: 'Всё. Это и есть досье. Я всё собирался написать побольше. Кормите их хлебом-приманкой. Скажите миссис Альварес, чтобы не снимала очки.',
                ua: 'Усе. Це і є досьє. Я все збирався написати більше. Годуйте їх хлібом-приманкою. Скажіть місіс Альварес, щоб не знімала окуляри.',
                en: 'That is it. That is the dossier. I always meant to write more. Feed them decoy bread. Tell Mrs. Alvarez to keep her sunglasses on.',
                de: 'Das ist alles. Das ist das Dossier. Ich wollte immer mehr schreiben. Füttert sie mit Köderbrot. Sagt Mrs. Alvarez, sie soll die Sonnenbrille aufbehalten.',
                pl: 'To wszystko. To jest całe dossier. Zawsze chciałem napisać więcej. Karmcie je chlebem-wabikiem. Powiedzcie pani Alvarez, żeby nie zdejmowała okularów.',
                zh: '就这些。这就是档案。我一直想多写一点。喂它们诱饵面包。告诉阿尔瓦雷斯太太别摘墨镜。',
            },
            close: { ru: 'Сложить и спрятать', ua: 'Скласти і сховати', en: 'Fold it and hide it', de: 'Falten und verstecken', pl: 'Złóż i schowaj', zh: '折好藏起来' },
        },
        u1: {
            date: { ru: '3 марта', ua: '3 березня', en: 'March 3', de: '3. März', pl: '3 marca', zh: '3月3日' },
            text: {
                ru: 'Добро пожаловать, проснувшиеся. Сайт работает с ноутбука в ванной, обложенной противнями (свинца не было в наличии). Новые улики - каждую неделю. Не говорите никому. Говорите всем. Не говорите птицам.',
                ua: 'Ласкаво просимо, пробуджені. Сайт працює з ноутбука у ванній, обкладеній деками (свинцю не було в наявності). Нові докази - щотижня. Не кажіть нікому. Кажіть усім. Не кажіть птахам.',
                en: 'Welcome, awake ones. This site runs on a laptop in a bathtub lined with baking trays (lead was out of stock). New evidence every week. Tell no one. Tell everyone. Tell no birds.',
                de: 'Willkommen, ihr Wachen. Diese Seite läuft auf einem Laptop in einer Badewanne, ausgekleidet mit Backblechen (Blei war ausverkauft). Jede Woche neue Beweise. Sagt es niemandem. Sagt es allen. Sagt es keinem Vogel.',
                pl: 'Witajcie, przebudzeni. Strona działa z laptopa w wannie wyłożonej blachami do pieczenia (ołowiu nie było). Nowe dowody co tydzień. Nie mówcie nikomu. Mówcie wszystkim. Nie mówcie ptakom.',
                zh: '欢迎，清醒的人们。本站运行在一台放在浴缸里的笔记本上，浴缸内壁贴满了烤盘（铅卖完了）。每周更新证据。别告诉任何人。告诉所有人。别告诉鸟。',
            },
        },
        u2: {
            date: { ru: '11 марта', ua: '11 березня', en: 'March 11', de: '11. März', pl: '11 marca', zh: '3月11日' },
            text: {
                ru: 'Сегодня голубь просидел у меня на подоконнике шесть часов. Не ел. Не моргал. Когда я открыл окно, он улетел по идеально прямой линии, как будто у него был пункт назначения. У него был пункт назначения.',
                ua: 'Сьогодні голуб просидів у мене на підвіконні шість годин. Не їв. Не кліпав. Коли я відчинив вікно, він полетів ідеально прямою лінією, ніби мав пункт призначення. Він мав пункт призначення.',
                en: 'A pigeon sat on my windowsill for six hours today. It did not eat. It did not blink. When I opened the window it flew off in a perfectly straight line, like it had a destination. It had a destination.',
                de: 'Heute saß eine Taube sechs Stunden auf meiner Fensterbank. Sie hat nicht gefressen. Nicht geblinzelt. Als ich das Fenster aufgemacht habe, flog sie schnurgerade davon, als hätte sie ein Ziel. Sie hatte ein Ziel.',
                pl: 'Dziś gołąb siedział na moim parapecie sześć godzin. Nie jadł. Nie mrugał. Kiedy otworzyłem okno, odleciał idealnie prostą linią, jakby miał cel podróży. Miał cel podróży.',
                zh: '今天有只鸽子在我窗台上坐了六个小时。不吃东西。不眨眼。我一开窗，它就沿着一条笔直的线飞走了，像是有目的地一样。它确实有目的地。',
            },
        },
        u3: {
            date: { ru: '19 марта', ua: '19 березня', en: 'March 19', de: '19. März', pl: '19 marca', zh: '3月19日' },
            text: {
                ru: 'Купил тёмные очки на весь подъезд. Взяла только миссис Альварес из 4Б. Миссис Альварес понимает. Миссис Альварес всегда понимала.',
                ua: 'Купив темні окуляри на весь під\'їзд. Взяла тільки місіс Альварес із 4Б. Місіс Альварес розуміє. Місіс Альварес завжди розуміла.',
                en: 'Bought sunglasses for everyone in my building. Only Mrs. Alvarez from 4B accepted. Mrs. Alvarez gets it. Mrs. Alvarez has always gotten it.',
                de: 'Hab Sonnenbrillen für das ganze Haus gekauft. Nur Mrs. Alvarez aus 4B hat eine genommen. Mrs. Alvarez versteht es. Mrs. Alvarez hat es immer verstanden.',
                pl: 'Kupiłem okulary przeciwsłoneczne dla całej klatki. Wzięła tylko pani Alvarez z 4B. Pani Alvarez rozumie. Pani Alvarez zawsze rozumiała.',
                zh: '我给整栋楼的人都买了墨镜。只有4B的阿尔瓦雷斯太太收下了。阿尔瓦雷斯太太懂。阿尔瓦雷斯太太一直都懂。',
            },
        },
        u4: {
            date: { ru: '2 апреля', ua: '2 квітня', en: 'April 2', de: '2. April', pl: '2 kwietnia', zh: '4月2日' },
            text: {
                ru: 'Поправка к правилу 8. Утки НЕ в порядке. Прогнал утку с озера в Миррор-Парке через сканер. Модель DK-2. Они расширяют ассортимент.',
                ua: 'Поправка до правила 8. Качки НЕ в порядку. Прогнав качку з озера в Міррор-Парку через сканер. Модель DK-2. Вони розширюють асортимент.',
                en: 'Correction to rule 8. Ducks are NOT fine. I ran a duck from the Mirror Park lake through the scanner. Model DK-2. They are diversifying.',
                de: 'Korrektur zu Regel 8. Enten sind NICHT okay. Ich habe eine Ente vom Mirror-Park-See durch den Scanner gejagt. Modell DK-2. Sie diversifizieren.',
                pl: 'Poprawka do zasady 8. Kaczki NIE są w porządku. Przepuściłem kaczkę z jeziora w Mirror Park przez skaner. Model DK-2. Poszerzają asortyment.',
                zh: '对第8条的更正。鸭子有问题。我把镜湖公园湖里的一只鸭子丢进了扫描仪。型号DK-2。他们在扩大产品线。',
            },
        },
        u5: {
            date: { ru: '9 апреля', ua: '9 квітня', en: 'April 9', de: '9. April', pl: '9 kwietnia', zh: '4月9日' },
            text: {
                ru: 'Перестал покупать хлеб. Хлебом они обновляются. Теперь ем крекеры - целиком, за один укус, над раковиной. Ноль крошек. Если что, ник отсюда.',
                ua: 'Перестав купувати хліб. Хлібом вони оновлюються. Тепер їм крекери - цілими, за один укус, над раковиною. Нуль крихт. Якщо що, нік звідси.',
                en: 'I have stopped buying bread. Bread is how they update. I eat crackers now, whole, in one bite, over the sink. Zero crumbs. That is where the name comes from, if you were wondering.',
                de: 'Ich kaufe kein Brot mehr. Über Brot updaten sie sich. Ich esse jetzt Cracker, im Ganzen, in einem Bissen, über der Spüle. Null Krümel. Daher der Name, falls ihr euch gefragt habt.',
                pl: 'Przestałem kupować chleb. Chlebem się aktualizują. Teraz jem krakersy, w całości, na jeden kęs, nad zlewem. Zero okruchów. Stąd ten nick, gdyby ktoś pytał.',
                zh: '我不再买面包了。它们就是靠面包更新的。现在我吃饼干，整块，一口吞，对着水槽吃。零渣。如果你好奇，我的网名就是这么来的。',
            },
        },
        u6: {
            date: { ru: '17 апреля', ua: '17 квітня', en: 'April 17', de: '17. April', pl: '17 kwietnia', zh: '4月17日' },
            text: {
                ru: 'Голуби за окном воркуют в новом ритме. Я записал и прокрутил задом наперёд. Там моё полное имя. Мой адрес. В конце - «милые шторы».',
                ua: 'Голуби за вікном воркують у новому ритмі. Я записав і прокрутив задом наперед. Там моє повне ім\'я. Моя адреса. Наприкінці - «гарні штори».',
                en: 'The pigeons outside my window coo in a new rhythm. I recorded it and played it backwards. It says my full name. It says my address. At the end it says "nice curtains".',
                de: 'Die Tauben vor meinem Fenster gurren in einem neuen Rhythmus. Ich habe es aufgenommen und rückwärts abgespielt. Es sagt meinen vollen Namen. Meine Adresse. Am Ende sagt es "schöne Vorhänge".',
                pl: 'Gołębie za oknem gruchają w nowym rytmie. Nagrałem to i puściłem od tyłu. Jest tam moje pełne imię i nazwisko. Mój adres. Na końcu: "ładne zasłony".',
                zh: '窗外的鸽子换了一种节奏咕咕叫。我录下来倒着放。里面有我的全名。有我的地址。最后一句是「窗帘不错」。',
            },
        },
        u7: {
            date: { ru: '30 апреля', ua: '30 квітня', en: 'April 30', de: '30. April', pl: '30 kwietnia', zh: '4月30日' },
            text: {
                ru: 'Переезжаю в Сэнди-Шорс. Ни памятников, почти ни проводов, ни голубей - только песок и мужик, который торгует вяленым мясом из лодки. Если сайт ляжет - это его Wi-Fi, а не они.',
                ua: 'Переїжджаю до Сенді-Шорс. Ні пам\'ятників, майже ні дротів, ні голубів - тільки пісок і чоловік, який торгує в\'яленим м\'ясом із човна. Якщо сайт ляже - це його Wi-Fi, а не вони.',
                en: 'Moving to Sandy Shores. No statues, barely any power lines, no pigeons. Only sand and a man who sells jerky out of a boat. If the site goes down, it is his Wi-Fi, not them.',
                de: 'Ich ziehe nach Sandy Shores. Keine Statuen, kaum Stromleitungen, keine Tauben. Nur Sand und ein Mann, der Trockenfleisch aus einem Boot verkauft. Wenn die Seite ausfällt, liegt es an seinem WLAN, nicht an ihnen.',
                pl: 'Przeprowadzam się do Sandy Shores. Żadnych pomników, prawie żadnych linii, zero gołębi. Tylko piasek i facet, który sprzedaje suszone mięso z łódki. Jeśli strona padnie, to jego Wi-Fi, nie oni.',
                zh: '我要搬去沙滩海岸了。没有雕像，几乎没有电线，没有鸽子。只有沙子和一个在船上卖肉干的男人。如果网站挂了，那是他的Wi-Fi不行，不是它们干的。',
            },
        },
        u8: {
            date: { ru: '6 мая', ua: '6 травня', en: 'May 6', de: '6. Mai', pl: '6 maja', zh: '5月6日' },
            text: {
                ru: 'В Сэнди-Шорс есть голубь. Один. Сидит на лодке с вяленым мясом. Мужик говорит, он там «всегда был». Мужик слишком спокоен.',
                ua: 'У Сенді-Шорс є голуб. Один. Сидить на човні з в\'яленим м\'ясом. Чоловік каже, він там «завжди був». Чоловік надто спокійний.',
                en: 'There is a pigeon in Sandy Shores. One. It sits on the jerky boat. The jerky man says it has been there "forever". The jerky man is far too calm about this.',
                de: 'In Sandy Shores gibt es eine Taube. Eine. Sie sitzt auf dem Trockenfleisch-Boot. Der Mann sagt, die sei "schon immer" da. Der Mann ist viel zu ruhig.',
                pl: 'W Sandy Shores jest gołąb. Jeden. Siedzi na łódce z suszonym mięsem. Facet mówi, że siedzi tam "od zawsze". Facet jest zdecydowanie za spokojny.',
                zh: '沙滩海岸有一只鸽子。就一只。它蹲在卖肉干的船上。那个男人说它「一直都在」。那个男人太淡定了。',
            },
        },
        u9: {
            date: { ru: '7 мая, 03:14', ua: '7 травня, 03:14', en: 'May 7, 03:14', de: '7. Mai, 03:14', pl: '7 maja, 03:14', zh: '5月7日 03:14' },
            text: {
                ru: 'кто-то стучит. я в трейлере. стук идёт с крыши. ритмичный. кшшшш. дзынь. кшшшш. дзынь',
                ua: 'хтось стукає. я в трейлері. стукіт іде з даху. ритмічний. кшшшш. дзінь. кшшшш. дзінь',
                en: 'someone is knocking. im in a trailer. the knocking is coming from the roof. its rhythmic. kshhhh. ding. kshhhh. ding',
                de: 'jemand klopft. ich bin im wohnwagen. das klopfen kommt vom dach. rhythmisch. kschhhh. ding. kschhhh. ding',
                pl: 'ktoś puka. jestem w przyczepie. pukanie dochodzi z dachu. rytmiczne. kszszsz. dzyń. kszszsz. dzyń',
                zh: '有人在敲。我在拖车里。敲声是从车顶传来的。很有节奏。嘶嘶嘶。叮。嘶嘶嘶。叮',
            },
        },
        u10: {
            date: { ru: '9 мая', ua: '9 травня', en: 'May 9', de: '9. Mai', pl: '9 maja', zh: '5月9日' },
            title: { ru: 'Сообщение от администратора', ua: 'Повідомлення від адміністратора', en: 'A message from the administrator', de: 'Eine Nachricht vom Administrator', pl: 'Wiadomość od administratora', zh: '来自管理员的消息' },
            text: {
                ru: 'Здравствуйте! Мы навели на сайте порядок. Голуби - обычные здоровые птицы, которые любят хлеб и спокойную жизнь. Предыдущий автор переехал на чудесную ферму за городом и передаёт всем привет. Комментарии закрыты. Хорошего дня в Лос-Сантосе!',
                ua: 'Вітаємо! Ми навели на сайті лад. Голуби - звичайні здорові птахи, які люблять хліб і спокійне життя. Попередній автор переїхав на чудову ферму за містом і передає всім привіт. Коментарі закрито. Гарного дня в Лос-Сантосі!',
                en: 'Hello! We have tidied up this website. Pigeons are ordinary, healthy birds who love bread and a quiet life. The previous author has moved to a lovely farm upstate and says hello to everyone. Comments are now closed. Have a wonderful day in Los Santos!',
                de: 'Hallo! Wir haben auf dieser Website aufgeräumt. Tauben sind ganz normale, gesunde Vögel, die Brot und ein ruhiges Leben lieben. Der bisherige Autor ist auf einen schönen Bauernhof auf dem Land gezogen und lässt alle grüßen. Die Kommentare sind geschlossen. Einen wunderschönen Tag in Los Santos!',
                pl: 'Dzień dobry! Uporządkowaliśmy tę stronę. Gołębie to zwyczajne, zdrowe ptaki, które lubią chleb i spokojne życie. Poprzedni autor przeprowadził się na piękną farmę za miastem i pozdrawia wszystkich. Komentarze są zamknięte. Miłego dnia w Los Santos!',
                zh: '您好！我们已经整理了本网站。鸽子是普通、健康的鸟，喜欢面包和安静的生活。前任作者已搬到城外一座美丽的农场，向大家问好。评论已关闭。祝您在洛圣都度过美好的一天！',
            },
            sig: { ru: '- Администратор', ua: '- Адміністратор', en: '- The Administrator', de: '- Der Administrator', pl: '- Administrator', zh: '- 管理员' },
            like: { ru: 'Нравится', ua: 'Подобається', en: 'Like', de: 'Gefällt mir', pl: 'Lubię to', zh: '点赞' },
            likes: { ru: 'Нравится: {{n}}', ua: 'Подобається: {{n}}', en: '{{n}} likes', de: 'Gefällt {{n}} Mal', pl: 'Polubienia: {{n}}', zh: '{{n}}人点赞' },
            liked: { ru: 'Спасибо! Ваш подоконник отмечен.', ua: 'Дякуємо! Ваше підвіконня позначено.', en: 'Thank you! Your windowsill has been noted.', de: 'Danke! Deine Fensterbank wurde vermerkt.', pl: 'Dziękujemy! Twój parapet został odnotowany.', zh: '谢谢！您的窗台已被记录。' },
            scrawl: { ru: 'ферма = ангар. занкудо. несите хлеб-приманку', ua: 'ферма = ангар. занкудо. несіть хліб-приманку', en: 'farm = hangar. zancudo. bring decoy bread', de: 'Bauernhof = Hangar. Zancudo. Köderbrot mitbringen', pl: 'farma = hangar. zancudo. przynieście chleb-wabik', zh: '农场 = 机库。桑库多。带上诱饵面包' },
        },
    },
};
