export default {
    cef: {
        close: {
            ua: 'Закрити',
            ru: 'Закрыть',
            en: 'Close',
            de: 'Schließen',
            pl: 'Zamknij',
            zh: '关闭',
        },
        tuning: {
            installed: {
                ua: 'Є',
                ru: 'Есть',
                en: 'Yes',
                de: 'Ja',
                pl: 'Tak',
                zh: '有',
            },
            notInstalled: {
                ua: 'Немає',
                ru: 'Нету',
                en: 'No',
                de: 'Nein',
                pl: 'Nie',
                zh: '无',
            },
        },
        labels: {
            plate: {
                ua: 'Номер',
                ru: 'Номер',
                en: 'Plate',
                de: 'Kennzeichen',
                pl: 'Tablica',
                zh: '车牌',
            },
            class: {
                ua: 'Клас',
                ru: 'Класс',
                en: 'Class',
                de: 'Klasse',
                pl: 'Klasa',
                zh: '类别',
            },
            engine: {
                ua: 'Тип двигуна',
                ru: 'Тип двигателя',
                en: 'Engine type',
                de: 'Motortyp',
                pl: 'Typ silnika',
                zh: '发动机类型',
            },
            govPrice: {
                ua: 'Держ. ціна',
                ru: 'Гос. цена',
                en: 'Gov. price',
                de: 'Staatspreis',
                pl: 'Cena państwowa',
                zh: '政府价格',
            },
            mileage: {
                ua: 'Пробіг',
                ru: 'Пробег',
                en: 'Mileage',
                de: 'Laufleistung',
                pl: 'Przebieg',
                zh: '里程',
            },
            tuningPrice: {
                ua: 'Ціна тюнінгу',
                ru: 'Цена тюнинга',
                en: 'Tuning price',
                de: 'Tuning-Preis',
                pl: 'Cena tuningu',
                zh: '改装价格',
            },
            capacity: {
                ua: 'Місткість',
                ru: 'Вместимость',
                en: 'Capacity',
                de: 'Kapazität',
                pl: 'Pojemność',
                zh: '容量',
            },
            owner: {
                ua: 'Власник',
                ru: 'Владелец',
                en: 'Owner',
                de: 'Besitzer',
                pl: 'Właściciel',
                zh: '所有者',
            },
            ownerUnknown: {
                ua: 'Невідомо',
                ru: 'Неизвестно',
                en: 'Unknown',
                de: 'Unbekannt',
                pl: 'Nieznany',
                zh: '未知',
            },
            factionOwner: {
                ua: 'Фракція: {{name}}',
                ru: 'Фракция: {{name}}',
                en: 'Faction: {{name}}',
                de: 'Fraktion: {{name}}',
                pl: 'Frakcja: {{name}}',
                zh: '派系: {{name}}',
            },
            rentOwner: {
                ua: 'Оренда до {{date}}',
                ru: 'Аренда до {{date}}',
                en: 'Rented until {{date}}',
                de: 'Gemietet bis {{date}}',
                pl: 'Wynajęte do {{date}}',
                zh: '租至 {{date}}',
            },
            customColor: {
                ua: 'Кастомний',
                ru: 'Кастомный',
                en: 'Custom',
                de: 'Benutzerdefiniert',
                pl: 'Niestandardowy',
                zh: '自定义',
            },
            noData: {
                ua: '—',
                ru: '—',
                en: '—',
                de: '—',
                pl: '—',
                zh: '—',
            },
            primaryColor: {
                ua: 'Основний колір',
                ru: 'Основной цвет',
                en: 'Primary color',
                de: 'Primärfarbe',
                pl: 'Kolor podstawowy',
                zh: '主要颜色',
            },
            secondaryColor: {
                ua: 'Додатковий колір',
                ru: 'Дополнительный цвет',
                en: 'Secondary color',
                de: 'Sekundärfarbe',
                pl: 'Kolor dodatkowy',
                zh: '次要颜色',
            },
            insurance: {
                ua: 'Страховка',
                ru: 'Страховка',
                en: 'Insurance',
                de: 'Versicherung',
                pl: 'Ubezpieczenie',
                zh: '保险',
            },
            insuranceActive: {
                ua: 'до {{date}}',
                ru: 'до {{date}}',
                en: 'until {{date}}',
                de: 'bis {{date}}',
                pl: 'do {{date}}',
                zh: '至 {{date}}',
            },
            insuranceNone: {
                ua: 'Немає',
                ru: 'Нет',
                en: 'None',
                de: 'Keine',
                pl: 'Brak',
                zh: '无',
            },
        },
        stats: {
            speed: {
                ua: 'Максимальна швидкість',
                ru: 'Максимальная скорость',
                en: 'Max speed',
                de: 'Höchstgeschwindigkeit',
                pl: 'Maksymalna prędkość',
                zh: '最高速度',
            },
            health: {
                ua: 'Міцність',
                ru: 'Прочность',
                en: 'Durability',
                de: 'Haltbarkeit',
                pl: 'Wytrzymałość',
                zh: '耐久度',
            },
            acceleration: {
                ua: 'Розгін',
                ru: 'Разгон',
                en: 'Acceleration',
                de: 'Beschleunigung',
                pl: 'Przyspieszenie',
                zh: '加速',
            },
            fuel: {
                ua: 'Паливо',
                ru: 'Топливо',
                en: 'Fuel',
                de: 'Kraftstoff',
                pl: 'Paliwo',
                zh: '燃料',
            },
            control: {
                ua: 'Керування',
                ru: 'Управление',
                en: 'Control',
                de: 'Steuerung',
                pl: 'Sterowanie',
                zh: '操控',
            },
            trunk: {
                ua: 'Багажник',
                ru: 'Багажник',
                en: 'Trunk',
                de: 'Kofferraum',
                pl: 'Bagażnik',
                zh: '后备箱',
            },
            brakes: {
                ua: 'Гальмування',
                ru: 'Торможение',
                en: 'Braking',
                de: 'Bremsen',
                pl: 'Hamowanie',
                zh: '刹车',
            },
            dirt: {
                ua: 'Забруднення',
                ru: 'Загрязнение',
                en: 'Dirt',
                de: 'Schmutz',
                pl: 'Zabrudzenie',
                zh: '污垢',
            },
        },
        units: {
            kmh: {
                ua: 'км/год',
                ru: 'км/ч',
                en: 'km/h',
                de: 'km/h',
                pl: 'km/h',
                zh: '公里/小时',
            },
            hp: {
                ua: 'HP',
                ru: 'HP',
                en: 'HP',
                de: 'HP',
                pl: 'HP',
                zh: 'HP',
            },
            l: {
                ua: 'л',
                ru: 'л',
                en: 'L',
                de: 'L',
                pl: 'L',
                zh: '升',
            },
            kg: {
                ua: 'кг',
                ru: 'кг',
                en: 'kg',
                de: 'kg',
                pl: 'kg',
                zh: '公斤',
            },
            km: {
                ua: 'км',
                ru: 'км',
                en: 'km',
                de: 'km',
                pl: 'km',
                zh: '公里',
            },
        },
    },
};
