export default {
    // Tank names: the vehicles' own designations, written the way each language writes them.
    names: {
        btr4e: { ru: 'БТР-4Е', ua: 'БТР-4Е', en: 'BTR-4E', de: 'BTR-4E', pl: 'BTR-4E' },
        m3a3: { ru: 'M3A3 Bradley', ua: 'M3A3 Bradley', en: 'M3A3 Bradley', de: 'M3A3 Bradley', pl: 'M3A3 Bradley' },
        pumaifv: { ru: 'Puma', ua: 'Puma', en: 'Puma', de: 'Puma', pl: 'Puma' },
        ajax: { ru: 'Ajax', ua: 'Ajax', en: 'Ajax', de: 'Ajax', pl: 'Ajax' },
        lavusmc: { ru: 'LAV-25', ua: 'LAV-25', en: 'LAV-25', de: 'LAV-25', pl: 'LAV-25' },
        t64b: { ru: 'Т-64БВ', ua: 'Т-64БВ', en: 'T-64BV', de: 'T-64BW', pl: 'T-64BW' },
        t72b3: { ru: 'Т-72Б3', ua: 'Т-72Б3', en: 'T-72B3', de: 'T-72B3', pl: 'T-72B3' },
        strykermgs: { ru: 'Stryker MGS', ua: 'Stryker MGS', en: 'Stryker MGS', de: 'Stryker MGS', pl: 'Stryker MGS' },
        t72b3m: { ru: 'Т-72Б3М', ua: 'Т-72Б3М', en: 'T-72B3M', de: 'T-72B3M', pl: 'T-72B3M' },
        leo2a4: { ru: 'Leopard 2A4', ua: 'Leopard 2A4', en: 'Leopard 2A4', de: 'Leopard 2A4', pl: 'Leopard 2A4' },
        k2panther: { ru: 'K2 Black Panther', ua: 'K2 Black Panther', en: 'K2 Black Panther', de: 'K2 Black Panther', pl: 'K2 Black Panther' },
        t90a: { ru: 'Т-90А', ua: 'Т-90А', en: 'T-90A', de: 'T-90A', pl: 'T-90A' },
        ztz99a: { ru: 'ZTZ-99A', ua: 'ZTZ-99A', en: 'ZTZ-99A', de: 'ZTZ-99A', pl: 'ZTZ-99A' },
        chally2: { ru: 'Challenger 2', ua: 'Challenger 2', en: 'Challenger 2', de: 'Challenger 2', pl: 'Challenger 2' },
        m1sepv2: { ru: 'M1A2 SEP V2', ua: 'M1A2 SEP V2', en: 'M1A2 SEP V2', de: 'M1A2 SEP V2', pl: 'M1A2 SEP V2' },
        leo2pso: { ru: 'Leopard 2 PSO', ua: 'Leopard 2 PSO', en: 'Leopard 2 PSO', de: 'Leopard 2 PSO', pl: 'Leopard 2 PSO' },
        t80bvm: { ru: 'Т-80БВМ', ua: 'Т-80БВМ', en: 'T-80BVM', de: 'T-80BWM', pl: 'T-80BWM' },
        ztz100: { ru: 'ZTZ-100', ua: 'ZTZ-100', en: 'ZTZ-100', de: 'ZTZ-100', pl: 'ZTZ-100' },
        strv122: { ru: 'Strv 122', ua: 'Strv 122', en: 'Strv 122', de: 'Strv 122', pl: 'Strv 122' },
        m1a2c: { ru: 'M1A2C', ua: 'M1A2C', en: 'M1A2C', de: 'M1A2C', pl: 'M1A2C' },
        leo2a7v: { ru: 'Leopard 2A7V', ua: 'Leopard 2A7V', en: 'Leopard 2A7V', de: 'Leopard 2A7V', pl: 'Leopard 2A7V' },
    },
    // Shell kinds as the gun bar and the damage log abbreviate them.
    shells: {
        ap: { ru: 'ББ', ua: 'ББ', en: 'AP', de: 'PzGr', pl: 'AP' },
        apcr: { ru: 'БП', ua: 'БП', en: 'APCR', de: 'HK', pl: 'APCR' },
        heat: { ru: 'КС', ua: 'КС', en: 'HEAT', de: 'HL', pl: 'HEAT' },
        he: { ru: 'ОФ', ua: 'ОФ', en: 'HE', de: 'Spr', pl: 'HE' },
    },
    ribbons: {
        penetration: { ru: 'Пробитие', ua: 'Пробиття', en: 'Penetration', de: 'Durchschlag', pl: 'Przebicie' },
        damage: { ru: 'Урон', ua: 'Шкода', en: 'Damage', de: 'Schaden', pl: 'Obrażenia' },
        critical: { ru: 'Критическое попадание', ua: 'Критичне влучання', en: 'Critical hit', de: 'Kritischer Treffer', pl: 'Trafienie krytyczne' },
        ricochet: { ru: 'Рикошет', ua: 'Рикошет', en: 'Ricochet', de: 'Abpraller', pl: 'Rykoszet' },
        noPenetration: { ru: 'Не пробил', ua: 'Не пробив', en: 'No penetration', de: 'Kein Durchschlag', pl: 'Brak przebicia' },
        blocked: { ru: 'Заблокировано', ua: 'Заблоковано', en: 'Blocked', de: 'Abgewehrt', pl: 'Zablokowano' },
        destroyed: { ru: 'Уничтожен', ua: 'Знищено', en: 'Destroyed', de: 'Zerstört', pl: 'Zniszczony' },
        spotted: { ru: 'Обнаружен', ua: 'Виявлено', en: 'Spotted', de: 'Aufgeklärt', pl: 'Wykryty' },
        assist: { ru: 'Содействие', ua: 'Сприяння', en: 'Assist', de: 'Unterstützung', pl: 'Asysta' },
        capture: { ru: 'Захват', ua: 'Захоплення', en: 'Capture', de: 'Eroberung', pl: 'Przejęcie' },
        defence: { ru: 'Защита базы', ua: 'Захист бази', en: 'Base defence', de: 'Basisverteidigung', pl: 'Obrona bazy' },
    },
    hud: {
        destroyed: { ru: 'Танк уничтожен', ua: 'Танк знищено', en: 'Tank destroyed', de: 'Panzer zerstört', pl: 'Czołg zniszczony' },
        destroyedBy: { ru: 'Уничтожил', ua: 'Знищив', en: 'Destroyed by', de: 'Zerstört von', pl: 'Zniszczony przez' },
        metres: { ru: '{{value}} м', ua: '{{value}} м', en: '{{value}} m', de: '{{value}} m', pl: '{{value}} m' },
        burning: { ru: 'Пожар', ua: 'Пожежа', en: 'Fire', de: 'Brand', pl: 'Pożar' },
        base: {
            ally: { ru: 'Наша база', ua: 'Наша база', en: 'Our base', de: 'Unsere Basis', pl: 'Nasza baza' },
            enemy: { ru: 'База противника', ua: 'База противника', en: 'Enemy base', de: 'Feindliche Basis', pl: 'Baza wroga' },
            neutral: { ru: 'База', ua: 'База', en: 'Base', de: 'Basis', pl: 'Baza' },
        },
    },
};
