export default {
    blip: {
        ru: 'Gruppe 6',
        ua: 'Gruppe 6',
        en: 'Gruppe 6',
        de: 'Gruppe 6',
        pl: 'Gruppe 6',
    },
    loadBlip: {
        ru: 'Кассовый центр Gruppe 6',
        ua: 'Касовий центр Gruppe 6',
        en: 'Gruppe 6 cash centre',
        de: 'Gruppe 6 Geldzentrum',
        pl: 'Centrum gotowkowe Gruppe 6',
    },
    atmBlip: {
        ru: 'Банкомат на маршруте',
        ua: 'Банкомат на маршруті',
        en: 'ATM on the route',
        de: 'Geldautomat auf der Route',
        pl: 'Bankomat na trasie',
    },
    vanBlip: {
        ru: 'Ваш броневик',
        ua: 'Ваш броньовик',
        en: 'Your armoured van',
        de: 'Dein Panzerwagen',
        pl: 'Twoj furgon',
    },
    notifyHeader: {
        ru: 'Gruppe 6',
        ua: 'Gruppe 6',
        en: 'Gruppe 6',
        de: 'Gruppe 6',
        pl: 'Gruppe 6',
    },
    startJob: {
        ru: 'Вы устроились инкассатором Gruppe 6. Первым делом загрузите броневик в кассовом центре',
        ua: 'Ви влаштувалися інкасатором Gruppe 6. Найперше завантажте броньовик у касовому центрі',
        en: 'You are hired as a Gruppe 6 collector. First thing: load the van at a cash centre',
        de: 'Du bist als Gruppe 6 Geldbote eingestellt. Als Erstes: den Wagen im Geldzentrum beladen',
        pl: 'Zostales zatrudniony jako konwojent Gruppe 6. Najpierw zaladuj furgon w centrum gotowkowym',
    },
    loadoutIssued: {
        ru: 'Вам выдано служебное снаряжение. Оно числится за Gruppe 6 и будет сдано в конце смены',
        ua: 'Вам видано службове спорядження. Воно числиться за Gruppe 6 і буде здане наприкінці зміни',
        en: 'Duty gear has been signed out to you. It belongs to Gruppe 6 and goes back at the end of the shift',
        de: 'Dir wurde Dienstausrüstung ausgegeben. Sie gehört Gruppe 6 und wird am Ende der Schicht zurückgegeben',
        pl: 'Wydano ci sprzet sluzbowy. Nalezy do Gruppe 6 i zostanie zdany na koniec zmiany',
    },
    loadoutNoSpace: {
        ru: 'В инвентаре нет места под служебное снаряжение, выходите на смену со своим',
        ua: 'В інвентарі немає місця під службове спорядження, виходите на зміну зі своїм',
        en: 'No room in your inventory for the duty gear - you are going out with your own',
        de: 'Kein Platz im Inventar für die Dienstausrüstung - du gehst mit deiner eigenen raus',
        pl: 'Brak miejsca w ekwipunku na sprzet sluzbowy - wychodzisz na zmiane ze swoim',
    },
    stoppedJob: {
        ru: 'Вы уволились из Gruppe 6',
        ua: 'Ви звільнилися з Gruppe 6',
        en: 'You have quit Gruppe 6',
        de: 'Du hast bei Gruppe 6 gekündigt',
        pl: 'Zrezygnowales z pracy w Gruppe 6',
    },
    joinedCrew: {
        ru: 'Вы присоединились к экипажу броневика',
        ua: 'Ви приєдналися до екіпажу броньовика',
        en: 'You joined the van crew',
        de: 'Du bist der Besatzung des Panzerwagens beigetreten',
        pl: 'Dolaczyles do zalogi furgonu',
    },
    ownerTransferred: {
        ru: 'Броневик закреплён за вами',
        ua: 'Броньовик закріплений за вами',
        en: 'The van is now assigned to you',
        de: 'Der Panzerwagen ist jetzt dir zugeteilt',
        pl: 'Furgon zostal przypisany do ciebie',
    },
    noVan: {
        ru: 'Сейчас нет свободного броневика, попробуйте позже',
        ua: 'Зараз немає вільного броньовика, спробуйте пізніше',
        en: 'There is no van available right now, try again later',
        de: 'Gerade ist kein Panzerwagen frei, versuche es später',
        pl: 'Nie ma teraz wolnego furgonu, sprobuj pozniej',
    },
    vanDestroyed: {
        ru: 'Броневик уничтожен. Смена окончена',
        ua: 'Броньовик знищено. Зміну закінчено',
        en: 'The van is wrecked. The shift is over',
        de: 'Der Panzerwagen ist Schrott. Die Schicht ist vorbei',
        pl: 'Furgon zostal zniszczony. Zmiana skonczona',
    },
    noActivePartySession: {
        ru: 'Никто из вашей пати сейчас не на смене Gruppe 6',
        ua: 'Ніхто з вашої паті зараз не на зміні Gruppe 6',
        en: 'Nobody in your party is on a Gruppe 6 run right now',
        de: 'Niemand aus deiner Gruppe ist gerade auf einer Gruppe 6 Tour',
        pl: 'Nikt z twojej grupy nie jest teraz na trasie Gruppe 6',
    },
    crewFull: {
        ru: 'В броневике уже полный экипаж - {{max}} человека',
        ua: 'У броньовику вже повний екіпаж - {{max}} особи',
        en: 'That van already has a full crew of {{max}}',
        de: 'Der Wagen hat bereits eine volle Besatzung von {{max}}',
        pl: 'Ten furgon ma juz pelna zaloge - {{max}} osoby',
    },
    // Short independent clauses, joined into one line by formatMissingRequirements:
    // the dispatcher's dialog names every blocker at once, so they have to read as a
    // list without agreeing with a carrier sentence.
    requirements: {
        need: {
            level: {
                ru: 'нужен {{level}} уровень',
                ua: 'потрібен {{level}} рівень',
                en: 'you need level {{level}}',
                de: 'du brauchst Level {{level}}',
                pl: 'potrzebujesz poziomu {{level}}',
            },
            driving: {
                ru: 'нет категории C',
                ua: 'немає категорії C',
                en: 'no category C licence',
                de: 'kein Führerschein C',
                pl: 'brak kategorii C',
            },
            military: {
                ru: 'нет военного билета',
                ua: 'немає військового квитка',
                en: 'no military ID',
                de: 'kein Wehrpass',
                pl: 'brak ksiazeczki wojskowej',
            },
            weapon: {
                ru: 'нет лицензии на оружие',
                ua: 'немає ліцензії на зброю',
                en: 'no weapon licence',
                de: 'kein Waffenschein',
                pl: 'brak licencji na bron',
            },
            robbed: {
                ru: 'после потери груза компания не берёт вас на смену ещё {{time}}',
                ua: 'після втрати вантажу компанія не бере вас на зміну ще {{time}}',
                en: 'after losing a load the company will not sign you on for another {{time}}',
                de: 'nach dem Verlust einer Ladung stellt dich die Firma erst in {{time}} wieder ein',
                pl: 'po utracie ladunku firma nie przyjmie cie na zmiane jeszcze przez {{time}}',
            },
        },
        expired: {
            driving: {
                ru: 'категория C просрочена',
                ua: 'категорія C прострочена',
                en: 'your category C licence has expired',
                de: 'dein Führerschein C ist abgelaufen',
                pl: 'kategoria C wygasla',
            },
            military: {
                ru: 'военный билет просрочен',
                ua: 'військовий квиток прострочений',
                en: 'your military ID has expired',
                de: 'dein Wehrpass ist abgelaufen',
                pl: 'ksiazeczka wojskowa wygasla',
            },
            weapon: {
                ru: 'лицензия на оружие просрочена',
                ua: 'ліцензія на зброю прострочена',
                en: 'your weapon licence has expired',
                de: 'dein Waffenschein ist abgelaufen',
                pl: 'licencja na bron wygasla',
            },
        },
    },
    cannotBeHired: {
        ru: 'Оформить не получится: {{missing}}',
        ua: 'Оформити не вийде: {{missing}}',
        en: 'You cannot be signed on: {{missing}}',
        de: 'Einstellen geht nicht: {{missing}}',
        pl: 'Nie mozna cie zapisac: {{missing}}',
    },
    onlyDriverCanLoad: {
        ru: 'Загрузить броневик может только водитель',
        ua: 'Завантажити броньовик може лише водій',
        en: 'Only the driver can load the van',
        de: 'Nur der Fahrer kann den Wagen beladen',
        pl: 'Tylko kierowca moze zaladowac furgon',
    },
    loadingInProgress: {
        ru: 'Броневик уже загружается',
        ua: 'Броньовик уже завантажується',
        en: 'The van is already being loaded',
        de: 'Der Wagen wird bereits beladen',
        pl: 'Furgon jest juz ladowany',
    },
    vanAlreadyFull: {
        ru: 'Броневик уже полон, развезите деньги по банкоматам',
        ua: 'Броньовик уже повний, розвезіть гроші по банкоматах',
        en: 'The van is already full, deliver the cash to the machines',
        de: 'Der Wagen ist bereits voll, bring das Geld zu den Automaten',
        pl: 'Furgon jest juz pelny, rozwiez gotowke do bankomatow',
    },
    loadingStarted: {
        ru: 'Идёт загрузка броневика',
        ua: 'Триває завантаження броньовика',
        en: 'Loading the van',
        de: 'Der Wagen wird beladen',
        pl: 'Trwa zaladunek furgonu',
    },
    loadingProgress: {
        ru: 'Загрузка денег',
        ua: 'Завантаження грошей',
        en: 'Loading cash',
        de: 'Geld wird verladen',
        pl: 'Zaladunek gotowki',
    },
    robberyProgress: {
        ru: 'Вскрытие броневика',
        ua: 'Розкриття броньовика',
        en: 'Cracking the van',
        de: 'Panzerwagen wird aufgebrochen',
        pl: 'Rozbijanie furgonu',
    },
    loadingComplete: {
        ru: 'В броневике {{amount}}. Маршрут выдан',
        ua: 'У броньовику {{amount}}. Маршрут видано',
        en: 'The van holds {{amount}}. Route issued',
        de: 'Im Wagen sind {{amount}}. Route erteilt',
        pl: 'W furgonie jest {{amount}}. Trasa wydana',
    },
    serviceProgress: {
        ru: 'Загрузка банкомата',
        ua: 'Завантаження банкомата',
        en: 'Refilling the ATM',
        de: 'Geldautomat wird befüllt',
        pl: 'Napelnianie bankomatu',
    },
    serviceInterrupted: {
        ru: 'Вы отошли от банкомата, загрузка прервана',
        ua: 'Ви відійшли від банкомата, завантаження перервано',
        en: 'You stepped away from the ATM, the refill is cancelled',
        de: 'Du bist vom Automaten weggegangen, das Befüllen ist abgebrochen',
        pl: 'Odszedles od bankomatu, napelnianie przerwane',
    },
    serviceInProgress: {
        ru: 'Банкомат уже загружает другой инкассатор',
        ua: 'Банкомат уже завантажує інший інкасатор',
        en: 'Another collector is already working that machine',
        de: 'Ein anderer Werttransporteur arbeitet schon an dem Automaten',
        pl: 'Inny konwojent juz obsluguje ten bankomat',
    },
    vanTooFar: {
        ru: 'Броневик слишком далеко. Подгоните его к банкомату (до {{distance}} м)',
        ua: 'Броньовик задалеко. Підженіть його до банкомата (до {{distance}} м)',
        en: 'The van is too far away. Bring it up to the machine (within {{distance}} m)',
        de: 'Der Wagen ist zu weit weg. Fahr ihn an den Automaten heran (bis {{distance}} m)',
        pl: 'Furgon jest za daleko. Podjedz nim do bankomatu (do {{distance}} m)',
    },
    atmServiced: {
        ru: 'Банкомат загружен. Начислено {{money}}',
        ua: 'Банкомат завантажено. Нараховано {{money}}',
        en: 'ATM refilled. You earned {{money}}',
        de: 'Automat befüllt. Du hast {{money}} verdient',
        pl: 'Bankomat napelniony. Zarobiles {{money}}',
    },
    missedPayout: {
        ru: 'Вы были далеко от броневика - за этот банкомат вам не начислено',
        ua: 'Ви були далеко від броньовика - за цей банкомат вам не нараховано',
        en: 'You were away from the van - this machine paid you nothing',
        de: 'Du warst weit weg vom Wagen - dieser Automat hat dir nichts gezahlt',
        pl: 'Byles daleko od furgonu - ten bankomat nic ci nie zaplacil',
    },
    vanEmpty: {
        ru: 'Деньги в броневике закончились. Возвращайтесь в кассовый центр',
        ua: 'Гроші в броньовику закінчилися. Повертайтеся до касового центру',
        en: 'The van is empty. Head back to a cash centre',
        de: 'Der Wagen ist leer. Zurück zum Geldzentrum',
        pl: 'Furgon jest pusty. Wracaj do centrum gotowkowego',
    },
    hud: {
        title: {
            ru: 'Gruppe 6',
            ua: 'Gruppe 6',
            en: 'Gruppe 6',
            de: 'Gruppe 6',
            pl: 'Gruppe 6',
        },
        goLoad: {
            ru: 'Загрузите броневик в кассовом центре',
            ua: 'Завантажте броньовик у касовому центрі',
            en: 'Load the van at a cash centre',
            de: 'Belade den Wagen im Geldzentrum',
            pl: 'Zaladuj furgon w centrum gotowkowym',
        },
        loading: {
            ru: 'Идёт загрузка',
            ua: 'Триває завантаження',
            en: 'Loading',
            de: 'Wird beladen',
            pl: 'Trwa zaladunek',
        },
        goAtm: {
            ru: 'Доедьте до банкомата и загрузите его',
            ua: 'Доїдьте до банкомата і завантажте його',
            en: 'Drive to the ATM and refill it',
            de: 'Fahr zum Automaten und befülle ihn',
            pl: 'Dojedz do bankomatu i napelnij go',
        },
        servicing: {
            ru: 'Загружаете банкомат',
            ua: 'Завантажуєте банкомат',
            en: 'Refilling the ATM',
            de: 'Du befüllst den Automaten',
            pl: 'Napelniasz bankomat',
        },
        vanCash: {
            ru: 'В броневике',
            ua: 'У броньовику',
            en: 'In the van',
            de: 'Im Wagen',
            pl: 'W furgonie',
        },
        serviced: {
            ru: 'Загружено банкоматов',
            ua: 'Завантажено банкоматів',
            en: 'ATMs refilled',
            de: 'Automaten befüllt',
            pl: 'Napelnionych bankomatow',
        },
        earned: {
            ru: 'Заработано',
            ua: 'Зароблено',
            en: 'Earned',
            de: 'Verdient',
            pl: 'Zarobiono',
        },
    },
    dialogMain: {
        hello: {
            ru: 'Здравствуйте. Gruppe 6, депо инкассации. Броневик выдаю под роспись, маршрут получите в кабине. Работа простая: набрали денег в кассовом центре и развезли их по банкоматам.',
            ua: 'Вітаю. Gruppe 6, депо інкасації. Броньовик видаю під розпис, маршрут отримаєте в кабіні. Робота проста: набрали грошей у касовому центрі і розвезли їх по банкоматах.',
            en: 'Good day. Gruppe 6, cash in transit. The van goes out on your signature, the route comes through to your cab. The work is simple: take the cash on at a centre and spread it around the machines.',
            de: 'Guten Tag. Gruppe 6, Geldtransport. Den Wagen gebe ich gegen Unterschrift heraus, die Route kommt in die Kabine. Die Arbeit ist einfach: Geld im Zentrum aufnehmen und auf die Automaten verteilen.',
            pl: 'Dzien dobry. Gruppe 6, konwojowanie gotowki. Furgon wydaje za podpisem, trase dostaniesz do kabiny. Robota jest prosta: nabrac gotowki w centrum i rozwiezc ja po bankomatach.',
        },
        start: {
            ru: 'Хочу работать',
            ua: 'Хочу працювати',
            en: 'I want the job',
            de: 'Ich will den Job',
            pl: 'Chce te prace',
        },
        more: {
            ru: 'Расскажите подробнее',
            ua: 'Розкажіть детальніше',
            en: 'Tell me more',
            de: 'Erzähl mir mehr',
            pl: 'Powiedz wiecej',
        },
        together: {
            ru: 'А можно работать вдвоём?',
            ua: 'А можна працювати вдвох?',
            en: 'Can we work as a pair?',
            de: 'Können wir zu zweit arbeiten?',
            pl: 'Mozna pracowac we dwoje?',
        },
        about: {
            ru: 'Броневик закрепляется за вами на смену, форму выдадим сразу. Едете в кассовый центр, грузите деньги, дальше диспетчерская даёт банкомат за банкоматом. Подошли к машине, загрузили, получили за заказ. Как деньги в броневике кончатся, возвращаетесь за новой загрузкой. Берём только с категорией C, военным билетом и лицензией на оружие.',
            ua: 'Броньовик закріплюється за вами на зміну, форму видамо одразу. Їдете до касового центру, вантажите гроші, далі диспетчерська дає банкомат за банкоматом. Підійшли до машини, завантажили, отримали за замовлення. Щойно гроші в броньовику скінчаться, повертаєтеся по нову загрузку. Беремо лише з категорією C, військовим квитком і ліцензією на зброю.',
            en: 'The van is assigned to you for the shift and the uniform comes with it. You drive to a cash centre, take the money on, and dispatch feeds you one machine after another. Walk up, refill it, get paid for the drop. When the van runs dry you come back for another load. We only hire with a category C licence, a military ID and a weapon licence.',
            de: 'Der Wagen wird dir für die Schicht zugeteilt, die Uniform gibt es dazu. Du fährst ins Geldzentrum, nimmst das Geld auf, und die Leitstelle gibt dir Automat für Automat. Hingehen, befüllen, für den Auftrag kassieren. Ist der Wagen leer, kommst du für eine neue Ladung zurück. Wir stellen nur mit Führerschein C, Wehrpass und Waffenschein ein.',
            pl: 'Furgon jest przypisany do ciebie na zmiane, mundur dostajesz od razu. Jedziesz do centrum gotowkowego, ladujesz pieniadze, a dyspozytornia podaje bankomat za bankomatem. Podchodzisz, napelniasz, dostajesz za zlecenie. Gdy furgon sie oprozni, wracasz po nowy zaladunek. Zatrudniamy tylko z kategoria C, ksiazeczka wojskowa i licencja na bron.',
        },
        aboutCrew: {
            ru: 'Настоятельно советую. Один броневик берёт до четырёх человек: старший расписывается за машину, остальные записываются сюда же и садятся с ним. За каждый банкомат платят всему экипажу, и чем вас больше, тем больше выходит каждому. Но платят только тем, кто был при машине - разбежались по городу, значит работали бесплатно. И держите оружие под рукой: за гружёным броневиком ездят не только мы.',
            ua: 'Наполегливо раджу. Один броньовик бере до чотирьох осіб: старший розписується за машину, решта записуються тут же і сідають з ним. За кожен банкомат платять усьому екіпажу, і чим вас більше, тим більше виходить кожному. Але платять тільки тим, хто був при машині - розбіглися по місту, значить працювали безкоштовно. І тримайте зброю під рукою: за завантаженим броньовиком їздять не тільки ми.',
            en: 'I strongly recommend it. One van takes up to four: the senior man signs for the vehicle, the rest sign on here and ride with him. Every machine pays the whole crew, and the more of you there are the more each one takes. But only those who stayed with the van get paid - scatter across the city and you worked for free. And keep your weapons handy: we are not the only ones following a loaded van.',
            de: 'Ich empfehle es dringend. Ein Wagen nimmt bis zu vier: der Ältere unterschreibt für das Fahrzeug, der Rest meldet sich hier an und fährt mit. Jeder Automat zahlt der ganzen Besatzung, und je mehr ihr seid, desto mehr bekommt jeder. Aber bezahlt wird nur, wer beim Wagen geblieben ist - verteilt euch über die Stadt und ihr habt umsonst gearbeitet. Und haltet die Waffen bereit: nicht nur wir folgen einem beladenen Wagen.',
            pl: 'Goraco polecam. Jeden furgon bierze do czterech osob: starszy podpisuje sie za pojazd, reszta zapisuje sie tutaj i jedzie z nim. Za kazdy bankomat placi sie calej zalodze, a im wiecej was jest, tym wiecej dostaje kazdy. Ale placa tylko tym, ktorzy zostali przy furgonie - rozejdziecie sie po miescie i pracowaliscie za darmo. I trzymajcie bron pod reka: nie tylko my jezdzimy za zaladowanym furgonem.',
        },
        understand: {
            ru: 'Понятно',
            ua: 'Зрозуміло',
            en: 'Got it',
            de: 'Verstanden',
            pl: 'Jasne',
        },
        confirmStart: {
            ru: 'Броневик и форму выдам сразу. Оформляем?',
            ua: 'Броньовик і форму видам одразу. Оформлюємо?',
            en: 'I will issue the van and the uniform right away. Shall I sign you on?',
            de: 'Wagen und Uniform gebe ich sofort heraus. Soll ich dich eintragen?',
            pl: 'Furgon i mundur wydam od razu. Zapisuje cie?',
        },
        yes: {
            ru: 'Да, оформляйте',
            ua: 'Так, оформлюйте',
            en: 'Yes, sign me on',
            de: 'Ja, trag mich ein',
            pl: 'Tak, zapisz mnie',
        },
        later: {
            ru: 'Я подумаю',
            ua: 'Я подумаю',
            en: 'I will think about it',
            de: 'Ich überlege es mir',
            pl: 'Zastanowie sie',
        },
        no: {
            ru: 'Не сейчас',
            ua: 'Не зараз',
            en: 'Not now',
            de: 'Nicht jetzt',
            pl: 'Nie teraz',
        },
        bye: {
            ru: 'Как надумаете, Gruppe 6 на месте. Всего доброго.',
            ua: 'Як надумаєте, Gruppe 6 на місці. Усього доброго.',
            en: 'Gruppe 6 is not going anywhere. Good day to you.',
            de: 'Gruppe 6 läuft dir nicht weg. Einen schönen Tag noch.',
            pl: 'Gruppe 6 nigdzie nie ucieknie. Milego dnia.',
        },
        byeAnswer: {
            ru: 'До свидания',
            ua: 'До побачення',
            en: 'Goodbye',
            de: 'Auf Wiedersehen',
            pl: 'Do widzenia',
        },
    },
    dialogLeave: {
        wantLeave: {
            ru: 'Хотите сдать смену и вернуть броневик?',
            ua: 'Хочете здати зміну і повернути броньовик?',
            en: 'Do you want to end the shift and hand the van back?',
            de: 'Willst du die Schicht beenden und den Wagen zurückgeben?',
            pl: 'Chcesz zakonczyc zmiane i oddac furgon?',
        },
        yes: {
            ru: 'Да',
            ua: 'Так',
            en: 'Yes',
            de: 'Ja',
            pl: 'Tak',
        },
        no: {
            ru: 'Нет',
            ua: 'Ні',
            en: 'No',
            de: 'Nein',
            pl: 'Nie',
        },
    },
    dialogRequirements: {
        refused: {
            ru: 'Броневик выдаю только по полному пакету, тут чужие деньги возят. По вам: {{missing}}. Что объяснить подробнее?',
            ua: 'Броньовик видаю лише за повним пакетом, тут возять чужі гроші. По вас: {{missing}}. Що пояснити докладніше?',
            en: 'The van goes out on a complete file only, it is other people money in there. On you: {{missing}}. What shall I go over?',
            de: 'Den Wagen gebe ich nur bei vollständigen Papieren heraus, da ist fremdes Geld drin. Bei dir: {{missing}}. Was soll ich erklären?',
            pl: 'Furgon wydaje tylko przy komplecie papierow, wozi sie tam cudze pieniadze. U ciebie: {{missing}}. Co mam wyjasnic?',
        },
        // Keyed by requirement id: the answer list is generated from the missing ones.
        ask: {
            level: {
                ru: 'А что не так с уровнем?',
                ua: 'А що не так із рівнем?',
                en: 'What is wrong with my level?',
                de: 'Was stimmt mit meinem Level nicht?',
                pl: 'Co jest nie tak z moim poziomem?',
            },
            driving: {
                ru: 'Где получить категорию C?',
                ua: 'Де отримати категорію C?',
                en: 'Where do I get a category C licence?',
                de: 'Wo bekomme ich den Führerschein C?',
                pl: 'Gdzie zdobyc kategorie C?',
            },
            military: {
                ru: 'Где взять военный билет?',
                ua: 'Де взяти військовий квиток?',
                en: 'Where do I get a military ID?',
                de: 'Wo bekomme ich einen Wehrpass?',
                pl: 'Gdzie zdobyc ksiazeczke wojskowa?',
            },
            weapon: {
                ru: 'Где получить лицензию на оружие?',
                ua: 'Де отримати ліцензію на зброю?',
                en: 'Where do I get a weapon licence?',
                de: 'Wo bekomme ich einen Waffenschein?',
                pl: 'Gdzie zdobyc licencje na bron?',
            },
        },
        aboutLevel: {
            ru: 'Тут дело не в бумаге. Броневик тяжёлый, маршрут по всему городу, и в кузове чужие деньги. Наберите {{level}} уровень, тогда и поговорим.',
            ua: 'Тут річ не в папері. Броньовик важкий, маршрут по всьому місту, і в кузові чужі гроші. Наберіть {{level}} рівень, тоді й поговоримо.',
            en: 'This one is not about paper. The van is heavy, the route runs across the whole city, and the load is other people money. Reach level {{level}} and we will talk.',
            de: 'Das ist keine Frage des Papiers. Der Wagen ist schwer, die Route geht durch die ganze Stadt, und geladen ist fremdes Geld. Komm auf Level {{level}}, dann reden wir.',
            pl: 'Tu nie chodzi o papier. Furgon jest ciezki, trasa idzie przez cale miasto, a w srodku sa cudze pieniadze. Zdobadz poziom {{level}}, wtedy pogadamy.',
        },
        aboutDriving: {
            ru: 'Броневик - это грузовик, без категории {{category}} за руль не пущу. Автошкола в Пуэрто-дель-Соль, у самого пляжа: сначала теория, потом город. Экзамен стоит {{price}}. Просроченную категорию там же и продлевают.',
            ua: 'Броньовик - це вантажівка, без категорії {{category}} за кермо не пущу. Автошкола в Пуерто-дель-Соль, біля самого пляжу: спершу теорія, потім місто. Іспит коштує {{price}}. Прострочену категорію там само й продовжують.',
            en: 'The van is a truck, and without a category {{category}} licence you are not driving it. The driving school is in Puerto Del Sol, right by the beach: theory first, then the road. The exam costs {{price}}. A lapsed category is renewed in the same place.',
            de: 'Der Wagen ist ein Lkw, ohne Führerschein {{category}} setzt du dich nicht ans Steuer. Die Fahrschule ist in Puerto Del Sol, direkt am Strand: erst Theorie, dann Stadtfahrt. Die Prüfung kostet {{price}}. Eine abgelaufene Klasse wird dort ebenfalls verlängert.',
            pl: 'Furgon to ciezarowka, bez kategorii {{category}} za kolko cie nie wpuszcze. Szkola jazdy jest w Puerto Del Sol, przy samej plazy: najpierw teoria, potem miasto. Egzamin kosztuje {{price}}. Wygasla kategorie odnawia sie w tym samym miejscu.',
        },
        aboutMilitary: {
            ru: 'Военный билет выписывает Национальная гвардия. Езжайте на базу Форт-Занкудо, к КПП, и спрашивайте дежурного - оформят и внесут в базу. Билет получаете один раз, продлевать его не надо.',
            ua: 'Військовий квиток виписує Національна гвардія. Їдьте на базу Форт-Занкудо, до КПП, і питайте чергового - оформлять і внесуть у базу. Квиток отримуєте один раз, продовжувати його не треба.',
            en: 'The military ID is issued by the National Guard. Drive out to Fort Zancudo, go to the gate and ask for the duty officer - they will write it up and put you on file. You get it once, there is nothing to renew.',
            de: 'Den Wehrpass stellt die Nationalgarde aus. Fahr raus nach Fort Zancudo, ans Tor, und frag nach dem Diensthabenden - der schreibt ihn aus und trägt dich ein. Den bekommst du einmal, verlängern musst du nichts.',
            pl: 'Ksiazeczke wojskowa wystawia Gwardia Narodowa. Jedz do Fort Zancudo, na brame, i pytaj o dyzurnego - wypisza ja i wpisza cie do rejestru. Dostajesz ja raz, nie trzeba jej odnawiac.',
        },
        aboutWeapon: {
            ru: 'Лицензию на оружие выдаёт полиция. Участок на Мишн-Роу в центре или офис шерифа в Палето-Бэй. Там же её и продлевают - лицензия не вечная, следите за датой.',
            ua: 'Ліцензію на зброю видає поліція. Дільниця на Мішн-Роу в центрі або офіс шерифа в Палето-Бей. Там само її й продовжують - ліцензія не вічна, стежте за датою.',
            en: 'The weapon licence comes from the police. The Mission Row station downtown, or the sheriff office in Paleto Bay. They renew it there too - it does not last forever, so watch the date.',
            de: 'Den Waffenschein gibt die Polizei aus. Die Wache in Mission Row in der Innenstadt oder das Sheriff-Büro in Paleto Bay. Dort wird er auch verlängert - er gilt nicht ewig, achte auf das Datum.',
            pl: 'Licencje na bron wydaje policja. Komisariat na Mission Row w centrum albo biuro szeryfa w Paleto Bay. Tam tez sie ja odnawia - nie jest wieczna, pilnuj daty.',
        },
        back: {
            ru: 'Ещё вопрос',
            ua: 'Ще питання',
            en: 'One more question',
            de: 'Noch eine Frage',
            pl: 'Jeszcze jedno pytanie',
        },
        understand: {
            ru: 'Понятно',
            ua: 'Зрозуміло',
            en: 'Got it',
            de: 'Verstanden',
            pl: 'Jasne',
        },
    },
    robbery: {
        alreadyRunning: {
            ru: 'Броневик уже вскрывают',
            ua: 'Броньовик уже розкривають',
            en: 'This van is already being cracked',
            de: 'Dieser Wagen wird bereits aufgebrochen',
            pl: 'Ten furgon jest juz rozbijany',
        },
        notAllowed: {
            ru: 'Такими делами занимаются банды и семьи с нужными связями',
            ua: 'Такими справами займаються банди та сімʼї з потрібними звʼязками',
            en: 'This is work for gangs and families with the right connections',
            de: 'Das ist Sache von Gangs und Familien mit den richtigen Verbindungen',
            pl: 'To robota dla gangow i rodzin z odpowiednimi ukladami',
        },
        needMask: {
            ru: 'С открытым лицом на инкассацию не выходят',
            ua: 'З відкритим обличчям на інкасацію не виходять',
            en: 'Nobody hits a cash van with their face showing',
            de: 'Mit offenem Gesicht ueberfaellt niemand einen Geldtransporter',
            pl: 'Nikt nie napada na konwoj z odslonieta twarza',
        },
        greenZone: {
            ru: 'Здесь слишком людно, вас разнимут раньше, чем вы вскроете дверь',
            ua: 'Тут надто людно, вас рознімуть раніше, ніж ви розкриєте двері',
            en: 'Too many eyes here - you would be pulled apart before the door gives',
            de: 'Hier sind zu viele Augen - man wuerde euch trennen, bevor die Tuer aufgeht',
            pl: 'Za duzo oczu - rozdziela was, zanim drzwi puszcza',
        },
        companyGround: {
            ru: 'Слишком близко к объектам Gruppe 6, здесь своя охрана',
            ua: 'Занадто близько до обʼєктів Gruppe 6, тут своя охорона',
            en: 'Too close to Gruppe 6 property - they have their own security here',
            de: 'Zu nah an Gruppe-6-Objekten - hier hat die Firma eigene Wachen',
            pl: 'Za blisko obiektow Gruppe 6 - tu maja wlasna ochrone',
        },
        vanMoving: {
            ru: 'Броневик надо сначала остановить',
            ua: 'Броньовик треба спершу зупинити',
            en: 'The van has to be stopped first',
            de: 'Der Wagen muss zuerst gestoppt werden',
            pl: 'Furgon trzeba najpierw zatrzymac',
        },
        vanEmpty: {
            ru: 'Броневик пустой, брать нечего',
            ua: 'Броньовик порожній, брати нема чого',
            en: 'The van is empty, there is nothing to take',
            de: 'Der Wagen ist leer, es gibt nichts zu holen',
            pl: 'Furgon jest pusty, nie ma czego brac',
        },
        vanUntouched: {
            ru: 'Этот броневик ещё не сделал ни одной выдачи. Слишком похоже на подставу',
            ua: 'Цей броньовик ще не зробив жодної видачі. Надто схоже на підставу',
            en: 'This van has not made a single delivery yet - that looks staged',
            de: 'Dieser Wagen hat noch keine einzige Auslieferung gemacht - das wirkt gestellt',
            pl: 'Ten furgon nie zrobil jeszcze zadnej dostawy - to wyglada na ustawke',
        },
        noPolice: {
            ru: 'Сейчас на улицах слишком мало полиции, шума никто не заметит. Нужно минимум {{count}} на смене',
            ua: 'Зараз на вулицях замало поліції, шуму ніхто не помітить. Потрібно щонайменше {{count}} на зміні',
            en: 'Too few police on the streets right now - at least {{count}} have to be on duty',
            de: 'Zu wenig Polizei auf den Strassen - mindestens {{count}} muessen im Dienst sein',
            pl: 'Za malo policji na ulicach - potrzeba co najmniej {{count}} na sluzbie',
        },
        crewNotSubdued: {
            ru: 'Инкассаторы у машины ещё на ногах. Пока они не подняли руки или не легли, к дверям не подойти',
            ua: 'Інкасатори біля машини ще на ногах. Поки вони не підняли руки або не лягли, до дверей не підійти',
            en: 'The collectors at the van are still on their feet - hands up or down, until then the doors stay shut',
            de: 'Die Geldboten am Wagen stehen noch - erst mit erhobenen Haenden oder am Boden geht es an die Tueren',
            pl: 'Konwojenci przy furgonie wciaz stoja - dopoki nie podniosa rak albo nie padna, drzwi zostaja zamkniete',
        },
        needParty: {
            ru: 'В одиночку броневик не вскрыть, соберите группу',
            ua: 'Наодинці броньовик не розкрити, зберіть групу',
            en: 'Nobody cracks a van alone - get a party together',
            de: 'Allein knackt niemand einen Panzerwagen - stell eine Gruppe zusammen',
            pl: 'Sam nie rozbijesz furgonu - zbierz grupe',
        },
        minCrew: {
            ru: 'У машины должно стоять минимум {{count}} человек из вашей группы',
            ua: 'Біля машини має стояти щонайменше {{count}} осіб з вашої групи',
            en: 'At least {{count}} of your party have to be standing at the van',
            de: 'Mindestens {{count}} aus deiner Gruppe muessen am Wagen stehen',
            pl: 'Przy furgonie musi stac co najmniej {{count}} osob z twojej grupy',
        },
        partyNotAllowed: {
            ru: 'Не у всех в группе есть право на такие дела',
            ua: 'Не всі в групі мають право на такі справи',
            en: 'Not everyone in your party is cleared for this kind of work',
            de: 'Nicht jeder in deiner Gruppe darf bei so etwas mitmachen',
            pl: 'Nie kazdy w twojej grupie ma prawo do takiej roboty',
        },
        partyOnShift: {
            ru: 'Кто-то из вашей группы сам работает инкассатором',
            ua: 'Хтось із вашої групи сам працює інкасатором',
            en: 'Someone in your party is working as a collector themselves',
            de: 'Jemand aus deiner Gruppe arbeitet selbst als Geldbote',
            pl: 'Ktos z twojej grupy sam pracuje jako konwojent',
        },
        partyCooldown: {
            ru: 'Кто-то из группы недавно уже брал броневик. Ждать ещё {{time}}',
            ua: 'Хтось із групи нещодавно вже брав броньовик. Чекати ще {{time}}',
            en: 'Someone in your party has taken a van recently - {{time}} left',
            de: 'Jemand aus deiner Gruppe hat erst kuerzlich einen Wagen genommen - noch {{time}}',
            pl: 'Ktos z grupy niedawno bral juz furgon - zostalo {{time}}',
        },
        staged: {
            ru: 'Слишком тесные связи с этим экипажем. Такое ограбление никто не купит',
            ua: 'Занадто тісні звʼязки з цим екіпажем. Таке пограбування ніхто не купить',
            en: 'Too close to this crew - nobody would buy that robbery',
            de: 'Zu enge Verbindungen zu dieser Besatzung - den Ueberfall kauft euch keiner ab',
            pl: 'Zbyt bliskie powiazania z ta zaloga - nikt w ten napad nie uwierzy',
        },
        tooFar: {
            ru: 'Подойдите к броневику ближе - не дальше {{distance}} м',
            ua: 'Підійдіть до броньовика ближче - не далі {{distance}} м',
            en: 'Get closer to the van - no further than {{distance}} m',
            de: 'Geh naeher an den Wagen - nicht weiter als {{distance}} m',
            pl: 'Podejdz blizej furgonu - nie dalej niz {{distance}} m',
        },
        started: {
            ru: 'Вскрытие началось. Держитесь у броневика ({{distance}} м) {{seconds}} сек. Если кто-то из группы умрёт или выйдет из зоны - всё сорвётся',
            ua: 'Розкриття почалося. Тримайтеся біля броньовика ({{distance}} м) {{seconds}} сек. Якщо хтось із групи помре або вийде із зони - усе зірветься',
            en: 'The van is being cracked. Hold at it (within {{distance}} m) for {{seconds}} s - if anyone in the party dies or leaves the ring, it falls apart',
            de: 'Der Wagen wird aufgebrochen. Haltet euch {{seconds}} s am Wagen ({{distance}} m) - stirbt jemand aus der Gruppe oder verlaesst den Ring, ist alles hin',
            pl: 'Rozbijanie furgonu ruszylo. Trzymajcie sie przy nim ({{distance}} m) przez {{seconds}} s - jesli ktos z grupy zginie albo wyjdzie ze strefy, wszystko przepadnie',
        },
        underAttack: {
            ru: 'Броневик вскрывают! Держитесь до приезда полиции',
            ua: 'Броньовик розкривають! Тримайтеся до приїзду поліції',
            en: 'Your van is being cracked open! Hold out until the police arrive',
            de: 'Euer Wagen wird aufgebrochen! Haltet durch, bis die Polizei da ist',
            pl: 'Wasz furgon jest rozbijany! Wytrzymajcie do przyjazdu policji',
        },
        share: {
            ru: 'Ваша доля с броневика: {{amount}} грязными',
            ua: 'Ваша частка з броньовика: {{amount}} брудними',
            en: 'Your share of the van: {{amount}} in dirty money',
            de: 'Dein Anteil am Wagen: {{amount}} in schmutzigem Geld',
            pl: 'Twoja dzialka z furgonu: {{amount}} w brudnej kasie',
        },
        failed: {
            ru: 'Взять груз не вышло',
            ua: 'Взяти вантаж не вийшло',
            en: 'The load got away',
            de: 'Die Ladung ist euch entkommen',
            pl: 'Ladunek wam uciekl',
        },
        heldOff: {
            ru: 'Груз остался при вас. Ограбление сорвалось',
            ua: 'Вантаж лишився при вас. Пограбування зірвалося',
            en: 'The load stayed with you - the robbery fell apart',
            de: 'Die Ladung bleibt bei euch - der Ueberfall ist geplatzt',
            pl: 'Ladunek zostal przy was - napad sie rozsypal',
        },
        penalty: {
            ru: 'Груз потерян. Выплата за смену удержана: {{amount}}. На смену вас не возьмут ещё {{time}}',
            ua: 'Вантаж втрачено. Виплату за зміну утримано: {{amount}}. На зміну вас не візьмуть ще {{time}}',
            en: 'The load is gone. Your shift pay is withheld: {{amount}}. The depot will not sign you on for another {{time}}',
            de: 'Die Ladung ist weg. Deine Schichtverguetung wird einbehalten: {{amount}}. Das Depot stellt dich erst in {{time}} wieder ein',
            pl: 'Ladunek przepadl. Wyplata za zmiane zostala wstrzymana: {{amount}}. Depot nie przyjmie cie jeszcze przez {{time}}',
        },
    },
    dialogPartyJoin: {
        memberWorking: {
            ru: 'Ваш напарник из пати уже расписался за броневик. Могу записать вас вторым номером в тот же экипаж. Присоединяетесь?',
            ua: 'Ваш напарник із паті вже розписався за броньовик. Можу записати вас другим номером у той самий екіпаж. Приєднуєтеся?',
            en: 'Someone in your party has already signed for a van. I can put you on the same crew as the second man. Joining?',
            de: 'Jemand aus deiner Gruppe hat bereits für einen Wagen unterschrieben. Ich kann dich als zweiten Mann auf dieselbe Besatzung setzen. Machst du mit?',
            pl: 'Ktos z twojej grupy juz podpisal sie za furgon. Moge wpisac cie jako drugiego do tej samej zalogi. Dolaczasz?',
        },
        joinYes: {
            ru: 'Да, присоединиться',
            ua: 'Так, приєднатися',
            en: 'Yes, join',
            de: 'Ja, beitreten',
            pl: 'Tak, dolacz',
        },
        joinNo: {
            ru: 'Нет, позже',
            ua: 'Ні, пізніше',
            en: 'No, later',
            de: 'Nein, später',
            pl: 'Nie, pozniej',
        },
    },
};
