export default {
    header: {
        ru: 'Подарок',
        ua: 'Подарунок',
        en: 'Gift',
        de: 'Geschenk',
        pl: 'Podarunek',
        zh: '以及“礼物',
    },
    winning: {
        ru: 'Вы выиграли - ',
        ua: 'Ви виграли - ',
        en: 'You won - ',
        de: 'Sie haben gewonnen - ',
        pl: 'Wygrałeś - ',
        zh: '你赢了',
    },
    prizes: {
        exp: {
            ru: 'опыт',
            ua: 'досвід',
            en: 'experience',
            de: 'Erfahrung',
            pl: 'doświadczenie',
            zh: '经验',
        },
        cash: {
            ru: 'деньги',
            ua: 'гроші',
            en: 'money',
            de: 'Geld',
            pl: 'pieniądze',
            zh: '钱',
        },
        item: {
            ru: 'случайный предмет',
            ua: 'випадковий предмет',
            en: 'mystery item',
            de: 'Überraschungsgegenstand',
            pl: 'przedmiot tajemnicy',
            zh: '神秘物品',
        },
        donate: {
            ru: 'донат-валюту',
            ua: 'донат-валюту',
            en: 'donation currency',
            de: 'Spendenwährung',
            pl: 'waluta darowizn',
            zh: '捐赠货币',
        },
    },
};
