export default {
    addText: {
        ru: 'Надпись',
        ua: 'Напис',
        en: 'Text',
        de: 'Text',
        pl: 'Napis',
    },
    addLogo: {
        ru: 'Логотип',
        ua: 'Логотип',
        en: 'Logo',
        de: 'Logo',
        pl: 'Logo',
    },
    text: {
        ru: 'Надпись',
        ua: 'Напис',
        en: 'Text',
        de: 'Text',
        pl: 'Napis',
    },
    textPlaceholder: {
        ru: 'Текст вывески',
        ua: 'Текст вивіски',
        en: 'Sign text',
        de: 'Schildtext',
        pl: 'Tekst szyldu',
    },
    sticker: {
        ru: 'Наклейка',
        ua: 'Наліпка',
        en: 'Sticker',
        de: 'Sticker',
        pl: 'Naklejka',
    },
    replaceSticker: {
        ru: 'Заменить наклейку',
        ua: 'Замінити наліпку',
        en: 'Replace sticker',
        de: 'Sticker ersetzen',
        pl: 'Zmień naklejkę',
    },
    shape: {
        ru: 'Фигура',
        ua: 'Фігура',
        en: 'Shape',
        de: 'Form',
        pl: 'Kształt',
    },
    search: {
        ru: 'Поиск',
        ua: 'Пошук',
        en: 'Search',
        de: 'Suche',
        pl: 'Szukaj',
    },
    nothingFound: {
        ru: 'Ничего не найдено',
        ua: 'Нічого не знайдено',
        en: 'Nothing found',
        de: 'Nichts gefunden',
        pl: 'Nic nie znaleziono',
    },
    categories: {
        geometry: {
            ru: 'Геометрия',
            ua: 'Геометрія',
            en: 'Geometry',
            de: 'Geometrie',
            pl: 'Geometria',
        },
        gradient: {
            ru: 'Градиенты',
            ua: 'Градієнти',
            en: 'Gradients',
            de: 'Verläufe',
            pl: 'Gradienty',
        },
        patterns: {
            ru: 'Узоры',
            ua: 'Візерунки',
            en: 'Patterns',
            de: 'Muster',
            pl: 'Wzory',
        },
        effects: {
            ru: 'Эффекты',
            ua: 'Ефекти',
            en: 'Effects',
            de: 'Effekte',
            pl: 'Efekty',
        },
        material: {
            ru: 'Текстуры',
            ua: 'Текстури',
            en: 'Materials',
            de: 'Materialien',
            pl: 'Materiały',
        },
        anime: {
            ru: 'Аниме',
            ua: 'Аніме',
            en: 'Anime',
            de: 'Anime',
            pl: 'Anime',
        },
        sticker: {
            ru: 'Наклейки',
            ua: 'Наліпки',
            en: 'Stickers',
            de: 'Sticker',
            pl: 'Naklejki',
        },
    },
    shapes: {
        rect: {
            ru: 'Прямоугольник',
            ua: 'Прямокутник',
            en: 'Rectangle',
            de: 'Rechteck',
            pl: 'Prostokąt',
        },
        line: {
            ru: 'Линия',
            ua: 'Лінія',
            en: 'Line',
            de: 'Linie',
            pl: 'Linia',
        },
        circle: {
            ru: 'Круг',
            ua: 'Коло',
            en: 'Circle',
            de: 'Kreis',
            pl: 'Koło',
        },
        ring: {
            ru: 'Кольцо',
            ua: 'Кільце',
            en: 'Ring',
            de: 'Ring',
            pl: 'Pierścień',
        },
        halfCircle: {
            ru: 'Полукруг',
            ua: 'Півколо',
            en: 'Half circle',
            de: 'Halbkreis',
            pl: 'Półkole',
        },
        triangle: {
            ru: 'Треугольник',
            ua: 'Трикутник',
            en: 'Triangle',
            de: 'Dreieck',
            pl: 'Trójkąt',
        },
        diamond: {
            ru: 'Ромб',
            ua: 'Ромб',
            en: 'Diamond',
            de: 'Raute',
            pl: 'Romb',
        },
        pentagon: {
            ru: 'Пятиугольник',
            ua: "П'ятикутник",
            en: 'Pentagon',
            de: 'Fünfeck',
            pl: 'Pięciokąt',
        },
        hexagon: {
            ru: 'Шестиугольник',
            ua: 'Шестикутник',
            en: 'Hexagon',
            de: 'Sechseck',
            pl: 'Sześciokąt',
        },
        octagon: {
            ru: 'Восьмиугольник',
            ua: 'Восьмикутник',
            en: 'Octagon',
            de: 'Achteck',
            pl: 'Ośmiokąt',
        },
        star5: {
            ru: 'Звезда',
            ua: 'Зірка',
            en: 'Star',
            de: 'Stern',
            pl: 'Gwiazda',
        },
        star6: {
            ru: 'Шестиконечная звезда',
            ua: 'Шестикутна зірка',
            en: 'Six-point star',
            de: 'Sechsstrahliger Stern',
            pl: 'Gwiazda sześcioramienna',
        },
        burst: {
            ru: 'Звезда-вспышка',
            ua: 'Зірка-спалах',
            en: 'Starburst',
            de: 'Strahlenstern',
            pl: 'Gwiazda promienista',
        },
        cross: {
            ru: 'Крест',
            ua: 'Хрест',
            en: 'Cross',
            de: 'Kreuz',
            pl: 'Krzyż',
        },
        arrow: {
            ru: 'Стрелка',
            ua: 'Стрілка',
            en: 'Arrow',
            de: 'Pfeil',
            pl: 'Strzałka',
        },
        chevron: {
            ru: 'Шеврон',
            ua: 'Шеврон',
            en: 'Chevron',
            de: 'Chevron',
            pl: 'Szewron',
        },
        shield: {
            ru: 'Щит',
            ua: 'Щит',
            en: 'Shield',
            de: 'Schild',
            pl: 'Tarcza',
        },
        heart: {
            ru: 'Сердце',
            ua: 'Серце',
            en: 'Heart',
            de: 'Herz',
            pl: 'Serce',
        },
        trapezoid: {
            ru: 'Трапеция',
            ua: 'Трапеція',
            en: 'Trapezoid',
            de: 'Trapez',
            pl: 'Trapez',
        },
        parallelogram: {
            ru: 'Параллелограмм',
            ua: 'Паралелограм',
            en: 'Parallelogram',
            de: 'Parallelogramm',
            pl: 'Równoległobok',
        },
    },
    layers: {
        ru: 'Слои',
        ua: 'Шари',
        en: 'Layers',
        de: 'Ebenen',
        pl: 'Warstwy',
    },
    empty: {
        ru: 'Пока пусто',
        ua: 'Поки порожньо',
        en: 'Nothing here yet',
        de: 'Noch leer',
        pl: 'Na razie pusto',
    },
    selected: {
        ru: 'Выбрано: {{count}}',
        ua: 'Обрано: {{count}}',
        en: 'Selected: {{count}}',
        de: 'Ausgewählt: {{count}}',
        pl: 'Wybrano: {{count}}',
    },
    plate: {
        ru: 'Плита',
        ua: 'Плита',
        en: 'Plate',
        de: 'Platte',
        pl: 'Płyta',
    },
    plateHint: {
        ru: 'Выберите слой, чтобы изменить его свойства',
        ua: 'Виберіть шар, щоб змінити його властивості',
        en: 'Select a layer to edit its properties',
        de: 'Ebene wählen, um ihre Eigenschaften zu ändern',
        pl: 'Wybierz warstwę, aby zmienić jej właściwości',
    },
    transform: {
        ru: 'Положение',
        ua: 'Положення',
        en: 'Transform',
        de: 'Position',
        pl: 'Położenie',
    },
    fill: {
        title: {
            ru: 'Заливка',
            ua: 'Заливка',
            en: 'Fill',
            de: 'Füllung',
            pl: 'Wypełnienie',
        },
        solid: {
            ru: 'Сплошная',
            ua: 'Суцільна',
            en: 'Solid',
            de: 'Einfarbig',
            pl: 'Jednolite',
        },
        linear: {
            ru: 'Линейный градиент',
            ua: 'Лінійний градієнт',
            en: 'Linear gradient',
            de: 'Linearer Verlauf',
            pl: 'Gradient liniowy',
        },
        radial: {
            ru: 'Радиальный градиент',
            ua: 'Радіальний градієнт',
            en: 'Radial gradient',
            de: 'Radialer Verlauf',
            pl: 'Gradient promienisty',
        },
        none: {
            ru: 'Нет',
            ua: 'Немає',
            en: 'None',
            de: 'Keine',
            pl: 'Brak',
        },
        angle: {
            ru: 'Угол',
            ua: 'Кут',
            en: 'Angle',
            de: 'Winkel',
            pl: 'Kąt',
        },
    },
    tint: {
        ru: 'Перекраска',
        ua: 'Перефарбування',
        en: 'Recolour',
        de: 'Umfärben',
        pl: 'Przebarwienie',
    },
    tintHint: {
        ru: 'Цвет ложится по силуэту картинки. Сила ниже 100 оставляет её видимой',
        ua: 'Колір лягає по силуету картинки. Сила нижче 100 залишає її видимою',
        en: 'The colour lies along the silhouette; a strength below 100 leaves the picture showing',
        de: 'Die Farbe folgt der Silhouette; unter 100 Stärke bleibt das Bild sichtbar',
        pl: 'Kolor układa się wzdłuż sylwetki; siła poniżej 100 pozostawia obraz widoczny',
    },
    effects: {
        ru: 'Эффекты',
        ua: 'Ефекти',
        en: 'Effects',
        de: 'Effekte',
        pl: 'Efekty',
    },
    addEffect: {
        ru: 'Добавить эффект',
        ua: 'Додати ефект',
        en: 'Add effect',
        de: 'Effekt hinzufügen',
        pl: 'Dodaj efekt',
    },
    removeEffect: {
        ru: 'Убрать эффект',
        ua: 'Прибрати ефект',
        en: 'Remove effect',
        de: 'Effekt entfernen',
        pl: 'Usuń efekt',
    },
    stroke: {
        ru: 'Обводка',
        ua: 'Обведення',
        en: 'Stroke',
        de: 'Kontur',
        pl: 'Obrys',
    },
    strokeWidth: {
        ru: 'Толщина',
        ua: 'Товщина',
        en: 'Width',
        de: 'Stärke',
        pl: 'Grubość',
    },
    shadow: {
        ru: 'Тень',
        ua: 'Тінь',
        en: 'Shadow',
        de: 'Schatten',
        pl: 'Cień',
    },
    blur: {
        ru: 'Размытие',
        ua: 'Розмиття',
        en: 'Blur',
        de: 'Weichzeichnen',
        pl: 'Rozmycie',
    },
    off: {
        ru: 'Выкл',
        ua: 'Вимк',
        en: 'Off',
        de: 'Aus',
        pl: 'Wył',
    },
    radius: {
        ru: 'Скругление',
        ua: 'Заокруглення',
        en: 'Corner radius',
        de: 'Eckenradius',
        pl: 'Zaokrąglenie',
    },
    defaultFont: {
        ru: 'Стандартный',
        ua: 'Стандартний',
        en: 'Default',
        de: 'Standard',
        pl: 'Domyślna',
    },
    italic: {
        ru: 'Курсив',
        ua: 'Курсив',
        en: 'Italic',
        de: 'Kursiv',
        pl: 'Kursywa',
    },
    upper: {
        ru: 'Заглавные',
        ua: 'Великі',
        en: 'Uppercase',
        de: 'Großbuchstaben',
        pl: 'Wielkie litery',
    },
    spacing: {
        ru: 'Межбукв.',
        ua: 'Міжлітер.',
        en: 'Letter sp.',
        de: 'Laufweite',
        pl: 'Odstęp liter',
    },
    lineHeight: {
        ru: 'Междустр.',
        ua: 'Міжрядк.',
        en: 'Line height',
        de: 'Zeilenhöhe',
        pl: 'Interlinia',
    },
    align: {
        left: {
            ru: 'По левому краю',
            ua: 'За лівим краєм',
            en: 'Align left',
            de: 'Linksbündig',
            pl: 'Do lewej',
        },
        center: {
            ru: 'По центру',
            ua: 'По центру',
            en: 'Align center',
            de: 'Zentriert',
            pl: 'Do środka',
        },
        right: {
            ru: 'По правому краю',
            ua: 'За правим краєм',
            en: 'Align right',
            de: 'Rechtsbündig',
            pl: 'Do prawej',
        },
    },
    alignTo: {
        left: {
            ru: 'К левому краю вывески',
            ua: 'До лівого краю вивіски',
            en: 'Align to left edge',
            de: 'Am linken Rand ausrichten',
            pl: 'Do lewej krawędzi',
        },
        centerX: {
            ru: 'По центру по горизонтали',
            ua: 'По центру горизонтально',
            en: 'Align horizontal centre',
            de: 'Horizontal zentrieren',
            pl: 'Wyśrodkuj w poziomie',
        },
        right: {
            ru: 'К правому краю вывески',
            ua: 'До правого краю вивіски',
            en: 'Align to right edge',
            de: 'Am rechten Rand ausrichten',
            pl: 'Do prawej krawędzi',
        },
        top: {
            ru: 'К верхнему краю',
            ua: 'До верхнього краю',
            en: 'Align to top edge',
            de: 'Am oberen Rand ausrichten',
            pl: 'Do górnej krawędzi',
        },
        centerY: {
            ru: 'По центру по вертикали',
            ua: 'По центру вертикально',
            en: 'Align vertical centre',
            de: 'Vertikal zentrieren',
            pl: 'Wyśrodkuj w pionie',
        },
        bottom: {
            ru: 'К нижнему краю',
            ua: 'До нижнього краю',
            en: 'Align to bottom edge',
            de: 'Am unteren Rand ausrichten',
            pl: 'Do dolnej krawędzi',
        },
    },
    distributeH: {
        ru: 'Равные промежутки по горизонтали',
        ua: 'Рівні проміжки горизонтально',
        en: 'Distribute horizontally',
        de: 'Horizontal verteilen',
        pl: 'Rozmieść w poziomie',
    },
    distributeV: {
        ru: 'Равные промежутки по вертикали',
        ua: 'Рівні проміжки вертикально',
        en: 'Distribute vertically',
        de: 'Vertikal verteilen',
        pl: 'Rozmieść w pionie',
    },
    toFront: {
        ru: 'На передний план',
        ua: 'На передній план',
        en: 'Bring to front',
        de: 'In den Vordergrund',
        pl: 'Na wierzch',
    },
    toBack: {
        ru: 'На задний план',
        ua: 'На задній план',
        en: 'Send to back',
        de: 'In den Hintergrund',
        pl: 'Na spód',
    },
    duplicate: {
        ru: 'Дублировать',
        ua: 'Дублювати',
        en: 'Duplicate',
        de: 'Duplizieren',
        pl: 'Duplikuj',
    },
    hide: {
        ru: 'Скрыть слой',
        ua: 'Сховати шар',
        en: 'Hide layer',
        de: 'Ebene ausblenden',
        pl: 'Ukryj warstwę',
    },
    lock: {
        ru: 'Заблокировать слой',
        ua: 'Заблокувати шар',
        en: 'Lock layer',
        de: 'Ebene sperren',
        pl: 'Zablokuj warstwę',
    },
    remove: {
        ru: 'Удалить слой',
        ua: 'Видалити шар',
        en: 'Delete layer',
        de: 'Ebene löschen',
        pl: 'Usuń warstwę',
    },
    flipX: {
        ru: 'Отразить по горизонтали',
        ua: 'Відобразити горизонтально',
        en: 'Flip horizontally',
        de: 'Horizontal spiegeln',
        pl: 'Odbij w poziomie',
    },
    flipY: {
        ru: 'Отразить по вертикали',
        ua: 'Відобразити вертикально',
        en: 'Flip vertically',
        de: 'Vertikal spiegeln',
        pl: 'Odbij w pionie',
    },
    width: {
        ru: 'Ширина',
        ua: 'Ширина',
        en: 'Width',
        de: 'Breite',
        pl: 'Szerokość',
    },
    height: {
        ru: 'Высота',
        ua: 'Висота',
        en: 'Height',
        de: 'Höhe',
        pl: 'Wysokość',
    },
    rotation: {
        ru: 'Поворот',
        ua: 'Поворот',
        en: 'Rotation',
        de: 'Drehung',
        pl: 'Obrót',
    },
    opacity: {
        ru: 'Прозрачность',
        ua: 'Прозорість',
        en: 'Opacity',
        de: 'Deckkraft',
        pl: 'Krycie',
    },
    undo: {
        ru: 'Отменить',
        ua: 'Скасувати',
        en: 'Undo',
        de: 'Rückgängig',
        pl: 'Cofnij',
    },
    redo: {
        ru: 'Вернуть',
        ua: 'Повернути',
        en: 'Redo',
        de: 'Wiederholen',
        pl: 'Ponów',
    },
    zoomIn: {
        ru: 'Приблизить',
        ua: 'Наблизити',
        en: 'Zoom in',
        de: 'Vergrößern',
        pl: 'Powiększ',
    },
    zoomOut: {
        ru: 'Отдалить',
        ua: 'Віддалити',
        en: 'Zoom out',
        de: 'Verkleinern',
        pl: 'Pomniejsz',
    },
    fit: {
        ru: 'Вписать в окно',
        ua: 'Вписати у вікно',
        en: 'Fit to window',
        de: 'An Fenster anpassen',
        pl: 'Dopasuj do okna',
    },
    blend: {
        normal: {
            ru: 'Обычный',
            ua: 'Звичайний',
            en: 'Normal',
            de: 'Normal',
            pl: 'Zwykły',
        },
        multiply: {
            ru: 'Умножение',
            ua: 'Множення',
            en: 'Multiply',
            de: 'Multiplizieren',
            pl: 'Mnożenie',
        },
        screen: {
            ru: 'Экран',
            ua: 'Екран',
            en: 'Screen',
            de: 'Negativ multiplizieren',
            pl: 'Ekran',
        },
        overlay: {
            ru: 'Перекрытие',
            ua: 'Перекриття',
            en: 'Overlay',
            de: 'Ineinanderkopieren',
            pl: 'Nakładka',
        },
        darken: {
            ru: 'Затемнение',
            ua: 'Затемнення',
            en: 'Darken',
            de: 'Abdunkeln',
            pl: 'Ciemniej',
        },
        lighten: {
            ru: 'Замена светлым',
            ua: 'Заміна світлим',
            en: 'Lighten',
            de: 'Aufhellen',
            pl: 'Jaśniej',
        },
        'color-dodge': {
            ru: 'Осветление основы',
            ua: 'Освітлення основи',
            en: 'Color dodge',
            de: 'Farbig abwedeln',
            pl: 'Rozjaśnianie',
        },
        'color-burn': {
            ru: 'Затемнение основы',
            ua: 'Затемнення основи',
            en: 'Color burn',
            de: 'Farbig nachbelichten',
            pl: 'Ściemnianie',
        },
        'hard-light': {
            ru: 'Жёсткий свет',
            ua: 'Жорстке світло',
            en: 'Hard light',
            de: 'Hartes Licht',
            pl: 'Ostre światło',
        },
        'soft-light': {
            ru: 'Мягкий свет',
            ua: "М'яке світло",
            en: 'Soft light',
            de: 'Weiches Licht',
            pl: 'Łagodne światło',
        },
        difference: {
            ru: 'Разница',
            ua: 'Різниця',
            en: 'Difference',
            de: 'Differenz',
            pl: 'Różnica',
        },
        exclusion: {
            ru: 'Исключение',
            ua: 'Виключення',
            en: 'Exclusion',
            de: 'Ausschluss',
            pl: 'Wyłączenie',
        },
        hue: {
            ru: 'Цветовой тон',
            ua: 'Колірний тон',
            en: 'Hue',
            de: 'Farbton',
            pl: 'Barwa',
        },
        saturation: {
            ru: 'Насыщенность',
            ua: 'Насиченість',
            en: 'Saturation',
            de: 'Sättigung',
            pl: 'Nasycenie',
        },
        color: {
            ru: 'Цветность',
            ua: 'Кольоровість',
            en: 'Color',
            de: 'Farbe',
            pl: 'Kolor',
        },
        luminosity: {
            ru: 'Яркость',
            ua: 'Яскравість',
            en: 'Luminosity',
            de: 'Luminanz',
            pl: 'Jasność',
        },
    },
    tintStrength: {
        ru: 'Сила',
        ua: 'Сила',
        en: 'Strength',
        de: 'Stärke',
        pl: 'Siła',
    },
    adjust: {
        title: {
            ru: 'Коррекция',
            ua: 'Корекція',
            en: 'Adjustments',
            de: 'Korrektur',
            pl: 'Korekcja',
        },
        brightness: {
            ru: 'Яркость',
            ua: 'Яскравість',
            en: 'Brightness',
            de: 'Helligkeit',
            pl: 'Jasność',
        },
        contrast: {
            ru: 'Контраст',
            ua: 'Контраст',
            en: 'Contrast',
            de: 'Kontrast',
            pl: 'Kontrast',
        },
        saturate: {
            ru: 'Насыщенность',
            ua: 'Насиченість',
            en: 'Saturation',
            de: 'Sättigung',
            pl: 'Nasycenie',
        },
        hue: {
            ru: 'Оттенок',
            ua: 'Відтінок',
            en: 'Hue',
            de: 'Farbton',
            pl: 'Odcień',
        },
        blur: {
            ru: 'Размытие',
            ua: 'Розмиття',
            en: 'Blur',
            de: 'Weichzeichnen',
            pl: 'Rozmycie',
        },
        grayscale: {
            ru: 'Ч/б',
            ua: 'Ч/б',
            en: 'Grayscale',
            de: 'Graustufen',
            pl: 'Odcienie szarości',
        },
        sepia: {
            ru: 'Сепия',
            ua: 'Сепія',
            en: 'Sepia',
            de: 'Sepia',
            pl: 'Sepia',
        },
        invert: {
            ru: 'Инверсия',
            ua: 'Інверсія',
            en: 'Invert',
            de: 'Invertieren',
            pl: 'Inwersja',
        },
        reset: {
            ru: 'Сбросить коррекцию',
            ua: 'Скинути корекцію',
            en: 'Reset adjustments',
            de: 'Korrektur zurücksetzen',
            pl: 'Zresetuj korekcję',
        },
    },
    contour: {
        title: {
            ru: 'Контур',
            ua: 'Контур',
            en: 'Outline',
            de: 'Kontur',
            pl: 'Kontur',
        },
        width: {
            ru: 'Толщина',
            ua: 'Товщина',
            en: 'Width',
            de: 'Stärke',
            pl: 'Grubość',
        },
    },
    tile: {
        title: {
            ru: 'Сетка копий',
            ua: 'Сітка копій',
            en: 'Tiling',
            de: 'Kachelung',
            pl: 'Kafelki',
        },
        cols: {
            ru: 'Колонки',
            ua: 'Колонки',
            en: 'Columns',
            de: 'Spalten',
            pl: 'Kolumny',
        },
        rows: {
            ru: 'Ряды',
            ua: 'Ряди',
            en: 'Rows',
            de: 'Reihen',
            pl: 'Rzędy',
        },
        gapX: {
            ru: 'Зазор X',
            ua: 'Зазор X',
            en: 'Gap X',
            de: 'Abstand X',
            pl: 'Odstęp X',
        },
        gapY: {
            ru: 'Зазор Y',
            ua: 'Зазор Y',
            en: 'Gap Y',
            de: 'Abstand Y',
            pl: 'Odstęp Y',
        },
        stagger: {
            ru: 'Смещение',
            ua: 'Зміщення',
            en: 'Stagger',
            de: 'Versatz',
            pl: 'Przesunięcie',
        },
    },
    mirror: {
        title: {
            ru: 'Зеркальная копия',
            ua: 'Дзеркальна копія',
            en: 'Mirrored copy',
            de: 'Spiegelkopie',
            pl: 'Kopia lustrzana',
        },
        copy: {
            ru: 'Копия',
            ua: 'Копія',
            en: 'Copy',
            de: 'Kopie',
            pl: 'Kopia',
        },
        axis: {
            x: {
                ru: 'По горизонтали',
                ua: 'По горизонталі',
                en: 'Horizontally',
                de: 'Horizontal',
                pl: 'Poziomo',
            },
            y: {
                ru: 'По вертикали',
                ua: 'По вертикалі',
                en: 'Vertically',
                de: 'Vertikal',
                pl: 'Pionowo',
            },
        },
    },
    mask: {
        title: {
            ru: 'Маска',
            ua: 'Маска',
            en: 'Mask',
            de: 'Maske',
            pl: 'Maska',
        },
        none: {
            ru: 'Без маски',
            ua: 'Без маски',
            en: 'No mask',
            de: 'Ohne Maske',
            pl: 'Bez maski',
        },
        invert: {
            ru: 'Вывернуть маску',
            ua: 'Вивернути маску',
            en: 'Invert the mask',
            de: 'Maske umkehren',
            pl: 'Odwróć maskę',
        },
        eraser: {
            ru: 'Ластик',
            ua: 'Гумка',
            en: 'Eraser',
            de: 'Radierer',
            pl: 'Gumka',
        },
        hint: {
            ru: 'Слой видно только внутри выбранной фигуры или картинки.',
            ua: 'Шар видно лише всередині обраної фігури чи картинки.',
            en: 'The layer only shows inside the chosen shape or picture.',
            de: 'Die Ebene ist nur innerhalb der gewählten Form oder des Bildes sichtbar.',
            pl: 'Warstwa widoczna tylko wewnątrz wybranego kształtu lub obrazka.',
        },
        eraserHint: {
            ru: 'Слой не рисуется, а вырезает свою форму из всего, что под ним.',
            ua: 'Шар не малюється, а вирізає свою форму з усього, що під ним.',
            en: 'The layer is not drawn: it cuts its own shape out of everything below it.',
            de: 'Die Ebene wird nicht gezeichnet, sondern schneidet ihre Form aus allem darunter heraus.',
            pl: 'Warstwa nie jest rysowana - wycina swój kształt ze wszystkiego pod nią.',
        },
    },
    group: {
        title: {
            ru: 'Группа',
            ua: 'Група',
            en: 'Group',
            de: 'Gruppe',
            pl: 'Grupa',
        },
        name: {
            ru: 'Название группы',
            ua: 'Назва групи',
            en: 'Group name',
            de: 'Gruppenname',
            pl: 'Nazwa grupy',
        },
        create: {
            ru: 'Сгруппировать',
            ua: 'Згрупувати',
            en: 'Group',
            de: 'Gruppieren',
            pl: 'Grupuj',
        },
        ungroup: {
            ru: 'Разгруппировать',
            ua: 'Розгрупувати',
            en: 'Ungroup',
            de: 'Gruppierung aufheben',
            pl: 'Rozgrupuj',
        },
    },
    view: {
        grid: {
            ru: 'Сетка',
            ua: 'Сітка',
            en: 'Grid',
            de: 'Raster',
            pl: 'Siatka',
        },
        snap: {
            ru: 'Прилипание',
            ua: 'Прилипання',
            en: 'Snapping',
            de: 'Einrasten',
            pl: 'Przyciąganie',
        },
        step: {
            ru: 'Шаг',
            ua: 'Крок',
            en: 'Step',
            de: 'Schritt',
            pl: 'Krok',
        },
        rulers: {
            ru: 'Линейки',
            ua: 'Лінійки',
            en: 'Rulers',
            de: 'Lineale',
            pl: 'Linijki',
        },
        clearGuides: {
            ru: 'Убрать направляющие',
            ua: 'Прибрати напрямні',
            en: 'Clear the guides',
            de: 'Hilfslinien entfernen',
            pl: 'Usuń prowadnice',
        },
    },
};
