export default {
    title: {
        ru: 'Транспорт фракции',
        ua: 'Транспорт фракції',
        en: 'Faction Vehicles',
        de: 'Fraktionsfahrzeuge',
        pl: 'Pojazdy frakcyjne',
    },
    searchInput: {
        ru: 'Поиск машины по названию',
        ua: 'Пошук машини за назвою',
        en: 'Search for a vehicle by name',
        de: 'Fahrzeug nach Namen suchen',
        pl: 'Szukaj pojazdu po nazwie',
    },
    stats: {
        label: {
            ru: 'Статистика',
            ua: 'Статистика',
            en: 'Statistics',
            de: 'Statistik',
            pl: 'Statystyka',
        },
        speed: {
            ru: 'Скорость',
            ua: 'Швидкість',
            en: 'Speed',
            de: 'Geschwindigkeit',
            pl: 'Prędkość',
        },
        acceleation: {
            ru: 'Ускорение',
            ua: 'Прискорення',
            en: 'Acceleration',
            de: 'Beschleunigung',
            pl: 'Przyspieszenie',
        },
        control: {
            ru: 'Управляемость',
            ua: 'Керованість',
            en: 'Control',
            de: 'Kontrolle',
            pl: 'Kontrola',
        },
        brakes: {
            ru: 'Тормоза',
            ua: 'Гальма',
            en: 'Brakes',
            de: 'Bremsen',
            pl: 'Hamulce',
        },
        passengers: {
            ru: 'Вместимость',
            ua: 'Вмістимість',
            en: 'Capacity',
            de: 'Kapazität',
            pl: 'Pojemność',
        },
        maxFuel: {
            ru: 'Бак',
            ua: 'Бак',
            en: 'Fuel tank',
            de: 'Tank',
            pl: 'Zbiornik paliwa',
        },
        maxTrunk: {
            ru: 'Вместительность багажника',
            ua: 'Вмістимість багажника',
            en: 'Trunk capacity',
            de: 'Kofferraumvolumen',
            pl: 'Pojemność bagażnika',
        },
        kmh: {
            ru: 'км/ч',
            ua: 'км/год',
            en: 'km/h',
            de: 'km/h',
            pl: 'km/h',
        },
        kg: {
            ru: 'кг',
            ua: 'кг',
            en: 'kg',
            de: 'kg',
            pl: 'kg',
        },
        l: {
            ru: 'л',
            ua: 'л',
            en: 'l',
            de: 'l',
            pl: 'l',
        },
    },
    status: {
        available: {
            ru: 'Свободна',
            ua: 'Вільна',
            en: 'Available',
            de: 'Frei',
            pl: 'Wolny',
        },
        occupied: {
            ru: 'Занята',
            ua: 'Зайнята',
            en: 'Occupied',
            de: 'Besetzt',
            pl: 'Zajęty',
        },
    },
    buttons: {
        take: {
            ru: 'Взять',
            ua: 'Взяти',
            en: 'Take',
            de: 'Nehmen',
            pl: 'Weź',
        },
        occupiedBy: {
            ru: 'Занято: {{name}}',
            ua: 'Зайнято: {{name}}',
            en: 'Occupied by: {{name}}',
            de: 'Besetzt von: {{name}}',
            pl: 'Zajęte przez: {{name}}',
        },
    },
    replaceDialog: {
        title: {
            ru: 'Уже есть активная машина',
            ua: 'Вже є активна машина',
            en: 'You already have a vehicle',
            de: 'Du hast bereits ein Fahrzeug',
            pl: 'Masz już pojazd',
        },
        message: {
            ru: 'У вас уже заспавнена фракционная машина <span style="color: white">{{name}}</span> <span style="color: white">({{plate}})</span>.<br/><br/>Если продолжить, текущая машина будет задеспавнена, а вместо неё вы получите новую.',
            ua: 'У вас вже заспавнена фракційна машина <span style="color: white">{{name}}</span> <span style="color: white">({{plate}})</span>.<br/><br/>Якщо продовжити, поточна машина буде задеспавнена, а замість неї ви отримаєте нову.',
            en: 'You already have a spawned faction vehicle <span style="color: white">{{name}}</span> <span style="color: white">({{plate}})</span>.<br/><br/>If you continue, the current vehicle will be despawned and replaced with the new one.',
            de: 'Du hast bereits ein gespawntes Fraktionsfahrzeug <span style="color: white">{{name}}</span> <span style="color: white">({{plate}})</span>.<br/><br/>Wenn du fortfährst, wird das aktuelle Fahrzeug despawnt und durch das neue ersetzt.',
            pl: 'Masz już zrespawnowany pojazd frakcyjny <span style="color: white">{{name}}</span> <span style="color: white">({{plate}})</span>.<br/><br/>Jeśli kontynuujesz, obecny pojazd zostanie zdespawnowany i zastąpiony nowym.',
        },
        confirmButton: {
            ru: 'Задеспавнить и взять',
            ua: 'Задеспавнити і взяти',
            en: 'Despawn and take',
            de: 'Despawnen und nehmen',
            pl: 'Despawnuj i weź',
        },
        cancelButton: {
            ru: 'Отмена',
            ua: 'Скасувати',
            en: 'Cancel',
            de: 'Abbrechen',
            pl: 'Anuluj',
        },
    },
};
