import dialogs from './dialogs';

export default {
    dialogs,
    notEnoughPoints: {
        ru: 'Похоже вы не смогли набить достаточное кол-во очков, попробуйте ещё раз!',
        ua: 'Схоже ви не змогли набрати достатню кількість очок, спробуйте ще раз!',
        en: "It seems you didn't score enough points, try again!",
        de: 'Sie haben anscheinend nicht genug Punkte erzielt, versuchen Sie es noch einmal!',
        pl: 'Wygląda na to, że nie zdobyłeś wystarczającej liczby punktów, spróbuj ponownie!',
       zh:'你似乎没有获得足够的分数，再试一次！',
    },
    testPassed: {
        ru: 'Вы смогли сдать тест, вот ваша лицензия!',
        ua: 'Ви змогли здати тест, ось ваша ліцензія!',
        en: 'You have successfully passed the test, here is your license!',
        de: 'Sie haben den Test bestanden, hier ist Ihre Lizenz!',
        pl: 'Zdałeś test, oto twoja licencja!',
        zh:'您已成功通过测试，这是您的驾照！',
    },
    timeRanOut: {
        ru: 'Похоже время вышло, попробуйте ещё раз!',
        ua: 'Схоже час вийшов, спробуйте ще раз!',
        en: 'It seems time has run out, try again!',
        de: 'Die Zeit ist anscheinend abgelaufen, versuchen Sie es noch einmal!',
        pl: 'Wygląda na to, że czas się skończył, spróbuj ponownie!',
       zh:'时间似乎用完了，再试一次！',
    },
    time: {
        ru: 'ВРЕМЯ:',
        ua: 'ЧАС:',
        en: 'TIME:',
        de: 'ZEIT:',
        pl: 'CZAS:',
       zh:'时间',
    },
    points: {
        ru: 'ОЧКИ:',
        ua: 'БАЛИ:',
        en: 'POINTS:',
        de: 'PUNKTE:',
        pl: 'PUNKTY:',
       zh:'积分',
    },
    toStart: {
        ru: 'До начала',
        ua: 'До початку',
        en: 'Until the start',
        de: 'Bis zum Start',
        pl: 'Do rozpoczęcia',
       zh:'开始吧',
    },
    great: {
        ru: 'Отлично',
        ua: 'Чудово',
        en: 'Great',
        de: 'Großartig',
        pl: 'Świetnie',
       zh:'太好了',
    },
    stats: {
        ru: 'Вы набили {{points}} очков за {{time}}',
        ua: 'Ви набрали {{points}} балiв за {{time}}',
        en: 'You scored {{points}} points in {{time}}',
        de: 'Sie haben {{points}} Punkte in {{time}} erzielt',
        pl: 'Zdobyłeś {{points}} punktów w czasie {{time}}',
        zh:'你在{时间}内得了{分}分',
    },
};
