export const contracts = {
    notify: {
        header: {
            ru: 'Контракты',
            ua: 'Контракти',
            en: 'Contracts',
            de: 'Vertraege',
            pl: 'Kontrakty',
        },
    },
    usage: {
        ru: 'Использование: /contract <list|take|take_family|status|abandon> [id]',
        ua: 'Використання: /contract <list|take|take_family|status|abandon> [id]',
        en: 'Usage: /contract <list|take|take_family|status|abandon> [id]',
        de: 'Verwendung: /contract <list|take|take_family|status|abandon> [id]',
        pl: 'Uzycie: /contract <list|take|take_family|status|abandon> [id]',
    },
    tracks: {
        legal: {
            ru: 'Легальный',
            ua: 'Легальний',
            en: 'Legal',
            de: 'Legal',
            pl: 'Legalny',
        },
        neutral: {
            ru: 'Нейтральный',
            ua: 'Нейтральний',
            en: 'Neutral',
            de: 'Neutral',
            pl: 'Neutralny',
        },
        crime: {
            ru: 'Криминальный',
            ua: 'Кримінальний',
            en: 'Crime',
            de: 'Kriminell',
            pl: 'Kryminalny',
        },
    },
    directions: {
        legal_elite: {
            ru: 'Легальный (elite)',
            ua: 'Легальний (elite)',
            en: 'Legal (elite)',
            de: 'Legal (elite)',
            pl: 'Legalny (elite)',
        },
        legal: {
            ru: 'Легальный',
            ua: 'Легальний',
            en: 'Legal',
            de: 'Legal',
            pl: 'Legalny',
        },
        neutral: {
            ru: 'Нейтральный',
            ua: 'Нейтральний',
            en: 'Neutral',
            de: 'Neutral',
            pl: 'Neutralny',
        },
        crime: {
            ru: 'Криминальный',
            ua: 'Кримінальний',
            en: 'Crime',
            de: 'Kriminell',
            pl: 'Kryminalny',
        },
        crime_hardcore: {
            ru: 'Криминальный (hardcore)',
            ua: 'Кримінальний (hardcore)',
            en: 'Crime (hardcore)',
            de: 'Kriminell (hardcore)',
            pl: 'Kryminalny (hardcore)',
        },
    },
    list: {
        header: {
            ru: 'Доступные контракты (направление орги: {{direction}}):',
            ua: 'Доступні контракти (напрям орги: {{direction}}):',
            en: 'Available contracts (organization direction: {{direction}}):',
            de: 'Verfuegbare Vertraege (Org-Richtung: {{direction}}):',
            pl: 'Dostepne kontrakty (kierunek org: {{direction}}):',
        },
        footer: {
            ru: 'Возьмите: /contract take <id> или /contract take_family <id>',
            ua: 'Візьміть: /contract take <id> або /contract take_family <id>',
            en: 'Take: /contract take <id> or /contract take_family <id>',
            de: 'Annehmen: /contract take <id> oder /contract take_family <id>',
            pl: 'Wez: /contract take <id> lub /contract take_family <id>',
        },
        entry: {
            ru: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            ua: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            en: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            de: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            pl: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
        },
        entryLocked: {
            ru: '!{#888888}[{{id}}] {{name}} - {{track}} (заблокирован направлением)',
            ua: '!{#888888}[{{id}}] {{name}} - {{track}} (заблокований напрямом)',
            en: '!{#888888}[{{id}}] {{name}} - {{track}} (locked by direction)',
            de: '!{#888888}[{{id}}] {{name}} - {{track}} (durch Richtung gesperrt)',
            pl: '!{#888888}[{{id}}] {{name}} - {{track}} (zablokowany kierunkiem)',
        },
        personalRewardLine: {
            ru: ' | Личный: ${{money}}, EXP {{exp}}, REP {{rep}}, шагов {{goal}}',
            ua: ' | Особистий: ${{money}}, EXP {{exp}}, REP {{rep}}, кроків {{goal}}',
            en: ' | Personal: ${{money}}, EXP {{exp}}, REP {{rep}}, steps {{goal}}',
            de: ' | Personal: ${{money}}, EXP {{exp}}, REP {{rep}}, Schritte {{goal}}',
            pl: ' | Osobisty: ${{money}}, EXP {{exp}}, REP {{rep}}, kroki {{goal}}',
        },
        familyRewardLine: {
            ru: ' | Семейный: ${{money}}, EXP {{exp}}, REP {{rep}}, шагов {{goal}}',
            ua: ' | Сімейний: ${{money}}, EXP {{exp}}, REP {{rep}}, кроків {{goal}}',
            en: ' | Family: ${{money}}, EXP {{exp}}, REP {{rep}}, steps {{goal}}',
            de: ' | Familie: ${{money}}, EXP {{exp}}, REP {{rep}}, Schritte {{goal}}',
            pl: ' | Rodzinny: ${{money}}, EXP {{exp}}, REP {{rep}}, kroki {{goal}}',
        },
        delivery: {
            name: {
                ru: 'Рассыльный',
                ua: 'Розсильний',
                en: 'Courier',
                de: 'Bote',
                pl: 'Goniec',
            },
            description: {
                ru: 'Доставка посылок по городу через Food Delivery.',
                ua: 'Доставка посилок містом через Food Delivery.',
                en: 'Deliver parcels around the city via Food Delivery.',
                de: 'Pakete in der Stadt ueber Food Delivery zustellen.',
                pl: 'Dostarczaj paczki po miescie przez Food Delivery.',
            },
        },
        quarry: {
            name: {
                ru: 'Рудник',
                ua: 'Рудник',
                en: 'Quarry',
                de: 'Steinbruch',
                pl: 'Kamieniolom',
            },
            description: {
                ru: 'Добыча и доставка руды (думпер/бульдозер).',
                ua: 'Видобуток і доставка руди (думпер/бульдозер).',
                en: 'Mine and deliver ore (dumper/bulldozer).',
                de: 'Erz abbauen und liefern (Kipper/Bulldozer).',
                pl: 'Wydobywaj i dostarczaj rude (wywrotka/buldozer).',
            },
        },
        carjacker: {
            name: {
                ru: 'Угонки',
                ua: 'Викрадення',
                en: 'Carjacking',
                de: 'Autodiebstahl',
                pl: 'Kradziez aut',
            },
            description: {
                ru: 'Заказы Анонима на угон транспорта.',
                ua: 'Замовлення Аноніма на викрадення транспорту.',
                en: 'Carjack orders from Anonymous.',
                de: 'Auftraege von Anonymous fuer Autodiebstahl.',
                pl: 'Zlecenia Anonima na kradziez aut.',
            },
        },
        greenCourier: {
            name: {
                ru: 'Кривая дорожка (Green)',
                ua: 'Крива доріжка (Green)',
                en: 'Crooked Path (Green)',
                de: 'Krummer Weg (Green)',
                pl: 'Kreta sciezka (Green)',
            },
            description: {
                ru: 'Развоз закладок Green по точкам сбыта.',
                ua: 'Розвезення закладок Green по точках збуту.',
                en: 'Plant Green stashes at delivery points.',
                de: 'Green-Verstecke an Abgabestellen platzieren.',
                pl: 'Rozkladaj zakladki Green w punktach sprzedazy.',
            },
        },
    },
    success: {
        taken: {
            ru: 'Контракт {{contract}} принят. Цель: {{goal}}.',
            ua: 'Контракт {{contract}} прийнятий. Ціль: {{goal}}.',
            en: 'Contract {{contract}} taken. Goal: {{goal}}.',
            de: 'Vertrag {{contract}} angenommen. Ziel: {{goal}}.',
            pl: 'Kontrakt {{contract}} przyjety. Cel: {{goal}}.',
        },
        familyTaken: {
            ru: 'Семейный контракт {{contract}} принят на партию. Цель: {{goal}}.',
            ua: 'Сімейний контракт {{contract}} прийнятий на партію. Ціль: {{goal}}.',
            en: 'Family contract {{contract}} taken by the party. Goal: {{goal}}.',
            de: 'Familienvertrag {{contract}} fuer die Gruppe angenommen. Ziel: {{goal}}.',
            pl: 'Kontrakt rodzinny {{contract}} przyjety przez druzyne. Cel: {{goal}}.',
        },
        abandoned: {
            ru: 'Контракт {{contract}} отменён.',
            ua: 'Контракт {{contract}} скасовано.',
            en: 'Contract {{contract}} abandoned.',
            de: 'Vertrag {{contract}} abgebrochen.',
            pl: 'Kontrakt {{contract}} anulowany.',
        },
        completedPersonal: {
            ru: 'Контракт {{contract}} выполнен! Награда зачислена.',
            ua: 'Контракт {{contract}} виконано! Винагороду зараховано.',
            en: 'Contract {{contract}} completed! Reward applied.',
            de: 'Vertrag {{contract}} abgeschlossen! Belohnung gutgeschrieben.',
            pl: 'Kontrakt {{contract}} wykonany! Nagroda zaliczona.',
        },
        completedFamily: {
            ru: 'Семейный контракт {{contract}} выполнен! Казна получила награду.',
            ua: 'Сімейний контракт {{contract}} виконано! Казна отримала винагороду.',
            en: 'Family contract {{contract}} completed! Treasury received the reward.',
            de: 'Familienvertrag {{contract}} abgeschlossen! Die Kasse erhielt die Belohnung.',
            pl: 'Kontrakt rodzinny {{contract}} wykonany! Skarbiec otrzymal nagrode.',
        },
    },
    info: {
        partyRecovered: {
            ru: 'Партия восстановила состав. Контракт продолжается.',
            ua: 'Партія відновила склад. Контракт триває.',
            en: 'Party restored. Contract continues.',
            de: 'Gruppe wiederhergestellt. Vertrag laeuft weiter.',
            pl: 'Druzyna odbudowana. Kontrakt trwa.',
        },
        progress: {
            ru: 'Прогресс {{contract}}: {{progress}}/{{goal}}.',
            ua: 'Прогрес {{contract}}: {{progress}}/{{goal}}.',
            en: 'Progress on {{contract}}: {{progress}}/{{goal}}.',
            de: 'Fortschritt {{contract}}: {{progress}}/{{goal}}.',
            pl: 'Postep {{contract}}: {{progress}}/{{goal}}.',
        },
        familyProgress: {
            ru: 'Семейный прогресс {{contract}}: {{progress}}/{{goal}}.',
            ua: 'Сімейний прогрес {{contract}}: {{progress}}/{{goal}}.',
            en: 'Family progress on {{contract}}: {{progress}}/{{goal}}.',
            de: 'Familienfortschritt {{contract}}: {{progress}}/{{goal}}.',
            pl: 'Postep rodzinny {{contract}}: {{progress}}/{{goal}}.',
        },
        status: {
            ru: 'Текущий контракт: {{contract}}, прогресс {{progress}}/{{goal}}.',
            ua: 'Поточний контракт: {{contract}}, прогрес {{progress}}/{{goal}}.',
            en: 'Current contract: {{contract}}, progress {{progress}}/{{goal}}.',
            de: 'Aktueller Vertrag: {{contract}}, Fortschritt {{progress}}/{{goal}}.',
            pl: 'Aktualny kontrakt: {{contract}}, postep {{progress}}/{{goal}}.',
        },
        familyStatus: {
            ru: 'Семейный контракт: {{contract}}, прогресс {{progress}}/{{goal}}.',
            ua: 'Сімейний контракт: {{contract}}, прогрес {{progress}}/{{goal}}.',
            en: 'Family contract: {{contract}}, progress {{progress}}/{{goal}}.',
            de: 'Familienvertrag: {{contract}}, Fortschritt {{progress}}/{{goal}}.',
            pl: 'Kontrakt rodzinny: {{contract}}, postep {{progress}}/{{goal}}.',
        },
    },
    errors: {
        notInGame: {
            ru: 'Сначала войдите в игру.',
            ua: 'Спочатку увійдіть у гру.',
            en: 'You must be in-game first.',
            de: 'Du musst zuerst im Spiel sein.',
            pl: 'Najpierw wejdz do gry.',
        },
        notInOrg: {
            ru: 'Вы не состоите в организации.',
            ua: 'Ви не перебуваєте в організації.',
            en: 'You are not in an organization.',
            de: 'Du bist in keiner Organisation.',
            pl: 'Nie nalezysz do organizacji.',
        },
        unknownContract: {
            ru: 'Неизвестный контракт.',
            ua: 'Невідомий контракт.',
            en: 'Unknown contract.',
            de: 'Unbekannter Vertrag.',
            pl: 'Nieznany kontrakt.',
        },
        missingContractId: {
            ru: 'Укажите id контракта: /contract take <id>',
            ua: 'Вкажіть id контракту: /contract take <id>',
            en: 'Specify contract id: /contract take <id>',
            de: 'Vertrag-Id angeben: /contract take <id>',
            pl: 'Podaj id kontraktu: /contract take <id>',
        },
        notSupportedAsPersonal: {
            ru: 'Этот контракт можно брать только как семейный.',
            ua: 'Цей контракт можна брати тільки як сімейний.',
            en: 'This contract is family-only.',
            de: 'Dieser Vertrag ist nur fuer Familien.',
            pl: 'Ten kontrakt jest tylko rodzinny.',
        },
        notSupportedAsFamily: {
            ru: 'Этот контракт можно брать только лично.',
            ua: 'Цей контракт можна брати тільки особисто.',
            en: 'This contract is personal-only.',
            de: 'Dieser Vertrag ist nur persoenlich.',
            pl: 'Ten kontrakt jest tylko osobisty.',
        },
        noPermissionPersonal: {
            ru: 'Ваш ранг не имеет права брать личные контракты.',
            ua: 'Ваш ранг не має права брати особисті контракти.',
            en: 'Your rank cannot take personal contracts.',
            de: 'Dein Rang darf keine persoenlichen Vertraege annehmen.',
            pl: 'Twoja ranga nie moze brac osobistych kontraktow.',
        },
        noPermissionFamily: {
            ru: 'Ваш ранг не имеет права брать семейные контракты.',
            ua: 'Ваш ранг не має права брати сімейні контракти.',
            en: 'Your rank cannot take family contracts.',
            de: 'Dein Rang darf keine Familienvertraege annehmen.',
            pl: 'Twoja ranga nie moze brac kontraktow rodzinnych.',
        },
        wrongDirection: {
            ru: 'Контракт несовместим с направлением вашей организации.',
            ua: 'Контракт несумісний з напрямом вашої організації.',
            en: 'Contract incompatible with your organization direction.',
            de: 'Vertrag mit der Org-Richtung nicht vereinbar.',
            pl: 'Kontrakt niezgodny z kierunkiem organizacji.',
        },
        notUnlockedInTree: {
            ru: 'Этот контракт ещё не разблокирован в дереве улучшений.',
            ua: 'Цей контракт ще не розблоковано у дереві покращень.',
            en: 'This contract is not yet unlocked in the upgrade tree.',
            de: 'Dieser Vertrag ist im Upgrade-Baum noch nicht freigeschaltet.',
            pl: 'Ten kontrakt nie jest jeszcze odblokowany w drzewie ulepszen.',
        },
        alreadyHaveContract: {
            ru: 'У вас уже есть активный контракт.',
            ua: 'У вас вже є активний контракт.',
            en: 'You already have an active contract.',
            de: 'Du hast bereits einen aktiven Vertrag.',
            pl: 'Masz juz aktywny kontrakt.',
        },
        notInParty: {
            ru: 'Вы не в группе. Создайте партию через /createparty.',
            ua: 'Ви не в групі. Створіть партію через /createparty.',
            en: 'You are not in a party. Use /createparty.',
            de: 'Du bist in keiner Gruppe. Nutze /createparty.',
            pl: 'Nie jestes w grupie. Uzyj /createparty.',
        },
        notPartyLeader: {
            ru: 'Только лидер партии может брать семейный контракт.',
            ua: 'Тільки лідер партії може брати сімейний контракт.',
            en: 'Only the party leader can take a family contract.',
            de: 'Nur der Gruppen-Leader kann einen Familienvertrag annehmen.',
            pl: 'Tylko lider druzyny moze wziac kontrakt rodzinny.',
        },
        partyTooSmall: {
            ru: 'В партии должно быть минимум 2 человека.',
            ua: 'У партії має бути мінімум 2 особи.',
            en: 'Party must have at least 2 members.',
            de: 'Gruppe braucht mindestens 2 Mitglieder.',
            pl: 'Druzyna musi miec minimum 2 czlonkow.',
        },
        partyMixedOrgs: {
            ru: 'Все участники партии должны быть в одной организации.',
            ua: 'Усі учасники партії мають бути в одній організації.',
            en: 'All party members must be in the same organization.',
            de: 'Alle Mitglieder muessen in derselben Organisation sein.',
            pl: 'Wszyscy czlonkowie druzyny musza byc w tej samej organizacji.',
        },
        partyMemberHasContract: {
            ru: 'У одного из членов партии уже есть активный контракт.',
            ua: 'Один з членів партії вже має активний контракт.',
            en: 'A party member already has an active contract.',
            de: 'Ein Gruppenmitglied hat bereits einen aktiven Vertrag.',
            pl: 'Czlonek druzyny ma juz aktywny kontrakt.',
        },
        noActiveContract: {
            ru: 'У вас нет активного контракта.',
            ua: 'У вас немає активного контракту.',
            en: 'You have no active contract.',
            de: 'Du hast keinen aktiven Vertrag.',
            pl: 'Nie masz aktywnego kontraktu.',
        },
        cooldownActive: {
            ru: 'Контракт на кулдауне ещё {{minutes}} мин.',
            ua: 'Контракт на кулдауні ще {{minutes}} хв.',
            en: 'Contract is on cooldown for {{minutes}} more min.',
            de: 'Vertrag im Cooldown noch {{minutes}} Min.',
            pl: 'Kontrakt na cooldownie jeszcze {{minutes}} min.',
        },
        onlyLeaderCanAbandonFamily: {
            ru: 'Отменить семейный контракт может только лидер или офицер.',
            ua: 'Скасувати сімейний контракт може тільки лідер або офіцер.',
            en: 'Only the leader or an officer can abandon a family contract.',
            de: 'Nur Leader oder Offizier kann einen Familienvertrag abbrechen.',
            pl: 'Tylko lider lub oficer moze anulowac kontrakt rodzinny.',
        },
        contractFailed: {
            ru: 'Контракт {{contract}} провален: {{reason}}.',
            ua: 'Контракт {{contract}} провалено: {{reason}}.',
            en: 'Contract {{contract}} failed: {{reason}}.',
            de: 'Vertrag {{contract}} fehlgeschlagen: {{reason}}.',
            pl: 'Kontrakt {{contract}} nieudany: {{reason}}.',
        },
    },
    fail: {
        reasons: {
            timeout: {
                ru: 'истёк таймер контракта',
                ua: 'час контракту вичерпано',
                en: 'contract timer expired',
                de: 'Vertragszeit abgelaufen',
                pl: 'czas kontraktu wygasl',
            },
            partyDrop: {
                ru: 'состав партии ниже минимума',
                ua: 'склад партії нижче мінімуму',
                en: 'party fell below minimum',
                de: 'Gruppe unter Mindestgroesse',
                pl: 'druzyna ponizej minimum',
            },
        },
    },
    warning: {
        partyDrop: {
            ru: 'Состав партии ниже минимума! У вас {{minutes}} мин, чтобы восстановиться, иначе провал.',
            ua: 'Склад партії нижче мінімуму! У вас {{minutes}} хв на відновлення, інакше провал.',
            en: 'Party below minimum! You have {{minutes}} min to recover or contract fails.',
            de: 'Gruppe unter Minimum! Du hast {{minutes}} Min zur Erholung, sonst Fehlschlag.',
            pl: 'Druzyna ponizej minimum! Masz {{minutes}} min na odbudowe, inaczej porazka.',
        },
    },
};
