import { harvestList, harvestBlips } from './contractFamilies/harvest';
import { cargoList, cargoBlips } from './contractFamilies/cargo';
import { workList, workBlips } from './contractFamilies/work';
import { pressList } from './contractFamilies/press';

export const contracts = {
    notify: {
        header: {
            ru: 'Контракты',
            ua: 'Контракти',
            en: 'Contracts',
            de: 'Verträge',
            pl: 'Kontrakty',
        },
    },
    usage: {
        ru: 'Использование: /contract <list|take|status|abandon> [id]',
        ua: 'Використання: /contract <list|take|status|abandon> [id]',
        en: 'Usage: /contract <list|take|status|abandon> [id]',
        de: 'Verwendung: /contract <list|take|status|abandon> [id]',
        pl: 'Użycie: /contract <list|take|status|abandon> [id]',
    },
    tracks: {
        legal: {
            ru: 'Официальный',
            ua: 'Офіційний',
            en: 'Official',
            de: 'Offiziell',
            pl: 'Oficjalny',
        },
        crime: {
            ru: 'Теневой',
            ua: 'Тіньовий',
            en: 'Shadow',
            de: 'Inoffiziell',
            pl: 'Nieoficjalny',
        },
    },
    scales: {
        legal: {
            ru: 'Доверие',
            ua: 'Довіра',
            en: 'Trust',
            de: 'Vertrauen',
            pl: 'Zaufanie',
        },
        crime: {
            ru: 'Авторитет',
            ua: 'Авторитет',
            en: 'Respect',
            de: 'Ansehen',
            pl: 'Autorytet',
        },
    },
    // Hover hint on the scale icon: what the counter is, and the two things that move it.
    scaleHints: {
        gainLabel: {
            ru: 'Растёт',
            ua: 'Зростає',
            en: 'Grows',
            de: 'Steigt',
            pl: 'Rośnie',
        },
        drainLabel: {
            ru: 'Падает',
            ua: 'Падає',
            en: 'Drops',
            de: 'Fällt',
            pl: 'Spada',
        },
        legal: {
            body: {
                ru: 'Чистое имя организации: связи в мэрии, банках и у поставщиков.',
                ua: 'Чисте ім\'я організації: зв\'язки в мерії, банках і в постачальників.',
                en: 'The clean name of the organization: ties in city hall, banks and suppliers.',
                de: 'Der saubere Name der Organisation: Draht zu Rathaus, Banken und Lieferanten.',
                pl: 'Czyste imię organizacji: dojścia w ratuszu, bankach i u dostawców.',
            },
            gain: {
                ru: 'Официальные контракты',
                ua: 'Офіційні контракти',
                en: 'Official contracts',
                de: 'Offizielle Verträge',
                pl: 'Oficjalne kontrakty',
            },
            drain: {
                ru: 'Каждый теневой заказ',
                ua: 'Кожне тіньове замовлення',
                en: 'Every shadow job',
                de: 'Jeder inoffizielle Auftrag',
                pl: 'Każde nieoficjalne zlecenie',
            },
            perk: {
                ru: 'Ступени дают скидку на лицензии, налог и аренду',
                ua: 'Щаблі дають знижку на ліцензії, податок та оренду',
                en: 'Rungs buy a discount on licences, tax and rent',
                de: 'Stufen bringen Rabatt auf Lizenzen, Steuer und Miete',
                pl: 'Progi dają zniżkę na licencje, podatek i czynsz',
            },
        },
        crime: {
            body: {
                ru: 'Вес организации на улице.',
                ua: 'Вага організації на вулиці.',
                en: 'How much weight the organization carries on the street.',
                de: 'Das Gewicht der Organisation auf der Straße.',
                pl: 'Waga organizacji na ulicy.',
            },
            gain: {
                ru: 'Теневые контракты и контроль территорий',
                ua: 'Тіньові контракти й контроль територій',
                en: 'Shadow contracts and territory control',
                de: 'Inoffizielle Verträge und Gebietskontrolle',
                pl: 'Nieoficjalne kontrakty i kontrola terytoriów',
            },
            drain: {
                ru: 'Простой: {{days}} дней без теневых заказов',
                ua: 'Простій: {{days}} днів без тіньових замовлень',
                en: 'Idling: {{days}} days with no shadow job',
                de: 'Leerlauf: {{days}} Tage ohne inoffiziellen Auftrag',
                pl: 'Bezczynność: {{days}} dni bez nieoficjalnego zlecenia',
            },
        },
    },
    list: {
        ...harvestList,
        ...cargoList,
        ...workList,
        ...pressList,
        header: {
            ru: 'Доступные контракты (репутация: доверие {{legal}}, авторитет {{crime}}):',
            ua: 'Доступні контракти (репутація: довіра {{legal}}, авторитет {{crime}}):',
            en: 'Available contracts (reputation: trust {{legal}}, respect {{crime}}):',
            de: 'Verfügbare Verträge (Ruf: Vertrauen {{legal}}, Ansehen {{crime}}):',
            pl: 'Dostępne kontrakty (reputacja: zaufanie {{legal}}, autorytet {{crime}}):',
        },
        footer: {
            ru: 'Возьмите: /contract take <id>',
            ua: 'Візьміть: /contract take <id>',
            en: 'Take: /contract take <id>',
            de: 'Annehmen: /contract take <id>',
            pl: 'Weź: /contract take <id>',
        },
        entry: {
            ru: '~g~[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            ua: '~g~[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            en: '~g~[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            de: '~g~[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            pl: '~g~[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
        },
        entryLocked: {
            ru: '~m~[{{id}}] {{name}} - {{track}} (недоступен)',
            ua: '~m~[{{id}}] {{name}} - {{track}} (недоступний)',
            en: '~m~[{{id}}] {{name}} - {{track}} (unavailable)',
            de: '~m~[{{id}}] {{name}} - {{track}} (nicht verfügbar)',
            pl: '~m~[{{id}}] {{name}} - {{track}} (niedostępny)',
        },
        personalRewardLine: {
            ru: ' | Личный: ${{money}}, EXP {{exp}}, REP {{rep}}, шагов {{goal}}',
            ua: ' | Особистий: ${{money}}, EXP {{exp}}, REP {{rep}}, кроків {{goal}}',
            en: ' | Personal: ${{money}}, EXP {{exp}}, REP {{rep}}, steps {{goal}}',
            de: ' | Persönlich: ${{money}}, EXP {{exp}}, REP {{rep}}, Schritte {{goal}}',
            pl: ' | Osobisty: ${{money}}, EXP {{exp}}, REP {{rep}}, kroki {{goal}}',
        },
        familyRewardLine: {
            ru: ' | Семейный: ${{money}}, EXP {{exp}}, REP {{rep}}, шагов {{goal}}',
            ua: ' | Сімейний: ${{money}}, EXP {{exp}}, REP {{rep}}, кроків {{goal}}',
            en: ' | Family: ${{money}}, EXP {{exp}}, REP {{rep}}, steps {{goal}}',
            de: ' | Familie: ${{money}}, EXP {{exp}}, REP {{rep}}, Schritte {{goal}}',
            pl: ' | Rodzinny: ${{money}}, EXP {{exp}}, REP {{rep}}, kroki {{goal}}',
        },
        quarry: {
            name: {
                ru: 'Рудник',
                ua: 'Рудник',
                en: 'Quarry',
                de: 'Steinbruch',
                pl: 'Kamieniołom',
            },
            description: {
                ru: 'Рук вечно не хватает - садись за думпер или бульдозер, кидай руду на склад. Плачу за объём, не за разговоры.',
                ua: 'Рук вічно бракує - сідай за думпер чи бульдозер, кидай руду на склад. Плачу за обсяг, не за балачки.',
                en: 'Always short on hands - jump in a dumper or bulldozer, haul ore to the yard. I pay by the load, not by the chatter.',
                de: 'Es fehlen immer Leute - schnapp dir den Kipper oder Bulldozer und schaff das Erz zum Lager. Ich zahl pro Ladung, nicht fürs Reden.',
                pl: 'Zawsze brak rąk - bierz wywrotkę albo buldożer i wioź rudę na skład. Płacę od kursu, nie od gadania.',
            },
            objective: {
                ru: 'Сделать рейсы в карьере',
                ua: 'Зробити рейси у кар\'єрі',
                en: 'Complete the quarry hauls',
                de: 'Die Steinbruch-Fahrten erledigen',
                pl: 'Wykonać kursy w kamieniołomie',
            },
        },
        mineOre: {
            name: {
                ru: 'Порода на заказ',
                ua: 'Порода на замовлення',
                en: 'Ore on order',
                de: 'Gestein auf Bestellung',
                pl: 'Urobek na zamówienie',
            },
            description: {
                ru: 'Плавильне нужна порода по списку, а не всё подряд из забоя. Что стоит в заказе - то и везите на приёмку: разряд выше, руда дороже и список длиннее.',
                ua: 'Плавильні потрібна порода за списком, а не все підряд із забою. Що стоїть у замовленні - те й везіть на приймання: розряд вищий, руда дорожча і список довший.',
                en: 'The smelter wants the rock on the list, not whatever falls off the face. Bring exactly what the order says to the receiving yard - the higher the grade, the better the ore and the longer the list.',
                de: 'Die Hütte will das Gestein von der Liste, nicht alles, was von der Wand fällt. Bringt genau das, was im Auftrag steht, zur Annahme - je höher die Stufe, desto besseres Erz und desto länger die Liste.',
                pl: 'Huta chce skały z listy, nie wszystkiego ze ściany. Przywieźcie dokładnie to, co jest w zleceniu, na punkt odbioru - im wyższy stopień, tym lepsza ruda i dłuższa lista.',
            },
            objective: {
                ru: 'Добыть руду по списку и сдать на приёмку',
                ua: 'Видобути руду за списком і здати на приймання',
                en: 'Mine the listed ore and hand it in at the receiving yard',
                de: 'Das Erz der Liste abbauen und an der Annahme abgeben',
                pl: 'Wydobyć rudę z listy i zdać na punkcie odbioru',
            },
        },
        paperwork: {
            name: {
                ru: 'Бумажная волокита',
                ua: 'Паперова тяганина',
                en: 'Paperwork',
                de: 'Papierkram',
                pl: 'Biurokracja',
            },
            description: {
                ru: 'Контора берёт пачки удостоверений с нашей печатью. Делают их только в цеху поддельных документов - держите цех за собой, гоните линию и привозите товар мне лично.',
                ua: 'Контора бере пачки посвідчень з нашою печаткою. Роблять їх лише в цеху підроблених документів - тримайте цех за собою, женіть лінію і привозьте товар мені особисто.',
                en: 'The office takes ID packs under our seal. They are made nowhere but a document forgery workshop - hold the workshop, keep the line running and bring the goods to me in person.',
                de: 'Das Büro nimmt Ausweispakete mit unserem Siegel. Gemacht werden sie nur in einer Dokumentenfälschung - haltet den Betrieb, lasst die Linie laufen und bringt die Ware persönlich zu mir.',
                pl: 'Kancelaria bierze paczki dowodów z naszą pieczęcią. Robi się je tylko w wytwórni fałszywych dokumentów - trzymajcie zakład, prowadźcie linię i przywoźcie towar do mnie osobiście.',
            },
            objective: {
                ru: 'Сдать пачки поддельных удостоверений',
                ua: 'Здати пачки підроблених посвідчень',
                en: 'Hand in the forged ID packs',
                de: 'Gefälschte Ausweispakete abgeben',
                pl: 'Oddać paczki fałszywych dowodów',
            },
        },
        notary: {
            name: {
                ru: 'Нотариус',
                ua: 'Нотаріус',
                en: 'Notary',
                de: 'Notar',
                pl: 'Notariusz',
            },
            description: {
                ru: 'Нужны нотариальные досье из вашего цеха документов. В одиночку столько не потянуть - тогда несите папки подставных фирм. Принимаю только лично и под подпись.',
                ua: 'Потрібні нотаріальні досьє з вашого цеху документів. Наодинці стільки не потягнути - тоді несіть теки підставних фірм. Приймаю лише особисто і під підпис.',
                en: 'I need notarial dossiers out of your forgery workshop. Alone you will not pull that many - then bring shell company files instead. I take them in person and against a signature.',
                de: 'Ich brauche Notarsdossiers aus eurer Dokumentenfälschung. Allein schafft ihr so viele nicht - dann bringt eben Briefkastenfirmen-Akten. Angenommen wird nur persönlich und gegen Unterschrift.',
                pl: 'Potrzebuję teczek notarialnych z waszej wytwórni dokumentów. Sam tyle nie udźwigniesz - wtedy przynieś akta firm słupów. Przyjmuję tylko osobiście i za podpisem.',
            },
            objective: {
                ru: 'Сдать документы из цеха',
                ua: 'Здати документи з цеху',
                en: 'Hand in the workshop paperwork',
                de: 'Papiere aus dem Betrieb abgeben',
                pl: 'Oddać dokumenty z zakładu',
            },
        },
        seafood: {
            name: {
                ru: 'Морской промысел',
                ua: 'Морський промисел',
                en: 'Sea Fishery',
                de: 'Seefischerei',
                pl: 'Rybołówstwo morskie',
            },
            description: {
                ru: 'Лови по списку и вези улов ко мне - взвешу, рассчитаю, лишних вопросов о ваших сетях задавать не буду. Море щедрое, если не лениться.',
                ua: 'Лови за списком і вези улов до мене - зважу, розрахую, зайвих питань про ваші сітки не питатиму. Море щедре, якщо не лінуватися.',
                en: 'Fish the list and bring the catch to me - I\'ll weigh, I\'ll pay, and I won\'t ask about your nets. The sea\'s generous if you don\'t laze about.',
                de: 'Fang nach Liste und bring den Fang zu mir - ich wieg, ich zahl, und ich frag nicht nach euren Netzen. Die See ist großzügig, wenn man nicht faulenzt.',
                pl: 'Łów według listy i przywieź połów do mnie - zważę, rozliczę, o waszych sieciach nie zapytam. Morze jest hojne, jak nie lenisz się.',
            },
            objective: {
                ru: 'Выловить рыбу по списку и сдать на приёмку',
                ua: 'Виловити рибу за списком і здати на приймання',
                en: 'Catch the listed fish and hand it in at the depot',
                de: 'Den Fisch der Liste fangen und an der Annahme abgeben',
                pl: 'Złowić ryby z listy i zdać je w skupie',
            },
        },
        streetNet: {
            name: {
                ru: 'Уличная сеть',
                ua: 'Вулична мережа',
                en: 'Street Net',
                de: 'Straßen-Netzwerk',
                pl: 'Uliczna sieć',
            },
            description: {
                ru: 'Уличной сети нужен ZAP! в розничной фасовке. Переводите свою лабораторию на пакеты и везите партию целиком.',
                ua: 'Вуличній мережі потрібен ZAP! у роздрібному фасуванні. Переводьте свою лабораторію на пакети й везіть партію цілком.',
                en: 'The street network needs ZAP! in retail packets. Switch your lab over to packing and bring the batch in one piece.',
                de: 'Das Straßennetz braucht ZAP! in Verkaufspäckchen. Stellt euer Labor auf Abpacken um und bringt die Partie am Stück.',
                pl: 'Sieć uliczna potrzebuje ZAP! w detalicznych paczkach. Przestawcie laboratorium na pakowanie i przywieźcie całą partię.',
            },
            objective: {
                ru: 'Сдать пакеты ZAP!',
                ua: 'Здати пакети ZAP!',
                en: 'Hand in the ZAP! packets',
                de: 'ZAP!-Päckchen abgeben',
                pl: 'Oddać paczki ZAP!',
            },
        },
        airDrop: {
            name: {
                ru: 'Воздушный груз',
                ua: 'Повітряний вантаж',
                en: 'Air Drop',
                de: 'Luftabwurf',
                pl: 'Zrzut z powietrza',
            },
            description: {
                ru: 'Со сброшенных контейнеров снимают электронику: чипсеты и платы. Забирайте из ящиков по всему городу и везите ко мне.',
                ua: 'Зі скинутих контейнерів знімають електроніку: чипсети й плати. Забирайте з ящиків по всьому місту й везіть до мене.',
                en: 'Dropped containers carry electronics: chipsets and boards. Take them off the crates around the city and bring them to me.',
                de: 'Aus abgeworfenen Containern holt man Elektronik: Chipsätze und Platinen. Nehmt sie von den Kisten in der ganzen Stadt und bringt sie zu mir.',
                pl: 'Ze zrzuconych kontenerów zdejmuje się elektronikę: chipsety i płytki. Bierzcie je ze skrzyń w całym mieście i przywoźcie do mnie.',
            },
            objective: {
                ru: 'Сдать электронику из ящиков',
                ua: 'Здати електроніку з ящиків',
                en: 'Hand in the crate electronics',
                de: 'Elektronik aus den Kisten abgeben',
                pl: 'Oddać elektronikę ze skrzyń',
            },
        },
        foreignFactory: {
            name: {
                ru: 'Чужая фабрика',
                ua: 'Чужа фабрика',
                en: 'Foreign Factory',
                de: 'Fremde Fabrik',
                pl: 'Cudza fabryka',
            },
            description: {
                ru: 'Нужны контейнеры двух марок сразу. Свой цех гонит только одну - вторую ищите у соседей: покупайте, меняйте или отбирайте.',
                ua: 'Потрібні контейнери двох марок одразу. Свій цех жене лише одну - другу шукайте в сусідів: купуйте, міняйте або відбирайте.',
                en: 'I need containers of two brands at once. Your own plant runs only one of them - the second you find at the neighbours: buy it, trade it or take it.',
                de: 'Ich brauche Container von zwei Marken auf einmal. Euer Betrieb produziert nur eine davon - die zweite holt ihr euch bei den Nachbarn: kaufen, tauschen oder nehmen.',
                pl: 'Potrzebuję kontenerów dwóch marek naraz. Wasz zakład robi tylko jedną - drugiej szukajcie u sąsiadów: kupcie, wymieńcie albo odbierzcie.',
            },
            objective: {
                ru: 'Сдать контейнеры двух марок',
                ua: 'Здати контейнери двох марок',
                en: 'Hand in containers of two brands',
                de: 'Container zweier Marken abgeben',
                pl: 'Oddać kontenery dwóch marek',
            },
        },
        intercept: {
            name: {
                ru: 'Перехват',
                ua: 'Перехоплення',
                en: 'Intercept',
                de: 'Abfangen',
                pl: 'Przechwycenie',
            },
            description: {
                ru: 'Чужая фура везёт канцелярию высшего сорта. Бумага и краска третьего сорта - привозите всё, что снимете с неё.',
                ua: 'Чужа фура везе канцелярію вищого гатунку. Папір і фарба третього сорту - привозьте все, що знімете з неї.',
                en: 'Somebody elses truck is moving top grade stationery. Grade three paper and ink - bring me everything you take off it.',
                de: 'Ein fremder Laster fährt Büromaterial höchster Güte. Papier und Tinte der Stufe drei - bringt mir alles, was ihr davon runterholt.',
                pl: 'Cudza ciężarówka wiezie papier najwyższej klasy. Papier i tusz trzeciej klasy - przywieźcie wszystko, co z niej zdejmiecie.',
            },
            objective: {
                ru: 'Сдать перехваченное сырьё',
                ua: 'Здати перехоплену сировину',
                en: 'Hand in the intercepted stock',
                de: 'Abgefangenes Material abgeben',
                pl: 'Oddać przechwycony surowiec',
            },
        },
        planting: {
            name: {
                ru: 'Посевная',
                ua: 'Сівба',
                en: 'Planting',
                de: 'Aussaat',
                pl: 'Siew',
            },
            description: {
                ru: 'Нужно сырьё с плантации. С грядок вручную или с линии - мне без разницы, но плантация должна быть за вами.',
                ua: 'Потрібна сировина з плантації. З грядок вручну чи з лінії - мені байдуже, але плантація має бути за вами.',
                en: 'I want raw crop off the farm. Picked by hand or run off the line, I do not care - but the farm has to be yours.',
                de: 'Ich will Rohernte von der Plantage. Von Hand gepflückt oder von der Linie, egal - aber die Plantage muss euch gehören.',
                pl: 'Potrzebuję surowca z plantacji. Zbierany ręcznie czy z linii, wszystko jedno - ale plantacja musi być wasza.',
            },
            objective: {
                ru: 'Сдать урожай STANK',
                ua: 'Здати врожай STANK',
                en: 'Hand in the STANK harvest',
                de: 'STANK-Ernte abgeben',
                pl: 'Oddać zbiory STANK',
            },
        },
        specialCargo: {
            name: {
                ru: 'Спецгруз',
                ua: 'Спецвантаж',
                en: 'Special Cargo',
                de: 'Spezialfracht',
                pl: 'Ładunek specjalny',
            },
            description: {
                ru: 'Крупный номинал из вашей печатни. Партия большая и долгая, так что везите её под охраной и одной ходкой.',
                ua: 'Великий номінал з вашої друкарні. Партія велика й довга, тож везіть її під охороною й однією ходкою.',
                en: 'The big denomination off your own press. It is a long, heavy batch, so move it under guard and in one run.',
                de: 'Die große Stückelung aus eurer eigenen Presse. Die Partie ist groß und langwierig, also fahrt sie bewacht und in einer Fahrt.',
                pl: 'Wysoki nominał z waszej drukarni. Partia jest duża i długa, więc woźcie ją pod ochroną i jednym kursem.',
            },
            objective: {
                ru: 'Сдать крупный номинал',
                ua: 'Здати великий номінал',
                en: 'Hand in the large denomination',
                de: 'Große Stückelung abgeben',
                pl: 'Oddać wysoki nominał',
            },
        },
        giftCard: {
            name: {
                ru: 'Наколка',
                ua: 'Розводка',
                en: 'Card Scam',
                de: 'Kartenbetrug',
                pl: 'Przekręt',
            },
            description: {
                ru: 'Печатайте доллары у себя и везите сумму мне в чёрном пакете. Беру вдвое дороже оптовика - за это и объёмы другие.',
                ua: 'Друкуйте долари в себе і везіть суму мені в чорному пакеті. Беру вдвічі дорожче за оптовика - за це й обсяги інші.',
                en: 'Print the dollars at your own press and bring me the sum in a black bag. I pay double what the wholesaler does - and I order in different volumes for it.',
                de: 'Druckt die Dollars bei euch und bringt mir die Summe in einer schwarzen Tüte. Ich zahle das Doppelte des Großhändlers - dafür sind die Mengen andere.',
                pl: 'Drukujcie dolary u siebie i przywieźcie mi sumę w czarnej torbie. Płacę dwa razy więcej niż hurtownik - i dlatego zamawiam inne ilości.',
            },
            objective: {
                ru: 'Сдать фальшивые доллары',
                ua: 'Здати фальшиві долари',
                en: 'Hand in the counterfeit dollars',
                de: 'Falsche Dollars abgeben',
                pl: 'Oddać fałszywe dolary',
            },
        },
        burglar: {
            // The name moved to `houseHaul`, which is the contract that actually rides the
            // burglary job. This one has always been about dirty money off business robberies.
            name: {
                ru: 'Грязные пачки',
                ua: 'Брудні пачки',
                en: 'Dirty Stacks',
                de: 'Schmutzige Bündel',
                pl: 'Brudne pliki',
            },
            description: {
                ru: 'Чистите бизнесы, грязные пачки везите ко мне. Плачу заметно выше отмывочной комиссии и о происхождении не спрашиваю.',
                ua: 'Чистіть бізнеси, брудні пачки везіть до мене. Плачу помітно вище за відмивочну комісію і про походження не питаю.',
                en: 'Clean out businesses and bring the dirty stacks to me. I pay well over the laundering cut and I do not ask where it came from.',
                de: 'Räumt Geschäfte aus und bringt mir die schmutzigen Bündel. Ich zahle deutlich mehr als die Waschprovision und frage nicht nach der Herkunft.',
                pl: 'Czyśćcie biznesy i przywoźcie mi brudne pliki. Płacę znacznie więcej niż prowizja za pranie i nie pytam o pochodzenie.',
            },
            objective: {
                ru: 'Сдать грязные деньги',
                ua: 'Здати брудні гроші',
                en: 'Hand in the dirty money',
                de: 'Schmutziges Geld abgeben',
                pl: 'Oddać brudne pieniądze',
            },
        },
        houseHaul: {
            name: {
                ru: 'Домушник',
                ua: 'Домушник',
                en: 'Burglar',
                de: 'Einbrecher',
                pl: 'Włamywacz',
            },
            description: {
                ru: 'У меня заказ на конкретные вещи, а не на всё подряд. Пройдись по адресам, вынеси что в списке и вези ко мне - за список плачу выше барыги.',
                ua: 'У мене замовлення на конкретні речі, а не на все підряд. Пройдись по адресах, винеси те, що в списку, і вези до мене - за список плачу вище за баригу.',
                en: 'I have an order for specific things, not for whatever fits in the boot. Work the addresses, carry out what is on the list and bring it to me - I pay over the fence for a list filled.',
                de: 'Ich habe eine Bestellung auf bestimmte Sachen, nicht auf alles Mögliche. Klapper die Adressen ab, trag heraus, was auf der Liste steht, und bring es mir - für eine volle Liste zahle ich mehr als der Hehler.',
                pl: 'Mam zamówienie na konkretne rzeczy, nie na wszystko po kolei. Obejdź adresy, wynieś to, co jest na liście, i przywieź do mnie - za pełną listę płacę więcej niż paser.',
            },
            objective: {
                ru: 'Сдать вещи из домов',
                ua: 'Здати речі з будинків',
                en: 'Hand in the house goods',
                de: 'Die Sachen aus den Häusern abgeben',
                pl: 'Oddać rzeczy z domów',
            },
        },
        undercover: {
            name: {
                ru: 'Под прикрытием',
                ua: 'Під прикриттям',
                en: 'Under Cover',
                de: 'Verdeckt',
                pl: 'Pod przykryciem',
            },
            description: {
                ru: 'Заказ деликатный: паста из вашей лаборатории POOF. Провезти через город тихо, без сирен и лишних глаз.',
                ua: 'Замовлення делікатне: паста з вашої лабораторії POOF. Провезти через місто тихо, без сирен і зайвих очей.',
                en: 'A delicate order: paste out of your own POOF lab. Move it across town quietly, no sirens and no extra eyes.',
                de: 'Ein heikler Auftrag: Paste aus eurem eigenen POOF-Labor. Bringt sie leise durch die Stadt, ohne Sirenen und ohne Zuschauer.',
                pl: 'Delikatne zlecenie: pasta z waszego laboratorium POOF. Przewieźcie ją przez miasto cicho, bez syren i zbędnych oczu.',
            },
            objective: {
                ru: 'Сдать пасту POOF',
                ua: 'Здати пасту POOF',
                en: 'Hand in the POOF paste',
                de: 'POOF-Paste abgeben',
                pl: 'Oddać pastę POOF',
            },
        },
        stashes: {
            name: {
                ru: 'Розница',
                ua: 'Роздріб',
                en: 'Retail',
                de: 'Einzelhandel',
                pl: 'Detal',
            },
            description: {
                ru: 'Варить ничего не надо, товар мой. Возьми партию, разложи по адресам и не попадись. Адресов в заказе - {{rolledGoal}}, плачу за весь заказ.',
                ua: 'Варити нічого не треба, товар мій. Візьми партію, розклади за адресами і не попадись. Адрес у замовленні - {{rolledGoal}}, плачу за все замовлення.',
                en: 'Nothing to cook, the product is mine. Take a batch, work the addresses and do not get caught. Addresses in the order - {{rolledGoal}}, I pay for the lot.',
                de: 'Nichts zu kochen, die Ware ist meine. Nimm eine Charge, arbeite die Adressen ab und flieg nicht auf. Adressen im Auftrag - {{rolledGoal}}, bezahlt wird der ganze Auftrag.',
                pl: 'Nic nie trzeba warzyć, towar jest mój. Bierz partię, rozłóż pod adresami i nie wpadnij. Adresów w zleceniu - {{rolledGoal}}, płacę za całość.',
            },
            objective: {
                ru: 'Взять партию у Дайса и разложить по адресам',
                ua: 'Взяти партію у Дайса і розкласти за адресами',
                en: 'Take a batch from Dice and work the addresses',
                de: 'Eine Charge bei Dice holen und die Adressen abarbeiten',
                pl: 'Wziąć partię od Dice i obsłużyć adresy',
            },
        },
        atelier: {
            name: {
                ru: 'Мануфактура',
                ua: 'Мануфактура',
                en: 'Manufactory',
                de: 'Manufaktur',
                pl: 'Manufaktura',
            },
            description: {
                ru: 'Взяла срочный заказ и одна не вытяну. Садись за станок, отшей форму и отвези заказчику - {{subjectName}}. Комплектов - {{rolledGoal}}, платят за привезённое.',
                ua: 'Взяла термінове замовлення і сама не витягну. Сідай за верстат, поший форму і відвези замовнику - {{subjectName}}. Комплектів - {{rolledGoal}}, платять за привезене.',
                en: 'I took a rush order and cannot fill it alone. Take a station, run off the uniforms and drive them to the client - {{subjectName}}. Sets - {{rolledGoal}}, paid on delivery.',
                de: 'Ich habe einen Eilauftrag angenommen und schaffe ihn nicht allein. Setz dich an die Maschine, näh die Uniformen und bring sie zum Kunden - {{subjectName}}. Sätze - {{rolledGoal}}, bezahlt wird Geliefertes.',
                pl: 'Wzięłam pilne zlecenie i sama go nie udźwignę. Siadaj do maszyny, uszyj mundury i zawieź je zleceniodawcy - {{subjectName}}. Kompletów - {{rolledGoal}}, płacą za dostarczone.',
            },
            objective: {
                ru: 'Отшить комплекты формы и сдать заказчику',
                ua: 'Пошити комплекти форми і здати замовнику',
                en: 'Sew the uniform sets and hand them to the client',
                de: 'Die Uniformsätze nähen und beim Kunden abgeben',
                pl: 'Uszyć komplety mundurów i zdać zleceniodawcy',
            },
        },
        illegalSupplier: {
            name: { ru: 'Нелегальный поставщик', ua: 'Нелегальний постачальник', en: 'Illegal supplier', de: 'Illegaler Lieferant', pl: 'Nielegalny dostawca' },
            description: {
                ru: 'Товар фасуют на месте, руками, партия за партией - партий в заказе {{rolledGoal}}. Готовое на точке не оставляйте: грузите и везите на приёмку.',
                ua: 'Товар фасують на місці, руками, партія за партією - партій у замовленні {{rolledGoal}}. Готове на точці не лишайте: вантажте і везіть на приймання.',
                en: 'The product gets packed on site by hand, batch after batch - {{rolledGoal}} in the order. Do not leave it standing there: load up and drive it to the receiving point.',
                de: 'Die Ware wird vor Ort von Hand verpackt, Charge um Charge - {{rolledGoal}} im Auftrag. Lasst sie nicht dort stehen: aufladen und zur Annahme fahren.',
                pl: 'Towar pakuje się na miejscu ręcznie, partia za partią - partii w zleceniu {{rolledGoal}}. Nie zostawiajcie go na miejscu: ładujcie i wieźcie na odbiór.',
            },
            objective: {
                ru: 'Расфасовать партии и сдать на приёмке',
                ua: 'Розфасувати партії і здати на прийманні',
                en: 'Pack the batches and hand them in at the receiving point',
                de: 'Die Chargen packen und an der Annahmestelle abgeben',
                pl: 'Spakować partie i zdać na odbiorze',
            },
        },
        laundry: {
            name: {
                ru: 'Прачечная',
                ua: 'Пральня',
                en: 'Laundromat',
                de: 'Waschsalon',
                pl: 'Pralnia',
            },
            description: {
                ru: 'Прачечная на Ла-Меса моя, машины стоят пустые. Отработайте смену вдвоём и привезите отмытое на приёмку. Довезёте - поговорим дальше.',
                ua: 'Пральня на Ла-Меса моя, машини стоять порожні. Відпрацюйте зміну вдвох і привезіть відмите на приймання. Довезете - поговоримо далі.',
                en: 'The laundromat on La Mesa is mine and the machines stand empty. Work a shift there, the two of you, and drive the clean stack to the counter. Get it there and we keep talking.',
                de: 'Der Waschsalon in La Mesa gehört mir und die Maschinen stehen leer. Fahrt zu zweit eine Schicht und bringt das saubere Bündel zur Annahme. Kommt es an, reden wir weiter.',
                pl: 'Pralnia na La Mesa jest moja, a maszyny stoją puste. Odróbcie zmianę we dwóch i przywieźcie czysty plik na odbiór. Dowieziecie - pogadamy dalej.',
            },
            objective: {
                ru: 'Отмыть партии в прачечной и сдать на приёмке',
                ua: 'Відмити партії у пральні й здати на прийманні',
                en: 'Wash the batches at the laundromat and hand them in',
                de: 'Die Chargen im Waschsalon waschen und abgeben',
                pl: 'Wyprać partie w pralni i zdać na odbiorze',
            },
            // Per rung (`LAUNDROMAT_TIERS`). Args: rolledGoal (batches), inputAmount (per batch),
            // inputTotal (whole order), inputName (the item). The briefs quote only the first two -
            // the total is the product of them and the objective line carries the count as well.
            tiers: {
                house: {
                    description: {
                        ru: 'Машины стоят пустые, наличка моя. Отработайте смену вдвоём - партий {{rolledGoal}} - и привезите отмытое на Гроув-стрит.',
                        ua: 'Машини стоять порожні, готівка моя. Відпрацюйте зміну вдвох - партій {{rolledGoal}} - і привезіть відмите на Ґроув-стріт.',
                        en: 'The machines stand empty and the cash is mine. Work a shift, the two of you - {{rolledGoal}} batches - and bring the clean stack to Grove Street.',
                        de: 'Die Maschinen stehen leer, das Geld ist meins. Fahrt zu zweit eine Schicht - {{rolledGoal}} Chargen - und bringt das Saubere zur Grove Street.',
                        pl: 'Maszyny stoją puste, gotówka jest moja. Odróbcie zmianę we dwóch - partii {{rolledGoal}} - i przywieźcie czyste na Grove Street.',
                    },
                    objective: {
                        ru: 'Отмыть {{rolledGoal}} партий в прачечной и сдать на приёмке',
                        ua: 'Відмити {{rolledGoal}} партій у пральні й здати на прийманні',
                        en: 'Wash {{rolledGoal}} batches at the laundromat and hand them in',
                        de: '{{rolledGoal}} Chargen im Waschsalon waschen und abgeben',
                        pl: 'Wyprać {{rolledGoal}} partii w pralni i zdać na odbiorze',
                    },
                },
                dirty: {
                    description: {
                        ru: 'Несите свою грязную наличку: {{inputAmount}} на партию, {{rolledGoal}} партий. Что не свелось под книгу - осталось в барабане. Чистое везите в Дэвис.',
                        ua: 'Несіть свою брудну готівку: {{inputAmount}} на партію, {{rolledGoal}} партій. Що не зійшлося під книгу - лишилося в барабані. Чисте везіть у Девіс.',
                        en: 'Bring your own dirty cash: {{inputAmount}} a batch, {{rolledGoal}} batches. Whatever does not balance stays in the drum. Drive the clean stacks to Davis.',
                        de: 'Bringt euer eigenes schmutziges Geld: {{inputAmount}} pro Charge, {{rolledGoal}} Chargen. Was nicht aufgeht, bleibt in der Trommel. Das Saubere fahrt ihr nach Davis.',
                        pl: 'Przynieście własną brudną gotówkę: {{inputAmount}} na partię, {{rolledGoal}} partii. Co się nie zejdzie, zostaje w bębnie. Czyste wieźcie do Davis.',
                    },
                    objective: {
                        ru: 'Заложить {{inputName}} в машины, отмыть {{rolledGoal}} партий и сдать в Дэвисе',
                        ua: 'Закласти {{inputName}} у машини, відмити {{rolledGoal}} партій і здати в Девісі',
                        en: 'Load the machines with {{inputName}}, wash {{rolledGoal}} batches and hand them in at Davis',
                        de: '{{inputName}} in die Maschinen laden, {{rolledGoal}} Chargen waschen und in Davis abgeben',
                        pl: 'Załadować {{inputName}} do maszyn, wyprać {{rolledGoal}} partii i zdać w Davis',
                    },
                },
                usd: {
                    description: {
                        ru: 'Скупщик даёт сорок центов, я больше: я эту бумагу не перепродаю, а провожу через кассу. {{inputAmount}} на партию, {{rolledGoal}} партий. Везите ко мне в порт.',
                        ua: 'Скупник дає сорок центів, я більше: я цей папір не перепродаю, а проводжу через касу. {{inputAmount}} на партію, {{rolledGoal}} партій. Везіть до мене в порт.',
                        en: 'The fence pays forty cents, I pay more: I put this paper through the till instead of reselling it. {{inputAmount}} a batch, {{rolledGoal}} batches. Bring it to me at the port.',
                        de: 'Der Hehler zahlt vierzig Cent, ich mehr: dieses Papier verkaufe ich nicht weiter, es läuft durch die Kasse. {{inputAmount}} pro Charge, {{rolledGoal}} Chargen. Bringt es zu mir in den Hafen.',
                        pl: 'Paser daje czterdzieści centów, ja więcej: tego papieru nie odsprzedaję, przepuszczam go przez kasę. {{inputAmount}} na partię, {{rolledGoal}} partii. Wieźcie do mnie do portu.',
                    },
                    objective: {
                        ru: 'Отмыть {{rolledGoal}} партий из {{inputName}} и сдать Шэдоу в порту',
                        ua: 'Відмити {{rolledGoal}} партій із {{inputName}} і здати Шедоу в порту',
                        en: 'Wash {{rolledGoal}} batches of {{inputName}} and hand them to Shadow at the port',
                        de: '{{rolledGoal}} Chargen {{inputName}} waschen und Shadow im Hafen übergeben',
                        pl: 'Wyprać {{rolledGoal}} partii {{inputName}} i zdać Shadowowi w porcie',
                    },
                },
                eur: {
                    description: {
                        ru: 'Евро идут через кассу тяжелее: в книге купюры покрупнее. {{inputAmount}} на партию, {{rolledGoal}} партий. Отмытое везите к Гранд-Сеноре.',
                        ua: 'Євро йдуть через касу важче: у книзі купюри більші. {{inputAmount}} на партію, {{rolledGoal}} партій. Відмите везіть до Гранд-Сенори.',
                        en: 'Euros go through the till harder: the books are written in bigger notes. {{inputAmount}} a batch, {{rolledGoal}} batches. Drive the clean stacks out to Grand Senora.',
                        de: 'Euro laufen schwerer durch die Kasse: in den Büchern stehen größere Scheine. {{inputAmount}} pro Charge, {{rolledGoal}} Chargen. Das Gewaschene fahrt ihr nach Grand Senora.',
                        pl: 'Euro idą przez kasę ciężej: w księdze są większe nominały. {{inputAmount}} na partię, {{rolledGoal}} partii. Wyprane wieźcie pod Grand Senora.',
                    },
                    objective: {
                        ru: 'Отмыть {{rolledGoal}} партий из {{inputName}} и сдать у Гранд-Сеноры',
                        ua: 'Відмити {{rolledGoal}} партій із {{inputName}} і здати біля Гранд-Сенори',
                        en: 'Wash {{rolledGoal}} batches of {{inputName}} and hand them in at Grand Senora',
                        de: '{{rolledGoal}} Chargen {{inputName}} waschen und bei Grand Senora abgeben',
                        pl: 'Wyprać {{rolledGoal}} partii {{inputName}} i zdać przy Grand Senora',
                    },
                },
                gbp: {
                    description: {
                        ru: 'Фунты. Ничего крупнее полтинника, считать дольше, ошибок прощаю меньше. {{inputAmount}} на партию, {{rolledGoal}} партий. Чистое отдадите Риперу на холмах.',
                        ua: 'Фунти. Нічого більшого за півсотні, рахувати довше, помилок прощаю менше. {{inputAmount}} на партію, {{rolledGoal}} партій. Чисте віддасте Ріперу на пагорбах.',
                        en: 'Pounds. Nothing above a fifty, so the count runs longer and I forgive less. {{inputAmount}} a batch, {{rolledGoal}} batches. The clean stacks go to Reaper in the hills.',
                        de: 'Pfund. Nichts über einem Fünfziger, das Zählen dauert länger und ich verzeihe weniger. {{inputAmount}} pro Charge, {{rolledGoal}} Chargen. Das Saubere geht an Reaper in den Hügeln.',
                        pl: 'Funty. Nic powyżej pięćdziesiątki, liczenie trwa dłużej, a błędów wybaczam mniej. {{inputAmount}} na partię, {{rolledGoal}} partii. Czyste oddacie Reaperowi na wzgórzach.',
                    },
                    objective: {
                        ru: 'Отмыть {{rolledGoal}} партий из {{inputName}} и сдать Риперу',
                        ua: 'Відмити {{rolledGoal}} партій із {{inputName}} і здати Ріперу',
                        en: 'Wash {{rolledGoal}} batches of {{inputName}} and hand them to Reaper',
                        de: '{{rolledGoal}} Chargen {{inputName}} waschen und Reaper übergeben',
                        pl: 'Wyprać {{rolledGoal}} partii {{inputName}} i zdać Reaperowi',
                    },
                },
                chf: {
                    description: {
                        ru: 'Франки - лучшая бумага вашего пресса и самая злая лента. {{inputAmount}} на партию, {{rolledGoal}} партий. Брак остаётся в барабане. Привозите в Чумаш, лично.',
                        ua: 'Франки - найкращий папір вашого пресу і найзліша стрічка. {{inputAmount}} на партію, {{rolledGoal}} партій. Брак лишається в барабані. Привозьте в Чумаш, особисто.',
                        en: 'Francs. The best paper your press prints and the meanest belt. {{inputAmount}} a batch, {{rolledGoal}} batches. A scrapped run stays in the drum. Bring it to Chumash, in person.',
                        de: 'Franken. Das beste Papier eurer Presse und das gemeinste Band. {{inputAmount}} pro Charge, {{rolledGoal}} Chargen. Ausschuss bleibt in der Trommel. Bringt es persönlich nach Chumash.',
                        pl: 'Franki. Najlepszy papier waszej prasy i najbardziej wredna taśma. {{inputAmount}} na partię, {{rolledGoal}} partii. Brak zostaje w bębnie. Przywieźcie do Chumash, osobiście.',
                    },
                    objective: {
                        ru: 'Отмыть {{rolledGoal}} партий из {{inputName}} и сдать на побережье Чумаш',
                        ua: 'Відмити {{rolledGoal}} партій із {{inputName}} і здати на узбережжі Чумаш',
                        en: 'Wash {{rolledGoal}} batches of {{inputName}} and hand them in on the Chumash coast',
                        de: '{{rolledGoal}} Chargen {{inputName}} waschen und an der Küste von Chumash abgeben',
                        pl: 'Wyprać {{rolledGoal}} partii {{inputName}} i zdać na wybrzeżu Chumash',
                    },
                },
            },
        },
    },
    hud: {
        delivered: {
            ru: 'Сдано',
            ua: 'Здано',
            en: 'Handed in',
            de: 'Abgegeben',
            pl: 'Zdano',
        },
        inTransit: {
            ru: 'В пути',
            ua: 'В дорозі',
            en: 'In transit',
            de: 'Unterwegs',
            pl: 'W drodze',
        },
        onHand: {
            ru: 'У тебя на руках',
            ua: 'У тебе на руках',
            en: 'On you',
            de: 'Bei dir',
            pl: 'Przy tobie',
        },
        photosOnHand: {
            ru: 'Снимков в камере',
            ua: 'Знімків у камері',
            en: 'Frames in the camera',
            de: 'Aufnahmen in der Kamera',
            pl: 'Zdjęć w aparacie',
        },
        spotsLeftIn: {
            ru: 'Осталось точек - {{area}}',
            ua: 'Залишилось точок - {{area}}',
            en: 'Marks left - {{area}}',
            de: 'Punkte übrig - {{area}}',
            pl: 'Pozostało miejsc - {{area}}',
        },
        toProduce: {
            ru: 'Осталось произвести',
            ua: 'Залишилось виробити',
            en: 'Left to produce',
            de: 'Noch zu produzieren',
            pl: 'Zostalo do wyprodukowania',
        },
        objective: {
            ru: '{{item}}',
            ua: '{{item}}',
            en: '{{item}}',
            de: '{{item}}',
            pl: '{{item}}',
        },
        available: {
            ru: 'Осталось на точке',
            ua: 'Залишилось на точці',
            en: 'Left at the loading point',
            de: 'Am Beladepunkt uebrig',
            pl: 'Zostalo na punkcie',
        },
        // The line a runner-less contract adds to the block of the job it rides: the order's own
        // name, with its count. Nothing but the name - the block around it belongs to the job.
        contract: {
            ru: '{{contract}}',
            ua: '{{contract}}',
            en: '{{contract}}',
            de: '{{contract}}',
            pl: '{{contract}}',
        },
    },

    actions: {
        dropCrate: {
            ru: 'Выбросить ящик',
            ua: 'Викинути ящик',
            en: 'Drop the crate',
            de: 'Kiste wegwerfen',
            pl: 'Wyrzuć skrzynię',
        },
    },

    // Lines the camera viewfinder prints under the frame while a photo order is running.
    photo: {
        accepted: {
            ru: 'Снято: {{spot}}',
            ua: 'Знято: {{spot}}',
            en: 'Got it: {{spot}}',
            de: 'Im Kasten: {{spot}}',
            pl: 'Jest: {{spot}}',
        },
        status: {
            done: {
                ru: 'Эта точка уже снята',
                ua: 'Ця точка вже знята',
                en: 'This spot is already shot',
                de: 'Dieser Punkt ist schon im Kasten',
                pl: 'To miejsce jest już sfotografowane',
            },
        },
        // The notification after a frame the desk will pay for. The viewfinder says it too, but
        // the camera comes down the moment the shot is taken and the count has to survive that.
        notify: {
            shotReady: {
                ru: 'Снимок готов: {{spot}}. В камере кадров: {{shots}}, точек осталось: {{left}}. Плёнку сдают в Weazel News',
                ua: 'Знімок готовий: {{spot}}. У камері кадрів: {{shots}}, точок залишилось: {{left}}. Плівку здають у Weazel News',
                en: 'Frame ready: {{spot}}. {{shots}} in the camera, {{left}} marks left. The film goes to Weazel News',
                de: 'Aufnahme im Kasten: {{spot}}. {{shots}} in der Kamera, {{left}} Punkte übrig. Der Film geht zu Weazel News',
                pl: 'Zdjęcie gotowe: {{spot}}. W aparacie {{shots}}, pozostało miejsc: {{left}}. Film oddaje się w Weazel News',
            },
        },
        errors: {
            tooClose: {
                ru: 'Слишком близко - отойди на {{distance}} м',
                ua: 'Занадто близько - відійди на {{distance}} м',
                en: 'Too close - back off to {{distance}} m',
                de: 'Zu nah - geh auf {{distance}} m zurück',
                pl: 'Za blisko - odejdź na {{distance}} m',
            },
            tooFar: {
                ru: 'Слишком далеко - подойди ближе {{distance}} м',
                ua: 'Занадто далеко - підійди ближче {{distance}} м',
                en: 'Too far - get within {{distance}} m',
                de: 'Zu weit - komm auf {{distance}} m heran',
                pl: 'Za daleko - podejdź bliżej niż {{distance}} m',
            },
            alreadyShot: {
                ru: 'Этот вид уже сдан',
                ua: 'Цей вид уже здано',
                en: 'That view is already filed',
                de: 'Diese Ansicht ist schon abgegeben',
                pl: 'Ten widok jest już oddany',
            },
            subjectMissed: {
                ru: 'Нужного вида нет в кадре',
                ua: 'Потрібного виду немає в кадрі',
                en: 'The subject is out of frame',
                de: 'Das Motiv ist nicht im Bild',
                pl: 'Motyw jest poza kadrem',
            },
            framePlayer: {
                ru: 'В кадре человек',
                ua: 'У кадрі людина',
                en: 'Someone is in the shot',
                de: 'Jemand steht im Bild',
                pl: 'Ktoś jest w kadrze',
            },
            frameVehicle: {
                ru: 'В кадре машина',
                ua: 'У кадрі машина',
                en: 'A car is in the shot',
                de: 'Ein Auto steht im Bild',
                pl: 'Samochód jest w kadrze',
            },
            framePed: {
                ru: 'В кадре посторонний',
                ua: 'У кадрі стороння особа',
                en: 'A bystander is in the shot',
                de: 'Ein Passant steht im Bild',
                pl: 'Ktoś obcy jest w kadrze',
            },
            needMembers: {
                ru: 'Рядом должна быть семья',
                ua: 'Поруч має бути сім\'я',
                en: 'The family has to be here',
                de: 'Die Familie muss dabei sein',
                pl: 'Rodzina musi tu być',
            },
        },
    },

    // The zones the photo marks live in - a mark carries no name of its own, it is named after
    // its district. Values are the game's own region names (`files/locations/<lang>.json`), keyed
    // by the popzone label the coordinate falls in (`.claude/skills/gta-data`, `whereis.js`).
    photoZones: {
        lago: {
            ru: 'Лаго-Занкудо',
            ua: 'Лаго-Занкудо',
            en: 'Lago Zancudo',
            de: 'Lago Zancudo',
            pl: 'Lago Zancudo',
        },
        zancudo: {
            ru: 'Река Занкудо',
            ua: 'Річка Занкудо',
            en: 'Zancudo River',
            de: 'Zancudo River',
            pl: 'Rzeka Zancudo',
        },
        cmsw: {
            ru: 'Заповедник горы Чилиад',
            ua: 'Заповідник гори Чіліад',
            en: 'Chiliad Mountain State Wilderness',
            de: 'Chiliad-Mountain-Naturschutzgebiet',
            pl: 'Park krajobrazowy Góry Chiliad',
        },
        paleto: {
            ru: 'Палето-Бэй',
            ua: 'Палето-Бей',
            en: 'Paleto Bay',
            de: 'Paleto Bay',
            pl: 'Paleto Bay',
        },
        desrt: {
            ru: 'Пустыня Гранд-Сенора',
            ua: 'Пустеля Гранд-Сенора',
            en: 'Grand Senora Desert',
            de: 'Grand-Senora-Wüste',
            pl: 'Pustynia Grand Senora',
        },
        palfor: {
            ru: 'Лес Палето',
            ua: 'Ліс Палето',
            en: 'Paleto Forest',
            de: 'Paleto Forest',
            pl: 'Las Paleto',
        },
        oceana: {
            ru: 'Тихий океан',
            ua: 'Тихий океан',
            en: 'Pacific Ocean',
            de: 'Pazifik',
            pl: 'Ocean Spokojny',
        },
        mtchil: {
            ru: 'Гора Чилиад',
            ua: 'Гора Чіліад',
            en: 'Mount Chiliad',
            de: 'Mount Chiliad',
            pl: 'Góra Chiliad',
        },
        grapes: {
            ru: 'Грейпсид',
            ua: 'Грейпсід',
            en: 'Grapeseed',
            de: 'Grapeseed',
            pl: 'Grapeseed',
        },
        tongvah: {
            ru: 'Тонгва-Хиллз',
            ua: 'Тонгва-Гіллз',
            en: 'Tongva Hills',
            de: 'Tongva Hills',
            pl: 'Tongva Hills',
        },
        mtgordo: {
            ru: 'Гора Гордо',
            ua: 'Гора Гордо',
            en: 'Mount Gordo',
            de: 'Mount Gordo',
            pl: 'Góra Gordo',
        },
        sanchia: {
            ru: 'Сан-Шаньский горный хребет',
            ua: 'Сан-Шаньський хребет',
            en: 'San Chianski Mountain Range',
            de: 'San-Chianski-Bergkette',
            pl: 'Masyw górski San Chianski',
        },
        windf: {
            ru: 'Ветряная ферма Ron Alternates',
            ua: 'Вітрова ферма Ron Alternates',
            en: 'Ron Alternates Wind Farm',
            de: 'Ron-Alternates-Windpark',
            pl: 'Farma wiatrowa Ron Alternates',
        },
        palcov: {
            ru: 'Бухта Палето',
            ua: 'Бухта Палето',
            en: 'Paleto Cove',
            de: 'Paleto Cove',
            pl: 'Zatoka Paleto',
        },
        zquar: {
            ru: 'Дэвис-Кварц',
            ua: 'Девіс-Кварц',
            en: 'Davis Quartz',
            de: 'Davis Quartz',
            pl: 'Davis Quartz',
        },
        chu: {
            ru: 'Чумаш',
            ua: 'Чумаш',
            en: 'Chumash',
            de: 'Chumash',
            pl: 'Chumash',
        },
        bhamca: {
            ru: 'Каньон Бэнхэм',
            ua: 'Каньйон Бенгем',
            en: 'Banham Canyon',
            de: 'Banham Canyon',
            pl: 'Kanion Banham',
        },
    },

    labels: {
        trainStanding: {
            ru: 'Поезд на платформе:',
            ua: 'Поїзд на платформі:',
            en: 'Train at the platform:',
            de: 'Zug an der Rampe:',
            pl: 'Pociąg na rampie:',
        },
        trainEta: {
            ru: 'Поезд через:',
            ua: 'Поїзд через:',
            en: 'Train in:',
            de: 'Zug in:',
            pl: 'Pociąg za:',
        },
    },

    blips: {
        ...harvestBlips,
        ...cargoBlips,
        ...workBlips,
        quarryHub: {
            ru: 'Карьер',
            ua: "Кар'єр",
            en: 'Quarry site',
            de: 'Steinbruch',
            pl: 'Kamieniolom',
        },
        meetNpc: {
            ru: 'Заказчик',
            ua: 'Замовник',
            en: 'Client',
            de: 'Auftraggeber',
            pl: 'Zleceniodawca',
        },
        // Prefix of the contract NPC's map blip: composed as "<this>: <npc name>".
        contractNpc: {
            ru: 'Контракт',
            ua: 'Контракт',
            en: 'Contract',
            de: 'Auftrag',
            pl: 'Kontrakt',
        },
        stashDealer: {
            ru: 'Угол Дайса',
            ua: 'Ріг Дайса',
            en: "Dice's corner",
            de: 'Dice-Ecke',
            pl: 'Róg Dice',
        },
        // Where the film of a photo order is handed in - the Weazel News picture desk.
        pictureDesk: {
            ru: 'Фотослужба Weazel News',
            ua: 'Фотослужба Weazel News',
            en: 'Weazel News picture desk',
            de: 'Bildredaktion von Weazel News',
            pl: 'Dział zdjęć Weazel News',
        },
        // These read as a prefix, not as a standalone label: the runner composes them into
        // "<point> - <contract> <tier>" for the map legend and the GPS list.
        loading: {
            ru: 'Точка загрузки',
            ua: 'Точка завантаження',
            en: 'Loading point',
            de: 'Beladepunkt',
            pl: 'Punkt załadunku',
        },
        unloading: {
            ru: 'Точка разгрузки',
            ua: 'Точка розвантаження',
            en: 'Unloading point',
            de: 'Entladepunkt',
            pl: 'Punkt rozładunku',
        },
        dropoff: {
            ru: 'Точка сдачи',
            ua: 'Точка здачі',
            en: 'Drop-off point',
            de: 'Abgabepunkt',
            pl: 'Punkt zdawczy',
        },
        pickup: {
            ru: 'Точка погрузки',
            ua: 'Точка забору вантажу',
            en: 'Pickup point',
            de: 'Abholpunkt',
            pl: 'Punkt odbioru',
        },
        fishingSpot: {
            ru: 'Точка ловли',
            ua: 'Точка лову',
            en: 'Fishing spot',
            de: 'Angelplatz',
            pl: 'Łowisko',
        },
        seafoodDepot: {
            ru: 'Приёмка улова',
            ua: 'Приймання улову',
            en: 'Catch receiving depot',
            de: 'Fanganlieferung',
            pl: 'Punkt odbioru połowu',
        },
        // Station labels stand alone in the GPS list - they name a real place, so they are
        // NOT composed with the contract the way the pickup/drop-off prefixes are.
        station: {
            ru: 'Рабочая точка',
            ua: 'Робоча точка',
            en: 'Workstation',
            de: 'Arbeitsplatz',
            pl: 'Stanowisko',
        },
        atelierStation: {
            ru: 'Швейная фабрика',
            ua: 'Швейна фабрика',
            en: 'Sewing factory',
            de: 'Nähfabrik',
            pl: 'Fabryka odzieżowa',
        },
        laundromat: {
            ru: 'Прачечная',
            ua: 'Пральня',
            en: 'Laundromat',
            de: 'Waschsalon',
            pl: 'Pralnia',
        },
    },
    // Subject keys mirror the real item / model ids the game emits, so a rolled
    // subject can be matched against the incoming event tag.
    subjects: {
        // The laundry's rungs (`LAUNDROMAT_TIERS`): what goes into the drum on that tier.
        laundryStack: {
            house: {
                ru: 'Наличные Шэдоу',
                ua: 'Готівка Шедоу',
                en: "Shadow's cash",
                de: 'Shadows Bargeld',
                pl: 'Gotówka Shadowa',
            },
            dirty: {
                ru: 'Грязные деньги',
                ua: 'Брудні гроші',
                en: 'Dirty money',
                de: 'Schmutziges Geld',
                pl: 'Brudne pieniądze',
            },
            usd: {
                ru: 'Фальшивые доллары',
                ua: 'Фальшиві долари',
                en: 'Counterfeit dollars',
                de: 'Falsche Dollar',
                pl: 'Fałszywe dolary',
            },
            eur: {
                ru: 'Фальшивые евро',
                ua: 'Фальшиві євро',
                en: 'Counterfeit euros',
                de: 'Falsche Euro',
                pl: 'Fałszywe euro',
            },
            gbp: {
                ru: 'Фальшивые фунты',
                ua: 'Фальшиві фунти',
                en: 'Counterfeit pounds',
                de: 'Falsche Pfund',
                pl: 'Fałszywe funty',
            },
            chf: {
                ru: 'Фальшивые франки',
                ua: 'Фальшиві франки',
                en: 'Counterfeit francs',
                de: 'Falsche Franken',
                pl: 'Fałszywe franki',
            },
        },
        // What the chop shop ordered. The tier IS the vehicle class the carjacker job sends
        // the driver after (`shared/configs/carjacker.ts`), so these seven read in the same
        // order as its seven bands.
        chopClass: {
            street: {
                ru: 'Уличные седаны',
                ua: 'Вуличні седани',
                en: 'Street sedans',
                de: 'Straßenlimousinen',
                pl: 'Uliczne sedany',
            },
            middle: {
                ru: 'Средний класс',
                ua: 'Середній клас',
                en: 'Mid-range cars',
                de: 'Mittelklasse',
                pl: 'Średnia klasa',
            },
            sport: {
                ru: 'Спорткары',
                ua: 'Спорткари',
                en: 'Sports cars',
                de: 'Sportwagen',
                pl: 'Sportowe auta',
            },
            premium: {
                ru: 'Премиум и кроссоверы',
                ua: 'Преміум і кросовери',
                en: 'Premium and crossovers',
                de: 'Premium und Crossover',
                pl: 'Premium i crossovery',
            },
            luxury: {
                ru: 'Люкс и суперкары',
                ua: 'Люкс і суперкари',
                en: 'Luxury and supercars',
                de: 'Luxus und Supersportwagen',
                pl: 'Luksus i superauta',
            },
            hyper: {
                ru: 'Гиперкары',
                ua: 'Гіперкари',
                en: 'Hypercars',
                de: 'Hypersportwagen',
                pl: 'Hiperauta',
            },
            legend: {
                ru: 'Легенды',
                ua: 'Легенди',
                en: 'Legends',
                de: 'Legenden',
                pl: 'Legendy',
            },
        },
        // Who the atelier order is for. The tier picks the client, and the client owns the
        // address the finished batch is driven to.
        atelierClient: {
            medical: {
                ru: 'Медицинская служба Лос-Сантоса',
                ua: 'Медична служба Лос-Сантоса',
                en: 'Los Santos Medical Service',
                de: 'Rettungsdienst von Los Santos',
                pl: 'Służba medyczna Los Santos',
            },
            police: {
                ru: 'Департамент полиции Лос-Сантоса',
                ua: 'Департамент поліції Лос-Сантоса',
                en: 'Los Santos Police Department',
                de: 'Polizeibehörde von Los Santos',
                pl: 'Departament policji Los Santos',
            },
            cityHall: {
                ru: 'Мэрия Лос-Сантоса',
                ua: 'Мерія Лос-Сантоса',
                en: 'Los Santos City Hall',
                de: 'Rathaus von Los Santos',
                pl: 'Ratusz Los Santos',
            },
            // The project shows this agency as the bare acronym in every language
            // (see localization/faction/factions/fib.js) - keep it consistent.
            fib: {
                ru: 'FIB',
                ua: 'FIB',
                en: 'FIB',
                de: 'FIB',
                pl: 'FIB',
            },
            prison: {
                ru: 'Федеральная тюрьма Болингброк',
                ua: "Федеральна в'язниця Болінгброк",
                en: 'Bolingbroke Penitentiary',
                de: 'Staatsgefängnis Bolingbroke',
                pl: 'Więzienie Bolingbroke',
            },
            nationalGuard: {
                ru: 'Национальная гвардия Сан-Андреас',
                ua: 'Національна гвардія Сан-Андреас',
                en: 'San Andreas National Guard',
                de: 'Nationalgarde von San Andreas',
                pl: 'Gwardia Narodowa San Andreas',
            },
        },
        ore: {
            iron: {
                ru: 'Железную руду',
                ua: 'Залізну руду',
                en: 'Iron ore',
                de: 'Eisenerz',
                pl: 'Rudę żelaza',
            },
            copper: {
                ru: 'Медную руду',
                ua: 'Мідну руду',
                en: 'Copper ore',
                de: 'Kupfererz',
                pl: 'Rudę miedzi',
            },
            lithium: {
                ru: 'Литиевый минерал',
                ua: 'Літієвий мінерал',
                en: 'Lithium mineral',
                de: 'Lithiummineral',
                pl: 'Minerał litu',
            },
            tin: {
                ru: 'Оловянную руду',
                ua: "Олов'яну руду",
                en: 'Tin ore',
                de: 'Zinnerz',
                pl: 'Rudę cyny',
            },
        },
        fish: {
            pike: {
                ru: 'Щуку',
                ua: 'Щуку',
                en: 'Pike',
                de: 'Hecht',
                pl: 'Szczupaka',
            },
            trout: {
                ru: 'Форель',
                ua: 'Форель',
                en: 'Trout',
                de: 'Forelle',
                pl: 'Pstrąga',
            },
            salmon: {
                ru: 'Лосося',
                ua: 'Лосося',
                en: 'Salmon',
                de: 'Lachs',
                pl: 'Łososia',
            },
            seaBass: {
                ru: 'Морского окуня',
                ua: 'Морського окуня',
                en: 'Sea bass',
                de: 'Wolfsbarsch',
                pl: 'Labraksa',
            },
            bluefinTuna: {
                ru: 'Голубого тунца',
                ua: 'Блакитного тунця',
                en: 'Bluefin tuna',
                de: 'Blauflossen-Thunfisch',
                pl: 'Tuńczyka błękitnopłetwego',
            },
            blueMarlin: {
                ru: 'Голубого марлина',
                ua: 'Блакитного марліна',
                en: 'Blue marlin',
                de: 'Blauer Marlin',
                pl: 'Marlina błękitnego',
            },
        },
    },
    success: {
        // A photo order is a district rather than a list of named places, so the one thing the
        // taker has to hear is where they are driving.
        photoTaken: {
            ru: 'Контракт {{contract}} принят: {{goal}} снимков, район - {{area}}.',
            ua: 'Контракт {{contract}} прийнятий: {{goal}} знімків, район - {{area}}.',
            en: 'Contract {{contract}} taken: {{goal}} pictures around {{area}}.',
            de: 'Vertrag {{contract}} angenommen: {{goal}} Aufnahmen im Gebiet {{area}}.',
            pl: 'Kontrakt {{contract}} przyjęty: {{goal}} zdjęć, rejon - {{area}}.',
        },
        taken: {
            ru: 'Контракт {{contract}} принят. Цель: {{goal}}.',
            ua: 'Контракт {{contract}} прийнятий. Мета: {{goal}}.',
            en: 'Contract {{contract}} taken. Goal: {{goal}}.',
            de: 'Vertrag {{contract}} angenommen. Ziel: {{goal}}.',
            pl: 'Kontrakt {{contract}} przyjęty. Cel: {{goal}}.',
        },
        familyTaken: {
            ru: 'Семейный контракт {{contract}} принят на группу. Цель: {{goal}}.',
            ua: 'Сімейний контракт {{contract}} прийнятий на групу. Мета: {{goal}}.',
            en: 'Family contract {{contract}} taken by the party. Goal: {{goal}}.',
            de: 'Familienvertrag {{contract}} für die Gruppe angenommen. Ziel: {{goal}}.',
            pl: 'Kontrakt rodzinny {{contract}} przyjęty przez grupę. Cel: {{goal}}.',
        },
        abandoned: {
            ru: 'Контракт {{contract}} отменён.',
            ua: 'Контракт {{contract}} скасовано.',
            en: 'Contract {{contract}} abandoned.',
            de: 'Vertrag {{contract}} abgebrochen.',
            pl: 'Kontrakt {{contract}} anulowany.',
        },
        completedPersonal: {
            ru: 'Контракт {{contract}} выполнен! Награда зачислена.',
            ua: 'Контракт {{contract}} виконано! Винагороду зараховано.',
            en: 'Contract {{contract}} completed! Reward applied.',
            de: 'Vertrag {{contract}} abgeschlossen! Belohnung gutgeschrieben.',
            pl: 'Kontrakt {{contract}} wykonany! Nagroda zaliczona.',
        },
        completedFamily: {
            ru: 'Семейный контракт {{contract}} выполнен! Награда зачислена на баланс организации.',
            ua: 'Сімейний контракт {{contract}} виконано! Винагороду зараховано на баланс організації.',
            en: 'Family contract {{contract}} completed! The reward went to the organization balance.',
            de: 'Familienvertrag {{contract}} abgeschlossen! Die Belohnung ging auf das Organisationsguthaben.',
            pl: 'Kontrakt rodzinny {{contract}} wykonany! Nagroda trafiła na bilans organizacji.',
        },
        completedFamilyShared: {
            ru: 'Семейный контракт {{contract}} выполнен! Участники получили {{share}}% награды по вкладу.',
            ua: 'Сімейний контракт {{contract}} виконано! Учасники отримали {{share}}% винагороди за внеском.',
            en: 'Family contract {{contract}} completed! Members received {{share}}% of the reward by contribution.',
            de: 'Familienvertrag {{contract}} abgeschlossen! Die Mitglieder erhielten {{share}}% der Belohnung nach Beitrag.',
            pl: 'Kontrakt rodzinny {{contract}} wykonany! Członkowie otrzymali {{share}}% nagrody według wkładu.',
        },
        batchDelivered: {
            ru: 'Партия принята: {{units}} ед. зачтено в контракт.',
            ua: 'Партію прийнято: {{units}} од. зараховано в контракт.',
            en: 'Batch accepted: {{units}} units counted toward the contract.',
            de: 'Charge angenommen: {{units}} Einheiten auf den Vertrag angerechnet.',
            pl: 'Partia przyjęta: zaliczono {{units}} jedn. do kontraktu.',
        },
        photosDelivered: {
            ru: 'Фотослужба приняла снимков: {{units}}. Зачтено в контракт.',
            ua: 'Фотослужба прийняла знімків: {{units}}. Зараховано в контракт.',
            en: 'The picture desk took {{units}} frames. Counted toward the contract.',
            de: 'Die Bildredaktion hat {{units}} Aufnahmen genommen. Auf den Vertrag angerechnet.',
            pl: 'Dział zdjęć przyjął {{units}} zdjęć. Zaliczono do kontraktu.',
        },
        crateLoaded: {
            ru: 'Ящик в багажнике. Можно грузить следующий.',
            ua: 'Ящик у багажнику. Можна вантажити наступний.',
            en: 'Crate is in the boot. Go get the next one.',
            de: 'Kiste liegt im Kofferraum. Hol die nächste.',
            pl: 'Skrzynia w bagażniku. Możesz brać kolejną.',
        },
    },
    info: {
        progress: {
            ru: 'Прогресс {{contract}}: {{progress}}/{{goal}}.',
            ua: 'Прогрес {{contract}}: {{progress}}/{{goal}}.',
            en: 'Progress on {{contract}}: {{progress}}/{{goal}}.',
            de: 'Fortschritt {{contract}}: {{progress}}/{{goal}}.',
            pl: 'Postęp {{contract}}: {{progress}}/{{goal}}.',
        },
        familyProgress: {
            ru: 'Семейный прогресс {{contract}}: {{progress}}/{{goal}}.',
            ua: 'Сімейний прогрес {{contract}}: {{progress}}/{{goal}}.',
            en: 'Family progress on {{contract}}: {{progress}}/{{goal}}.',
            de: 'Familienfortschritt {{contract}}: {{progress}}/{{goal}}.',
            pl: 'Postęp rodzinny {{contract}}: {{progress}}/{{goal}}.',
        },
        status: {
            ru: 'Текущий контракт: {{contract}}, прогресс {{progress}}/{{goal}}.',
            ua: 'Поточний контракт: {{contract}}, прогрес {{progress}}/{{goal}}.',
            en: 'Current contract: {{contract}}, progress {{progress}}/{{goal}}.',
            de: 'Aktueller Vertrag: {{contract}}, Fortschritt {{progress}}/{{goal}}.',
            pl: 'Aktualny kontrakt: {{contract}}, postęp {{progress}}/{{goal}}.',
        },
        familyStatus: {
            ru: 'Семейный контракт: {{contract}}, прогресс {{progress}}/{{goal}}.',
            ua: 'Сімейний контракт: {{contract}}, прогрес {{progress}}/{{goal}}.',
            en: 'Family contract: {{contract}}, progress {{progress}}/{{goal}}.',
            de: 'Familienvertrag: {{contract}}, Fortschritt {{progress}}/{{goal}}.',
            pl: 'Kontrakt rodzinny: {{contract}}, postęp {{progress}}/{{goal}}.',
        },
        deliverNow: {
            ru: 'Груз у вас. Везите его к точке сдачи на карте.',
            ua: 'Вантаж у вас. Везіть його до точки здачі на карті.',
            en: 'Cargo is on you. Take it to the drop-off marker on the map.',
            de: 'Du hast die Ladung. Bring sie zur Abgabestelle auf der Karte.',
            pl: 'Masz łup. Wieź go do punktu zdania na mapie.',
        },
        crateDropped: {
            ru: 'Ящик выброшен. Можно взять другой на точке погрузки.',
            ua: 'Ящик викинуто. Можна взяти інший на точці завантаження.',
            en: 'Crate dropped. There is another one waiting at the loading point.',
            de: 'Kiste weggeworfen. Am Beladepunkt liegt die nächste.',
            pl: 'Skrzynia wyrzucona. Na punkcie załadunku czeka kolejna.',
        },
        loadIntoTrunk: {
            ru: 'Ящик у вас в руках. Положите его в багажник машины - за рулём с ним не поехать.',
            ua: 'Ящик у вас у руках. Покладіть його в багажник машини - за кермом з ним не поїхати.',
            en: 'The crate is in your hands. Put it in a car boot - you cannot drive holding it.',
            de: 'Die Kiste ist in deinen Händen. Leg sie in einen Kofferraum - damit fährst du nicht.',
            pl: 'Trzymasz skrzynię. Włóż ją do bagażnika - z nią nie poprowadzisz auta.',
        },
        needPickupFirst: {
            ru: 'Сначала заберите груз с точки погрузки.',
            ua: 'Спершу заберіть вантаж з точки завантаження.',
            en: 'Pick up the cargo first.',
            de: 'Hol erst die Ladung am Beladepunkt ab.',
            pl: 'Najpierw odbierz łup z punktu załadunku.',
        },
        alreadyCarrying: {
            ru: 'Вы уже несёте груз по этому контракту.',
            ua: 'Ви вже несете вантаж за цим контрактом.',
            en: 'You are already carrying cargo for this contract.',
            de: 'Du trägst bereits Ladung für diesen Vertrag.',
            pl: 'Już niesiesz łup z tego kontraktu.',
        },
        batchProduced: {
            ru: 'Готово: +{{units}}. Не сдано: {{pending}}. Отвезите партию заказчику.',
            ua: 'Готово: +{{units}}. Не здано: {{pending}}. Відвезіть партію замовнику.',
            en: 'Done: +{{units}}. Undelivered: {{pending}}. Take the batch to the client.',
            de: 'Fertig: +{{units}}. Nicht abgegeben: {{pending}}. Bring die Charge zum Kunden.',
            pl: 'Gotowe: +{{units}}. Niezdane: {{pending}}. Zawieź partię zleceniodawcy.',
        },
        nothingToDeliver: {
            ru: 'Сдавать нечего - сначала изготовьте партию.',
            ua: 'Здавати нічого - спершу виготовте партію.',
            en: 'Nothing to hand in - make a batch first.',
            de: 'Nichts abzugeben - fertige zuerst eine Charge.',
            pl: 'Nie ma czego zdać - najpierw zrób partię.',
        },
    },
    errors: {
        stationInputMissing: {
            ru: 'Для партии нужно {{amount}} {{itemName}}. Принесите пачку к машине.',
            ua: 'Для партії потрібно {{amount}} {{itemName}}. Принесіть пачку до машини.',
            en: 'A batch takes {{amount}} {{itemName}}. Bring the stack to the machine.',
            de: 'Eine Charge braucht {{amount}} {{itemName}}. Bring das Bündel zur Maschine.',
            pl: 'Partia wymaga {{amount}} {{itemName}}. Przynieś plik do maszyny.',
        },
        noTrunk: {
            ru: 'У этой машины нет багажника для груза.',
            ua: 'У цієї машини немає багажника для вантажу.',
            en: 'This car has no boot for the load.',
            de: 'Dieses Auto hat keinen Kofferraum für die Ladung.',
            pl: 'To auto nie ma bagażnika na ładunek.',
        },
        noTrunkAccess: {
            ru: 'Багажник этой машины для вас закрыт.',
            ua: 'Багажник цієї машини для вас зачинений.',
            en: 'This car keeps its boot shut to you.',
            de: 'Der Kofferraum dieses Autos bleibt für dich zu.',
            pl: 'Bagażnik tego auta jest dla ciebie zamknięty.',
        },
        trunkFull: {
            ru: 'Багажник полный - ящик туда не влезет.',
            ua: 'Багажник повний - ящик туди не влізе.',
            en: 'The boot is full - the crate will not fit.',
            de: 'Der Kofferraum ist voll - die Kiste passt nicht.',
            pl: 'Bagażnik jest pełny - skrzynia się nie zmieści.',
        },
        notInGame: {
            ru: 'Сначала войдите в игру.',
            ua: 'Спочатку увійдіть у гру.',
            en: 'You must be in-game first.',
            de: 'Du musst zuerst im Spiel sein.',
            pl: 'Najpierw wejdź do gry.',
        },
        notInOrg: {
            ru: 'Вы не состоите в организации.',
            ua: 'Ви не перебуваєте в організації.',
            en: 'You are not in an organization.',
            de: 'Du bist in keiner Organisation.',
            pl: 'Nie należysz do organizacji.',
        },
        unknownContract: {
            ru: 'Неизвестный контракт.',
            ua: 'Невідомий контракт.',
            en: 'Unknown contract.',
            de: 'Unbekannter Vertrag.',
            pl: 'Nieznany kontrakt.',
        },
        missingContractId: {
            ru: 'Укажите id контракта: /contract take <id>',
            ua: 'Вкажіть id контракту: /contract take <id>',
            en: 'Specify contract id: /contract take <id>',
            de: 'Vertrags-ID angeben: /contract take <id>',
            pl: 'Podaj id kontraktu: /contract take <id>',
        },
        noPermissionPersonal: {
            ru: 'Ваш ранг не имеет права брать личные контракты.',
            ua: 'Ваш ранг не має права брати особисті контракти.',
            en: 'Your rank cannot take personal contracts.',
            de: 'Dein Rang darf keine persönlichen Verträge annehmen.',
            pl: 'Twoja ranga nie może brać osobistych kontraktów.',
        },
        noPermissionFamily: {
            ru: 'Ваш ранг не имеет права брать семейные контракты.',
            ua: 'Ваш ранг не має права брати сімейні контракти.',
            en: 'Your rank cannot take family contracts.',
            de: 'Dein Rang darf keine Familienverträge annehmen.',
            pl: 'Twoja ranga nie może brać kontraktów rodzinnych.',
        },
        notUnlockedInTree: {
            ru: 'Этот контракт ещё не разблокирован в дереве улучшений.',
            ua: 'Цей контракт ще не розблоковано у дереві покращень.',
            en: 'This contract is not yet unlocked in the upgrade tree.',
            de: 'Dieser Vertrag ist im Upgrade-Baum noch nicht freigeschaltet.',
            pl: 'Ten kontrakt nie jest jeszcze odblokowany w drzewie ulepszeń.',
        },
        alreadyHaveContract: {
            ru: 'У вас уже есть активный контракт.',
            ua: 'У вас вже є активний контракт.',
            en: 'You already have an active contract.',
            de: 'Du hast bereits einen aktiven Vertrag.',
            pl: 'Masz już aktywny kontrakt.',
        },
        notInParty: {
            ru: 'Вы не в группе. Создайте её через /createparty.',
            ua: 'Ви не в групі. Створіть її через /createparty.',
            en: 'You are not in a party. Use /createparty.',
            de: 'Du bist in keiner Gruppe. Nutze /createparty.',
            pl: 'Nie jesteś w grupie. Użyj /createparty.',
        },
        notPartyLeader: {
            ru: 'Только лидер группы может брать семейный контракт.',
            ua: 'Тільки лідер групи може брати сімейний контракт.',
            en: 'Only the party leader can take a family contract.',
            de: 'Nur der Gruppen-Leader kann einen Familienvertrag annehmen.',
            pl: 'Tylko lider grupy może wziąć kontrakt rodzinny.',
        },
        partyTooSmall: {
            ru: 'В группе должно быть минимум 2 человека.',
            ua: 'У групі має бути мінімум 2 особи.',
            en: 'Party must have at least 2 members.',
            de: 'Gruppe braucht mindestens 2 Mitglieder.',
            pl: 'Grupa musi mieć minimum 2 członków.',
        },
        partyMixedOrgs: {
            ru: 'Все участники группы должны быть в одной организации.',
            ua: 'Усі учасники групи мають бути в одній організації.',
            en: 'All party members must be in the same organization.',
            de: 'Alle Mitglieder müssen in derselben Organisation sein.',
            pl: 'Wszyscy członkowie grupy muszą być w tej samej organizacji.',
        },
        partyMemberHasContract: {
            ru: 'У одного из членов группы уже есть активный контракт.',
            ua: 'Один з членів групи вже має активний контракт.',
            en: 'A party member already has an active contract.',
            de: 'Ein Gruppenmitglied hat bereits einen aktiven Vertrag.',
            pl: 'Członek grupy ma już aktywny kontrakt.',
        },
        noActiveContract: {
            ru: 'У вас нет активного контракта.',
            ua: 'У вас немає активного контракту.',
            en: 'You have no active contract.',
            de: 'Du hast keinen aktiven Vertrag.',
            pl: 'Nie masz aktywnego kontraktu.',
        },
        notEnoughLegalReputation: {
            ru: 'Не хватает доверия для этого контракта.',
            ua: 'Не вистачає довіри для цього контракту.',
            en: 'Not enough trust for this contract.',
            de: 'Zu wenig Vertrauen für diesen Vertrag.',
            pl: 'Za mało zaufania na ten kontrakt.',
        },
        notEnoughCrimeReputation: {
            ru: 'Не хватает авторитета для этого контракта.',
            ua: 'Не вистачає авторитету для цього контракту.',
            en: 'Not enough respect for this contract.',
            de: 'Zu wenig Ansehen für diesen Vertrag.',
            pl: 'Za mało autorytetu na ten kontrakt.',
        },
        notEnoughMoneyToActivate: {
            ru: 'Недостаточно наличных для активации контракта.',
            ua: 'Недостатньо готівки для активації контракту.',
            en: 'Not enough cash to activate the contract.',
            de: 'Nicht genug Bargeld, um den Vertrag zu aktivieren.',
            pl: 'Za mało gotówki, aby aktywować kontrakt.',
        },
        notEnoughOrgMoneyToActivate: {
            ru: 'На балансе организации недостаточно денег для активации контракта.',
            ua: 'На балансі організації недостатньо грошей для активації контракту.',
            en: 'The organization balance cannot cover the contract activation.',
            de: 'Das Organisationsguthaben reicht nicht für die Vertragsaktivierung.',
            pl: 'Bilans organizacji nie pokryje aktywacji kontraktu.',
        },
        characterLevelTooLow: {
            ru: 'Ваш уровень персонажа слишком низкий для этого контракта.',
            ua: 'Ваш рівень персонажа замалий для цього контракту.',
            en: 'Your character level is too low for this contract.',
            de: 'Dein Charakterlevel ist für diesen Vertrag zu niedrig.',
            pl: 'Twój poziom postaci jest za niski na ten kontrakt.',
        },
        notEnoughOrgMembers: {
            ru: 'В организации слишком мало людей для этого контракта.',
            ua: 'В організації замало людей для цього контракту.',
            en: 'The organization is too small for this contract.',
            de: 'Die Organisation hat zu wenige Mitglieder für diesen Vertrag.',
            pl: 'Organizacja ma za mało członków na ten kontrakt.',
        },
        noFactory: {
            ru: 'Заказ выполняют только на своём предприятии - организация его не контролирует.',
            ua: 'Замовлення виконують лише на своєму підприємстві - організація його не контролює.',
            en: 'This order is only filled at your own facility - the organization does not control one.',
            de: 'Dieser Auftrag wird nur im eigenen Betrieb erfüllt - die Organisation kontrolliert keinen.',
            pl: 'To zlecenie realizuje się tylko we własnym zakładzie - organizacja żadnego nie kontroluje.',
        },
        noProperty: {
            ru: 'Нужен семейный склад - без него заказчик не работает.',
            ua: 'Потрібен сімейний склад - без нього замовник не працює.',
            en: 'You need a family warehouse - the client will not deal without one.',
            de: 'Ihr braucht ein Familienlager - ohne das arbeitet der Kunde nicht.',
            pl: 'Potrzebny jest magazyn rodziny - bez niego zleceniodawca nie współpracuje.',
        },
        missingItems: {
            ru: 'На складе организации не хватает нужных предметов.',
            ua: 'На складі організації бракує потрібних предметів.',
            en: 'The organization warehouse is missing the required items.',
            de: 'Im Lager der Organisation fehlen die nötigen Gegenstände.',
            pl: 'W magazynie organizacji brakuje wymaganych przedmiotów.',
        },
        jobRankTooLow: {
            ru: 'Нужен более высокий ранг работы.',
            ua: 'Потрібен вищий ранг роботи.',
            en: 'You need a higher job rank.',
            de: 'Du brauchst einen höheren Job-Rang.',
            pl: 'Potrzebujesz wyższej rangi pracy.',
        },
        sideJobLocked: {
            ru: 'Организация не открыла подработку, на которой держится этот контракт.',
            ua: 'Організація не відкрила підробіток, на якому тримається цей контракт.',
            en: 'The organization has not opened the side job this contract rides.',
            de: 'Die Organisation hat den Nebenjob, auf dem dieser Vertrag läuft, nicht freigeschaltet.',
            pl: 'Organizacja nie otworzyła dorywczej pracy, na której opiera się ten kontrakt.',
        },
        notOffered: {
            ru: 'Этого контракта нет в текущем наборе - набор обновится после рестарта.',
            ua: 'Цього контракту немає в поточному наборі - набір оновиться після рестарту.',
            en: 'This contract is not on the current roster - the roster is rolled again after the restart.',
            de: 'Dieser Vertrag steht nicht auf der aktuellen Liste - die Liste wird nach dem Neustart neu gewuerfelt.',
            pl: 'Tego kontraktu nie ma w aktualnym zestawie - zestaw odswiezy sie po restarcie.',
        },
        alreadyCompleted: {
            ru: 'Этот контракт уже выполнен - он вернётся со следующим набором.',
            ua: 'Цей контракт уже виконано - він повернеться з наступним набором.',
            en: 'This contract is already done - it comes back with the next roster.',
            de: 'Dieser Vertrag ist bereits erledigt - er kehrt mit der nächsten Liste zurück.',
            pl: 'Ten kontrakt jest już wykonany - wróci z następnym zestawem.',
        },
        takeInProgress: {
            ru: 'Организация уже берёт контракт, попробуйте ещё раз.',
            ua: 'Організація вже бере контракт, спробуйте ще раз.',
            en: 'The organization is already taking a contract, try again.',
            de: 'Die Organisation nimmt bereits einen Vertrag an, versuche es erneut.',
            pl: 'Organizacja właśnie bierze kontrakt, spróbuj ponownie.',
        },
        alreadyRunningInOrg: {
            ru: 'Этот контракт уже выполняет другой участник организации.',
            ua: 'Цей контракт уже виконує інший учасник організації.',
            en: 'Another member of the organization is already running this contract.',
            de: 'Ein anderes Mitglied der Organisation führt diesen Vertrag bereits aus.',
            pl: 'Inny członek organizacji już wykonuje ten kontrakt.',
        },
        orgHasActiveContract: {
            ru: 'У организации уже есть активный контракт.',
            ua: 'В організації вже є активний контракт.',
            en: 'Organization already has an active contract.',
            de: 'Organisation hat bereits einen aktiven Vertrag.',
            pl: 'Organizacja ma już aktywny kontrakt.',
        },
        onlyLeaderCanAbandonFamily: {
            ru: 'Отменить семейный контракт может только лидер или офицер.',
            ua: 'Скасувати сімейний контракт може тільки лідер або офіцер.',
            en: 'Only the leader or an officer can abandon a family contract.',
            de: 'Nur Leader oder Offizier kann einen Familienvertrag abbrechen.',
            pl: 'Tylko lider lub oficer może anulować kontrakt rodzinny.',
        },
        contractFailed: {
            ru: 'Контракт {{contract}} провален: {{reason}}.',
            ua: 'Контракт {{contract}} провалено: {{reason}}.',
            en: 'Contract {{contract}} failed: {{reason}}.',
            de: 'Vertrag {{contract}} fehlgeschlagen: {{reason}}.',
            pl: 'Kontrakt {{contract}} nieudany: {{reason}}.',
        },
    },
    fail: {
        reasons: {
            timeout: {
                ru: 'истёк таймер контракта',
                ua: 'час контракту вичерпано',
                en: 'contract timer expired',
                de: 'Vertragszeit abgelaufen',
                pl: 'czas kontraktu wygasł',
            },
        },
    },
    warning: {
        stationInputLost: {
            ru: 'Партия ушла в брак. {{amount}} {{itemName}} остались в барабане.',
            ua: 'Партія пішла в брак. {{amount}} {{itemName}} лишилися в барабані.',
            en: 'The batch was scrapped. {{amount}} {{itemName}} stayed in the drum.',
            de: 'Die Charge ist Ausschuss. {{amount}} {{itemName}} sind in der Trommel geblieben.',
            pl: 'Partia poszła na straty. {{amount}} {{itemName}} zostało w bębnie.',
        },
        needMembersNearby: {
            ru: 'Работать по контракту {{contract}} нужно вместе: рядом должно быть {{required}} членов организации (в радиусе {{radius}} м). Сдавать груз можно и в одиночку.',
            ua: 'Працювати за контрактом {{contract}} потрібно разом: поруч має бути {{required}} членів організації (у радіусі {{radius}} м). Здавати вантаж можна й самому.',
            en: 'Working the {{contract}} contract takes a crew: {{required}} organization members within {{radius}} m. Handing the load in can be done alone.',
            de: 'Am Auftrag {{contract}} wird gemeinsam gearbeitet: {{required}} Mitglieder im Umkreis von {{radius}} m. Die Abgabe geht auch allein.',
            pl: 'Przy kontrakcie {{contract}} pracuje się razem: {{required}} członków organizacji w promieniu {{radius}} m. Zdać ładunek można samemu.',
        },
        maxPerPlayerReached: {
            ru: 'По контракту {{contract}} с одного игрока принимаем максимум {{cap}} единиц. Передайте остаток партнёрам.',
            ua: 'За контрактом {{contract}} від одного гравця приймаємо максимум {{cap}} одиниць. Передайте залишок партнерам.',
            en: 'Contract {{contract}} accepts up to {{cap}} units from one player. Let your partners handle the rest.',
            de: 'Vertrag {{contract}} nimmt von einem Spieler höchstens {{cap}} Einheiten. Den Rest sollen die Partner erledigen.',
            pl: 'Kontrakt {{contract}} przyjmuje maksymalnie {{cap}} jednostek od jednego gracza. Resztę niech wezmą partnerzy.',
        },
        busy: {
            ru: 'Дождитесь окончания текущего действия.',
            ua: 'Зачекайте завершення поточної дії.',
            en: 'Wait until the current action finishes.',
            de: 'Warte, bis die aktuelle Aktion abgeschlossen ist.',
            pl: 'Poczekaj na zakończenie obecnej akcji.',
        },
        seatOccupied: {
            ru: 'За этим станком уже работают. Займите свободный.',
            ua: 'За цим верстатом вже працюють. Займіть вільний.',
            en: 'Somebody is already working at this machine. Take a free one.',
            de: 'An dieser Maschine arbeitet bereits jemand. Nimm eine freie.',
            pl: 'Przy tej maszynie ktoś już pracuje. Zajmij wolną.',
        },
        trainNotStanding: {
            ru: 'Поезда на платформе нет. Состав встаёт здесь на пятнадцать минут каждый час - грузить можно только тогда.',
            ua: 'Поїзда на платформі немає. Поїзд стоїть тут по п\'ятнадцять хвилин щогодини - вантажити можна лише тоді.',
            en: 'No train at the platform. The consist stands here fifteen minutes every hour, and that is the only time it can be unloaded.',
            de: 'Kein Zug an der Rampe. Der Zug steht hier fünfzehn Minuten pro Stunde - nur dann kann abgeladen werden.',
            pl: 'Na rampie nie ma pociągu. Skład stoi tu piętnaście minut na godzinę i tylko wtedy można rozładowywać.',
        },
        allCratesTaken: {
            ru: 'Весь груз по контракту {{contract}} уже разобран. Везите его заказчику.',
            ua: 'Весь вантаж за контрактом {{contract}} уже розібрано. Везіть його замовнику.',
            en: 'Every crate of {{contract}} is already lifted. Run the load to the client.',
            de: 'Jede Kiste von {{contract}} ist schon aufgenommen. Bring die Ladung zum Kunden.',
            pl: 'Cały ładunek kontraktu {{contract}} jest już rozebrany. Wieźcie go zleceniodawcy.',
        },
        batchReadyToDeliver: {
            ru: 'По контракту {{contract}} изготовлено всё. Везите партию заказчику.',
            ua: 'За контрактом {{contract}} виготовлено все. Везіть партію замовнику.',
            en: 'Contract {{contract}} is fully produced. Take the batch to the client.',
            de: 'Für Vertrag {{contract}} ist alles gefertigt. Bring die Charge zum Kunden.',
            pl: 'Kontrakt {{contract}} jest w całości wykonany. Wieź partię zleceniodawcy.',
        },
    },
};
