export const contracts = {
    notify: {
        header: {
            ru: 'Контракты',
            ua: 'Контракти',
            en: 'Contracts',
            de: 'Vertraege',
            pl: 'Kontrakty',
        },
    },
    usage: {
        ru: 'Использование: /contract <list|take|take_family|status|abandon> [id]',
        ua: 'Використання: /contract <list|take|take_family|status|abandon> [id]',
        en: 'Usage: /contract <list|take|take_family|status|abandon> [id]',
        de: 'Verwendung: /contract <list|take|take_family|status|abandon> [id]',
        pl: 'Uzycie: /contract <list|take|take_family|status|abandon> [id]',
    },
    tracks: {
        legal: {
            ru: 'Легальный',
            ua: 'Легальний',
            en: 'Legal',
            de: 'Legal',
            pl: 'Legalny',
        },
        neutral: {
            ru: 'Нейтральный',
            ua: 'Нейтральний',
            en: 'Neutral',
            de: 'Neutral',
            pl: 'Neutralny',
        },
        crime: {
            ru: 'Криминальный',
            ua: 'Кримінальний',
            en: 'Crime',
            de: 'Kriminell',
            pl: 'Kryminalny',
        },
    },
    directions: {
        legal_elite: {
            ru: 'Легальный (elite)',
            ua: 'Легальний (elite)',
            en: 'Legal (elite)',
            de: 'Legal (elite)',
            pl: 'Legalny (elite)',
        },
        legal: {
            ru: 'Легальный',
            ua: 'Легальний',
            en: 'Legal',
            de: 'Legal',
            pl: 'Legalny',
        },
        neutral: {
            ru: 'Нейтральный',
            ua: 'Нейтральний',
            en: 'Neutral',
            de: 'Neutral',
            pl: 'Neutralny',
        },
        crime: {
            ru: 'Криминальный',
            ua: 'Кримінальний',
            en: 'Crime',
            de: 'Kriminell',
            pl: 'Kryminalny',
        },
        crime_hardcore: {
            ru: 'Криминальный (hardcore)',
            ua: 'Кримінальний (hardcore)',
            en: 'Crime (hardcore)',
            de: 'Kriminell (hardcore)',
            pl: 'Kryminalny (hardcore)',
        },
    },
    list: {
        header: {
            ru: 'Доступные контракты (направление орги: {{direction}}):',
            ua: 'Доступні контракти (напрям орги: {{direction}}):',
            en: 'Available contracts (organization direction: {{direction}}):',
            de: 'Verfuegbare Vertraege (Org-Richtung: {{direction}}):',
            pl: 'Dostepne kontrakty (kierunek org: {{direction}}):',
        },
        footer: {
            ru: 'Возьмите: /contract take <id> или /contract take_family <id>',
            ua: 'Візьміть: /contract take <id> або /contract take_family <id>',
            en: 'Take: /contract take <id> or /contract take_family <id>',
            de: 'Annehmen: /contract take <id> oder /contract take_family <id>',
            pl: 'Wez: /contract take <id> lub /contract take_family <id>',
        },
        entry: {
            ru: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            ua: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            en: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            de: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
            pl: '!{#7ad07a}[{{id}}] {{name}} - {{track}}{{personalLine}}{{familyLine}}',
        },
        entryLocked: {
            ru: '!{#888888}[{{id}}] {{name}} - {{track}} (заблокирован направлением)',
            ua: '!{#888888}[{{id}}] {{name}} - {{track}} (заблокований напрямом)',
            en: '!{#888888}[{{id}}] {{name}} - {{track}} (locked by direction)',
            de: '!{#888888}[{{id}}] {{name}} - {{track}} (durch Richtung gesperrt)',
            pl: '!{#888888}[{{id}}] {{name}} - {{track}} (zablokowany kierunkiem)',
        },
        personalRewardLine: {
            ru: ' | Личный: ${{money}}, EXP {{exp}}, REP {{rep}}, шагов {{goal}}',
            ua: ' | Особистий: ${{money}}, EXP {{exp}}, REP {{rep}}, кроків {{goal}}',
            en: ' | Personal: ${{money}}, EXP {{exp}}, REP {{rep}}, steps {{goal}}',
            de: ' | Personal: ${{money}}, EXP {{exp}}, REP {{rep}}, Schritte {{goal}}',
            pl: ' | Osobisty: ${{money}}, EXP {{exp}}, REP {{rep}}, kroki {{goal}}',
        },
        familyRewardLine: {
            ru: ' | Семейный: ${{money}}, EXP {{exp}}, REP {{rep}}, шагов {{goal}}',
            ua: ' | Сімейний: ${{money}}, EXP {{exp}}, REP {{rep}}, кроків {{goal}}',
            en: ' | Family: ${{money}}, EXP {{exp}}, REP {{rep}}, steps {{goal}}',
            de: ' | Familie: ${{money}}, EXP {{exp}}, REP {{rep}}, Schritte {{goal}}',
            pl: ' | Rodzinny: ${{money}}, EXP {{exp}}, REP {{rep}}, kroki {{goal}}',
        },
        delivery: {
            name: {
                ru: 'Рассыльный',
                ua: 'Розсильний',
                en: 'Courier',
                de: 'Bote',
                pl: 'Goniec',
            },
            description: {
                ru: 'Привет, я Мариана. Координирую развоз посылок по городу - возьмёшь маршрут на сегодня? Платим за каждую доставку, главное не задерживайся у клиентов.',
                ua: 'Привіт, я Маріана. Координую розвезення посилок містом - візьмеш маршрут на сьогодні? Платимо за кожну доставку, головне не затримуйся у клієнтів.',
                en: 'Hi, I\'m Mariana. I run parcel routes across the city - want to take a shift today? We pay per drop, just don\'t linger at the doors.',
                de: 'Hi, ich bin Mariana. Ich koordiniere die Paketrouten in der Stadt - uebernimmst du heute eine Tour? Wir zahlen pro Zustellung, halt dich an den Tueren nicht auf.',
                pl: 'Czesc, jestem Mariana. Koordynuje rozwozke paczek po miescie - bierzesz dzis trase? Placimy od dostawy, tylko nie marudz u klientow.',
            },
            objective: {
                ru: 'Развезти посылки клиентам',
                ua: 'Розвезти посилки клієнтам',
                en: 'Deliver parcels to clients',
                de: 'Pakete an Kunden ausliefern',
                pl: 'Rozwiezc paczki klientom',
            },
        },
        quarry: {
            name: {
                ru: 'Рудник',
                ua: 'Рудник',
                en: 'Quarry',
                de: 'Steinbruch',
                pl: 'Kamieniolom',
            },
            description: {
                ru: 'Я Биг Джо, держу карьер. Рук вечно не хватает - садись за думпер или бульдозер, кидай руду на склад. Плачу за объём, не за разговоры.',
                ua: 'Я Біг Джо, тримаю кар\'єр. Рук вічно бракує - сідай за думпер чи бульдозер, кидай руду на склад. Плачу за обсяг, не за балачки.',
                en: 'Name\'s Big Joe, I run this quarry. Always short on hands - jump in a dumper or bulldozer, haul ore to the yard. I pay by the load, not by the chatter.',
                de: 'Bin Big Joe, ich leite den Steinbruch. Es fehlen immer Leute - schnapp dir den Kipper oder Bulldozer und schaff das Erz zum Lager. Ich zahl pro Ladung, nicht fuers Reden.',
                pl: 'Nazywam sie Big Joe, prowadze ten kamieniolom. Zawsze brak rak - bierz wywrotke albo buldozer i wioz rude na sklad. Place od kursu, nie od gadania.',
            },
            objective: {
                ru: 'Сделать рейсы на карьере',
                ua: 'Зробити рейси у кар\'єрі',
                en: 'Complete quarry hauls',
                de: 'Steinbruch-Fahrten erledigen',
                pl: 'Wykonac kursy w kamieniolomie',
            },
        },
        carjacker: {
            name: {
                ru: 'Угонки',
                ua: 'Викрадення',
                en: 'Carjacking',
                de: 'Autodiebstahl',
                pl: 'Kradziez aut',
            },
            description: {
                ru: 'Шэдоу. Нужны конкретные модели машин. Пригони их по списку, оплачу каждую.',
                ua: 'Шедоу. Потрібні конкретні моделі машин. Пригоню їх за списком, оплачу кожну.',
                en: 'Shadow. I need specific car models. Bring them by the list, I pay per car.',
                de: 'Shadow. Brauch bestimmte Modelle. Bring sie nach Liste, ich zahl pro Wagen.',
                pl: 'Shadow. Potrzebne konkretne modele aut. Przygoń je po liście, plac za kazde.',
            },
            objective: {
                ru: 'Угнать машины по списку',
                ua: 'Викрасти машини за списком',
                en: 'Bring cars from the list',
                de: 'Autos von der Liste bringen',
                pl: 'Przygnac auta z listy',
            },
        },
        greenCourier: {
            name: {
                ru: 'Кривая дорожка (Green)',
                ua: 'Крива доріжка (Green)',
                en: 'Crooked Path (Green)',
                de: 'Krummer Weg (Green)',
                pl: 'Kreta sciezka (Green)',
            },
            description: {
                ru: 'Эй, я Маркиз. Раскидай закладки Green по точкам - бери груз, маршрут держи в голове, бумажек после себя не оставляй. На районе тебя прикроют.',
                ua: 'Гей, я Маркіз. Розкидай закладки Green по точках - бери вантаж, маршрут тримай у голові, паперів по собі не лишай. На районі тебе прикриють.',
                en: 'Yo, Marquis here. Drop the Green stashes along the route - take the pack, keep the spots in your head, no paper trail. The block\'s got your back.',
                de: 'Yo, hier Marquis. Verteil die Green-Verstecke auf der Strecke - nimm das Paeckchen, Strecke im Kopf, kein Papier hinterlassen. Das Viertel deckt dir den Ruecken.',
                pl: 'Hej, tu Marquis. Rozrzuc zakladki Green po trasie - bierz towar, trase trzymaj w glowie, bez papierow. Dzielnia cie pilnuje.',
            },
            objective: {
                ru: 'Раскидать закладки Green',
                ua: 'Розкидати закладки Green',
                en: 'Plant Green stashes on the route',
                de: 'Green-Verstecke verteilen',
                pl: 'Rozrzucic zakladki Green',
            },
        },
        paperwork: {
            name: {
                ru: 'Бумажная волокита',
                ua: 'Паперова тяганина',
                en: 'Paperwork',
                de: 'Papierkram',
                pl: 'Biurokracja',
            },
            description: {
                ru: 'Каплан, мэрия. Соберите по адресам бумаги, заверьте печатями и доставьте мне лично. Никаких помарок, никаких опозданий - я не люблю переделывать чужую работу.',
                ua: 'Каплан, мерія. Зберіть за адресами папери, завірте печатками і доставте мені особисто. Жодних помарок, жодних запізнень - я не люблю переробляти чужу роботу.',
                en: 'Kaplan, city hall. Collect the documents at the listed addresses, stamp them, deliver them to me personally. No smudges, no delays - I don\'t enjoy redoing other people\'s work.',
                de: 'Kaplan, Rathaus. Holen Sie die Unterlagen an den Adressen ab, lassen Sie sie abstempeln und bringen Sie sie mir persoenlich. Keine Flecken, keine Verspaetungen - ich arbeite nicht gern fremde Schlampereien nach.',
                pl: 'Kaplan, ratusz. Zbierzcie dokumenty pod adresami, ostemplujcie i dostarczcie mi osobiscie. Bez plam, bez opoznien - nie lubie poprawiac cudzej roboty.',
            },
            objective: {
                ru: 'Доставить пакеты документов',
                ua: 'Доставити пакети документів',
                en: 'Deliver document packages',
                de: 'Dokumentenpakete ausliefern',
                pl: 'Dostarczyc pakiety dokumentow',
            },
        },
        notary: {
            name: {
                ru: 'Нотариус',
                ua: 'Нотаріус',
                en: 'Notary',
                de: 'Notar',
                pl: 'Notariusz',
            },
            description: {
                ru: 'Патриция Салливан, нотариус. Подвезите доверенности, проведите встречу строго по протоколу - и оригиналы получите лично у меня под подпись. Других вариантов закон не предусматривает.',
                ua: 'Патриція Салліван, нотаріус. Підвезіть довіреності, проведіть зустріч суворо за протоколом - і оригінали отримаєте особисто у мене під підпис. Інших варіантів закон не передбачає.',
                en: 'Patricia Sullivan, notary public. Bring the powers of attorney, run the meeting strictly by the book, and you\'ll sign for the originals at my desk. The law allows no shortcuts.',
                de: 'Patricia Sullivan, Notarin. Bringen Sie die Vollmachten, fuehren Sie das Gespraech strikt nach Vorschrift - die Originale erhalten Sie persoenlich gegen Unterschrift. Abkuerzungen sieht das Gesetz nicht vor.',
                pl: 'Patricia Sullivan, notariusz. Przywiezcie pelnomocnictwa, przeprowadzcie spotkanie sciscle wedlug procedury - oryginaly odbierzecie u mnie osobiscie za podpisem. Prawo nie przewiduje skrotow.',
            },
            objective: {
                ru: 'Сдать нотариальные дела',
                ua: 'Здати нотаріальні справи',
                en: 'Submit notarial cases',
                de: 'Notarakten abgeben',
                pl: 'Oddac sprawy notarialne',
            },
        },
        dock7: {
            name: {
                ru: 'Док №7',
                ua: 'Док №7',
                en: 'Dock 7',
                de: 'Dock 7',
                pl: 'Dok 7',
            },
            description: {
                ru: 'Серджио, седьмой док, и у меня нет лишнего времени. Расставь бригаду, грузите контейнеры в трак - чем быстрее закончим, тем спокойнее всем спится в этом порту. Capisci?',
                ua: 'Серджіо, сьомий док, і зайвого часу у мене нема. Розстав бригаду, вантажте контейнери у трак - чим швидше закінчимо, тим спокійніше всім спиться в цьому порту. Capisci?',
                en: 'Sergio, dock seven, and I don\'t have time to waste. Set your crew, load those containers onto the truck - faster we wrap up, easier the whole port sleeps. Capisci?',
                de: 'Sergio, Dock sieben, und ich hab keine Zeit zu verlieren. Stell die Crew auf, ladet die Container auf den LKW - je schneller wir fertig sind, desto besser schlaeft der ganze Hafen. Capisci?',
                pl: 'Sergio, dok siodmy, i nie mam czasu do stracenia. Ustaw ekipe, ladujcie kontenery na ciezarowke - im szybciej skonczymy, tym spokojniej spi caly port. Capisci?',
            },
            objective: {
                ru: 'Загрузить контейнеры в трак',
                ua: 'Завантажити контейнери у трак',
                en: 'Load containers onto the truck',
                de: 'Container auf den LKW laden',
                pl: 'Zaladowac kontenery na ciezarowke',
            },
        },
        industrial: {
            name: {
                ru: 'Промышленная погрузка',
                ua: 'Промислове завантаження',
                en: 'Industrial Haul',
                de: 'Industrieladung',
                pl: 'Zaladunek przemyslowy',
            },
            description: {
                ru: 'Серджио на связи. Один садится за кран, второй за руль - промышленный кабель должен лечь по маршруту до конца смены. Я предупреждал заказчика, что управлюсь, не подведи меня.',
                ua: 'Серджіо на зв\'язку. Один сідає за кран, другий за кермо - промисловий кабель має лягти за маршрутом до кінця зміни. Я обіцяв замовнику, що впораюся, не підведи мене.',
                en: 'Sergio on the line. One of you takes the crane, the other drives - that industrial cable better be down by end of shift. I gave the buyer my word, don\'t make me a liar.',
                de: 'Sergio am Apparat. Einer ans Kran, einer ans Steuer - das Industriekabel liegt bis Schichtende auf der Strecke. Ich hab dem Kaeufer mein Wort gegeben, mach mich nicht zum Luegner.',
                pl: 'Sergio na linii. Jeden na dzwig, drugi za kolko - kabel przemyslowy ma byc polozony do konca zmiany. Dalem klientowi slowo, nie zrob ze mnie klamcy.',
            },
            objective: {
                ru: 'Перевезти партии кабеля',
                ua: 'Перевезти партії кабелю',
                en: 'Haul industrial cable runs',
                de: 'Industriekabel-Ladungen fahren',
                pl: 'Przewiezc partie kabla',
            },
        },
        seafood: {
            name: {
                ru: 'Дары моря',
                ua: 'Дари моря',
                en: 'Bounty of the Sea',
                de: 'Gaben des Meeres',
                pl: 'Dary morza',
            },
            description: {
                ru: 'Хэнк «Энкор» на приёмке. Привезёшь мне {{rolledGoal}} партий {{subjectName}} - взвешу, рассчитаю, лишних вопросов о ваших сетях задавать не буду. Море щедрое, если не лениться.',
                ua: 'Хенк «Енкор» на приймачі. Привезеш мені {{rolledGoal}} партій {{subjectName}} - зважу, розрахую, зайвих питань про ваші сітки не питатиму. Море щедре, якщо не лінуватися.',
                en: 'Hank "Anchor" at the depot. Bring me {{rolledGoal}} hauls of {{subjectName}} - I\'ll weigh, I\'ll pay, and I won\'t ask about your nets. The sea\'s generous if you don\'t laze about.',
                de: 'Hank "Anchor" an der Annahme. Bring mir {{rolledGoal}} Faenge {{subjectName}} - ich wieg, ich zahl, und ich frag nicht nach euren Netzen. Die See ist grosszuegig, wenn man nicht faulenzt.',
                pl: 'Hank "Anchor" w skupie. Przywiez mi {{rolledGoal}} polowow {{subjectName}} - zwaze, rozlicze, o waszych sieciach nie zapytam. Morze jest hojne, jak nie lenisz sie.',
            },
            objective: {
                ru: 'Сдать партии {{subjectName}}',
                ua: 'Здати партії {{subjectName}}',
                en: 'Hand in hauls of {{subjectName}}',
                de: 'Faenge {{subjectName}} abgeben',
                pl: 'Oddac polowy {{subjectName}}',
            },
        },
        streetNet: {
            name: {
                ru: 'Уличная сеть',
                ua: 'Вулична мережа',
                en: 'Street Net',
                de: 'Strassen-Netzwerk',
                pl: 'Uliczna siec',
            },
            description: {
                ru: 'Маркиз. Собирай уличных дилеров по районам и вези их в лабу. Платим за каждого.',
                ua: 'Маркіз. Збирай вуличних дилерів по районах і вези їх до лабораторії. Платимо за кожного.',
                en: 'Marquis. Pick up street dealers across the boroughs and bring them to the lab. We pay per dealer.',
                de: 'Marquis. Sammel Strassendealer aus den Bezirken ein und bring sie ins Labor. Zahlung pro Dealer.',
                pl: 'Marquis. Zbieraj ulicznych dilerow z dzielnic i wiezisz ich do laboratorium. Placimy za kazdego.',
            },
            objective: {
                ru: 'Привезти дилеров в лабу',
                ua: 'Привезти дилерів у лабу',
                en: 'Bring dealers to the lab',
                de: 'Dealer ins Labor bringen',
                pl: 'Przywiezc dilerow do laboratorium',
            },
        },
        airDrop: {
            name: {
                ru: 'Воздушный груз',
                ua: 'Повітряний вантаж',
                en: 'Air Drop',
                de: 'Luftabwurf',
                pl: 'Zrzut z powietrza',
            },
            description: {
                ru: 'Рипер. Аирдроп упадёт в указанной точке. Забрать груз и привезти ко мне. Оплата за груз.',
                ua: 'Ріпер. Аірдроп упаде у вказаній точці. Забрати вантаж і привезти до мене. Оплата за вантаж.',
                en: 'Reaper. Airdrop lands at the marked spot. Pick it up and bring it to me. Payment per drop.',
                de: 'Reaper. Airdrop landet am markierten Punkt. Holen und zu mir bringen. Zahlung pro Drop.',
                pl: 'Reaper. Zrzut spadnie w oznaczonym punkcie. Zabierz lup i przywiez do mnie. Zaplata za lup.',
            },
            objective: {
                ru: 'Забрать груз с аирдропа',
                ua: 'Забрати вантаж з аірдропу',
                en: 'Pick up the air-drop cargo',
                de: 'Air-Drop-Ladung abholen',
                pl: 'Odebrac zrzut z powietrza',
            },
        },
        foreignFactory: {
            name: {
                ru: 'Чужая фабрика',
                ua: 'Чужа фабрика',
                en: 'Foreign Factory',
                de: 'Fremde Fabrik',
                pl: 'Cudza fabryka',
            },
            description: {
                ru: 'Рипер. Цель - чужой цех. Заберите оттуда продукцию и привезите ко мне на склад. Платим за партию.',
                ua: 'Ріпер. Ціль - чужий цех. Заберіть звідти продукцію і привезіть до мене на склад. Платимо за партію.',
                en: 'Reaper. Target: rival workshop. Grab the product and bring it to my warehouse. Payment per batch.',
                de: 'Reaper. Ziel: fremdes Werk. Hol die Ware und bring sie zu meinem Lager. Zahlung pro Charge.',
                pl: 'Reaper. Cel: obcy zaklad. Zabierz towar i przywiez do mojego magazynu. Zaplata za partie.',
            },
            objective: {
                ru: 'Вывезти партии с чужого цеха',
                ua: 'Вивезти партії з чужого цеху',
                en: 'Bring batches from the rival workshop',
                de: 'Chargen aus fremdem Werk bringen',
                pl: 'Przywiezc partie z obcego zakladu',
            },
        },
        intercept: {
            name: {
                ru: 'Перехват',
                ua: 'Перехоплення',
                en: 'Intercept',
                de: 'Abfangen',
                pl: 'Przechwycenie',
            },
            description: {
                ru: 'Рипер. Цель - чужая матовозка на ходу. Догнать, вскрыть багажник на дороге, груз перегрузить себе и уйти раньше, чем подъедет их прикрытие. Следов после себя не оставлять.',
                ua: 'Ріпер. Ціль - чужа матовозка на ходу. Наздогнати, зламати багажник на дорозі, вантаж перевантажити до себе і піти раніше, ніж під\'їде їхнє прикриття. Слідів по собі не лишати.',
                en: 'Reaper. Target: rival cargo van in motion. Run it down, crack the trunk on the move, transfer the haul to your own van and break off before their backup rolls in. Leave no trace.',
                de: 'Reaper. Ziel: fremder Cargo-Van in Bewegung. Einholen, Kofferraum auf der Strecke aufbrechen, Ladung in euren Van umladen und weg, bevor deren Backup anrueckt. Keine Spuren hinterlassen.',
                pl: 'Reaper. Cel: obcy van z towarem w trasie. Dogonic, otworzyc bagaznik w ruchu, lup przeladowac do siebie i zerwac sie zanim podjedzie ich obstawa. Bez sladow.',
            },
            objective: {
                ru: 'Перехватить чужие матовозки',
                ua: 'Перехопити чужі матовозки',
                en: 'Intercept rival cargo vans',
                de: 'Fremde Cargo-Vans abfangen',
                pl: 'Przechwycic obce vany',
            },
        },
        planting: {
            name: {
                ru: 'Посевная',
                ua: 'Сівба',
                en: 'Planting',
                de: 'Aussaat',
                pl: 'Siew',
            },
            description: {
                ru: 'Маркиз. Бери семена в лабе, посади на поле, дождись урожая и привези мне. Платим за партию.',
                ua: 'Маркіз. Бери насіння в лабораторії, посади на полі, дочекайся врожаю і привези мені. Платимо за партію.',
                en: 'Marquis. Take seeds from the lab, plant them on the field, wait for the harvest and bring me the batch. Payment per batch.',
                de: 'Marquis. Hol Samen aus dem Labor, pflanze sie auf dem Feld, ernte und bring die Charge zu mir. Zahlung pro Charge.',
                pl: 'Marquis. Bierz nasiona z labki, zasiej na polu, doczekaj zniw i przywiez partie. Zaplata za partie.',
            },
            objective: {
                ru: 'Собрать урожай с поля',
                ua: 'Зібрати урожай з поля',
                en: 'Harvest the crop fields',
                de: 'Ernte vom Feld einholen',
                pl: 'Zebrac plony z pola',
            },
        },
        specialCargo: {
            name: {
                ru: 'Спецгруз',
                ua: 'Спецвантаж',
                en: 'Special Cargo',
                de: 'Spezialfracht',
                pl: 'Ladunek specjalny',
            },
            description: {
                ru: 'Рипер. Возите спецгрузы через город по контрольным точкам. Платим за каждую партию.',
                ua: 'Ріпер. Возите спецвантажі містом за контрольними точками. Платимо за кожну партію.',
                en: 'Reaper. Move special cargo across the city through checkpoints. Payment per batch.',
                de: 'Reaper. Spezialfracht ueber Checkpoints durch die Stadt fahren. Zahlung pro Charge.',
                pl: 'Reaper. Wieziesz specjalny ladunek przez miasto przez punkty kontrolne. Zaplata za partie.',
            },
            objective: {
                ru: 'Провести спецгрузы через город',
                ua: 'Провести спецвантажі містом',
                en: 'Move special cargo across the city',
                de: 'Spezialfracht durch die Stadt bringen',
                pl: 'Przewiezc specjalny ladunek przez miasto',
            },
        },
        giftCard: {
            name: {
                ru: 'Наколка',
                ua: 'Наколка',
                en: 'Card Scam',
                de: 'Kartenbetrug',
                pl: 'Przekret',
            },
            description: {
                ru: 'Шэдоу. Подгонят пачку поддельных подарочных карт - бегайте по магазинам, разводите кассиров, выручку привозите мне в чёрном пакете. Палиться нельзя, тревога - и весь контракт в мусор.',
                ua: 'Шедоу. Підкинуть пачку підроблених подарункових карт - бігайте магазинами, розводите касирок, виручку везете мені в чорному пакеті. Світитися не можна, тривога - і весь контракт у смітник.',
                en: 'Shadow. You\'ll get a stack of fake gift cards - hit the stores, scam the clerks, bring me the take in a black bag. Don\'t get burned - one alarm and the whole contract\'s trash.',
                de: 'Shadow. Ihr kriegt einen Stapel gefaelschte Gutscheinkarten - ab in die Laeden, Kassierer linken, Beute im schwarzen Beutel zu mir. Auffliegen ist nicht - ein Alarm und der ganze Vertrag ist Muell.',
                pl: 'Shadow. Dostaniecie paczke podrobionych kart podarunkowych - biegacie po sklepach, robicie kasjerow w trabe, kase wieziecie do mnie w czarnym worku. Nie sypac sie - jeden alarm i caly kontrakt do kosza.',
            },
            objective: {
                ru: 'Реализовать поддельные карты',
                ua: 'Реалізувати підроблені карти',
                en: 'Cash out the fake gift cards',
                de: 'Gefaelschte Gutscheinkarten verkaufen',
                pl: 'Wprowadzic podrobione karty',
            },
        },
        burglar: {
            name: {
                ru: 'Домушник',
                ua: 'Домушник',
                en: 'Burglar',
                de: 'Einbrecher',
                pl: 'Wlamywacz',
            },
            description: {
                ru: 'Шэдоу. Точка с жирным барахлом, дверь под сигнализацией - забираешь кабели у мастерской, ломаешь замок, чистишь хату и тащишь хабар ко мне. Шумишь - твой косяк, не мой.',
                ua: 'Шедоу. Точка з жирним добром, двері під сигналізацією - береш кабелі у майстерні, ламаєш замок, чистиш хату й тягнеш хабар до мене. Шумиш - твій косяк, не мій.',
                en: 'Shadow. A place packed with goods, door wired up - grab the cables from the workshop, crack the lock, clean the spot and bring the haul to me. You make noise, that\'s your screw-up, not mine.',
                de: 'Shadow. Eine Bude voller Beute, Tuer mit Alarmanlage - hol dir die Kabel aus der Werkstatt, knack das Schloss, raeum den Laden aus und bring den Haul zu mir. Wenn du Krach machst, ist das dein Bockmist, nicht meiner.',
                pl: 'Shadow. Chata pelna towaru, drzwi pod alarmem - bierzesz kable z warsztatu, lamiesz zamek, czyscisz mieszkanie i ciagniesz lup do mnie. Halasujesz - twoj problem, nie moj.',
            },
            objective: {
                ru: 'Обнести богатые хаты',
                ua: 'Обнести багаті хати',
                en: 'Crack the loaded houses',
                de: 'Reiche Buden ausraeumen',
                pl: 'Wlamac sie do bogatych chat',
            },
        },
        undercover: {
            name: {
                ru: 'Под прикрытием',
                ua: 'Під прикриттям',
                en: 'Under Cover',
                de: 'Verdeckt',
                pl: 'Pod przykryciem',
            },
            description: {
                ru: 'Рипер. Заказ деликатный - груз надо снять с точки и провезти через город так, чтобы ни одна сирена не дёрнулась. Маршрут с обходом патрулей, инструменты у мастерской. Засветился под камеру - провал.',
                ua: 'Ріпер. Замовлення делікатне - вантаж треба зняти з точки і провезти через місто так, щоб жодна сирена не смикнулась. Маршрут з оминанням патрулів, інструменти у майстерні. Засвітився під камеру - провал.',
                en: 'Reaper. Delicate job: pick the cargo up from the spot and move it across the city without a single siren going up. Route bypasses the patrols, tools at the workshop. Caught on camera - that\'s a failure.',
                de: 'Reaper. Heikler Auftrag: Fracht am Punkt abholen und so durch die Stadt fahren, dass keine Sirene losgeht. Strecke geht an Streifen vorbei, Werkzeug in der Werkstatt. Vor die Kamera geraten - Fehlschlag.',
                pl: 'Reaper. Sprawa delikatna - towar trzeba zabrac z punktu i przewiezc przez miasto tak, zeby zadna syrena nie pisnela. Trasa omija patrole, narzedzia w warsztacie. Wpadasz w kamere - kontrakt nieudany.',
            },
            objective: {
                ru: 'Провезти грузы скрытно',
                ua: 'Провезти вантажі приховано',
                en: 'Move cargo without being spotted',
                de: 'Ladung unentdeckt transportieren',
                pl: 'Przewiezc lup bez wpadki',
            },
        },
        stashes: {
            name: {
                ru: 'Закладки',
                ua: 'Закладки',
                en: 'Stashes',
                de: 'Verstecke',
                pl: 'Zakladki',
            },
            description: {
                ru: 'Маркиз. Возьми пакеты из лабы и разложи по моим точкам в городе. Платим за каждую закладку.',
                ua: 'Маркіз. Бери пакети з лабораторії і розкладай по моїх точках у місті. Платимо за кожну закладку.',
                en: 'Marquis. Take the packs from the lab and plant them at my spots around town. Payment per stash.',
                de: 'Marquis. Hol die Pakete aus dem Labor und leg sie an meinen Punkten in der Stadt ab. Zahlung pro Versteck.',
                pl: 'Marquis. Bierz paczki z labki i rozkladaj po moich punktach w miescie. Zaplata za zakladke.',
            },
            objective: {
                ru: 'Разложить закладки по точкам',
                ua: 'Розкласти закладки по точках',
                en: 'Plant stashes around the city',
                de: 'Verstecke in der Stadt platzieren',
                pl: 'Rozlozyc zakladki w punktach',
            },
        },
        atelier: {
            name: {
                ru: 'Ателье',
                ua: 'Ательє',
                en: 'Atelier',
                de: 'Atelier',
                pl: 'Atelier',
            },
            description: {
                ru: 'Хозяйка ателье. Партия одежды горит по срокам - встань за швейный станок и отработай смену. Чем больше партий пошьёшь, тем толще конверт уйдёт в кассу орги.',
                ua: 'Господиня ательє. Партія одягу горить по строках - стань за швейний верстат і відпрацюй зміну. Чим більше партій пошиєш, тим товщий конверт піде в касу орги.',
                en: 'The atelier owner. A clothing batch is burning through its deadline - take the sewing station and put in a shift. The more batches you finish, the fatter the envelope going to the org treasury.',
                de: 'Atelier-Chefin. Eine Kleidungscharge laeuft die Frist davon - ans Naehgeraet und Schicht schieben. Je mehr Chargen du fertig kriegst, desto dicker der Umschlag fuer die Org-Kasse.',
                pl: 'Wlascicielka atelier. Partii ubran konczy sie czas - stan przy maszynie krawieckiej i odrob zmiane. Im wiecej partii ukoncz, tym grubsza koperta wyladuje w kasie orgi.',
            },
            objective: {
                ru: 'Сшить партии одежды на фабрике',
                ua: 'Пошити партії одягу на фабриці',
                en: 'Sew clothing batches at the factory',
                de: 'Kleidungschargen in der Fabrik naehen',
                pl: 'Uszyc partie ubran w fabryce',
            },
        },
    },
    blips: {
        meetNpc: {
            ru: 'Заказчик',
            ua: 'Замовник',
            en: 'Client',
            de: 'Auftraggeber',
            pl: 'Zleceniodawca',
        },
        loading: {
            ru: 'Загрузка',
            ua: 'Завантаження',
            en: 'Loading',
            de: 'Beladung',
            pl: 'Zaladunek',
        },
        unloading: {
            ru: 'Разгрузка',
            ua: 'Розвантаження',
            en: 'Unloading',
            de: 'Entladung',
            pl: 'Rozladunek',
        },
        dropoff: {
            ru: 'Сдача',
            ua: 'Здача',
            en: 'Drop-off',
            de: 'Abgabe',
            pl: 'Oddanie',
        },
        pickup: {
            ru: 'Забор груза',
            ua: 'Забір вантажу',
            en: 'Pickup',
            de: 'Abholung',
            pl: 'Odbior',
        },
        fishingSpot: {
            ru: 'Точка ловли',
            ua: 'Точка лову',
            en: 'Fishing spot',
            de: 'Angelplatz',
            pl: 'Lowisko',
        },
        station: {
            ru: 'Рабочая точка',
            ua: 'Робоча точка',
            en: 'Workstation',
            de: 'Arbeitsplatz',
            pl: 'Stanowisko',
        },
        atelierStation: {
            ru: 'Швейный станок',
            ua: 'Швейний верстат',
            en: 'Sewing station',
            de: 'Naehstation',
            pl: 'Stanowisko krawieckie',
        },
    },
    subjects: {
        fish: {
            tilapia: {
                ru: 'Тилапии',
                ua: 'Тилапії',
                en: 'Tilapia',
                de: 'Tilapia',
                pl: 'Tilapii',
            },
            perch: {
                ru: 'Окуня',
                ua: 'Окуня',
                en: 'Perch',
                de: 'Barsch',
                pl: 'Okonia',
            },
            tuna: {
                ru: 'Тунца',
                ua: 'Тунця',
                en: 'Tuna',
                de: 'Thunfisch',
                pl: 'Tunczyka',
            },
            salmon: {
                ru: 'Лосося',
                ua: 'Лосося',
                en: 'Salmon',
                de: 'Lachs',
                pl: 'Lososia',
            },
            halibut: {
                ru: 'Палтуса',
                ua: 'Палтуса',
                en: 'Halibut',
                de: 'Heilbutt',
                pl: 'Halibuta',
            },
            marlin: {
                ru: 'Марлина',
                ua: 'Марліна',
                en: 'Marlin',
                de: 'Marlin',
                pl: 'Marlina',
            },
        },
    },
    success: {
        taken: {
            ru: 'Контракт {{contract}} принят. Цель: {{goal}}.',
            ua: 'Контракт {{contract}} прийнятий. Ціль: {{goal}}.',
            en: 'Contract {{contract}} taken. Goal: {{goal}}.',
            de: 'Vertrag {{contract}} angenommen. Ziel: {{goal}}.',
            pl: 'Kontrakt {{contract}} przyjety. Cel: {{goal}}.',
        },
        familyTaken: {
            ru: 'Семейный контракт {{contract}} принят на партию. Цель: {{goal}}.',
            ua: 'Сімейний контракт {{contract}} прийнятий на партію. Ціль: {{goal}}.',
            en: 'Family contract {{contract}} taken by the party. Goal: {{goal}}.',
            de: 'Familienvertrag {{contract}} fuer die Gruppe angenommen. Ziel: {{goal}}.',
            pl: 'Kontrakt rodzinny {{contract}} przyjety przez druzyne. Cel: {{goal}}.',
        },
        abandoned: {
            ru: 'Контракт {{contract}} отменён.',
            ua: 'Контракт {{contract}} скасовано.',
            en: 'Contract {{contract}} abandoned.',
            de: 'Vertrag {{contract}} abgebrochen.',
            pl: 'Kontrakt {{contract}} anulowany.',
        },
        completedPersonal: {
            ru: 'Контракт {{contract}} выполнен! Награда зачислена.',
            ua: 'Контракт {{contract}} виконано! Винагороду зараховано.',
            en: 'Contract {{contract}} completed! Reward applied.',
            de: 'Vertrag {{contract}} abgeschlossen! Belohnung gutgeschrieben.',
            pl: 'Kontrakt {{contract}} wykonany! Nagroda zaliczona.',
        },
        completedFamily: {
            ru: 'Семейный контракт {{contract}} выполнен! Казна получила награду.',
            ua: 'Сімейний контракт {{contract}} виконано! Казна отримала винагороду.',
            en: 'Family contract {{contract}} completed! Treasury received the reward.',
            de: 'Familienvertrag {{contract}} abgeschlossen! Die Kasse erhielt die Belohnung.',
            pl: 'Kontrakt rodzinny {{contract}} wykonany! Skarbiec otrzymal nagrode.',
        },
    },
    info: {
        partyRecovered: {
            ru: 'Партия восстановила состав. Контракт продолжается.',
            ua: 'Партія відновила склад. Контракт триває.',
            en: 'Party restored. Contract continues.',
            de: 'Gruppe wiederhergestellt. Vertrag laeuft weiter.',
            pl: 'Druzyna odbudowana. Kontrakt trwa.',
        },
        progress: {
            ru: 'Прогресс {{contract}}: {{progress}}/{{goal}}.',
            ua: 'Прогрес {{contract}}: {{progress}}/{{goal}}.',
            en: 'Progress on {{contract}}: {{progress}}/{{goal}}.',
            de: 'Fortschritt {{contract}}: {{progress}}/{{goal}}.',
            pl: 'Postep {{contract}}: {{progress}}/{{goal}}.',
        },
        familyProgress: {
            ru: 'Семейный прогресс {{contract}}: {{progress}}/{{goal}}.',
            ua: 'Сімейний прогрес {{contract}}: {{progress}}/{{goal}}.',
            en: 'Family progress on {{contract}}: {{progress}}/{{goal}}.',
            de: 'Familienfortschritt {{contract}}: {{progress}}/{{goal}}.',
            pl: 'Postep rodzinny {{contract}}: {{progress}}/{{goal}}.',
        },
        status: {
            ru: 'Текущий контракт: {{contract}}, прогресс {{progress}}/{{goal}}.',
            ua: 'Поточний контракт: {{contract}}, прогрес {{progress}}/{{goal}}.',
            en: 'Current contract: {{contract}}, progress {{progress}}/{{goal}}.',
            de: 'Aktueller Vertrag: {{contract}}, Fortschritt {{progress}}/{{goal}}.',
            pl: 'Aktualny kontrakt: {{contract}}, postep {{progress}}/{{goal}}.',
        },
        familyStatus: {
            ru: 'Семейный контракт: {{contract}}, прогресс {{progress}}/{{goal}}.',
            ua: 'Сімейний контракт: {{contract}}, прогрес {{progress}}/{{goal}}.',
            en: 'Family contract: {{contract}}, progress {{progress}}/{{goal}}.',
            de: 'Familienvertrag: {{contract}}, Fortschritt {{progress}}/{{goal}}.',
            pl: 'Kontrakt rodzinny: {{contract}}, postep {{progress}}/{{goal}}.',
        },
        deliverNow: {
            ru: 'Груз у вас. Везите его к точке сдачи на карте.',
            ua: 'Вантаж у вас. Везіть його до точки здачі на карті.',
            en: 'Cargo is on you. Take it to the drop-off marker on the map.',
            de: 'Du hast die Ladung. Bring sie zur Abgabestelle auf der Karte.',
            pl: 'Masz lup. Wiez go do punktu zdania na mapie.',
        },
        needPickupFirst: {
            ru: 'Сначала заберите груз с точки погрузки.',
            ua: 'Спершу заберіть вантаж з точки завантаження.',
            en: 'Pick up the cargo first.',
            de: 'Hol erst die Ladung am Beladepunkt ab.',
            pl: 'Najpierw odbierz lup z punktu zaladunku.',
        },
        alreadyCarrying: {
            ru: 'Вы уже несёте груз по этому контракту.',
            ua: 'Ви вже несете вантаж за цим контрактом.',
            en: 'You are already carrying cargo for this contract.',
            de: 'Du traegst bereits Ladung fuer diesen Vertrag.',
            pl: 'Juz niesiesz lup z tego kontraktu.',
        },
    },
    errors: {
        notInGame: {
            ru: 'Сначала войдите в игру.',
            ua: 'Спочатку увійдіть у гру.',
            en: 'You must be in-game first.',
            de: 'Du musst zuerst im Spiel sein.',
            pl: 'Najpierw wejdz do gry.',
        },
        notInOrg: {
            ru: 'Вы не состоите в организации.',
            ua: 'Ви не перебуваєте в організації.',
            en: 'You are not in an organization.',
            de: 'Du bist in keiner Organisation.',
            pl: 'Nie nalezysz do organizacji.',
        },
        unknownContract: {
            ru: 'Неизвестный контракт.',
            ua: 'Невідомий контракт.',
            en: 'Unknown contract.',
            de: 'Unbekannter Vertrag.',
            pl: 'Nieznany kontrakt.',
        },
        missingContractId: {
            ru: 'Укажите id контракта: /contract take <id>',
            ua: 'Вкажіть id контракту: /contract take <id>',
            en: 'Specify contract id: /contract take <id>',
            de: 'Vertrag-Id angeben: /contract take <id>',
            pl: 'Podaj id kontraktu: /contract take <id>',
        },
        notSupportedAsPersonal: {
            ru: 'Этот контракт можно брать только как семейный.',
            ua: 'Цей контракт можна брати тільки як сімейний.',
            en: 'This contract is family-only.',
            de: 'Dieser Vertrag ist nur fuer Familien.',
            pl: 'Ten kontrakt jest tylko rodzinny.',
        },
        notSupportedAsFamily: {
            ru: 'Этот контракт можно брать только лично.',
            ua: 'Цей контракт можна брати тільки особисто.',
            en: 'This contract is personal-only.',
            de: 'Dieser Vertrag ist nur persoenlich.',
            pl: 'Ten kontrakt jest tylko osobisty.',
        },
        noPermissionPersonal: {
            ru: 'Ваш ранг не имеет права брать личные контракты.',
            ua: 'Ваш ранг не має права брати особисті контракти.',
            en: 'Your rank cannot take personal contracts.',
            de: 'Dein Rang darf keine persoenlichen Vertraege annehmen.',
            pl: 'Twoja ranga nie moze brac osobistych kontraktow.',
        },
        noPermissionFamily: {
            ru: 'Ваш ранг не имеет права брать семейные контракты.',
            ua: 'Ваш ранг не має права брати сімейні контракти.',
            en: 'Your rank cannot take family contracts.',
            de: 'Dein Rang darf keine Familienvertraege annehmen.',
            pl: 'Twoja ranga nie moze brac kontraktow rodzinnych.',
        },
        wrongDirection: {
            ru: 'Контракт несовместим с направлением вашей организации.',
            ua: 'Контракт несумісний з напрямом вашої організації.',
            en: 'Contract incompatible with your organization direction.',
            de: 'Vertrag mit der Org-Richtung nicht vereinbar.',
            pl: 'Kontrakt niezgodny z kierunkiem organizacji.',
        },
        notUnlockedInTree: {
            ru: 'Этот контракт ещё не разблокирован в дереве улучшений.',
            ua: 'Цей контракт ще не розблоковано у дереві покращень.',
            en: 'This contract is not yet unlocked in the upgrade tree.',
            de: 'Dieser Vertrag ist im Upgrade-Baum noch nicht freigeschaltet.',
            pl: 'Ten kontrakt nie jest jeszcze odblokowany w drzewie ulepszen.',
        },
        alreadyHaveContract: {
            ru: 'У вас уже есть активный контракт.',
            ua: 'У вас вже є активний контракт.',
            en: 'You already have an active contract.',
            de: 'Du hast bereits einen aktiven Vertrag.',
            pl: 'Masz juz aktywny kontrakt.',
        },
        notInParty: {
            ru: 'Вы не в группе. Создайте партию через /createparty.',
            ua: 'Ви не в групі. Створіть партію через /createparty.',
            en: 'You are not in a party. Use /createparty.',
            de: 'Du bist in keiner Gruppe. Nutze /createparty.',
            pl: 'Nie jestes w grupie. Uzyj /createparty.',
        },
        notPartyLeader: {
            ru: 'Только лидер партии может брать семейный контракт.',
            ua: 'Тільки лідер партії може брати сімейний контракт.',
            en: 'Only the party leader can take a family contract.',
            de: 'Nur der Gruppen-Leader kann einen Familienvertrag annehmen.',
            pl: 'Tylko lider druzyny moze wziac kontrakt rodzinny.',
        },
        partyTooSmall: {
            ru: 'В партии должно быть минимум 2 человека.',
            ua: 'У партії має бути мінімум 2 особи.',
            en: 'Party must have at least 2 members.',
            de: 'Gruppe braucht mindestens 2 Mitglieder.',
            pl: 'Druzyna musi miec minimum 2 czlonkow.',
        },
        partyMixedOrgs: {
            ru: 'Все участники партии должны быть в одной организации.',
            ua: 'Усі учасники партії мають бути в одній організації.',
            en: 'All party members must be in the same organization.',
            de: 'Alle Mitglieder muessen in derselben Organisation sein.',
            pl: 'Wszyscy czlonkowie druzyny musza byc w tej samej organizacji.',
        },
        partyMemberHasContract: {
            ru: 'У одного из членов партии уже есть активный контракт.',
            ua: 'Один з членів партії вже має активний контракт.',
            en: 'A party member already has an active contract.',
            de: 'Ein Gruppenmitglied hat bereits einen aktiven Vertrag.',
            pl: 'Czlonek druzyny ma juz aktywny kontrakt.',
        },
        noActiveContract: {
            ru: 'У вас нет активного контракта.',
            ua: 'У вас немає активного контракту.',
            en: 'You have no active contract.',
            de: 'Du hast keinen aktiven Vertrag.',
            pl: 'Nie masz aktywnego kontraktu.',
        },
        cooldownActive: {
            ru: 'Контракт на кулдауне ещё {{minutes}} мин.',
            ua: 'Контракт на кулдауні ще {{minutes}} хв.',
            en: 'Contract is on cooldown for {{minutes}} more min.',
            de: 'Vertrag im Cooldown noch {{minutes}} Min.',
            pl: 'Kontrakt na cooldownie jeszcze {{minutes}} min.',
        },
        notInDailyRoster: {
            ru: 'Контракт отсутствует в сегодняшнем списке.',
            ua: 'Контракт відсутній у сьогоднішньому списку.',
            en: 'Contract is not in today\'s roster.',
            de: 'Vertrag steht heute nicht zur Verfuegung.',
            pl: 'Kontrakt nie jest w dzisiejszej liscie.',
        },
        dailyConsumed: {
            ru: 'Этот контракт уже взят сегодня - доступен после следующего обновления.',
            ua: 'Цей контракт вже взято сьогодні - доступний після наступного оновлення.',
            en: 'This contract is already taken today - available after the next reset.',
            de: 'Dieser Vertrag wurde heute schon genommen - verfuegbar nach dem naechsten Reset.',
            pl: 'Ten kontrakt jest juz wziety dzisiaj - dostepny po nastepnym resecie.',
        },
        orgHasActiveContract: {
            ru: 'У организации уже есть активный контракт.',
            ua: 'У організації вже є активний контракт.',
            en: 'Organization already has an active contract.',
            de: 'Organisation hat bereits einen aktiven Vertrag.',
            pl: 'Organizacja ma juz aktywny kontrakt.',
        },
        notEnoughOnlineMembers: {
            ru: 'Недостаточно онлайн-членов орги для активации контракта.',
            ua: 'Недостатньо онлайн-членів орги для активації контракту.',
            en: 'Not enough online org members to activate this contract.',
            de: 'Nicht genug Online-Mitglieder zum Aktivieren des Vertrags.',
            pl: 'Za malo czlonkow online, aby aktywowac kontrakt.',
        },
        onlyLeaderCanAbandonFamily: {
            ru: 'Отменить семейный контракт может только лидер или офицер.',
            ua: 'Скасувати сімейний контракт може тільки лідер або офіцер.',
            en: 'Only the leader or an officer can abandon a family contract.',
            de: 'Nur Leader oder Offizier kann einen Familienvertrag abbrechen.',
            pl: 'Tylko lider lub oficer moze anulowac kontrakt rodzinny.',
        },
        contractFailed: {
            ru: 'Контракт {{contract}} провален: {{reason}}.',
            ua: 'Контракт {{contract}} провалено: {{reason}}.',
            en: 'Contract {{contract}} failed: {{reason}}.',
            de: 'Vertrag {{contract}} fehlgeschlagen: {{reason}}.',
            pl: 'Kontrakt {{contract}} nieudany: {{reason}}.',
        },
    },
    fail: {
        reasons: {
            timeout: {
                ru: 'истёк таймер контракта',
                ua: 'час контракту вичерпано',
                en: 'contract timer expired',
                de: 'Vertragszeit abgelaufen',
                pl: 'czas kontraktu wygasl',
            },
            partyDrop: {
                ru: 'состав партии ниже минимума',
                ua: 'склад партії нижче мінімуму',
                en: 'party fell below minimum',
                de: 'Gruppe unter Mindestgroesse',
                pl: 'druzyna ponizej minimum',
            },
        },
    },
    warning: {
        partyDrop: {
            ru: 'Состав партии ниже минимума! У вас {{minutes}} мин, чтобы восстановиться, иначе провал.',
            ua: 'Склад партії нижче мінімуму! У вас {{minutes}} хв на відновлення, інакше провал.',
            en: 'Party below minimum! You have {{minutes}} min to recover or contract fails.',
            de: 'Gruppe unter Minimum! Du hast {{minutes}} Min zur Erholung, sonst Fehlschlag.',
            pl: 'Druzyna ponizej minimum! Masz {{minutes}} min na odbudowe, inaczej porazka.',
        },
        maxPerPlayerReached: {
            ru: 'По контракту {{contract}} с одного игрока принимаем максимум {{cap}} единиц. Передайте остаток партнёрам.',
            ua: 'За контрактом {{contract}} від одного гравця приймаємо максимум {{cap}} одиниць. Передайте залишок партнерам.',
            en: 'Contract {{contract}} accepts up to {{cap}} units from one player. Let your partners handle the rest.',
            de: 'Vertrag {{contract}} nimmt von einem Spieler hoechstens {{cap}} Einheiten. Den Rest sollen die Partner erledigen.',
            pl: 'Kontrakt {{contract}} przyjmuje maksymalnie {{cap}} jednostek od jednego gracza. Reszte niech wezma partnerzy.',
        },
        busy: {
            ru: 'Дождитесь окончания текущего действия.',
            ua: 'Зачекайте завершення поточної дії.',
            en: 'Wait until the current action finishes.',
            de: 'Warte, bis die aktuelle Aktion abgeschlossen ist.',
            pl: 'Poczekaj na zakonczenie obecnej akcji.',
        },
    },
};
