export const lifecycle = {
    notify: {
        header: {
            ru: 'Организация',
            ua: 'Організація',
            en: 'Organization',
            de: 'Organisation',
            pl: 'Organizacja',
        },
    },
    transfer: {
        offer: {
            ru: 'Передаёт вам лидерство в организации {{orgName}}',
            ua: 'Передає вам лідерство в організації {{orgName}}',
            en: 'Offers you leadership of organization {{orgName}}',
            de: 'Übergibt dir die Führung der Organisation {{orgName}}',
            pl: 'Przekazuje ci dowództwo organizacji {{orgName}}',
        },
        success: {
            transferred: {
                ru: 'Лидерство передано игроку {{name}}',
                ua: 'Лідерство передано гравцю {{name}}',
                en: 'Leadership transferred to {{name}}',
                de: 'Führung an {{name}} übertragen',
                pl: 'Dowództwo przekazane graczowi {{name}}',
            },
            received: {
                ru: 'Вы стали лидером организации {{orgName}}',
                ua: 'Ви стали лідером організації {{orgName}}',
                en: 'You became the leader of {{orgName}}',
                de: 'Du bist der neue Anführer von {{orgName}}',
                pl: 'Zostałeś liderem organizacji {{orgName}}',
            },
            broadcast: {
                ru: 'Новый лидер организации - {{name}}',
                ua: 'Новий лідер організації - {{name}}',
                en: 'New organization leader: {{name}}',
                de: 'Neuer Anführer der Organisation: {{name}}',
                pl: 'Nowy lider organizacji: {{name}}',
            },
        },
        errors: {
            notLeader: {
                ru: 'Только лидер может передать лидерство',
                ua: 'Тільки лідер може передати лідерство',
                en: 'Only the leader can transfer leadership',
                de: 'Nur der Anführer kann die Führung übertragen',
                pl: 'Tylko lider może przekazać dowództwo',
            },
            targetNotMember: {
                ru: 'Игрок не состоит в вашей организации',
                ua: 'Гравець не перебуває у вашій організації',
                en: 'Player is not in your organization',
                de: 'Spieler ist nicht in deiner Organisation',
                pl: 'Gracz nie należy do twojej organizacji',
            },
            targetNotInGame: {
                ru: 'Игрок ещё не загрузился в игру',
                ua: 'Гравець ще не завантажився в гру',
                en: 'Player is not yet in game',
                de: 'Spieler ist noch nicht im Spiel',
                pl: 'Gracz nie jest jeszcze w grze',
            },
            targetTooFar: {
                ru: 'Игрок слишком далеко',
                ua: 'Гравець надто далеко',
                en: 'Player is too far away',
                de: 'Spieler ist zu weit weg',
                pl: 'Gracz jest zbyt daleko',
            },
            noDeputyRank: {
                ru: 'Нет ранга для понижения. Создайте дополнительный ранг',
                ua: 'Немає рангу для пониження. Створіть додатковий ранг',
                en: 'No deputy rank available. Create one first',
                de: 'Kein Stellvertreterrang vorhanden. Erstelle zuerst einen',
                pl: 'Brak rangi do degradacji. Najpierw utwórz dodatkową',
            },
            failed: {
                ru: 'Не удалось передать лидерство',
                ua: 'Не вдалося передати лідерство',
                en: 'Failed to transfer leadership',
                de: 'Übertragung der Führung fehlgeschlagen',
                pl: 'Nie udało się przekazać dowództwa',
            },
        },
    },
    disband: {
        modal: {
            title: {
                ru: 'Роспуск организации',
                ua: 'Розпуск організації',
                en: 'Disband Organization',
                de: 'Organisation auflösen',
                pl: 'Rozwiąż organizację',
            },
            message: {
                ru: 'Распустить организацию {{orgName}}? Это действие необратимо.<br /><br />- База перейдёт вам в личное владение.<br />- Остаток казны (${{balance}}) будет зачислен на ваш банковский счёт.<br />- Машины, переданные участниками, вернутся владельцам.<br />- Машины, купленные организацией, будут удалены без компенсации.<br />- Офисы, склад и всё его содержимое будут потеряны.<br />- Территории станут свободными.<br />- Все взятые контракты будут отменены.<br /><br />Для подтверждения введите пароль от аккаунта.',
                ua: 'Розпустити організацію {{orgName}}? Ця дія незворотна.<br /><br />- База перейде вам в особисте володіння.<br />- Залишок казни (${{balance}}) буде зараховано на ваш банківський рахунок.<br />- Машини, передані учасниками, повернуться власникам.<br />- Машини, куплені організацією, буде видалено без компенсації.<br />- Офіси, склад і весь його вміст буде втрачено.<br />- Території стануть вільними.<br />- Усі взяті контракти буде скасовано.<br /><br />Для підтвердження введіть пароль від акаунта.',
                en: 'Disband organization {{orgName}}? This cannot be undone.<br /><br />- The HQ becomes your personal property.<br />- The remaining treasury (${{balance}}) is credited to your bank account.<br />- Vehicles transferred by members return to their owners.<br />- Vehicles bought by the organization are deleted without compensation.<br />- Offices, the warehouse and everything in it are lost.<br />- Territories become free.<br />- All taken contracts are cancelled.<br /><br />Enter your account password to confirm.',
                de: 'Organisation {{orgName}} auflösen? Dies kann nicht rückgängig gemacht werden.<br /><br />- Das HQ geht in deinen persönlichen Besitz über.<br />- Der Rest der Kasse (${{balance}}) wird deinem Bankkonto gutgeschrieben.<br />- Von Mitgliedern übergebene Fahrzeuge gehen an ihre Besitzer zurück.<br />- Von der Organisation gekaufte Fahrzeuge werden ohne Entschädigung gelöscht.<br />- Büros, das Lager und sein gesamter Inhalt gehen verloren.<br />- Gebiete werden frei.<br />- Alle angenommenen Aufträge werden abgebrochen.<br /><br />Gib zur Bestätigung dein Kontopasswort ein.',
                pl: 'Rozwiązać organizację {{orgName}}? Tego nie można cofnąć.<br /><br />- HQ przejdzie na twoją własność.<br />- Reszta skarbca (${{balance}}) zostanie zapisana na twoje konto bankowe.<br />- Pojazdy przekazane przez członków wrócą do właścicieli.<br />- Pojazdy kupione przez organizację zostaną usunięte bez rekompensaty.<br />- Biura, magazyn i cała jego zawartość przepadną.<br />- Terytoria staną się wolne.<br />- Wszystkie przyjęte kontrakty zostaną anulowane.<br /><br />Aby potwierdzić, wpisz hasło do konta.',
            },
            confirm: {
                ru: 'Распустить',
                ua: 'Розпустити',
                en: 'Disband',
                de: 'Auflösen',
                pl: 'Rozwiąż',
            },
            passwordPlaceholder: {
                ru: 'Пароль от аккаунта',
                ua: 'Пароль від акаунта',
                en: 'Account password',
                de: 'Kontopasswort',
                pl: 'Hasło do konta',
            },
            cancel: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
        },
        notify: {
            ru: 'Организация {{orgName}} распущена',
            ua: 'Організацію {{orgName}} розпущено',
            en: 'Organization {{orgName}} has been disbanded',
            de: 'Organisation {{orgName}} wurde aufgelöst',
            pl: 'Organizacja {{orgName}} została rozwiązana',
        },
        success: {
            disbanded: {
                ru: 'Вы распустили организацию {{orgName}}',
                ua: 'Ви розпустили організацію {{orgName}}',
                en: 'You disbanded organization {{orgName}}',
                de: 'Du hast die Organisation {{orgName}} aufgelöst',
                pl: 'Rozwiązałeś organizację {{orgName}}',
            },
            youReceivedHq: {
                ru: 'Дом #{{id}} возвращён вам в личное владение',
                ua: 'Будинок #{{id}} повернуто вам в особисте володіння',
                en: 'House #{{id}} has been returned to your personal ownership',
                de: 'Haus #{{id}} wurde dir wieder als Privateigentum übertragen',
                pl: 'Dom #{{id}} został zwrócony w twoje osobiste posiadanie',
            },
            youReceivedBalance: {
                ru: 'На ваш банковский счёт зачислено ${{amount}}',
                ua: 'На ваш банківський рахунок зараховано ${{amount}}',
                en: '${{amount}} credited to your bank account',
                de: '${{amount}} wurden deinem Bankkonto gutgeschrieben',
                pl: 'Na twoje konto bankowe wpłynęło ${{amount}}',
            },
        },
        errors: {
            notLeader: {
                ru: 'Только лидер может распустить организацию',
                ua: 'Тільки лідер може розпустити організацію',
                en: 'Only the leader can disband the organization',
                de: 'Nur der Anführer kann die Organisation auflösen',
                pl: 'Tylko lider może rozwiązać organizację',
            },
            maxHouses: {
                ru: 'У вас лимит личных домов. Освободите слот, прежде чем распускать организацию',
                ua: 'У вас ліміт особистих будинків. Звільніть слот, перш ніж розпускати організацію',
                en: 'Your personal house limit is reached. Free a slot before disbanding',
                de: 'Dein Limit für private Häuser ist erreicht. Mache zuerst einen Platz frei',
                pl: 'Osiągnąłeś limit prywatnych domów. Zwolnij slot przed rozwiązaniem',
            },
            wrongPassword: {
                ru: 'Неверный пароль',
                ua: 'Невірний пароль',
                en: 'Wrong password',
                de: 'Falsches Passwort',
                pl: 'Nieprawidłowe hasło',
            },
            failed: {
                ru: 'Не удалось распустить организацию',
                ua: 'Не вдалося розпустити організацію',
                en: 'Failed to disband the organization',
                de: 'Auflösung der Organisation fehlgeschlagen',
                pl: 'Nie udało się rozwiązać organizacji',
            },
        },
    },
};
