export const logs = {
    categories: {
        all: {
            ru: 'Все',
            ua: 'Усі',
            en: 'All',
            de: 'Alle',
            pl: 'Wszystkie',
        },
        lifecycle: {
            ru: 'Организация',
            ua: 'Організація',
            en: 'Lifecycle',
            de: 'Lebenszyklus',
            pl: 'Cykl życia',
        },
        members: {
            ru: 'Участники',
            ua: 'Учасники',
            en: 'Members',
            de: 'Mitglieder',
            pl: 'Członkowie',
        },
        ranks: {
            ru: 'Ранги',
            ua: 'Ранги',
            en: 'Ranks',
            de: 'Ränge',
            pl: 'Rangi',
        },
        bank: {
            ru: 'Казна',
            ua: 'Скарбниця',
            en: 'Treasury',
            de: 'Kasse',
            pl: 'Skarbiec',
        },
        tree: {
            ru: 'Прокачка',
            ua: 'Прокачування',
            en: 'Tree',
            de: 'Talentbaum',
            pl: 'Drzewko',
        },
        contracts: {
            ru: 'Контракты',
            ua: 'Контракти',
            en: 'Contracts',
            de: 'Verträge',
            pl: 'Kontrakty',
        },
    },
    entries: {
        lifecycle: {
            created: {
                ru: '{{actor}} основал организацию "{{name}}" [{{tag}}]',
                ua: '{{actor}} заснував організацію "{{name}}" [{{tag}}]',
                en: '{{actor}} founded organization "{{name}}" [{{tag}}]',
                de: '{{actor}} hat die Organisation "{{name}}" [{{tag}}] gegründet',
                pl: '{{actor}} założył organizację "{{name}}" [{{tag}}]',
            },
            leadershipTransferred: {
                ru: '{{actor}} передал лидерство {{target}}',
                ua: '{{actor}} передав лідерство {{target}}',
                en: '{{actor}} transferred leadership to {{target}}',
                de: '{{actor}} hat die Führung an {{target}} übertragen',
                pl: '{{actor}} przekazał przywództwo {{target}}',
            },
            disbanded: {
                ru: '{{actor}} распустил организацию (участников: {{members}}, остаток: ${{balance}})',
                ua: '{{actor}} розпустив організацію (учасників: {{members}}, залишок: ${{balance}})',
                en: '{{actor}} disbanded the organization (members: {{members}}, balance: ${{balance}})',
                de: '{{actor}} hat die Organisation aufgelöst (Mitglieder: {{members}}, Restguthaben: ${{balance}})',
                pl: '{{actor}} rozwiązał organizację (członków: {{members}}, saldo: ${{balance}})',
            },
            confiscated: {
                ru: 'HQ #{{hqId}} конфискован за долги. Компенсация лидеру: ${{refund}} + остаток ${{leftover}}',
                ua: 'HQ #{{hqId}} конфісковано за борги. Компенсація лідеру: ${{refund}} + залишок ${{leftover}}',
                en: 'HQ #{{hqId}} confiscated for debt. Leader refund: ${{refund}} + leftover ${{leftover}}',
                de: 'HQ #{{hqId}} wegen Schulden beschlagnahmt. Erstattung an Leiter: ${{refund}} + Rest ${{leftover}}',
                pl: 'HQ #{{hqId}} skonfiskowano za długi. Zwrot dla lidera: ${{refund}} + reszta ${{leftover}}',
            },
            confiscationSkippedNoHq: {
                ru: 'Конфискация пропущена: HQ не найден',
                ua: 'Конфіскацію пропущено: HQ не знайдено',
                en: 'Confiscation skipped: no HQ found',
                de: 'Beschlagnahmung übersprungen: kein HQ gefunden',
                pl: 'Konfiskata pominięta: brak HQ',
            },
        },
        members: {
            invited: {
                ru: '{{actor}} принял {{target}} в организацию (ранг: {{rank}})',
                ua: '{{actor}} прийняв {{target}} до організації (ранг: {{rank}})',
                en: '{{actor}} invited {{target}} into the organization (rank: {{rank}})',
                de: '{{actor}} hat {{target}} in die Organisation aufgenommen (Rang: {{rank}})',
                pl: '{{actor}} przyjął {{target}} do organizacji (ranga: {{rank}})',
            },
            kicked: {
                ru: '{{actor}} исключил {{target}} из организации',
                ua: '{{actor}} виключив {{target}} з організації',
                en: '{{actor}} kicked {{target}} from the organization',
                de: '{{actor}} hat {{target}} aus der Organisation entfernt',
                pl: '{{actor}} wyrzucił {{target}} z organizacji',
            },
            left: {
                ru: '{{actor}} покинул организацию',
                ua: '{{actor}} залишив організацію',
                en: '{{actor}} left the organization',
                de: '{{actor}} hat die Organisation verlassen',
                pl: '{{actor}} opuścił organizację',
            },
            rankChanged: {
                ru: '{{actor}} назначил {{target}} ранг {{rank}}',
                ua: '{{actor}} призначив {{target}} ранг {{rank}}',
                en: '{{actor}} set {{target}}\'s rank to {{rank}}',
                de: '{{actor}} hat den Rang von {{target}} auf {{rank}} gesetzt',
                pl: '{{actor}} ustawił {{target}} rangę {{rank}}',
            },
            salaryChanged: {
                ru: '{{actor}} установил зарплату {{target}}: ${{amount}}',
                ua: '{{actor}} встановив зарплату {{target}}: ${{amount}}',
                en: '{{actor}} set {{target}}\'s salary to ${{amount}}',
                de: '{{actor}} hat das Gehalt von {{target}} auf ${{amount}} festgelegt',
                pl: '{{actor}} ustawił wypłatę {{target}}: ${{amount}}',
            },
        },
        ranks: {
            created: {
                ru: '{{actor}} создал ранг "{{name}}" (уровень {{level}})',
                ua: '{{actor}} створив ранг "{{name}}" (рівень {{level}})',
                en: '{{actor}} created rank "{{name}}" (level {{level}})',
                de: '{{actor}} hat den Rang "{{name}}" erstellt (Stufe {{level}})',
                pl: '{{actor}} stworzył rangę "{{name}}" (poziom {{level}})',
            },
            renamed: {
                ru: '{{actor}} переименовал ранг "{{previousName}}" в "{{name}}"',
                ua: '{{actor}} перейменував ранг "{{previousName}}" на "{{name}}"',
                en: '{{actor}} renamed rank "{{previousName}}" to "{{name}}"',
                de: '{{actor}} hat den Rang "{{previousName}}" in "{{name}}" umbenannt',
                pl: '{{actor}} zmienił nazwę rangi "{{previousName}}" na "{{name}}"',
            },
            deleted: {
                ru: '{{actor}} удалил ранг "{{name}}"',
                ua: '{{actor}} видалив ранг "{{name}}"',
                en: '{{actor}} deleted rank "{{name}}"',
                de: '{{actor}} hat den Rang "{{name}}" gelöscht',
                pl: '{{actor}} usunął rangę "{{name}}"',
            },
            permissionsUpdated: {
                ru: '{{actor}} обновил права ранга "{{name}}"',
                ua: '{{actor}} оновив права рангу "{{name}}"',
                en: '{{actor}} updated permissions for rank "{{name}}"',
                de: '{{actor}} hat die Rechte für Rang "{{name}}" aktualisiert',
                pl: '{{actor}} zaktualizował uprawnienia rangi "{{name}}"',
            },
            reordered: {
                ru: '{{actor}} изменил порядок рангов',
                ua: '{{actor}} змінив порядок рангів',
                en: '{{actor}} reordered ranks',
                de: '{{actor}} hat die Rangreihenfolge geändert',
                pl: '{{actor}} zmienił kolejność rang',
            },
        },
        bank: {
            deposited: {
                ru: '{{actor}} внёс ${{amount}} в казну (баланс: ${{total}})',
                ua: '{{actor}} вніс ${{amount}} у скарбницю (баланс: ${{total}})',
                en: '{{actor}} deposited ${{amount}} into the treasury (balance: ${{total}})',
                de: '{{actor}} hat ${{amount}} in die Kasse eingezahlt (Stand: ${{total}})',
                pl: '{{actor}} wpłacił ${{amount}} do skarbca (saldo: ${{total}})',
            },
            withdrawn: {
                ru: '{{actor}} снял ${{amount}} с казны (баланс: ${{total}})',
                ua: '{{actor}} зняв ${{amount}} зі скарбниці (баланс: ${{total}})',
                en: '{{actor}} withdrew ${{amount}} from the treasury (balance: ${{total}})',
                de: '{{actor}} hat ${{amount}} aus der Kasse abgehoben (Stand: ${{total}})',
                pl: '{{actor}} pobrał ${{amount}} ze skarbca (saldo: ${{total}})',
            },
            paydayPaid: {
                ru: 'Выплата зарплат: ${{amount}} распределено между {{members}} участниками',
                ua: 'Виплата зарплат: ${{amount}} розподілено між {{members}} учасниками',
                en: 'Payday: ${{amount}} distributed to {{members}} members',
                de: 'Gehaltsauszahlung: ${{amount}} an {{members}} Mitglieder verteilt',
                pl: 'Wypłata: ${{amount}} rozdzielone między {{members}} członków',
            },
            paydaySkipped: {
                ru: 'Зарплаты не выплачены: фонд ${{pool}} больше баланса ${{balance}}',
                ua: 'Зарплати не виплачено: фонд ${{pool}} більший за баланс ${{balance}}',
                en: 'Payday skipped: pool ${{pool}} exceeds balance ${{balance}}',
                de: 'Gehaltsauszahlung übersprungen: Pool ${{pool}} übersteigt Kasse ${{balance}}',
                pl: 'Wypłata pominięta: pula ${{pool}} przekracza saldo ${{balance}}',
            },
            rentPaid: {
                ru: 'Аренда HQ #{{hqId}} списана: ${{amount}}',
                ua: 'Оренду HQ #{{hqId}} списано: ${{amount}}',
                en: 'HQ #{{hqId}} rent charged: ${{amount}}',
                de: 'Miete für HQ #{{hqId}} abgebucht: ${{amount}}',
                pl: 'Czynsz HQ #{{hqId}} pobrany: ${{amount}}',
            },
            debtStarted: {
                ru: 'Начался долг по аренде (${{rent}}/день). До конфискации 72 часа',
                ua: 'Розпочалася заборгованість з оренди (${{rent}}/день). До конфіскації 72 години',
                en: 'Rent debt started (${{rent}}/day). 72 hours until confiscation',
                de: 'Mietschuld eingetragen (${{rent}}/Tag). 72 Stunden bis zur Beschlagnahmung',
                pl: 'Powstał dług czynszowy (${{rent}}/dzień). 72 godziny do konfiskaty',
            },
            debtCleared: {
                ru: 'Долг по аренде погашен',
                ua: 'Заборгованість з оренди погашено',
                en: 'Rent debt cleared',
                de: 'Mietschuld beglichen',
                pl: 'Dług czynszowy spłacony',
            },
        },
        tree: {
            unlockStarted: {
                ru: '{{actor}} начал исследование "{{node}}" (завершится {{completesAt}})',
                ua: '{{actor}} розпочав дослідження "{{node}}" (завершиться {{completesAt}})',
                en: '{{actor}} started researching "{{node}}" (completes {{completesAt}})',
                de: '{{actor}} hat die Erforschung "{{node}}" gestartet (Abschluss {{completesAt}})',
                pl: '{{actor}} rozpoczął badanie "{{node}}" (koniec {{completesAt}})',
            },
            unlockCompleted: {
                ru: 'Исследование "{{node}}" завершено',
                ua: 'Дослідження "{{node}}" завершено',
                en: 'Research "{{node}}" completed',
                de: 'Erforschung "{{node}}" abgeschlossen',
                pl: 'Badanie "{{node}}" zakończone',
            },
            unlocked: {
                ru: '{{actor}} открыл "{{node}}"',
                ua: '{{actor}} відкрив "{{node}}"',
                en: '{{actor}} unlocked "{{node}}"',
                de: '{{actor}} hat "{{node}}" freigeschaltet',
                pl: '{{actor}} odblokował "{{node}}"',
            },
        },
        contracts: {
            taken: {
                ru: '{{actor}} взял контракт "{{contract}}" ({{type}})',
                ua: '{{actor}} узяв контракт "{{contract}}" ({{type}})',
                en: '{{actor}} took contract "{{contract}}" ({{type}})',
                de: '{{actor}} hat den Auftrag "{{contract}}" ({{type}}) angenommen',
                pl: '{{actor}} przyjął kontrakt "{{contract}}" ({{type}})',
            },
            completed: {
                ru: '{{actor}} завершил контракт "{{contract}}" ({{type}})',
                ua: '{{actor}} завершив контракт "{{contract}}" ({{type}})',
                en: '{{actor}} completed contract "{{contract}}" ({{type}})',
                de: '{{actor}} hat den Auftrag "{{contract}}" ({{type}}) abgeschlossen',
                pl: '{{actor}} ukończył kontrakt "{{contract}}" ({{type}})',
            },
            abandoned: {
                ru: '{{actor}} отказался от контракта "{{contract}}" ({{type}})',
                ua: '{{actor}} відмовився від контракту "{{contract}}" ({{type}})',
                en: '{{actor}} abandoned contract "{{contract}}" ({{type}})',
                de: '{{actor}} hat den Auftrag "{{contract}}" ({{type}}) abgebrochen',
                pl: '{{actor}} porzucił kontrakt "{{contract}}" ({{type}})',
            },
            failed: {
                ru: 'Контракт "{{contract}}" ({{type}}) провален: {{reason}}',
                ua: 'Контракт "{{contract}}" ({{type}}) провалено: {{reason}}',
                en: 'Contract "{{contract}}" ({{type}}) failed: {{reason}}',
                de: 'Auftrag "{{contract}}" ({{type}}) gescheitert: {{reason}}',
                pl: 'Kontrakt "{{contract}}" ({{type}}) nieudany: {{reason}}',
            },
            lostOnQuit: {
                ru: '{{actor}} вышел из игры с активным контрактом "{{contract}}"',
                ua: '{{actor}} вийшов з гри з активним контрактом "{{contract}}"',
                en: '{{actor}} quit with active contract "{{contract}}"',
                de: '{{actor}} hat das Spiel mit aktivem Auftrag "{{contract}}" verlassen',
                pl: '{{actor}} wyszedł z gry z aktywnym kontraktem "{{contract}}"',
            },
        },
    },
};
