export const menu = {
    title: {
        ru: 'Организация',
        ua: 'Організація',
        en: 'Organization',
        de: 'Organisation',
        pl: 'Organizacja',
    },
    notify: {
        header: {
            ru: 'Меню орги',
            ua: 'Меню орги',
            en: 'Org menu',
            de: 'Org-Menue',
            pl: 'Menu org',
        },
    },
    loading: {
        ru: 'Загрузка...',
        ua: 'Завантаження...',
        en: 'Loading...',
        de: 'Laedt...',
        pl: 'Ladowanie...',
    },
    tabs: {
        main: {
            ru: 'Главная',
            ua: 'Головна',
            en: 'Main',
            de: 'Haupt',
            pl: 'Glowna',
        },
        property: {
            ru: 'Имущество',
            ua: 'Майно',
            en: 'Property',
            de: 'Eigentum',
            pl: 'Wlasnosc',
        },
        upgrades: {
            ru: 'Улучшения',
            ua: 'Покращення',
            en: 'Upgrades',
            de: 'Upgrades',
            pl: 'Ulepszenia',
        },
    },
    errors: {
        noOrg: {
            ru: 'Вы не состоите в организации.',
            ua: 'Ви не перебуваєте в організації.',
            en: 'You are not in an organization.',
            de: 'Du bist in keiner Organisation.',
            pl: 'Nie nalezysz do organizacji.',
        },
        fetch: {
            ru: 'Не удалось загрузить данные.',
            ua: 'Не вдалося завантажити дані.',
            en: 'Failed to load data.',
            de: 'Daten konnten nicht geladen werden.',
            pl: 'Nie udalo sie zaladowac danych.',
        },
    },
    upgrades: {
        title: {
            ru: 'Улучшения',
            ua: 'Покращення',
            en: 'Upgrades',
            de: 'Upgrades',
            pl: 'Ulepszenia',
        },
        changeDirection: {
            ru: 'Сменить направление',
            ua: 'Змінити напрям',
            en: 'Change direction',
            de: 'Richtung wechseln',
            pl: 'Zmien kierunek',
        },
    },
    main: {
        balance: {
            ru: 'Казна',
            ua: 'Казна',
            en: 'Treasury',
            de: 'Kasse',
            pl: 'Skarbiec',
        },
        level: {
            ru: 'Уровень',
            ua: 'Рівень',
            en: 'Level',
            de: 'Stufe',
            pl: 'Poziom',
        },
        reputation: {
            ru: 'Репутация',
            ua: 'Репутація',
            en: 'Reputation',
            de: 'Reputation',
            pl: 'Reputacja',
        },
        members: {
            ru: 'Состав',
            ua: 'Склад',
            en: 'Members',
            de: 'Mitglieder',
            pl: 'Czlonkowie',
        },
        membersHint: {
            ru: 'Расширяется в дереве',
            ua: 'Розширюється у дереві',
            en: 'Expandable via tree',
            de: 'Im Baum erweiterbar',
            pl: 'Rozszerzalne w drzewie',
        },
        contracts: {
            ru: 'Контракты',
            ua: 'Контракти',
            en: 'Contracts',
            de: 'Vertraege',
            pl: 'Kontrakty',
        },
        legal: {
            ru: 'Легал',
            ua: 'Легал',
            en: 'Legal',
            de: 'Legal',
            pl: 'Legalne',
        },
        crime: {
            ru: 'Крайм',
            ua: 'Крайм',
            en: 'Crime',
            de: 'Crime',
            pl: 'Kryminalne',
        },
        hqStatus: {
            ru: 'HQ',
            ua: 'HQ',
            en: 'HQ',
            de: 'HQ',
            pl: 'HQ',
        },
        hqLinked: {
            ru: 'Привязан',
            ua: 'Прив\'язаний',
            en: 'Linked',
            de: 'Verknuepft',
            pl: 'Przypisany',
        },
        hqMissing: {
            ru: 'Не привязан',
            ua: 'Не прив\'язаний',
            en: 'Not linked',
            de: 'Nicht verknuepft',
            pl: 'Nieprzypisany',
        },
        treeUnlocked: {
            ru: 'Узлы дерева',
            ua: 'Вузли дерева',
            en: 'Tree nodes',
            de: 'Baum-Knoten',
            pl: 'Wezly drzewa',
        },
        branchLock: {
            ru: 'Блокировка ветки',
            ua: 'Блокування гілки',
            en: 'Branch lock',
            de: 'Zweigsperre',
            pl: 'Blokada galezi',
        },
        lockedToLegal: {
            ru: 'Закреплено за легалом',
            ua: 'Закріплено за легалом',
            en: 'Locked to legal',
            de: 'Auf Legal beschraenkt',
            pl: 'Przypiete do legalu',
        },
        lockedToCrime: {
            ru: 'Закреплено за краймом',
            ua: 'Закріплено за краймом',
            en: 'Locked to crime',
            de: 'Auf Crime beschraenkt',
            pl: 'Przypiete do krymu',
        },
        lockNeutral: {
            ru: 'Свободна',
            ua: 'Вільна',
            en: 'Open',
            de: 'Offen',
            pl: 'Wolna',
        },
    },
    property: {
        hq: {
            title: {
                ru: 'Семейный дом',
                ua: 'Сімейний будинок',
                en: 'Family house',
                de: 'Familienhaus',
                pl: 'Dom rodzinny',
            },
            slots: {
                ru: 'Слоты гаража',
                ua: 'Слоти гаража',
                en: 'Garage slots',
                de: 'Garagenplaetze',
                pl: 'Miejsca w garazu',
            },
            empty: {
                ru: 'Дом не привязан',
                ua: 'Будинок не прив\'язаний',
                en: 'No house linked',
                de: 'Kein Haus verknuepft',
                pl: 'Brak przypisanego domu',
            },
        },
        office: {
            title: {
                ru: 'Офис',
                ua: 'Офіс',
                en: 'Office',
                de: 'Buero',
                pl: 'Biuro',
            },
            slots: {
                ru: 'Слоты гаража',
                ua: 'Слоти гаража',
                en: 'Garage slots',
                de: 'Garagenplaetze',
                pl: 'Miejsca w garazu',
            },
            empty: {
                ru: 'Офис не приобретён',
                ua: 'Офіс не придбаний',
                en: 'No office owned',
                de: 'Kein Buero gekauft',
                pl: 'Brak biura',
            },
        },
        warehouse: {
            title: {
                ru: 'Склад',
                ua: 'Склад',
                en: 'Warehouse',
                de: 'Lager',
                pl: 'Magazyn',
            },
            units: {
                ru: 'Хранилищ',
                ua: 'Сховищ',
                en: 'Storages',
                de: 'Lager',
                pl: 'Magazynow',
            },
            itemsCount: {
                ru: 'Предметов',
                ua: 'Предметів',
                en: 'Items',
                de: 'Gegenstaende',
                pl: 'Przedmiotow',
            },
            uniqueItems: {
                ru: 'Видов',
                ua: 'Видів',
                en: 'Unique',
                de: 'Arten',
                pl: 'Rodzajow',
            },
            empty: {
                ru: 'Склад не оборудован',
                ua: 'Склад не обладнаний',
                en: 'No storages set up',
                de: 'Kein Lager vorhanden',
                pl: 'Brak magazynu',
            },
        },
        vehicles: {
            title: {
                ru: 'Транспорт',
                ua: 'Транспорт',
                en: 'Vehicles',
                de: 'Fahrzeuge',
                pl: 'Pojazdy',
            },
            empty: {
                ru: 'Нет машин',
                ua: 'Немає машин',
                en: 'No vehicles',
                de: 'Keine Fahrzeuge',
                pl: 'Brak pojazdow',
            },
        },
        vehicleStatus: {
            parked: {
                ru: 'В гараже',
                ua: 'У гаражі',
                en: 'Parked',
                de: 'Geparkt',
                pl: 'Zaparkowany',
            },
            taken: {
                ru: 'Выехал',
                ua: 'Виїхав',
                en: 'Taken out',
                de: 'Unterwegs',
                pl: 'Wyjechal',
            },
            destroyed: {
                ru: 'Разбит',
                ua: 'Розбитий',
                en: 'Destroyed',
                de: 'Zerstoert',
                pl: 'Zniszczony',
            },
            impounded: {
                ru: 'На штрафстоянке',
                ua: 'На штрафмайданчику',
                en: 'Impounded',
                de: 'Beschlagnahmt',
                pl: 'Zajety',
            },
            orphan: {
                ru: 'Без слота',
                ua: 'Без слота',
                en: 'Unbound',
                de: 'Kein Platz',
                pl: 'Bez miejsca',
            },
        },
        locations: {
            hq: {
                ru: 'HQ {id}',
                ua: 'HQ {id}',
                en: 'HQ {id}',
                de: 'HQ {id}',
                pl: 'HQ {id}',
            },
            office: {
                ru: 'Офис',
                ua: 'Офіс',
                en: 'Office',
                de: 'Buero',
                pl: 'Biuro',
            },
            unbound: {
                ru: 'Без привязки',
                ua: 'Без прив\'язки',
                en: 'Unbound',
                de: 'Ungebunden',
                pl: 'Niepowiazany',
            },
        },
        houseClass: {
            economy: {
                ru: 'Эконом',
                ua: 'Економ',
                en: 'Economy',
                de: 'Oekonom',
                pl: 'Ekonom',
            },
            middle: {
                ru: 'Средний',
                ua: 'Середній',
                en: 'Middle',
                de: 'Mittel',
                pl: 'Sredni',
            },
            premium: {
                ru: 'Премиум',
                ua: 'Преміум',
                en: 'Premium',
                de: 'Premium',
                pl: 'Premium',
            },
            elite: {
                ru: 'Элит',
                ua: 'Еліт',
                en: 'Elite',
                de: 'Elite',
                pl: 'Elita',
            },
        },
    },
};
