export const menu = {
    title: {
        ru: 'Организация',
        ua: 'Організація',
        en: 'Organization',
        de: 'Organisation',
        pl: 'Organizacja',
    },
    notify: {
        header: {
            ru: 'Меню орги',
            ua: 'Меню орги',
            en: 'Org menu',
            de: 'Org-Menue',
            pl: 'Menu org',
        },
    },
    loading: {
        ru: 'Загрузка...',
        ua: 'Завантаження...',
        en: 'Loading...',
        de: 'Laedt...',
        pl: 'Ladowanie...',
    },
    tabs: {
        main: {
            ru: 'Главная',
            ua: 'Головна',
            en: 'Main',
            de: 'Haupt',
            pl: 'Glowna',
        },
        upgrades: {
            ru: 'Улучшения',
            ua: 'Покращення',
            en: 'Upgrades',
            de: 'Upgrades',
            pl: 'Ulepszenia',
        },
    },
    errors: {
        noOrg: {
            ru: 'Вы не состоите в организации.',
            ua: 'Ви не перебуваєте в організації.',
            en: 'You are not in an organization.',
            de: 'Du bist in keiner Organisation.',
            pl: 'Nie nalezysz do organizacji.',
        },
        fetch: {
            ru: 'Не удалось загрузить данные.',
            ua: 'Не вдалося завантажити дані.',
            en: 'Failed to load data.',
            de: 'Daten konnten nicht geladen werden.',
            pl: 'Nie udalo sie zaladowac danych.',
        },
    },
    upgrades: {
        title: {
            ru: 'Улучшения',
            ua: 'Покращення',
            en: 'Upgrades',
            de: 'Upgrades',
            pl: 'Ulepszenia',
        },
        changeDirection: {
            ru: 'Сменить направление',
            ua: 'Змінити напрям',
            en: 'Change direction',
            de: 'Richtung wechseln',
            pl: 'Zmien kierunek',
        },
    },
    main: {
        balance: {
            ru: 'Казна',
            ua: 'Казна',
            en: 'Treasury',
            de: 'Kasse',
            pl: 'Skarbiec',
        },
        level: {
            ru: 'Уровень',
            ua: 'Рівень',
            en: 'Level',
            de: 'Stufe',
            pl: 'Poziom',
        },
        reputation: {
            ru: 'Репутация',
            ua: 'Репутація',
            en: 'Reputation',
            de: 'Reputation',
            pl: 'Reputacja',
        },
        members: {
            ru: 'Состав',
            ua: 'Склад',
            en: 'Members',
            de: 'Mitglieder',
            pl: 'Czlonkowie',
        },
        membersHint: {
            ru: 'Расширяется в дереве',
            ua: 'Розширюється у дереві',
            en: 'Expandable via tree',
            de: 'Im Baum erweiterbar',
            pl: 'Rozszerzalne w drzewie',
        },
        contracts: {
            ru: 'Контракты',
            ua: 'Контракти',
            en: 'Contracts',
            de: 'Vertraege',
            pl: 'Kontrakty',
        },
        legal: {
            ru: 'Легал',
            ua: 'Легал',
            en: 'Legal',
            de: 'Legal',
            pl: 'Legalne',
        },
        crime: {
            ru: 'Крайм',
            ua: 'Крайм',
            en: 'Crime',
            de: 'Crime',
            pl: 'Kryminalne',
        },
        hqStatus: {
            ru: 'HQ',
            ua: 'HQ',
            en: 'HQ',
            de: 'HQ',
            pl: 'HQ',
        },
        hqLinked: {
            ru: 'Привязан',
            ua: 'Прив\'язаний',
            en: 'Linked',
            de: 'Verknuepft',
            pl: 'Przypisany',
        },
        hqMissing: {
            ru: 'Не привязан',
            ua: 'Не прив\'язаний',
            en: 'Not linked',
            de: 'Nicht verknuepft',
            pl: 'Nieprzypisany',
        },
        treeUnlocked: {
            ru: 'Узлы дерева',
            ua: 'Вузли дерева',
            en: 'Tree nodes',
            de: 'Baum-Knoten',
            pl: 'Wezly drzewa',
        },
        branchLock: {
            ru: 'Блокировка ветки',
            ua: 'Блокування гілки',
            en: 'Branch lock',
            de: 'Zweigsperre',
            pl: 'Blokada galezi',
        },
        lockedToLegal: {
            ru: 'Закреплено за легалом',
            ua: 'Закріплено за легалом',
            en: 'Locked to legal',
            de: 'Auf Legal beschraenkt',
            pl: 'Przypiete do legalu',
        },
        lockedToCrime: {
            ru: 'Закреплено за краймом',
            ua: 'Закріплено за краймом',
            en: 'Locked to crime',
            de: 'Auf Crime beschraenkt',
            pl: 'Przypiete do krymu',
        },
        lockNeutral: {
            ru: 'Свободна',
            ua: 'Вільна',
            en: 'Open',
            de: 'Offen',
            pl: 'Wolna',
        },
    },
};
