export const menu = {
    title: {
        ru: 'Организация',
        ua: 'Організація',
        en: 'Organization',
        de: 'Organisation',
        pl: 'Organizacja',
    },
    notify: {
        header: {
            ru: 'Меню орги',
            ua: 'Меню орги',
            en: 'Org menu',
            de: 'Org-Menue',
            pl: 'Menu org',
        },
    },
    loading: {
        ru: 'Загрузка...',
        ua: 'Завантаження...',
        en: 'Loading...',
        de: 'Laedt...',
        pl: 'Ladowanie...',
    },
    tabs: {
        main: {
            ru: 'Главная',
            ua: 'Головна',
            en: 'Main',
            de: 'Haupt',
            pl: 'Glowna',
        },
        members: {
            ru: 'Состав',
            ua: 'Склад',
            en: 'Members',
            de: 'Mitglieder',
            pl: 'Czlonkowie',
        },
        ranks: {
            ru: 'Ранги',
            ua: 'Ранги',
            en: 'Ranks',
            de: 'Ränge',
            pl: 'Rangi',
        },
        upgrades: {
            ru: 'Улучшения',
            ua: 'Покращення',
            en: 'Upgrades',
            de: 'Upgrades',
            pl: 'Ulepszenia',
        },
        territories: {
            ru: 'Карта',
            ua: 'Карта',
            en: 'Map',
            de: 'Karte',
            pl: 'Mapa',
        },
        property: {
            ru: 'Имущество',
            ua: 'Майно',
            en: 'Property',
            de: 'Eigentum',
            pl: 'Wlasnosc',
        },
        contracts: {
            ru: 'Контракты',
            ua: 'Контракти',
            en: 'Contracts',
            de: 'Vertraege',
            pl: 'Kontrakty',
        },
        settings: {
            ru: 'Настройки',
            ua: 'Налаштування',
            en: 'Settings',
            de: 'Einstellungen',
            pl: 'Ustawienia',
        },
    },
    comingSoon: {
        ru: 'Раздел в разработке',
        ua: 'Розділ у розробці',
        en: 'Section in development',
        de: 'Bereich in Entwicklung',
        pl: 'Sekcja w przygotowaniu',
    },
    contracts: {
        balance: {
            ru: 'Баланс организации',
            ua: 'Баланс організації',
            en: 'Organization balance',
            de: 'Organisationsguthaben',
            pl: 'Bilans organizacji',
        },
        reputation: {
            ru: 'Репутация',
            ua: 'Репутація',
            en: 'Reputation',
            de: 'Reputation',
            pl: 'Reputacja',
        },
        completed: {
            ru: 'Завершено контрактов',
            ua: 'Завершено контрактів',
            en: 'Contracts completed',
            de: 'Vertraege abgeschlossen',
            pl: 'Ukonczone kontrakty',
        },
        searchPlaceholder: {
            ru: 'Введите значение',
            ua: 'Введіть значення',
            en: 'Enter a query',
            de: 'Wert eingeben',
            pl: 'Wpisz zapytanie',
        },
        empty: {
            ru: 'Контракты не найдены',
            ua: 'Контрактів не знайдено',
            en: 'No contracts found',
            de: 'Keine Vertraege gefunden',
            pl: 'Brak kontraktow',
        },
        dialog: {
            ru: 'Диалог',
            ua: 'Діалог',
            en: 'Dialog',
            de: 'Dialog',
            pl: 'Dialog',
        },
        objectives: {
            ru: 'Цели',
            ua: 'Цілі',
            en: 'Objectives',
            de: 'Ziele',
            pl: 'Cele',
        },
        reward: {
            ru: 'Награда',
            ua: 'Нагорода',
            en: 'Reward',
            de: 'Belohnung',
            pl: 'Nagroda',
        },
        rewardMoney: {
            ru: 'Деньги',
            ua: 'Гроші',
            en: 'Money',
            de: 'Geld',
            pl: 'Pieniadze',
        },
        rewardReputation: {
            ru: 'Репутация',
            ua: 'Репутація',
            en: 'Reputation',
            de: 'Reputation',
            pl: 'Reputacja',
        },
        rewardExperience: {
            ru: 'Опыт',
            ua: 'Досвід',
            en: 'Experience',
            de: 'Erfahrung',
            pl: 'Doswiadczenie',
        },
        activate: {
            ru: 'Активировать контракт за',
            ua: 'Активувати контракт за',
            en: 'Activate contract for',
            de: 'Vertrag aktivieren fuer',
            pl: 'Aktywuj kontrakt za',
        },
        activateBare: {
            ru: 'Активировать контракт',
            ua: 'Активувати контракт',
            en: 'Activate contract',
            de: 'Vertrag aktivieren',
            pl: 'Aktywuj kontrakt',
        },
        activeNow: {
            ru: 'Контракт уже активен',
            ua: 'Контракт вже активний',
            en: 'Contract already active',
            de: 'Vertrag bereits aktiv',
            pl: 'Kontrakt juz aktywny',
        },
        lockedHint: {
            ru: 'Недоступно для вашего направления',
            ua: 'Недоступно для вашого напряму',
            en: 'Unavailable for your direction',
            de: 'Fuer deine Richtung nicht verfuegbar',
            pl: 'Niedostepne dla twojego kierunku',
        },
        cooldownHint: {
            ru: 'Доступно через {{minutes}} мин',
            ua: 'Доступно через {{minutes}} хв',
            en: 'Available in {{minutes}} min',
            de: 'Verfuegbar in {{minutes}} Min',
            pl: 'Dostepne za {{minutes}} min',
        },
        allTracks: {
            ru: 'Все направления',
            ua: 'Усі напрями',
            en: 'All tracks',
            de: 'Alle Richtungen',
            pl: 'Wszystkie kierunki',
        },
        untilReset: {
            ru: 'До обновления',
            ua: 'До оновлення',
            en: 'Until reset',
            de: 'Bis zum Reset',
            pl: 'Do resetu',
        },
        dailyConsumed: {
            ru: 'Уже взят сегодня',
            ua: 'Вже взято сьогодні',
            en: 'Already taken today',
            de: 'Heute schon genommen',
            pl: 'Juz wziety dzisiaj',
        },
        insufficient: {
            ru: 'Недостаточно средств на балансе',
            ua: 'Недостатньо коштів на балансі',
            en: 'Insufficient balance',
            de: 'Guthaben nicht ausreichend',
            pl: 'Niewystarczajacy bilans',
        },
        selectHint: {
            ru: 'Выберите контракт слева',
            ua: 'Оберіть контракт ліворуч',
            en: 'Pick a contract from the list',
            de: 'Vertrag links auswaehlen',
            pl: 'Wybierz kontrakt z listy',
        },
        maxPerPlayerHint: {
            ru: 'Не более {{count}} единиц от одного игрока',
            ua: 'Не більше {{count}} одиниць від одного гравця',
            en: 'Up to {{count}} units accepted from one player',
            de: 'Maximal {{count}} Einheiten pro Spieler',
            pl: 'Maksymalnie {{count}} jednostek od jednego gracza',
        },
        inProgressBadge: {
            ru: 'В работе',
            ua: 'У роботі',
            en: 'In progress',
            de: 'Laeuft',
            pl: 'W toku',
        },
        consumedBadge: {
            ru: 'Взят',
            ua: 'Взято',
            en: 'Taken',
            de: 'Genommen',
            pl: 'Wziety',
        },
        tier: {
            negative: {
                ru: 'Отрицательный',
                ua: 'Негативний',
                en: 'Negative',
                de: 'Negativ',
                pl: 'Negatywny',
            },
            neutral: {
                ru: 'Нейтральный',
                ua: 'Нейтральний',
                en: 'Neutral',
                de: 'Neutral',
                pl: 'Neutralny',
            },
            positive: {
                ru: 'Положительный',
                ua: 'Позитивний',
                en: 'Positive',
                de: 'Positiv',
                pl: 'Pozytywny',
            },
            excellent: {
                ru: 'Превосходный',
                ua: 'Чудовий',
                en: 'Excellent',
                de: 'Hervorragend',
                pl: 'Doskonaly',
            },
        },
        categories: {
            all: {
                ru: 'Все категории',
                ua: 'Усі категорії',
                en: 'All categories',
                de: 'Alle Kategorien',
                pl: 'Wszystkie kategorie',
            },
            fishing: {
                ru: 'Рыболовство',
                ua: 'Рибальство',
                en: 'Fishing',
                de: 'Fischerei',
                pl: 'Rybolowstwo',
            },
            metallurgy: {
                ru: 'Металлургия',
                ua: 'Металургія',
                en: 'Metallurgy',
                de: 'Metallurgie',
                pl: 'Metalurgia',
            },
            tailor: {
                ru: 'Ателье',
                ua: 'Ательє',
                en: 'Tailor',
                de: 'Schneiderei',
                pl: 'Krawiectwo',
            },
            ship: {
                ru: 'Контрабанда',
                ua: 'Контрабанда',
                en: 'Smuggling',
                de: 'Schmuggel',
                pl: 'Przemyt',
            },
            delivery: {
                ru: 'Доставка',
                ua: 'Доставка',
                en: 'Delivery',
                de: 'Lieferung',
                pl: 'Dostawa',
            },
        },
    },
    errors: {
        noOrg: {
            ru: 'Вы не состоите в организации.',
            ua: 'Ви не перебуваєте в організації.',
            en: 'You are not in an organization.',
            de: 'Du bist in keiner Organisation.',
            pl: 'Nie nalezysz do organizacji.',
        },
        fetch: {
            ru: 'Не удалось загрузить данные.',
            ua: 'Не вдалося завантажити дані.',
            en: 'Failed to load data.',
            de: 'Daten konnten nicht geladen werden.',
            pl: 'Nie udalo sie zaladowac danych.',
        },
    },
    upgrades: {
        title: {
            ru: 'Улучшения',
            ua: 'Покращення',
            en: 'Upgrades',
            de: 'Upgrades',
            pl: 'Ulepszenia',
        },
        changeDirection: {
            ru: 'Сменить направление',
            ua: 'Змінити напрям',
            en: 'Change direction',
            de: 'Richtung wechseln',
            pl: 'Zmien kierunek',
        },
    },
    main: {
        balance: {
            ru: 'Баланс организации',
            ua: 'Баланс організації',
            en: 'Organization balance',
            de: 'Organisationsguthaben',
            pl: 'Bilans organizacji',
        },
        level: {
            ru: 'Уровень',
            ua: 'Рівень',
            en: 'Level',
            de: 'Stufe',
            pl: 'Poziom',
        },
        reputation: {
            ru: 'Репутация',
            ua: 'Репутація',
            en: 'Reputation',
            de: 'Reputation',
            pl: 'Reputacja',
        },
        members: {
            ru: 'Состав',
            ua: 'Склад',
            en: 'Members',
            de: 'Mitglieder',
            pl: 'Czlonkowie',
        },
        membersHint: {
            ru: 'Расширяется в дереве',
            ua: 'Розширюється у дереві',
            en: 'Expandable via tree',
            de: 'Im Baum erweiterbar',
            pl: 'Rozszerzalne w drzewie',
        },
        contracts: {
            ru: 'Контракты',
            ua: 'Контракти',
            en: 'Contracts',
            de: 'Vertraege',
            pl: 'Kontrakty',
        },
        legal: {
            ru: 'Легал',
            ua: 'Легал',
            en: 'Legal',
            de: 'Legal',
            pl: 'Legalne',
        },
        crime: {
            ru: 'Крайм',
            ua: 'Крайм',
            en: 'Crime',
            de: 'Crime',
            pl: 'Kryminalne',
        },
        hqStatus: {
            ru: 'HQ',
            ua: 'HQ',
            en: 'HQ',
            de: 'HQ',
            pl: 'HQ',
        },
        hqLinked: {
            ru: 'Привязан',
            ua: 'Прив\'язаний',
            en: 'Linked',
            de: 'Verknuepft',
            pl: 'Przypisany',
        },
        hqMissing: {
            ru: 'Не привязан',
            ua: 'Не прив\'язаний',
            en: 'Not linked',
            de: 'Nicht verknuepft',
            pl: 'Nieprzypisany',
        },
        treeUnlocked: {
            ru: 'Узлы дерева',
            ua: 'Вузли дерева',
            en: 'Tree nodes',
            de: 'Baum-Knoten',
            pl: 'Wezly drzewa',
        },
        branchLock: {
            ru: 'Блокировка ветки',
            ua: 'Блокування гілки',
            en: 'Branch lock',
            de: 'Zweigsperre',
            pl: 'Blokada galezi',
        },
        lockedToLegal: {
            ru: 'Закреплено за легалом',
            ua: 'Закріплено за легалом',
            en: 'Locked to legal',
            de: 'Auf Legal beschraenkt',
            pl: 'Przypiete do legalu',
        },
        lockedToCrime: {
            ru: 'Закреплено за краймом',
            ua: 'Закріплено за краймом',
            en: 'Locked to crime',
            de: 'Auf Crime beschraenkt',
            pl: 'Przypiete do krymu',
        },
        lockNeutral: {
            ru: 'Свободна',
            ua: 'Вільна',
            en: 'Open',
            de: 'Offen',
            pl: 'Wolna',
        },
        overview: {
            ru: 'Сводка',
            ua: 'Зведення',
            en: 'Overview',
            de: 'Uebersicht',
            pl: 'Podsumowanie',
        },
        treasury: {
            title: {
                ru: 'Баланс организации',
                ua: 'Баланс організації',
                en: 'Organization balance',
                de: 'Organisationsguthaben',
                pl: 'Bilans organizacji',
            },
            hint: {
                ru: 'Внесение и снятие средств',
                ua: 'Внесення і зняття коштів',
                en: 'Deposit and withdrawal',
                de: 'Einzahlung und Auszahlung',
                pl: 'Wplata i wyplata srodkow',
            },
            deposit: {
                ru: 'Внести',
                ua: 'Внести',
                en: 'Deposit',
                de: 'Einzahlen',
                pl: 'Wplac',
            },
            withdraw: {
                ru: 'Снять',
                ua: 'Зняти',
                en: 'Withdraw',
                de: 'Auszahlen',
                pl: 'Wyplac',
            },
            amountLabel: {
                ru: 'Сумма',
                ua: 'Сума',
                en: 'Amount',
                de: 'Betrag',
                pl: 'Kwota',
            },
            amountPlaceholder: {
                ru: '0',
                ua: '0',
                en: '0',
                de: '0',
                pl: '0',
            },
            commentLabel: {
                ru: 'Комментарий',
                ua: 'Коментар',
                en: 'Comment',
                de: 'Kommentar',
                pl: 'Komentarz',
            },
            commentOptional: {
                ru: '(необязательно)',
                ua: '(необов\'язково)',
                en: '(optional)',
                de: '(optional)',
                pl: '(opcjonalnie)',
            },
            commentPlaceholder: {
                ru: 'Например: на бензин для рейда',
                ua: 'Наприклад: на бензин для рейду',
                en: 'e.g. fuel for the raid',
                de: 'z.B. Sprit fuer den Einsatz',
                pl: 'np. paliwo na rajd',
            },
            confirmDeposit: {
                ru: 'Внести на баланс',
                ua: 'Внести на баланс',
                en: 'Deposit to balance',
                de: 'Auf das Guthaben einzahlen',
                pl: 'Wplac na bilans',
            },
            confirmWithdraw: {
                ru: 'Снять с баланса',
                ua: 'Зняти з балансу',
                en: 'Withdraw from balance',
                de: 'Vom Guthaben abheben',
                pl: 'Wyplac z bilansu',
            },
            noBankPerm: {
                ru: 'Нет прав на снятие',
                ua: 'Немає прав на зняття',
                en: 'No withdrawal permission',
                de: 'Keine Abhebungsberechtigung',
                pl: 'Brak uprawnien do wyplaty',
            },
            afterOperation: {
                ru: 'После операции',
                ua: 'Після операції',
                en: 'After operation',
                de: 'Nach der Aktion',
                pl: 'Po operacji',
            },
            exceeds: {
                ru: 'Сумма больше доступного баланса',
                ua: 'Сума перевищує доступний баланс',
                en: 'Amount exceeds available balance',
                de: 'Betrag uebersteigt das verfuegbare Guthaben',
                pl: 'Kwota przekracza dostepny bilans',
            },
        },
        feed: {
            title: {
                ru: 'Журнал',
                ua: 'Журнал',
                en: 'Activity',
                de: 'Verlauf',
                pl: 'Dziennik',
            },
            hint: {
                ru: 'Последние действия',
                ua: 'Останні дії',
                en: 'Recent activity',
                de: 'Letzte Aktionen',
                pl: 'Ostatnie dzialania',
            },
            empty: {
                ru: 'Пока нет записей',
                ua: 'Поки немає записів',
                en: 'No entries yet',
                de: 'Noch keine Eintraege',
                pl: 'Brak wpisow',
            },
            emptyFiltered: {
                ru: 'Ничего не найдено по фильтру',
                ua: 'Нічого не знайдено за фільтром',
                en: 'No matches for current filter',
                de: 'Keine Treffer fuer Filter',
                pl: 'Brak wynikow dla filtra',
            },
            loading: {
                ru: 'Загрузка...',
                ua: 'Завантаження...',
                en: 'Loading...',
                de: 'Laedt...',
                pl: 'Ladowanie...',
            },
            loadMore: {
                ru: 'Загрузить ещё',
                ua: 'Завантажити ще',
                en: 'Load more',
                de: 'Mehr laden',
                pl: 'Zaladuj wiecej',
            },
            searchPlaceholder: {
                ru: 'Поиск по записям',
                ua: 'Пошук за записами',
                en: 'Search entries',
                de: 'Eintraege suchen',
                pl: 'Szukaj w dzienniku',
            },
            clearSearch: {
                ru: 'Очистить',
                ua: 'Очистити',
                en: 'Clear',
                de: 'Loeschen',
                pl: 'Wyczysc',
            },
            today: {
                ru: 'Сегодня',
                ua: 'Сьогодні',
                en: 'Today',
                de: 'Heute',
                pl: 'Dzisiaj',
            },
            yesterday: {
                ru: 'Вчера',
                ua: 'Вчора',
                en: 'Yesterday',
                de: 'Gestern',
                pl: 'Wczoraj',
            },
        },
    },
    property: {
        hq: {
            title: {
                ru: 'Семейный дом',
                ua: 'Сімейний будинок',
                en: 'Family house',
                de: 'Familienhaus',
                pl: 'Dom rodzinny',
            },
            slots: {
                ru: 'Слоты гаража',
                ua: 'Слоти гаража',
                en: 'Garage slots',
                de: 'Garagenplaetze',
                pl: 'Miejsca w garazu',
            },
            empty: {
                ru: 'Дом не привязан',
                ua: 'Будинок не прив\'язаний',
                en: 'No house linked',
                de: 'Kein Haus verknuepft',
                pl: 'Brak przypisanego domu',
            },
        },
        office: {
            title: {
                ru: 'Офис',
                ua: 'Офіс',
                en: 'Office',
                de: 'Buero',
                pl: 'Biuro',
            },
            slots: {
                ru: 'Слоты гаража',
                ua: 'Слоти гаража',
                en: 'Garage slots',
                de: 'Garagenplaetze',
                pl: 'Miejsca w garazu',
            },
            empty: {
                ru: 'Офис не приобретён',
                ua: 'Офіс не придбаний',
                en: 'No office owned',
                de: 'Kein Buero gekauft',
                pl: 'Brak biura',
            },
        },
        warehouse: {
            title: {
                ru: 'Коллеги',
                ua: 'Колеги',
                en: 'Colleagues',
                de: 'Kollegen',
                pl: 'Koledzy',
            },
            units: {
                ru: 'Хранилищ',
                ua: 'Сховищ',
                en: 'Storages',
                de: 'Lager',
                pl: 'Magazynow',
            },
            itemsCount: {
                ru: 'Предметов',
                ua: 'Предметів',
                en: 'Items',
                de: 'Gegenstaende',
                pl: 'Przedmiotow',
            },
            uniqueItems: {
                ru: 'Видов',
                ua: 'Видів',
                en: 'Unique',
                de: 'Arten',
                pl: 'Rodzajow',
            },
            empty: {
                ru: 'Склад не оборудован',
                ua: 'Склад не обладнаний',
                en: 'No storages set up',
                de: 'Kein Lager vorhanden',
                pl: 'Brak magazynu',
            },
        },
        vehicles: {
            title: {
                ru: 'Транспорт',
                ua: 'Транспорт',
                en: 'Vehicles',
                de: 'Fahrzeuge',
                pl: 'Pojazdy',
            },
            empty: {
                ru: 'Нет машин',
                ua: 'Немає машин',
                en: 'No vehicles',
                de: 'Keine Fahrzeuge',
                pl: 'Brak pojazdow',
            },
        },
        vehicleStatus: {
            parked: {
                ru: 'В гараже',
                ua: 'У гаражі',
                en: 'Parked',
                de: 'Geparkt',
                pl: 'Zaparkowany',
            },
            taken: {
                ru: 'Выехал',
                ua: 'Виїхав',
                en: 'Taken out',
                de: 'Unterwegs',
                pl: 'Wyjechal',
            },
            destroyed: {
                ru: 'Разбит',
                ua: 'Розбитий',
                en: 'Destroyed',
                de: 'Zerstoert',
                pl: 'Zniszczony',
            },
            impounded: {
                ru: 'На штрафстоянке',
                ua: 'На штрафмайданчику',
                en: 'Impounded',
                de: 'Beschlagnahmt',
                pl: 'Zajety',
            },
            orphan: {
                ru: 'Без слота',
                ua: 'Без слота',
                en: 'Unbound',
                de: 'Kein Platz',
                pl: 'Bez miejsca',
            },
        },
        locations: {
            hq: {
                ru: 'HQ {id}',
                ua: 'HQ {id}',
                en: 'HQ {id}',
                de: 'HQ {id}',
                pl: 'HQ {id}',
            },
            office: {
                ru: 'Офис',
                ua: 'Офіс',
                en: 'Office',
                de: 'Buero',
                pl: 'Biuro',
            },
            unbound: {
                ru: 'Без привязки',
                ua: 'Без прив\'язки',
                en: 'Unbound',
                de: 'Ungebunden',
                pl: 'Niepowiazany',
            },
        },
        houseClass: {
            economy: {
                ru: 'Эконом',
                ua: 'Економ',
                en: 'Economy',
                de: 'Oekonom',
                pl: 'Ekonom',
            },
            middle: {
                ru: 'Средний',
                ua: 'Середній',
                en: 'Middle',
                de: 'Mittel',
                pl: 'Sredni',
            },
            premium: {
                ru: 'Премиум',
                ua: 'Преміум',
                en: 'Premium',
                de: 'Premium',
                pl: 'Premium',
            },
            elite: {
                ru: 'Элит',
                ua: 'Еліт',
                en: 'Elite',
                de: 'Elite',
                pl: 'Elita',
            },
        },
    },
    members: {
        searchPlaceholder: {
            ru: 'Поиск по имени или ID',
            ua: 'Пошук за іменем або ID',
            en: 'Search by name or ID',
            de: 'Suche nach Name oder ID',
            pl: 'Szukaj po nazwie lub ID',
        },
        manage: {
            ru: 'Управлять',
            ua: 'Керувати',
            en: 'Manage',
            de: 'Verwalten',
            pl: 'Zarządzaj',
        },
        view: {
            ru: 'Просмотр',
            ua: 'Перегляд',
            en: 'View',
            de: 'Ansehen',
            pl: 'Podgląd',
        },
        online: {
            ru: 'Онлайн',
            ua: 'Онлайн',
            en: 'Online',
            de: 'Online',
            pl: 'Online',
        },
        offline: {
            ru: 'Оффлайн',
            ua: 'Офлайн',
            en: 'Offline',
            de: 'Offline',
            pl: 'Offline',
        },
        youTag: {
            ru: 'Вы',
            ua: 'Ви',
            en: 'You',
            de: 'Du',
            pl: 'Ty',
        },
        unknownName: {
            ru: 'Имя неизвестно',
            ua: 'Ім\'я невідоме',
            en: 'Unknown name',
            de: 'Unbekannter Name',
            pl: 'Nieznane imię',
        },
        joinedShort: {
            ru: 'в организации с {{date}}',
            ua: 'в організації з {{date}}',
            en: 'joined {{date}}',
            de: 'seit {{date}}',
            pl: 'w organizacji od {{date}}',
        },
        allRanks: {
            ru: 'Все ранги',
            ua: 'Усі ранги',
            en: 'All ranks',
            de: 'Alle Ränge',
            pl: 'Wszystkie rangi',
        },
        confirmKick: {
            title: {
                ru: 'Исключение из организации',
                ua: 'Виключення з організації',
                en: 'Kick from organization',
                de: 'Aus der Organisation entfernen',
                pl: 'Wyrzucenie z organizacji',
            },
            message: {
                ru: 'Вы уверены, что хотите выгнать {{name}} из организации?',
                ua: 'Ви впевнені, що хочете вигнати {{name}} з організації?',
                en: 'Are you sure you want to kick {{name}} from the organization?',
                de: 'Möchtest du {{name}} wirklich aus der Organisation entfernen?',
                pl: 'Czy na pewno chcesz wyrzucić {{name}} z organizacji?',
            },
            confirm: {
                ru: 'Выгнать',
                ua: 'Вигнати',
                en: 'Kick',
                de: 'Entfernen',
                pl: 'Wyrzuć',
            },
            cancel: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
        },
        empty: {
            ru: 'Участники не найдены',
            ua: 'Учасників не знайдено',
            en: 'No members found',
            de: 'Keine Mitglieder gefunden',
            pl: 'Nie znaleziono członków',
        },
        columns: {
            name: {
                ru: 'Имя',
                ua: 'Ім\'я',
                en: 'Name',
                de: 'Name',
                pl: 'Imię',
            },
            rank: {
                ru: 'Ранг',
                ua: 'Ранг',
                en: 'Rank',
                de: 'Rang',
                pl: 'Ranga',
            },
            status: {
                ru: 'Статус',
                ua: 'Статус',
                en: 'Status',
                de: 'Status',
                pl: 'Status',
            },
            joined: {
                ru: 'Вступил',
                ua: 'Вступив',
                en: 'Joined',
                de: 'Beigetreten',
                pl: 'Dołączył',
            },
            action: {
                ru: 'Действие',
                ua: 'Дія',
                en: 'Action',
                de: 'Aktion',
                pl: 'Akcja',
            },
        },
        modal: {
            kickerSelf: {
                ru: 'Ваш профиль',
                ua: 'Ваш профіль',
                en: 'Your profile',
                de: 'Dein Profil',
                pl: 'Twój profil',
            },
            kickerView: {
                ru: 'Профиль участника',
                ua: 'Профіль учасника',
                en: 'Member profile',
                de: 'Mitgliederprofil',
                pl: 'Profil członka',
            },
            kickerManage: {
                ru: 'Управление участником',
                ua: 'Керування учасником',
                en: 'Manage member',
                de: 'Mitglied verwalten',
                pl: 'Zarządzanie członkiem',
            },
            staticId: {
                ru: 'Static ID',
                ua: 'Static ID',
                en: 'Static ID',
                de: 'Static ID',
                pl: 'Static ID',
            },
            status: {
                ru: 'Статус',
                ua: 'Статус',
                en: 'Status',
                de: 'Status',
                pl: 'Status',
            },
            joined: {
                ru: 'Дата вступления',
                ua: 'Дата вступу',
                en: 'Joined',
                de: 'Beigetreten',
                pl: 'Data dołączenia',
            },
            currentRank: {
                ru: 'Текущий ранг',
                ua: 'Поточний ранг',
                en: 'Current rank',
                de: 'Aktueller Rang',
                pl: 'Obecna ranga',
            },
            changeRank: {
                ru: 'Сменить ранг',
                ua: 'Змінити ранг',
                en: 'Change rank',
                de: 'Rang ändern',
                pl: 'Zmień rangę',
            },
            applyRank: {
                ru: 'Сохранить',
                ua: 'Зберегти',
                en: 'Apply',
                de: 'Übernehmen',
                pl: 'Zastosuj',
            },
            kick: {
                ru: 'Выгнать из организации',
                ua: 'Вигнати з організації',
                en: 'Kick from organization',
                de: 'Aus der Organisation werfen',
                pl: 'Wyrzuć z organizacji',
            },
            closeView: {
                ru: 'Закрыть',
                ua: 'Закрити',
                en: 'Close',
                de: 'Schließen',
                pl: 'Zamknij',
            },
        },
    },
    ranks: {
        searchPlaceholder: {
            ru: 'Поиск ранга',
            ua: 'Пошук рангу',
            en: 'Search rank',
            de: 'Rang suchen',
            pl: 'Szukaj rangi',
        },
        create: {
            ru: 'Создать ранг',
            ua: 'Створити ранг',
            en: 'Create rank',
            de: 'Rang erstellen',
            pl: 'Utwórz rangę',
        },
        manage: {
            ru: 'Управлять',
            ua: 'Керувати',
            en: 'Manage',
            de: 'Verwalten',
            pl: 'Zarządzaj',
        },
        view: {
            ru: 'Просмотр',
            ua: 'Перегляд',
            en: 'View',
            de: 'Ansehen',
            pl: 'Podgląd',
        },
        leaderTag: {
            ru: 'Лидер',
            ua: 'Лідер',
            en: 'Leader',
            de: 'Anführer',
            pl: 'Lider',
        },
        yourRank: {
            ru: 'Вы',
            ua: 'Ви',
            en: 'You',
            de: 'Du',
            pl: 'Ty',
        },
        empty: {
            ru: 'Рангов не найдено',
            ua: 'Рангів не знайдено',
            en: 'No ranks found',
            de: 'Keine Ränge gefunden',
            pl: 'Nie znaleziono rang',
        },
        columns: {
            name: {
                ru: 'Название',
                ua: 'Назва',
                en: 'Name',
                de: 'Name',
                pl: 'Nazwa',
            },
            members: {
                ru: 'Участники',
                ua: 'Учасники',
                en: 'Members',
                de: 'Mitglieder',
                pl: 'Członkowie',
            },
            action: {
                ru: 'Действие',
                ua: 'Дія',
                en: 'Action',
                de: 'Aktion',
                pl: 'Akcja',
            },
        },
        errors: {
            nameEmpty: {
                ru: 'Введите название ранга',
                ua: 'Введіть назву рангу',
                en: 'Enter a rank name',
                de: 'Bitte Rangname eingeben',
                pl: 'Wpisz nazwę rangi',
            },
            nameTooLong: {
                ru: 'Не более 32 символов',
                ua: 'Не більше 32 символів',
                en: 'Up to 32 characters',
                de: 'Bis zu 32 Zeichen',
                pl: 'Do 32 znaków',
            },
        },
        confirmDelete: {
            title: {
                ru: 'Удаление ранга',
                ua: 'Видалення рангу',
                en: 'Delete rank',
                de: 'Rang löschen',
                pl: 'Usunięcie rangi',
            },
            message: {
                ru: 'Удалить ранг «{{name}}»? Это действие нельзя отменить.',
                ua: 'Видалити ранг «{{name}}»? Цю дію не можна скасувати.',
                en: 'Delete rank "{{name}}"? This action cannot be undone.',
                de: 'Rang «{{name}}» löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
                pl: 'Usunąć rangę „{{name}}"? Tego nie można cofnąć.',
            },
            confirm: {
                ru: 'Удалить',
                ua: 'Видалити',
                en: 'Delete',
                de: 'Löschen',
                pl: 'Usuń',
            },
            cancel: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
        },
        panel: {
            kickerCreate: {
                ru: 'Новый ранг',
                ua: 'Новий ранг',
                en: 'New rank',
                de: 'Neuer Rang',
                pl: 'Nowa ranga',
            },
            kickerEdit: {
                ru: 'Управление рангом',
                ua: 'Керування рангом',
                en: 'Manage rank',
                de: 'Rang verwalten',
                pl: 'Zarządzaj rangą',
            },
            titleCreate: {
                ru: 'Создание ранга',
                ua: 'Створення рангу',
                en: 'Create rank',
                de: 'Rang anlegen',
                pl: 'Utwórz rangę',
            },
            nameLabel: {
                ru: 'Название',
                ua: 'Назва',
                en: 'Name',
                de: 'Name',
                pl: 'Nazwa',
            },
            namePlaceholder: {
                ru: 'Например: Капитан',
                ua: 'Наприклад: Капітан',
                en: 'e.g. Captain',
                de: 'z.B. Kapitän',
                pl: 'np. Kapitan',
            },
            permsLabel: {
                ru: 'Права',
                ua: 'Права',
                en: 'Permissions',
                de: 'Rechte',
                pl: 'Uprawnienia',
            },
            delete: {
                ru: 'Удалить',
                ua: 'Видалити',
                en: 'Delete',
                de: 'Löschen',
                pl: 'Usuń',
            },
            createSubmit: {
                ru: 'Создать',
                ua: 'Створити',
                en: 'Create',
                de: 'Erstellen',
                pl: 'Utwórz',
            },
            saveSubmit: {
                ru: 'Сохранить',
                ua: 'Зберегти',
                en: 'Save',
                de: 'Speichern',
                pl: 'Zapisz',
            },
            closeView: {
                ru: 'Закрыть',
                ua: 'Закрити',
                en: 'Close',
                de: 'Schließen',
                pl: 'Zamknij',
            },
        },
    },
    territories: {
        frozen: {
            ru: 'Территории заморожены',
            ua: 'Території заморожені',
            en: 'Territories frozen',
            de: 'Gebiete eingefroren',
            pl: 'Terytoria zamrozone',
        },
        brush: {
            ru: 'Кисть',
            ua: 'Пензель',
            en: 'Brush',
            de: 'Pinsel',
            pl: 'Pedzel',
        },
        brushHint: {
            ru: '(клик — смена цвета, клик по квадрату — перекраска)',
            ua: '(клік — зміна кольору, клік по квадрату — перефарбування)',
            en: '(click to cycle, click cell to paint)',
            de: '(klick zum Wechseln, klick Feld zum Faerben)',
            pl: '(klik aby zmienic, klik pole aby pomalowac)',
        },
        logsEmpty: {
            ru: 'Действий пока нет',
            ua: 'Дій поки немає',
            en: 'No actions yet',
            de: 'Noch keine Aktionen',
            pl: 'Brak akcji',
        },
        admin: {
            addAttack: {
                ru: 'Добавить +1 атаку',
                ua: 'Додати +1 атаку',
                en: 'Add +1 attack',
                de: '+1 Angriff hinzufuegen',
                pl: 'Dodaj +1 atak',
            },
            removeAttack: {
                ru: 'Удалить -1 атаку',
                ua: 'Видалити -1 атаку',
                en: 'Remove -1 attack',
                de: '-1 Angriff entfernen',
                pl: 'Usun -1 atak',
            },
            resetAttackCd: {
                ru: 'Сбросить КД атаки',
                ua: 'Скинути КД атаки',
                en: 'Reset attack CD',
                de: 'Angriffs-CD ruecksetzen',
                pl: 'Reset CD ataku',
            },
            addDefense: {
                ru: 'Добавить +1 защиту',
                ua: 'Додати +1 захист',
                en: 'Add +1 defense',
                de: '+1 Verteidigung hinzufuegen',
                pl: 'Dodaj +1 obrone',
            },
            removeDefense: {
                ru: 'Удалить -1 защиту',
                ua: 'Видалити -1 захист',
                en: 'Remove -1 defense',
                de: '-1 Verteidigung entfernen',
                pl: 'Usun -1 obrone',
            },
            resetDefenseCd: {
                ru: 'Сбросить КД защиты',
                ua: 'Скинути КД захисту',
                en: 'Reset defense CD',
                de: 'Verteidigungs-CD ruecksetzen',
                pl: 'Reset CD obrony',
            },
            createAppeal: {
                ru: 'Создать обращение к организации',
                ua: 'Створити звернення до організації',
                en: 'Create appeal to org',
                de: 'Anfrage an Organisation',
                pl: 'Utworz wniosek do org',
            },
            freezeAll: {
                ru: 'Заморозить все территории',
                ua: 'Заморозити всі території',
                en: 'Freeze all territories',
                de: 'Alle Gebiete einfrieren',
                pl: 'Zamroz wszystkie terytoria',
            },
            actionLogs: {
                ru: 'Логи действий',
                ua: 'Логи дій',
                en: 'Action logs',
                de: 'Aktionsprotokoll',
                pl: 'Logi akcji',
            },
            repaintMode: {
                ru: 'Режим перекраски территорий',
                ua: 'Режим перефарбовування територій',
                en: 'Repaint mode',
                de: 'Umfaerben-Modus',
                pl: 'Tryb przemalowywania',
            },
        },
        typeDescriptions: {
            plain: {
                ru: 'Базовая территория организации',
                ua: 'Базова територія організації',
                en: 'Plain organization territory',
                de: 'Normales Org-Gebiet',
                pl: 'Zwykle terytorium org',
            },
            business_24_7: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_clothes: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_barber: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_lsc: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_gas: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_carshop: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_carwash: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_fishing: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_mushroom: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_restaurant: {
                ru: 'Получение выплат от бизнеса на счёт организации',
                ua: 'Отримання виплат від бізнесу на рахунок організації',
                en: 'Income from this business goes to the org treasury',
                de: 'Geschaeftseinkommen fliesst in die Org-Kasse',
                pl: 'Dochod biznesu trafia do skarbca org',
            },
            business_free: {
                ru: 'Помещение для интерьеров организации',
                ua: 'Приміщення для інтер\'єрів організації',
                en: 'Free-use premises for the org',
                de: 'Mehrzweckraeumlichkeit',
                pl: 'Lokal uzytkowy organizacji',
            },
            ems: {
                ru: 'Контроль приносит фиксированное Влияние',
                ua: 'Контроль приносить фіксований Вплив',
                en: 'Control grants fixed Influence',
                de: 'Kontrolle bringt festen Einfluss',
                pl: 'Kontrola daje staly Wplyw',
            },
            scrapyard: {
                ru: 'Точка переработки транспорта',
                ua: 'Точка переробки транспорту',
                en: 'Vehicle scrap depot',
                de: 'Schrottdepot',
                pl: 'Zlomowisko pojazdow',
            },
            narcoLab: {
                ru: 'Подпольная лаборатория по производству наркотиков',
                ua: 'Підпільна лабораторія виробництва наркотиків',
                en: 'Clandestine narcotics lab',
                de: 'Geheimes Drogenlabor',
                pl: 'Tajne laboratorium narkotykowe',
            },
            workshop: {
                ru: 'Цех по крафту документов и инструментов',
                ua: 'Цех з крафту документів і інструментів',
                en: 'Workshop for documents and tools',
                de: 'Werkstatt fuer Dokumente und Werkzeug',
                pl: 'Warsztat dokumentow i narzedzi',
            },
            bunker: {
                ru: 'Подземная база по производству оружия',
                ua: 'Підземна база виробництва зброї',
                en: 'Underground arms production base',
                de: 'Unterirdische Waffenbasis',
                pl: 'Podziemna baza produkcji broni',
            },
            casino: {
                ru: 'Уменьшает комиссию при обмене фишек',
                ua: 'Зменшує комісію при обміні фішок',
                en: 'Reduces chip exchange commission',
                de: 'Senkt Chip-Wechselgebuehr',
                pl: 'Zmniejsza prowizje za zetony',
            },
            controlPoint: {
                ru: 'Усиленная точка контроля территории',
                ua: 'Посилена точка контролю території',
                en: 'Fortified control point',
                de: 'Verstaerkter Kontrollpunkt',
                pl: 'Wzmocniony punkt kontroli',
            },
            businessMultiplier: {
                ru: 'Множитель Влияния со всех бизнесов организации',
                ua: 'Множник Впливу з усіх бізнесів організації',
                en: 'Multiplier on Influence from all org businesses',
                de: 'Multiplikator auf Org-Geschaeftseinfluss',
                pl: 'Mnoznik Wplywu z biznesow org',
            },
        },
        hud: {
            control: {
                ru: 'Контроль',
                ua: 'Контроль',
                en: 'Control',
                de: 'Kontrolle',
                pl: 'Kontrola',
            },
        },
        notifications: {
            button: {
                ru: 'Уведомления',
                ua: 'Сповіщення',
                en: 'Notifications',
                de: 'Benachrichtigungen',
                pl: 'Powiadomienia',
            },
        },
        history: {
            button: {
                ru: 'История битв',
                ua: 'Історія битв',
                en: 'Battle history',
                de: 'Kampfverlauf',
                pl: 'Historia bitew',
            },
            title: {
                ru: 'История битв',
                ua: 'Історія битв',
                en: 'Battle history',
                de: 'Kampfverlauf',
                pl: 'Historia bitew',
            },
            close: {
                ru: 'Закрыть',
                ua: 'Закрити',
                en: 'Close',
                de: 'Schliessen',
                pl: 'Zamknij',
            },
            empty: {
                ru: 'Битв пока не было',
                ua: 'Битв поки не було',
                en: 'No battles yet',
                de: 'Noch keine Kaempfe',
                pl: 'Brak bitew',
            },
            justNow: {
                ru: 'только что',
                ua: 'щойно',
                en: 'just now',
                de: 'gerade eben',
                pl: 'wlasnie teraz',
            },
            minutesAgo: {
                ru: '{{count}} мин назад',
                ua: '{{count}} хв тому',
                en: '{{count}} min ago',
                de: 'vor {{count}} Min',
                pl: '{{count}} min temu',
            },
            hoursAgo: {
                ru: '{{count}} ч назад',
                ua: '{{count}} год тому',
                en: '{{count}} h ago',
                de: 'vor {{count}} Std',
                pl: '{{count}} godz temu',
            },
            daysAgo: {
                ru: '{{count}} д назад',
                ua: '{{count}} д тому',
                en: '{{count}} d ago',
                de: 'vor {{count}} T',
                pl: '{{count}} d temu',
            },
            result: {
                victory: {
                    ru: 'Победа',
                    ua: 'Перемога',
                    en: 'Victory',
                    de: 'Sieg',
                    pl: 'Zwyciestwo',
                },
                defeat: {
                    ru: 'Поражение',
                    ua: 'Поразка',
                    en: 'Defeat',
                    de: 'Niederlage',
                    pl: 'Porazka',
                },
                draw: {
                    ru: 'Ничья',
                    ua: 'Нічия',
                    en: 'Draw',
                    de: 'Unentschieden',
                    pl: 'Remis',
                },
            },
            kind: {
                attack: {
                    ru: 'Атака',
                    ua: 'Атака',
                    en: 'Attack',
                    de: 'Angriff',
                    pl: 'Atak',
                },
                defense: {
                    ru: 'Защита',
                    ua: 'Захист',
                    en: 'Defense',
                    de: 'Verteidigung',
                    pl: 'Obrona',
                },
            },
            summary: {
                total: {
                    ru: 'Всего',
                    ua: 'Усього',
                    en: 'Total',
                    de: 'Gesamt',
                    pl: 'Razem',
                },
                victories: {
                    ru: 'Победы',
                    ua: 'Перемоги',
                    en: 'Wins',
                    de: 'Siege',
                    pl: 'Wygrane',
                },
                defeats: {
                    ru: 'Поражения',
                    ua: 'Поразки',
                    en: 'Losses',
                    de: 'Niederlagen',
                    pl: 'Przegrane',
                },
                net: {
                    ru: 'Δ влияние',
                    ua: 'Δ вплив',
                    en: 'Δ influence',
                    de: 'Δ Einfluss',
                    pl: 'Δ wplyw',
                },
            },
            filter: {
                all: {
                    ru: 'Все',
                    ua: 'Усі',
                    en: 'All',
                    de: 'Alle',
                    pl: 'Wszystkie',
                },
                wars: {
                    ru: 'Войны',
                    ua: 'Війни',
                    en: 'Wars',
                    de: 'Kriege',
                    pl: 'Wojny',
                },
                peaceful: {
                    ru: 'Захваты',
                    ua: 'Захоплення',
                    en: 'Captures',
                    de: 'Eroberungen',
                    pl: 'Przejecia',
                },
            },
            loading: {
                ru: 'Загрузка истории...',
                ua: 'Завантаження історії...',
                en: 'Loading history...',
                de: 'Verlauf wird geladen...',
                pl: 'Wczytywanie historii...',
            },
            peaceful: {
                ru: 'Захват',
                ua: 'Захоплення',
                en: 'Capture',
                de: 'Eroberung',
                pl: 'Przejecie',
            },
            attackers: {
                ru: 'Атакующие',
                ua: 'Атакуючі',
                en: 'Attackers',
                de: 'Angreifer',
                pl: 'Atakujacy',
            },
            defenders: {
                ru: 'Защитники',
                ua: 'Захисники',
                en: 'Defenders',
                de: 'Verteidiger',
                pl: 'Obroncy',
            },
            participantsEmpty: {
                ru: 'Данные об участниках недоступны',
                ua: 'Дані про учасників недоступні',
                en: 'Participant data unavailable',
                de: 'Teilnehmerdaten nicht verfuegbar',
                pl: 'Brak danych o uczestnikach',
            },
            influenceShort: {
                ru: 'ВЛ',
                ua: 'ВПЛ',
                en: 'INF',
                de: 'EIN',
                pl: 'WPL',
            },
            back: {
                ru: 'Назад',
                ua: 'Назад',
                en: 'Back',
                de: 'Zurueck',
                pl: 'Wstecz',
            },
            vs: {
                ru: 'vs',
                ua: 'vs',
                en: 'vs',
                de: 'vs',
                pl: 'vs',
            },
            map: {
                ru: 'Карта',
                ua: 'Мапа',
                en: 'Map',
                de: 'Karte',
                pl: 'Mapa',
            },
            peacefulCaptureNote: {
                ru: 'Мирный захват — без участников',
                ua: 'Мирне захоплення — без учасників',
                en: 'Peaceful capture — no participants',
                de: 'Friedliche Eroberung — ohne Teilnehmer',
                pl: 'Spokojne przejecie — bez uczestnikow',
            },
            cols: {
                kills: {
                    ru: 'У',
                    ua: 'В',
                    en: 'K',
                    de: 'K',
                    pl: 'Z',
                },
                deaths: {
                    ru: 'С',
                    ua: 'С',
                    en: 'D',
                    de: 'T',
                    pl: 'S',
                },
                assists: {
                    ru: 'А',
                    ua: 'А',
                    en: 'A',
                    de: 'A',
                    pl: 'A',
                },
                headshots: {
                    ru: 'HS',
                    ua: 'HS',
                    en: 'HS',
                    de: 'HS',
                    pl: 'HS',
                },
                damage: {
                    ru: 'УРН',
                    ua: 'УРН',
                    en: 'DMG',
                    de: 'SCH',
                    pl: 'OBR',
                },
                kd: {
                    ru: 'У/С',
                    ua: 'В/С',
                    en: 'K/D',
                    de: 'K/T',
                    pl: 'Z/S',
                },
            },
            details: {
                result: {
                    ru: 'Итог',
                    ua: 'Підсумок',
                    en: 'Result',
                    de: 'Ergebnis',
                    pl: 'Wynik',
                },
                kind: {
                    ru: 'Тип',
                    ua: 'Тип',
                    en: 'Type',
                    de: 'Typ',
                    pl: 'Typ',
                },
                influence: {
                    ru: 'Влияние',
                    ua: 'Вплив',
                    en: 'Influence',
                    de: 'Einfluss',
                    pl: 'Wplyw',
                },
                when: {
                    ru: 'Время',
                    ua: 'Час',
                    en: 'Time',
                    de: 'Zeit',
                    pl: 'Czas',
                },
            },
        },
        breakdown: {
            title: {
                ru: 'Кол-во влияния за день',
                ua: 'Кіл-ть впливу за день',
                en: 'Influence per day',
                de: 'Einfluss pro Tag',
                pl: 'Wplyw na dzien',
            },
            empty: {
                ru: 'Нет источников Влияния — захватывайте квадраты',
                ua: 'Немає джерел Впливу — захоплюйте квадрати',
                en: 'No Influence sources yet — claim squares',
                de: 'Noch keine Einfluss-Quellen — Felder erobern',
                pl: 'Brak zrodel Wplywu — przejmuj pola',
            },
        },
        tooltip: {
            profit: {
                ru: 'Прибыль',
                ua: 'Прибуток',
                en: 'Profit',
                de: 'Gewinn',
                pl: 'Zysk',
            },
            perHour: {
                ru: 'час',
                ua: 'год',
                en: 'hour',
                de: 'Std',
                pl: 'godz',
            },
            influence: {
                ru: 'Влияние',
                ua: 'Вплив',
                en: 'Influence',
                de: 'Einfluss',
                pl: 'Wplyw',
            },
            perDay: {
                ru: 'в день',
                ua: 'на день',
                en: 'per day',
                de: 'pro Tag',
                pl: 'na dzien',
            },
            received: {
                ru: 'Получено',
                ua: 'Отримано',
                en: 'Received',
                de: 'Erhalten',
                pl: 'Otrzymano',
            },
            requirements: {
                ru: 'Требования для атаки',
                ua: 'Вимоги для атаки',
                en: 'Attack requirements',
                de: 'Angriffsanforderungen',
                pl: 'Wymagania ataku',
            },
            controlledBy: {
                ru: 'Контроль',
                ua: 'Контроль',
                en: 'Held by',
                de: 'Kontrolle',
                pl: 'Kontrola',
            },
            neutral: {
                ru: 'нейтральный',
                ua: 'нейтральний',
                en: 'neutral',
                de: 'neutral',
                pl: 'neutralny',
            },
            singletonHint: {
                ru: 'Можно контролировать не больше {max} квадратов данного типа.',
                ua: 'Можна контролювати не більше {max} квадратів цього типу.',
                en: 'You may control at most {max} squares of this type.',
                de: 'Du kannst hoechstens {max} Felder dieses Typs halten.',
                pl: 'Mozna kontrolowac maks. {max} pol tego typu.',
            },
        },
        actions: {
            attack: {
                ru: 'Совершить нападение',
                ua: 'Здійснити напад',
                en: 'Attack',
                de: 'Angreifen',
                pl: 'Zaatakuj',
            },
            claim: {
                ru: 'Захватить',
                ua: 'Захопити',
                en: 'Claim',
                de: 'Einnehmen',
                pl: 'Przejmij',
            },
        },
        requirements: {
            plainCells_20: {
                ru: 'Обычные квадраты (20)',
                ua: 'Звичайні квадрати (20)',
                en: 'Plain squares (20)',
                de: 'Normale Felder (20)',
                pl: 'Zwykle pola (20)',
            },
            plainCells_30: {
                ru: 'Обычные квадраты (30)',
                ua: 'Звичайні квадрати (30)',
                en: 'Plain squares (30)',
                de: 'Normale Felder (30)',
                pl: 'Zwykle pola (30)',
            },
            neighbors_7: {
                ru: 'Необходимо контролировать более 7 квадратов вокруг',
                ua: 'Необхідно контролювати понад 7 квадратів навколо',
                en: 'Must control 7+ surrounding squares',
                de: 'Muss 7+ angrenzende Felder halten',
                pl: 'Musisz kontrolowac 7+ sasiednich pol',
            },
            neighbors_10: {
                ru: 'Необходимо контролировать более 10 квадратов вокруг',
                ua: 'Необхідно контролювати понад 10 квадратів навколо',
                en: 'Must control 10+ surrounding squares',
                de: 'Muss 10+ angrenzende Felder halten',
                pl: 'Musisz kontrolowac 10+ sasiednich pol',
            },
            neighborsPct_60_min7: {
                ru: 'Контроль 60% соседей (мин. 7)',
                ua: 'Контроль 60% сусідів (мін. 7)',
                en: '60% of neighbors (min 7)',
                de: '60% der Nachbarn (min. 7)',
                pl: '60% sasiadow (min. 7)',
            },
            allNeighborsOwned: {
                ru: 'Все соседние квадраты принадлежат вам',
                ua: 'Усі сусідні квадрати належать вам',
                en: 'All adjacent squares are yours',
                de: 'Alle angrenzenden Felder gehoeren dir',
                pl: 'Wszystkie sasiednie pola sa Twoje',
            },
            treeNode_territoryControl: {
                ru: 'Узел дерева «Контроль территорий»',
                ua: 'Вузол дерева «Контроль територій»',
                en: 'Tree node "Territory control"',
                de: 'Baumknoten "Gebietskontrolle"',
                pl: 'Wezel drzewa "Kontrola terytoriow"',
            },
        },
        typeNames: {
            plain: {
                ru: 'Обычный квадрат',
                ua: 'Звичайний квадрат',
                en: 'Plain square',
                de: 'Normales Feld',
                pl: 'Zwykle pole',
            },
            business_24_7: {
                ru: 'Магазин 24/7',
                ua: 'Магазин 24/7',
                en: '24/7 store',
                de: 'Laden 24/7',
                pl: 'Sklep 24/7',
            },
            business_clothes: {
                ru: 'Магазин одежды',
                ua: 'Магазин одягу',
                en: 'Clothing store',
                de: 'Bekleidungsgeschaeft',
                pl: 'Sklep odziezowy',
            },
            business_barber: {
                ru: 'Барбершоп',
                ua: 'Барбершоп',
                en: 'Barbershop',
                de: 'Barbier',
                pl: 'Fryzjer',
            },
            business_lsc: {
                ru: 'LSC',
                ua: 'LSC',
                en: 'LSC',
                de: 'LSC',
                pl: 'LSC',
            },
            business_gas: {
                ru: 'АЗС',
                ua: 'АЗС',
                en: 'Gas station',
                de: 'Tankstelle',
                pl: 'Stacja paliw',
            },
            business_carshop: {
                ru: 'Автосалон',
                ua: 'Автосалон',
                en: 'Car dealer',
                de: 'Autohaus',
                pl: 'Salon samochodowy',
            },
            business_carwash: {
                ru: 'Автомойка',
                ua: 'Автомийка',
                en: 'Car wash',
                de: 'Autowaesche',
                pl: 'Myjnia',
            },
            business_fishing: {
                ru: 'Точка ловли рыбы',
                ua: 'Точка ловлі риби',
                en: 'Fishing spot',
                de: 'Angelplatz',
                pl: 'Lowisko',
            },
            business_mushroom: {
                ru: 'Точка сбора грибов',
                ua: 'Точка збору грибів',
                en: 'Mushroom patch',
                de: 'Pilzstelle',
                pl: 'Grzybobranie',
            },
            business_restaurant: {
                ru: 'Ресторан',
                ua: 'Ресторан',
                en: 'Restaurant',
                de: 'Restaurant',
                pl: 'Restauracja',
            },
            business_free: {
                ru: 'Помещение свободного назначения',
                ua: 'Приміщення вільного призначення',
                en: 'Free-use premises',
                de: 'Mehrzweckimmobilie',
                pl: 'Lokal uzytkowy',
            },
            ems: {
                ru: 'Emergency Medical Service (EMS)',
                ua: 'Emergency Medical Service (EMS)',
                en: 'Emergency Medical Service (EMS)',
                de: 'Emergency Medical Service (EMS)',
                pl: 'Emergency Medical Service (EMS)',
            },
            scrapyard: {
                ru: 'Свалка транспорта',
                ua: 'Звалище транспорту',
                en: 'Scrapyard',
                de: 'Schrottplatz',
                pl: 'Zlomowisko',
            },
            narcoLab: {
                ru: 'Нарколаба',
                ua: 'Наркола́ба',
                en: 'Narco lab',
                de: 'Drogenlabor',
                pl: 'Laboratorium narkotykowe',
            },
            workshop: {
                ru: 'Мастерская',
                ua: 'Майстерня',
                en: 'Workshop',
                de: 'Werkstatt',
                pl: 'Warsztat',
            },
            bunker: {
                ru: 'Бункер',
                ua: 'Бункер',
                en: 'Bunker',
                de: 'Bunker',
                pl: 'Bunkier',
            },
            casino: {
                ru: 'Казино',
                ua: 'Казино',
                en: 'Casino',
                de: 'Casino',
                pl: 'Kasyno',
            },
            controlPoint: {
                ru: 'Контрольная точка',
                ua: 'Контрольна точка',
                en: 'Control point',
                de: 'Kontrollpunkt',
                pl: 'Punkt kontrolny',
            },
            businessMultiplier: {
                ru: 'Множитель бизнесов',
                ua: 'Множник бізнесів',
                en: 'Business multiplier',
                de: 'Geschaeftsmultiplikator',
                pl: 'Mnoznik biznesow',
            },
        },
        planAttack: {
            back: {
                ru: 'Назад',
                ua: 'Назад',
                en: 'Back',
                de: 'Zurueck',
                pl: 'Wstecz',
            },
            controlLabel: {
                ru: 'Контроль',
                ua: 'Контроль',
                en: 'Control',
                de: 'Kontrolle',
                pl: 'Kontrola',
            },
            scheduleCta: {
                ru: 'Запланировать атаку',
                ua: 'Запланувати атаку',
                en: 'Schedule attack',
                de: 'Angriff planen',
                pl: 'Zaplanuj atak',
            },
            editTitle: {
                ru: 'Изменить состав',
                ua: 'Змінити склад',
                en: 'Edit roster',
                de: 'Trupp bearbeiten',
                pl: 'Edytuj sklad',
            },
            saveCta: {
                ru: 'Сохранить',
                ua: 'Зберегти',
                en: 'Save',
                de: 'Speichern',
                pl: 'Zapisz',
            },
            startTimeLabel: {
                ru: 'Укажите время начала атаки',
                ua: 'Вкажіть час початку атаки',
                en: 'Pick attack start time',
                de: 'Startzeit des Angriffs',
                pl: 'Wybierz czas rozpoczecia ataku',
            },
            hours: {
                ru: 'Часы',
                ua: 'Години',
                en: 'Hours',
                de: 'Stunden',
                pl: 'Godziny',
            },
            minutes: {
                ru: 'Минуты',
                ua: 'Хвилини',
                en: 'Minutes',
                de: 'Minuten',
                pl: 'Minuty',
            },
            slotsLabel: {
                ru: 'Участники каждой из сторон',
                ua: 'Учасники кожної зі сторін',
                en: 'Slots per side',
                de: 'Plaetze pro Seite',
                pl: 'Miejsca na strone',
            },
            slotsCaption: {
                ru: 'Участников',
                ua: 'Учасників',
                en: 'Slots',
                de: 'Plaetze',
                pl: 'Miejsca',
            },
            caliberLabel: {
                ru: 'Выбор калибра оружия',
                ua: 'Вибір калібру зброї',
                en: 'Weapon caliber',
                de: 'Waffenkaliber',
                pl: 'Kaliber broni',
            },
            caliberCaption: {
                ru: 'Калибр',
                ua: 'Калібр',
                en: 'Caliber',
                de: 'Kaliber',
                pl: 'Kaliber',
            },
            orgMembers: {
                ru: 'Участники организации',
                ua: 'Учасники організації',
                en: 'Organization members',
                de: 'Mitglieder der Organisation',
                pl: 'Czlonkowie organizacji',
            },
            captMembers: {
                ru: 'Участники капта',
                ua: 'Учасники капту',
                en: 'Capture roster',
                de: 'Angriffstrupp',
                pl: 'Sklad ataku',
            },
            clickToAdd: {
                ru: 'кликните для добавления',
                ua: 'клікніть, щоб додати',
                en: 'click to add',
                de: 'Klick zum Hinzufuegen',
                pl: 'kliknij, aby dodac',
            },
            clickToRemove: {
                ru: 'кликните для удаления',
                ua: 'клікніть, щоб видалити',
                en: 'click to remove',
                de: 'Klick zum Entfernen',
                pl: 'kliknij, aby usunac',
            },
            search: {
                ru: 'Поиск по списку',
                ua: 'Пошук по списку',
                en: 'Search list',
                de: 'Liste durchsuchen',
                pl: 'Szukaj na liscie',
            },
            colName: {
                ru: 'Имя Фамилия',
                ua: 'Імя Прізвище',
                en: 'Name Surname',
                de: 'Name Nachname',
                pl: 'Imie Nazwisko',
            },
            colRank: {
                ru: 'Ранг',
                ua: 'Ранг',
                en: 'Rank',
                de: 'Rang',
                pl: 'Ranga',
            },
            colStatus: {
                ru: 'Статус в сети',
                ua: 'Статус у мережі',
                en: 'Online status',
                de: 'Online-Status',
                pl: 'Status online',
            },
            online: {
                ru: 'В игре',
                ua: 'У грі',
                en: 'Online',
                de: 'Im Spiel',
                pl: 'W grze',
            },
            empty: {
                ru: 'Подходящих участников нет',
                ua: 'Відповідних учасників немає',
                en: 'No matching members',
                de: 'Keine passenden Mitglieder',
                pl: 'Brak pasujacych czlonkow',
            },
            captEmpty: {
                ru: 'Слоты пустые, добавьте участников из списка слева',
                ua: 'Слоти порожні, додайте учасників зі списку зліва',
                en: 'Roster empty, add members from the list on the left',
                de: 'Trupp leer, fuege Mitglieder von links hinzu',
                pl: 'Sklad pusty, dodaj czlonkow z listy po lewej',
            },
        },
    },
    settings: {
        cancel: {
            ru: 'Отмена',
            ua: 'Скасувати',
            en: 'Cancel',
            de: 'Abbrechen',
            pl: 'Anuluj',
        },
        processing: {
            ru: 'Обработка...',
            ua: 'Обробка...',
            en: 'Processing...',
            de: 'Wird verarbeitet...',
            pl: 'Przetwarzanie...',
        },
        leaderOnly: {
            ru: 'Изменения доступны только лидеру организации',
            ua: 'Зміни доступні лише лідеру організації',
            en: 'Only the leader can change these settings',
            de: 'Nur der Anfuehrer kann diese Einstellungen aendern',
            pl: 'Tylko lider moze zmieniac te ustawienia',
        },
        logo: {
            title: {
                ru: 'Логотип',
                ua: 'Логотип',
                en: 'Logo',
                de: 'Logo',
                pl: 'Logo',
            },
            subtitle: {
                ru: 'Замена доступна раз в {{days}} дней',
                ua: 'Заміна доступна раз на {{days}} днів',
                en: 'Replacement allowed once every {{days}} days',
                de: 'Wechsel alle {{days}} Tage erlaubt',
                pl: 'Zmiana raz na {{days}} dni',
            },
            action: {
                ru: 'Выбрать файл',
                ua: 'Обрати файл',
                en: 'Choose file',
                de: 'Datei waehlen',
                pl: 'Wybierz plik',
            },
            actionReplace: {
                ru: 'Выбрать другой',
                ua: 'Обрати інший',
                en: 'Choose another',
                de: 'Anderes waehlen',
                pl: 'Wybierz inny',
            },
            apply: {
                ru: 'Сменить логотип',
                ua: 'Змінити логотип',
                en: 'Change logo',
                de: 'Logo aendern',
                pl: 'Zmien logo',
            },
            uploading: {
                ru: 'Загрузка...',
                ua: 'Завантаження...',
                en: 'Uploading...',
                de: 'Wird hochgeladen...',
                pl: 'Przesylanie...',
            },
            available: {
                ru: 'Доступно',
                ua: 'Доступно',
                en: 'Available',
                de: 'Verfuegbar',
                pl: 'Dostepne',
            },
            cooldownDays: {
                ru: 'Через {{count}} дн',
                ua: 'Через {{count}} дн',
                en: 'In {{count}} d',
                de: 'In {{count}} T',
                pl: 'Za {{count}} d',
            },
            cooldownHours: {
                ru: 'Через {{count}} ч',
                ua: 'Через {{count}} год',
                en: 'In {{count}} h',
                de: 'In {{count}} Std',
                pl: 'Za {{count}} godz',
            },
            cooldownMinutes: {
                ru: 'Через {{count}} мин',
                ua: 'Через {{count}} хв',
                en: 'In {{count}} min',
                de: 'In {{count}} Min',
                pl: 'Za {{count}} min',
            },
            hint: {
                ru: 'PNG, AVIF или WEBP, до {{mb}} КБ. Без анимаций.',
                ua: 'PNG, AVIF чи WEBP, до {{mb}} КБ. Без анімацій.',
                en: 'PNG, AVIF or WEBP, up to {{mb}} KB. No animations.',
                de: 'PNG, AVIF oder WEBP, bis zu {{mb}} KB. Keine Animationen.',
                pl: 'PNG, AVIF lub WEBP, do {{mb}} KB. Bez animacji.',
            },
            errors: {
                invalidFormat: {
                    ru: 'Неподдерживаемый формат файла',
                    ua: 'Непідтримуваний формат файлу',
                    en: 'Unsupported file format',
                    de: 'Nicht unterstuetztes Dateiformat',
                    pl: 'Nieobslugiwany format pliku',
                },
                tooLarge: {
                    ru: 'Файл слишком большой',
                    ua: 'Файл занадто великий',
                    en: 'File is too large',
                    de: 'Datei ist zu gross',
                    pl: 'Plik jest zbyt duzy',
                },
                invalidLogoSize: {
                    ru: 'Файл слишком большой',
                    ua: 'Файл занадто великий',
                    en: 'File is too large',
                    de: 'Datei ist zu gross',
                    pl: 'Plik jest zbyt duzy',
                },
                invalidLogoFormat: {
                    ru: 'Неподдерживаемый формат файла',
                    ua: 'Непідтримуваний формат файлу',
                    en: 'Unsupported file format',
                    de: 'Nicht unterstuetztes Dateiformat',
                    pl: 'Nieobslugiwany format pliku',
                },
                logoOnCooldown: {
                    ru: 'Логотип уже менялся недавно',
                    ua: 'Логотип уже змінювали нещодавно',
                    en: 'Logo was changed recently',
                    de: 'Logo wurde kuerzlich geaendert',
                    pl: 'Logo bylo niedawno zmieniane',
                },
                invalidLogo: {
                    ru: 'Не удалось обработать изображение',
                    ua: 'Не вдалося обробити зображення',
                    en: 'Failed to process the image',
                    de: 'Bild konnte nicht verarbeitet werden',
                    pl: 'Nie udalo sie przetworzyc obrazu',
                },
                invalidLogoToken: {
                    ru: 'Сессия загрузки истекла',
                    ua: 'Сесія завантаження минула',
                    en: 'Upload session expired',
                    de: 'Upload-Sitzung abgelaufen',
                    pl: 'Sesja wysylki wygasla',
                },
                noPermission: {
                    ru: 'Только лидер может менять логотип',
                    ua: 'Лише лідер може змінювати логотип',
                    en: 'Only the leader can change the logo',
                    de: 'Nur der Anfuehrer darf das Logo aendern',
                    pl: 'Tylko lider moze zmienic logo',
                },
                invalidPayload: {
                    ru: 'Некорректный запрос',
                    ua: 'Некоректний запит',
                    en: 'Invalid request',
                    de: 'Ungueltige Anfrage',
                    pl: 'Nieprawidlowe zapytanie',
                },
                antispam: {
                    ru: 'Слишком часто, попробуйте позже',
                    ua: 'Занадто часто, спробуйте пізніше',
                    en: 'Too often, try again later',
                    de: 'Zu oft, spaeter erneut versuchen',
                    pl: 'Zbyt czesto, sprobuj pozniej',
                },
                unavailable: {
                    ru: 'Сервис временно недоступен',
                    ua: 'Сервіс тимчасово недоступний',
                    en: 'Service temporarily unavailable',
                    de: 'Dienst voruebergehend nicht verfuegbar',
                    pl: 'Usluga chwilowo niedostepna',
                },
            },
        },
        name: {
            title: {
                ru: 'Название и тэг',
                ua: 'Назва і тег',
                en: 'Name & tag',
                de: 'Name und Tag',
                pl: 'Nazwa i tag',
            },
            subtitle: {
                ru: 'Уникальное название и короткий тэг',
                ua: 'Унікальна назва та короткий тег',
                en: 'A unique name and a short tag',
                de: 'Eindeutiger Name und kurzer Tag',
                pl: 'Unikalna nazwa i krotki tag',
            },
            label: {
                ru: 'Новое название',
                ua: 'Нова назва',
                en: 'New name',
                de: 'Neuer Name',
                pl: 'Nowa nazwa',
            },
            placeholder: {
                ru: 'Введите название',
                ua: 'Введіть назву',
                en: 'Enter a name',
                de: 'Name eingeben',
                pl: 'Wpisz nazwe',
            },
            tagLabel: {
                ru: 'Тэг',
                ua: 'Тег',
                en: 'Tag',
                de: 'Tag',
                pl: 'Tag',
            },
            tagPlaceholder: {
                ru: 'TAG',
                ua: 'TAG',
                en: 'TAG',
                de: 'TAG',
                pl: 'TAG',
            },
            apply: {
                ru: 'Применить',
                ua: 'Застосувати',
                en: 'Apply',
                de: 'Anwenden',
                pl: 'Zastosuj',
            },
            errors: {
                required: {
                    ru: 'Введите название',
                    ua: 'Введіть назву',
                    en: 'Enter a name',
                    de: 'Name eingeben',
                    pl: 'Wpisz nazwe',
                },
                tooShort: {
                    ru: 'Название слишком короткое',
                    ua: 'Назва занадто коротка',
                    en: 'Name is too short',
                    de: 'Name ist zu kurz',
                    pl: 'Nazwa jest zbyt krotka',
                },
                tooLong: {
                    ru: 'Название слишком длинное',
                    ua: 'Назва занадто довга',
                    en: 'Name is too long',
                    de: 'Name ist zu lang',
                    pl: 'Nazwa jest zbyt dluga',
                },
                invalidName: {
                    ru: 'Недопустимое название',
                    ua: 'Недопустима назва',
                    en: 'Invalid name',
                    de: 'Ungueltiger Name',
                    pl: 'Niedozwolona nazwa',
                },
                nameTaken: {
                    ru: 'Название уже занято',
                    ua: 'Назва вже зайнята',
                    en: 'Name is already taken',
                    de: 'Name ist bereits vergeben',
                    pl: 'Nazwa jest juz zajeta',
                },
                tagRequired: {
                    ru: 'Введите тэг',
                    ua: 'Введіть тег',
                    en: 'Enter a tag',
                    de: 'Tag eingeben',
                    pl: 'Wpisz tag',
                },
                tagTooShort: {
                    ru: 'Тэг слишком короткий',
                    ua: 'Тег занадто короткий',
                    en: 'Tag is too short',
                    de: 'Tag ist zu kurz',
                    pl: 'Tag jest zbyt krotki',
                },
                tagTooLong: {
                    ru: 'Тэг слишком длинный',
                    ua: 'Тег занадто довгий',
                    en: 'Tag is too long',
                    de: 'Tag ist zu lang',
                    pl: 'Tag jest zbyt dlugi',
                },
                tagInvalidCharacters: {
                    ru: 'В тэге только латинские буквы',
                    ua: 'У тегу лише латинські літери',
                    en: 'Tag must use latin letters only',
                    de: 'Tag nur mit lateinischen Buchstaben',
                    pl: 'Tag tylko z lacinskich liter',
                },
                invalidTag: {
                    ru: 'Недопустимый тэг',
                    ua: 'Недопустимий тег',
                    en: 'Invalid tag',
                    de: 'Ungueltiger Tag',
                    pl: 'Niedozwolony tag',
                },
                tagTaken: {
                    ru: 'Тэг уже занят',
                    ua: 'Тег вже зайнятий',
                    en: 'Tag is already taken',
                    de: 'Tag ist bereits vergeben',
                    pl: 'Tag jest juz zajety',
                },
                sameValue: {
                    ru: 'Эти значения уже установлены',
                    ua: 'Ці значення вже встановлені',
                    en: 'These values are already set',
                    de: 'Diese Werte sind bereits gesetzt',
                    pl: 'Te wartosci sa juz ustawione',
                },
                insufficientCoins: {
                    ru: 'Недостаточно Olymp-Coin',
                    ua: 'Недостатньо Olymp-Coin',
                    en: 'Not enough Olymp Coins',
                    de: 'Nicht genug Olymp-Coin',
                    pl: 'Za malo Olymp-Coin',
                },
                noPermission: {
                    ru: 'Только лидер может менять название',
                    ua: 'Лише лідер може змінювати назву',
                    en: 'Only the leader can change the name',
                    de: 'Nur der Anfuehrer darf den Namen aendern',
                    pl: 'Tylko lider moze zmienic nazwe',
                },
                invalidPayload: {
                    ru: 'Некорректный запрос',
                    ua: 'Некоректний запит',
                    en: 'Invalid request',
                    de: 'Ungueltige Anfrage',
                    pl: 'Nieprawidlowe zapytanie',
                },
                antispam: {
                    ru: 'Слишком часто, попробуйте позже',
                    ua: 'Занадто часто, спробуйте пізніше',
                    en: 'Too often, try again later',
                    de: 'Zu oft, spaeter erneut versuchen',
                    pl: 'Zbyt czesto, sprobuj pozniej',
                },
                unavailable: {
                    ru: 'Сервис временно недоступен',
                    ua: 'Сервіс тимчасово недоступний',
                    en: 'Service temporarily unavailable',
                    de: 'Dienst voruebergehend nicht verfuegbar',
                    pl: 'Usluga chwilowo niedostepna',
                },
            },
        },
        colors: {
            title: {
                ru: 'Цвета',
                ua: 'Кольори',
                en: 'Colors',
                de: 'Farben',
                pl: 'Kolory',
            },
            subtitle: {
                ru: 'Основной цвет и цвет в HUD',
                ua: 'Основний колір та колір у HUD',
                en: 'Main color and HUD color',
                de: 'Hauptfarbe und HUD-Farbe',
                pl: 'Glowny kolor i kolor HUD',
            },
            mainLabel: {
                ru: 'Основной цвет',
                ua: 'Основний колір',
                en: 'Main color',
                de: 'Hauptfarbe',
                pl: 'Glowny kolor',
            },
            hudLabel: {
                ru: 'Цвет в HUD',
                ua: 'Колір у HUD',
                en: 'HUD color',
                de: 'HUD-Farbe',
                pl: 'Kolor HUD',
            },
            apply: {
                ru: 'Сменить цвета',
                ua: 'Змінити кольори',
                en: 'Change colors',
                de: 'Farben aendern',
                pl: 'Zmien kolory',
            },
            errors: {
                invalidColor: {
                    ru: 'Цвет недоступен в палитре',
                    ua: 'Колір недоступний у палітрі',
                    en: 'Color is not in the palette',
                    de: 'Farbe nicht in der Palette',
                    pl: 'Kolor poza paleta',
                },
                sameValue: {
                    ru: 'Цвета не изменились',
                    ua: 'Кольори не змінилися',
                    en: 'Colors did not change',
                    de: 'Farben sind unveraendert',
                    pl: 'Kolory bez zmian',
                },
                insufficientCoins: {
                    ru: 'Недостаточно Olymp-Coin',
                    ua: 'Недостатньо Olymp-Coin',
                    en: 'Not enough Olymp Coins',
                    de: 'Nicht genug Olymp-Coin',
                    pl: 'Za malo Olymp-Coin',
                },
                noPermission: {
                    ru: 'Только лидер может менять цвета',
                    ua: 'Лише лідер може змінювати кольори',
                    en: 'Only the leader can change the colors',
                    de: 'Nur der Anfuehrer darf die Farben aendern',
                    pl: 'Tylko lider moze zmieniac kolory',
                },
                invalidPayload: {
                    ru: 'Некорректный запрос',
                    ua: 'Некоректний запит',
                    en: 'Invalid request',
                    de: 'Ungueltige Anfrage',
                    pl: 'Nieprawidlowe zapytanie',
                },
                antispam: {
                    ru: 'Слишком часто, попробуйте позже',
                    ua: 'Занадто часто, спробуйте пізніше',
                    en: 'Too often, try again later',
                    de: 'Zu oft, spaeter erneut versuchen',
                    pl: 'Zbyt czesto, sprobuj pozniej',
                },
                unavailable: {
                    ru: 'Сервис временно недоступен',
                    ua: 'Сервіс тимчасово недоступний',
                    en: 'Service temporarily unavailable',
                    de: 'Dienst voruebergehend nicht verfuegbar',
                    pl: 'Usluga chwilowo niedostepna',
                },
            },
        },
        errors: {
            forbidden: {
                ru: 'Действие недоступно',
                ua: 'Дія недоступна',
                en: 'Action is not available',
                de: 'Aktion nicht verfuegbar',
                pl: 'Akcja niedostepna',
            },
            noPermission: {
                ru: 'Только лидер может менять настройки',
                ua: 'Тільки лідер може змінювати налаштування',
                en: 'Only the leader can change these settings',
                de: 'Nur der Anfuehrer kann das aendern',
                pl: 'Tylko lider moze to zmieniac',
            },
            invalidPayload: {
                ru: 'Некорректный запрос',
                ua: 'Некоректний запит',
                en: 'Invalid request',
                de: 'Ungueltige Anfrage',
                pl: 'Nieprawidlowe zapytanie',
            },
            invalidName: {
                ru: 'Недопустимое название',
                ua: 'Недопустима назва',
                en: 'Invalid name',
                de: 'Ungueltiger Name',
                pl: 'Niedozwolona nazwa',
            },
            nameTaken: {
                ru: 'Название уже занято',
                ua: 'Назва вже зайнята',
                en: 'Name is already taken',
                de: 'Name ist bereits vergeben',
                pl: 'Nazwa juz zajeta',
            },
            invalidColor: {
                ru: 'Цвет недоступен в палитре',
                ua: 'Колір недоступний у палітрі',
                en: 'Color is not in the palette',
                de: 'Farbe nicht in der Palette',
                pl: 'Kolor poza paleta',
            },
            sameValue: {
                ru: 'Значение не изменилось',
                ua: 'Значення не змінилося',
                en: 'Value did not change',
                de: 'Wert ist unveraendert',
                pl: 'Wartosc bez zmian',
            },
            logoOnCooldown: {
                ru: 'Логотип уже менялся недавно',
                ua: 'Логотип уже змінювали нещодавно',
                en: 'Logo was changed recently',
                de: 'Logo wurde kuerzlich geaendert',
                pl: 'Logo bylo niedawno zmieniane',
            },
            invalidLogo: {
                ru: 'Не удалось обработать изображение',
                ua: 'Не вдалося обробити зображення',
                en: 'Failed to process the image',
                de: 'Bild konnte nicht verarbeitet werden',
                pl: 'Nie udalo sie przetworzyc obrazu',
            },
            invalidLogoFormat: {
                ru: 'Неподдерживаемый формат файла',
                ua: 'Непідтримуваний формат файлу',
                en: 'Unsupported file format',
                de: 'Nicht unterstuetztes Dateiformat',
                pl: 'Nieobslugiwany format pliku',
            },
            invalidLogoSize: {
                ru: 'Файл слишком большой',
                ua: 'Файл занадто великий',
                en: 'File is too large',
                de: 'Datei ist zu gross',
                pl: 'Plik jest zbyt duzy',
            },
            insufficientCoins: {
                ru: 'Недостаточно Olymp-Coin',
                ua: 'Недостатньо Olymp-Coin',
                en: 'Not enough Olymp Coins',
                de: 'Nicht genug Olymp-Coin',
                pl: 'Za malo Olymp-Coin',
            },
            unavailable: {
                ru: 'Сервис временно недоступен',
                ua: 'Сервіс тимчасово недоступний',
                en: 'Service temporarily unavailable',
                de: 'Dienst voruebergehend nicht verfuegbar',
                pl: 'Usluga chwilowo niedostepna',
            },
        },
        notify: {
            nameChanged: {
                ru: 'Название изменено на «{{name}}»',
                ua: 'Назву змінено на «{{name}}»',
                en: 'Name changed to "{{name}}"',
                de: 'Name geaendert in «{{name}}»',
                pl: 'Nazwa zmieniona na «{{name}}»',
            },
            colorsChanged: {
                ru: 'Цвета организации обновлены',
                ua: 'Кольори організації оновлено',
                en: 'Organization colors updated',
                de: 'Organisationsfarben aktualisiert',
                pl: 'Kolory organizacji zaktualizowane',
            },
            logoChanged: {
                ru: 'Логотип организации обновлён',
                ua: 'Логотип організації оновлено',
                en: 'Organization logo updated',
                de: 'Organisationslogo aktualisiert',
                pl: 'Logo organizacji zaktualizowane',
            },
        },
    },
};
