export const permissions = {
    categories: {
        core: {
            ru: 'Основные',
            ua: 'Основні',
            en: 'Core',
            de: 'Allgemein',
            pl: 'Podstawowe',
        },
        gameplay: {
            ru: 'Игровые',
            ua: 'Ігрові',
            en: 'Gameplay',
            de: 'Spielweise',
            pl: 'Rozgrywka',
        },
        assets: {
            ru: 'Имущество',
            ua: 'Майно',
            en: 'Assets',
            de: 'Eigentum',
            pl: 'Majątek',
        },
        base: {
            ru: 'База',
            ua: 'База',
            en: 'Base',
            de: 'Basis',
            pl: 'Baza',
        },
    },
    labels: {
        leader: {
            ru: 'Лидер',
            ua: 'Лідер',
            en: 'Leader',
            de: 'Anführer',
            pl: 'Lider',
        },
        invite: {
            ru: 'Приглашать в организацию',
            ua: 'Запрошувати в організацію',
            en: 'Invite to organization',
            de: 'In die Organisation einladen',
            pl: 'Zapraszać do organizacji',
        },
        kick: {
            ru: 'Исключать из организации',
            ua: 'Виключати з організації',
            en: 'Kick from organization',
            de: 'Aus der Organisation entfernen',
            pl: 'Wyrzucać z organizacji',
        },
        manageRanks: {
            ru: 'Управление рангами',
            ua: 'Керування рангами',
            en: 'Manage ranks',
            de: 'Ränge verwalten',
            pl: 'Zarządzanie rangami',
        },
        manageProperties: {
            ru: 'Управление имуществом',
            ua: 'Керування майном',
            en: 'Manage properties',
            de: 'Eigentum verwalten',
            pl: 'Zarządzanie majątkiem',
        },
        manageSalaries: {
            ru: 'Управление зарплатами',
            ua: 'Керування зарплатами',
            en: 'Manage salaries',
            de: 'Gehälter verwalten',
            pl: 'Zarządzanie wypłatami',
        },
        manageBank: {
            ru: 'Управление банком',
            ua: 'Керування банком',
            en: 'Manage bank',
            de: 'Bank verwalten',
            pl: 'Zarządzanie bankiem',
        },
        viewFullStats: {
            ru: 'Видеть полную статистику',
            ua: 'Бачити повну статистику',
            en: 'View full statistics',
            de: 'Volle Statistik einsehen',
            pl: 'Pełna statystyka',
        },
        takePersonalContracts: {
            ru: 'Брать личные контракты',
            ua: 'Брати особисті контракти',
            en: 'Take personal contracts',
            de: 'Persönliche Aufträge annehmen',
            pl: 'Brać osobiste kontrakty',
        },
        takeFamilyContracts: {
            ru: 'Брать семейные контракты',
            ua: 'Брати сімейні контракти',
            en: 'Take family contracts',
            de: 'Familienaufträge annehmen',
            pl: 'Brać rodzinne kontrakty',
        },
        participateInWars: {
            ru: 'Участвовать в каптах',
            ua: 'Брати участь у каптах',
            en: 'Participate in wars',
            de: 'An Kriegen teilnehmen',
            pl: 'Brać udział w wojnach',
        },
        manageWars: {
            ru: 'Управление войнами',
            ua: 'Керування війнами',
            en: 'Manage wars',
            de: 'Kriege verwalten',
            pl: 'Zarządzanie wojnami',
        },
        enterprisesAccess: {
            ru: 'Доступ к предприятиям',
            ua: 'Доступ до підприємств',
            en: 'Access to enterprises',
            de: 'Zugang zu Betrieben',
            pl: 'Dostęp do przedsiębiorstw',
        },
        familyTransport: {
            ru: 'Доступ к семейному транспорту',
            ua: 'Доступ до сімейного транспорту',
            en: 'Access to family vehicles',
            de: 'Zugang zu Familienfahrzeugen',
            pl: 'Dostęp do rodzinnych pojazdów',
        },
        safeOffice: {
            ru: 'Сейф офиса',
            ua: 'Сейф офісу',
            en: 'Office safe',
            de: 'Bürotresor',
            pl: 'Sejf biura',
        },
        warehouseAccess: {
            ru: 'Полный доступ к складу',
            ua: 'Повний доступ до складу',
            en: 'Full warehouse access',
            de: 'Vollzugriff auf Lager',
            pl: 'Pełny dostęp do magazynu',
        },
        warehouseDeposit: {
            ru: 'Класть на склад',
            ua: 'Класти на склад',
            en: 'Deposit to warehouse',
            de: 'Im Lager einlagern',
            pl: 'Dodawać do magazynu',
        },
        workshop: {
            ru: 'Воркшоп HQ',
            ua: 'Воркшоп HQ',
            en: 'HQ workshop',
            de: 'HQ-Werkstatt',
            pl: 'Warsztat HQ',
        },
        safeHQ: {
            ru: 'Сейф HQ',
            ua: 'Сейф HQ',
            en: 'HQ safe',
            de: 'HQ-Tresor',
            pl: 'Sejf HQ',
        },
        lock: {
            ru: 'Запирать дверь HQ',
            ua: 'Замикати двері HQ',
            en: 'Lock HQ door',
            de: 'HQ-Tür abschließen',
            pl: 'Zamykać drzwi HQ',
        },
        storage: {
            ru: 'Хранилище HQ',
            ua: 'Сховище HQ',
            en: 'HQ storage',
            de: 'HQ-Lager',
            pl: 'Magazyn HQ',
        },
        parkingSlots: {
            ru: 'Парковка HQ и офиса',
            ua: 'Паркування HQ та офісу',
            en: 'HQ and office parking',
            de: 'HQ- und Büroparkplatz',
            pl: 'Parking HQ i biura',
        },
        buyUpgrades: {
            ru: 'Покупка апгрейдов',
            ua: 'Купівля апгрейдів',
            en: 'Buy upgrades',
            de: 'Upgrades kaufen',
            pl: 'Kupować ulepszenia',
        },
        enterEditor: {
            ru: 'Редактор мебели',
            ua: 'Редактор меблів',
            en: 'Furniture editor',
            de: 'Möbel-Editor',
            pl: 'Edytor mebli',
        },
        deleteFurniture: {
            ru: 'Удалять мебель',
            ua: 'Видаляти меблі',
            en: 'Delete furniture',
            de: 'Möbel entfernen',
            pl: 'Usuwać meble',
        },
        kickPlayersInEditor: {
            ru: 'Выгонять из редактора',
            ua: 'Виганяти з редактора',
            en: 'Kick players from editor',
            de: 'Spieler aus dem Editor entfernen',
            pl: 'Wyrzucać z edytora',
        },
    },
};
