export const territories = {
    notify: {
        header: {
            ru: 'Территории',
            ua: 'Території',
            en: 'Territories',
            de: 'Territorien',
            pl: 'Terytoria',
        },
        errors: {
            noOrg: {
                ru: 'Вы не состоите в организации',
                ua: 'Ви не перебуваєте в організації',
                en: 'You are not in an organization',
                de: 'Du bist in keiner Organisation',
                pl: 'Nie nalezysz do organizacji',
            },
            noPermission: {
                ru: 'Недостаточно прав ранга',
                ua: 'Недостатньо прав рангу',
                en: 'Rank permission denied',
                de: 'Keine Rangberechtigung',
                pl: 'Brak uprawnien rangi',
            },
            frozen: {
                ru: 'Захваты территорий заморожены администрацией',
                ua: 'Захоплення територій заморожені адміністрацією',
                en: 'Captures are frozen by the administration',
                de: 'Eroberungen sind von der Verwaltung eingefroren',
                pl: 'Przejmowania sa zamrozone przez administracje',
            },
            ownCell: {
                ru: 'Этот квадрат уже принадлежит вам',
                ua: 'Цей квадрат уже належить вам',
                en: 'This square already belongs to you',
                de: 'Dieses Feld gehoert bereits dir',
                pl: 'To pole juz nalezy do Ciebie',
            },
            unknownSquare: {
                ru: 'Квадрат не найден',
                ua: 'Квадрат не знайдено',
                en: 'Square not found',
                de: 'Feld nicht gefunden',
                pl: 'Pole nie znalezione',
            },
            alreadyUnderAttack: {
                ru: 'Квадрат уже находится под атакой',
                ua: 'Квадрат уже атакують',
                en: 'Square is already under attack',
                de: 'Feld wird bereits angegriffen',
                pl: 'Pole jest juz atakowane',
            },
            noAdminLevel: {
                ru: 'Требуется уровень администратора 4+',
                ua: 'Потрібен рівень адміністратора 4+',
                en: 'Admin level 4+ required',
                de: 'Adminstufe 4+ erforderlich',
                pl: 'Wymagany poziom administratora 4+',
            },
            unknownOrg: {
                ru: 'Организация не найдена',
                ua: 'Організацію не знайдено',
                en: 'Organization not found',
                de: 'Organisation nicht gefunden',
                pl: 'Nie znaleziono organizacji',
            },
            captureCooldown: {
                ru: 'Захват доступен через {{minutes}} мин',
                ua: 'Захоплення доступне через {{minutes}} хв',
                en: 'Capture available in {{minutes}} min',
                de: 'Eroberung in {{minutes}} Min. verfuegbar',
                pl: 'Przejecie dostepne za {{minutes}} min',
            },
            warNotImplemented: {
                ru: 'Война за занятый квадрат в разработке. Скоро будет доступна',
                ua: 'Війна за зайнятий квадрат у розробці. Невдовзі буде доступна',
                en: 'War over occupied squares is in development',
                de: 'Krieg um besetzte Felder ist in Entwicklung',
                pl: 'Wojna o zajete pola jest w opracowaniu',
            },
        },
        capture: {
            success: {
                ru: 'Квадрат {{cell}} захвачен мирно',
                ua: 'Квадрат {{cell}} захоплено мирно',
                en: 'Square {{cell}} captured peacefully',
                de: 'Feld {{cell}} friedlich erobert',
                pl: 'Pole {{cell}} przejete pokojowo',
            },
        },
        attack: {
            started: {
                ru: 'Атака начата',
                ua: 'Атаку розпочато',
                en: 'Attack started',
                de: 'Angriff gestartet',
                pl: 'Atak rozpoczety',
            },
            incoming: {
                ru: 'Организация {{tag}} атакует ваш квадрат {{cell}}',
                ua: 'Організація {{tag}} атакує ваш квадрат {{cell}}',
                en: 'Organization {{tag}} is attacking your square {{cell}}',
                de: 'Organisation {{tag}} greift dein Feld {{cell}} an',
                pl: 'Organizacja {{tag}} atakuje twoje pole {{cell}}',
            },
            victory: {
                ru: 'Атака на {{cell}} успешна',
                ua: 'Атака на {{cell}} успішна',
                en: 'Attack on {{cell}} succeeded',
                de: 'Angriff auf {{cell}} erfolgreich',
                pl: 'Atak na {{cell}} powiodl sie',
            },
            defeat: {
                ru: 'Атака на {{cell}} провалена',
                ua: 'Атаку на {{cell}} провалено',
                en: 'Attack on {{cell}} failed',
                de: 'Angriff auf {{cell}} fehlgeschlagen',
                pl: 'Atak na {{cell}} nieudany',
            },
        },
        defense: {
            held: {
                ru: 'Квадрат {{cell}} удержан',
                ua: 'Квадрат {{cell}} утримано',
                en: 'Square {{cell}} held',
                de: 'Feld {{cell}} verteidigt',
                pl: 'Pole {{cell}} utrzymane',
            },
            lost: {
                ru: 'Квадрат {{cell}} потерян',
                ua: 'Квадрат {{cell}} втрачено',
                en: 'Square {{cell}} lost',
                de: 'Feld {{cell}} verloren',
                pl: 'Pole {{cell}} utracone',
            },
        },
        admin: {
            painted: {
                ru: 'Квадрат перекрашен',
                ua: 'Квадрат перефарбовано',
                en: 'Square repainted',
                de: 'Feld neu eingefaerbt',
                pl: 'Pole przemalowane',
            },
        },
    },
};
