const STATIC_NODES = {
    opportunities: {
        ru: 'Возможности',
        ua: 'Можливості',
        en: 'Opportunities',
        de: 'Moeglichkeiten',
        pl: 'Mozliwosci',
    },
    territoryControl: {
        ru: 'Контроль территорий',
        ua: 'Контроль територій',
        en: 'Territory control',
        de: 'Gebietskontrolle',
        pl: 'Kontrola terytoriow',
    },
    playerRobbery: {
        ru: 'Ограбление игроков',
        ua: 'Пограбування гравців',
        en: 'Player robbery',
        de: 'Spielerueberfaelle',
        pl: 'Napady na graczy',
    },
    illegalContracts: {
        ru: 'Нелегальные контракты',
        ua: 'Нелегальні контракти',
        en: 'Illegal contracts',
        de: 'Illegale Vertraege',
        pl: 'Nielegalne kontrakty',
    },
    legalContracts: {
        ru: 'Легальные контракты',
        ua: 'Легальні контракти',
        en: 'Legal contracts',
        de: 'Legale Vertraege',
        pl: 'Legalne kontrakty',
    },
    illegalJobs: {
        ru: 'Нелегальная подработка',
        ua: 'Нелегальна підробка',
        en: 'Illegal side jobs',
        de: 'Illegale Nebenjobs',
        pl: 'Nielegalne dorywcze',
    },
    robBusiness: { ru: 'Ограбление бизнеса', ua: 'Пограбування бізнесу', en: 'Business robbery', de: 'Geschaeftsueberfaelle', pl: 'Napady na biznesy' },
    robBank: { ru: 'Ограбление банка', ua: 'Пограбування банку', en: 'Bank robbery', de: 'Bankueberfaelle', pl: 'Napad na bank' },
    robMilitary: { ru: 'Ограбление военной базы', ua: 'Пограбування військової бази', en: 'Military base raid', de: 'Militaerbasis-Raubzug', pl: 'Napad na baze wojskowa' },
    robIsland: { ru: 'Ограбление острова', ua: 'Пограбування острова', en: 'Island heist', de: 'Insel-Raubzug', pl: 'Napad na wyspe' },
    armorStrip: { ru: 'Срезание бронежилета', ua: 'Зрізання бронежилета', en: 'Armor stripping', de: 'Westen-Klau', pl: 'Zerwanie kamizelki' },
    cashSum1: { ru: '+$8000 к сумме', ua: '+$8000 до суми', en: '+$8000 to payout', de: '+$8000 Auszahlung', pl: '+$8000 do wyplaty' },
    cashSum2: { ru: '+$16000 к сумме', ua: '+$16000 до суми', en: '+$16000 to payout', de: '+$16000 Auszahlung', pl: '+$16000 do wyplaty' },
    cashSum3: { ru: '+$24000 к сумме', ua: '+$24000 до суми', en: '+$24000 to payout', de: '+$24000 Auszahlung', pl: '+$24000 do wyplaty' },
    cashSum4: { ru: '+$32000 к сумме', ua: '+$32000 до суми', en: '+$32000 to payout', de: '+$32000 Auszahlung', pl: '+$32000 do wyplaty' },
    cashSum5: { ru: '+$40000 к сумме', ua: '+$40000 до суми', en: '+$40000 to payout', de: '+$40000 Auszahlung', pl: '+$40000 do wyplaty' },
};

const STATIC_DESCRIPTIONS = {
    opportunities: {
        ru: 'Категория ключевых возможностей организации.',
        ua: 'Категорія ключових можливостей організації.',
        en: 'Category of core organization opportunities.',
        de: 'Kategorie der zentralen Org-Moeglichkeiten.',
        pl: 'Kategoria kluczowych mozliwosci organizacji.',
    },
    territoryControl: {
        ru: 'Открывает участие в боях за территории.',
        ua: 'Відкриває участь у боях за території.',
        en: 'Unlocks territory war participation.',
        de: 'Schaltet Teilnahme an Gebietskaempfen frei.',
        pl: 'Odblokowuje udzial w walkach o terytoria.',
    },
    playerRobbery: {
        ru: 'Разрешает грабить игроков.',
        ua: 'Дозволяє грабувати гравців.',
        en: 'Allows robbing players.',
        de: 'Erlaubt Spielerueberfaelle.',
        pl: 'Pozwala napadac na graczy.',
    },
    illegalContracts: {
        ru: 'Раздел нелегальных контрактов организации.',
        ua: 'Розділ нелегальних контрактів організації.',
        en: 'Illegal contracts section.',
        de: 'Bereich illegale Vertraege.',
        pl: 'Sekcja nielegalnych kontraktow.',
    },
    legalContracts: {
        ru: 'Раздел легальных контрактов организации.',
        ua: 'Розділ легальних контрактів організації.',
        en: 'Legal contracts section.',
        de: 'Bereich legale Vertraege.',
        pl: 'Sekcja legalnych kontraktow.',
    },
    illegalJobs: {
        ru: 'Раздел нелегальной подработки.',
        ua: 'Розділ нелегальної підробки.',
        en: 'Illegal side jobs section.',
        de: 'Bereich illegale Nebenjobs.',
        pl: 'Sekcja nielegalnych dorywczych.',
    },
    robBusiness: { ru: 'Разрешает грабить игровые бизнесы.', ua: 'Дозволяє грабувати ігрові бізнеси.', en: 'Allows robbing in-game businesses.', de: 'Erlaubt Geschaeftsueberfaelle.', pl: 'Pozwala napadac na biznesy.' },
    robBank: { ru: 'Разрешает грабить банк.', ua: 'Дозволяє грабувати банк.', en: 'Allows robbing the bank.', de: 'Erlaubt Bankueberfaelle.', pl: 'Pozwala napadac na bank.' },
    robMilitary: { ru: 'Разрешает грабить военную базу.', ua: 'Дозволяє грабувати військову базу.', en: 'Allows raiding the military base.', de: 'Erlaubt Militaerbasis-Raubzug.', pl: 'Pozwala napadac na baze wojskowa.' },
    robIsland: { ru: 'Разрешает грабить остров.', ua: 'Дозволяє грабувати острів.', en: 'Allows the island heist.', de: 'Erlaubt Insel-Raubzug.', pl: 'Pozwala napadac na wyspe.' },
    armorStrip: { ru: 'Разрешает срезать бронежилеты у ограбленных игроков.', ua: 'Дозволяє зрізати бронежилети у пограбованих гравців.', en: 'Allows stripping armor from robbed players.', de: 'Erlaubt das Stehlen von Westen.', pl: 'Pozwala zerwac kamizelki napadnietym graczom.' },
    cashSum1: { ru: 'Добавляет $8000 к выплате за ограбление игроков.', ua: 'Додає $8000 до виплати за пограбування гравців.', en: 'Adds $8000 to player robbery payout.', de: 'Fuegt $8000 zur Auszahlung hinzu.', pl: 'Dodaje $8000 do wyplaty.' },
    cashSum2: { ru: 'Добавляет $16000 к выплате.', ua: 'Додає $16000 до виплати.', en: 'Adds $16000 to the payout.', de: 'Fuegt $16000 zur Auszahlung hinzu.', pl: 'Dodaje $16000 do wyplaty.' },
    cashSum3: { ru: 'Добавляет $24000 к выплате.', ua: 'Додає $24000 до виплати.', en: 'Adds $24000 to the payout.', de: 'Fuegt $24000 zur Auszahlung hinzu.', pl: 'Dodaje $24000 do wyplaty.' },
    cashSum4: { ru: 'Добавляет $32000 к выплате.', ua: 'Додає $32000 до виплати.', en: 'Adds $32000 to the payout.', de: 'Fuegt $32000 zur Auszahlung hinzu.', pl: 'Dodaje $32000 do wyplaty.' },
    cashSum5: { ru: 'Добавляет $40000 к выплате.', ua: 'Додає $40000 до виплати.', en: 'Adds $40000 to the payout.', de: 'Fuegt $40000 zur Auszahlung hinzu.', pl: 'Dodaje $40000 do wyplaty.' },
};

// Reusable templates for repeating nodes. Catalog points to these via shared keys
// `organizations.tree.shared.<id>.name|description`. Contract-derived names get composed
// at resolve-time inside `resolveTreeNodeName/Description` from `contracts.list.<id>.name`.
const SHARED = {
    memberSlots: {
        name: { ru: '+10 участников', ua: '+10 учасників', en: '+10 members', de: '+10 Mitglieder', pl: '+10 czlonkow' },
        description: { ru: 'Увеличивает максимальный состав на 10.', ua: 'Збільшує максимальний склад на 10.', en: 'Increases member cap by 10.', de: 'Erhoeht die Mitgliederkapazitaet um 10.', pl: 'Zwieksza pojemnosc czlonkow o 10.' },
    },
    armorChance: {
        name: { ru: '+10% к шансу', ua: '+10% до шансу', en: '+10% chance', de: '+10% Chance', pl: '+10% szansy' },
        description: { ru: 'Увеличивает шанс срезания брони на 10%.', ua: 'Збільшує шанс зрізання броні на 10%.', en: 'Increases armor strip chance by 10%.', de: 'Erhoeht die Westen-Chance um 10%.', pl: 'Zwieksza szanse zerwania kamizelki o 10%.' },
    },
    bizSum: {
        name: { ru: '+20% к сумме', ua: '+20% до суми', en: '+20% to payout', de: '+20% Auszahlung', pl: '+20% wyplaty' },
        description: { ru: 'Увеличивает выплату за ограбление бизнеса на 20%.', ua: 'Збільшує виплату за пограбування бізнесу на 20%.', en: 'Increases business robbery payout by 20%.', de: 'Erhoeht die Auszahlung um 20%.', pl: 'Zwieksza wyplate z napadu o 20%.' },
    },
    contractTier: {
        name: { ru: 'Контракт', ua: 'Контракт', en: 'Contract', de: 'Vertrag', pl: 'Kontrakt' },
        description: {
            ru: 'Усиливает контракт «{{name}}» (уровень {{level}}).',
            ua: 'Підсилює контракт «{{name}}» (рівень {{level}}).',
            en: 'Boosts the "{{name}}" contract (tier {{level}}).',
            de: 'Verstaerkt den Vertrag "{{name}}" (Stufe {{level}}).',
            pl: 'Wzmacnia kontrakt "{{name}}" (poziom {{level}}).',
        },
    },
    contractUnlock: {
        name: { ru: 'Открыть контракт', ua: 'Відкрити контракт', en: 'Unlock contract', de: 'Vertrag freischalten', pl: 'Odblokuj kontrakt' },
        description: {
            ru: 'Открывает контракт «{{name}}».',
            ua: 'Відкриває контракт «{{name}}».',
            en: 'Unlocks the "{{name}}" contract.',
            de: 'Schaltet den Vertrag "{{name}}" frei.',
            pl: 'Odblokowuje kontrakt "{{name}}".',
        },
    },
    jobTier: {
        name: { ru: 'Работа', ua: 'Робота', en: 'Job', de: 'Job', pl: 'Praca' },
        description: {
            ru: 'Открывает уровень {{level}} работы «{{name}}».',
            ua: 'Відкриває рівень {{level}} роботи «{{name}}».',
            en: 'Unlocks tier {{level}} of the "{{name}}" job.',
            de: 'Schaltet Stufe {{level}} des Jobs "{{name}}" frei.',
            pl: 'Odblokowuje poziom {{level}} pracy "{{name}}".',
        },
    },
    jobUnlock: {
        name: { ru: 'Открыть работу', ua: 'Відкрити роботу', en: 'Unlock job', de: 'Job freischalten', pl: 'Odblokuj prace' },
        description: {
            ru: 'Открывает работу «{{name}}».',
            ua: 'Відкриває роботу «{{name}}».',
            en: 'Unlocks the "{{name}}" job.',
            de: 'Schaltet den Job "{{name}}" frei.',
            pl: 'Odblokowuje prace "{{name}}".',
        },
    },
};

const nodes = {};
for (const id of Object.keys(STATIC_NODES)) {
    nodes[id] = {
        name: STATIC_NODES[id],
        description: STATIC_DESCRIPTIONS[id],
    };
}

export const tree = {
    shared: SHARED,
    notify: {
        header: {
            ru: 'Дерево улучшений',
            ua: 'Дерево покращень',
            en: 'Upgrade tree',
            de: 'Upgrade-Baum',
            pl: 'Drzewo ulepszen',
        },
        broadcast: {
            unlock: {
                ru: 'Орга разблокировала узел дерева: {{name}} (от {{by}}).',
                ua: 'Організація розблокувала вузол дерева: {{name}} (від {{by}}).',
                en: 'Organization unlocked tree node: {{name}} (by {{by}}).',
                de: 'Organisation hat Knoten freigeschaltet: {{name}} (von {{by}}).',
                pl: 'Organizacja odblokowala wezel drzewa: {{name}} (przez {{by}}).',
            },
            unlockStarted: {
                ru: 'Запущено улучшение: {{name}} (от {{by}}).',
                ua: 'Запущено покращення: {{name}} (від {{by}}).',
                en: 'Upgrade started: {{name}} (by {{by}}).',
                de: 'Upgrade gestartet: {{name}} (von {{by}}).',
                pl: 'Rozpoczeto ulepszenie: {{name}} (przez {{by}}).',
            },
            unlockComplete: {
                ru: 'Улучшение завершено: {{name}}.',
                ua: 'Покращення завершено: {{name}}.',
                en: 'Upgrade complete: {{name}}.',
                de: 'Upgrade abgeschlossen: {{name}}.',
                pl: 'Ulepszenie ukonczone: {{name}}.',
            },
        },
    },
    branches: {
        legal: { ru: 'Легальная', ua: 'Легальна', en: 'Legal', de: 'Legal', pl: 'Legalna' },
        neutral: { ru: 'Нейтральная', ua: 'Нейтральна', en: 'Neutral', de: 'Neutral', pl: 'Neutralna' },
        crime: { ru: 'Криминальная', ua: 'Кримінальна', en: 'Crime', de: 'Crime', pl: 'Kryminalna' },
    },
    entry: {
        unlocked: { ru: 'РАЗБЛОКИРОВАНО', ua: 'РОЗБЛОКОВАНО', en: 'UNLOCKED', de: 'FREIGESCHALTET', pl: 'ODBLOKOWANO' },
        available: { ru: 'ДОСТУПНО', ua: 'ДОСТУПНО', en: 'AVAILABLE', de: 'VERFUEGBAR', pl: 'DOSTEPNE' },
        locked: { ru: 'ЗАБЛОКИРОВАНО', ua: 'ЗАБЛОКОВАНО', en: 'LOCKED', de: 'GESPERRT', pl: 'ZABLOKOWANE' },
    },
    usage: {
        ru: 'Использование: /tree <list|info|unlock> [nodeId]',
        ua: 'Використання: /tree <list|info|unlock> [nodeId]',
        en: 'Usage: /tree <list|info|unlock> [nodeId]',
        de: 'Verwendung: /tree <list|info|unlock> [nodeId]',
        pl: 'Uzycie: /tree <list|info|unlock> [nodeId]',
    },
    list: {
        header: {
            ru: 'Дерево улучшений (направление орги: {{direction}}):',
            ua: 'Дерево покращень (напрям орги: {{direction}}):',
            en: 'Upgrade tree (organization direction: {{direction}}):',
            de: 'Upgrade-Baum (Org-Richtung: {{direction}}):',
            pl: 'Drzewo ulepszen (kierunek org: {{direction}}):',
        },
        branchHeader: {
            ru: '!{#cccccc}--- {{branch}} ---',
            ua: '!{#cccccc}--- {{branch}} ---',
            en: '!{#cccccc}--- {{branch}} ---',
            de: '!{#cccccc}--- {{branch}} ---',
            pl: '!{#cccccc}--- {{branch}} ---',
        },
        entry: {
            ru: '!{#7ad07a}[{{id}}] {{name}} | {{branch}} | ур.{{level}} | ${{money}} | {{status}}',
            ua: '!{#7ad07a}[{{id}}] {{name}} | {{branch}} | р.{{level}} | ${{money}} | {{status}}',
            en: '!{#7ad07a}[{{id}}] {{name}} | {{branch}} | lvl {{level}} | ${{money}} | {{status}}',
            de: '!{#7ad07a}[{{id}}] {{name}} | {{branch}} | Stufe {{level}} | ${{money}} | {{status}}',
            pl: '!{#7ad07a}[{{id}}] {{name}} | {{branch}} | poz.{{level}} | ${{money}} | {{status}}',
        },
        footer: {
            ru: 'Подробнее: /tree info <id>. Купить: /tree unlock <id>.',
            ua: 'Детальніше: /tree info <id>. Купити: /tree unlock <id>.',
            en: 'Details: /tree info <id>. Buy: /tree unlock <id>.',
            de: 'Details: /tree info <id>. Kaufen: /tree unlock <id>.',
            pl: 'Szczegoly: /tree info <id>. Kup: /tree unlock <id>.',
        },
    },
    info: {
        header: {
            ru: '!{#cccccc}{{name}} ({{branch}}) - {{status}}',
            ua: '!{#cccccc}{{name}} ({{branch}}) - {{status}}',
            en: '!{#cccccc}{{name}} ({{branch}}) - {{status}}',
            de: '!{#cccccc}{{name}} ({{branch}}) - {{status}}',
            pl: '!{#cccccc}{{name}} ({{branch}}) - {{status}}',
        },
        description: {
            ru: '{{text}}',
            ua: '{{text}}',
            en: '{{text}}',
            de: '{{text}}',
            pl: '{{text}}',
        },
        requirementLevel: {
            ru: ' - Уровень орги: {{current}}/{{required}}',
            ua: ' - Рівень орги: {{current}}/{{required}}',
            en: ' - Org level: {{current}}/{{required}}',
            de: ' - Org-Stufe: {{current}}/{{required}}',
            pl: ' - Poziom org: {{current}}/{{required}}',
        },
        requirementRepMin: {
            ru: ' - Репутация минимум: {{current}}/{{required}}',
            ua: ' - Репутація мінімум: {{current}}/{{required}}',
            en: ' - Reputation min: {{current}}/{{required}}',
            de: ' - Reputation min: {{current}}/{{required}}',
            pl: ' - Reputacja min: {{current}}/{{required}}',
        },
        requirementRepMax: {
            ru: ' - Репутация максимум: {{current}}/{{required}}',
            ua: ' - Репутація максимум: {{current}}/{{required}}',
            en: ' - Reputation max: {{current}}/{{required}}',
            de: ' - Reputation max: {{current}}/{{required}}',
            pl: ' - Reputacja max: {{current}}/{{required}}',
        },
        requirementContractsTotal: {
            ru: ' - Контрактов всего: {{current}}/{{required}}',
            ua: ' - Контрактів усього: {{current}}/{{required}}',
            en: ' - Contracts total: {{current}}/{{required}}',
            de: ' - Vertraege gesamt: {{current}}/{{required}}',
            pl: ' - Kontrakty lacznie: {{current}}/{{required}}',
        },
        requirementContractsLegal: {
            ru: ' - Легальных контрактов: {{current}}/{{required}}',
            ua: ' - Легальних контрактів: {{current}}/{{required}}',
            en: ' - Legal contracts: {{current}}/{{required}}',
            de: ' - Legale Vertraege: {{current}}/{{required}}',
            pl: ' - Legalne kontrakty: {{current}}/{{required}}',
        },
        requirementContractsCrime: {
            ru: ' - Крайм-контрактов: {{current}}/{{required}}',
            ua: ' - Крайм-контрактів: {{current}}/{{required}}',
            en: ' - Crime contracts: {{current}}/{{required}}',
            de: ' - Crime-Vertraege: {{current}}/{{required}}',
            pl: ' - Kontrakty kryminalne: {{current}}/{{required}}',
        },
        requirementMoney: {
            ru: ' - Казна орги: ${{current}}/${{required}}',
            ua: ' - Казна орги: ${{current}}/${{required}}',
            en: ' - Org treasury: ${{current}}/${{required}}',
            de: ' - Org-Kasse: ${{current}}/${{required}}',
            pl: ' - Skarbiec org: ${{current}}/${{required}}',
        },
        requirementItem: {
            ru: ' - Предмет: {{itemId}} x{{quantity}}',
            ua: ' - Предмет: {{itemId}} x{{quantity}}',
            en: ' - Item: {{itemId}} x{{quantity}}',
            de: ' - Gegenstand: {{itemId}} x{{quantity}}',
            pl: ' - Przedmiot: {{itemId}} x{{quantity}}',
        },
        prerequisites: {
            ru: ' - Требуются разблокированные узлы: {{list}}',
            ua: ' - Потрібні розблоковані вузли: {{list}}',
            en: ' - Required unlocked nodes: {{list}}',
            de: ' - Benoetigte freigeschaltete Knoten: {{list}}',
            pl: ' - Wymagane odblokowane wezly: {{list}}',
        },
    },
    success: {
        nodeUnlocked: {
            ru: 'Узел дерева разблокирован: {{name}}.',
            ua: 'Вузол дерева розблоковано: {{name}}.',
            en: 'Tree node unlocked: {{name}}.',
            de: 'Baum-Knoten freigeschaltet: {{name}}.',
            pl: 'Wezel drzewa odblokowany: {{name}}.',
        },
        nodeUnlockStarted: {
            ru: 'Запущено улучшение: {{name}}.',
            ua: 'Запущено покращення: {{name}}.',
            en: 'Upgrade started: {{name}}.',
            de: 'Upgrade gestartet: {{name}}.',
            pl: 'Rozpoczeto ulepszenie: {{name}}.',
        },
    },
    errors: {
        notInGame: {
            ru: 'Сначала войдите в игру.',
            ua: 'Спочатку увійдіть у гру.',
            en: 'You must be in-game first.',
            de: 'Du musst zuerst im Spiel sein.',
            pl: 'Najpierw wejdz do gry.',
        },
        notInOrg: {
            ru: 'Вы не состоите в организации.',
            ua: 'Ви не перебуваєте в організації.',
            en: 'You are not in an organization.',
            de: 'Du bist in keiner Organisation.',
            pl: 'Nie nalezysz do organizacji.',
        },
        noPermission: {
            ru: 'Ваш ранг не имеет права покупать улучшения.',
            ua: 'Ваш ранг не має права купувати покращення.',
            en: 'Your rank cannot buy upgrades.',
            de: 'Dein Rang darf keine Upgrades kaufen.',
            pl: 'Twoja ranga nie moze kupowac ulepszen.',
        },
        unknownNode: {
            ru: 'Неизвестный узел дерева.',
            ua: 'Невідомий вузол дерева.',
            en: 'Unknown tree node.',
            de: 'Unbekannter Baum-Knoten.',
            pl: 'Nieznany wezel drzewa.',
        },
        alreadyPending: {
            ru: 'Этот узел уже разблокируется.',
            ua: 'Цей вузол вже розблоковується.',
            en: 'This node is already unlocking.',
            de: 'Dieser Knoten wird bereits freigeschaltet.',
            pl: 'Ten wezel jest juz odblokowywany.',
        },
        alreadyUnlocked: {
            ru: 'Этот узел уже разблокирован.',
            ua: 'Цей вузол вже розблоковано.',
            en: 'This node is already unlocked.',
            de: 'Dieser Knoten ist bereits freigeschaltet.',
            pl: 'Ten wezel jest juz odblokowany.',
        },
        prerequisiteMissing: {
            ru: 'Требуется разблокировать сначала: {{list}}.',
            ua: 'Потрібно спочатку розблокувати: {{list}}.',
            en: 'Requires unlocking first: {{list}}.',
            de: 'Erst freischalten: {{list}}.',
            pl: 'Wymaga najpierw odblokowania: {{list}}.',
        },
        branchLockedLegal: {
            ru: 'Ветка заблокирована: уже куплены легальные узлы.',
            ua: 'Гілка заблокована: вже придбані легальні вузли.',
            en: 'Branch locked: legal nodes already purchased.',
            de: 'Zweig gesperrt: Legale Knoten bereits gekauft.',
            pl: 'Galaz zablokowana: legalne wezly juz zakupione.',
        },
        branchLockedCrime: {
            ru: 'Ветка заблокирована: уже куплены крайм-узлы.',
            ua: 'Гілка заблокована: вже придбані крайм-вузли.',
            en: 'Branch locked: crime nodes already purchased.',
            de: 'Zweig gesperrt: Crime-Knoten bereits gekauft.',
            pl: 'Galaz zablokowana: kryminalne wezly juz zakupione.',
        },
        insufficientLevel: {
            ru: 'Недостаточный уровень орги: {{current}}/{{required}}.',
            ua: 'Недостатній рівень орги: {{current}}/{{required}}.',
            en: 'Insufficient org level: {{current}}/{{required}}.',
            de: 'Org-Stufe zu niedrig: {{current}}/{{required}}.',
            pl: 'Niewystarczajacy poziom org: {{current}}/{{required}}.',
        },
        insufficientReputation: {
            ru: 'Недостаточная репутация: {{current}}/{{required}}.',
            ua: 'Недостатня репутація: {{current}}/{{required}}.',
            en: 'Insufficient reputation: {{current}}/{{required}}.',
            de: 'Reputation zu niedrig: {{current}}/{{required}}.',
            pl: 'Niewystarczajaca reputacja: {{current}}/{{required}}.',
        },
        missingContracts: {
            total: {
                ru: 'Недостаточно завершённых контрактов: {{current}}/{{required}}.',
                ua: 'Недостатньо завершених контрактів: {{current}}/{{required}}.',
                en: 'Not enough completed contracts: {{current}}/{{required}}.',
                de: 'Nicht genug abgeschlossene Vertraege: {{current}}/{{required}}.',
                pl: 'Za malo wykonanych kontraktow: {{current}}/{{required}}.',
            },
            legal: {
                ru: 'Недостаточно легальных контрактов: {{current}}/{{required}}.',
                ua: 'Недостатньо легальних контрактів: {{current}}/{{required}}.',
                en: 'Not enough legal contracts: {{current}}/{{required}}.',
                de: 'Nicht genug legale Vertraege: {{current}}/{{required}}.',
                pl: 'Za malo legalnych kontraktow: {{current}}/{{required}}.',
            },
            crime: {
                ru: 'Недостаточно крайм-контрактов: {{current}}/{{required}}.',
                ua: 'Недостатньо крайм-контрактів: {{current}}/{{required}}.',
                en: 'Not enough crime contracts: {{current}}/{{required}}.',
                de: 'Nicht genug Crime-Vertraege: {{current}}/{{required}}.',
                pl: 'Za malo kryminalnych kontraktow: {{current}}/{{required}}.',
            },
        },
        insufficientFunds: {
            ru: 'Недостаточно средств в казне орги: ${{current}}/${{required}}.',
            ua: 'Недостатньо коштів у казні орги: ${{current}}/${{required}}.',
            en: 'Insufficient org treasury: ${{current}}/${{required}}.',
            de: 'Org-Kasse nicht ausreichend: ${{current}}/${{required}}.',
            pl: 'Niewystarczajacy skarbiec org: ${{current}}/${{required}}.',
        },
        hqMissing: {
            ru: 'У орги не привязан HQ-дом.',
            ua: 'У орги не прив\'язаний HQ-будинок.',
            en: 'Organization has no HQ house linked.',
            de: 'Organisation hat kein HQ-Haus verknuepft.',
            pl: 'Organizacja nie ma przypisanego domu HQ.',
        },
        missingItems: {
            ru: 'Не хватает предметов в шкафах HQ: {{list}}.',
            ua: 'Не вистачає предметів у шафах HQ: {{list}}.',
            en: 'Missing items in HQ cabinets: {{list}}.',
            de: 'Fehlende Gegenstaende in HQ-Schraenken: {{list}}.',
            pl: 'Brak przedmiotow w szafach HQ: {{list}}.',
        },
        furnitureLocked: {
            ru: 'Объект «{{furniture}}» ещё не разблокирован в дереве улучшений.',
            ua: 'Об\'єкт «{{furniture}}» ще не розблоковано у дереві покращень.',
            en: 'Object "{{furniture}}" not yet unlocked in upgrade tree.',
            de: 'Objekt "{{furniture}}" im Upgrade-Baum nicht freigeschaltet.',
            pl: 'Obiekt "{{furniture}}" nie odblokowany w drzewie ulepszen.',
        },
    },
    labels: {
        illegalContracts: {
            ru: 'Нелегальные контракты',
            ua: 'Нелегальні контракти',
            en: 'Illegal contracts',
            de: 'Illegale Vertraege',
            pl: 'Nielegalne kontrakty',
        },
        legalContracts: {
            ru: 'Легальные контракты',
            ua: 'Легальні контракти',
            en: 'Legal contracts',
            de: 'Legale Vertraege',
            pl: 'Legalne kontrakty',
        },
    },
    panel: {
        selectNode: {
            ru: 'Выберите узел дерева',
            ua: 'Виберіть вузол дерева',
            en: 'Select a tree node',
            de: 'Knoten auswaehlen',
            pl: 'Wybierz wezel drzewa',
        },
        selectNodeHint: {
            ru: 'Кликните по узлу на холсте, чтобы увидеть требования и эффекты.',
            ua: 'Клікніть по вузлу на полотні, щоб побачити вимоги й ефекти.',
            en: 'Click any node on the canvas to inspect its requirements and effect.',
            de: 'Klicke auf einen Knoten, um Anforderungen und Effekt zu sehen.',
            pl: 'Kliknij wezel na kanwie, aby zobaczyc wymagania i efekt.',
        },
        effect: { ru: 'Эффект', ua: 'Ефект', en: 'Effect', de: 'Effekt', pl: 'Efekt' },
        requirements: { ru: 'Требования', ua: 'Вимоги', en: 'Requirements', de: 'Anforderungen', pl: 'Wymagania' },
        prereqs: { ru: 'Предусловия', ua: 'Передумови', en: 'Prerequisites', de: 'Voraussetzungen', pl: 'Wymagania wstepne' },
        orgLevel: { ru: 'Уровень орги', ua: 'Рівень орги', en: 'Org level', de: 'Org-Stufe', pl: 'Poziom org' },
        reputation: { ru: 'Репутация', ua: 'Репутація', en: 'Reputation', de: 'Reputation', pl: 'Reputacja' },
        contractsTotal: { ru: 'Контракты всего', ua: 'Контракти усього', en: 'Contracts total', de: 'Vertraege gesamt', pl: 'Kontrakty lacznie' },
        contractsLegal: { ru: 'Легальные контракты', ua: 'Легальні контракти', en: 'Legal contracts', de: 'Legale Vertraege', pl: 'Legalne kontrakty' },
        contractsCrime: { ru: 'Крайм-контракты', ua: 'Крайм-контракти', en: 'Crime contracts', de: 'Crime-Vertraege', pl: 'Kontrakty kryminalne' },
        money: { ru: 'Казна', ua: 'Казна', en: 'Treasury', de: 'Kasse', pl: 'Skarbiec' },
        item: { ru: 'Предмет', ua: 'Предмет', en: 'Item', de: 'Gegenstand', pl: 'Przedmiot' },
        unlock: { ru: 'Разблокировать', ua: 'Розблокувати', en: 'Unlock', de: 'Freischalten', pl: 'Odblokuj' },
        alreadyUnlocked: { ru: 'Уже разблокировано', ua: 'Вже розблоковано', en: 'Already unlocked', de: 'Bereits freigeschaltet', pl: 'Juz odblokowane' },
        noPermission: { ru: 'Нет прав на покупку', ua: 'Немає прав на купівлю', en: 'No permission', de: 'Keine Berechtigung', pl: 'Brak uprawnien' },
        requirementsNotMet: { ru: 'Требования не выполнены', ua: 'Вимоги не виконано', en: 'Requirements not met', de: 'Anforderungen nicht erfuellt', pl: 'Wymagania nie spelnione' },
        requirementsTitle: { ru: 'Требования к разблокировке', ua: 'Вимоги до розблокування', en: 'Unlock requirements', de: 'Freischaltungsanforderungen', pl: 'Wymagania do odblokowania' },
        priceTitle: { ru: 'Цена улучшения', ua: 'Ціна покращення', en: 'Upgrade price', de: 'Upgrade-Preis', pl: 'Cena ulepszenia' },
        timeTitle: { ru: 'Время улучшения', ua: 'Час покращення', en: 'Upgrade time', de: 'Upgrade-Zeit', pl: 'Czas ulepszenia' },
        instant: { ru: 'Мгновенно', ua: 'Миттєво', en: 'Instant', de: 'Sofort', pl: 'Natychmiast' },
        inProgress: { ru: 'В процессе', ua: 'У процесi', en: 'In progress', de: 'In Bearbeitung', pl: 'W toku' },
        timeRemaining: { ru: 'Осталось', ua: 'Залишилось', en: 'Remaining', de: 'Verbleibend', pl: 'Pozostalo' },
    },
    duration: {
        seconds: { ru: '{{value}}с', ua: '{{value}}с', en: '{{value}}s', de: '{{value}}s', pl: '{{value}}s' },
        minutes: { ru: '{{value}}м', ua: '{{value}}хв', en: '{{value}}m', de: '{{value}}m', pl: '{{value}}m' },
        hours: { ru: '{{value}}ч', ua: '{{value}}год', en: '{{value}}h', de: '{{value}}h', pl: '{{value}}g' },
        days: { ru: '{{value}}д', ua: '{{value}}д', en: '{{value}}d', de: '{{value}}t', pl: '{{value}}d' },
    },
    nodes,
};
