/**
 * Планировщик войны со стороны организации. Ключи повторяют контракт общего
 * компонента (`webviews/src/components/warPlanner`) - тот же набор, что у банд
 * в `faction/warPlanner.js`, но своими словами: у организаций квадрат, а не
 * зона, и атака, а не капт.
 */
export const warPlanner = {
    title: {
        ru: 'Объявление атаки',
        ua: 'Оголошення атаки',
        en: 'Declare attack',
        de: 'Angriff ankündigen',
        pl: 'Ogłoszenie ataku',
    },
    declare: {
        ru: 'Объявить атаку',
        ua: 'Оголосити атаку',
        en: 'Declare attack',
        de: 'Angriff ankündigen',
        pl: 'Ogłoś atak',
    },
    // Тот же планировщик со стороны обороны: время и условия задал атакующий,
    // защитники выбирают только людей.
    defenseTitle: {
        ru: 'Состав на оборону',
        ua: 'Склад на оборону',
        en: 'Defense roster',
        de: 'Verteidigungsaufstellung',
        pl: 'Skład do obrony',
    },
    defenseSubmit: {
        ru: 'Сохранить состав',
        ua: 'Зберегти склад',
        en: 'Save the roster',
        de: 'Aufstellung speichern',
        pl: 'Zapisz skład',
    },
    close: {
        ru: 'Закрыть',
        ua: 'Закрити',
        en: 'Close',
        de: 'Schliessen',
        pl: 'Zamknij',
    },
    square: {
        ru: 'Квадрат',
        ua: 'Квадрат',
        en: 'Square',
        de: 'Sektor',
        pl: 'Kwadrat',
    },
    prizeLevel: {
        ru: 'влияния за уровень {{level}}',
        ua: 'впливу за рівень {{level}}',
        en: 'influence at level {{level}}',
        de: 'Einfluss auf Stufe {{level}}',
        pl: 'wplywow za poziom {{level}}',
    },
    prizeFortified: {
        ru: 'квадрат укреплён',
        ua: 'квадрат укріплений',
        en: 'fortified',
        de: 'befestigt',
        pl: 'umocnione',
    },
    hour: {
        ru: 'Час',
        ua: 'Година',
        en: 'Hour',
        de: 'Stunde',
        pl: 'Godzina',
    },
    minute: {
        ru: 'Минута',
        ua: 'Хвилина',
        en: 'Minute',
        de: 'Minute',
        pl: 'Minuta',
    },
    now: {
        ru: 'сейчас',
        ua: 'зараз',
        en: 'now',
        de: 'jetzt',
        pl: 'teraz',
    },
    startsIn: {
        ru: 'через',
        ua: 'через',
        en: 'in',
        de: 'in',
        pl: 'za',
    },
    slots: {
        ru: 'Состав',
        ua: 'Ростер',
        en: 'Roster',
        de: 'Aufstellung',
        pl: 'Sklad',
    },
    picked: {
        ru: 'отобрано',
        ua: 'відібрано',
        en: 'picked',
        de: 'gewaehlt',
        pl: 'wybrano',
    },
    // Причина, по которой кнопка объявления погашена.
    blocked: {
        noRoster: {
            ru: 'Не выбраны участники',
            ua: 'Не обрано учасників',
            en: 'No members picked',
            de: 'Keine Mitglieder gewaehlt',
            pl: 'Nie wybrano uczestnikow',
        },
        tooFew: {
            ru: 'Нужно не меньше {{count}} участников',
            ua: 'Потрібно щонайменше {{count}} учасників',
            en: 'At least {{count}} members needed',
            de: 'Mindestens {{count}} Mitglieder noetig',
            pl: 'Potrzeba co najmniej {{count}} uczestnikow',
        },
        tooMany: {
            ru: 'Участников больше, чем мест',
            ua: 'Учасників більше, ніж місць',
            en: 'More members than slots',
            de: 'Mehr Mitglieder als Plaetze',
            pl: 'Wiecej uczestnikow niz miejsc',
        },
        equipment: {
            ru: 'Не выбрано снаряжение',
            ua: 'Не обрано спорядження',
            en: 'Equipment not selected',
            de: 'Ausruestung nicht gewaehlt',
            pl: 'Nie wybrano wyposazenia',
        },
        time: {
            ru: 'Время начала уже недоступно',
            ua: 'Час початку вже недоступний',
            en: 'That start time is no longer available',
            de: 'Diese Startzeit ist nicht mehr verfuegbar',
            pl: 'Ta godzina rozpoczecia jest juz niedostepna',
        },
        notWarTime: {
            ru: 'Время вне окна боёв',
            ua: 'Час поза вікном боїв',
            en: 'Outside the battle window',
            de: 'Ausserhalb des Kampffensters',
            pl: 'Poza oknem walk',
        },
        declarationsClosed: {
            ru: 'Объявления сейчас закрыты',
            ua: 'Оголошення зараз закриті',
            en: 'Declarations are closed right now',
            de: 'Ansagen sind derzeit geschlossen',
            pl: 'Zgloszenia sa teraz zamkniete',
        },
        leadTooShort: {
            ru: 'Слишком скоро: бой назначают заранее',
            ua: 'Занадто скоро: бій призначають заздалегідь',
            en: 'Too soon: a battle needs notice',
            de: 'Zu frueh: ein Kampf braucht Vorlauf',
            pl: 'Za wczesnie: walka wymaga wyprzedzenia',
        },
    },
    allowedItems: {
        ru: 'Разрешено в бою',
        ua: 'Дозволено в бою',
        en: 'Allowed in battle',
        de: 'Im Kampf erlaubt',
        pl: 'Dozwolone w walce',
    },
    equipment: {
        ru: 'Снаряжение',
        ua: 'Спорядження',
        en: 'Equipment',
        de: 'Ausruestung',
        pl: 'Wyposazenie',
    },
    gear: {
        ru: 'Экипировка',
        ua: 'Екіпірування',
        en: 'Gear',
        de: 'Ausstattung',
        pl: 'Sprzet',
    },
    back: {
        ru: 'Назад',
        ua: 'Назад',
        en: 'Back',
        de: 'Zurueck',
        pl: 'Wstecz',
    },
    chosen: {
        ru: 'оружия',
        ua: 'зброї',
        en: 'weapons',
        de: 'Waffen',
        pl: 'broni',
    },
    equipmentTitle: {
        ru: 'Выбор снаряжения',
        ua: 'Вибір спорядження',
        en: 'Equipment selection',
        de: 'Ausruestungsauswahl',
        pl: 'Wybor wyposazenia',
    },
    equipmentDesc: {
        ru: 'Выбранное снаряжение будет доступно в бою обеим сторонам.',
        ua: 'Обране спорядження буде доступне в бою обом сторонам.',
        en: 'The selected equipment will be available during the battle for both sides.',
        de: 'Die gewaehlte Ausruestung steht im Kampf beiden Seiten zur Verfuegung.',
        pl: 'Wybrane wyposazenie bedzie dostepne w walce dla obu stron.',
    },
    slotBanned: {
        ru: 'Этот тип оружия на бою запрещён',
        ua: 'Цей тип зброї на бою заборонений',
        en: 'This weapon type is banned in the battle',
        de: 'Dieser Waffentyp ist im Kampf verboten',
        pl: 'Ten typ broni jest zabroniony w walce',
    },
    roster: {
        available: {
            ru: 'Состав организации',
            ua: 'Склад організації',
            en: 'Organization members',
            de: 'Organisationsmitglieder',
            pl: 'Czlonkowie organizacji',
        },
        picked: {
            ru: 'Идут на бой',
            ua: 'Йдуть у бій',
            en: 'Going to battle',
            de: 'Nehmen am Kampf teil',
            pl: 'Idą do walki',
        },
        clickToAdd: {
            ru: 'нажмите, чтобы добавить',
            ua: 'натисніть, щоб додати',
            en: 'click to add',
            de: 'klicken zum Hinzufuegen',
            pl: 'kliknij, aby dodac',
        },
        clickToRemove: {
            ru: 'нажмите, чтобы убрать',
            ua: 'натисніть, щоб прибрати',
            en: 'click to remove',
            de: 'klicken zum Entfernen',
            pl: 'kliknij, aby usunac',
        },
        search: {
            ru: 'Поиск по имени или рангу',
            ua: 'Пошук за іменем або рангом',
            en: 'Search by name or rank',
            de: 'Suche nach Name oder Rang',
            pl: 'Szukaj po imieniu lub randze',
        },
        loading: {
            ru: 'Загрузка',
            ua: 'Завантаження',
            en: 'Loading',
            de: 'Laedt',
            pl: 'Wczytywanie',
        },
        empty: {
            ru: 'Никого не найдено',
            ua: 'Нікого не знайдено',
            en: 'Nobody found',
            de: 'Niemand gefunden',
            pl: 'Nikogo nie znaleziono',
        },
        pickedEmpty: {
            ru: 'Выберите, кто пойдёт на бой',
            ua: 'Оберіть, хто піде в бій',
            en: 'Pick who goes to the battle',
            de: 'Wähle aus, wer am Kampf teilnimmt',
            pl: 'Wybierz, kto idzie do walki',
        },
    },
};
