export const warsLobby = {
    lobby: {
        title: {
            ru: 'Лобби капта',
            ua: 'Лобі бою',
            en: 'War lobby',
            de: 'Kriegs-Lobby',
            pl: 'Lobby wojny',
        },
        waitingForStart: {
            ru: 'Ожидание начала пик-бана',
            ua: 'Очікування початку пік-бана',
            en: 'Waiting for pick-ban to start',
            de: 'Warten auf Pick-Ban-Start',
            pl: 'Czekanie na rozpoczecie pick-ban',
        },
        cancel: {
            ru: 'Отменить капт',
            ua: 'Скасувати бій',
            en: 'Cancel war',
            de: 'Krieg abbrechen',
            pl: 'Anuluj wojne',
        },
        openPool: {
            ru: 'Открыть пул',
            ua: 'Відкрити пул',
            en: 'Open pool',
            de: 'Pool oeffnen',
            pl: 'Otworz sklad',
        },
        bottomDock: {
            roster: {
                ru: 'Состав',
                ua: 'Склад',
                en: 'Roster',
                de: 'Kader',
                pl: 'Sklad',
            },
            cancel: {
                ru: 'Отменить',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
        },
        gridLabel: {
            ru: 'Грид',
            ua: 'Грід',
            en: 'Grid',
            de: 'Grid',
            pl: 'Grid',
        },
        countdownCaption: {
            waiting: {
                ru: 'До начала',
                ua: 'До початку',
                en: 'To start',
                de: 'Bis Start',
                pl: 'Do startu',
            },
            turn: {
                ru: 'Ход',
                ua: 'Хід',
                en: 'Turn',
                de: 'Zug',
                pl: 'Tura',
            },
            starting: {
                ru: 'Старт',
                ua: 'Старт',
                en: 'Start',
                de: 'Start',
                pl: 'Start',
            },
        },
        sideShort: {
            attacker: {
                ru: 'АТК',
                ua: 'АТК',
                en: 'ATK',
                de: 'ATK',
                pl: 'ATK',
            },
            defender: {
                ru: 'ЗАЩ',
                ua: 'ЗАХ',
                en: 'DEF',
                de: 'DEF',
                pl: 'OBR',
            },
        },
        inLobby: {
            ru: 'В лобби',
            ua: 'У лобі',
            en: 'In lobby',
            de: 'In Lobby',
            pl: 'W lobby',
        },
        rosterLabel: {
            ru: 'Состав',
            ua: 'Склад',
            en: 'Roster',
            de: 'Kader',
            pl: 'Sklad',
        },
        targetLabel: {
            ru: 'Цель',
            ua: 'Ціль',
            en: 'Target',
            de: 'Ziel',
            pl: 'Cel',
        },
        emptyCandidates: {
            ru: 'Нет онлайн-кандидатов',
            ua: 'Немає кандидатів онлайн',
            en: 'No online candidates',
            de: 'Keine Online-Kandidaten',
            pl: 'Brak kandydatow online',
        },
        header: {
            waiting: {
                ru: 'Ожидание',
                ua: 'Очікування',
                en: 'Waiting',
                de: 'Warten',
                pl: 'Oczekiwanie',
            },
            pickBan: {
                ru: 'Пик-бан карт',
                ua: 'Пік-бан карт',
                en: 'Map pick-ban',
                de: 'Karten Pick-Ban',
                pl: 'Pick-ban map',
            },
            starting: {
                ru: 'Запуск боя',
                ua: 'Запуск бою',
                en: 'Starting war',
                de: 'Krieg startet',
                pl: 'Rozpoczynanie wojny',
            },
            closed: {
                ru: 'Закрыто',
                ua: 'Закрито',
                en: 'Closed',
                de: 'Geschlossen',
                pl: 'Zamkniete',
            },
        },
        side: {
            attacker: {
                ru: 'Атакующие',
                ua: 'Атакуючі',
                en: 'Attackers',
                de: 'Angreifer',
                pl: 'Atakujacy',
            },
            defender: {
                ru: 'Защитники',
                ua: 'Захисники',
                en: 'Defenders',
                de: 'Verteidiger',
                pl: 'Obroncy',
            },
        },
        modal: {
            stage: {
                ru: '{{n}} стадия',
                ua: '{{n}} стадія',
                en: '{{n}} stage',
                de: '{{n}} Phase',
                pl: '{{n}} etap',
            },
            enemyBans: {
                ru: 'КОМАНДА ПРОТИВНИКА БАНИТ 1 КАРТУ',
                ua: 'КОМАНДА СУПЕРНИКА БАНИТЬ 1 КАРТУ',
                en: 'ENEMY TEAM BANS 1 MAP',
                de: 'GEGNERTEAM BANNT 1 KARTE',
                pl: 'DRUZYNA PRZECIWNIKA BANUJE 1 MAPE',
            },
            youBan: {
                ru: 'ВЫ БАНИТЕ 1 КАРТУ',
                ua: 'ВИ БАНИТЕ 1 КАРТУ',
                en: 'YOU BAN 1 MAP',
                de: 'DU BANNST 1 KARTE',
                pl: 'BANUJESZ 1 MAPE',
            },
            pickInstruction: {
                ru: 'Выберите 1 карту для бана',
                ua: 'Виберіть 1 карту для бана',
                en: 'Pick 1 map to ban',
                de: 'Waehle 1 Karte zum Bannen',
                pl: 'Wybierz 1 mape do banowania',
            },
            waitInstruction: {
                ru: 'Ожидайте хода противника',
                ua: 'Очікуйте ходу супротивника',
                en: 'Wait for opponent turn',
                de: 'Warte auf gegnerischen Zug',
                pl: 'Czekaj na ture przeciwnika',
            },
            helperText: {
                ru: 'Выбранные карты гарантированно не будут использоваться для игры',
                ua: 'Вибрані карти гарантовано не будуть використовуватися в грі',
                en: 'Banned maps are guaranteed not to be used in the match',
                de: 'Gebannte Karten werden garantiert nicht im Spiel verwendet',
                pl: 'Zbanowane mapy gwarantowanie nie zostana uzyte w grze',
            },
            matchStartsIn: {
                ru: 'До начала матча',
                ua: 'До початку матчу',
                en: 'Match starts in',
                de: 'Match startet in',
                pl: 'Mecz startuje za',
            },
            mapPickedHelper: {
                ru: 'Подготовка к запуску',
                ua: 'Підготовка до запуску',
                en: 'Preparing launch',
                de: 'Start wird vorbereitet',
                pl: 'Przygotowanie do startu',
            },
        },
        pickBan: {
            title: {
                ru: 'Выбор карты — банами',
                ua: 'Вибір карти - банами',
                en: 'Map selection by bans',
                de: 'Kartenauswahl durch Bans',
                pl: 'Wybor mapy przez bany',
            },
            turn: {
                attacker: {
                    ru: 'Ходят атакующие',
                    ua: 'Ходять атакуючі',
                    en: 'Attackers turn',
                    de: 'Angreifer am Zug',
                    pl: 'Tura atakujacych',
                },
                defender: {
                    ru: 'Ходят защитники',
                    ua: 'Ходять захисники',
                    en: 'Defenders turn',
                    de: 'Verteidiger am Zug',
                    pl: 'Tura obroncow',
                },
            },
            bannedBy: {
                ru: 'Забанено',
                ua: 'Забанено',
                en: 'Banned by',
                de: 'Gebannt von',
                pl: 'Zbanowane przez',
            },
            picked: {
                ru: 'Карта боя',
                ua: 'Карта бою',
                en: 'Picked map',
                de: 'Gewaehlte Karte',
                pl: 'Wybrana mapa',
            },
            bansLeft: {
                ru: 'Банов осталось',
                ua: 'Банів залишилось',
                en: 'Bans left',
                de: 'Bans uebrig',
                pl: 'Banow zostalo',
            },
            yourTurn: {
                ru: 'Ваш ход',
                ua: 'Ваш хід',
                en: 'Your turn',
                de: 'Dein Zug',
                pl: 'Twoja tura',
            },
        },
        battlefields: {
            industrial: {
                name: {
                    ru: 'Промзона',
                    ua: 'Промзона',
                    en: 'Industrial',
                    de: 'Industriegebiet',
                    pl: 'Przemyslowka',
                },
            },
            docks: {
                name: {
                    ru: 'Доки',
                    ua: 'Доки',
                    en: 'Docks',
                    de: 'Docks',
                    pl: 'Doki',
                },
            },
            sandyShores: {
                name: {
                    ru: 'Сэнди-Шорс',
                    ua: 'Сенді-Шорс',
                    en: 'Sandy Shores',
                    de: 'Sandy Shores',
                    pl: 'Sandy Shores',
                },
            },
            sawmill: {
                name: {
                    ru: 'Лесопилка',
                    ua: 'Лісопилка',
                    en: 'Sawmill',
                    de: 'Saegewerk',
                    pl: 'Tartak',
                },
            },
            lsRooftops: {
                name: {
                    ru: 'Крыши Лос-Сантоса',
                    ua: 'Дахи Лос-Сантоса',
                    en: 'LS Rooftops',
                    de: 'LS Daecher',
                    pl: 'Dachy LS',
                },
            },
        },
        errors: {
            invalidPayload: {
                ru: 'Некорректные данные',
                ua: 'Некоректні дані',
                en: 'Invalid payload',
                de: 'Ungueltige Daten',
                pl: 'Nieprawidlowe dane',
            },
            lobbyNotFound: {
                ru: 'Лобби не найдено',
                ua: 'Лобі не знайдено',
                en: 'Lobby not found',
                de: 'Lobby nicht gefunden',
                pl: 'Lobby nie znalezione',
            },
            lobbyClosed: {
                ru: 'Лобби закрыто',
                ua: 'Лобі закрите',
                en: 'Lobby is closed',
                de: 'Lobby ist geschlossen',
                pl: 'Lobby zamkniete',
            },
            lobbyStarting: {
                ru: 'Бой уже запускается',
                ua: 'Бій уже стартує',
                en: 'War is already starting',
                de: 'Krieg startet bereits',
                pl: 'Wojna juz sie rozpoczyna',
            },
            notInGame: {
                ru: 'Персонаж не загружен',
                ua: 'Персонаж не завантажений',
                en: 'Character not loaded',
                de: 'Charakter nicht geladen',
                pl: 'Postac nie zaladowana',
            },
            noCharacter: {
                ru: 'Персонаж не определён',
                ua: 'Персонаж не визначений',
                en: 'Character undefined',
                de: 'Charakter nicht definiert',
                pl: 'Postac niezdefiniowana',
            },
            notInOrg: {
                ru: 'Вы не состоите в организации',
                ua: 'Ви не перебуваєте в організації',
                en: 'You are not in an organization',
                de: 'Du bist in keiner Organisation',
                pl: 'Nie nalezysz do organizacji',
            },
            noPermission: {
                ru: 'Недостаточно прав',
                ua: 'Недостатньо прав',
                en: 'No permission',
                de: 'Keine Berechtigung',
                pl: 'Brak uprawnien',
            },
            wrongOrg: {
                ru: 'Ваша организация не участвует в этом капте',
                ua: 'Ваша організація не бере участь у цьому бою',
                en: 'Your organization is not part of this war',
                de: 'Deine Organisation ist an diesem Krieg nicht beteiligt',
                pl: 'Twoja organizacja nie bierze udzialu w tej wojnie',
            },
            invalidCandidate: {
                ru: 'Игрок не подходит для состава',
                ua: 'Гравець не підходить для складу',
                en: 'Player cannot join roster',
                de: 'Spieler kann nicht in den Kader',
                pl: 'Gracz nie moze dolaczyc do skladu',
            },
            slotFull: {
                ru: 'Достигнут лимит слотов',
                ua: 'Досягнуто ліміт слотів',
                en: 'Slot limit reached',
                de: 'Slotlimit erreicht',
                pl: 'Limit slotow osiagniety',
            },
            rosterLocked: {
                ru: 'Состав уже заблокирован',
                ua: 'Склад уже заблоковано',
                en: 'Roster is locked',
                de: 'Kader ist gesperrt',
                pl: 'Sklad zablokowany',
            },
            notInLobby: {
                ru: 'Вы не в лобби',
                ua: 'Ви не в лобі',
                en: 'You are not in the lobby',
                de: 'Du bist nicht in der Lobby',
                pl: 'Nie jestes w lobby',
            },
            noOrg: {
                ru: 'Организация не найдена',
                ua: 'Організацію не знайдено',
                en: 'Organization not found',
                de: 'Organisation nicht gefunden',
                pl: 'Nie znaleziono organizacji',
            },
            pickBanNotActive: {
                ru: 'Пик-бан сейчас не активен',
                ua: 'Пік-бан зараз не активний',
                en: 'Pick-ban is not active',
                de: 'Pick-Ban ist nicht aktiv',
                pl: 'Pick-ban nie jest aktywny',
            },
            turnNotYours: {
                ru: 'Сейчас не ваш ход',
                ua: 'Зараз не ваш хід',
                en: 'Not your turn',
                de: 'Nicht dein Zug',
                pl: 'Nie twoja tura',
            },
            alreadyBanned: {
                ru: 'Карта уже забанена',
                ua: 'Карту вже забанено',
                en: 'Map already banned',
                de: 'Karte bereits gebannt',
                pl: 'Mapa juz zbanowana',
            },
            unknownBattlefield: {
                ru: 'Карта не найдена',
                ua: 'Карту не знайдено',
                en: 'Battlefield not found',
                de: 'Karte nicht gefunden',
                pl: 'Mapa nie znaleziona',
            },
            closed: {
                ru: 'Лобби закрыто',
                ua: 'Лобі закрите',
                en: 'Lobby is closed',
                de: 'Lobby geschlossen',
                pl: 'Lobby zamkniete',
            },
            cannotCancelNow: {
                ru: 'Сейчас отменить нельзя',
                ua: 'Зараз скасувати не можна',
                en: 'Cannot cancel now',
                de: 'Kann jetzt nicht abgebrochen werden',
                pl: 'Nie mozna teraz anulowac',
            },
            onlyAttackerCanCancel: {
                ru: 'Отменить может только атакующий',
                ua: 'Скасувати може лише атакуючий',
                en: 'Only attacker can cancel',
                de: 'Nur Angreifer kann abbrechen',
                pl: 'Tylko atakujacy moze anulowac',
            },
            enterFailed: {
                ru: 'Не удалось войти в лобби',
                ua: 'Не вдалося увійти в лобі',
                en: 'Failed to enter lobby',
                de: 'Lobby-Beitritt fehlgeschlagen',
                pl: 'Nie udalo sie wejsc do lobby',
            },
            rankTooLowToRemove: {
                ru: 'Нельзя убрать игрока с равным или более высоким рангом',
                ua: 'Не можна прибрати гравця з рівним або вищим рангом',
                en: 'Cannot remove a player of equal or higher rank',
                de: 'Spieler mit gleichem oder hoeherem Rang kann nicht entfernt werden',
                pl: 'Nie mozna usunac gracza o rownym lub wyzszym randze',
            },
            awaitDefenderRosterCommit: {
                ru: 'Дождитесь, пока лидер защиты сформирует состав',
                ua: 'Дочекайтеся, поки лідер захисту сформує склад',
                en: 'Wait until the defender leader commits the roster',
                de: 'Warte, bis der Verteidiger-Anfuehrer den Kader bestaetigt',
                pl: 'Poczekaj az lider obrony zatwierdzi sklad',
            },
            defenderRosterTooSmall: {
                ru: 'Минимальный состав - {{min}} из {{max}}',
                ua: 'Мінімальний склад - {{min}} із {{max}}',
                en: 'Minimum roster is {{min}} of {{max}}',
                de: 'Mindestkader - {{min}} von {{max}}',
                pl: 'Minimalny sklad - {{min}} z {{max}}',
            },
            rosterEditLocked: {
                ru: 'Состав сейчас редактирует {{name}}',
                ua: 'Склад зараз редагує {{name}}',
                en: '{{name}} is editing the roster',
                de: '{{name}} bearbeitet gerade den Kader',
                pl: '{{name}} edytuje teraz sklad',
            },
            rosterEditLockExpired: {
                ru: 'Сначала нажмите "Редактировать состав"',
                ua: 'Спочатку натисніть "Редагувати склад"',
                en: 'Click "Edit roster" first',
                de: 'Klicke zuerst auf "Kader bearbeiten"',
                pl: 'Najpierw kliknij "Edytuj sklad"',
            },
            onlyHighestRankCanBan: {
                ru: 'Карты банит только игрок с высшим рангом ({{name}})',
                ua: 'Карти банить лише гравець з найвищим рангом ({{name}})',
                en: 'Only the highest-ranked player ({{name}}) can ban maps',
                de: 'Nur der ranghoechste Spieler ({{name}}) kann Karten bannen',
                pl: 'Tylko gracz z najwyzszym rangiem ({{name}}) banuje mapy',
            },
            notInRoster: {
                ru: 'Вас нет в составе защиты',
                ua: 'Вас немає у складі захисту',
                en: 'You are not in the defender roster',
                de: 'Du bist nicht im Verteidiger-Kader',
                pl: 'Nie jestes w skladzie obrony',
            },
            awaitDefenderRoster: {
                ru: 'Лидер защиты ещё не сформировал состав',
                ua: 'Лідер захисту ще не сформував склад',
                en: 'Defender leader has not committed a roster yet',
                de: 'Verteidiger-Anfuehrer hat den Kader noch nicht bestaetigt',
                pl: 'Lider obrony jeszcze nie zatwierdzil skladu',
            },
            defenderRosterNotCommitted: {
                ru: 'Сначала сформируйте состав защиты',
                ua: 'Спочатку сформуйте склад захисту',
                en: 'Commit the defender roster first',
                de: 'Bestaetige zuerst den Verteidiger-Kader',
                pl: 'Najpierw zatwierdz sklad obrony',
            },
        },
        announce: {
            timeLeft: {
                ru: 'До войны за {{target}} осталось {{minutes}} мин. Будьте в лобби.',
                ua: 'До війни за {{target}} залишилось {{minutes}} хв. Будьте в лобі.',
                en: 'War for {{target}} starts in {{minutes}} min. Be in the lobby.',
                de: 'Krieg um {{target}} startet in {{minutes}} Min. Sei in der Lobby.',
                pl: 'Wojna o {{target}} za {{minutes}} min. Badz w lobby.',
            },
        },
        notify: {
            attackerNoShow: {
                ru: 'Атакующие не явились на бой за {{target}}. Защита удержала клетку.',
                ua: 'Атакуючі не зʼявилися на бій за {{target}}. Захист утримав клітинку.',
                en: 'Attackers did not show up for {{target}}. Defenders kept the cell.',
                de: 'Angreifer sind nicht zum Kampf um {{target}} erschienen. Verteidigung behaelt die Zelle.',
                pl: 'Atakujacy nie pojawili sie na walce o {{target}}. Obrona utrzymala pole.',
            },
            defenderNoShow: {
                ru: 'Защита не явилась на бой за {{target}}. Клетка переходит атакующим.',
                ua: 'Захист не зʼявився на бій за {{target}}. Клітинка переходить атакуючим.',
                en: 'Defenders did not show up for {{target}}. Cell goes to the attackers.',
                de: 'Verteidiger sind nicht zum Kampf um {{target}} erschienen. Zelle geht an die Angreifer.',
                pl: 'Obrona nie pojawila sie na walce o {{target}}. Pole przechodzi do atakujacych.',
            },
            bothNoShow: {
                ru: 'Никто не явился на бой за {{target}}. Клетка остаётся за владельцем.',
                ua: 'Ніхто не зʼявився на бій за {{target}}. Клітинка залишається у власника.',
                en: 'Nobody showed up for {{target}}. Cell stays with its owner.',
                de: 'Niemand ist zum Kampf um {{target}} erschienen. Zelle bleibt beim Besitzer.',
                pl: 'Nikt nie pojawil sie na walce o {{target}}. Pole zostaje przy wlascicielu.',
            },
        },
        leaveModal: {
            title: {
                ru: 'Выйти из лобби?',
                ua: 'Вийти з лобі?',
                en: 'Leave the lobby?',
                de: 'Lobby verlassen?',
                pl: 'Wyjsc z lobby?',
            },
            message: {
                ru: 'Если выйдешь сейчас, тебя удалит из лобби. Чтобы попасть обратно, придётся снова обращаться к секретарю.',
                ua: 'Якщо вийдеш зараз, тебе буде видалено з лобі. Щоб повернутися, доведеться знову звертатися до секретаря.',
                en: 'Leaving now removes you from the lobby. You will need to talk to the secretary again to come back.',
                de: 'Wenn du jetzt gehst, wirst du aus der Lobby entfernt. Du musst dann wieder mit der Sekretaerin sprechen.',
                pl: 'Wyjscie teraz usunie cie z lobby. Aby wrocic, trzeba bedzie znowu pojsc do sekretarki.',
            },
            defenderUncommittedMessage: {
                ru: 'Состав защиты ещё не сформирован. Если выйдешь сейчас, защита проиграет без боя.',
                ua: 'Склад захисту ще не сформовано. Якщо вийдеш зараз, захист програє без бою.',
                en: 'Defender roster is not committed yet. Leaving now forfeits the territory without a fight.',
                de: 'Der Verteidiger-Kader steht noch nicht. Wenn du jetzt gehst, verliert die Verteidigung kampflos.',
                pl: 'Sklad obrony nie jest jeszcze zatwierdzony. Wyjscie teraz oznacza walkower dla atakujacych.',
            },
            confirm: {
                ru: 'Выйти',
                ua: 'Вийти',
                en: 'Leave',
                de: 'Verlassen',
                pl: 'Wyjdz',
            },
            cancel: {
                ru: 'Остаться',
                ua: 'Залишитись',
                en: 'Stay',
                de: 'Bleiben',
                pl: 'Zostan',
            },
        },
        npc: {
            enterWarLobby: {
                ru: 'Перейти в лобби — {{cell}}',
                ua: 'Перейти в лобі - {{cell}}',
                en: 'Enter war lobby — {{cell}}',
                de: 'Lobby betreten - {{cell}}',
                pl: 'Wejdz do lobby - {{cell}}',
            },
        },
    },
};
