export const inventory = {
    inventory: {
        ua: 'Інвентар',
        en: 'Inventory',
        ru: 'Инвентарь',
        de: 'Inventar',
        pl: 'Inwentarz',
        zh: '库存',
    },
    unavailable: {
        ua: '(недоступно)',
        en: '(unavailable)',
        ru: '(недоступно)',
        de: '(nicht verfügbar)',
        pl: '(niedostępne)',
        zh: '(不可用)',
    },
    equipment: {
        ua: 'Ваше спорядження',
        en: 'Your Equipment',
        ru: 'Ваше снаряжение',
        de: 'Deine Ausrüstung',
        pl: 'Twój sprzęt',
        zh: '组配',
    },
    environment: {
        ua: 'Середовище',
        en: 'Environment',
        ru: 'Окружение',
        de: 'Umgebung',
        pl: 'Otoczenie',
        zh: '环境',
    },
    weapons: {
        ua: 'Ваша зброя',
        en: 'Your Weapons',
        ru: 'Ваше оружие',
        de: 'Deine Waffen',
        pl: 'Twoje bronie',
        zh: '你的武器',
    },
    weight: {
        ua: 'кг',
        en: 'kg',
        ru: 'кг',
        de: 'kg',
        pl: 'kg',
        zh: 'kg',
    },

    trunk: {
        ru: 'Багажник',
        ua: 'Багажник',
        en: 'Trunk',
        de: 'Kofferraum',
        pl: 'Bagażnik',
        zh: '树干',
    },

    airdrop: {
        ru: 'Аирдроп',
        ua: 'Аірдроп',
        en: 'Airdrop',
        de: 'Airdrop',
        pl: 'Airdrop',
    },

    houseInventory: {
        ru: 'Склад дома',
        ua: 'Склад дому',
        en: 'House storage',
        de: 'Hauslager',
        pl: 'Magazyn domu',
    },
    faction: {
        ru: 'Склад фракции',
        ua: 'Склад фракції',
        en: 'Faction warehouse',
        de: 'Fraktionslager',
        pl: 'Magazyn frakcji',
    },

    contextMenu: {
        kg: {
            ua: ' кг.',
            en: ' kg.',
            ru: ' кг.',
            de: ' kg.',
            pl: ' kg.',
            zh: 'kg',
        },
        weight: {
            ua: 'Вага',
            ru: 'Вес',
            en: 'Weight',
            de: 'Gewicht',
            pl: 'Waga',
            zh: '重量',
        },
        totalWeight: {
            ru: 'Общий вес',
            ua: 'Загальна вага',
            en: 'Total Weight',
            de: 'Gesamtgewicht',
            pl: 'Całkowita waga',
            zh: '总重量',
        },
        quantity: {
            ru: 'Количество',
            ua: 'Кількість',
            en: 'Quantity',
            de: 'Menge',
            pl: 'Ilość',
            zh: '量',
        },

        ammoType: {
            ru: 'Тип патронов',
            ua: 'Тип патронів',
            en: 'Ammo Type',
            de: 'Munitionstyp',
            pl: 'Typ amunicji',
            zh: '弹药类型',
        },

        water: {
            ru: 'Запас воды',
            ua: 'Запас води',
            en: 'Water supply',
            de: 'Wasservorrat',
            pl: 'Zapas wody',
            ge: 'წყლის მარაგი',
            zh: '供水',
        },

        bindingText: {
            ru: 'Нажмите кнопку для привязки',
            ua: "Натисніть кнопку для прив'язки",
            en: 'Press the button to bind',
            de: 'Drücke eine Taste zum Binden',
            pl: 'Naciśnij przycisk, aby przypisać',
            zh: '按下按钮进行绑定',
        },

        use: {
            ru: 'Использовать',
            ua: 'Використати',
            en: 'Use',
            de: 'Verwenden',
            pl: 'Użyj',
            zh: '使用',
        },
        dontUse: {
            ru: 'Не использовать',
            ua: 'Не використовувати',
            en: "Don't Use",
            de: 'Nicht verwenden',
            pl: 'Nie używaj',
            zh: '勿使用',
        },
        bind: {
            ru: 'Назначить на кнопку',
            ua: 'Призначити на кнопку',
            en: 'Bind to button',
            de: 'Auf Taste binden',
            pl: 'Przypisz do przycisku',
            zh: '绑定到按钮',
        },
        unbind: {
            ru: 'Отвязать от кнопки',
            ua: "Відв'язати від кнопки",
            en: 'Unbind from button',
            de: 'Von der Taste lösen',
            pl: 'Odpiąć od przycisku',
            zh: '解除绑定按钮',
        },
        divide: {
            ru: 'Разделить',
            ua: 'Поділити',
            en: 'Divide',
            de: 'Teilen',
            pl: 'Podziel',
            zh: '差异',
        },
        drop: {
            ru: 'Выбросить',
            ua: 'Викинути',
            en: 'Drop',
            de: 'Fallen lassen',
            pl: 'Upuść',
            zh: '下降',
        },
        durability: {
            ru: 'Прочность',
            ua: 'Міцність',
            en: 'Durability',
            de: 'Haltbarkeit',
            pl: 'Wytrzymałość',
            zh: '持久性',
        },

        exclusiveWeapon: {
            ru: 'Это оружие является эксклюзивным и оно не будет выпадать в случае смерти.',
            ua: 'Ця зброя є ексклюзивною і вона не буде випадати у випадку смерті.',
            en: 'This weapon is exclusive and will not drop upon death.',
            de: 'Diese Waffe ist exklusiv und wird beim Tod nicht fallen gelassen.',
            pl: 'Ta broń jest ekskluzywna i nie wypadnie po śmierci.',
        },
    },
    quantityMenu: {
        divide: {
            header: {
                ru: 'Разделение предмета',
                ua: 'Розділення предмета',
                en: 'Item Division',
                de: 'Gegenstandsteilung',
                pl: 'Podział przedmiotu',
                zh: '项目区分',
            },
            accept: {
                ru: 'Разделить',
                ua: 'Поділити',
                en: 'Divide',
                de: 'Teilen',
                pl: 'Podziel',
                zh: '分开',
            },
        },
        drop: {
            header: {
                ru: 'Выбросить предмет',
                ua: 'Викинути предмет',
                en: 'Drop Item',
                de: 'Gegenstand fallen lassen',
                pl: 'Upuść przedmiot',
                zh: '扔掉物品',
            },
            accept: {
                ru: 'Выбросить',
                ua: 'Викинути',
                en: 'Drop',
                de: 'Fallen lassen',
                pl: 'Upuść',
                zh: '下降',
            },
        },
        pickUpDrop: {
            header: {
                ru: 'Подобрать предмет',
                ua: 'Підібрати предмет',
                en: 'Pick Up Item',
                de: 'Gegenstand aufheben',
                pl: 'Podnieś przedmiot',
                zh: '从地面上取物',
            },
            accept: {
                ru: 'Подобрать',
                ua: 'Підібрати',
                en: 'Pick Up',
                de: 'Aufheben',
                pl: 'Podnieś',
                zh: '拾起',
            },
        },
        quantity: {
            ru: 'Количество:',
            ua: 'Кількість:',
            en: 'Quantity:',
            de: 'Menge:',
            pl: 'Ilość:',
            zh: '数量:',
        },
        pcs: {
            ru: 'шт.',
            ua: 'шт.',
            en: 'pcs',
            de: 'Stk.',
            pl: 'szt.',
            zh: '件数',
        },
        close: {
            ru: 'Отмена',
            ua: 'Скасувати',
            en: 'Cancel',
            de: 'Abbrechen',
            pl: 'Anuluj',
            zh: '取消 ',
        },
        all: {
            ru: 'ВСЁ',
            ua: 'ВСЕ',
            en: 'All',
            de: 'Alles',
            pl: 'Wszystko',
            zh: '全部',
        },
    },
    slot: {
        pcs: {
            ru: 'шт.',
            ua: 'шт.',
            en: 'pcs',
            de: 'Stk.',
            pl: 'szt.',
            zh: '件数',
        },
        weight: {
            ua: 'кг',
            en: 'kg',
            ru: 'кг',
            de: 'kg',
            pl: 'kg',
            zh: 'kg',
        },
    },
};
