export const macros = {
    title: { ru: 'Макросы', ua: 'Макроси', en: 'Macros', de: 'Makros', pl: 'Makra' },
    addProfile: { ru: 'Добавить профиль', ua: 'Додати профіль', en: 'Add profile', de: 'Profil hinzufügen', pl: 'Dodaj profil' },
    deleteProfile: { ru: 'Удалить профиль', ua: 'Видалити профіль', en: 'Delete profile', de: 'Profil löschen', pl: 'Usuń profil' },
    profileNamePlaceholder: { ru: 'Название профиля', ua: 'Назва профілю', en: 'Profile name', de: 'Profilname', pl: 'Nazwa profilu' },
    macroNamePlaceholder: { ru: 'Название макроса', ua: 'Назва макроса', en: 'Macro name', de: 'Makroname', pl: 'Nazwa makra' },
    macroFallbackName: { ru: 'Без названия', ua: 'Без назви', en: 'Untitled', de: 'Unbenannt', pl: 'Bez nazwy' },
    createNewMacro: { ru: 'Создать новый макрос', ua: 'Створити новий макрос', en: 'Create new macro', de: 'Neues Makro', pl: 'Utwórz makro' },
    emptyProfile: { ru: 'В этом профиле ещё нет макросов', ua: 'У цьому профілі ще немає макросів', en: 'No macros in this profile yet', de: 'Noch keine Makros in diesem Profil', pl: 'Brak makr w tym profilu' },
    noProfile: { ru: 'Нет активного профиля. Создайте новый.', ua: 'Немає активного профілю. Створіть новий.', en: 'No active profile. Create one.', de: 'Kein aktives Profil. Erstelle eines.', pl: 'Brak aktywnego profilu. Utwórz nowy.' },
    activation: { ru: 'Активация', ua: 'Активація', en: 'Activation', de: 'Aktivierung', pl: 'Aktywacja' },
    showInHints: { ru: 'Отображать макрос в меню подсказок', ua: 'Показувати макрос у меню підказок', en: 'Show in hints menu', de: 'Im Hinweismenü anzeigen', pl: 'Pokaż w menu podpowiedzi' },
    commandsHeader: { ru: 'Команды', ua: 'Команди', en: 'Commands', de: 'Befehle', pl: 'Polecenia' },
    addCommandHint: { ru: 'Добавьте действие и настройте его', ua: 'Додайте дію та налаштуйте її', en: 'Add an action and configure it', de: 'Aktion hinzufügen und konfigurieren', pl: 'Dodaj akcję i skonfiguruj ją' },
    selectMacroHint: { ru: 'Создайте макрос, чтобы начать настройку', ua: 'Створіть макрос, щоб почати налаштування', en: 'Create a macro to start configuring', de: 'Erstelle ein Makro zum Konfigurieren', pl: 'Utwórz makro, aby rozpocząć konfigurację' },

    codePlaceholder: { ru: 'Вставьте код профиля', ua: 'Вставте код профілю', en: 'Paste profile code', de: 'Profilcode einfügen', pl: 'Wklej kod profilu' },
    load: { ru: 'Импортировать', ua: 'Імпортувати', en: 'Import', de: 'Importieren', pl: 'Importuj' },
    share: { ru: 'Поделиться профилем', ua: 'Поділитися профілем', en: 'Share profile', de: 'Profil teilen', pl: 'Udostępnij profil' },
    or: { ru: 'или', ua: 'або', en: 'or', de: 'oder', pl: 'lub' },
    notifyHeader: { ru: 'Макросы', ua: 'Макроси', en: 'Macros', de: 'Makros', pl: 'Makra' },
    notifyCopiedBody: { ru: 'Код профиля скопирован в буфер обмена', ua: 'Код профілю скопійовано в буфер обміну', en: 'Profile code copied to clipboard', de: 'Profilcode in die Zwischenablage kopiert', pl: 'Kod profilu skopiowano do schowka' },
    importedOk: { ru: 'Профиль импортирован', ua: 'Профіль імпортовано', en: 'Profile imported', de: 'Profil importiert', pl: 'Profil zaimportowany' },
    importedFail: { ru: 'Неверный или повреждённый код', ua: 'Невірний або пошкоджений код', en: 'Invalid or corrupted code', de: 'Ungültiger oder beschädigter Code', pl: 'Nieprawidłowy lub uszkodzony kod' },
    shareFailed: { ru: 'Не удалось сгенерировать код', ua: 'Не вдалося згенерувати код', en: 'Failed to generate code', de: 'Code konnte nicht erzeugt werden', pl: 'Nie udało się wygenerować kodu' },
    clipboardFailed: { ru: 'Не удалось скопировать в буфер - код в поле ввода', ua: 'Не вдалося скопіювати у буфер - код у полі вводу', en: 'Could not access clipboard - code is in the input', de: 'Zwischenablage nicht verfügbar - Code im Feld', pl: 'Nie udało się skopiować - kod w polu' },

    pressKey: { ru: 'Нажмите клавишу', ua: 'Натисніть клавішу', en: 'Press a key', de: 'Taste drücken', pl: 'Naciśnij klawisz' },
    pickerBack: { ru: '‹ Назад', ua: '‹ Назад', en: '‹ Back', de: '‹ Zurück', pl: '‹ Wstecz' },

    deleteConfirm: {
        title: { ru: 'Удалить профиль?', ua: 'Видалити профіль?', en: 'Delete profile?', de: 'Profil löschen?', pl: 'Usunąć profil?' },
        message: {
            ru: 'Профиль <b>{{name}}</b> и все его макросы будут удалены безвозвратно.',
            ua: 'Профіль <b>{{name}}</b> та всі його макроси буде видалено назавжди.',
            en: 'Profile <b>{{name}}</b> and all its macros will be permanently deleted.',
            de: 'Profil <b>{{name}}</b> und alle seine Makros werden dauerhaft gelöscht.',
            pl: 'Profil <b>{{name}}</b> i wszystkie jego makra zostaną trwale usunięte.',
        },
        confirm: { ru: 'Удалить', ua: 'Видалити', en: 'Delete', de: 'Löschen', pl: 'Usuń' },
        cancel: { ru: 'Отмена', ua: 'Скасувати', en: 'Cancel', de: 'Abbrechen', pl: 'Anuluj' },
    },

    deleteMacroConfirm: {
        title: { ru: 'Удалить макрос?', ua: 'Видалити макрос?', en: 'Delete macro?', de: 'Makro löschen?', pl: 'Usunąć makro?' },
        message: {
            ru: 'Макрос <b>{{name}}</b> будет удалён безвозвратно.',
            ua: 'Макрос <b>{{name}}</b> буде видалено назавжди.',
            en: 'Macro <b>{{name}}</b> will be permanently deleted.',
            de: 'Makro <b>{{name}}</b> wird dauerhaft gelöscht.',
            pl: 'Makro <b>{{name}}</b> zostanie trwale usunięte.',
        },
        confirm: { ru: 'Удалить', ua: 'Видалити', en: 'Delete', de: 'Löschen', pl: 'Usuń' },
        cancel: { ru: 'Отмена', ua: 'Скасувати', en: 'Cancel', de: 'Abbrechen', pl: 'Anuluj' },
    },

    categories: {
        message: { ru: 'Сообщение', ua: 'Повідомлення', en: 'Message', de: 'Nachricht', pl: 'Wiadomość' },
        roleplay: { ru: 'Отыгровка', ua: 'Відіграш', en: 'Roleplay', de: 'Rollenspiel', pl: 'Odgrywanie' },
        gov: { ru: 'Государственное', ua: 'Державне', en: 'Government', de: 'Behörde', pl: 'Państwowe' },
        ems: { ru: 'EMS', ua: 'EMS', en: 'EMS', de: 'EMS', pl: 'EMS' },
        vehicle: { ru: 'Транспорт', ua: 'Транспорт', en: 'Vehicle', de: 'Fahrzeug', pl: 'Pojazd' },
        documents: { ru: 'Документы', ua: 'Документи', en: 'Documents', de: 'Dokumente', pl: 'Dokumenty' },
        criminal: { ru: 'Криминальное', ua: 'Кримінальне', en: 'Criminal', de: 'Kriminell', pl: 'Kryminalne' },
        delay: { ru: 'Задержка', ua: 'Затримка', en: 'Delay', de: 'Verzögerung', pl: 'Opóźnienie' },
    },

    actions: {
        'chat.normal': { ru: 'Чат: обычный', ua: 'Чат: звичайний', en: 'Chat: normal', de: 'Chat: normal', pl: 'Czat: zwykły' },
        'chat.ooc': { ru: 'Чат: OOC', ua: 'Чат: OOC', en: 'Chat: OOC', de: 'Chat: OOC', pl: 'Czat: OOC' },
        'chat.shout': { ru: 'Чат: крик', ua: 'Чат: крик', en: 'Chat: shout', de: 'Chat: Schrei', pl: 'Czat: krzyk' },
        'chat.whisper': { ru: 'Чат: шёпот', ua: 'Чат: шепіт', en: 'Chat: whisper', de: 'Chat: Flüstern', pl: 'Czat: szept' },
        'chat.radio': { ru: 'Чат: рация фракции', ua: 'Чат: рація фракції', en: 'Chat: faction radio', de: 'Chat: Fraktionsfunk', pl: 'Czat: radio frakcji' },

        'rp.me': { ru: '/me', ua: '/me', en: '/me', de: '/me', pl: '/me' },
        'rp.do': { ru: '/do', ua: '/do', en: '/do', de: '/do', pl: '/do' },
        'rp.try': { ru: '/try', ua: '/try', en: '/try', de: '/try', pl: '/try' },
        'rp.todo': { ru: '/todo', ua: '/todo', en: '/todo', de: '/todo', pl: '/todo' },

        'delay.ms': { ru: 'Задержка', ua: 'Затримка', en: 'Delay', de: 'Verzögerung', pl: 'Opóźnienie' },

        'faction.cuff': { ru: 'Надеть наручники', ua: 'Надіти наручники', en: 'Cuff player', de: 'Handschellen anlegen', pl: 'Założyć kajdanki' },
        'faction.cabbleTie': { ru: 'Надеть стяжки', ua: 'Надіти стяжки', en: 'Use cable tie', de: 'Kabelbinder anlegen', pl: 'Założyć opaski' },
        'faction.uncuff': { ru: 'Снять наручники', ua: 'Зняти наручники', en: 'Remove restraints', de: 'Fesseln abnehmen', pl: 'Zdjąć kajdanki' },
        'faction.frisk': { ru: 'Обыскать игрока', ua: 'Обшукати гравця', en: 'Frisk player', de: 'Spieler durchsuchen', pl: 'Przeszukać gracza' },
        'faction.checkVehicle': { ru: 'Проверить транспорт', ua: 'Перевірити транспорт', en: 'Check vehicle', de: 'Fahrzeug prüfen', pl: 'Sprawdzić pojazd' },
        'faction.takeMask': { ru: 'Снять маску', ua: 'Зняти маску', en: 'Remove mask', de: 'Maske abnehmen', pl: 'Zdjąć maskę' },
        'faction.takeLicenses': { ru: 'Изъять лицензии', ua: 'Вилучити ліцензії', en: 'Take licenses', de: 'Lizenzen entziehen', pl: 'Odebrać licencje' },
        'faction.putToVehicle': { ru: 'Посадить в транспорт', ua: 'Посадити у транспорт', en: 'Put into vehicle', de: 'In Fahrzeug setzen', pl: 'Wsadzić do pojazdu' },
        'faction.removeFromVehicle': { ru: 'Высадить из транспорта', ua: 'Висадити з транспорту', en: 'Remove from vehicle', de: 'Aus Fahrzeug entfernen', pl: 'Wyciągnąć z pojazdu' },
        'faction.dep': { ru: 'Чат: департамент (/dep)', ua: 'Чат: департамент (/dep)', en: 'Chat: department (/dep)', de: 'Chat: Abteilung (/dep)', pl: 'Czat: departament (/dep)' },
        'faction.gov': { ru: 'Чат: госструктуры (/gov)', ua: 'Чат: держструктури (/gov)', en: 'Chat: government (/gov)', de: 'Chat: Regierung (/gov)', pl: 'Czat: rząd (/gov)' },

        'ems.takeBlood': { ru: 'Взять кровь', ua: 'Взяти кров', en: 'Take blood', de: 'Blut abnehmen', pl: 'Pobrać krew' },
        'ems.checkDiseases': { ru: 'Проверить болезни', ua: 'Перевірити хвороби', en: 'Check diseases', de: 'Krankheiten prüfen', pl: 'Sprawdzić choroby' },
        'ems.heal': { ru: 'Вылечить болезни', ua: 'Вилікувати хвороби', en: 'Heal diseases', de: 'Krankheiten heilen', pl: 'Uleczyć choroby' },
        'ems.reanimate': { ru: 'Реанимировать', ua: 'Реанімувати', en: 'Reanimate', de: 'Reanimieren', pl: 'Reanimować' },

        'vehicle.engine': { ru: 'Двигатель', ua: 'Двигун', en: 'Engine toggle', de: 'Motor schalten', pl: 'Silnik' },
        'vehicle.lights': { ru: 'Фары', ua: 'Фари', en: 'Lights toggle', de: 'Lichter schalten', pl: 'Światła' },
        'vehicle.lock': { ru: 'Замок', ua: 'Замок', en: 'Lock toggle', de: 'Schloss', pl: 'Zamek' },
        'vehicle.siren': { ru: 'Сирена', ua: 'Сирена', en: 'Siren toggle', de: 'Sirene', pl: 'Syrena' },
        'vehicle.trunk': { ru: 'Багажник', ua: 'Багажник', en: 'Trunk toggle', de: 'Kofferraum', pl: 'Bagażnik' },

        'documents.showBadge': { ru: 'Показать жетон', ua: 'Показати жетон', en: 'Show badge', de: 'Marke zeigen', pl: 'Pokazać odznakę' },
        'documents.showPassport': { ru: 'Показать паспорт', ua: 'Показати паспорт', en: 'Show passport', de: 'Pass zeigen', pl: 'Pokazać paszport' },
        'documents.showLicenses': { ru: 'Показать лицензии', ua: 'Показати ліцензії', en: 'Show licenses', de: 'Lizenzen zeigen', pl: 'Pokazać licencje' },
        'documents.showDrivingLicenses': { ru: 'Показать водительское', ua: 'Показати посвідчення водія', en: 'Show driving license', de: 'Führerschein zeigen', pl: 'Pokazać prawo jazdy' },
    },

    placeholders: {
        chatNormal: { ru: 'Сообщение в обычный чат', ua: 'Повідомлення у звичайний чат', en: 'Message to local chat', de: 'Nachricht an Lokalchat', pl: 'Wiadomość na lokalny czat' },
        chatOoc: { ru: 'Сообщение в OOC', ua: 'Повідомлення в OOC', en: 'OOC message', de: 'OOC-Nachricht', pl: 'Wiadomość OOC' },
        rpDesc: { ru: 'Описание действия персонажа', ua: 'Опис дії персонажа', en: 'Character action description', de: 'Aktionsbeschreibung', pl: 'Opis akcji postaci' },
        doDesc: { ru: 'Описание окружения / результата', ua: 'Опис оточення / результату', en: 'Environment / result description', de: 'Umgebungs- / Ergebnisbeschreibung', pl: 'Opis otoczenia / rezultatu' },
        delaySeconds: { ru: 'Длительность', ua: 'Тривалість', en: 'Duration', de: 'Dauer', pl: 'Czas trwania' },
        delayUnit: { ru: 'сек', ua: 'сек', en: 's', de: 's', pl: 's' },
    },
};
