export const settings = {
    tabs: {
        general: {
            ru: 'Общие',
            ua: 'Загальні',
            en: 'General',
            de: 'Allgemein',
            pl: 'Ogólne',
        },
        hud: {
            en: 'HUD',
        },
        account: {
            ru: 'Аккаунт',
            ua: 'Акаунт',
            en: 'Account',
            de: 'Konto',
            pl: 'Konto',
        },
        binds: {
            ru: 'Привязка клавиш',
            ua: "Прив'язка клавіш",
            en: 'Key Bindings',
            de: 'Tastenbelegung',
            pl: 'Przypisanie klawiszy',
        },
        aim: {
            ru: 'Прицел',
            ua: 'Приціл',
            en: 'Aim',
            de: 'Visier',
            pl: 'Celownik',
        },
        sounds: {
            ru: 'Звуки',
            ua: 'Звуки',
            en: 'Sounds',
            de: 'Sounds',
            pl: 'Dźwięki',
        },
    },

    keyBindCategories: {
        general: {
            ru: 'Основные',
            ua: 'Основні',
            en: 'General',
            de: 'Allgemeines',
            pl: 'Główne',
        },
        character: {
            ru: 'Персонаж',
            ua: 'Персонаж',
            en: 'Character',
            de: 'Charakter',
            pl: 'Postać',
        },
        vehicle: {
            ru: 'Транспорт',
            ua: 'Транспорт',
            en: 'Vehicle',
            de: 'Fahrzeug',
            pl: 'Pojazd',
        },
        weapons: {
            ru: 'Оружие',
            ua: 'Зброя',
            en: 'Weapons',
            de: 'Waffen',
            pl: 'Broń',
        },
        casino: {
            ru: 'Казино',
            ua: 'Казино',
            en: 'Casino',
            de: 'Casino',
            pl: 'Kasyno',
        },
        gov: {
            ru: 'Государственные',
            ua: 'Державні',
            en: 'Government',
            de: 'Staatliche',
            pl: 'Rządowe',
        },
        furnitureEditor: {
            ru: 'Редактор мебели',
            ua: 'Редактор меблів',
            en: 'Furniture Editor',
            de: 'Möbeleditor',
            pl: 'Edytor mebli',
        },
    },
    walkingStyles: {
        default: {
            ru: 'Обычная',
            ua: 'Звичайна',
            en: 'Normal',
            de: 'Normal',
            pl: 'Zwykła',
        },
        m_generic: {
            ru: 'Стандартная',
            ua: 'Стандартна',
            en: 'Standard',
            de: 'Standard',
            pl: 'Standardowa',
        },
        m_casualA: {
            ru: 'Повседневная A',
            ua: 'Повсякденна A',
            en: 'Casual A',
            de: 'Lässig A',
            pl: 'Codzienna A',
        },
        m_casualB: {
            ru: 'Повседневная B',
            ua: 'Повсякденна B',
            en: 'Casual B',
            de: 'Lässig B',
            pl: 'Codzienna B',
        },
        m_casualC: {
            ru: 'Повседневная C',
            ua: 'Повсякденна C',
            en: 'Casual C',
            de: 'Lässig C',
            pl: 'Codzienna C',
        },
        m_casualD: {
            ru: 'Повседневная D',
            ua: 'Повсякденна D',
            en: 'Casual D',
            de: 'Lässig D',
            pl: 'Codzienna D',
        },
        m_casualE: {
            ru: 'Повседневная E',
            ua: 'Повсякденна E',
            en: 'Casual E',
            de: 'Lässig E',
            pl: 'Codzienna E',
        },
        m_casualF: {
            ru: 'Повседневная F',
            ua: 'Повсякденна F',
            en: 'Casual F',
            de: 'Lässig F',
            pl: 'Codzienna F',
        },
        m_businessA: {
            ru: 'Деловая A',
            ua: 'Ділова A',
            en: 'Business A',
            de: 'Business A',
            pl: 'Biznesowa A',
        },
        m_businessB: {
            ru: 'Деловая B',
            ua: 'Ділова B',
            en: 'Business B',
            de: 'Business B',
            pl: 'Biznesowa B',
        },
        m_businessC: {
            ru: 'Деловая C',
            ua: 'Ділова C',
            en: 'Business C',
            de: 'Business C',
            pl: 'Biznesowa C',
        },
        m_confident: {
            ru: 'Уверенная',
            ua: 'Впевнена',
            en: 'Confident',
            de: 'Selbstbewusst',
            pl: 'Pewna siebie',
        },
        m_brave: {
            ru: 'Решительная',
            ua: 'Рішуча',
            en: 'Brave',
            de: 'Mutig',
            pl: 'Zdecydowana',
        },
        m_gangster: {
            ru: 'Гангстерская',
            ua: 'Гангстерська',
            en: 'Gangster',
            de: 'Gangster',
            pl: 'Gangsterska',
        },
        m_gangsterNG: {
            ru: 'Гангстерская (узкая)',
            ua: 'Гангстерська (вузька)',
            en: 'Gangster (narrow)',
            de: 'Gangster (schmal)',
            pl: 'Gangsterska (wąska)',
        },
        m_tough: {
            ru: 'Жёсткая',
            ua: 'Жорстка',
            en: 'Tough',
            de: 'Hart',
            pl: 'Twarda',
        },
        m_muscle: {
            ru: 'Качок',
            ua: 'Качок',
            en: 'Muscle Guy',
            de: 'Muskeltyp',
            pl: 'Koks',
        },
        m_fat: {
            ru: 'Тяжёлая походка',
            ua: 'Важка хода',
            en: 'Heavy Walk',
            de: 'Schwerer Gang',
            pl: 'Ciężki chód',
        },
        m_hobo: {
            ru: 'Бродяга',
            ua: 'Бродяга',
            en: 'Hobo',
            de: 'Penner',
            pl: 'Włóczęga',
        },
        m_hurry: {
            ru: 'Спешка',
            ua: 'Поспіх',
            en: 'Hurry',
            de: 'Eile',
            pl: 'Pośpiech',
        },
        m_hurryButch: {
            ru: 'Грубая спешка',
            ua: 'Грубий поспіх',
            en: 'Rough Hurry',
            de: 'Grobe Eile',
            pl: 'Ostry pośpiech',
        },
        f_femme: {
            ru: 'Элегантная',
            ua: 'Елегантна',
            en: 'Elegant',
            de: 'Elegant',
            pl: 'Elegancka',
        },
        f_sexy: {
            ru: 'Соблазнительная',
            ua: 'Зваблива',
            en: 'Sexy',
            de: 'Sexy',
            pl: 'Seksowna',
        },
        f_heelsC: {
            ru: 'На каблуках C',
            ua: 'На підборах C',
            en: 'Heels C',
            de: 'Absätze C',
            pl: 'Na obcasach C',
        },
        f_heelsD: {
            ru: 'На каблуках D',
            ua: 'На підборах D',
            en: 'Heels D',
            de: 'Absätze D',
            pl: 'Na obcasach D',
        },
        f_arrogant: {
            ru: 'Высокомерная',
            ua: 'Зарозуміла',
            en: 'Arrogant',
            de: 'Arrogant',
            pl: 'Arogancka',
        },
        f_maneater: {
            ru: 'Хищная',
            ua: 'Хижа',
            en: 'Predatory',
            de: 'Räuberisch',
            pl: 'Drapieżna',
        },
        f_sassy: {
            ru: 'Дерзкая',
            ua: 'Нахабна',
            en: 'Sassy',
            de: 'Frech',
            pl: 'Zuchwała',
        },
        f_tough: {
            ru: 'Жёсткая походка',
            ua: 'Жорстка хода',
            en: 'Tough Walk',
            de: 'Harter Gang',
            pl: 'Twardy chód',
        },
        f_gangsterNG: {
            ru: 'Уличная',
            ua: 'Вулична',
            en: 'Street',
            de: 'Straßenstil',
            pl: 'Uliczna',
        },
        f_posh: {
            ru: 'Аристократичная',
            ua: 'Аристократична',
            en: 'Posh',
            de: 'Vornehm',
            pl: 'Wytworna',
        },
        f_hurry: {
            ru: 'Быстрая походка',
            ua: 'Швидка хода',
            en: 'Fast Walk',
            de: 'Schneller Gang',
            pl: 'Szybki chód',
        },
        f_flee: {
            ru: 'Бегство',
            ua: 'Втеча',
            en: 'Flee',
            de: 'Flucht',
            pl: 'Ucieczka',
        },
        f_scared: {
            ru: 'Испуганная',
            ua: 'Налякана',
            en: 'Scared',
            de: 'Verängstigt',
            pl: 'Wystraszona',
        },
        u_injuredGeneric: {
            ru: 'Раненая',
            ua: 'Поранена',
            en: 'Injured',
            de: 'Verletzt',
            pl: 'Ranna',
        },
        u_injuredMale: {
            ru: 'Раненая тяжёлая',
            ua: 'Тяжко поранена',
            en: 'Severely Injured',
            de: 'Schwer verletzt',
            pl: 'Ciężko ranna',
        },
        u_cowardMale: {
            ru: 'Трусливая',
            ua: 'Боягузлива',
            en: 'Cowardly',
            de: 'Feige',
            pl: 'Tchórzliwa',
        },
        u_ballistic: {
            ru: 'Тактическая (с оружием)',
            ua: 'Тактична (зі зброєю)',
            en: 'Tactical (with weapon)',
            de: 'Taktisch (mit Waffe)',
            pl: 'Taktyczna (z bronią)',
        },
        u_trash: {
            ru: 'Рабочая - мусорщик',
            ua: 'Робоча - сміттяр',
            en: 'Worker - Garbage Collector',
            de: 'Arbeiter – Müllmann',
            pl: 'Pracownik - śmieciarz',
        },
        u_heistLester: {
            ru: 'Сутулая криминальная',
            ua: 'Сутула кримінальна',
            en: 'Hunched Criminal',
            de: 'Gekrümmter Krimineller',
            pl: 'Zgarbiony przestępca',
        },
        u_lesterCane: {
            ru: 'Походка с тростью',
            ua: 'Хода з палицею',
            en: 'Cane Walk',
            de: 'Gehstock-Gang',
            pl: 'Chód z laską',
        },
        u_alien: {
            ru: 'Инопланетянин',
            ua: 'Інопланетянин',
            en: 'Alien',
            de: 'Außerirdischer',
            pl: 'Obcy',
        },
        u_hiking: {
            ru: 'Походная',
            ua: 'Похідна',
            en: 'Hiking',
            de: 'Wandern',
            pl: 'Trekkingowa',
        },
        u_jog: {
            ru: 'Бег трусцой',
            ua: 'Біг підтюпцем',
            en: 'Jog',
            de: 'Joggen',
            pl: 'Trucht',
        },
        u_bucket: {
            ru: 'С ведром',
            ua: 'З відром',
            en: 'With Bucket',
            de: 'Mit Eimer',
            pl: 'Z wiadrem',
        },
        u_mop: {
            ru: 'Со шваброй',
            ua: 'З шваброю',
            en: 'With Mop',
            de: 'Mit Mopp',
            pl: 'Z mopem',
        },
    },
    walkStyleTitle: {
        ru: 'Стиль походки',
        ua: 'Стиль ходи',
        en: 'Walk Style',
        de: 'Gehstil',
        pl: 'Styl chodu',
    },
    walkStyleDesc: {
        ru: 'Вы можете выбрать стиль походки',
        ua: 'Ти можеш вибрати стиль ходи',
        en: 'You can choose a walk style',
        de: 'Du kannst einen Gehstil auswählen',
        pl: 'Możesz wybrać styl chodu',
    },
    name: {
        ua: 'Налаштування',
        en: 'Settings',
        ru: 'Настройки',
        de: 'Einstellungen',
        pl: 'Ustawienia',
        zh: '设置',
    },
    chooseLanguage: {
        ua: 'Оберіть мову',
        en: 'Choose a language',
        ru: 'Выберите язык',
        de: 'Wähle eine Sprache',
        pl: 'Wybierz język',
        zh: '选择语言',
    },
    chatSettings: {
        ru: 'Настройки чата',
        ua: 'Налаштування чату',
        en: 'Chat settings',
        de: 'Chateinstellungen',
        pl: 'Ustawienia czatu',
    },
    hudSettings: {
        ru: 'Настройки HUD',
        ua: 'Налаштування HUD',
        en: 'HUD Settings',
        de: 'HUD-Einstellungen',
        pl: 'Ustawienia HUD',
    },
    showDailyCase: {
        ru: 'Показывать время до получения ежедневного кейса',
        ua: 'Показувати час до отримання щоденного кейсу',
        en: 'Show time until daily case is available',
        de: 'Zeit bis zur Verfügbarkeit der täglichen Kiste anzeigen',
        pl: 'Pokaż czas do otrzymania codziennej skrzynki',
    },
    showWeapon: {
        ru: 'Показывать оружие',
        ua: 'Показувати зброю',
        en: 'Show weapon',
        de: 'Waffe anzeigen',
        pl: 'Pokaż broń',
    },
    showHints: {
        ru: 'Показывать подсказки',
        ua: 'Показувати підказки',
        en: 'Show hints',
        de: 'Hinweise anzeigen',
        pl: 'Pokaż wskazówki',
    },
    customLogo: {
        ru: 'Кастомный логотип',
        ua: 'Кастомний логотип',
        en: 'Custom logo',
        de: 'Benutzerdefiniertes Logo',
        pl: 'Niestandardowe logo',
    },
    chatFontSize: {
        ru: 'Размер шрифта в чате',
        ua: 'Розмір шрифту в чаті',
        en: 'Chat font size',
        de: 'Schriftgröße im Chat',
        pl: 'Rozmiar czcionki w czacie',
    },
    chatInactiveTime: {
        ru: 'Время через которое будет исчезать чат (в секундах)',
        ua: 'Час через який чат буде зникати (у секундах)',
        en: 'Time after which the chat will disappear (in seconds)',
        de: 'Zeit, nach der der Chat verschwindet (in Sekunden)',
        pl: 'Czas po którym czat zniknie (w sekundach)',
    },
    chatShowTime: {
        ru: 'Показывать время в чате',
        ua: 'Показувати час у чаті',
        en: 'Show time in chat',
        de: 'Zeit im Chat anzeigen',
        pl: 'Pokazywać czas w czacie',
    },

    gameSettings: {
        ru: 'Настройки игры',
        ua: 'Налаштування гри',
        en: 'Game Settings',
        de: 'Spieleinstellungen',
        pl: 'Ustawienia gry',
    },
    keybinds: {
        ru: 'Назначение клавиш',
        ua: 'Призначення клавіш',
        en: 'Keybinds',
        de: 'Tastenbelegung',
        pl: 'Przypisanie klawiszy',
    },

    disableMusicPlayer: {
        ru: 'Отключить звук музыкальных плееров',
        ua: 'Вимкнути звук музичних плеєрів',
        en: 'Disable sound of music players',
        de: 'Ton von Musikplayern deaktivieren',
        pl: 'Wyłącz dźwięk odtwarzaczy muzyki',
    },
    interactionOutlineEnabled: {
        ru: 'Подсветка объектов при взаимодействии',
        ua: 'Підсвітка обʼєктів при взаємодії',
        en: 'Interaction object outline',
        de: 'Objektumrandung bei Interaktion',
        pl: 'Obrys obiektów podczas interakcji',
    },

    aspectRatio: {
        ru: 'Соотношение сторон',
        ua: 'Співвідношення сторін',
        en: 'Aspect ratio',
        de: 'Seitenverhältnis',
        pl: 'Współczynnik proporcji',
    },

    //

    avatar: {
        ru: 'Аватар',
        ua: 'Аватар',
        en: 'Avatar',
        de: 'Avatar',
        pl: 'Awatar',
    },
    avatarDesc: {
        ru: 'Ты можешь вставить прямую ссылку (URL) на картинку с почти любого фотохостинга (например, Imgur)',
        ua: 'Ти можеш вставити пряме посилання (URL) на зображення з майже будь-якого фотохостингу (наприклад, Imgur)',
        en: 'You can paste a direct image URL from almost any image host (e.g., Imgur)',
        de: 'Du kannst eine direkte Bild-URL von fast jedem Bildhoster einfügen (z. B. Imgur)',
        pl: 'Możesz wkleić bezpośredni adres URL obrazu z prawie każdego hostingu obrazów (np. Imgur)',
    },
    avatarApply: {
        ru: 'Применить',
        ua: 'Застосувати',
        en: 'Apply',
        de: 'Übernehmen',
        pl: 'Zastosuj',
    },
    disableOtherAvatars: {
        ru: 'Отображать аватары других игроков',
        ua: 'Показувати аватари інших гравців',
        en: 'Show other players’ avatars',
        de: 'Avatare anderer Spieler anzeigen',
        pl: 'Wyświetlaj awatary innych graczy',
    },
};
