export default {
    control: {
        ru: 'Чтобы открыть пульт ворот, нажмите',
        ua: 'Щоб відкрити пульт воріт, натисніть',
        en: 'To open the gate panel, press',
        de: 'Um das Torpult zu öffnen, drücke',
        pl: 'Aby otworzyć pulpit bramy, naciśnij',
    },
    nameMain: {
        ru: 'КПП «Главный въезд»',
        ua: "КПП «Головний в'їзд»",
        en: 'Main Gate Checkpoint',
        de: 'Kontrollpunkt Haupteinfahrt',
        pl: 'Punkt kontrolny - brama główna',
    },
    nameNorth: {
        ru: 'КПП «Северный въезд»',
        ua: "КПП «Північний в'їзд»",
        en: 'North Gate Checkpoint',
        de: 'Kontrollpunkt Nordeinfahrt',
        pl: 'Punkt kontrolny - brama północna',
    },
    stateOpened: {
        ru: 'Ворота открыты',
        ua: 'Ворота відчинені',
        en: 'The gate is open',
        de: 'Das Tor ist offen',
        pl: 'Brama jest otwarta',
    },
    stateClosed: {
        ru: 'Ворота закрыты',
        ua: 'Ворота зачинені',
        en: 'The gate is closed',
        de: 'Das Tor ist geschlossen',
        pl: 'Brama jest zamknięta',
    },
    actionOpen: {
        ru: 'Открыть',
        ua: 'Відчинити',
        en: 'Open',
        de: 'Öffnen',
        pl: 'Otwórz',
    },
    actionClose: {
        ru: 'Закрыть',
        ua: 'Зачинити',
        en: 'Close',
        de: 'Schließen',
        pl: 'Zamknij',
    },
    cancel: {
        ru: 'Отмена',
        ua: 'Скасувати',
        en: 'Cancel',
        de: 'Abbrechen',
        pl: 'Anuluj',
    },
    noAccess: {
        ru: 'Нет доступа к управлению воротами КПП',
        ua: 'Немає доступу до керування воротами КПП',
        en: 'No access to checkpoint gate controls',
        de: 'Kein Zugriff auf die Kontrollpunkt-Torsteuerung',
        pl: 'Brak dostępu do sterowania bramami punktu kontrolnego',
    },
    busy: {
        ru: 'Ворота ещё в движении, подожди',
        ua: 'Ворота ще в русі, зачекай',
        en: 'The gate is still moving, wait',
        de: 'Das Tor bewegt sich noch, warte',
        pl: 'Brama jeszcze się porusza, poczekaj',
    },
    labelOpened: {
        ru: 'Управление воротами\nВорота открыты',
        ua: 'Керування воротами\nВорота відчинені',
        en: 'Gate control\nGate is open',
        de: 'Torsteuerung\nTor ist offen',
        pl: 'Sterowanie bramą\nBrama otwarta',
    },
    labelClosed: {
        ru: 'Управление воротами\nВорота закрыты',
        ua: 'Керування воротами\nВорота зачинені',
        en: 'Gate control\nGate is closed',
        de: 'Torsteuerung\nTor ist geschlossen',
        pl: 'Sterowanie bramą\nBrama zamknięta',
    },
    labelMoving: {
        ru: 'Управление воротами\nВорота в движении',
        ua: 'Керування воротами\nВорота в русі',
        en: 'Gate control\nGate is moving',
        de: 'Torsteuerung\nTor bewegt sich',
        pl: 'Sterowanie bramą\nBrama w ruchu',
    },
};
