export default {
    gov: {
        dontUnderstandWhyHereLeave: {
            ru: 'Я не понял нахуй, ты что здесь делаешь? Брысь отсюда!',
            ua: 'Я не зрозумів нахуй, ти що тут робиш? Пішов звідси бистро!',
            en: `I don't fucking get it, what are you doing here? Get outta here!`,
            pl: 'Nie rozumiem, kurwa, co ty tu robisz? Wynoś się stąd!',
            de: `Ich kapier's nicht, was machst du hier? Raus mit dir!`,
           zh:'我他妈不明白，你在这里干什么?滚出去!',
        },
        sorry: {
            ru: 'Извини',
            ua: 'Вибач',
            en: 'Sorry',
            de: 'Entschuldigung',
            pl: 'Przepraszam',
            zh:'抱歉',
        },
        fuckYou: {
            ru: 'Пошёл нахуй',
            ua: 'Пішов нахуй..',
            en: 'Fuck you',
            de: 'Leck mich',
            pl: 'Spierdalaj',
           zh:'去你妈的',
        },
    },
    job: {
        heyLookingJobStealCarPayWell: {
            ru: 'Привет! Ищешь работу? Просто нужно украсть машину..',
            ua: 'Привіт! Шукаєш роботу? Просто треба вкрасти автомобіль...',
            en: 'Hey there! Looking for a job? Just need to steal a car, pay well!',
            de: 'Hallo! Auf der Suche nach Arbeit? Muss nur ein Auto stehlen, gut bezahlen!',
            pl: 'Cześć! Szukasz pracy? Wystarczy ukraść samochód, płacę dobrze!',
            zh:'嘿!在找工作吗?只需要偷一辆车，我会付一大笔钱',
        },
        moreInfo: {
            ru: 'Подробнее',
            ua: 'Детальніше',
            en: 'More Info',
            de: 'Mehr Info',
            pl: 'Więcej informacji',
            zh:'更多信息',
        },
        go: {
            ru: 'Давай',
            ua: 'Давай',
            en: 'Go',
            de: 'Los',
            pl: 'Idź',
           zh:'走',
        },
        //
        readyGoSendCoordinatesCarDetails: {
            ru: 'Да, тут все просто. Я даю тебе приблизные координаты машины, ее цвет, модель, а ты находишь ее и доставляешь на место. Ну что, ты готов?',
            ua: 'Так, тут все просто. Я даю тобі приблизні координати автомобіля, його колір, модель, а ти знаходиш його і доставляєш на місце. Ну, як, ти готовий?',
            en: `Yeah, it's simple. I give you approximate coordinates of the car, its color, model, and you find it and bring it to the location. So, are you ready?`,
            de: 'Ja, das ist einfach. Ich gebe dir ungefähre Koordinaten des Autos, seine Farbe, Modell, und du findest es und bringst es zum Zielort. Also, bist du bereit?',
            pl: 'Tak, to proste. Podaję ci przybliżone współrzędne samochodu, jego kolor, model, a ty go znajdujesz i dostarczasz pod wskazane miejsce. Czy jesteś gotowy?',
           zh:'是的，很简单。我给你车的大概坐标，颜色，型号，然后你找到它，把它带到指定地点。那么，你准备好了吗?',
        },
        yes: {
            ru: 'Да',
            ua: 'Так',
            en: 'Yes',
            de: 'Ja',
            pl: 'Tak',
            zh:'是的',
        },
        no: {
            ru: 'В другой раз',
            ua: 'Іншим разом',
            en: 'Another time',
            de: 'Ein anderes Mal',
            pl: 'Innym razem',
           zh:'下一次',
        },

        //
        OKWaitingSMSLocationDetails: {
            ru: 'Отлично! Скоро тебе придёт SMS с данными о местоположении и другой информацией, ожидай.',
            ua: 'Чудово! Незабаром тобі прийде SMS з даними про місцезнаходження та іншою інформацією, зачекай.',
            en: 'Great! You will soon receive an SMS with location details and other information, please wait.',
            de: 'Super! Du wirst bald eine SMS mit Standortdetails und anderen Informationen erhalten, bitte warte.',
            pl: 'Świetnie! Wkrótce otrzymasz SMS z danymi dotyczącymi lokalizacji i innymi informacjami, proszę czekać.',
            zh:'太棒了!您将很快收到一条包含位置详细信息和其他信息的短信，请稍候',
        },
        okay: {
            ru: 'Хорошо',
            ua: 'Добре',
            en: 'Okay',
            de: 'Okay',
            pl: 'Dobra',
           zh:'好吧',
        },
    },
    already: {
        stillHereGaveTaskLeave: {
            ru: 'Ты всё ещё тут? Я же тебе дал задание, проваливай',
            ua: 'Ти ще тут? Я ж тобі дав завдання, вали',
            en: 'Are you still here? I gave you a task, get out',
            de: 'Bist du immer noch hier? Ich habe dir eine Aufgabe gegeben, verschwinde',
            pl: 'Jesteś jeszcze tutaj? Dałem ci zadanie, wynoś się',
            zh:'你怎么还在这里?给我滚去做任务！',
        },
        ahYes: {
            ru: 'Забыл уже',
            ua: 'Вже забув',
            en: 'Forgot already',
            de: 'Schon vergessen',
            pl: 'Już zapomniałem',
            zh:'你已经忘了我',
        },
        bye: {
            ru: 'Хорошо',
            ua: 'Добре',
            en: 'Okay',
            de: 'Gut',
            pl: 'Dobrze',
           zh:'好吧',
        },
    },
    cooldown: {
        yoWait: {
            ru: 'Йоу бро, подожди {{minutes}} минут и тогда я смогу дать тебе новую работу!',
            ua: 'Йоу бро, зачекай {{minutes}} хвилин і тоді я зможу дати тобі нову роботу!',
            en: 'Yo bro, wait {{minutes}} minutes and then I can give you a new job!',
            de: 'Yo Bro, warte {{minutes}} Minuten und dann kann ich dir einen neuen Job geben!',
            pl: 'Yo bro, poczekaj {{minutes}} minut i wtedy będę mógł dać ci nową robotę!',
           zh:'嘿，兄弟，等{{minutes}}分钟，然后我可以给你一份新工作',


',
        },
        ok: {
            ru: 'Ладно',
            ua: 'Гаразд',
            en: 'Okay',
            de: 'Okay',
            pl: 'Ok',
           zh:'好吧',
        },
    },
};
