import dialogs from './dialogs';

export default {
    dialogs,
    waitSMS: {
        ru: 'Ожидай СМС',
        ua: 'Очікуй СМС',
        en: 'Wait for SMS',
        de: 'Warte auf SMS',
        pl: 'Czekaj na SMS',
        zh: '请等待短信',
    },
    // Так называемое разнообразие
    order1: {
        ru: 'Здарова! Сегодня у нас {{model}}, цвет {{color}}, номера {{plate}}. Приблизительные данные у тебя на карте, поторопись.',
        ua: 'Здоров! Сьогодні у нас {{model}}, колір {{color}}, номери {{plate}}. Приблизні дані в тебе на мапі, поспішай.',
        en: 'Hey! Today we’ve got a {{model}}, color {{color}}, plates {{plate}}. Approximate info is on your map, hurry up.',
        de: 'Hey! Heute haben wir einen {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Ungefähre Angaben findest du auf der Karte, beeil dich.',
        pl: 'Siema! Dziś mamy {{model}}, kolor {{color}}, tablice {{plate}}. Przybliżone dane masz na mapie, pośpiesz się.',
    },
    order2: {
        ru: 'Йо, брат! Сегодняшняя цель — {{model}}, цвет {{color}}, номера {{plate}}. Глянь на карту и действуй быстро.',
        ua: 'Йо, брате! Сьогоднішня ціль — {{model}}, колір {{color}}, номери {{plate}}. Глянь на мапу й дій швидко.',
        en: 'Yo, bro! Today’s target is {{model}}, color {{color}}, plates {{plate}}. Check the map and move fast.',
        de: 'Yo, Bruder! Das heutige Ziel ist ein {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Schau auf die Karte und handle schnell.',
        pl: 'Jo, bracie! Dzisiejszy cel to {{model}}, kolor {{color}}, tablice {{plate}}. Sprawdź mapę i działaj szybko.',
    },
    order3: {
        ru: 'Эй! Сегодня в фокусе {{model}}, цвет {{color}}, номера {{plate}}. Координаты примерно есть, не тупи.',
        ua: 'Гей! Сьогодні в фокусі {{model}}, колір {{color}}, номери {{plate}}. Координати приблизно є, не гальмуй.',
        en: 'Hey! Today’s focus is on {{model}}, color {{color}}, plates {{plate}}. Coordinates are roughly known, don’t stall.',
        de: 'Hey! Heute im Fokus: {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Ungefährer Standort ist bekannt, nicht trödeln.',
        pl: 'Hej! Dziś na celowniku {{model}}, kolor {{color}}, tablice {{plate}}. Miejsce mniej więcej znane, nie ociągaj się.',
    },
    order4: {
        ru: 'Слушай сюда! У нас {{model}} цвета {{color}}, номера {{plate}}. Инфу найдёшь на карте, давай быстрее.',
        ua: 'Слухай сюди! У нас {{model}} кольору {{color}}, номери {{plate}}. Інфу знайдеш на мапі, давай швидше.',
        en: 'Listen up! We\'ve got a {{model}} in {{color}}, plates {{plate}}. Info is on the map, move it.',
        de: 'Hör zu! Wir haben einen {{model}} in Farbe {{color}}, Kennzeichen {{plate}}. Infos findest du auf der Karte, los jetzt.',
        pl: 'Słuchaj! Mamy {{model}} koloru {{color}}, tablice {{plate}}. Info znajdziesz na mapie, rusz się.',
    },
    order5: {
        ru: 'На выезде сегодня {{model}}, цвет {{color}}, номера {{plate}}. Глянь карту — и не тормози.',
        ua: 'На виїзді сьогодні {{model}}, колір {{color}}, номери {{plate}}. Подивись мапу — і не гальмуй.',
        en: 'On the move today: {{model}}, color {{color}}, plates {{plate}}. Check the map — and don’t slow down.',
        de: 'Heute unterwegs: {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Schau auf die Karte — und nicht trödeln.',
        pl: 'Dziś na wyjeździe {{model}}, kolor {{color}}, tablice {{plate}}. Sprawdź mapę — i nie zwlekaj.',
    },
    order6: {
        ru: 'У нас тут {{model}} в цвете {{color}}, номера {{plate}}. Всё на карте, двигай.',
        ua: 'У нас тут {{model}} кольору {{color}}, номери {{plate}}. Все є на мапі, рухайся.',
        en: 'We\'ve got a {{model}} in {{color}}, plates {{plate}}. Everything’s on the map, move.',
        de: 'Hier ist ein {{model}} in Farbe {{color}}, Kennzeichen {{plate}}. Alles ist auf der Karte, los geht’s.',
        pl: 'Mamy tutaj {{model}} w kolorze {{color}}, tablice {{plate}}. Wszystko jest na mapie, ruszaj.',
    },
    order7: {
        ru: '{{model}} сегодня в работе, цвет {{color}}, номера {{plate}}. Место отмечено на карте, не зевай.',
        ua: '{{model}} сьогодні в роботі, колір {{color}}, номери {{plate}}. Місце позначено на мапі, не зевай.',
        en: '{{model}} is the job today, color {{color}}, plates {{plate}}. Location is marked on the map, stay sharp.',
        de: '{{model}} ist heute dran, Farbe {{color}}, Kennzeichen {{plate}}. Ort ist auf der Karte markiert, sei wachsam.',
        pl: '{{model}} dziś w robocie, kolor {{color}}, tablice {{plate}}. Miejsce zaznaczone na mapie, nie śpij.',
    },
    order8: {
        ru: 'Залетай! Работаем по {{model}}, цвет {{color}}, номера {{plate}}. Карта тебе в помощь.',
        ua: 'Залітай! Працюємо по {{model}}, колір {{color}}, номери {{plate}}. Карта допоможе.',
        en: 'Jump in! We’re working on {{model}}, color {{color}}, plates {{plate}}. Use the map.',
        de: 'Komm rein! Wir arbeiten an einem {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Die Karte hilft dir.',
        pl: 'Wpadaj! Pracujemy nad {{model}}, kolor {{color}}, tablice {{plate}}. Mapa ci pomoże.',
    },
    order9: {
        ru: 'Цель на сегодня — {{model}}, цвет {{color}}, номера {{plate}}. Место примерно известно, поторопись.',
        ua: 'Ціль на сьогодні — {{model}}, колір {{color}}, номери {{plate}}. Місце приблизно відоме, поспішай.',
        en: 'Today’s target — {{model}}, color {{color}}, plates {{plate}}. Place is roughly known, hurry up.',
        de: 'Das heutige Ziel — {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Ort ist ungefähr bekannt, beeil dich.',
        pl: 'Dzisiejszy cel — {{model}}, kolor {{color}}, tablice {{plate}}. Miejsce mniej więcej znane, pośpiesz się.',
    },
    order10: {
        ru: 'Сегодня в деле {{model}}, цвет {{color}}, номера {{plate}}. Всё, что нужно — уже есть на карте.',
        ua: 'Сьогодні в справі {{model}}, колір {{color}}, номери {{plate}}. Все, що треба — вже на мапі.',
        en: '{{model}} is in action today, color {{color}}, plates {{plate}}. Everything you need is already on the map.',
        de: '{{model}} ist heute im Einsatz, Farbe {{color}}, Kennzeichen {{plate}}. Alles Notwendige ist schon auf der Karte.',
        pl: '{{model}} dziś w akcji, kolor {{color}}, tablice {{plate}}. Wszystko, czego trzeba — już na mapie.',
    },

    orderTuned1: {
        ru: 'Здарова! Сегодня у нас тюнингованная {{model}}, цвет {{color}}, номера {{plate}}. Примерная точка на карте, действуй.',
        ua: 'Здоров! Сьогодні у нас тюнінгована {{model}}, колір {{color}}, номери {{plate}}. Приблизна точка на мапі, дій.',
        en: 'Hey! Today we’ve got a tuned {{model}}, color {{color}}, plates {{plate}}. Approximate spot is on the map, move.',
        de: 'Hey! Heute haben wir einen getunten {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Ungefähre Position auf der Karte, los geht’s.',
        pl: 'Siema! Dziś mamy stuningowane {{model}}, kolor {{color}}, tablice {{plate}}. Przybliżony punkt na mapie, działaj.',
    },
    orderTuned2: {
        ru: 'Йо! В городе замечена прокачанная {{model}}, цвет {{color}}, номера {{plate}}. Координаты у тебя на карте.',
        ua: 'Йо! У місті помічена прокачана {{model}}, колір {{color}}, номери {{plate}}. Координати на мапі.',
        en: 'Yo! A modded {{model}} spotted in the city, color {{color}}, plates {{plate}}. Coordinates are on your map.',
        de: 'Yo! In der Stadt wurde ein getunter {{model}} gesehen, Farbe {{color}}, Kennzeichen {{plate}}. Koordinaten hast du auf der Karte.',
        pl: 'Jo! W mieście zauważono podrasowane {{model}}, kolor {{color}}, tablice {{plate}}. Koordynaty są na mapie.',
    },
    orderTuned3: {
        ru: 'Слышь, дело срочное — тюнингованная {{model}}, цвет {{color}}, номера {{plate}}. Место примерно известно, шевелись.',
        ua: 'Чуєш, справа термінова — тюнінгована {{model}}, колір {{color}}, номери {{plate}}. Місце приблизно відоме, рушай.',
        en: 'Listen, urgent job — tuned {{model}}, color {{color}}, plates {{plate}}. Location is roughly known, get moving.',
        de: 'Hör zu, das ist dringend — getunter {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Ort ist ungefähr bekannt, los!',
        pl: 'Słuchaj, sprawa pilna — stuningowane {{model}}, kolor {{color}}, tablice {{plate}}. Miejsce mniej więcej znane, ruszaj się.',
    },
    orderTuned4: {
        ru: 'Брат, на радаре тюнингованная {{model}}, цвет {{color}}, номера {{plate}}. Метка есть, не тупи.',
        ua: 'Брате, на радарі тюнінгована {{model}}, колір {{color}}, номери {{plate}}. Мітка є, не гальмуй.',
        en: 'Bro, a tuned {{model}} is on the radar, color {{color}}, plates {{plate}}. Mark is there, don’t lag.',
        de: 'Bruder, ein getunter {{model}} ist auf dem Radar, Farbe {{color}}, Kennzeichen {{plate}}. Markierung ist da, trödel nicht.',
        pl: 'Bracie, na radarze stuningowane {{model}}, kolor {{color}}, tablice {{plate}}. Znacznik jest, nie ociągaj się.',
    },
    orderTuned5: {
        ru: 'Сегодня цель — заряженная {{model}}, цвет {{color}}, номера {{plate}}. Глянь на карту и выдвигайся.',
        ua: 'Сьогодні ціль — заряджена {{model}}, колір {{color}}, номери {{plate}}. Подивись на мапу й рушай.',
        en: 'Today’s target — souped-up {{model}}, color {{color}}, plates {{plate}}. Check the map and roll out.',
        de: 'Heutiges Ziel — aufgemotzter {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Schau auf die Karte und los!',
        pl: 'Dzisiejszy cel — podrasowane {{model}}, kolor {{color}}, tablice {{plate}}. Sprawdź mapę i ruszaj.',
    },
    orderTuned6: {
        ru: 'Вижу тюнингованную {{model}}, цвет {{color}}, номера {{plate}}. Инфа на карте, время не жди.',
        ua: 'Бачу тюнінговану {{model}}, колір {{color}}, номери {{plate}}. Інфа на мапі, не гай часу.',
        en: 'I see a tuned {{model}}, color {{color}}, plates {{plate}}. Info’s on the map, don’t wait.',
        de: 'Sehe einen getunten {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Infos sind auf der Karte, verlier keine Zeit.',
        pl: 'Widzę stuningowane {{model}}, kolor {{color}}, tablice {{plate}}. Info jest na mapie, nie czekaj.',
    },
    orderTuned7: {
        ru: 'Сегодня охотимся на тюнингованную {{model}} — цвет {{color}}, номера {{plate}}. Координаты у тебя, двигай!',
        ua: 'Сьогодні полюємо на тюнінговану {{model}} — колір {{color}}, номери {{plate}}. Координати в тебе, рухайся!',
        en: 'Today we’re hunting a tuned {{model}} — color {{color}}, plates {{plate}}. You’ve got the coordinates, go!',
        de: 'Heute jagen wir einen getunten {{model}} — Farbe {{color}}, Kennzeichen {{plate}}. Koordinaten hast du, los!',
        pl: 'Dziś polujemy na stuningowane {{model}} — kolor {{color}}, tablice {{plate}}. Masz koordynaty, ruszaj!',
    },
    orderTuned8: {
        ru: 'Внимание! Прокачанная {{model}}, цвет {{color}}, номера {{plate}}. Примерное местоположение на карте.',
        ua: 'Увага! Прокачана {{model}}, колір {{color}}, номери {{plate}}. Приблизне місце на мапі.',
        en: 'Attention! Modded {{model}}, color {{color}}, plates {{plate}}. Approximate location is on the map.',
        de: 'Achtung! Getunter {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Ungefährer Standort ist auf der Karte.',
        pl: 'Uwaga! Podrasowane {{model}}, kolor {{color}}, tablice {{plate}}. Przybliżona lokalizacja na mapie.',
    },
    orderTuned9: {
        ru: 'Залетай! Цель — тюнингованная {{model}}, цвет {{color}}, номера {{plate}}. Всё отмечено, не зевай.',
        ua: 'Залітай! Ціль — тюнінгована {{model}}, колір {{color}}, номери {{plate}}. Все відмічено, не зевай.',
        en: 'Jump in! Target — tuned {{model}}, color {{color}}, plates {{plate}}. Everything’s marked, stay alert.',
        de: 'Komm rein! Ziel — getunter {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Alles markiert, bleib wach.',
        pl: 'Wpadaj! Cel — stuningowane {{model}}, kolor {{color}}, tablice {{plate}}. Wszystko zaznaczone, nie śpij.',
    },
    orderTuned10: {
        ru: 'На сегодня у нас заряженная {{model}}, цвет {{color}}, номера {{plate}}. Примерная позиция есть, поторопись.',
        ua: 'Сьогодні у нас заряджена {{model}}, колір {{color}}, номери {{plate}}. Приблизна позиція є, поспішай.',
        en: 'Today we’ve got a souped-up {{model}}, color {{color}}, plates {{plate}}. Approximate location is known, hurry.',
        de: 'Heute haben wir einen aufgemotzten {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Ungefähre Position ist bekannt, beeil dich.',
        pl: 'Dziś mamy podrasowane {{model}}, kolor {{color}}, tablice {{plate}}. Przybliżona pozycja znana, pośpiesz się.',
    },

    dropOffPerfect: {
        ru: 'Отлично! Ты справился с заданием, ты заработал: ${{salary}} + ${{bonus}} бонус за отсутствие повреждений.',
        ua: 'Відмінно! Ти впорався із завданням, ти заробив: ${{salary}} + ${{bonus}} бонус за відсутність пошкоджень.',
        en: 'Great! You completed the task, you earned: ${{salary}} + ${{bonus}} bonus for no damage.',
        de: 'Großartig! Du hast die Aufgabe geschafft, du hast verdient: ${{salary}} + ${{bonus}} Bonus für keine Schäden.',
        pl: 'Świetnie! Udało ci się wykonać zadanie, zarobiłeś: ${{salary}} + ${{bonus}} premia za brak uszkodzeń.',
    },
    dropOffBad: {
        ru: 'Ты справился с заданием почти идеально. Ты заработал: ${{salary}} - ${{penalty}} штраф за повреждения.',
        ua: 'Ти впорався із завданням майже ідеально. Ти заробив: ${{salary}} - ${{penalty}} штраф за пошкодження.',
        en: 'You almost completed the task perfectly. You earned: ${{salary}} - ${{penalty}} penalty for damage.',
        de: 'Du hast die Aufgabe fast perfekt geschafft. Du hast verdient: ${{salary}} - ${{penalty}} Strafe für Schäden.',
        pl: 'Prawie idealnie wykonałeś zadanie. Zarobiłeś: ${{salary}} - ${{penalty}} kara za uszkodzenia.',
    },
    smsDropOff: {
        ru: 'Я вижу ты успешно доставил машину как я хотел, держи бесплатную доставку личной машины!',
        ua: 'Я бачу, ти успішно доставив машину, як я хотів, тримай безкоштовну доставку особистого автомобіля!',
        en: 'I see you successfully delivered the car as I wanted, enjoy a free personal car delivery!',
        de: 'Ich sehe, dass du das Auto erfolgreich geliefert hast, wie ich es wollte, hier ist eine kostenlose Lieferung eines persönlichen Autos!',
        pl: 'Widzę, że dostarczyłeś samochód zgodnie z moimi oczekiwaniami, oto darmowa dostawa osobistego samochodu!',
        zh: '我看到你按我的要求成功送货，享受免费送货上门!',
    },
    smsBrokenWindow: {
        ru: 'За кражу машины путём взлома окна мы платим в двое меньше, так что научись взламывать машину без следов.',
        ua: 'За крадіжку машини шляхом злому вікна ми платимо вдвічі менше, тож навчися зламувати машину без слідів.',
        en: 'For stealing a car by breaking the window, we pay half as much, so learn to steal a car without leaving traces.',
        de: 'Für den Diebstahl eines Autos durch das Einschlagen eines Fensters zahlen wir nur die Hälfte, also lerne, ein Auto ohne Spuren zu stehlen.',
        pl: 'Za kradzież samochodu przez wybicie szyby płacimy o połowę mniej, więc naucz się kraść samochód bez zostawiania śladów.',
    },
    carStolen: {
        ru: 'Внимание! Сообщено про угон автомобиля. Модель: {{model}}, номер: {{plate}}. Просьба усилить бдительность.',
        ua: 'Увага! Повідомлено про викрадення автомобіля. Модель: {{model}}, номер: {{plate}}. Просимо бути пильними.',
        en: 'Attention! A car theft has been reported. Model: {{model}}, plate: {{plate}}. Please stay alert.',
        de: 'Achtung! Ein Autodiebstahl wurde gemeldet. Modell: {{model}}, Kennzeichen: {{plate}}. Bitte seien Sie wachsam.',
        pl: 'Uwaga! Zgłoszono kradzież samochodu. Model: {{model}}, numer rejestracyjny: {{plate}}. Prosimy o czujność.',
    },
    messageForPoliceman: {
        ru: 'Отвезите угнаную машину в специальное место чтобы получить премию!',
        ua: 'Відвезіть викрадену машину в спеціальне місце щоб отримати премію!',
        en: 'Take the stolen car to a special place to get a reward!',
        de: 'Bringen Sie das gestohlene Auto an einen besonderen Ort, um eine Belohnung zu erhalten!',
        pl: 'Zawieź skradziony samochód do specjalnego miejsca, aby otrzymać nagrodę!',
        zh: '把偷来的车带到一个特别的地方换钱!',
    },
    policemanModal: {
        title: {
            ru: 'Успешная работа',
            ua: 'Успішна робота',
            en: 'Successful work',
            de: 'Erfolgreiche Arbeit',
            pl: 'Udane prace',
            zh: '干得好',
        },
        message: {
            ru: 'Вы смогли найти угнаный автомобиль, поздравляем! Ваша награда: ${{salary}}.',
            ua: 'Ви змогли знайти викрадений автомобіль, вітаємо! Ваша нагорода: ${{salary}}.',
            en: 'You were able to find the stolen car, congratulations! Your reward: ${{salary}}.',
            de: 'Du hast das gestohlene Auto gefunden, herzlichen Glückwunsch! Deine Belohnung: ${{salary}}.',
            pl: 'Udało ci się znaleźć skradziony samochód, gratulacje! Twoja nagroda: ${{salary}}.',
            zh: '你找到了被偷的车，恭喜你!你的报酬:${{salary}}',
        },
        confirmButton: {
            ru: 'Спасибо',
            ua: 'Дякую',
            en: 'Thank you',
            de: 'Danke',
            pl: 'Dziękuję',
            zh: '谢谢',
        },
    },
    cooldown: {
        ru: 'Подождите {{time}}',
        ua: 'Зачекайте {{time}}',
        en: 'Wait {{time}}',
        de: 'Warten Sie {{time}}',
        pl: 'Czekaj {{time}}',
        zh: '等待{{time}}',
    },
    noFreePosition: {
        ru: 'Попробуйте позже',
        ua: 'Спробуйте пізніше',
        en: 'Try again later',
        de: 'Versuche es später noch einmal',
        pl: 'Spróbuj ponownie później',
        zh: '请稍后在尝试',
    },

    //
    header: {
        ru: 'Автоугонщик',
        ua: 'Автовикрадач',
        en: 'Car Thief',
        de: 'Autodieb',
        pl: 'Złodziej samochodów',
    },
    timeLeft: {
        ru: 'Времени осталось',
        ua: 'Часу залишилося',
        en: 'Time Left',
        de: 'Verbleibende Zeit',
        pl: 'Pozostało czasu',
    },

    //
    hudAction: {
        ru: 'Начать взлом',
        ua: 'Почати злам',
        en: 'Start hacking',
        de: 'Hacken starten',
        pl: 'Rozpocznij hakowanie',
    },
    noLockPick: {
        ru: 'У вас нет отмычки',
        ua: 'У вас немає відмички',
        en: 'You don\'t have a lockpick',
        de: 'Du hast kein Dietrich',
        pl: 'Nie masz wytrychu',
    },
    yourLockpickBroken: {
        ru: 'Ваша отмычка сломалась',
        ua: 'Ваша відмичка зламалась',
        en: 'Your lockpick broke',
        de: 'Dein Dietrich ist zerbrochen',
        pl: 'Twoje wytrychy się złamały',
    },
    youHackedLockpick: {
        ru: 'Вы взломали замок отмычкой',
        ua: 'Ви зламали замок відмичкою',
        en: 'You picked the lock',
        de: 'Du hast das Schloss geknackt',
        pl: 'Otworzyłeś zamek wytrychem',
    },
    youHackedEngine: {
        ru: 'Вы смогли завезти двигатель',
        ua: 'Вам вдалося завести двигун',
        en: 'You managed to start the engine',
        de: 'Du konntest den Motor starten',
        pl: 'Udało ci się uruchomić silnik',
    },
    vehiclePdBlip: {
        ru: 'Угнанное авто',
        ua: 'Викрадене авто',
        en: 'Stolen vehicle',
        de: 'Gestohlenes Fahrzeug',
        pl: 'Skradziony pojazd',
    },

    //
    "timeOutSms": {
        "ru": "Похоже ты не успел доставить машину во время, ты подвёл нас.",
        "ua": "Схоже, ти не встиг доставити машину вчасно, ти підвів нас.",
        "en": "Looks like you didn't deliver the car in time, you let us down.",
        "de": "Sieht so aus, als hättest du das Auto nicht rechtzeitig geliefert – du hast uns enttäuscht.",
        "pl": "Wygląda na to, że nie dostarczyłeś auta na czas, zawiodłeś nas.",
    },
    "vehicleDeathSms": {
        "ru": "Машину, которую ты должен был привезти в целости и сохранности, ты каким-то чудом уничтожил, задание провалено",
        "ua": "Машину, яку ти мав привезти цілою й неушкодженою, ти якимось дивом знищив — завдання провалено.",
        "en": "The car you were supposed to deliver safe and sound—you somehow destroyed it. Mission failed.",
        "de": "Das Auto, das du heil liefern solltest, hast du irgendwie zerstört – Auftrag gescheitert.",
        "pl": "Auto, które miałeś dostarczyć w jednym kawałku, jakoś zniszczyłeś – misja nieudana.",
    },
    "evacuationWorkSms": {
        "ru": "Похоже тебя схватили копы, я тебя не знаю",
        "ua": "Схоже, тебе впіймали копи, я тебе не знаю.",
        "en": "Looks like the cops caught you. I don't know you.",
        "de": "Sieht so aus, als hätten dich die Cops geschnappt. Ich kenn dich nicht.",
        "pl": "Wygląda na to, że złapali cię gliniarze. Nie znam cię.",
    },
};
