import dialogs from './dialogs';

export default {
    dialogs,
    waitSMS: {
        ru: 'Ожидай СМС',
        ua: 'Очікуй СМС',
        en: 'Wait for SMS',
        de: 'Warte auf SMS',
        pl: 'Czekaj na SMS',
        zh: '请等待短信',
    },
    order: {
        ru: 'Здарова! Сегодня у нас {{model}}, цвет {{color}}, номера {{plate}}. Приблизительные данные у тебя на карте, поторопись.',
        ua: 'Привіт! Сьогодні у нас {{model}}, колір {{color}}, номери {{plate}}. Приблизні дані у тебе на карті, поспішай.',
        en: 'Hello! Today we have {{model}}, color {{color}}, plates {{plate}}. Approximate data is on your map, hurry up.',
        de: 'Hallo! Heute haben wir {{model}}, Farbe {{color}}, Nummernschilder {{plate}}. Ungefähre Daten sind auf Ihrer Karte, beeilen Sie sich.',
        pl: 'Cześć! Dzisiaj mamy {{model}}, kolor {{color}}, tablice rejestracyjne {{plate}}. Przybliżone dane są na twojej mapie, pospiesz się.',
        zh: '你好！今天我们有{{model}}，颜色{{color}}，车牌号{{plate}}. 大致位置在您的地图上，快点过来吧！',
    },
    orderTuned: {
        ru: 'Здарова! Сегодня у нас тюнингованая {{model}}, цвет {{color}}, номера {{plate}}. Приблизительные данные у тебя на карте, поторопись.',
        ua: 'Здоров! Сьогодні у нас тюнінгована {{model}}, колір {{color}}, номери {{plate}}. Приблизні дані у тебе на карті, поспішай.',
        en: 'Hey there! Today we have a tuned {{model}}, color {{color}}, plates {{plate}}. Approximate data is on your map, hurry up.',
        de: 'Hallo! Heute haben wir ein getuntes {{model}}, Farbe {{color}}, Kennzeichen {{plate}}. Ungefähre Daten findest du auf deiner Karte, beeil dich.',
        pl: 'Cześć! Dzisiaj mamy stuningowany {{model}}, kolor {{color}}, tablice {{plate}}. Przybliżone dane masz na mapie, pospiesz się.',
    },
    dropOffPerfect: {
        ru: 'Отлично! Ты справился с заданием, ты заработал: ${{salary}} + ${{bonus}} бонус за отсутствие повреждений.',
        ua: 'Відмінно! Ти впорався із завданням, ти заробив: ${{salary}} + ${{bonus}} бонус за відсутність пошкоджень.',
        en: 'Great! You completed the task, you earned: ${{salary}} + ${{bonus}} bonus for no damage.',
        de: 'Großartig! Du hast die Aufgabe geschafft, du hast verdient: ${{salary}} + ${{bonus}} Bonus für keine Schäden.',
        pl: 'Świetnie! Udało ci się wykonać zadanie, zarobiłeś: ${{salary}} + ${{bonus}} premia za brak uszkodzeń.',
    },
    dropOffBad: {
        ru: 'Ты справился с заданием почти идеально. Ты заработал: ${{salary}} - ${{penalty}} штраф за повреждения.',
        ua: 'Ти впорався із завданням майже ідеально. Ти заробив: ${{salary}} - ${{penalty}} штраф за пошкодження.',
        en: 'You almost completed the task perfectly. You earned: ${{salary}} - ${{penalty}} penalty for damage.',
        de: 'Du hast die Aufgabe fast perfekt geschafft. Du hast verdient: ${{salary}} - ${{penalty}} Strafe für Schäden.',
        pl: 'Prawie idealnie wykonałeś zadanie. Zarobiłeś: ${{salary}} - ${{penalty}} kara za uszkodzenia.',
    },
    smsDropOff: {
        ru: 'Я вижу ты успешно доставил машину как я хотел, держи бесплатную доставку личной машины!',
        ua: 'Я бачу, ти успішно доставив машину, як я хотів, тримай безкоштовну доставку особистого автомобіля!',
        en: 'I see you successfully delivered the car as I wanted, enjoy a free personal car delivery!',
        de: 'Ich sehe, dass du das Auto erfolgreich geliefert hast, wie ich es wollte, hier ist eine kostenlose Lieferung eines persönlichen Autos!',
        pl: 'Widzę, że dostarczyłeś samochód zgodnie z moimi oczekiwaniami, oto darmowa dostawa osobistego samochodu!',
        zh: '我看到你按我的要求成功送货，享受免费送货上门!',
    },
    smsBrokenWindow: {
        ru: 'За кражу машины путём взлома окна мы платим в двое меньше, так что научись взламывать машину без следов.',
        ua: 'За крадіжку машини шляхом злому вікна ми платимо вдвічі менше, тож навчися зламувати машину без слідів.',
        en: 'For stealing a car by breaking the window, we pay half as much, so learn to steal a car without leaving traces.',
        de: 'Für den Diebstahl eines Autos durch das Einschlagen eines Fensters zahlen wir nur die Hälfte, also lerne, ein Auto ohne Spuren zu stehlen.',
        pl: 'Za kradzież samochodu przez wybicie szyby płacimy o połowę mniej, więc naucz się kraść samochód bez zostawiania śladów.',
    },
    carStolen: {
        ru: 'Внимание! Сообщено про угон автомобиля. Модель: {{model}}, номер: {{plate}}. Просьба усилить бдительность.',
        ua: 'Увага! Повідомлено про викрадення автомобіля. Модель: {{model}}, номер: {{plate}}. Просимо бути пильними.',
        en: 'Attention! A car theft has been reported. Model: {{model}}, plate: {{plate}}. Please stay alert.',
        de: 'Achtung! Ein Autodiebstahl wurde gemeldet. Modell: {{model}}, Kennzeichen: {{plate}}. Bitte seien Sie wachsam.',
        pl: 'Uwaga! Zgłoszono kradzież samochodu. Model: {{model}}, numer rejestracyjny: {{plate}}. Prosimy o czujność.',
    },
    messageForPoliceman: {
        ru: 'Отвезите угнаную машину в специальное место чтобы получить премию!',
        ua: 'Відвезіть викрадену машину в спеціальне місце щоб отримати премію!',
        en: 'Take the stolen car to a special place to get a reward!',
        de: 'Bringen Sie das gestohlene Auto an einen besonderen Ort, um eine Belohnung zu erhalten!',
        pl: 'Zawieź skradziony samochód do specjalnego miejsca, aby otrzymać nagrodę!',
        zh: '把偷来的车带到一个特别的地方换钱!',
    },
    policemanModal: {
        title: {
            ru: 'Успешная работа',
            ua: 'Успішна робота',
            en: 'Successful work',
            de: 'Erfolgreiche Arbeit',
            pl: 'Udane prace',
            zh: '干得好',
        },
        message: {
            ru: 'Вы смогли найти угнаный автомобиль, поздравляем! Ваша награда: ${{salary}}.',
            ua: 'Ви змогли знайти викрадений автомобіль, вітаємо! Ваша нагорода: ${{salary}}.',
            en: 'You were able to find the stolen car, congratulations! Your reward: ${{salary}}.',
            de: 'Sie haben das gestohlene Auto gefunden, herzlichen Glückwunsch! Ihre Belohnung: ${{salary}}.',
            pl: 'Udało ci się znaleźć skradziony samochód, gratulacje! Twoja nagroda: ${{salary}}.',
            zh: '你找到了被偷的车，恭喜你!你的报酬:${{salary}}',
        },
        confirmButton: {
            ru: 'Спасибо',
            ua: 'Дякую',
            en: 'Thank you',
            de: 'Danke',
            pl: 'Dziękuję',
            zh: '谢谢',
        },
    },
    cooldown: {
        ru: 'Подождите {{time}}',
        ua: 'Зачекайте {{time}}',
        en: 'Wait {{time}}',
        de: 'Warten Sie {{time}}',
        pl: 'Czekaj {{time}}',
        zh: '等待{{time}}',
    },
    noFreePosition: {
        ru: 'Попробуйте позже',
        ua: 'Спробуйте пізніше',
        en: 'Try again later',
        de: 'Versuchen Sie es später noch einmal',
        pl: 'Spróbuj ponownie później',
        zh: '请稍后在尝试',
    },

    //
    header: {
        ru: 'Автоугонщик',
        ua: 'Автовикрадач',
        en: 'Car Thief',
        de: 'Autodieb',
        pl: 'Złodziej samochodów',
    },
    timeLeft: {
        ru: 'Времени осталось',
        ua: 'Часу залишилося',
        en: 'Time Left',
        de: 'Verbleibende Zeit',
        pl: 'Pozostało czasu',
    },

    //
    hudAction: {
        ru: 'Начать взлом',
        ua: 'Почати злам',
        en: 'Start hacking',
        de: 'Hacken starten',
        pl: 'Rozpocznij hakowanie',
    },
    noLockPick: {
        ru: 'У вас нет отмычки',
        ua: 'У вас немає відмички',
        en: "You don't have a lockpick",
        de: 'Du hast kein Dietrich',
        pl: 'Nie masz wytrychu',
    },
    yourLockpickBroken: {
        ru: 'Ваша отмычка сломалась',
        ua: 'Ваша відмичка зламалась',
        en: 'Your lockpick broke',
        de: 'Dein Dietrich ist zerbrochen',
        pl: 'Twoje wytrychy się złamały',
    },
};
