export const object = {
    header: {
        ru: 'Объект',
        ua: "Об'єкт",
        en: 'Object',
        de: 'Objekt',
        pl: 'Obiekt',
        zh: '物体',
    },
    remove: {
        ru: 'Убрать',
        ua: 'Прибрати',
        en: 'Remove',
        de: 'Entfernen',
        pl: 'Usuń',
        zh: '移除',
    },
    placeMeat: {
        ru: 'Положить мясо',
        ua: "Покласти м'ясо",
        en: 'Place meat',
        de: 'Fleisch auflegen',
        pl: 'Połóż mięso',
        zh: '放上肉',
    },
    cook: {
        ru: 'Готовить',
        ua: 'Готувати',
        en: 'Cook',
        de: 'Kochen',
        pl: 'Gotuj',
        zh: '烹饪',
    },
    takeMeat: {
        ru: 'Забрать мясо',
        ua: "Забрати м'ясо",
        en: 'Take meat',
        de: 'Fleisch nehmen',
        pl: 'Zabierz mięso',
        zh: '拿走肉',
    },
    startSelling: {
        ru: 'Начать продавать',
        ua: 'Почати продавати',
        en: 'Start selling',
        de: 'Verkauf starten',
        pl: 'Rozpocznij sprzedaż',
        zh: '开始出售',
    },
    buyMeat: {
        ru: 'Купить мясо',
        ua: "Купити м'ясо",
        en: 'Buy meat',
        de: 'Fleisch kaufen',
        pl: 'Kup mięso',
        zh: '购买肉',
    },
    takeSpecificMeat: {
        ru: 'Забрать {{meatName}}',
        ua: 'Забрати {{meatName}}',
        en: 'Take {{meatName}}',
        de: '{{meatName}} nehmen',
        pl: 'Zabierz {{meatName}}',
        zh: '拿走{{meatName}}',
    },
    buySpecificMeat: {
        ru: 'Купить {{meatName}}',
        ua: 'Купити {{meatName}}',
        en: 'Buy {{meatName}}',
        de: '{{meatName}} kaufen',
        pl: 'Kup {{meatName}}',
        zh: '购买{{meatName}}',
    },
    selectMeatForGrill: {
        ru: 'Выберите мясо для гриля',
        ua: "Оберіть м'ясо для гриля",
        en: 'Choose meat for the grill',
        de: 'Wähle Fleisch für den Grill',
        pl: 'Wybierz mięso na grill',
        zh: '选择要烤的肉',
    },
    selectReadyMeatToTake: {
        ru: 'Выберите готовое мясо',
        ua: 'Оберіть готове мʼясо',
        en: 'Choose ready meat',
        de: 'Wähle fertiges Fleisch',
        pl: 'Wybierz gotowe mięso',
        zh: '选择熟肉',
    },
    selectReadyMeatToBuy: {
        ru: 'Выберите мясо для покупки',
        ua: 'Оберіть мʼясо для покупки',
        en: 'Choose meat to buy',
        de: 'Wähle Fleisch zum Kaufen',
        pl: 'Wybierz mięso do kupienia',
        zh: '选择要购买的肉',
    },
    pricePerPiece: {
        ru: 'Цена за кусок',
        ua: 'Ціна за шматок',
        en: 'Price per piece',
        de: 'Preis pro Stück',
        pl: 'Cena za kawałek',
        zh: '每块价格',
    },
    finishCurrentPlacement: {
        ru: 'Сначала завершите текущее размещение объекта',
        ua: "Спочатку завершіть поточне розміщення об'єкта",
        en: 'Finish the current object placement first',
        de: 'Beende zuerst die aktuelle Objektplatzierung',
        pl: 'Najpierw zakończ bieżące rozmieszczanie obiektu',
        zh: '请先完成当前对象摆放',
    },
    cannotPlaceInGreenZone: {
        ru: 'Нельзя размещать {{label}} в green zone',
        ua: 'Не можна розміщувати {{label}} у green zone',
        en: 'You cannot place {{label}} in the green zone',
        de: '{{label}} kann nicht in der Green Zone platziert werden',
        pl: 'Nie można umieszczać {{label}} w green zone',
        zh: '你不能在绿色区域放置{{label}}',
    },
    itemNoLongerInInventory: {
        ru: '{{label}} больше нет в инвентаре',
        ua: '{{label}} більше немає в інвентарі',
        en: '{{label}} is no longer in your inventory',
        de: '{{label}} befindet sich nicht mehr in deinem Inventar',
        pl: '{{label}} nie ma już w twoim ekwipunku',
        zh: '{{label}}已不在你的背包中',
    },
    placed: {
        ru: '{{label}} установлен',
        ua: '{{label}} встановлено',
        en: '{{label}} placed',
        de: '{{label}} platziert',
        pl: '{{label}} ustawiono',
        zh: '{{label}}已放置',
    },
    failedPlace: {
        ru: 'Не удалось установить {{label}}',
        ua: 'Не вдалося встановити {{label}}',
        en: 'Failed to place {{label}}',
        de: '{{label}} konnte nicht platziert werden',
        pl: 'Nie udało się ustawić {{label}}',
        zh: '无法放置{{label}}',
    },
    failedStartPlacement: {
        ru: 'Не удалось начать размещение {{label}}',
        ua: 'Не вдалося почати розміщення {{label}}',
        en: 'Failed to start placement for {{label}}',
        de: 'Die Platzierung für {{label}} konnte nicht gestartet werden',
        pl: 'Nie udało się rozpocząć rozmieszczania {{label}}',
        zh: '无法开始摆放{{label}}',
    },
    tooManyOwnPlacedObjects: {
        ru: 'Вы уже разместили слишком много объектов',
        ua: 'Ви вже розмістили занадто багато обʼєктів',
        en: 'You have already placed too many objects',
        de: 'Du hast bereits zu viele Objekte platziert',
        pl: 'Umieściłeś już zbyt wiele obiektów',
        zh: '你已经放置了太多物体',
    },
    tooManyObjectsNearby: {
        ru: 'Рядом уже слишком много объектов: максимум {{limit}} в радиусе {{radius}} м',
        ua: 'Поруч уже занадто багато обʼєктів: максимум {{limit}} у радіусі {{radius}} м',
        en: 'There are already too many objects nearby: maximum {{limit}} within {{radius}} m',
        de: 'In der Nähe gibt es bereits zu viele Objekte: maximal {{limit}} im Radius von {{radius}} m',
        pl: 'W pobliżu jest już zbyt wiele obiektów: maksymalnie {{limit}} w promieniu {{radius}} m',
        zh: '附近物体太多：{{radius}}米内最多{{limit}}个',
    },
    tooManyOwnObjectsNearby: {
        ru: 'Вы уже разместили слишком много своих объектов в этом месте: максимум {{limit}} в радиусе {{radius}} м',
        ua: 'Ви вже розмістили занадто багато своїх обʼєктів у цьому місці: максимум {{limit}} у радіусі {{radius}} м',
        en: 'You have already placed too many of your own objects here: maximum {{limit}} within {{radius}} m',
        de: 'Du hast hier bereits zu viele eigene Objekte platziert: maximal {{limit}} im Radius von {{radius}} m',
        pl: 'Umieściłeś już tutaj zbyt wiele własnych obiektów: maksymalnie {{limit}} w promieniu {{radius}} m',
        zh: '你已在这里放置过多自己的物体：{{radius}}米内最多{{limit}}个',
    },
    tooManySimilarObjectsNearby: {
        ru: 'Рядом уже слишком много объектов {{label}}: максимум {{limit}} в радиусе {{radius}} м',
        ua: 'Поруч уже занадто багато обʼєктів {{label}}: максимум {{limit}} у радіусі {{radius}} м',
        en: 'There are already too many nearby {{label}} objects: maximum {{limit}} within {{radius}} m',
        de: 'In der Nähe gibt es bereits zu viele {{label}}-Objekte: maximal {{limit}} im Radius von {{radius}} m',
        pl: 'W pobliżu jest już zbyt wiele obiektów {{label}}: maksymalnie {{limit}} w promieniu {{radius}} m',
        zh: '附近{{label}}太多：{{radius}}米内最多{{limit}}个',
    },
    placementBlocked: {
        ru: 'Вам запрещено размещать объекты ещё {{time}}',
        ua: 'Вам заборонено розміщувати обʼєкти ще {{time}}',
        en: 'You are forbidden from placing objects for another {{time}}',
        de: 'Dir ist das Platzieren von Objekten noch für {{time}} verboten',
        pl: 'Masz zakaz rozmieszczania obiektów jeszcze przez {{time}}',
        zh: '你在接下来的{{time}}内无法放置对象',
    },
    placementBannedByAdmin: {
        ru: 'Администратор запретил вам размещать объекты на {{minutes}} мин.',
        ua: 'Адміністратор заборонив вам розміщувати обʼєкти на {{minutes}} хв.',
        en: 'An administrator has forbidden you from placing objects for {{minutes}} min.',
        de: 'Ein Administrator hat dir das Platzieren von Objekten für {{minutes}} Min. verboten.',
        pl: 'Administrator zabronił ci rozmieszczania obiektów na {{minutes}} min.',
        zh: '管理员禁止你在{{minutes}}分钟内放置对象',
    },
    placementBanRemovedByAdmin: {
        ru: 'Администратор снова разрешил вам размещать объекты',
        ua: 'Адміністратор знову дозволив вам розміщувати обʼєкти',
        en: 'An administrator has allowed you to place objects again',
        de: 'Ein Administrator hat dir das Platzieren von Objekten wieder erlaubt',
        pl: 'Administrator ponownie pozwolił ci rozmieszczać obiekty',
        zh: '管理员已重新允许你放置对象',
    },
    notOwner: {
        ru: 'Вы можете убрать только свой объект',
        ua: "Ви можете прибрати лише свій об'єкт",
        en: 'You can only remove your own object',
        de: 'Du kannst nur dein eigenes Objekt entfernen',
        pl: 'Możesz usunąć tylko swój własny obiekt',
        zh: '你只能移除自己的物体',
    },
    removed: {
        ru: 'Объект убран',
        ua: "Об'єкт прибрано",
        en: 'Object removed',
        de: 'Objekt entfernt',
        pl: 'Obiekt usunięty',
        zh: '物体已移除',
    },
    tooFarFromGrill: {
        ru: 'Вы слишком далеко от гриля',
        ua: 'Ви занадто далеко від гриля',
        en: 'You are too far from the grill',
        de: 'Du bist zu weit vom Grill entfernt',
        pl: 'Jesteś za daleko od grilla',
        zh: '你离烤架太远了',
    },
    cantUseGrillInVehicle: {
        ru: 'Нельзя пользоваться грилем в транспорте',
        ua: 'Не можна користуватися грилем у транспорті',
        en: 'You cannot use the grill in a vehicle',
        de: 'Du kannst den Grill nicht in einem Fahrzeug benutzen',
        pl: 'Nie możesz używać grilla w pojeździe',
        zh: '你不能在载具中使用烤架',
    },
    noRawMeatToGrill: {
        ru: 'У вас нет сырого мяса для жарки',
        ua: "У вас немає сирого м'яса для смаження",
        en: 'You have no raw meat to grill',
        de: 'Du hast kein rohes Fleisch zum Grillen',
        pl: 'Nie masz surowego mięsa do grillowania',
        zh: '你没有可烤的生肉',
    },
    rawMeatNotFound: {
        ru: 'Сырое мясо не найдено в инвентаре',
        ua: "Сире м'ясо не знайдено в інвентарі",
        en: 'Raw meat not found in inventory',
        de: 'Rohes Fleisch wurde im Inventar nicht gefunden',
        pl: 'Nie znaleziono surowego mięsa w ekwipunku',
        zh: '背包中未找到生肉',
    },
    grillFull: {
        ru: 'На гриле больше нет свободного места',
        ua: 'На грилі більше немає вільного місця',
        en: 'There is no free space left on the grill',
        de: 'Auf dem Grill ist kein Platz mehr frei',
        pl: 'Na grillu nie ma już wolnego miejsca',
        zh: '烤架上没有空位了',
    },
    meatPlacedOnGrill: {
        ru: 'Мясо положено на гриль',
        ua: "М'ясо покладено на гриль",
        en: 'Meat placed on the grill',
        de: 'Fleisch wurde auf den Grill gelegt',
        pl: 'Mięso zostało położone na grill',
        zh: '肉已放到烤架上',
    },
    failedPlaceMeatOnGrill: {
        ru: 'Не удалось положить мясо на гриль',
        ua: "Не вдалося покласти м'ясо на гриль",
        en: 'Failed to place meat on the grill',
        de: 'Fleisch konnte nicht auf den Grill gelegt werden',
        pl: 'Nie udało się położyć mięsa na grillu',
        zh: '无法把肉放到烤架上',
    },
    noMeatOnGrill: {
        ru: 'На гриле нет мяса',
        ua: "На грилі немає м'яса",
        en: 'There is no meat on the grill',
        de: 'Auf dem Grill ist kein Fleisch',
        pl: 'Na grillu nie ma mięsa',
        zh: '烤架上没有肉',
    },
    noCookingMeatOnGrill: {
        ru: 'На гриле нет мяса, которое сейчас готовится',
        ua: "На грилі немає м'яса, яке зараз готується",
        en: 'There is no meat currently cooking on the grill',
        de: 'Auf dem Grill befindet sich derzeit kein Fleisch, das gerade zubereitet wird',
        pl: 'Na grillu nie ma mięsa, które właśnie się przygotowuje',
        zh: '烤架上当前没有正在烹饪的肉',
    },
    noReadyMeatOnGrill: {
        ru: 'На гриле пока нет готового мяса',
        ua: "На грилі поки немає готового м'яса",
        en: 'There is no ready meat on the grill yet',
        de: 'Auf dem Grill gibt es noch kein fertiges Fleisch',
        pl: 'Na grillu nie ma jeszcze gotowego mięsa',
        zh: '烤架上暂时没有熟肉',
    },
    rawMeatTaken: {
        ru: 'Сырое мясо забрано с гриля',
        ua: "Сире м'ясо забрано з гриля",
        en: 'Raw meat taken from the grill',
        de: 'Rohes Fleisch wurde vom Grill genommen',
        pl: 'Surowe mięso zostało zabrane z grilla',
        zh: '已从烤架上拿走生肉',
    },
    cookedMeatTaken: {
        ru: 'Готовое мясо забрано с гриля',
        ua: "Готове м'ясо забрано з гриля",
        en: 'Cooked meat taken from the grill',
        de: 'Fertiges Fleisch wurde vom Grill genommen',
        pl: 'Gotowe mięso zostało zabrane z grilla',
        zh: '已从烤架上拿走熟肉',
    },
    grillSaleModalTitle: {
        ru: 'Продажа с гриля',
        ua: 'Продаж із гриля',
        en: 'Grill sales',
        de: 'Grillverkauf',
        pl: 'Sprzedaż z grilla',
        zh: '烧烤售卖',
    },
    grillSaleModalMessage: {
        ru: 'Укажите название лавки и цену за один готовый кусок мяса. Цена 0 отключает продажу.',
        ua: "Вкажіть назву лавки та ціну за один готовий шматок м'яса. Ціна 0 вимикає продаж.",
        en: 'Enter the stall name and the price for one cooked meat piece. Price 0 disables sales.',
        de: 'Gib den Standnamen und den Preis für ein fertiges Fleischstück an. Preis 0 deaktiviert den Verkauf.',
        pl: 'Podaj nazwę stoiska i cenę za jeden gotowy kawałek mięsa. Cena 0 wyłącza sprzedaż.',
        zh: '输入摊位名称和每块熟肉的价格。价格为0会关闭出售。',
    },
    grillSaleModalShopNamePlaceholder: {
        ru: 'Название лавки',
        ua: 'Назва лавки',
        en: 'Stall name',
        de: 'Standname',
        pl: 'Nazwa stoiska',
        zh: '摊位名称',
    },
    grillSaleModalPricePlaceholder: {
        ru: 'Цена за штуку, например 250. От 1 до 5000',
        ua: 'Ціна за штуку, наприклад 250. Від 1 до 5000',
        en: 'Price per piece, for example 250. From 1 to 5000',
        de: 'Preis pro Stück, zum Beispiel 250. Von 1 bis 5000',
        pl: 'Cena za sztukę, na przykład 250. Od 1 do 5000',
        zh: '每份价格，例如250。范围1到5000',
    },
    grillSaleModalConfirmButton: {
        ru: 'Сохранить',
        ua: 'Зберегти',
        en: 'Save',
        de: 'Speichern',
        pl: 'Zapisz',
        zh: '保存',
    },
    grillSaleModalCancelButton: {
        ru: 'Отмена',
        ua: 'Скасувати',
        en: 'Cancel',
        de: 'Abbrechen',
        pl: 'Anuluj',
        zh: '取消',
    },
    invalidGrillSaleShopName: {
        ru: 'Введите название лавки от 1 до 32 символов',
        ua: 'Введіть назву лавки від 1 до 32 символів',
        en: 'Enter a stall name from 1 to 32 characters',
        de: 'Gib einen Standnamen mit 1 bis 32 Zeichen ein',
        pl: 'Wpisz nazwę stoiska od 1 do 32 znaków',
        zh: '请输入1到32个字符的摊位名称',
    },
    invalidGrillPrice: {
        ru: 'Введите целую цену от 0 до 5000',
        ua: 'Введіть цілу ціну від 0 до 5000',
        en: 'Enter a whole price from 0 to 5000',
        de: 'Gib einen ganzen Preis von 0 bis 5000 ein',
        pl: 'Wpisz pełną cenę od 0 do 5000',
        zh: '请输入0到5000之间的整数价格',
    },
    grillSaleStarted: {
        ru: 'Продажа запущена: {{shopName}}, {{price}} за кусок',
        ua: 'Продаж розпочато: {{shopName}}, {{price}} за шматок',
        en: 'Sales started: {{shopName}}, {{price}} per piece',
        de: 'Verkauf gestartet: {{shopName}}, {{price}} pro Stück',
        pl: 'Sprzedaż rozpoczęta: {{shopName}}, {{price}} za kawałek',
        zh: '已开始售卖：{{shopName}}，每块{{price}}',
    },
    grillSaleStopped: {
        ru: 'Продажа мяса с гриля отключена',
        ua: "Продаж м'яса з гриля вимкнено",
        en: 'Grill meat sales disabled',
        de: 'Der Verkauf von Grillfleisch wurde deaktiviert',
        pl: 'Sprzedaż mięsa z grilla została wyłączona',
        zh: '烤架肉类销售已关闭',
    },
    grillNotForSale: {
        ru: 'Это мясо сейчас не продаётся',
        ua: "Це м'ясо зараз не продається",
        en: 'This meat is not for sale right now',
        de: 'Dieses Fleisch wird derzeit nicht verkauft',
        pl: 'To mięso nie jest teraz na sprzedaż',
        zh: '这份肉当前未出售',
    },
    noReadyMeatForSale: {
        ru: 'На гриле пока нет готового мяса для продажи',
        ua: "На грилі поки немає готового м'яса для продажу",
        en: 'There is no ready meat for sale on the grill yet',
        de: 'Auf dem Grill ist noch kein fertiges Fleisch zum Verkauf',
        pl: 'Na grillu nie ma jeszcze gotowego mięsa na sprzedaż',
        zh: '烤架上暂时没有可出售的熟肉',
    },
    grillOwnerUnavailable: {
        ru: 'Владелец гриля сейчас недоступен',
        ua: 'Власник гриля зараз недоступний',
        en: 'The grill owner is currently unavailable',
        de: 'Der Grillbesitzer ist derzeit nicht verfügbar',
        pl: 'Właściciel grilla jest obecnie niedostępny',
        zh: '烤架所有者当前不可用',
    },
    boughtGrilledMeat: {
        ru: 'Вы купили {{meatName}} за {{price}}',
        ua: 'Ви купили {{meatName}} за {{price}}',
        en: 'You bought {{meatName}} for {{price}}',
        de: 'Du hast {{meatName}} für {{price}} gekauft',
        pl: 'Kupiono {{meatName}} za {{price}}',
        zh: '你以{{price}}购买了{{meatName}}',
    },
    soldGrilledMeat: {
        ru: '{{buyer}} купил {{meatName}} за {{price}}',
        ua: '{{buyer}} купив {{meatName}} за {{price}}',
        en: '{{buyer}} bought {{meatName}} for {{price}}',
        de: '{{buyer}} hat {{meatName}} für {{price}} gekauft',
        pl: '{{buyer}} kupił {{meatName}} za {{price}}',
        zh: '{{buyer}}以{{price}}购买了{{meatName}}',
    },
    removeMeatFromGrillFirst: {
        ru: 'Сначала уберите мясо с гриля',
        ua: "Спочатку приберіть м'ясо з гриля",
        en: 'Remove the meat from the grill first',
        de: 'Entferne zuerst das Fleisch vom Grill',
        pl: 'Najpierw zdejmij mięso z grilla',
        zh: '请先把肉从烤架上拿走',
    },
    notFoundById: {
        ru: 'Объект {{id}} не найден',
        ua: "Об'єкт {{id}} не знайдено",
        en: 'Object {{id}} not found',
        de: 'Objekt {{id}} wurde nicht gefunden',
        pl: 'Nie znaleziono obiektu {{id}}',
        zh: '未找到对象{{id}}',
    },
};
