export const server = {
    header: {
        ru: 'Автосвалка',
        ua: 'Автозвалище',
        en: 'Scrapyard',
        de: 'Schrottplatz',
        pl: 'Złomowisko',
    },
    modal: {
        title: {
            ru: 'Продажа {{name}}',
            en: 'Selling {{name}}',
            ua: 'Продаж {{name}}',
            de: 'Verkauf von {{name}}',
            pl: 'Sprzedaż {{name}}',
            zh: '销售{{name}}',
        },
        message: {
            ru: 'Вы действительно хотите продать {{name}} за ${{price}}?<br/>Учтите, что вы навсегда потеряете всё, что связано с этим Т/С.',
            en: 'Do you really want to sell {{name}} for ${{price}}?<br/>Keep in mind that everything tied to this vehicle is lost for good.',
            ua: 'Ви дійсно хочете продати {{name}} за ${{price}}?<br/>Врахуйте, що ви назавжди втратите все, що стосується цього Т/З.',
            de: 'Möchtest du {{name}} wirklich für ${{price}} verkaufen?<br/>Beachte, dass alles, was zu diesem Fahrzeug gehört, für immer verloren geht.',
            pl: 'Czy naprawdę chcesz sprzedać {{name}} za ${{price}}?<br/>Pamiętaj, że na zawsze stracisz wszystko, co jest związane z tym pojazdem.',
            zh: '您真的想以${{price}}的价格出售{{name}}吗?<br/>请注意,与该车辆相关的一切都将永久失去。',
        },
        lossesTitle: {
            ru: 'Вы потеряете:',
            en: 'You will lose:',
            ua: 'Ви втратите:',
            de: 'Du verlierst:',
            pl: 'Stracisz:',
            zh: '您将失去:',
        },
        lossTuning: {
            ru: 'Весь тюнинг и улучшения.',
            en: 'All tuning and upgrades.',
            ua: 'Весь тюнінг та покращення.',
            de: 'Das gesamte Tuning und alle Upgrades.',
            pl: 'Cały tuning i ulepszenia.',
            zh: '所有改装和升级。',
        },
        lossPlate: {
            ru: 'Номера: {{number}}',
            en: 'Plate: {{number}}',
            ua: 'Номери: {{number}}',
            de: 'Kennzeichen: {{number}}',
            pl: 'Tablice: {{number}}',
            zh: '车牌:{{number}}',
        },
        lossTrunk: {
            ru: 'Вещи в багажнике: {{count}} шт. {{weight}} кг.',
            en: 'Items in the trunk: {{count}} pcs. {{weight}} kg.',
            ua: 'Речі в багажнику: {{count}} шт. {{weight}} кг.',
            de: 'Gegenstände im Kofferraum: {{count}} Stk. {{weight}} kg.',
            pl: 'Przedmioty w bagażniku: {{count}} szt. {{weight}} kg.',
            zh: '后备箱内的物品:{{count}} 件,{{weight}} 公斤。',
        },
        confirmButton: {
            ru: 'Продать',
            en: 'Sell',
            ua: 'Продати',
            de: 'Verkaufen',
            pl: 'Sprzedaj',
            zh: '出售',
        },
        cancelButton: {
            ru: 'Отмена',
            en: 'Cancel',
            ua: 'Скасувати',
            de: 'Abbrechen',
            pl: 'Anuluj',
            zh: '取消',
        },
    },
    successMessage: {
        ru: 'Вы успешно продали {{name}} за ${{price}}',
        en: 'You have successfully sold {{name}} for ${{price}}',
        ua: 'Ви успішно продали {{name}} за ${{price}}',
        de: 'Du hast {{name}} erfolgreich für ${{price}} verkauft',
        pl: 'Pomyślnie sprzedano {{name}} za ${{price}}',
        zh: '您已成功将{{name}}以${{price}}的价格出售',
    },
};
