export default {
    title: {
        ru: 'Выдать премию',
        ua: 'Видати премію',
        en: 'Give Bonus',
        de: 'Bonus vergeben',
        pl: 'Przyznać premię',
    },
    reason: {
        ru: 'Укажите причину',
        ua: 'Вкажіть причину',
        en: 'Specify Reason',
        de: 'Gib einen Grund an',
        pl: 'Podaj powód',
    },
    sum: {
        ru: 'Введите сумму от {{min}} до {{max}}',
        ua: 'Введіть суму від {{min}} до {{max}}',
        en: 'Enter Amount from {{min}} to {{max}}',
        de: 'Gib einen Betrag zwischen {{min}} und {{max}} ein',
        pl: 'Wprowadź kwotę od {{min}} do {{max}}',
    },
    accept: {
        ru: 'Подтвердить',
        ua: 'Підтвердити',
        en: 'Confirm',
        de: 'Bestätigen',
        pl: 'Zatwierdź',
    },
    decline: {
        ru: 'Отмена',
        ua: 'Скасування',
        en: 'Cancel',
        de: 'Abbrechen',
        pl: 'Anuluj',
    },

    // Notifications (server-side)
    successGiver: {
        ru: 'Вы выдали премию ${{value}} игроку {{name}}',
        ua: 'Ви видали премію ${{value}} гравцю {{name}}',
        en: 'You gave a ${{value}} bonus to {{name}}',
        de: 'Du hast {{name}} einen Bonus von ${{value}} gegeben',
        pl: 'Przyznałeś premię ${{value}} graczowi {{name}}',
    },
    successTarget: {
        ru: '{{name}} выдал вам премию в размере ${{value}}',
        ua: '{{name}} видав вам премію у розмірі ${{value}}',
        en: '{{name}} gave you a bonus of ${{value}}',
        de: '{{name}} hat dir einen Bonus von ${{value}} gegeben',
        pl: '{{name}} przyznał ci premię w wysokości ${{value}}',
    },
    cantGiveSelf: {
        ru: 'Нельзя выдать премию самому себе',
        ua: 'Не можна видати премію самому собі',
        en: 'You cannot give a bonus to yourself',
        de: 'Du kannst dir keinen Bonus selbst geben',
        pl: 'Nie możesz przyznać premii samemu sobie',
    },
    targetNotInFaction: {
        ru: 'Игрок не состоит в вашей фракции',
        ua: 'Гравець не перебуває у вашій фракції',
        en: 'The player is not in your faction',
        de: 'Der Spieler ist nicht in deiner Fraktion',
        pl: 'Gracz nie jest w twojej frakcji',
    },
    cooldown: {
        ru: 'Вы уже выдавали премию сегодня',
        ua: 'Ви вже видавали премію сьогодні',
        en: 'You have already given a bonus today',
        de: 'Du hast heute bereits einen Bonus vergeben',
        pl: 'Już dziś przyznałeś premię',
    },
    notEnoughBudget: {
        ru: 'Недостаточно средств в бюджете фракции',
        ua: 'Недостатньо коштів у бюджеті фракції',
        en: 'Not enough funds in the faction budget',
        de: 'Nicht genug Mittel im Fraktionsbudget',
        pl: 'Niewystarczające środki w budżecie frakcji',
    },
    invalidData: {
        ru: 'Проверьте сумму и причину премии',
        ua: 'Перевірте суму та причину премії',
        en: 'Check the bonus amount and reason',
        de: 'Prüfe Betrag und Grund des Bonus',
        pl: 'Sprawdź kwotę i powód premii',
    },
    targetNoBank: {
        ru: 'У игрока нет банковского счёта',
        ua: 'У гравця немає банківського рахунку',
        en: 'The player does not have a bank account',
        de: 'Der Spieler hat kein Bankkonto',
        pl: 'Gracz nie posiada konta bankowego',
    },

    // Rank bonus (rank control dialog)
    rankOpen: {
        ru: 'Выдать премию рангу',
        ua: 'Видати премію рангу',
        en: 'Give a bonus to the rank',
        de: 'Dem Rang einen Bonus geben',
        pl: 'Przyznaj premię randze',
    },
    rankTitle: {
        ru: 'Премия рангу',
        ua: 'Премія рангу',
        en: 'Rank bonus',
        de: 'Rangbonus',
        pl: 'Premia dla rangi',
    },
    rankAmount: {
        ru: 'Сумма каждому',
        ua: 'Сума кожному',
        en: 'Amount per member',
        de: 'Betrag pro Mitglied',
        pl: 'Kwota dla każdego',
    },
    rankAmountRange: {
        ru: 'От ${{min}} до ${{max}}',
        ua: 'Від ${{min}} до ${{max}}',
        en: 'From ${{min}} to ${{max}}',
        de: 'Von ${{min}} bis ${{max}}',
        pl: 'Od ${{min}} do ${{max}}',
    },
    rankReason: {
        ru: 'Причина',
        ua: 'Причина',
        en: 'Reason',
        de: 'Grund',
        pl: 'Powód',
    },
    rankReasonPlaceholder: {
        ru: 'За что премия',
        ua: 'За що премія',
        en: 'What the bonus is for',
        de: 'Wofür der Bonus ist',
        pl: 'Za co premia',
    },
    rankMembers: {
        ru: 'Участников в ранге: {{count}}',
        ua: 'Учасників у ранзі: {{count}}',
        en: 'Members in the rank: {{count}}',
        de: 'Mitglieder im Rang: {{count}}',
        pl: 'Członków w randze: {{count}}',
    },
    rankTotal: {
        ru: 'Из бюджета',
        ua: 'З бюджету',
        en: 'From the budget',
        de: 'Aus dem Budget',
        pl: 'Z budżetu',
    },
    rankGive: {
        ru: 'Выдать премию',
        ua: 'Видати премію',
        en: 'Give bonus',
        de: 'Bonus vergeben',
        pl: 'Przyznaj premię',
    },
    rankBack: {
        ru: 'Назад к рангу',
        ua: 'Назад до рангу',
        en: 'Back to the rank',
        de: 'Zurück zum Rang',
        pl: 'Wróć do rangi',
    },

    // Rank bonus (server-side)
    rankModalTitle: {
        ru: 'Премия рангу',
        ua: 'Премія рангу',
        en: 'Rank bonus',
        de: 'Rangbonus',
        pl: 'Premia dla rangi',
    },
    rankModalMessage: {
        ru: 'Ранг <span style="color: white">{{rank}}</span>: {{count}} чел. получат по ${{value}}.<br/>Из бюджета фракции будет списано <span style="color: white">${{total}}</span>.<br/>Причина: {{reason}}',
        ua: 'Ранг <span style="color: white">{{rank}}</span>: {{count}} ос. отримають по ${{value}}.<br/>З бюджету фракції буде списано <span style="color: white">${{total}}</span>.<br/>Причина: {{reason}}',
        en: 'Rank <span style="color: white">{{rank}}</span>: {{count}} members get ${{value}} each.<br/><span style="color: white">${{total}}</span> will be taken from the faction budget.<br/>Reason: {{reason}}',
        de: 'Rang <span style="color: white">{{rank}}</span>: {{count}} Mitglieder erhalten je ${{value}}.<br/><span style="color: white">${{total}}</span> werden vom Fraktionsbudget abgebucht.<br/>Grund: {{reason}}',
        pl: 'Ranga <span style="color: white">{{rank}}</span>: {{count}} os. otrzyma po ${{value}}.<br/>Z budżetu frakcji zostanie pobrane <span style="color: white">${{total}}</span>.<br/>Powód: {{reason}}',
    },
    rankCooldown: {
        ru: 'Этот ранг уже получал премию. Следующая будет доступна через {{time}}',
        ua: 'Цей ранг уже отримував премію. Наступна буде доступна через {{time}}',
        en: 'This rank has already received a bonus. The next one is available in {{time}}',
        de: 'Dieser Rang hat bereits einen Bonus erhalten. Der nächste ist in {{time}} möglich',
        pl: 'Ta ranga otrzymała już premię. Następna będzie dostępna za {{time}}',
    },
    rankEmpty: {
        ru: 'В ранге нет участников с банковским счётом',
        ua: 'У ранзі немає учасників з банківським рахунком',
        en: 'No one in this rank has a bank account',
        de: 'Niemand in diesem Rang hat ein Bankkonto',
        pl: 'Nikt w tej randze nie ma konta bankowego',
    },
    rankBusy: {
        ru: 'Другая премия рангу ещё выдаётся, попробуйте через пару секунд',
        ua: 'Інша премія рангу ще видається, спробуйте за кілька секунд',
        en: 'Another rank bonus is still being paid out, try again in a few seconds',
        de: 'Ein anderer Rangbonus wird noch ausgezahlt, versuche es in ein paar Sekunden erneut',
        pl: 'Inna premia dla rangi jest jeszcze wypłacana, spróbuj za kilka sekund',
    },
    rankSuccessGiver: {
        ru: 'Премия выдана рангу {{rank}}: {{count}} чел. по ${{value}}, всего ${{total}}',
        ua: 'Премію видано рангу {{rank}}: {{count}} ос. по ${{value}}, усього ${{total}}',
        en: 'Bonus paid to {{rank}}: {{count}} members, ${{value}} each, ${{total}} in total',
        de: 'Bonus an {{rank}} ausgezahlt: {{count}} Mitglieder, je ${{value}}, insgesamt ${{total}}',
        pl: 'Premia wypłacona randze {{rank}}: {{count}} os. po ${{value}}, łącznie ${{total}}',
    },
    rankSuccessTarget: {
        ru: 'Ваш ранг {{rank}} получил премию: ${{value}} на банковский счёт',
        ua: 'Ваш ранг {{rank}} отримав премію: ${{value}} на банківський рахунок',
        en: 'Your rank {{rank}} received a bonus: ${{value}} to your bank account',
        de: 'Dein Rang {{rank}} hat einen Bonus erhalten: ${{value}} auf dein Bankkonto',
        pl: 'Twoja ranga {{rank}} otrzymała premię: ${{value}} na konto bankowe',
    },
};
