export default {
    //

    listOfUpgrades: {
        ru: 'Список улучшений',
        ua: 'Список поліпшень',
        en: 'List of Upgrades',
        de: 'Liste der Upgrades',
        pl: 'Lista ulepszeń',
        zh: '升级列表',
    },

    active: {
        ru: 'Активно',
        ua: 'Активно',
        en: 'Active',
        de: 'Aktiv',
        pl: 'Aktywny',
        zh: '活跃',
    },
    activate: {
        ru: 'Активировать',
        ua: 'Активувати',
        en: 'Activate',
        de: 'Aktivieren',
        pl: 'Aktywować',
        zh: '激活',
    },
    hour: {
        ru: 'Час',
        ua: 'Година',
        en: 'Hour',
        de: 'Stunde',
        pl: 'Godzina',
        zh: '时间',
    },

    // Categories
    cars: {
        ru: 'Автомобили',
        ua: 'Автомобілі',
        en: 'Cars',
        de: 'Autos',
        pl: 'Samochody',
        zh: '汽车',
    },

    // EMS Cars
    defaultEMSCarsTitle: {
        ru: 'Обычные мед. автомобили',
        ua: 'Звичайні мед. автомобілі',
        en: 'Regular medical cars',
        de: 'Normale medizinische Autos',
        pl: 'Zwykłe samochody medyczne',
        zh: '普通医疗车',
    },
    defaultEMSCarsDesc: {
        ru: 'Это обычные медецинские автомобили, отлично подходят для вызовов',
        ua: 'Це звичайні медичні автомобілі, чудово підходять для викликів',
        en: 'These are regular medical cars, great for calls',
        de: 'Das sind normale medizinische Autos, ideal für Anrufe',
        pl: 'To są zwykłe samochody medyczne, świetne do wywołań',
        zh: '这些是普通的医疗车，打电话很好',
    },
    mediumEMSCarsTitle: {
        ru: 'Доп. автомобили',
        ua: 'Доп. автомобілі',
        en: 'Additional cars',
        de: 'Zusätzliche Autos',
        pl: 'Dodatkowe samochody',
        zh: '其他汽车',
    },
    mediumEMSCarsDesc: {
        ru: 'Этот апгрейд включает в себя 5 новеньких быстрых Infiniti FX50S',
        ua: 'Цей апгрейд включає в себе 5 новеньких швидких Infiniti FX50S',
        en: 'This upgrade includes 5 brand new and fast Infiniti FX50S',
        de: 'Dieses Upgrade beinhaltet 5 brandneue und schnelle Infiniti FX50S',
        pl: 'Ten upgrade obejmuje 5 nowych i szybkich Infiniti FX50S',
        zh: '此次批准包括五款新的快速英菲尼迪FX50S',
    },
    highEMSCarsTitle: {
        ru: 'Вертолёт?',
        ua: 'Вертоліт?',
        en: 'Helicopter?',
        de: 'Hubschrauber?',
        pl: 'Helikopter?',
        zh: '直升机？',
    },
    highEMSCarsDesc: {
        ru: 'Этот апгрейд включает себя вертолёт на крыше EMS',
        ua: 'Цей апгрейд включає в себе вертоліт на даху EMS',
        en: 'This upgrade includes a helicopter on the EMS roof',
        de: 'Dieses Upgrade beinhaltet einen Hubschrauber auf dem EMS-Dach',
        pl: 'Ten upgrade obejmuje helikopter na dachu EMS',
        zh: '这项批准包括EMS屋顶上的一架直升机',
    },

    // Cars
    defaultCarsTitle: {
        ru: 'Обычные автомобили',
        ua: 'Звичайні автомобілі',
        en: 'Default Cars',
        de: 'Standardautos',
        pl: 'Standardowe samochody',
        zh: '普通汽车',
    },
    mediumCarsTitle: {
        ru: 'Средние автомобили',
        ua: 'Середні автомобілі',
        en: 'Medium Cars',
        de: 'Mittlere Autos',
        pl: 'Średnie samochody',
        zh: '中型汽车',
    },
    highCarsTitle: {
        ru: 'Высококлассные автомобили',
        ua: 'Висококласні автомобілі',
        en: 'High-end Cars',
        de: 'Hochwertige Autos',
        pl: 'Samochody wysokiej klasy',
        zh: '高级轿车',
    },
    defaultCarsDesc: {
        ru: 'Это стандартные автомобили, идеально подходящие для повседневного использования.',
        ua: 'Це стандартні автомобілі, ідеально підходять для щоденного використання.',
        en: 'These are standard cars, perfect for everyday use.',
        de: 'Das sind Standardautos, perfekt für den täglichen Gebrauch.',
        pl: 'To są standardowe samochody, idealne do codziennego użytku.',
        zh: '这些是标准车，非常适合日常使用',
    },
    mediumCarsDesc: {
        ru: 'Это автомобили среднего класса, предлагающие больше комфорта и функций.',
        ua: 'Це автомобілі середнього класу, які пропонують більше комфорту та функцій.',
        en: 'These are mid-range cars, offering more comfort and features.',
        de: 'Das sind Mittelklassewagen, die mehr Komfort und Funktionen bieten.',
        pl: 'To są samochody średniej klasy, oferujące więcej komfortu i funkcji.',
        zh: '这些是中产阶级的汽车，提供更多的舒适性和功能',
    },
    highCarsDesc: {
        ru: 'Это высококлассные автомобили, предлагающие премиальные функции и высочайший уровень комфорта.',
        ua: 'Це висококласні автомобілі, які пропонують преміальні функції та найвищий рівень комфорту.',
        en: 'These are high-end cars, offering premium features and the highest level of comfort.',
        de: 'Das sind hochwertige Autos, die Premium-Funktionen und höchsten Komfort bieten.',
        pl: 'To są samochody wysokiej klasy, oferujące funkcje premium i najwyższy poziom komfortu.',
        zh: '这些是高级轿车，功能齐全，舒适度高',
    },

    // LSPD
    lowLSPDCarsName: {
        ru: 'Базовые автомобили',
        ua: 'Базові автомобілі',
        en: 'Basic Cars',
        de: 'Basis-Fahrzeuge',
        pl: 'Podstawowe samochody',
        zh: '基础车',
    },
    lowLSPDCarsDesc: {
        ru: 'Включает в себя все нужные автомобили, ничего особеного, патрульные машины и два джипа',
        ua: 'Включає в себе всі необхідні автомобілі, нічого особливого, патрульні машини та два джипи',
        en: 'Includes all the necessary cars, nothing special, patrol cars, and two jeeps',
        de: 'Enthält alle notwendigen Autos, nichts Besonderes, Streifenwagen und zwei Jeeps',
        pl: 'Zawiera wszystkie niezbędne samochody, nic specjalnego, radiowozy i dwa dżipy',
        zh: '包括所有必要的汽车，没什么特别的，巡逻车和两辆吉普车',
    },
    mediumLSPDCarsName: {
        ru: 'Средние автомобили',
        ua: 'Середні автомобілі',
        en: 'Medium Cars',
        de: 'Mittelklasse-Fahrzeuge',
        pl: 'Samochody średniej klasy',
        zh: '中型车',
    },
    mediumLSPDCarsDesc: {
        ru: 'Включает в себя уже больше качественых авто, а также большой джип и мотоциклы',
        ua: 'Включає в себе вже більше якісних авто, а також великий джип і мотоцикли',
        en: 'Includes more high-quality cars, as well as a large jeep and motorcycles',
        de: 'Enthält mehr hochwertige Autos sowie einen großen Jeep und Motorräder',
        pl: 'Zawiera więcej wysokiej jakości samochodów, a także dużego jeepa i motocykle',
        zh: '包括更多优质汽车以及更多吉普车和摩托车',
    },
    highLSPDCarsName: {
        ru: 'Лучший выбор',
        ua: 'Найкращий вибір',
        en: 'Best Choice',
        de: 'Beste Wahl',
        pl: 'Najlepszy wybór',
        zh: '最佳选择',
    },
    highLSPDCarsDesc: {
        ru: 'Включает в себя всё что надо, спортивные электрически машины, патрульная без виннила, вертолёты на крыше',
        ua: 'Включає в себе все, що треба, спортивні електричні машини, патрульна без вініла, вертольоти на даху',
        en: 'Includes everything you need, sports electric cars, unmarked patrol cars, helicopters on the roof',
        de: 'Enthält alles, was Sie brauchen, Sport-Elektroautos, unmarkierte Streifenwagen, Hubschrauber auf dem Dach',
        pl: 'Zawiera wszystko, czego potrzebujesz, sportowe samochody elektryczne, nieoznakowane radiowozy, helikoptery na dachu',
        zh: '包括你需要的一切，运动型电动汽车、无罪巡逻、屋顶上的直升机',
    },

    // army
    basicArmyCarsTitle: {
        ru: 'Базовый транспорт',
        ua: 'Базовий транспорт',
        en: 'Basic Transport',
        de: 'Basisfahrzeuge',
        pl: 'Podstawowy transport',
    },
    basicArmyCarsDesc: {
        ru: 'Включает в себя всё нужное, матовозки, куча транспорта. Больше чем в армии некоторых стран',
        ua: 'Містить усе необхідне: матовозки, купу транспорту. Більше, ніж в армії деяких країн',
        en: "Includes everything you need: supply trucks, tons of vehicles. More than some countries' armies have",
        de: 'Enthält alles Notwendige: Versorgungsfahrzeuge, jede Menge Transportmittel. Mehr als manche Armeen haben',
        pl: 'Zawiera wszystko, co potrzebne: ciężarówki zaopatrzeniowe, mnóstwo pojazdów. Więcej niż ma armia niektórych krajów',
    },
    betterArmyCarsTitle: {
        ru: 'Дополнительные вертолёты',
        ua: 'Додаткові гелікоптери',
        en: 'Additional Helicopters',
        de: 'Zusätzliche Hubschrauber',
        pl: 'Dodatkowe helikoptery',
    },
    betterArmyCarsDesc: {
        ru: 'Включает в себя 4 новых вертолёта карго боба готовых к любым полётам!',
        ua: 'Містить 4 нові гелікоптери Карго Боба, готові до будь-яких польотів!',
        en: 'Includes 4 new Cargo Bob helicopters ready for any flight!',
        de: 'Enthält 4 neue Cargo-Bob-Hubschrauber, bereit für jeden Flug!',
        pl: 'Zawiera 4 nowe helikoptery Cargo Bob gotowe na każdy lot!',
    },
    // Gangs
    mediumGangCarsTitle: {
        ru: 'Премиум автомобили',
        ua: 'Преміум автомобілі',
        en: 'Premium Cars',
        de: 'Premium-Autos',
        pl: 'Samochody premium',
    },
    mediumGangCarsDesc: {
        ru: 'Включает в себя премиум автомобили такие как BMW M5 F90 и Mercedes-AMG C 63 S. Будете самыми крутыми на районе!',
        ua: 'Включає в себе преміум автомобілі такі як BMW M5 F90 і Mercedes-AMG C 63 S. Будете найкрутішими в районі!',
        en: "Includes premium cars like BMW M5 F90 and Mercedes-AMG C 63 S. You'll be the coolest in the neighborhood!",
        de: 'Umfasst Premium-Autos wie BMW M5 F90 und Mercedes-AMG C 63 S. Ihr werdet die Coolsten in der Nachbarschaft sein!',
        pl: 'Obejmuje samochody premium, takie jak BMW M5 F90 i Mercedes-AMG C 63 S. Będziecie najfajniejsi w okolicy!',
    },
    highGangCarsTitle: {
        ru: 'Дополнительные авто внедорожники',
        ua: 'Додаткові авто позашляховики',
        en: 'Additional Off-Road Vehicles',
        de: 'Zusätzliche Geländewagen',
        pl: 'Dodatkowe samochody terenowe',
    },
    highGangCarsDesc: {
        ru: 'Внедорожные авто такие как BMW X5 G05 и Toyota Land Cruiser 200, для выездов за город',
        ua: 'Позашляхові авто такі як BMW X5 G05 і Toyota Land Cruiser 200, для виїздів за місто',
        en: 'Off-road vehicles like BMW X5 G05 and Toyota Land Cruiser 200, for trips out of town',
        de: 'Geländewagen wie BMW X5 G05 und Toyota Land Cruiser 200, für Ausflüge aus der Stadt',
        pl: 'Samochody terenowe, takie jak BMW X5 G05 i Toyota Land Cruiser 200, na wyjazdy poza miasto',
    },

    // inventory
    inventory: {
        ru: 'Склад',
        ua: 'Склад',
        en: 'Warehouse',
        de: 'Lager',
        pl: 'Magazyn',
        zh: '存储库',
    },
    defaultInventory: {
        ru: 'Маленький склад',
        ua: 'Маленький склад',
        en: 'Small Warehouse',
        de: 'Kleines Lager',
        pl: 'Mały magazyn',
        zh: '小型存储',
    },
    mediumInventory: {
        ru: 'Средний склад',
        ua: 'Середній склад',
        en: 'Medium Warehouse',
        de: 'Mittleres Lager',
        pl: 'Średni magazyn',
        zh: '中型仓库',
    },
    highInventory: {
        ru: 'Большой склад',
        ua: 'Великий склад',
        en: 'Large Warehouse',
        de: 'Großes Lager',
        pl: 'Duży magazyn',
        zh: '大型仓库',
    },

    defaultInventoryDesc: {
        ru: 'Небольшой склад для хранения вещей.',
        ua: 'Невеликий склад для зберігання речей.',
        en: 'A small warehouse for storing things.',
        de: 'Ein kleines Lager zur Aufbewahrung von Dingen.',
        pl: 'Mały magazyn do przechowywania rzeczy.',
        zh: '一个用来存放东西的小仓库',
    },
    mediumInventoryDesc: {
        ru: 'Вполне себе средний склад для хранения вещей.',
        ua: 'Цілком середній склад для зберігання речей.',
        en: 'Quite a medium warehouse for storing things.',
        de: 'Ein ganz mittleres Lager zur Aufbewahrung von Dingen.',
        pl: 'Całkiem średni magazyn do przechowywania rzeczy.',
        zh: '用于存储物品的中等存储设施',
    },
    highInventoryDesc: {
        ru: 'Большой склад для хранения вещей.',
        ua: 'Великий склад для зберігання речей.',
        en: 'A large warehouse for storing things.',
        de: 'Ein großes Lager zur Aufbewahrung von Dingen.',
        pl: 'Duży magazyn do przechowywania rzeczy.',
        zh: '一个用来存放东西的大仓库',
    },
};
