export const operations = {
    deposited: {
        ru: 'Пополнил счёт',
        en: 'Deposited',
        ua: 'Поповнив рахунок',
        de: 'Einzahlung',
        pl: 'Dokonano wpłaty',
        zh: '存取',
    },
    withdrew: {
        ru: 'Снял со счёта',
        en: 'Withdrew',
        ua: 'Зняв з рахунку',
        de: 'Abgehoben',
        pl: 'Wypłacono',
        zh: '收回',
    },
    transferFrom: {
        ru: 'Вам перевели со счёта {{account}}',
        en: 'You received a transfer from account {{account}}',
        ua: 'Вам перерахували з рахунку {{account}}',
        de: 'Du hast eine Überweisung von Konto {{account}} erhalten',
        pl: 'Otrzymałeś transfer z konta {{account}}',
        zh: '您收到账户{{account}}的转账',
    },
    transferFromSms: {
        ru: 'Перевод {{amount}}$ от {{account}}. Баланс: {{balance}}$',
        ua: 'Переказ {{amount}}$ від {{account}}. Баланс: {{balance}}$',
        en: 'Transfer of {{amount}}$ from {{account}}. Balance: {{balance}}$',
        de: 'Überweisung von {{amount}}$ von {{account}}. Kontostand: {{balance}}$',
        pl: 'Przelew {{amount}}$ od {{account}}. Saldo: {{balance}}$',
    },
    transferTo: {
        ru: 'Вы перевели на счёт {{account}}',
        en: 'You transferred to account {{account}}',
        ua: 'Ви перерахували на рахунок {{account}}',
        de: 'Du hast auf Konto {{account}} überwiesen',
        pl: 'Przekazałeś na konto {{account}}',
        zh: '您已转帐到帐户{{account}}',
    },
    withdrawFromContributions: {
        ru: 'Снял со счёта вкладов',
        en: 'Withdrew from contributions account',
        ua: 'Зняв зі скарбничого рахунку',
        de: 'Von Beitragsguthaben abgehoben',
        pl: 'Wypłacono z konta wkładów',
        zh: '从供款帐户提款',
    },
    depositToContributions: {
        ru: 'Пополнил счёт вкладов',
        en: 'Deposited to contributions account',
        ua: 'Поповнив на скарбничий рахунок',
        de: 'Einzahlung auf Beitragsguthaben',
        pl: 'Dokonano wpłaty na konta wkładów',
        zh: '存入供款帐户',
    },
    depositToTax: {
        ru: 'Пополнил комунальный счёт',
        ua: 'Поповнив комунальний рахунок',
        en: 'Topped up the utility account',
        de: 'Habe das Gemeinschaftskonto aufgefüllt',
        pl: 'Doładowałem konto komunalne',
        zh: '给公用事业账户充值',
    },
    depositedToCommercial: {
        ru: 'Пополнил коммерческий счёт',
        ua: 'Поповнив комерційний рахунок',
        en: 'Deposited to commercial account',
        de: 'Auf das Geschäftskonto eingezahlt',
        pl: 'Wpłacono na konto komercyjne',
        zh: '存入商业帐户',
    },
    depositToPhone: {
        ru: 'Пополнил мобильный',
        ua: 'Поповнив мобільний',
        en: 'Topped up mobile',
        de: 'Handy aufgeladen',
        pl: 'Doładowano telefon',
    },
    takeHouse: {
        ru: 'Отобран дом #{{id}}',
        en: 'Taken house #{{id}}',
        ua: 'Відібрано будинок #{{id}}',
        de: 'Haus übernommen #{{id}}',
        pl: 'Wybrano dom #{{id}}',
        zh: '被占用房屋#{{id}}',
    },
    takeAtm: {
        ru: 'Отобран банкомат #{{id}}',
        ua: 'Відібрано банкомат #{{id}}',
        en: 'ATM taken #{{id}}',
        de: 'Geldautomat übernommen #{{id}}',
        pl: 'Przejęto bankomat #{{id}}',
        zh: '自动取款机#{{id}}',
    },
};
