export const operations = {
    deposited: {
        ru: 'Пополнил счёт',
        en: 'Deposited',
        ua: 'Поповнив рахунок',
        de: 'Einzahlung',
        pl: 'Dokonano wpłaty',
    },
    withdrew: {
        ru: 'Снял со счёта',
        en: 'Withdrew',
        ua: 'Зняв з рахунку',
        de: 'Abgehoben',
        pl: 'Wypłacono',
    },
    transferFrom: {
        ru: 'Вам перевели со счёта {{account}}',
        en: 'You received a transfer from account {{account}}',
        ua: 'Вам перерахували з рахунку {{account}}',
        de: 'Sie haben eine Überweisung von Konto {{account}} erhalten',
        pl: 'Otrzymałeś transfer z konta {{account}}',
    },
    transferTo: {
        ru: 'Вы перевели на счёт {{account}}',
        en: 'You transferred to account {{account}}',
        ua: 'Ви перерахували на рахунок {{account}}',
        de: 'Sie haben auf Konto {{account}} überwiesen',
        pl: 'Przekazałeś na konto {{account}}',
    },
    withdrawFromContributions: {
        ru: 'Снял со счёта вкладов',
        en: 'Withdrew from contributions account',
        ua: 'Зняв зі скарбничого рахунку',
        de: 'Von Beitragsguthaben abgehoben',
        pl: 'Wypłacono z konta wkładów',
    },
    depositToContributions: {
        ru: 'Пополнил счёт вкладов',
        en: 'Deposited to contributions account',
        ua: 'Поповнив на скарбничий рахунок',
        de: 'Einzahlung auf Beitragsguthaben',
        pl: 'Dokonano wpłaty na konta wkładów',
    },
    depositToTax: {
        ru: 'Пополнил комунальный счёт',
        ua: 'Поповнив комунальний рахунок',
        en: 'Topped up the utility account',
        de: 'Habe das Gemeinschaftskonto aufgefüllt',
        pl: 'Doładowałem konto komunalne',
    },
    depositedToCommercial: {
        ru: 'Пополнил коммерческий счёт',
        ua: 'Поповнив комерційний рахунок',
        en: 'Deposited to commercial account',
        de: 'Auf das Geschäftskonto eingezahlt',
        pl: 'Wpłacono na konto komercyjne',
    },
    takeHouse: {
        ru: 'Отобран дом #{{id}}',
        en: 'Taken house #{{id}}',
        ua: 'Відібрано будинок #{{id}}',
        de: 'Haus genommen #{{id}}',
        pl: 'Wybrano dom #{{id}}',
    },
    takeAtm: {
        ru: 'Отобран банкомат #{{id}}',
        ua: 'Відібрано банкомат #{{id}}',
        en: 'ATM taken #{{id}}',
        de: 'Geldautomat genommen #{{id}}',
        pl: 'Przejęto bankomat #{{id}}',
    },
};
