export default {
    tabHome: {
        ru: 'Главная · FREEWEB',
        ua: 'Головна · FREEWEB',
        en: 'Home · FREEWEB',
        de: 'Start · FREEWEB',
        pl: 'Strona główna · FREEWEB',
        zh: '首页 · FREEWEB',
    },
    tabSearch: {
        ru: 'Поиск · FREEWEB',
        ua: 'Пошук · FREEWEB',
        en: 'Search · FREEWEB',
        de: 'Suche · FREEWEB',
        pl: 'Wyszukiwanie · FREEWEB',
        zh: '搜索 · FREEWEB',
    },
    tabNotFound: {
        ru: 'Страница не найдена · FREEWEB',
        ua: 'Сторінку не знайдено · FREEWEB',
        en: 'Page not found · FREEWEB',
        de: 'Seite nicht gefunden · FREEWEB',
        pl: 'Strona nie znaleziona · FREEWEB',
        zh: '页面未找到 · FREEWEB',
    },
    back: {
        ru: 'Назад',
        ua: 'Назад',
        en: 'Back',
        de: 'Zurück',
        pl: 'Wstecz',
        zh: '返回',
    },
    forward: {
        ru: 'Вперёд',
        ua: 'Вперед',
        en: 'Forward',
        de: 'Vorwärts',
        pl: 'Naprzód',
        zh: '前进',
    },
    reload: {
        ru: 'Обновить',
        ua: 'Оновити',
        en: 'Reload',
        de: 'Neu laden',
        pl: 'Odśwież',
        zh: '刷新',
    },
    bookmark: {
        ru: 'В закладки',
        ua: 'У закладки',
        en: 'Bookmark',
        de: 'Lesezeichen',
        pl: 'Dodaj do zakładek',
        zh: '加入书签',
    },
    newTab: {
        ru: 'Новая вкладка',
        ua: 'Нова вкладка',
        en: 'New tab',
        de: 'Neuer Tab',
        pl: 'Nowa karta',
        zh: '新标签页',
    },
    closeTab: {
        ru: 'Закрыть вкладку',
        ua: 'Закрити вкладку',
        en: 'Close tab',
        de: 'Tab schließen',
        pl: 'Zamknij kartę',
        zh: '关闭标签页',
    },
    ctxOpen: {
        ru: 'Открыть',
        ua: 'Відкрити',
        en: 'Open',
        de: 'Öffnen',
        pl: 'Otwórz',
        zh: '打开',
    },
    ctxOpenNewTab: {
        ru: 'Открыть в новой вкладке',
        ua: 'Відкрити в новій вкладці',
        en: 'Open in new tab',
        de: 'In neuem Tab öffnen',
        pl: 'Otwórz w nowej karcie',
        zh: '在新标签页中打开',
    },
    ctxRemove: {
        ru: 'Удалить',
        ua: 'Видалити',
        en: 'Remove',
        de: 'Entfernen',
        pl: 'Usuń',
        zh: '删除',
    },
};
